Repository cms-sw/cmssw, pull requests merged in 2018-10, with the labels that each got.

#24697 DQM/SiStripCommissioningClients: replace auto_ptr deprecated and removed in std=c++17
  DQM/SiStripCommissioningClients/interface/CommissioningHistograms.h
  DQM/SiStripCommissioningClients/interface/FedCablingHistograms.h
  DQM/SiStripCommissioningClients/interface/FedTimingHistograms.h
  DQM/SiStripCommissioningClients/src/ApvTimingHistograms.cc
  DQM/SiStripCommissioningClients/src/CalibrationHistograms.cc
  DQM/SiStripCommissioningClients/src/DaqScopeModeHistograms.cc
  DQM/SiStripCommissioningClients/src/FastFedCablingHistograms.cc
  DQM/SiStripCommissioningClients/src/NoiseHistograms.cc
  DQM/SiStripCommissioningClients/src/OptoScanHistograms.cc
  DQM/SiStripCommissioningClients/src/PedestalsHistograms.cc
  DQM/SiStripCommissioningClients/src/PedsFullNoiseHistograms.cc
  DQM/SiStripCommissioningClients/src/PedsOnlyHistograms.cc
  DQM/SiStripCommissioningClients/src/SamplingHistograms.cc
  DQM/SiStripCommissioningClients/src/VpspScanHistograms.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24702 DQMServices/FwkIO: replace auto_ptr removed in strict std=c++17
  DQMServices/FwkIO/plugins/DQMRootOutputModule.cc
  DQMServices/FwkIO/plugins/DQMRootSource.cc
  DQMServices/FwkIO/test/DummyFillDQMStore.cc
  DQMServices/FwkIO/test/DummyReadDQMStore.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24719 IORawData/CaloPatterns: replace auto_ptr removed in strict std=c++17
  IORawData/CaloPatterns/src/HcalPatternXMLParser.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24723 L1Trigger/GlobalTriggerAnalyzer: replace auto_ptr removed in strict std=c++17
  L1Trigger/GlobalTriggerAnalyzer/interface/L1GtPatternGenerator.h
  L1Trigger/GlobalTriggerAnalyzer/src/L1GtPatternGenerator.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24725 MuonAnalysis/MomentumScaleCalibration: replace auto_ptr removed in strict std=c++17
  MuonAnalysis/MomentumScaleCalibration/bin/ZntupleToTreeConverter.cc
  MuonAnalysis/MomentumScaleCalibration/plugins/DBReader.h
  MuonAnalysis/MomentumScaleCalibration/plugins/DBWriter.h
  MuonAnalysis/MomentumScaleCalibration/plugins/Histograms.h
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFit.cc
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFitFilter.cc
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFitUtils.cc
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFitUtils.h
  MuonAnalysis/MomentumScaleCalibration/plugins/TestCorrection.cc
  MuonAnalysis/MomentumScaleCalibration/plugins/TestCorrection.h
  MuonAnalysis/MomentumScaleCalibration/plugins/TestResolution.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#24727 PhysicsTools MVA*: replace functions and template remove in strict std=c++17.
  PhysicsTools/MVAComputer/bin/mvaConvertTMVAWeights.cpp
  PhysicsTools/MVAComputer/interface/MVAComputer.h
  PhysicsTools/MVAComputer/interface/MVAComputerCache.h
  PhysicsTools/MVAComputer/src/MVAComputer.cc
  PhysicsTools/MVAComputer/src/MVAComputerCache.cc
  PhysicsTools/MVAComputer/src/MVAComputerESSourceBase.cc
  PhysicsTools/MVAComputer/src/ProcLikelihood.cc
  PhysicsTools/MVATrainer/plugins/ProcMLP.cc
  PhysicsTools/MVATrainer/plugins/ProcTMVA.cc
  PhysicsTools/MVATrainer/src/ProcLikelihood.cc
  PhysicsTools/MVATrainer/src/TreeSaver.cc
  PhysicsTools/MVATrainer/src/TreeTrainer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#24741 RecoTauTag/RecoTau: replace functions and templates removed by stict std=c++17(where possible).
  RecoTauTag/RecoTau/interface/CombinatoricGenerator.h
  RecoTauTag/RecoTau/interface/RecoTauIsolationMasking.h
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByNProngs.cc
  RecoTauTag/RecoTau/plugins/PFTauPrimaryVertexProducer.cc
  RecoTauTag/RecoTau/plugins/RecoTauMVATransform.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroCombinatoricPlugin.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroProducer.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroStripPlugin.cc
  RecoTauTag/RecoTau/plugins/RecoTauProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24744 PhotonIDValueMapProducer use auto const ref to avoid unnecessary object copies
  RecoEgamma/PhotonIdentification/plugins/PhotonIDValueMapProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24745 RecoTracker/TkTrackingRegions: replace functions removed in strict std=c++17 with equivalent lambda
  RecoTracker/TkTrackingRegions/plugins/PixelInactiveAreaFinder.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24748 EventFilter/L1TRawToDigi: replace auto_ptr removed in strict implementation of std=c++17
  EventFilter/L1TRawToDigi/src/Block.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24747 RecoBTag/TrackProbability: replace bind1st removed from strict implementations of std=c++17 with equivalent lambda.
  RecoBTag/TrackProbability/src/HistogramProbabilityEstimator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24749 JetMETCorrections/FFTJetModules: replace auto_ptr removed in strict implementation of std=c++17
  JetMETCorrections/FFTJetModules/plugins/FFTJetCorrectorDBWriter.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#24751 Fix HiFJRhoProducer.cc for ConfDB (103X)
  RecoHI/HiJetAlgos/plugins/HiFJRhoProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24679 Porting new config file for HI and proton-proton to master branch
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24764 New pixel RecHit infrastructure for FastSim (for Phases 0, 1, 2, and beyond), backport of ##23799 for 94X
  FastSimulation/TrackingRecHitProducer/interface/PixelResolutionHistograms.h
  FastSimulation/TrackingRecHitProducer/interface/PixelTemplateSmearerBase.h
  FastSimulation/TrackingRecHitProducer/interface/TrackingRecHitAlgorithm.h
  FastSimulation/TrackingRecHitProducer/plugins/PixelBarrelTemplateSmearerPlugin.cc
  FastSimulation/TrackingRecHitProducer/plugins/PixelForwardTemplateSmearerPlugin.cc
  FastSimulation/TrackingRecHitProducer/plugins/PixelTemplateSmearerPlugin.cc
  FastSimulation/TrackingRecHitProducer/plugins/TrackingRecHitProducer.cc
  FastSimulation/TrackingRecHitProducer/python/PixelPluginsPhase0_cfi.py
  FastSimulation/TrackingRecHitProducer/python/PixelPluginsPhase1_cfi.py
  FastSimulation/TrackingRecHitProducer/python/PixelPluginsPhase2_cfi.py
  FastSimulation/TrackingRecHitProducer/python/TrackingRecHitProducer_cfi.py
  FastSimulation/TrackingRecHitProducer/src/PixelResolutionHistograms.cc
  FastSimulation/TrackingRecHitProducer/src/PixelTemplateSmearerBase.cc
  FastSimulation/TrackingRecHitProducer/src/TrackingRecHitAlgorithm.cc
Labels: comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#24651 VBFGenJetFilter has been modfied in order to select generator level Mjj
  GeneratorInterface/GenFilters/interface/VBFGenJetFilter.h
  GeneratorInterface/GenFilters/python/VBFGenJetFilter_cfi.py
  GeneratorInterface/GenFilters/src/VBFGenJetFilter.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24750 PhysicsTools/CondLiteIO: replace auto_ptr removed in strict implementation of std=c++17
  PhysicsTools/CondLiteIO/plugins/FWLiteESSource.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#24756 Eliminate an infinite loop from MVAVariableManager<T>::init()
  RecoEgamma/EgammaTools/interface/MVAVariableManager.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24769 Removed stub EGM regressor producers from production
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoEgamma/ElectronIdentification/plugins/ElectronRegressionValueMapProducer.cc
  RecoEgamma/ElectronIdentification/python/ElectronRegressionValueMapProducer_cfi.py
  RecoEgamma/ElectronIdentification/python/egmGsfElectronIDs_cff.py
  RecoEgamma/PhotonIdentification/plugins/PhotonRegressionValueMapProducer.cc
  RecoEgamma/PhotonIdentification/python/PhotonRegressionValueMapProducer_cfi.py
  RecoEgamma/PhotonIdentification/python/egmPhotonIDs_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#24726 OnlineDB/EcalCondDB: replace auto_ptr removed in strict std=c++17
  OnlineDB/EcalCondDB/bin/cmsecal_write_offline_det_id.cpp
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#24792 print date before executing gdb
  FWCore/Services/plugins/InitRootHandlers.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24718 GeneratorInterface/Pythia8Interface: replace auto_ptr removed in strict std=c++17
  GeneratorInterface/Pythia8Interface/interface/Py8InterfaceBase.h
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24717 GeneratorInterface/PartonShowerVeto: replace auto_ptr removed in strict std=c++17
  GeneratorInterface/PartonShowerVeto/interface/JetMatching.h
  GeneratorInterface/PartonShowerVeto/src/JetMatching.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24716 GeneratorInterface/LHEInterface: replace auto_ptr removed in strict std=c++17
  GeneratorInterface/LHEInterface/interface/LHEEvent.h
  GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc
  GeneratorInterface/LHEInterface/src/LHEEvent.cc
  GeneratorInterface/LHEInterface/src/LHEReader.cc
  GeneratorInterface/LHEInterface/src/LHERunInfo.cc
  GeneratorInterface/LHEInterface/src/XMLUtils.cc
  GeneratorInterface/LHEInterface/src/XMLUtils.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24715 GeneratorInterface/Herwig7Interface: replace auto_ptr removed in strict std=c++17
  GeneratorInterface/Core/interface/BaseHadronizer.h
  GeneratorInterface/Herwig7Interface/interface/Herwig7Interface.h
  GeneratorInterface/Herwig7Interface/src/Herwig7Interface.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24714 GeneratorInterface/Herwig6Interface: replace auto_ptr removed in strict std=c++17
  GeneratorInterface/Herwig6Interface/src/fastjetfortran_madfks.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24712 GeneratorInterface/Core: replace auto_ptr removed in strict std=c++17
  GeneratorInterface/Core/interface/BaseHadronizer.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-pending, tests-approved

#24713 GeneratorInterface/GenFilters: replace auto_ptr removed in strict std=c++17
  GeneratorInterface/GenFilters/interface/PythiaFilterGammaGamma.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24760 some quick damage control to uninitialized arrays and global statics in CastorDigiMonitor
  DQM/CastorMonitor/src/CastorDigiMonitor.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24621 Hi conformal pixel tracks qa
  DQM/TrackingMonitorSource/python/TrackCollections2monitor_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24777 enable PF HEM mitigation for HI 2018 and add Run2_2018_pp_on_AA_noHCALmitigation era
  Configuration/Eras/python/Era_Run2_2018_pp_on_AA_cff.py
  Configuration/Eras/python/Era_Run2_2018_pp_on_AA_noHCALmitigation_cff.py
  Configuration/StandardSequences/python/Eras.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#24655 Fixing RECO in pp_on_AA era jet reconstruction
  RecoHI/HiJetAlgos/python/HiRecoPFJets_cff.py
  RecoJets/Configuration/python/RecoPFJets_cff.py
  RecoJets/JetProducers/python/ak4PFJets_cfi.py
  RecoJets/JetProducers/python/ak8PFJets_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24775 [10.2.X]Change GT. Add ExtendedDetailedCavern Geom in 2018 MC
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24700 DQMOffline/RecoB: replace bind2nd with equivalent lambda
  DQMOffline/RecoB/src/MatchJet.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24790 call Fit with SERIAL option
  DQM/DTMonitorClient/src/DTResolutionAnalysisTest.cc
  DQMOffline/Muon/test/langauFit.C
  DQMOffline/PFTau/plugins/PFClient.cc
  DQMOffline/PFTau/plugins/PFClient_JetRes.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24797 Bug fixes for new PluginDescription code
  FWCore/Integration/test/PluginUsingProducer.cc
  FWCore/ParameterSet/interface/PluginDescription.h
Labels: bug-fix, code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24680 Rename MTDModuleNumbering plugin to avoid duplicates
  Geometry/MTDNumberingBuilder/test/MTDModuleNumbering.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#24689 CondTools/Hcal: replace auto_ptr deprecated and removed in std=c++17
  CondTools/Hcal/plugins/BufferedBoostIODBWriter.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#24691 CondTools/L1Trigger: replace auto_ptr deprecated and removed in std=c++17
  CondTools/L1Trigger/src/DataWriter.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#24692 CondTools/L1TriggerExt: replace auto_ptr deprecated and removed in std=c++17
  CondTools/L1TriggerExt/src/DataWriterExt.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#24693 CondTools/RPC: replace auto_ptr deprecated and removed in std=c++17
  CondTools/RPC/src/RPCDCCLinkMapHandler.cc
  CondTools/RPC/src/RPCLBLinkMapHandler.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#24695 DPGAnalysis/SiStripTools: replace bind2nd with equivalent lambda.
  DPGAnalysis/SiStripTools/plugins/TrackerDpgAnalysis.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#24770 Fix to Online Forward Pixel maps
  DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24798 Add missing seeding producer for FastSim
  FastSimulation/Tracking/python/SeedingMigration.py
Labels: comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#24804 Added a unique exception for missing secondary files
  FWCore/Utilities/interface/EDMException.h
  FWCore/Utilities/src/EDMException.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24782 [10.3]Change Gts. Fix geometry in LS2 GTs, and new HI 2018 MC GT
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24799 Remove workflow 136.7321
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#24659 Fix switch EMTF O2O Endcap to EndCap
  CondTools/L1TriggerExt/python/L1O2OTagsExt_cfi.py
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonEndCapObjectKeysOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonEndCapParamsOnlineProd.cc
  L1TriggerConfig/Utilities/test/dumpAll.py
  L1TriggerConfig/Utilities/test/dumpL1TMuonEndCapParams.py
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#24752 Pr103x L1T for HI - update centrality algo in CaloLayer2 demux
  L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_4_cfi.py
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2DemuxSumsAlgoFirmwareImp1.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24821 Added Mixing scenario for PU250 and PU300
  Configuration/StandardSequences/python/Mixing.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#24813 Workflow 511.1: herwig7+ MG5+Openloops pptoee at NLO QCD
  Configuration/Generator/python/Herwig7_Matchbox_madgraph_openloops_Herwig_ppToee_cff.py
  Configuration/PyReleaseValidation/python/relval_generator.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24816 update relval recycle strings of 10_3_0_pre5
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24678 add gen fragment for DarkSUSY MC relval production
  Configuration/Generator/python/DarkSUSY_mH_125_mN1_60_mGammaD_10_cT_10_Madgraph_LHE_13TeV_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24823 Settings for Herwig7 CH2 tune
  Configuration/Generator/python/Herwig7Settings/Herwig7CH2TuneSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7StableParticlesForDetector_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24773 Update several heavy ion wfs to 2018 pp_on_AA era
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24837 Pr103x L1T update centrality, saturation fixes, EG eta restriction, jetphi ring subtraction (rebased)
  L1Trigger/L1TCalorimeter/interface/CaloParamsHelper.h
  L1Trigger/L1TCalorimeter/interface/Stage2Layer2JetAlgorithmFirmware.h
  L1Trigger/L1TCalorimeter/plugins/L1TCaloParamsESProducer.cc
  L1Trigger/L1TCalorimeter/plugins/L1TCaloStage2ParamsESProducer.cc
  L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_4_cfi.py
  L1Trigger/L1TCalorimeter/python/convertParamsToOnlineFormat.py
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2DemuxSumsAlgoFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2EtSumAlgorithmFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2JetAlgorithmFirmwareImp1.cc
  L1TriggerConfig/L1TConfigProducers/src/CaloParamsHelperO2O.h
  L1TriggerConfig/L1TConfigProducers/src/L1TCaloParamsOnlineProd.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24811 [10.2.X] converting bare pointers to unique ptrs to fix mem leak
  Calibration/TkAlCaRecoProducers/plugins/CalibrationTrackSelectorFromDetIdList.cc
Labels: alca-approved, backport-ok, bug-fix, comparison-available, fully-signed, orp-approved, tests-approved

#24419 Extend the hit pattern class to include MTD hits
  DataFormats/TrackReco/interface/HitPattern.h
  DataFormats/TrackReco/src/HitPattern.cc
  DataFormats/TrackReco/src/classes_def.xml
  DataFormats/TrackReco/test/testHitPattern.cpp
  RecoMuon/L3MuonProducer/src/L3TkMuonProducer.cc
  RecoParticleFlow/PFSimProducer/plugins/EcalBarrelClusterFastTimer.cc
  RecoTracker/TkSeedGenerator/src/SeedFromProtoTrack.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#24422 Remove smartME1aME1b in ME1/1. Make ME1/1 upgrade TMB inherit from CSCUpgradeMotherboard
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.cc
  L1Trigger/CSCTriggerPrimitives/python/cscTriggerPrimitiveDigis_cfi.py
  L1Trigger/CSCTriggerPrimitives/src/CSCAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCAnodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.h
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME11.h
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME21.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME21.h
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.h
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME11.h
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME3141.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME3141.h
  L1Trigger/CSCTriggerPrimitives/src/CSCTriggerPrimitivesBuilder.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCTriggerPrimitivesBuilder.h
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboard.h
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboardLUT.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboardLUT.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24465 Extend TrackBase and Track to include time and velocity
  DataFormats/GsfTrackReco/src/classes_def.xml
  DataFormats/TrackReco/interface/Track.h
  DataFormats/TrackReco/interface/TrackBase.h
  DataFormats/TrackReco/src/Track.cc
  DataFormats/TrackReco/src/TrackBase.cc
  DataFormats/TrackReco/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24496 Prepare HcalTPGCoderULUT for concurrent IOVs
  CalibCalorimetry/HcalAlgos/interface/HcalPulseContainmentManager.h
  CalibCalorimetry/HcalAlgos/src/HcalPulseContainmentManager.cc
  CalibCalorimetry/HcalTPGAlgos/interface/HcaluLUTTPGCoder.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  CalibCalorimetry/HcalTPGEventSetup/src/HcalTPGCoderULUT.cc
  DataFormats/HcalRecHit/src/HFQIE10Info.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, reconstruction-approved, tests-approved

#24547 Tau offline DQM update
  Validation/RecoTau/interface/TauTagValidation.h
  Validation/RecoTau/python/DQMMCValidation_cfi.py
  Validation/RecoTau/python/DQMSequences_cfi.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnQCD_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnRealData_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnRealElectronsData_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnRealMuonsData_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZEEFastSim_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZEE_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZMM_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZTTFastSim_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZTT_cff.py
  Validation/RecoTau/src/TauTagValidation.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24658 Prepare RPCConeBuilder for concurrent IOVs
  L1Trigger/RPCTrigger/interface/RPCConeBuilder.h
  L1Trigger/RPCTrigger/plugins/RPCConeBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24690 Clean-up Geant4 interface
  SimG4Core/Application/interface/RunManagerMT.h
  SimG4Core/Application/src/OscarMTMasterThread.cc
  SimG4Core/Application/src/RunManagerMT.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#24841 Add more unit tests for PluginDescription
  FWCore/Integration/python/testProducerWithPsetDescEmpty_cfi.py
  FWCore/Integration/test/ProducerWithPSetDesc.cc
  FWCore/Integration/test/runAutoGeneratedCfi_cfg.py
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_briefdoc.txt
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_cfi.py
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_doc.txt
  FWCore/ParameterSet/interface/PluginDescription.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24829 fastsim 2017 PU and pmx wfs
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_premix.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24625 Validation/Geometry: No histos ROOT file being created by configuration scripts && CleanUp
  Validation/Geometry/interface/MaterialBudgetData.h
  Validation/Geometry/interface/MaterialBudgetEcalHistos.h
  Validation/Geometry/interface/MaterialBudgetFormat.h
  Validation/Geometry/interface/MaterialBudgetHGCalHistos.h
  Validation/Geometry/interface/MaterialBudgetHistos.h
  Validation/Geometry/interface/MaterialBudgetTrackerHistos.h
  Validation/Geometry/interface/MaterialBudgetTree.h
  Validation/Geometry/interface/MaterialBudgetTxt.h
  Validation/Geometry/interface/TestHistoMgr.h
  Validation/Geometry/src/MaterialBudgetAction.cc
  Validation/Geometry/src/MaterialBudgetCastorHistos.cc
  Validation/Geometry/src/MaterialBudgetCategorizer.cc
  Validation/Geometry/src/MaterialBudgetData.cc
  Validation/Geometry/src/MaterialBudgetEcalHistos.cc
  Validation/Geometry/src/MaterialBudgetHGCalHistos.cc
  Validation/Geometry/src/MaterialBudgetHistos.cc
  Validation/Geometry/src/MaterialBudgetTrackerHistos.cc
  Validation/Geometry/src/MaterialBudgetTree.cc
  Validation/Geometry/src/MaterialBudgetTxt.cc
  Validation/Geometry/src/TestHistoMgr.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#24746 Prepare for concurrent IOVs, MisalignedMuonESProducer
  Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorAsAnalyzer.cc
  Alignment/CommonAlignmentProducer/src/AlignmentProducerBase.cc
  Alignment/MuonAlignment/plugins/MisalignedMuonESProducer.cc
  Alignment/MuonAlignment/src/MuonAlignmentInputMethod.cc
  Alignment/MuonAlignment/src/MuonAlignmentOutputXML.cc
  Alignment/MuonAlignment/test/TestReader.cpp
  Geometry/CSCGeometryBuilder/plugins/CSCGeometryESModule.cc
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilder.cc
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilder.h
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilderFromDDD.cc
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilderFromDDD.h
  Geometry/DTGeometryBuilder/plugins/DTGeometryESModule.cc
  Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromDDD.cc
  Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromDDD.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#24754 made double em enrichment filter parameters tracked
  Configuration/Generator/python/doubleEMEnrichingHepMCfilter_cfi.py
  GeneratorInterface/Core/interface/PythiaHepMCFilterGammaGamma.h
  GeneratorInterface/Core/src/PythiaHepMCFilterGammaGamma.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24759 [10.3.X] CalibrationTrackSelectorFromDetIdList: clone hits only when building track
  Calibration/TkAlCaRecoProducers/plugins/CalibrationTrackSelectorFromDetIdList.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24766 EMTF new LCT coordinate conversion LUTs
  L1Trigger/L1TMuonEndCap/interface/SectorProcessorLUT.h
  L1Trigger/L1TMuonEndCap/python/simEmtfDigis_cfi.py
  L1Trigger/L1TMuonEndCap/src/ConditionHelper.cc
  L1Trigger/L1TMuonEndCap/src/SectorProcessorLUT.cc
  L1Trigger/L1TMuonEndCap/src/TrackFinder.cc
  L1Trigger/L1TMuonEndCap/test/tools/MakeCoordLUT.cc
  L1Trigger/L1TMuonEndCap/test/tools/README.md
  L1Trigger/L1TMuonEndCap/test/tools/make_coordlut_MC.py
  L1Trigger/L1TMuonEndCap/test/tools/make_coordlut_data.py
  L1Trigger/L1TMuonEndCap/test/tools/write_ph_lut_v2.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24761 Implementation of the option preexistingprimaryvertex
  Alignment/OfflineValidation/python/TkAlAllInOneTool/preexistingValidation.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexValidation.py
  Alignment/OfflineValidation/scripts/validateAlignments.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24603 Ecal Transparency corrections : use either a tag or a file for TPG
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
  CalibCalorimetry/EcalTPGTools/test/produceTPGParameters_beamv6_2021_235fb.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24805 Fixed interface to Geant4 for custom dark matter photon
  SimG4Core/CustomPhysics/src/CMSDarkPairProduction.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#24807 Phase2-hgx158 Correct density of PCB for v9 geometry
  Configuration/Geometry/python/dict2023Geometry.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D28XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D30XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D31XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D32XML_cfi.py
  Geometry/HGCalCommonData/data/hgcal/v9/hgcal.xml
  Geometry/HGCalCommonData/data/hgcal/v9a/hgcal.xml
  Geometry/HGCalCommonData/data/hgcal/v9p/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalEE/v9/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalEE/v9/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalEE/v9a/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v9/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v9/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v9a/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v9/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v9/hgcalHEsil.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v9a/hgcalHEsil.xml
  Geometry/HGCalCommonData/data/hgcalMaterial/v1/hgcalMaterial.xml
  Geometry/HGCalCommonData/python/testHGCV8XML_cfi.py
  Geometry/HGCalCommonData/python/testHGCV9XML_cfi.py
  Geometry/HGCalCommonData/python/testHGCXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalEEXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalHEmixXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalHEsilXML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#24796 Phase2-hgx157 Update the standalone digi study of HGCal (upgrade) to give reasonable o/p
  Validation/HGCalValidation/python/hgcDigiStudy_cfi.py
  Validation/HGCalValidation/test/HGCalDigiStudy.cc
  Validation/HGCalValidation/test/runHGCalDigiStudy_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24815 Phase2-159 Update the xml files for HFNose to make it working again
  Geometry/ForwardCommonData/data/hfnose/v0/hfnose.xml
  Geometry/ForwardCommonData/data/hfnose/v1/hfnose.xml
  SimG4CMS/Calo/test/python/runHFNose_cfg.py
  Validation/HGCalValidation/python/hfnoseSimHitStudy_cfi.py
  Validation/HGCalValidation/test/HGCalSimHitStudy.cc
  Validation/HGCalValidation/test/runHFNoseSimHitStudy_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#24509 Start conversion to using user-defined literals for Geometry
  DetectorDescription/Core/interface/DDTypes.h
  DetectorDescription/Core/src/DDTypes.cc
  Geometry/MuonCommonData/plugins/DDGEMAngular.cc
  Geometry/MuonCommonData/plugins/DDMuonAngular.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#24833 Fix Relval steps for GEN workflow 535
  Configuration/Generator/python/TT_13TeV_Pow_Herwig7_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24711 FastSimulation/ParticleDecay: replace auto_ptr removed in strict std=c++17
  FastSimulation/ParticleDecay/interface/PythiaDecays.h
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#24789 Replaced BOOST_FOREACH in RecoTauTag_RecoTau
  RecoTauTag/RecoTau/interface/RecoTauCrossCleaning.h
  RecoTauTag/RecoTau/interface/RecoTauQualityCuts.h
  RecoTauTag/RecoTau/plugins/PFRecoTauChargedHadronProducer.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByHPSSelection.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByInvMass.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByNProngs.cc
  RecoTauTag/RecoTau/plugins/PFTauPrimaryVertexProducer.cc
  RecoTauTag/RecoTau/plugins/PFTauViewRefMerger.cc
  RecoTauTag/RecoTau/plugins/RecoTauBuilderCombinatoricPlugin.cc
  RecoTauTag/RecoTau/plugins/RecoTauBuilderConePlugin.cc
  RecoTauTag/RecoTau/plugins/RecoTauDecayModeCutMultiplexer.cc
  RecoTauTag/RecoTau/plugins/RecoTauDiscriminantFromDiscriminator.cc
  RecoTauTag/RecoTau/plugins/RecoTauDiscriminantInvariantWidth.cc
  RecoTauTag/RecoTau/plugins/RecoTauDiscriminationByFlight.cc
  RecoTauTag/RecoTau/plugins/RecoTauIsolationDiscriminantPlugins.cc
  RecoTauTag/RecoTau/plugins/RecoTauMVATransform.cc
  RecoTauTag/RecoTau/plugins/RecoTauPhotonFilter.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroProducer.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroStripPlugin.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroStripPlugin2.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroTrivialPlugin.cc
  RecoTauTag/RecoTau/plugins/RecoTauProducer.cc
  RecoTauTag/RecoTau/src/RecoTauBinnedIsolationPlugin.cc
  RecoTauTag/RecoTau/src/RecoTauConstructor.cc
  RecoTauTag/RecoTau/src/RecoTauDiscriminantFunctions.cc
  RecoTauTag/RecoTau/src/RecoTauIsolationMasking.cc
  RecoTauTag/RecoTau/src/RecoTauQualityCuts.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24808 Added mixing scenario for PU250 PU300 in Configuration/StandardSequences/python/Mixing.py
  Configuration/StandardSequences/python/Mixing.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#24774 Replaced BOOST_STATIC_ASSERT with static_assert keyword
  CommonTools/UtilAlgos/interface/SelectionAdderTrait.h
  CommonTools/UtilAlgos/interface/StoreManagerTrait.h
  CondFormats/Serialization/interface/eos/portable_iarchive.hpp
  CondFormats/Serialization/interface/eos/portable_oarchive.hpp
  DataFormats/BTauReco/interface/TaggingVariable.h
  PhysicsTools/UtilAlgos/interface/SelectionAdderTrait.h
  PhysicsTools/Utilities/interface/Fraction.h
  PhysicsTools/Utilities/interface/RooFitFunction.h
  PhysicsTools/Utilities/interface/Sum.h
  PhysicsTools/Utilities/test/testSimplifications.cc
  RecoBTau/JetTagComputer/interface/JetTagComputerESProducer.h
  RecoTauTag/RecoTau/interface/RecoTauCommonUtilities.h
Labels: analysis-pending, code-checks-approved, comparison-available, db-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#24620 Factorize PythonParameterSet code from other fwk to reduce dependencies
  CondFormats/CSCObjects/test/BuildFile.xml
  CondFormats/CSCObjects/test/testCSCMapping.cpp
  CondFormats/CSCObjects/test/testCSCTriggerMapping.cpp
  EventFilter/CSCTFRawToDigi/test/BuildFile.xml
  EventFilter/CSCTFRawToDigi/test/testCSCTFRawToDigi.cpp
  FWCore/Framework/BuildFile.xml
  FWCore/Framework/bin/BuildFile.xml
  FWCore/Framework/bin/cmsRun.cpp
  FWCore/Framework/interface/EventProcessor.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/test/BuildFile.xml
  FWCore/Framework/test/eventprocessor2_t.cppunit.cc
  FWCore/Framework/test/eventprocessor_t.cppunit.cc
  FWCore/Framework/test/productregistry.cppunit.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/standalone_t.cppunit.cc
  FWCore/ParameterSet/interface/ProcessDesc.h
  FWCore/ParameterSet/src/ProcessDesc.cc
  FWCore/ParameterSetReader/BuildFile.xml
  FWCore/ParameterSetReader/interface/ParameterSetReader.h
  FWCore/ParameterSetReader/interface/ProcessDescImpl.h
  FWCore/ParameterSetReader/src/ParameterSetReader.cc
  FWCore/PythonParameterSet/bin/edmConfigHash.cpp
  FWCore/PythonParameterSet/bin/edmParameterSetDump.cpp
  FWCore/PythonParameterSet/interface/MakeParameterSets.h
  FWCore/PythonParameterSet/interface/PythonProcessDesc.h
  FWCore/PythonParameterSet/src/MakeParameterSets.cc
  FWCore/PythonParameterSet/src/PythonProcessDesc.cc
  FWCore/PythonParameterSet/test/readpsetsfrom_t.cppunit.cc
  FWCore/ServiceRegistry/BuildFile.xml
  FWCore/ServiceRegistry/src/ServiceRegistry.cc
  FWCore/TestProcessor/src/TestProcessor.cc
  FWCore/TestProcessor/test/testprocessor_t.cppunit.cc
  Fireworks/FWInterface/src/FWPSetTableManager.cc
  Fireworks/FWInterface/src/FWPathsPopup.cc
  PhysicsTools/FWLite/bin/BuildFile.xml
  PhysicsTools/FWLite/bin/FWLiteWithPythonConfig.cc
  PhysicsTools/FWLite/bin/FWLiteWithSelectorUtils.cc
  PhysicsTools/PatExamples/bin/BuildFile.xml
  PhysicsTools/PatExamples/bin/PatAnalysisTasksExercise.cc
  PhysicsTools/PatExamples/bin/PatBasicFWLiteAnalyzer.cc
  PhysicsTools/PatExamples/bin/PatBasicFWLiteJetAnalyzer.cc
  PhysicsTools/PatExamples/bin/PatBasicFWLiteJetAnalyzer_Selector.cc
  PhysicsTools/PatExamples/bin/PatCleaningExercise.cc
  PhysicsTools/PatExamples/bin/PatMuonFWLiteAnalyzer.cc
  PhysicsTools/SelectorUtils/bin/BuildFile.xml
  PhysicsTools/SelectorUtils/bin/calculateIdMD5.cc
  PhysicsTools/SelectorUtils/bin/testSelection_wplusjets.C
  PhysicsTools/SelectorUtils/interface/MakePyVIDClassBuilder.h
  PhysicsTools/UtilAlgos/bin/FWLiteWithBasicAnalyzer.cc
  PhysicsTools/UtilAlgos/interface/FWLiteAnalyzerWrapper.h
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, core-approved, db-pending, l1-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved, visualization-approved

#24800 Update anti-e tau discriminant
  RecoTauTag/RecoTau/interface/AntiElectronIDMVA6.h
  RecoTauTag/RecoTau/plugins/PATTauDiscriminationAgainstElectronMVA6.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationAgainstElectronMVA6.cc
  RecoTauTag/RecoTau/python/PATTauDiscriminationAgainstElectronMVA6_cfi.py
  RecoTauTag/RecoTau/src/AntiElectronIDMVA6.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24812 SiStrip unpacker: update packet code check in cmMedian (for nonstandard ZS modes)
  EventFilter/SiStripRawToDigi/src/SiStripFEDBufferComponents.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24858 Prepare for concurrent IOVs in FWCore
  FWCore/Integration/test/ESTestProducers.cc
  FWCore/Skeletons/scripts/mkTemplates/ESProducer/ESProducer.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24861 New fastsim geometry fix, AddOn faliure fix - backport to 94X
  FastSimulation/SimplifiedGeometryPropagator/interface/StraightTrajectory.h
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
  FastSimulation/SimplifiedGeometryPropagator/src/HelixTrajectory.cc
  FastSimulation/SimplifiedGeometryPropagator/src/ParticleManager.cc
Labels: comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#24809 updated relval gridpacks for gcc630
  Configuration/Generator/python/sherpa_ZtoEE_0j_BlackHat_13TeV_MASTER_cff.py
  Configuration/Generator/python/sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER_cff.py
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#24846 Avoid unneccessary copies in RecoParticleFlow__PFProducer with emplace
  RecoParticleFlow/PFProducer/src/PFAlgo.cc
  RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc
  RecoParticleFlow/PFProducer/src/PFElectronAlgo.cc
  RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc
  RecoParticleFlow/PFProducer/src/PFPhotonAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24835 HI Plots for the CaloLayer2 DQM
  DQM/L1TMonitor/interface/L1TStage2CaloLayer2.h
  DQM/L1TMonitor/interface/L1TdeStage2CaloLayer2.h
  DQM/L1TMonitor/src/L1TStage2CaloLayer2.cc
  DQM/L1TMonitor/src/L1TdeStage2CaloLayer2.cc
  DQM/L1TMonitorClient/src/L1TStage2CaloLayer2DEClientSummary.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24853 BMTFTriggerAlgoSelector InputTag change for HeavyIons
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24803 Revert back from oversight about rawDataRepacker and rawDataCollector for the BeamPixel DQM application
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24503 Move from tinyxml to tinyxml2 in FWCore-MessageLogger
  FWCore/MessageLogger/BuildFile.xml
  FWCore/MessageLogger/src/JobReport.cc
  GeneratorInterface/RivetInterface/BuildFile.xml
  GeneratorInterface/RivetInterface/plugins/BuildFile.xml
  GeneratorInterface/RivetInterface/plugins/RivetHarvesting.cc
  IOPool/Common/test/proper_fjr_output
  IOPool/Common/test/proper_fjrx_output
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, generators-approved, orp-approved, tests-approved

#24867 HI O2O update: add new parameters and tidy up
  L1Trigger/L1TCalorimeter/python/convertParamsToOnlineFormat.py
  L1TriggerConfig/L1TConfigProducers/src/CaloParamsHelperO2O.h
  L1TriggerConfig/L1TConfigProducers/src/L1TCaloParamsOnlineProd.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24832 Added the capability to switch the mode of charge asymmetry evaluation
  RecoLocalCalo/HcalRecAlgos/interface/HFSimpleTimeCheck.h
  RecoLocalCalo/HcalRecAlgos/src/HFFlexibleTimeCheck.cc
  RecoLocalCalo/HcalRecAlgos/src/HFSimpleTimeCheck.cc
  RecoLocalCalo/HcalRecAlgos/src/parseHFPhase1AlgoDescription.cc
  RecoLocalCalo/HcalRecProducers/python/HFPhase1Reconstructor_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24802 Revert back from oversight about rawDataRepacker and rawDataCollector for the BeamPixel DQM application
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24859 disabling pixel resolution histogram load messages
  FastSimulation/TrackingRecHitProducer/src/PixelResolutionHistograms.cc
Labels: backport, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#24838 Time for layerClusters in HGCAL
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalLayerClusterProducer.cc
  RecoLocalCalo/HGCalRecProducers/python/hgcalLayerClusters_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#24877 disabling pixel histogram load messages - rebase to master
  FastSimulation/TrackingRecHitProducer/src/PixelResolutionHistograms.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#24590 [10_2_X] Add protection for disabled FEDs in the SiStrip packer
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRaw.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRaw.h
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRawModule.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRawModule.h
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.h
  EventFilter/SiStripRawToDigi/plugins/WarningSummary.cc
  EventFilter/SiStripRawToDigi/plugins/WarningSummary.h
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24840 Add settings for Herwig7 CH2 tune, and for setting stable particles.
  Configuration/Generator/python/Herwig7Settings/Herwig7CH2TuneSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7StableParticlesForDetector_cfi.py
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24607 HCALDQM: Add FCDTask for FCD demonstrator (10_2_X)
  DQM/HcalTasks/interface/FCDTask.h
  DQM/HcalTasks/plugins/FCDTask.cc
  DQM/HcalTasks/python/FCDTask.py
  DQM/Integration/python/clients/hcal_dqm_sourceclient-live_cfg.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24683 Totem Timing detectors: updated mapping for future rereco of dedicated run data
  CondFormats/CTPPSReadoutObjects/xml/mapping_totem_timing_2018.xml
  EventFilter/CTPPSRawToDigi/src/RawToDigiConverter.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24870 OfflineDQM: Offline L1T muon DQM bugfix for muon resolution plots CMSLITDPG-763
  DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#24613 RPC Digi Collection Merger
  Configuration/StandardSequences/python/RawToDigi_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py
  EventFilter/RPCRawToDigi/plugins/RPCDigiMerger.cc
  EventFilter/RPCRawToDigi/plugins/RPCDigiMerger.h
  EventFilter/RPCRawToDigi/plugins/RPCTwinMuxRawToDigi.cc
  EventFilter/RPCRawToDigi/python/RPCDigiMerger_cff.py
  EventFilter/RPCRawToDigi/python/RPCTwinMuxRawToDigi_cff.py
  EventFilter/RPCRawToDigi/python/RPCTwinMuxRawToDigi_sqlite_cff.py
  EventFilter/RPCRawToDigi/test/testRPCDigiMerger_cfg.py
  EventFilter/RPCRawToDigi/test/testRPCNewReadoutMergerWithDQM.py
  L1Trigger/Configuration/python/L1TRawToDigi_cff.py
  RecoLocalMuon/Configuration/python/RecoLocalMuonCosmics_cff.py
  RecoLocalMuon/Configuration/python/RecoLocalMuon_cff.py
  RecoLocalMuon/RPCRecHit/python/rpcRecHits_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, operations-approved, orp-approved, reconstruction-approved, tests-approved

#24879 Backport to 94X: add fast sim2017 PU and pmx wfs
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_premix.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24757 HCALDQM: bad capid/LED misfire sound alarms only for last 60 LSes (10_3_X)
  DQM/HcalTasks/data/HcalQualityTests.xml
  DQM/HcalTasks/interface/DigiTask.h
  DQM/HcalTasks/plugins/DigiTask.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24828 Backport of POWHEG EmissionVeto1 updates
  GeneratorInterface/Pythia8Interface/doc/README_EmissionVeto1
  GeneratorInterface/Pythia8Interface/plugins/EmissionVetoHook1.cc
  GeneratorInterface/Pythia8Interface/plugins/EmissionVetoHook1.h
  GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.cc
  GeneratorInterface/Pythia8Interface/plugins/PowhegHooksBB4L.h
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/src/Py8InterfaceBase.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24694 CondFormats/HcalObjects: replace auto_ptr deprecated and removed in std=c++17
  CondFormats/HcalObjects/interface/StorableDoubleMap.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#24819 Raw data remapper
  EventFilter/RawDataCollector/src/RawDataCollectorByLabel.cc
  EventFilter/RawDataCollector/src/RawDataMapperByLabel.cc
  EventFilter/RawDataCollector/src/SealModule.cc
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, tests-approved

#24875 HI O2O update: add new parameters and tidy up **103X BACKPORT**
  L1Trigger/L1TCalorimeter/python/convertParamsToOnlineFormat.py
  L1TriggerConfig/L1TConfigProducers/src/CaloParamsHelperO2O.h
  L1TriggerConfig/L1TConfigProducers/src/L1TCaloParamsOnlineProd.cc
Labels: backport-ok, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24857 [10_3_X] Implement second HF min-bias feature bit
  CalibCalorimetry/HcalTPGAlgos/interface/HcaluLUTTPGCoder.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  CalibCalorimetry/HcalTPGEventSetup/src/HcalTPGCoderULUT.cc
  CaloOnlineTools/HcalOnlineDb/test/template.py
  SimCalorimetry/HcalTrigPrimAlgos/interface/HcalTriggerPrimitiveAlgo.h
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalTriggerPrimitiveAlgo.cc
  SimCalorimetry/HcalTrigPrimProducers/python/hcaltpdigi_cff.py
  SimCalorimetry/HcalTrigPrimProducers/python/hcaltpdigi_cfi.py
  SimCalorimetry/HcalTrigPrimProducers/src/HcalTrigPrimDigiProducer.cc
Labels: alca-approved, backport-ok, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#24891 Raw data remapper
  EventFilter/RawDataCollector/src/RawDataCollectorByLabel.cc
  EventFilter/RawDataCollector/src/RawDataMapperByLabel.cc
  EventFilter/RawDataCollector/src/SealModule.cc
Labels: backport-ok, comparison-available, daq-approved, fully-signed, orp-approved, tests-approved

#24810 deleting RivetHarvesting
  GeneratorInterface/RivetInterface/interface/RivetHarvesting.h
  GeneratorInterface/RivetInterface/plugins/RivetHarvesting.cc
  GeneratorInterface/RivetInterface/python/rivetHarvesting_cfi.py
  GeneratorInterface/RivetInterface/test/runRivetHarvesting_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24904 make use of new iftool scram tag to conditionaly build/run tests
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/imports.txt
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, requires-external, tests-approved

#24896 Remove obsolete cout in CSCGEMMotherboard
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24849 Prepare for concurrent IOVs
  CondFormats/CTPPSReadoutObjects/plugins/TotemDAQMappingESSourceXML.cc
  CondTools/L1TriggerExt/interface/L1ObjectKeysOnlineProdBaseExt.h
  CondTools/L1TriggerExt/plugins/L1SubsystemKeysOnlineProdExt.cc
  CondTools/L1TriggerExt/plugins/L1SubsystemKeysOnlineProdExt.h
  CondTools/L1TriggerExt/plugins/L1TriggerKeyDummyProdExt.cc
  CondTools/L1TriggerExt/plugins/L1TriggerKeyDummyProdExt.h
  CondTools/L1TriggerExt/plugins/L1TriggerKeyListDummyProdExt.cc
  CondTools/L1TriggerExt/plugins/L1TriggerKeyListDummyProdExt.h
  CondTools/L1TriggerExt/plugins/L1TriggerKeyOnlineProdExt.cc
  CondTools/L1TriggerExt/plugins/L1TriggerKeyOnlineProdExt.h
  CondTools/L1TriggerExt/src/L1ObjectKeysOnlineProdBaseExt.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TCaloParamsObjectKeysOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TGlobalPrescalesVetosObjectKeysOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonBarrelObjectKeysOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonEndCapObjectKeysOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonGlobalObjectKeysOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonOverlapObjectKeysOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TUtmTriggerMenuObjectKeysOnlineProd.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#24851 Regional strip unpacker: support for legacy modes and bugfix for virgin raw
  RecoLocalTracker/SiStripClusterizer/plugins/ClustersFromRawProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#24910 Raw data remapper sequence
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/RawToDigi_DataMapper_cff.py
  EventFilter/RawDataCollector/src/RawDataMapperByLabel.cc
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24883 Calo Layer 2 saturation fixes
  EventFilter/L1TRawToDigi/utils/unpackBuffers-CaloStage2.py
  L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_4_cfi.py
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2DemuxJetAlgoFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2DemuxSumsAlgoFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2JetAlgorithmFirmwareImp1.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24885 Calo Layer 2 saturation fixes **10_3_X BACKPORT**
  EventFilter/L1TRawToDigi/utils/unpackBuffers-CaloStage2.py
  L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_4_cfi.py
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2DemuxJetAlgoFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2DemuxSumsAlgoFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2JetAlgorithmFirmwareImp1.cc
Labels: backport, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24921 Raw data mapper sequence backport
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/RawToDigi_DataMapper_cff.py
  EventFilter/RawDataCollector/src/RawDataMapperByLabel.cc
Labels: backport, comparison-available, daq-pending, operations-approved, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#24911 Prepare for concurrent IOVs, Fireworks & FastSimulation
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimGeometryESProducer.cc
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimGeometryESProducer.h
  Fireworks/Geometry/interface/FWRecoGeometryESProducer.h
  Fireworks/Geometry/interface/FWTGeoRecoGeometryESProducer.h
  Fireworks/Geometry/interface/TGeoMgrFromDdd.h
  Fireworks/Geometry/src/FWRecoGeometryESProducer.cc
  Fireworks/Geometry/src/FWTGeoRecoGeometryESProducer.cc
  Fireworks/Geometry/src/TGeoMgrFromDdd.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved, visualization-approved

#24884 Changing default values of CaloLayer2 Agreement plots
  DQM/L1TMonitorClient/src/L1TStage2CaloLayer2DEClientSummary.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24916 [10.4.X][Change GT] Update HI MC ECAL GT + 2019 GT Geom. fix
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24878 Ecal Bad calib filter adding a new problematic crystal
  RecoMET/METFilters/python/ecalBadCalibFilter_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#24949 add test for import pydablooms
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
Labels: analysis-pending, code-checks-approved, comparison-available, orp-pending, pending-signatures, requires-external, tests-approved

#24946 Update Utilities/StaticAnalyzers to use dablooms library added in CMSDIST PR 4436
  Utilities/StaticAnalyzers/BuildFile.xml
  Utilities/StaticAnalyzers/src/dablooms.c
  Utilities/StaticAnalyzers/src/dablooms.h
  Utilities/StaticAnalyzers/src/murmur.c
  Utilities/StaticAnalyzers/src/murmur.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, requires-external, tests-approved

#24814 bug fix in the linearizer ...
  SimCalorimetry/EcalEBTrigPrimAlgos/src/EcalFenixLinearizer.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#24863 PFEGammaProducer with fillDescriptions
  RecoParticleFlow/PFProducer/interface/PFEGammaAlgo.h
  RecoParticleFlow/PFProducer/plugins/PFEGammaProducer.cc
  RecoParticleFlow/PFProducer/plugins/PFEGammaProducer.h
  RecoParticleFlow/PFProducer/python/particleFlowEGamma_cfi.py
  RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24892 Centrality reco modification for 2018 heavy ion run
  DataFormats/HeavyIonEvent/interface/Centrality.h
  DataFormats/HeavyIonEvent/src/Centrality.cc
  DataFormats/HeavyIonEvent/src/classes_def.xml
  RecoHI/HiCentralityAlgos/plugins/CentralityProducer.cc
  RecoHI/HiCentralityAlgos/python/HiCentrality_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24953 Prepare for concurrent IOVs, miscellaneous packages
  JetMETCorrections/Modules/interface/JetCorrectionESSource.h
  PhysicsTools/MVAComputer/interface/MVAComputerESSourceBase.h
  PhysicsTools/MVAComputer/src/MVAComputerESSourceBase.cc
  RecoLocalCalo/EcalRecProducers/test/stubs/EcalSampleMaskRecordESProducer.cc
  RecoMTD/DetLayers/plugins/MTDDetLayerGeometryESProducer.cc
  RecoMTD/DetLayers/plugins/MTDDetLayerGeometryESProducer.h
  TrackingTools/GsfTools/plugins/CloseComponentsMergerESProducer.h
  TrackingTools/GsfTools/plugins/CloseComponentsMergerESProducer.icc
  TrackingTools/GsfTools/plugins/DistanceBetweenComponentsESProducer.h
  TrackingTools/GsfTools/plugins/DistanceBetweenComponentsESProducer.icc
  TrackingTools/TrackFitters/plugins/FlexibleKFFittingSmootherESProducer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, upgrade-approved

#24937 [10_4_X] Fixed copy-paste typo in Spring15 photon MVA weight file names
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_25ns_nonTrig_V0_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_25ns_nonTrig_V2_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_25ns_nonTrig_V2p1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_50ns_nonTrig_V0_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_50ns_nonTrig_V1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_50ns_nonTrig_V2_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_50ns_nonTrig_V2p1_cff.py
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24943 Fix numerical bug that causes NaNs in DeepCSV output
  RecoBTag/SecondaryVertex/interface/CombinedSVComputer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24944 online DQM GT update
  DQM/Integration/python/config/FrontierCondition_GT_autoExpress_cfi.py
  DQM/Integration/python/config/FrontierCondition_GT_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24901 pat::Muon member function declaration bug fix
  DataFormats/PatCandidates/interface/Muon.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#24964 Utilities/StaticAnalyzer: include dablooms library header as extern "C"
  Utilities/StaticAnalyzers/src/CmsSupport.cpp
  Utilities/StaticAnalyzers/src/ConstCastAwayChecker.h
  Utilities/StaticAnalyzers/src/ConstCastChecker.h
  Utilities/StaticAnalyzers/src/FiniteMathChecker.h
  Utilities/StaticAnalyzers/src/FunctionChecker.cpp
  Utilities/StaticAnalyzers/src/FunctionDumper.cpp
  Utilities/StaticAnalyzers/src/GlobalStaticChecker.h
  Utilities/StaticAnalyzers/src/MutableMemberChecker.h
  Utilities/StaticAnalyzers/src/StaticLocalChecker.h
  Utilities/StaticAnalyzers/src/ThrUnsafeFCallChecker.cpp
  Utilities/StaticAnalyzers/src/TrunCastChecker.h
  Utilities/StaticAnalyzers/src/getByChecker.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24895 DQM/Event Display: update scenario for HI [10_3_X]
  DQM/Integration/python/clients/visualization-live-secondInstance_cfg.py
  DQM/Integration/python/clients/visualization-live_cfg.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24908 Remove cscTriggerPrimitiveDigis to prevent online client from crashing. Backport of PR24905
  DQM/Integration/python/clients/csc_dqm_sourceclient-live_cfg.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24938 Skip tests if no CUDA devices are present
  DataFormats/Math/test/cudaAtan2Test.cu
  DataFormats/Math/test/cudaMathTest.cu
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24909 Changing default values of Calo Layer 2 DQM D/E Agreement plots (L1TEMU)
  DQM/L1TMonitorClient/src/L1TStage2CaloLayer2DEClientSummary.cc
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24945 online DQM GT update (backport)
  DQM/Integration/python/config/FrontierCondition_GT_autoExpress_cfi.py
  DQM/Integration/python/config/FrontierCondition_GT_cfi.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24852 [10_3_X] Regional strip unpacker: support for legacy modes and bugfix for virgin raw
  RecoLocalTracker/SiStripClusterizer/plugins/ClustersFromRawProducer.cc
Labels: backport-ok, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#24906 Implemented option to run jobs in parallel for PV validation
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexValidation.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24876 MET EE noise mitigation in 2017 data
  JetMETCorrections/Type1MET/plugins/BadPFCandidateJetsEEnoiseProducer.cc
  JetMETCorrections/Type1MET/plugins/UnclusteredBlobProducer.cc
  JetMETCorrections/Type1MET/python/cleanJetFromEEnoise_cfi.py
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#24929 Move HGCal and MTD event content customizations to SimCalorimetry and SimFastTiming
  Configuration/EventContent/python/EventContent_cff.py
  SimCalorimetry/Configuration/python/SimCalorimetry_EventContent_cff.py
  SimFastTiming/Configuration/python/SimFastTiming_EventContent_cff.py
  SimGeneral/Configuration/python/SimGeneral_EventContent_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#24955 SiStripMonitorClient: Fix caching logic in SiStripBadComponentInfo
  DQM/SiStripMonitorClient/plugins/SiStripBadComponentInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripBadComponentInfo.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24556 Complete HE depth feature bit implementation
  CalibCalorimetry/HcalTPGAlgos/src/LutXml.cc
  CaloOnlineTools/HcalOnlineDb/BuildFile.xml
  CaloOnlineTools/HcalOnlineDb/bin/hcalLUT.cc
  CaloOnlineTools/HcalOnlineDb/interface/HcalLutManager.h
  CaloOnlineTools/HcalOnlineDb/src/HcalLutManager.cc
  CaloOnlineTools/HcalOnlineDb/test/template.py
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalFinegrainBit.cc
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalTriggerPrimitiveAlgo.cc
Labels: alca-pending, code-checks-approved, comparison-available, db-approved, l1-approved, orp-approved, pending-signatures, tests-approved

#24963 Trivial bug fixes to record EcalSampleMask
  CondFormats/EcalObjects/interface/EcalSampleMask.h
  CondFormats/EcalObjects/src/EcalSampleMask.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved
