Repository cms-sw/cmssw, pull requests merged in 2018-09, with the labels that each got.

#24423 Fix MultiToken.h with missing header include
  RecoEgamma/EgammaTools/interface/MultiToken.h
  RecoEgamma/EgammaTools/interface/Utils.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24413 modify electron track seeding regions for pp_on_AA era
  RecoTracker/IterativeTracking/python/ElectronSeeds_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24418 temporarily disable trigger for hgcal V9 (again)
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#24441 DD Unlock Stores
  DetectorDescription/Core/src/DDCompactView.cc
Labels: code-checks-approved, comparison-available, geometry-pending, orp-approved, pending-signatures, tests-approved

#24403 New CSCBaseboard class and helper function in CSCDetId
  DataFormats/MuonDetId/interface/CSCDetId.h
  DataFormats/MuonDetId/src/CSCDetId.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCBaseboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCBaseboard.h
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved

#24435 Fix CkfTrackCandidates_cfi.py (10_3)
  RecoTracker/CkfPattern/python/CkfTrackCandidates_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24366 TkAl validation - automatically read APEs from the MillePede output if present
  Alignment/OfflineValidation/python/TkAlAllInOneTool/alignment.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24380 2018_pp_on_AA era HI jet sequences
  RecoHI/HiJetAlgos/python/HiRecoPFJets_cff.py
  RecoHI/HiJetAlgos/python/hiFJGridEmptyAreaCalculator_cff.py
  RecoHI/HiJetAlgos/python/hiFJRhoProducer.py
  RecoJets/Configuration/python/RecoJetsGlobal_cff.py
  RecoJets/Configuration/python/RecoJets_EventContent_cff.py
  RecoJets/Configuration/python/RecoJets_cff.py
  RecoJets/Configuration/python/RecoPFJets_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24383 [10.3.X] Introduce a special AlCaReco for Strip Small Bias Scans
  Calibration/TkAlCaRecoProducers/plugins/BuildFile.xml
  Calibration/TkAlCaRecoProducers/plugins/CalibrationTrackSelectorFromDetIdList.cc
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalSmallBiasScan_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalSmallBiasScan_cff.py
  Calibration/TkAlCaRecoProducers/python/CalibrationTrackSelectorFromDetIdList_cfi.py
  Configuration/AlCa/python/autoCond.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24453 Backport of #24379 to 10_2_X, missing EGM ID modules for DQM
  DQMOffline/Trigger/python/HLTEGTnPMonitor_cfi.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24468 data processing scenarios for T0 for heavy ions data taking in 2018
  Configuration/DataProcessing/python/Impl/HeavyIonsEra_Run2_2018.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2018_pp_on_AA.py
  Configuration/DataProcessing/python/RecoTLR.py
  Configuration/DataProcessing/test/run_CfgTest.sh
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#24174 Tune dependent reweighting
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/plugins/ReweightUserHooks.h
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24427 Use new C++ abilities in FWCore/SOA
  FWCore/SOA/interface/Column.h
  FWCore/SOA/interface/ColumnFillers.h
  FWCore/SOA/interface/Table.h
  FWCore/SOA/interface/TableView.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24429 Explicitly allow ParameterSet and its internals to be moveable
  FWCore/ParameterSet/interface/Entry.h
  FWCore/ParameterSet/interface/ParameterSet.h
  FWCore/ParameterSet/interface/ParameterSetEntry.h
  FWCore/ParameterSet/interface/VParameterSetEntry.h
  FWCore/ParameterSet/src/Entry.cc
  FWCore/ParameterSet/src/ParameterSet.cc
  FWCore/ParameterSet/src/ParameterSetEntry.cc
  FWCore/ParameterSet/src/VParameterSetEntry.cc
  FWCore/Utilities/interface/atomic_value_ptr.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24439 SiPixelQuality PCL bug fix
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.cc
  CalibTracker/SiPixelQuality/test/step4_ALCAHARVEST.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24454 Removed unnused variable in lambda capture
  FWCore/Integration/test/ESTestProducers.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24455 Removed std::move on return to allow compiler optimization
  Geometry/EcalTestBeam/plugins/EcalTBHodoscopeGeometryLoaderFromDDD.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#24457 Removed unnecessary parentheses in Geometry/HGCalCommonData
  Geometry/HGCalCommonData/plugins/DDHGCalWafer8.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#24456 Removed unnecessary std::move from Geometry/ForwardGeometry
  Geometry/ForwardGeometry/src/CastorHardcodeGeometryLoader.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#24458 Removed unused variable in Geometry/HcalCommonData
  Geometry/HcalCommonData/src/HcalHitRelabeller.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#24459 Removed self assignment in Geometry/TrackerNumberingBuilder
  Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#24382 Refactor tau cluster variable computation
  RecoTauTag/RecoTau/interface/PFRecoTauClusterVariables.h
  RecoTauTag/RecoTau/plugins/PATTauDiscriminationByMVAIsolationRun2.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByMVAIsolationRun2.cc
  RecoTauTag/RecoTau/src/PFRecoTauClusterVariables.cc
  RecoTauTag/RecoTau/test/rerunMVAIsolationOnMiniAOD.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24409 Phase2-hgx146 Add a new method for HGCalGeometry and add a test for corners
  Geometry/HGCalCommonData/python/testGeometryExtended_cff.py
  Geometry/HGCalCommonData/test/dumpExtended2023HGCalGeometry_cfg.py
  Geometry/HGCalGeometry/interface/HGCalGeometry.h
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
  Geometry/HGCalGeometry/test/HGCalGeometryCornerTester.cc
  Geometry/HGCalGeometry/test/python/testHGCalCorner_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#24470 Tracker alignment: fixing space at beginning of line in auto-created python scripts
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_splice.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24339 Add Hybrid Format SiStrip Zero Suppression algorithm for 2018 PbPb data-taking
  Configuration/EventContent/python/EventContentHeavyIons_cff.py
  Configuration/StandardSequences/python/DigiToRaw_Repack_cff.py
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalTracker/SiStripClusterizer/plugins/ClustersFromRawProducer.cc
  RecoLocalTracker/SiStripClusterizer/python/SiStripClusterizerOnDemand_cfi.py
  RecoLocalTracker/SiStripClusterizer/python/SiStripClusterizer_RealData_cfi.py
  RecoLocalTracker/SiStripClusterizer/python/SiStripClustersFromRaw_cfi.py
  RecoLocalTracker/SiStripClusterizer/python/hltSiStripClustersFromRaw_cfi.py
  RecoLocalTracker/SiStripZeroSuppression/interface/FastLinearCMNSubtractor.h
  RecoLocalTracker/SiStripZeroSuppression/interface/IteratedMedianCMNSubtractor.h
  RecoLocalTracker/SiStripZeroSuppression/interface/MedianCMNSubtractor.h
  RecoLocalTracker/SiStripZeroSuppression/interface/PercentileCMNSubtractor.h
  RecoLocalTracker/SiStripZeroSuppression/interface/SiStripAPVRestorer.h
  RecoLocalTracker/SiStripZeroSuppression/interface/SiStripCommonModeNoiseSubtractor.h
  RecoLocalTracker/SiStripZeroSuppression/interface/SiStripFedZeroSuppression.h
  RecoLocalTracker/SiStripZeroSuppression/interface/SiStripPedestalsSubtractor.h
  RecoLocalTracker/SiStripZeroSuppression/interface/SiStripRawProcessingAlgorithms.h
  RecoLocalTracker/SiStripZeroSuppression/interface/SiStripRawProcessingFactory.h
  RecoLocalTracker/SiStripZeroSuppression/interface/TT6CMNSubtractor.h
  RecoLocalTracker/SiStripZeroSuppression/plugins/SiStripBaselineAnalyzer.cc
  RecoLocalTracker/SiStripZeroSuppression/plugins/SiStripZeroSuppression.cc
  RecoLocalTracker/SiStripZeroSuppression/plugins/SiStripZeroSuppression.h
  RecoLocalTracker/SiStripZeroSuppression/python/DefaultAlgorithms_cff.py
  RecoLocalTracker/SiStripZeroSuppression/python/SiStripBaselineAnalyzer_cfi.py
  RecoLocalTracker/SiStripZeroSuppression/python/SiStripMeanCMExtractor_cfi.py
  RecoLocalTracker/SiStripZeroSuppression/python/SiStripZeroSuppression_SimData_cfi.py
  RecoLocalTracker/SiStripZeroSuppression/python/SiStripZeroSuppression_cfi.py
  RecoLocalTracker/SiStripZeroSuppression/python/customiseHybrid.py
  RecoLocalTracker/SiStripZeroSuppression/python/siStripMergeZeroSuppression_cfi.py
  RecoLocalTracker/SiStripZeroSuppression/src/FastLinearCMNSubtractor.cc
  RecoLocalTracker/SiStripZeroSuppression/src/IteratedMedianCMNSubtractor.cc
  RecoLocalTracker/SiStripZeroSuppression/src/MedianCMNSubtractor.cc
  RecoLocalTracker/SiStripZeroSuppression/src/PercentileCMNSubtractor.cc
  RecoLocalTracker/SiStripZeroSuppression/src/SiStripAPVRestorer.cc
  RecoLocalTracker/SiStripZeroSuppression/src/SiStripFedZeroSuppression.cc
  RecoLocalTracker/SiStripZeroSuppression/src/SiStripPedestalsSubtractor.cc
  RecoLocalTracker/SiStripZeroSuppression/src/SiStripRawProcessingAlgorithms.cc
  RecoLocalTracker/SiStripZeroSuppression/src/SiStripRawProcessingFactory.cc
  RecoLocalTracker/SiStripZeroSuppression/src/TT6CMNSubtractor.cc
  RecoLocalTracker/SiStripZeroSuppression/test/BuildFile.xml
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripBaselineAnalyzer.cc
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripBaselineComparator.cc
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripHybridFormatAnalyzer.cc
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripMeanCMExtractor.cc
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripMergeZeroSuppression.cc
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripZS_EmulateHybrid_RealData.py
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripZS_RealData.py
  RecoLocalTracker/SiStripZeroSuppression/test/displayBaselineMacro.C
  RecoLocalTracker/SiStripZeroSuppression/test/displayBaselineMacro_2types.C
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, operations-approved, orp-approved, reconstruction-approved, tests-approved

#24477 data processing scenarios for T0 for heavy ions data taking in 2018 [bp of #24468 ]
  Configuration/DataProcessing/python/Impl/HeavyIonsEra_Run2_2018.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2018_pp_on_AA.py
  Configuration/DataProcessing/python/RecoTLR.py
  Configuration/DataProcessing/test/run_CfgTest.sh
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#24449 add check validity of edm::Handle in HLTDQM modules [forwardport of #24445]
  DQMOffline/Trigger/plugins/BPHMonitor.cc
  DQMOffline/Trigger/plugins/BPHMonitor.h
  DQMOffline/Trigger/plugins/HTMonitor.cc
  DQMOffline/Trigger/plugins/HTMonitor.h
  DQMOffline/Trigger/plugins/METMonitor.cc
  DQMOffline/Trigger/plugins/METMonitor.h
  DQMOffline/Trigger/python/B2GMonitoring_cff.py
  DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24445 add check validity of edm::Handle in HLTDQM modules
  DQMOffline/Trigger/plugins/BPHMonitor.cc
  DQMOffline/Trigger/plugins/BPHMonitor.h
  DQMOffline/Trigger/plugins/HTMonitor.cc
  DQMOffline/Trigger/plugins/HTMonitor.h
  DQMOffline/Trigger/plugins/METMonitor.cc
  DQMOffline/Trigger/plugins/METMonitor.h
  DQMOffline/Trigger/python/B2GMonitoring_cff.py
  DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24484 [10.3.X] Introduce RelVal wf for testing SiStrip hybrid emulation and Hybrid ZeroSuppression of 2015 PbPb VirginRaw data
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#24475 New EOS muon validation repository
  Validation/RecoMuon/test/new_userparams.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24466 Raised nPix threshhold on pp_on_AA_2018 era track cluster checker
  RecoTracker/TkSeedGenerator/python/trackerClusterCheck_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24450 adding QIE10 ZDC digis to 2018 HI run
  RecoLocalCalo/Configuration/python/RecoLocalCalo_EventContent_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24283 Cleanup pixel tracking code (10.2.x)
  EventFilter/SiPixelRawToDigi/plugins/BuildFile.xml
  EventFilter/SiPixelRawToDigi/plugins/SealModule.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelDigiToRaw.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc
  RecoLocalTracker/SiPixelRecHits/python/SiPixelRecHits_cfi.py
  RecoPixelVertexing/Configuration/python/customizePixelTracksForProfiling.py
  RecoPixelVertexing/PixelLowPtUtilities/src/ClusterShapeTrackFilter.cc
  RecoPixelVertexing/PixelLowPtUtilities/src/LowPtClusterShapeSeedComparitor.cc
  RecoPixelVertexing/PixelLowPtUtilities/src/ThirdHitPrediction.cc
  RecoPixelVertexing/PixelLowPtUtilities/src/TrackFitter.cc
  RecoPixelVertexing/PixelTrackFitting/interface/CircleFromThreePoints.h
  RecoPixelVertexing/PixelTrackFitting/src/CircleFromThreePoints.cc
  RecoPixelVertexing/PixelTrackFitting/src/KFBasedPixelFitter.cc
  RecoPixelVertexing/PixelTrackFitting/src/PixelFitterByHelixProjections.cc
  RecoPixelVertexing/PixelTrackFitting/src/PixelTrackReconstruction.cc
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletEDProducerT.cc
  RecoPixelVertexing/PixelTriplets/src/CACell.h
  RecoPixelVertexing/PixelTriplets/src/CAGraph.h
  RecoPixelVertexing/PixelTriplets/src/CAHitQuadrupletGenerator.cc
  RecoPixelVertexing/PixelTriplets/src/CAHitTripletGenerator.cc
  RecoPixelVertexing/PixelTriplets/src/CellularAutomaton.cc
  RecoPixelVertexing/PixelTriplets/src/CellularAutomaton.h
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24325 Implimentation of Dual-Slope signal scaling for the Inner Pixel
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/python/Phase2TrackerMonitorDigi_cfi.py
  SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py
  SimTracker/SiPhase2Digitizer/test/Phase2TrackerMonitorDigi.cc
  SimTracker/SiPhase2Digitizer/test/Phase2TrackerMonitorDigi.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#24404 Convert BeamMonitor to be a one::DQMEDAnalyzer
  DQM/BeamMonitor/plugins/BeamMonitor.cc
  DQM/BeamMonitor/plugins/BeamMonitor.h
  DQM/BeamMonitor/python/BeamMonitor_Cosmics_cff.py
  DQM/BeamMonitor/python/BeamMonitor_MC_cff.py
  DQM/BeamMonitor/python/BeamMonitor_PixelLess_cff.py
  DQM/BeamMonitor/python/BeamMonitor_Pixel_cff.py
  DQM/BeamMonitor/python/BeamMonitor_cff.py
  DQMServices/Core/interface/DQMEDAnalyzer.h
  DQMServices/Core/interface/oneDQMEDAnalyzer.h
  DQMServices/Core/src/DQMEDAnalyzer.cc
  DQMServices/Core/src/oneDQMEDAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24431 Phase2-hgx148 Make use of HGCal validation code for HFNose validation
  Validation/HGCalValidation/plugins/HGCalDigiValidation.cc
  Validation/HGCalValidation/python/HFNoseDigiValidation_cfi.py
  Validation/HGCalValidation/python/HFNoseSimHitClient_cfi.py
  Validation/HGCalValidation/python/HFNoseSimHitValidation_cfi.py
  Validation/HGCalValidation/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24483 Remove spurious file
  RecoLocalCalo/HGCalRecProducers/python/hgcalLayerClusters_cfi.pybak
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#24486 Phase2-hgx149 Use fewer corner points for HGCal
  Fireworks/Geometry/interface/FWTGeoRecoGeometry.h
  Fireworks/Geometry/src/FWRecoGeometryESProducer.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#24447 Added new muon HLT collections (validation)
  Validation/RecoMuon/python/associators_cff.py
  Validation/RecoMuon/python/muonValidationHLT_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24463 Prepare EcalLaserCorrectionService for concurrent IOVs
  CalibCalorimetry/EcalLaserCorrection/interface/EcalLaserDbService.h
  CalibCalorimetry/EcalLaserCorrection/plugins/EcalLaserCorrectionService.cc
  CalibCalorimetry/EcalLaserCorrection/plugins/EcalLaserCorrectionService.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24474 Print SiStripDetVoff summary
  CalibTracker/SiStripDCS/plugins/SiStripDetVOffPrinter.cc
  CalibTracker/SiStripDCS/python/dcs_print_summary_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24493 add HEM-15-16 relval workflows
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24497 Fix GCC 8 compiler warning, catch by const reference
  RecoLocalTracker/SiStripClusterizer/plugins/ClustersFromRawProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23894 backport of CASTOR updates on rechitcorrector and noise simulation
  RecoLocalCalo/Castor/src/RecHitCorrector.cc
  SimCalorimetry/CastorSim/src/CastorAmplifier.cc
  SimCalorimetry/CastorSim/src/CastorSimParameters.cc
  SimCalorimetry/CastorSim/src/CastorSimParameters.h
  SimGeneral/MixingModule/python/castorDigitizer_cfi.py
Labels: backport-ok, comparison-available, orp-approved, pending-signatures, reconstruction-approved, simulation-pending, tests-approved

#23895 backport of CASTOR rechitcorrector and noise simulation fixes
  RecoLocalCalo/Castor/src/RecHitCorrector.cc
  SimCalorimetry/CastorSim/src/CastorAmplifier.cc
  SimCalorimetry/CastorSim/src/CastorSimParameters.cc
  SimCalorimetry/CastorSim/src/CastorSimParameters.h
  SimGeneral/MixingModule/python/castorDigitizer_cfi.py
Labels: backport-ok, comparison-available, orp-approved, pending-signatures, reconstruction-approved, simulation-pending, tests-approved

#24480 extend Modifier boolean expressions to include "not" and "or" [94X]
  FWCore/ParameterSet/python/Config.py
Labels: comparison-available, core-approved, fully-signed, orp-approved, tests-rejected

#24492 Bugfix in HcalDumpConditions
  CondTools/Hcal/plugins/CastorDumpConditions.cc
  CondTools/Hcal/plugins/HcalDumpConditions.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#24499 L1T DQM - Add new unpackers for HI run configuration
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24500 L1T DQM - Add new unpackers for HI run configuration - 102x
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
Labels: backport, bug-fix, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24434 Fix CkfTrackCandidates_cfi.py (10_2)
  RecoTracker/CkfPattern/python/CkfTrackCandidates_cfi.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24239 L1T muon offline DQM Fix dPhi calculation - 102x
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_SecondStep_cff.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_cff.py
  DQMOffline/L1Trigger/src/L1TMuonDQMOffline.cc
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#24481 GEM unpacker FED numbering range bug fix
  EventFilter/GEMRawToDigi/plugins/GEMRawToDigiModule.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24233 Ape parallel features: Backport of #24192
  Alignment/APEEstimation/macros/DrawPlot.C
  Alignment/APEEstimation/python/AlignmentTrackSelector_cff.py
  Alignment/APEEstimation/python/samples/Data_TkAlMinBias_Run2018C_PromptReco_v3_cff.py
  Alignment/APEEstimation/scripts/initialise.bash
  Alignment/APEEstimation/test/SkimProducer/skimProducer_cfg.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitter.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitterTemplates.py
  Alignment/APEEstimation/test/autoSubmitter/config.ini
  Alignment/APEEstimation/test/batch/startSkim.py
  Alignment/APEEstimation/test/cfgTemplate/apeEstimatorSummary_cfg.py
  Alignment/APEEstimation/test/cfgTemplate/apeEstimator_cfg.py
  Alignment/APEEstimation/test/cfgTemplate/apeLocalSetting_cfg.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#24451 [10.3][Change GT] Add ZDC, Castor geometry to 2018 MC Gts
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24428 Run2-alca139 Update macros for IsoTrack and Muon calibration
  Calibration/HcalCalibAlgos/macros/AnalyzeLepTree.C
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibTree.C
  Calibration/HcalCalibAlgos/macros/HBHEMuonOfflineAnalyzer.C
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24394 TopHLTMonitor: electronID WP changed to tight - Corrected btagalgo name
  DQMOffline/Trigger/plugins/TopMonitor.cc
  DQMOffline/Trigger/python/TopMonitor_cfi.py
  DQMOffline/Trigger/python/TopMonitoring_cff.py
  DQMOffline/Trigger/python/singletopHLTEventDQM_cfi.py
  DQMOffline/Trigger/python/topDiLeptonHLTEventDQM_cfi.py
  DQMOffline/Trigger/python/topSingleLeptonHLTEventDQM_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24491 Pixel code cleanup 10_3
  CalibTracker/SiPixelESProducers/plugins/SiPixel2DTemplateDBObjectESProducer.cc
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEBase.h
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEBase.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24494 Phase2-hgx150 Add a new validation code for Digi's to be used in standalone way
  Validation/HGCalValidation/python/hgcDigiStudy_cfi.py
  Validation/HGCalValidation/test/HGCalDigiStudy.cc
  Validation/HGCalValidation/test/runHGCalDigiStudy_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24502 add unit test for PyMVA root macro
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/test_PyMVA.cpp
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, requires-external, tests-approved

#24510 Disable IMT for merging of NanoAOD (master branch)
  Configuration/DataProcessing/python/Merge.py
Labels: code-checks-approved, comparison-pending, fully-signed, operations-approved, orp-approved, tests-approved

#24291 L1T offline emulator DQM config upgrades - 102x
  DQMOffline/L1Trigger/python/L1EmulatorQualityTestsOffline_cff.py
  DQMOffline/L1Trigger/python/L1TEmulatorMonitorClientOffline_cff.py
  DQMOffline/L1Trigger/python/L1TEmulatorMonitorOffline_cff.py
  DQMOffline/L1Trigger/python/L1TMonitorClientOffline_cff.py
  DQMOffline/L1Trigger/python/L1TMuonDQMEfficiency_cff.py
  DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_SecondStep_cff.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_cff.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#24437 [10.2.X] Introduce a special AlCaReco for Strip Small Bias Scans
  Calibration/TkAlCaRecoProducers/plugins/BuildFile.xml
  Calibration/TkAlCaRecoProducers/plugins/CalibrationTrackSelectorFromDetIdList.cc
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalSmallBiasScan_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalSmallBiasScan_cff.py
  Calibration/TkAlCaRecoProducers/python/CalibrationTrackSelectorFromDetIdList_cfi.py
  Configuration/AlCa/python/autoCond.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24443 SiPixelQuality PCL bug fix
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.cc
  CalibTracker/SiPixelQuality/test/step4_ALCAHARVEST.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#24508 Disable IMT for merging of NanoAOD.
  Configuration/DataProcessing/python/Merge.py
Labels: comparison-pending, fully-signed, operations-approved, orp-approved, tests-approved

#24421 SiPixelDigitizerAlgorithm uninitialized variables
  CondFormats/SiPixelTransient/interface/SiPixelTemplate2D.h
  CondFormats/SiPixelTransient/src/SiPixelTemplate2D.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
Labels: bug-fix, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#24498 Fix SimPFProducer for electrons
  RecoParticleFlow/PFSimProducer/plugins/SimPFProducer.cc
  Validation/HGCalValidation/plugins/CaloParticleValidation.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24473 FastSim: make two parameters of the KineParticleFilter configurable
  FastSimulation/Event/python/ParticleFilter_cfi.py
  FastSimulation/Event/src/KineParticleFilter.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#24517 Move computation of debug-only variables in SiPixelDigitizerAlgorithm inside TP_DEBUG
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#24487 Add HI jet histograms to offline DQM for pp_on_AA_2018 era
  DQMOffline/JetMET/interface/JetAnalyzer_HeavyIons.h
  DQMOffline/JetMET/python/jetAnalyzer_cff.py
  DQMOffline/JetMET/src/JetAnalyzer_HeavyIons.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24329 Implementation of the dual slope in the clusterizer for Phase2 IT
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.h
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#24507 Fix imaging algo for post tdr geometries
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalImagingAlgo.h
  RecoLocalCalo/HGCalRecAlgos/src/HGCalImagingAlgo.cc
  RecoLocalCalo/HGCalRecAlgos/src/RecHitTools.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#24519 fix the output name repetition issue and adjust the job splitting
  Configuration/PyReleaseValidation/python/MatrixInjector.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24529 L1T DQM - Add missing HI rawDataRepacker changes
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24533 Phase2-hgx152 Extend SimHitStudy validation test for HFNose
  Validation/HGCalValidation/python/hfnoseSimHitStudy_cfi.py
  Validation/HGCalValidation/test/runHFNoseSimHitStudy_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24525 GEM online DQM client update for HI run test
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24531 HCALDQM: Fix sources for heavy ion runs (10_3_X)
  DQM/Integration/python/clients/hcal_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24515 HCALDQM: Improve LED monitoring (10_3_X)
  DQM/HcalCommon/interface/ValueQuantity.h
  DQM/HcalTasks/data/HcalQualityTests.xml
  DQM/HcalTasks/interface/DigiTask.h
  DQM/HcalTasks/interface/LEDTask.h
  DQM/HcalTasks/plugins/DigiTask.cc
  DQM/HcalTasks/plugins/LEDTask.cc
  DQM/HcalTasks/python/DigiTask.py
  DQM/HcalTasks/python/LEDCalibrationChannels.py
  DQM/HcalTasks/python/LEDTask.py
  DQM/HcalTasks/src/DigiRunSummary.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24552 Revert "L1T offline emulator DQM config upgrades - 102x"
  DQMOffline/L1Trigger/python/L1EmulatorQualityTestsOffline_cff.py
  DQMOffline/L1Trigger/python/L1TEmulatorMonitorClientOffline_cff.py
  DQMOffline/L1Trigger/python/L1TEmulatorMonitorOffline_cff.py
  DQMOffline/L1Trigger/python/L1TMonitorClientOffline_cff.py
  DQMOffline/L1Trigger/python/L1TMuonDQMEfficiency_cff.py
  DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_SecondStep_cff.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_cff.py
Labels: comparison-available, dqm-pending, l1-pending, orp-approved, pending-signatures, tests-approved

#24535 Fireworks: Fix in EveService (forward port to master)
  Fireworks/Eve/plugins/DummyEvelyser.cc
  Fireworks/Eve/python/testEve_cfg.py
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#24538 Add support for CaloParticle in Fireworks
  Fireworks/SimData/plugins/BuildFile.xml
  Fireworks/SimData/plugins/FWCaloParticleProxyBuilder.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#24527 Create PythiaCP5TuneDownSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP5TuneDownSettings_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24528 Create PythiaCP5TuneUpSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP5TuneUpSettings_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24460 Prepare for concurrent IOVs DT and CSC Geometry
  Geometry/CSCGeometry/interface/CSCGeometry.h
  Geometry/CSCGeometry/src/CSCGeometry.cc
  Geometry/CSCGeometryBuilder/plugins/CSCGeometryESModule.cc
  Geometry/CSCGeometryBuilder/plugins/CSCGeometryESModule.h
  Geometry/DTGeometry/interface/DTGeometry.h
  Geometry/DTGeometry/src/DTGeometry.cc
  Geometry/DTGeometryBuilder/plugins/DTGeometryESModule.cc
  Geometry/DTGeometryBuilder/plugins/DTGeometryESModule.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#24462 Prepare CastorDbProducer for concurrent IOVs
  CalibCalorimetry/CastorCalib/plugins/CastorDbProducer.cc
  CalibCalorimetry/CastorCalib/plugins/CastorDbProducer.h
  CalibFormats/CastorObjects/interface/CastorCalibrationWidths.h
  CalibFormats/CastorObjects/interface/CastorCalibrations.h
  CalibFormats/CastorObjects/interface/CastorDbService.h
  CalibFormats/CastorObjects/src/CastorDbService.cc
  SimCalorimetry/CastorSim/test/CastorDigitizerTest.cpp
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#24561 OfflineDQM: Offline L1T muon DQM with coordinates extrapolated to the muon system CMSLITDPG-729
  DQMOffline/L1Trigger/BuildFile.xml
  DQMOffline/L1Trigger/interface/L1TMuonDQMOffline.h
  DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py
  DQMOffline/L1Trigger/src/L1TMuonDQMOffline.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#24558 [10.2.X] backport: Introduce RelVal wf for testing Hybrid ZeroSuppression
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24571 FWCore/Framework: changes needed for Clang 9.1 on macOS wrapped in ifdef statements.
  FWCore/Framework/src/EventSetupRecordProvider.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/make_shared_noexcept_false.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24485 Further usability improvements for APE tool
  Alignment/APEEstimation/python/conditions/init.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitter.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitterTemplates.py
  Alignment/APEEstimation/test/autoSubmitter/config.ini
  Alignment/APEEstimation/test/batch/startSkim.py
  Alignment/APEEstimation/test/cfgTemplate/apeEstimator_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24559 Hcal phase1 fastsim update and run2 hcx178 : backport to 94X
  FastSimulation/CaloGeometryTools/src/CaloGeometryHelper.cc
  FastSimulation/Calorimetry/src/CalorimetryManager.cc
  FastSimulation/ShowerDevelopment/interface/FastHFShowerLibrary.h
  FastSimulation/ShowerDevelopment/src/FastHFShowerLibrary.cc
  Geometry/HcalTowerAlgo/interface/HcalGeometry.h
  Geometry/HcalTowerAlgo/src/HcalGeometry.cc
  SimCalorimetry/HcalSimProducers/python/hcalUnsuppressedDigis_cfi.py
  Validation/HcalDigis/python/HLTHcalDigisParam_cfi.py
  Validation/HcalDigis/python/HcalDigisParam_cfi.py
  Validation/HcalHits/python/HcalSimHitStudy_cfi.py
  Validation/HcalHits/python/HcalSimHitsValidation_cfi.py
  Validation/HcalHits/python/SimHitsValidationHcal_cfi.py
  Validation/HcalRecHits/python/HLTHcalRecHitParam_cfi.py
  Validation/HcalRecHits/python/HcalRecHitParam_cfi.py
Labels: comparison-available, dqm-approved, fastsim-approved, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#24433 Fix CkfTrackCandidates_cfi.py (10_1)
  RecoTracker/CkfPattern/python/CkfTrackCandidates_cfi.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24365 island clustering can exclude flagged rechits
  Calibration/EcalCalibAlgos/interface/Pi0FixedMassWindowCalibration.h
  Calibration/EcalCalibAlgos/src/Pi0FixedMassWindowCalibration.cc
  RecoEcal/EgammaClusterAlgos/interface/IslandClusterAlgo.h
  RecoEcal/EgammaClusterAlgos/src/IslandClusterAlgo.cc
  RecoEcal/EgammaClusterProducers/interface/IslandClusterProducer.h
  RecoEcal/EgammaClusterProducers/python/islandBasicClusters_cfi.py
  RecoEcal/EgammaClusterProducers/src/IslandClusterProducer.cc
  RecoEgamma/EgammaHLTProducers/src/EgammaHLTIslandClusterProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#24476 Prepare for concurrent IOVs, HcalDbProducer
  CalibCalorimetry/HcalPlugins/src/HcalDbProducer.cc
  CalibCalorimetry/HcalPlugins/src/HcalDbProducer.h
  CalibFormats/HcalObjects/interface/HcalDbService.h
  CalibFormats/HcalObjects/src/HcalDbService.cc
  SimCalorimetry/HcalSimAlgos/test/HcalDigitizerTest.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#24495 ZDC/RPD QIE10 Digis DQM online
  DQM/HcalTasks/interface/ZDCQIE10Task.h
  DQM/HcalTasks/plugins/ZDCQIE10Task.cc
  DQM/HcalTasks/python/ZDCTask.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24588 Fix a.clone(b=dict(c=None)) (94X)
  FWCore/ParameterSet/python/Config.py
  FWCore/ParameterSet/python/Mixins.py
Labels: backport-ok, comparison-available, core-approved, fully-signed, orp-approved, tests-rejected

#24084 Displaying Hcal Conditions via the CondDB Browser
  CondCore/HcalPlugins/interface/HcalObjRepresent.h
  CondCore/HcalPlugins/plugins/BuildFile.xml
  CondCore/HcalPlugins/plugins/HcalChannelQuality_PayloadInspector.cc
  CondCore/HcalPlugins/plugins/HcalGains_PayloadInspector.cc
  CondCore/HcalPlugins/plugins/HcalL1TriggerObjects_PayloadInspector.cc
  CondCore/HcalPlugins/plugins/HcalPedestalWidths_PayloadInspector.cc
  CondCore/HcalPlugins/plugins/HcalPedestals_PayloadInspector.cc
  CondCore/HcalPlugins/plugins/HcalRecoParams_PayloadInspector.cc
  CondCore/HcalPlugins/plugins/HcalRespCorrs_PayloadInspector.cc
  CondCore/HcalPlugins/plugins/HcalSiPMCharacteristics_PayloadInspector.cc
  CondCore/HcalPlugins/plugins/HcalSiPMParameters_PayloadInspector.cc
  CondFormats/HcalObjects/src/HcalSiPMCharacteristics.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#24504 Phase2-hgx151 Modify RecHitTools for servicing old and new geometries
  RecoLocalCalo/HGCalRecAlgos/interface/RecHitTools.h
  RecoLocalCalo/HGCalRecAlgos/src/RecHitTools.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#24546 clean up SiPixel digitizer and clusterizer code removing variables used for pre-phase2 TDR studies
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.h
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.h
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#24537 Update to pp_on_AA_2018 era track selection with new MVAs
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  RecoTracker/IterativeTracking/python/DetachedQuadStep_cff.py
  RecoTracker/IterativeTracking/python/DetachedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/HighPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/InitialStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtQuadStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/MixedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoTracker/IterativeTracking/python/TobTecStep_cff.py
  RecoTracker/IterativeTracking/python/iterativeTkConfig.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, reconstruction-approved, tests-approved, upgrade-approved

#24564 Fireworks packages: changes required to compile with Apple Clang 9.1
  Fireworks/Core/BuildFile.xml
  Fireworks/Core/bin/cmsShow.cc
  Fireworks/Core/interface/CmsShowMainBase.h
  Fireworks/Core/interface/FWEveView.h
  Fireworks/Core/interface/FWGUIManager.h
  Fireworks/Core/interface/FWXMLConfigParser.h
  Fireworks/Core/src/CmsShowMain.cc
  Fireworks/Core/src/CmsShowMain.h
  Fireworks/Core/src/FWConfigurationManager.cc
  Fireworks/Core/src/FWFileEntry.cc
  Fireworks/Core/src/FWGUIValidatingTextEntry.cc
  Fireworks/Core/src/FWJobMetadataManager.cc
  Fireworks/Core/test/unittest_fwconfiguration.cc
  Fireworks/Electrons/plugins/FWConvTrackHitsDetailView.cc
  Fireworks/Macros/FileUrlService.C
  Fireworks/Macros/eve_macros.cc
  Fireworks/Muons/plugins/FWCSCStripDigiProxyBuilder.cc
  Fireworks/Muons/src/FWMuonBuilder.cc
  Fireworks/Tracks/plugins/FWTrackHitsDetailView.cc
  Fireworks/Tracks/src/TrackUtils.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#24566 PhysicsTool/Utilities : Changes required to compile with Apple Clang 9.1
  PhysicsTools/Utilities/interface/Expression.h
  PhysicsTools/Utilities/interface/NumericalIntegration.h
  PhysicsTools/Utilities/interface/RootMinuit.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#24583 add 3 production workflows for premix2018
  Configuration/PyReleaseValidation/python/relval_premix.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24614 fix eta range plots for pixel Phase1
  DQMOffline/RecoB/python/PrimaryVertexMonitor_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24536 Prepare FFT ESProducers for concurrent IOVs
  JetMETCorrections/FFTJetModules/plugins/FFTJetCorrectionESProducer.h
  JetMETCorrections/FFTJetModules/plugins/FFTJetLookupTableESProducer.cc
  JetMETCorrections/FFTJetObjects/interface/FFTJetCorrectorSequence.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#24540 SiStrip/Pixel online client setup for HI2018
  DQM/Integration/python/clients/pixel_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24599 Phase2-hgx153 Bug fix for RecoGeometry in FireWorks
  Fireworks/Geometry/src/FWRecoGeometryESProducer.cc
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved, visualization-approved

#24600 Phase2-hgx154 Some helpful addition to prints
  DataFormats/ForwardDetId/src/HFNoseDetId.cc
  DataFormats/ForwardDetId/src/HGCScintillatorDetId.cc
  DataFormats/ForwardDetId/src/HGCSiliconDetId.cc
  DataFormats/ForwardDetId/src/HGCalDetId.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#24601 monitor island superclusters and photons for HI
  DQMOffline/EGamma/python/egammaDQMOffline_cff.py
  Validation/EcalClusters/python/egammaSCAnalyzer_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24593 Run2-alca140 Modify the calibration scripts
  Calibration/HcalCalibAlgos/macros/AnalyzeLepTree.C
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibTree.C
  Calibration/HcalCalibAlgos/macros/HBHEMuonOfflineAnalyzer.C
  Calibration/HcalCalibAlgos/macros/OfflineMain.C
  Calibration/HcalCalibAlgos/macros/install_OfflineMain.sh
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24623 Fix seg fault occurring after EventSetup exception
  FWCore/Framework/interface/EventProcessor.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/TransitionProcessors.icc
  FWCore/Framework/test/MockEventProcessor.cc
  FWCore/Framework/test/MockEventProcessor.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24610 Fix premixing for HGCal v9 geometry
  DataFormats/HGCDigi/interface/PHGCSimAccumulator.h
  SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#24591 Cleanup of Geant4 interface
  SimG4Core/Application/interface/ParametrisedEMPhysics.h
  SimG4Core/Application/interface/RunAction.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/EventAction.cc
  SimG4Core/Application/src/ParametrisedEMPhysics.cc
  SimG4Core/Application/src/RunAction.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/CustomPhysics/src/CustomPhysicsList.cc
  SimG4Core/CustomPhysics/src/CustomPhysicsListSS.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#24573 Add new scenarios for HPBeamspot in ExpressAlignment HcalCalMinBias in HCalNZS PD
  Configuration/DataProcessing/python/Impl/hcalnzsEra_Run2_2018_pp_on_AA.py
  Configuration/DataProcessing/python/Impl/trackingOnlyEra_Run2_2018_pp_on_AA.py
  Configuration/DataProcessing/python/RecoTLR.py
  Configuration/DataProcessing/test/run_CfgTest.sh
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#24560 PPS: input flags for lite track producer
  RecoCTPPS/TotemRPLocal/plugins/CTPPSLocalTrackLiteProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24553 adding centrality to offline DQM/Physics for 2018 Heavy Ion run
  DQM/Physics/python/DQMPhysics_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24568 DataFormats/PatCandidates: Changes required to compile with Apple Clang 9.1
  DataFormats/PatCandidates/src/JetCorrFactors.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#24577 Add protection for disabled FEDs in the SiStrip packer
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRaw.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRaw.h
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRawModule.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRawModule.h
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.h
  EventFilter/SiStripRawToDigi/plugins/WarningSummary.cc
  EventFilter/SiStripRawToDigi/plugins/WarningSummary.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24548 Prepare ecal ESProducers for concurrent IOVs
  CondFormats/EcalObjects/interface/EcalCondObjectContainer.h
  DataFormats/EcalDetId/interface/EcalContainer.h
  RecoEcal/EgammaCoreTools/plugins/EcalNextToDeadChannelESProducer.cc
  RecoLocalCalo/EcalRecAlgos/plugins/EcalSeverityLevelESProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#24567 CommonTools/Statistics: Changes required to compile with Apple Clang 9.1
  CommonTools/Statistics/interface/SequentialCombinationGenerator.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#24622 User plugin ParameterSet validation
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/PluginUsingProducer.cc
  FWCore/ParameterSet/interface/PluginDescription.h
  FWCore/ParameterSet/interface/PluginDescriptionAdaptor.h
  FWCore/ParameterSet/interface/PluginDescriptionAdaptorBase.h
  FWCore/ParameterSet/interface/ValidatedPluginFactoryMacros.h
  FWCore/ParameterSet/interface/ValidatedPluginMacros.h
  FWCore/ParameterSet/test/parameterSetDescription_t.cc
  FWCore/PluginManager/interface/PluginFactory.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#24415 activating usage of EcalSimPulseShapeRcd (>= 10_3_X)
  CalibCalorimetry/EcalSRTools/src/EcalDccWeightBuilder.cc
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
  Configuration/AlCa/python/autoCond.py
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerGlobal.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerGlobal.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerWeights.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerWeights.h
  SimCalorimetry/EcalSimAlgos/test/testEcalShape.cpp
  SimCalorimetry/EcalSimProducers/interface/EcalDigiProducer.h
  SimCalorimetry/EcalSimProducers/src/EcalDigiProducer.cc
  Validation/EcalDigis/interface/EcalMixingModuleValidation.h
  Validation/EcalDigis/src/EcalMixingModuleValidation.cc
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#24569 Pr103x HeavyIon 2018 CaloLayer2, Un/Packer, Emulator, O2O
  DataFormats/L1Trigger/interface/EtSum.h
  EventFilter/L1TRawToDigi/plugins/L1TRawToDigi.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/CaloSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EtSumPacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EtSumUnpacker_0x10010057.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EtSumUnpacker_0x10010057.h
  EventFilter/L1TRawToDigi/utils/unpackBuffers-CaloStage2.py
  L1Trigger/Configuration/python/customiseSettings.py
  L1Trigger/L1TCalorimeter/interface/CaloParamsHelper.h
  L1Trigger/L1TCalorimeter/interface/CaloTools.h
  L1Trigger/L1TCalorimeter/interface/Stage2Layer2DemuxSumsAlgoFirmware.h
  L1Trigger/L1TCalorimeter/interface/Stage2Layer2JetAlgorithmFirmware.h
  L1Trigger/L1TCalorimeter/macros/compHwEmu.C
  L1Trigger/L1TCalorimeter/plugins/L1TCaloParamsESProducer.cc
  L1Trigger/L1TCalorimeter/plugins/L1TCaloStage2ParamsESProducer.cc
  L1Trigger/L1TCalorimeter/plugins/L1TStage2CaloAnalyzer.cc
  L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_4_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParams_cfi.py
  L1Trigger/L1TCalorimeter/python/convertParamsToOnlineFormat.py
  L1Trigger/L1TCalorimeter/python/customiseReEmulateCaloLayer2.py
  L1Trigger/L1TCalorimeter/python/l1tStage2InputPatternWriter_cfi.py
  L1Trigger/L1TCalorimeter/src/CaloTools.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2DemuxSumsAlgoFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2EtSumAlgorithmFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2JetAlgorithmFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/test/runCaloLayer2MPFWValidation.py
  L1Trigger/L1TCalorimeter/test/runEmulator-CaloStage2.py
  L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeDataFormat.h
  L1TriggerConfig/L1TConfigProducers/src/CaloParamsHelperO2O.h
  L1TriggerConfig/L1TConfigProducers/src/L1TCaloParamsOnlineProd.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24184 Change premixing library format from RAW to DIGI
  Configuration/EventContent/python/EventContent_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/DigiToRaw_cff.py
  EventFilter/ESDigiToRaw/python/esDigiToRaw_cfi.py
  EventFilter/SiStripRawToDigi/python/SiStripDigiToRaw_cfi.py
  L1Trigger/Configuration/python/L1TDigiToRaw_cff.py
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  SimCalorimetry/Configuration/python/SimCalorimetry_EventContent_cff.py
  SimGeneral/Configuration/python/SimGeneral_EventContent_cff.py
  SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py
  SimMuon/Configuration/python/SimMuon_EventContent_cff.py
  SimTracker/Configuration/python/SimTracker_EventContent_cff.py
Labels: code-checks-approved, comparison-available, daq-pending, l1-approved, operations-approved, orp-approved, pdmv-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#24627 Added unit test to make sure poisoned datafiles are not read from release
  CondTools/Geometry/test/BuildFile.xml
  CondTools/Geometry/test/test-data-file-deletion.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#24644 Fireworks: replace functions/templates deprecated by std=c++17
  Fireworks/FWInterface/interface/FWFFLooper.h
  Fireworks/FWInterface/interface/FWFFService.h
  Fireworks/Geometry/src/TGeoFromDddService.cc
  Fireworks/Geometry/src/TGeoMgrFromDdd.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#24539 sync OMTF code (as in tag omtfdev_mk20).
  EventFilter/L1TRawToDigi/interface/OmtfRpcPacker.h
  EventFilter/L1TRawToDigi/interface/OmtfRpcUnpacker.h
  EventFilter/L1TRawToDigi/src/OmtfCscPacker.cc
  EventFilter/L1TRawToDigi/src/OmtfCscUnpacker.cc
  EventFilter/L1TRawToDigi/src/OmtfRpcPacker.cc
  EventFilter/L1TRawToDigi/src/OmtfRpcUnpacker.cc
  L1Trigger/L1TMuonOverlap/interface/AlgoMuon.h
  L1Trigger/L1TMuonOverlap/interface/OMTFReconstruction.h
  L1Trigger/L1TMuonOverlap/interface/OMTFinput.h
  L1Trigger/L1TMuonOverlap/interface/OMTFinputMaker.h
  L1Trigger/L1TMuonOverlap/plugins/L1TMuonOverlapTrackProducer.cc
  L1Trigger/L1TMuonOverlap/python/simOmtfDigis_cfi.py
  L1Trigger/L1TMuonOverlap/src/GhostBusterPreferRefDt.cc
  L1Trigger/L1TMuonOverlap/src/OMTFProcessor.cc
  L1Trigger/L1TMuonOverlap/src/OMTFReconstruction.cc
  L1Trigger/L1TMuonOverlap/src/OMTFSorter.cc
  L1Trigger/L1TMuonOverlap/src/OMTFinput.cc
  L1Trigger/L1TMuonOverlap/src/OMTFinputMaker.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24586 Migrate from boost::optional to std::optional in EventSetup system
  CondTools/SiStrip/plugins/SiStripFedCablingReader.cc
  DQM/DTMonitorClient/src/DTDAQInfo.cc
  DQM/EcalPreshowerMonitorModule/src/ESDaqInfoTask.cc
  DQM/HcalCommon/src/DQClient.cc
  DQM/HcalCommon/src/DQHarvester.cc
  DQM/HcalCommon/src/DQTask.cc
  DQM/RPCMonitorClient/src/RPCDCSSummary.cc
  DQM/RPCMonitorClient/src/RPCDaqInfo.cc
  DQM/RPCMonitorClient/src/RPCDataCertification.cc
  DQM/RPCMonitorClient/src/RPCEventSummary.cc
  DQM/SiPixelMonitorClient/src/SiPixelDaqInfo.cc
  DQM/SiPixelMonitorClient/src/SiPixelDcsInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripDaqInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripDcsInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripOfflineDQM.cc
  DQM/SiStripMonitorDigi/src/SiStripMonitorDigi.cc
  DQM/TrackingMonitorClient/plugins/TrackingOfflineDQM.cc
  DQM/TrackingMonitorClient/src/TrackingCertificationInfo.cc
  DQMServices/Components/src/DQMDaqInfo.cc
  FWCore/Framework/interface/CallbackProxy.h
  FWCore/Framework/interface/ESProducer.h
  FWCore/Framework/interface/EventSetup.h
  FWCore/Framework/interface/es_Label.h
  FWCore/Framework/interface/produce_helpers.h
  FWCore/Framework/src/EventSetup.cc
  FWCore/Framework/test/DummyData.h
  FWCore/Framework/test/DummyProxyProvider.h
  FWCore/Framework/test/eventsetup_t.cppunit.cc
  FWCore/Modules/src/EventSetupRecordDataGetter.cc
  L1TriggerConfig/RCTConfigProducers/src/L1RCTChannelMaskTester.cc
  PhysicsTools/CondLiteIO/plugins/FWLiteESRecordWriterAnalyzer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, core-approved, db-approved, dqm-approved, l1-approved, orp-approved, pending-signatures, tests-approved

#24335 add d_xy error plots [backport #24315]
  DQM/TrackingMonitor/interface/TrackAnalyzer.h
  DQM/TrackingMonitor/python/TrackingMonitor_cfi.py
  DQM/TrackingMonitor/src/TrackAnalyzer.cc
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24526 GEM online DQM client update for HI run test Backport
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24530 L1T DQM - Add missing HI rawDataRepacker changes - 102x
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
Labels: backport-ok, bug-fix, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24532 HCALDQM: Fix sources for heavy ion runs (10_2_X)
  DQM/Integration/python/clients/hcal_dqm_sourceclient-live_cfg.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24534 Fireworks 10_2_X : Fix access of collections in EveService
  Fireworks/Eve/plugins/DummyEvelyser.cc
  Fireworks/Eve/python/testEve_cfg.py
Labels: backport-ok, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#24550 [10.2.X] add HEM-15-16 relval workflows
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24584 backport of PythiaCP5TuneDownSettings
  Configuration/Generator/python/MCTunes2017/PythiaCP5TuneDownSettings_cfi.py
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24585 backport of PythiaCP5TuneUpSettings
  Configuration/Generator/python/MCTunes2017/PythiaCP5TuneUpSettings_cfi.py
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#24616 fix eta range plots for pixel Phase1 [backport #24614]
  DQMOffline/RecoB/python/PrimaryVertexMonitor_cff.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#24618 backport [10.2.X] add 3 production workflows for premix2018
  Configuration/PyReleaseValidation/python/relval_premix.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#24654 Bug fix: truncate when copying digis in hybrid zero-suppression
  RecoLocalTracker/SiStripZeroSuppression/src/SiStripRawProcessingAlgorithms.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24640 CalibTracker/SiStripDCS: replace functions/templates deprecated in std=c++17.
  CalibTracker/SiStripDCS/interface/SiStripCoralIface.h
  CalibTracker/SiStripDCS/interface/SiStripDetVOffBuilder.h
  CalibTracker/SiStripDCS/src/SiStripCoralIface.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24638 Alignment/CommonAlignment: replace use of functions/templates deprecated in c++17 std.
  Alignment/CommonAlignment/src/AlignableModifier.cc
  Alignment/CommonAlignment/src/AlignmentParametersData.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24634 Alignment/SurveyAnalsis: replace use of deprecated functions for std=c++17
  Alignment/SurveyAnalysis/src/SurveyPxbDicer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24635 Alignment/ReferenceTrajectories: replace templates deprecated by std=c++17
  Alignment/ReferenceTrajectories/plugins/CombinedTrajectoryFactory.cc
  Alignment/ReferenceTrajectories/src/ReferenceTrajectory.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24636 Alignment/OfflineValidation: replace use of templates deprecated by std=cxx17
  Alignment/OfflineValidation/plugins/EopTreeWriter.cc
  Alignment/OfflineValidation/plugins/TrackerOfflineValidation.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24642 CaloOnlineTools/EcalTools: replace functions/templated deprecated by std=c++17
  CaloOnlineTools/EcalTools/plugins/EcalPulseShapeGrapher.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24639 CalibCalorimetry packages: replace use of functions/templates deprecated by std=c++17
  CalibCalorimetry/CaloTPG/plugins/CaloTPGTranscoderULUTs.cc
  CalibCalorimetry/EcalLaserSorting/interface/LaserSorter.h
  CalibCalorimetry/EcalLaserSorting/interface/WatcherStreamFileReader.h
  CalibCalorimetry/EcalLaserSorting/src/WatcherStreamFileReader.cc
  CalibCalorimetry/HcalAlgos/plugins/HcalPulseContainmentTest.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#24637 Alignment/CommonAlignmentAlgorithm: replace functions deprecated in std=c++17
  Alignment/CommonAlignmentAlgorithm/plugins/SiPixelLorentzAngleCalibration.cc
  Alignment/CommonAlignmentAlgorithm/plugins/SiStripBackplaneCalibration.cc
  Alignment/CommonAlignmentAlgorithm/plugins/SiStripLorentzAngleCalibration.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24641 Calibration/EcalCalibAlgos: replace fuctions/templates deprecated by std=c++17.
  Calibration/EcalCalibAlgos/src/Pi0FixedMassWindowCalibration.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#24612 Prepare some Geometry ESProducers for concurrent IOVs
  Geometry/EcalMapping/plugins/EcalElectronicsMappingBuilder.cc
  Geometry/EcalMapping/plugins/EcalElectronicsMappingBuilder.h
  Geometry/HcalCommonData/plugins/HcalDDDSimConstantsESModule.cc
  Geometry/HcalEventSetup/interface/HcalDDDGeometryEP.h
  Geometry/HcalEventSetup/interface/HcalHardcodeGeometryEP.h
  Geometry/HcalEventSetup/interface/HcalTopologyIdealEP.h
  Geometry/HcalEventSetup/src/CaloTowerHardcodeGeometryEP.cc
  Geometry/HcalEventSetup/src/CaloTowerHardcodeGeometryEP.h
  Geometry/HcalEventSetup/src/HcalDDDGeometryEP.cc
  Geometry/HcalEventSetup/src/HcalHardcodeGeometryEP.cc
  Geometry/HcalEventSetup/src/HcalTopologyIdealEP.cc
  Geometry/HcalEventSetup/src/SealModule.cc
  Geometry/HcalTowerAlgo/interface/HcalDDDGeometryLoader.h
  Geometry/HcalTowerAlgo/interface/HcalFlexiHardcodeGeometryLoader.h
  Geometry/HcalTowerAlgo/interface/HcalHardcodeGeometryLoader.h
  Geometry/HcalTowerAlgo/src/HcalFlexiHardcodeGeometryLoader.cc
  Geometry/HcalTowerAlgo/src/HcalHardcodeGeometryLoader.cc
  Geometry/HcalTowerAlgo/test/HcalCellSizeCheck.cc
  Geometry/HcalTowerAlgo/test/HcalDetIdTester.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryAnalyzer.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryDetIdAnalyzer.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryDump.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryPlan1Tester.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryTester.cc
  Geometry/MuonNumbering/plugins/MuonNumberingInitialization.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#24656 Allow PluginDescription default to work in release build
  FWCore/ParameterSet/interface/PluginDescription.h
  FWCore/PluginManager/interface/PluginManager.h
  FWCore/PluginManager/src/PluginManager.cc
Labels: code-checks-approved, comparison-pending, core-approved, fully-signed, orp-approved, tests-started

#24514 fix compilation error with EDM DEBUG in 80X
  TrackingTools/TrackFitters/plugins/KFFittingSmoother.h
  TrackingTools/TrackFitters/src/KFTrajectorySmoother.cc
Labels: comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24580 Update PythiaCP5TuneUpSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP5TuneUpSettings_cfi.py
Labels: backport-ok, comparison-pending, fully-signed, generators-approved, orp-approved, tests-approved
