Repository cms-sw/cmssw, pull requests merged in 2018-06, with the labels that each got.

#23395 update VtxSmearingScenario for 10_2_X MC production
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealistic25ns13TeVEarly2018Collision_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#23410 Better protect EventProcessor::globalEndLumiAsync from exceptions
  FWCore/Framework/src/EventProcessor.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23412 DD Compact View: Fix Excessive Output
  DetectorDescription/Core/src/DDCompactView.cc
Labels: code-checks-approved, comparison-pending, geometry-pending, orp-approved, pending-signatures, tests-started

#23206 DeepCSV and CSVv2 negative tagger bugfix
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/Combined/python/deepFlavour_cff.py
  RecoBTag/SecondaryVertex/interface/CombinedSVComputer.h
  RecoBTag/SecondaryVertex/plugins/TemplatedSecondaryVertexProducer.cc
  RecoBTag/SecondaryVertex/python/pfInclusiveSecondaryVertexFinderNegativeTagInfos_cfi.py
  RecoBTag/SecondaryVertex/src/CombinedSVComputer.cc
  RecoVertex/AdaptiveVertexFinder/interface/TrackVertexArbitration.h
  RecoVertex/AdaptiveVertexFinder/plugins/InclusiveVertexFinder.h
  RecoVertex/AdaptiveVertexFinder/python/inclusiveNegativeVertexing_cff.py
  RecoVertex/AdaptiveVertexFinder/python/inclusiveVertexing_cff.py
  RecoVertex/AdaptiveVertexFinder/src/TracksClusteringFromDisplacedSeed.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23033 TensorFlow-based DeepDoubleB tagger integration
  DataFormats/BTauReco/interface/BoostedDoubleSVTagInfoFeatures.h
  DataFormats/BTauReco/interface/ChargedCandidateFeatures.h
  DataFormats/BTauReco/interface/DeepDoubleBFeatures.h
  DataFormats/BTauReco/interface/DeepDoubleBTagInfo.h
  DataFormats/BTauReco/src/classes.h
  DataFormats/BTauReco/src/classes_def.xml
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/Configuration/python/RecoBTag_cff.py
  RecoBTag/DeepFlavour/plugins/BTagConverter.h
  RecoBTag/DeepFlavour/plugins/BuildFile.xml
  RecoBTag/DeepFlavour/plugins/ChargedCandidateConverter.h
  RecoBTag/DeepFlavour/plugins/JetConverter.h
  RecoBTag/DeepFlavour/plugins/NeutralCandidateConverter.h
  RecoBTag/DeepFlavour/plugins/SVConverter.h
  RecoBTag/DeepFlavour/plugins/deep_helpers.h
  RecoBTag/DeepFlavour/python/pfDeepFlavour_cff.py
  RecoBTag/TensorFlow/BuildFile.xml
  RecoBTag/TensorFlow/interface/BoostedDoubleSVTagInfoConverter.h
  RecoBTag/TensorFlow/interface/ChargedCandidateConverter.h
  RecoBTag/TensorFlow/interface/JetConverter.h
  RecoBTag/TensorFlow/interface/NeutralCandidateConverter.h
  RecoBTag/TensorFlow/interface/SecondaryVertexConverter.h
  RecoBTag/TensorFlow/interface/ShallowTagInfoConverter.h
  RecoBTag/TensorFlow/interface/TrackInfoBuilder.h
  RecoBTag/TensorFlow/interface/deep_helpers.h
  RecoBTag/TensorFlow/interface/sorting_modules.h
  RecoBTag/TensorFlow/interface/tensor_fillers.h
  RecoBTag/TensorFlow/plugins/BuildFile.xml
  RecoBTag/TensorFlow/plugins/DeepDoubleBTFJetTagsProducer.cc
  RecoBTag/TensorFlow/plugins/DeepDoubleBTagInfoProducer.cc
  RecoBTag/TensorFlow/plugins/DeepFlavourTFJetTagsProducer.cc
  RecoBTag/TensorFlow/plugins/DeepFlavourTagInfoProducer.cc
  RecoBTag/TensorFlow/python/pfDeepFlavour_cff.py
  RecoBTag/TensorFlow/python/pfNegativeDeepFlavourJetTags_cfi.py
  RecoBTag/TensorFlow/python/pfNegativeDeepFlavourTagInfos_cfi.py
  RecoBTag/TensorFlow/src/BoostedDoubleSVTagInfoConverter.cc
  RecoBTag/TensorFlow/src/ChargedCandidateConverter.cc
  RecoBTag/TensorFlow/src/JetConverter.cc
  RecoBTag/TensorFlow/src/NeutralCandidateConverter.cc
  RecoBTag/TensorFlow/src/SecondaryVertexConverter.cc
  RecoBTag/TensorFlow/src/ShallowTagInfoConverter.cc
  RecoBTag/TensorFlow/src/TrackInfoBuilder.cc
  RecoBTag/TensorFlow/src/deep_helpers.cc
  RecoBTag/TensorFlow/src/sorting_modules.cc
  RecoBTag/TensorFlow/src/tensor_fillers.cc
  RecoBTag/TensorFlow/test/test_deep_doubleb_cfg.py
  RecoBTag/TensorFlow/test/test_deep_doubleb_cfg_AOD.py
  RecoBTag/TensorFlow/test/test_deep_flavour_cfg.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23419 fix hdrs TrackingTools
  TrackingTools/TrackFitters/interface/DebugHelpers.h
  TrackingTools/TransientTrackingRecHit/interface/SeedingLayerSetsLooper.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23415 Update DataFormats/Math package to disable test
  DataFormats/Math/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23424 Bug fix in IndexIntoFileItrImpl::firstEventEntryThisLumi
  DataFormats/Provenance/src/IndexIntoFile.cc
  DataFormats/Provenance/test/indexIntoFile3_t.cppunit.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23431 added unit test for rootpymva
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/test_PyMVA.cpp
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#23406 fix hdr Utilities/XrdAdaptor
  Utilities/XrdAdaptor/src/XrdSource.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23408 fix hdr TopQuarkAnalysis/TopEventProducers
  TopQuarkAnalysis/TopEventProducers/interface/TtEvtBuilder.h
  TopQuarkAnalysis/TopEventProducers/interface/TtGenEventReco.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#23422 [10.2.X] Cleanup PhysicsTools/PythonAnalysis BuildFile
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#23402 EvtGen access in multiple Pythia guns
  GeneratorInterface/Pythia8Interface/interface/Py8GunBase.h
  GeneratorInterface/Pythia8Interface/plugins/Py8EGun.cc
  GeneratorInterface/Pythia8Interface/plugins/Py8PtGun.cc
  GeneratorInterface/Pythia8Interface/src/Py8GunBase.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#23413 Update DataFormats/DetId package to disable test
  DataFormats/DetId/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23271 Speedup puppi [94X]
  CommonTools/PileupAlgos/interface/PuppiAlgo.h
  CommonTools/PileupAlgos/interface/PuppiCandidate.h
  CommonTools/PileupAlgos/interface/PuppiContainer.h
  CommonTools/PileupAlgos/plugins/PuppiProducer.cc
  CommonTools/PileupAlgos/src/PuppiAlgo.cc
  CommonTools/PileupAlgos/src/PuppiCandidate.cc
  CommonTools/PileupAlgos/src/PuppiContainer.cc
Labels: analysis-pending, backport-ok, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23420 [10.2.X] cleanup HLTrigger/HLTanalyzers BuildFile
  HLTrigger/HLTanalyzers/plugins/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#23267 SiPixelQuality : fix tagging of the stuckTBM channels
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.cc
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.cc
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.h
  CalibTracker/SiPixelQuality/test/step4_ALCAHARVEST.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#23388 Adding 2 data workflows to test 90 m beta* Totem run reconstruction
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#23448 [10.2.X] Add switch to contrain vertex refit to BeamSpot in Alignment PV Validation
  Alignment/OfflineValidation/plugins/PrimaryVertexValidation.cc
  Alignment/OfflineValidation/plugins/PrimaryVertexValidation.h
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexValidation.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexValidationTemplates.py
  Alignment/OfflineValidation/test/PVValidation_TEMPL_cfg.py
  Alignment/OfflineValidation/test/PVValidation_T_cfg.py
  Alignment/OfflineValidation/test/testPVValidation_all_ini_one.ini
  Alignment/OfflineValidation/test/test_all_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23418 DD4Hep: Angular Algorithm
  DetectorDescription/DDCMS/data/cms-mf-geometry.xml
  DetectorDescription/DDCMS/data/cmsMagneticField.xml
  DetectorDescription/DDCMS/plugins/DDAngular.cc
  DetectorDescription/DDCMS/python/cmsMFGeometryXML_cfi.py
  DetectorDescription/DDCMS/test/python/dumpMFGeometry.py
  DetectorDescription/DDCMS/test/python/testMFGeometry.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#23444 fix hdrs in Alignment
  Alignment/LaserAlignment/plugins/RawDataConverter.h
  Alignment/SurveyAnalysis/plugins/SurveyDataConverter.h
  Alignment/SurveyAnalysis/plugins/SurveyInputCSCfromPins.cc
  Alignment/SurveyAnalysis/plugins/SurveyInputCSCfromPins.h
  Alignment/TrackerAlignment/plugins/TrackerSystematicMisalignments.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23447 fix hdr CalibCalorimetry/CastorCalib
  CalibCalorimetry/CastorCalib/plugins/CastorTextCalibrations.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23450 fix hdr Calibration/HcalIsolatedTrackReco
  Calibration/HcalIsolatedTrackReco/src/HITRegionalPixelSeedGenerator.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23462 fix hdr CaloOnlineTools/EcalTools
  CaloOnlineTools/EcalTools/plugins/EcalTPGAnalyzer.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23455 python modernize 2to3 toolfix_getcwdu
  Alignment/MuonAlignmentAlgorithms/scripts/alignCSCRings.py
  Alignment/MuonAlignmentAlgorithms/scripts/createBeamHaloJobs.py
  Alignment/MuonAlignmentAlgorithms/scripts/createCSCRingsJobs.py
  Alignment/MuonAlignmentAlgorithms/scripts/createJobs.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23449 python 2to3 migration tool - fixes.fix_exec
  Alignment/OfflineValidation/python/TkAlAllInOneTool/helperFunctions.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23457 fix hdr CalibTracker/SiPixelGainCalibration
  CalibTracker/SiPixelGainCalibration/plugins/SiPixelCalibDigiProducer.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23407 fix hdr Validation/RecoParticleFlow
  Validation/RecoParticleFlow/plugins/GenJetClosestMatchSelectorDefinition.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23132 Updating MssmHbb and Trigger Btagging Monitor with DeepCSV algo
  DQMOffline/Trigger/python/MssmHbbBtagTriggerMonitor_cfi.py
  DQMOffline/Trigger/python/MssmHbbMonitoring_cff.py
  DQMOffline/Trigger/python/MssmHbbMonitoring_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23468 PR emtf report summary map
  DQM/Integration/python/config/fileinputsource_cfi.py
  DQM/L1TMonitorClient/src/L1TEMTFEventInfoClient.cc
Labels: backport, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23416 Temporarily revert "Adapt @express sequence for T0"
  DQMOffline/Configuration/python/autoDQM.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23437 Add filter to count pixel tracks for beta star 90m run
  HLTrigger/special/plugins/HLTPixelTrackFilter.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#23440 L1T muon DQM upgrades part2
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/L1TMonitor/src/L1TStage2uGMT.cc
  DQM/L1TMonitor/src/L1TStage2uGMTMuon.cc
  DQM/L1TMonitorClient/data/L1TStage2EMTFQualityTests.xml
  DQM/L1TMonitorClient/data/L1TStage2MuonQualityTests.xml
  DQM/L1TMonitorClient/data/L1TStage2MuonQualityTestsCollisions.xml
  DQM/L1TMonitorClient/data/L1TStage2OMTFQualityTests.xml
  DQM/L1TMonitorClient/data/L1TStage2uGMTQualityTests.xml
  DQM/L1TMonitorClient/data/L1TStage2uGTDEQualityTests.xml
  DQM/L1TMonitorClient/python/L1TStage2EmulatorEventInfoClient_cfi.py
  DQM/L1TMonitorClient/python/L1TStage2EmulatorQualityTests_cff.py
  DQM/L1TMonitorClient/python/L1TStage2EventInfoClient_cfi.py
  DQM/L1TMonitorClient/python/L1TStage2MuonQualityTests_cff.py
  DQM/L1TMonitorClient/python/L1TStage2QualityTests_cff.py
  DQM/L1TMonitorClient/python/L1TStage2uGTDEQualityTests_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23263 Significant reduction of memory footprint for 2D templates, etc.
  RecoLocalTracker/SiPixelRecHits/interface/SiPixelTemplate2D.h
  RecoLocalTracker/SiPixelRecHits/interface/SiPixelTemplateReco2D.h
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc
  RecoLocalTracker/SiPixelRecHits/src/SiPixelTemplate.cc
  RecoLocalTracker/SiPixelRecHits/src/SiPixelTemplate2D.cc
  RecoLocalTracker/SiPixelRecHits/src/SiPixelTemplateReco2D.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23303 Phase2-hgx112 Correct Reco geometry of post TDR definition and interface to DIGI+RECO codes
  Configuration/Eras/python/Modifier_phase2_hgcalV9_cff.py
  DataFormats/ForwardDetId/interface/HGCScintillatorDetId.h
  DataFormats/ForwardDetId/src/HGCScintillatorDetId.cc
  Geometry/CaloEventSetup/plugins/CaloGeometryBuilder.cc
  Geometry/CaloTopology/interface/HGCalTopology.h
  Geometry/CaloTopology/src/HGCalTopology.cc
  Geometry/HGCalCommonData/BuildFile.xml
  Geometry/HGCalCommonData/interface/HGCalDDDConstants.h
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
  Geometry/HGCalCommonData/test/HGCalNumberingTester.cc
  Geometry/HGCalGeometry/interface/HGCalGeometry.h
  Geometry/HGCalGeometry/plugins/HGCalGeometryESProducer.cc
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
  Geometry/HGCalGeometry/src/HGCalGeometryLoader.cc
  Geometry/HGCalGeometry/test/HGCalGeometryTester.cc
  Geometry/HGCalGeometry/test/HGCalTestRecHitTool.cc
  Geometry/HGCalGeometry/test/python/testHGCalGeometry_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalRecHitTool_cfg.py
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalImagingAlgo.h
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalRecHitSimpleAlgo.h
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalUncalibRecHitRecWeightsAlgo.h
  RecoLocalCalo/HGCalRecAlgos/interface/RecHitTools.h
  RecoLocalCalo/HGCalRecAlgos/src/ClusterTools.cc
  RecoLocalCalo/HGCalRecAlgos/src/RecHitTools.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitWorkerSimple.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitWorkerSimple.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalUncalibRecHitWorkerWeights.h
  SimCalorimetry/HGCalSimProducers/interface/HGCDigitizer.h
  SimCalorimetry/HGCalSimProducers/python/hgcalDigitizer_cfi.py
  SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc
  SimCalorimetry/HGCalSimProducers/src/HGCDigitizerBase.cc
  SimCalorimetry/HGCalSimProducers/src/HGCHEbackDigitizer.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#23359 Phase2-hgx114 Define a scenario with the new HGCal Geometry
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2023D28Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2023D28_cff.py
  Configuration/Geometry/python/dict2023Geometry.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D28XML_cfi.py
  Geometry/CaloGeometry/interface/CaloGeometry.h
  Geometry/CaloGeometry/src/CaloGeometry.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, tests-approved, upgrade-approved

#23370 fix headers in PhysicsTools/PatAlgos
  PhysicsTools/Heppy/interface/MuScleFitCorrector.h
  PhysicsTools/PatAlgos/plugins/BaseMVAValueMapProducer.cc
  PhysicsTools/PatAlgos/plugins/BaseMVAValueMapProducer.h
  PhysicsTools/PatAlgos/plugins/JetCorrFactorsProducer.h
  PhysicsTools/PatAlgos/plugins/PATJetSelector.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23464 fix hdrs CondCore
  CondCore/AlignmentPlugins/interface/AlignmentPayloadInspectorHelper.h
  CondCore/CondDB/plugins/XMLAuthenticationService.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#23465 fix hdrs DataFormats
  DataFormats/BTauReco/interface/TrackProbabilityTagInfo.h
  DataFormats/GeometryVector/interface/Basic3DVectorLD.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#23479 fix hdrs DQM/TrackingMonitorSource
  DQM/TrackingMonitorSource/interface/StandaloneTrackMonitor.h
  DQM/TrackingMonitorSource/interface/TrackTypeMonitor.h
  DQM/TrackingMonitorSource/interface/WtoLNuSelector.h
  DQM/TrackingMonitorSource/interface/ZtoEEEventSelector.h
  DQM/TrackingMonitorSource/interface/ZtoMMEventSelector.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23386 Hcal DetIds/Digi DataFrames adjustments to be used with cuda
  DataFormats/Common/interface/DataFrame.h
  DataFormats/HcalDetId/interface/HcalDetId.h
  DataFormats/HcalDetId/interface/HcalElectronicsId.h
  DataFormats/HcalDetId/src/HcalDetId.cc
  DataFormats/HcalDetId/src/HcalElectronicsId.cc
  DataFormats/HcalDetId/test/BuildFile.xml
  DataFormats/HcalDetId/test/test_hcal_detid.cu
  DataFormats/HcalDigi/interface/HBHEDataFrame.h
  DataFormats/HcalDigi/interface/HFDataFrame.h
  DataFormats/HcalDigi/interface/HODataFrame.h
  DataFormats/HcalDigi/interface/HcalQIESample.h
  DataFormats/HcalDigi/interface/QIE10DataFrame.h
  DataFormats/HcalDigi/interface/QIE11DataFrame.h
  DataFormats/HcalDigi/src/HBHEDataFrame.cc
  DataFormats/HcalDigi/src/HFDataFrame.cc
  DataFormats/HcalDigi/src/HODataFrame.cc
  DataFormats/HcalDigi/src/HcalQIESample.cc
  DataFormats/HcalDigi/src/QIE10DataFrame.cc
  DataFormats/HcalDigi/src/QIE11DataFrame.cc
  DataFormats/HcalDigi/test/BuildFile.xml
  DataFormats/HcalDigi/test/test_hcal_digi.cu
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#23376 Run2-TB38 Describes the 2018 DESY test beam setup for HGCal
  Geometry/HGCalCommonData/data/TB180/Absorb12/hgcalAbsorber.xml
  Geometry/HGCalCommonData/data/TB180/Absorb16/hgcalAbsorber.xml
  Geometry/HGCalCommonData/data/TB180/Absorb20/hgcalAbsorber.xml
  Geometry/HGCalCommonData/data/TB180/Absorb22/hgcalAbsorber.xml
  Geometry/HGCalCommonData/data/TB180/cms.xml
  Geometry/HGCalCommonData/data/TB180/hgcProdCuts.xml
  Geometry/HGCalCommonData/data/TB180/hgcal.xml
  Geometry/HGCalCommonData/data/TB180/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB180/hgcalEE.xml
  Geometry/HGCalCommonData/data/TB180/hgcalsense.xml
  SimG4CMS/HGCalTestBeam/python/HGCalTB180A12XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB180A16XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB180A20XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB180A22XML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#23421 [10.2.X] Cleanup CondTools/SiStrip BuildFile
  CondTools/SiStrip/plugins/BuildFile.xml
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#23371 Remove OOT photons from 2018 heavy-ion (AA) era
  PhysicsTools/PatAlgos/python/producersLayer1/patCandidates_cff.py
  PhysicsTools/PatAlgos/python/selectionLayer1/selectedPatCandidates_cff.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  RecoEcal/EgammaClusterProducers/python/reducedRecHitsSequence_cff.py
  RecoEgamma/EgammaIsolationAlgos/python/interestingEgammaIsoDetIdsSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/interface/ReducedEGProducer.h
  RecoEgamma/EgammaPhotonProducers/python/reducedEgamma_cfi.py
  RecoEgamma/EgammaPhotonProducers/src/ReducedEGProducer.cc
  RecoLocalCalo/HcalRecProducers/python/HcalHitSelection_cfi.py
  RecoParticleFlow/PFProducer/python/particleFlowEGamma_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23471 Fix the length of the string buffer to accommodate the "new format" of the HCAL DetId
  DQM/HcalCommon/src/HashFunctions.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23484 Fix hdrs dqm services/file io
  DQMServices/FileIO/plugins/DQMFileSaverBase.cc
  DQMServices/FileIO/plugins/DQMFileSaverBase.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23482 fix hdr DQMOffline/RecoB
  DQMOffline/RecoB/src/SimpleMatrix.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23458 [L1T][DQMOffline] CaloJets -> PFJets for L1T Offline DQM
  DQMOffline/L1Trigger/interface/L1TStage2CaloLayer2Offline.h
  DQMOffline/L1Trigger/python/L1TEtSumJetOffline_cfi.py
  DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc
  DQMOffline/L1Trigger/test/runDQMOffline_step1_L1TStage2CaloLayer2_cfg.py
  DQMOffline/L1Trigger/test/runDQMOffline_step2_L1TStage2CaloLayer2_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#23483 adding e-mu btag paths to BTVHLTOfflineSource
  DQMOffline/Trigger/python/BTVHLTOfflineSource_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23432 Prioritize exception from Paths
  FWCore/Concurrency/interface/WaitingTask.h
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/src/StreamSchedule.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23443 Muon reco modification for 2018 heavy ion era
  RecoMuon/MuonIdentification/python/muons1stStep_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23423 [10.2.X] Cleanup CondCore/SiStripPlugins y moving the plugin in plugins directory
  CondCore/SiStripPlugins/BuildFile.xml
  CondCore/SiStripPlugins/plugins/BuildFile.xml
  CondCore/SiStripPlugins/plugins/plugin.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#23463 fix hdrs CommonTools
  CommonTools/PileupAlgos/plugins/PuppiPhoton.cc
  CommonTools/PileupAlgos/plugins/PuppiPhoton.h
  CommonTools/PileupAlgos/plugins/PuppiProducer.cc
  CommonTools/PileupAlgos/plugins/PuppiProducer.h
  CommonTools/UtilAlgos/interface/EtaRangeSelector.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23404 electron reco modifications for 2018 heavy ion era
  RecoEgamma/EgammaElectronProducers/python/ecalDrivenElectronSeedsParameters_cff.py
  RecoEgamma/EgammaElectronProducers/python/gedGsfElectrons_cfi.py
  RecoEgamma/EgammaElectronProducers/python/gsfElectrons_cfi.py
  RecoParticleFlow/PFTracking/plugins/ElectronSeedMerger.cc
  RecoParticleFlow/PFTracking/python/mergedElectronSeeds_cfi.py
  TrackingTools/GsfTracking/python/GsfElectronTracking_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23425 Update L1TdeStage2uGT_cfi.py
  DQM/L1TMonitor/python/L1TdeStage2uGT_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23352 TOTEM Timing detectors: backports for 10_1_X
  CondFormats/CTPPSReadoutObjects/interface/TotemDAQMapping.h
  CondFormats/CTPPSReadoutObjects/plugins/TotemDAQMappingESSourceXML.cc
  CondFormats/CTPPSReadoutObjects/src/TotemDAQMapping.cc
  CondFormats/CTPPSReadoutObjects/xml/mapping_totem_timing_2018.xml
  Configuration/StandardSequences/python/Reconstruction_cff.py
  DataFormats/CTPPSDetId/interface/TotemTimingDetId.h
  DataFormats/CTPPSDetId/src/TotemTimingDetId.cc
  DataFormats/CTPPSDetId/src/classes.h
  DataFormats/CTPPSDetId/src/classes_def.xml
  DataFormats/CTPPSDigi/interface/TotemTimingDigi.h
  DataFormats/CTPPSDigi/interface/TotemTimingEventInfo.h
  DataFormats/CTPPSDigi/src/TotemTimingDigi.cc
  DataFormats/CTPPSDigi/src/TotemTimingEventInfo.cc
  DataFormats/CTPPSDigi/src/classes.h
  DataFormats/CTPPSDigi/src/classes_def.xml
  DataFormats/CTPPSReco/interface/CTPPSDiamondRecHit.h
  DataFormats/CTPPSReco/interface/CTPPSTimingRecHit.h
  DataFormats/CTPPSReco/interface/TotemTimingRecHit.h
  DataFormats/CTPPSReco/src/classes.h
  DataFormats/CTPPSReco/src/classes_def.xml
  EventFilter/CTPPSRawToDigi/interface/RawDataUnpacker.h
  EventFilter/CTPPSRawToDigi/interface/RawToDigiConverter.h
  EventFilter/CTPPSRawToDigi/interface/TotemSampicFrame.h
  EventFilter/CTPPSRawToDigi/interface/VFATFrame.h
  EventFilter/CTPPSRawToDigi/plugins/TotemVFATRawToDigi.cc
  EventFilter/CTPPSRawToDigi/python/ctppsRawToDigi_cff.py
  EventFilter/CTPPSRawToDigi/python/totemTimingRawToDigi_cfi.py
  EventFilter/CTPPSRawToDigi/src/RawDataUnpacker.cc
  EventFilter/CTPPSRawToDigi/src/RawToDigiConverter.cc
  EventFilter/CTPPSRawToDigi/test/TotemVFATFrameAnalyzer.cc
  EventFilter/CTPPSRawToDigi/test/analyze_vfat_frames.py
  EventFilter/CTPPSRawToDigi/test/test_standard_sequence_cfg.py
  EventFilter/CTPPSRawToDigi/test/test_totem_timing_cfg.py
  Geometry/VeryForwardData/data/2016_ctpps_15sigma_margin0/RP_Dist_Beam_Cent.xml
  Geometry/VeryForwardData/data/TotemTiming/TotemTiming_DetectorAssembly.xml
  Geometry/VeryForwardData/data/TotemTiming/TotemTiming_Dist_Beam_Cent.xml
  Geometry/VeryForwardData/data/TotemTiming/TotemTiming_Parameters.xml
  Geometry/VeryForwardData/data/TotemTiming/TotemTiming_Plane.xml
  Geometry/VeryForwardData/data/TotemTiming/TotemTiming_Station.xml
  Geometry/VeryForwardGeometry/python/geometryRPFromDD_2018_cfi.py
  Geometry/VeryForwardGeometry/test/test_geom_cfg.py
  Geometry/VeryForwardGeometryBuilder/interface/CTPPSDDDNames.h
  Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryESModule.cc
  Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryInfo.cc
  Geometry/VeryForwardGeometryBuilder/src/CTPPSGeometry.cc
  Geometry/VeryForwardGeometryBuilder/test/print_geometry_info_cfg.py
  RecoCTPPS/Configuration/python/RecoCTPPS_EventContent_cff.py
  RecoCTPPS/Configuration/python/recoCTPPS_sequences_cff.py
  RecoCTPPS/TotemRPLocal/interface/TotemTimingConversions.h
  RecoCTPPS/TotemRPLocal/interface/TotemTimingRecHitProducerAlgorithm.h
  RecoCTPPS/TotemRPLocal/plugins/TotemTimingRecHitProducer.cc
  RecoCTPPS/TotemRPLocal/python/totemTimingLocalReconstruction_cff.py
  RecoCTPPS/TotemRPLocal/src/TotemTimingConversions.cc
  RecoCTPPS/TotemRPLocal/src/TotemTimingRecHitProducerAlgorithm.cc
  RecoCTPPS/TotemRPLocal/test/totemTiming_reco_cfg.py
Labels: alca-approved, backport-ok, comparison-available, db-approved, fully-signed, geometry-approved, operations-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#23356 CTPPS: strips mapping for 2018
  CondFormats/CTPPSReadoutObjects/xml/mapping_tracking_strip_2018.xml
  EventFilter/CTPPSRawToDigi/python/ctppsRawToDigi_cff.py
Labels: alca-approved, backport-ok, comparison-available, db-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23360 Tracking hgh beta star 2018 (101X backport)
  Configuration/Eras/python/Era_Run2_2018_highBetaStar_cff.py
  Configuration/Eras/python/Modifier_highBetaStar_2018_cff.py
  Configuration/StandardSequences/python/Eras.py
  RecoTracker/IterativeTracking/python/DetachedQuadStep_cff.py
  RecoTracker/IterativeTracking/python/DetachedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/HighPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/InitialStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtQuadStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/MixedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoVertex/PrimaryVertexProducer/python/OfflinePrimaryVertices_cfi.py
  RecoVertex/PrimaryVertexProducer/python/TkClusParameters_cff.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved

#23436 [10.1.X] added using test for rootpymva
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/test_PyMVA.cpp
Labels: analysis-pending, backport-ok, comparison-available, orp-approved, pending-signatures, requires-external, tests-approved

#23506 fix hdrs HLTrigger
  HLTrigger/btau/plugins/HLTDisplacedmumumuVtxProducer.h
  HLTrigger/btau/plugins/HLTmmkFilter.h
  HLTrigger/btau/plugins/HLTmmkkFilter.h
  HLTrigger/btau/plugins/HLTmumutkFilter.h
  HLTrigger/btau/plugins/HLTmumutkVtxProducer.h
  HLTrigger/btau/plugins/HLTmumutktkFilter.h
  HLTrigger/btau/plugins/HLTmumutktkVtxProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#23512 fix hdrs FWCore
  FWCore/SOA/interface/ColumnFillers.h
  FWCore/SOA/interface/ColumnValues.h
  FWCore/SOA/interface/TableExaminerBase.h
  FWCore/TestProcessor/interface/ESProduceEntry.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23062 improving dynamic inefficiency monitoring (backport)
  DQM/SiPixelPhase1Clusters/python/SiPixelPhase1Clusters_cfi.py
  DQM/SiPixelPhase1DeadFEDChannels/python/SiPixelPhase1DeadFEDChannels_cfi.py
  DQM/SiPixelPhase1Digis/python/SiPixelPhase1Digis_cfi.py
  DQM/SiPixelPhase1TrackClusters/python/SiPixelPhase1TrackClusters_cfi.py
  DQM/SiPixelPhase1TrackClusters/src/SiPixelPhase1TrackClusters.cc
Labels: backport, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23090 L1T DQM timing plot upgrades - 101x
  DQM/L1TMonitor/interface/L1TObjectsTiming.h
  DQM/L1TMonitor/interface/L1TStage2uGT.h
  DQM/L1TMonitor/interface/L1TStage2uGTTiming.h
  DQM/L1TMonitor/plugins/SealModule.cc
  DQM/L1TMonitor/python/L1TObjectsTiming_cfi.py
  DQM/L1TMonitor/python/L1TStage2_cff.py
  DQM/L1TMonitor/python/L1TStage2uGTEmul_cfi.py
  DQM/L1TMonitor/python/L1TStage2uGTTiming_cfi.py
  DQM/L1TMonitor/python/L1TStage2uGT_cff.py
  DQM/L1TMonitor/python/L1TStage2uGT_cfi.py
  DQM/L1TMonitor/src/L1TObjectsTiming.cc
  DQM/L1TMonitor/src/L1TStage2uGT.cc
  DQM/L1TMonitor/src/L1TStage2uGTTiming.cc
  DQM/L1TMonitorClient/python/L1TObjectsTimingClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2CaloLayer2Client_cff.py
  DQM/L1TMonitorClient/python/L1TStage2MonitorClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2uGTClient_cff.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23282 Updated cfg file for beampixel application for 2018 run
  DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.cc
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23485 Backport pixel track filter to 101X
  HLTrigger/special/plugins/HLTPixelTrackFilter.cc
Labels: backport-ok, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#23364 10_1_X Backport of #23349, add DataProcessing configurations for 2018 high beta star scenario
  Configuration/DataProcessing/python/Impl/hcalnzsEra_Run2_2018_highBetaStar.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2018_highBetaStar.py
  Configuration/DataProcessing/python/Impl/trackingOnlyEra_Run2_2018_highBetaStar.py
  Configuration/DataProcessing/test/run_CfgTest.sh
Labels: comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#23367 Add Pixel MergedDeadROCOccupancy Maps to TkMap script and FPix panel bug patch (backport to 10_1_X of #23339)
  DQM/SiStripMonitorClient/bin/moduleOccupancyPlots.cc
  DQM/SiStripMonitorClient/data/index_template_TKMap.html
  DQM/SiStripMonitorClient/data/index_template_TKMap_cosmics.html
  DQM/SiStripMonitorClient/scripts/DeadROC_duringRun.py
  DQM/SiStripMonitorClient/scripts/MergeOccDeadROC.py
  DQM/SiStripMonitorClient/scripts/TH2PolyOfflineMaps.py
  DQM/SiStripMonitorClient/scripts/TkMap_script_phase1.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23511 fix hdr L1TriggerConfig/GMTConfigProducers
  L1TriggerConfig/GMTConfigProducers/interface/GTRecordGroup.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#23508 [10.2.X] Build cuda based tests only for amd64
  DataFormats/HcalDetId/test/BuildFile.xml
  DataFormats/HcalDigi/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23469 updated bb4l userhook, modified ev1 to be consistent with latest ...
  GeneratorInterface/Pythia8Interface/doc/README_EmissionVeto1
  GeneratorInterface/Pythia8Interface/plugins/EmissionVetoHook1.cc
  GeneratorInterface/Pythia8Interface/plugins/EmissionVetoHook1.h
  GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.cc
  GeneratorInterface/Pythia8Interface/plugins/PowhegHooksBB4L.h
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/src/Py8InterfaceBase.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#23385 fix headers RecoMuon pkgs
  RecoMuon/L3TrackFinder/src/EtaPhiEstimator.h
  RecoMuon/MuonIdentification/plugins/MuonRefProducer.cc
  RecoMuon/MuonIdentification/plugins/MuonRefProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#23502 [10.2.X][DQM] Remove unused variables to avoid compilation warnings
  DQM/L1TMonitorClient/src/L1TEMTFEventInfoClient.cc
Labels: code-checks-approved, comparison-available, dqm-pending, orp-approved, pending-signatures, tests-approved

#23519 Backport of #23015 to 101X, DQMOffline/Muon fixes
  DQMOffline/Muon/src/EfficiencyAnalyzer.cc
  DQMOffline/Muon/src/MuonRecoAnalyzer.cc
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23342 Run2-hcx177 Small bug fixes in view of Phase2 HCAL
  Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/hcalRecNumbering.xml
  Geometry/HcalCommonData/data/hcalSimNumbering/Eta4/hcalSimNumbering.xml
  Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/hcalSimNumbering.xml
  Geometry/HcalCommonData/src/HcalDDDSimConstants.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#23505 fix headers EventFilter
  EventFilter/CSCTFRawToDigi/src/CSCSPCounters.h
  EventFilter/CSCTFRawToDigi/src/CSCSPTrailer.h
  EventFilter/CSCTFRawToDigi/src/CSCSP_MBblock.h
  EventFilter/CSCTFRawToDigi/src/CSCSP_MEblock.h
  EventFilter/CSCTFRawToDigi/src/CSCSP_SPblock.h
  EventFilter/CTPPSRawToDigi/interface/TotemSampicFrame.h
  EventFilter/DTRawToDigi/plugins/DTDDUUnpacker.cc
  EventFilter/DTRawToDigi/plugins/DTDDUUnpacker.h
  EventFilter/EcalRawToDigi/interface/MatacqRawEvent.h
  EventFilter/RctRawToDigi/src/CTP7Format.hh
  EventFilter/RctRawToDigi/src/RctDataDecoder.hh
  EventFilter/Utilities/plugins/RecoEventOutputModuleForFU.h
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, l1-approved, orp-approved, reconstruction-approved, tests-approved

#23507 update TimePerEvent parameter of relval workflows
  Configuration/PyReleaseValidation/python/MatrixInjector.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#23480 Geant4 sensitive detectors clean-up 6
  SimG4CMS/Calo/interface/CaloHitID.h
  SimG4CMS/Calo/interface/CaloSD.h
  SimG4CMS/Calo/interface/HcalNumberingScheme.h
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Calo/src/HCalSD.cc
  SimG4CMS/Muon/BuildFile.xml
  SimG4CMS/Muon/interface/MuonFrameRotation.h
  SimG4CMS/Muon/interface/MuonGEMFrameRotation.h
  SimG4CMS/Muon/interface/MuonSensitiveDetector.h
  SimG4CMS/Muon/src/MuonEndcapFrameRotation.cc
  SimG4CMS/Muon/src/MuonFrameRotation.cc
  SimG4CMS/Muon/src/MuonGEMFrameRotation.cc
  SimG4CMS/Muon/src/MuonME0FrameRotation.cc
  SimG4CMS/Muon/src/MuonRPCFrameRotation.cc
  SimG4CMS/Muon/src/MuonSensitiveDetector.cc
  SimG4CMS/Tracker/interface/TkAccumulatingSensitiveDetector.h
  SimG4CMS/Tracker/src/FakeFrameRotation.cc
  SimG4CMS/Tracker/src/TkAccumulatingSensitiveDetector.cc
  SimG4CMS/Tracker/src/TrackerFrameRotation.cc
  SimG4Core/SensitiveDetector/BuildFile.xml
  SimG4Core/SensitiveDetector/interface/FrameRotation.h
  SimG4Core/SensitiveDetector/interface/SensitiveDetector.h
  SimG4Core/SensitiveDetector/src/SensitiveDetector.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23481 Additional EMTF plots for Single Muon Quality tracks. Reorganization …
  DQM/L1TMonitor/interface/L1TStage2EMTF.h
  DQM/L1TMonitor/src/L1TStage2EMTF.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23518 fix hdr RecoBTag
  RecoBTag/SecondaryVertex/interface/V0Filter.h
  RecoBTag/SecondaryVertex/src/V0Filter.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23544 Have FileWriteError be an edm::Exception
  FWCore/Utilities/interface/EDMException.h
  FWCore/Utilities/src/EDMException.cc
  Utilities/DCacheAdaptor/src/DCacheFile.cc
  Utilities/DavixAdaptor/src/DavixFile.cc
  Utilities/StorageFactory/src/UnixFile.cc
  Utilities/StorageFactory/src/UnixIOChannel.cc
  Utilities/XrdAdaptor/src/XrdFile.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23541 Add cluster counting split in BPix and FPix to HLTPixelActitivityFilter
  HLTrigger/special/plugins/HLTPixelActivityFilter.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#23538 Fix hdr sim tracker/tracker material analysis
  SimMuon/CSCDigitizer/src/CSCStripElectronicsSim.h
  SimTracker/TrackerMaterialAnalysis/plugins/ListGroups.cc
  SimTracker/TrackerMaterialAnalysis/plugins/ListGroupsMaterialDifference.h
  SimTracker/TrackerMaterialAnalysis/plugins/MaterialAccountingGroup.h
  SimTracker/TrackerMaterialAnalysis/plugins/TrackingMaterialProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23537 fix hdr SimG4Core/GFlash
  SimG4Core/GFlash/interface/GflashG4Watcher.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23536 fix hdr SimGeneral/MixingModule
  SimGeneral/MixingModule/plugins/TestMixedSource.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23534 fix hdrs TopQuarkAnalysis/TopJetCombination
  TopQuarkAnalysis/TopJetCombination/plugins/TtSemiLepJetCombMVATrainer.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#23532 fix hdr PhysicsTools/MVATrainer
  PhysicsTools/MVATrainer/plugins/MLP.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#23526 DD: Fix gcc 8 Warning
  DetectorDescription/RegressionTest/src/DDErrorDetection.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#23520 ged photon modifications for pp_on_AA_2018 era
  RecoEcal/EgammaClusterProducers/python/particleFlowSuperClusterECAL_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23414 Change puppi weight compression
  CommonTools/PileupAlgos/plugins/PuppiProducer.cc
  DataFormats/PatCandidates/interface/PackedCandidate.h
  DataFormats/PatCandidates/src/PackedCandidate.cc
  DataFormats/PatCandidates/src/classes_def_objects.xml
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23523 Fix for AlCaSiStripCalMinBias as discussed on PR #23498
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalMinBiasDQM_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23467 DeepFlavour Negative Tagger + DeepFlavour 10X training
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/TensorFlow/interface/ChargedCandidateConverter.h
  RecoBTag/TensorFlow/interface/SecondaryVertexConverter.h
  RecoBTag/TensorFlow/plugins/DeepFlavourTFJetTagsProducer.cc
  RecoBTag/TensorFlow/plugins/DeepFlavourTagInfoProducer.cc
  RecoBTag/TensorFlow/python/pfNegativeDeepFlavourTagInfos_cfi.py
  RecoBTag/TensorFlow/src/ChargedCandidateConverter.cc
  RecoBTag/TensorFlow/src/SecondaryVertexConverter.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved

#23476 [L1T][DQMOffline] Added PFMetNoMu to L1T Offline DQM
  DQMOffline/L1Trigger/interface/L1TStage2CaloLayer2Offline.h
  DQMOffline/L1Trigger/python/L1TEtSumDiff_cfi.py
  DQMOffline/L1Trigger/python/L1TEtSumEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TEtSumJetOffline_cfi.py
  DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc
  DQMOffline/L1Trigger/test/runDQMOffline_step1_L1TStage2CaloLayer2_cfg.py
  L1Trigger/L1TNtuples/interface/L1TPFMetNoMuProducer.h
  L1Trigger/L1TNtuples/plugins/L1TPFMetNoMuProducer.cc
  L1Trigger/L1TNtuples/python/L1TPFMetNoMuProducer_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#23529 Phase2-hgx116 Update the validation codes in the test area
  Validation/HGCalValidation/test/HGCGeometryCheck.cc
  Validation/HGCalValidation/test/HGCHitValidation.cc
  Validation/HGCalValidation/test/HGCalBHValidation.cc
  Validation/HGCalValidation/test/HGCalRecHitStudy.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23552 fix hdr SimRomanPot/SimFP420
  SimRomanPot/SimFP420/interface/AmplitudeSegmentFP420.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23551 fix hdr DQM/CSCMonitorModule
  DQM/CSCMonitorModule/plugins/CSCDQM_HistoDef.h
  DQM/CSCMonitorModule/plugins/CSCDQM_HistoNames.icc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23550 fix hdr MagneticField/ParametrizedEngine
  MagneticField/ParametrizedEngine/src/BFit3D.cc
  MagneticField/ParametrizedEngine/src/BFit3D_data.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23533 fix hdrs Validation
  Validation/RecoHI/plugins/HitPixelLayersTPSelector.h
  Validation/RecoMuon/plugins/MuonTrackValidatorBase.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23539 L1T DQM Fix filling of wrong BX
  DQM/L1TMonitor/src/L1TObjectsTiming.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23268 SiPixelQuality : fix tagging of the stuckTBM channels
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.cc
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.cc
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.h
  CalibTracker/SiPixelQuality/test/step4_ALCAHARVEST.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
Labels: alca-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#23309 [101X] [L1T][DQMOffline] Fixes for L1T jet DQMOffline
  DQMOffline/L1Trigger/interface/L1TStage2CaloLayer2Offline.h
  DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#23329 SiStripMonitorCluster & SiStripMonitorDigi - Fix the FED digi/cluster plots ranges and error [Backport for 10_1_X of #23307]
  DQM/SiStripMonitorCluster/python/SiStripMonitorCluster_cfi.py
  DQM/SiStripMonitorCluster/src/SiStripMonitorCluster.cc
  DQM/SiStripMonitorDigi/python/SiStripMonitorDigi_cfi.py
  DQM/SiStripMonitorDigi/src/SiStripMonitorDigi.cc
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23378 Backported the Pixel Track Eff PR to 10_1_X
  DQM/SiPixelPhase1TrackEfficiency/BuildFile.xml
  DQM/SiPixelPhase1TrackEfficiency/python/SiPixelPhase1TrackEfficiency_cfi.py
  DQM/SiPixelPhase1TrackEfficiency/src/SiPixelPhase1TrackEfficiency.cc
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23426 Update L1TdeStage2uGT_cfi.py [backport to 10_1_X]
  DQM/L1TMonitor/python/L1TdeStage2uGT_cfi.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23456 [10.1.X] Add switch to contrain vertex refit to BeamSpot in Alignment PV Validation
  Alignment/OfflineValidation/plugins/PrimaryVertexValidation.cc
  Alignment/OfflineValidation/plugins/PrimaryVertexValidation.h
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexValidation.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexValidationTemplates.py
  Alignment/OfflineValidation/test/PVValidation_TEMPL_cfg.py
  Alignment/OfflineValidation/test/PVValidation_T_cfg.py
  Alignment/OfflineValidation/test/testPVValidation_all_ini_one.ini
  Alignment/OfflineValidation/test/test_all_cfg.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#23554 [10.2.X] Bug fixed in SiStripBadComponentInfo
  DQM/SiStripMonitorClient/plugins/SiStripBadComponentInfo.cc
  DQM/SiStripMonitorClient/python/SiStripClientConfig_Tier0_Cosmic_cff.py
  DQM/SiStripMonitorClient/python/SiStripClientConfig_Tier0_HeavyIons_cff.py
  DQM/SiStripMonitorClient/python/SiStripClientConfig_Tier0_cff.py
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23548 Disable [[cms::...]] attributes while building with nvcc
  FWCore/Utilities/interface/thread_safety_macros.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23528 [10.1.X] Fix for ALCARECOSiStripCalMinBiasTrackingDQM as discussed on PR #23498
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalMinBiasDQM_cff.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23563 Fix reading of input parameters for PixelTrackFilter for 90m beta star run
  HLTrigger/special/plugins/HLTPixelTrackFilter.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#23564 Fix reading of input parameters for PixelTrackFilter for 90m beta star run [101X backport]
  HLTrigger/special/plugins/HLTPixelTrackFilter.cc
Labels: backport, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#23452 python 2to3 migration tool fix_basestring
  Alignment/MuonAlignment/python/svgfig.py
  CalibMuon/DTCalibration/python/Workflow/Crabtools/crabConfigParser.py
  Configuration/AlCa/python/GlobalTag.py
  Configuration/PyReleaseValidation/python/relval_machine.py
  Documentation/ReferenceManualScripts/python/BeautifulSoup.py
  FWCore/ParameterSet/python/Types.py
  FWCore/PythonUtilities/python/XML2Python.py
  FWCore/PythonUtilities/scripts/fjr2json.py
  FWCore/Skeletons/python/pkg.py
  FWCore/Skeletons/python/utils.py
  L1Trigger/L1TMuonEndCap/test/unittests/FWLiteAnalyzer.py
  PhysicsTools/HeppyCore/python/analyzers/Matcher.py
  PhysicsTools/HeppyCore/python/framework/chain.py
  PhysicsTools/HeppyCore/python/framework/config.py
  PhysicsTools/PythonAnalysis/python/XML2Python.py
  RecoHI/HiEgammaAlgos/python/HiHelperTools.py
  RecoLuminosity/LumiDB/python/CommonUtil.py
  RecoLuminosity/LumiDB/python/lumiQueryAPI.py
  SimTracker/TrackerMaterialAnalysis/test/tools/material.py
  Utilities/ReleaseScripts/scripts/XML2Python.py
  Validation/RecoTrack/python/plotting/plotting.py
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, core-approved, db-approved, docs-pending, dqm-approved, l1-approved, orp-approved, pdmv-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#23503 Phase2-hgx115 Adopt validation package to new geometry
  Validation/HGCalValidation/plugins/HGCGeometryClient.cc
  Validation/HGCalValidation/plugins/HGCGeometryValidation.cc
  Validation/HGCalValidation/plugins/HGCalDigiValidation.cc
  Validation/HGCalValidation/plugins/HGCalHitCalibration.cc
  Validation/HGCalValidation/plugins/HGCalHitClient.cc
  Validation/HGCalValidation/plugins/HGCalHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalRecHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalSimHitValidation.cc
  Validation/HGCalValidation/plugins/SimG4HGCalValidation.cc
  Validation/HGCalValidation/python/hgcGeometryValidationV6_cfi.py
  Validation/HGCalValidation/python/hgcGeometryValidationV9_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23556 Reduce copy-paste by making PreMixingSiPixelWorker to use SiPixelDigitizerAlgorithm
  SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py
  SimTracker/SiPixelDigitizer/plugins/PreMixingSiPixelWorker.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23566 Remove positional arguments from PSet.clone()
  FWCore/ParameterSet/python/Types.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23558 Add a LowPU version of the HP Beam Spot workflow for PCL
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdBeamSpotHPLowPU_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdBeamSpotHPLowPU_cff.py
  Configuration/AlCa/python/autoPCL.py
  Configuration/DataProcessing/test/run_CfgTest.sh
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_production.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, code-checks-approved, comparison-pending, operations-approved, orp-approved, pdmv-pending, pending-signatures, tests-approved, upgrade-approved

#23559 Add a LowPU version of the HP Beam Spot workflow for PCL
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdBeamSpotHPLowPU_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdBeamSpotHPLowPU_cff.py
  Configuration/AlCa/python/autoPCL.py
  Configuration/DataProcessing/test/run_CfgTest.sh
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_production.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, backport, comparison-pending, operations-approved, orp-approved, pdmv-pending, pending-signatures, tests-approved, upgrade-approved

#23454 python modernize 2to3 tool fix_filter
  Alignment/MillePedeAlignmentAlgorithm/python/alignmentsetup/SetCondition.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpsvalidate/geometry.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_alisetup.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_create_file_lists.py
  CalibTracker/SiStripDCS/test/MakeTkMaps.py
  CondCore/Utilities/python/CondDBFW/uploads.py
  CondTools/BTau/python/checkBTagCalibrationConsistency.py
  CondTools/BTau/python/dataLoader.py
  CondTools/BTau/python/generateFlavCfromFlavB.py
  Configuration/DataProcessing/python/Impl/AlCa.py
  Configuration/DataProcessing/python/Reco.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  DQM/SiPixelPhase1Common/python/SpecificationBuilder_cfi.py
  DQMServices/FileIO/scripts/dqmMemoryStats.py
  FWCore/GuiBrowsers/python/EnablePSetHistory.py
  FWCore/GuiBrowsers/python/Vispa/Gui/ConnectableWidget.py
  HLTriggerOffline/Btag/python/readConfig.py
  IOMC/RandomEngine/python/RandomServiceHelper.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/createGains.py
  PhysicsTools/Heppy/python/analyzers/objects/VertexAnalyzer.py
  PhysicsTools/Heppy/python/physicsutils/VBF.py
  PhysicsTools/Heppy/python/physicsutils/genutils.py
  PhysicsTools/HeppyCore/python/utils/deltar.py
  PhysicsTools/RooStatsCms/test/testCrabToyMC_summary.py
  RecoLuminosity/LumiDB/python/checkforupdate.py
  RecoLuminosity/LumiDB/scripts/lumiDBFiller.py
  SimMuon/Configuration/python/customizeMuonDigi.py
  Utilities/RelMon/python/directories2html.py
  Utilities/RelMon/python/dirstructure.py
  Utilities/RelMon/python/dqm_interfaces.py
  Utilities/RelMon/python/utils.py
  Utilities/RelMon/scripts/ValidationMatrix.py
  Validation/Configuration/python/autoValidation.py
  Validation/Performance/scripts/cmsPerfPublish.py
  Validation/Performance/scripts/cmsRelvalreport.py
  Validation/Performance/scripts/cmsRelvalreportInput.py
  Validation/RecoTau/Tools/RefreshWebPage.py
  Validation/RecoTau/python/DQMSequences_cfi.py
  Validation/RecoTau/python/DeltaR.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnQCD_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnRealData_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnRealElectronsData_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnRealMuonsData_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZEEFastSim_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZEE_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZMM_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZTTFastSim_cff.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZTT_cff.py
  Validation/RecoTrack/python/TrackValidation_cff.py
  Validation/RecoTrack/python/plotting/ntuplePrintersDiff.py
  Validation/RecoTrack/python/plotting/plotting.py
  Validation/RecoTrack/python/plotting/trackingPlots.py
  Validation/RecoTrack/python/plotting/validation.py
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, core-approved, db-approved, dqm-approved, l1-approved, operations-approved, orp-approved, pdmv-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#23583 Bugfix in pixel detector's cluster charge re-weighting
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23580 Tracker alignment - fix incorrect assumption in data file names
  Alignment/OfflineValidation/python/TkAlAllInOneTool/dataset.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23570 Changed function local static map to be const
  RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23585 fix header DetectorDescription/DDCMS
  DetectorDescription/DDCMS/interface/DDPlugins.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#23553 fix hdr GeneratorInterface/Herwig7Interface
  GeneratorInterface/Herwig7Interface/interface/HepMCTemplate.h
  GeneratorInterface/Herwig7Interface/interface/Herwig7Interface.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#23543 [10.2.X] MC conditions for 2018
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23496 HGCal - Separate layerClusters from MultiClusters producer
  RecoLocalCalo/Configuration/python/RecoLocalCalo_EventContent_cff.py
  RecoLocalCalo/Configuration/python/hgcalLocalReco_cff.py
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalLayerClusterProducer.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalMultiClusterProducer.cc
  RecoLocalCalo/HGCalRecProducers/python/HGCalLocalRecoSequence_cff.py
  RecoLocalCalo/HGCalRecProducers/python/HGCalLocalRecoTestBeamSequence_cff.py
  RecoLocalCalo/HGCalRecProducers/python/hgcalLayerClusters_cff.py
  RecoLocalCalo/HGCalRecProducers/python/hgcalLayerClusters_cfi.pybak
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHGC_cfi.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimDigiReco_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#23524 DQM Phase2: Added a zoomed pT efficiency plot for the L1 tracks
  DQM/SiOuterTracker/python/OuterTrackerMonitorTTCluster_cfi.py
  DQM/SiOuterTracker/python/OuterTrackerMonitorTTStub_cfi.py
  Validation/SiOuterTrackerV/interface/OuterTrackerMonitorTrackingParticles.h
  Validation/SiOuterTrackerV/plugins/OuterTrackerMonitorTrackingParticles.cc
  Validation/SiOuterTrackerV/python/OuterTrackerMonitorTrackingParticles_cfi.py
  Validation/SiOuterTrackerV/src/OuterTrackerMCHarvester.cc
Labels: code-checks-approved, comparison-available, dqm-pending, orp-approved, pending-signatures, tests-approved

#23591 adding displacedStandAlone muon collection to miniaod
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23546 Changed set to vector in PFDisplacedVertexSeed
  DataFormats/ParticleFlowReco/interface/PFDisplacedVertexSeed.h
  DataFormats/ParticleFlowReco/src/PFDisplacedVertexSeed.cc
  DataFormats/ParticleFlowReco/test/BuildFile.xml
  DataFormats/ParticleFlowReco/test/test_catch2_PFDisplacedVertexSeed.cc
  DataFormats/ParticleFlowReco/test/test_catch2_main.cc
  RecoParticleFlow/PFTracking/src/PFDisplacedVertexFinder.cc
  RecoParticleFlow/PFTracking/test/BuildFile.xml
  RecoParticleFlow/PFTracking/test/test_catch2_PFDisplacedVertexProducer.cc
  RecoParticleFlow/PFTracking/test/test_catch2_main.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23603 New ETL geometry with 11 rings based on engineering drawings, add approximate support plate
  Geometry/MTDCommonData/data/CrystalBar/mtd.xml
  Geometry/MTDCommonData/data/CrystalTile/mtd.xml
  Geometry/MTDCommonData/data/etl.xml
  Geometry/MTDCommonData/src/ETLNumberingScheme.cc
  Geometry/MTDSimData/data/CrystalBar/mtdProdCuts.xml
  Geometry/MTDSimData/data/CrystalBar/mtdsens.xml
  Geometry/MTDSimData/data/CrystalTile/mtdProdCuts.xml
  Geometry/MTDSimData/data/CrystalTile/mtdsens.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#23417 SiStrip (un)packer: fixes and support for nonstandard ZS(lite) modes
  Configuration/StandardSequences/python/DigiToRawDM_cff.py
  Configuration/StandardSequences/python/DigiToRaw_Repack_cff.py
  EventFilter/SiStripRawToDigi/interface/SiStripFEDBuffer.h
  EventFilter/SiStripRawToDigi/interface/SiStripFEDBufferComponents.h
  EventFilter/SiStripRawToDigi/interface/SiStripFEDBufferGenerator.h
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRaw.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRaw.h
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRawModule.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRawModule.h
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiModule.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiModule.h
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.h
  EventFilter/SiStripRawToDigi/python/SiStripDigiToRaw_cfi.py
  EventFilter/SiStripRawToDigi/python/test/SiStripDigiAnalyzer_cfg.py
  EventFilter/SiStripRawToDigi/python/test/SiStripFEDRawDataAnalyzer_cfg.py
  EventFilter/SiStripRawToDigi/python/test/Validate_DigiToRawToClusters_cff.py
  EventFilter/SiStripRawToDigi/python/test/Validate_DigiToRawToClusters_cfg.py
  EventFilter/SiStripRawToDigi/python/test/Validate_DigiToRawToDigi_cff.py
  EventFilter/SiStripRawToDigi/python/test/Validate_DigiToRawToDigi_cfg.py
  EventFilter/SiStripRawToDigi/src/SiStripFEDBufferComponents.cc
  EventFilter/SiStripRawToDigi/src/SiStripFEDBufferGenerator.cc
  RecoLocalTracker/SiPixelClusterizer/test/runClusToTracks.py
  SimTracker/SiPixelDigitizer/test/runDigisToTracks.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#23530 GEM realistic digitiser
  SimMuon/GEMDigitizer/interface/GEMSimpleModel.h
  SimMuon/GEMDigitizer/python/muonGEMDigis_cfi.py
  SimMuon/GEMDigitizer/src/GEMSimpleModel.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#23363 Phase1 in FastSim of CMS
  Configuration/Eras/python/Era_Run2_2017_FastSim_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/Eras.py
  FastSimulation/SimplifiedGeometryPropagator/python/TrackerMaterial_cfi.py
  FastSimulation/Tracking/interface/SeedFinderSelector.h
  FastSimulation/Tracking/plugins/TrajectorySeedProducer.cc
  FastSimulation/Tracking/python/DetachedTripletStep_cff.py
  FastSimulation/Tracking/python/InitialStep_cff.py
  FastSimulation/Tracking/python/JetCoreRegionalStep_cff.py
  FastSimulation/Tracking/python/LowPtTripletStep_cff.py
  FastSimulation/Tracking/python/MixedTripletStep_cff.py
  FastSimulation/Tracking/python/PixelLessStep_cff.py
  FastSimulation/Tracking/python/PixelPairStep_cff.py
  FastSimulation/Tracking/python/SeedingMigration.py
  FastSimulation/Tracking/python/TobTecStep_cff.py
  FastSimulation/Tracking/python/TrajectorySeedProducer_cfi.py
  FastSimulation/Tracking/python/hltSeeds_cff.py
  FastSimulation/Tracking/python/iterativeTk_cff.py
  FastSimulation/Tracking/src/SeedFinderSelector.cc
  RecoPixelVertexing/PixelTriplets/interface/CAHitQuadrupletGenerator.h
  RecoPixelVertexing/PixelTriplets/interface/CAHitTripletGenerator.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletEDProducerT.cc
  RecoPixelVertexing/PixelTriplets/src/CACell.h
  RecoPixelVertexing/PixelTriplets/src/CAGraph.h
  RecoPixelVertexing/PixelTriplets/src/CAHitQuadrupletGenerator.cc
  RecoPixelVertexing/PixelTriplets/src/CAHitTripletGenerator.cc
  RecoPixelVertexing/PixelTriplets/src/CellularAutomaton.cc
  RecoPixelVertexing/PixelTriplets/src/CellularAutomaton.h
  RecoTracker/IterativeTracking/python/DetachedQuadStep_cff.py
  RecoTracker/IterativeTracking/python/DetachedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/HighPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/InitialStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtQuadStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/MixedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoTracker/IterativeTracking/python/TobTecStep_cff.py
  RecoTracker/TkHitPairs/interface/LayerHitMapCache.h
  RecoTracker/TkSeedingLayers/interface/SeedingLayerSetsBuilder.h
  RecoTracker/TkSeedingLayers/src/SeedingLayerSetsBuilder.cc
  Validation/Configuration/python/globalValidation_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fastsim-approved, fully-signed, operations-approved, orp-approved, pdmv-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#23610 Correction of a tag name
  CondTools/Ecal/test/EcalIntercalibConstants_O2O_test.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#23586 fix hdr FWCore/SOA
  FWCore/SOA/interface/TableExaminer.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23607 updated express GT for Event Display to v8
  DQM/Integration/python/config/FrontierCondition_GT_autoExpress_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23587 fixing bug which affects selections without electrons
  DQMOffline/Trigger/plugins/TopMonitor.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23578 Add code/configs for monitoring the new HLT_Photon35_TwoProngs35_v* paths
  DQMOffline/Trigger/plugins/HMesonGammaDQM.cc
  DQMOffline/Trigger/plugins/HMesonGammaDQM.h
  DQMOffline/Trigger/plugins/ObjMonitor.cc
  DQMOffline/Trigger/plugins/ObjMonitor.h
  DQMOffline/Trigger/python/HMesonGammaMonitor_Client_cff.py
  DQMOffline/Trigger/python/HMesonGammaMonitor_cff.py
  DQMOffline/Trigger/python/HiggsMonitoring_Client_cff.py
  DQMOffline/Trigger/python/HiggsMonitoring_cff.py
  DQMOffline/Trigger/python/ObjMonitor_cfi.py
  DQMOffline/Trigger/python/VBFMETMonitor_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23590 cleanup static variables in PFResolutionMap.cc
  RecoParticleFlow/PFClusterTools/BuildFile.xml
  RecoParticleFlow/PFClusterTools/src/PFResolutionMap.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23493 [L1T][DQMOffline] Minor adjustments to Jets & energy sums plots
  DQMOffline/L1Trigger/python/L1TCommon.py
  DQMOffline/L1Trigger/python/L1TEtSumEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TJetEfficiency_cfi.py
  DQMOffline/L1Trigger/src/L1TDiffHarvesting.cc
  DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc
  DQMOffline/L1Trigger/test/runDQMOffline_step2_L1TStage2CaloLayer2_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#23568 HCAL MAHI Code optimization to reduce CPU consuming
  RecoLocalCalo/HcalRecAlgos/interface/EigenMatrixTypes.h
  RecoLocalCalo/HcalRecAlgos/interface/MahiFit.h
  RecoLocalCalo/HcalRecAlgos/src/MahiFit.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23569 Fix issues with DTRecHitQuality
  Validation/DTRecHits/plugins/DTRecHitQuality.cc
  Validation/DTRecHits/plugins/DTRecHitQuality.h
  Validation/DTRecHits/plugins/DTSegment2DQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DQuality.h
  Validation/DTRecHits/plugins/DTSegment2DSLPhiQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DSLPhiQuality.h
  Validation/DTRecHits/plugins/DTSegment4DQuality.cc
  Validation/DTRecHits/plugins/DTSegment4DQuality.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23575 Fix issue #23475 in the hlTPixel plugin (LogError from SiPixelPhase1 DQM)
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_TrackCluster_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#23613 Pileup scenario for 2018 using an extrapolation of data to date.
  Configuration/StandardSequences/python/Mixing.py
  SimGeneral/MixingModule/python/mix_2018_25ns_JuneProjectionFull18_PoissonOOTPU_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#23626 Fixes to eliminate warnings from scram b check-headers
  DataFormats/Provenance/interface/IndexIntoFile.h
  FWCore/ParameterSet/interface/AllowedLabelsDescription.h
  FWCore/ParameterSet/interface/ParameterDescription.h
  FWCore/ParameterSet/interface/ParameterDescriptionNode.h
  FWCore/ParameterSet/interface/ParameterSetDescriptionTraits.h
  FWCore/ParameterSet/interface/ParameterWildcard.h
  FWCore/ParameterSet/interface/VParameterSetEntry.h
  FWCore/ParameterSet/src/AllowedLabelsDescription.cc
  FWCore/ParameterSet/src/ParameterSetDescriptionTraits.cc
  FWCore/ParameterSet/src/VParameterSetEntry.cc
  FWCore/Utilities/interface/value_ptr.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#23615 fix testProduceSystematicMisalignment_cfg.py
  Alignment/TrackerAlignment/test/testProduceSystematicMisalignment_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#23611 Handle any trailing white space
  CommonTools/Utils/src/MethodArgumentSetter.h
  CommonTools/Utils/test/testCutParser.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23622 Correction of an ECAL tag name in IB tests
  CondTools/Ecal/test/EcalIntercalibConstants_O2O_test.sh
Labels: comparison-available, db-pending, orp-approved, pending-signatures, tests-approved

#23623 Ignore EDFilters in the reconstruction_step path
  RecoEgamma/ElectronIdentification/plugins/ElectronIdMVABased.cc
  RecoEgamma/ElectronIdentification/python/electronIdMVABased_cfi.py
  RecoParticleFlow/PFProducer/python/particleFlowEGamma_cff.py
  RecoParticleFlow/PFProducer/python/pfGsfElectronCiCSelector_cff.py
  RecoParticleFlow/PFProducer/python/pfGsfElectronMVASelector_cff.py
  RecoParticleFlow/PFProducer/python/pfGsfElectronMVASelector_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#23597 Disable hcalLaserEventFilter occupancy filter
  RecoMET/METFilters/python/hcalLaserEventFilter_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#23625 Sensitive detectors update 7
  SimG4CMS/Forward/interface/BHMNumberingScheme.h
  SimG4CMS/Forward/interface/BHMSD.h
  SimG4CMS/Forward/interface/Bcm1fSD.h
  SimG4CMS/Forward/interface/BscG4Hit.h
  SimG4CMS/Forward/interface/BscG4HitCollection.h
  SimG4CMS/Forward/interface/BscNumberingScheme.h
  SimG4CMS/Forward/interface/BscSD.h
  SimG4CMS/Forward/interface/FastTimerSD.h
  SimG4CMS/Forward/interface/MtdSD.h
  SimG4CMS/Forward/interface/PltSD.h
  SimG4CMS/Forward/interface/TimingSD.h
  SimG4CMS/Forward/interface/TotemRPOrganization.h
  SimG4CMS/Forward/interface/TotemSD.h
  SimG4CMS/Forward/interface/TotemT1Organization.h
  SimG4CMS/Forward/interface/TotemT2OrganizationGem.h
  SimG4CMS/Forward/interface/TotemVDetectorOrganization.h
  SimG4CMS/Forward/src/BHMNumberingScheme.cc
  SimG4CMS/Forward/src/BHMSD.cc
  SimG4CMS/Forward/src/BSCG4Hit.cc
  SimG4CMS/Forward/src/Bcm1fSD.cc
  SimG4CMS/Forward/src/BscNumberingScheme.cc
  SimG4CMS/Forward/src/BscSD.cc
  SimG4CMS/Forward/src/FastTimerSD.cc
  SimG4CMS/Forward/src/MtdSD.cc
  SimG4CMS/Forward/src/PltSD.cc
  SimG4CMS/Forward/src/TimingSD.cc
  SimG4CMS/Forward/src/TotemRPOrganization.cc
  SimG4CMS/Forward/src/TotemSD.cc
  SimG4CMS/Forward/src/TotemT1NumberingScheme.cc
  SimG4CMS/Forward/src/TotemT1Organization.cc
  SimG4CMS/Forward/src/TotemT2OrganizationGem.cc
  SimG4CMS/Forward/src/ZdcSD.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#23257 Update to uGT and CaloLayer2 unpackers to fill object collections from 6 uGT boards
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/CaloCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EGammaUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EGammaUnpacker.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EtSumUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EtSumUnpacker.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTCollections.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/JetUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/JetUnpacker.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/L1TObjectCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/TauUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/TauUnpacker.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#23594 ctpps pixel dqm: add tracks, removed some histograms
  DQM/CTPPS/plugins/CTPPSPixelDQMSource.cc
  DQM/CTPPS/python/ctppsPixelDQMSource_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved
