Repository cms-sw/cmssw, pull requests merged in 2018-02, with the labels that each got.

#22170 make use of external cms_oracleocci_abi_hack
  OnlineDB/Oracle/test/BuildFile.xml
  OnlineDB/Oracle/test/cms_occi_hack.cc
Labels: code-checks-approved, comparison-available, db-pending, orp-pending, pending-signatures, requires-external, tests-approved

#22005 Candidate Seeded option for automated doublet recovery in HLT tracking
  RecoTracker/TkTrackingRegions/plugins/AreaSeededTrackingRegionsBuilder.cc
  RecoTracker/TkTrackingRegions/plugins/AreaSeededTrackingRegionsBuilder.h
  RecoTracker/TkTrackingRegions/plugins/PixelInactiveAreaTrackingRegionsSeedingLayersProducer.cc
  RecoTracker/TkTrackingRegions/plugins/TrackingSeedCandidates.cc
  RecoTracker/TkTrackingRegions/plugins/TrackingSeedCandidates.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22082 migrate Validation/DTRecHits DQM sources to concurrent DQM (10.1.x)
  Validation/DTRecHits/plugins/DT2DSegmentClients.cc
  Validation/DTRecHits/plugins/DT2DSegmentClients.h
  Validation/DTRecHits/plugins/DT4DSegmentClients.cc
  Validation/DTRecHits/plugins/DT4DSegmentClients.h
  Validation/DTRecHits/plugins/DTRecHitClients.cc
  Validation/DTRecHits/plugins/DTRecHitClients.h
  Validation/DTRecHits/plugins/DTRecHitQuality.cc
  Validation/DTRecHits/plugins/DTRecHitQuality.h
  Validation/DTRecHits/plugins/DTSegment2DQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DQuality.h
  Validation/DTRecHits/plugins/DTSegment2DSLPhiQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DSLPhiQuality.h
  Validation/DTRecHits/plugins/DTSegment4DQuality.cc
  Validation/DTRecHits/plugins/DTSegment4DQuality.h
  Validation/DTRecHits/plugins/Histograms.h
  Validation/DTRecHits/plugins/SealModule.cc
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22130 [10X][DQM][L1T] Reduce memory consumption of L1T DQM plots
  DQMOffline/L1Trigger/interface/HistDefinition.h
  DQMOffline/L1Trigger/interface/L1TEGammaOffline.h
  DQMOffline/L1Trigger/interface/L1TStage2CaloLayer2Offline.h
  DQMOffline/L1Trigger/interface/L1TTauOffline.h
  DQMOffline/L1Trigger/python/L1TEGammaOffline_cfi.py
  DQMOffline/L1Trigger/python/L1THistDefinitions_cff.py
  DQMOffline/L1Trigger/python/L1TStage2CaloLayer2Offline_cfi.py
  DQMOffline/L1Trigger/python/L1TTauOffline_cfi.py
  DQMOffline/L1Trigger/src/HistDefinition.cc
  DQMOffline/L1Trigger/src/L1TEGammaOffline.cc
  DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc
  DQMOffline/L1Trigger/src/L1TTauOffline.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#22009 Instrument cmssw for nvidia nvprof/nvvm (10.1.x)
  HeterogeneousCore/CUDAServices/plugins/BuildFile.xml
  HeterogeneousCore/CUDAServices/plugins/NVProfilerService.cc
Labels: code-checks-approved, comparison-available, new-feature, new-package-pending, orp-approved, pending-signatures, tests-approved

#22166 Fix typo in setting pixel AddNoisyPixels in premixing
  SimGeneral/MixingModule/python/digi_noNoise_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#22171 Fix bug when an exception happens near lumi end
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/test/test_earlyTerminationSignal.sh
  FWCore/Framework/test/test_exceptionInShortLumi_cfg.py
Labels: bug-fix, code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22173 Minor thread related improvements to the framework
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/GlobalSchedule.h
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/src/StreamSchedule.h
  FWCore/Framework/src/Worker.cc
  IOPool/Input/src/RootFile.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#20277 Topic photonvbf trigger
  DQMOffline/Trigger/plugins/ObjMonitor.cc
  DQMOffline/Trigger/plugins/ObjMonitor.h
  DQMOffline/Trigger/python/ExoticaMonitoring_Client_cff.py
  DQMOffline/Trigger/python/PhotonMonitor_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22096 Only HCAL HT versions 0 and 1 should be considered valid
  Geometry/CaloTopology/src/HcalTopology.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#22143 [10.1.X] Add few more CondFormats to Module_2XML to speed up payload dump
  CondCore/Utilities/plugins/Module_2XML.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#21936 Post Muon TDR ME0 geometry cleanup
  Geometry/GEMGeometry/interface/ME0EtaPartition.h
  Geometry/GEMGeometry/src/ME0EtaPartition.cc
  Geometry/GEMGeometry/test/BuildFile.xml
  Geometry/GEMGeometry/test/ME0GeometryAnalyzer.cc
  Geometry/GEMGeometry/test/ME0GeometryAnalyzer10EtaPart.cc
  Geometry/GEMGeometry/test/testGEMGeometry_cfg.py
  Geometry/GEMGeometry/test/testME0Geometry_cfg.py
  Geometry/GEMGeometryBuilder/data/v7/GEMSpecs.xml
  Geometry/GEMGeometryBuilder/plugins/ME0GeometryESModule.cc
  Geometry/GEMGeometryBuilder/plugins/ME0GeometryESModule.h
  Geometry/GEMGeometryBuilder/src/ME0GeometryBuilderFromCondDB.cc
  Geometry/GEMGeometryBuilder/src/ME0GeometryBuilderFromDDD.cc
  Geometry/GEMGeometryBuilder/src/ME0GeometryBuilderFromDDD.h
  Geometry/GEMGeometryBuilder/src/ME0GeometryBuilderFromDDD10EtaPart.cc
  Geometry/GEMGeometryBuilder/src/ME0GeometryBuilderFromDDD10EtaPart.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#22175 use getOraMessage instead of e.getMessage()
  OnlineDB/Oracle/test/test.cpp
Labels: code-checks-approved, comparison-pending, db-pending, orp-pending, pending-signatures, tests-rejected

#22156 Protect against reading invalid prescales
  L1Trigger/L1TGlobal/src/L1TGlobalUtil.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22091 Pass const ref to ALCT and CLCT in CSCMotherboard
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME21.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.h
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME11.h
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME3141.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME3141.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22148 [10.1.X] Fix include of TkHistoMap for geometry comparison tool.
  Alignment/OfflineValidation/python/TkAlAllInOneTool/geometryComparisonTemplates.py
Labels: alca-approved, bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#22113 work around clang-tidy multi-line YAML issues (10.0.x backport)
  .clang-tidy
Labels: backport-ok, bug-fix, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#21947 Instrument cmssw for nvidia nvprof/nvvm (10.0.x)
  HeterogeneousCore/CUDAServices/plugins/BuildFile.xml
  HeterogeneousCore/CUDAServices/plugins/NVProfilerService.cc
Labels: backport, comparison-available, new-package-pending, orp-approved, pending-signatures, tests-approved

#22102 Redefine central CSC LCT BX in CSCCommonTrigger/CSCConstants
  DataFormats/L1TMuon/BuildFile.xml
  DataFormats/L1TMuon/src/EMTFHit.cc
  L1Trigger/CSCCommonTrigger/interface/CSCConstants.h
  L1Trigger/CSCTrackFinder/src/CSCTFDTReceiver.cc
  L1Trigger/CSCTrackFinder/src/CSCTFMuonSorter.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.h
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME21.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.h
  L1Trigger/L1TMuonOverlap/src/OMTFinputMaker.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22160 Adapt RelVal steps and standard RelVal for L1T offline DQM sequences
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_premix.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#22180 CTPPS Geometry Payload Default Label
  Geometry/VeryForwardGeometry/python/geometryRPFromDB_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#22184 L1T object comparison producer for calo objects
  DataFormats/L1Trigger/interface/EGamma.h
  DataFormats/L1Trigger/interface/EtSum.h
  DataFormats/L1Trigger/interface/Jet.h
  DataFormats/L1Trigger/interface/Tau.h
  DataFormats/L1Trigger/src/EGamma.cc
  DataFormats/L1Trigger/src/EtSum.cc
  DataFormats/L1Trigger/src/Jet.cc
  DataFormats/L1Trigger/src/Tau.cc
  DataFormats/L1Trigger/src/classes.h
  DataFormats/L1Trigger/src/classes_def.xml
  L1Trigger/L1TCommon/plugins/L1TComparisonResultFilter.cc
  L1Trigger/L1TCommon/plugins/L1TStage2ObjectComparison.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#21773 Revert making a copy of RefCore in RefVector calls
  DataFormats/Common/interface/RefVector.h
Labels: backport-ok, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22131 Fix reading prescale values during miniAOD production
  PhysicsTools/PatAlgos/python/triggerLayer1/triggerProducer_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, l1-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#22179 Fix comp warnings in Validation/DTRecHits
  Validation/DTRecHits/plugins/DTRecHitQuality.cc
  Validation/DTRecHits/plugins/DTRecHitQuality.h
  Validation/DTRecHits/plugins/DTSegment2DQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DQuality.h
  Validation/DTRecHits/plugins/DTSegment2DSLPhiQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DSLPhiQuality.h
  Validation/DTRecHits/plugins/DTSegment4DQuality.cc
  Validation/DTRecHits/plugins/DTSegment4DQuality.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22188 Initialise extended variables of L1T calo objects
  DataFormats/L1Trigger/interface/EGamma.h
  DataFormats/L1Trigger/interface/Jet.h
  DataFormats/L1Trigger/interface/Tau.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22150 Fix memory access error in HardwareSortingMethods
  L1Trigger/L1TCalorimeter/src/HardwareSortingMethods.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22050 L1T DQM module for BMTF zero suppression monitoring
  DQM/L1TMonitor/python/L1TStage2BMTF_cff.py
  DQM/L1TMonitor/python/L1TStage2_cff.py
  DQM/L1TMonitorClient/python/L1TStage2BMTFClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2MonitorClient_cff.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22052 Dedicated Timing Plots - New Settings for uGT and Eta/Phi Map - L1T & Online DQM - CMSSW - 100X
  DQM/L1TMonitor/interface/L1TObjectsTiming.h
  DQM/L1TMonitor/interface/L1TStage2uGT.h
  DQM/L1TMonitor/plugins/SealModule.cc
  DQM/L1TMonitor/python/L1TObjectsTiming_cfi.py
  DQM/L1TMonitor/python/L1TStage2_cff.py
  DQM/L1TMonitor/python/L1TStage2uGT_cfi.py
  DQM/L1TMonitor/src/L1TObjectsTiming.cc
  DQM/L1TMonitor/src/L1TStage2uGT.cc
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22169 EMTF unpacked muons match uGMT unpacked muons, backport to 10_0_X
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockSP.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFCollections.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFCollections.h
  L1Trigger/L1TMuonEndCap/interface/MicroGMTConverter.h
  L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapTrackProducer.cc
  L1Trigger/L1TMuonEndCap/src/MicroGMTConverter.cc
Labels: backport-ok, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22149 [10.0.X] Fix include of TkHistoMap for geometry comparison tool.
  Alignment/OfflineValidation/python/TkAlAllInOneTool/geometryComparisonTemplates.py
Labels: alca-approved, backport-ok, bug-fix, comparison-available, fully-signed, orp-approved, tests-approved

#22164 [10.1.X] Add Payload Inspector plugins for Tracker Alignment
  CondCore/AlignmentPlugins/interface/AlignmentPayloadInspectorHelper.h
  CondCore/AlignmentPlugins/plugins/BuildFile.xml
  CondCore/AlignmentPlugins/plugins/TrackerAlignmentErrorExtended_PayloadInspector.cc
  CondCore/AlignmentPlugins/plugins/TrackerAlignment_PayloadInspector.cc
  CondCore/AlignmentPlugins/plugins/TrackerSurfaceDeformations_PayloadInspector.cc
  CondCore/AlignmentPlugins/test/BuildFile.xml
  CondCore/AlignmentPlugins/test/testTrackerAlignment.sh
  CondCore/AlignmentPlugins/test/testTrackerAlignmentErrosExtended.sh
  CondCore/AlignmentPlugins/test/testTrackerAlignmentPayloadInspector.cpp
  CondCore/AlignmentPlugins/test/testTrackerSurfaceDeformations.sh
  CondCore/AlignmentPlugins/test/testTrackerSurfaceDeformationsDeltaMap.sh
  CondCore/AlignmentPlugins/test/testingMultiIOV.csh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22142 Fix for O2O execution in CC7
  CondCore/CondDB/interface/Utils.h
  CondTools/RunInfo/test/RunInfoStart_O2O_test.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22098 Dire integration (for internal partons)
  GeneratorInterface/Pythia8Interface/BuildFile.xml
  GeneratorInterface/Pythia8Interface/interface/Py8InterfaceBase.h
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/test/pythia8ex14_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-pending, requires-external, tests-approved

#22076 CondTools/Hcal: change ESProducer return type to unique_ptr.
  CondTools/Hcal/interface/BufferedBoostIOESProducer.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22049 New feature: CSC CLCT pre-trigger digi object in CSC L1 trigger emulator
  DataFormats/CSCDigi/interface/CSCCLCTPreTriggerDigi.h
  DataFormats/CSCDigi/interface/CSCCLCTPreTriggerDigiCollection.h
  DataFormats/CSCDigi/src/CSCCLCTPreTriggerDigi.cc
  DataFormats/CSCDigi/src/classes.h
  DataFormats/CSCDigi/src/classes_def.xml
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/src/CSCTriggerPrimitivesBuilder.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCTriggerPrimitivesBuilder.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved

#21882 [94X GT update][2017 MC] Hcal MCParams update
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#22198 Fix for EcalDAQO2O test
  CondTools/Ecal/test/EcalDAQ_O2O_test.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22095 Add unit tests for SiStrip DAQ and DCS O2O.
  CondTools/SiStrip/python/SiStripDCS_popcon.py
  CondTools/SiStrip/python/SiStripO2O_cfg_template.py
  CondTools/SiStrip/scripts/SiStripDCSPopCon.py
  CondTools/SiStrip/scripts/o2oRun_SiStripDCS.py
  CondTools/SiStrip/test/BuildFile.xml
  CondTools/SiStrip/test/testSiStripDAQO2O.sh
  CondTools/SiStrip/test/testSiStripDCSO2O.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22202 New fastsim geometry fix
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
  FastSimulation/SimplifiedGeometryPropagator/src/HelixTrajectory.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#22192 Fix SimHitsCaloHitsDumper
  SimG4Core/Application/test/SimHitCaloHitDumper.cc
  SimG4Core/Application/test/SimHitCaloHitDumper.h
  SimG4Core/Application/test/runSimHitCaloHitDumper_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#22176 Fix compile warnings in FastSimulation/SimplifiedGeometryPropagator pkg
  FastSimulation/SimplifiedGeometryPropagator/interface/SimplifiedGeometry.h
  FastSimulation/SimplifiedGeometryPropagator/interface/Trajectory.h
  FastSimulation/SimplifiedGeometryPropagator/src/Trajectory.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#22229 Fireworks 10_1: Fix crash on geometry load
  Fireworks/Core/src/FWGeometry.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#21941 Puppi weighted multiplicities, 94X backport
  PhysicsTools/PatAlgos/plugins/PATPuppiJetSpecificsProducer.cc
  PhysicsTools/PatAlgos/test/patTuple_updateJets_fromMiniAOD_cfg.py
Labels: analysis-pending, backport-ok, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#21929 Backport updated python AI pkgs tests
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/imports.sh
  PhysicsTools/PythonAnalysis/test/testDownhill.sh
  PhysicsTools/PythonAnalysis/test/testTheano.py
  PhysicsTools/PythonAnalysis/test/testTheano.sh
  PhysicsTools/PythonAnalysis/test/testhep_ml.sh
Labels: analysis-pending, comparison-available, orp-approved, pending-signatures, tests-approved

#22118 Vincia shower weights for uncertainty bands
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/test/pythia8ex13_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#22199 Migrate Validation/DTRecHit clients to DQMEDHarvester + update efficiency plots
  Validation/DTRecHits/plugins/BuildFile.xml
  Validation/DTRecHits/plugins/DT2DSegmentClients.cc
  Validation/DTRecHits/plugins/DT2DSegmentClients.h
  Validation/DTRecHits/plugins/DT4DSegmentClients.cc
  Validation/DTRecHits/plugins/DT4DSegmentClients.h
  Validation/DTRecHits/plugins/DTRecHitClients.cc
  Validation/DTRecHits/plugins/DTRecHitClients.h
  Validation/DTRecHits/plugins/DTRecHitQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DSLPhiQuality.cc
  Validation/DTRecHits/plugins/DTSegment4DQuality.cc
  Validation/DTRecHits/plugins/Histograms.h
  Validation/DTRecHits/python/DTRecHitClients_cfi.py
  Validation/DTRecHits/python/DTRecHitQuality_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22225 Add ActivityRegistry signals for writeRun and writeLumi
  FWCore/Framework/interface/Schedule.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/OutputModuleCommunicator.h
  FWCore/Framework/src/OutputModuleCommunicatorT.cc
  FWCore/Framework/src/OutputModuleCommunicatorT.h
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/SubProcess.cc
  FWCore/Framework/test/global_outputmodule_t.cppunit.cc
  FWCore/Framework/test/limited_outputmodule_t.cppunit.cc
  FWCore/Framework/test/one_outputmodule_t.cppunit.cc
  FWCore/Integration/test/unit_test_outputs/testGetBy1.log
  FWCore/Integration/test/unit_test_outputs/testGetBy2.log
  FWCore/Integration/test/unit_test_outputs/testSubProcess.grep2.txt
  FWCore/ServiceRegistry/interface/ActivityRegistry.h
  FWCore/ServiceRegistry/src/ActivityRegistry.cc
  FWCore/Services/plugins/Tracer.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22224 Extend StallMonitor to trace Run and Lumis
  FWCore/Services/plugins/StallMonitor.cc
Labels: code-checks-approved, comparison-pending, core-approved, fully-signed, orp-approved, tests-approved

#22233 Fix RecoTrack/DebugTools BuildFile.xml
  RecoTracker/DebugTools/plugins/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22219 Bug fix: remove empty or undefined methods
  DQM/TrigXMonitor/interface/HLTScalers.h
  DQMOffline/CalibCalo/src/DQMSourcePi0.cc
  DQMOffline/CalibCalo/src/DQMSourcePi0.h
  HLTriggerOffline/Egamma/interface/EmDQMReco.h
  HLTriggerOffline/Egamma/src/EmDQMReco.cc
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22093 Adding capability to write out Ptrs in JetConstituentSelector (Backport of #22092)
  CommonTools/RecoAlgos/plugins/JetConstituentSelector.cc
  DataFormats/PatCandidates/src/classes_def_objects.xml
  DataFormats/PatCandidates/src/classes_objects.h
Labels: analysis-pending, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#22042 Backport to 9_4_X of DeepFlavour and TF API
  DataFormats/BTauReco/interface/ChargedCandidateFeatures.h
  DataFormats/BTauReco/interface/DeepFlavourFeatures.h
  DataFormats/BTauReco/interface/DeepFlavourTagInfo.h
  DataFormats/BTauReco/interface/JetFeatures.h
  DataFormats/BTauReco/interface/NeutralCandidateFeatures.h
  DataFormats/BTauReco/interface/SecondaryVertexFeatures.h
  DataFormats/BTauReco/interface/ShallowTagInfoFeatures.h
  DataFormats/BTauReco/src/classes.h
  DataFormats/BTauReco/src/classes_def.xml
  PhysicsTools/PatAlgos/plugins/PATJetUpdater.cc
  PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cff.py
  PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cfi.py
  PhysicsTools/PatAlgos/python/producersLayer1/jetUpdater_cfi.py
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  PhysicsTools/TensorFlow/BuildFile.xml
  PhysicsTools/TensorFlow/interface/TensorFlow.h
  PhysicsTools/TensorFlow/src/NTSession.cc
  PhysicsTools/TensorFlow/src/NTSession.h
  PhysicsTools/TensorFlow/src/TBBSession.cc
  PhysicsTools/TensorFlow/src/TBBSession.h
  PhysicsTools/TensorFlow/src/TensorFlow.cc
  PhysicsTools/TensorFlow/test/BuildFile.xml
  PhysicsTools/TensorFlow/test/createconstantgraph.py
  PhysicsTools/TensorFlow/test/creategraph.py
  PhysicsTools/TensorFlow/test/readconstantgraph.py
  PhysicsTools/TensorFlow/test/testGraphLoading.cc
  PhysicsTools/TensorFlow/test/testHelloWorld.cc
  PhysicsTools/TensorFlow/test/testLoading.cc
  PhysicsTools/TensorFlow/test/testMetaGraphLoading.cc
  PhysicsTools/TensorFlow/test/testRunner.cpp
  RecoBTag/Combined/python/deepFlavour_cff.py
  RecoBTag/Combined/test/testDeepCSV_cfg.py
  RecoBTag/Configuration/python/RecoBTag_cff.py
  RecoBTag/DeepFlavour/BuildFile.xml
  RecoBTag/DeepFlavour/plugins/BTagConverter.h
  RecoBTag/DeepFlavour/plugins/BuildFile.xml
  RecoBTag/DeepFlavour/plugins/ChargedCandidateConverter.h
  RecoBTag/DeepFlavour/plugins/DeepFlavourTFJetTagsProducer.cc
  RecoBTag/DeepFlavour/plugins/DeepFlavourTagInfoProducer.cc
  RecoBTag/DeepFlavour/plugins/JetConverter.h
  RecoBTag/DeepFlavour/plugins/NeutralCandidateConverter.h
  RecoBTag/DeepFlavour/plugins/SVConverter.h
  RecoBTag/DeepFlavour/plugins/TrackInfoBuilder.h
  RecoBTag/DeepFlavour/plugins/deep_helpers.h
  RecoBTag/DeepFlavour/plugins/sorting_modules.h
  RecoBTag/DeepFlavour/plugins/tensor_fillers.h
  RecoBTag/DeepFlavour/python/pfDeepFlavour_cff.py
  RecoBTag/DeepFlavour/python/pfNegativeDeepFlavourJetTags_cfi.py
  RecoBTag/DeepFlavour/python/pfNegativeDeepFlavourTagInfos_cfi.py
  RecoBTag/DeepFlavour/src/sorting_modules.cc
  RecoBTag/DeepFlavour/test/test_deep_flavour_cfg.py
Labels: analysis-pending, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#22125 Fix dE/dx hit association index (94X)
  PhysicsTools/PatAlgos/plugins/PATIsolatedTrackProducer.cc
Labels: analysis-pending, backport-ok, bug-fix, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#22231 Fix testRandomService.sh unit test
  IOMC/RandomEngine/test/testRandomService.sh
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22239 Reset patTrigger.ReadPrescalesFromFile = True in run2_miniAOD_80XLegacy
  PhysicsTools/PatAlgos/python/triggerLayer1/triggerProducer_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#22058 BMTF ZS Unpacker
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFUnpackerInputs.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFUnpackerOutput.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFUnpackerOutput.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22236 Fixed bug in CTPPSDiamondRecHitProducer
  RecoCTPPS/TotemRPLocal/src/CTPPSDiamondRecHitProducerAlgorithm.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22246 Differentiate non-event transitions in stall graph
  FWCore/Concurrency/bin/edmStreamStallGrapher.py
  FWCore/Services/plugins/StallMonitor.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22208 Fix static issues in HIMultiTrackSelector and TkSeedGenerator packages
  RecoHI/HiTracking/plugins/HIMultiTrackSelector.cc
  RecoTracker/TkSeedGenerator/plugins/MultiHitGeneratorFromChi2.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22105 Rerunning MVA based tauIDs for "run2_miniAOD_94XFall17" and "run2_miniAOD_80XLegacy" eras + one additional fix in boostedTau reconstruction for miniAOD
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/Configuration/python/HPSPFTaus_cff.py
  RecoTauTag/Configuration/python/boostedHPSPFTaus_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#22228 Make functions const in CSCCorrelatedLCTDigi
  DataFormats/CSCDigi/interface/CSCCorrelatedLCTDigi.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#22205 overriding inefficient CalosubdetectorGeometry::present function
  Geometry/EcalAlgo/interface/EcalBarrelGeometry.h
  Geometry/EcalAlgo/interface/EcalEndcapGeometry.h
  Geometry/EcalAlgo/src/EcalBarrelGeometry.cc
  Geometry/EcalAlgo/src/EcalEndcapGeometry.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#21930 Displace-tracking development in heavy ion tracking
  RecoHI/HiTracking/python/HiTracking_cff.py
  RecoHI/HiTracking/python/MergeTrackCollectionsHI_cff.py
  RecoHI/HiTracking/python/hiMixedTripletStep_cff.py
  RecoHI/HiTracking/python/hiPixelLessStep_cff.py
  RecoHI/HiTracking/python/hiTobTecStep_cff.py
  RecoTracker/TkSeedGenerator/python/GlobalSeedsFromPairsWithVertices_cff.py
  RecoTracker/TkTrackingRegions/plugins/GlobalTrackingRegionWithVerticesProducer.h
  RecoTracker/TkTrackingRegions/python/GlobalTrackingRegionWithVertices_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22255 activate 2018DesignPU workflow
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#22256 FullSim GENSIM and FastSim strings update
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#22121 Modifications to HCAL trigger LUTs
  CalibCalorimetry/HcalAlgos/interface/HcalPulseContainmentManager.h
  CalibCalorimetry/HcalAlgos/interface/HcalPulseShapes.h
  CalibCalorimetry/HcalAlgos/src/HcalPulseContainmentManager.cc
  CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
  CalibCalorimetry/HcalTPGAlgos/interface/HcaluLUTTPGCoder.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  CalibCalorimetry/HcalTPGEventSetup/src/HcalTPGCoderULUT.cc
  CalibFormats/HcalObjects/interface/HcalDbRecord.h
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22226 remove all zero pt particles in constituent subtraction used for heavy ion events
  RecoJets/JetProducers/plugins/CSJetProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#22195 Superclusterfbrem_10_0_X-v1
  Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22155 FastSimulation/*: Change return type of ESProducers to unique_ptr.
  FastSimulation/ParticlePropagator/plugins/MagneticFieldMapESProducer.cc
  FastSimulation/ParticlePropagator/plugins/MagneticFieldMapESProducer.h
  FastSimulation/TrackerSetup/plugins/TrackerInteractionGeometryESProducer.cc
  FastSimulation/TrackerSetup/plugins/TrackerInteractionGeometryESProducer.h
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#22249 Remove setting the RefCore streamer where unnecessary
  DataFormats/Common/interface/RefCoreStreamer.h
  DataFormats/Common/src/RefCoreStreamer.cc
  FWCore/FWLite/src/RefStreamer.cc
  FWCore/Services/plugins/InitRootHandlers.cc
  IOPool/Input/src/RootFile.cc
  IOPool/Streamer/src/StreamerInputSource.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22206 overriding inefficient CalosubdetectorGeometry::present function :100X backport
  Geometry/EcalAlgo/interface/EcalBarrelGeometry.h
  Geometry/EcalAlgo/interface/EcalEndcapGeometry.h
  Geometry/EcalAlgo/src/EcalBarrelGeometry.cc
  Geometry/EcalAlgo/src/EcalEndcapGeometry.cc
Labels: comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#22258 Completed test coverage for Ecal O2Os
  CondCore/Utilities/python/popcon2dropbox.py
  CondCore/Utilities/python/popcon2dropbox_job_conf.py
  CondTools/Ecal/python/updateADCToGeV_test.py
  CondTools/Ecal/python/updateIntercali_test.py
  CondTools/Ecal/test/BuildFile.xml
  CondTools/Ecal/test/EcalADCToGeV_update_test.sh
  CondTools/Ecal/test/EcalDCS_O2O_test.sh
  CondTools/Ecal/test/EcalIntercalibConstants_O2O_test.sh
  CondTools/Ecal/test/EcalIntercalib_update_test.sh
  CondTools/Ecal/test/EcalLaser_O2O_test.sh
  CondTools/Ecal/test/EcalTPGBadStripStatus_O2O_test.sh
  CondTools/Ecal/test/EcalTPGCrystalStatus_O2O_test.sh
  CondTools/Ecal/test/EcalTPGFineGrainEBGroup_O2O_test.sh
  CondTools/Ecal/test/EcalTPGFineGrainEBIdMap_O2O_test.sh
  CondTools/Ecal/test/EcalTPGFineGrainStripEE_O2O_test.sh
  CondTools/Ecal/test/EcalTPGFineGrainTowerEE_O2O_test.sh
  CondTools/Ecal/test/EcalTPGLinearizationConst_O2O_test.sh
  CondTools/Ecal/test/EcalTPGLutGroup_O2O_test.sh
  CondTools/Ecal/test/EcalTPGLutIdMap_O2O_test.sh
  CondTools/Ecal/test/EcalTPGPedestals_O2O_test.sh
  CondTools/Ecal/test/EcalTPGPhysicsConst_O2O_test.sh
  CondTools/Ecal/test/EcalTPGSlidingWindow_O2O_test.sh
  CondTools/Ecal/test/EcalTPGSpike_O2O_test.sh
  CondTools/Ecal/test/EcalTPGTowerStatus_O2O_test.sh
  CondTools/Ecal/test/EcalTPGWeightGroup_O2O_test.sh
  CondTools/Ecal/test/EcalTPGWeightIdMap_O2O_test.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22237 Splitting the L1TStage2CaloLayer2DEClient module into two
  DQM/L1TMonitorClient/interface/L1TStage2CaloLayer2DEClient.h
  DQM/L1TMonitorClient/interface/L1TStage2CaloLayer2DEClientSummary.h
  DQM/L1TMonitorClient/python/L1TStage2CaloLayer2DEClientSummary_cfi.py
  DQM/L1TMonitorClient/python/L1TStage2EmulatorMonitorClient_cff.py
  DQM/L1TMonitorClient/src/L1TStage2CaloLayer2DEClient.cc
  DQM/L1TMonitorClient/src/L1TStage2CaloLayer2DEClientSummary.cc
  DQM/L1TMonitorClient/src/SealModule.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22217 DAQ file locking compatibility fix for CC 7.4 (master)
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/src/EvFDaqDirector.cc
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22250 add 2018 HI MC wf 150.0 to the short matrix
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#22248 Run2-hcx171 Add 3 new Det names for HGCal
  DataFormats/DetId/interface/DetId.h
  DataFormats/HcalDetId/src/HcalDetId.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#22238 Fixing SiStripGainsPCLWorker when running on AlCaReco input dataset
  CalibTracker/SiStripChannelGain/interface/APVGainHelpers.h
  CalibTracker/SiStripChannelGain/interface/SiStripGainsPCLWorker.h
  CalibTracker/SiStripChannelGain/plugins/SiStripGainFromCalibTree.cc
  CalibTracker/SiStripChannelGain/src/APVGainHelpers.cc
  CalibTracker/SiStripChannelGain/src/SiStripGainsPCLWorker.cc
  CalibTracker/SiStripChannelGain/test/BuildFile.xml
  CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.cpp
  CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh
  CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO_cfg.py
Labels: alca-approved, bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#22211 L1T offline DQM directory cleanup
  DQMOffline/L1Trigger/interface/L1TStage2CaloLayer2Offline.h
  DQMOffline/L1Trigger/python/L1TEGammaDiff_cfi.py
  DQMOffline/L1Trigger/python/L1TEGammaEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TEGammaOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TEtSumDiff_cfi.py
  DQMOffline/L1Trigger/python/L1TEtSumEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TEtSumJetOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TJetDiff_cfi.py
  DQMOffline/L1Trigger/python/L1TJetEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TMuonDQMEfficiency_cff.py
  DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TTauDiff_cfi.py
  DQMOffline/L1Trigger/python/L1TTauEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TTauOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_SecondStep_cff.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_cff.py
  DQMOffline/L1Trigger/src/L1TEGammaOffline.cc
  DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc
  DQMOffline/L1Trigger/test/runDQMOffline_step1_L1TStage2CaloLayer2_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#22261 pr10_1_X Enbale TrackTriggerAssociatorClustersStubs in L1TrackTrigger sequence
  Configuration/StandardSequences/python/L1TrackTrigger_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved, upgrade-approved

#22227 set serial option for TH1::Fit in BeamSpotProducer
  RecoVertex/BeamSpotProducer/src/BSFitter.cc
  RecoVertex/BeamSpotProducer/src/PVFitter.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22134 Added TkMaps switch whether the map is TH2 or TProfile2D
  CalibTracker/SiStripQuality/plugins/SiStripQualityStatistics.cc
  CalibTracker/SiStripQuality/plugins/SiStripQualityStatistics.h
  DQM/SiStripCommon/interface/TkHistoMap.h
  DQM/SiStripCommon/src/TkHistoMap.cc
  DQM/SiStripCommon/test/plugins/testTkHistoMap.cc
  DQM/SiStripMonitorClient/src/SiStripAnalyser.cc
  DQM/SiStripMonitorClient/src/SiStripTrackerMapCreator.cc
  DQM/SiStripMonitorTrack/interface/SiStripMonitorTrack.h
  DQM/SiStripMonitorTrack/src/SiStripMonitorTrack.cc
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#19560 TOP DQM: muon selections for topSingleMediumDQM_MINIAOD are updated
  DQM/Physics/python/singleTopDQM_cfi.py
  DQM/Physics/python/singleTopDQM_miniAOD_cfi.py
  DQM/Physics/python/topSingleLeptonDQM_cfi.py
  DQM/Physics/python/topSingleLeptonDQM_miniAOD_cfi.py
  DQM/Physics/src/SingleTopTChannelLeptonDQM.cc
  DQM/Physics/src/SingleTopTChannelLeptonDQM.h
  DQM/Physics/src/SingleTopTChannelLeptonDQM_miniAOD.cc
  DQM/Physics/src/SingleTopTChannelLeptonDQM_miniAOD.h
  DQM/Physics/src/TopSingleLeptonDQM.cc
  DQM/Physics/src/TopSingleLeptonDQM.h
  DQM/Physics/src/TopSingleLeptonDQM_miniAOD.cc
  DQM/Physics/src/TopSingleLeptonDQM_miniAOD.h
  DQM/Physics/test/topDQM_production_cfg.py
  DQM/Physics/test/topDQM_production_miniAOD.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22209 Fix for O2O execution in CC7
  CondCore/CondDB/interface/Utils.h
  CondTools/Ecal/test/BuildFile.xml
  CondTools/Ecal/test/EcalDAQ_O2O_test.sh
  CondTools/RunInfo/test/BuildFile.xml
  CondTools/RunInfo/test/RunInfoStart_O2O_test.sh
Labels: comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22267 New muon validation scripts macros
  Validation/RecoMuon/test/README
  Validation/RecoMuon/test/macro/IsoValHistoPublisher.C
  Validation/RecoMuon/test/macro/NewTrackValHistoPublisher.C
  Validation/RecoMuon/test/macro/RecoMuonValHistoPublisher.C
  Validation/RecoMuon/test/macro/RecoValHistoPublisher.C
  Validation/RecoMuon/test/macro/SeedValHistoPublisher.C
  Validation/RecoMuon/test/macro/TrackValHistoPublisher.C
  Validation/RecoMuon/test/macro/new_PlotHelpers.C
  Validation/RecoMuon/test/macro/new_TrackValHistoPublisher.C
  Validation/RecoMuon/test/new_muonReleaseSummary.py
  Validation/RecoMuon/test/new_userparams.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22271 OnlineDQM: uGMT DQM plot improvements CMSLITDPG-466
  DQM/L1TMonitor/interface/L1TStage2uGMT.h
  DQM/L1TMonitor/src/L1TStage2MuonComp.cc
  DQM/L1TMonitor/src/L1TStage2RegionalMuonCandComp.cc
  DQM/L1TMonitor/src/L1TStage2uGMT.cc
  DQM/L1TMonitor/src/L1TStage2uGMTMuon.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22215 DAQ file locking compatibility fix for CC 7.4
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/src/EvFDaqDirector.cc
Labels: comparison-available, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22274 Patch oracle getMessage to getOraMessage in missed files
  OnlineDB/SiStripConfigDb/src/SiStripConfigDb.cc
Labels: comparison-pending, db-pending, orp-pending, pending-signatures, tests-approved

#21794 Migrate MultiTrackValidator to concurrent DQM
  CommonTools/CandAlgos/interface/GenParticleCustomSelector.h
  CommonTools/RecoAlgos/interface/RecoTrackSelectorBase.h
  DQMServices/ClientConfig/interface/DQMGenericClient.h
  DQMServices/ClientConfig/plugins/DQMGenericClient.cc
  SimTracker/Common/interface/TrackingParticleSelector.h
  Validation/RecoTrack/interface/MTVHistoProducerAlgoForTracker.h
  Validation/RecoTrack/interface/MultiTrackValidator.h
  Validation/RecoTrack/interface/MultiTrackValidatorGenPs.h
  Validation/RecoTrack/plugins/MultiTrackValidator.cc
  Validation/RecoTrack/plugins/MultiTrackValidatorGenPs.cc
  Validation/RecoTrack/python/PostProcessorTracker_cfi.py
  Validation/RecoTrack/src/MTVHistoProducerAlgoForTracker.cc
Labels: analysis-pending, code-checks-approved, comparison-available, dqm-approved, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved

#22174 L1Trigger/TrackTrigger: Update return type of produce to unique_ptr.
  L1Trigger/TrackTrigger/interface/TTClusterAlgorithm_neighbor.h
  L1Trigger/TrackTrigger/interface/TTClusterAlgorithm_official.h
  L1Trigger/TrackTrigger/interface/TTStubAlgorithm_cbc3.h
  L1Trigger/TrackTrigger/interface/TTStubAlgorithm_official.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#22191 L1T Fix try/catch improper use in Omtf->Rpc mapping (PR 10_1_X)
  EventFilter/L1TRawToDigi/interface/OmtfLinkMappingRpc.h
  EventFilter/L1TRawToDigi/src/OmtfLinkMappingRpc.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22183 Modify the track type to allow for L2 muons to pass through
  RecoMuon/L3MuonProducer/src/L3MuonCandidateProducerFromMuons.cc
Labels: code-checks-approved, comparison-pending, hlt-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#22218 Migrate DQMEDAnalyzers from `stream` to `one` modules
  DQMServices/Core/interface/DQMEDAnalyzer.h
  DQMServices/Core/interface/DQMStore.h
  DQMServices/Core/interface/Standalone.h
  DQMServices/Core/src/DQMEDAnalyzer.cc
  DQMServices/Core/src/DQMStore.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22251 Removing SiStripDetIds dependencies on SiStripTKNumbers. Replacing Si…
  DPGAnalysis/SiStripTools/interface/SiStripTKNumbers.h
  DPGAnalysis/SiStripTools/src/SiStripTKNumbers.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#22276 Migrate DQM/Phase2OuterTracker to DQMEDAnalyzer
  DQM/Phase2OuterTracker/interface/OuterTrackerMonitorTTClusterClient.h
  DQM/Phase2OuterTracker/interface/OuterTrackerMonitorTTStubClient.h
  DQM/Phase2OuterTracker/interface/OuterTrackerMonitorTTTrack.h
  DQM/Phase2OuterTracker/interface/OuterTrackerMonitorTTTrackClient.h
  DQM/Phase2OuterTracker/plugins/OuterTrackerMonitorTTCluster.cc
  DQM/Phase2OuterTracker/plugins/OuterTrackerMonitorTTCluster.h
  DQM/Phase2OuterTracker/plugins/OuterTrackerMonitorTTClusterClient.cc
  DQM/Phase2OuterTracker/plugins/OuterTrackerMonitorTTStub.cc
  DQM/Phase2OuterTracker/plugins/OuterTrackerMonitorTTStub.h
  DQM/Phase2OuterTracker/plugins/OuterTrackerMonitorTTStubClient.cc
  DQM/Phase2OuterTracker/plugins/OuterTrackerMonitorTTTrack.cc
  DQM/Phase2OuterTracker/plugins/OuterTrackerMonitorTTTrackClient.cc
  DQM/Phase2OuterTracker/python/OuterTrackerClientConfig_cff.py
  DQM/Phase2OuterTracker/python/OuterTrackerMonitorTTClusterClient_cfi.py
  DQM/Phase2OuterTracker/python/OuterTrackerMonitorTTStubClient_cfi.py
  DQM/Phase2OuterTracker/python/OuterTrackerMonitorTTTrackClient_cfi.py
  DQM/Phase2OuterTracker/python/OuterTrackerMonitorTTTrack_cfi.py
  DQM/Phase2OuterTracker/python/OuterTrackerSourceConfig_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22268 Sped up call to SiPixelFrameConverter::hasDetUnit
  CondFormats/SiPixelObjects/interface/SiPixelFedCabling.h
  CondFormats/SiPixelObjects/interface/SiPixelFedCablingMap.h
  CondFormats/SiPixelObjects/interface/SiPixelFedCablingTree.h
  CondFormats/SiPixelObjects/src/SiPixelFedCablingMap.cc
  CondFormats/SiPixelObjects/src/SiPixelFedCablingTree.cc
  CondFormats/SiPixelObjects/src/SiPixelFrameConverter.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22059 BMTF ZS Unpacker
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFUnpackerInputs.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFUnpackerOutput.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFUnpackerOutput.h
Labels: backport-ok, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22189 EMTF first PR for quality tests, backport
  DQM/L1TMonitor/src/L1TStage2EMTF.cc
  DQM/L1TMonitorClient/data/L1TStage2EMTFQualityTests.xml
  DQM/L1TMonitorClient/interface/L1TEMTFEventInfoClient.h
  DQM/L1TMonitorClient/python/L1TStage2EMTFEventInfoClient_cfi.py
  DQM/L1TMonitorClient/python/L1TStage2EMTFQualityTests_cfi.py
  DQM/L1TMonitorClient/python/L1TStage2MonitorClient_cff.py
  DQM/L1TMonitorClient/src/L1TEMTFEventInfoClient.cc
  DQM/L1TMonitorClient/src/SealModule.cc
  DQMServices/ClientConfig/interface/QTestConfigure.h
  DQMServices/ClientConfig/src/QTestConfigure.cc
  DQMServices/ClientConfig/test/QT_ContentSigma.xml
  DQMServices/Core/interface/QTest.h
  DQMServices/Core/src/DQMStore.cc
  DQMServices/Core/src/QTest.cc
  DQMServices/Core/test/DQMBackEndInterfaceQTestsExample.cc
  DQMServices/Core/test/DQMMonitorUIRootStandaloneExample.cc
  DQMServices/Core/test/DQMQualityTest.hpp
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22193 Remove hardcoded paths - (backport of PR #22237)
  DQM/L1TMonitorClient/interface/L1TStage2CaloLayer2DEClient.h
  DQM/L1TMonitorClient/interface/L1TStage2CaloLayer2DEClientSummary.h
  DQM/L1TMonitorClient/python/L1TStage2CaloLayer2DEClientSummary_cfi.py
  DQM/L1TMonitorClient/python/L1TStage2EmulatorMonitorClient_cff.py
  DQM/L1TMonitorClient/src/L1TStage2CaloLayer2DEClient.cc
  DQM/L1TMonitorClient/src/L1TStage2CaloLayer2DEClientSummary.cc
  DQM/L1TMonitorClient/src/SealModule.cc
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22196 Backport of Candidate Seeded Pixel Recovery
  RecoTracker/TkTrackingRegions/plugins/AreaSeededTrackingRegionsBuilder.cc
  RecoTracker/TkTrackingRegions/plugins/AreaSeededTrackingRegionsBuilder.h
  RecoTracker/TkTrackingRegions/plugins/PixelInactiveAreaTrackingRegionsSeedingLayersProducer.cc
  RecoTracker/TkTrackingRegions/plugins/TrackingSeedCandidates.cc
  RecoTracker/TkTrackingRegions/plugins/TrackingSeedCandidates.h
Labels: comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#21975 2017 Photon ID (cut based +MVA) Electron ID (cut based) implementation
  PhysicsTools/TagAndProbe/src/TagProbePairMaker.cc
  PhysicsTools/TagAndProbe/test/utilities/dumpPileup.py
  RecoEgamma/ElectronIdentification/data/Fall17/effAreaElectrons_cone03_pfNeuHadronsAndPhotons_92X.txt
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleHadronicOverEMEnergyScaledCut.cc
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Fall17_94X_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_tools.py
  RecoEgamma/ElectronIdentification/test/runtests.sh
  RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfChargedHadrons_90percentBased.txt
  RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfChargedHadrons_90percentBased_TrueVtx.txt
  RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfNeutralHadrons_90percentBased.txt
  RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfNeutralHadrons_90percentBased_TrueVtx.txt
  RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfPhotons_90percentBased.txt
  RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfPhotons_90percentBased_TrueVtx.txt
  RecoEgamma/PhotonIdentification/plugins/PhotonIDValueMapProducer.cc
  RecoEgamma/PhotonIdentification/plugins/PhotonMVAEstimatorRunIIFall17.cc
  RecoEgamma/PhotonIdentification/plugins/PhotonMVAEstimatorRunIIFall17.h
  RecoEgamma/PhotonIdentification/python/Identification/cutBasedPhotonID_Fall17_94X_V1_TrueVtx_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/cutBasedPhotonID_Fall17_94X_V1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Fall17_94X_V1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Fall17_94X_V1p1_cff.py
  RecoEgamma/PhotonIdentification/python/PhotonMVAValueMapProducer_cfi.py
  RecoEgamma/PhotonIdentification/test/runtests.sh
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#22235 Enable option for ALCT-centric matching
  DataFormats/CSCDigi/interface/CSCCorrelatedLCTDigi.h
  L1Trigger/CSCTriggerPrimitives/python/cscTriggerPrimitiveDigis_cfi.py
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved

#21802 CPPFDigis dataformat and RPC unpacker
  CondTools/RPC/python/RPCCPPFLinkMapPopConAnalyzer_cfi.py
  DataFormats/L1TMuon/interface/CPPFDigi.h
  DataFormats/L1TMuon/src/CPPFDigi.cc
  DataFormats/L1TMuon/src/classes.h
  DataFormats/L1TMuon/src/classes_def.xml
  DataFormats/RPCDigi/interface/RPCAMCLinkCounters.h
  DataFormats/RPCDigi/interface/RPCAMCLinkCounters.icc
  DataFormats/RPCDigi/src/DataRecord.cc
  DataFormats/RPCDigi/src/RPCAMCLinkCounters.cc
  EventFilter/RPCRawToDigi/interface/RPCAMC13Record.h
  EventFilter/RPCRawToDigi/interface/RPCAMC13Record.icc
  EventFilter/RPCRawToDigi/interface/RPCAMCLinkEvent.h
  EventFilter/RPCRawToDigi/interface/RPCAMCLinkEvents.h
  EventFilter/RPCRawToDigi/interface/RPCAMCRecord.h
  EventFilter/RPCRawToDigi/interface/RPCAMCRecord.icc
  EventFilter/RPCRawToDigi/interface/RPCCPPFRecord.h
  EventFilter/RPCRawToDigi/interface/RPCCPPFRecord.icc
  EventFilter/RPCRawToDigi/interface/RPCMP7Record.h
  EventFilter/RPCRawToDigi/interface/RPCMP7Record.icc
  EventFilter/RPCRawToDigi/plugins/BuildFile.xml
  EventFilter/RPCRawToDigi/plugins/RPCAMCRawToDigi.cc
  EventFilter/RPCRawToDigi/plugins/RPCAMCRawToDigi.h
  EventFilter/RPCRawToDigi/plugins/RPCAMCUnpacker.cc
  EventFilter/RPCRawToDigi/plugins/RPCAMCUnpacker.h
  EventFilter/RPCRawToDigi/plugins/RPCAMCUnpackerFactory.cc
  EventFilter/RPCRawToDigi/plugins/RPCAMCUnpackerFactory.h
  EventFilter/RPCRawToDigi/plugins/RPCCPPFUnpacker.cc
  EventFilter/RPCRawToDigi/plugins/RPCCPPFUnpacker.h
  EventFilter/RPCRawToDigi/plugins/RPCTwinMuxRawToDigi.cc
  EventFilter/RPCRawToDigi/python/RPCCPPFRawToDigi_cff.py
  EventFilter/RPCRawToDigi/python/RPCCPPFRawToDigi_cfi.py
  EventFilter/RPCRawToDigi/python/RPCCPPFRawToDigi_sqlite_cff.py
  EventFilter/RPCRawToDigi/src/RPCAMC13Record.cc
  EventFilter/RPCRawToDigi/src/RPCAMCLinkEvents.cc
  EventFilter/RPCRawToDigi/src/RPCAMCRecord.cc
  EventFilter/RPCRawToDigi/src/RPCCPPFRecord.cc
  EventFilter/RPCRawToDigi/src/RPCMP7Record.cc
  EventFilter/RPCRawToDigi/test/testRPCCPPF_cfg.py
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#22262 Hcal TP fix ngHE saturation + switch from bare to effective pedestals
  CalibCalorimetry/HcalTPGAlgos/interface/HcaluLUTTPGCoder.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  CaloOnlineTools/HcalOnlineDb/src/WriteL1TriggerObjectsTxt.cc
  SimCalorimetry/HcalTrigPrimAlgos/interface/HcalFeatureHFEMBit.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#22279 Do not fit vertex for single track in PFTauSecondaryVertexProducer
  RecoTauTag/RecoTau/plugins/PFTauSecondaryVertexProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22265 Allow ECAL pfrechit thresholds eta dependent in all regions, disregarding if ZS of FR (10-1-X)
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoParticleFlow/PFClusterProducer/interface/PFRecHitQTests.h
  RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitECAL_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowZeroSuppressionECAL_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#22283 Re-structure visualization client configuration
  DQM/Integration/python/clients/visualization-live-secondInstance_cfg.py
  DQM/Integration/python/clients/visualization-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22245 Run2-alca118 Add a new tool for charge isolation
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksFilter.cc
  Calibration/HcalCalibAlgos/test/HcalIsoTrkAnalyzer.cc
  Calibration/IsolatedParticles/interface/CaloPropagateTrack.h
  Calibration/IsolatedParticles/interface/ChargeIsolation.h
  Calibration/IsolatedParticles/interface/ChargeIsolationExtra.h
  Calibration/IsolatedParticles/plugins/HcalRaddamMuon.cc
  Calibration/IsolatedParticles/plugins/IsoTrackCalib.cc
  Calibration/IsolatedParticles/plugins/StudyHLT.cc
  Calibration/IsolatedParticles/src/CaloPropagateTrack.cc
  Calibration/IsolatedParticles/src/ChargeIsolation.cc
  Calibration/IsolatedParticles/src/ChargeIsolationExtra.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#22289 Ignore invalid IOVs when determining interval
  FWCore/Framework/src/EventSetupProvider.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22144 [10.0.X] Add few more CondFormats to Module_2XML to speed up payload dump
  CondCore/Utilities/plugins/Module_2XML.cc
Labels: backport-ok, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22284 Re-structure visualization client configuration
  DQM/Integration/python/clients/visualization-live-secondInstance_cfg.py
  DQM/Integration/python/clients/visualization-live_cfg.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22277 Update DQM monitoring code for empty MET problem
  DQMOffline/Trigger/python/METMonitor_cff.py
  DQMOffline/Trigger/python/METMonitor_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#22282 Remove the TIBDetId, TOBDetId, TIDDetId and TECDetId classes
  DQM/SiStripHistoricInfoClient/src/HDQMInspectorConfigSiStrip.cc
  DataFormats/SiStripDetId/doc/SiStripDetId.doc
  DataFormats/SiStripDetId/interface/TECDetId.h
  DataFormats/SiStripDetId/interface/TIBDetId.h
  DataFormats/SiStripDetId/interface/TIDDetId.h
  DataFormats/SiStripDetId/interface/TOBDetId.h
  DataFormats/SiStripDetId/src/TECDetId.cc
  DataFormats/SiStripDetId/src/TIBDetId.cc
  DataFormats/SiStripDetId/src/TIDDetId.cc
  DataFormats/SiStripDetId/src/TOBDetId.cc
  DataFormats/SiStripDetId/src/classes.h
  DataFormats/SiStripDetId/src/classes_def.xml
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#22270 Fix undefined behaviour in MixCollection<T>::MixItr
  SimDataFormats/CrossingFrame/interface/MixCollection.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#22313 Created OneLumiPoolSource for testing
  IOPool/Input/src/OneLumiPoolSource.cc
  IOPool/Input/src/PoolSource.h
  IOPool/Input/test/TestPoolInput.sh
  IOPool/Input/test/test_make_multi_lumi_cfg.py
  IOPool/Input/test/test_read_multi_lumi_as_one_cfg.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22286 Fix compilation warning RecoJets/JetAlgorithms
  RecoJets/JetAlgorithms/src/Qjets.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22311 Fix after urgent message from validation campaign
  FastSimulation/SimplifiedGeometryPropagator/interface/BarrelSimplifiedGeometry.h
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#22314 Add fix for different indexing convention in early uGT prescale columns
  L1Trigger/L1TGlobal/src/L1TGlobalUtil.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22269 HCAL: hardcode conditions update
  CalibCalorimetry/HcalPlugins/python/Hcal_Conditions_forGlobalTag_cff.py
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#22200 re-miniAOD workflows on 94X input datasets
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#22285 Disable multi-thread for ALCAHARVEST
  Configuration/PyReleaseValidation/python/WorkFlowRunner.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#22069 Replace swap_or_assign with move in edm::Wrapper<T> constructor
  DataFormats/Common/interface/DetSetVectorNew.h
  DataFormats/Common/interface/Wrapper.h
  DataFormats/Common/interface/WrapperDetail.h
  DataFormats/Common/test/DetSetNew_t.cpp
  DataFormats/Common/test/Wrapper_t.cpp
  JetMETCorrections/JetCorrector/interface/JetCorrector.h
  RecoPixelVertexing/PixelTriplets/interface/IntermediateHitTriplets.h
  RecoTracker/MeasurementDet/interface/MeasurementTrackerEvent.h
  RecoTracker/MeasurementDet/src/MeasurementTrackerEvent.cc
  RecoTracker/TkHitPairs/interface/IntermediateHitDoublets.h
  RecoTracker/TkHitPairs/interface/LayerHitMapCache.h
  RecoTracker/TkHitPairs/interface/RegionsSeedingHitSets.h
  SimDataFormats/Associations/interface/MuonToTrackingParticleAssociator.h
  SimDataFormats/Associations/interface/TrackToGenParticleAssociator.h
  SimDataFormats/Associations/interface/TrackToTrackingParticleAssociator.h
  SimDataFormats/Associations/interface/VertexToTrackingVertexAssociator.h
  SimDataFormats/Associations/src/MuonToTrackingParticleAssociator.cc
  SimDataFormats/Associations/src/TrackToGenParticleAssociator.cc
  SimDataFormats/Associations/src/TrackToTrackingParticleAssociator.cc
  SimDataFormats/Associations/src/VertexToTrackingVertexAssociator.cc
  SimDataFormats/GeneratorProducts/interface/LHEEventProduct.h
Labels: analysis-pending, code-checks-approved, comparison-available, core-approved, generators-approved, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved

#22221 Removing Obsolete Phase2 Tracker (T4) and the corresponding WF (2023D20)
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2023D20Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2023D20_cff.py
  Configuration/Geometry/python/dict2023Geometry.py
  Configuration/PyReleaseValidation/python/relval_2023.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  DetectorDescription/RegressionTest/test/run_DOMCount.sh
  Fireworks/Geometry/python/dumpRecoGeometry_cfg.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D20XML_cfi.py
  Geometry/TrackerCommonData/data/PhaseII/FlatTracker/pixbar.xml
  Geometry/TrackerCommonData/data/PhaseII/FlatTracker/pixel.xml
  Geometry/TrackerCommonData/data/PhaseII/FlatTracker/pixelStructureTopology.xml
  Geometry/TrackerCommonData/data/PhaseII/FlatTracker/pixfwd.xml
  Geometry/TrackerCommonData/data/PhaseII/FlatTracker/tracker.xml
  Geometry/TrackerCommonData/data/PhaseII/FlatTracker/trackerStructureTopology.xml
  Geometry/TrackerCommonData/data/PhaseII/FlatTracker/trackerbar.xml
  Geometry/TrackerCommonData/data/PhaseII/FlatTracker/trackerfwd.xml
  Geometry/TrackerRecoData/data/PhaseII/FlatTracker/trackerRecoMaterial.xml
  Geometry/TrackerSimData/data/PhaseII/FlatTracker/pixelProdCuts.xml
  Geometry/TrackerSimData/data/PhaseII/FlatTracker/pixelsens.xml
  Geometry/TrackerSimData/data/PhaseII/FlatTracker/trackerProdCuts.xml
  Geometry/TrackerSimData/data/PhaseII/FlatTracker/trackersens.xml
  SLHCUpgradeSimulations/Geometry/data/PhaseII/Flat/EmptyPixelSkimmedGeometry.txt
  SLHCUpgradeSimulations/Geometry/python/fakeConditions_phase2TkFlat_cff.py
Labels: code-checks-approved, comparison-available, geometry-approved, operations-approved, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-approved, visualization-pending

#22263 Modifications to HCAL trigger LUTs
  CalibCalorimetry/HcalAlgos/interface/HcalPulseContainmentManager.h
  CalibCalorimetry/HcalAlgos/interface/HcalPulseShapes.h
  CalibCalorimetry/HcalAlgos/src/HcalPulseContainmentManager.cc
  CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
  CalibCalorimetry/HcalTPGAlgos/interface/HcaluLUTTPGCoder.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  CalibCalorimetry/HcalTPGEventSetup/src/HcalTPGCoderULUT.cc
  CalibFormats/HcalObjects/interface/HcalDbRecord.h
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22254 flag to allow the possibility to activate the ZS offline applied to all crystals
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoParticleFlow/PFClusterProducer/interface/PFRecHitQTests.h
  RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitECAL_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowZeroSuppressionECAL_cff.py
Labels: backport-ok, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#22316 HBHE: energy reco
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalCalo/HcalRecAlgos/interface/HcalDeterministicFit.h
  RecoLocalCalo/HcalRecAlgos/interface/HcalSimpleRecAlgo.h
  RecoLocalCalo/HcalRecAlgos/interface/PedestalSub.h
  RecoLocalCalo/HcalRecAlgos/interface/PulseShapeFitOOTPileupCorrection.h
  RecoLocalCalo/HcalRecAlgos/interface/PulseShapeFunctor.h
  RecoLocalCalo/HcalRecAlgos/src/HcalDeterministicFit.cc
  RecoLocalCalo/HcalRecAlgos/src/HcalSimpleRecAlgo.cc
  RecoLocalCalo/HcalRecAlgos/src/HybridMinimizer.cc
  RecoLocalCalo/HcalRecAlgos/src/MahiFit.cc
  RecoLocalCalo/HcalRecAlgos/src/PedestalSub.cc
  RecoLocalCalo/HcalRecAlgos/src/PulseShapeFitOOTPileupCorrection.cc
  RecoLocalCalo/HcalRecAlgos/src/PulseShapeFunctor.cc
  RecoLocalCalo/HcalRecAlgos/src/parseHBHEPhase1AlgoDescription.cc
  RecoLocalCalo/HcalRecProducers/python/HBHEMethod2Parameters_cfi.py
  RecoLocalCalo/HcalRecProducers/python/HBHEMethod3Parameters_cfi.py
  RecoLocalCalo/HcalRecProducers/src/HcalHitReconstructor.cc
Labels: backport-ok, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#22326 Validate top level ParameterSets like options
  FWCore/Framework/bin/cmsRun.cpp
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/ExceptionActions.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/ScheduleItems.cc
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/src/SubProcess.cc
  FWCore/Framework/test/test_dependentRunDataAndException_cfg.py
  FWCore/Framework/test/test_tbb_threads_cfg.py
  FWCore/Integration/test/run_ParameterSet.sh
  FWCore/ParameterSet/bin/edmPluginHelp.cpp
  FWCore/ParameterSet/interface/validateTopLevelParameterSets.h
  FWCore/ParameterSet/src/validateTopLevelParameterSets.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22335 Improve message for duplicate branch name exception
  DataFormats/Provenance/src/ProductRegistry.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#22299 Complete integration of HP beamspot workflow for PCL
  Calibration/TkAlCaRecoProducers/plugins/AlcaBeamSpotHarvester.cc
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdBeamSpotHP_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdBeamSpotHP_cff.py
  Calibration/TkAlCaRecoProducers/python/AlcaBeamSpotProducerHP_cff.py
  Calibration/TkAlCaRecoProducers/python/AlcaBeamSpotProducerHP_cfi.py
  Configuration/AlCa/python/autoPCL.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2017_trackingOnly.py
  Configuration/DataProcessing/python/Impl/trackingOnly.py
  Configuration/DataProcessing/python/Impl/trackingOnlyEra_Run2_2017.py
  Configuration/DataProcessing/python/Impl/trackingOnlyEra_Run2_2018.py
  Configuration/DataProcessing/test/run_CfgTest.sh
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#22306 Run2-sim23 Provide 2018 geometry with no SD declaration
  Configuration/Geometry/python/GeometryExtended2018NoSD_cff.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2018NoSDXML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#22325 EMTF unpacked single-LCT muons match uGMT
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockSP.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22210 Customize premixing stage1 and parts of stage2 with modifiers, and extend Modifier boolean expressions to include "not" and "or"
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/Applications/python/cmsDriverOptions.py
  Configuration/ProcessModifiers/python/premix_stage1_cff.py
  Configuration/ProcessModifiers/python/premix_stage2_cff.py
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/DataMixerPreMix_cff.py
  Configuration/StandardSequences/python/DigiDMPreMix_cff.py
  Configuration/StandardSequences/python/DigiDM_cff.py
  Configuration/StandardSequences/python/DigiToRawPreMixing_cff.py
  Configuration/StandardSequences/python/DigiToRaw_cff.py
  Configuration/StandardSequences/python/Digi_PreMix_cff.py
  Configuration/StandardSequences/python/Digi_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorPreMix_cff.py
  EventFilter/ESDigiToRaw/python/esDigiToRaw_cfi.py
  EventFilter/SiStripRawToDigi/python/SiStripDigiToRaw_cfi.py
  FWCore/ParameterSet/python/Config.py
  FastSimulation/Configuration/python/DigiAliases_cff.py
  L1Trigger/Configuration/python/L1TDigiToRaw_cff.py
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  SimCalorimetry/Configuration/python/ecalDigiSequence_cff.py
  SimCalorimetry/Configuration/python/hcalDigiSequence_cff.py
  SimCalorimetry/EcalSelectiveReadoutProducers/python/ecalDigis_cfi.py
  SimCalorimetry/EcalSimProducers/python/ecalDigiParameters_cff.py
  SimCalorimetry/EcalSimProducers/python/ecalElectronicsSim_cff.py
  SimCalorimetry/EcalSimProducers/python/esElectronicsSim_cff.py
  SimCalorimetry/HcalSimProducers/python/hcalUnsuppressedDigis_cfi.py
  SimCalorimetry/HcalZeroSuppressionProducers/python/hcalDigisRealistic_cfi.py
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
  SimGeneral/MixingModule/python/SiStripSimParameters_cfi.py
  SimGeneral/MixingModule/python/digi_MixPreMix_cfi.py
  SimGeneral/MixingModule/python/digi_noNoise_cfi.py
  SimGeneral/MixingModule/python/digitizers_cfi.py
  SimGeneral/MixingModule/python/pixelDigitizer_cfi.py
  SimGeneral/MixingModule/python/stripDigitizer_cfi.py
  SimGeneral/PileupInformation/python/AddPileupSummary_cfi.py
  SimMuon/RPCDigitizer/python/muonRPCDigis_cfi.py
  SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py
Labels: code-checks-approved, comparison-available, core-approved, daq-approved, fastsim-approved, fully-signed, l1-approved, operations-approved, orp-approved, pdmv-approved, reconstruction-approved, simulation-approved, tests-rejected, upgrade-approved

#22342 Use edm::ProducerBase in DigiAccumulatorMixModFactory parameters
  FastSimulation/Tracking/plugins/RecoTrackAccumulator.cc
  FastSimulation/Tracking/plugins/RecoTrackAccumulator.h
  SimCalorimetry/CastorSim/plugins/CastorDigiProducer.cc
  SimCalorimetry/CastorSim/plugins/CastorDigiProducer.h
  SimCalorimetry/EcalSimProducers/interface/EcalDigiProducer.h
  SimCalorimetry/EcalSimProducers/interface/EcalTimeDigiProducer.h
  SimCalorimetry/EcalSimProducers/src/EcalDigiProducer.cc
  SimCalorimetry/EcalSimProducers/src/EcalTimeDigiProducer.cc
  SimCalorimetry/EcalTestBeam/interface/EcalTBDigiProducer.h
  SimCalorimetry/EcalTestBeam/src/EcalTBDigiProducer.cc
  SimCalorimetry/HGCalSimProducers/plugins/HGCDigiProducer.cc
  SimCalorimetry/HGCalSimProducers/plugins/HGCDigiProducer.h
  SimCalorimetry/HcalSimProducers/interface/HcalDigiProducer.h
  SimCalorimetry/HcalSimProducers/src/HcalDigiProducer.cc
  SimCalorimetry/HcalTestBeam/interface/HcalTBDigiProducer.h
  SimCalorimetry/HcalTestBeam/src/HcalTBDigiProducer.cc
  SimFastTiming/FastTimingCommon/interface/FTLDigitizer.h
  SimFastTiming/FastTimingCommon/interface/FTLDigitizerBase.h
  SimFastTiming/FastTimingCommon/plugins/FTLDigiProducer.cc
  SimFastTiming/FastTimingCommon/plugins/FTLDigiProducer.h
  SimGeneral/CaloAnalysis/plugins/CaloTruthAccumulator.cc
  SimGeneral/CaloAnalysis/plugins/CaloTruthAccumulator.h
  SimGeneral/MixingModule/interface/DigiAccumulatorMixModFactory.h
  SimGeneral/MixingModule/src/DigiAccumulatorMixModFactory.cc
  SimGeneral/PileupInformation/plugins/PileupVertexAccumulator.cc
  SimGeneral/PileupInformation/plugins/PileupVertexAccumulator.h
  SimGeneral/TrackingAnalysis/plugins/TrackingTruthAccumulator.cc
  SimGeneral/TrackingAnalysis/plugins/TrackingTruthAccumulator.h
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizer.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizer.h
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.h
  SimTracker/SiStripDigitizer/plugins/SiStripDigitizer.cc
  SimTracker/SiStripDigitizer/plugins/SiStripDigitizer.h
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#22352 Do not produce a new payload if low stat
  Calibration/EcalCalibAlgos/interface/ECALpedestalPCLHarvester.h
  Calibration/EcalCalibAlgos/python/ecalPedestalPCLHarvester_cfi.py
  Calibration/EcalCalibAlgos/src/ECALpedestalPCLHarvester.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#22362 add new function getFixedSizeArray to be used with ParameterSet
  FWCore/Integration/test/ProducerWithPSetDesc.cc
  FWCore/ParameterSet/interface/getFixedSizeArray.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-rejected

#22295 92X-tuned electron ID and removing upper bound for Zmass
  DPGAnalysis/Skims/python/ZElectronSkim_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved

#22356 Restore description of DataFormats/FEDRawData
  DataFormats/FEDRawData/doc/FEDRawData.doc
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, tests-approved

#22332 Add fix for different indexing convention in early uGT prescale columns
  L1Trigger/L1TGlobal/src/L1TGlobalUtil.cc
Labels: backport-ok, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#22204 Code for Phase2Pixel Ntuple with Unit Tests (+ cleaning old stuff)
  SLHCUpgradeSimulations/Geometry/test/BuildFile.xml
  SLHCUpgradeSimulations/Geometry/test/MyRad.C
  SLHCUpgradeSimulations/Geometry/test/MyRad.h
  SLHCUpgradeSimulations/Geometry/test/Phase2PixelNtuple.cc
  SLHCUpgradeSimulations/Geometry/test/TPNtuplizer.cc
  SLHCUpgradeSimulations/Geometry/test/TPNtuplizer.h
  SLHCUpgradeSimulations/Geometry/test/phase2_digi_reco_pixelntuple.sh
  SLHCUpgradeSimulations/Geometry/test/phase2_digi_reco_pixelntuple_cfg.py
  SLHCUpgradeSimulations/Geometry/test/testPhase2PixelNtuple.cpp
  SLHCUpgradeSimulations/Geometry/test/writeFile_phase1_cfg.py
  SLHCUpgradeSimulations/Geometry/test/writeFile_phase2_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#22310 Fix bug in candidate seeded mode of AreaSeededTrackingRegionsBuilder
  RecoTracker/TkTrackingRegions/plugins/AreaSeededTrackingRegionsBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#22366 set LD_PRELOAD for oracle unittests
  CondTools/Ecal/test/BuildFile.xml
  CondTools/SiStrip/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#22357 Configure Geant4 physics list to be similar to GeantV
  SimG4Core/PhysicsLists/interface/DummyEMPhysics.h
  SimG4Core/PhysicsLists/plugins/DummyPhysics.cc
  SimG4Core/PhysicsLists/plugins/DummyPhysics.h
  SimG4Core/PhysicsLists/src/DummyEMPhysics.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#22319 Migrate DQMEDAnalyze to producers
  DQM/Phase2OuterTracker/python/OuterTrackerMonitorTTCluster_cfi.py
  DQM/Phase2OuterTracker/python/OuterTrackerMonitorTTStub_cfi.py
  DQMServices/Components/plugins/EDMtoMEConverter.cc
  DQMServices/Components/plugins/EDMtoMEConverter.h
  DQMServices/Components/plugins/MEtoEDMConverter.cc
  DQMServices/Components/plugins/MEtoEDMConverter.h
  DQMServices/Components/python/EDMtoMEConverter_cfi.py
  DQMServices/Core/interface/DQMEDAnalyzer.h
  DQMServices/Core/interface/DQMEDHarvester.h
  DQMServices/Core/interface/DQMStore.h
  DQMServices/Core/interface/Standalone.h
  DQMServices/Core/python/DQMEDAnalyzer.py
  DQMServices/Core/src/DQMEDAnalyzer.cc
  DQMServices/Core/src/DQMEDHarvester.cc
  DQMServices/Core/src/DQMStore.cc
  DQMServices/Examples/src/DQMSourceExample.cc
  DataFormats/Histograms/interface/DQMToken.h
  Validation/RecoTau/python/DQMSequences_cfi.py
Labels: code-checks-approved, comparison-available, core-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#22364 Remove the stream id from the MonitorElement public interface
  DQMServices/Core/interface/MonitorElement.h
  DQMServices/Core/src/DQMStore.cc
  DQMServices/Core/src/MonitorElement.cc
  DQMServices/Core/test/DQMTestMultiThread.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved
