Repository cms-sw/cmssw, pull requests merged in 2018-12, with the labels that each got.

#25346 Fix MTV validation of initialStepPreSplitting tracks
  DataFormats/Provenance/src/classes.h
  DataFormats/Provenance/src/classes_def.xml
  SimTracker/TrackerHitAssociation/BuildFile.xml
  SimTracker/TrackerHitAssociation/interface/ClusterTPAssociation.h
  SimTracker/TrackerHitAssociation/src/ClusterTPAssociation.cc
  Validation/RecoTrack/plugins/MultiTrackValidator.cc
  Validation/RecoTrack/python/TrackValidation_cff.py
  Validation/RecoTrack/python/plotting/trackingPlots.py
  Validation/RecoVertex/python/VertexValidation_cff.py
Labels: code-checks-approved, comparison-available, core-approved, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#25357 Phase 2 Trackers T12 and T13: TBPX Lp GBTs placement study
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2023D36Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2023D36_cff.py
  Configuration/Geometry/python/GeometryExtended2023D37Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2023D37_cff.py
  Configuration/Geometry/python/dict2023Geometry.py
  Configuration/PyReleaseValidation/python/relval_2023.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D36XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D37XML_cfi.py
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025TwentyPercent/tracker.xml
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker460/pixel.xml
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker461/pixel.xml
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker461/pixfwd.xml
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker461/tracker.xml
  Geometry/TrackerRecoData/data/PhaseII/TiltedTracker4025FiftyPercent/trackerRecoMaterial.xml
  Geometry/TrackerRecoData/data/PhaseII/TiltedTracker461/trackerRecoMaterial.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#25358 Run2-alca146 Update the AlCaReco code for IsoTracksProducer
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalIsoTrkNoHLT_cff.py
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalIsoTrk_cff.py
  Calibration/HcalAlCaRecoProducers/python/alcaisotrk_cfi.py
  Calibration/HcalAlCaRecoProducers/python/alcastreamHcalIsotrk_cff.py
  Calibration/HcalAlCaRecoProducers/src/AlCaIsoTracksProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25383 fix TrackTimeValueProducer inputs for premixing
  SimTracker/TrackAssociation/python/trackTimeValueMapProducer_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25373 NanoAOD developments, 29Nov2018 version [104X]
  Configuration/Applications/python/ConfigBuilder.py
  PhysicsTools/NanoAOD/plugins/IsFromLostTrackMapProducer.cc
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/isotracks_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#25388 Updating Phase2 Digitizer configuration for Inner Pixel
  SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25394 edmStreamStallGrapher.py timings only count module Event times
  FWCore/Concurrency/scripts/edmStreamStallGrapher.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25381 Validation/Geometry: CleanUp
  Validation/Geometry/test/runP_BeamPipe_cfg.py
  Validation/Geometry/test/runP_InnerServices_cfg.py
  Validation/Geometry/test/runP_PixBar_cfg.py
  Validation/Geometry/test/runP_PixFwdMinus_cfg.py
  Validation/Geometry/test/runP_PixFwdPlus_cfg.py
  Validation/Geometry/test/runP_TEC_cfg.py
  Validation/Geometry/test/runP_TIB_cfg.py
  Validation/Geometry/test/runP_TIDB_cfg.py
  Validation/Geometry/test/runP_TIDF_cfg.py
  Validation/Geometry/test/runP_TOB_cfg.py
  Validation/Geometry/test/runP_TkStrct_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#25395 Phase2-hgx175 Update documentation of trigger DetId of HGCal and also the mask for trigger type
  DataFormats/ForwardDetId/interface/HGCalTriggerDetId.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25393 FWCore/Framework: fix make_shared_noexcept_false template for macOS
  FWCore/Framework/src/make_shared_noexcept_false.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25399 DD4hep: Add Trd1 Division
  DetectorDescription/DDCMS/macros/cms.fwc
  DetectorDescription/DDCMS/plugins/DDCMSDetElementCreator.cc
  DetectorDescription/DDCMS/plugins/DDDefinitions2Objects.cc
  DetectorDescription/DDCMS/src/DDAlgoArguments.cc
  DetectorDescription/DDCMS/src/DDNamespace.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#25351 LS-aware access to HcalChannelQuality
  Calibration/HcalAlCaRecoProducers/src/AlCaHOCalibProducer.cc
  RecoLocalCalo/HcalRecAlgos/test/HcalRecHitReflagger.cc
  RecoMET/METFilters/plugins/EcalDeadCellDeltaRFilter.cc
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#25378 Run2-TB40 Update TB geometry for June2018 setup
  Geometry/HGCalCommonData/data/TB181/June18/hgcProdCuts.xml
  Geometry/HGCalCommonData/data/TB181/June18/hgcal.xml
  Geometry/HGCalCommonData/data/TB181/June18/hgcalBeam.xml
  Geometry/HGCalCommonData/data/TB181/June18/hgcalEE.xml
  SimG4CMS/HGCalTestBeam/python/HGCalTB181JuneXML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25374 Tracker DQM HI Quality Test tuning and cleaning for Offline and Online
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
  DQM/SiStripMonitorClient/data/sistrip_qualitytest_config_heavyion.xml
  DQM/SiStripMonitorClient/data/sistrip_qualitytest_config_tier0_heavyions.xml
  DQM/SiStripMonitorClient/python/SiStripClientConfig_Tier0_cff.py
  DQM/TrackingMonitorClient/data/tracking_qualitytest_config_heavyion.xml
  DQM/TrackingMonitorClient/data/tracking_qualitytest_config_tier0_heavyions.xml
  DQM/TrackingMonitorClient/python/TrackingClientConfig_Tier0_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25348 Changes in SiPixelPhase1Summary and TrackEfficiencyMonitor_cfi
  DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
  DQM/TrackingMonitor/python/TrackEfficiencyMonitor_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25302 bsunanda:Run2 alca143 A new AlCaReco from Nan for muons at high |ieta|'s
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsolatedBunchFilter.cc
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalHEMuonFilter_Output_cff.py
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalHEMuonFilter_cff.py
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalIsolatedBunchFilter_cff.py
  Calibration/HcalAlCaRecoProducers/python/alcaIsolatedBunchFilter_cfi.py
  Calibration/HcalAlCaRecoProducers/test/AlCaHEMuonFilterProducer_cfg.py
  Configuration/AlCa/python/autoAlca.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreamsHeavyIons_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#25376 Change default DDBvL model to 94X
  RecoBTag/TensorFlow/plugins/DeepDoubleXTFJetTagsProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#25400 Remove std::move call from function return statement for L1TRawToDigi/Block
  EventFilter/L1TRawToDigi/src/Block.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#25405 Fix clang warnings in RecoTracker/MeasurementDet
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerEventProducer.cc
  RecoTracker/MeasurementDet/plugins/TkGluedMeasurementDet.cc
  RecoTracker/MeasurementDet/plugins/TkStripMeasurementDet.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25404 Removed unused variables and functions in RecoLocalCalo/HGCalRecAlgos
  RecoLocalCalo/HGCalRecAlgos/src/ClusterTools.cc
  RecoLocalCalo/HGCalRecAlgos/src/RecHitTools.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#25415 DD4hep: Add Trd2 Shape
  DetectorDescription/DDCMS/data/testLogicalParts.xml
  DetectorDescription/DDCMS/data/testPosParts.xml
  DetectorDescription/DDCMS/data/testSolids.xml
  DetectorDescription/DDCMS/plugins/DDDefinitions2Objects.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#25316 Update anti-e tau discriminant (94X)
  RecoTauTag/RecoTau/interface/AntiElectronIDMVA6.h
  RecoTauTag/RecoTau/plugins/PATTauDiscriminationAgainstElectronMVA6.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationAgainstElectronMVA6.cc
  RecoTauTag/RecoTau/python/PATTauDiscriminationAgainstElectronMVA6_cfi.py
  RecoTauTag/RecoTau/src/AntiElectronIDMVA6.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25406 Forward delcare as class not struct in PhysicsTools/Heppy
  PhysicsTools/Heppy/interface/EGammaMvaEleEstimatorFWLite.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#25421 Do not hold on to empty strings passed to getByLabel
  DataFormats/FWLite/src/DataGetterHelper.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25412 Fix obvious bug in particle boosting (recursive statement)
  GeneratorInterface/GenFilters/src/MCParticlePairFilter.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25420 Do not hold on to empty strings passed to getByLabel [9_4]
  DataFormats/FWLite/src/DataGetterHelper.cc
Labels: backport-ok, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25344 Phase2-hgx174 Bug fixes
  Geometry/HGCalCommonData/src/HGCalGeomTools.cc
  Geometry/HGCalGeometry/interface/HGCalGeometry.h
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#25016 DNN-based Tau-Id discrimians
  RecoTauTag/RecoTau/BuildFile.xml
  RecoTauTag/RecoTau/interface/DeepTauBase.h
  RecoTauTag/RecoTau/plugins/BuildFile.xml
  RecoTauTag/RecoTau/plugins/DPFIsolation.cc
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/python/DPFIsolation_cff.py
  RecoTauTag/RecoTau/python/DeepTauId_cff.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/src/DeepTauBase.cc
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#25360 HCALDQM: Move channel quality lookup to dqmBeginLuminosityBlock (+increase pedestal RMS axis)
  DQM/HcalCommon/interface/DQClient.h
  DQM/HcalCommon/interface/DQHarvester.h
  DQM/HcalCommon/src/DQClient.cc
  DQM/HcalCommon/src/DQHarvester.cc
  DQM/HcalCommon/src/DQTask.cc
  DQM/HcalTasks/plugins/PedestalTask.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25390 Added 2018 PbPb collision vertex smearing parameters
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealisticPbPbCollision2018_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#25430 Fixed broken include guard in L1TMuonBarrelKalmanLUTs
  L1Trigger/L1TMuonBarrel/interface/L1TMuonBarrelKalmanLUTs.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#25418 FWCore: Update StallMonitor service to use microsecond timing
  FWCore/Concurrency/scripts/edmStreamStallGrapher.py
  FWCore/Services/plugins/StallMonitor.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25423 Remove workflow 1325.9 testing NanoAOD on 92X
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#25417 MTD geometry: move topology parameters from PSet to xml, adapt the code
  Configuration/Geometry/python/dict2023Geometry.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D24XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D25XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D33XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D34XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D35XML_cfi.py
  Geometry/MTDCommonData/data/CrystalBar/mtdParameters.xml
  Geometry/MTDCommonData/data/CrystalBarZflat/mtdParameters.xml
  Geometry/MTDCommonData/data/CrystalBarZflatNOhole/mtdParameters.xml
  Geometry/MTDCommonData/data/CrystalTile/mtdParameters.xml
  Geometry/MTDCommonData/interface/MTDTopologyMode.h
  Geometry/MTDCommonData/src/MTDTopologyMode.cc
  Geometry/MTDCommonData/src/MtdTopologyMode.cc
  Geometry/MTDGeometryBuilder/interface/MTDParametersFromDD.h
  Geometry/MTDGeometryBuilder/plugins/MTDParametersESModule.cc
  Geometry/MTDGeometryBuilder/python/mtdParameters_cfi.py
  Geometry/MTDGeometryBuilder/src/MTDParametersFromDD.cc
  Geometry/MTDNumberingBuilder/plugins/MTDTopologyEP.cc
  Geometry/MTDNumberingBuilder/test/MTDTopologyAnalyzer.cc
  Geometry/MTDNumberingBuilder/test/trackerTopology_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#25426 Switching the mode of charge asymmetry evaluation
  RecoLocalCalo/HcalRecProducers/python/HFPhase1Reconstructor_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25359 RECO Geometry: CTPPS DetGeomDesc Cleanup
  Geometry/VeryForwardGeometryBuilder/interface/DetGeomDesc.h
  Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryESModule.cc
  Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryInfo.cc
  Geometry/VeryForwardGeometryBuilder/src/CTPPSGeometry.cc
  Geometry/VeryForwardGeometryBuilder/src/DetGeomDesc.cc
  RecoCTPPS/PixelLocal/src/RPixPlaneCombinatoryTracking.cc
  RecoCTPPS/PixelLocal/src/RPixRoadFinder.cc
  RecoCTPPS/TotemRPLocal/src/CTPPSDiamondRecHitProducerAlgorithm.cc
  RecoCTPPS/TotemRPLocal/src/FastLineRecognition.cc
  RecoCTPPS/TotemRPLocal/src/TotemTimingRecHitProducerAlgorithm.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, reconstruction-approved, tests-approved

#25422 [104X] Change GT. Offline GT Fix ECAL Queues
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25427 Bugfix for cavern
  Geometry/CMSCommonData/data/cavern/2018/v1/cavern.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2018XML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#25429 Fixed clang warnings in L1Trigger/L1THGCal
  L1Trigger/L1THGCal/interface/HGCalTriggerTowerGeometryHelper.h
  L1Trigger/L1THGCal/src/HGCalTriggerTools.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#25438 Added extra Physics Lists for neutron background study
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_HP_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_HP_EMM.h
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_EMM.h
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_HP_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_HP_EMM.h
  SimG4Core/PhysicsLists/plugins/module.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25397 Validation/Geometry: Add reference plots to Material Budget test
  Validation/Geometry/test/genTrackerPlots.sh
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#25364 Return unique_ptr from fetchPayload
  CondCore/CondDB/interface/Session.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25451 Remove duplicate entry in Geometry/GlobalTrackingGeometryBuilder/test/BuildFile.xml
  Geometry/GlobalTrackingGeometryBuilder/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#25449 Only call consumes in ElectronSeedProducer if actually needed
  RecoEgamma/EgammaElectronProducers/plugins/ElectronSeedProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/ElectronSeedProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25454 Fix clang warnings in TrackingTools/PatternTools
  TrackingTools/PatternTools/src/TwoTrackMinimumDistanceHelixHelix.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25424 Fix obvious bug in particle boosting - backport of PR #25412 in 10.2.X for actual MC generation
  GeneratorInterface/GenFilters/src/MCParticlePairFilter.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25450 fix clang warnings in MuonAnalysis/MomentumScaleCalibration
  MuonAnalysis/MomentumScaleCalibration/plugins/Histograms.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#25443 Define new run2_miniAOD_devel and run2_nanoAOD_102Xv1 modifiers
  Configuration/Eras/python/Modifier_run2_miniAOD_devel_cff.py
  Configuration/Eras/python/Modifier_run2_nanoAOD_102Xv1_cff.py
  Configuration/StandardSequences/python/Eras.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#25401 Sim magnetic field
  SimG4Core/Application/interface/RunManager.h
  SimG4Core/Application/interface/RunManagerMT.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/RunManager.cc
  SimG4Core/Application/src/RunManagerMT.cc
  SimG4Core/MagneticField/interface/CMSFieldManager.h
  SimG4Core/MagneticField/interface/ChordFinderSetter.h
  SimG4Core/MagneticField/interface/FieldBuilder.h
  SimG4Core/MagneticField/interface/FieldStepper.h
  SimG4Core/MagneticField/src/CMSFieldManager.cc
  SimG4Core/MagneticField/src/ChordFinderSetter.cc
  SimG4Core/MagneticField/src/FieldBuilder.cc
  SimG4Core/MagneticField/src/FieldStepper.cc
  SimG4Core/PhysicsLists/interface/CMSMonopolePhysics.h
  SimG4Core/PhysicsLists/interface/MonopoleTransportation.h
  SimG4Core/PhysicsLists/src/CMSMonopolePhysics.cc
  SimG4Core/PhysicsLists/src/MonopoleTransportation.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25337 Make ElectronMVA usable in FWlite again
  DQMOffline/Lumi/src/ElectronIdentifier.cc
  DQMOffline/Trigger/plugins/LepHTMonitor.cc
  DQMServices/Examples/src/DQMExample_Step1.cc
  EgammaAnalysis/ElectronTools/src/EGammaCutBasedEleId.cc
  EgammaAnalysis/ElectronTools/test/ElectronIDValidationAnalyzer.cc
  EgammaAnalysis/ElectronTools/test/MiniAODElectronIDValidationAnalyzer.cc
  HLTriggerOffline/SUSYBSM/src/SUSY_HLT_SingleLepton.cc
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/PatAlgos/plugins/PATElectronProducer.cc
  PhysicsTools/PatAlgos/plugins/PATPhotonProducer.cc
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/slimming/modifyPrimaryPhysicsObjects_cff.py
  RecoBTag/SoftLepton/plugins/SoftPFElectronTagInfoProducer.cc
  RecoEgamma/EgammaTools/interface/AnyMVAEstimatorRun2Base.h
  RecoEgamma/EgammaTools/interface/ConversionTools.h
  RecoEgamma/EgammaTools/interface/EffectiveAreas.h
  RecoEgamma/EgammaTools/interface/MVAValueMapProducer.h
  RecoEgamma/EgammaTools/interface/MVAVariableHelper.h
  RecoEgamma/EgammaTools/interface/MVAVariableManager.h
  RecoEgamma/EgammaTools/src/ConversionTools.cc
  RecoEgamma/EgammaTools/src/EffectiveAreas.cc
  RecoEgamma/EgammaTools/src/MVAVariableHelper.cc
  RecoEgamma/ElectronIdentification/interface/ElectronMVAEstimatorRun2.h
  RecoEgamma/ElectronIdentification/plugins/ElectronMVANtuplizer.cc
  RecoEgamma/ElectronIdentification/plugins/ElectronMVAVariableHelper.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleConversionVetoCut.cc
  RecoEgamma/ElectronIdentification/python/ElectronMVAValueMapProducer_cfi.py
  RecoEgamma/ElectronIdentification/python/FWLite.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Fall17_iso_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Fall17_iso_V2_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Fall17_noIso_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Fall17_noIso_V2_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Spring15_25ns_Trig_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Spring15_25ns_nonTrig_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Spring15_50ns_Trig_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Spring16_GeneralPurpose_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Spring16_HZZ_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_tools.py
  RecoEgamma/ElectronIdentification/python/Training/ElectronMVANtuplizer_cfg.py
  RecoEgamma/ElectronIdentification/python/egmGsfElectronIDs_cff.py
  RecoEgamma/ElectronIdentification/src/ElectronMVAEstimatorRun2.cc
  RecoEgamma/ElectronIdentification/test/testElectronMVA_cfg.py
  RecoEgamma/ElectronIdentification/test/test_eleid_fwlite.py
  RecoEgamma/PhotonIdentification/interface/PhotonMVAEstimator.h
  RecoEgamma/PhotonIdentification/plugins/PhotonMVAEstimator.cc
  RecoEgamma/PhotonIdentification/plugins/PhotonMVANtuplizer.cc
  RecoEgamma/PhotonIdentification/test/testPhotonMVA_cfg.py
  Validation/RecoEgamma/plugins/ElectronConversionRejectionValidator.cc
Labels: analysis-pending, code-checks-approved, comparison-available, dqm-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-pending

#25419 Backport of 2018 PbPb vertex smearing parameters
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealisticPbPbCollision2018_cfi.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#25433 MTD: Add PMTDParameters to the GeometryObjects serialization test
  CondFormats/GeometryObjects/test/testSerializationGeometryObjects.cpp
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25403 Clang fixes in CondTools/SiPixel
  CondFormats/DataRecord/interface/PixelDCSRcds.h
  CondTools/SiPixel/test/SiPixelGainCalibrationReadDQMFile.cc
  CondTools/SiPixel/test/SiPixelGainCalibrationReadDQMFile.h
  CondTools/SiPixel/test/SiPixelGainCalibrationRejectNoisyAndDead.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25444 Define new run2_miniAOD_devel and run2_nanoAOD_102Xv1 modifiers [102X]
  Configuration/Eras/python/Modifier_run2_miniAOD_devel_cff.py
  Configuration/Eras/python/Modifier_run2_nanoAOD_102Xv1_cff.py
  Configuration/StandardSequences/python/Eras.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#25396 ECAL : New method for MC production : outliers treatment. Legacy Run2.
  CondTools/Ecal/interface/EcalPedestalsHandler.h
  CondTools/Ecal/python/copyPedestalsMC.py
  CondTools/Ecal/src/EcalPedestalsHandler.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25452 Remove invalid tool from IORawData/DTCommissioning/plugins/BuildFile.xml
  IORawData/DTCommissioning/plugins/BuildFile.xml
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25428 Fixed shifting a negative signed value in CondFormats/L1TObjects
  CondFormats/L1TObjects/interface/L1MuPacking.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#25460 DD4hep: Add Access to dd4hep::Detector from an EventSetup Source
  DetectorDescription/DDCMS/BuildFile.xml
  DetectorDescription/DDCMS/interface/DDDetector.h
  DetectorDescription/DDCMS/interface/DetectorDescriptionRcd.h
  DetectorDescription/DDCMS/plugins/BuildFile.xml
  DetectorDescription/DDCMS/plugins/DDDetectorESProducer.cc
  DetectorDescription/DDCMS/plugins/DDTestNavigateGeometry.cc
  DetectorDescription/DDCMS/src/DDDetector.cc
  DetectorDescription/DDCMS/src/ES_DDDetector.cc
  DetectorDescription/DDCMS/test/python/testDDDetectorESProducer.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#25437 TkAl: making mille job submission via condor possible
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_fire.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_setup.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_update.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25356 COCOA: Remove Dependency on DD
  Alignment/CocoaApplication/BuildFile.xml
  Alignment/CocoaApplication/interface/CocoaAnalyzer.h
  Alignment/CocoaApplication/src/CocoaAnalyzer.cc
  Alignment/CocoaApplication/src/SealModule.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25391 [103X] Change GT. Offline GT Fix ECAL Tags
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25375 Tracker DQM HI Quality Test tuning for Offline and Online (backport of #25374)
  DQM/SiStripMonitorClient/data/sistrip_qualitytest_config_tier0.xml
  DQM/SiStripMonitorClient/data/sistrip_qualitytest_config_tier0_heavyions.xml
  DQM/SiStripMonitorClient/python/SiStripClientConfig_Tier0_cff.py
  DQM/TrackingMonitorClient/data/tracking_qualitytest_config_tier0.xml
  DQM/TrackingMonitorClient/data/tracking_qualitytest_config_tier0_heavyions.xml
  DQM/TrackingMonitorClient/python/TrackingClientConfig_Tier0_cff.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25392 [102X] Change GT. Offline GT Fix ECAL Tags
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25367 Filter for semi-visible jet signal production [93X]
  GeneratorInterface/GenFilters/src/MCParticleModuloFilter.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25459 Backport updated ecalBadCalibFilter crystal list [102X]
  RecoMET/METFilters/python/ecalBadCalibFilter_cfi.py
Labels: analysis-pending, backport-ok, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#25372 [10_2_X] Fall17 V2 Photon ID and PhotonIDValueMapProducer speedup
  DQMOffline/Trigger/python/HLTEGTnPMonitor_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoEgamma/EgammaTools/interface/MultiToken.h
  RecoEgamma/EgammaTools/interface/Utils.h
  RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfChargedHadrons_90percentBased_V2.txt
  RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfNeutralHadrons_90percentBased_V2.txt
  RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfPhotons_90percentBased_V2.txt
  RecoEgamma/PhotonIdentification/data/PhotonMVAEstimatorRun2VariablesFall17.txt
  RecoEgamma/PhotonIdentification/data/PhotonMVAEstimatorRun2VariablesFall17V1p1.txt
  RecoEgamma/PhotonIdentification/data/PhotonMVAEstimatorRun2VariablesSpring16.txt
  RecoEgamma/PhotonIdentification/plugins/PhotonIDValueMapProducer.cc
  RecoEgamma/PhotonIdentification/python/Identification/cutBasedPhotonID_Fall17_94X_V2_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Fall17_94X_V1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Fall17_94X_V1p1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Fall17_94X_V2_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_25ns_nonTrig_V0_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_25ns_nonTrig_V2_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_25ns_nonTrig_V2p1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_50ns_nonTrig_V0_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_50ns_nonTrig_V1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_50ns_nonTrig_V2_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring15_50ns_nonTrig_V2p1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Spring16_nonTrig_V1_cff.py
  RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_tools.py
  RecoEgamma/PhotonIdentification/python/PhotonIDValueMapProducer_cfi.py
  RecoEgamma/PhotonIdentification/python/PhotonMVAValueMapProducer_cfi.py
  RecoEgamma/PhotonIdentification/python/egmPhotonIDs_cff.py
  RecoEgamma/PhotonIdentification/python/photonIDValueMapProducer_cff.py
  RecoEgamma/PhotonIdentification/test/runtests.sh
  RecoEgamma/PhotonIdentification/test/testPhotonMVA_cfg.py
Labels: analysis-pending, comparison-available, dqm-approved, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved, xpog-approved

#25474 Fix the forgotten new default for 2018 HI vertex smearing (as in 10_3_X)
  Configuration/StandardSequences/python/VtxSmeared.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#25471 MTD geometry: Update MTDGeometryBuilder test to make it really useful for MTD reco geometry
  Geometry/MTDGeometryBuilder/test/MTDDigiGeometryAnalyzer.cc
  Geometry/MTDGeometryBuilder/test/mtd_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#25386 DNN-based Tau-Id discrimians (102X)
  RecoTauTag/RecoTau/BuildFile.xml
  RecoTauTag/RecoTau/interface/DeepTauBase.h
  RecoTauTag/RecoTau/plugins/BuildFile.xml
  RecoTauTag/RecoTau/plugins/DPFIsolation.cc
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/python/DPFIsolation_cff.py
  RecoTauTag/RecoTau/python/DeepTauId_cff.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/src/DeepTauBase.cc
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: backport-ok, comparison-available, fully-signed, orp-pending, reconstruction-approved, tests-approved

#25435 update PFCluster calibration for HGCal v9 geometry
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHGC_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowRealisticSimClusterHGCCalibrations_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#25407 Phase2-TB41: Add first version of October 2018 HGCal TB setup
  Geometry/HGCalCommonData/data/TB181/Oct181/ahcal.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcal.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalBeam.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalEE.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalHE.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalsense.xml
  Geometry/HGCalCommonData/data/TB181/cms.xml
  Geometry/HGCalCommonData/data/TB181/hgcProdCuts.xml
  SimG4CMS/HGCalTestBeam/python/HGCalTB181Oct1XML_cfi.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25368 NanoAOD developments, 29Nov2018 version [102X]
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  PhysicsTools/NanoAOD/plugins/IsFromLostTrackMapProducer.cc
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/extraflags_cff.py
  PhysicsTools/NanoAOD/python/isotracks_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
Labels: analysis-pending, backport-ok, comparison-pending, operations-approved, orp-approved, pdmv-pending, pending-signatures, tests-started, upgrade-pending, xpog-approved

#25473 NanoAOD developments, 29Nov2018 version [104X part 2]
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/extraflags_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  RecoMET/METFilters/python/ecalBadCalibFilter_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#25489 Add to IB/release history PR 25386 DNN-based Tau-Id discrimians (102X)
  RecoTauTag/RecoTau/test/edmTauVariables_slimmed_cfg.py
Labels: comparison-pending, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25480 Update 2018 HI MC to latest GT and HLT menu
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, code-checks-approved, comparison-available, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#25481 Update 2018 HI MC to latest GT and HLT menu (103X)
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, backport, comparison-available, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#25296 Removed remaining binary_/unary_functions
  CommonTools/ParticleFlow/interface/IPCutPFCandidateSelectorDefinition.h
  CommonTools/ParticleFlow/interface/PFCandidateSelectorDefinition.h
  CommonTools/ParticleFlow/interface/PFCandidateWithSrcPtrFactory.h
  CommonTools/ParticleFlow/interface/PFJetSelectorDefinition.h
  CommonTools/ParticleFlow/plugins/TopProjector.h
  CondFormats/L1TObjects/src/LUT.cc
  DQMOffline/CalibCalo/src/DQMSourcePi0.cc
  DQMOffline/CalibCalo/src/DQMSourcePi0.h
  DQMOffline/RecoB/plugins/BTagPerformanceAnalyzerOnData.h
  DQMOffline/RecoB/src/Matching.h
  DQMOffline/Trigger/interface/EgHLTPhoHLTFilterMon.h
  DQMOffline/Trigger/plugins/EgHLTOfflineSource.cc
  DataFormats/Common/interface/AssociationMap.h
  DataFormats/Common/interface/DetSetRefVector.h
  DataFormats/Common/interface/DetSetVector.h
  DataFormats/Common/interface/DetSetVectorNew.h
  DataFormats/Common/interface/FwdRef.h
  DataFormats/Common/interface/Ref.h
  DataFormats/Common/interface/RefTraits.h
  DataFormats/METReco/interface/HcalNoiseHPD.h
  DataFormats/StdDictionaries/src/classes_def_others.xml
  DataFormats/StdDictionaries/src/classes_others.h
  EventFilter/ESDigiToRaw/src/ESDataFormatterV4.cc
  Fireworks/Calo/interface/FWECALCaloDataDetailViewBuilder.h
  Fireworks/Calo/interface/FWECALDetailViewBuilder.h
  HLTrigger/JetMET/interface/HLTCATopTagFilter.h
  HLTrigger/JetMET/interface/HLTCAWZTagFilter.h
  HLTriggerOffline/Btag/interface/HLTBTagPerformanceAnalyzer.h
  L1Trigger/DTTrackFinder/interface/L1MuDTTrack.h
  L1Trigger/DTTrackFinder/src/L1MuDTEUX.h
  L1Trigger/DTTrackFinder/src/L1MuDTMuonSorter.cc
  L1Trigger/DTTrackFinder/src/L1MuDTWedgeSorter.cc
  L1Trigger/HardwareValidation/interface/DEutils.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMEUX.h
  MagneticField/GeomBuilder/src/MagGeoBuilderFromDDD.h
  MagneticField/GeomBuilder/src/volumeHandle.h
  PhysicsTools/MVAComputer/src/ProcSort.cc
  PhysicsTools/SelectorUtils/interface/CandidateCut.h
  RecoBTag/SoftLepton/plugins/SoftLepton.h
  RecoBTau/JetTagComputer/plugins/JetTagProducer.cc
  RecoJets/JetAlgorithms/interface/CATopJetHelper.h
  RecoMET/METAlgorithms/src/METSignificance.cc
  RecoTauTag/RecoTau/interface/CombinatoricGenerator.h
  RecoTauTag/RecoTau/interface/ConeTools.h
  RecoTauTag/RecoTau/plugins/RecoTauPileUpVertexSelector.cc
  RecoTracker/CkfPattern/plugins/TrajectorySegmentBuilder.cc
  RecoTracker/CkfPattern/src/CkfTrajectoryBuilder.cc
  RecoTracker/CkfPattern/src/RecHitIsInvalid.h
  RecoTracker/DebugTools/plugins/RecHitIsInvalid.h
  RecoTracker/NuclearSeedGenerator/src/NuclearTester.cc
  RecoTracker/TkNavigation/plugins/BeamHaloNavigationSchool.cc
  RecoTracker/TkNavigation/plugins/CosmicNavigationSchool.cc
  RecoTracker/TkNavigation/plugins/SimpleBarrelNavigableLayer.cc
  RecoTracker/TkNavigation/plugins/SimpleNavigationSchool.cc
  RecoTracker/TkNavigation/plugins/SymmetricLayerFinder.cc
  RecoVertex/VertexTools/interface/ModeFinder3d.h
  SimDataFormats/GeneratorProducts/interface/HepMCProduct.h
  TrackingTools/DetLayers/src/DetBelowZ.h
  TrackingTools/TrajectoryCleaning/src/TrajectoryCleanerBySharedHits.cc
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, core-approved, daq-approved, db-approved, dqm-approved, generators-approved, hlt-approved, l1-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved, visualization-approved

#25432 PFAlgo range based loops and TestBench removal
  RecoParticleFlow/PFProducer/interface/PFAlgo.h
  RecoParticleFlow/PFProducer/interface/PFAlgoTestBenchConversions.h
  RecoParticleFlow/PFProducer/interface/PFAlgoTestBenchElectrons.h
  RecoParticleFlow/PFProducer/interface/PFElectronAlgo.h
  RecoParticleFlow/PFProducer/interface/PFPhotonAlgo.h
  RecoParticleFlow/PFProducer/plugins/PFProducer.cc
  RecoParticleFlow/PFProducer/src/PFAlgo.cc
  RecoParticleFlow/PFProducer/src/PFAlgoTestBenchConversions.cc
  RecoParticleFlow/PFProducer/src/PFAlgoTestBenchElectrons.cc
  RecoParticleFlow/PFProducer/src/PFElectronAlgo.cc
  RecoParticleFlow/PFProducer/src/PFPhotonAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25482 HGCal MultiCluster Proxy for LEGO view
  Fireworks/Calo/plugins/FWHGCalMultiClusterLegoProxyBuilder.cc
  Fireworks/Calo/plugins/FWHGCalMultiClusterLegoProxyBuilder.h
  Fireworks/Calo/plugins/FWHGCalMultiClusterSliceSelector.cc
  Fireworks/Calo/plugins/FWHGCalMultiClusterSliceSelector.h
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#25496 Fixes OOTPU for BTLDigitisation
  SimFastTiming/FastTimingCommon/src/BTLBarDeviceSim.cc
  SimFastTiming/FastTimingCommon/src/BTLTileDeviceSim.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25447 Validation/Geometry: Fix floats definition. default constructor
  Fireworks/Core/src/FWGeometryTableViewManager.cc
  Validation/Geometry/src/MaterialBudgetData.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved, visualization-approved

#25477 Add treatment for C-style arrays in friendly class names
  FWCore/Utilities/src/FriendlyName.cc
  FWCore/Utilities/test/friendlyname_t.cppunit.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25333 make Constrain Hits first class citizen
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1RecHits.cc
  DataFormats/TrackerRecHit2D/interface/BaseTrackerRecHit.h
  DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h
  DataFormats/TrackerRecHit2D/src/SiStripMatchedRecHit2D.cc
  DataFormats/TrackerRecHit2D/src/TrackerSingleRecHit.cc
  RecoLocalTracker/SubCollectionProducers/src/TrackClusterRemover.cc
  RecoTracker/CkfPattern/plugins/GroupedCkfTrajectoryBuilder.cc
  RecoTracker/DeDx/plugins/DeDxEstimatorProducer.cc
  RecoTracker/DeDx/plugins/DeDxHitInfoProducer.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackCutClassifier.cc
  RecoTracker/TrackProducer/src/TrackProducerAlgorithm.cc
  RecoTracker/TransientTrackingRecHit/interface/TRecHit2DPosConstraint.h
  RecoTracker/TransientTrackingRecHit/interface/TRecHit5DParamConstraint.h
  RecoTracker/TransientTrackingRecHit/interface/Traj2TrackHits.h
  SimTracker/TrackAssociation/interface/trackHitsToClusterRefs.h
  TrackingTools/GsfTracking/src/GsfConstraintAtVertex.cc
  TrackingTools/PatternTools/src/TempTrajectory.cc
  TrackingTools/PatternTools/src/Trajectory.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#25442 TkAlInOneTool: optional muon pT cut and set default eta ranges in Zmm validation
  Alignment/OfflineValidation/python/TkAlAllInOneTool/zMuMuValidation.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/zMuMuValidationTemplates.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25498 NJetsMC filter
  GeneratorInterface/GenFilters/src/NJetsMC.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25503 Remove unused variables from lambdas
  RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZT_vect.cc
  RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZ_vect.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25500 Fix for conddb copy GT tool
  CondCore/Utilities/scripts/conddb
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25509 updated lost plugins definition for SiPixelQuality
  Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25506 L1T offline DQM - Fix logic error in L1T muon DQM
  DQMOffline/L1Trigger/src/L1TMuonDQMOffline.cc
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#25505 Removed from L1 config files parameters which are not longer used
  DQM/L1TMonitor/python/L1TRCT_cfi.py
  DQM/L1TMonitor/python/L1TRPCTF_cfi.py
  DQM/L1TMonitor/python/L1TdeRCT_cfi.py
  DQMOffline/L1Trigger/python/L1TSync_Offline_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#25504 Clean-up Geant4 sensitive detectors 7
  SimG4CMS/CherenkovAnalysis/BuildFile.xml
  SimG4CMS/CherenkovAnalysis/interface/DreamSD.h
  SimG4CMS/CherenkovAnalysis/interface/PMTResponse.h
  SimG4CMS/CherenkovAnalysis/plugins/BuildFile.xml
  SimG4CMS/CherenkovAnalysis/src/DreamSD.cc
  SimG4CMS/CherenkovAnalysis/src/PMTResponse.cc
  SimG4CMS/HcalTestBeam/BuildFile.xml
  SimG4CMS/HcalTestBeam/interface/HcalTB02SD.h
  SimG4CMS/HcalTestBeam/src/HcalTB02SD.cc
  SimG4CMS/HcalTestBeam/src/HcalTB06BeamSD.cc
  SimG4Core/Application/src/RunManager.cc
  SimG4Core/Application/src/RunManagerMT.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/Geometry/src/DDG4Builder.cc
  SimG4Core/Geometry/src/DDG4SensitiveConverter.cc
  SimG4Core/GeometryProducer/BuildFile.xml
  SimG4Core/GeometryProducer/src/GeometryProducer.cc
  SimG4Core/SensitiveDetector/BuildFile.xml
  SimG4Core/SensitiveDetector/interface/AttachSD.h
  SimG4Core/SensitiveDetector/interface/SensitiveCaloDetector.h
  SimG4Core/SensitiveDetector/interface/SensitiveDetector.h
  SimG4Core/SensitiveDetector/interface/SensitiveDetectorMaker.h
  SimG4Core/SensitiveDetector/interface/SensitiveDetectorMakerBase.h
  SimG4Core/SensitiveDetector/interface/SensitiveDetectorPluginFactory.h
  SimG4Core/SensitiveDetector/interface/SensitiveTkDetector.h
  SimG4Core/SensitiveDetector/src/AttachSD.cc
  SimG4Core/SensitiveDetector/src/SensitiveDetector.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25467 fixed one bug in GEMCSC algorithm resulting in memory issue. the bug …
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboard.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#25501 factor out btagDiscriminators definition for easier modification
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#25379 Run2-alca147 Add a new class for low lumi runs
  Calibration/HcalAlCaRecoProducers/plugins/AlCaLowPUHBHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalLowPUHBHEMuonFilter_Output_cff.py
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalLowPUHBHEMuonFilter_cff.py
  Calibration/HcalAlCaRecoProducers/test/AlCaLowPUHBHEMuonFilter_cfg.py
  Configuration/AlCa/python/autoAlca.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreamsHeavyIons_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#25468 [HBHE] Use uniform timeslew parameters
  CalibCalorimetry/HcalPlugins/python/HcalTimeSlew_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25466 Simulation of the pixel bad components on the FED channel basis
  CalibTracker/Records/interface/SiPixelFEDChannelContainerESProducerRcd.h
  CalibTracker/Records/src/SiPixelFEDChannelContainerESProducerRcd.cc
  CalibTracker/SiPixelESProducers/plugins/PixelFEDChannelCollectionProducer.cc
  CalibTracker/SiPixelESProducers/python/PixelFEDChannelCollectionProducer_cfi.py
  CalibTracker/SiPixelESProducers/test/PixelFEDChannelCollectionMapTestReader.cc
  CalibTracker/SiPixelESProducers/test/PixelFEDChannelCollectionMapTestReader_cfg.py
  CondCore/SiPixelPlugins/src/plugin.cc
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
  CondFormats/DataRecord/interface/SiPixelStatusScenarioProbabilityRcd.h
  CondFormats/DataRecord/interface/SiPixelStatusScenariosRcd.h
  CondFormats/DataRecord/src/SiPixelStatusScenarioProbabilityRcd.cc
  CondFormats/DataRecord/src/SiPixelStatusScenariosRcd.cc
  CondFormats/External/interface/PixelFEDChannel.h
  CondFormats/External/test/testSerializationExternal.cpp
  CondFormats/SiPixelObjects/interface/SiPixelFEDChannelContainer.h
  CondFormats/SiPixelObjects/interface/SiPixelQualityProbabilities.h
  CondFormats/SiPixelObjects/src/SiPixelFEDChannelContainer.cc
  CondFormats/SiPixelObjects/src/SiPixelQualityProbabilities.cc
  CondFormats/SiPixelObjects/src/T_EventSetup_SiPixelFEDChannelContainer.cc
  CondFormats/SiPixelObjects/src/T_EventSetup_SiPixelQualityProbabilities.cc
  CondFormats/SiPixelObjects/src/classes.h
  CondFormats/SiPixelObjects/src/classes_def.xml
  CondFormats/SiPixelObjects/src/headers.h
  CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerTestReader.cc
  CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerTestReader_cfg.py
  CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerTestWriter.cc
  CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerTestWriter_cfg.py
  CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerWriteFromASCII.cc
  CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerWriteFromASCII_cfg.py
  CondFormats/SiPixelObjects/test/SiPixelQualityProbabilitiesTestReader.cc
  CondFormats/SiPixelObjects/test/SiPixelQualityProbabilitiesTestReader_cfg.py
  CondFormats/SiPixelObjects/test/SiPixelQualityProbabilitiesTestWriter.cc
  CondFormats/SiPixelObjects/test/SiPixelQualityProbabilitiesTestWriter_cfg.py
  CondFormats/SiPixelObjects/test/testSerializationSiPixelObjects.cpp
  DataFormats/SiPixelDetId/BuildFile.xml
  DataFormats/SiPixelDetId/src/ES_PixelFEDChannelCollectionMap.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.h
  EventFilter/SiPixelRawToDigi/python/SiPixelRawToDigi_cfi.py
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
  SimGeneral/MixingModule/python/pixelDigitizer_cfi.py
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#25370 [10_2_X] DeepDoubleCvL and DeepDoubleCvB tagger integration
  DataFormats/BTauReco/interface/DeepDoubleBTagInfo.h
  DataFormats/BTauReco/interface/DeepDoubleXFeatures.h
  DataFormats/BTauReco/interface/DeepDoubleXTagInfo.h
  DataFormats/BTauReco/src/classes.h
  DataFormats/BTauReco/src/classes_def.xml
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/Configuration/python/RecoBTag_cff.py
  RecoBTag/FeatureTools/plugins/DeepDoubleXTagInfoProducer.cc
  RecoBTag/FeatureTools/python/pfDeepDoubleXTagInfosNopt_cfi.py
  RecoBTag/TensorFlow/interface/tensor_fillers.h
  RecoBTag/TensorFlow/plugins/DeepDoubleXTFJetTagsProducer.cc
  RecoBTag/TensorFlow/python/pfDeepDoubleX_cff.py
  RecoBTag/TensorFlow/python/pfDeepFlavour_cff.py
  RecoBTag/TensorFlow/python/pfMassIndependentDeepDoubleXJetTags_cff.py
  RecoBTag/TensorFlow/src/tensor_fillers.cc
  RecoBTag/TensorFlow/test/plotDDX.py
  RecoBTag/TensorFlow/test/test_deep_doubleb_cfg_AOD.py
  RecoBTag/TensorFlow/test/test_deep_doublex_cfg.py
Labels: analysis-pending, backport-ok, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#25508 NJetsMC filter backport to CMSSW_10_2_X
  GeneratorInterface/GenFilters/src/NJetsMC.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25539 Fix clang warnings in RecoEcal/EgammaClusterAlgos
  RecoEcal/EgammaClusterAlgos/src/CosmicClusterAlgo.cc
  RecoEcal/EgammaClusterAlgos/src/Multi5x5ClusterAlgo.cc
  RecoEcal/EgammaClusterAlgos/src/PFECALSuperClusterAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25538 Removed unused variable in HFClusterAlgo
  RecoEgamma/EgammaHFProducers/plugins/HFClusterAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25533 Removed unused variables in RecoEgamma/EgammaPhotonProducers
  RecoEgamma/EgammaPhotonProducers/src/GEDPhotonCoreProducer.cc
  RecoEgamma/EgammaPhotonProducers/src/PhotonCoreProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25532 Fix clang warning in ConversionFinder
  RecoEgamma/EgammaTools/src/ConversionFinder.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25531 fix clang warnings in RecoEgamma/Examples
  RecoEgamma/Examples/plugins/ElectronSeedAnalyzer.cc
  RecoEgamma/Examples/plugins/GsfElectronFakeAnalyzer.cc
  RecoEgamma/Examples/plugins/GsfElectronMCFakeAnalyzer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25483 Update non-aged noise for V9 geometries
  SimCalorimetry/HGCalSimProducers/python/hgcalDigitizer_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25511 Geant4 sensitive detectors 8
  SimG4CMS/Forward/plugins/BuildFile.xml
  SimG4CMS/Tracker/plugins/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25555 Remove unused function from InnerDeltaPhi.cc
  RecoTracker/TkHitPairs/src/InnerDeltaPhi.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25556 Fix clang warnings in RecoMuon/TrackerSeedGenerator
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromOrderedHits.h
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromPropagation.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromPropagation.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25558 Remove inappropriate use of std::move
  RecoMuon/MuonIsolationProducers/plugins/MuIsoDepositCopyProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25559 Declare MuonShower as a struct, not a class
  RecoMuon/MuonIdentification/interface/MuonShowerInformationFiller.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25560 Avoid hiding base class method 'trajectories'
  RecoMuon/GlobalTrackFinder/interface/GlobalMuonTrajectoryBuilder.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25535 Removed unused variable in OutInConversionSeedFinder
  RecoEgamma/EgammaPhotonAlgos/src/OutInConversionSeedFinder.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25565 [10.5.X][RECONSTRUCTION] Fix deps to resolve undefined reference mentioned in UBSAN IBS
  RecoTracker/TrackProducer/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25564 [10.5.X][SIMULATION] Fix deps to resolve undefined reference mentioned in UBSAN IBS
  SimG4Core/HelpfulWatchers/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25554 Remove unused variables from CosmicRegionalSeedGenerator
  RecoTracker/SpecialSeedGenerators/src/CosmicRegionalSeedGenerator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25552 Remove std::move to allow better compiler optimization in RecoTracker/SingleTrackPattern
  RecoTracker/SingleTrackPattern/src/CRackTrajectoryBuilder.cc
  RecoTracker/SingleTrackPattern/src/CosmicTrajectoryBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25537 Removed unused variables in RecoEgamma/EgammaIsolationALgos
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaRecHitExtractor.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EleIsoDetIdCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/GamIsoDetIdCollectionProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25486 New training for anti-e tau-Id
  RecoTauTag/Configuration/python/HPSPFTaus_cff.py
  RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py
  RecoTauTag/RecoTau/plugins/PATTauDiscriminantCutMultiplexer.cc
  RecoTauTag/RecoTau/plugins/PATTauDiscriminationAgainstElectronMVA6.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationAgainstElectronMVA6.cc
  RecoTauTag/RecoTau/plugins/RecoTauDiscriminantCutMultiplexer.cc
  RecoTauTag/RecoTau/python/PATTauDiscriminationAgainstElectronMVA6_cfi.py
  RecoTauTag/RecoTau/python/PFRecoTauDiscriminationAgainstElectronMVA6_cfi.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25567 Fixed clang warnings in RecoParticleFlow/PFProducer
  RecoParticleFlow/PFProducer/interface/PFBlockAlgo.h
  RecoParticleFlow/PFProducer/plugins/PFBlockProducer.cc
  RecoParticleFlow/PFProducer/plugins/PFBlockProducer.h
  RecoParticleFlow/PFProducer/src/PFBlockAlgo.cc
  RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc
  RecoParticleFlow/PFProducer/src/combination.hpp
  RecoParticleFlow/PFProducer/test/EgGEDPhotonAnalyzer.cc
  RecoParticleFlow/PFProducer/test/GsfGEDElectronAnalyzer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#24855 Kalman BMTF Emu v2.7
  DataFormats/L1TMuon/interface/L1MuKBMTrack.h
  DataFormats/L1TMuon/src/L1MuKBMTrack.cc
  L1Trigger/L1TMuon/src/RegionalMuonRawDigiTranslator.cc
  L1Trigger/L1TMuonBarrel/interface/L1TMuonBarrelKalmanAlgo.h
  L1Trigger/L1TMuonBarrel/interface/L1TMuonBarrelKalmanRegionModule.h
  L1Trigger/L1TMuonBarrel/interface/L1TMuonBarrelKalmanSectorProcessor.h
  L1Trigger/L1TMuonBarrel/python/simKBmtfDigis_cfi.py
  L1Trigger/L1TMuonBarrel/python/simKBmtfStubs_cfi.py
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanAlgo.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanRegionModule.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanSectorProcessor.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanStubProcessor.cc
  L1Trigger/L1TMuonBarrel/test/kalmanTools/createGains.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/kmtfAnalysis.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/makeEtaLuts.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/makeInitialState.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/makePTPhiLUTs.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/runCalibration.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/validation.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved
