Repository cms-sw/cmssw, pull requests merged in 2019-09, with the labels that each got.

#27522 New GsfEleEBEECut class to generalize some ElectronIdentification cuts
  RecoEgamma/EgammaTools/interface/EBEECutValues.h
  RecoEgamma/ElectronIdentification/BuildFile.xml
  RecoEgamma/ElectronIdentification/interface/VersionedGsfElectronSelector.h
  RecoEgamma/ElectronIdentification/interface/VersionedPatElectronSelector.h
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleDEtaInCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleDEtaInLinearCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleDeltaBetaIsoCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleDeltaBetaIsoCutStandalone.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleE2x5OverE5x5Cut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleEBEECut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleEInverseMinusPInverseCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleEmHadD1IsoRhoCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleFull5x5E2x5OverE5x5Cut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleFull5x5E2x5OverE5x5WithSatCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleFull5x5SigmaIEtaIEtaWithSatCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleHadronicOverEMCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleHadronicOverEMLinearCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleNormalizedGsfChi2Cut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleTrkPtIsoCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleTrkPtIsoRhoCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleValueMapIsoRhoCut.cc
  RecoEgamma/ElectronIdentification/plugins/plugins.cc
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronHLTPreselecition_Summer16_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Fall17_94X_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Fall17_94X_V2_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Spring15_25ns_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Spring15_50ns_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Spring15_50ns_V2_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Summer16_80X_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_tools.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_tools.py
  RecoEgamma/ElectronIdentification/python/Validation/CfiFile_cfi.py
  RecoEgamma/ElectronIdentification/python/Validation/ConfFile_cfg.py
  RecoEgamma/ElectronIdentification/python/Validation/DYJetsToLL_Sc1_AODSIM.py
  RecoEgamma/ElectronIdentification/python/Validation/DYJetsToLL_Sc1_MINIAOD.py
  RecoEgamma/ElectronIdentification/python/Validation/DYJetsToLL_Sc2_AODSIM.py
  RecoEgamma/ElectronIdentification/src/classes.h
  RecoEgamma/PhotonIdentification/plugins/cuts/PhoGenericRhoPtScaledCut.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27821 Remove dead assignments in a few sparse reco packages
  RecoLocalMuon/CSCRecHitD/src/CSCMake2DRecHit.cc
  RecoLocalMuon/CSCRecHitD/src/CSCRecHitDBuilder.cc
  RecoLocalMuon/DTSegment/src/DTLinearFit.cc
  RecoParticleFlow/PFClusterTools/interface/PFPhotonClusters.h
  RecoParticleFlow/PFClusterTools/src/PFPhotonClusters.cc
  RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc
  RecoTBCalo/EcalTBRecProducers/src/EcalTBWeightUncalibRecHitProducer.cc
  RecoTracker/TkDetLayers/src/PixelForwardLayerPhase1.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27900 Updated tool for Tracker Alignment: DrmsNR trends
  Alignment/OfflineValidation/bin/DMRtrends.cc
  Alignment/OfflineValidation/bin/README.md
  Alignment/OfflineValidation/data/lumiperIOV2017.txt
  Alignment/OfflineValidation/data/lumiperrun2016.txt
  Alignment/OfflineValidation/data/lumiperrun2018.txt
  Alignment/OfflineValidation/macros/PlotAlignmentValidation.C
  Alignment/OfflineValidation/macros/PlotAlignmentValidation.h
  Alignment/OfflineValidation/plugins/ColorParser.C
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27914 Add missing headers for DD4
  DetectorDescription/DDCMS/interface/DDSolidShapes.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27591 [PPS][106X] Diamond DQM patch for 2017
  DQM/CTPPS/plugins/CTPPSDiamondDQMSource.cc
Labels: backport, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27606 [10.6.X] Activate Pixel Charge Reweighting for phase-0 detector (2016 only)
  Configuration/AlCa/python/autoCond.py
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Modifier_pixel_2016_cff.py
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#27620 [106x] including ctpps in DQMOffline standard conf
  DQM/CTPPS/python/ctppsDQM_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27778 Exclude dark photon 3000022 tracking for CMSSW_10_6_X
  SimG4Core/Generators/src/Generator.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27816 enabling UL regression for 2018 (and likely Run3) : 106X
  Configuration/AlCa/python/autoCond.py
  Configuration/Eras/python/Era_Run3_cff.py
  RecoEgamma/EgammaTools/python/regressionModifier_cfi.py
Labels: alca-approved, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved

#27425 updated FastSim treatment of long-lived charginos in the muon system
  FastSimulation/Calorimetry/src/CalorimetryManager.cc
  FastSimulation/MuonSimHitProducer/src/MuonSimHitProducer.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#27835 Try to remove a few LogicErrors and DeadStores in DT/CSC LocalMuon reco
  RecoLocalMuon/CSCRecHitD/src/CSCMake2DRecHit.cc
  RecoLocalMuon/DTSegment/src/DTSegmentCand.cc
  RecoLocalMuon/DTSegment/src/DTSegmentExtendedCand.cc
  RecoLocalMuon/DTSegment/src/DTSegmentUpdator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27878 Disabled PCA inputs for deepTau v2
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#27913 move TreeWriterForEcalCorrection in to a plugin directory
  FastSimulation/Calorimetry/plugins/BuildFile.xml
  FastSimulation/Calorimetry/plugins/TreeWriterForEcalCorrection.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#27910 FixLumisPerJobSplittingFor2018
  Configuration/PyReleaseValidation/python/MatrixInjector.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27746 Update autoskim for egamma datasets
  Configuration/Skimming/python/autoSkim.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved

#27828 Removed use of L1Trigger/GlobalMuonTrigger from test
  L1Trigger/GlobalMuonTrigger/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#27915 move EcalPedestalHistory in to plugins directory to avoid duplicate definitions
  CondTools/Ecal/plugins/EcalPedestalHistory.cc
  CondTools/Ecal/plugins/EcalPedestalHistory.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27843 Fix gcc9 warnings in CommonTools
  CommonTools/Statistics/interface/SequentialCombinationGenerator.h
  CommonTools/Statistics/interface/SequentialPartitionGenerator.h
  CommonTools/Statistics/src/SequentialCombinationGenerator.cc
  CommonTools/Statistics/src/SequentialPartitionGenerator.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27912 Fix simulation of the pixel bad components on the FED channel basis for PreMixing
  SimTracker/SiPixelDigitizer/plugins/PreMixingSiPixelWorker.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.h
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, urgent

#27797 Fix warnings for gcc9 IB for HeterogeneousCore/CUDAServices
  HeterogeneousCore/CUDAServices/plugins/NVProfilerService.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27747 Update autoskim for egamma datasets
  Configuration/Skimming/python/autoSkim.py
Labels: comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved

#27911 FixLumisPerJobSplittingFor2018
  Configuration/PyReleaseValidation/python/MatrixInjector.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27818 Fix gcc 9 warnings in L1Trigger/L1TCalorimeter
  L1Trigger/L1TCalorimeter/interface/L1GObject.h
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#27785 Properly veto HGCal superclusters from entering regular PFBlocks - phase2 scenarios
  RecoParticleFlow/PFProducer/plugins/importers/GSFTrackImporter.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27923 Data and MC global tags for 2018 UL
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27931 Update Reconstruction_Data for move of jetCorrectorsForReco to Task
  Configuration/StandardSequences/python/Reconstruction_Data_cff.py
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#27920 DD4hep: Move Files to an Approved Directory Structure
  DetectorDescription/DDCMS/plugins/BuildFile.xml
  DetectorDescription/DDCMS/plugins/dd4hep/DDAngular.cc
  DetectorDescription/DDCMS/plugins/dd4hep/DDCMSDetElementCreator.cc
  DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
  DetectorDescription/DDCMS/plugins/dd4hep/DDLinear.cc
  DetectorDescription/DDCMS/plugins/dd4hep/DDTestVectorAlgo.cc
  DetectorDescription/DDCMS/plugins/test/DDTestCompactView.cc
  DetectorDescription/DDCMS/plugins/test/DDTestDumpFile.cc
  DetectorDescription/DDCMS/plugins/test/DDTestDumpGeometry.cc
  DetectorDescription/DDCMS/plugins/test/DDTestNavigateGeometry.cc
  DetectorDescription/DDCMS/plugins/test/DDTestSpecPars.cc
  DetectorDescription/DDCMS/plugins/test/DDTestSpecParsFilter.cc
  DetectorDescription/DDCMS/plugins/test/DDTestVectors.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDCutTubsFromPoints.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDPixBarLayerAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDPixBarLayerUpgradeAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDPixFwdDiskAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDPixPhase1FwdDiskAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECCoolAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECModuleAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECOptoHybAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECPhiAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECPhiAltAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIBLayerAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIDModuleAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIDModulePosAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIDRingAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTOBAxCableAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTOBRadCableAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTOBRodAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerAngular.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerLinear.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerPhiAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerPhiAltAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerXYZPosAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerZPosAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27833 HGCal and jets validation plots harvesting
  DQMOffline/PFTau/interface/Benchmark.h
  DQMOffline/PFTau/interface/MatchCandidateBenchmark.h
  DQMOffline/PFTau/interface/PFJetMonitor.h
  DQMOffline/PFTau/src/MatchCandidateBenchmark.cc
  DQMOffline/PFTau/src/PFJetMonitor.cc
  Validation/Configuration/python/hgcalSimValid_cff.py
  Validation/HGCalValidation/scripts/harvestHGCalValidationPlots.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#27892 SiPixel Payload Inspector improvements
  CondCore/SiPixelPlugins/interface/SiPixelPayloadInspectorHelper.h
  CondCore/SiPixelPlugins/plugins/SiPixelLorentzAngle_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelQuality_PayloadInspector.cc
  CondCore/SiPixelPlugins/test/BuildFile.xml
  CondCore/SiPixelPlugins/test/testLorentzAngleMap.sh
  CondCore/SiPixelPlugins/test/testSiPixelLorentzAngle.sh
  CondCore/SiPixelPlugins/test/testSiPixelPayloadInspector.cpp
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27844 Fix gcc 9 warnings in DataFormats
  DataFormats/EgammaCandidates/src/Photon.cc
  DataFormats/HcalCalibObjects/src/HFRecalibration.cc
  DataFormats/TrackReco/src/HitPattern.cc
  DataFormats/TrackerCommon/src/TrackerTopology.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27921 Define move assignment in SoATuple.h
  FWCore/Utilities/interface/SoATuple.h
  FWCore/Utilities/test/soatuple_t.cppunit.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27854 Fix gcc9 warning in L1TriggerConfig
  L1TriggerConfig/L1GtConfigProducers/src/L1GtTriggerMenuConfigOnlineProd.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#27901 simplify elementLoop flow, add comments
  RecoParticleFlow/PFProducer/interface/PFAlgo.h
  RecoParticleFlow/PFProducer/src/PFAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#27927 Explicitly removed methods implicitly ignored by compiler in FWCore/Framework
  FWCore/Framework/interface/ConsumesCollector.h
  FWCore/Framework/interface/ESConsumesCollector.h
  FWCore/Framework/interface/SubProcess.h
  FWCore/Framework/src/EarlyDeleteHelper.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, requires-external, tests-approved

#27951 Fix headers for check-headers errors reported in PR 27841
  GeneratorInterface/LHEInterface/interface/LHEProxy.h
  PhysicsTools/Utilities/interface/FunctClone.h
  PhysicsTools/Utilities/interface/RootFunctionAdapter.h
Labels: analysis-pending, code-checks-approved, comparison-available, generators-pending, orp-approved, pending-signatures, tests-approved

#27943 Run3-sim45 Remove reference to G4DataQuestionaire
  SimG4Core/CustomPhysics/src/CustomPhysics.cc
  SimG4Core/GFlash/plugins/GFlash.cc
  SimG4Core/PhysicsLists/plugins/FTFCMS_BIC.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_ATL_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EML.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMM_TRK.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMN.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMV.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMY.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMZ.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_HP_EML.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_HP_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_XS_EML.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_HP_EMM.cc
  SimG4Core/PhysicsLists/plugins/QBBCCMS.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_BERT.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_BERT_EML.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_BERT_EMV.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_BERT_HP_EML.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EML.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EMM.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EMN.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EMY.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EMZ.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27944 Fixing VID return value for HEEP Trk Iso: 11_0_X
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleTrkPtIsoCut.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27939 Minor technical fix for FastSim de/dx LLP
  FastSimulation/Calorimetry/src/CalorimetryManager.cc
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastTrackDeDxProducer.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#27850 Fix gcc9 warning in HeavyFlavorAnalysis/RecoDecay
  HeavyFlavorAnalysis/RecoDecay/src/BPHPlusMinusCandidate.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#27852 Fix gcc9 warning in MuonAnalysis/MuonAssociators
  MuonAnalysis/MuonAssociators/src/MatcherUsingTracksAlgorithm.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#27827 Fix gcc9 warnings L1Trigger/GlobalCaloTrigger
  L1Trigger/GlobalCaloTrigger/src/L1GctRegion.cc
  L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#27925 TAU miniaod validation/dqm
  Configuration/StandardSequences/python/Validation_cff.py
  Validation/RecoTau/BuildFile.xml
  Validation/RecoTau/interface/TauValidationMiniAOD.h
  Validation/RecoTau/python/DQMMCValidation_cfi.py
  Validation/RecoTau/python/DQMSequences_cfi.py
  Validation/RecoTau/python/RecoTauValidationMiniAOD_cfi.py
  Validation/RecoTau/python/RecoTauValidation_cff.py
  Validation/RecoTau/src/SealModule.cc
  Validation/RecoTau/src/TauValidationMiniAOD.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#27673 SimG4CMS/PPS module for the PPS full simulation
  SimG4CMS/PPS/BuildFile.xml
  SimG4CMS/PPS/interface/PPSDiamondG4Hit.h
  SimG4CMS/PPS/interface/PPSDiamondG4HitCollection.h
  SimG4CMS/PPS/interface/PPSDiamondNumberingScheme.h
  SimG4CMS/PPS/interface/PPSDiamondOrganization.h
  SimG4CMS/PPS/interface/PPSDiamondSD.h
  SimG4CMS/PPS/interface/PPSPixelG4Hit.h
  SimG4CMS/PPS/interface/PPSPixelG4HitCollection.h
  SimG4CMS/PPS/interface/PPSPixelNumberingScheme.h
  SimG4CMS/PPS/interface/PPSPixelOrganization.h
  SimG4CMS/PPS/interface/PPSPixelSD.h
  SimG4CMS/PPS/interface/PPSStripNumberingScheme.h
  SimG4CMS/PPS/interface/PPSStripOrganization.h
  SimG4CMS/PPS/interface/PPSVDetectorOrganization.h
  SimG4CMS/PPS/interface/TotemRPG4Hit.h
  SimG4CMS/PPS/interface/TotemRPG4HitCollection.h
  SimG4CMS/PPS/interface/TotemRPSD.h
  SimG4CMS/PPS/interface/TotemRPVDetectorOrganization.h
  SimG4CMS/PPS/plugins/BuildFile.xml
  SimG4CMS/PPS/plugins/module.cc
  SimG4CMS/PPS/python/geometryTotemRP_cfi.py
  SimG4CMS/PPS/src/PPSDiamondG4Hit.cc
  SimG4CMS/PPS/src/PPSDiamondNumberingScheme.cc
  SimG4CMS/PPS/src/PPSDiamondOrganization.cc
  SimG4CMS/PPS/src/PPSDiamondSD.cc
  SimG4CMS/PPS/src/PPSPixelG4Hit.cc
  SimG4CMS/PPS/src/PPSPixelNumberingScheme.cc
  SimG4CMS/PPS/src/PPSPixelOrganization.cc
  SimG4CMS/PPS/src/PPSPixelSD.cc
  SimG4CMS/PPS/src/PPSStripNumberingScheme.cc
  SimG4CMS/PPS/src/PPSStripOrganization.cc
  SimG4CMS/PPS/src/TotemRPG4Hit.cc
  SimG4CMS/PPS/src/TotemRPSD.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27855 Fix gcc9 warning in PhysicsTools
  PhysicsTools/IsolationUtils/src/ConeAreaFunction.cc
  PhysicsTools/IsolationUtils/src/IntegrandThetaFunction.cc
  PhysicsTools/RecoUtils/src/CandKinematicVertexFitter.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#25239 Convert auto_ptr to unique_ptr in SimDataFormats/GeneratorProducts.
  SimDataFormats/GeneratorProducts/interface/GenEventInfoProduct.h
  SimDataFormats/GeneratorProducts/interface/LHEEventProduct.h
  SimDataFormats/GeneratorProducts/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#27953 Move SimG4CMS/PPS dependency to geant4core only
  SimG4CMS/PPS/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27952 Ignore sanitize options when generating CondFormat serialzations
  CondFormats/Serialization/python/condformats_serialization_generate.py
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27922 fix handling of intermediate lumi values in HCAL aging
  CondFormats/HcalObjects/src/HBHEDarkening.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27908 More verbose error if plugin could not be loaded due to missing shared library
  CondCore/AlignmentPlugins/test/testTrackerAlignmentPayloadInspector.cpp
  CondCore/CondDB/test/testConditionDatabase_0.cpp
  CondCore/CondDB/test/testConditionDatabase_1.cpp
  CondCore/CondDB/test/testConditionDatabase_2.cpp
  CondCore/CondDB/test/testConnectionPool.cpp
  CondCore/CondDB/test/testFrontier.cpp
  CondCore/CondDB/test/testGroupSelection.cpp
  CondCore/CondDB/test/testPayloadProxy.cpp
  CondCore/CondDB/test/testReadWritePayloads.cpp
  CondCore/CondDB/test/testRunInfo.cpp
  CondCore/CondDB/test/testTempWrapper_0.cpp
  CondCore/RunInfoPlugins/test/testRunInfoPayloadInspector.cpp
  CondCore/SiStripPlugins/test/testSiStripPayloadInspector.cpp
  CondCore/Utilities/src/Utilities.cc
  CondCore/Utilities/test/testBasicPayload.cpp
  CondCore/Utilities/test/testPngHistograms.cpp
  FWCore/PluginManager/src/PluginManager.cc
Labels: code-checks-approved, comparison-available, core-approved, db-approved, fully-signed, orp-approved, tests-approved

#27928 Add an LHE-based mc relval with multiple lumi sections and concurrent lumi settings
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27847 Fix gcc9 warnings in FastSimDataFormats/L1GlobalMuonTrigger
  FastSimDataFormats/L1GlobalMuonTrigger/src/SimpleL1MuGMTCand.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#27938 Run3-sim44 Make changes to conform G4/GV Comparison
  Geometry/CMSCommonData/data/cmsProdCuts.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2018NoSDXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D45NoSDXML_cfi.py
  SimG4Core/Application/interface/RunManager.h
  SimG4Core/Application/interface/RunManagerMT.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/RunManager.cc
  SimG4Core/Application/src/RunManagerMT.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#27950 HBHE: bugfix for MAHI on issue of missing SOI+4 subtraction
  RecoLocalCalo/HcalRecAlgos/src/MahiFit.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27954 DD4hep: Strip off Residual Namespace while Calculating the History
  DetectorDescription/DDCMS/src/DDFilteredView.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27946 DD4hep: Legacy DD Shape ID Support and Mapping
  DetectorDescription/DDCMS/data/cms-mf-geometry.xml
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/interface/DDShapes.h
  DetectorDescription/DDCMS/interface/DDSolidShapes.h
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  DetectorDescription/DDCMS/src/DDShapes.cc
  DetectorDescription/DDCMS/test/BuildFile.xml
  DetectorDescription/DDCMS/test/DDSolidLegacyShapes.cppunit.cc
  DetectorDescription/DDCMS/test/DDSolidShapes.cppunit.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27940 Run3-hgx218 Conevrt one DDHGCalNoTaperEndcap algorithm to DD4Hep format
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalNoTaperEndcap-algorithm.xml
  Geometry/HGCalCommonData/data/dd4hep/cms.xml
  Geometry/HGCalCommonData/data/dd4hep/esalgo.xml
  Geometry/HGCalCommonData/data/dd4hep/escon.xml
  Geometry/HGCalCommonData/data/fastTiming.xml
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalNoTaperEndcap.cc
  Geometry/HGCalCommonData/python/testFastTimeEndcapXML_cfi.py
  Geometry/HGCalCommonData/test/python/dumpFastTimeEndcap_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalFastTimeEndcap_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#27792 ECAL : SRP and TPG tools
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
  CondTools/Ecal/python/copyFileAlignEB_cfg.py
  CondTools/Ecal/python/copyFileAlignEE_cfg.py
  CondTools/Ecal/python/copyFileAlignES_cfg.py
  CondTools/Ecal/python/copyTrivialAlignEB_cfg.py
  CondTools/Ecal/python/copyTrivialAlignEE_cfg.py
  CondTools/Ecal/python/copyTrivialAlignES_cfg.py
  CondTools/Ecal/python/srCondWrite_cfg.py
  CondTools/Ecal/src/EcalSRPHandler.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#27865 backporting generator filter modifications to CMSSW_7_1_X
  GeneratorInterface/Core/interface/EmbeddingHepMCFilter.h
  GeneratorInterface/Core/src/EmbeddingHepMCFilter.cc
  GeneratorInterface/Core/src/HepMCFilterDriver.cc
  TauAnalysis/MCEmbeddingTools/python/EmbeddingPythia8Hadronizer_cfi.py
Labels: analysis-approved, comparison-available, fully-signed, generators-approved, orp-approved, simulation-approved, tests-approved

#27906 packport LHEJetFilter 7_1_X
  GeneratorInterface/GenFilters/BuildFile.xml
  GeneratorInterface/GenFilters/python/LHEJetFilter_cfi.py
  GeneratorInterface/GenFilters/src/LHEJetFilter.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#27864 backporting generator filter modifications to CMSSW_9_3_X
  GeneratorInterface/Core/interface/EmbeddingHepMCFilter.h
  GeneratorInterface/Core/src/EmbeddingHepMCFilter.cc
  TauAnalysis/MCEmbeddingTools/python/EmbeddingPythia8Hadronizer_cfi.py
Labels: analysis-approved, comparison-available, fully-signed, generators-approved, orp-approved, simulation-approved, tests-approved

#27902 rebase of LHEJetFilter
  GeneratorInterface/GenFilters/BuildFile.xml
  GeneratorInterface/GenFilters/python/LHEJetFilter_cfi.py
  GeneratorInterface/GenFilters/src/LHEJetFilter.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#27863 backporting generator filter modifications to CMSSW_10_2_X
  GeneratorInterface/Core/interface/EmbeddingHepMCFilter.h
  GeneratorInterface/Core/src/EmbeddingHepMCFilter.cc
  TauAnalysis/MCEmbeddingTools/python/EmbeddingPythia8Hadronizer_cfi.py
Labels: analysis-approved, comparison-available, fully-signed, generators-approved, orp-approved, simulation-approved, tests-approved

#27881 HCALDQM: HB TDC fix (10_6_X backport)
  DQM/HcalCommon/interface/ValueQuantity.h
  DQM/HcalTasks/interface/DigiTask.h
  DQM/HcalTasks/plugins/DigiTask.cc
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27924 [DQM][backport] Migrated subsystem availability per lumi plot to softFED
  DQM/Integration/python/clients/info_dqm_sourceclient-live_cfg.py
  DQMServices/Components/BuildFile.xml
  DQMServices/Components/plugins/DQMProvInfo.cc
  DQMServices/Components/plugins/DQMProvInfo.h
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27812 backport of LHEJetFilter
  GeneratorInterface/GenFilters/BuildFile.xml
  GeneratorInterface/GenFilters/python/LHEJetFilter_cfi.py
  GeneratorInterface/GenFilters/src/LHEJetFilter.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#27937 Add a data based relval test wf with lumi boundary crossing
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27961 Support concurrent LuminosityBlocks in HLTrigReport
  HLTrigger/HLTanalyzers/plugins/HLTrigReport.cc
  HLTrigger/HLTanalyzers/plugins/HLTrigReport.h
  HLTrigger/HLTanalyzers/test/BuildFile.xml
  HLTrigger/HLTanalyzers/test/TestHLTrigReport.cpp
  HLTrigger/HLTanalyzers/test/comparison_logs/event_event.log
  HLTrigger/HLTanalyzers/test/comparison_logs/event_job.log
  HLTrigger/HLTanalyzers/test/comparison_logs/event_lumi.log
  HLTrigger/HLTanalyzers/test/comparison_logs/event_run.log
  HLTrigger/HLTanalyzers/test/comparison_logs/lumi_event.log
  HLTrigger/HLTanalyzers/test/comparison_logs/lumi_job.log
  HLTrigger/HLTanalyzers/test/comparison_logs/lumi_lumi.log
  HLTrigger/HLTanalyzers/test/comparison_logs/lumi_run.log
  HLTrigger/HLTanalyzers/test/comparison_logs/never_event.log
  HLTrigger/HLTanalyzers/test/comparison_logs/never_job.log
  HLTrigger/HLTanalyzers/test/comparison_logs/never_lumi.log
  HLTrigger/HLTanalyzers/test/comparison_logs/never_run.log
  HLTrigger/HLTanalyzers/test/comparison_logs/run_event.log
  HLTrigger/HLTanalyzers/test/comparison_logs/run_job.log
  HLTrigger/HLTanalyzers/test/comparison_logs/run_lumi.log
  HLTrigger/HLTanalyzers/test/comparison_logs/run_run.log
  HLTrigger/HLTanalyzers/test/test_hltrigreport.sh
  HLTrigger/HLTanalyzers/test/test_hltrigreport_base_cfg.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_event_event.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_event_job.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_event_lumi.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_event_run.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_lumi_event.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_lumi_job.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_lumi_lumi.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_lumi_run.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_never_event.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_never_job.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_never_lumi.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_never_run.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_run_event.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_run_job.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_run_lumi.py
  HLTrigger/HLTanalyzers/test/test_hltrigreport_run_run.py
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#27979 Run3-hgx220 Convert DDHGCalTBModule algorithm for DD4Hep
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalTBModule-algorithm.xml
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalTBModule.cc
  Geometry/HGCalCommonData/python/testHGCalTBModuleXML_cfi.py
  Geometry/HGCalCommonData/test/python/dumpHGCalTBModuleGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalTBModuleGeometry_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#27935 [HGCal] dEdx weights and plots
  SimTracker/TrackerMaterialAnalysis/plugins/MaterialAccountingGroup.cc
  SimTracker/TrackerMaterialAnalysis/plugins/TrackingMaterialAnalyser.cc
  SimTracker/TrackerMaterialAnalysis/plugins/TrackingMaterialAnalyser.h
  SimTracker/TrackerMaterialAnalysis/plugins/TrackingMaterialProducer.cc
  SimTracker/TrackerMaterialAnalysis/plugins/TrackingMaterialProducer.h
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForHGCalPhaseII_cff.py
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForHGCalPhaseII_cfi.py
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseII_cfi.py
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseI_cfi.py
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_cfi.py
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialProducerHGCal_cff.py
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialProducerHGCal_cfi.py
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialProducer_cfi.py
  SimTracker/TrackerMaterialAnalysis/test/dEdxWeights.ipynb
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForHGCalPhaseII.py
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino_ForHGCalPhaseII.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27748 HCAL DQMOffline: adding rechits spectra with enabled cleaning
  DQMOffline/Hcal/interface/HcalRecHitsAnalyzer.h
  DQMOffline/Hcal/src/HcalRecHitsAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27984 Tracker Alignment: update PV Validation tool as used in Ultra-Legacy
  Alignment/OfflineValidation/interface/PVValidationHelpers.h
  Alignment/OfflineValidation/macros/FitPVResiduals.C
  Alignment/OfflineValidation/macros/MultiRunAndPlotPVValidation.C
  Alignment/OfflineValidation/plugins/PrimaryVertexValidation.cc
  Alignment/OfflineValidation/plugins/PrimaryVertexValidation.h
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexValidationTemplates.py
  Alignment/OfflineValidation/test/PVValidation_T_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27991 Removed unimplemented move constructor from StorageAccount
  Utilities/StorageFactory/interface/StorageAccount.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27992 Explicitly declare copy assignment for bqueue
  TrackingTools/PatternTools/interface/bqueue.h
  TrackingTools/PatternTools/test/bqueue_t.cpp
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27993 Removed implicitly dropped move assignment from RectangularEtaPhiTrackingRegion
  RecoTracker/TkTrackingRegions/interface/RectangularEtaPhiTrackingRegion.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27994 stronger edm::propagate_const const-correctness
  FWCore/Utilities/interface/propagate_const.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27823 Simulation of APV dynamic gain
  SimGeneral/MixingModule/python/SiStripSimParameters_cfi.py
  SimTracker/SiStripDigitizer/data/pulse_2016.txt
  SimTracker/SiStripDigitizer/plugins/SiStripDigitizer.cc
  SimTracker/SiStripDigitizer/plugins/SiStripDigitizer.h
  SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc
  SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, requires-external, simulation-approved, tests-approved

#27941 Add SiStripApvSimulationParameters database object and record
  CalibTracker/SiStripESProducers/plugins/real/SiStripApvSimulationParametersESProducer.cc
  CondCore/SiStripPlugins/plugins/plugin.cc
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
  CondFormats/DataRecord/interface/SiStripCondDataRecords.h
  CondFormats/DataRecord/src/SiStripCondDataRecords.cc
  CondFormats/PhysicsToolsObjects/interface/Histogram3D.icc
  CondFormats/SiStripObjects/BuildFile.xml
  CondFormats/SiStripObjects/interface/SiStripApvSimulationParameters.h
  CondFormats/SiStripObjects/src/SiStripApvSimulationParameters.cc
  CondFormats/SiStripObjects/src/T_EventSetup_SiStrip.cc
  CondFormats/SiStripObjects/src/classes_def.xml
  CondFormats/SiStripObjects/src/headers.h
  CondFormats/SiStripObjects/test/testSerializationSiStripObjects.cpp
  CondTools/SiStrip/plugins/SiStripApvSimulationParametersBuilder.cc
  CondTools/SiStrip/test/SiStripApvSimulationParametersBuilder_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, requires-external, tests-approved

#27982 reintroduce missing lseek() for header-less files
  EventFilter/Utilities/src/EvFDaqDirector.cc
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#28006 Fix ExpandVisitor.result() to work also with an empty result
  FWCore/ParameterSet/python/SequenceTypes.py
Labels: bug-fix, code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27895 Add EDProducers for mkFit
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  RecoTracker/MkFit/BuildFile.xml
  RecoTracker/MkFit/README.md
  RecoTracker/MkFit/interface/MkFitHitIndexMap.h
  RecoTracker/MkFit/interface/MkFitInputWrapper.h
  RecoTracker/MkFit/interface/MkFitOutputWrapper.h
  RecoTracker/MkFit/plugins/BuildFile.xml
  RecoTracker/MkFit/plugins/MkFitInputConverter.cc
  RecoTracker/MkFit/plugins/MkFitOutputConverter.cc
  RecoTracker/MkFit/plugins/MkFitProducer.cc
  RecoTracker/MkFit/python/customizeInitialStepOnly.py
  RecoTracker/MkFit/python/customizeInitialStepToMkFit.py
  RecoTracker/MkFit/python/mkFitInputConverter_cfi.py
  RecoTracker/MkFit/src/MkFitHitIndexMap.cc
  RecoTracker/MkFit/src/MkFitInputWrapper.cc
  RecoTracker/MkFit/src/MkFitOutputWrapper.cc
  RecoTracker/MkFit/src/classes.h
  RecoTracker/MkFit/src/classes_def.xml
  Validation/RecoTrack/python/plotting/trackingPlots.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, pdmv-approved, reconstruction-approved, tests-approved, upgrade-approved

#27978 DD4hep: DDFilteredView Cleanup and One More Test
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryBuilder.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryBuilder.h
  Geometry/DTGeometryBuilder/test/BuildFile.xml
  Geometry/DTGeometryBuilder/test/dtGeometry.log.org
  Geometry/DTGeometryBuilder/test/dummyMain.cpp
  Geometry/DTGeometryBuilder/test/runTest.sh
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27866 Scenario2026D49: no Overlaps inside the Muon System and all MB4 Shiel…
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2026D49Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D49_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/cms/2026/v3/cms.xml
  Geometry/CMSCommonData/data/muonBase/2026/v3/muonBase.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D49XML_cfi.py
  Geometry/MuonCommonData/data/me0/TDR_Dev/v2/me0.xml
  Geometry/MuonCommonData/data/rpcf/2026/v2/rpcf.xml
Labels: code-checks-approved, comparison-available, geometry-pending, operations-approved, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-approved

#27958 Fix mix-up between the physical and the trigger chamber number in upgrade CSC motherboard
  L1Trigger/CSCTriggerPrimitives/interface/GEMCoPadProcessor.h
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/GEMCoPadProcessor.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#27986 Remove EcalDeadChannelRecoveryNN
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/BuildFile.xml
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/interface/EcalDeadChannelRecoveryAlgos.h
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/interface/EcalDeadChannelRecoveryBDTG.h
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/interface/EcalDeadChannelRecoveryNN.h
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/src/EcalDeadChannelRecoveryNN.cc
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/BuildFile.xml
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/DeadCells2448.txt
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/EBDeadCellsEach5.txt
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/EEDeadCellsEach5.txt
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/RecoAllKilledAndCorrected_002_cfg.py
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/plugins/EcalChannelKiller.cc
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/plugins/EcalChannelKiller.h
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/plugins/EcalDeadChannelRecoveryAnalyzer.cc
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/plugins/EcalDeadChannelRecoveryProducers.cc
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/plugins/EcalDeadChannelRecoveryProducers.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27997 DD4hep: HGCalTBModule Algo Bugfix
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalTBModule.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#27998 Removed move assignment op from SeedingLayerSetsBuilder
  RecoTracker/TkSeedingLayers/interface/SeedingLayerSetsBuilder.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#28003 Removed unimplementable assignment ops from TrackerAlignableIndexer
  Alignment/TrackerAlignment/interface/TrackerAlignableIndexer.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#28004 Add support for custom deleter to edm::ReusableObjectHolder
  FWCore/Utilities/interface/ReusableObjectHolder.h
  FWCore/Utilities/test/reusableobjectholder_t.cppunit.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#28005 improve upgrade PU assignment
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27903 DQMIO lumisection extraction script
  DQMServices/Components/scripts/dqmiolumiharvest.py
  DQMServices/Components/scripts/root2sqlite.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#28001 Removed assignment ops from ProcessCallGraph
  HLTrigger/Timer/interface/ProcessCallGraph.h
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#28014 Corrected Egamma 2018 UL PF cluster corrections
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27934 Data and MC global tags for 2018 UL [10_6_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#27916 [10.6.X] Fix simulation of the pixel bad components on the FED channel basis for PreMixing
  SimTracker/SiPixelDigitizer/plugins/PreMixingSiPixelWorker.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.h
Labels: backport-ok, bug-fix, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27936 APE tool: Trend plots, some minor fixes: Backport of #27656
  Alignment/APEEstimation/data/lumiperrun2017.txt
  Alignment/APEEstimation/data/lumiperrun2018.txt
  Alignment/APEEstimation/plugins/ApeEstimator.cc
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitter.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitterTemplates.py
  Alignment/APEEstimation/test/autoSubmitter/config.ini
  Alignment/APEEstimation/test/autoSubmitter/helpers.py
  Alignment/APEEstimation/test/batch/startSkim.py
  Alignment/APEEstimation/test/cfgTemplate/apeEstimator_cfg.py
  Alignment/APEEstimation/test/plottingTools/drawIterations.py
  Alignment/APEEstimation/test/plottingTools/drawResults.py
  Alignment/APEEstimation/test/plottingTools/drawTrend.py
  Alignment/APEEstimation/test/plottingTools/resultPlotter.py
  Alignment/APEEstimation/test/plottingTools/trendPlotter.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#27882 Disabled PCA inputs for deepTau v2 (10_6_X)
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Era_Run3_cff.py
  Configuration/Eras/python/Modifier_run2_tau_ul_2016_cff.py
  Configuration/Eras/python/Modifier_run2_tau_ul_2018_cff.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: analysis-pending, backport-ok, comparison-available, operations-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#27682 add MTD related hits plots
  Validation/RecoTrack/interface/MTVHistoProducerAlgoForTracker.h
  Validation/RecoTrack/python/MTVHistoProducerAlgoForTrackerBlock_cfi.py
  Validation/RecoTrack/python/MultiTrackValidator_cfi.py
  Validation/RecoTrack/src/MTVHistoProducerAlgoForTracker.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#28019 DD4hep: get a current node SpecPar value by name
  DetectorDescription/DDCMS/src/DDFilteredView.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#28000 Explicitly tell compiler to generate methods for SimplifiedGeometry
  FastSimulation/SimplifiedGeometryPropagator/interface/SimplifiedGeometry.h
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#28017 Added a tool to list MEs inside a DQMIO file
  DQMServices/Components/scripts/dqmiolistmes.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27624 Remove genreflex workaround.
  Fireworks/Core/interface/FWTriggerTableView.h
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#28011 Phase2-hgx220 Convert DDHGCalEEAlgo to DD4Hep format
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalEEAlgo.cc
  Geometry/HGCalCommonData/test/python/dumpHGCalEEGeometry_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#28027 Removed __user__ option in Skeleton generator
  FWCore/Skeletons/python/pkg.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27686 L1 track trigger TTTrack mods
  DQM/SiOuterTracker/plugins/OuterTrackerMonitorTTTrack.cc
  DataFormats/L1TrackTrigger/interface/TTTrack.h
  DataFormats/L1TrackTrigger/interface/TTTrack_TrackWord.h
  DataFormats/L1TrackTrigger/src/TTTrack_TrackWord.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#28032 Temporarily revert "Disabled PCA inputs for deepTau v2 (10_6_X)"
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Era_Run3_cff.py
  Configuration/Eras/python/Modifier_run2_tau_ul_2016_cff.py
  Configuration/Eras/python/Modifier_run2_tau_ul_2018_cff.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: analysis-pending, comparison-pending, operations-approved, orp-approved, pending-signatures, reconstruction-pending, tests-started, xpog-pending

#28012 Fixup of L1REPACK for tasks
  HLTrigger/Configuration/python/CustomConfigs.py
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#27988 Truncate pt of PackedCandidate
  DataFormats/PatCandidates/src/PackedCandidate.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#28025 A fix for DQM HV per lumi plot
  DQMServices/Components/plugins/DQMProvInfo.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27945 Fixing VID return value for HEEP Trk Iso: 10_6_X
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleTrkPtIsoCut.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27826 Add customized NanoAOD content for JetMET JERC studies
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/PatAlgos/python/tools/jetCollectionTools.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#28046 Restore Disabled PCA inputs for deepTau v2 (10_6_X)
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Era_Run3_cff.py
  Configuration/Eras/python/Modifier_run2_tau_ul_2016_cff.py
  Configuration/Eras/python/Modifier_run2_tau_ul_2018_cff.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#28031 Python3: Changes needed to build cmssw with python3 as default
  CondFormats/Serialization/python/condformats_serialization_generate.py
  FWCore/Utilities/scripts/edmCheckClassTransients
  FWCore/Utilities/scripts/edmCheckClassVersion
Labels: code-checks-approved, comparison-available, core-approved, db-approved, fully-signed, orp-approved, tests-approved

#28022 Fix GCC 9 shadowing compiler warnings in Core (2nd try)
  DataFormats/Common/interface/RangeMap.h
  DataFormats/Common/src/RefCoreStreamer.cc
  DataFormats/Common/test/containermask_t.cppunit.cc
  DataFormats/Common/test/ptr_t.cppunit.cc
  DataFormats/Common/test/reftobaseprod_t.cppunit.cc
  DataFormats/Common/test/testOwnVector.cc
  DataFormats/Common/test/testValueMapNew.cc
  DataFormats/FWLite/src/DataGetterHelper.cc
  DataFormats/Provenance/src/ProductProvenanceRetriever.cc
  DataFormats/Provenance/src/ProductRegistry.cc
  DataFormats/Provenance/test/indexIntoFile3_t.cppunit.cc
  FWCore/Catalog/test/FileLocator_t.cpp
  FWCore/Concurrency/src/SerialTaskQueue.cc
  FWCore/Concurrency/test/limitedtaskqueue_t.cppunit.cpp
  FWCore/Concurrency/test/waitingtasklist_t.cppunit.cpp
  FWCore/Framework/interface/GetterOfProducts.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/OutputModuleCommunicatorT.cc
  FWCore/Framework/src/Principal.cc
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/SubProcess.cc
  FWCore/Framework/src/Worker.h
  FWCore/Framework/src/throwIfImproperDependencies.cc
  FWCore/Framework/test/DummyFinder.h
  FWCore/Framework/test/Event_t.cpp
  FWCore/Framework/test/dependentrecord_t.cppunit.cc
  FWCore/Framework/test/eventsetup_t.cppunit.cc
  FWCore/Framework/test/generichandle_t.cppunit.cc
  FWCore/Framework/test/intersectingiovrecordintervalfinder_t.cppunit.cc
  FWCore/Framework/test/test_catch2notTP_MergeableRunProductMetadata.cc
  FWCore/Framework/test/throwIfImproperDependencies_t.cppunit.cc
  FWCore/Integration/test/OtherThingAnalyzer.cc
  FWCore/Integration/test/ProcessHistory_t.cpp
  FWCore/ParameterSet/interface/PluginDescription.h
  FWCore/ParameterSet/src/ParameterDescription.cc
  FWCore/ParameterSet/src/ParameterSetConverter.cc
  FWCore/ParameterSet/test/parameterSetDescription_t.cc
  FWCore/PluginManager/test/cacheparser_t.cc
  FWCore/ServiceRegistry/test/serviceregistry_t.cppunit.cpp
  FWCore/ServiceRegistry/test/servicesmanager_t.cppunit.cc
  FWCore/Services/plugins/DependencyGraph.cc
  FWCore/Services/plugins/SimpleMemoryCheck.cc
  FWCore/Services/test/test_catch2_SiteLocalConfigService.cc
  IOMC/RandomEngine/test/TestRandomNumberServiceGlobal.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#28054 DDAngular: Minor bug fix of a debug message
  DetectorDescription/DDCMS/plugins/dd4hep/DDAngular.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#28037 [DQM]Removed a nop call of DQMStore::setVerbose()
  DQM/HLTEvF/plugins/FourVectorHLT.cc
  DQM/SiStripCommissioningClients/src/CommissioningHistograms.cc
  DQM/SiStripCommissioningClients/src/SiStripCommissioningOfflineClient.cc
  DQM/SiStripCommissioningSources/src/SiStripCommissioningSource.cc
  DQM/TrigXMonitorClient/src/HLTScalersClient.cc
  DQMOffline/CalibTracker/plugins/SiStripQualityHotStripIdentifierRoot.cc
  DQMOffline/Trigger/plugins/EgHLTOfflineSummaryClient.cc
  DQMOffline/Trigger/plugins/HLTInclusiveVBFClient.cc
  DQMOffline/Trigger/plugins/HLTOverallSummary.cc
  GeneratorInterface/RivetInterface/plugins/RivetAnalyzer.cc
  RecoLocalCalo/EcalRecProducers/test/EcalLocalRecoTask.cc
  SimG4Core/MagneticField/test/FieldStepWatcher.cc
  Validation/EcalHits/src/EcalBarrelSimHitsValidation.cc
  Validation/EcalHits/src/EcalEndcapSimHitsValidation.cc
  Validation/EcalHits/src/EcalPreshowerSimHitsValidation.cc
  Validation/EcalHits/src/EcalSimHitsValidation.cc
  Validation/GlobalHits/src/GlobalHitsProdHistStripper.cc
  Validation/RecoEgamma/plugins/ConversionPostprocessing.cc
  Validation/RecoEgamma/plugins/PhotonPostprocessing.cc
  Validation/TrackerHits/src/TrackerHitAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, generators-approved, hlt-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#28048 HGCal - bugfix: Fix clamp range in tiling
  DataFormats/HGCalReco/interface/TICLLayerTile.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalLayerTiles.h
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27985 DQM tau miniaod validation CMSSW_106X
  Configuration/StandardSequences/python/Validation_cff.py
  Validation/RecoTau/BuildFile.xml
  Validation/RecoTau/interface/TauValidationMiniAOD.h
  Validation/RecoTau/python/DQMMCValidation_cfi.py
  Validation/RecoTau/python/DQMSequences_cfi.py
  Validation/RecoTau/python/RecoTauValidationMiniAOD_cfi.py
  Validation/RecoTau/python/RecoTauValidation_cff.py
  Validation/RecoTau/src/SealModule.cc
  Validation/RecoTau/src/TauValidationMiniAOD.cc
Labels: comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#28043 Backport of #27988 (Truncate pt of PackedCandidate)
  DataFormats/PatCandidates/src/PackedCandidate.cc
Labels: analysis-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#28064 Add AAA fallback to DQMRootSource
  DQMServices/FwkIO/plugins/DQMRootSource.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27917 Add energy regression and particle identification to RecoHGCal/TICL (reopened)
  DataFormats/HGCalReco/interface/Trackster.h
  DataFormats/HGCalReco/src/classes_def.xml
  RecoHGCal/TICL/interface/GlobalCache.h
  RecoHGCal/TICL/interface/PatternRecognitionAlgoBase.h
  RecoHGCal/TICL/plugins/BuildFile.xml
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.h
  RecoHGCal/TICL/plugins/PatternRecognitionbyMultiClusters.h
  RecoHGCal/TICL/plugins/TrackstersProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved, upgrade-approved

#28028 Add APV simulation in PreMixingSiStripWorker
  SimTracker/SiStripDigitizer/plugins/PreMixingSiStripWorker.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, requires-external, simulation-approved, tests-approved

#28024 Introduce Special RelVals for SiStrip APV dynamic gain simulation
  CalibTracker/SiStripESProducers/plugins/real/SiStripApvSimulationParametersESProducer.cc
  CondTools/SiStrip/test/SiStripApvSimulationParametersBuilder_cfg.py
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_premix.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  SimTracker/SiStripDigitizer/python/customizeSiStripAPVDynamicGainSimulation.py
Labels: alca-approved, code-checks-approved, comparison-available, db-pending, orp-approved, pdmv-approved, pending-signatures, requires-external, simulation-approved, tests-approved, upgrade-approved

#28021 Python3: Changes needed to run runTheMatrix with python2/3
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/Applications/scripts/cmsDriver.py
  Configuration/PyReleaseValidation/python/MatrixReader.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/scripts/das-selected-lumis.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
  FWCore/PythonUtilities/python/LumiList.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27942 Run3-hgx219 Convert algorithm for DDHGCalTBModuleX
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalTBModuleX-algorithm.xml
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalTBModuleX.cc
  Geometry/HGCalCommonData/python/testHGCalTBModuleXXML_cfi.py
  Geometry/HGCalCommonData/test/python/dumpHGCalTBModuleXGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalTBModuleXGeometry_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#27731 Allow for ME0 triggers to be produced from pads directly
  L1Trigger/ME0Trigger/interface/ME0TriggerBuilder.h
  L1Trigger/ME0Trigger/plugins/ME0TriggerProducer.cc
  L1Trigger/ME0Trigger/plugins/ME0TriggerProducer.h
  L1Trigger/ME0Trigger/python/me0TriggerDigis_cfi.py
  L1Trigger/ME0Trigger/src/ME0TriggerBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#27947 ME0TriggerPseudoBuilder mistook GEM strip pitch unit as radiu and this commit is to fix it
  L1Trigger/ME0Trigger/src/ME0TriggerPseudoBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#28068 Run3-hcx227 Small fixes to dd4hep algorithms
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalEE-algorithm.xml
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalHEsil-algorithm.xml
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalEEAlgo.cc
  Geometry/HcalAlgo/data/cms-test-ddhcalHEPhase1-algorithm.xml
  Geometry/HcalAlgo/plugins/dd4hep/DDHCalEndcapModuleAlgo.cc
  Geometry/HcalAlgo/test/data/world.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#27957 Update GE2/1 LUTs for GE2/1-ME2/1 integrated local trigger
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboardLUT.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#27987 Adding trigonometric functions into the FormulaEvaluator
  CommonTools/Utils/src/FormulaEvaluator.cc
  CommonTools/Utils/test/testFormulaEvaluator.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#28056 Phase2-hgx221 Convert HGCal algorithm for mixed layer to dd4hep
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalHEAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#28066 Run3-hcx226 DD4Hep algorithm for HCAL barrel
  Geometry/HcalAlgo/data/cms-test-ddhcalHB-algorithm.xml
  Geometry/HcalAlgo/plugins/DDHCalBarrelAlgo.cc
  Geometry/HcalAlgo/plugins/dd4hep/DDHCalBarrelAlgo.cc
  Geometry/HcalAlgo/test/python/dumpHBGeom_cfg.py
  Geometry/HcalAlgo/test/python/testHBGeom_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#28061 Nano AOD step added for 2016 standard and pileup relvals
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-pending, pending-signatures, tests-approved, upgrade-pending

#27990 Config files needed to integrate PPS simhits into the cms simulation
  Configuration/StandardSequences/python/Eras.py
  SimG4Core/Application/python/g4SimHits_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#27608 SimPPS/RPDigiProducer package for PPS Full simulation
  SimPPS/RPDigiProducer/BuildFile.xml
  SimPPS/RPDigiProducer/interface/RPEnergyDepositUnit.h
  SimPPS/RPDigiProducer/interface/RPSignalPoint.h
  SimPPS/RPDigiProducer/interface/RPSimTypes.h
  SimPPS/RPDigiProducer/plugins/BuildFile.xml
  SimPPS/RPDigiProducer/plugins/DeadChannelsManager.cc
  SimPPS/RPDigiProducer/plugins/DeadChannelsManager.h
  SimPPS/RPDigiProducer/plugins/RPDetDigitizer.cc
  SimPPS/RPDigiProducer/plugins/RPDetDigitizer.h
  SimPPS/RPDigiProducer/plugins/RPDigiProducer.cc
  SimPPS/RPDigiProducer/plugins/RPDisplacementGenerator.cc
  SimPPS/RPDigiProducer/plugins/RPDisplacementGenerator.h
  SimPPS/RPDigiProducer/plugins/RPGaussianTailNoiseAdder.cc
  SimPPS/RPDigiProducer/plugins/RPGaussianTailNoiseAdder.h
  SimPPS/RPDigiProducer/plugins/RPHitChargeConverter.cc
  SimPPS/RPDigiProducer/plugins/RPHitChargeConverter.h
  SimPPS/RPDigiProducer/plugins/RPLinearChargeCollectionDrifter.cc
  SimPPS/RPDigiProducer/plugins/RPLinearChargeCollectionDrifter.h
  SimPPS/RPDigiProducer/plugins/RPLinearChargeDivider.cc
  SimPPS/RPDigiProducer/plugins/RPLinearChargeDivider.h
  SimPPS/RPDigiProducer/plugins/RPLinearInduceChargeOnStrips.cc
  SimPPS/RPDigiProducer/plugins/RPLinearInduceChargeOnStrips.h
  SimPPS/RPDigiProducer/plugins/RPPileUpSignals.cc
  SimPPS/RPDigiProducer/plugins/RPPileUpSignals.h
  SimPPS/RPDigiProducer/plugins/RPVFATSimulator.cc
  SimPPS/RPDigiProducer/plugins/RPVFATSimulator.h
  SimPPS/RPDigiProducer/test/RPDigiProducerTest_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved
