Repository cms-sw/cmssw, pull requests merged in 2019-04, with the labels that each got.

#26233 Adding PUPPI combined isolation Working Points in miniAOD muon selector
  DataFormats/MuonReco/interface/Muon.h
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.h
  PhysicsTools/PatAlgos/python/producersLayer1/muonProducer_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26275 Activate Simulation of the Pixel Bad Components on the FED channel basis
  Configuration/AlCa/python/autoCond.py
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26234 Run2-TB33 Enable test beam setup to dump geometry for cmsShow
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcal.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalEE.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalHE.xml
  Geometry/HGCalCommonData/plugins/DDHGCalTBModuleX.cc
  Geometry/HGCalCommonData/plugins/DDHGCalTBModuleX.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26280 update job splitting for 2018 HI data workflows
  Configuration/PyReleaseValidation/python/MatrixInjector.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26256 Run2-TB34 Update some of the code for material budget calculation and re-arrange
  SimG4CMS/HGCalTestBeam/interface/AHCalSD.h
  SimG4CMS/HGCalTestBeam/interface/HGCalTB16SD01.h
  SimG4CMS/HGCalTestBeam/interface/HGCalTBMB.h
  SimG4CMS/HGCalTestBeam/plugins/AHCalSD.cc
  SimG4CMS/HGCalTestBeam/plugins/HGCalTB16SD01.cc
  SimG4CMS/HGCalTestBeam/plugins/HGCalTBAnalyzer.cc
  SimG4CMS/HGCalTestBeam/plugins/HGCalTBCheckGunPosition.cc
  SimG4CMS/HGCalTestBeam/plugins/HGCalTBMB.cc
  SimG4CMS/HGCalTestBeam/plugins/module.cc
  SimG4CMS/HGCalTestBeam/python/hgcalTBMBCERN_cfi.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimCERNMB_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#26306 speed up Mixins.py
  FWCore/ParameterSet/python/Mixins.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26270 HBHE: Mahi arrival time
  RecoLocalCalo/HcalRecAlgos/interface/MahiFit.h
  RecoLocalCalo/HcalRecAlgos/src/MahiFit.cc
  RecoLocalCalo/HcalRecAlgos/src/parseHBHEPhase1AlgoDescription.cc
  RecoLocalCalo/HcalRecAlgos/test/MahiDebugger.cc
  RecoLocalCalo/HcalRecProducers/python/HBHEMahiParameters_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26194 HGCAL Clue algorithm 106 x
  RecoEgamma/EgammaTools/src/EgammaPCAHelper.cc
  RecoLocalCalo/HGCalRecAlgos/interface/HGCal3DClustering.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalCLUEAlgo.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalClusteringAlgoBase.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalImagingAlgo.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalLayerClusterAlgoFactory.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalCLUEAlgo.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalImagingAlgo.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalLayerClusterPluginFactory.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalLayerClusterProducer.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalMultiClusterProducer.cc
  RecoLocalCalo/HGCalRecProducers/python/hgcalLayerClusters_cff.py
  Validation/HGCalValidation/interface/HGCalValidator.h
  Validation/HGCalValidation/interface/HGVHistoProducerAlgo.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#26230 RecoParticleFlow/PFProducers - Improve how the PFEGammaFilters and PFMuonAlgo are constructed
  RecoParticleFlow/PFProducer/interface/PFAlgo.h
  RecoParticleFlow/PFProducer/interface/PFEGammaFilters.h
  RecoParticleFlow/PFProducer/interface/PFMuonAlgo.h
  RecoParticleFlow/PFProducer/plugins/PFProducer.cc
  RecoParticleFlow/PFProducer/plugins/PFProducer.h
  RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporterWithVeto.cc
  RecoParticleFlow/PFProducer/src/PFAlgo.cc
  RecoParticleFlow/PFProducer/src/PFEGammaFilters.cc
  RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26277 Adding E, R and Z ranges to CloseByParticleGun generator
  Configuration/Generator/python/CloseByParticle_Photon_ERZRanges_cfi.py
  IOMC/EventVertexGenerators/src/PassThroughEvtVtxGenerator.cc
  IOMC/ParticleGuns/interface/CloseByParticleGunProducer.h
  IOMC/ParticleGuns/src/CloseByParticleGunProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, simulation-approved, tests-approved

#26311 Make sure isPixel is always initialized in TestAssociator
  SimTracker/TrackerHitAssociation/test/TestAssociator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26313 cleanup dependency: DataFormats/Provenance does not depend on MessageLogger
  DataFormats/Provenance/BuildFile.xml
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26310 Make Modifier.isChosen() private
  Configuration/StandardSequences/python/Eras.py
  FWCore/ParameterSet/python/Config.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, operations-approved, orp-approved, tests-approved

#26307 Adapt ETL numbering scheme to new forward volume hierarchy (scenario D41, HGCal v10)
  Geometry/MTDCommonData/src/ETLNumberingScheme.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26309 Make sure all member variables are initialized in RPCEMapSourceHandler
  CondTools/RPC/src/RPCEMapSourceHandler.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26318 Fix GEM eMap and PF calibration in 2017 ideal simulation GT
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26201 DT calibration updates2019
  CalibMuon/DTCalibration/interface/DTSegmentSelector.h
  CalibMuon/DTCalibration/plugins/DTResidualCalibration.cc
  CalibMuon/DTCalibration/plugins/DTResidualCalibration.h
  CalibMuon/DTCalibration/plugins/DTT0Calibration.cc
  CalibMuon/DTCalibration/plugins/DTT0Calibration.h
  CalibMuon/DTCalibration/plugins/DTTTrigOffsetCalibration.cc
  CalibMuon/DTCalibration/plugins/DTTTrigOffsetCalibration.h
  CalibMuon/DTCalibration/plugins/DTVDriftCalibration.cc
  CalibMuon/DTCalibration/plugins/DTVDriftCalibration.h
  CalibMuon/DTCalibration/plugins/DTVDriftSegmentCalibration.cc
  CalibMuon/DTCalibration/plugins/DTVDriftSegmentCalibration.h
  CalibMuon/DTCalibration/python/Workflow/CLIHelper.py
  CalibMuon/DTCalibration/python/Workflow/CrabHelper.py
  CalibMuon/DTCalibration/python/Workflow/DTCalibrationWorker.py
  CalibMuon/DTCalibration/python/Workflow/DTT0WireWorkflow.py
  CalibMuon/DTCalibration/python/Workflow/DTTtrigWorkflow.py
  CalibMuon/DTCalibration/python/Workflow/DTVdriftWorkflow.py
  CalibMuon/DTCalibration/python/Workflow/addPoolDBESSource.py
  CalibMuon/DTCalibration/python/dtCalibValidationFromMuons_cfg.py
  CalibMuon/DTCalibration/python/dtCalibValidationFromMuons_cfi.py
  CalibMuon/DTCalibration/python/dtResidualCalibration_cfi.py
  CalibMuon/DTCalibration/python/dtSegmentSelection_cfi.py
  CalibMuon/DTCalibration/python/dtT0WireCalibration_cfg.py
  CalibMuon/DTCalibration/python/dt_offlineAnalysis_common_cff.py
  CalibMuon/DTCalibration/python/messageLoggerDebug_cff.py
  CalibMuon/DTCalibration/scripts/allPlotsResiduals.py
  CalibMuon/DTCalibration/scripts/dtCalibrationOld
  CalibMuon/DTCalibration/src/DTSegmentSelector.cc
  DQM/DTMonitorModule/interface/DTCalibValidationFromMuons.h
  DQM/DTMonitorModule/plugins/plugins.cc
  DQM/DTMonitorModule/src/DTCalibValidationFromMuons.cc
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26289 Fix race condition in EventProcessor
  FWCore/Framework/interface/EventProcessor.h
  FWCore/Framework/src/EventProcessor.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26300 Pythia filter to focus on the probe side of B decays (backport)
  GeneratorInterface/GenFilters/interface/PythiaProbeFilter.h
  GeneratorInterface/GenFilters/src/PythiaProbeFilter.cc
  GeneratorInterface/GenFilters/src/SealModule.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26304 Fix a corner case in ClusterTPAssociationProducer
  SimTracker/TrackerHitAssociation/interface/ClusterTPAssociation.h
  SimTracker/TrackerHitAssociation/plugins/ClusterTPAssociationProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26226 Interface for external Pyquen #4790
  GeneratorInterface/PyquenInterface/BuildFile.xml
  GeneratorInterface/PyquenInterface/interface/PyquenWrapper.h
  GeneratorInterface/PyquenInterface/python/pyquenPythiaDefault_cff.py
  GeneratorInterface/PyquenInterface/src/HepEvt.F
  GeneratorInterface/PyquenInterface/src/PyquenHadronizer.cc
  GeneratorInterface/PyquenInterface/src/hepevt.inc
  GeneratorInterface/PyquenInterface/src/pyquen.F
  GeneratorInterface/PyquenInterface/test/PyquenAnalyzer.cc
  GeneratorInterface/PyquenInterface/test/PyquenAnalyzer.h
  GeneratorInterface/PyquenInterface/test/testPyquen.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#26247 [PPS] Track time selector for miniAOD lite format
  RecoCTPPS/TotemRPLocal/plugins/CTPPSLocalTrackLiteProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26248 BTagCalibration: Added protection against -ve eta values for SFs calculated on abs(eta)
  CondTools/BTau/src/BTagCalibrationReader.cc
  CondTools/BTau/test/BTagCalibrationStandalone.cpp
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26276 add necessary changes to handle dump import and fetch novel TrackerDetToDTCELinkCablingMap and DTCELinkId CondFormats
  CondCore/Utilities/BuildFile.xml
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26305 PPS: alignment from auto GT
  CalibPPS/ESProducers/python/ctppsAlignment_cff.py
  Configuration/AlCa/python/autoCond.py
  RecoCTPPS/ProtonReconstruction/python/ctppsProtons_cff.py
  Validation/CTPPS/test/year_2016/proton_reconstruction_LHC_data/test_reconstruction_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26267 DD4hep: Drop Namespace in Geometry Definition
  DetectorDescription/DDCMS/data/cms-tracker.xml
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/interface/Filter.h
  DetectorDescription/DDCMS/plugins/DDTECModuleAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTECPhiAltAlgo.cc
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  DetectorDescription/DDCMS/src/DDNamespace.cc
  DetectorDescription/DDCMS/src/Filter.cc
  DetectorDescription/DDCMS/test/python/testDDDetectorESProducer.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, requires-external, tests-approved

#26312 Added std namespace to avoid cxxmodule Ib errors
  DataFormats/FEDRawData/interface/DaqData.h
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, tests-approved

#26314 Phase2-hgx190 Modify the hit analyzer code to make tree or a set of histos
  Validation/HGCalValidation/test/HGCGeometryCheck.cc
  Validation/HGCalValidation/test/HGCHitValidation.cc
  Validation/HGCalValidation/test/runHGCalSimHitStudy_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26316 PPS geometry fix for Timing detectors
  Geometry/VeryForwardData/data/CTPPS_Diamond_2018/CTPPS_Diamond_Planes/CTPPS_Diamond_Plane3.xml
  Geometry/VeryForwardData/data/CTPPS_Diamond_2018/CTPPS_Diamond_Planes/CTPPS_Diamond_Plane4.xml
  Geometry/VeryForwardData/data/CTPPS_UFSD_Planes/CTPPS_UFSD_Plane4.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26297 change of the argument definition of some reco::Muon functions
  DataFormats/MuonReco/interface/Muon.h
  DataFormats/MuonReco/src/Muon.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26324 Added plots to monitor pixel clusterrepair algorithm
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1RecHits.cc
  DQM/SiPixelPhase1Track/python/SiPixelPhase1RecHits_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26331 Run2-hgx185 Add 2 algorithms for HGCal to DD4Hep format
  DetectorDescription/DDCMS/data/cms-test-ddhgcalcell-algorithm.xml
  DetectorDescription/DDCMS/data/testDDHGCalCellAlgorithm.xml
  DetectorDescription/DDCMS/plugins/DDHGCalCell.cc
  DetectorDescription/DDCMS/plugins/DDHGCalWafer.cc
  DetectorDescription/DDCMS/test/python/testDDHGCalCellAlgorithm.py
  DetectorDescription/DDCMS/test/runTest.sh
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26339 keep hidden valley and dark matter particles in miniAOD
  PhysicsTools/PatAlgos/python/slimming/prunedGenParticles_cfi.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26239 backport CSCCLCTPreTriggerDigi for ULHLT
  DataFormats/CSCDigi/interface/CSCCLCTPreTriggerDigi.h
  DataFormats/CSCDigi/interface/CSCCLCTPreTriggerDigiCollection.h
  DataFormats/CSCDigi/src/CSCCLCTPreTriggerDigi.cc
  DataFormats/CSCDigi/src/classes.h
  DataFormats/CSCDigi/src/classes_def.xml
Labels: comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26286 Pythia filter to focus on the probe side of B decays
  GeneratorInterface/GenFilters/interface/PythiaProbeFilter.h
  GeneratorInterface/GenFilters/src/PythiaProbeFilter.cc
  GeneratorInterface/GenFilters/src/SealModule.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26308 Properly handle a polymorphic exception in DTCCablingMapProducer
  CondTools/SiPhase2Tracker/plugins/DTCCablingMapProducer.cc
Labels: alca-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved, upgrade-approved

#26338 remove incorrect build dependencies on FWCore/PythonParameterSet
  FWCore/TestProcessor/test/BuildFile.xml
  Geometry/HcalCommonData/test/BuildFile.xml
  Geometry/HcalTowerAlgo/test/BuildFile.xml
  MuonAnalysis/MomentumScaleCalibration/bin/BuildFile.xml
Labels: analysis-pending, code-checks-approved, comparison-available, core-approved, geometry-approved, orp-approved, pending-signatures, tests-approved

#26344 MTD Geometry: avoid dependence on namespace in volume name string
  Geometry/MTDCommonData/src/ETLNumberingScheme.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26334 Added missing skipEvents to LHESource
  GeneratorInterface/LHEInterface/plugins/LHESource.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26353 move PythonFramework to PyDevParameterSet
  FWCore/PyDevParameterSet/interface/PyBind11ProcessDesc.h
  FWCore/PyDevParameterSet/src/PyBind11Module.h
  FWCore/PyDevParameterSet/src/PyBind11ProcessDesc.cc
  FWCore/PythonFramework/BuildFile.xml
  FWCore/PythonFramework/interface/PythonEventProcessor.h
  FWCore/PythonFramework/python/CmsRun.py
  FWCore/PythonFramework/src/PythonEventProcessor.cc
  FWCore/PythonFramework/src/PythonModule.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26330 Let DummyLHEAnalyzer test run out of the box
  GeneratorInterface/LHEInterface/test/DummyLHEAnalyzer.cc
  GeneratorInterface/LHEInterface/test/dumpLHE_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26301 Phase2-hgx189 Add specifics for HGCal V10 geometry
  Configuration/Eras/python/Era_Phase2C8_cff.py
  Configuration/Eras/python/Era_Phase2C8_timing_cff.py
  Configuration/Eras/python/Era_Phase2C8_timing_layer_bar_cff.py
  Configuration/Eras/python/Modifier_phase2_hgcalV10_cff.py
  Configuration/Geometry/python/dict2023Geometry.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/Eras.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26346 Phase2-hgx191 Fix the scintillator cell size for V10
  Geometry/HGCalCommonData/data/hgcalCons/v10/hgcalCons.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26356 Remove FWCore/PythonParameterSet dependencies from unit tests in FWCore/Integration
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/EDAlias_t.cpp
  FWCore/Integration/test/SwitchProducer_t.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26336 A small fix to dqmMemoryStats.py
  DQMServices/FileIO/python/DQM.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26321 Fix thread safety issue in FEDNumbering
  DataFormats/FEDRawData/interface/FEDNumbering.h
  DataFormats/FEDRawData/src/FEDNumbering.cc
  DataFormats/FEDRawData/test/BuildFile.xml
  DataFormats/FEDRawData/test/FEDNumbering_t.cpp
  EventFilter/SiStripRawToDigi/interface/SiStripFEDBufferComponents.h
Labels: code-checks-approved, comparison-available, compilation-warnings, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26340 keep hidden valley and dark matter particles in miniAOD [102X]
  PhysicsTools/PatAlgos/python/slimming/prunedGenParticles_cfi.py
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26341 keep hidden valley and dark matter particles in miniAOD [94X]
  PhysicsTools/PatAlgos/python/slimming/prunedGenParticles_cfi.py
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26342 Move fireworks exception handling to pybind11
  FWCore/PyDevParameterSet/interface/PyBind11Wrapper.h
  FWCore/PyDevParameterSet/interface/Python11ParameterSet.h
  FWCore/PyDevParameterSet/src/PyBind11ProcessDesc.cc
  FWCore/PyDevParameterSet/src/PyBind11Wrapper.cc
  Fireworks/FWInterface/BuildFile.xml
  Fireworks/FWInterface/src/FWPathsPopup.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved, visualization-approved

#26303 hadronizer for HToGG Minlo NNLOPS pLHE relval
  Configuration/Generator/python/Hadronizer_TuneCUETP8M1_13TeV_powhegEmissionVeto_2p_HToGG_M125_LHE_py8_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26251 HFStripFilter for Run 2 data
  DataFormats/METReco/interface/HcalPhase1FlagLabels.h
  RecoLocalCalo/HcalRecAlgos/BuildFile.xml
  RecoLocalCalo/HcalRecAlgos/interface/HFStripFilter.h
  RecoLocalCalo/HcalRecAlgos/python/hcalRecAlgoESProd_cfi.py
  RecoLocalCalo/HcalRecAlgos/src/HFStripFilter.cc
  RecoLocalCalo/HcalRecAlgos/src/HcalSeverityLevelComputer.cc
  RecoLocalCalo/HcalRecProducers/python/HFPhase1Reconstructor_cfi.py
  RecoLocalCalo/HcalRecProducers/src/HFPhase1Reconstructor.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26366 Removed unused variable from SiPixelFedFillerWordEventNumber
  CalibTracker/SiPixelTools/plugins/SiPixelFedFillerWordEventNumber.cc
Labels: alca-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#26273 Adjust a few reco tau config
  RecoTauTag/Configuration/python/RecoPFTauTag_cff.py
  RecoTauTag/RecoTau/plugins/PFRecoTauProducer.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroProducer.cc
  RecoTauTag/RecoTau/python/PFRecoTauProducer_cfi.py
  RecoTauTag/RecoTau/python/RecoTauPiZeroBuilderPlugins_cfi.py
  RecoTauTag/RecoTau/python/RecoTauPiZeroProducer_cff.py
  RecoTauTag/TauTagTools/test/training/skimming/buildBackgroundDataSet_cfg.py
  RecoTauTag/TauTagTools/test/training/skimming/buildSignalDataSet_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26359 Filter for semi-visible jet signal production [71X]
  GeneratorInterface/GenFilters/src/MCParticleModuloFilter.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26360 Filter for semi-visible jet signal production [102X]
  GeneratorInterface/GenFilters/src/MCParticleModuloFilter.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26372 fix fillDescr config of PFRecoTauChargedHadronProducer
  RecoTauTag/Configuration/python/RecoPFTauTag_cff.py
  RecoTauTag/RecoTau/plugins/PFRecoTauChargedHadronProducer.cc
  RecoTauTag/RecoTau/python/PFRecoTauChargedHadronProducer_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26375 Avoid conflict between HE and HGC in phase2 geometry when running an aged scenario
  SLHCUpgradeSimulations/Configuration/python/aging.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#26364 use python3 compatible syntax in DQMOffline packages
  DQMOffline/L1Trigger/python/L1TCommon.py
  DQMOffline/L1Trigger/python/L1TEGammaOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TEtSumJetOffline_cfi.py
  DQMOffline/L1Trigger/python/L1THistDefinitions_cff.py
  DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TTauOffline_cfi.py
  DQMOffline/Trigger/python/FSQHLTOfflineSource_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, l1-pending, orp-approved, pending-signatures, tests-approved

#26367 python3 compatibility in FWCore/ParameterSet
  FWCore/ParameterSet/python/Types.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26349 Bug fix for behavior after exceptions with concurrent lumis
  FWCore/Framework/interface/EventProcessor.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/TransitionProcessors.icc
  FWCore/Framework/test/MockEventProcessor.cc
  FWCore/Framework/test/MockEventProcessor.h
  FWCore/Framework/test/run_cmsRun.sh
  FWCore/Framework/test/stubs/ToyIntProducers.cc
  FWCore/Framework/test/testConcurrentLumiExceptions_cfg.py
  FWCore/Framework/test/testMaxEventsOutput_cfg.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26376 DummyLHEAnalyzer: add option not to print event
  GeneratorInterface/LHEInterface/test/DummyLHEAnalyzer.cc
  GeneratorInterface/LHEInterface/test/dumpLHE_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26368 python3 compatibility in PhysicsTools pieces of reco sequence
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  PhysicsTools/SelectorUtils/python/centralIDRegistry.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26231 DD4hep: Merge Development to a Usual Geometry Structure
  DetectorDescription/DDCMS/data/cms-2015-muon-geometry.xml
  DetectorDescription/DDCMS/interface/DDDetector.h
  DetectorDescription/DDCMS/interface/MuonNumbering.h
  DetectorDescription/DDCMS/interface/MuonSubDetector.h
  DetectorDescription/DDCMS/plugins/BuildFile.xml
  DetectorDescription/DDCMS/plugins/DDCMSDetector.cc
  DetectorDescription/DDCMS/plugins/DDDetectorESProducer.cc
  DetectorDescription/DDCMS/plugins/DDSpecParRegistryESProducer.cc
  DetectorDescription/DDCMS/plugins/DDTestDumpFile.cc
  DetectorDescription/DDCMS/plugins/DDTestDumpGeometry.cc
  DetectorDescription/DDCMS/plugins/DDTestNavigateGeometry.cc
  DetectorDescription/DDCMS/plugins/DDTestSpecPars.cc
  DetectorDescription/DDCMS/plugins/DDTestSpecParsFilter.cc
  DetectorDescription/DDCMS/plugins/DDTestVectors.cc
  DetectorDescription/DDCMS/plugins/DDVectorRegistryESProducer.cc
  DetectorDescription/DDCMS/src/DDDetector.cc
  DetectorDescription/DDCMS/src/ES_DDDetector.cc
  DetectorDescription/DDCMS/test/DDFilteredView.cppunit.cc
  DetectorDescription/DDCMS/test/python/testDDSpecParsFilterG4ProdCuts.py
  DetectorDescription/DDCMS/test/runTest.sh
  DetectorDescription/RecoGeometry/BuildFile.xml
  DetectorDescription/RecoGeometry/interface/DTNumberingScheme.h
  DetectorDescription/RecoGeometry/plugins/BuildFile.xml
  DetectorDescription/RecoGeometry/src/DTNumberingScheme.cc
  Geometry/DTGeometryBuilder/plugins/BuildFile.xml
  Geometry/DTGeometryBuilder/plugins/DTGeometryValidate.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryBuilder.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryBuilder.h
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryESProducer.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryTest.cc
  Geometry/DTGeometryBuilder/test/python/testDTGeometry.py
  Geometry/DTGeometryBuilder/test/python/testDTGeometryAndDump.py
  Geometry/DTGeometryBuilder/test/python/validateDTGeometry_cfg.py
  Geometry/MuonNumbering/interface/DD4hep_DTNumberingScheme.h
  Geometry/MuonNumbering/interface/DD4hep_MuonNumbering.h
  Geometry/MuonNumbering/plugins/BuildFile.xml
  Geometry/MuonNumbering/plugins/DDTestMuonNumbering.cc
  Geometry/MuonNumbering/plugins/MuonNumberingESProducer.cc
  Geometry/MuonNumbering/src/DD4hep_DTNumberingScheme.cc
  Geometry/MuonNumbering/src/DD4hep_MuonNumbering.cc
  Geometry/Records/interface/DDSpecParRegistryRcd.h
  Geometry/Records/interface/DDVectorRegistryRcd.h
  Geometry/Records/interface/DetectorDescriptionRcd.h
  Geometry/Records/interface/MuonGeometryRcd.h
  Geometry/Records/interface/MuonNumberingRcd.h
  Geometry/Records/src/DDSpecParRegistryRcd.cc
  Geometry/Records/src/DDVectorRegistryRcd.cc
  Geometry/Records/src/DetectorDescriptionRcd.cc
  Geometry/Records/src/ES_MuonDDDConstants.cc
  Geometry/Records/src/MuonGeometryRcd.cc
  Geometry/Records/src/MuonNumberingRcd.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26381 Avoid null reference in getTrackFromChargedHadron
  RecoTauTag/RecoTau/src/pfRecoTauChargedHadronAuxFunctions.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26332 First attempt of premixing for MTD
  DataFormats/FTLDigi/interface/PMTDSimAccumulator.h
  DataFormats/FTLDigi/src/classes.h
  DataFormats/FTLDigi/src/classes_def.xml
  RecoLocalFastTime/FTLRecProducers/python/mtdUncalibratedRecHits_cfi.py
  SimFastTiming/Configuration/python/SimFastTiming_EventContent_cff.py
  SimFastTiming/FastTimingCommon/interface/MTDDigitizer.h
  SimFastTiming/FastTimingCommon/interface/MTDDigitizerBase.h
  SimFastTiming/FastTimingCommon/interface/MTDDigitizerTypes.h
  SimFastTiming/FastTimingCommon/plugins/BuildFile.xml
  SimFastTiming/FastTimingCommon/plugins/PreMixingMTDWorker.cc
  SimFastTiming/FastTimingCommon/python/mtdDigitizer_cfi.py
  SimGeneral/MixingModule/python/digitizers_cfi.py
  SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#26352 DD4hep: Merge Geometry Event Setup Records
  DetectorDescription/DDCMS/plugins/DDCMSDetector.cc
  DetectorDescription/DDCMS/plugins/DDDetectorESProducer.cc
  DetectorDescription/DDCMS/plugins/DDSpecParRegistryESProducer.cc
  DetectorDescription/DDCMS/plugins/DDTestDumpFile.cc
  DetectorDescription/DDCMS/plugins/DDTestDumpGeometry.cc
  DetectorDescription/DDCMS/plugins/DDTestNavigateGeometry.cc
  DetectorDescription/DDCMS/plugins/DDVectorRegistryESProducer.cc
  DetectorDescription/DDCMS/src/ES_DDDetector.cc
  DetectorDescription/Parser/test/testmat.cpp
  DetectorDescription/RegressionTest/test/dumpDDCompactView.cpp
  Geometry/DTGeometryBuilder/plugins/DTGeometryValidate.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryBuilder.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryESProducer.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryTest.cc
  Geometry/MuonNumbering/plugins/DDTestMuonNumbering.cc
  Geometry/MuonNumbering/plugins/MuonNumberingESProducer.cc
  Geometry/Records/interface/DDSpecParRegistryRcd.h
  Geometry/Records/interface/DDVectorRegistryRcd.h
  Geometry/Records/interface/MuonGeometryRecord.h
  Geometry/Records/interface/MuonNumberingRecord.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26325 split matching into GSF to track and GSF to Packed, store the first in AOD
  DataFormats/TrackReco/interface/TrackFwd.h
  DataFormats/TrackReco/src/classes_def.xml
  PhysicsTools/PatAlgos/plugins/LowPtGSFToPackedCandidateLinker.cc
  RecoEgamma/Configuration/python/RecoEgamma_EventContent_cff.py
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGSFToTrackLinker.cc
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSequence_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfToTrackLinks_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-started

#26391 defining DQM auto config for rereco
  DQMOffline/Configuration/python/autoDQM.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26387 Removed unnecesary include from EcalLaserDbService
  CalibCalorimetry/EcalLaserCorrection/interface/EcalLaserDbService.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26392 Explicitly cast values in array used in FWHeatmapProxyBuilderTemplate
  Fireworks/Calo/interface/FWHeatmapProxyBuilderTemplate.h
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#26328 skip nonexistent branch checks in L1TGlobalUtilHelper
  L1Trigger/L1TGlobal/src/L1TGlobalUtilHelper.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#26323 Fix const declaration of static used in OAQuality
  CondFormats/OptAlignObjects/interface/OAQuality.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26350 Add small changes in CondCore for PPS proton reco, and serialization …
  CondCore/CTPPSPlugins/src/plugin.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
  CondFormats/CTPPSReadoutObjects/test/BuildFile.xml
  CondFormats/CTPPSReadoutObjects/test/testSerializationLHCOpticalFunctionsSet.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26357 remove incorrect dependencies on boost_python and an obsolete build file
  CondCore/AlignmentPlugins/plugins/BuildFile.xml
  CondCore/EcalPlugins/plugins/BuildFile.xml
  CondCore/HLTPlugins/plugins/BuildFile.xml
  CondCore/HcalPlugins/interface/BuildFile
  CondCore/HcalPlugins/plugins/BuildFile.xml
  CondCore/PCLConfigPlugins/plugins/BuildFile.xml
  CondCore/RunInfoPlugins/plugins/BuildFile.xml
  CondCore/SiStripPlugins/plugins/BuildFile.xml
  CondCore/Utilities/interface/PayloadInspector.h
  CondCore/Utilities/plugins/BuildFile.xml
  PhysicsTools/SelectorUtils/bin/BuildFile.xml
Labels: analysis-approved, code-checks-approved, comparison-available, db-approved, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#26365 add standard prod-like 2018 relvals w/ and w/o b-parking
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, requires-external, tests-approved, upgrade-approved

#26382 New slopes for S9S1filter
  RecoLocalCalo/HcalRecProducers/python/HFPhase1Reconstructor_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26397 add clang-format file to CMSSW
  .clang-format
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26407 Avoid ambiguous statement in dqmfilesaver::fillJson
  DQMServices/Components/src/fillJson.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26414 xrange migration for python3
  Alignment/CommonAlignment/scripts/tkal_create_file_lists.py
  Alignment/MillePedeAlignmentAlgorithm/python/alignmentsetup/helper.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpslib/Mpslibclass.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpslib/tools.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpsvalidate/beamerCreator.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpsvalidate/bigModule.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpsvalidate/bigStructure.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpsvalidate/geometry.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpsvalidate/pdfCreator.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpsvalidate/subModule.py
  Alignment/MillePedeAlignmentAlgorithm/python/mpsvalidate/timeStructure.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_check.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_fetch.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_fire.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_merge.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_monitormerge.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_setup.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_splice.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_update.py
  Alignment/MuonAlignment/python/MCScenario_CRAFT1_22X.py
  Alignment/MuonAlignment/python/MuonGeometrySanityCheck_cfi.py
  Alignment/MuonAlignment/python/geometryDiff.py
  Alignment/MuonAlignment/python/makeMuonMisalignmentScenario.py
  Alignment/MuonAlignment/python/svgfig.py
  Alignment/MuonAlignmentAlgorithms/scripts/alignmentValidation.py
  Alignment/MuonAlignmentAlgorithms/scripts/applyRadialCorrections.py
  Alignment/MuonAlignmentAlgorithms/scripts/corrVsCorr.py
  Alignment/MuonAlignmentAlgorithms/scripts/createBeamHaloJobs.py
  Alignment/MuonAlignmentAlgorithms/scripts/createCSCRingsJobs.py
  Alignment/MuonAlignmentAlgorithms/scripts/createJobs.py
  Alignment/MuonAlignmentAlgorithms/scripts/createTree.py
  Alignment/MuonAlignmentAlgorithms/scripts/findQualityFiles.py
  Alignment/MuonAlignmentAlgorithms/scripts/groupFilesInBlocks.py
  Alignment/MuonAlignmentAlgorithms/scripts/motionPolicyChamber.py
  Alignment/MuonAlignmentAlgorithms/scripts/plotscripts.py
  Alignment/MuonAlignmentAlgorithms/scripts/reportVsReport.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/dataset.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/genericValidation.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/helperFunctions.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/plottingOptions.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/presentation.py
  Alignment/OfflineValidation/test/submitAllJobs.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26408 make ECALHCAL.py python3 compatible
  Validation/Configuration/python/ECALHCAL.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, requires-external, simulation-approved, tests-approved

#26409 swapping order of cuts to avoid expensive dxy/dz calc
  RecoEgamma/PhotonIdentification/plugins/PhotonIDValueMapProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26418 migrate away from commands in das utility
  Utilities/General/python/cmssw_das_client.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26426 Allow return value optimization in getAnyPtr
  FWCore/Utilities/interface/getAnyPtr.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26427 add bool method to cms.Bool
  FWCore/ParameterSet/python/Types.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26428 Remove unused variable in Geometry/MTDNumberingBuilder
  Geometry/MTDNumberingBuilder/plugins/CmsMTDSubStrctBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26390 Run2-alca153 Correct the calibration algos
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibTree.C
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26422 (Backport) Provide forward compatibility to HepMC::GenEvent reading
  SimDataFormats/GeneratorProducts/src/classes.h
  SimDataFormats/GeneratorProducts/src/classes_def.xml
  SimDataFormats/GeneratorProducts/src/hepmc_rootio.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26417 Data relvals 2018 ABC,2016 and 2017 relvals using Offline GTs now by …
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26263 Turning on ClusterRepair for edge hits only
  Configuration/AlCa/python/autoCond.py
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEBase.h
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEClusterRepair.h
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEClusterRepairESProducer.h
  RecoLocalTracker/SiPixelRecHits/plugins/PixelCPEClusterRepairESProducer.cc
  RecoLocalTracker/SiPixelRecHits/python/PixelCPEClusterRepair_cfi.py
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc
  RecoTracker/TransientTrackingRecHit/python/TTRHBuilderWithTemplate_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26403 HCAL updates for phase 1 HB digis
  DataFormats/HcalDigi/interface/QIE11DataFrame.h
  EventFilter/HcalRawToDigi/src/HcalUnpacker.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#26410 xrange migration in fwk packages for python3
  DataFormats/FWLite/examples/patZpeak.py
  DataFormats/FWLite/test/chainEvent_python.py
  DataFormats/FWLite/test/pyroot_read_associationvector.py
  DataFormats/PatCandidates/test/dump_parameterization.py
  FWCore/Concurrency/scripts/edmStreamStallGrapher.py
  FWCore/GuiBrowsers/python/EnablePSetHistory.py
  FWCore/GuiBrowsers/python/Vispa/Gui/PortConnection.py
  FWCore/GuiBrowsers/python/Vispa/Gui/ToolBoxContainer.py
  FWCore/GuiBrowsers/python/Vispa/Gui/VispaWidget.py
  FWCore/GuiBrowsers/python/Vispa/Main/Application.py
  FWCore/GuiBrowsers/python/Vispa/Main/MainWindow.py
  FWCore/GuiBrowsers/python/Vispa/Main/RotatingIcon.py
  FWCore/GuiBrowsers/python/Vispa/Main/SplitterTab.py
  FWCore/GuiBrowsers/python/Vispa/Main/StartupScreen.py
  FWCore/GuiBrowsers/python/Vispa/Main/TabController.py
  FWCore/GuiBrowsers/python/Vispa/Plugins/ConfigEditor/ConfigDataAccessor.py
  FWCore/GuiBrowsers/python/Vispa/Plugins/EdmBrowser/EdmDataAccessor.py
  FWCore/GuiBrowsers/python/Vispa/Plugins/EdmBrowser/EventContentDataAccessor.py
  FWCore/GuiBrowsers/python/Vispa/Plugins/EdmBrowser/EventContentView.py
  FWCore/GuiBrowsers/python/Vispa/Views/LineDecayView.py
  FWCore/GuiBrowsers/python/Vispa/Views/PropertyView.py
  FWCore/GuiBrowsers/python/Vispa/Views/TableView.py
  FWCore/Modules/test/emptysource_cfg.py
  FWCore/Modules/test/emptysource_firstLuminosityBlockForEachRun_cfg.py
  FWCore/Modules/test/testBunchCrossingFilter.py
  FWCore/ParameterSet/python/Mixins.py
  FWCore/ParameterSet/python/SequenceTypes.py
  FWCore/ParameterSet/python/TreeCrawler.py
  FWCore/PythonUtilities/python/LumiList.py
  FWCore/PythonUtilities/scripts/generateEDF.py
  FWCore/Skeletons/python/cms.py
  FWCore/Skeletons/python/utils.py
  Utilities/RelMon/python/directories2html.py
  Utilities/RelMon/python/dirstructure.py
  Utilities/RelMon/python/dqm_interfaces.py
  Utilities/RelMon/python/utils.py
  Utilities/RelMon/python/utils_v2.py
  Utilities/RelMon/scripts/ValidationMatrix.py
  Utilities/ReleaseScripts/python/cmsCodeRules/cppFunctionSkipper.py
  Utilities/ReleaseScripts/python/cmsCodeRules/keyFinder.py
  Utilities/ReleaseScripts/python/cmsCodeRules/showPage.py
  Utilities/ReleaseScripts/python/commentSkipper/buildFileCommentSkipper.py
  Utilities/ReleaseScripts/python/commentSkipper/cppCommentSkipper.py
  Utilities/ReleaseScripts/scripts/addOnTests.py
  Utilities/ReleaseScripts/scripts/cmsCodeRulesChecker.py
  Utilities/ReleaseScripts/scripts/storeTreeInfo.py
  Utilities/StaticAnalyzers/scripts/statics.py
Labels: analysis-pending, code-checks-approved, comparison-available, core-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26421 replace map in python by list
  DQM/EcalMonitorTasks/python/TrigPrimTask_cfi.py
  DQM/Integration/python/config/inputsource_cfi.py
  SimMuon/Configuration/python/SimMuon_EventContent_cff.py
  Validation/RecoTrack/python/trackingNtuple_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#26434 Python3 syntax error cleanup
  CalibTracker/SiStripESProducers/test/python/SiStripBadAPVListBuilder_byHand_cfg.py
  IOPool/Input/test/PrePoolInputTest_cfg.py
  IOPool/Input/test/RunPerLumiTest_cfg.py
  RecoEgamma/ElectronIdentification/test/runElectron_VID.py
  RecoEgamma/PhotonIdentification/test/runPhoton_VID.py
  RecoTauTag/RecoTau/test/rerunTauRecoOnMiniAOD.py
Labels: alca-approved, code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26435 Correction of static check include path for edm::isNotFinite
  Utilities/StaticAnalyzers/src/FiniteMathChecker.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26327 [PPS] Timing calibration for diamond rechits/tracks
  CalibPPS/ESProducers/test/ppsTimingCalibrationAnalyzer_cfg.py
  CalibPPS/ESProducers/test/ppsTimingCalibrationWriter_cfg.py
  RecoCTPPS/TotemRPLocal/interface/CTPPSDiamondRecHitProducerAlgorithm.h
  RecoCTPPS/TotemRPLocal/interface/CTPPSDiamondTrackRecognition.h
  RecoCTPPS/TotemRPLocal/interface/CTPPSTimingTrackRecognition.h
  RecoCTPPS/TotemRPLocal/interface/TotemTimingTrackRecognition.h
  RecoCTPPS/TotemRPLocal/plugins/CTPPSDiamondLocalTrackFitter.cc
  RecoCTPPS/TotemRPLocal/plugins/CTPPSDiamondRecHitProducer.cc
  RecoCTPPS/TotemRPLocal/plugins/TotemTimingLocalTrackFitter.cc
  RecoCTPPS/TotemRPLocal/python/PPSTimingCalibrationModeEnum_cff.py
  RecoCTPPS/TotemRPLocal/src/CTPPSDiamondRecHitProducerAlgorithm.cc
  RecoCTPPS/TotemRPLocal/src/CTPPSDiamondTrackRecognition.cc
  RecoCTPPS/TotemRPLocal/src/TotemTimingTrackRecognition.cc
  RecoCTPPS/TotemRPLocal/test/diamonds_reco_cfg.py
  RecoCTPPS/TotemRPLocal/test/totemTiming_reco_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26436 Fix include for HFStripFilter
  RecoLocalCalo/HcalRecAlgos/interface/HFStripFilter.h
  RecoLocalCalo/HcalRecAlgos/src/HFStripFilter.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26430 Added Residuals plots and fix monitoring plots for Pixel ClusterRepairs
  Alignment/OfflineValidation/interface/TrackerValidationVariables.h
  Alignment/OfflineValidation/src/TrackerValidationVariables.cc
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1RecHits.cc
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1TrackResiduals.cc
  DQM/SiPixelPhase1Track/python/SiPixelPhase1RecHits_cfi.py
  DQM/SiPixelPhase1Track/python/SiPixelPhase1TrackResiduals_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26424 xrange migration to L1 and egammaanalysis
  EgammaAnalysis/ElectronTools/test/compareMass.py
  L1Trigger/L1THGCal/test/macros/DrawingUtilities.py
  L1Trigger/L1THGCal/test/macros/drawTriggerCells.py
  L1Trigger/L1THGCal/test/macros/drawTriggerModules.py
  L1Trigger/L1THGCal/test/macros/drawTriggerModulesHex.py
Labels: analysis-pending, code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#26354 [HGCal] dEdx weights and thickness correction factors for V10 (D41)
  RecoLocalCalo/HGCalRecProducers/python/HGCalRecHit_cfi.py
  RecoLocalCalo/HGCalRecProducers/python/HGCalUncalibRecHit_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#26429 Fix clang warnings in FastSimulation/SimplifiedGeometryPropagator
  FastSimulation/SimplifiedGeometryPropagator/plugins/NuclearInteraction.cc
  FastSimulation/SimplifiedGeometryPropagator/plugins/NuclearInteractionFTF.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#26335 PPS: proton reconstruction, algorithm update
  CalibPPS/ESProducers/plugins/CTPPSInterpolatedOpticalFunctionsESSource.cc
  CalibPPS/ESProducers/plugins/CTPPSLHCInfoESSource.cc
  CalibPPS/ESProducers/plugins/CTPPSOpticalFunctionsESSource.cc
  CalibPPS/ESProducers/python/ctppsOpticalFunctions_cff.py
  DataFormats/ProtonReco/interface/ForwardProton.h
  DataFormats/ProtonReco/src/ForwardProton.cc
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoCTPPS/ProtonReconstruction/BuildFile.xml
  RecoCTPPS/ProtonReconstruction/interface/ProtonReconstructionAlgorithm.h
  RecoCTPPS/ProtonReconstruction/plugins/CTPPSProtonProducer.cc
  RecoCTPPS/ProtonReconstruction/src/ProtonReconstructionAlgorithm.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionPlotter.cc
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, dqm-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26271 Run2-hcx192 Changes to DDHCalAngular by removing explicit reference to CLHEP
  DetectorDescription/Core/interface/DDTypes.h
  DetectorDescription/Core/src/DDTypes.cc
  Geometry/HcalAlgo/plugins/DDHCalAngular.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26355 Updates on DQMOffline ZCounting for ultra legacy reco
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_run2_HLTconditions_2016_cff.py
  Configuration/Eras/python/Modifier_run2_HLTconditions_2017_cff.py
  Configuration/Eras/python/Modifier_run2_HLTconditions_2018_cff.py
  Configuration/StandardSequences/python/Eras.py
  DQMOffline/Lumi/interface/TTrigger.h
  DQMOffline/Lumi/plugins/ZCounting.cc
  DQMOffline/Lumi/plugins/ZCounting.h
  DQMOffline/Lumi/python/ZCounting_cff.py
  DQMOffline/Lumi/src/TTrigger.cc
  DQMOffline/Lumi/test/ZCounting_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#26420 adding fixedGridRhoFastjetAllTmp to MiniAOD event content
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#26294 New feature for the Payload Inspector: support for two tags/ single IOV plot generation
  CondCore/CondDB/interface/Session.h
  CondCore/CondDB/interface/Types.h
  CondCore/CondDB/src/Session.cc
  CondCore/Utilities/interface/PayloadInspector.h
  CondCore/Utilities/interface/PayloadInspectorModule.h
  CondCore/Utilities/plugins/BasicP_PayloadInspector.cc
  CondCore/Utilities/plugins/Module_PayloadInspector.cc
  CondCore/Utilities/scripts/getPayloadData.py
  CondCore/Utilities/src/PayloadInspector.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26399 Import additions for UL from CMSSW_9_4_13_UL1 (#26168) and #26211
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
  DataFormats/CSCDigi/interface/CSCCLCTPreTriggerDigi.h
  DataFormats/CSCDigi/interface/CSCCLCTPreTriggerDigiCollection.h
  DataFormats/CSCDigi/src/CSCCLCTPreTriggerDigi.cc
  DataFormats/CSCDigi/src/classes.h
  DataFormats/CSCDigi/src/classes_def.xml
  SimDataFormats/GeneratorProducts/src/classes.h
  SimDataFormats/GeneratorProducts/src/classes_def.xml
  SimDataFormats/GeneratorProducts/src/hepmc_rootio.cc
Labels: comparison-available, fully-signed, generators-approved, operations-approved, orp-approved, simulation-approved, tests-approved

#26404 Split lowpt links
  DataFormats/TrackReco/interface/TrackFwd.h
  DataFormats/TrackReco/src/classes_def.xml
  PhysicsTools/PatAlgos/plugins/LowPtGSFToPackedCandidateLinker.cc
  RecoEgamma/Configuration/python/RecoEgamma_EventContent_cff.py
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGSFToTrackLinker.cc
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSequence_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfToTrackLinks_cfi.py
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-started

#26400 add 2018 Prod-like workflow w & w/o bParking
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, requires-external, tests-approved, upgrade-approved

#26258 Ban DQMReferenceHistogramRootFileEventSetupAnalyzer from Production DQM sequences.
  DQMOffline/Configuration/python/DQMOfflineCosmics_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26443 more iteritems and integer division cleanups (python3 unit tests)
  DQMServices/FwkIO/test/read_file1_file3_cfg.py
  RecoTauTag/Configuration/python/tools/adaptToRunAtMiniAOD.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26272 Run2-hcx193 Changes to DDHCalBarrelAlgo by removing explicit reference to CLHEP
  DetectorDescription/Core/src/DDTypes.cc
  Geometry/HcalAlgo/plugins/DDHCalAngular.cc
  Geometry/HcalAlgo/plugins/DDHCalBarrelAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26456 python test updates for new sklearn version -
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/testDeepDish.py
  PhysicsTools/PythonAnalysis/test/testTheanets.py
  PhysicsTools/PythonAnalysis/test/testXGBoost_and_sklearn.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#26329 skip nonexistent branch checks in L1TGlobalUtilHelper
  L1Trigger/L1TGlobal/src/L1TGlobalUtilHelper.cc
Labels: backport-ok, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#26337 DQMIO-related tools
  DQMServices/Components/scripts/dqmiodatasetharvest.py
  DQMServices/Components/scripts/root2sqlite.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26351 Run2-hcx194 Changes to some of the algorithms used for TB application by removing explicit reference to CLHEP
  Geometry/HcalAlgo/plugins/DDHCalTBCableAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalTBZposAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalTestBeamAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalXtalAlgo.cc
  SimG4CMS/HcalTestBeam/python/TB2007GeometryNoESXML_cfi.py
  SimG4CMS/HcalTestBeam/python/TB2007GeometryNoEcalXML_cfi.py
  SimG4CMS/HcalTestBeam/python/TB2007GeometryXML_cfi.py
  SimG4CMS/HcalTestBeam/test/python/run2006_33_cfg.py
  SimG4CMS/HcalTestBeam/test/python/run2006_37_cfg.py
  SimG4CMS/HcalTestBeam/test/python/run2006_77_cfg.py
  SimG4CMS/HcalTestBeam/test/python/run2006_cfg.py
  SimG4CMS/HcalTestBeam/test/python/run2007_cfg.py
  SimG4CMS/HcalTestBeam/test/python/run2010_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#26384 [HGCal] Material budget for V10 geometry scenario
  Validation/Geometry/data/hgcalMaterials.l0
  Validation/Geometry/data/hgcalMaterials.x0
  Validation/Geometry/interface/MaterialBudgetData.h
  Validation/Geometry/python/plot_hgcal_utils.py
  Validation/Geometry/src/MaterialBudgetCategorizer.cc
  Validation/Geometry/src/MaterialBudgetData.cc
  Validation/Geometry/src/MaterialBudgetHGCalHistos.cc
  Validation/Geometry/test/MaterialBudgetHGCal.py
  Validation/Geometry/test/runP_HGCal_cfg.py
  Validation/HGCalValidation/data/D41.cumulative.xo
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#26450 Run2-alca155 Source code reformatting with clang-format in Calibration/HcalAlCaRecoProducers
  Calibration/HcalAlCaRecoProducers/interface/AlCaEcalHcalReadoutsProducer.h
  Calibration/HcalAlCaRecoProducers/interface/AlCaHcalNoiseProducer.h
  Calibration/HcalAlCaRecoProducers/plugins/AlCaGammaJetSelector.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksProducerFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsolatedBunchFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsolatedBunchSelector.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaLowPUHBHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/ConeDefinition.h
  Calibration/HcalAlCaRecoProducers/plugins/PrescalerFHN.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaDiJetsProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaEcalHcalReadoutsProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaGammaJetProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaHBHEMuonProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaHOCalibProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaHcalNoiseProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaIsoTracksProducer.cc
  Calibration/HcalAlCaRecoProducers/src/ProducerAnalyzer.cc
  Calibration/HcalAlCaRecoProducers/src/ProducerAnalyzer.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26451 Run2-alca154 Source code reformatting with clang-format in Calibration/HcalCalibAlgos
  Calibration/HcalCalibAlgos/interface/CommonUsefulStuff.h
  Calibration/HcalCalibAlgos/interface/HcalConstantsXMLWriter.h
  Calibration/HcalCalibAlgos/interface/hcalCalib.h
  Calibration/HcalCalibAlgos/interface/hcalCalibUtils.h
  Calibration/HcalCalibAlgos/plugins/AnalyzerMinbias.cc
  Calibration/HcalCalibAlgos/plugins/Analyzer_minbias.cc
  Calibration/HcalCalibAlgos/plugins/Analyzer_minbias.h
  Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalCalibrator.cc
  Calibration/HcalCalibAlgos/plugins/HcalCalibrator.h
  Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HitReCalibrator.cc
  Calibration/HcalCalibAlgos/plugins/HitReCalibrator.h
  Calibration/HcalCalibAlgos/plugins/RecAnalyzerHF.cc
  Calibration/HcalCalibAlgos/plugins/RecAnalyzerMinbias.cc
  Calibration/HcalCalibAlgos/plugins/SimAnalyzerMinbias.cc
  Calibration/HcalCalibAlgos/plugins/ValidIsoTrkCalib.cc
  Calibration/HcalCalibAlgos/src/HcalConstantsXMLWriter.cc
  Calibration/HcalCalibAlgos/src/TCell.h
  Calibration/HcalCalibAlgos/src/classes.h
  Calibration/HcalCalibAlgos/src/hcalCalib.cc
  Calibration/HcalCalibAlgos/src/hcalCalibUtils.cc
  Calibration/HcalCalibAlgos/test/DiJetAnalyzer.cc
  Calibration/HcalCalibAlgos/test/DiJetAnalyzer.h
  Calibration/HcalCalibAlgos/test/GammaJetAnalysis.cc
  Calibration/HcalCalibAlgos/test/GammaJetAnalysis.h
  Calibration/HcalCalibAlgos/test/HcalConstantsASCIIWriter.cc
  Calibration/HcalCalibAlgos/test/HcalConstantsASCIIWriter.h
  Calibration/HcalCalibAlgos/test/HcalCorrPFCalculation.cc
  Calibration/HcalCalibAlgos/test/HcalIsoTrackStudy.cc
  Calibration/HcalCalibAlgos/test/HcalLaserTest.cc
  Calibration/HcalCalibAlgos/test/ValidationHcalIsoTrackAlCaReco.cc
  Calibration/HcalCalibAlgos/test/ValidationHcalIsoTrackAlCaReco.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26393 ECAL : automatic Ecal Preshower Gain Switching in DB, by O2O
  CondTools/Ecal/interface/PopConESTransitionSourceHandler.h
  CondTools/Ecal/plugins/ESGainPopConTransitionAnalyzer.cc
  CondTools/Ecal/plugins/ESIntercalibConstantsPopConTransitionAnalyzer.cc
  CondTools/Ecal/plugins/ESRecHitRatioCutsPopConTransitionAnalyzer.cc
  CondTools/Ecal/plugins/ESTimeSampleWeightsPopConTransitionAnalyzer.cc
  CondTools/Ecal/python/ESGainPopConTransitionAnalyzer_cfg.py
  CondTools/Ecal/python/ESIntercalibConstantsPopConTransitionAnalyzer_cfg.py
  CondTools/Ecal/python/ESRecHitRatioCutsPopConTransitionAnalyzer_cfg.py
  CondTools/Ecal/python/ESTimeSampleWeightsPopConTransitionAnalyzer_cfg.py
  CondTools/Ecal/python/conddb_init.py
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26459 [muon] updated multiIso working points
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26432 HCAL: adding Phase 1 HBX/HEX channels to CalibDetId and ASCII conditions processing
  CalibFormats/HcalObjects/src/HcalText2DetIdConverter.cc
  DataFormats/HcalDetId/interface/HcalCalibDetId.h
  DataFormats/HcalDetId/src/HcalCalibDetId.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26475 remove deepdish from list of things to test in imports unit test
  PhysicsTools/PythonAnalysis/test/imports.txt
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#26477 Add to short matrix upgrade scenario D41 (baseline for L1T TDR)
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26394 PPS: proton reco finalisation before UL re-reco
  CalibPPS/ESProducers/plugins/CTPPSLHCInfoESSource.cc
  CalibPPS/ESProducers/python/ctppsLHCInfo_cff.py
  CalibPPS/ESProducers/python/ctppsOpticalFunctions_cff.py
  Configuration/AlCa/python/autoCond.py
  RecoCTPPS/ProtonReconstruction/plugins/CTPPSProtonProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26470 [HGCal] Fix thread safety issue in layer clustering density map filling
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalCLUEAlgo.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalImagingAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#26461 Add trigger bit to emulated GlobalExtBlk to indicate event was not selected …
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py
  L1Trigger/L1TGlobal/plugins/BuildFile.xml
  L1Trigger/L1TGlobal/plugins/L1TExtCondProducer.cc
  L1Trigger/L1TGlobal/python/simGtExtFakeProd_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, operations-approved, orp-approved, tests-approved

#26484 fixing getPayloadData.py script to be able to compile
  CondCore/Utilities/scripts/getPayloadData.py
Labels: bug-fix, code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, tests-approved

#26249 SimTrack to muon SimHit matching classes in Muon Validation code
  Validation/MuonHits/BuildFile.xml
  Validation/MuonHits/interface/CSCSimHitMatcher.h
  Validation/MuonHits/interface/DTSimHitMatcher.h
  Validation/MuonHits/interface/GEMSimHitMatcher.h
  Validation/MuonHits/interface/ME0SimHitMatcher.h
  Validation/MuonHits/interface/MuonHitHelper.h
  Validation/MuonHits/interface/MuonSimHitMatcher.h
  Validation/MuonHits/interface/RPCSimHitMatcher.h
  Validation/MuonHits/plugins/BuildFile.xml
  Validation/MuonHits/plugins/MuonSimHitsValidAnalyzer.cc
  Validation/MuonHits/plugins/MuonSimHitsValidAnalyzer.h
  Validation/MuonHits/plugins/SealModule.cc
  Validation/MuonHits/python/muonSimHitMatcherPSet.py
  Validation/MuonHits/src/CSCSimHitMatcher.cc
  Validation/MuonHits/src/DTSimHitMatcher.cc
  Validation/MuonHits/src/GEMSimHitMatcher.cc
  Validation/MuonHits/src/ME0SimHitMatcher.cc
  Validation/MuonHits/src/MuonHitHelper.cc
  Validation/MuonHits/src/MuonSimHitMatcher.cc
  Validation/MuonHits/src/RPCSimHitMatcher.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26232 Save DQM output per lumisection for UL rereco
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/DataProcessing/python/Merge.py
  DQM/EcalMonitorClient/interface/DQWorkerClient.h
  DQM/EcalMonitorClient/plugins/EcalDQMonitorClient.cc
  DQM/EcalMonitorClient/src/DQWorkerClient.cc
  DQM/HcalTasks/src/DigiRunSummary.cc
  DQM/TrackingMonitorClient/src/TrackingQualityChecker.cc
  DQMOffline/EGamma/interface/ElectronDqmAnalyzerBase.h
  DQMOffline/EGamma/src/ElectronDqmAnalyzerBase.cc
  DQMServices/Components/plugins/DQMDcsInfoClient.cc
  DQMServices/Components/plugins/DQMDcsInfoClient.h
  DQMServices/Components/python/DQMDcsInfoClient_cfi.py
  DQMServices/Core/interface/DQMStore.h
  DQMServices/Core/interface/oneDQMEDAnalyzer.h
  DQMServices/Core/python/DQMStoreNonLegacy_cff.py
  DQMServices/Core/python/DQMStore_cfi.py
  DQMServices/Core/src/DQMStore.cc
  DQMServices/FwkIO/plugins/DQMRootSource.cc
  DQMServices/FwkIO/test/copy_file_multi_types_cfg.py
  DQMServices/FwkIO/test/create_run_lumi_file_cfg.py
  DQMServices/FwkIO/test/merge_file1_file2_cfg.py
  DQMServices/FwkIO/test/merge_file1_file3_file2_cfg.py
  DQMServices/FwkIO/test/merge_file1_file3_file2_filterOnRun1_cfg.py
  DQMServices/FwkIO/test/merge_file1_file3_file4_cfg.py
  DQMServices/FwkIO/test/read_file1_file2_cfg.py
  DQMServices/FwkIO/test/read_file1_file3_cfg.py
  DQMServices/FwkIO/test/read_lumi_only_file_cfg.py
  DQMServices/FwkIO/test/read_merged_file1_file2_cfg.py
  DQMServices/FwkIO/test/read_merged_file1_file3_file2_cfg.py
  DQMServices/FwkIO/test/read_merged_file1_file3_file4_cfg.py
  DQMServices/FwkIO/test/read_write_merged_file1_file3_file2_filterOnRun1_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#26347 MTD validation package
  Validation/Configuration/python/autoValidation.py
  Validation/Configuration/python/globalValidation_cff.py
  Validation/Configuration/python/mtdSimValid_cff.py
  Validation/MtdValidation/plugins/BtlDigiHitsValidation.cc
  Validation/MtdValidation/plugins/BtlRecHitsValidation.cc
  Validation/MtdValidation/plugins/BtlSimHitsValidation.cc
  Validation/MtdValidation/plugins/BuildFile.xml
  Validation/MtdValidation/plugins/EtlDigiHitsValidation.cc
  Validation/MtdValidation/plugins/EtlRecHitsValidation.cc
  Validation/MtdValidation/plugins/EtlSimHitsValidation.cc
  Validation/MtdValidation/python/btlDigiHits_cfi.py
  Validation/MtdValidation/python/etlDigiHits_cfi.py
  Validation/MtdValidation/test/mtdValidation_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#26415 Update Data/MC GTs in 106X
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26369 Adding digi-based shower tagging to reco::Muon
  DataFormats/MuonReco/interface/Muon.h
  DataFormats/MuonReco/interface/MuonChamberMatch.h
  DataFormats/MuonReco/src/Muon.cc
  DataFormats/MuonReco/src/classes_def.xml
  RecoMuon/MuonIdentification/interface/MuonShowerDigiFiller.h
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.cc
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.h
  RecoMuon/MuonIdentification/python/MuonShowerDigiFiller_cfi.py
  RecoMuon/MuonIdentification/python/muons1stStep_cfi.py
  RecoMuon/MuonIdentification/src/MuonShowerDigiFiller.cc
  TauAnalysis/MCEmbeddingTools/python/customisers.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, simulation-pending, tests-approved

#26343 DyT algorithm new thresholds parameterization
  RecoMuon/GlobalMuonProducer/python/tevMuons_cfi.py
  RecoMuon/GlobalTrackingTools/interface/DynamicTruncation.h
  RecoMuon/GlobalTrackingTools/interface/GlobalMuonRefitter.h
  RecoMuon/GlobalTrackingTools/plugins/GlobalTrackQualityProducer.cc
  RecoMuon/GlobalTrackingTools/plugins/GlobalTrackQualityProducer.h
  RecoMuon/GlobalTrackingTools/python/GlobalMuonRefitter_cff.py
  RecoMuon/GlobalTrackingTools/python/GlobalTrajectoryBuilderCommon_cff.py
  RecoMuon/GlobalTrackingTools/src/DynamicTruncation.cc
  RecoMuon/GlobalTrackingTools/src/GlobalMuonRefitter.cc
  RecoMuon/L3MuonProducer/src/L3MuonProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#26467 Make ESInputTag constructors explicit
  FWCore/Utilities/interface/ESInputTag.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26501 Add DT digis and CSC strip digis to RECO event content
  RecoLocalMuon/Configuration/python/RecoLocalMuon_EventContent_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26469 Add back DeepBoostedJet V01
  RecoBTag/MXNet/python/Parameters/V01/pfDeepBoostedJetPreprocessParams_cfi.py
  RecoBTag/MXNet/python/Parameters/V02/pfDeepBoostedJetPreprocessParams_cfi.py
  RecoBTag/MXNet/python/Parameters/V02/pfMassDecorrelatedDeepBoostedJetPreprocessParams_cfi.py
  RecoBTag/MXNet/python/pfDeepBoostedJet_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26479 Fix generation of DTuROSControlData in case of missing FEDs
  DataFormats/DTDigi/interface/DTuROSControlData.h
  EventFilter/DTRawToDigi/plugins/DTuROSRawToDigi.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#26490 Run3-gem29 Update the testing and change debugs
  Geometry/MuonCommonData/plugins/DDGEMAngular.cc
  Geometry/MuonCommonData/plugins/DDMuonAngular.cc
  Geometry/MuonCommonData/python/testMFXML_cfi.py
  Geometry/MuonCommonData/test/runME_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26491 Run2-hcx195 Remove direct CLHEP reference in the algorithm for HCAL endcap
  Geometry/HcalAlgo/plugins/DDHCalAngular.cc
  Geometry/HcalAlgo/plugins/DDHCalBarrelAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalEndcapAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalEndcapModuleAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalXtalAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26471 Run2-TB36 Create the two remaining setups for HGCal October TB runs
  Geometry/HGCalCommonData/data/TB181/Oct182/ahcal.xml
  Geometry/HGCalCommonData/data/TB181/Oct182/hgcal.xml
  Geometry/HGCalCommonData/data/TB181/Oct182/hgcalBeam.xml
  Geometry/HGCalCommonData/data/TB181/Oct182/hgcalEE.xml
  Geometry/HGCalCommonData/data/TB181/Oct182/hgcalHE.xml
  Geometry/HGCalCommonData/data/TB181/Oct183/ahcal.xml
  Geometry/HGCalCommonData/data/TB181/Oct183/hgcal.xml
  Geometry/HGCalCommonData/data/TB181/Oct183/hgcalBeam.xml
  Geometry/HGCalCommonData/data/TB181/Oct183/hgcalEE.xml
  Geometry/HGCalCommonData/data/TB181/Oct183/hgcalHE.xml
  SimG4CMS/HGCalTestBeam/python/HGCalTB181Oct2XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB181Oct3XML_cfi.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct2_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct3_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#26489 Era based effective area to be used in Muon selectors
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_run2_muon_2016_cff.py
  Configuration/Eras/python/Modifier_run2_muon_2017_cff.py
  Configuration/Eras/python/Modifier_run2_muon_2018_cff.py
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.h
  PhysicsTools/PatAlgos/python/producersLayer1/muonProducer_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatUtils/interface/MiniIsolation.h
  PhysicsTools/PatUtils/src/MiniIsolation.cc
Labels: analysis-approved, code-checks-approved, comparison-available, operations-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26433 Reduced output string on data relvals to avoid exceed length limit
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26480 DD4Hep: DDTrackerRingAlgo Remove redundant matrices
  Geometry/MTDGeometryBuilder/test/python/testMTDGeometry.py
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerRingAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26488 Removed all EgammaAnalysis packages except for ElectronTools
  EgammaAnalysis/CSA07Skims/BuildFile.xml
  EgammaAnalysis/CSA07Skims/interface/EgammaProbeSelector.h
  EgammaAnalysis/CSA07Skims/python/AODSIMEgammaSkimEventContent_cff.py
  EgammaAnalysis/CSA07Skims/python/EgammaLooseZOutputModule_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaLowEtTrigger_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaSkimEventContent_cff.py
  EgammaAnalysis/CSA07Skims/python/EgammaVeryHighEtOutputModule_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaVeryHighEtPath_cff.py
  EgammaAnalysis/CSA07Skims/python/EgammaVeryHighEtTrigger_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaWJetOutputModule_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaWJetSkimPath_cff.py
  EgammaAnalysis/CSA07Skims/python/EgammaWJetToEleHLT_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaWJetToElePlusProbe_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaWJetToMuHLT_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaWJetToMuPlusProbe_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaWPlusEMOrJetOutputModule_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaWPlusEMOrJetPath_cff.py
  EgammaAnalysis/CSA07Skims/python/EgammaZJetOutputModule_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaZJetSkimPath_cff.py
  EgammaAnalysis/CSA07Skims/python/EgammaZJetToEleHLT_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaZJetToElePlusProbe_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaZJetToMuHLT_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaZJetToMuPlusProbe_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaZPlusEMOrJetOutputModule_cfi.py
  EgammaAnalysis/CSA07Skims/python/EgammaZPlusEMOrJetPath_cff.py
  EgammaAnalysis/CSA07Skims/python/FEVTSIMEgammaSkimEventContent_cff.py
  EgammaAnalysis/CSA07Skims/python/RECOSIMEgammaSkimEventContent_cff.py
  EgammaAnalysis/CSA07Skims/python/egammaLooseZOutputModuleAODSIM_cfi.py
  EgammaAnalysis/CSA07Skims/python/egammaLooseZOutputModuleFEVTSIM_cfi.py
  EgammaAnalysis/CSA07Skims/python/egammaLooseZOutputModuleRECOSIM_cfi.py
  EgammaAnalysis/CSA07Skims/python/egammaVeryHighEtOutputModuleAODSIM_cfi.py
  EgammaAnalysis/CSA07Skims/python/egammaVeryHighEtOutputModuleRECOSIM_cfi.py
  EgammaAnalysis/CSA07Skims/python/egammaWPlusEMOrJetOutputModuleAODSIM_cfi.py
  EgammaAnalysis/CSA07Skims/python/egammaWPlusEMOrJetOutputModuleRECOSIM_cfi.py
  EgammaAnalysis/CSA07Skims/python/egammaZPlusEMOrJetOutputModuleAODSIM_cfi.py
  EgammaAnalysis/CSA07Skims/python/egammaZPlusEMOrJetOutputModuleRECOSIM_cfi.py
  EgammaAnalysis/CSA07Skims/src/EgammaProbeSelector.cc
  EgammaAnalysis/CSA07Skims/src/SealModule.cc
  EgammaAnalysis/Configuration/python/EgammaAnalysis_EventContent_cff.py
  EgammaAnalysis/Configuration/python/EgammaAnalysis_OutputModules_cff.py
  EgammaAnalysis/Configuration/python/EgammaAnalysis_SkimPaths_cff.py
  EgammaAnalysis/ElectronIDESSources/python/likelihoodESetup_cfi.py
  EgammaAnalysis/ElectronIDESSources/python/likelihoodPdfsDB_cfi.py
  EgammaAnalysis/PhotonIDProducers/BuildFile.xml
  EgammaAnalysis/PhotonIDProducers/interface/PiZeroDiscriminatorProducer.h
  EgammaAnalysis/PhotonIDProducers/python/piZeroDiscriminators_cfi.py
  EgammaAnalysis/PhotonIDProducers/src/PiZeroDiscriminatorProducer.cc
  EgammaAnalysis/PhotonIDProducers/src/SealModule.cc
  Utilities/ReleaseScripts/scripts/git-publish
Labels: analysis-approved, code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26495 Remove unused DQMStore pointers
  CalibTracker/SiStripChannelGain/plugins/SiStripGainFromData.cc
  DQM/Physics/src/QcdLowPtDQM.h
  DQM/SiStripCommissioningClients/interface/CommissioningHistograms.h
  DQM/SiStripCommissioningClients/src/CommissioningHistograms.cc
  DQM/SiStripMonitorCluster/interface/MonitorLTC.h
  DQM/SiStripMonitorCluster/interface/SiStripMonitorFilter.h
  DQM/SiStripMonitorCluster/interface/SiStripMonitorHLT.h
  DQM/SiStripMonitorCluster/src/MonitorLTC.cc
  DQM/SiStripMonitorCluster/src/SiStripMonitorFilter.cc
  DQM/SiStripMonitorCluster/src/SiStripMonitorHLT.cc
  DQM/SiStripMonitorHardware/interface/HistogramBase.hh
  DQMOffline/EGamma/plugins/PhotonOfflineClient.h
  DQMOffline/Muon/interface/EfficiencyPlotter.h
  DQMOffline/Muon/interface/MuonKinVsEtaAnalyzer.h
  DQMOffline/Muon/interface/MuonSeedsAnalyzer.h
  DQMOffline/Muon/interface/MuonTestSummary.h
  DQMOffline/Muon/interface/TriggerMatchEfficiencyPlotter.h
  DQMOffline/Muon/interface/TriggerMatchMonitor.h
  DQMOffline/Muon/src/MuonKinVsEtaAnalyzer.cc
  DQMOffline/Muon/src/TriggerMatchMonitor.cc
  DQMServices/Components/plugins/DQMEventInfo.h
  HLTriggerOffline/HeavyFlavor/src/HeavyFlavorValidation.cc
  Validation/EcalDigis/interface/EcalMixingModuleValidation.h
  Validation/MuonIsolation/interface/MuIsoValidation.h
  Validation/MuonIsolation/src/MuIsoValidation.cc
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26497 Run3-gem30 Use edm::Log in the code rather than cout in Geometry/MuonNumbering
  Geometry/MuonNumbering/plugins/DDTestMuonNumbering.cc
  Geometry/MuonNumbering/plugins/MuonNumberingESProducer.cc
  Geometry/MuonNumbering/src/CSCNumberingScheme.cc
  Geometry/MuonNumbering/src/DD4hep_MuonNumbering.cc
  Geometry/MuonNumbering/src/DTNumberingScheme.cc
  Geometry/MuonNumbering/src/GEMNumberingScheme.cc
  Geometry/MuonNumbering/src/ME0NumberingScheme.cc
  Geometry/MuonNumbering/src/MuonBaseNumber.cc
  Geometry/MuonNumbering/src/MuonDDDConstants.cc
  Geometry/MuonNumbering/src/MuonDDDNumbering.cc
  Geometry/MuonNumbering/src/MuonNumberingScheme.cc
  Geometry/MuonNumbering/src/MuonSimHitNumberingScheme.cc
  Geometry/MuonNumbering/src/MuonSubDetector.cc
  Geometry/MuonNumbering/src/RPCNumberingScheme.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26505 HcalCalibDetId fix
  DataFormats/HcalDetId/src/HcalCalibDetId.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26507 Fixed clang warning about self-assignment in OwnVector_t
  DataFormats/Common/test/OwnVector_t.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26509 Avoid side-effects in typeid call within rz_harm_poly in MagneticField
  MagneticField/ParametrizedEngine/src/rz_harm_poly.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26512 Modernized DTBtiChip used in L1
  L1Trigger/DTBti/interface/DTBtiChip.h
  L1Trigger/DTBti/src/DTBtiCard.cc
  L1Trigger/DTBti/src/DTBtiChip.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved
