Repository cms-sw/cmssw, pull requests merged in 2019-08, with the labels that each got.

#27632 DD: Replace PseudoTrap shape by TruncTubs
  Configuration/Geometry/python/dict2026Geometry.py
  DetectorDescription/DDCMS/data/cms-2015-muon-geometry.xml
  Fireworks/Geometry/python/dumpMFGeometry_cfg.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015CastorMeasuredXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015CastorSystMinusXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015CastorSystPlusXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015MuonGEMDevXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015XML_RPC2Gap_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015XML_RPC4RE11_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015ZeroMaterialXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015devCastorMeasuredXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015devCastorSystMinusXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015devCastorSystPlusXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2015devXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2016XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2016aXML_CTPPS_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2016aXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2017Plan1XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2017Plan1ZeroMaterialXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2017XML_CTPPS_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2017XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2018NoSDXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2018Plan36XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2018XML_CTPPS_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2018XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2018ZeroMaterialXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2019XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D35XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D41XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D43XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D44XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D45XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D46XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2017Plan1XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2017Plan1ZeroMaterialXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2017XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2018XML_cfi.py
  Geometry/CMSCommonData/python/cmsIdealGeometry2015XML_cfi.py
  Geometry/CMSCommonData/python/cmsIdealGeometry2015devXML_cfi.py
  Geometry/MuonCommonData/data/Nominal/mf.xml
  Geometry/MuonCommonData/data/Nominal/muonNumbering.xml
  Geometry/MuonCommonData/data/Run2/v2/mbCommon.xml
  Geometry/MuonCommonData/data/WrongRPCDimension/mf.xml
  Geometry/MuonCommonData/data/muonYoke/2015/v1/muonYoke.xml
  Geometry/MuonCommonData/data/muonYoke/2021/v1/muonYoke.xml
  Geometry/MuonCommonData/data/muonYoke/2021/v2/muonYoke.xml
  Geometry/MuonCommonData/data/v1/MagneticFieldVolumes_1103l.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved, visualization-approved

#27639 Fireworks: Change logs description
  Fireworks/Core/src/FWGeometryTableViewManager.cc
  Fireworks/FWInterface/src/FWFFLooper.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#27589 Modernized ES modules in RecoTracker/MeasurementDet
  RecoLocalTracker/SubCollectionProducers/python/splitter_tracking_RunI_setup_cff.py
  RecoTracker/Configuration/python/RecoTrackerTopBottom_cff.py
  RecoTracker/MeasurementDet/plugins/Chi2ChargeMeasurementEstimatorESProducer.cc
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerESProducer.cc
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerESProducer.h
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.cc
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.h
  RecoTracker/MeasurementDet/plugins/module.cc
  RecoTracker/MeasurementDet/python/MeasurementTrackerESProducer_cfi.py
  RecoTracker/MeasurementDet/src/TkMeasurementDetSet.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27668 DD4hep: HCal Algorithms Moved to Geometry/HcalAlgo Package
  Geometry/HcalAlgo/plugins/BuildFile.xml
  Geometry/HcalAlgo/plugins/DDHCalAngular.cc
  Geometry/HcalAlgo/plugins/DDHCalAngular.h
  Geometry/HcalAlgo/plugins/DDHCalBarrelAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalBarrelAlgo.h
  Geometry/HcalAlgo/plugins/DDHCalEndcapAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalEndcapAlgo.h
  Geometry/HcalAlgo/plugins/DDHCalEndcapModuleAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalEndcapModuleAlgo.h
  Geometry/HcalAlgo/plugins/DDHCalFibreBundle.cc
  Geometry/HcalAlgo/plugins/DDHCalFibreBundle.h
  Geometry/HcalAlgo/plugins/DDHCalForwardAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalForwardAlgo.h
  Geometry/HcalAlgo/plugins/DDHCalLinearXY.cc
  Geometry/HcalAlgo/plugins/DDHCalLinearXY.h
  Geometry/HcalAlgo/plugins/DDHCalTBCableAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalTBCableAlgo.h
  Geometry/HcalAlgo/plugins/DDHCalTBZposAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalTBZposAlgo.h
  Geometry/HcalAlgo/plugins/DDHCalTestBeamAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalTestBeamAlgo.h
  Geometry/HcalAlgo/plugins/DDHCalXtalAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalXtalAlgo.h
  Geometry/HcalAlgo/plugins/dd4hep/DDHCalAngular.cc
  Geometry/HcalAlgo/plugins/dd4hep/DDHCalLinearXY.cc
  Geometry/HcalAlgo/plugins/module.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27175 Ecal DPG - Deploy new software (based on BDT) to recover isolated dead channels…
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/BuildFile.xml
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/interface/EcalDeadChannelRecoveryAlgos.h
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/interface/EcalDeadChannelRecoveryBDTG.h
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/src/EcalDeadChannelRecoveryAlgos.cc
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/src/EcalDeadChannelRecoveryBDTG.cc
  RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test/plugins/EcalDeadChannelRecoveryProducers.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducer.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitWorkerRecover.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitWorkerRecover.h
  RecoLocalCalo/EcalRecProducers/python/ecalRecHit_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#27664 [HGCal] make makeHGCalValidationPlots.py executable
  Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27637 Define and use cms units
  DataFormats/GeometryVector/interface/Phi.h
  DataFormats/Math/interface/CMSUnits.h
  DataFormats/Math/interface/GeantUnits.h
  DataFormats/Math/interface/angle_units.h
  DataFormats/Math/interface/deltaPhi.h
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalBarrelNewAlgo.cc
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalEndcapAlgo.cc
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalPreshowerAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved, urgent

#27646 DD4hep: Add 2021 CMS Geometry Scenario
  Configuration/Geometry/python/DD4hep_GeometrySim_cff.py
  DetectorDescription/DDCMS/data/cms-2015-muon-geometry.xml
  DetectorDescription/DDCMS/data/cms-geometry-2021.xml
  DetectorDescription/DDCMS/plugins/DDDefinitions2Objects.cc
  DetectorDescription/DDCMS/test/python/testGeometry2021.py
  Geometry/CMSCommonData/data/materials/2021/v1/materials.xml
  Geometry/ForwardCommonData/data/zdc/2021/v1/zdc.xml
  Geometry/ForwardCommonData/data/zdclumi/2021/v1/zdclumi.xml
  Geometry/MuonCommonData/data/muonNumbering/2021/v2/muonNumbering.xml
  Geometry/TrackerCommonData/data/pixfwdMaterials/2021/v1/pixfwdMaterials.xml
  SimG4Core/DD4hepGeometry/test/python/testZMM_13TeV_TuneCUETP8M1_cfi_GEN_SIM.py
  SimG4Core/DD4hepGeometry/test/runTest.sh
  SimG4Core/Geometry/interface/DD4hep_DDG4Builder.h
  SimG4Core/Geometry/interface/DDG4ProductionCuts.h
  SimG4Core/Geometry/src/DD4hep_DDG4Builder.cc
  SimG4Core/Geometry/src/DDDWorld.cc
  SimG4Core/Geometry/src/DDG4ProductionCuts.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved, urgent

#27669 DD4hep: Migrate Muon Algorithms to Geometry/MuonCommonData Package
  Geometry/MuonCommonData/plugins/BuildFile.xml
  Geometry/MuonCommonData/plugins/DDGEMAngular.cc
  Geometry/MuonCommonData/plugins/DDGEMAngular.h
  Geometry/MuonCommonData/plugins/DDMuonAngular.cc
  Geometry/MuonCommonData/plugins/DDMuonAngular.h
  Geometry/MuonCommonData/plugins/dd4hep/DDGEMAngular.cc
  Geometry/MuonCommonData/plugins/dd4hep/DDMuonAngular.cc
  Geometry/MuonCommonData/plugins/module.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27681 TEC: Radius is defined in mm
  Geometry/TrackerCommonData/data/tecwheel/2021/v1/tecwheel.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27667 revert SignalPropagationSpeed at GEMDigiProducer
  SimMuon/GEMDigitizer/plugins/GEMDigiProducer.cc
  SimMuon/GEMDigitizer/src/GEMSignalModel.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#27485 Layer Clustering for HGCal Scintillator
  RecoLocalCalo/HGCalRecAlgos/interface/RecHitTools.h
  RecoLocalCalo/HGCalRecAlgos/src/RecHitTools.cc
  RecoLocalCalo/HGCalRecProducers/interface/HGCalCLUEAlgo.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalClusteringAlgoBase.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalLayerTiles.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalTilesConstants.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalCLUEAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27594 Modernized TrackerRecoGeometryESProducer
  RecoTracker/GeometryESProducer/plugins/TrackerRecoGeometryESProducer.cc
  RecoTracker/GeometryESProducer/plugins/TrackerRecoGeometryESProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27596 Modernized ESProducers in RecoPixelVertexing/PixelLowPtUtilities
  RecoLocalTracker/SiStripClusterizer/interface/ClusterChargeCut.h
  RecoPixelVertexing/PixelLowPtUtilities/interface/ClusterShapeHitFilterESProducer.h
  RecoPixelVertexing/PixelLowPtUtilities/plugins/ClusterShapeHitFilterESProducer.cc
  RecoPixelVertexing/PixelLowPtUtilities/plugins/TrackCleanerESProducer.cc
  RecoPixelVertexing/PixelLowPtUtilities/plugins/modules.cc
  RecoPixelVertexing/PixelLowPtUtilities/src/ClusterShapeHitFilterESProducer.cc
  RecoTracker/Record/interface/CkfComponentsRecord.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27670 Run3-sim40 Move all files from interface/src to plugins for TB simulation
  SimG4CMS/HGCalTestBeam/BuildFile.xml
  SimG4CMS/HGCalTestBeam/plugins/AHCalDetId.cc
  SimG4CMS/HGCalTestBeam/plugins/AHCalDetId.h
  SimG4CMS/HGCalTestBeam/plugins/AHCalGeometry.cc
  SimG4CMS/HGCalTestBeam/plugins/AHCalGeometry.h
  SimG4CMS/HGCalTestBeam/plugins/AHCalSD.cc
  SimG4CMS/HGCalTestBeam/plugins/BuildFile.xml
  SimG4CMS/HGCalTestBeam/plugins/HGCalTBAnalyzer.cc
  SimG4CMS/HGCalTestBeam/plugins/HGCalTimingAnalyzer.cc
  SimG4CMS/HcalTestBeam/BuildFile.xml
  SimG4CMS/HcalTestBeam/interface/HcalTB02Analysis.h
  SimG4CMS/HcalTestBeam/interface/HcalTB04Analysis.h
  SimG4CMS/HcalTestBeam/interface/HcalTB06Analysis.h
  SimG4CMS/HcalTestBeam/plugins/BuildFile.xml
  SimG4CMS/HcalTestBeam/plugins/HcalTB02Analysis.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB02HcalNumberingScheme.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB02HcalNumberingScheme.h
  SimG4CMS/HcalTestBeam/plugins/HcalTB02Histo.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB02Histo.h
  SimG4CMS/HcalTestBeam/plugins/HcalTB02NumberingScheme.h
  SimG4CMS/HcalTestBeam/plugins/HcalTB02SD.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB02SD.h
  SimG4CMS/HcalTestBeam/plugins/HcalTB02XtalNumberingScheme.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB02XtalNumberingScheme.h
  SimG4CMS/HcalTestBeam/plugins/HcalTB04Analysis.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB04Histo.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB04Histo.h
  SimG4CMS/HcalTestBeam/plugins/HcalTB04XtalNumberingScheme.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB04XtalNumberingScheme.h
  SimG4CMS/HcalTestBeam/plugins/HcalTB06Analysis.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB06BeamSD.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB06BeamSD.h
  SimG4CMS/HcalTestBeam/plugins/HcalTB06Histo.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB06Histo.h
  SimG4CMS/HcalTestBeam/plugins/HcalTBNumberingScheme.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTBNumberingScheme.h
  SimG4CMS/HcalTestBeam/plugins/module.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#27671 Run3-sim41 Add provision for testing the passive material
  SimG4CMS/Calo/interface/CaloSteppingAction.h
  SimG4CMS/Calo/macros/MakeGVPlots.C
  SimG4CMS/Calo/plugins/CaloSimHitAnalysis.cc
  SimG4CMS/Calo/src/CaloSteppingAction.cc
  SimG4CMS/Calo/test/python/calostepAnalysis_cfg.py
  SimG4CMS/Calo/test/python/calostep_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27678 fix short matrix for 2021
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27683 Updates to DT, PF hadron, HCAL, PPS and pixel calibrations for 2018 UL
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27684 Add support for ESInputTag to ParameterDescription
  FWCore/Integration/test/ProducerWithPSetDesc.cc
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_briefdoc.txt
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_cfi.py
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_doc.txt
  FWCore/ParameterSet/interface/ParameterDescription.h
  FWCore/ParameterSet/interface/ParameterDescriptionNode.h
  FWCore/ParameterSet/src/ParameterDescription.cc
  FWCore/ParameterSet/src/ParameterDescriptionNode.cc
  FWCore/ParameterSet/test/parameterSetDescription_t.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27184 Include option for 2018 Jetid working points
  PhysicsTools/SelectorUtils/interface/PFJetIDSelectionFunctor.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#27661 Tracker reco material tool for phase2 in CMSSW_11_0_X
  SimTracker/TrackerMaterialAnalysis/data/trackingMaterialGroups_ForPhaseII.xml
  SimTracker/TrackerMaterialAnalysis/data/trackingMaterialGroups_ForPhaseII_D4.xml
  SimTracker/TrackerMaterialAnalysis/plugins/ListGroups.cc
  SimTracker/TrackerMaterialAnalysis/plugins/ListGroupsMaterialDifference.h
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseII_cfi.py
  SimTracker/TrackerMaterialAnalysis/test/dumpFullXML_ForPhaseII.py
  SimTracker/TrackerMaterialAnalysis/test/listGroups.py
  SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseII.py
  SimTracker/TrackerMaterialAnalysis/test/trackerRecoMaterial.xml
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseII.py
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino.py
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino_ForPhaseII.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27679 DD4hep: Tracker usage of CMSUnits
  DetectorDescription/DDCMS/data/cms-tracker-2021.xml
  DetectorDescription/DDCMS/plugins/DDAngular.cc
  DetectorDescription/DDCMS/plugins/DDCutTubsFromPoints.cc
  DetectorDescription/DDCMS/plugins/DDHGCalCell.cc
  DetectorDescription/DDCMS/plugins/DDHGCalWafer.cc
  DetectorDescription/DDCMS/plugins/DDHGCalWafer8.cc
  DetectorDescription/DDCMS/plugins/DDLinear.cc
  DetectorDescription/DDCMS/plugins/DDPixBarLayerAlgo.cc
  DetectorDescription/DDCMS/plugins/DDPixBarLayerUpgradeAlgo.cc
  DetectorDescription/DDCMS/plugins/DDPixFwdDiskAlgo.cc
  DetectorDescription/DDCMS/plugins/DDPixPhase1FwdDiskAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTECCoolAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTECModuleAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTECOptoHybAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTECPhiAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTECPhiAltAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTIBLayerAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTIDModuleAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTIDModulePosAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTIDRingAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTOBAxCableAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTOBRadCableAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTrackerAngular.cc
  DetectorDescription/DDCMS/plugins/DDTrackerPhiAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTrackerPhiAltAlgo.cc
  Geometry/HcalAlgo/plugins/dd4hep/DDHCalAngular.cc
  Geometry/MuonCommonData/plugins/dd4hep/DDGEMAngular.cc
  Geometry/MuonCommonData/plugins/dd4hep/DDMuonAngular.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIDAxialCableAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerRingAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27631 [HGCal] New fragments for special HGCal RelVal requests
  Configuration/Generator/python/CE_E_Front_120um_cfi.py
  Configuration/Generator/python/CE_E_Front_200um_cfi.py
  Configuration/Generator/python/CE_E_Front_300um_cfi.py
  Configuration/Generator/python/CE_H_Coarse_300um_cfi.py
  Configuration/Generator/python/CE_H_Coarse_Scint_cfi.py
  Configuration/Generator/python/CE_H_Fine_120um_cfi.py
  Configuration/Generator/python/CE_H_Fine_200um_cfi.py
  Configuration/Generator/python/CE_H_Fine_300um_cfi.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, generators-approved, orp-approved, pdmv-pending, pending-signatures, tests-approved, upgrade-approved

#27647 DQM: Remove empty labels from METAnalyzer
  DQMOffline/JetMET/src/METAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27655 remove GENREFLEX_ARGS flag
  CondCore/CondDB/test/BuildFile.xml
  CondFormats/Alignment/BuildFile.xml
  CondFormats/BTauObjects/BuildFile.xml
  CondFormats/BeamSpotObjects/BuildFile.xml
  CondFormats/CSCObjects/BuildFile.xml
  CondFormats/Calibration/BuildFile.xml
  CondFormats/CastorObjects/BuildFile.xml
  CondFormats/Common/BuildFile.xml
  CondFormats/DQMObjects/BuildFile.xml
  CondFormats/DTObjects/BuildFile.xml
  CondFormats/EcalCorrections/BuildFile.xml
  CondFormats/GEMObjects/BuildFile.xml
  CondFormats/GeometryObjects/BuildFile.xml
  CondFormats/HIObjects/BuildFile.xml
  CondFormats/HLTObjects/BuildFile.xml
  CondFormats/HcalObjects/BuildFile.xml
  CondFormats/L1TObjects/BuildFile.xml
  CondFormats/Luminosity/BuildFile.xml
  CondFormats/MFObjects/BuildFile.xml
  CondFormats/OptAlignObjects/BuildFile.xml
  CondFormats/PCLConfig/BuildFile.xml
  CondFormats/RPCObjects/BuildFile.xml
  CondFormats/RecoMuonObjects/BuildFile.xml
  CondFormats/RunInfo/BuildFile.xml
  CondFormats/SiPhase2TrackerObjects/BuildFile.xml
  CondFormats/SiPixelObjects/BuildFile.xml
  DPGAnalysis/SiStripTools/BuildFile.xml
Labels: alca-pending, analysis-pending, code-checks-approved, comparison-available, db-pending, dqm-approved, hlt-pending, l1-pending, orp-approved, pending-signatures, tests-approved

#27680 Run3-TB39 Update the cfg files, now that the analyzers work with simulation
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct2_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct3_cfg.py
Labels: code-checks-approved, comparison-available, orp-approved, pending-signatures, simulation-approved, tests-approved, upgrade-pending

#27695 throw a meaninful error if LFN isn't found in FileCatalog
  IOPool/Streamer/interface/StreamerInputFile.h
  IOPool/Streamer/src/StreamerFileReader.cc
  IOPool/Streamer/src/StreamerFileReader.h
  IOPool/Streamer/src/StreamerInputFile.cc
  IOPool/Streamer/test/BuildFile.xml
  IOPool/Streamer/test/ReadStreamerFile.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27650 Cleanup PFHBHERecHitCreatorMaxSample etc
  RecoParticleFlow/PFClusterProducer/interface/PFEcalRecHitCreatorMaxSample.h
  RecoParticleFlow/PFClusterProducer/interface/PFHBHERecHitCreatorMaxSample.h
  RecoParticleFlow/PFClusterProducer/plugins/RecHitCreators.cc
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHBHEMaxSampleTimeSelected_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHBHETimeSelected_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHCALLegacy_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHFEM_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHFHAD_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowCluster_cff.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitHCAL_cfi.py
  RecoParticleFlow/PFProducer/python/tools/pfClusteringCustoms.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27689 DD4Hep: Tracker overlaps TEC
  DetectorDescription/DDCMS/plugins/DDTECModuleAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, urgent

#27224 Validation fixes - 10_6_X
  Validation/EventGenerator/plugins/TauValidation.cc
  Validation/EventGenerator/src/HepMCValidationHelper.cc
  Validation/MuonGEMHits/plugins/MuonGEMHitsHarvestor.cc
Labels: backport-ok, bug-fix, comparison-available, dqm-approved, fully-signed, generators-approved, orp-approved, tests-approved

#27435 New plots for Tracking Workspace (Backport to CMSSW_10_6_X of #27330)
  DQM/TrackingMonitor/interface/TrackAnalyzer.h
  DQM/TrackingMonitor/interface/TrackingMonitor.h
  DQM/TrackingMonitor/src/TrackAnalyzer.cc
  DQM/TrackingMonitor/src/TrackingMonitor.cc
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27475 PPS: update of association cuts (backport of #27440)
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_ctpps_2017_cff.py
  Configuration/Eras/python/Modifier_ctpps_2018_cff.py
  RecoCTPPS/ProtonReconstruction/python/ctppsProtons_cff.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved

#27487 [Backport] DQMGEMStatusDigi bug fix
  DQM/GEM/plugins/GEMDQMStatusDigi.cc
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27496 Pr ultra legacy ps weigts
  Configuration/Generator/python/Herwig7Settings/Herwig7LHECommonSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7PSWeightsSettings_cfi.py
  GeneratorInterface/Herwig7Interface/interface/Herwig7Interface.h
  GeneratorInterface/Herwig7Interface/plugins/Herwig7Hadronizer.cc
  GeneratorInterface/Herwig7Interface/python/Herwig7_loadCommonSettings_cff.py
  GeneratorInterface/Herwig7Interface/src/Herwig7Interface.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#27506 Fix energy fractions after jet resolution smearing [106X backport]
  DataFormats/PatCandidates/interface/Jet.h
  DataFormats/PatCandidates/interface/JetCorrFactors.h
  DataFormats/PatCandidates/src/Jet.cc
  DataFormats/PatCandidates/src/JetCorrFactors.cc
Labels: analysis-pending, backport-ok, bug-fix, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#27605 Update ECAL conditions to provide correct reference for 2016 and 2018 UL [10_6_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#27702 Minor improvement to edmPluginHelp output
  FWCore/Integration/test/unit_test_outputs/testDescriptionComments_doc.txt
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_briefdoc.txt
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_doc.txt
  FWCore/ParameterSet/src/ParameterDescriptionBase.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27662 remove obsolete DataFormats/Phase2ITPixelCluster package
  DataFormats/Phase2ITPixelCluster/BuildFile.xml
  DataFormats/Phase2ITPixelCluster/README.md
  DataFormats/Phase2ITPixelCluster/interface/Phase2ITPixelCluster.h
  DataFormats/Phase2ITPixelCluster/interface/Phase2ITPixelClusterShapeCache.h
  DataFormats/Phase2ITPixelCluster/src/Phase2ITPixelCluster.cc
  DataFormats/Phase2ITPixelCluster/src/Phase2ITPixelClusterShapeCache.cc
  DataFormats/Phase2ITPixelCluster/src/classes.h
  DataFormats/Phase2ITPixelCluster/src/classes_def.xml
  DataFormats/Phase2ITPixelCluster/test/BuildFile.xml
  DataFormats/Phase2ITPixelCluster/test/Phase2ITPixelCluster_t.cpp
  RecoLocalTracker/Phase2ITPixelClusterizer/Buildfile.xml
  RecoLocalTracker/Phase2ITPixelClusterizer/plugins/Phase2ITPixelArrayBuffer.h
  RecoLocalTracker/Phase2ITPixelClusterizer/plugins/Phase2ITPixelClusterProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27701 DD4hep: Tracker TEC Bridge overlaps
  DetectorDescription/DDCMS/data/cms-geometry-2021.xml
  DetectorDescription/DDCMS/data/cms-tracker-2021.xml
  DetectorDescription/DDCMS/plugins/DDTECModuleAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTECPhiAltAlgo.cc
  DetectorDescription/DDCMS/test/python/dumpSimGeometry_cfg.py
  DetectorDescription/DDCMS/test/python/testTracker2021Geometry.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27710 Revert TF changes on DEVEL
  DQMServices/Core/src/ROOTFilePB.pb.cc
  DQMServices/Core/src/ROOTFilePB.pb.h
  PhysicsTools/TensorFlow/BuildFile.xml
  PhysicsTools/TensorFlow/interface/TensorFlow.h
  PhysicsTools/TensorFlow/src/NTSession.cc
  PhysicsTools/TensorFlow/src/NTSession.h
  PhysicsTools/TensorFlow/src/TBBSession.cc
  PhysicsTools/TensorFlow/src/TBBSession.h
  PhysicsTools/TensorFlow/src/TensorFlow.cc
  PhysicsTools/TensorFlow/test/BuildFile.xml
  PhysicsTools/TensorFlow/test/testGraphLoading.cc
  PhysicsTools/TensorFlow/test/testHelloWorld.cc
  PhysicsTools/TensorFlow/test/testLoading.cc
  PhysicsTools/TensorFlow/test/testMetaGraphLoading.cc
  PhysicsTools/TensorFlow/test/tfadd_t.cpp
Labels: analysis-pending, comparison-available, dqm-pending, orp-pending, pending-signatures, reconstruction-pending, requires-external, tests-rejected

#27666 HGCal - Minimum Cluster size for Pattern Recognition
  RecoHGCal/TICL/plugins/ClusterFilterByAlgoAndSize.h
  RecoHGCal/TICL/plugins/FilteredLayerClustersProducer.cc
  RecoHGCal/TICL/plugins/filters.cc
  RecoHGCal/TICL/python/ticl_iterations.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27692 remove stuck-TBM specific workflows
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  SimTracker/SiPixelDigitizer/python/customiseStuckTBMSimulation.py
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-approved, pending-signatures, simulation-approved, tests-approved, upgrade-pending

#27625 shared_ptr has arrived to the standard. NFC
  Alignment/Geners/interface/AbsArchive.hh
  Alignment/Geners/interface/AbsCatalog.hh
  Alignment/Geners/interface/AbsReference.hh
  Alignment/Geners/interface/ArchiveRecord.hh
  Alignment/Geners/interface/ArrayRecord.hh
  Alignment/Geners/interface/BinaryArchiveBase.hh
  Alignment/Geners/interface/CPP11_shared_ptr.hh
  Alignment/Geners/interface/ClassId.hh
  Alignment/Geners/interface/ContiguousCatalog.hh
  Alignment/Geners/interface/GeneralCatalog.hh
  Alignment/Geners/interface/GenericIO.hh
  Alignment/Geners/interface/IOIsSharedPtr.hh
  Alignment/Geners/interface/Record.hh
  Alignment/Geners/interface/Reference.hh
  Alignment/Geners/interface/StringArchive.hh
  Alignment/Geners/interface/WriteOnlyCatalog.hh
  Alignment/Geners/interface/binaryIO.hh
  Alignment/Geners/src/AbsArchive.cc
  Alignment/Geners/src/AbsReference.cc
  Alignment/Geners/src/BinaryArchiveBase.cc
  Alignment/Geners/src/ContiguousCatalog.cc
  Alignment/Geners/src/GeneralCatalog.cc
  Alignment/Geners/src/MultiFileArchive.cc
  Alignment/Geners/src/StringArchive.cc
  Alignment/Geners/src/WriteOnlyCatalog.cc
  Alignment/Geners/test/CmdLine.hh
  Alignment/Geners/test/cdump.cc
  Alignment/Geners/test/cmerge.cc
  Alignment/Geners/test/gssa_dump.cc
  Alignment/Geners/test/print_items.cc
  JetMETCorrections/FFTJetModules/interface/FFTJetESParameterParser.h
  JetMETCorrections/FFTJetModules/plugins/FFTJetCorrectorDBReader.cc
  JetMETCorrections/FFTJetModules/plugins/FFTJetLookupTableESProducer.cc
  JetMETCorrections/FFTJetObjects/interface/AbsFFTJetScaleCalculator.h
  JetMETCorrections/FFTJetObjects/interface/FFTJetScaleCalculators.h
  JetMETCorrections/FFTJetObjects/src/loadFFTJetInterpolationTable.cc
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#27626 shared_ptr has arrived to the standard. NFC
  JetMETCorrections/FFTJetModules/interface/FFTJetESParameterParser.h
  JetMETCorrections/FFTJetModules/plugins/FFTJetCorrectorDBReader.cc
  JetMETCorrections/FFTJetModules/plugins/FFTJetLookupTableESProducer.cc
  JetMETCorrections/FFTJetObjects/interface/AbsFFTJetScaleCalculator.h
  JetMETCorrections/FFTJetObjects/interface/FFTJetScaleCalculators.h
  JetMETCorrections/FFTJetObjects/src/loadFFTJetInterpolationTable.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-pending, pending-signatures, tests-approved

#27690 Fix pixel fiducial volume selection for cosmics
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1TrackClusters.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27663 Update clang headers location and changed interfaces
  Utilities/StaticAnalyzers/src/ClangCmsCheckerPluginRegister.cpp
  Utilities/StaticAnalyzers/src/ClassChecker.cpp
Labels: comparison-available, core-pending, orp-pending, pending-signatures, requires-external, tests-approved

#27709 Restore updated PPS association cuts for 2017
  RecoCTPPS/ProtonReconstruction/python/ctppsProtons_cff.py
Labels: comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27719 Fix copy constructor for TRecHit1DMomConstraint
  RecoTracker/TransientTrackingRecHit/interface/TRecHit1DMomConstraint.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27715 Provide initial values for all struct members in SiStripDcsInfo
  DQM/SiStripMonitorClient/plugins/SiStripDcsInfo.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27720 Fix filling histograms in JetTester_HeavyIons
  Validation/RecoJets/plugins/JetTester_HeavyIons.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27716 Added [[fallthrough]] to SUSY_HLT_SingleLepton switch statements
  HLTriggerOffline/SUSYBSM/src/SUSY_HLT_SingleLepton.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27721 Explicitly use default c'tor in muon DetId copy c'tors
  DataFormats/MuonDetId/src/DTLayerId.cc
  DataFormats/MuonDetId/src/DTSuperLayerId.cc
  DataFormats/MuonDetId/src/DTWireId.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27717 Added missing return statement in switch for SiStripPayloadInspectorHelper
  CondCore/SiStripPlugins/interface/SiStripPayloadInspectorHelper.h
Labels: code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, tests-approved

#27708 Run3-TB42 Correct numbering for AHCal so that |row|/|column| can exceed 10
  Geometry/HGCalCommonData/plugins/DDAHcalModuleAlgo.cc
  SimG4CMS/HGCalTestBeam/plugins/AHCalSD.cc
Labels: code-checks-approved, comparison-available, geometry-approved, orp-approved, pending-signatures, simulation-approved, tests-approved, upgrade-pending

#27609 Run3-hcx213 Make HcalSimParameter class to handle simulation parameters for HCAL
  CondFormats/GeometryObjects/interface/HcalSimulationParameters.h
  CondFormats/GeometryObjects/src/T_EventSetup_HcalParameters.cc
  CondFormats/GeometryObjects/src/classes.h
  CondFormats/GeometryObjects/src/classes_def.xml
  CondFormats/GeometryObjects/test/testSerializationGeometryObjects.cpp
  Geometry/HcalCommonData/interface/HcalSimParametersFromDD.h
  Geometry/HcalCommonData/plugins/HcalSimParametersESModule.cc
  Geometry/HcalCommonData/python/hcalDDConstants_cff.py
  Geometry/HcalCommonData/python/testGeometry17aXML_cfi.py
  Geometry/HcalCommonData/python/testGeometry17bXML_cfi.py
  Geometry/HcalCommonData/python/testPhase0GeometryXML_cfi.py
  Geometry/HcalCommonData/python/testPhase1GeometryXML_cfi.py
  Geometry/HcalCommonData/python/testPhase2GeometryFineXML_cfi.py
  Geometry/HcalCommonData/python/testPhase2GeometryXML_cfi.py
  Geometry/HcalCommonData/src/HcalSimParametersFromDD.cc
  Geometry/HcalCommonData/test/HcalParametersAnalyzer.cc
  Geometry/HcalCommonData/test/python/runHcalParametersFromDDAnalyzer_cfg.py
Labels: alca-pending, code-checks-approved, comparison-available, db-pending, geometry-pending, orp-approved, pending-signatures, tests-approved

#27713 Add 2023 test workflow to the short PyRelVal matrix, add a protection for not defined workflows
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#27706 Fixed Geant4 sequential
  SimG4Core/Application/interface/ExceptionHandler.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/RunManager.cc
  SimG4Core/Application/src/RunManagerMT.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27714 Add explicit fallthrough attribute to hash64
  CondFormats/Common/src/hash64.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, tests-approved

#27725 DD4hep: Numeric vector units parsing
  DetectorDescription/DDCMS/plugins/DDCutTubsFromPoints.cc
  DetectorDescription/DDCMS/plugins/DDDefinitions2Objects.cc
  DetectorDescription/DDCMS/plugins/DDTrackerAngular.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, urgent

#27733 Bug fix for 2016-2017 HBHE negative energy filter
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27728 DD4hep: Update to a new DD4hep version - no need to cleanup
  DetectorDescription/DDCMS/interface/DDDetector.h
  DetectorDescription/DDCMS/src/DDDetector.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, requires-external, tests-approved

#27740 Fixes for DDShapes to support DD4hep migration
  DetectorDescription/DDCMS/interface/DDShapes.h
  DetectorDescription/DDCMS/src/DDShapes.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27699 [TkDQM] Update of SiStripMonitorTrack : ES access put outside tracks loop
  DQM/SiStripMonitorTrack/interface/SiStripMonitorTrack.h
  DQM/SiStripMonitorTrack/src/SiStripMonitorTrack.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27705 TemplateReco: Fix out of bounds memory write for very large clusters
  RecoLocalTracker/SiPixelRecHits/src/SiPixelTemplateReco.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27735 Run3-hcx215 Transfer ForwardShield algorithm to DD4Hep
  Geometry/HcalAlgo/data/cms-test-ddhcalForwardShield-algorithm.xml
  Geometry/HcalAlgo/plugins/dd4hep/DDHCalFibreBundle.cc
  Geometry/HcalAlgo/python/testGeomForwardShield_cfi.py
  Geometry/HcalAlgo/test/python/dumpForwardShield_cfg.py
  Geometry/HcalAlgo/test/python/testForwardShield.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27736 DD4hep: Tracker overlaps on PixelForwardDiskRings
  DetectorDescription/DDCMS/plugins/DDCutTubsFromPoints.cc
  DetectorDescription/DDCMS/plugins/DDDefinitions2Objects.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27723 Fix expression evaluator unit test
  CommonTools/Utils/src/ExpressionEvaluator.cc
  CommonTools/Utils/test/ExpressionEvaluatorUnitTest.cpp
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved

#27711 Phase2-hgx209 Clean up the plugin area in view of transition to dd4hep
  Geometry/HGCalCommonData/plugins/DDHGCalCell.cc
  Geometry/HGCalCommonData/plugins/DDHGCalCell.h
  Geometry/HGCalCommonData/plugins/DDHGCalEEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalEEAlgo.h
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.h
  Geometry/HGCalCommonData/plugins/DDHGCalModule.cc
  Geometry/HGCalCommonData/plugins/DDHGCalModule.h
  Geometry/HGCalCommonData/plugins/DDHGCalModuleAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalModuleAlgo.h
  Geometry/HGCalCommonData/plugins/DDHGCalNoTaperEndcap.cc
  Geometry/HGCalCommonData/plugins/DDHGCalNoTaperEndcap.h
  Geometry/HGCalCommonData/plugins/DDHGCalTBModule.cc
  Geometry/HGCalCommonData/plugins/DDHGCalTBModule.h
  Geometry/HGCalCommonData/plugins/DDHGCalTBModuleX.cc
  Geometry/HGCalCommonData/plugins/DDHGCalTBModuleX.h
  Geometry/HGCalCommonData/plugins/DDHGCalWafer.cc
  Geometry/HGCalCommonData/plugins/DDHGCalWafer.h
  Geometry/HGCalCommonData/plugins/DDHGCalWafer8.cc
  Geometry/HGCalCommonData/plugins/DDHGCalWafer8.h
  Geometry/HGCalCommonData/plugins/DDHGCalWaferAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalWaferAlgo.h
  Geometry/HGCalCommonData/plugins/module.cc
  Geometry/HGCalCommonData/python/testGeometryExtended_cff.py
  Geometry/HGCalCommonData/test/dumpExtendedHGCalGeometry_cfg.py
Labels: code-checks-approved, comparison-available, geometry-approved, orp-approved, pending-signatures, tests-approved, upgrade-pending

#27656 APE tool: Trend plots, some minor fixes
  Alignment/APEEstimation/data/lumiperrun2017.txt
  Alignment/APEEstimation/data/lumiperrun2018.txt
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitter.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitterTemplates.py
  Alignment/APEEstimation/test/autoSubmitter/config.ini
  Alignment/APEEstimation/test/autoSubmitter/helpers.py
  Alignment/APEEstimation/test/batch/startSkim.py
  Alignment/APEEstimation/test/cfgTemplate/apeEstimator_cfg.py
  Alignment/APEEstimation/test/plottingTools/drawIterations.py
  Alignment/APEEstimation/test/plottingTools/drawResults.py
  Alignment/APEEstimation/test/plottingTools/drawTrend.py
  Alignment/APEEstimation/test/plottingTools/resultPlotter.py
  Alignment/APEEstimation/test/plottingTools/trendPlotter.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27517 Phase-2 InnerTracker conditions from DB (version 2)
  Configuration/AlCa/python/autoCond.py
  Configuration/AlCa/python/autoCondPhase2.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  RecoLocalTracker/SiPixelRecHits/python/PixelCPEGeneric_cfi.py
  SLHCUpgradeSimulations/Geometry/python/fakeConditions_phase2TkT14_cff.py
  SLHCUpgradeSimulations/Geometry/python/fakeConditions_phase2TkT6_cff.py
  SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, geometry-pending, orp-approved, pdmv-pending, pending-signatures, reconstruction-pending, simulation-pending, tests-approved, upgrade-pending

#27697 Run3-TB40 Correct AHCal DetId for # of row/column and apply smearing for position/time
  SimG4CMS/HGCalTestBeam/plugins/AHCalDetId.cc
  SimG4CMS/HGCalTestBeam/plugins/AHCalDetId.h
  SimG4CMS/HGCalTestBeam/plugins/HGCalTBAnalyzer.cc
Labels: code-checks-approved, comparison-available, orp-approved, pending-signatures, simulation-approved, tests-approved, upgrade-pending

#27704 Run3-TB41 Add a special particle gun for HGCal TB studies
  IOMC/ParticleGuns/interface/BeamMomentumGunProducer.h
  IOMC/ParticleGuns/src/BeamMomentumGunProducer.cc
  IOMC/ParticleGuns/src/SealModule.cc
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1el100_cfg.py
Labels: code-checks-approved, comparison-available, generators-approved, orp-approved, pending-signatures, simulation-approved, tests-approved, upgrade-pending

#27658 Introduce Payload Inspector for SiPixel conditions
  CondCore/SiPixelPlugins/interface/SiPixelPayloadInspectorHelper.h
  CondCore/SiPixelPlugins/plugins/BuildFile.xml
  CondCore/SiPixelPlugins/plugins/SiPixelLorentzAngle_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelQuality_PayloadInspector.cc
  CondCore/SiPixelPlugins/test/testSiPixelLorentzAngle.sh
  CondCore/SiPixelPlugins/test/testSiPixelQuality.sh
  CondCore/SiPixelPlugins/test/testSiPixelQualityMap.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27737 Put test in condition for arm and ppc
  CondCore/CondDB/test/BuildFile.xml
Labels: code-checks-approved, comparison-pending, db-approved, fully-signed, orp-approved, tests-approved

#27610 Update RivetInterface for Rivet 3.x
  GeneratorInterface/RivetInterface/interface/RivetAnalysis.h
  GeneratorInterface/RivetInterface/interface/RivetAnalyzer.h
  GeneratorInterface/RivetInterface/plugins/GenParticles2HepMCConverter.cc
  GeneratorInterface/RivetInterface/plugins/HTXSRivetProducer.cc
  GeneratorInterface/RivetInterface/plugins/ParticleLevelProducer.cc
  GeneratorInterface/RivetInterface/plugins/RivetAnalyzer.cc
  GeneratorInterface/RivetInterface/python/rivetAnalyzer_cfi.py
  GeneratorInterface/RivetInterface/src/CMS_2013_I1224539_DIJET.cc
  GeneratorInterface/RivetInterface/src/HiggsTemplateCrossSections.cc
  GeneratorInterface/RivetInterface/test/particleLevel_cfg.py
  GeneratorInterface/RivetInterface/test/runRivetAnalyzerMiniAOD_cfg.py
  GeneratorInterface/RivetInterface/test/runRivetHTXS_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#27630 Miscellanous fixes to SiPixel Bad Components db loaders
  CondFormats/SiPixelObjects/test/SiPixelBadFEDChannelSimulationSanityChecker_cfg.py
  CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerWriteFromASCII.cc
  CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerWriteFromASCII_cfg.py
  CondFormats/SiPixelObjects/test/SiPixelQualityProbabilitiesWriteFromASCII.cc
  CondFormats/SiPixelObjects/test/SiPixelQualityProbabilitiesWriteFromASCII_cfg.py
  CondTools/SiPixel/test/SiPixelBadModuleByHandBuilder.cc
  CondTools/SiPixel/test/SiPixelBadModuleByHandBuilder.h
  CondTools/SiPixel/test/SiPixelBadModuleByHandBuilderFromROCList_cfg.py
  CondTools/SiPixel/test/SiPixelBadModuleByHandBuilder_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27756 Update the ADG database host names used by ConfDB
  HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#27744 Scenario 2021, no overlaps for the Muon system in DD and DD4HEP geome…
  DetectorDescription/DDCMS/data/cms-geometry-2021.xml
  Geometry/CMSCommonData/data/cavern/2021/v1/cavern.xml
  Geometry/CMSCommonData/data/cavernData/2021/v1/cavernData.xml
  Geometry/CMSCommonData/data/cms/2021/v2/cms.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/MuonCommonData/data/mb4Shield/2021/v1/mb4Shield.xml
  Geometry/MuonCommonData/data/mbCommon/2021/v1/mbCommon.xml
Labels: code-checks-approved, comparison-available, geometry-approved, orp-approved, pending-signatures, tests-approved, upgrade-pending

#27755 apply postEra customization for HI 2018 data
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#27727 Move 2015/2016 Data ReReco ZeroBias RelVals to use @rerecoZeroBias DQM sequence
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: code-checks-approved, comparison-available, dqm-approved, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#27722 Fix TrackerAlignment_PayloadInspector switch case fallthrough
  CondCore/AlignmentPlugins/plugins/TrackerAlignment_PayloadInspector.cc
Labels: bug-fix, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27638 [DQM] Migrated subsystem availability per lumi plot to softFED
  DQM/Integration/python/clients/info_dqm_sourceclient-live_cfg.py
  DQMServices/Components/BuildFile.xml
  DQMServices/Components/plugins/DQMProvInfo.cc
  DQMServices/Components/plugins/DQMProvInfo.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27752 DD4hep: Tracker FixSupport
  DetectorDescription/DDCMS/plugins/DDTOBRadCableAlgo.cc
  Geometry/TrackerCommonData/data/tecwheel6.xml
  Geometry/TrackerCommonData/data/tecwheela.xml
  Geometry/TrackerCommonData/data/tecwheelb.xml
  Geometry/TrackerCommonData/data/tecwheelc.xml
  Geometry/TrackerCommonData/data/tecwheeld.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27763 Run3-sim42 Modify the hit analysis class to make detailed comparison between G4 and GV
  SimG4CMS/Calo/macros/MakeGVPlots.C
  SimG4CMS/Calo/plugins/CaloSimHitAnalysis.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27764 Use puppi jets for phase2 scenario for PF validation
  Validation/RecoParticleFlow/python/particleFlowDQM_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27768 Exclude dark photon 3000022 tracking for CMSSW_11_0_X
  SimG4Core/Generators/src/Generator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27769 Run3-TB43 Create interface/src for SimG4CMS/HGCalTestBeam to help TB analysis
  Geometry/HGCalCommonData/BuildFile.xml
  Geometry/HGCalCommonData/interface/AHCalParameters.h
  Geometry/HGCalCommonData/plugins/DDAHcalModuleAlgo.cc
  Geometry/HGCalCommonData/src/AHCalParameters.cc
  SimG4CMS/HGCalTestBeam/BuildFile.xml
  SimG4CMS/HGCalTestBeam/interface/AHCalDetId.h
  SimG4CMS/HGCalTestBeam/interface/AHCalGeometry.h
  SimG4CMS/HGCalTestBeam/plugins/AHCalGeometry.cc
  SimG4CMS/HGCalTestBeam/plugins/AHCalSD.cc
  SimG4CMS/HGCalTestBeam/plugins/BuildFile.xml
  SimG4CMS/HGCalTestBeam/plugins/HGCalTBAnalyzer.cc
  SimG4CMS/HGCalTestBeam/src/AHCalDetId.cc
  SimG4CMS/HGCalTestBeam/src/AHCalGeometry.cc
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1el100_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct2_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct3_cfg.py
Labels: code-checks-approved, comparison-available, geometry-approved, orp-approved, pending-signatures, simulation-approved, tests-approved, upgrade-pending

#27773 DD4hep: Tracker overlaps on pixel forward blades
  DetectorDescription/DDCMS/plugins/DDPixPhase1FwdDiskAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTECModuleAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27777 Update TEC in 2021 Scenario (squash of 27745 commits)
  DetectorDescription/DDCMS/data/cms-geometry-2021.xml
  DetectorDescription/DDCMS/plugins/DDDefinitions2Objects.cc
Labels: code-checks-approved, comparison-pending, fully-signed, geometry-approved, orp-approved, tests-approved

#27644 enabling UL regression for 2018 (and likely Run3)
  Configuration/AlCa/python/autoCond.py
  RecoEgamma/EgammaTools/python/regressionModifier_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27750 Adding FRD file header (DAQ)
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/interface/FedRawDataInputSource.h
  EventFilter/Utilities/plugins/FRDStreamSource.cc
  EventFilter/Utilities/plugins/RawEventFileWriterForBU.cc
  EventFilter/Utilities/plugins/RawEventFileWriterForBU.h
  EventFilter/Utilities/src/EvFDaqDirector.cc
  EventFilter/Utilities/src/FedRawDataInputSource.cc
  EventFilter/Utilities/test/analyzerGNs_cfg.py
  EventFilter/Utilities/test/startBU.py
  IOPool/Streamer/interface/FRDFileHeader.h
Labels: code-checks-approved, comparison-available, core-approved, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27751 Fix product labels for tokens in VolumeBasedMagneticFieldESProducer
  MagneticField/GeomBuilder/plugins/VolumeBasedMagneticFieldESProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27640 Moving Sequence to Task :RecoLocalMuon RecoMuon RecoEgamma RecoEcal RecoHI
  RecoEcal/Configuration/python/RecoEcalCosmics_cff.py
  RecoEcal/Configuration/python/RecoEcal_cff.py
  RecoEcal/EgammaClusterProducers/python/cosmicClusteringSequence_cff.py
  RecoEcal/EgammaClusterProducers/python/dynamicHybridClusteringSequence_cff.py
  RecoEcal/EgammaClusterProducers/python/ecalClusteringSequence_cff.py
  RecoEcal/EgammaClusterProducers/python/fixedMatrixClusteringSequence_cff.py
  RecoEcal/EgammaClusterProducers/python/fixedMatrixPreshowerClusteringSequence_cff.py
  RecoEcal/EgammaClusterProducers/python/islandClusteringSequence_cff.py
  RecoEcal/EgammaClusterProducers/python/particleFlowSuperClusteringSequence_cff.py
  RecoEcal/EgammaClusterProducers/python/preshowerClusteringSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/photonSequence_cff.py
  RecoHI/HiEgammaAlgos/python/HiEgamma_cff.py
  RecoHI/HiEgammaAlgos/python/HiIslandClusteringSequence_cff.py
  RecoLocalMuon/Configuration/python/RecoLocalMuonCosmics_cff.py
  RecoLocalMuon/Configuration/python/RecoLocalMuon_cff.py
  RecoLocalMuon/GEMRecHit/python/gemLocalReco_cff.py
  RecoLocalMuon/GEMRecHit/python/me0LocalReco_cff.py
  RecoMuon/Configuration/python/RecoMuonCosmics_cff.py
  RecoMuon/MuonIdentification/python/me0MuonReco_cff.py
  RecoMuon/StandAloneMuonProducer/python/standAloneCosmicMuons_cff.py
Labels: code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, upgrade-pending

#27757 Update the ADG database host names used by ConfDB (10.6.x)
  HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py
Labels: backport-ok, bug-fix, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#27760 Update the ADG database host names used by ConfDB (10.2.x)
  HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py
Labels: backport-ok, bug-fix, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#27759 Update the ADG database host names used by ConfDB (10.3.x)
  HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py
Labels: backport-ok, bug-fix, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#27762 update configurations for phase2 Inner Tracker ntuple unit tests
  SLHCUpgradeSimulations/Geometry/test/phase2_digi_reco_pixelntuple_cfg.py
  SLHCUpgradeSimulations/Geometry/test/phase2_reco_pixelntuple_cfg.py
Labels: code-checks-approved, comparison-available, geometry-approved, orp-approved, pending-signatures, tests-approved, upgrade-pending

#27742 Reduce DD exposure to help with furter DD4hep migration
  CondTools/Geometry/plugins/PGeometricDetBuilder.cc
  DetectorDescription/Core/interface/DDExpandedView.h
  DetectorDescription/Core/interface/DDFilteredView.h
  DetectorDescription/Core/src/DDExpandedView.cc
  DetectorDescription/Core/src/DDFilteredView.cc
  Geometry/MTDCommonData/test/TestMTDNumbering.cc
  Geometry/MTDGeometryBuilder/src/MTDGeomBuilderFromGeometricTimingDet.cc
  Geometry/MTDGeometryBuilder/src/MTDGeometry.cc
  Geometry/MTDNumberingBuilder/bin/stubs/GeometricTimingDetLoader.cc
  Geometry/MTDNumberingBuilder/interface/GeometricTimingDet.h
  Geometry/MTDNumberingBuilder/interface/GeometricTimingDetExtra.h
  Geometry/MTDNumberingBuilder/plugins/CmsMTDBuilder.cc
  Geometry/MTDNumberingBuilder/plugins/CmsMTDConstruction.cc
  Geometry/MTDNumberingBuilder/plugins/CmsMTDDiscBuilder.cc
  Geometry/MTDNumberingBuilder/plugins/CmsMTDEndcapBuilder.cc
  Geometry/MTDNumberingBuilder/plugins/CmsMTDSubStrctBuilder.cc
  Geometry/MTDNumberingBuilder/plugins/CmsMTDTrayBuilder.cc
  Geometry/MTDNumberingBuilder/plugins/MTDGeometricTimingDetExtraESModule.cc
  Geometry/MTDNumberingBuilder/src/CmsMTDDebugNavigator.cc
  Geometry/MTDNumberingBuilder/src/CmsMTDStringToEnum.cc
  Geometry/MTDNumberingBuilder/src/GeometricTimingDet.cc
  Geometry/MTDNumberingBuilder/test/MTDModuleNumbering.cc
  Geometry/MTDNumberingBuilder/test/MTDTopologyAnalyzer.cc
  Geometry/MTDNumberingBuilder/test/mtd_cfg.py
  Geometry/TrackerGeometryBuilder/src/TrackerGeomBuilderFromGeometricDet.cc
  Geometry/TrackerGeometryBuilder/src/TrackerGeometry.cc
  Geometry/TrackerGeometryBuilder/test/ModuleInfo.cc
  Geometry/TrackerNumberingBuilder/bin/stubs/GeometricDetLoader.cc
  Geometry/TrackerNumberingBuilder/interface/GeometricDet.h
  Geometry/TrackerNumberingBuilder/interface/GeometricDetExtra.h
  Geometry/TrackerNumberingBuilder/plugins/CmsTrackerPixelPhase1EndcapBuilder.cc
  Geometry/TrackerNumberingBuilder/src/CmsTrackerDebugNavigator.cc
  Geometry/TrackerNumberingBuilder/src/GeometricDet.cc
  Geometry/TrackerNumberingBuilder/src/GeometricDetExtra.cc
  Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc
  SLHCUpgradeSimulations/Geometry/test/ModuleInfo_Phase2.cc
Labels: code-checks-approved, comparison-available, db-approved, geometry-approved, orp-approved, pending-signatures, tests-approved, upgrade-pending

#27775 [HGCal] Validation: Increase the score for matching Layerclusters and CaloParticles
  Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27790 DD4hep: Tracker overlaps on OuterCylinder
  DetectorDescription/DDCMS/plugins/DDTECCoolAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTECModuleAlgo.cc
  DetectorDescription/DDCMS/plugins/DDTrackerAngular.cc
  DetectorDescription/DDCMS/plugins/DDTrackerLinear.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27761 DD4hep: Tracker overlaps TIB
  DetectorDescription/DDCMS/plugins/DDTIBLayerAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27712 Replace DecodingStructure struct with local unsigned integers
  CondFormats/SiPixelObjects/interface/SiPixelGainCalibration.h
  CondFormats/SiPixelObjects/src/SiPixelGainCalibration.cc
  CondFormats/SiPixelObjects/src/SiPixelGainCalibrationForHLT.cc
  CondFormats/SiPixelObjects/src/SiPixelGainCalibrationOffline.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27789 Geant4 parameters for tracking in field
  SimG4Core/Application/python/g4SimHits_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27776 Run3-sim43 Expand passive hits to contain PDG Id of track and store this in CaloSteppingAction
  SimDataFormats/CaloHit/interface/PassiveHit.h
  SimDataFormats/CaloHit/src/classes_def.xml
  SimG4CMS/Calo/interface/CaloSteppingAction.h
  SimG4CMS/Calo/src/CaloSteppingAction.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27793 Removed obsolete code from SIM
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Calo/src/HFFibreFiducial.cc
  SimG4CMS/Forward/src/CastorSD.cc
  SimG4CMS/Muon/interface/MuonGEMFrameRotation.h
  SimG4CMS/Muon/interface/MuonME0FrameRotation.h
  SimG4CMS/Muon/src/MuonGEMFrameRotation.cc
  SimG4CMS/Muon/src/MuonME0FrameRotation.cc
  SimG4CMS/Muon/src/MuonSensitiveDetector.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27809 renamed TopLHEFilter -> LHEJetFilter
  GeneratorInterface/GenFilters/BuildFile.xml
  GeneratorInterface/GenFilters/python/LHEJetFilter_cfi.py
  GeneratorInterface/GenFilters/src/LHEJetFilter.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#27805 python3 compatibility change in autoCondPhase2.py
  Configuration/AlCa/python/autoCondPhase2.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27633 Light by light modifier 1100 pre1
  Configuration/ProcessModifiers/python/egamma_lowPt_exclusive_cff.py
  RecoEcal/EgammaClusterProducers/python/ecalDigiSelector_cfi.py
  RecoEcal/EgammaClusterProducers/python/particleFlowSuperClusterECAL_cfi.py
  RecoEcal/EgammaClusterProducers/python/reducedRecHitsSequence_cff.py
  RecoEgamma/EgammaElectronProducers/python/ecalDrivenElectronSeeds_cfi.py
  RecoEgamma/EgammaElectronProducers/python/gedGsfElectrons_cfi.py
  RecoEgamma/EgammaElectronProducers/python/gsfElectrons_cfi.py
  RecoEgamma/EgammaIsolationAlgos/python/interestingEgammaIsoDetIdsSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/gedPhotonSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/photonCore_cfi.py
  RecoEgamma/EgammaPhotonProducers/python/photons_cfi.py
  RecoLocalCalo/Configuration/python/RecoLocalCalo_EventContent_cff.py
  RecoLocalTracker/Configuration/python/RecoLocalTracker_EventContent_cff.py
  RecoParticleFlow/PFProducer/python/particleFlowBlock_cfi.py
  RecoParticleFlow/PFProducer/python/particleFlow_cfi.py
  RecoParticleFlow/PFTracking/python/pfTrackElec_cfi.py
  RecoParticleFlow/PFTracking/python/trackerDrivenElectronSeeds_cfi.py
Labels: code-checks-approved, comparison-available, operations-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#27465 Update tau anti electron discriminators in RECO and MiniAOD
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
  RecoTauTag/Configuration/python/HPSPFTaus_cff.py
  RecoTauTag/RecoTau/test/rerunMVAIsolationOnMiniAOD.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#27691 Jetid muon fraction fix
  PhysicsTools/SelectorUtils/interface/PFJetIDSelectionFunctor.h
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved, xpog-approved

#27772 functionality to avoid creating (empty) DQM outputs for invalid HLT paths
  CommonTools/TriggerUtils/interface/GenericTriggerEventFlag.h
  CommonTools/TriggerUtils/src/GenericTriggerEventFlag.cc
  DQMOffline/Trigger/plugins/TopMonitor.cc
  DQMOffline/Trigger/plugins/TopMonitor.h
Labels: analysis-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27779 Ad-hoc fix of Relvals TaskName more than 50 characters
  Configuration/PyReleaseValidation/python/MatrixInjector.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27753 Add combined premixing workflows for Run 3
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27783 Phase2-hgx212 Rearrange Geometry/HGCalCommonData in view of DD4Hep transition
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalEE-algorithm.xml
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalHEmix-algorithm.xml
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalHEsil-algorithm.xml
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalcell-algorithm.xml
  Geometry/HGCalCommonData/plugins/BuildFile.xml
  Geometry/HGCalCommonData/plugins/DDAHcalModuleAlgo.cc
  Geometry/HGCalCommonData/plugins/DDAHcalModuleAlgo.h
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalCell.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalWafer.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalWafer8.cc
  Geometry/HGCalCommonData/plugins/module.cc
  Geometry/HGCalCommonData/test/python/dumpEEGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/dumpExtendedHGCalGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHEmixGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHEsilGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalCellGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWafer8Geometry_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWaferGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/dumpTBGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/hgcalParameters_cfg.py
  Geometry/HGCalCommonData/test/python/testFastTimeNumbering_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalCellGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalEEGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalHEmixGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalHEsilGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalNumbering_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalParameters_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalWafer8Geometry_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalWaferGeometry_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalWafer_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#27784 Fix 'allowed' configuration construct to deduce also later types than just the first one
  FWCore/ParameterSet/python/Types.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27796 Fix gcc9 warnings in OnlineDB/EcalCondDB
  OnlineDB/EcalCondDB/src/LMFLmrSubIOV.cc
  OnlineDB/EcalCondDB/src/LMFRunIOV.cc
  OnlineDB/EcalCondDB/src/RunDCSHVDat.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27798 Fix warnings in gcc9 DataFormats/HGCDigi
  DataFormats/HGCDigi/interface/HGCSample.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#27807 Fix gcc9 warnings : Add breaks in switch statements
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalMatacqAnalyzer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27808 Fix gcc9 warnigns in EventFilter/CTPPSRawToDigi add 0 init values
  EventFilter/CTPPSRawToDigi/src/CTPPSPixelDataFormatter.cc
  EventFilter/CTPPSRawToDigi/src/CTPPSTotemDataFormatter.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27822 Fix gcc9 warnings in RecoEgamma/EgammaElectronAlgos
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27831 Made commandline utils python3 compatible
  FWCore/ParameterSet/scripts/edmPythonConfigToCppValidation
  FWCore/Utilities/scripts/edmAddClassVersion
  FWCore/Utilities/scripts/edmCheckClassVersion
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27804 First attempt to fix DQM GUI urls in RelMon
  Utilities/RelMon/python/directories2html.py
  Utilities/RelMon/python/web/templates/directory_summary.html
  Utilities/RelMon/python/web/templates/release_summary.html
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27806 NanoAOD step added in upgrade 2017 samples
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27820 Fix gcc9 warnings in DQM/EcalMonitorClient
  DQM/EcalMonitorClient/src/SummaryClient.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27791 modifying filters to use with higgs samples
  GeneratorInterface/Core/interface/EmbeddingHepMCFilter.h
  GeneratorInterface/Core/src/EmbeddingHepMCFilter.cc
  TauAnalysis/MCEmbeddingTools/python/EmbeddingPythia8Hadronizer_cfi.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, simulation-approved, tests-approved

#27665 Phase2-hcx214 Add a new scenario and workflow with latest Phase2 configuration including HFNose
  Configuration/Eras/python/Era_Phase2C10_cff.py
  Configuration/Eras/python/Era_Phase2C10_timing_cff.py
  Configuration/Eras/python/Era_Phase2C10_timing_layer_bar_cff.py
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2026D47Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D47_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/Eras.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D47XML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27817 Run3-hcx219 Transform one more DDD algorithm to DD4Hep type
  Geometry/HcalAlgo/data/cms-test-ddhcalXtal-algorithm.xml
  Geometry/HcalAlgo/plugins/DDHCalXtalAlgo.cc
  Geometry/HcalAlgo/plugins/dd4hep/DDHCalXtalAlgo.cc
  Geometry/HcalAlgo/python/testGeomHcalXtal_cfi.py
  Geometry/HcalAlgo/test/python/dumpHcalXtal_cfg.py
  Geometry/HcalAlgo/test/python/testHcalXyal_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27859 Replace inconsistent tabbing with spaces in MatrixInector.py
  Configuration/PyReleaseValidation/python/MatrixInjector.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27799 Fix warnings for gcc9 in DQMServices/Core
  DQMServices/Core/interface/DQMNet.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27811 Fix gcc 9 warnings DQM/DTMonitorClient - Add fallthroughs to clear the warnings
  DQM/DTMonitorClient/src/DTLocalTriggerLutTest.cc
  DQM/DTMonitorClient/src/DTLocalTriggerTest.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27825 Fix gcc9 warnings Alignment/MillePedeAlignmentAlgorithm
  Alignment/MillePedeAlignmentAlgorithm/src/PedeReader.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27834 Fix gcc9 warnings in GeneratorInterface
  GeneratorInterface/Herwig6Interface/src/params.inc
  GeneratorInterface/LHEInterface/src/LHERunInfo.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#27837 Fix gcc9 warnings in CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos
  CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos/src/TEcnaNArrayD.cc
  CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos/src/TEcnaRead.cc
  CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos/src/TEcnaRun.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27838 Fix gcc9 warnings in Alignment
  Alignment/CocoaApplication/bin/cocoa.cpp
  Alignment/CocoaModel/src/ALIUnitsTable.cc
  Alignment/CocoaModel/src/EntryAngleAffAngles.cc
  Alignment/CommonAlignmentAlgorithm/src/AlignableDataIORoot.cc
  Alignment/CommonAlignmentAlgorithm/src/AlignmentParameterBuilder.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27840 Fix gcc9 warnings in Calibration
  CalibCalorimetry/HcalAlgos/src/PadeTableODE.cc
  CalibFormats/SiStripObjects/src/SiStripQuality.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27845 Fix warnings for gcc9 in DQM
  DQM/EcalCommon/src/MESetBinningUtils.cc
  DQM/TrackingMonitor/src/TrackAnalyzer.cc
  DQMOffline/Trigger/plugins/BPHMonitor.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27439 HGCAL TICL seeded iteration
  DataFormats/HGCalReco/BuildFile.xml
  DataFormats/HGCalReco/interface/TICLSeedingRegion.h
  DataFormats/HGCalReco/interface/Trackster.h
  DataFormats/HGCalReco/src/classes.h
  DataFormats/HGCalReco/src/classes_def.xml
  RecoHGCal/TICL/interface/PatternRecognitionAlgoBase.h
  RecoHGCal/TICL/interface/SeedingRegionAlgoBase.h
  RecoHGCal/TICL/plugins/BuildFile.xml
  RecoHGCal/TICL/plugins/HGCDoublet.cc
  RecoHGCal/TICL/plugins/HGCDoublet.h
  RecoHGCal/TICL/plugins/HGCGraph.cc
  RecoHGCal/TICL/plugins/HGCGraph.h
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.h
  RecoHGCal/TICL/plugins/PatternRecognitionbyMultiClusters.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyMultiClusters.h
  RecoHGCal/TICL/plugins/SeedingRegionByTracks.cc
  RecoHGCal/TICL/plugins/SeedingRegionByTracks.h
  RecoHGCal/TICL/plugins/SeedingRegionGlobal.cc
  RecoHGCal/TICL/plugins/SeedingRegionGlobal.h
  RecoHGCal/TICL/plugins/TICLSeedingRegionProducer.cc
  RecoHGCal/TICL/plugins/TrackstersProducer.cc
  RecoHGCal/TICL/python/ticl_iterations.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27672 Complete the implementation of RPC Digi Collection Merger started in PR #24613
  Configuration/Eras/python/Modifier_run3_RPC_cff.py
  Configuration/StandardSequences/python/Eras.py
  Configuration/StandardSequences/python/RawToDigi_Data_cff.py
  Configuration/StandardSequences/python/RawToDigi_cff.py
  EventFilter/RPCRawToDigi/plugins/RPCDigiMerger.cc
  EventFilter/RPCRawToDigi/plugins/RPCDigiMerger.h
  EventFilter/RPCRawToDigi/python/RPCRawToDigi_cfi.py
  RecoLocalMuon/Configuration/python/RecoLocalMuonCosmics_cff.py
  RecoLocalMuon/Configuration/python/RecoLocalMuon_cff.py
  RecoLocalMuon/RPCRecHit/python/rpcRecHits_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved

#27829 Run3-TB44 Update the usage of TB beam generator
  IOMC/ParticleGuns/interface/BeamMomentumGunProducer.h
  IOMC/ParticleGuns/src/BeamMomentumGunProducer.cc
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1el100_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#27830 Run3-alca158 Update the analysis macros for MIP monitoring of HE RadDam
  Calibration/HcalCalibAlgos/macros/AnalyzeLepTree.C
  Calibration/HcalCalibAlgos/macros/HBHEMuonOfflineAnalyzer.C
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27832 Update GEMPadDigi clustering procedure
  SimMuon/GEMDigitizer/plugins/GEMPadDigiClusterProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#27848 Remove DD Dependency
  RecoRomanPot/RecoFP420/BuildFile.xml
  TrackPropagation/Geant4e/test/BuildFile.xml
  TrackPropagation/Geant4e/test/Geant4ePropagatorAnalyzer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#27766 Exclude dark photon 3000022 tracking for CMSSW_10_2_X
  SimG4Core/Generators/src/Generator.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27794 Add TopLHEFilter
  GeneratorInterface/GenFilters/BuildFile.xml
  GeneratorInterface/GenFilters/python/LHEJetFilter_cfi.py
  GeneratorInterface/GenFilters/src/LHEJetFilter.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#27765 Exclude dark photon 3000022 tracking for CMSSW_9_3_X
  SimG4Core/Generators/src/Generator.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27849 python 3 fix for GlobalTag.py
  Configuration/AlCa/python/GlobalTag.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27774 Adding 2021 scripts to CondTools/Geometry
  CondTools/Geometry/test/writehelpers/createExtended2021Payloads.sh
  CondTools/Geometry/test/writehelpers/geometryExtended2021_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2021_xmlwriter.py
  CondTools/Geometry/test/writehelpers/splitExtended2021Database.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#27803 Run3-hcx217 Move remaining geometry parameters for SIM step to HcalSimulationParameters
  CondFormats/GeometryObjects/interface/HcalSimulationParameters.h
  Geometry/HcalCommonData/interface/HcalSimParametersFromDD.h
  Geometry/HcalCommonData/src/HcalSimParametersFromDD.cc
  Geometry/HcalCommonData/test/HcalParametersAnalyzer.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#27842 Fix gcc9 warnings in CondTools & CondFormats
  CondFormats/DTObjects/src/DTKeyedConfig.cc
  CondTools/HLT/src/AlCaRecoTriggerBitsRcdRead.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#27861 Allow std::vector<std::unique_ptr<T>> be produced, and be read with edm::View<T>
  DataFormats/Common/interface/GetProduct.h
  DataFormats/Common/interface/WrapperDetail.h
  DataFormats/Provenance/src/ProductResolverIndexHelper.cc
  DataFormats/StdDictionaries/src/classes_def_vector.xml
  DataFormats/StdDictionaries/src/classes_vector.h
  DataFormats/TestObjects/interface/ToyProducts.h
  DataFormats/TestObjects/src/classes_def.xml
  DataFormats/WrappedStdDictionaries/src/classes_def.xml
  FWCore/Framework/test/stubs/ToySTLProducers.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/ExistingDictionaryTestModules.cc
  FWCore/Integration/test/ViewAnalyzer.cc
  FWCore/Integration/test/ViewTest_cfg.py
  FWCore/Integration/test/run_TestExistingDictionary.sh
  FWCore/Integration/test/testExistingDictionaryCheckingRead_cfg.py
  FWCore/Integration/test/testExistingDictionaryChecking_cfg.py
  FWCore/Utilities/src/FriendlyName.cc
  FWCore/Utilities/test/friendlyname_t.cppunit.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved
