Repository cms-sw/cmssw, pull requests merged in 2019-02, with the labels that each got.

#25831 Removed struct dictionary from classes.h in TBDataFormats
  TBDataFormats/EcalTBObjects/src/classes.h
  TBDataFormats/HcalTBObjects/src/classes.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#25814 Remove unused variable from SiStripMonitorDigi
  DQM/SiStripMonitorDigi/src/SiStripMonitorDigi.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25822 Run2-alca150 Make year dependent EE thresholds for IsoTrack analysis
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibTree.C
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkAnalyzer.cc
  Calibration/HcalCalibAlgos/python/HcalIsoTrkAnalyzer_cff.py
  Calibration/HcalCalibAlgos/test/isoTrackAlCaRecoAnalysis_cfg.py
  Calibration/HcalCalibAlgos/test/isoTrackRecoAnalysis_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25779 Remove empty endJob() functions from AlcaBeamMonitorClient and BeamMonitorBx
  DQM/BeamMonitor/plugins/AlcaBeamMonitorClient.cc
  DQM/BeamMonitor/plugins/AlcaBeamMonitorClient.h
  DQM/BeamMonitor/plugins/BeamMonitorBx.cc
  DQM/BeamMonitor/plugins/BeamMonitorBx.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25832 Use unique_ptr constructor for PluginFactory plugins in AttachSD
  SimG4Core/SensitiveDetector/src/AttachSD.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25824 FastSim memory fix in TrajectorSeedProducer
  FastSimulation/Tracking/src/SeedFinderSelector.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#25819 Extend field parameters modification to e+ and p
  SimG4Core/Application/interface/ParametrisedEMPhysics.h
  SimG4Core/Application/src/ParametrisedEMPhysics.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25815 Remove redundant configuration settings for siPixelDigis
  EventFilter/SiPixelRawToDigi/python/SiPixelRawToDigi_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25802 Phase2-hgx178 Get rid of Magic numbers
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#25835 Removed unused EcalTPGScale which has same class name
  CalibFormats/CaloTPG/interface/EcalTPGScale.h
  CalibFormats/CaloTPG/src/ES_EcalTPGScale.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25793 Run2-alca149 Make year dependent thresholds for IsoTrackFilter
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksFilter.cc
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalIsoTrkFilter_cff.py
  Calibration/HcalAlCaRecoProducers/python/alcaIsoTracksFilter_cff.py
  Calibration/HcalAlCaRecoProducers/test/AlCaIsoTrackFilterProducer_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25770 Add a mechanism to adjust the pileup distribution in PreMixingModule
  DQM/SiStripMonitorHardware/src/SiStripSpyEventMatcher.cc
  FWCore/Sources/interface/VectorInputSource.h
  FWCore/Sources/src/VectorInputSource.cc
  IOPool/SecondaryInput/test/SecondaryProducer.cc
  IOPool/SecondaryInput/test/SecondaryProducer.h
  Mixing/Base/interface/PileUp.h
  SimGeneral/DataMixingModule/plugins/DataMixingModule.cc
  SimGeneral/DataMixingModule/plugins/DataMixingModule.h
  SimGeneral/MixingModule/plugins/MixingModule.cc
  SimGeneral/MixingModule/plugins/MixingModule.h
  SimGeneral/MixingModule/plugins/SecSourceAnalyzer.cc
  SimGeneral/MixingModule/plugins/SecSourceAnalyzer.h
  SimGeneral/PileupInformation/plugins/PileupInformation.cc
  SimGeneral/PreMixingModule/plugins/BuildFile.xml
  SimGeneral/PreMixingModule/plugins/PreMixingModule.cc
  SimGeneral/PreMixingModule/plugins/PreMixingPileupCopy.cc
  SimGeneral/PreMixingModule/plugins/PreMixingPileupCopy.h
  SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py
  SimGeneral/PreMixingModule/test/BuildFile.xml
  SimGeneral/PreMixingModule/test/TestPreMixingPileupAnalyzer.cc
  SimGeneral/PreMixingModule/test/fakeminbias_cfg.py
  SimGeneral/PreMixingModule/test/run_testPremixPileupAdjustment.sh
  SimGeneral/PreMixingModule/test/runtestSimGeneralPreMixingModule.cpp
  SimGeneral/PreMixingModule/test/testFakeMinBias_cfg.py
  SimGeneral/PreMixingModule/test/testPremixStage1_cfg.py
  SimGeneral/PreMixingModule/test/testPremixStage2_cfg.py
Labels: code-checks-approved, comparison-available, core-approved, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#25837 Manage PluginFactory plugins with unique_ptr in CalibMuon/DTCalibration
  CalibMuon/DTCalibration/interface/DTTMax.h
  CalibMuon/DTCalibration/plugins/DTT0Correction.cc
  CalibMuon/DTCalibration/plugins/DTT0Correction.h
  CalibMuon/DTCalibration/plugins/DTTPAnalyzer.cc
  CalibMuon/DTCalibration/plugins/DTTTrigCalibration.cc
  CalibMuon/DTCalibration/plugins/DTTTrigCalibration.h
  CalibMuon/DTCalibration/plugins/DTTTrigCorrection.cc
  CalibMuon/DTCalibration/plugins/DTTTrigCorrection.h
  CalibMuon/DTCalibration/plugins/DTVDriftCalibration.cc
  CalibMuon/DTCalibration/plugins/DTVDriftCalibration.h
  CalibMuon/DTCalibration/plugins/DTVDriftWriter.cc
  CalibMuon/DTCalibration/plugins/DTVDriftWriter.h
  CalibMuon/DTCalibration/src/DTTMax.cc
  CalibMuon/DTDigiSync/interface/DTTTrigBaseSync.h
  CalibMuon/DTDigiSync/src/DTTTrigBaseSync.cc
  CalibMuon/DTDigiSync/src/DTTTrigSyncFromDB.cc
  CalibMuon/DTDigiSync/src/DTTTrigSyncFromDB.h
  CalibMuon/DTDigiSync/src/DTTTrigSyncT0Only.cc
  CalibMuon/DTDigiSync/src/DTTTrigSyncT0Only.h
  CalibMuon/DTDigiSync/src/DTTTrigSyncTOFCorr.cc
  CalibMuon/DTDigiSync/src/DTTTrigSyncTOFCorr.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25827 Manage PluginFactory plugin with unique_ptr in HLTMuonIsoFilter
  HLTrigger/Muon/plugins/HLTMuonIsoFilter.cc
  HLTrigger/Muon/plugins/HLTMuonIsoFilter.h
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#25847 Removed unused function from writeInt.cc
  CondCore/DBOutputService/test/stubs/writeInt.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25479 Add filter for Charm quarks to produce C-enriched samples
  GeneratorInterface/Core/interface/PartonShowerCsHepMCFilter.h
  GeneratorInterface/Core/src/HepMCFilterDriver.cc
  GeneratorInterface/Core/src/PartonShowerCsHepMCFilter.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25846 Modernized CastorDumpConditions
  CondTools/Hcal/plugins/CastorDumpConditions.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25844 Removed unused functions in HcalQIECoder
  CondFormats/HcalObjects/src/HcalQIECoder.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25843 Changed forward declaration to struct in DBSpecToDetUnit
  CondFormats/RPCObjects/interface/DBSpecToDetUnit.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25777 CondDB formats for PPS/Totem timing calibrations
  CondCore/CTPPSPlugins/src/plugin.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
  CondFormats/CTPPSReadoutObjects/interface/PPSTimingCalibration.h
  CondFormats/CTPPSReadoutObjects/plugins/PPSTimingCalibrationESSource.cc
  CondFormats/CTPPSReadoutObjects/src/PPSTimingCalibration.cc
  CondFormats/CTPPSReadoutObjects/src/T_EventSetup_PPSTimingCalibration.cc
  CondFormats/CTPPSReadoutObjects/src/classes.h
  CondFormats/CTPPSReadoutObjects/src/classes_def.xml
  CondFormats/CTPPSReadoutObjects/src/headers.h
  CondFormats/CTPPSReadoutObjects/test/BuildFile.xml
  CondFormats/CTPPSReadoutObjects/test/testSerializationPPSTimingCalibration.cc
  CondFormats/DataRecord/interface/PPSTimingCalibrationRcd.h
  CondFormats/DataRecord/src/PPSTimingCalibrationRcd.cc
  CondTools/CTPPS/plugins/PPSTimingCalibrationAnalyzer.cc
  CondTools/CTPPS/plugins/PPSTimingCalibrationWriter.cc
  CondTools/CTPPS/test/ppsTimingCalibrationAnalyzer_cfg.py
  CondTools/CTPPS/test/ppsTimingCalibrationWriter_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25577 Remove nearly all calls to Modifier.isChosen() from L1T configurations
  Configuration/StandardSequences/python/DigiToRawDM_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorDM_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_CalouGT_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full2015Data_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_FullMC_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_FullSimTP_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py
  HLTrigger/Configuration/python/CustomConfigs.py
  L1Trigger/Configuration/python/L1TDigiToRaw_cff.py
  L1Trigger/Configuration/python/L1TRawToDigi_cff.py
  L1Trigger/Configuration/python/SimL1TechnicalTriggers_cff.py
  L1Trigger/Configuration/python/customiseReEmul.py
  L1Trigger/L1TCalorimeter/python/hackConditions_cff.py
  L1Trigger/L1TCalorimeter/python/simDigis_cff.py
  L1Trigger/L1TCommon/test/reEmul.py
  L1Trigger/L1TGlobal/python/hackConditions_cff.py
  L1Trigger/L1TGlobal/python/simDigis_cff.py
  L1Trigger/L1TMuon/python/hackConditions_cff.py
  L1Trigger/L1TMuon/python/simDigis_cff.py
  L1Trigger/L1TNtuples/python/L1NtupleEMU_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, l1-approved, operations-approved, orp-approved, tests-approved

#25841 Use unique_ptr constructor for PluginFactory plugins in RecoLocalCalo/HGCalRecProducers
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitProducer.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalUncalibRecHitProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#25816 Manage PluginFactory plugin with a unique_ptr in CondDBESSource
  CondCore/ESSources/plugins/CondDBESSource.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25852 reconstruction - removing '//' from header include.
  RecoEgamma/EgammaElectronAlgos/interface/ElectronSeedGenerator.h
  RecoEgamma/EgammaTools/src/HGCalIsoCalculator.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerRatio.h
  RecoParticleFlow/PFClusterProducer/plugins/PFCTRecHitProducer.h
  RecoTracker/SiTrackerMRHTools/interface/SimpleDAFHitCollector.h
  RecoTracker/TransientTrackingRecHit/plugins/TkTransientTrackingRecHitBuilderESProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25851 Generate events without MPI if LBCR or CRSS performed with MPI.
  GeneratorInterface/SherpaInterface/data/MakeSherpaLibs.sh
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25839 Removed RPCRunIOV which conflicts with another class with same name
  CondTools/RPC/interface/RPCRunIOV.h
  CondTools/RPC/src/RPCRunIOV.cc
  CondTools/RPC/test/RiovTest.cc
  CondTools/RPC/test/riovtest_cfg.py
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25840 Manage PluginFactory plugin with unique_ptr in DTLocalTriggerSynchTask
  DQM/DTMonitorModule/src/DTLocalTriggerSynchTask.cc
  DQM/DTMonitorModule/src/DTLocalTriggerSynchTask.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25823 No more possibility to ignore exceptions in TagAndProbe
  PhysicsTools/TagAndProbe/interface/BaseTreeFiller.h
  PhysicsTools/TagAndProbe/src/BaseTreeFiller.cc
  PhysicsTools/TagAndProbe/test/Electron_TagProbeTreeProducer_cfg.py
  PhysicsTools/TagAndProbe/test/Photon_TagProbeTreeProducer_cfg.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25595 Conversions from low pt ele tracks released in PR 25455
  Configuration/StandardSequences/python/Reconstruction_cff.py
  DataFormats/EgammaCandidates/interface/Conversion.h
  DataFormats/EgammaTrackReco/interface/ConversionTrack.h
  DataFormats/EgammaTrackReco/src/classes_def.xml
  RecoEgamma/Configuration/python/RecoEgamma_EventContent_cff.py
  RecoEgamma/EgammaPhotonProducers/interface/ConversionTrackProducer.h
  RecoEgamma/EgammaPhotonProducers/python/conversionOpenTrackSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/conversionTrackProducer_cfi.py
  RecoEgamma/EgammaPhotonProducers/python/gsfTracksOpenConversionSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/src/ConversionProducer.cc
  RecoEgamma/EgammaPhotonProducers/src/ConversionTrackProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved

#25811 Some modernization for SiPixelClusterProducer
  CalibTracker/SiPixelESProducers/interface/SiPixelGainCalibrationServiceBase.h
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.h
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelClusterProducer.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelClusterProducer.h
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#25748 Pixel simulated bad channel info packed into FED raw data
  EventFilter/SiPixelRawToDigi/interface/PixelDataFormatter.h
  EventFilter/SiPixelRawToDigi/plugins/SiPixelDigiToRaw.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.h
  EventFilter/SiPixelRawToDigi/python/SiPixelRawToDigi_cfi.py
  EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25784 Phase2-sim26 Add one simproducer class which can save hits of calorimeters
  Configuration/Geometry/python/GeometryExtended2018NoSD_cff.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2018NoSDXML_cfi.py
  SimG4CMS/Calo/interface/CaloGVHit.h
  SimG4CMS/Calo/interface/CaloSteppingAction.h
  SimG4CMS/Calo/plugins/module.cc
  SimG4CMS/Calo/src/CaloGVHit.cc
  SimG4CMS/Calo/src/CaloSteppingAction.cc
  SimG4CMS/Calo/test/python/calostep_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25854 alca - removing '//' from header include.
  CondFormats/DataRecord/src/DTRecoUncertaintiesRcd.cc
  CondFormats/DataRecord/src/DropBoxMetadataRcd.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25853 simulation - removing '//' from header include.
  SimG4CMS/FP420/plugins/FP420Test.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25821 Geo2018 with Detailed Cavern and MB4Shiedls for CMSSw_10_3
  CondTools/Geometry/test/writehelpers/createExtended2018Payloads.sh
  CondTools/Geometry/test/writehelpers/splitExtended2018Database.sh
  Configuration/Geometry/python/GeometryExtended2018DetailedCavern_cff.py
Labels: backport-ok, comparison-available, db-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#25861 MakeSherpaLibs backport to 10_2_X
  GeneratorInterface/SherpaInterface/data/MakeSherpaLibs.sh
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25862 MakeSherpaLibs backport to 9_3_X
  GeneratorInterface/SherpaInterface/data/MakeSherpaLibs.sh
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25863 MakeSherpaLibs backport to 7_1_X
  GeneratorInterface/SherpaInterface/data/MakeSherpaLibs.sh
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25845 Pass intergral value to SetLineWidth in CondCore/EcalPlugins
  CondCore/EcalPlugins/plugins/EcalPulseCovariances_PayloadInspector.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25828 Modernize dictionary generation in FastSimDataFormats
  FastSimDataFormats/CTPPSFastSim/src/classes.h
  FastSimDataFormats/External/src/classes.h
  FastSimDataFormats/NuclearInteractions/src/classes.h
  FastSimDataFormats/PileUpEvents/src/classes.h
Labels: code-checks-approved, comparison-available, fastsim-approved, new-package-pending, orp-approved, pending-signatures, tests-approved

#25855 analysis - removing '//' from header include.
  PhysicsTools/TagAndProbe/interface/TriggerCandProducer.h
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25838 Remove EventSetup from PixelFitterBase-derived classes
  FastSimulation/Tracking/plugins/PixelTracksProducer.cc
  RecoPixelVertexing/PixelLowPtUtilities/interface/TrackFitter.h
  RecoPixelVertexing/PixelLowPtUtilities/plugins/TrackFitterProducer.cc
  RecoPixelVertexing/PixelLowPtUtilities/src/TrackFitter.cc
  RecoPixelVertexing/PixelTrackFitting/interface/KFBasedPixelFitter.h
  RecoPixelVertexing/PixelTrackFitting/interface/PixelFitter.h
  RecoPixelVertexing/PixelTrackFitting/interface/PixelFitterBase.h
  RecoPixelVertexing/PixelTrackFitting/interface/PixelFitterByConformalMappingAndLine.h
  RecoPixelVertexing/PixelTrackFitting/interface/PixelFitterByHelixProjections.h
  RecoPixelVertexing/PixelTrackFitting/plugins/KFBasedPixelFitterProducer.cc
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelFitterByConformalMappingAndLineProducer.cc
  RecoPixelVertexing/PixelTrackFitting/src/KFBasedPixelFitter.cc
  RecoPixelVertexing/PixelTrackFitting/src/PixelFitterByConformalMappingAndLine.cc
  RecoPixelVertexing/PixelTrackFitting/src/PixelFitterByHelixProjections.cc
  RecoPixelVertexing/PixelTrackFitting/src/PixelTrackReconstruction.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25817 ParticleLevelProducer: fix warnings
  GeneratorInterface/RivetInterface/interface/RivetAnalysis.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#25829 Modernize dictionary generation in SimDataFormats
  SimDataFormats/CaloHit/src/classes.h
  SimDataFormats/CaloTest/src/classes.h
  SimDataFormats/CrossingFrame/src/classes.h
  SimDataFormats/DigiSimLinks/src/classes.h
  SimDataFormats/EcalTestBeam/src/classes.h
  SimDataFormats/EncodedEventId/src/classes.h
  SimDataFormats/Forward/src/classes.h
  SimDataFormats/GEMDigiSimLink/src/classes.h
  SimDataFormats/GeneratorProducts/src/classes.h
  SimDataFormats/HTXS/src/classes.h
  SimDataFormats/HcalTestBeam/src/classes.h
  SimDataFormats/HiGenData/src/classes.h
  SimDataFormats/JetMatching/src/classes.h
  SimDataFormats/PileupSummaryInfo/src/classes.h
  SimDataFormats/RPCDigiSimLink/src/classes.h
  SimDataFormats/RandomEngine/src/classes.h
  SimDataFormats/RandomEngine/src/classes_def.xml
  SimDataFormats/Track/src/classes.h
  SimDataFormats/TrackerDigiSimLink/src/classes.h
  SimDataFormats/TrackingAnalysis/src/classes.h
  SimDataFormats/TrackingHit/src/classes.h
  SimDataFormats/ValidationFormats/src/classes.h
  SimDataFormats/Vertex/src/classes.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25825 Manage PluginFactory plugin with unique_ptr in ExternalDecayDriver
  GeneratorInterface/ExternalDecays/interface/ExternalDecayDriver.h
  GeneratorInterface/ExternalDecays/src/ExternalDecayDriver.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25850 fixing missing pointer between lumi boundaries
  GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25805 Fix clang warnings in EventFilter/SiPixelRawToDigi
  EventFilter/SiPixelRawToDigi/src/ErrorChecker.cc
  EventFilter/SiPixelRawToDigi/src/PixelUnpackingRegions.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25878 Added new and cleaned up existing Geant4 Physics Lists
  SimG4Core/Application/src/RunManager.cc
  SimG4Core/Application/src/RunManagerMT.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMN.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMN.h
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EMN.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EMN.h
  SimG4Core/PhysicsLists/plugins/module.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsLPM.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsXS.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25877 Impoved edm::ESGetToken
  FWCore/Framework/interface/EDConsumerBase.h
  FWCore/Framework/interface/ESConsumesCollector.h
  FWCore/Framework/interface/ESHandle.h
  FWCore/Framework/interface/ESProducer.h
  FWCore/Framework/interface/ESValidHandle.h
  FWCore/Framework/interface/EventSetup.h
  FWCore/Framework/interface/EventSetupRecord.h
  FWCore/Framework/interface/EventSetupRecordImplementation.h
  FWCore/Framework/src/ESValidHandle.cc
  FWCore/Framework/test/eventsetup_t.cppunit.cc
  FWCore/Framework/test/eventsetuprecord_t.cppunit.cc
  FWCore/Framework/test/stubs/TestESDummyDataAnalyzer.cc
  FWCore/Integration/test/WhatsItESProducer.cc
  FWCore/Utilities/interface/ESGetToken.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25800 Fixed possible buffer overflow in CSCTriggerPrimitivesReader
  L1Trigger/CSCTriggerPrimitives/test/CSCTriggerPrimitivesReader.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#25809 Fix clang warnings in L1TriggerConfig/L1GtConfigProducers
  L1TriggerConfig/L1GtConfigProducers/src/L1GtTriggerMenuXmlParser.cc
  L1TriggerConfig/L1GtConfigProducers/src/L1GtVhdlWriterCore.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#25872 updating relvals strings
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#25886 Use unique_ptr in HiEgammaSCCorrectionMaker
  RecoHI/HiEgammaAlgos/plugins/HiEgammaSCCorrectionMaker.cc
  RecoHI/HiEgammaAlgos/plugins/HiEgammaSCCorrectionMaker.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25882 Moved "FWHeatmapProxyBuilderTemplate" to Fireworks/Calo package
  Fireworks/Calo/interface/FWHeatmapProxyBuilderTemplate.h
  Fireworks/Calo/plugins/FWCaloClusterProxyBuilder.cc
  Fireworks/Calo/plugins/FWHGCalMultiClusterProxyBuilder.cc
  Fireworks/SimData/plugins/FWCaloParticleProxyBuilder.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#25871 Backport PS weight settings fragment
  Configuration/Generator/python/PSweightsPythia/PythiaPSweightsSettings_cfi.py
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25836 GEM - new gem emapping format for vfat v3
  CondCore/GEMPlugins/src/BuildFile.xml
  CondCore/GEMPlugins/src/plugins.cc
  CondFormats/DataRecord/interface/GEMeMapRcd.h
  CondFormats/DataRecord/src/GEMeMapRcd.cc
  CondFormats/GEMObjects/interface/GEMROMapping.h
  CondFormats/GEMObjects/interface/GEMeMap.h
  CondFormats/GEMObjects/src/GEMeMap.cc
  CondFormats/GEMObjects/src/T_EventSetup_GEMeMap.cc
  CondFormats/GEMObjects/src/classes_def.xml
  CondFormats/GEMObjects/src/headers.h
  CondFormats/GEMObjects/test/test_serialization.cpp
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25857 Continue migration of Geometry code to user-defined literals
  Geometry/CSCGeometry/src/CSCLayerGeometry.cc
  Geometry/CSCGeometry/src/CSCWireTopology.cc
  Geometry/CaloEventSetup/test/CaloGeometryAnalyzer.cc
  Geometry/CaloTopology/src/HcalTopology.cc
  Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromCondDB.cc
  Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromCondDB.h
  Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromDDD.cc
  Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromDDD.h
  Geometry/DTGeometryBuilder/src/DTGeometryParsFromDD.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#25896 Use fixed order vector instead of map in EventSetup
  FWCore/Framework/interface/EventSetup.h
  FWCore/Framework/interface/EventSetupImpl.h
  FWCore/Framework/interface/EventSetupKnownRecordsSupplier.h
  FWCore/Framework/interface/EventSetupProvider.h
  FWCore/Framework/interface/EventSetupRecordKey.h
  FWCore/Framework/src/EventSetup.cc
  FWCore/Framework/src/EventSetupImpl.cc
  FWCore/Framework/src/EventSetupProvider.cc
  FWCore/Framework/test/eventsetup_t.cppunit.cc
  FWCore/Framework/test/eventsetuprecord_t.cppunit.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25753 Complete low pT electron chain (2)
  PhysicsTools/PatAlgos/python/producersLayer1/lowPtElectronProducer_cff.py
  PhysicsTools/PatAlgos/python/producersLayer1/patCandidates_cff.py
  PhysicsTools/PatAlgos/python/selectionLayer1/lowPtElectronSelector_cfi.py
  PhysicsTools/PatAlgos/python/selectionLayer1/selectedPatCandidates_cff.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/slimmedLowPtElectrons_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  PhysicsTools/PatAlgos/python/tools/coreTools.py
  PhysicsTools/PatAlgos/test/IntegrationTest_cfg.py
  PhysicsTools/PatAlgos/test/patTuple_addTriggerInfo_cfg.py
  RecoEgamma/Configuration/python/RecoEgamma_EventContent_cff.py
  RecoEgamma/EgammaElectronProducers/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/interface/LowPtGsfElectronIDHeavyObjectCache.h
  RecoEgamma/EgammaElectronProducers/interface/LowPtGsfElectronSeedHeavyObjectCache.h
  RecoEgamma/EgammaElectronProducers/plugins/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronBaseProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronCoreProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronCoreProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronIDProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronIDProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSCProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSCProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedValueMapsProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedValueMapsProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/SealModule.cc
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronCores_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronID_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSeedValueMaps_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSequence_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSuperClusters_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectrons_cfi.py
  RecoEgamma/EgammaElectronProducers/src/LowPtGsfElectronIDHeavyObjectCache.cc
  RecoEgamma/EgammaElectronProducers/src/LowPtGsfElectronSeedHeavyObjectCache.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved

#25864 FastSim memory fix in TrajectorySeedProducer -- backport to 102X
  FastSimulation/Tracking/src/SeedFinderSelector.cc
Labels: backport-ok, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#25881 fixing missing pointer between lumi boundaries in 102x
  GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25873 Ecal : to dump the tags based on EcalSimPulseShapeRcd
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondFormats.h
  CondTools/Ecal/interface/XMLTags.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#25894 Added extra protection to Geant4 SteppingAction
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/src/SteppingAction.cc
  SimG4Core/Notification/interface/CMSSteppingVerbose.h
  SimG4Core/Notification/src/CMSSteppingVerbose.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25897 DD4Hep: DT Geometry Builder with Correct Numbering
  DetectorDescription/DDCMS/interface/BenchmarkGrd.h
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/interface/DDSpecParRegistry.h
  DetectorDescription/DDCMS/interface/MuonNumbering.h
  DetectorDescription/DDCMS/plugins/DDTestSpecParsFilter.cc
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  DetectorDescription/DDCMS/src/DDSpecparRegistry.cc
  DetectorDescription/DDCMS/src/MuonNumbering.cc
  DetectorDescription/RecoGeometry/interface/DTGeometryBuilder.h
  DetectorDescription/RecoGeometry/plugins/DTGeometryESProducer.cc
  DetectorDescription/RecoGeometry/plugins/DTGeometryTest.cc
  DetectorDescription/RecoGeometry/src/DTGeometryBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#25866 Use unique_ptr constructor for PluginFactory plugin in RecoLocalFastTime/FTLRecProducers
  RecoLocalFastTime/FTLRecProducers/plugins/FTLRecHitProducer.cc
  RecoLocalFastTime/FTLRecProducers/plugins/FTLUncalibratedRecHitProducer.cc
  RecoLocalFastTime/FTLRecProducers/plugins/MTDRecHitProducer.cc
  RecoLocalFastTime/FTLRecProducers/plugins/MTDUncalibratedRecHitProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#25867 Use unique_ptr constructor for PluginFactory plugins in L1Trigger/L1THGCal
  L1Trigger/L1THGCal/plugins/HGCalBackendLayer1Producer.cc
  L1Trigger/L1THGCal/plugins/HGCalBackendLayer2Producer.cc
  L1Trigger/L1THGCal/plugins/HGCalConcentratorProducer.cc
  L1Trigger/L1THGCal/plugins/HGCalTowerMapProducer.cc
  L1Trigger/L1THGCal/plugins/HGCalTowerProducer.cc
  L1Trigger/L1THGCal/plugins/HGCalTriggerDigiFEReproducer.cc
  L1Trigger/L1THGCal/plugins/HGCalVFEProducer.cc
  L1Trigger/L1THGCal/plugins/ntuples/HGCalTriggerNtupleHGCMulticlusters.cc
  L1Trigger/L1THGCal/src/HGCalTriggerBackendProcessor.cc
  L1Trigger/L1THGCal/src/backend/HGCalMulticlusteringHistoImpl.cc
  L1Trigger/L1THGCal/src/backend/HGCalMulticlusteringImpl.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#25899 Manage PluginFactory plugins with unique_ptr in RecoLocalMuon
  RecoLocalMuon/CSCSegment/src/CSCSegmentBuilder.cc
  RecoLocalMuon/CSCSegment/src/CSCSegmentBuilder.h
  RecoLocalMuon/DTRecHit/interface/DTRecHitBaseAlgo.h
  RecoLocalMuon/DTRecHit/plugins/DTRecHitProducer.cc
  RecoLocalMuon/DTRecHit/plugins/DTRecHitProducer.h
  RecoLocalMuon/DTRecHit/src/DTRecHitBaseAlgo.cc
  RecoLocalMuon/DTSegment/src/DTRecSegment2DProducer.cc
  RecoLocalMuon/DTSegment/src/DTRecSegment2DProducer.h
  RecoLocalMuon/DTSegment/src/DTRecSegment4DProducer.cc
  RecoLocalMuon/DTSegment/src/DTRecSegment4DProducer.h
  RecoLocalMuon/DTSegment/src/DTSegmentUpdator.cc
  RecoLocalMuon/DTSegment/src/DTSegmentUpdator.h
  RecoLocalMuon/DTSegment/test/DTAnalyzerDetailed.cc
  RecoLocalMuon/DTSegment/test/DTAnalyzerDetailed.h
  RecoLocalMuon/DTSegment/test/DTSegAnalyzer.cc
  RecoLocalMuon/DTSegment/test/DTSegAnalyzer.h
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentBuilder.cc
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentBuilder.h
  RecoLocalMuon/GEMRecHit/src/GEMRecHitProducer.cc
  RecoLocalMuon/GEMRecHit/src/GEMRecHitProducer.h
  RecoLocalMuon/GEMRecHit/src/ME0RecHitProducer.cc
  RecoLocalMuon/GEMRecHit/src/ME0RecHitProducer.h
  RecoLocalMuon/RPCRecHit/src/RPCRecHitProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#25762 CMSSW Config Tracing Tool
  DQMOffline/Configuration/scripts/cmsswConfigtrace.py
  DQMOffline/Configuration/scripts/cmsswFiletrace.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25906 Exclude additional ROOT math libraries in DataFormats/Math
  DataFormats/Math/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25484 Herwig7Interface backport 9_3_X
  GeneratorInterface/Herwig6Interface/interface/Herwig6Instance.h
  GeneratorInterface/Herwig6Interface/plugins/Herwig6Hadronizer.cc
  GeneratorInterface/Herwig6Interface/src/Herwig6Instance.cc
  GeneratorInterface/Herwig6Interface/src/fastjetfortran_madfks.cc
  GeneratorInterface/Herwig7Interface/BuildFile.xml
  GeneratorInterface/Herwig7Interface/doc/Readme.txt
  GeneratorInterface/Herwig7Interface/doc/TODOs.md
  GeneratorInterface/Herwig7Interface/interface/Herwig7Interface.h
  GeneratorInterface/Herwig7Interface/interface/HerwigUIProvider.h
  GeneratorInterface/Herwig7Interface/interface/Proxy.h
  GeneratorInterface/Herwig7Interface/interface/RandomEngineGlue.h
  GeneratorInterface/Herwig7Interface/plugins/BuildFile.xml
  GeneratorInterface/Herwig7Interface/plugins/Herwig7Hadronizer.cc
  GeneratorInterface/Herwig7Interface/python/Herwig7_Dummy_ConfigFile_cff.py
  GeneratorInterface/Herwig7Interface/python/Herwig7_Dummy_Matchbox_90X_ppToee.py
  GeneratorInterface/Herwig7Interface/python/Herwig7_Dummy_ReadLHE_GEN_SIM.py
  GeneratorInterface/Herwig7Interface/scripts/README.md
  GeneratorInterface/Herwig7Interface/scripts/parallelization.py
  GeneratorInterface/Herwig7Interface/src/Herwig7Interface.cc
  GeneratorInterface/Herwig7Interface/src/HerwigUIProvider.cc
  GeneratorInterface/Herwig7Interface/src/Proxy.cc
  GeneratorInterface/Herwig7Interface/src/RandomEngineGlue.cc
  GeneratorInterface/Herwig7Interface/test/Herwig7Test_ConfigFile_GEN_SIM.py
  GeneratorInterface/Herwig7Interface/test/Herwig7_Matchbox_90X_ppToee_GEN_SIM.py
  GeneratorInterface/Herwig7Interface/test/LEP.in
  GeneratorInterface/Herwig7Interface/test/LHC-Matchbox.in
  GeneratorInterface/Herwig7Interface/test/LHC-Powheg.in
  GeneratorInterface/Herwig7Interface/test/LHE.in
  GeneratorInterface/Herwig7Interface/test/TestConfig.in
  GeneratorInterface/ThePEGInterface/interface/HepMCTemplate.h
  GeneratorInterface/ThePEGInterface/interface/ThePEGInterface.h
  GeneratorInterface/ThePEGInterface/plugins/BuildFile.xml
  GeneratorInterface/ThePEGInterface/plugins/ThePEGHadronizer.cc
  GeneratorInterface/ThePEGInterface/plugins/ThePEGLesHouchesInterface.cc
  GeneratorInterface/ThePEGInterface/python/herwigValidation_cff.py
  GeneratorInterface/ThePEGInterface/src/ThePEGInterface.cc
  GeneratorInterface/ThePEGInterface/test/Readme.txt
  GeneratorInterface/ThePEGInterface/test/custom.py
  GeneratorInterface/ThePEGInterface/test/print_cfg.py
  GeneratorInterface/ThePEGInterface/test/runCmsDriver.sh
  GeneratorInterface/ThePEGInterface/test/testThePEGGeneratorFilter.py
  GeneratorInterface/ThePEGInterface/test/testThePEGGeneratorFilter_GEN_MC.py
  GeneratorInterface/ThePEGInterface/test/testThePEGHadronizerFilter.py
  GeneratorInterface/ThePEGInterface/test/ttbar.lhe
  GeneratorInterface/ThePEGInterface/test/w01j_5f_NLO.lhe
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#25904 Backport c filter in 93X
  GeneratorInterface/Core/interface/PartonShowerCsHepMCFilter.h
  GeneratorInterface/Core/src/HepMCFilterDriver.cc
  GeneratorInterface/Core/src/PartonShowerCsHepMCFilter.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25860 Store PS weights when calling hadronize()
  Configuration/Generator/python/PSweightsPythia/PythiaPSweightsSettings_cfi.py
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25895 Backport CsHepFilter
  GeneratorInterface/Core/interface/PartonShowerCsHepMCFilter.h
  GeneratorInterface/Core/src/HepMCFilterDriver.cc
  GeneratorInterface/Core/src/PartonShowerCsHepMCFilter.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25865 FastSim memory fix in TrajectorySeedProducer in 94X
  FastSimulation/Tracking/src/SeedFinderSelector.cc
Labels: backport-ok, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#25880 Phase2-sim27 Try to remove dependency of CLHEP in a few places and streamline the SteppingAction code for transporting to GeantV application
  FastSimulation/ShowerDevelopment/src/FastHFShowerLibrary.cc
  Geometry/HcalCommonData/interface/HcalNumberingFromDDD.h
  Geometry/HcalCommonData/src/HcalNumberingFromDDD.cc
  SimG4CMS/Calo/interface/CaloGVHit.h
  SimG4CMS/Calo/interface/CaloSteppingAction.h
  SimG4CMS/Calo/src/CaloGVHit.cc
  SimG4CMS/Calo/src/CaloSteppingAction.cc
  SimG4CMS/Calo/src/HCalSD.cc
  SimG4CMS/Calo/src/HcalNumberingScheme.cc
  Validation/HGCalValidation/plugins/SimG4HGCalValidation.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fastsim-approved, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#25900 Manage PluginFactory plugins with unique_ptr in SimMuon
  SimMuon/DTDigitizer/src/DTDigitizer.cc
  SimMuon/GEMDigitizer/interface/GEMDigiProducer.h
  SimMuon/GEMDigitizer/interface/ME0DigiPreRecoProducer.h
  SimMuon/GEMDigitizer/interface/ME0DigiProducer.h
  SimMuon/GEMDigitizer/src/GEMDigiProducer.cc
  SimMuon/GEMDigitizer/src/ME0DigiPreRecoProducer.cc
  SimMuon/GEMDigitizer/src/ME0DigiProducer.cc
  SimMuon/RPCDigitizer/src/IRPCDigitizer.cc
  SimMuon/RPCDigitizer/src/IRPCDigitizer.h
  SimMuon/RPCDigitizer/src/RPCDigitizer.cc
  SimMuon/RPCDigitizer/src/RPCDigitizer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25911 Small fixes to analyzers used for phase2 tracker studies
  SLHCUpgradeSimulations/Geometry/test/BuildFile.xml
  SLHCUpgradeSimulations/Geometry/test/Phase2PixelNtuple.cc
  SLHCUpgradeSimulations/Geometry/test/README.Phase2PixelNtuple.md
  SLHCUpgradeSimulations/Geometry/test/phase2_digi_reco_pixelntuple_cfg.py
  Validation/RecoVertex/src/MCVerticesAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#25918 Use emplace_back() directly for PluginFactory plugins in SimFastTiming and SimTracker
  SimFastTiming/FastTimingCommon/plugins/FTLDigiProducer.cc
  SimFastTiming/FastTimingCommon/plugins/MTDDigiProducer.cc
  SimTracker/TrackAssociation/plugins/TrackTimeValueMapProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#25926 Minor fix of p/pbar NIEL sampling
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsXS.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25920 python3 migration get __builtin__ from six
  FWCore/ParameterSet/python/Types.py
  HLTrigger/Configuration/test/add/tracingImport.py
  PhysicsTools/PythonAnalysis/python/cmscompleter.py
Labels: analysis-approved, code-checks-approved, comparison-available, core-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#25915 Low pT electrons: modify value maps storing Seed BDT outputs
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedValueMapsProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedValueMapsProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25602 adapt Pythia8Interface to pythia8 240
  GeneratorInterface/Pythia8Interface/interface/MultiUserHook.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#25902 Run2-sim28 Correct a cfi file to make a successful run of the overlap code
  SimG4Core/PrintGeomInfo/python/cmsMuon2017XML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#21717 LWTNN Deep Neural Networks for track classification
  RecoTracker/FinalTrackSelectors/BuildFile.xml
  RecoTracker/FinalTrackSelectors/interface/TrackMVAClassifier.h
  RecoTracker/FinalTrackSelectors/plugins/BuildFile.xml
  RecoTracker/FinalTrackSelectors/plugins/LwtnnESProducer.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackLwtnnClassifier.cc
  RecoTracker/FinalTrackSelectors/python/trackSelectionLwtnn_cfi.py
  RecoTracker/FinalTrackSelectors/src/ES_Lwtnn.cc
  RecoTracker/FinalTrackSelectors/src/TrackMVAClassifierBase.cc
  RecoTracker/IterativeTracking/python/DetachedQuadStep_cff.py
  RecoTracker/IterativeTracking/python/DetachedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/HighPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/InitialStep_cff.py
  RecoTracker/IterativeTracking/python/JetCoreRegionalStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtQuadStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/MixedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoTracker/IterativeTracking/python/TobTecStep_cff.py
  RecoTracker/IterativeTracking/python/customise_MVAPhase1_cfi.py
  RecoTracker/IterativeTracking/python/iterativeTkUtils.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#25938 Fixed include guard in DaqScopeModeHistosUsingDb.h
  DQM/SiStripCommissioningDbClients/interface/DaqScopeModeHistosUsingDb.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25940 Removed unused RPCBxTest
  DQM/RPCMonitorClient/interface/RPCBxTest.h
  DQM/RPCMonitorClient/src/RPCBxTest.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25939 Removed unnecessary iterator declarations from RPCMonitorDigi
  DQM/RPCMonitorDigi/src/RPCMonitorDigi.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25937 Corrected forward declaration in SiStripSpyEventMatcher
  DQM/SiStripMonitorHardware/interface/SiStripSpyEventMatcher.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25941 Added missing override in L1TEMTFEventInfoClient
  DQM/L1TMonitorClient/interface/L1TEMTFEventInfoClient.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25942 Use unique_ptr constructor for PluginFactory plugins in RecoParticleFlow
  RecoParticleFlow/PFClusterProducer/interface/PFClusterBuilderBase.h
  RecoParticleFlow/PFClusterProducer/plugins/Basic2DGenericPFlowClusterizer.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFCTRecHitProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFCTRecHitProducer.h
  RecoParticleFlow/PFClusterProducer/plugins/PFClusterProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFMultiDepthClusterProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFMultiDepthClusterizer.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFRecHitProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFlow2DClusterizerWithTime.cc
  RecoParticleFlow/PFProducer/src/PFBlockAlgo.cc
  RecoParticleFlow/PFSimProducer/plugins/EcalBarrelClusterFastTimer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25943 Added missing override to ESTrendTask
  DQM/EcalPreshowerMonitorModule/interface/ESTrendTask.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25944 Removed unused variable from lambda capture in EcalDQMMonitorTask
  DQM/EcalMonitorTasks/plugins/EcalDQMonitorTask.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25945 Avoid implicit conversion problem in DTDataIntegrityTest
  DQM/DTMonitorClient/src/DTDataIntegrityTest.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25946 Use unique_ptr constructor for PluginFactory plugins RecoTauTag
  RecoTauTag/RecoTau/plugins/RecoTauCleaner.cc
  RecoTauTag/RecoTau/plugins/RecoTauProducer.cc
  RecoTauTag/TauTagTools/plugins/PFTauMVAInputDiscriminantTranslator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25947 Bug fix to EventSetupImpl::find
  FWCore/Framework/src/EventSetupImpl.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25921 Manage PluginFactory plugins with unique_ptr in RecoMuon
  RecoMuon/L2MuonIsolationProducer/src/L2MuonIsolationProducer.cc
  RecoMuon/L2MuonIsolationProducer/src/L2MuonIsolationProducer.h
  RecoMuon/L3MuonIsolationProducer/src/L3MuonCombinedRelativeIsolationProducer.cc
  RecoMuon/L3MuonIsolationProducer/src/L3MuonCombinedRelativeIsolationProducer.h
  RecoMuon/L3MuonIsolationProducer/src/L3MuonIsolationProducer.cc
  RecoMuon/L3MuonIsolationProducer/src/L3MuonIsolationProducer.h
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.cc
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.h
  RecoMuon/MuonIsolation/interface/MuIsoByTrackPt.h
  RecoMuon/MuonIsolation/src/MuIsoByTrackPt.cc
  RecoMuon/MuonIsolationProducers/plugins/MuIsoDepositProducer.cc
  RecoMuon/MuonIsolationProducers/plugins/MuIsoDepositProducer.h
  RecoMuon/TrackerSeedGenerator/plugins/CompositeTSG.cc
  RecoMuon/TrackerSeedGenerator/plugins/CompositeTSG.h
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromL1Muon.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromL1Muon.h
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromL2Muon.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromL2Muon.h
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromOrderedHits.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromOrderedHits.h
  RecoMuon/TrackerSeedGenerator/plugins/TSGSmart.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGSmart.h
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#25929 Update GT in CMSSW to 105X for ultra legacy
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25952 fastsim to use firstStepPrimaryVerticesBeforeMixing in all iter tracking classifiers
  RecoTracker/IterativeTracking/python/DetachedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/InitialStep_cff.py
  RecoTracker/IterativeTracking/python/JetCoreRegionalStep_cff.py
  RecoTracker/IterativeTracking/python/MixedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/IterativeTracking/python/TobTecStep_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25953 Pass PluginFactory plugin directly to emplace_back() in TrajectoryFilterAnalyzer
  TrackingTools/TrajectoryFiltering/test/TrajectoryFilterAnalyzer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25892 Add BPHParking skim module and the relval steps
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/Skimming/BuildFile.xml
  Configuration/Skimming/interface/LeptonSkimming.h
  Configuration/Skimming/python/Skims_PDWG_cff.py
  Configuration/Skimming/python/pwdgSkimBPark_cfi.py
  Configuration/Skimming/src/LeptonSkimming.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#25888 Manage PluginFactory plugins with unique_ptr in FastSim
  FastSimulation/Tracking/plugins/PixelTracksProducer.cc
  FastSimulation/Tracking/plugins/PixelTracksProducer.h
  FastSimulation/Tracking/plugins/TrajectorySeedProducer.cc
  FastSimulation/Tracking/src/SeedFinderSelector.cc
  FastSimulation/TrackingRecHitProducer/plugins/TrackingRecHitProducer.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#25961 Fix ECAL pedestal tag to be prompt sync and remove PPS alignment tag in GT
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25755 Some GsfElectronAlgo modernization
  RecoEgamma/EgammaElectronAlgos/interface/EgAmbiguityTools.h
  RecoEgamma/EgammaElectronAlgos/interface/ElectronHcalHelper.h
  RecoEgamma/EgammaElectronAlgos/interface/GsfElectronAlgo.h
  RecoEgamma/EgammaElectronAlgos/src/EgAmbiguityTools.cc
  RecoEgamma/EgammaElectronAlgos/src/ElectronHcalHelper.cc
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronBaseProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronBaseProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25954 Removed unused variable from src/EcalTrivialObjectAnalyzer
  CalibCalorimetry/EcalTrivialCondModules/src/EcalTrivialObjectAnalyzer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25956 Use unique_ptr constructor for PluginFactory plugins in RecoPixelVertexing
  RecoPixelVertexing/PixelTriplets/plugins/CombinedHitTripletGenerator.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletHLTGenerator.cc
  RecoPixelVertexing/PixelTriplets/src/CAHitQuadrupletGenerator.cc
  RecoPixelVertexing/PixelTriplets/src/CAHitTripletGenerator.cc
  RecoPixelVertexing/PixelTriplets/test/HitTripletProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25958 Manage PluginFactory plugins with unique_ptr in RecoEcal and RecoLocalCalo/EcalRecProducers
  RecoEcal/EgammaClusterProducers/interface/EgammaSCCorrectionMaker.h
  RecoEcal/EgammaClusterProducers/src/EgammaSCCorrectionMaker.cc
  RecoEcal/EgammaCoreTools/test/testEcalClusterFunctions.cc
  RecoLocalCalo/EcalRecProducers/plugins/ESRecHitProducer.cc
  RecoLocalCalo/EcalRecProducers/plugins/ESRecHitProducer.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducer.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducer.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducer.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25960 Several fixes/improvements to LowPtGsfElectronSCProducer
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSCProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25890 pybind11 based parameter set reading tools
  FWCore/Framework/bin/BuildFile.xml
  FWCore/Framework/bin/cmsRunPyDev.cpp
  FWCore/PyDevParameterSet/BuildFile.xml
  FWCore/PyDevParameterSet/interface/MakePyBind11ParameterSets.h
  FWCore/PyDevParameterSet/interface/PyBind11ProcessDesc.h
  FWCore/PyDevParameterSet/interface/Python11ParameterSet.h
  FWCore/PyDevParameterSet/src/MakePyBind11ParameterSets.cc
  FWCore/PyDevParameterSet/src/PyBind11Module.h
  FWCore/PyDevParameterSet/src/PyBind11ProcessDesc.cc
  FWCore/PyDevParameterSet/src/PyBind11Wrapper.cc
  FWCore/PyDevParameterSet/src/PyBind11Wrapper.h
  FWCore/PyDevParameterSet/src/Python11ParameterSet.cc
  FWCore/PyDevParameterSet/src/initializePyBind11Module.cc
  FWCore/PyDevParameterSet/src/initializePyBind11Module.h
  FWCore/PyDevParameterSet/test/BuildFile.xml
  FWCore/PyDevParameterSet/test/fip.txt
  FWCore/PyDevParameterSet/test/makeprocess_t.cppunit.cc
  FWCore/PyDevParameterSet/test/makepset_t.cppunit.cc
  FWCore/PyDevParameterSet/test/processbuilder_t.cppunit.cpp
  FWCore/PyDevParameterSet/test/readpsetsfrom_t.cppunit.cc
  FWCore/PyDevParameterSet/test/ufip.txt
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25963 Avoid a possible memory leak in PixelTripletNoTipGenerator.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletNoTipGenerator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25913 Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromDDD.cc const-cast fix
  Geometry/GEMGeometry/interface/GEMGeometry.h
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromDDD.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#25975 Change devel build to use pybind11 for cmsRun
  FWCore/Framework/bin/BuildFile.xml
Labels: comparison-pending, core-pending, pending-signatures, tests-pending

#25966 [102X] Backport script for multithreaded tarball management
  GeneratorInterface/LHEInterface/data/run_generic_tarball_cvmfs_manual_multithread.sh
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25874 Utilities and fixes for HipPy alignment
  Alignment/CommonAlignment/scripts/tkal_create_file_lists.py
  Alignment/HIPAlignmentAlgorithm/python/OptionParser/HipPyOptionParser.py
  Alignment/HIPAlignmentAlgorithm/python/align_tpl_py.txt
  Alignment/HIPAlignmentAlgorithm/scripts/hippyaddtobaddatafiles.py
  Alignment/HIPAlignmentAlgorithm/scripts/makeHippyCampaign.py
  Alignment/HIPAlignmentAlgorithm/test/hippysubmittertemplate.sh
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#25885 Add label for pixel digitizer in SiPixelQualityESProducer
  CalibTracker/SiPixelESProducers/interface/SiPixelQualityESProducer.h
  CalibTracker/SiPixelESProducers/plugins/SiPixelQualityESProducer.cc
  CalibTracker/SiPixelESProducers/python/SiPixelQualityESProducer_cfi.py
  Configuration/AlCa/python/autoCond.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_run2_SiPixel_2018_cff.py
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#25935 Add missing overide in HTXSRivetProducer
  GeneratorInterface/RivetInterface/plugins/HTXSRivetProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25934 Fix clang warnings in LzmaFile
  GeneratorInterface/ReggeGribovPartonMCInterface/src/LzmaFile.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25932 Fix clang warning in AMPTHadronizer
  GeneratorInterface/AMPTInterface/src/AMPTHadronizer.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25931 Use auto for iterator declaration in PythiaHepMCFilterGammaGamma
  GeneratorInterface/Core/src/PythiaHepMCFilterGammaGamma.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25962 Clean-up RecoParticleFlow/PFClusterProducer
  RecoParticleFlow/PFClusterProducer/plugins/RBXAndHPDCleaner.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25974 Low pT electrons: bug fix for SuperCluster class
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSCProducer.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25761 Conversion from lowPtGsfTracks backported to 10_2_x
  Configuration/StandardSequences/python/Reconstruction_cff.py
  DataFormats/EgammaCandidates/interface/Conversion.h
  DataFormats/EgammaTrackReco/interface/ConversionTrack.h
  DataFormats/EgammaTrackReco/src/classes_def.xml
  RecoEgamma/Configuration/python/RecoEgamma_EventContent_cff.py
  RecoEgamma/EgammaPhotonProducers/interface/ConversionTrackProducer.h
  RecoEgamma/EgammaPhotonProducers/python/conversionOpenTrackSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/conversionTrackProducer_cfi.py
  RecoEgamma/EgammaPhotonProducers/python/gsfTracksOpenConversionSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/src/ConversionProducer.cc
  RecoEgamma/EgammaPhotonProducers/src/ConversionTrackProducer.cc
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved

#25887 Complete low pT electron chain (back port)
  PhysicsTools/PatAlgos/python/producersLayer1/lowPtElectronProducer_cff.py
  PhysicsTools/PatAlgos/python/producersLayer1/patCandidates_cff.py
  PhysicsTools/PatAlgos/python/selectionLayer1/lowPtElectronSelector_cfi.py
  PhysicsTools/PatAlgos/python/selectionLayer1/selectedPatCandidates_cff.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/slimmedLowPtElectrons_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  PhysicsTools/PatAlgos/python/tools/coreTools.py
  PhysicsTools/PatAlgos/test/IntegrationTest_cfg.py
  PhysicsTools/PatAlgos/test/patTuple_addTriggerInfo_cfg.py
  RecoEgamma/Configuration/python/RecoEgamma_EventContent_cff.py
  RecoEgamma/EgammaElectronProducers/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/interface/LowPtGsfElectronIDHeavyObjectCache.h
  RecoEgamma/EgammaElectronProducers/interface/LowPtGsfElectronSeedHeavyObjectCache.h
  RecoEgamma/EgammaElectronProducers/plugins/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronBaseProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronCoreProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronCoreProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronIDProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronIDProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSCProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSCProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedValueMapsProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedValueMapsProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/SealModule.cc
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronCores_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronID_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSeedValueMaps_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSequence_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSuperClusters_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectrons_cfi.py
  RecoEgamma/EgammaElectronProducers/src/LowPtGsfElectronIDHeavyObjectCache.cc
  RecoEgamma/EgammaElectronProducers/src/LowPtGsfElectronSeedHeavyObjectCache.cc
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#25971 Remove all references to JetCrystalsAssociator
  DataFormats/BTauReco/interface/EMIsolatedTauTagInfo.h
  DataFormats/BTauReco/interface/JetCrystalsAssociation.h
  DataFormats/BTauReco/src/classes.h
  DataFormats/BTauReco/src/classes_def.xml
  RecoBTau/JetCrystalsAssociator/BuildFile.xml
  RecoBTau/JetCrystalsAssociator/src/JetCrystalsAssociator.cc
  Utilities/ReleaseScripts/scripts/git-publish
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25968 Clean the online clients which are unused
  DQM/Integration/python/clients/pixel_timingScan_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/pixel_up_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/pixeltracking_timing_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25955 removing three fragments from override
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#25226 Adding some beta-star variables for JEC workflows. Intended for NANOAOD. Backport of #25223 to 10.2.x
  RecoJets/JetProducers/plugins/BetaStarVarProducer.cc
  RecoJets/JetProducers/python/ak4PFJetsBetaStar_cfi.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25225 Adding some beta-star variables for JEC workflows. Intended for NANOAOD. Backport of #25223 to 9.4.x
  RecoJets/JetProducers/plugins/BetaStarVarProducer.cc
  RecoJets/JetProducers/python/ak4PFJetsBetaStar_cfi.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25986 pybind11 enable interface that takes argc/argv
  FWCore/PyDevParameterSet/interface/PyBind11ProcessDesc.h
  FWCore/PyDevParameterSet/src/MakePyBind11ParameterSets.cc
  FWCore/PyDevParameterSet/src/PyBind11ProcessDesc.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-rejected

#25998 fix typo in FS2018 PU input string
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#25973 Create a prefire veto bit using trigger rules
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py
  L1Trigger/L1TGlobal/plugins/BuildFile.xml
  L1Trigger/L1TGlobal/plugins/L1TExtCondProducer.cc
  L1Trigger/L1TGlobal/python/simGtExtFakeProd_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, operations-approved, orp-approved, tests-approved

#25924 Remove last Modifier.isChosen() calls from L1T configuration
  Configuration/StandardSequences/python/SimL1EmulatorRepack_CalouGT_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full2015Data_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_FullMC_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_FullSimTP_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py
  L1Trigger/Configuration/python/customise_ReEmulateL1_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, operations-approved, orp-approved, tests-approved

#25964 Apply some cleaning in RecoEcal/Egamma*
  RecoEcal/EgammaClusterProducers/src/PreshowerClusterShapeProducer.cc
  RecoEcal/EgammaCoreTools/src/ClusterShapeAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25977 Removed unneeded uses of unique_ptr from GsfElectronAlgo
  RecoEgamma/EgammaElectronAlgos/interface/GsfElectronAlgo.h
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25914 Manage PluginFactory plugins with unique_ptr in PhysicsTools
  PhysicsTools/IsolationAlgos/plugins/CITKPFIsolationSumProducer.cc
  PhysicsTools/IsolationAlgos/plugins/CITKPFIsolationSumProducerForPUPPI.cc
  PhysicsTools/IsolationAlgos/plugins/CandIsoDepositProducer.cc
  PhysicsTools/IsolationAlgos/plugins/CandIsoDepositProducer.h
  PhysicsTools/MVAComputer/src/VarProcessor.cc
  PhysicsTools/MVATrainer/src/TrainProcessor.cc
  PhysicsTools/PatAlgos/interface/ObjectModifier.h
  PhysicsTools/SelectorUtils/interface/VersionedSelector.h
  PhysicsTools/UtilAlgos/interface/CachingVariable.h
  PhysicsTools/UtilAlgos/interface/Selections.h
  PhysicsTools/UtilAlgos/plugins/ConfigurableAnalysis.cc
  PhysicsTools/UtilAlgos/plugins/NTuplingDevice.cc
  PhysicsTools/UtilAlgos/plugins/PlottingDevice.cc
  PhysicsTools/UtilAlgos/src/CachingVariable.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-rejected

#25930 Fix wrong delete called in Herwig6Instance
  GeneratorInterface/Herwig6Interface/interface/Herwig6Instance.h
  GeneratorInterface/Herwig6Interface/src/Herwig6Instance.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25879 Cavern 2018 updated + mb4shileds for neutrons (version 07.02.2019)
  Geometry/CMSCommonData/data/cavern/2018/v1/cavern.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2018XML_cfi.py
Labels: backport-ok, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#25984 B parking Skimming code update
  Configuration/Skimming/interface/LeptonSkimming.h
  Configuration/Skimming/python/pwdgSkimBPark_cfi.py
  Configuration/Skimming/src/LeptonSkimming.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, pdmv-approved, tests-rejected

#26003 Revert "Create a prefire veto bit using trigger rules"
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py
  L1Trigger/L1TGlobal/plugins/BuildFile.xml
  L1Trigger/L1TGlobal/plugins/L1TExtCondProducer.cc
  L1Trigger/L1TGlobal/python/simGtExtFakeProd_cfi.py
Labels: code-checks-approved, comparison-notrun, l1-pending, operations-approved, orp-approved, pending-signatures, tests-rejected

#25997 [105X] removing three fragments from override (backport of #25955)
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26009 Removed unused functions in ClusteringTest
  CommonTools/Clustering1D/test/ClusteringTest.cpp
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26008 Made base and inheriting class agree on checkForCompatibility in CalibTracker
  DQMOffline/CalibTracker/plugins/SiStripDQMPopConSourceHandler.h
  DQMOffline/CalibTracker/plugins/SiStripPopConHistoryDQMBase.cc
  DQMOffline/CalibTracker/plugins/SiStripPopConHistoryDQMBase.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25979 Fix the modifier for HGCalRecHit.layerWeights
  RecoLocalCalo/HGCalRecProducers/python/HGCalRecHit_cfi.py
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#26010 Fix clang warnings in CommonTools/CandAlgos
  CommonTools/UtilAlgos/interface/AssociatedVariableCollectionSelector.h
  CommonTools/Utils/interface/PdgIdExcluder.h
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26015 New working point for B parking skim
  Configuration/Skimming/python/pwdgSkimBPark_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved

#25976 Move duplicate getCtfTrackRef function to its own file
  RecoEgamma/EgammaElectronAlgos/interface/GsfElectronAlgo.h
  RecoEgamma/EgammaElectronAlgos/interface/GsfElectronTools.h
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronTools.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronCoreBaseProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronCoreBaseProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26005 Fixed clang warnings in DQMOffline/RecoB
  DQMOffline/RecoB/interface/TaggingVariablePlotter.h
  DQMOffline/RecoB/src/MatchJet.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26007 Removed HTMHTAnalyzer
  DQMOffline/JetMET/interface/HTMHTAnalyzer.h
  DQMOffline/JetMET/src/HTMHTAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#25948 fixed bugs in relval_step.py and added VBF Hbb Hinv 2018 workflows
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26018 Add forgotten modifications to TB 2006 analysis
  SimG4CMS/HcalTestBeam/python/TB2006Analysis_cfi.py
  SimG4CMS/HcalTestBeam/test/python/run_tb06_all_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25928 New option to the ExternalLHEProducer to enable UNLOPS merging
  GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved
