Repository cms-sw/cmssw, pull requests merged in 2019-05, with the labels that each got.

#26395 BuildFile cleanup: Remove un-used dependency
  CommonTools/Utils/BuildFile.xml
  DataFormats/EgammaTrackReco/BuildFile.xml
  JetMETCorrections/MinBias/BuildFile.xml
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26460 Updating training of MVA, adding low pt MVA and bugfix (muon POG)
  DataFormats/MuonReco/interface/Muon.h
  DataFormats/MuonReco/src/classes_def.xml
  DataFormats/PatCandidates/interface/Muon.h
  DataFormats/PatCandidates/src/Muon.cc
  DataFormats/PatCandidates/src/classes_def_objects.xml
  PhysicsTools/PatAlgos/interface/MuonMvaEstimator.h
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.h
  PhysicsTools/PatAlgos/python/producersLayer1/muonProducer_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/src/MuonMvaEstimator.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved

#26528 Remove AnalysisDataFormats/SiStripClusterInfo and AnalysisDataFormats/Egamma packages plus dependent code
  AnalysisDataFormats/Egamma/BuildFile.xml
  AnalysisDataFormats/Egamma/interface/ElectronID.h
  AnalysisDataFormats/Egamma/interface/ElectronIDAssociation.h
  AnalysisDataFormats/Egamma/interface/ElectronIDFwd.h
  AnalysisDataFormats/Egamma/src/classes.h
  AnalysisDataFormats/Egamma/src/classes_def.xml
  AnalysisDataFormats/SiStripClusterInfo/BuildFile.xml
  AnalysisDataFormats/SiStripClusterInfo/interface/SiStripClusterInfo.h
  CalibTracker/SiStripHitEfficiency/plugins/BuildFile.xml
  CalibTracker/SiStripHitEfficiency/plugins/SiStripHitEffFromCalibTree.cc
  CalibTracker/SiStripHitEfficiency/src/HitEff.cc
  DQM/SiStripMonitorTrack/interface/SiStripMonitorTrack.h
  DQMOffline/Trigger/interface/HLTTauRefProducer.h
  DQMOffline/Trigger/plugins/HLTTauRefProducer.cc
  PhysicsTools/PatUtils/interface/ElectronSelector.h
  PhysicsTools/PatUtils/src/ElectronSelector.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackerTrackHitFilter.cc
  Utilities/ReleaseScripts/scripts/git-publish
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, core-approved, dqm-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26580 Migrate EcalElectronicsMappingBuilder to EventSetup consumes
  Geometry/EcalMapping/plugins/EcalElectronicsMappingBuilder.cc
  Geometry/EcalMapping/plugins/EcalElectronicsMappingBuilder.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26520 [PPS] [UL rereco] Labels for PPS/TOTEM timing calibration
  Configuration/AlCa/python/autoCond.py
  RecoCTPPS/TotemRPLocal/plugins/CTPPSDiamondRecHitProducer.cc
  RecoCTPPS/TotemRPLocal/plugins/TotemTimingRecHitProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26542 DMRs separated by charge - Tracker Alignment
  Alignment/OfflineValidation/plugins/TrackerOfflineValidation.cc
  Alignment/OfflineValidation/python/TkAlAllInOneTool/offlineValidation.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/offlineValidationTemplates.py
  Alignment/OfflineValidation/python/TrackerOfflineValidation_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26564 Phase2-hgx193 PhUpdate HGCal geometry for the support structure
  Geometry/HGCalCommonData/data/hgcalEE/v10/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v10/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v10/hgcalHEsil.xml
  Geometry/HGCalCommonData/interface/HGCalGeomTools.h
  Geometry/HGCalCommonData/plugins/DDHGCalEEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.cc
  Geometry/HGCalCommonData/src/HGCalGeomTools.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26566 Migrate CSCGeometryESModule to EventSetup consumes
  Geometry/CSCGeometryBuilder/plugins/CSCGeometryESModule.cc
  Geometry/CSCGeometryBuilder/plugins/CSCGeometryESModule.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26574 Remove dead assignments inside CSCRawToDigi
  EventFilter/CSCRawToDigi/src/CSCDCCExaminer.cc
  EventFilter/CSCRawToDigi/src/CSCDDUEventData.cc
  EventFilter/CSCRawToDigi/src/CSCTMBData.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26527 Migrate DigiToRaw to Tasks
  Configuration/StandardSequences/python/DigiToRawDM_cff.py
  Configuration/StandardSequences/python/DigiToRaw_Repack_cff.py
  Configuration/StandardSequences/python/DigiToRaw_cff.py
  EventFilter/HcalRawToDigi/python/HcalDigiToRaw_cfi.py
  EventFilter/L1TRawToDigi/python/caloLayer1Raw_cfi.py
  EventFilter/L1TRawToDigi/test/test_CaloLayer1.py
  L1Trigger/Configuration/python/L1TDigiToRaw_cff.py
Labels: code-checks-approved, comparison-available, l1-pending, operations-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26577 Migrate Geometry/DTGeometryBuilder to EventSetup consumes
  Geometry/DTGeometryBuilder/plugins/DTGeometryESModule.cc
  Geometry/DTGeometryBuilder/plugins/DTGeometryESModule.h
  Geometry/DTGeometryBuilder/plugins/DTGeometryValidate.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryESProducer.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryTest.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26549 Migrate L1 step to Tasks
  Configuration/StandardSequences/python/SimL1EmulatorRepack_CalouGT_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full2015Data_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_FullMC_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_FullSimTP_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_GCTGT_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_GT1_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_GT2_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_GT_cff.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py
  HLTrigger/Configuration/python/CustomConfigs.py
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/Configuration/python/SimL1TechnicalTriggers_cff.py
  L1Trigger/L1TCalorimeter/python/L1TCaloStage1_PPFromRaw_cff.py
  L1Trigger/L1TCalorimeter/python/L1TCaloStage1_cff.py
  L1Trigger/L1TCalorimeter/python/L1TCaloStage2_PPFromRaw_cff.py
  L1Trigger/L1TCalorimeter/python/L1TCaloStage2_cff.py
  L1Trigger/L1TCalorimeter/python/L1TRerunHCALTP_FromRaw_cff.py
  L1Trigger/L1TCalorimeter/python/simDigis_cff.py
  L1Trigger/L1TGlobal/python/simDigis_cff.py
  L1Trigger/L1THGCal/python/hgcalBackEndLayer1_cff.py
  L1Trigger/L1THGCal/python/hgcalBackEndLayer2_cff.py
  L1Trigger/L1THGCal/python/hgcalConcentrator_cff.py
  L1Trigger/L1THGCal/python/hgcalTowerMap_cff.py
  L1Trigger/L1THGCal/python/hgcalTower_cff.py
  L1Trigger/L1THGCal/python/hgcalTriggerPrimitives_cff.py
  L1Trigger/L1THGCal/python/hgcalVFE_cff.py
  L1Trigger/L1THGCalUtilities/python/hgcalTriggerChains.py
  L1Trigger/L1TMuon/python/simDigis_cff.py
  L1Trigger/ME0Trigger/python/me0TriggerPseudoDigis_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, l1-approved, operations-approved, orp-approved, tests-approved, upgrade-approved

#26581 Migrate Geometry/EcalTestBeam to EventSetup consumes
  Geometry/EcalTestBeam/plugins/EcalTBGeometryBuilder.cc
  Geometry/EcalTestBeam/plugins/EcalTBGeometryBuilder.h
  Geometry/EcalTestBeam/plugins/EcalTBHodoscopeGeometryEP.cc
  Geometry/EcalTestBeam/plugins/EcalTBHodoscopeGeometryEP.h
  Geometry/EcalTestBeam/test/CrystalCenterDump.cc
  Geometry/EcalTestBeam/test/EcalTBHodoscopeGeometryAnalyzer.cc
  Geometry/EcalTestBeam/test/ee/CaloGeometryEPtest.h
  Geometry/EcalTestBeam/test/ee/SurveyToTransforms.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26585 Migrate WriteESAlignments to EventSetup consumes
  Geometry/CaloEventSetup/test/TestWriteESAlignments.cc
  Geometry/EcalAlgo/interface/WriteESAlignments.h
  Geometry/EcalAlgo/src/WriteESAlignments.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26588 Allow python 3 execution of test configs in FWCore/Framework
  FWCore/Framework/test/test_global_modules_cfg.py
  FWCore/Framework/test/test_limited_modules_cfg.py
  FWCore/Framework/test/test_one_modules_cfg.py
  FWCore/Framework/test/test_stream_modules_cfg.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26587 Migrate Geometry/GlobalTrackingGeometryBuilder to EventSetup consumes
  Geometry/GlobalTrackingGeometryBuilder/plugins/GlobalTrackingGeometryESProducer.cc
  Geometry/GlobalTrackingGeometryBuilder/plugins/GlobalTrackingGeometryESProducer.h
  Geometry/GlobalTrackingGeometryBuilder/test/GlobalTrackingGeometryTest.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26370 [102X] Update DeepAK8 to 94X training
  RecoBTag/MXNet/plugins/DeepBoostedJetTagsProducer.cc
  RecoBTag/MXNet/python/Parameters/V01/pfDeepBoostedJetPreprocessParams_cfi.py
  RecoBTag/MXNet/python/Parameters/V02/pfDeepBoostedJetPreprocessParams_cfi.py
  RecoBTag/MXNet/python/Parameters/V02/pfMassDecorrelatedDeepBoostedJetPreprocessParams_cfi.py
  RecoBTag/MXNet/python/pfDeepBoostedJet_cff.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved, xpog-approved

#26583 Fix memory usage in PPSUtilities and PPSProtonTransport
  FastSimulation/CTPPSFastTrackingProducer/plugins/CTPPSFastTrackingProducer.cc
  SimTransport/PPSProtonTransport/interface/ProtonTransport.h
  SimTransport/PPSProtonTransport/src/HectorTransport.cc
  SimTransport/PPSProtonTransport/src/ProtonTransport.cc
  SimTransport/PPSProtonTransport/src/TotemTransport.cc
  Utilities/PPS/interface/PPSUtilities.h
  Utilities/PPS/src/PPSUtilities.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#26575 Phase2-hgx194 Add new method maskCell to topology or RecHitTool
  Geometry/CaloTopology/interface/HGCalTopology.h
  RecoLocalCalo/HGCalRecAlgos/interface/RecHitTools.h
  RecoLocalCalo/HGCalRecAlgos/src/RecHitTools.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#26283 Added a tool to do a bin by bin DQM root file comparison
  DQMServices/FileIO/scripts/blacklist.py
  DQMServices/FileIO/scripts/compareDQMOutput.py
  DQMServices/FileIO/scripts/compareHistograms.py
  DQMServices/FileIO/scripts/dqm-histo-comparison-summary-template.html
  DQMServices/FileIO/scripts/visDQMUpload.py
  DQMServices/FileIO/scripts/visDQMUtils.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26578 Decrease memory used by OscarMTProducer
  SimG4CMS/Calo/interface/CaloSD.h
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Tracker/interface/TkAccumulatingSensitiveDetector.h
  SimG4CMS/Tracker/src/TkAccumulatingSensitiveDetector.cc
  SimG4Core/Application/interface/RunManager.h
  SimG4Core/Application/interface/RunManagerMTWorker.h
  SimG4Core/Application/plugins/OscarMTProducer.cc
  SimG4Core/Application/plugins/OscarProducer.cc
  SimG4Core/Application/src/RunManager.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/SensitiveDetector/interface/SensitiveCaloDetector.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26541 switch to tau id MVA2017v2 in AOD and MiniAOD
  RecoTauTag/Configuration/python/HPSPFTaus_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26572 2017 pileup scenario for ultra-legacy using bunch-by-bunch 2017 data
  Configuration/StandardSequences/python/Mixing.py
  SimGeneral/MixingModule/python/mix_2017_25ns_UltraLegacy_PoissonOOTPU_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#26591 Migrate Geometry/HGCalCommonData to EventSetup consumes
  Geometry/HGCalCommonData/plugins/FastTimeNumberingInitialization.cc
  Geometry/HGCalCommonData/plugins/FastTimeParametersESModule.cc
  Geometry/HGCalCommonData/plugins/HGCalNumberingInitialization.cc
  Geometry/HGCalCommonData/plugins/HGCalParametersESModule.cc
  Geometry/HGCalCommonData/test/FastTimeNumberingTester.cc
  Geometry/HGCalCommonData/test/HGCGeometryTester.cc
  Geometry/HGCalCommonData/test/HGCalNumberingTester.cc
  Geometry/HGCalCommonData/test/HGCalParameterTester.cc
  Geometry/HGCalCommonData/test/HGCalParametersAnalyzer.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26586 atomize counters in BaseIsolator.h
  PhysicsTools/PatAlgos/interface/BaseIsolator.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26596 Have checkImportPermission work properly under python3
  FWCore/ParameterSet/python/Config.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25883 Removing hard-coded eta dependency from PFEnergyCalibration.cc
  CondFormats/PhysicsToolsObjects/interface/PerformanceResult.h
  RecoParticleFlow/PFClusterTools/interface/PFEnergyCalibration.h
  RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc
  RecoParticleFlow/PFClusterTools/test/BuildFile.xml
  RecoParticleFlow/PFClusterTools/test/ProducePFCalibration.py
  RecoParticleFlow/PFClusterTools/test/ProducePFCalibrationObject.cc
  RecoParticleFlow/PFClusterTools/test/ProducePFCalibrationObject.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26616 Fix dressed lepton constituents, add tau ghosts
  GeneratorInterface/RivetInterface/interface/RivetAnalysis.h
  GeneratorInterface/RivetInterface/plugins/ParticleLevelProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26634 drop provenance checks when not needed in DeepFlavourTagInfoProducer
  RecoBTag/FeatureTools/plugins/DeepFlavourTagInfoProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26633 Use explicit type for lambda in CaloSD
  SimG4CMS/Calo/src/CaloSD.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26510 Introduce relval worflow for beam-halo in 2018 and post-LS2 detector configuration
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  SimGeneral/MixingModule/python/digitizersCosmics_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, simulation-approved, tests-approved, upgrade-approved

#26605 Code format to avoid recursive formatting
  Alignment/CocoaModel/src/ALILine.cc
  Alignment/CocoaModel/src/EntryAngleAffAngles.cc
  Alignment/CocoaModel/src/OptOTiltmeter.cc
  Alignment/CocoaToDDL/src/CocoaToDDLMgr.cc
  Alignment/CocoaUtilities/interface/ALIUtils.h
  Alignment/MillePedeAlignmentAlgorithm/src/MillePedeMonitor.cc
  Alignment/TrackerAlignment/src/AlignableSiStripDet.cc
  CalibFormats/HcalObjects/interface/HcalCoderDb.h
  CalibFormats/HcalObjects/src/HcalCoderDb.cc
  CalibFormats/SiPixelObjects/src/PixelFEDCard.cc
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAngle.cc
  Calibration/Tools/bin/mergeXMLEB.cpp
  Calibration/Tools/bin/mergeXMLEE.cpp
  CommonTools/TriggerUtils/plugins/CandidateTriggerObjectProducer.cc
  CondCore/EcalPlugins/plugins/EcalPedestals_PayloadInspector.cc
  DQM/SiPixelMonitorDigi/interface/SiPixelDigiModule.h
  DQMOffline/JetMET/src/DQMPFCandidateAnalyzer.cc
  EventFilter/CSCTFRawToDigi/src/CSCSPEvent.cc
  EventFilter/Utilities/test/testGlobalNumbers.cc
  GeneratorInterface/GenFilters/src/HeavyQuarkFromMPIFilterAlgo.cc
  GeneratorInterface/Hydjet2Interface/src/EquationSolver.icc
  GeneratorInterface/ReggeGribovPartonMCInterface/src/LzmaDec.h
  L1Trigger/CSCTrackFinder/src/CSCTFPtMethods.cc
  L1Trigger/DTBti/src/DTBtiChip.cc
  L1Trigger/DTTriggerServerTheta/src/DTTSTheta.cc
  L1Trigger/L1TMuonEndCap/src/PtAssignmentEngine2017.cc
  L1Trigger/RPCTrigger/src/RPCBasicTrigConfig.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelClusterProducer.cc
  RecoTBCalo/EcalTBRecProducers/src/EcalTBWeightUncalibRecHitProducer.cc
  SimCalorimetry/EcalSelectiveReadoutProducers/src/EcalSelectiveReadoutProducer.cc
  SimTracker/TrackAssociatorProducers/plugins/TrackAssociatorByHitsImpl.cc
  TBDataFormats/EcalTBObjects/interface/EcalTBTDCRawInfo.h
  Utilities/StaticAnalyzers/src/ArgSizeChecker.cpp
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, core-pending, daq-approved, db-pending, dqm-approved, generators-pending, l1-pending, orp-approved, pending-signatures, reconstruction-approved, simulation-pending, tests-approved

#26597 Prevent simultaneous execution of Rivet modules
  GeneratorInterface/RivetInterface/interface/RivetAnalyzer.h
  GeneratorInterface/RivetInterface/plugins/HTXSRivetProducer.cc
  GeneratorInterface/RivetInterface/plugins/ParticleLevelProducer.cc
  GeneratorInterface/RivetInterface/plugins/RivetAnalyzer.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26639 [HeaderCheck][CORE] Cleanup headers to avoid header inconsistency errors
  FWCore/Framework/interface/ESConsumesCollector.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26649 [HeaderCheck][GEO] Cleanup headers to avoid header inconsistency errors
  Geometry/CommonTopologies/BuildFile.xml
  Geometry/Records/interface/GeometricDetExtraRcd.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26643 [HeaderCheck][DB] Cleanup headers to avoid header inconsistency errors
  CondTools/SiPixel/interface/PixelPopConDCSSourceHandler.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26506 Add more calorimeter energy fractions to PackedCandidates
  DataFormats/PatCandidates/interface/PackedCandidate.h
  DataFormats/PatCandidates/src/PackedCandidate.cc
  DataFormats/PatCandidates/src/classes_def_objects.xml
  PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc
  RecoBTag/FeatureTools/plugins/DeepBoostedJetTagInfoProducer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#26544 Phase 2 Trackers. Remove T12 and T13 (IT portcards placement study). Add T15 (Major Inner Tracker MB update from latest Mechanical designs).
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2023D36Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2023D36_cff.py
  Configuration/Geometry/python/GeometryExtended2023D42Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2023D42_cff.py
  Configuration/Geometry/python/dict2023Geometry.py
  Configuration/PyReleaseValidation/python/relval_2023.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D36XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D42XML_cfi.py
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker460/pixel.xml
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker613_MB_2019_04/pixbar.xml
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker613_MB_2019_04/pixel.xml
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker613_MB_2019_04/pixfwd.xml
  Geometry/TrackerCommonData/data/PhaseII/TiltedTracker613_MB_2019_04/tracker.xml
  Geometry/TrackerRecoData/data/PhaseII/TiltedTracker613_MB_2019_04/trackerRecoMaterial.xml
Labels: code-checks-approved, comparison-available, geometry-approved, operations-approved, orp-approved, pdmv-pending, pending-signatures, tests-approved, upgrade-approved

#26582 Make static map const in HGCalConcentratorSuperTriggerCellImpl
  L1Trigger/L1THGCal/interface/concentrator/HGCalConcentratorSuperTriggerCellImpl.h
  L1Trigger/L1THGCal/src/concentrator/HGCalConcentratorSuperTriggerCellImpl.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#26671 Migrate Geometry/HcalCommonData to EventSetup consumes
  Geometry/HcalCommonData/plugins/HcalDDDRecConstantsESMoudle.cc
  Geometry/HcalCommonData/plugins/HcalDDDSimConstantsESModule.cc
  Geometry/HcalCommonData/plugins/HcalParametersESModule.cc
  Geometry/HcalCommonData/test/HcalParametersAnalyzer.cc
  Geometry/HcalCommonData/test/HcalRecNumberingTester.cc
  Geometry/HcalCommonData/test/HcalSimNumberingTester.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26650 [HeaderCheck][L1] Cleanup headers to avoid header inconsistency errors
  L1Trigger/RegionalCaloTrigger/interface/L1GctRegion.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#26534 Bring performance improvement in KDTreeLinkerAlgo as in #772 to RecoParticleFlow
  CommonTools/RecoAlgos/interface/KDTreeLinkerAlgo.h
  CommonTools/RecoAlgos/interface/KDTreeLinkerTools.h
  RecoParticleFlow/PFProducer/interface/KDTreeLinkerAlgo.h
  RecoParticleFlow/PFProducer/interface/KDTreeLinkerBase.h
  RecoParticleFlow/PFProducer/interface/KDTreeLinkerTools.h
  RecoParticleFlow/PFProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerPSEcal.cc
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerPSEcal.h
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackEcal.cc
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackEcal.h
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackHcal.cc
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackHcal.h
  RecoParticleFlow/PFProducer/src/KDTreeLinkerAlgo.cc
  RecoPixelVertexing/PixelTriplets/plugins/BuildFile.xml
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletHLTGenerator.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletLargeTipGenerator.cc
  RecoTracker/TkSeedGenerator/plugins/BuildFile.xml
  RecoTracker/TkSeedGenerator/plugins/MultiHitGeneratorFromChi2.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26556 Fix bit value checks in HcalNoiseInfoProducer
  RecoMET/METProducers/src/HcalNoiseInfoProducer.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26615 BugFix for the reconstruction_fromReco sequences: https://github.com/cms-sw/cmssw/issues/26500
  Configuration/ProcessModifiers/python/recoFromReco_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  RecoLocalMuon/Configuration/python/RecoLocalMuon_EventContent_cff.py
  RecoMuon/MuonIdentification/python/muons1stStep_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, pdmv-approved, reconstruction-approved, tests-approved, upgrade-approved

#26640 [HeaderCheck][Sim] DataFormats/SiPixelDigi and Mixing/Base
  DataFormats/SiPixelDigi/interface/PixelDigifwd.h
  Mixing/Base/interface/PoissonPUGenerator.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26642 [HeaderCheck][DAQ] Cleanup headers to avoid header inconsistency errors
  DataFormats/FEDRawData/interface/DaqData.h
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, tests-approved

#26545 [HGCAL trigger] Configuration updates. New eg ID. Gen macthing selector. Noise threshold.
  L1Trigger/L1THGCal/interface/veryfrontend/HGCalVFESummationImpl.h
  L1Trigger/L1THGCal/plugins/veryfrontend/HGCalVFEProcessorSums.cc
  L1Trigger/L1THGCal/python/customClustering.py
  L1Trigger/L1THGCal/python/customIdentification.py
  L1Trigger/L1THGCal/python/customTriggerCellSelect.py
  L1Trigger/L1THGCal/python/egammaIdentification.py
  L1Trigger/L1THGCal/python/hgcalBackEndLayer1Producer_cfi.py
  L1Trigger/L1THGCal/python/hgcalBackEndLayer2Producer_cfi.py
  L1Trigger/L1THGCal/python/hgcalConcentratorProducer_cfi.py
  L1Trigger/L1THGCal/python/hgcalTriggerPrimitives_cff.py
  L1Trigger/L1THGCal/python/hgcalVFEProducer_cfi.py
  L1Trigger/L1THGCal/src/veryfrontend/HGCalTriggerCellCalibration.cc
  L1Trigger/L1THGCal/src/veryfrontend/HGCalVFESummationImpl.cc
  L1Trigger/L1THGCalUtilities/plugins/selectors/HGC3DClusterGenMatchSelector.cc
  L1Trigger/L1THGCalUtilities/python/HGC3DClusterGenMatchSelector_cff.py
  L1Trigger/L1THGCalUtilities/python/HGC3DClusterGenMatchSelector_cfi.py
  L1Trigger/L1THGCalUtilities/python/clustering2d.py
  L1Trigger/L1THGCalUtilities/python/clustering3d.py
  L1Trigger/L1THGCalUtilities/python/concentrator.py
  L1Trigger/L1THGCalUtilities/python/customNtuples.py
  L1Trigger/L1THGCalUtilities/python/hgcalTriggerChains.py
  L1Trigger/L1THGCalUtilities/python/hgcalTriggerNtuples_cfi.py
  L1Trigger/L1THGCalUtilities/python/selectors.py
  L1Trigger/L1THGCalUtilities/test/testHGCalL1T_multialgo_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, requires-external, tests-approved, upgrade-approved

#26620 Phase2-hgx195 Add new access code for scintillator cells of HGCal
  Geometry/HGCalCommonData/interface/HGCalDDDConstants.h
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.cc
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26654 Store L1 prefiring weights in 2016 and 2017 MINIAOD
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_run2_L1prefiring_cff.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#26656 [HeaderCheck][RECO1] Cleanup headers to avoid header inconsistency errors
  RecoTracker/CkfPattern/interface/bqueue.h
  RecoTracker/MeasurementDet/interface/NonPropagatingDetMeasurements.h
  RecoTracker/MeasurementDet/interface/OnDemandMeasurementTracker.h
  RecoTracker/MeasurementDet/interface/RecHitPropagator.h
  RecoTracker/MeasurementDet/interface/StripClusterAboveU.h
  RecoTracker/Record/interface/Records.h
  RecoTracker/TkSeedGenerator/interface/SeedFromConsecutiveHitsCreator.h
  RecoTracker/TkSeedGenerator/interface/SeedFromConsecutiveHitsStraightLineCreator.h
  RecoTracker/TkSeedGenerator/interface/SeedFromConsecutiveHitsTripletOnlyCreator.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26659 [HeaderCheck][RECO2] Cleanup headers to avoid header inconsistency errors
  TrackingTools/GsfTools/interface/KeepingNonZeroWeightsMerger.h
  TrackingTools/GsfTools/interface/LargestWeightsStateMerger.h
  TrackingTools/GsfTools/interface/MahalanobisDistance.h
  TrackingTools/GsfTools/interface/RCMultiGaussianState.h
  TrackingTools/MeasurementDet/interface/GeometricSearchDetMeasurements.h
  TrackingTools/TrajectoryFiltering/interface/BaseCkfTrajectoryFilter.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26660 [HeaderCheck][Reco] RecoVertex/KinematicFitPrimitives
  RecoVertex/KinematicFitPrimitives/interface/KinematicVertexAssociator.h
  RecoVertex/KinematicFitPrimitives/interface/KinematicVertexDistance.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26662 [HeaderCheck][RECO3] Cleanup headers to avoid header inconsistency errors
  RecoEcal/EgammaClusterAlgos/interface/LogPositionCalc.h
  RecoLocalCalo/EcalRecAlgos/interface/EcalSeverityLevelService.h
  RecoMuon/GlobalTrackingTools/interface/MuonTkNavigationSchool.h
  RecoMuon/MuonIsolation/interface/MuIsoExtractor.h
  RecoMuon/MuonIsolation/interface/MuIsoExtractorFactory.h
  RecoPixelVertexing/PixelTriplets/interface/CombinedHitTripletGenerator.h
  RecoPixelVertexing/PixelTriplets/interface/ThirdHitPredictionFromInvLine.h
  RecoPixelVertexing/PixelTriplets/interface/ThirdHitPredictionFromInvParabola.h
  RecoPixelVertexing/PixelTriplets/interface/ThirdHitRZPrediction.h
  RecoTauTag/TauTagTools/interface/ElementsInEllipseRef.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26664 Migrate Geometry/HGCalGeometry to EventSetup consumes
  Geometry/HGCalGeometry/plugins/FastTimeGeometryESProducer.cc
  Geometry/HGCalGeometry/plugins/HGCalGeometryESProducer.cc
  Geometry/HGCalGeometry/test/CaloCellGeometryTester.cc
  Geometry/HGCalGeometry/test/FastTimeGeometryTester.cc
  Geometry/HGCalGeometry/test/HGCalGeometryCheck.cc
  Geometry/HGCalGeometry/test/HGCalGeometryCornerTester.cc
  Geometry/HGCalGeometry/test/HGCalGeometryTester.cc
  Geometry/HGCalGeometry/test/HGCalSizeTester.cc
  Geometry/HGCalGeometry/test/HGCalTestNeighbor.cc
  Geometry/HGCalGeometry/test/HGCalTestRecHitTool.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26673 Modernized CTPPSGeometryESModule
  Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryESModule.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26680 print statement fixes and preserve integer division with python3
  DQMServices/FwkIO/test/read_merged_file1_file3_file2_cfg.py
  DQMServices/FwkIO/test/read_merged_file1_file3_file4_cfg.py
  Validation/Geometry/test/runP_Tracker_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#26681 Get rid of useless repeated config_.exists() in SiPixelRawToDigi.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26638 [HeaderCheck] Cleanup ALCA headers to avoid header inconsistency errors
  Alignment/LaserAlignment/interface/LaserHitPairGenerator.h
  Alignment/LaserAlignment/interface/SeedGeneratorForLaserBeams.h
  CalibFormats/SiPixelObjects/interface/PixelMaskCommon.h
  CalibTracker/SiStripCommon/plugins/SealModules.cc
  CalibTracker/SiStripCommon/plugins/ShallowSimTracksProducer.cc
  CalibTracker/SiStripCommon/plugins/ShallowSimTracksProducer.h
  CalibTracker/SiStripLorentzAngle/interface/SiStripCalibLorentzAngle.h
  CalibTracker/SiStripLorentzAngle/interface/SiStripLAProfileBooker.h
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLAProfileBooker.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26644 [HeaderCheck][Sim] SimGeneral/NoiseGenerators
  SimGeneral/NoiseGenerators/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26667 [HeaderCheck][Reco] RecoVertex/MultiVertexFit
  RecoVertex/MultiVertexFit/interface/LinPtFinderFromAdaptiveFitter.h
  RecoVertex/MultiVertexFit/src/LinPtFinderFromAdaptiveFitter.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26646 [HeaderCheck][DQM] Cleanup headers to avoid header inconsistency errors
  DQM/SiStripCommissioningDbClients/interface/SamplingHistosUsingDb.h
  DQM/SiStripHistoricInfoClient/interface/classes.h
  DQM/SiStripHistoricInfoClient/interface/fitUtilities.h
  DQMServices/Diagnostic/interface/classes.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26647 [HeaderCheck][GenIfc] Pythia8 & Tauola
  GeneratorInterface/Pythia8Interface/interface/RandomP8.h
  GeneratorInterface/TauolaInterface/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26648 Fix for PSMonitor if the PrescaleService is not available
  DQM/HLTEvF/plugins/PSMonitor.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#26653 [HeaderCheck][DQM-GEN] Validation/EventGenerator
  Validation/EventGenerator/BuildFile.xml
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, generators-approved, orp-approved, tests-approved

#26661 Add tau ghosts for dressed leptons (10_2_X)
  GeneratorInterface/RivetInterface/interface/RivetAnalysis.h
  GeneratorInterface/RivetInterface/plugins/ParticleLevelProducer.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26655 JETMET LumiFlag
  DQMOffline/JetMET/src/METAnalyzer.cc
Labels: code-checks-approved, comparison-pending, dqm-approved, fully-signed, orp-approved, tests-approved

#26689 Update DQMServices for protobuf 3.6.1.2 and tensorflow interfaces for TF 1.13.1 (copy of 25889)
  DQMServices/Core/src/ROOTFilePB.pb.cc
  DQMServices/Core/src/ROOTFilePB.pb.h
  PhysicsTools/TensorFlow/BuildFile.xml
  PhysicsTools/TensorFlow/interface/TensorFlow.h
  PhysicsTools/TensorFlow/src/NTSession.cc
  PhysicsTools/TensorFlow/src/NTSession.h
  PhysicsTools/TensorFlow/src/TBBSession.cc
  PhysicsTools/TensorFlow/src/TBBSession.h
  PhysicsTools/TensorFlow/src/TensorFlow.cc
  PhysicsTools/TensorFlow/test/BuildFile.xml
  PhysicsTools/TensorFlow/test/testGraphLoading.cc
  PhysicsTools/TensorFlow/test/testHelloWorld.cc
  PhysicsTools/TensorFlow/test/testLoading.cc
  PhysicsTools/TensorFlow/test/testMetaGraphLoading.cc
  PhysicsTools/TensorFlow/test/tfadd_t.cpp
Labels: analysis-pending, comparison-pending, dqm-pending, pending-signatures, reconstruction-pending, tests-pending

#26464 Bump TObject versions for ROOT 6.14.
  DQMServices/Components/test/testSchemaEvolution.cpp
Labels: comparison-available, dqm-pending, hold, pending-signatures, requires-external, tests-approved

#26636 Output BadFED Channel only for Phase 1
  SimGeneral/MixingModule/python/aliases_PreMix_cfi.py
  SimGeneral/MixingModule/python/aliases_cfi.py
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26652 [HeaderCheck][GenIfc] GeneratorInterface/EvtGenInterface
  GeneratorInterface/EvtGenInterface/BuildFile.xml
  GeneratorInterface/EvtGenInterface/interface/EvtGenLHCInterface.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26604 DD4hep: DDTIDAxialCable Algorithm
  DetectorDescription/DDCMS/data/cms-test-tid-axial-cable-algorithm.xml
  DetectorDescription/DDCMS/data/testDDTIDAxialCableAlgorithm.xml
  DetectorDescription/DDCMS/test/python/testDDTIDAxialCableAlgorithm.py
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIDAxialCableAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26526 Overlap Validation for Tracker Alignment
  Alignment/OfflineValidation/macros/FitPVResiduals.C
  Alignment/OfflineValidation/macros/PlotAlignmentValidation.C
  Alignment/OfflineValidation/macros/TkAlStyle.cc
  Alignment/OfflineValidation/macros/trackSplitPlot.C
  Alignment/OfflineValidation/plugins/BuildFile.xml
  Alignment/OfflineValidation/plugins/OverlapValidation.cc
  Alignment/OfflineValidation/python/TkAlAllInOneTool/configTemplates.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/overlapValidation.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/overlapValidationTemplates.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/plottingOptions.py
  Alignment/OfflineValidation/python/TkAlStyle.py
  Alignment/OfflineValidation/python/overlapValidationPlot.py
  Alignment/OfflineValidation/scripts/compareAlignments.cc
  Alignment/OfflineValidation/scripts/validateAlignments.py
  Alignment/OfflineValidation/test/testTkAlStyle.C
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26531 Added random particles to CloseByParticleGun generator
  Configuration/Generator/python/CloseByParticle_Photon_ERZRanges_cfi.py
  IOMC/ParticleGuns/interface/CloseByParticleGunProducer.h
  IOMC/ParticleGuns/src/CloseByParticleGunProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26698 [HeaderCheck][Sim] Remove unused header in Mixing/Base
  Mixing/Base/interface/PoissonPUGenerator.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26699 Phase2 Cluster1D Visualization
  Fireworks/Geometry/src/FWRecoGeometryESProducer.cc
  Fireworks/Tracks/interface/TrackUtils.h
  Fireworks/Tracks/plugins/FWItemTrackAccessors.cc
  Fireworks/Tracks/plugins/FWPhase2TrackerCluster1DDetProxyBuilder.cc
  Fireworks/Tracks/plugins/FWPhase2TrackerCluster1DProxyBuilder.cc
  Fireworks/Tracks/src/TrackUtils.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#26701 Use EventSetup consumes in TrackerDigiGeometryESModule
  Geometry/TrackerGeometryBuilder/plugins/TrackerDigiGeometryESModule.cc
  Geometry/TrackerGeometryBuilder/plugins/TrackerDigiGeometryESModule.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26665 [HeaderCheck][Reco] CommonTools/RecoAlgos & MagneticField/Interpolation
  CommonTools/RecoAlgos/interface/PixelMatchGsfElectronSelector.h
  MagneticField/Interpolation/interface/MFGrid3D.h
  MagneticField/VolumeGeometry/interface/MagneticFieldVolume.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26720 Move tabs to spaces to avoid complaints from the python3 compiler
  Alignment/OfflineValidation/python/overlapValidationPlot.py
Labels: alca-pending, code-checks-approved, comparison-pending, orp-approved, pending-signatures, tests-started

#26657 Prevent simultaneous execution of Rivet modules (10_2_X)
  GeneratorInterface/RivetInterface/interface/RivetAnalyzer.h
  GeneratorInterface/RivetInterface/plugins/HTXSRivetProducer.cc
  GeneratorInterface/RivetInterface/plugins/ParticleLevelProducer.cc
  GeneratorInterface/RivetInterface/plugins/RivetAnalyzer.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26302 Fixing the calculation of MET Uncertainties by using PFMuons, PFElectrons, PFTaus, and PFPhotons
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
Labels: analysis-pending, bug-fix, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26607 [PPS] Timing detectors tracks window reduced to 25 ns in lite tracks format
  RecoCTPPS/TotemRPLocal/plugins/CTPPSLocalTrackLiteProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26672 define nano 2018 _102Xv1 steps and use in 2018 data nano wf 136.8521
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, requires-external, tests-started, upgrade-approved, xpog-approved

#26682 preserve integer divisions compatible with python3 syntax
  DQMOffline/Trigger/python/FSQHLTOfflineSource_cfi.py
  L1Trigger/ME0Trigger/python/me0TriggerPseudoDigis_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#26651 Updating DT Online-DQM to work with slice test data
  DQM/DTMonitorModule/interface/DTDigiTask.h
  DQM/DTMonitorModule/python/dtDigiTask_TP_cfi.py
  DQM/DTMonitorModule/python/dtDigiTask_cfi.py
  DQM/DTMonitorModule/python/slice_test_customizations_cff.py
  DQM/DTMonitorModule/python/test/dtDqmPythonTypes.py
  DQM/DTMonitorModule/python/test/dt_dqm_sourceclient-live_cfg.py
  DQM/DTMonitorModule/python/test/inputsource_live_cfi.py
  DQM/DTMonitorModule/src/DTDigiTask.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26704 [muon] add sim hit match quality and pileup identification information in MiniAOD
  DataFormats/PatCandidates/interface/Muon.h
  DataFormats/PatCandidates/src/classes_def_objects.xml
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26723 Fix in preselection of low pt muon mva (muon POG)
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26593 RelMon histogram comparison: adapt ranges in a compatible way with the definition of getNbins
  Utilities/RelMon/python/utils.py
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26732 removing unused header
  GeneratorInterface/EvtGenInterface/interface/EvtGenLHCInterface.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26725 Fix: dump HGCal rechit center
  Fireworks/Calo/plugins/FWCaloClusterProxyBuilder.cc
  Fireworks/Geometry/src/FWRecoGeometryESProducer.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#26522 ECAL : management of PF RecHits Thresholds and Laser Alphas parameters
  CalibCalorimetry/EcalTrivialCondModules/data/EBAlignment_2010.txt
  CalibCalorimetry/EcalTrivialCondModules/data/EEAlignment_2010.txt
  CalibCalorimetry/EcalTrivialCondModules/data/EEMap.txt
  CalibCalorimetry/EcalTrivialCondModules/data/ESAlignment_2010.txt
  CalibCalorimetry/EcalTrivialCondModules/data/ampWeightsAfterGainSwitch_CMS.txt
  CalibCalorimetry/EcalTrivialCondModules/data/ampWeightsAfterGainSwitch_TB.txt
  CalibCalorimetry/EcalTrivialCondModules/data/ampWeightsES
  CalibCalorimetry/EcalTrivialCondModules/data/ampWeightsES_CMS.txt
  CalibCalorimetry/EcalTrivialCondModules/data/ampWeights_CMS.txt
  CalibCalorimetry/EcalTrivialCondModules/data/ampWeights_TB.txt
  CalibCalorimetry/EcalTrivialCondModules/data/barrel_ly.txt
  CalibCalorimetry/EcalTrivialCondModules/data/chi2MatrixAfterGainSwitch_CMS.txt
  CalibCalorimetry/EcalTrivialCondModules/data/chi2MatrixAfterGainSwitch_TB.txt
  CalibCalorimetry/EcalTrivialCondModules/data/chi2Matrix_CMS.txt
  CalibCalorimetry/EcalTrivialCondModules/data/chi2Matrix_TB.txt
  CalibCalorimetry/EcalTrivialCondModules/data/endcap_ly.txt
  CalibCalorimetry/EcalTrivialCondModules/data/pedWeightsAfterGainSwitch_CMS.txt
  CalibCalorimetry/EcalTrivialCondModules/data/pedWeightsAfterGainSwitch_TB.txt
  CalibCalorimetry/EcalTrivialCondModules/data/pedWeights_CMS.txt
  CalibCalorimetry/EcalTrivialCondModules/data/pedWeights_TB.txt
  CalibCalorimetry/EcalTrivialCondModules/data/timeWeightsAfterGainSwitch_CMS.txt
  CalibCalorimetry/EcalTrivialCondModules/data/timeWeightsAfterGainSwitch_TB.txt
  CalibCalorimetry/EcalTrivialCondModules/data/timeWeights_CMS.txt
  CalibCalorimetry/EcalTrivialCondModules/data/timeWeights_TB.txt
  CalibCalorimetry/EcalTrivialCondModules/interface/EcalTrivialConditionRetriever.h
  CalibCalorimetry/EcalTrivialCondModules/python/EcalTrivialCondRetriever_cfi.py
  CalibCalorimetry/EcalTrivialCondModules/src/EcalTrivialConditionRetriever.cc
  CalibCalorimetry/EcalTrivialCondModules/src/EcalTrivialObjectAnalyzer.cc
  CondTools/Ecal/test/alpha/create_alpha_trivial_byLaser_v6.py
Labels: alca-pending, code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, requires-external, tests-approved

#26688 Rename UP19 to UP21 in matrix workflows and introduce phase1_2021_cosmics key
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26708 DataFormats/SiPixelDetId: fix for undefined unordered_map when compiling with clang 4.0.1 and macos10.9.X SDK under Conda
  DataFormats/SiPixelDetId/src/ES_PixelFEDChannelCollectionMap.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26730 Utilities/General: Replace invalid XML characters in test/BuildFile.xml
  Utilities/General/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26739 PPS: bugfix in proton reconstruction.
  CalibPPS/ESProducers/plugins/CTPPSInterpolatedOpticalFunctionsESSource.cc
  RecoCTPPS/ProtonReconstruction/plugins/CTPPSProtonProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26072 Updated json for DeepCSV Phase 2 model
  RecoBTag/Combined/python/pfDeepCSVJetTags_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-rejected, upgrade-approved

#26537 Bump TObject versions for ROOT master
  DQMServices/Components/test/testSchemaEvolution.cpp
Labels: code-checks-approved, comparison-available, dqm-pending, orp-approved, pending-signatures, requires-external, tests-rejected

#26703 NanoAOD developments: 190508 version, part 1 for UL
  JetMETCorrections/Type1MET/interface/JetCleanerForType1METT.h
  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
  PhysicsTools/NanoAOD/plugins/CandMCMatchTableProducer.cc
  PhysicsTools/NanoAOD/plugins/EGMSeedGainProducer.cc
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/plugins/GlobalVariablesTableProducer.cc
  PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc
  PhysicsTools/NanoAOD/plugins/LHETablesProducer.cc
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/plugins/VIDNestedWPBitmapProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
  PhysicsTools/NanoAOD/python/ttbarCategorization_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved, xpog-approved

#26757 Run3-sim33 Add one function to be useful in some geometry application
  DataFormats/Math/interface/GeantUnits.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26762 Fix for CondCore/CondDB unit tests
  CondCore/CondDB/test/testConditionDatabase_0.cpp
  CondCore/CondDB/test/testConditionDatabase_1.cpp
  CondCore/CondDB/test/testConditionDatabase_2.cpp
  CondCore/CondDB/test/testGroupSelection.cpp
  CondCore/CondDB/test/testPayloadProxy.cpp
  CondCore/CondDB/test/testReadWritePayloads.cpp
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26764 Update the RelMon blacklist file for histos in DT/Run summary/EventInfo/DCSContents with Nans
  Utilities/RelMon/data/blacklist.txt
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26735 fixing the lost tracks quality assignment
  PhysicsTools/PatAlgos/plugins/PATLostTracks.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#26645 [HeaderCheck][FastSim] FastSimulation/Utilities
  FastSimulation/Utilities/interface/RandomEngine.h
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#26666 [HeaderCheck][ANALYSIS] Cleanup headers to avoid header inconsistency errors
  ElectroWeakAnalysis/ZMuMu/BuildFile.xml
  ElectroWeakAnalysis/ZMuMu/interface/SmoothStepFunction.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuMuBack.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuMuBackNorm.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuMuFunction.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuMuNormalBack.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuMuScaledFunction.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuStandaloneFunction.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuStandaloneScaledFunction.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuTrackFunction.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuTrackScaledFunction.h
  ElectroWeakAnalysis/ZMuMu/interface/ZMuTrackScaledNormalBack.h
  ElectroWeakAnalysis/ZMuMu/src/ZMuMuBack.cc
  ElectroWeakAnalysis/ZMuMu/src/ZMuMuBackNorm.cc
  ElectroWeakAnalysis/ZMuMu/src/ZMuMuFunction.cc
  ElectroWeakAnalysis/ZMuMu/src/ZMuMuNormalBack.cc
  ElectroWeakAnalysis/ZMuMu/src/ZMuMuScaledFunction.cc
  ElectroWeakAnalysis/ZMuMu/src/ZMuStandaloneFunction.cc
  ElectroWeakAnalysis/ZMuMu/src/ZMuStandaloneScaledFunction.cc
  ElectroWeakAnalysis/ZMuMu/src/ZMuTrackFunction.cc
  ElectroWeakAnalysis/ZMuMu/src/ZMuTrackScaledFunction.cc
  ElectroWeakAnalysis/ZMuMu/src/ZMuTrackScaledNormalBack.cc
  PhysicsTools/HepMCCandAlgos/interface/MCTruthCompositeMatcher.h
  PhysicsTools/IsolationAlgos/interface/CalIsolationNoExtrapol.h
  PhysicsTools/IsolationUtils/interface/CalIsolationAlgoNoExp.h
  PhysicsTools/IsolationUtils/interface/TauConeIsolationAlgo.h
  PhysicsTools/UtilAlgos/interface/AdHocNTupler.h
  PhysicsTools/UtilAlgos/interface/NullPostProcessor.h
  PhysicsTools/UtilAlgos/interface/StoreManagerTrait.h
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26685 Modernized Geometry/CmsTrackerDetIdBuilder
  Geometry/TrackerNumberingBuilder/plugins/CmsTrackerDetIdBuilder.cc
  Geometry/TrackerNumberingBuilder/plugins/CmsTrackerDetIdBuilder.h
  Geometry/TrackerNumberingBuilder/plugins/CondDBCmsTrackerConstruction.cc
  Geometry/TrackerNumberingBuilder/plugins/CondDBCmsTrackerConstruction.h
  Geometry/TrackerNumberingBuilder/plugins/DDDCmsTrackerContruction.cc
  Geometry/TrackerNumberingBuilder/plugins/DDDCmsTrackerContruction.h
  Geometry/TrackerNumberingBuilder/plugins/TrackerGeometricDetESModule.cc
  Geometry/TrackerNumberingBuilder/plugins/TrackerGeometricDetESModule.h
  Geometry/TrackerNumberingBuilder/plugins/TrackerGeometricDetExtraESModule.cc
  Geometry/TrackerNumberingBuilder/plugins/TrackerGeometricDetExtraESModule.h
  Geometry/TrackerNumberingBuilder/plugins/TrackerTopologyEP.cc
  Geometry/TrackerNumberingBuilder/plugins/TrackerTopologyEP.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26697 [HeaderCheck][Reco] CommonTools/RecoAlgos
  CommonTools/RecoAlgos/interface/PhotonSelector.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26705 Added consumes calls to RPCGeometryESModule
  Geometry/RPCGeometryBuilder/plugins/RPCGeometryESModule.cc
  Geometry/RPCGeometryBuilder/plugins/RPCGeometryESModule.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26706 Added EventSetup consumes calls to MuonNumberingESProducer
  Geometry/MuonNumbering/plugins/MuonNumberingESProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26707 Migrate Geometry/HcalEventSetup to EventSetup consumes
  Geometry/HcalEventSetup/interface/CaloTowerTopologyEP.h
  Geometry/HcalEventSetup/interface/HcalAlignmentEP.h
  Geometry/HcalEventSetup/interface/HcalDDDGeometryEP.h
  Geometry/HcalEventSetup/interface/HcalHardcodeGeometryEP.h
  Geometry/HcalEventSetup/interface/HcalTopologyIdealEP.h
  Geometry/HcalEventSetup/src/CaloTowerHardcodeGeometryEP.cc
  Geometry/HcalEventSetup/src/CaloTowerHardcodeGeometryEP.h
  Geometry/HcalEventSetup/src/CaloTowerTopologyEP.cc
  Geometry/HcalEventSetup/src/HcalAlignmentEP.cc
  Geometry/HcalEventSetup/src/HcalDDDGeometryEP.cc
  Geometry/HcalEventSetup/src/HcalHardcodeGeometryEP.cc
  Geometry/HcalEventSetup/src/HcalTopologyIdealEP.cc
  Geometry/HcalEventSetup/test/HcalDDDGeometryAnalyzer.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26733 Migrate HcalTrigTowerGeometryESProducer to EventSetup consumes
  Geometry/HcalTowerAlgo/plugins/HcalTrigTowerGeometryESProducer.cc
  Geometry/HcalTowerAlgo/plugins/HcalTrigTowerGeometryESProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26734 Modernized ES modules in Geometry/MTDNumberingBuilder
  Geometry/MTDNumberingBuilder/plugins/CondDBCmsMTDConstruction.cc
  Geometry/MTDNumberingBuilder/plugins/CondDBCmsMTDConstruction.h
  Geometry/MTDNumberingBuilder/plugins/DDDCmsMTDConstruction.cc
  Geometry/MTDNumberingBuilder/plugins/DDDCmsMTDConstruction.h
  Geometry/MTDNumberingBuilder/plugins/MTDGeometricTimingDetESModule.cc
  Geometry/MTDNumberingBuilder/plugins/MTDGeometricTimingDetESModule.h
  Geometry/MTDNumberingBuilder/plugins/MTDGeometricTimingDetExtraESModule.cc
  Geometry/MTDNumberingBuilder/plugins/MTDGeometricTimingDetExtraESModule.h
  Geometry/MTDNumberingBuilder/plugins/MTDTopologyEP.cc
  Geometry/MTDNumberingBuilder/plugins/MTDTopologyEP.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26736 Modernized EventSetup modules in Geometry/MTDGeometryBuilder
  Geometry/MTDGeometryBuilder/plugins/MTDDigiGeometryESModule.cc
  Geometry/MTDGeometryBuilder/plugins/MTDDigiGeometryESModule.h
  Geometry/MTDGeometryBuilder/plugins/MTDParametersESModule.cc
  Geometry/MTDGeometryBuilder/plugins/MTDParametersESModule.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26700 MTV : adjust impact parameter selection
  Validation/RecoTrack/python/GenParticleSelectionsForEfficiency_cff.py
  Validation/RecoTrack/python/MultiTrackValidatorGenPs_cfi.py
  Validation/RecoTrack/python/TrackingParticleSelectionsForEfficiency_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26571 Migrate Geometry/CaloEventSetup to EventSetup consumes
  CondTools/Geometry/plugins/calowriters.cc
  Geometry/CaloEventSetup/interface/CaloGeometryDBEP.h
  Geometry/CaloEventSetup/interface/CaloGeometryDBReader.h
  Geometry/CaloEventSetup/interface/CaloGeometryDBWriter.h
  Geometry/CaloEventSetup/interface/CaloGeometryEP.h
  Geometry/CaloEventSetup/plugins/CaloGeometryBuilder.cc
  Geometry/CaloEventSetup/plugins/CaloGeometryBuilder.h
  Geometry/CaloEventSetup/plugins/CaloTopologyBuilder.cc
  Geometry/CaloEventSetup/plugins/CaloTopologyBuilder.h
  Geometry/CaloEventSetup/plugins/CaloTowerConstituentsMapBuilder.cc
  Geometry/CaloEventSetup/plugins/CaloTowerConstituentsMapBuilder.h
  Geometry/CaloEventSetup/plugins/EcalTrigTowerConstituentsMapBuilder.h
  Geometry/CaloEventSetup/plugins/FastTimeTopologyBuilder.cc
  Geometry/CaloEventSetup/plugins/HGCalTopologyBuilder.cc
  Geometry/CaloEventSetup/test/CaloAlignmentRcdRead.cc
  Geometry/CaloEventSetup/test/CaloAlignmentRcdWrite.cc
  Geometry/CaloEventSetup/test/CaloGeometryAnalyzer.cc
  Geometry/CaloEventSetup/test/DumpEcalTrigTowerMapping.cc
  Geometry/CaloEventSetup/test/TestEcalGetWindow.cc
  Geometry/HGCalGeometry/interface/CaloGeometryDBHGCal.h
  Geometry/HGCalGeometry/plugins/moduleDB.cc
  Geometry/HcalEventSetup/src/moduleDB.cc
  Geometry/HcalTowerAlgo/interface/CaloGeometryDBCaloTower.h
  Geometry/HcalTowerAlgo/interface/CaloGeometryDBHcal.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26641 [HeaderCheck][ALCA][DB] Cleanup headers to avoid header inconsistency errors
  CondCore/PopCon/interface/VerifyState.h
  CondFormats/Calibration/interface/EfficiencyPayloads.h
  CondFormats/DTObjects/interface/DTCompactMapAbstractHandler.h
  CondFormats/DTObjects/interface/DTConfigAbstractHandler.h
  CondFormats/GeometryObjects/interface/GeometryFile.h
  CondFormats/SiPixelObjects/interface/SerializationManual.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26737 Added additional TimerServices plots to a blacklist
  DQMServices/FileIO/scripts/blacklist.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26770 move header in private directory
  DataFormats/GeometrySurface/interface/TkRotation.h
  DataFormats/GeometrySurface/interface/private/extTkRotation.h
  DataFormats/GeometrySurface/interface/private/newTkRotation.h
  DataFormats/GeometrySurface/interface/private/oldTkRotation.h
  DataFormats/GeometrySurface/interface/private/sseTkRotation.h
  DataFormats/GeometryVector/interface/Basic2DVector.h
  DataFormats/GeometryVector/interface/Basic3DVector.h
  DataFormats/GeometryVector/interface/private/Basic3DVectorLD.h
  DataFormats/GeometryVector/interface/private/extBasic2DVector.h
  DataFormats/GeometryVector/interface/private/extBasic3DVector.h
  DataFormats/GeometryVector/interface/private/oldBasic2DVector.h
  DataFormats/GeometryVector/interface/private/oldBasic3DVector.h
  DataFormats/GeometryVector/interface/private/sseBasic2DVector.h
  DataFormats/GeometryVector/interface/private/sseBasic3DVector.h
  DataFormats/Math/interface/SSEVec.h
  DataFormats/Math/interface/private/AVXVec.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#26775 [BuildFile] Added explicit dependencies
  DataFormats/TrajectoryState/BuildFile.xml
  FWCore/MessageLogger/BuildFile.xml
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26774 TkAl: Improving job output copying + error reporting
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_check.py
  Alignment/MillePedeAlignmentAlgorithm/templates/mps_runMille_template.sh
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26772 Fixes for code rule violations in Validation/RecoB and HLTriggerOffline/SUSYBSM
  HLTriggerOffline/SUSYBSM/src/SUSY_HLT_SingleLepton.cc
  Validation/RecoB/plugins/BDHadronTrackMonitoringAnalyzer.cc
  Validation/RecoB/plugins/BDHadronTrackMonitoringAnalyzer.h
  Validation/RecoB/plugins/BDHadronTrackMonitoringHarvester.cc
  Validation/RecoB/plugins/BDHadronTrackMonitoringHarvester.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26765 cleanup: use LocalError.h directly from GeometrySurface instead of indirectly via GeometryCommonDetAlgo
  Alignment/APEEstimation/plugins/ApeEstimator.cc
  Alignment/CommonAlignment/src/Alignable.cc
  DataFormats/GeometryCommonDetAlgo/interface/ErrorFrameTransformer.h
  DataFormats/GeometryCommonDetAlgo/interface/LocalError.h
  Geometry/CommonDetUnit/interface/MuonGeomDet.h
  Geometry/CommonTopologies/interface/Topology.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#26486 Adapting VID & Nano to the new E/gamma UL format + adding HEEP V7.1
  EgammaAnalysis/ElectronTools/test/id_validation/runEleIDTest_CSA14_sc1.py
  EgammaAnalysis/ElectronTools/test/id_validation/runEleIDTest_CSA14_sc1_miniAOD.py
  EgammaAnalysis/ElectronTools/test/id_validation/runEleIDTest_CSA14_sc2.py
  EgammaAnalysis/ElectronTools/test/id_validation/validateWP_Scenario1.C
  EgammaAnalysis/ElectronTools/test/id_validation/validateWP_Scenario2.C
  PhysicsTools/NanoAOD/plugins/IsoValueMapProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoEgamma/EgammaTools/interface/EleEnergyRetriever.h
  RecoEgamma/EgammaTools/plugins/EG9X105XObjectUpdateModifier.cc
  RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py
  RecoEgamma/EgammaTools/src/MVAVariableHelper.cc
  RecoEgamma/ElectronIdentification/data/ElectronIDVariables.txt
  RecoEgamma/ElectronIdentification/data/ElectronMVAEstimatorRun2Fall17V1Variables.txt
  RecoEgamma/ElectronIdentification/data/ElectronMVAEstimatorRun2Variables.txt
  RecoEgamma/ElectronIdentification/interface/EBEECutValues.h
  RecoEgamma/ElectronIdentification/interface/ElectronMVAEstimatorRun2.h
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleEmHadD1IsoRhoCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleMinEcalEtCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleTrkPtIsoCut.cc
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_tools.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_HEEPV50_CSA14_25ns_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_HEEPV50_CSA14_startup_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_HEEPV50_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_HEEPV71_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_tools.py
  RecoEgamma/PhotonIdentification/data/PhotonMVAEstimatorRun2VariablesFall17V1p1.txt
  RecoEgamma/PhotonIdentification/data/PhotonMVAEstimatorRun2VariablesSpring16.txt
  RecoEgamma/PhotonIdentification/plugins/cuts/PhoGenericRhoPtScaledCut.cc
  RecoEgamma/PhotonIdentification/python/Identification/cutBasedPhotonID_tools.py
  RecoEgamma/PhotonIdentification/python/PhotonMVAValueMapProducer_cfi.py
  RecoEgamma/PhotonIdentification/python/egmPhotonIDs_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#26759 Run3-hcx198 Put protections in validation codes
  Validation/HcalHits/src/HcalSimHitStudy.cc
  Validation/HcalHits/src/HcalSimHitsValidation.cc
  Validation/HcalHits/src/SimG4HcalValidation.cc
  Validation/HcalHits/src/SimHitsValidationHcal.cc
  Validation/HcalHits/src/ZdcSimHitStudy.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26555 Initial PPS Simulation Geometry PR
  Configuration/Geometry/python/GeometryExtended2016_CTPPS_cff.py
  Configuration/Geometry/python/GeometryExtended2017_CTPPS_cff.py
  Configuration/Geometry/python/GeometryExtended2018_CTPPS_cff.py
  Geometry/CMSCommonData/data/cmsextent/2018/v1/cmsextent.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2016aXML_CTPPS_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2017XML_CTPPS_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2018XML_CTPPS_cfi.py
  Geometry/CMSCommonData/test/DDFilteredViewAnalyzer.cc
  Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_210_Left_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_210_Right_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_220_Left_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_220_Right_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2016/RP_Dist_Beam_Cent.xml
  Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_210_Left_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_210_Right_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_220_Left_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_220_Right_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2017/RP_Dist_Beam_Cent.xml
  Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_210_Left_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_210_Right_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_220_Left_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_220_Right_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2018/RP_Dist_Beam_Cent.xml
  Geometry/VeryForwardData/data/CTPPS_Cuts_Per_Region.xml
  Geometry/VeryForwardData/data/CTPPS_Diamond_Sensitive_Dets_TimingHits.xml
  Geometry/VeryForwardData/data/CTPPS_Stations_Assembly.xml
  Geometry/VeryForwardData/data/CTPPS_UFSD_Sensitive_Dets_TimingHits.xml
  Geometry/VeryForwardGeometry/BuildFile.xml
  Geometry/VeryForwardGeometry/interface/CTPPSPixelSimTopology.h
  Geometry/VeryForwardGeometry/interface/CTPPSPixelTopology.h
  Geometry/VeryForwardGeometry/python/geometryPPS_CMSxz_fromDD_2016_cfi.py
  Geometry/VeryForwardGeometry/python/geometryPPS_CMSxz_fromDD_2017_cfi.py
  Geometry/VeryForwardGeometry/python/geometryPPS_CMSxz_fromDD_2018_cfi.py
  Geometry/VeryForwardGeometry/src/CTPPSPixelSimTopology.cc
  Geometry/VeryForwardGeometry/src/CTPPSPixelTopology.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26763 updating SC reg corrector for UL regression
  RecoEcal/EgammaClusterProducers/python/particleFlowSuperClusterECAL_cfi.py
  RecoEcal/EgammaClusterProducers/src/PFECALSuperClusterProducer.cc
  RecoEgamma/EgammaTools/interface/SCEnergyCorrectorSemiParm.h
  RecoEgamma/EgammaTools/src/SCEnergyCorrectorSemiParm.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26768 Fix logic problems in MuScleFitBase
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFitBase.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#26808 [HeaderCheck][ANA][RECO] Remove obsolete headers
  CommonTools/UtilAlgos/interface/ChargeSelector.h
  CommonTools/UtilAlgos/interface/TFileDirectory.h
  CommonTools/Utils/interface/ChargeSelector.h
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26793 Phase2-hgx196 Handle the current issues of validation
  Validation/HGCalValidation/plugins/HGCalHitCalibration.cc
  Validation/HGCalValidation/plugins/HGCalSimHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalSimHitsClient.cc
  Validation/HGCalValidation/python/hgcalHitCalibration_cfi.py
  Validation/HGCalValidation/test/HGCalDigiStudy.cc
  Validation/HGCalValidation/test/HGCalRecHitStudy.cc
  Validation/HGCalValidation/test/HGCalSimHitStudy.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26761 DQMOffline/Hcal : minimal protection of histo booking&processing
  DQMOffline/Hcal/src/HcalRecHitsAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26320 Add Alignment Records for GEM Geometry
  CondCore/AlignmentPlugins/src/plugin.cc
  CondFormats/AlignmentRecord/interface/GEMAlignmentErrorExtendedRcd.h
  CondFormats/AlignmentRecord/interface/GEMAlignmentErrorRcd.h
  CondFormats/AlignmentRecord/interface/GEMAlignmentRcd.h
  CondFormats/AlignmentRecord/src/GEMAlignmentErrorExtendedRcd.cc
  CondFormats/AlignmentRecord/src/GEMAlignmentErrorRcd.cc
  CondFormats/AlignmentRecord/src/GEMAlignmentRcd.cc
  Geometry/GEMGeometry/interface/GEMGeometry.h
  Geometry/GEMGeometryBuilder/plugins/BuildFile.xml
  Geometry/GEMGeometryBuilder/plugins/GEMGeometryESModule.cc
  Geometry/GEMGeometryBuilder/plugins/GEMGeometryESModule.h
  Geometry/GEMGeometryBuilder/python/gemGeometryDB_cfi.py
  Geometry/GEMGeometryBuilder/python/gemGeometry_cfi.py
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromCondDB.cc
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromDDD.cc
  Geometry/Records/interface/MuonGeometryRecord.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26740 DD4hep: Material Conversion
  DetectorDescription/DDCMS/data/cms-2015-muon-geometry.xml
  DetectorDescription/DDCMS/plugins/DDDefinitions2Objects.cc
  SimG4Core/DD4hepGeometry/BuildFile.xml
  SimG4Core/DD4hepGeometry/interface/DD4hep_DDDWorld.h
  SimG4Core/DD4hepGeometry/plugins/BuildFile.xml
  SimG4Core/DD4hepGeometry/plugins/DD4hep_DDTestG4Geometry.cc
  SimG4Core/DD4hepGeometry/plugins/DD4hep_GeometryESProducer.cc
  SimG4Core/DD4hepGeometry/src/DD4hep_DDDWorld.cc
  SimG4Core/DD4hepGeometry/test/python/testG4Geometry.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#26670 DataFormats/ParticleFlowReco - remove unused data formats
  DataFormats/ParticleFlowReco/interface/Calibratable.h
  DataFormats/ParticleFlowReco/interface/CalibrationProvenance.h
  DataFormats/ParticleFlowReco/interface/CalibrationResultWrapper.h
  DataFormats/ParticleFlowReco/interface/CaloBox.h
  DataFormats/ParticleFlowReco/interface/CaloEllipse.h
  DataFormats/ParticleFlowReco/interface/CaloWindow.h
  DataFormats/ParticleFlowReco/src/Calibratable.cc
  DataFormats/ParticleFlowReco/src/CaloBox.cc
  DataFormats/ParticleFlowReco/src/CaloEllipse.cc
  DataFormats/ParticleFlowReco/src/CaloWindow.cc
  DataFormats/ParticleFlowReco/src/classes_1.h
  DataFormats/ParticleFlowReco/src/classes_2.h
  DataFormats/ParticleFlowReco/src/classes_def_2.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26810 [Headers][RECO] Remove unused header
  RecoVertex/LinearizationPointFinders/interface/GenericLinearizationPointFinder.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26782 Run3-hcx200 dump specific collections
  Validation/HcalRecHits/test/BuildFile.xml
  Validation/HcalRecHits/test/HcalDumpHits.cc
  Validation/HcalRecHits/test/runHcalDumpHits_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26684 Updated runPromptReco.py
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/DataProcessing/python/Reco.py
  Configuration/DataProcessing/test/RunPromptReco.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26749 Run3-hcx196 Modify Hcal geometry in view of no HE
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
  Geometry/CaloTopology/interface/HcalTopology.h
  Geometry/CaloTopology/src/HcalTopology.cc
  Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/hcalSimNumbering.xml
  Geometry/HcalCommonData/src/HcalDDDRecConstants.cc
  Geometry/HcalCommonData/src/HcalDDDSimConstants.cc
  Geometry/HcalCommonData/src/HcalParametersFromDD.cc
  Geometry/HcalCommonData/test/HcalRecNumberingTester.cc
  Geometry/HcalCommonData/test/HcalSimNumberingTester.cc
  Geometry/HcalCommonData/test/python/runHcalRecNumberingTester_cfg.py
  Geometry/HcalCommonData/test/python/runHcalSimNumberingTester_cfg.py
  Geometry/HcalTowerAlgo/src/HcalTrigTowerGeometry.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26778 DyT v2 on up to eta 1p2
  RecoMuon/GlobalTrackingTools/plugins/GlobalTrackQualityProducer.cc
  RecoMuon/GlobalTrackingTools/python/GlobalMuonRefitter_cff.py
  RecoMuon/GlobalTrackingTools/python/GlobalTrajectoryBuilderCommon_cff.py
  RecoMuon/GlobalTrackingTools/src/DynamicTruncation.cc
  RecoMuon/L3MuonProducer/src/L3MuonProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#26785 Update triggers for Run2 monopole analysis
  Configuration/Skimming/python/PDWG_EXOMONOPOLE_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved

#26802 Tunesetforpythia8vgt235
  Configuration/Generator/python/MCTunes2017/PythiaCP1Settings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP1TuneDownSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP1TuneUpSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP2Settings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP2TuneDownSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP2TuneUpSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP3Settings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP3TuneDownSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP3TuneUpSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP4Settings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP4TuneDownSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP4TuneUpSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP5Settings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP5TuneDownSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP5TuneUpSettings_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26819 Add in cmsDriver LHE and GEN as steps defining the isMC option
  Configuration/Applications/python/cmsDriverOptions.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26683 Run3-alca156 Add studies relevant for tuning tracker cuts to go to forward regions
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/test/HcalIsoTrackAnalysis.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26750 Run2-hcx197 Modify testing of Run3 geometry
  Geometry/HcalCommonData/python/testPhase1GeometryXML_cfi.py
  Geometry/HcalCommonData/python/testPhase2GeometryXML_cfi.py
  Geometry/HcalTowerAlgo/test/HcalGeometryDetIdAnalyzer.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryTester.cc
  Geometry/HcalTowerAlgo/test/runHcalDetIdTester_cfg.py
  Geometry/HcalTowerAlgo/test/runHcalGeometryDetIdAnalyzer_cfg.py
  Geometry/HcalTowerAlgo/test/runHcalGeometryTester_cfg.py
  Validation/HcalHits/BuildFile.xml
  Validation/HcalHits/test/BuildFile.xml
  Validation/HcalHits/test/HcalGeomCheck.cc
  Validation/HcalHits/test/runHcalGeomCheckStep1_cfg.py
  Validation/HcalHits/test/runHcalGeomCheckStep2_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#26766 Run3-hcx199 Add unit tests for Hcal DD algos
  Geometry/HcalAlgo/python/testGeomHB_cfi.py
  Geometry/HcalAlgo/python/testGeomHEPhase0_cfi.py
  Geometry/HcalAlgo/python/testGeomHEPhase1_cfi.py
  Geometry/HcalAlgo/python/testGeomHF_cfi.py
  Geometry/HcalAlgo/python/testGeomHO_cfi.py
  Geometry/HcalAlgo/test/python/dumpHBGeom_cfg.py
  Geometry/HcalAlgo/test/python/dumpHEPhase0Geom_cfg.py
  Geometry/HcalAlgo/test/python/dumpHEPhase1Geom_cfg.py
  Geometry/HcalAlgo/test/python/dumpHFGeom_cfg.py
  Geometry/HcalAlgo/test/python/dumpHOGeom_cfg.py
  Geometry/HcalAlgo/test/runTest.sh
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26788 Run3-hcx202 Neutal density filter kept for HB in Run3
  Geometry/HcalCommonData/data/hcalSimNumbering/2019/hcalSimNumbering.xml
  Geometry/HcalCommonData/data/hcalSimNumbering/2021/hcalSimNumbering.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26540 Devel dqm offline trigger top
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  DQMOffline/Trigger/plugins/TopMonitor.cc
  DQMOffline/Trigger/plugins/TopMonitor.h
  DQMOffline/Trigger/python/TopMonitor_cfi.py
  DQMOffline/Trigger/python/TopMonitoring_Client_cff.py
  DQMOffline/Trigger/python/TopMonitoring_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#26817 ECAL : Use of Extra Package in cms-data
  CalibCalorimetry/EcalTrivialCondModules/src/EcalTrivialConditionRetriever.cc
  CalibCalorimetry/EcalTrivialCondModules/src/EcalTrivialObjectAnalyzer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26807 Changes from scram build code-format-all
  HeterogeneousCore/CUDAServices/plugins/NVProfilerService.cc
  Utilities/General/interface/ClassName.h
  Utilities/General/interface/precomputed_value_sort.h
  Utilities/General/src/ClassName.cc
  Utilities/General/test/test_precomputed_value_sort.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26780 Enforce ESInputTag label separation
  DetectorDescription/DDCMS/plugins/DDCMSDetector.cc
  DetectorDescription/DDCMS/plugins/DDTestDumpFile.cc
  DetectorDescription/DDCMS/plugins/DDTestDumpGeometry.cc
  DetectorDescription/DDCMS/plugins/DDTestNavigateGeometry.cc
  DetectorDescription/DDCMS/plugins/DDTestSpecPars.cc
  DetectorDescription/DDCMS/plugins/DDTestSpecParsFilter.cc
  DetectorDescription/DDCMS/plugins/DDTestVectors.cc
  DetectorDescription/DDCMS/test/python/dump.py
  DetectorDescription/DDCMS/test/python/dumpMuonGeometry.py
  DetectorDescription/DDCMS/test/python/testDDAngularAlgorithm.py
  DetectorDescription/DDCMS/test/python/testDDDetectorESProducer.py
  DetectorDescription/DDCMS/test/python/testDDHGCalCellAlgorithm.py
  DetectorDescription/DDCMS/test/python/testDDSpecPars.py
  DetectorDescription/DDCMS/test/python/testDDSpecParsFilter.py
  DetectorDescription/DDCMS/test/python/testDDSpecParsFilterG4ProdCuts.py
  DetectorDescription/DDCMS/test/python/testDDTIDAxialCableAlgorithm.py
  DetectorDescription/DDCMS/test/python/testDDVectors.py
  DetectorDescription/DDCMS/test/python/testMFGeometry.py
  DetectorDescription/DDCMS/test/python/testMuonGeometry.py
  DetectorDescription/DDCMS/test/python/testNavigateGeometry.py
  DetectorDescription/DDCMS/test/python/testShapes.py
  DetectorDescription/DDCMS/test/python/testTGeoIterator.py
  FWCore/ParameterSet/python/Types.py
  FWCore/ParameterSet/src/types.cc
  FWCore/ParameterSet/test/ps_t.cppunit.cc
  FWCore/PyDevParameterSet/test/makepset_t.cppunit.cc
  FWCore/PythonParameterSet/test/makepset_t.cppunit.cc
  FWCore/Utilities/src/ESInputTag.cc
  FWCore/Utilities/test/esinputtag.cppunit.cpp
  Geometry/DTGeometryBuilder/test/python/testDTGeometry.py
  Geometry/DTGeometryBuilder/test/python/testDTGeometryAndDump.py
  Geometry/DTGeometryBuilder/test/python/validateDTGeometry_cfg.py
  Geometry/EcalAlgo/test/python/testEcalGeometry.py
  Geometry/MTDGeometryBuilder/test/python/testMTDGeometry.py
  Geometry/TrackerGeometryBuilder/test/python/testTrackerGeometry.py
  RecoBTag/CTagging/python/charmTagsComputerCvsL_cfi.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, geometry-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#26809 [Header][GEO] added the needed includes
  Geometry/HGCalGeometry/interface/CaloGeometryDBHGCal.h
  Geometry/HcalTowerAlgo/interface/CaloGeometryDBCaloTower.h
  Geometry/HcalTowerAlgo/interface/CaloGeometryDBHcal.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26828 updating GT and BeamSpot for 2021 relvals
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26829 cleanup of some static analyzer issues in isolation-related code
  CommonTools/ParticleFlow/plugins/PFCandIsolatorFromDeposit.cc
  DataFormats/RecoCandidate/interface/IsoDeposit.h
  PhysicsTools/IsolationAlgos/plugins/CandIsolatorFromDeposits.cc
  PhysicsTools/IsolationAlgos/plugins/CandViewExtractor.icc
  PhysicsTools/IsolationAlgos/src/IsoDepositVetoFactory.cc
  PhysicsTools/PatAlgos/src/IsoDepositIsolator.cc
  RecoMuon/MuonIsolation/src/NominalEfficiencyThresholds.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved
