Repository cms-sw/cmssw, pull requests merged in 2019-03, with the labels that each got.

#26006 Removed incorrect virtual functions in DQMOffline/L1Trigger
  DQMOffline/L1Trigger/interface/L1TDiffHarvesting.h
  DQMOffline/L1Trigger/interface/L1TEfficiencyHarvesting.h
  DQMOffline/L1Trigger/src/L1TDiffHarvesting.cc
  DQMOffline/L1Trigger/src/L1TEfficiencyHarvesting.cc
Labels: code-checks-approved, comparison-available, dqm-approved, l1-pending, orp-approved, pending-signatures, tests-approved

#25858 DB usage for Totem/PPS timing local reconstruction
  RecoCTPPS/TotemRPLocal/BuildFile.xml
  RecoCTPPS/TotemRPLocal/interface/TotemTimingConversions.h
  RecoCTPPS/TotemRPLocal/interface/TotemTimingParser.h
  RecoCTPPS/TotemRPLocal/interface/TotemTimingRecHitProducerAlgorithm.h
  RecoCTPPS/TotemRPLocal/plugins/BuildFile.xml
  RecoCTPPS/TotemRPLocal/plugins/TotemTimingRecHitProducer.cc
  RecoCTPPS/TotemRPLocal/src/TotemTimingConversions.cc
  RecoCTPPS/TotemRPLocal/src/TotemTimingParser.cc
  RecoCTPPS/TotemRPLocal/src/TotemTimingRecHitProducerAlgorithm.cc
  RecoCTPPS/TotemRPLocal/test/totemTiming_reco_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26030 Add options to bypassVersionCheck in Merge step
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26034 Phase2-hgx180 Make some of the validation jobs more silent
  Validation/HGCalValidation/plugins/HGCGeometryValidation.cc
  Validation/HGCalValidation/plugins/HGCalDigiValidation.cc
  Validation/HGCalValidation/plugins/HGCalRecHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalSimHitValidation.cc
  Validation/HGCalValidation/plugins/SimG4HGCalValidation.cc
  Validation/HGCalValidation/python/hgcGeometryValidationV6_cfi.py
  Validation/HGCalValidation/python/hgcGeometryValidationV9_cfi.py
  Validation/HGCalValidation/python/hgcGeometryValidation_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26025 FWCore/ParameterSet changes for python3 compatibility
  FWCore/ParameterSet/python/Config.py
  FWCore/ParameterSet/python/DictTypes.py
  FWCore/ParameterSet/python/Mixins.py
  FWCore/ParameterSet/python/SequenceTypes.py
  FWCore/ParameterSet/python/Types.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26024 add DQMEventInfo to SiPixelQuality PCL workflow
  CalibTracker/SiPixelQuality/python/DQMEventInfoSiPixelQuality_cff.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26027 use auto:run2_data_promptlike_hi in RECOHID18 instead of a hardcoded GT
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26023 Run2-sim30 Try to remove dependency of Reco geometry for CaloSteppingAction
  Geometry/HcalCommonData/src/HcalGeomParameters.cc
  Geometry/HcalCommonData/src/HcalNumberingFromDDD.cc
  SimG4CMS/Calo/interface/CaloSteppingAction.h
  SimG4CMS/Calo/interface/HcalNumberingFromPS.h
  SimG4CMS/Calo/src/CaloSteppingAction.cc
  SimG4CMS/Calo/src/HcalNumberingFromPS.cc
  SimG4CMS/Calo/test/python/calostep_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#26047 fix long-standing typo, python3 compatible syntax for running python files
  FWCore/ParameterSet/python/DictTypes.py
  FWCore/PyDevParameterSet/src/MakePyBind11ParameterSets.cc
  FWCore/PyDevParameterSet/src/PyBind11ProcessDesc.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25633 Some EcalClusterTools maintainance and energy matrix in Egamma MVA Ntuplizers
  RecoCaloTools/Navigation/interface/CaloRectangle.h
  RecoEcal/EgammaClusterProducers/src/EcalDigiSelector.cc
  RecoEcal/EgammaCoreTools/interface/EcalClusterLazyTools.h
  RecoEcal/EgammaCoreTools/interface/EcalClusterTools.h
  RecoEcal/EgammaCoreTools/src/EcalClusterLazyTools.cc
  RecoEcal/EgammaCoreTools/test/testEcalClusterLazyTools.cc
  RecoEcal/EgammaCoreTools/test/testEcalClusterLazyTools.py
  RecoEcal/EgammaCoreTools/test/testEcalClusterTools.cc
  RecoEcal/EgammaCoreTools/test/testEcalClusterTools.py
  RecoEgamma/ElectronIdentification/plugins/ElectronMVANtuplizer.cc
  RecoEgamma/ElectronIdentification/test/testElectronMVA_cfg.py
  RecoEgamma/PhotonIdentification/plugins/PhotonIDValueMapProducer.cc
  RecoEgamma/PhotonIdentification/plugins/PhotonMVANtuplizer.cc
  RecoEgamma/PhotonIdentification/test/testPhotonMVA_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26031 Added links from LowPtGsf to PackedCandidates and LostTracks in MiniAOD
  PhysicsTools/PatAlgos/plugins/LowPtGSFToPackedCandidateLinker.cc
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/lowPtGsfLinks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26052 Avoid race condition in WaitingTaskList cache
  FWCore/Concurrency/src/WaitingTaskList.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26033 Continue GsfElectronAlgo refactoring
  RecoEgamma/EgammaElectronAlgos/interface/GsfElectronAlgo.h
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc
  RecoEgamma/EgammaElectronProducers/plugins/GEDGsfElectronProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/GEDGsfElectronProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronBaseProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronBaseProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronEcalDrivenProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26048 Added monopole ionisation classes
  SimG4Core/PhysicsLists/interface/CMSmplIonisation.h
  SimG4Core/PhysicsLists/interface/CMSmplIonisationWithDeltaModel.h
  SimG4Core/PhysicsLists/src/CMSMonopolePhysics.cc
  SimG4Core/PhysicsLists/src/CMSmplIonisation.cc
  SimG4Core/PhysicsLists/src/CMSmplIonisationWithDeltaModel.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26040 Another pybind11 fix for setting argv correctly in python session from cmsRun
  FWCore/PyDevParameterSet/src/PyBind11ProcessDesc.cc
  FWCore/PyDevParameterSet/src/PyBind11Wrapper.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26020 Cleanups in TrackingTools/GsfTools
  TrackingTools/GsfTools/BuildFile.xml
  TrackingTools/GsfTools/interface/CloseComponentsMerger.icc
  TrackingTools/GsfTools/interface/GaussianStateLessWeight.h
  TrackingTools/GsfTools/interface/MultiGaussianState.h
  TrackingTools/GsfTools/interface/MultiGaussianState.icc
  TrackingTools/GsfTools/interface/MultiGaussianStateCombiner.h
  TrackingTools/GsfTools/interface/SingleGaussianState1D.h
  TrackingTools/GsfTools/plugins/CloseComponentsMergerESProducer.h
  TrackingTools/GsfTools/plugins/DistanceBetweenComponentsESProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26035 Add B parking test workflows
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26036 10.2.X Added links from LowPtGsf to PackedCandidates and LostTracks in MiniAOD
  PhysicsTools/PatAlgos/plugins/LowPtGSFToPackedCandidateLinker.cc
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/lowPtGsfLinks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
Labels: analysis-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26059 [10.6.X] typo: fix unit test.
  Alignment/TrackerAlignment/test/pixelPositions.sh
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26038 Add relval for b parking skim 102x
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/Skimming/BuildFile.xml
  Configuration/Skimming/interface/LeptonSkimming.h
  Configuration/Skimming/python/Skims_PDWG_cff.py
  Configuration/Skimming/python/pwdgSkimBPark_cfi.py
  Configuration/Skimming/src/LeptonSkimming.cc
Labels: comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26044 backport bypassVersionCheck in Merge step to 80X
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26045 backport bypassVersionCheck in Merge step to 94X
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26051 MultiTrajectoryStateMode from class to namespace
  RecoEgamma/EgammaElectronAlgos/interface/GsfElectronAlgo.h
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc
  RecoEgamma/EgammaHLTAlgos/interface/EgammaHLTPixelMatchElectronAlgo.h
  RecoEgamma/EgammaHLTAlgos/src/EgammaHLTPixelMatchElectronAlgo.cc
  RecoEgamma/EgammaHLTProducers/interface/EgammaHLTGsfTrackVarProducer.h
  RecoEgamma/EgammaHLTProducers/src/EgammaHLTGsfTrackVarProducer.cc
  RecoParticleFlow/PFTracking/interface/PFElecTkProducer.h
  RecoParticleFlow/PFTracking/interface/PFTrackTransformer.h
  RecoParticleFlow/PFTracking/plugins/PFElecTkProducer.cc
  RecoParticleFlow/PFTracking/src/PFTrackTransformer.cc
  RecoTracker/TrackProducer/src/GsfTrackProducerBase.cc
  TrackingTools/GsfTools/interface/MultiTrajectoryStateMode.h
  TrackingTools/GsfTools/src/MultiTrajectoryStateMode.cc
  TrackingTools/GsfTools/src/MultiTrajectoryStateTransform.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#26060 [10.6.X] fix unit test to run if directly run from cmssw release area.
  CondTools/Geometry/test/test-data-file-deletion.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26057 [10.6.X] Python2to3 fixes
  Alignment/OfflineValidation/python/TkAlAllInOneTool/betterConfigParser.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTracker/IterativeTracking/python/customise_MVAPhase1_cfi.py
  SimPPS/PPSSimTrackProducer/python/SimTrackProducerForFastSim_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#26068 Fix gcc8 cuda warnings
  DataFormats/Math/test/cudaAtan2Test.cu
  DataFormats/Math/test/cudaMathTest.cu
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26058 Fix: FWHGCRecHitProxyBuilder
  Fireworks/Calo/plugins/FWHGCRecHitProxyBuilder.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#25992 Ecal : PayloadInspector for EcalSimPulseShape
  CondCore/EcalPlugins/plugins/BuildFile.xml
  CondCore/EcalPlugins/plugins/EcalSimPulseShape_PayloadInspector.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26041 add BeamSpotRcdPrinter utility
  CondTools/BeamSpot/plugins/BeamSpotRcdPrinter.cc
  CondTools/BeamSpot/plugins/BuildFile.xml
  CondTools/BeamSpot/test/BeamSpotRcdPrinter_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26046 Default data set for D35
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-pending, orp-approved, pdmv-pending, pending-signatures, tests-started, upgrade-pending

#26077 Restore no delta ray option for monopole ionisation
  SimG4Core/PhysicsLists/src/CMSMonopolePhysics.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#19166 add possibility of using getPU_NumInteractions
  PhysicsTools/Utilities/plugins/PileUpFilter.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26037 add template classes for BeamSpot PaylaodInspector (vs run,time,history)
  CondCore/BeamSpotPlugins/plugins/BeamSpot_PayloadInspector.cc
  CondCore/BeamSpotPlugins/test/testBeamsSpotPayloadInspector.sh
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26067 Store PS weights in 94X
  Configuration/Generator/python/PSweightsPythia/PythiaPSweightsSettings_cfi.py
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25848 added pull_request_template.md
  pull_request_template.md
Labels: alca-approved, analysis-approved, code-checks-approved, comparison-available, core-approved, daq-pending, db-pending, dqm-approved, fastsim-approved, generators-pending, geometry-approved, hlt-pending, l1-pending, orp-approved, pdmv-approved, pending-signatures, reconstruction-pending, simulation-approved, tests-approved, upgrade-approved, visualization-approved, xpog-pending

#26081 RECO sequence python3 compatibility changes
  RecoBTag/TensorFlow/python/pfMassIndependentDeepDoubleXJetTags_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_tools.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26095 changes needed for DDUnits to GeantUnits migration
  SimG4CMS/Calo/src/HcalNumberingFromPS.cc
Labels: code-checks-approved, comparison-pending, orp-approved, pending-signatures, simulation-pending, tests-approved

#26092 Backport fix of monopole ionisation
  SimG4Core/PhysicsLists/interface/CMSmplIonisation.h
  SimG4Core/PhysicsLists/interface/CMSmplIonisationWithDeltaModel.h
  SimG4Core/PhysicsLists/src/CMSMonopolePhysics.cc
  SimG4Core/PhysicsLists/src/CMSmplIonisation.cc
  SimG4Core/PhysicsLists/src/CMSmplIonisationWithDeltaModel.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26073 Switch to using ROOT's Transform3D
  RecoEgamma/EgammaTools/BuildFile.xml
  RecoEgamma/EgammaTools/interface/EgammaPCAHelper.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26042 Add alias for PixelFEDChannelCollection.
  SimGeneral/MixingModule/python/aliases_PreMix_cfi.py
  SimGeneral/MixingModule/python/aliases_cfi.py
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26093 Fixing MultiIso in muon Selector: Removing the double declaration of the variable "miniIsoValue "
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc
Labels: analysis-pending, bug-fix, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26097 retain name of script that is fed to cmsRun in pybind11 interface
  FWCore/PyDevParameterSet/src/PyBind11ProcessDesc.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#25684 Update CSC RU segment builder
  RecoLocalMuon/CSCSegment/python/CSCSegmentAlgorithmRU_cfi.py
  RecoLocalMuon/CSCSegment/src/CSCSegAlgoRU.cc
  RecoLocalMuon/CSCSegment/src/CSCSegAlgoRU.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26049 Update GT for ultra legacy : MC ECAL, GEM eMap, PF calibration
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26074 Backport : Update GT for ultra legacy - MC ECAL, GEM eMap
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26107 Revert "Default data set for D35"
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-pending, pending-signatures, tests-approved, upgrade-pending

#26120 Fix types in Merge.py, and RunMerge.py for missing mergeNANO default
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
Labels: code-checks-approved, comparison-pending, fully-signed, operations-approved, orp-approved, tests-started

#26110 Fix config in Merge.py
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26129 bug fix on Merge.py for 80X
  Configuration/DataProcessing/python/Merge.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26108 Add ParkingBPH skim spec to autoskim.py
  Configuration/Skimming/python/autoSkim.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved

#26122 Herwig7 common configs to make writing easier
  Configuration/Generator/python/Herwig7Settings/Herwig7CommonMergingSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHECommonSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHEMG5aMCatNLOSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHEPowhegSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHESettings_cfi.py
  GeneratorInterface/Herwig7Interface/python/Herwig7_loadCommonMergingSettings_cff.py
  GeneratorInterface/Herwig7Interface/python/Herwig7_loadCommonSettings_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26111 Fix Rivet weights
  GeneratorInterface/RivetInterface/plugins/RivetAnalyzer.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26053 Fix excessive stack use when storing HepMCProduct
  SimDataFormats/GeneratorProducts/src/classes.h
  SimDataFormats/GeneratorProducts/src/classes_def.xml
  SimDataFormats/GeneratorProducts/src/hepmc_rootio.cc
  SimDataFormats/GeneratorProducts/test/BuildFile.xml
  SimDataFormats/GeneratorProducts/test/rootio_t.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26021 Store HCAL RecHits for volumes crossed by muon trajectory
  DataFormats/MuonReco/interface/MuonEnergy.h
  DataFormats/MuonReco/src/classes_def.xml
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.cc
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.h
  RecoMuon/MuonIdentification/python/muons1stStep_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26101 Added missing include of memory to Herwig6Instance
  GeneratorInterface/Herwig6Interface/interface/Herwig6Instance.h
Labels: code-checks-approved, comparison-pending, fully-signed, generators-approved, orp-approved, tests-approved

#26069 Adding emplace_back method to edm::DetSet
  DataFormats/Common/interface/DetSet.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26113 Fix clang warnings in Calibration
  DataFormats/HcalCalibObjects/interface/HOCalibVariables.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26039 Backports all needs for runTheMatrix to 80X
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26137 Protect against accessing nullptr in MessageSender
  FWCore/MessageLogger/src/MessageSender.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26054 HCAL M0 timing update/cleanup
  RecoLocalCalo/HcalRecAlgos/src/SimpleHBHEPhase1Algo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26078 Phase2-hgx181 First step of making v10 HGCal geometry
  Geometry/CMSCommonData/data/caloBase/2023/v2/caloBase.xml
  Geometry/CMSCommonData/data/cms/2023/v2/cms.xml
  Geometry/EcalCommonData/data/PhaseII/v2/ectkcable.xml
  Geometry/EcalCommonData/data/PhaseII/v2/ectkcablemat.xml
  Geometry/EcalCommonData/data/PhaseII/v2/eregalgo.xml
  Geometry/HGCalCommonData/data/hgcal/v10/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalCons/v10/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalEE/v10/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalEE/v9/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalEE/v9a/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v10/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v9/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v9a/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v10/hgcalHEsil.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v9/hgcalHEsil.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v9a/hgcalHEsil.xml
  Geometry/HGCalCommonData/interface/HGCalGeomTools.h
  Geometry/HGCalCommonData/plugins/DDHGCalEEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalEEAlgo.h
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.h
  Geometry/HGCalCommonData/python/testHGCV10XML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalV10XML_cfi.py
  Geometry/HGCalCommonData/src/HGCalGeomTools.cc
  Geometry/HGCalCommonData/test/dumpHGCalGeometry_cfg.py
  Geometry/HcalCommonData/data/hcal/v2/hcalalgo.xml
  Geometry/HcalCommonData/data/hcalcablealgo/v1/hcalcablealgo.xml
  Geometry/HcalCommonData/data/hcalcablealgo/v2/hcalcablealgo.xml
  SimG4CMS/Calo/test/python/runHGC4_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#26112 Fix clang warnings in Calibration
  Calibration/EcalAlCaRecoProducers/plugins/AlCaECALRecHitReducer.cc
  Calibration/HcalCalibAlgos/test/HcalCorrPFCalculation.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26070 Removed inclusion of Transform3DPJ from HGCalTriggerNtupleGen
  L1Trigger/L1THGCal/plugins/BuildFile.xml
  L1Trigger/L1THGCal/plugins/ntuples/HGCalTriggerNtupleGen.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#26032 Introduce SiStripCalCosmics ALCARECO
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalCosmics_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalCosmics_cff.py
  Configuration/AlCa/python/autoAlca.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaRecoStreamsHeavyIons_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26143 Remove warning in ElectroWeakAnalysis/ZMuMu
  ElectroWeakAnalysis/ZMuMu/plugins/MC_Efficiency_Analyzer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#26102 add import FWCore.ParameterSet.Config as cms to top to fix unit tests
  CondTools/Ecal/python/EcalDAQ_popcon.py
  CondTools/Ecal/python/EcalDCS_popcon.py
  CondTools/Ecal/python/EcalLaser_express_popcon.py
  CondTools/Ecal/python/EcalLaser_prompt_popcon.py
  CondTools/Ecal/python/db_credentials.py
Labels: code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, tests-approved

#26146 Revert "Revert "Default data set for D35""
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26144 Remove warning in DQMServices/ClientConfig
  DQMServices/ClientConfig/interface/QTestParameterNames.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26141 Remove unused var in MuonAnalysis/MuonAssociators
  MuonAnalysis/MuonAssociators/plugins/TriggerMatcherToHLTDebug.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26148 [94X] bypassVersionCheck should not apply to DQMRootSource
  Configuration/DataProcessing/python/Merge.py
Labels: backport, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26114 Fix comp error in CaloOnlineTools/HcalOnlineDb
  CaloOnlineTools/HcalOnlineDb/src/HcalLutManager.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26142 Remove unused typedef in L1Trigger/TrackTrigger
  L1Trigger/TrackTrigger/src/TTClusterAlgorithm_neighbor.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#26145 Remove copy pasted argument assingment
  OnlineDB/EcalCondDB/src/EcalDBConnection.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26147 bypassVersionCheck should not apply to DQMRootSource
  Configuration/DataProcessing/python/Merge.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26066 Fix CaloParticle Debugger
  SimGeneral/Debugging/plugins/CaloParticleDebugger.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26090 Conversions from low pt gsf tracks mini aod 105x
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#25982 HBHE: mahi speed up
  CalibCalorimetry/HcalAlgos/interface/HcalTimeSlew.h
  CalibCalorimetry/HcalAlgos/src/HcalTimeSlew.cc
  CalibCalorimetry/HcalPlugins/src/HcalTimeSlewEP.cc
  RecoLocalCalo/HcalRecAlgos/interface/MahiFit.h
  RecoLocalCalo/HcalRecAlgos/interface/PulseShapeFunctor.h
  RecoLocalCalo/HcalRecAlgos/src/MahiFit.cc
  RecoLocalCalo/HcalRecAlgos/src/PulseShapeFunctor.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26159 Temporarily restore 9_4_13 DataProcessing status, pending full validation
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
Labels: comparison-pending, fully-signed, operations-approved, orp-approved, tests-started

#26149 [80X] bypassVersionCheck should not apply to DQMRootSource
  Configuration/DataProcessing/python/Merge.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26123 herwig 7 settings
  Configuration/Generator/python/Herwig7Settings/Herwig7CH2TuneSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7CH3TuneSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7CommonMergingSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHECommonSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHEMG5aMCatNLOSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHEPowhegSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHESettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7StableParticlesForDetector_cfi.py
  GeneratorInterface/Herwig7Interface/python/Herwig7_loadCommonMergingSettings_cff.py
  GeneratorInterface/Herwig7Interface/python/Herwig7_loadCommonSettings_cff.py
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26056 Added monopole ionisation classes
  SimG4Core/PhysicsLists/interface/CMSmplIonisation.h
  SimG4Core/PhysicsLists/interface/CMSmplIonisationWithDeltaModel.h
  SimG4Core/PhysicsLists/src/CMSMonopolePhysics.cc
  SimG4Core/PhysicsLists/src/CMSmplIonisation.cc
  SimG4Core/PhysicsLists/src/CMSmplIonisationWithDeltaModel.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26124 Herwig7 Settings
  Configuration/Generator/python/Herwig7Settings/Herwig7CommonMergingSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHECommonSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHEMG5aMCatNLOSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHEPowhegSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHESettings_cfi.py
  GeneratorInterface/Herwig7Interface/python/Herwig7_loadCommonMergingSettings_cff.py
  GeneratorInterface/Herwig7Interface/python/Herwig7_loadCommonSettings_cff.py
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#25993 GEMRecHits - added masking
  CondFormats/GEMObjects/interface/GEMDeadStrips.h
  CondFormats/GEMObjects/interface/GEMMaskedStrips.h
  CondFormats/GEMObjects/test/test_serialization.cpp
  RecoLocalMuon/GEMRecHit/BuildFile.xml
  RecoLocalMuon/GEMRecHit/data/deadStrips.txt
  RecoLocalMuon/GEMRecHit/data/maskedStrips.txt
  RecoLocalMuon/GEMRecHit/interface/GEMCluster.h
  RecoLocalMuon/GEMRecHit/interface/GEMClusterContainer.h
  RecoLocalMuon/GEMRecHit/interface/GEMClusterizer.h
  RecoLocalMuon/GEMRecHit/interface/GEMEtaPartitionMask.h
  RecoLocalMuon/GEMRecHit/interface/GEMMaskReClusterizer.h
  RecoLocalMuon/GEMRecHit/interface/GEMRecHitAlgoFactory.h
  RecoLocalMuon/GEMRecHit/interface/GEMRecHitBaseAlgo.h
  RecoLocalMuon/GEMRecHit/plugins/BuildFile.xml
  RecoLocalMuon/GEMRecHit/plugins/GEMRecHitProducer.cc
  RecoLocalMuon/GEMRecHit/plugins/GEMRecHitProducer.h
  RecoLocalMuon/GEMRecHit/plugins/GEMRecHitStandardAlgo.cc
  RecoLocalMuon/GEMRecHit/plugins/GEMRecHitStandardAlgo.h
  RecoLocalMuon/GEMRecHit/plugins/ME0RecHitProducer.cc
  RecoLocalMuon/GEMRecHit/plugins/ME0RecHitProducer.h
  RecoLocalMuon/GEMRecHit/plugins/ME0RecHitStandardAlgo.cc
  RecoLocalMuon/GEMRecHit/plugins/ME0RecHitStandardAlgo.h
  RecoLocalMuon/GEMRecHit/plugins/SealModule.cc
  RecoLocalMuon/GEMRecHit/python/gemRecHits_cfi.py
  RecoLocalMuon/GEMRecHit/src/GEMCluster.cc
  RecoLocalMuon/GEMRecHit/src/GEMClusterContainer.h
  RecoLocalMuon/GEMRecHit/src/GEMClusterizer.cc
  RecoLocalMuon/GEMRecHit/src/GEMClusterizer.h
  RecoLocalMuon/GEMRecHit/src/GEMMaskReClusterizer.cc
  RecoLocalMuon/GEMRecHit/src/GEMMaskReClusterizer.h
  RecoLocalMuon/GEMRecHit/src/GEMRecHitBaseAlgo.cc
  RecoLocalMuon/GEMRecHit/src/GEMRecHitProducer.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#26065 Close by gun generator
  IOMC/EventVertexGenerators/interface/PassThroughEvtVtxGenerator.h
  IOMC/EventVertexGenerators/src/PassThroughEvtVtxGenerator.cc
  IOMC/EventVertexGenerators/src/module.cc
  IOMC/ParticleGuns/interface/CloseByParticleGunProducer.h
  IOMC/ParticleGuns/src/CloseByParticleGunProducer.cc
  IOMC/ParticleGuns/src/SealModule.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, simulation-approved, tests-approved

#26140 Update VtxSmearingScenario for 10_6_X MC production - Round Optics
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRun3RoundOptics25ns13TeVHighSigmaZ_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRun3RoundOptics25ns13TeVLowSigmaZ_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#26151 Fix a conflict with UpgradeProperties
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26169 [10.6.X][PAT] Fix for clang warnings: PhysicsTools
  CommonTools/UtilAlgos/interface/SingleElementCollectionRefSelector.h
  PhysicsTools/CondLiteIO/test/IntProductESSource.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26134 Removed unused function getfullpathfromfip_
  GeneratorInterface/ReggeGribovPartonMCInterface/src/fileinpathwrapper.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26130 PFSimParticle: import ParticleFilter setting from pre-defined config rather than re-…
  RecoParticleFlow/PFProducer/python/particleFlowSimParticle_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26168 Updates for UL reprocessing test: DataProcessing and CSC missing data format
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
  DataFormats/CSCDigi/interface/CSCCLCTPreTriggerDigi.h
  DataFormats/CSCDigi/interface/CSCCLCTPreTriggerDigiCollection.h
  DataFormats/CSCDigi/src/CSCCLCTPreTriggerDigi.cc
  DataFormats/CSCDigi/src/classes.h
  DataFormats/CSCDigi/src/classes_def.xml
Labels: comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#26089 Phase2-hgx182 Change in ETL due to change in HGCal geometry
  Geometry/MTDCommonData/data/etl/v1/etl.xml
  Geometry/MTDCommonData/data/etl/v2/etl.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26117 Adding CHS area
  PhysicsTools/PatAlgos/python/slimming/applySubstructure_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26160 Fixed pt shift in the muon validation plots
  Validation/RecoMuon/test/macro/new_PlotHelpers.C
  Validation/RecoMuon/test/macro/new_TrackValHistoPublisher.C
  Validation/RecoMuon/test/new_userparams.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26165 [10.6.X][SIM] fix for clang warnings: simulation
  SimCalorimetry/EcalSelectiveReadoutAlgos/src/EcalSelectiveReadout.cc
  SimCalorimetry/EcalSelectiveReadoutAlgos/src/EcalSelectiveReadoutSuppressor.cc
  SimG4Core/CustomPhysics/src/CMSDarkPairProduction.cc
  SimTracker/SiStripDigitizer/plugins/SiTrivialInduceChargeOnStrips.cc
  SimTracker/TrackerMaterialAnalysis/plugins/ListGroups.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26166 [10.6.X][SIM] fix for clang warnings: SimG4CMS/Forward
  SimG4CMS/Forward/interface/FastTimerSD.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26133 Do not pass nullptr to strcmp in CZString
  EventFilter/Utilities/src/json_value.cpp
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26139 Switching HCAL Run3 MC to DB conditions
  CalibCalorimetry/HcalPlugins/python/Hcal_Conditions_forGlobalTag_cff.py
  Configuration/Eras/python/Era_Phase2_cff.py
  Configuration/Eras/python/Era_Run3_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26164 [10.6.X][Validation] Fix clang warnings in validation subsystem
  Validation/GlobalRecHits/src/GlobalRecHitsAnalyzer.cc
  Validation/HcalDigis/src/HcalDigisValidation.cc
  Validation/SiPixelPhase1RecHitsV/src/SiPixelPhase1RecHitsV.cc
Labels: code-checks-approved, comparison-pending, dqm-approved, fully-signed, orp-approved, tests-started

#26132 Do not pass nullptr to memcpy in DTConfigLUTs
  L1TriggerConfig/DTTPGConfig/src/DTConfigLUTs.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#26157 Implemented time window selection for HGCalLayerClusters
  Fireworks/Calo/interface/FWHeatmapProxyBuilderTemplate.h
  Fireworks/Calo/plugins/FWCaloClusterProxyBuilder.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#26192 TkAl MillePede: add setting to increase OMP_STACKSIZE
  Alignment/MillePedeAlignmentAlgorithm/templates/universalConfigTemplate.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26150 PPS pixel detector edges
  Geometry/VeryForwardGeometry/interface/CTPPSPixelSimTopology.h
  Geometry/VeryForwardGeometry/interface/CTPPSPixelTopology.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26196 one::OutputModule now supports transition caches
  FWCore/Framework/interface/one/OutputModule.h
  FWCore/Framework/interface/one/OutputModuleBase.h
  FWCore/Framework/interface/one/outputmoduleAbilityToImplementor.h
  FWCore/Framework/src/one/OutputModuleBase.cc
  FWCore/Framework/test/one_outputmodule_t.cppunit.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26200 set False as default for bypassVersionCheck
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#26202 Initialize pointer in MCMatchCandRefSelector constructor
  PhysicsTools/HepMCCandAlgos/plugins/MCMatchCandRefSelector.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26084 Add the conversions from lowPtGsfTracks (bparking) to the miniAOD content
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26152 Fix a conflict with UpgradeProperties (102X)
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26109 Add ParkingBPH skim spec to autoskim.py (back port to 10_2_X)
  Configuration/Skimming/python/autoSkim.py
Labels: comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved

#26116 Fixed lost definition of dictionaries errors
  DataFormats/L1TrackTrigger/src/classes_def.xml
  DataFormats/Phase2TrackerDigi/src/classes_def.xml
  DataFormats/RecoCandidate/src/classes_def.xml
  SimDataFormats/TrackingAnalysis/src/classes.h
  SimDataFormats/TrackingAnalysis/src/classes_def.xml
  Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, l1-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#26138 Remove direct dependency on PythonParameterSet from FWCore/SerivceRegistry
  CondCore/Utilities/BuildFile.xml
  DetectorDescription/Parser/test/BuildFile.xml
  DetectorDescription/Parser/test/testmat.cpp
  DetectorDescription/RegressionTest/test/BuildFile.xml
  DetectorDescription/RegressionTest/test/dumpDDCompactView.cpp
  DetectorDescription/RegressionTest/test/dumpDDExpandedView.cpp
  DetectorDescription/RegressionTest/test/testDDCompactView.cpp
  FWCore/Catalog/test/BuildFile.xml
  FWCore/Catalog/test/FileLocator_t.cpp
  FWCore/MessageService/bin/BuildFile.xml
  FWCore/MessageService/bin/Standalone.cpp
  FWCore/PythonFramework/test/BuildFile.xml
  FWCore/ServiceRegistry/BuildFile.xml
  FWCore/ServiceRegistry/interface/ServiceRegistry.h
  FWCore/ServiceRegistry/src/ServiceRegistry.cc
  Fireworks/FWInterface/BuildFile.xml
  PhysicsTools/UtilAlgos/bin/BuildFile.xml
Labels: analysis-approved, code-checks-approved, comparison-available, core-approved, db-pending, geometry-approved, orp-approved, pending-signatures, tests-rejected, visualization-approved

#26185 ClusterRepair template initialization bugfix
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26214 Revert "Fixed lost definition of dictionaries errors"
  DataFormats/L1TrackTrigger/src/classes_def.xml
  DataFormats/Phase2TrackerDigi/src/classes_def.xml
  DataFormats/RecoCandidate/src/classes_def.xml
  SimDataFormats/TrackingAnalysis/src/classes.h
  SimDataFormats/TrackingAnalysis/src/classes_def.xml
  Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py
Labels: code-checks-approved, comparison-pending, core-pending, l1-pending, orp-approved, pending-signatures, reconstruction-pending, simulation-pending, tests-started, upgrade-pending

#26176 [10.2.X] Additional GBRForest parser without TMVA for LowPtGsfElectrons
  CommonTools/MVAUtils/BuildFile.xml
  CommonTools/MVAUtils/interface/GBRForestTools.h
  CommonTools/MVAUtils/src/GBRForestTools.cc
  CondFormats/EgammaObjects/interface/GBRTree.h
  CondFormats/EgammaObjects/src/GBRTree.cxx
  RecoEgamma/EgammaElectronProducers/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/src/LowPtGsfElectronIDHeavyObjectCache.cc
  RecoEgamma/EgammaElectronProducers/src/LowPtGsfElectronSeedHeavyObjectCache.cc
Labels: alca-approved, analysis-pending, comparison-available, db-pending, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved

#26167 [10.6.X][TRACK] fix for clang warnings
  TrackPropagation/SteppingHelixPropagator/src/SteppingHelixPropagator.cc
  TrackingTools/TrackRefitter/src/TrackTransformerForCosmicMuons.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26162 Fix clang warnings
  RecoBTag/PerformanceDB/plugins/BtagPerformanceESProducer.cc
  RecoCTPPS/PixelLocal/src/RPixDetClusterizer.cc
  RecoHI/HiCentralityAlgos/plugins/HiTrivialConditionRetriever.cc
  RecoTracker/TkNavigation/plugins/SimpleNavigableLayer.cc
  RecoTracker/TransientTrackingRecHit/test/TTRHBuilderTest.cc
  RecoVertex/KinematicFit/src/FinalTreeBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26179 EgammaTools - empty classes to free functions and ConversionInfo to struct
  Calibration/HcalCalibAlgos/test/GammaJetAnalysis.cc
  EgammaAnalysis/ElectronTools/interface/SuperClusterHelper.h
  EgammaAnalysis/ElectronTools/src/SuperClusterHelper.cc
  ElectroWeakAnalysis/ZEE/src/ZeeCandidateFilter.cc
  PhysicsTools/PatAlgos/plugins/PATPhotonProducer.h
  PhysicsTools/TagAndProbe/plugins/ElectronConversionRejectionVars.cc
  PhysicsTools/UtilAlgos/interface/AdHocNTupler.h
  RecoEgamma/EgammaElectronAlgos/interface/RegressionHelper.h
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc
  RecoEgamma/EgammaHLTProducers/src/EgammaHLTElectronDetaDphiProducer.cc
  RecoEgamma/EgammaHLTProducers/src/EgammaHLTGsfTrackVarProducer.cc
  RecoEgamma/EgammaTools/interface/BaselinePFSCRegression.h
  RecoEgamma/EgammaTools/interface/ConversionFinder.h
  RecoEgamma/EgammaTools/interface/ConversionInfo.h
  RecoEgamma/EgammaTools/interface/ECALPositionCalculator.h
  RecoEgamma/EgammaTools/interface/EGEnergyCorrector.h
  RecoEgamma/EgammaTools/interface/EcalClusterLocal.h
  RecoEgamma/EgammaTools/plugins/EGRegressionModifierV1.cc
  RecoEgamma/EgammaTools/plugins/EGRegressionModifierV2.cc
  RecoEgamma/EgammaTools/src/ConversionFinder.cc
  RecoEgamma/EgammaTools/src/ECALPositionCalculator.cc
  RecoEgamma/EgammaTools/src/EGEnergyCorrector.cc
  RecoEgamma/EgammaTools/src/EcalClusterLocal.cc
  RecoEgamma/EgammaTools/src/EcalRegressionData.cc
  RecoEgamma/ElectronIdentification/src/CutBasedElectronID.cc
Labels: alca-approved, analysis-approved, code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#26208 pr106x Fix bug memory over-read in OMTF Producer
  L1Trigger/L1TMuonOverlap/src/GhostBusterPreferRefDt.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#26153 Phase2-hgx183 Second set of work for V10 geometry of HGCal
  Geometry/HGCalCommonData/data/hgcalHEmix/v10/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v10/hgcalHEsil.xml
  Geometry/HGCalCommonData/plugins/DDHGCalEEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalEEAlgo.h
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.h
  Geometry/HGCalCommonData/python/testHGCV10XML_cfi.py
  SimG4CMS/Calo/src/HcalNumberingFromPS.cc
  SimG4CMS/Calo/test/python/runHGC4_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckHGCal_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#26180 Ecal constexpr formats
  DataFormats/EcalDigi/interface/EcalMGPASample.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#25701 changing strips from 192 to 96
  Geometry/RPCGeometryBuilder/data/2023/v1/RPCSpecs.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26220 drop commented out code of TMVA in LowPtGsfElectron\*
  RecoEgamma/EgammaElectronProducers/src/LowPtGsfElectronSeedHeavyObjectCache.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26217 Tweaked pixel pair MVA selection for pp_on_AA
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26210 Incremented GenParticle version number for storage
  SimDataFormats/GeneratorProducts/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26189 Run2-TB42 Add a new version of TB (October 19 v1)
  Geometry/HGCalCommonData/data/TB181/Oct181/ahcal.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/cms.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcal.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalEE.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalHE.xml
  Geometry/HGCalCommonData/plugins/DDHGCalTBModuleX.cc
  Geometry/HGCalCommonData/plugins/DDHGCalTBModuleX.h
  Geometry/HGCalCommonData/plugins/module.cc
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#26218 DD4hep: DD Filtered View
  DetectorDescription/DDCMS/data/cms-2015-muon-geometry.xml
  DetectorDescription/DDCMS/interface/DDExpandedNode.h
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/interface/ExpandedNodes.h
  DetectorDescription/DDCMS/interface/Filter.h
  DetectorDescription/DDCMS/interface/MuonNumbering.h
  DetectorDescription/DDCMS/python/cmsMFGeometryXML_cfi.py
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  DetectorDescription/DDCMS/src/Filter.cc
  DetectorDescription/DDCMS/src/MuonNumbering.cc
  DetectorDescription/DDCMS/test/BuildFile.xml
  DetectorDescription/DDCMS/test/DDFilteredView.cppunit.cc
  DetectorDescription/DDCMS/test/ExpandedNodes.cppunit.cc
  DetectorDescription/DDCMS/test/Filter.cppunit.cc
  DetectorDescription/RecoGeometry/interface/DTGeometryBuilder.h
  DetectorDescription/RecoGeometry/plugins/DTGeometryTest.cc
  DetectorDescription/RecoGeometry/src/DTGeometryBuilder.cc
  Geometry/DTGeometryBuilder/data/dtSpecsFilter/2019/v1/dtSpecsFilter.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26203 Make L1Trigger/ME0Trigger comply with new CMSSW style rules.
  L1Trigger/ME0Trigger/interface/ME0Motherboard.h
  L1Trigger/ME0Trigger/interface/ME0TriggerBuilder.h
  L1Trigger/ME0Trigger/interface/ME0TriggerPseudoBuilder.h
  L1Trigger/ME0Trigger/plugins/ME0TriggerProducer.cc
  L1Trigger/ME0Trigger/plugins/ME0TriggerPseudoProducer.cc
  L1Trigger/ME0Trigger/src/ME0Motherboard.cc
  L1Trigger/ME0Trigger/src/ME0TriggerBuilder.cc
  L1Trigger/ME0Trigger/src/ME0TriggerPseudoBuilder.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#26177 Masking legacy HB- energy correction for Run 3
  RecoLocalCalo/HcalRecAlgos/interface/SimpleHBHEPhase1Algo.h
  RecoLocalCalo/HcalRecAlgos/interface/parseHBHEPhase1AlgoDescription.h
  RecoLocalCalo/HcalRecAlgos/src/SimpleHBHEPhase1Algo.cc
  RecoLocalCalo/HcalRecAlgos/src/parseHBHEPhase1AlgoDescription.cc
  RecoLocalCalo/HcalRecProducers/python/HBHEPhase1Reconstructor_cfi.py
  RecoLocalCalo/HcalRecProducers/src/HBHEPhase1Reconstructor.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26228 Initialize useTriple in MahiFit::phase1Apply so that it is never returned as undefined
  RecoLocalCalo/HcalRecAlgos/src/MahiFit.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26187 Move FastSimulation/BaseParticlePropagator to CommonTools
  CommonTools/BaseParticlePropagator/BuildFile.xml
  CommonTools/BaseParticlePropagator/interface/BaseParticlePropagator.h
  CommonTools/BaseParticlePropagator/interface/RawParticle.h
  CommonTools/BaseParticlePropagator/interface/makeMuon.h
  CommonTools/BaseParticlePropagator/src/BaseParticlePropagator.cc
  CommonTools/BaseParticlePropagator/src/RawParticle.cc
  CommonTools/BaseParticlePropagator/src/makeMuon.cc
  CommonTools/BaseParticlePropagator/test/BuildFile.xml
  CommonTools/BaseParticlePropagator/test/makeMuon_catch2.cc
  FastSimulation/BaseParticlePropagator/test/BuildFile.xml
  FastSimulation/CaloHitMakers/test/testEcalHitMaker.cc
  FastSimulation/Calorimetry/interface/CalorimetryManager.h
  FastSimulation/Event/BuildFile.xml
  FastSimulation/Event/interface/FBaseSimEvent.h
  FastSimulation/Event/interface/FSimTrack.h
  FastSimulation/Event/src/FBaseSimEvent.cc
  FastSimulation/Event/src/KineParticleFilter.cc
  FastSimulation/Particle/BuildFile.xml
  FastSimulation/Particle/src/makeParticle.cc
  FastSimulation/ParticlePropagator/BuildFile.xml
  FastSimulation/ParticlePropagator/interface/ParticlePropagator.h
  FastSimulation/ShowerDevelopment/interface/EMShower.h
  FastSimulation/Tracking/plugins/BuildFile.xml
  GeneratorInterface/GenFilters/BuildFile.xml
  GeneratorInterface/GenFilters/interface/BHFilter.h
  RecoEgamma/EgammaElectronProducers/plugins/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedProducer.cc
  RecoParticleFlow/PFSimProducer/plugins/ConvBremSeedProducer.h
  RecoParticleFlow/PFTracking/BuildFile.xml
  RecoParticleFlow/PFTracking/plugins/GoodSeedProducer.cc
  RecoParticleFlow/PFTracking/src/PFGsfHelper.cc
  RecoParticleFlow/PFTracking/src/PFTrackTransformer.cc
  RecoTauTag/RecoTau/BuildFile.xml
  RecoTauTag/RecoTau/interface/AntiElectronIDMVA6.h
  RecoTauTag/RecoTau/plugins/BuildFile.xml
  RecoTauTag/RecoTau/plugins/PFRecoTauChargedHadronFromTrackPlugin.cc
  Utilities/ReleaseScripts/scripts/CMSSWReleaseDependency.rules
  Utilities/ReleaseScripts/scripts/git-publish
Labels: code-checks-approved, comparison-available, core-approved, fastsim-approved, fully-signed, generators-approved, orp-approved, reconstruction-approved, tests-approved

#26205 Fix v12 IO rule for HitPattern
  DataFormats/TrackReco/interface/HitPattern.h
  DataFormats/TrackReco/src/classes_def.xml
  DataFormats/TrackReco/src/rootio_HitPattern.cc
  DataFormats/TrackReco/test/testHitPattern.cpp
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#26186 Removed unused RecoParticleFlow/PFClusterShapeProducer package
  RecoParticleFlow/PFClusterShapeProducer/BuildFile.xml
  RecoParticleFlow/PFClusterShapeProducer/interface/PFClusterShapeAlgo.h
  RecoParticleFlow/PFClusterShapeProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFClusterShapeProducer/plugins/PFClusterShapeProducer.cc
  RecoParticleFlow/PFClusterShapeProducer/plugins/PFClusterShapeProducer.h
  RecoParticleFlow/PFClusterShapeProducer/plugins/SealModule.cc
  RecoParticleFlow/PFClusterShapeProducer/python/pfClusterShapesSequence_cff.py
  RecoParticleFlow/PFClusterShapeProducer/python/pfClusterShapes_cfi.py
  RecoParticleFlow/PFClusterShapeProducer/src/PFClusterShapeAlgo.cc
  Utilities/ReleaseScripts/scripts/createBuildFile.conf
  Utilities/ReleaseScripts/scripts/git-publish
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#25588 Fix module label in IsFromLostTrackMapProducer::fillDescriptions()
  PhysicsTools/NanoAOD/plugins/IsFromLostTrackMapProducer.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved, xpog-approved

#26135 fix math tests
  DataFormats/Math/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26209 Run2-alca152 Update the macros used for calibration of HCAL
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibTree.C
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26235 TkAl AllInOneTool: Moving to absolute imports at the end of presentation.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/presentation.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26224 [106X] Cleanup lost dictionaries errors
  DataFormats/L1TrackTrigger/src/classes_def.xml
  DataFormats/Phase2TrackerDigi/src/classes_def.xml
  Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py
Labels: code-checks-approved, comparison-available, core-approved, l1-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved, upgrade-approved

#26212 Phase2 hgx186 Define a new scenario D41
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2023D41Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2023D41_cff.py
  Configuration/Geometry/python/dict2023Geometry.py
  Configuration/PyReleaseValidation/python/relval_2023.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023D41XML_cfi.py
  Geometry/MTDCommonData/data/CrystalBarPhiFlat/v2/mtd.xml
  L1Trigger/L1THGCal/python/customTriggerGeometry.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, l1-approved, operations-approved, orp-approved, pdmv-approved, requires-external, tests-approved, upgrade-approved

#26195 Tool for producing DMR trends
  Alignment/OfflineValidation/bin/BuildFile.xml
  Alignment/OfflineValidation/bin/DMRtrends.cc
  Alignment/OfflineValidation/bin/README.md
  Alignment/OfflineValidation/data/lumiperIOV2017.txt
  Alignment/OfflineValidation/data/lumiperIOV2018.txt
  Alignment/OfflineValidation/data/lumiperrun2017.txt
  Alignment/OfflineValidation/data/lumiperrun2018.txt
  Alignment/OfflineValidation/macros/PlotAlignmentValidation.C
  Alignment/OfflineValidation/macros/PlotAlignmentValidation.h
  Alignment/OfflineValidation/python/TkAlAllInOneTool/plottingOptions.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26244 Run2-hcx190 Avoid direct reference to CLHEP
  Geometry/HcalAlgo/plugins/DDHCalFibreBundle.cc
  Geometry/HcalAlgo/plugins/DDHCalForwardAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalLinearXY.cc
  Geometry/HcalAlgo/plugins/DDHCalTBCableAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26237 Phase2-hgx187 Update V10 geometry with input from Philippe
  Geometry/HGCalCommonData/data/hgcal/v10/hgcal.xml
  Geometry/HGCalCommonData/src/HGCalWaferType.cc
  Geometry/HGCalGeometry/interface/HGCalGeometry.h
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
  Geometry/HGCalGeometry/test/HGCalGeometryCornerTester.cc
  Geometry/HGCalGeometry/test/python/testHGCalCorner_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#26207 [PPS] Conditions format update for diamond timing calibration
  CondFormats/CTPPSReadoutObjects/interface/PPSTimingCalibration.h
  CondFormats/CTPPSReadoutObjects/plugins/PPSTimingCalibrationESSource.cc
  CondFormats/CTPPSReadoutObjects/python/PPSTimingDetEnum_cff.py
  CondFormats/CTPPSReadoutObjects/src/PPSTimingCalibration.cc
  CondTools/CTPPS/test/ppsTimingCalibrationAnalyzer_cfg.py
  CondTools/CTPPS/test/ppsTimingCalibrationWriter_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#26223 Update VtxSmearingScenario for 10_6_X MC production - Flat Optics
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRun3FlatOpticsGaussSigmaZ4p2cm_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRun3FlatOpticsGaussSigmaZ5p3cm_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#26254 Fix configurations and their descriptions in recoTau
  RecoTauTag/RecoTau/plugins/PATTauDiscriminantCutMultiplexer.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByHPSSelection.cc
  RecoTauTag/RecoTau/plugins/RecoTauDiscriminantCutMultiplexer.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroProducer.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroStripPlugin3.cc
  RecoTauTag/RecoTau/plugins/RecoTauProducer.cc
  RecoTauTag/RecoTau/python/PFRecoTauProducer_cfi.py
  RecoTauTag/RecoTau/python/RecoTauDiscriminantCutMultiplexer_cfi.py
  RecoTauTag/RecoTau/python/RecoTauPiZeroBuilderPlugins_cfi.py
  RecoTauTag/RecoTau/python/RecoTauPiZeroProducer_cfi.py
  RecoTauTag/RecoTau/src/TauDiscriminationProducerBase.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26262 Removed unnecessary dictionary struct from FWCore/MessageLogger
  FWCore/MessageLogger/src/classes.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#26257 Phase2-hcx191 Take care of hfnose in view of change in algorithm
  Geometry/ForwardCommonData/data/hfnose/v0/hfnose.xml
  Geometry/ForwardCommonData/data/hfnose/v1/hfnose.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#26211 Provide forward compatibility to HepMC::GenEvent reading
  SimDataFormats/GeneratorProducts/src/classes.h
  SimDataFormats/GeneratorProducts/src/classes_def.xml
  SimDataFormats/GeneratorProducts/src/hepmc_rootio.cc
Labels: backport-ok, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26100 [HGCal] Modify MultiTrackValidator plotting for easier browsing of HGCal plots
  Validation/RecoTrack/python/plotting/html.py
  Validation/RecoTrack/python/plotting/plotting.py
  Validation/RecoTrack/python/plotting/validation.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26125 Pf gen jet specifics
  DataFormats/HepMCCandidate/interface/GenParticleFwd.h
  DataFormats/JetReco/interface/GenJet.h
  DataFormats/JetReco/src/classes_def_1.xml
  RecoJets/JetProducers/src/JetSpecific.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, reconstruction-approved, tests-approved

#26260 Removed unnecessary dictionary struct from DataFormats/TrackingRecHit
  DataFormats/TrackingRecHit/src/classes.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26261 Removed unnecessary dictionary struct from DataFormats/TrajectorySeed
  DataFormats/TrajectorySeed/src/classes.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved
