Repository cms-sw/cmssw, pull requests merged in 2019-06, with the labels that each got.

#26979 Running code-format for fastsim-reconstruction
  CommonTools/BaseParticlePropagator/interface/BaseParticlePropagator.h
  CommonTools/BaseParticlePropagator/interface/RawParticle.h
  CommonTools/BaseParticlePropagator/interface/makeMuon.h
  CommonTools/BaseParticlePropagator/src/BaseParticlePropagator.cc
  CommonTools/BaseParticlePropagator/src/RawParticle.cc
  CommonTools/BaseParticlePropagator/src/makeMuon.cc
  CommonTools/BaseParticlePropagator/test/makeMuon_catch2.cc
Labels: code-checks-approved, comparison-available, fastsim-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26980 Running code-format for generators
  GeneratorInterface/EvtGenInterface/interface/DataCardFileWriter.h
  GeneratorInterface/EvtGenInterface/interface/EvtGenFactory.h
  GeneratorInterface/EvtGenInterface/interface/EvtGenInterfaceBase.h
  GeneratorInterface/EvtGenInterface/interface/myEvtRandomEngine.h
  GeneratorInterface/EvtGenInterface/plugins/DataCardFileWriter.cc
  GeneratorInterface/EvtGenInterface/plugins/EvtGen/EvtGenInterface.cc
  GeneratorInterface/EvtGenInterface/plugins/EvtGen/EvtGenInterface.h
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtLb2plnuLCSR.cpp
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtLb2plnuLCSR.hh
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtLb2plnuLCSRFF.cpp
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtLb2plnuLCSRFF.hh
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtModelUserReg.cpp
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtModelUserReg.h
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtSLBaryonAmp.cpp
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtSLBaryonAmp.hh
  GeneratorInterface/EvtGenInterface/plugins/myEvtRandomEngine.cc
  GeneratorInterface/EvtGenInterface/src/EvtGenFactory.cc
Labels: code-checks-approved, comparison-available, generators-pending, orp-approved, pending-signatures, tests-approved

#26988 Running code-format for pdmv
  Configuration/Skimming/interface/LeptonRecoSkim.h
  Configuration/Skimming/interface/LeptonSkimming.h
  Configuration/Skimming/src/LeptonRecoSkim.cc
  Configuration/Skimming/src/LeptonSkimming.cc
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-pending, pending-signatures, tests-approved

#26945 Fix the storage of the header record from the SiPixel template in case it is less than 80 chars long
  CalibTracker/SiPixelESProducers/plugins/SiPixelFakeGenErrorDBObjectESSource.cc
  CalibTracker/SiPixelESProducers/plugins/SiPixelFakeTemplateDBObjectESSource.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26958 [RECONSTRUCTION] fixes needed to build cxxmodules
  DataFormats/CaloRecHit/BuildFile.xml
  DataFormats/EcalRecHit/BuildFile.xml
  DataFormats/EgammaCandidates/src/classes.h
  DataFormats/EgammaCandidates/src/classes_def.xml
  DataFormats/EgammaReco/BuildFile.xml
  DataFormats/ParticleFlowCandidate/BuildFile.xml
  DataFormats/RecoCandidate/BuildFile.xml
  DataFormats/TrackReco/BuildFile.xml
  DataFormats/TrackerCommon/interface/ClusterSummary.h
  DataFormats/TrackerRecHit2D/BuildFile.xml
  DataFormats/TrackingRecHit/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27006 Modernize CastorDbProducer
  CalibCalorimetry/CastorCalib/plugins/CastorDbProducer.cc
  CalibCalorimetry/CastorCalib/plugins/CastorDbProducer.h
  CalibCalorimetry/CastorCalib/plugins/SealModule.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27007 Modernize EcalLaserCorrectionService
  CalibCalorimetry/EcalLaserCorrection/plugins/EcalLaserCorrectionService.cc
  CalibCalorimetry/EcalLaserCorrection/plugins/EcalLaserCorrectionService.h
  CalibCalorimetry/EcalLaserCorrection/plugins/SealModule.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26990 Running code-format for simulation
  DataFormats/GeometryVector/interface/Basic2DVector.h
  DataFormats/GeometryVector/interface/Basic3DVector.h
  DataFormats/GeometryVector/interface/CoordinateSets.h
  DataFormats/GeometryVector/interface/EtaInterval.h
  DataFormats/GeometryVector/interface/GlobalPoint.h
  DataFormats/GeometryVector/interface/GlobalTag.h
  DataFormats/GeometryVector/interface/GlobalVector.h
  DataFormats/GeometryVector/interface/LocalPoint.h
  DataFormats/GeometryVector/interface/LocalTag.h
  DataFormats/GeometryVector/interface/LocalVector.h
  DataFormats/GeometryVector/interface/MeasurementTag.h
  DataFormats/GeometryVector/interface/PV2DBase.h
  DataFormats/GeometryVector/interface/PV3DBase.h
  DataFormats/GeometryVector/interface/Phi.h
  DataFormats/GeometryVector/interface/PhiInterval.h
  DataFormats/GeometryVector/interface/Pi.h
  DataFormats/GeometryVector/interface/Point2DBase.h
  DataFormats/GeometryVector/interface/Point3DBase.h
  DataFormats/GeometryVector/interface/PointTag.h
  DataFormats/GeometryVector/interface/PreciseFloatType.h
  DataFormats/GeometryVector/interface/Theta.h
  DataFormats/GeometryVector/interface/TrackingJacobians.h
  DataFormats/GeometryVector/interface/Vector2DBase.h
  DataFormats/GeometryVector/interface/Vector3DBase.h
  DataFormats/GeometryVector/interface/VectorTag.h
  DataFormats/GeometryVector/interface/VectorUtil.h
  DataFormats/GeometryVector/interface/private/Basic3DVectorLD.h
  DataFormats/GeometryVector/interface/private/extBasic3DVector.h
  DataFormats/GeometryVector/interface/private/sseBasic2DVector.h
  DataFormats/GeometryVector/interface/private/sseBasic3DVector.h
  DataFormats/GeometryVector/src/TrackingJacobians.cc
  DataFormats/GeometryVector/src/classes.h
  DataFormats/GeometryVector/test/BasicVector_t.cpp
  DataFormats/GeometryVector/test/Intervals_t.cpp
  DataFormats/GeometryVector/test/PhiTest.cc
  DataFormats/GeometryVector/test/phiLess_t.cpp
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26894 refactored first part of PFAlgo::processBlock
  RecoParticleFlow/PFProducer/interface/PFAlgo.h
  RecoParticleFlow/PFProducer/src/PFAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26960 [SIMULATION] fixes needed to build cxxmodules
  DataFormats/HcalDetId/interface/HcalTestNumbering.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#26968 Change default beamspot from "RoundOpticsHighSigmaZ" to "RoundOpticsLowSigmaZ"
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26997 Migrate CaloTPGTranscoderULUTs to EventSetup consumes
  CalibCalorimetry/CaloTPG/plugins/CaloTPGTranscoderULUTs.cc
Labels: alca-approved, code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#27013 Run2-hcx207 Take care of memory issue in loading constants for calib channels
  Geometry/CaloTopology/src/HcalTopology.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27014 Modernize HcalDbProducer
  CalibCalorimetry/HcalPlugins/src/HcalDbProducer.cc
  CalibCalorimetry/HcalPlugins/src/HcalDbProducer.h
  CalibCalorimetry/HcalPlugins/src/SealModule.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27027 Sim Geometry: Tidy up the SensitiveDetectorCatalog
  SimG4Core/Geometry/interface/SensitiveDetectorCatalog.h
  SimG4Core/Geometry/src/SensitiveDetectorCatalog.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27035 added pileup scenario for 2018 ultra legacy
  Configuration/StandardSequences/python/Mixing.py
  SimGeneral/MixingModule/python/mix_2018_25ns_UltraLegacy_PoissonOOTPU_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#26933 Add ECaloParticle Proxy
  Fireworks/Calo/interface/FWHeatmapProxyBuilderTemplate.h
  Fireworks/SimData/plugins/FWECaloParticleProxyBuilder.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#27042 Modernize ESProducers in CalibTracker/SiPixelESProducers
  CalibTracker/SiPixelESProducers/interface/SiPixel2DTemplateDBObjectESProducer.h
  CalibTracker/SiPixelESProducers/interface/SiPixelGenErrorDBObjectESProducer.h
  CalibTracker/SiPixelESProducers/interface/SiPixelQualityESProducer.h
  CalibTracker/SiPixelESProducers/interface/SiPixelTemplateDBObjectESProducer.h
  CalibTracker/SiPixelESProducers/plugins/PixelFEDChannelCollectionProducer.cc
  CalibTracker/SiPixelESProducers/plugins/SealModules.cc
  CalibTracker/SiPixelESProducers/plugins/SiPixel2DTemplateDBObjectESProducer.cc
  CalibTracker/SiPixelESProducers/plugins/SiPixelGenErrorDBObjectESProducer.cc
  CalibTracker/SiPixelESProducers/plugins/SiPixelQualityESProducer.cc
  CalibTracker/SiPixelESProducers/plugins/SiPixelTemplateDBObjectESProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27041 remove unused non-const static in CastorJetIDHelper
  RecoJets/JetProducers/interface/CastorJetIDHelper.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27023 Running code-format for alca-db
  CondFormats/GeometryObjects/interface/CSCRecoDigiParameters.h
  CondFormats/GeometryObjects/interface/HcalParameters.h
  CondFormats/GeometryObjects/interface/PCaloGeometry.h
  CondFormats/GeometryObjects/interface/PGeometricDet.h
  CondFormats/GeometryObjects/interface/PGeometricDetExtra.h
  CondFormats/GeometryObjects/interface/PGeometricTimingDet.h
  CondFormats/GeometryObjects/interface/PGeometricTimingDetExtra.h
  CondFormats/GeometryObjects/interface/PHGCalParameters.h
  CondFormats/GeometryObjects/interface/PMTDParameters.h
  CondFormats/GeometryObjects/interface/PTrackerParameters.h
  CondFormats/GeometryObjects/interface/RecoIdealGeometry.h
  CondFormats/GeometryObjects/src/PCaloGeometry.cc
  CondFormats/GeometryObjects/src/T_EventSetup_PCaloGeometry.cc
  CondFormats/GeometryObjects/src/T_EventSetup_PGeometricDet.cc
  CondFormats/GeometryObjects/src/T_EventSetup_PGeometricDetExtra.cc
  CondFormats/GeometryObjects/src/T_EventSetup_PGeometricTimingDet.cc
  CondFormats/GeometryObjects/src/T_EventSetup_PGeometricTimingDetExtra.cc
  CondFormats/GeometryObjects/src/classes.h
  CondFormats/GeometryObjects/test/testSerializationGeometryObjects.cpp
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27018 Running code-format for alca-upgrade
  CondTools/SiPhase2Tracker/plugins/DTCCablingMapProducer.cc
  CondTools/SiPhase2Tracker/plugins/DTCCablingMapTestProducer.cc
  CondTools/SiPhase2Tracker/plugins/DTCCablingMapTestReader.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved, upgrade-approved

#27046 Migrate TkDetMapESProducer to EventSetup consumes
  CalibTracker/SiStripCommon/plugins/TkDetMapESProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27016 Manage PluginFactory plugin with unique_ptr in FilteredLayerClustersProducer
  RecoHGCal/TICL/plugins/FilteredLayerClustersProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27017 Running code-format for alca-db-hlt
  CondFormats/HLTObjects/interface/AlCaRecoTriggerBits.h
  CondFormats/HLTObjects/interface/HLTPrescaleTableCond.h
  CondFormats/HLTObjects/src/AlCaRecoTriggerBits.cc
  CondFormats/HLTObjects/src/classes.h
  CondFormats/HLTObjects/src/headers.h
  CondFormats/HLTObjects/test/testSerializationHLTObjects.cpp
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, hlt-pending, orp-approved, pending-signatures, tests-approved

#26959 [RECO_ANALYSIS] fixes needed to build cxxmodules
  DataFormats/Candidate/interface/CandidateWithRef.h
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26963 Forward-port #26937: Remove warnings from L1T DQM
  DQM/L1TMonitor/python/L1TStage2uGT_cff.py
  DQMOffline/L1Trigger/python/L1TEtSumJetOffline_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#27012 Migrate HcalTPGCoderULUT to EventSetup consumes
  CalibCalorimetry/HcalTPGEventSetup/src/HcalTPGCoderULUT.cc
Labels: alca-approved, code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#26538 Run3-gem31 Change GEMDetId in view of merging ME0 with GE1/2
  DataFormats/MuonDetId/interface/GEMDetId.h
  DataFormats/MuonDetId/src/GEMDetId.cc
  DataFormats/MuonDetId/src/classes_def.xml
  DataFormats/MuonDetId/test/BuildFile.xml
  DataFormats/MuonDetId/test/GEMDetIdAnalyzer.cc
  DataFormats/MuonDetId/test/runGEMDetIdAnalysis_cfg.py
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentBuilder.cc
  SimMuon/GEMDigitizer/src/GEMDigiProducer.cc
  Validation/MuonGEMHits/src/GEMBaseValidation.cc
  Validation/MuonGEMHits/src/GEMHitsValidation.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, requires-external, simulation-approved, tests-approved, upgrade-approved

#26944 Run3-gem33 Fix GEMGeometry to allow DetId transition
  Geometry/GEMGeometry/src/GEMGeometry.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, requires-external, tests-approved, upgrade-approved

#27019 Running code-format for dqm-generators
  Validation/EventGenerator/interface/BPhysicsSpectrum.h
  Validation/EventGenerator/interface/BPhysicsValidation.h
  Validation/EventGenerator/interface/BasicGenParticleValidation.h
  Validation/EventGenerator/interface/BasicHepMCHeavyIonValidation.h
  Validation/EventGenerator/interface/BasicHepMCValidation.h
  Validation/EventGenerator/interface/CaloCellId.h
  Validation/EventGenerator/interface/CaloCellManager.h
  Validation/EventGenerator/interface/DQMHelper.h
  Validation/EventGenerator/interface/DrellYanValidation.h
  Validation/EventGenerator/interface/DuplicationChecker.h
  Validation/EventGenerator/interface/HepMCValidationHelper.h
  Validation/EventGenerator/interface/HiggsValidation.h
  Validation/EventGenerator/interface/PdtPdgMini.h
  Validation/EventGenerator/interface/TTbarSpinCorrHepMCAnalyzer.h
  Validation/EventGenerator/interface/TTbar_GenJetAnalyzer.h
  Validation/EventGenerator/interface/TTbar_GenLepAnalyzer.h
  Validation/EventGenerator/interface/TTbar_Kinematics.h
  Validation/EventGenerator/interface/TauDecay.h
  Validation/EventGenerator/interface/TauDecay_CMSSW.h
  Validation/EventGenerator/interface/TauDecay_GenParticle.h
  Validation/EventGenerator/interface/TauValidation.h
  Validation/EventGenerator/interface/WValidation.h
  Validation/EventGenerator/interface/WeightManager.h
  Validation/EventGenerator/plugins/BPhysicsSpectrum.cc
  Validation/EventGenerator/plugins/BPhysicsValidation.cc
  Validation/EventGenerator/plugins/BasicGenParticleValidation.cc
  Validation/EventGenerator/plugins/BasicHepMCHeavyIonValidation.cc
  Validation/EventGenerator/plugins/BasicHepMCValidation.cc
  Validation/EventGenerator/plugins/DrellYanValidation.cc
  Validation/EventGenerator/plugins/DuplicationChecker.cc
  Validation/EventGenerator/plugins/HiggsValidation.cc
  Validation/EventGenerator/plugins/MBUEandQCDValidation.cc
  Validation/EventGenerator/plugins/MBUEandQCDValidation.h
  Validation/EventGenerator/plugins/Module.cc
  Validation/EventGenerator/plugins/TTbarSpinCorrHepMCAnalyzer.cc
  Validation/EventGenerator/plugins/TTbar_GenJetAnalyzer.cc
  Validation/EventGenerator/plugins/TTbar_GenLepAnalyzer.cc
  Validation/EventGenerator/plugins/TTbar_Kinematics.cc
  Validation/EventGenerator/plugins/TauValidation.cc
  Validation/EventGenerator/plugins/WValidation.cc
  Validation/EventGenerator/plugins/WeightManager.cc
  Validation/EventGenerator/src/CaloCellId.cc
  Validation/EventGenerator/src/CaloCellManager.cc
  Validation/EventGenerator/src/DQMHelper.cc
  Validation/EventGenerator/src/HepMCValidationHelper.cc
  Validation/EventGenerator/src/TauDecay.cc
  Validation/EventGenerator/src/TauDecay_CMSSW.cc
  Validation/EventGenerator/src/TauDecay_GenParticle.cc
  Validation/EventGenerator/src/WeightManager.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, generators-approved, orp-approved, tests-approved

#27085 Fixed incorrect string comparison method in DQM bin by bin comparison tool
  DQMServices/FileIO/scripts/compareDQMOutput.py
  DQMServices/FileIO/scripts/compareHistograms.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27083 Minor style modification to avoid unnecessary line splitting
  EventFilter/CSCTFRawToDigi/src/CSCSPRecord.h
  EventFilter/CSCTFRawToDigi/src/CSCSP_MEblock.h
  EventFilter/CSCTFRawToDigi/src/CSCSP_SPblock.h
  EventFilter/CSCTFRawToDigi/src/CSCTFEvent.cc
  L1Trigger/TrackTrigger/plugins/TTStubBuilder.cc
  L1Trigger/TrackTrigger/src/StubPtConsistency.cc
  L1Trigger/TrackTrigger/src/TTStubAlgorithm_official.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#26999 TkAl All in One tool: don't import crabWrapper
  Alignment/OfflineValidation/scripts/validateAlignments.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27003 Modernized ES modules in TrackingTools/TrackFitters
  TrackingTools/TrackFitters/interface/DebugHelpers.h
  TrackingTools/TrackFitters/interface/KFSplittingFitter.h
  TrackingTools/TrackFitters/interface/KFTrajectoryFitter.h
  TrackingTools/TrackFitters/interface/KFTrajectorySmoother.h
  TrackingTools/TrackFitters/interface/RecHitLessByDet.h
  TrackingTools/TrackFitters/interface/RecHitSorter.h
  TrackingTools/TrackFitters/interface/RecHitSplitter.h
  TrackingTools/TrackFitters/interface/TrajectoryFitter.h
  TrackingTools/TrackFitters/interface/TrajectoryFitterRecord.h
  TrackingTools/TrackFitters/interface/TrajectoryStateCombiner.h
  TrackingTools/TrackFitters/interface/TrajectoryStateWithArbitraryError.h
  TrackingTools/TrackFitters/plugins/FlexibleKFFittingSmootherESProducer.cc
  TrackingTools/TrackFitters/plugins/KFFittingSmoother.h
  TrackingTools/TrackFitters/plugins/KFFittingSmootherESProducer.cc
  TrackingTools/TrackFitters/plugins/KFTrajectoryFitterESProducer.cc
  TrackingTools/TrackFitters/plugins/KFTrajectorySmootherESProducer.cc
  TrackingTools/TrackFitters/src/KFSplittingFitter.cc
  TrackingTools/TrackFitters/src/KFTrajectoryFitter.cc
  TrackingTools/TrackFitters/src/KFTrajectorySmoother.cc
  TrackingTools/TrackFitters/src/RecHitSorter.cc
  TrackingTools/TrackFitters/src/RecHitSplitter.cc
  TrackingTools/TrackFitters/src/TrajectoryStateCombiner.cc
  TrackingTools/TrackFitters/src/TrajectoryStateWithArbitraryError.cc
  TrackingTools/TrackFitters/src/module.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27088 Validation/Geometry: Cleanup
  Validation/Geometry/test/MaterialBudget.py
  Validation/Geometry/test/OvalFile
  Validation/Geometry/test/TrackerGeometryValidation.sh
  Validation/Geometry/test/copyReferenceFiles.sh
  Validation/Geometry/test/copyWWWTrackerGeometry.sh
  Validation/Geometry/test/go
  Validation/Geometry/test/go_debug
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#27011 Added consumes to GlobalDetLayerGeometryESProducer
  TrackingTools/RecoGeometry/plugins/GlobalDetLayerGeometryESProducer.cc
  TrackingTools/RecoGeometry/plugins/GlobalDetLayerGeometryESProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27005 Adjust a few weird clang format updates
  RecoLocalMuon/GEMSegment/plugins/ME0SegAlgoRU.cc
  RecoLocalTracker/SiStripRecHitConverter/src/SiStripRecHitMatcher.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#26783 [106X] MTV : adjust impact parameter selection (backport of #26700)
  Validation/RecoTrack/python/GenParticleSelectionsForEfficiency_cff.py
  Validation/RecoTrack/python/MultiTrackValidatorGenPs_cfi.py
  Validation/RecoTrack/python/TrackingParticleSelectionsForEfficiency_cff.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26826 backport of updated monopole skim
  Configuration/Skimming/python/PDWG_EXOMONOPOLE_cff.py
Labels: comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved

#26876 Fireworks 10_6_X: Support regular exressions in geometry table (backport)
  Fireworks/Core/src/FWGeometryTableManager.cc
Labels: comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#26955 [Backport] Fixed DQM bin by bin tool to upload all produced files to GUI
  DQMServices/FileIO/scripts/compareDQMOutput.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#26970 Change default beamspot from "RoundOpticsHighSigmaZ" to "RoundOpticsLowSigmaZ" [106X backport]
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26804 Move strip tracker partition and ModuleGeometry enums to TrackerTopology.h
  Alignment/CommonAlignmentMonitor/plugins/AlignmentStats.cc
  Alignment/SurveyAnalysis/src/SurveyDataReader.cc
  Alignment/TrackerAlignment/plugins/MCMisalignmentScaler.cc
  Alignment/TrackerAlignment/plugins/TkAlCaOverlapTagger.cc
  Alignment/TrackerAlignment/src/AlignableTrackerBuilder.cc
  Alignment/TrackerAlignment/src/TrackerAlignmentLevelBuilder.cc
  Alignment/TrackerAlignment/test/TrackerGeometryAnalyzer.cc
  CalibFormats/SiStripObjects/src/SiStripDetCabling.cc
  CalibTracker/SiPixelErrorEstimation/src/SiPixelErrorEstimation.cc
  CalibTracker/SiStripCommon/plugins/ShallowClustersProducer.cc
  CalibTracker/SiStripESProducers/plugins/fake/SiStripBackPlaneCorrectionFakeESSource.cc
  CalibTracker/SiStripESProducers/plugins/fake/SiStripBadModuleConfigurableFakeESSource.cc
  CalibTracker/SiStripESProducers/plugins/fake/SiStripLorentzAngleFakeESSource.cc
  CalibTracker/SiStripHitEfficiency/plugins/SiStripHitEffFromCalibTree.cc
  CalibTracker/SiStripLorentzAngle/src/LA_Filler.cc
  CalibTracker/SiStripQuality/plugins/SiStripQualityStatistics.cc
  CalibTracker/SiStripQuality/src/SiStripBadAPVAlgorithmFromClusterOccupancy.cc
  CalibTracker/SiStripQuality/src/SiStripBadAPVandHotStripAlgorithmFromClusterOccupancy.cc
  CalibTracker/SiStripQuality/src/SiStripHotStripAlgorithmFromClusterOccupancy.cc
  CalibTracker/StandaloneTrackerTopology/src/StandaloneTrackerTopology.cc
  CondFormats/SiStripObjects/src/SiStripBackPlaneCorrection.cc
  CondFormats/SiStripObjects/src/SiStripDetSummary.cc
  DQM/SiStripCommissioningSources/plugins/tracking/SiStripFineDelayHit.cc
  DQM/SiStripMonitorClient/plugins/SiStripBadComponentInfo.cc
  DQM/SiStripMonitorSummary/plugins/SiStripCorrelateBadStripAndNoise.cc
  DQM/SiStripMonitorSummary/plugins/SiStripCorrelateNoise.cc
  DQM/SiStripMonitorSummary/plugins/SiStripPlotGain.cc
  DQM/SiStripMonitorSummary/src/SiStripBaseCondObjDQM.cc
  DQM/SiStripMonitorSummary/src/SiStripCablingDQM.cc
  DQM/SiStripMonitorSummary/src/SiStripLorentzAngleDQM.cc
  DQM/SiStripMonitorTrack/src/SiStripMonitorTrack.cc
  DQM/TrackingMonitor/src/TrackingRecoMaterialAnalyser.cc
  DataFormats/L1TrackTrigger/interface/TTTrack.h
  DataFormats/SiStripCluster/interface/SiStripClusterTools.h
  DataFormats/SiStripDetId/interface/SiStripDetId.h
  DataFormats/SiStripDetId/interface/StripSubdetector.h
  DataFormats/TrackerCommon/interface/SiStripEnums.h
  DataFormats/TrackerCommon/interface/TrackerTopology.h
  DataFormats/TrackerCommon/src/TrackerTopology.cc
  FastSimulation/Tracking/src/TrackingLayer.cc
  FastSimulation/TrackingRecHitProducer/src/TrackerDetIdSelector.cc
  Geometry/TrackerGeometryBuilder/src/trackerHierarchy.cc
  RecoLocalTracker/SiStripRecHitConverter/interface/StripCPE.h
  RecoLocalTracker/SiStripRecHitConverter/src/StripCPE.cc
  RecoLocalTracker/SiStripRecHitConverter/src/StripCPEgeometric.cc
  RecoLocalTracker/SubCollectionProducers/src/HITrackClusterRemover.cc
  RecoLocalTracker/SubCollectionProducers/test/ClusterMCsplitStrips.cc
  RecoPixelVertexing/PixelTriplets/plugins/MatchedHitRZCorrectionFromBending.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackerTrackHitFilter.cc
  SimGeneral/TrackingAnalysis/src/TrackingParticleNumberOfLayers.cc
  SimTracker/SiPhase2Digitizer/test/TBeamTest.cc
  SimTracker/SiStripDigitizer/plugins/PreMixingSiStripWorker.cc
  SimTracker/TrackAssociatorProducers/plugins/TrackAssociatorByHitsImpl.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-pending, dqm-approved, fastsim-approved, geometry-approved, l1-pending, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#27084 Validation/Configuration/python/autoValidation.py Phase2 modification
  Validation/Configuration/python/autoValidation.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#27090 Modified OuterTrackerMonitorTrackingParticles to run much faster
  Validation/SiOuterTrackerV/interface/OuterTrackerMonitorTrackingParticles.h
  Validation/SiOuterTrackerV/plugins/OuterTrackerMonitorTrackingParticles.cc
  Validation/SiOuterTrackerV/python/OuterTrackerMonitorTrackingParticles_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27015 Phase2-hcx208 First set of changes for RecHits of HFNose
  DataFormats/HGCRecHit/interface/HGCRecHit.h
  DataFormats/HGCRecHit/interface/HGCRecHitCollections.h
  DataFormats/HGCRecHit/src/HGCRecHit.cc
  RecoLocalCalo/HGCalRecAlgos/interface/RecHitTools.h
  RecoLocalCalo/HGCalRecAlgos/src/RecHitTools.cc
  RecoLocalCalo/HGCalRecProducers/python/HGCalRecHit_cfi.py
  RecoLocalCalo/HGCalRecProducers/python/HGCalUncalibRecHit_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27091 Code format fixes after CMSSW_11_0_X_2019-06-04-1100
  CommonTools/TriggerUtils/interface/PrescaleWeightProvider.h
  CommonTools/TriggerUtils/src/GenericTriggerEventFlag.cc
  DataFormats/EcalRecHit/interface/EcalUncalibratedRecHit.h
  DataFormats/JetReco/src/Jet.cc
  DataFormats/MuonDetId/interface/GEMDetId.h
  DataFormats/MuonDetId/src/GEMDetId.cc
  DataFormats/MuonDetId/test/GEMDetIdAnalyzer.cc
  DataFormats/TrackReco/interface/TrackBase.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitWorkerRecover.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerMultiFit.cc
  RecoLocalCalo/EcalRecProducers/test/EcalCompactTrigPrimProducerTest.cc
  RecoLocalMuon/DTRecHit/plugins/DTTime2DriftParametrization.cc
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentBuilder.cc
  RecoTracker/MeasurementDet/plugins/TkGluedMeasurementDet.cc
  Validation/EventGenerator/interface/BasicHepMCValidation.h
  Validation/EventGenerator/plugins/BasicHepMCValidation.cc
  Validation/EventGenerator/plugins/MBUEandQCDValidation.cc
  Validation/EventGenerator/plugins/TauValidation.cc
  Validation/EventGenerator/plugins/WValidation.cc
  Validation/EventGenerator/src/TauDecay_GenParticle.cc
  Validation/Geometry/interface/MaterialBudget.h
  Validation/Geometry/interface/MaterialBudgetForward.h
  Validation/Geometry/interface/MaterialBudgetHcal.h
  Validation/Geometry/src/MaterialBudgetCastorHistos.cc
  Validation/Geometry/src/MaterialBudgetMtdHistos.cc
  Validation/Geometry/test/CMS_lumi.C
  Validation/Geometry/test/CMS_lumi.h
  Validation/Geometry/test/MaterialBudgetMtd.C
  Validation/Geometry/test/tdrStyle.C
  Validation/MuonGEMHits/src/GEMBaseValidation.cc
  Validation/MuonGEMHits/src/GEMHitsValidation.cc
Labels: analysis-pending, code-checks-approved, comparison-available, dqm-pending, generators-pending, geometry-pending, orp-approved, pending-signatures, reconstruction-approved, simulation-pending, tests-approved, upgrade-pending

#27047 Added consumes to ESProducers in TrackingTools/Producers
  TrackingTools/Producers/interface/AnalyticalPropagatorESProducer.h
  TrackingTools/Producers/interface/BeamHaloPropagatorESProducer.h
  TrackingTools/Producers/interface/SmartPropagatorESProducer.h
  TrackingTools/Producers/interface/StraightLinePropagatorESProducer.h
  TrackingTools/Producers/interface/TrajectoryCleanerESProducer.h
  TrackingTools/Producers/src/AnalyticalPropagatorESProducer.cc
  TrackingTools/Producers/src/BeamHaloPropagatorESProducer.cc
  TrackingTools/Producers/src/SmartPropagatorESProducer.cc
  TrackingTools/Producers/src/StraightLinePropagatorESProducer.cc
  TrackingTools/Producers/src/TrajectoryCleanerESProducer.cc
  TrackingTools/Producers/src/module.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26797 updating SC reg corrector for UL regression: 106X
  RecoEcal/EgammaClusterProducers/python/particleFlowSuperClusterECAL_cfi.py
  RecoEcal/EgammaClusterProducers/src/PFECALSuperClusterProducer.cc
  RecoEgamma/EgammaTools/interface/SCEnergyCorrectorSemiParm.h
  RecoEgamma/EgammaTools/src/SCEnergyCorrectorSemiParm.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26827 Backport PR 26778 to 106X: DyT v2 on up to eta 1p2
  RecoMuon/GlobalTrackingTools/plugins/GlobalTrackQualityProducer.cc
  RecoMuon/GlobalTrackingTools/python/GlobalMuonRefitter_cff.py
  RecoMuon/GlobalTrackingTools/python/GlobalTrajectoryBuilderCommon_cff.py
  RecoMuon/GlobalTrackingTools/src/DynamicTruncation.cc
  RecoMuon/L3MuonProducer/src/L3MuonProducer.cc
Labels: backport-ok, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#26845 NanoAOD developments: 190520 version, part 2 for UL [106X]
  EgammaAnalysis/ElectronTools/test/id_validation/runEleIDTest_CSA14_sc1.py
  EgammaAnalysis/ElectronTools/test/id_validation/runEleIDTest_CSA14_sc1_miniAOD.py
  EgammaAnalysis/ElectronTools/test/id_validation/runEleIDTest_CSA14_sc2.py
  EgammaAnalysis/ElectronTools/test/id_validation/validateWP_Scenario1.C
  EgammaAnalysis/ElectronTools/test/id_validation/validateWP_Scenario2.C
  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
  PhysicsTools/NanoAOD/plugins/GenJetTauTaggerProducer.cc
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/plugins/IsoValueMapProducer.cc
  PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc
  PhysicsTools/NanoAOD/python/common_cff.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/genparticles_cff.py
  PhysicsTools/NanoAOD/python/globals_cff.py
  PhysicsTools/NanoAOD/python/isotracks_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoEgamma/EgammaTools/interface/EleEnergyRetriever.h
  RecoEgamma/EgammaTools/plugins/EG9X105XObjectUpdateModifier.cc
  RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py
  RecoEgamma/EgammaTools/src/MVAVariableHelper.cc
  RecoEgamma/ElectronIdentification/data/ElectronIDVariables.txt
  RecoEgamma/ElectronIdentification/data/ElectronMVAEstimatorRun2Fall17V1Variables.txt
  RecoEgamma/ElectronIdentification/data/ElectronMVAEstimatorRun2Variables.txt
  RecoEgamma/ElectronIdentification/interface/EBEECutValues.h
  RecoEgamma/ElectronIdentification/interface/ElectronMVAEstimatorRun2.h
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleEmHadD1IsoRhoCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleMinEcalEtCut.cc
  RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleTrkPtIsoCut.cc
  RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_tools.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_HEEPV50_CSA14_25ns_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_HEEPV50_CSA14_startup_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_HEEPV50_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_HEEPV71_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/heepElectronID_tools.py
  RecoEgamma/PhotonIdentification/data/PhotonMVAEstimatorRun2VariablesFall17V1p1.txt
  RecoEgamma/PhotonIdentification/data/PhotonMVAEstimatorRun2VariablesSpring16.txt
  RecoEgamma/PhotonIdentification/plugins/cuts/PhoGenericRhoPtScaledCut.cc
  RecoEgamma/PhotonIdentification/python/Identification/cutBasedPhotonID_tools.py
  RecoEgamma/PhotonIdentification/python/PhotonMVAValueMapProducer_cfi.py
  RecoEgamma/PhotonIdentification/python/egmPhotonIDs_cff.py
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved, xpog-approved

#26847 Backport STXS Stage 1.1 to 10_6_X
  GeneratorInterface/RivetInterface/src/HiggsTemplateCrossSections.cc
  SimDataFormats/HTXS/interface/HiggsTemplateCrossSections.h
Labels: comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#26859 Followup of switch to TauId MVA2017v2 for UL
  PhysicsTools/PatAlgos/python/producersLayer1/tauProducer_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/tools/tauTools.py
  RecoTauTag/Configuration/python/HPSPFTaus_cff.py
  RecoTauTag/Configuration/python/RecoTauTag_EventContent_cff.py
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26937 Address warnings raised from L1T DQM for UL reco
  DQM/L1TMonitor/python/L1TStage2uGT_cff.py
  DQMOffline/L1Trigger/python/L1TEtSumJetOffline_cfi.py
Labels: comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#26861 updates to Top-HLT sequence in DQMOffline (backport of #26540)
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  DQMOffline/Trigger/plugins/TopMonitor.cc
  DQMOffline/Trigger/plugins/TopMonitor.h
  DQMOffline/Trigger/python/TopMonitor_cfi.py
  DQMOffline/Trigger/python/TopMonitoring_Client_cff.py
  DQMOffline/Trigger/python/TopMonitoring_cff.py
Labels: comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#27110 Running code-format for daq-l1-reconstruction
  DataFormats/Scalers/interface/BeamSpotOnline.h
  DataFormats/Scalers/interface/DcsStatus.h
  DataFormats/Scalers/interface/L1AcceptBunchCrossing.h
  DataFormats/Scalers/interface/L1TriggerRates.h
  DataFormats/Scalers/interface/L1TriggerScalers.h
  DataFormats/Scalers/interface/Level1TriggerRates.h
  DataFormats/Scalers/interface/Level1TriggerScalers.h
  DataFormats/Scalers/interface/LumiScalers.h
  DataFormats/Scalers/interface/ScalersRaw.h
  DataFormats/Scalers/interface/TimeSpec.h
  DataFormats/Scalers/src/BeamSpotOnline.cc
  DataFormats/Scalers/src/DcsStatus.cc
  DataFormats/Scalers/src/L1AcceptBunchCrossing.cc
  DataFormats/Scalers/src/L1TriggerRates.cc
  DataFormats/Scalers/src/L1TriggerScalers.cc
  DataFormats/Scalers/src/Level1TriggerRates.cc
  DataFormats/Scalers/src/Level1TriggerScalers.cc
  DataFormats/Scalers/src/LumiScalers.cc
  DataFormats/Scalers/src/classes.h
  DataFormats/Scalers/test/ScalersTest.cpp
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, l1-approved, orp-approved, reconstruction-approved, tests-approved

#26998 DD4hep: Augment tested features and enable runing the tests without disabling biglibs
  BigProducts/Simulation/BuildFile.xml
  SimG4Core/DD4hepGeometry/interface/DD4hep_DDDWorld.h
  SimG4Core/DD4hepGeometry/src/DD4hep_DDDWorld.cc
  SimG4Core/DD4hepGeometry/test/plugins/DD4hepTestDDDWorld.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#27036 Backport of HTXS filter to 102X
  GeneratorInterface/GenFilters/interface/HTXSFilter.h
  GeneratorInterface/GenFilters/src/HTXSFilter.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26966 Run2-hcx206 Take care of Phase2 situations for HCAL
  CalibCalorimetry/CaloTPG/src/CaloTPGTranscoderULUT.cc
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
  CalibCalorimetry/HcalPlugins/test/HBHEDarkeningAnalyzer.cc
  CalibCalorimetry/HcalPlugins/test/hbhedarkeninganalyzer_cfg.py
  Geometry/CaloTopology/interface/HcalTopology.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, geometry-approved, l1-approved, orp-approved, tests-approved

#27107 Running code-format for dqm
  DQMServices/FwkIO/plugins/DQMRootOutputModule.cc
  DQMServices/FwkIO/plugins/DQMRootSource.cc
  DQMServices/FwkIO/plugins/format.h
  DQMServices/FwkIO/test/DummyFillDQMStore.cc
  DQMServices/FwkIO/test/DummyReadDQMStore.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27104 Running code-format for dqm-l1
  DQMOffline/L1Trigger/interface/HistDefinition.h
  DQMOffline/L1Trigger/interface/L1TBeamConfiguration.h
  DQMOffline/L1Trigger/interface/L1TCommon.h
  DQMOffline/L1Trigger/interface/L1TDiffHarvesting.h
  DQMOffline/L1Trigger/interface/L1TEGammaOffline.h
  DQMOffline/L1Trigger/interface/L1TEfficiencyHarvesting.h
  DQMOffline/L1Trigger/interface/L1TFillWithinLimits.h
  DQMOffline/L1Trigger/interface/L1TLSBlock.h
  DQMOffline/L1Trigger/interface/L1TMuonDQMOffline.h
  DQMOffline/L1Trigger/interface/L1TRate_Offline.h
  DQMOffline/L1Trigger/interface/L1TStage2CaloLayer2Offline.h
  DQMOffline/L1Trigger/interface/L1TSync_Offline.h
  DQMOffline/L1Trigger/interface/L1TTauOffline.h
  DQMOffline/L1Trigger/src/HistDefinition.cc
  DQMOffline/L1Trigger/src/L1TBeamConfiguration.cc
  DQMOffline/L1Trigger/src/L1TCommon.cc
  DQMOffline/L1Trigger/src/L1TDiffHarvesting.cc
  DQMOffline/L1Trigger/src/L1TEGammaOffline.cc
  DQMOffline/L1Trigger/src/L1TEfficiencyHarvesting.cc
  DQMOffline/L1Trigger/src/L1TFillWithinLimits.cc
  DQMOffline/L1Trigger/src/L1TLSBlock.cc
  DQMOffline/L1Trigger/src/L1TMuonDQMOffline.cc
  DQMOffline/L1Trigger/src/L1TRate_Offline.cc
  DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc
  DQMOffline/L1Trigger/src/L1TSync_Offline.cc
  DQMOffline/L1Trigger/src/L1TTauOffline.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#27109 Running code-format for db-reconstruction
  CondFormats/SiPixelTransient/interface/SiPixelGenError.h
  CondFormats/SiPixelTransient/interface/SiPixelTemplate.h
  CondFormats/SiPixelTransient/interface/SiPixelTemplate2D.h
  CondFormats/SiPixelTransient/interface/SiPixelTemplateDefs.h
  CondFormats/SiPixelTransient/interface/SimplePixel.h
  CondFormats/SiPixelTransient/src/SiPixelGenError.cc
  CondFormats/SiPixelTransient/src/SiPixelTemplate.cc
  CondFormats/SiPixelTransient/src/SiPixelTemplate2D.cc
Labels: code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#27103 Running code-format for generators
  GeneratorInterface/RivetInterface/interface/DQMRivetClient.h
  GeneratorInterface/RivetInterface/interface/ParticleLevelProducer.h
  GeneratorInterface/RivetInterface/interface/RivetAnalysis.h
  GeneratorInterface/RivetInterface/plugins/DQMRivetClient.cc
  GeneratorInterface/RivetInterface/plugins/GenParticles2HepMCConverter.cc
  GeneratorInterface/RivetInterface/plugins/MergedGenParticleProducer.cc
  GeneratorInterface/RivetInterface/plugins/MergedGenParticleProducer.hh
  GeneratorInterface/RivetInterface/plugins/ParticleLevelProducer.cc
  GeneratorInterface/RivetInterface/src/HiggsTemplateCrossSections.cc
  SimDataFormats/HTXS/interface/HiggsTemplateCrossSections.h
  SimDataFormats/HTXS/src/classes.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#26996 Remove lastLayerEE/FH magic numbers and use RecHitTools instead
  RecoLocalCalo/HGCalRecAlgos/interface/ClusterTools.h
  RecoLocalCalo/HGCalRecAlgos/interface/HGCal3DClustering.h
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalDepthPreClusterer.h
  RecoLocalCalo/HGCalRecAlgos/src/ClusterTools.cc
  RecoLocalCalo/HGCalRecAlgos/src/HGCal3DClustering.cc
  RecoLocalCalo/HGCalRecAlgos/src/HGCalDepthPreClusterer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27004 Scenario 2021 with: Detailed Cavern, MB4 Neutron Shields (YB+2, YB-2,…
  Geometry/CMSCommonData/data/cms/2021/v1/cms.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/MuonCommonData/data/csc/2021/v1/csc.xml
  Geometry/MuonCommonData/data/design/2021/v1/muonYoke.xml
  Geometry/MuonCommonData/data/mf/2021/v1/mf.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#27108 Running code-format for analysis-reconstruction-xpog
  DataFormats/NanoAOD/interface/FlatTable.h
  DataFormats/NanoAOD/interface/MergeableCounterTable.h
  DataFormats/NanoAOD/interface/UniqueString.h
  DataFormats/NanoAOD/src/FlatTable.cc
  DataFormats/NanoAOD/src/classes.h
Labels: analysis-approved, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-pending

#27105 Running code-format for analysis-simulation
  TauAnalysis/MCEmbeddingTools/plugins/CaloCleaner.cc
  TauAnalysis/MCEmbeddingTools/plugins/CaloCleaner.h
  TauAnalysis/MCEmbeddingTools/plugins/CollectionMerger.cc
  TauAnalysis/MCEmbeddingTools/plugins/CollectionMerger.h
  TauAnalysis/MCEmbeddingTools/plugins/DYToMuMuGenFilter.cc
  TauAnalysis/MCEmbeddingTools/plugins/EmbeddingLHEProducer.cc
  TauAnalysis/MCEmbeddingTools/plugins/EmbeddingVertexCorrector.cc
  TauAnalysis/MCEmbeddingTools/plugins/MuMuForEmbeddingSelector.cc
  TauAnalysis/MCEmbeddingTools/plugins/MuonDetCleaner.cc
  TauAnalysis/MCEmbeddingTools/plugins/MuonDetCleaner.h
  TauAnalysis/MCEmbeddingTools/plugins/TrackMergeremb.cc
  TauAnalysis/MCEmbeddingTools/plugins/TrackMergeremb.h
  TauAnalysis/MCEmbeddingTools/plugins/TrackerCleaner.cc
  TauAnalysis/MCEmbeddingTools/plugins/TrackerCleaner.h
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27112 Running code-format for alca-reconstruction
  RecoVertex/BeamSpotProducer/interface/BSFitter.h
  RecoVertex/BeamSpotProducer/interface/BSTrkParameters.h
  RecoVertex/BeamSpotProducer/interface/BSpdfsFcn.h
  RecoVertex/BeamSpotProducer/interface/BeamFitter.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotAnalyzer.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotFitPVData.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotFromDB.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotOnlineProducer.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotProducer.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotTreeData.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotWrite2DB.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotWrite2Txt.h
  RecoVertex/BeamSpotProducer/interface/FcnBeamSpotFitPV.h
  RecoVertex/BeamSpotProducer/interface/PVFitter.h
  RecoVertex/BeamSpotProducer/plugins/BeamSpotAnalyzer.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotFakeConditions.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotFromDB.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotOnlineProducer.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotProducer.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotWrite2DB.cc
  RecoVertex/BeamSpotProducer/src/BSFitter.cc
  RecoVertex/BeamSpotProducer/src/BSpdfsFcn.cc
  RecoVertex/BeamSpotProducer/src/BeamFitter.cc
  RecoVertex/BeamSpotProducer/src/BeamSpotTreeData.cc
  RecoVertex/BeamSpotProducer/src/FcnBeamSpotFitPV.cc
  RecoVertex/BeamSpotProducer/src/PVFitter.cc
  RecoVertex/BeamSpotProducer/src/SealModules.cc
  RecoVertex/BeamSpotProducer/test/BeamFit.cc
  RecoVertex/BeamSpotProducer/test/NtupleHelper.cc
  RecoVertex/BeamSpotProducer/test/NtupleHelper.h
  RecoVertex/BeamSpotProducer/test/classes.h
  RecoVertex/BeamSpotProducer/test/global.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26088 First version of DeepVertex b-tagger
  DataFormats/BTauReco/interface/DeepFlavourFeatures.h
  DataFormats/BTauReco/interface/JetFeatures.h
  DataFormats/BTauReco/interface/SeedingTrackFeatures.h
  DataFormats/BTauReco/interface/TrackPairFeatures.h
  DataFormats/BTauReco/src/classes.h
  DataFormats/BTauReco/src/classes_def.xml
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  RecoBTag/FeatureTools/BuildFile.xml
  RecoBTag/FeatureTools/interface/JetConverter.h
  RecoBTag/FeatureTools/interface/SeedingTrackInfoBuilder.h
  RecoBTag/FeatureTools/interface/SeedingTracksConverter.h
  RecoBTag/FeatureTools/interface/TrackPairInfoBuilder.h
  RecoBTag/FeatureTools/plugins/BuildFile.xml
  RecoBTag/FeatureTools/plugins/DeepFlavourTagInfoProducer.cc
  RecoBTag/FeatureTools/src/SeedingTrackInfoBuilder.cc
  RecoBTag/FeatureTools/src/SeedingTracksConverter.cc
  RecoBTag/FeatureTools/src/TrackPairInfoBuilder.cc
  RecoBTag/TensorFlow/interface/tensor_fillers.h
  RecoBTag/TensorFlow/plugins/DeepVertexTFJetTagsProducer.cc
  RecoBTag/TensorFlow/python/pfDeepFlavour_cff.py
  RecoBTag/TensorFlow/src/tensor_fillers.cc
  RecoBTag/TensorFlow/test/test_deepvertex_cfg.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27010 Modernized DetIdAssociatorESProducer
  Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorMuonSystemMap1D.cc
  Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorMuonVsCurvature.cc
  Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorSegmentDifferences.cc
  Alignment/MuonAlignmentAlgorithms/plugins/MuonAlignmentFromReference.cc
  Alignment/MuonAlignmentAlgorithms/test/StandAloneTest.cc
  RecoJets/JetAssociationProducers/src/TrackExtrapolator.cc
  RecoJets/JetProducers/src/JetMuonHitsIDHelper.cc
  SUSYBSMAnalysis/HSCP/src/BetaCalculatorECAL.cc
  TrackingTools/TrackAssociator/interface/DetIdAssociator.h
  TrackingTools/TrackAssociator/plugins/CaloDetIdAssociator.cc
  TrackingTools/TrackAssociator/plugins/CaloDetIdAssociator.h
  TrackingTools/TrackAssociator/plugins/CaloDetIdAssociatorMaker.cc
  TrackingTools/TrackAssociator/plugins/CaloDetIdAssociatorMaker.h
  TrackingTools/TrackAssociator/plugins/DetIdAssociatorESProducer.cc
  TrackingTools/TrackAssociator/plugins/DetIdAssociatorFactory.h
  TrackingTools/TrackAssociator/plugins/DetIdAssociatorMaker.h
  TrackingTools/TrackAssociator/plugins/EcalDetIdAssociator.h
  TrackingTools/TrackAssociator/plugins/EcalDetIdAssociatorMaker.h
  TrackingTools/TrackAssociator/plugins/HODetIdAssociator.h
  TrackingTools/TrackAssociator/plugins/HODetIdAssociatorMaker.h
  TrackingTools/TrackAssociator/plugins/HcalDetIdAssociator.h
  TrackingTools/TrackAssociator/plugins/HcalDetIdAssociatorMaker.cc
  TrackingTools/TrackAssociator/plugins/HcalDetIdAssociatorMaker.h
  TrackingTools/TrackAssociator/plugins/MuonDetIdAssociator.cc
  TrackingTools/TrackAssociator/plugins/MuonDetIdAssociator.h
  TrackingTools/TrackAssociator/plugins/MuonDetIdAssociatorMaker.cc
  TrackingTools/TrackAssociator/plugins/MuonDetIdAssociatorMaker.h
  TrackingTools/TrackAssociator/plugins/PreshowerDetIdAssociator.h
  TrackingTools/TrackAssociator/plugins/PreshowerDetIdAssociatorMaker.h
  TrackingTools/TrackAssociator/plugins/modules.cc
Labels: alca-approved, analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#27050 SiPixel quality harvester for Ultra legacy
  CalibTracker/SiPixelQuality/plugins/BuildFile.xml
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.cc
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.h
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.cc
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.h
  CalibTracker/SiPixelQuality/python/SiPixelStatusHarvester_cfi.py
  CalibTracker/SiPixelQuality/src/SiPixelStatusManager.cc
  CalibTracker/SiPixelQuality/test/step3_SiPixelCalZeroBias_RAW2DIGI_RECO_ALCA.py
  CalibTracker/SiPixelQuality/test/step4_harvest_ALCAHARVEST.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27087 Remove ListOfRecordToMerge configuration parameter from SiPixelQualityESProducer
  CalibTracker/SiPixelESProducers/plugins/SiPixelQualityESProducer.cc
  CalibTracker/SiPixelESProducers/python/SiPixelQualityESProducer_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27092 TkAlignment HipPy condor submission
  Alignment/HIPAlignmentAlgorithm/scripts/submitAndWatchHippy.sh
  Alignment/HIPAlignmentAlgorithm/scripts/submitJobs_py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27093 Returning a lost method call in DQM bin by bin comparison tool
  DQMServices/FileIO/scripts/compareHistograms.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27127 Improvements to PSet Entry implementation
  FWCore/ParameterSet/src/Entry.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27133 Running code-format for geometry
  Geometry/CaloTopology/interface/CaloDirection.h
  Geometry/CaloTopology/interface/CaloSubdetectorTopology.h
  Geometry/CaloTopology/interface/CaloTopology.h
  Geometry/CaloTopology/interface/CaloTowerConstituentsMap.h
  Geometry/CaloTopology/interface/CaloTowerTopology.h
  Geometry/CaloTopology/interface/EcalBarrelHardcodedTopology.h
  Geometry/CaloTopology/interface/EcalBarrelTopology.h
  Geometry/CaloTopology/interface/EcalEndcapHardcodedTopology.h
  Geometry/CaloTopology/interface/EcalEndcapTopology.h
  Geometry/CaloTopology/interface/EcalPreshowerTopology.h
  Geometry/CaloTopology/interface/EcalTrigTowerConstituentsMap.h
  Geometry/CaloTopology/interface/FastTimeTopology.h
  Geometry/CaloTopology/interface/HGCalTopology.h
  Geometry/CaloTopology/interface/HcalTopology.h
  Geometry/CaloTopology/interface/HcalTopologyMode.h
  Geometry/CaloTopology/interface/HcalTopologyRestrictionParser.h
  Geometry/CaloTopology/src/CaloDirection.cc
  Geometry/CaloTopology/src/CaloSubdetectorTopology.cc
  Geometry/CaloTopology/src/CaloTopology.cc
  Geometry/CaloTopology/src/CaloTowerConstituentsMap.cc
  Geometry/CaloTopology/src/CaloTowerTopology.cc
  Geometry/CaloTopology/src/ES_CaloSubdetectorTopology.cc
  Geometry/CaloTopology/src/ES_CaloTopogy.cc
  Geometry/CaloTopology/src/EcalBarrelHardcodedTopology.cc
  Geometry/CaloTopology/src/EcalBarrelTopology.cc
  Geometry/CaloTopology/src/EcalEndcapHardcodedTopology.cc
  Geometry/CaloTopology/src/EcalEndcapTopology.cc
  Geometry/CaloTopology/src/EcalPreshowerTopology.cc
  Geometry/CaloTopology/src/EcalTrigTowerConstituentsMap.cc
  Geometry/CaloTopology/src/FastTimeTopology.cc
  Geometry/CaloTopology/src/HGCalTopology.cc
  Geometry/CaloTopology/src/HcalTopology.cc
  Geometry/CaloTopology/src/HcalTopologyMode.cc
  Geometry/CaloTopology/src/HcalTopologyRestrictionParser.cc
  Geometry/CaloTopology/test/CaloTowerMapTester.cc
  Geometry/CaloTopology/test/CaloTowerTopologyTester.cc
  Geometry/CaloTopology/test/FastTimeTopologyTester.cc
  Geometry/CaloTopology/test/HGCalTopologyTester.cc
  Geometry/CaloTopology/test/HcalDetId2DenseTester.cc
  Geometry/CaloTopology/test/HcalTopologyTester.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27139 Running code-format for dqm
  DQM/TrackingMonitor/interface/GetLumi.h
  DQM/TrackingMonitor/interface/LogMessageMonitor.h
  DQM/TrackingMonitor/interface/TrackAnalyzer.h
  DQM/TrackingMonitor/interface/TrackBuildingAnalyzer.h
  DQM/TrackingMonitor/interface/TrackEfficiencyClient.h
  DQM/TrackingMonitor/interface/TrackEfficiencyMonitor.h
  DQM/TrackingMonitor/interface/TrackSplittingMonitor.h
  DQM/TrackingMonitor/interface/TrackingMonitor.h
  DQM/TrackingMonitor/interface/V0Monitor.h
  DQM/TrackingMonitor/interface/VertexMonitor.h
  DQM/TrackingMonitor/interface/dEdxAnalyzer.h
  DQM/TrackingMonitor/interface/dEdxHitAnalyzer.h
  DQM/TrackingMonitor/src/GetLumi.cc
  DQM/TrackingMonitor/src/LogMessageMonitor.cc
  DQM/TrackingMonitor/src/PackedCandidateTrackValidator.cc
  DQM/TrackingMonitor/src/PrimaryVertexResolution.cc
  DQM/TrackingMonitor/src/TrackAnalyzer.cc
  DQM/TrackingMonitor/src/TrackBuildingAnalyzer.cc
  DQM/TrackingMonitor/src/TrackEfficiencyClient.cc
  DQM/TrackingMonitor/src/TrackEfficiencyMonitor.cc
  DQM/TrackingMonitor/src/TrackSplittingMonitor.cc
  DQM/TrackingMonitor/src/TrackingMonitor.cc
  DQM/TrackingMonitor/src/TrackingRecoMaterialAnalyser.cc
  DQM/TrackingMonitor/src/V0Monitor.cc
  DQM/TrackingMonitor/src/VertexMonitor.cc
  DQM/TrackingMonitor/src/dEdxAnalyzer.cc
  DQM/TrackingMonitor/src/dEdxHitAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27118 Fix use-after-move in CITKPFIsolationSumProducer(ForPUPPI)
  PhysicsTools/IsolationAlgos/plugins/CITKPFIsolationSumProducer.cc
  PhysicsTools/IsolationAlgos/plugins/CITKPFIsolationSumProducerForPUPPI.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#26796 Update of DeepTauID to ver. 2017v2
  DataFormats/MuonDetId/interface/MuonSubdetId.h
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/RecoTau/interface/DeepTauBase.h
  RecoTauTag/RecoTau/plugins/DPFIsolation.cc
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/src/DeepTauBase.cc
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, simulation-approved, tests-approved

#27143 Code format fixes after CMSSW_11_0_X_2019-06-06-2300
  CondFormats/SiPixelTransient/interface/SiPixelGenError.h
  CondFormats/SiPixelTransient/interface/SiPixelTemplate.h
  DataFormats/Luminosity/src/LumiSummary.cc
  DataFormats/MuonReco/interface/MuonSegmentMatch.h
  DataFormats/MuonReco/interface/MuonSelectors.h
  DataFormats/MuonReco/src/MuonSelectors.cc
  DataFormats/TauReco/interface/PFTau.h
  DataFormats/TauReco/interface/PFTauDecayMode.h
  EventFilter/CSCRawToDigi/src/CSCDigiToRaw.cc
  EventFilter/GEMRawToDigi/interface/AMCdata.h
  EventFilter/GEMRawToDigi/interface/VFATdata.h
  EventFilter/SiStripRawToDigi/test/plugins/SiStripDigiAnalyzer.h
  GeneratorInterface/RivetInterface/plugins/GenParticles2HepMCConverter.cc
  RecoCTPPS/PixelLocal/src/RPixPlaneCombinatoryTracking.cc
  RecoEcal/EgammaCoreTools/src/EcalClusterPUCleaningTools.cc
  RecoMET/METProducers/src/HcalNoiseInfoProducer.cc
  RecoMuon/MuonSeedGenerator/src/MuonSeedCreator.cc
  RecoMuon/MuonSeedGenerator/src/RPCSeedPattern.cc
  RecoMuon/MuonSeedGenerator/src/SETPatternRecognition.cc
  RecoMuon/MuonSeedGenerator/src/SETSeedFinder.cc
  RecoParticleFlow/PFTracking/plugins/GoodSeedProducer.cc
  RecoParticleFlow/PFTracking/test/PreIdAnalyzer.cc
  RecoTracker/ConversionSeedGenerators/plugins/PhotonConversionTrajectorySeedProducerFromQuadrupletsAlgo.cc
  RecoTracker/SpecialSeedGenerators/src/BeamHaloPairGenerator.cc
  RecoTracker/SpecialSeedGenerators/src/CosmicRegionalSeedGenerator.cc
  RecoTracker/SpecialSeedGenerators/src/CosmicSeedCreator.cc
  RecoTracker/SpecialSeedGenerators/src/CtfSpecialSeedGenerator.cc
  RecoTracker/TkNavigation/test/NavigationSchoolAnalyzer.cc
  RecoTracker/TrackProducer/interface/TrackProducerAlgorithm.icc
  RecoTracker/TrackProducer/test/FakeCPEFiller.cc
  TrackingTools/TrackFitters/interface/KFTrajectorySmoother.h
  TrackingTools/TrackFitters/plugins/KFFittingSmoother.h
Labels: code-checks-approved, comparison-available, db-pending, generators-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#26864 Follow up on "Remove PFElectronAlgo and PFPhotonAlgo used back in Run 1"
  RecoParticleFlow/PFProducer/interface/PFAlgo.h
  RecoParticleFlow/PFProducer/plugins/PFProducer.cc
  RecoParticleFlow/PFProducer/src/PFAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27102 Running code-format for analysis-db
  CondFormats/JetMETObjects/bin/JetResolution_t.cc
  CondFormats/JetMETObjects/interface/FFTJetCorrTypes.h
  CondFormats/JetMETObjects/interface/FFTJetCorrectorParameters.h
  CondFormats/JetMETObjects/interface/FFTJetLUTTypes.h
  CondFormats/JetMETObjects/interface/FactorizedJetCorrector.h
  CondFormats/JetMETObjects/interface/FactorizedJetCorrectorCalculator.h
  CondFormats/JetMETObjects/interface/JetCorrectionUncertainty.h
  CondFormats/JetMETObjects/interface/JetCorrectorParameters.h
  CondFormats/JetMETObjects/interface/JetCorrectorParametersHelper.h
  CondFormats/JetMETObjects/interface/JetResolution.h
  CondFormats/JetMETObjects/interface/JetResolutionObject.h
  CondFormats/JetMETObjects/interface/METCorrectorParameters.h
  CondFormats/JetMETObjects/interface/MEtXYcorrectParameters.h
  CondFormats/JetMETObjects/interface/QGLikelihoodObject.h
  CondFormats/JetMETObjects/interface/SimpleJetCorrectionUncertainty.h
  CondFormats/JetMETObjects/interface/SimpleJetCorrector.h
  CondFormats/JetMETObjects/interface/Utilities.h
  CondFormats/JetMETObjects/src/FactorizedJetCorrector.cc
  CondFormats/JetMETObjects/src/FactorizedJetCorrectorCalculator.cc
  CondFormats/JetMETObjects/src/JetCorrectionUncertainty.cc
  CondFormats/JetMETObjects/src/JetCorrectorParameters.cc
  CondFormats/JetMETObjects/src/JetCorrectorParametersHelper.cc
  CondFormats/JetMETObjects/src/JetResolution.cc
  CondFormats/JetMETObjects/src/JetResolutionObject.cc
  CondFormats/JetMETObjects/src/METCorrectorParameters.cc
  CondFormats/JetMETObjects/src/MEtXYcorrectParameters.cc
  CondFormats/JetMETObjects/src/SimpleJetCorrectionUncertainty.cc
  CondFormats/JetMETObjects/src/SimpleJetCorrector.cc
  CondFormats/JetMETObjects/src/classes.h
  CondFormats/JetMETObjects/test/JetCorrectorParameters_t.cpp
  CondFormats/JetMETObjects/test/testSerializationJetMETObjects.cpp
Labels: analysis-approved, code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, tests-approved

#27134 Running code-format for reconstruction-upgrade
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegAlgoRR.cc
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegAlgoRR.h
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegFit.cc
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegFit.h
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentAlgorithm.h
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentBuilder.h
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentBuilderPluginFactory.cc
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentBuilderPluginFactory.h
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentProducer.cc
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentProducer.h
  RecoLocalMuon/GEMCSCSegment/test/TestGEMCSCSegmentAnalyzer.cc
Labels: code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, upgrade-pending

#27136 Running code-format for l1-upgrade
  DataFormats/L1TrackTrigger/interface/TTCluster.h
  DataFormats/L1TrackTrigger/interface/TTStub.h
  DataFormats/L1TrackTrigger/interface/TTTrack.h
  DataFormats/L1TrackTrigger/interface/TTTypes.h
  DataFormats/L1TrackTrigger/src/TTCluster.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-pending

#27135 Running code-format for simulation
  SimG4Core/DD4hepGeometry/interface/DD4hep_DDDWorld.h
  SimG4Core/DD4hepGeometry/src/DD4hep_DDDWorld.cc
  SimG4Core/DD4hepGeometry/test/plugins/DD4hepTestDDDWorld.cc
  SimG4Core/DD4hepGeometry/test/plugins/DD4hepTestG4Geometry.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27137 Running code-format for simulation-upgrade
  SimTracker/SiPhase2Digitizer/plugins/DigitizerUtility.h
  SimTracker/SiPhase2Digitizer/plugins/PSPDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PSPDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PSSDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PSSDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizer.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizer.h
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerFwd.h
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PreMixingPhase2TrackerWorker.cc
  SimTracker/SiPhase2Digitizer/plugins/SSDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/SSDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/test/Phase2TrackerMonitorDigi.cc
  SimTracker/SiPhase2Digitizer/test/Phase2TrackerMonitorDigi.h
  SimTracker/SiPhase2Digitizer/test/Phase2TrackerValidateDigi.cc
  SimTracker/SiPhase2Digitizer/test/Phase2TrackerValidateDigi.h
  SimTracker/SiPhase2Digitizer/test/TBeamTest.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#26811 improvements to the HGCHEback digitizer and implementation of a end-of-life scenario for the HGC scintillator section
  L1Trigger/L1THGCal/python/hgcalVFEProducer_cfi.py
  L1Trigger/L1THGCal/src/veryfrontend/HGCalVFESummationImpl.cc
  RecoLocalCalo/HGCalRecProducers/interface/HGCalCLUEAlgo.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalImagingAlgo.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitWorkerSimple.cc
  RecoLocalCalo/HGCalRecProducers/python/HGCalRecHit_cfi.py
  RecoLocalCalo/HGCalRecProducers/python/hgcalLayerClusters_cff.py
  SimCalorimetry/HGCalSimProducers/data/doseParams_3000fb_fluka-3.5.15.9.txt
  SimCalorimetry/HGCalSimProducers/interface/HGCHEbackDigitizer.h
  SimCalorimetry/HGCalSimProducers/python/hgcalDigitizer_cfi.py
  SimCalorimetry/HGCalSimProducers/src/HGCHEbackDigitizer.cc
  SimCalorimetry/HGCalSimProducers/test/BuildFile.xml
  SimCalorimetry/HGCalSimProducers/test/HGCHEbackSignalScalerAnalyzer.cc
  SimCalorimetry/HGCalSimProducers/test/hgchebacksignalscaler_cfg.py
  SimCalorimetry/HcalSimAlgos/test/sipmnonlinearityanalyzer_cfg.py
  SimGeneral/MixingModule/python/digitizers_cfi.py
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#27097 Change PluginFactory to return unique_ptr
  FWCore/PluginManager/interface/PluginFactory.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27144 TkAl MillePede: Make condor submission default
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_fire.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_scriptm.pl
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_setup.py
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_update.py
  Alignment/MillePedeAlignmentAlgorithm/templates/alignment_config.ini
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27121 Phase2-hgx197 Test geometry for HFNose and also TB setups
  Geometry/CaloEventSetup/plugins/CaloGeometryBuilder.cc
  Geometry/HGCalCommonData/python/testTB181XML_cfi.py
  Geometry/HGCalCommonData/test/dumpTBGeometry_cfg.py
  Geometry/HGCalGeometry/test/CaloCellGeometryTester.cc
  Geometry/HGCalGeometry/test/python/runCaloCellGeometryTest_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#27122 Phase2-hgx198 preparing for corner centered wafers
  Geometry/HGCalCommonData/data/hgcalCons/v10/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v9/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v9a/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v9ap/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v9p/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalEE/v10/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalEE/v9/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalEE/v9a/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v10/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v9/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v9a/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v10/hgcalHEsil.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v9/hgcalHEsil.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v9a/hgcalHEsil.xml
  Geometry/HGCalCommonData/interface/HGCalDDDConstants.h
  Geometry/HGCalCommonData/interface/HGCalGeomTools.h
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalCommonData/src/HGCalGeomTools.cc
  Geometry/HGCalGeometry/test/HGCalTestRecHitTool.cc
  Geometry/HGCalGeometry/test/python/testHGCalRecHitTool_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#27045 Slight refactoring of PFEGammaAlgo
  RecoParticleFlow/PFProducer/interface/PFEGammaAlgo.h
  RecoParticleFlow/PFProducer/interface/PFEGammaHeavyObjectCache.h
  RecoParticleFlow/PFProducer/plugins/PFEGammaProducer.cc
  RecoParticleFlow/PFProducer/plugins/PFEGammaProducer.h
  RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27158 Fix assert failure in readLuminosityBlock
  FWCore/Framework/src/LuminosityBlockProcessingStatus.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27132 Use ESGetToken in BufferedBoostIOESProducer
  CondTools/Hcal/interface/BufferedBoostIOESProducer.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#27142 Added dependency on py2-sqlalchemy
  CondTools/RunInfo/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, requires-external, tests-approved

#27147 [TRK Validation] add chi2 and chi2prob plots, and pT-eta plane for efficiency and fake in slices
  Validation/RecoTrack/interface/MTVHistoProducerAlgoForTracker.h
  Validation/RecoTrack/python/PostProcessorTracker_cfi.py
  Validation/RecoTrack/src/MTVHistoProducerAlgoForTracker.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27163 Running code-format for geometry
  Geometry/TrackerGeometryBuilder/interface/PixelGeomDetType.h
  Geometry/TrackerGeometryBuilder/interface/PixelGeomDetUnit.h
  Geometry/TrackerGeometryBuilder/interface/PixelTopologyBuilder.h
  Geometry/TrackerGeometryBuilder/interface/PlaneBuilderForGluedDet.h
  Geometry/TrackerGeometryBuilder/interface/PlaneBuilderFromGeometricDet.h
  Geometry/TrackerGeometryBuilder/interface/ProxyPixelTopology.h
  Geometry/TrackerGeometryBuilder/interface/ProxyStripTopology.h
  Geometry/TrackerGeometryBuilder/interface/RectangularPixelTopology.h
  Geometry/TrackerGeometryBuilder/interface/StackGeomDet.h
  Geometry/TrackerGeometryBuilder/interface/StripGeomDetType.h
  Geometry/TrackerGeometryBuilder/interface/StripGeomDetUnit.h
  Geometry/TrackerGeometryBuilder/interface/StripTopologyBuilder.h
  Geometry/TrackerGeometryBuilder/interface/TrackerGeomBuilderFromGeometricDet.h
  Geometry/TrackerGeometryBuilder/interface/TrackerGeometry.h
  Geometry/TrackerGeometryBuilder/interface/TrackerParametersFromDD.h
  Geometry/TrackerGeometryBuilder/interface/phase1PixelTopology.h
  Geometry/TrackerGeometryBuilder/interface/trackerHierarchy.h
  Geometry/TrackerGeometryBuilder/plugins/TrackerDigiGeometryESModule.cc
  Geometry/TrackerGeometryBuilder/plugins/TrackerDigiGeometryESModule.h
  Geometry/TrackerGeometryBuilder/plugins/TrackerParametersESModule.cc
  Geometry/TrackerGeometryBuilder/plugins/TrackerParametersESModule.h
  Geometry/TrackerGeometryBuilder/src/ES_TrackerGeometry.cc
  Geometry/TrackerGeometryBuilder/src/PixelGeomDetUnit.cc
  Geometry/TrackerGeometryBuilder/src/PixelTopologyBuilder.cc
  Geometry/TrackerGeometryBuilder/src/PlaneBuilderForGluedDet.cc
  Geometry/TrackerGeometryBuilder/src/PlaneBuilderFromGeometricDet.cc
  Geometry/TrackerGeometryBuilder/src/ProxyPixelTopology.cc
  Geometry/TrackerGeometryBuilder/src/ProxyStripTopology.cc
  Geometry/TrackerGeometryBuilder/src/RectangularPixelTopology.cc
  Geometry/TrackerGeometryBuilder/src/StackGeomDet.cc
  Geometry/TrackerGeometryBuilder/src/StripGeomDetType.cc
  Geometry/TrackerGeometryBuilder/src/StripGeomDetUnit.cc
  Geometry/TrackerGeometryBuilder/src/StripTopologyBuilder.cc
  Geometry/TrackerGeometryBuilder/src/TrackerGeomBuilderFromGeometricDet.cc
  Geometry/TrackerGeometryBuilder/src/TrackerGeometry.cc
  Geometry/TrackerGeometryBuilder/src/TrackerParametersFromDD.cc
  Geometry/TrackerGeometryBuilder/src/trackerHierarchy.cc
  Geometry/TrackerGeometryBuilder/test/GeoHierarchyTest.cc
  Geometry/TrackerGeometryBuilder/test/ModuleInfo.cc
  Geometry/TrackerGeometryBuilder/test/TrackerDigiGeometryAnalyzer.cc
  Geometry/TrackerGeometryBuilder/test/TrackerMapTool.cc
  Geometry/TrackerGeometryBuilder/test/TrackerParametersAnalyzer.cc
  Geometry/TrackerGeometryBuilder/test/phase1PixelTopology_t.cpp
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27120 Enable tau validation for phase 2
  DQMOffline/Configuration/python/DQMOffline_cff.py
  FastSimulation/Configuration/python/DQMOfflineMC_cff.py
  Validation/Configuration/python/autoValidation.py
  Validation/RecoTau/python/DQMSequences_cfi.py
  Validation/RecoTau/python/dataTypes/ValidateTausOnZTT_cff.py
  Validation/RecoTau/src/TauTagValidation.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fastsim-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#27161 Running code-format for alca
  CalibTracker/Records/interface/SiPixel2DTemplateDBObjectESProducerRcd.h
  CalibTracker/Records/interface/SiPixelFEDChannelContainerESProducerRcd.h
  CalibTracker/Records/interface/SiPixelGenErrorDBObjectESProducerRcd.h
  CalibTracker/Records/interface/SiPixelTemplateDBObjectESProducerRcd.h
  CalibTracker/Records/interface/SiStripDependentRecords.h
  CalibTracker/Records/src/SiStripDependentRecords.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27155 Added new Run3 relval to the list
  Configuration/Generator/python/ZTT_All_hadronic_14TeV_TuneCUETP8M1_cfi.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27164 Running code-format for analysis
  SUSYBSMAnalysis/HSCP/interface/BetaCalculatorECAL.h
  SUSYBSMAnalysis/HSCP/interface/BetaCalculatorMUON.h
  SUSYBSMAnalysis/HSCP/interface/BetaCalculatorRPC.h
  SUSYBSMAnalysis/HSCP/interface/BetaCalculatorTK.h
  SUSYBSMAnalysis/HSCP/interface/CandidateSelector.h
  SUSYBSMAnalysis/HSCP/plugins/HSCPDeDxInfoProducer.cc
  SUSYBSMAnalysis/HSCP/plugins/HSCPDeDxInfoProducer.h
  SUSYBSMAnalysis/HSCP/plugins/HSCPHLTFilter.cc
  SUSYBSMAnalysis/HSCP/plugins/HSCPTreeBuilder.cc
  SUSYBSMAnalysis/HSCP/plugins/HSCPValidator.cc
  SUSYBSMAnalysis/HSCP/plugins/HSCPValidator.h
  SUSYBSMAnalysis/HSCP/plugins/HSCParticleProducer.cc
  SUSYBSMAnalysis/HSCP/plugins/HSCParticleProducer.h
  SUSYBSMAnalysis/HSCP/plugins/HSCParticleSelector.cc
  SUSYBSMAnalysis/HSCP/plugins/MuonSegmentProducer.cc
  SUSYBSMAnalysis/HSCP/plugins/SimHitShifter.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_HSCPFilter.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_HighPtTrackEcalDetIdProducer.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_MonoPhotonSkimmer.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_ProduceIsolationMap.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_ReduceHcalRecHitCollectionProducer.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_UpdatedMuonInnerTrackRef.cc
  SUSYBSMAnalysis/HSCP/src/BetaCalculatorECAL.cc
  SUSYBSMAnalysis/HSCP/src/BetaCalculatorMUON.cc
  SUSYBSMAnalysis/HSCP/src/BetaCalculatorRPC.cc
  SUSYBSMAnalysis/HSCP/src/BetaCalculatorTK.cc
  SUSYBSMAnalysis/HSCP/src/CandidateSelector.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27156 Run3-sim33 Add testing tool for Geant4/GeantV compatibility
  SimG4CMS/Calo/test/BuildFile.xml
  SimG4CMS/Calo/test/CaloSimHitAnalysis.cc
  SimG4CMS/Calo/test/python/calostepAnalysis_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27162 Running code-format for fastsim
  FastSimulation/Tracking/interface/FastTrackerRecHitSplitter.h
  FastSimulation/Tracking/interface/FastTrackingUtilities.h
  FastSimulation/Tracking/interface/SeedFinder.h
  FastSimulation/Tracking/interface/SeedFinderSelector.h
  FastSimulation/Tracking/interface/SeedMatcher.h
  FastSimulation/Tracking/interface/SeedingTree.h
  FastSimulation/Tracking/interface/TrackingLayer.h
  FastSimulation/Tracking/interface/TrajectorySeedHitCandidate.h
  FastSimulation/Tracking/plugins/ConversionTrackRefFix.cc
  FastSimulation/Tracking/plugins/ConversionTrackRefFix.h
  FastSimulation/Tracking/plugins/ElectronSeedTrackRefFix.cc
  FastSimulation/Tracking/plugins/ElectronSeedTrackRefFix.h
  FastSimulation/Tracking/plugins/FastTrackerRecHitCombiner.cc
  FastSimulation/Tracking/plugins/FastTrackerRecHitMaskProducer.cc
  FastSimulation/Tracking/plugins/PixelTracksProducer.cc
  FastSimulation/Tracking/plugins/PixelTracksProducer.h
  FastSimulation/Tracking/plugins/RecoTrackAccumulator.cc
  FastSimulation/Tracking/plugins/RecoTrackAccumulator.h
  FastSimulation/Tracking/plugins/TrackCandidateProducer.cc
  FastSimulation/Tracking/plugins/TrajectorySeedProducer.cc
  FastSimulation/Tracking/src/SeedFinderSelector.cc
  FastSimulation/Tracking/src/SeedMatcher.cc
  FastSimulation/Tracking/src/TrackingLayer.cc
  FastSimulation/Tracking/src/TrajectorySeedHitCandidate.cc
  FastSimulation/Tracking/test/testGeneralTracks.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#27157 [RFC] Remove FastSimGeometryESProducer as obsolete
  FastSimulation/Configuration/python/Geometries_cff.py
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimGeometryESProducer.cc
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimGeometryESProducer.h
  FastSimulation/SimplifiedGeometryPropagator/python/FastSimGeometryESProducer_cfi.py
  FastSimulation/SimplifiedGeometryPropagator/src/ES_Geometry.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#27167 Running code-format for simulation-upgrade
  SimCalorimetry/HGCalSimProducers/interface/HFNoseDigitizer.h
  SimCalorimetry/HGCalSimProducers/interface/HGCDigitizer.h
  SimCalorimetry/HGCalSimProducers/interface/HGCDigitizerBase.h
  SimCalorimetry/HGCalSimProducers/interface/HGCDigitizerTypes.h
  SimCalorimetry/HGCalSimProducers/interface/HGCEEDigitizer.h
  SimCalorimetry/HGCalSimProducers/interface/HGCFEElectronics.h
  SimCalorimetry/HGCalSimProducers/interface/HGCHEbackDigitizer.h
  SimCalorimetry/HGCalSimProducers/interface/HGCHEfrontDigitizer.h
  SimCalorimetry/HGCalSimProducers/plugins/HGCDigiProducer.cc
  SimCalorimetry/HGCalSimProducers/plugins/HGCDigiProducer.h
  SimCalorimetry/HGCalSimProducers/plugins/PreMixingHGCalWorker.cc
  SimCalorimetry/HGCalSimProducers/src/HFNoseDigitizer.cc
  SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc
  SimCalorimetry/HGCalSimProducers/src/HGCDigitizerBase.cc
  SimCalorimetry/HGCalSimProducers/src/HGCEEDigitizer.cc
  SimCalorimetry/HGCalSimProducers/src/HGCFEElectronics.cc
  SimCalorimetry/HGCalSimProducers/src/HGCHEbackDigitizer.cc
  SimCalorimetry/HGCalSimProducers/src/HGCHEfrontDigitizer.cc
  SimCalorimetry/HGCalSimProducers/test/HGCHEbackSignalScalerAnalyzer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#26892 Adapting EGRegression Modifiers to 106X and adding V3 modifier
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_run2_egamma_2016_cff.py
  Configuration/Eras/python/Modifier_run2_egamma_2017_cff.py
  Configuration/Eras/python/Modifier_run2_egamma_2018_cff.py
  DataFormats/EgammaCandidates/interface/GsfElectron.h
  RecoEgamma/EgammaElectronProducers/python/gedGsfElectronFinalizer_cfi.py
  RecoEgamma/EgammaPhotonProducers/python/gedPhotons_cfi.py
  RecoEgamma/EgammaTools/interface/EgammaRegressionContainer.h
  RecoEgamma/EgammaTools/plugins/EGRegressionModifierV1.cc
  RecoEgamma/EgammaTools/plugins/EGRegressionModifierV2.cc
  RecoEgamma/EgammaTools/plugins/EGRegressionModifierV3.cc
  RecoEgamma/EgammaTools/python/calibratedEgammas_cff.py
  RecoEgamma/EgammaTools/python/regressionModifier_cfi.py
  RecoEgamma/EgammaTools/src/EgammaRegressionContainer.cc
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, requires-external, tests-approved

#27089 Update global tags to include new EGamma regression
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, requires-external, tests-approved

#27173 Fix hcalFraction definition in DeepTauID
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27165 Running code-format for simulation
  DataFormats/MuonDetId/interface/CSCDetId.h
  DataFormats/MuonDetId/interface/CSCIndexer.h
  DataFormats/MuonDetId/interface/CSCTriggerNumbering.h
  DataFormats/MuonDetId/interface/DTBtiId.h
  DataFormats/MuonDetId/interface/DTChamberId.h
  DataFormats/MuonDetId/interface/DTLayerId.h
  DataFormats/MuonDetId/interface/DTSectCollId.h
  DataFormats/MuonDetId/interface/DTSectCollId.icc
  DataFormats/MuonDetId/interface/DTSuperLayerId.h
  DataFormats/MuonDetId/interface/DTTracoId.h
  DataFormats/MuonDetId/interface/DTWireId.h
  DataFormats/MuonDetId/interface/ME0DetId.h
  DataFormats/MuonDetId/interface/MuonSubdetId.h
  DataFormats/MuonDetId/interface/RPCCompDetId.h
  DataFormats/MuonDetId/interface/RPCDetId.h
  DataFormats/MuonDetId/src/CSCDetId.cc
  DataFormats/MuonDetId/src/CSCIndexer.cc
  DataFormats/MuonDetId/src/CSCTriggerNumbering.cc
  DataFormats/MuonDetId/src/DTChamberId.cc
  DataFormats/MuonDetId/src/DTLayerId.cc
  DataFormats/MuonDetId/src/DTSectCollId.cc
  DataFormats/MuonDetId/src/DTSuperLayerId.cc
  DataFormats/MuonDetId/src/DTWireId.cc
  DataFormats/MuonDetId/src/ME0DetId.cc
  DataFormats/MuonDetId/src/RPCCompDetId.cc
  DataFormats/MuonDetId/src/RPCDetId.cc
  DataFormats/MuonDetId/src/classes.h
  DataFormats/MuonDetId/test/CSCDetIdAnalyzer.cc
  DataFormats/MuonDetId/test/RPCDetIdAnalyzer.cc
  DataFormats/MuonDetId/test/testCSCDetId.cc
  DataFormats/MuonDetId/test/testCSCTriggerNumbering.cc
  DataFormats/MuonDetId/test/testDTDetIds.cc
  DataFormats/MuonDetId/test/testME0DetId.cc
  DataFormats/MuonDetId/test/testRPCCompDetId.cc
  DataFormats/MuonDetId/test/testRPCDetId.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27153 Further non-physics refactoring of PFAlgo::processBlock
  RecoParticleFlow/PFProducer/interface/PFAlgo.h
  RecoParticleFlow/PFProducer/src/PFAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#26898 Adding Sistrip DQM Cluster Maps (backport of PR #26897)
  DQM/SiStripMonitorTrack/interface/SiStripMonitorTrack.h
  DQM/SiStripMonitorTrack/src/SiStripMonitorTrack.cc
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27044 Backport of "Turn off Cluster Repair for 0T data (26940)"
  CalibTracker/SiPixelESProducers/plugins/SiPixel2DTemplateDBObjectESProducer.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27086 [Backport] Fixed incorrect string comparison method
  DQMServices/FileIO/scripts/compareDQMOutput.py
  DQMServices/FileIO/scripts/compareHistograms.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27101 Backport for OuterTrackingMonitorTrackingParticle
  Validation/SiOuterTrackerV/interface/OuterTrackerMonitorTrackingParticles.h
  Validation/SiOuterTrackerV/plugins/OuterTrackerMonitorTrackingParticles.cc
  Validation/SiOuterTrackerV/python/OuterTrackerMonitorTrackingParticles_cfi.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27130 Backport of SiPixel quality harvester for Ultra legacy
  CalibTracker/SiPixelQuality/plugins/BuildFile.xml
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.cc
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.h
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.cc
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.h
  CalibTracker/SiPixelQuality/python/SiPixelStatusHarvester_cfi.py
  CalibTracker/SiPixelQuality/src/SiPixelStatusManager.cc
  CalibTracker/SiPixelQuality/test/step3_SiPixelCalZeroBias_RAW2DIGI_RECO_ALCA.py
  CalibTracker/SiPixelQuality/test/step4_harvest_ALCAHARVEST.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#27196 Running code-format for dqm-geometry
  Validation/Geometry/interface/MaterialBudgetHGCalHistos.h
  Validation/Geometry/src/MaterialBudgetAction.cc
  Validation/Geometry/src/MaterialBudgetHGCalHistos.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#27189 Fix python3 interface problem in RecoTauTag/RecoTau
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27203 Adapting EGRegression Modifiers to 106X and adding V3 modifier: 106X
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_run2_egamma_2016_cff.py
  Configuration/Eras/python/Modifier_run2_egamma_2017_cff.py
  Configuration/Eras/python/Modifier_run2_egamma_2018_cff.py
  DataFormats/EgammaCandidates/interface/GsfElectron.h
  RecoEgamma/EgammaElectronProducers/python/gedGsfElectronFinalizer_cfi.py
  RecoEgamma/EgammaPhotonProducers/python/gedPhotons_cfi.py
  RecoEgamma/EgammaTools/interface/EgammaRegressionContainer.h
  RecoEgamma/EgammaTools/plugins/EGRegressionModifierV1.cc
  RecoEgamma/EgammaTools/plugins/EGRegressionModifierV2.cc
  RecoEgamma/EgammaTools/plugins/EGRegressionModifierV3.cc
  RecoEgamma/EgammaTools/python/calibratedEgammas_cff.py
  RecoEgamma/EgammaTools/python/regressionModifier_cfi.py
  RecoEgamma/EgammaTools/src/EgammaRegressionContainer.cc
Labels: comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, requires-external, tests-approved

#27205 Update global tags to include new EGamma regression [10_6_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, requires-external, tests-approved

#27200 add pileup scenario for 2018 ultra legacy (10_6 backport)
  Configuration/StandardSequences/python/Mixing.py
  SimGeneral/MixingModule/python/mix_2018_25ns_UltraLegacy_PoissonOOTPU_cfi.py
Labels: comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#27146 Update of DeepTauID to ver. 2017v2 (backport for UL)
  DataFormats/MuonDetId/interface/MuonSubdetId.h
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/RecoTau/interface/DeepTauBase.h
  RecoTauTag/RecoTau/plugins/DPFIsolation.cc
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/src/DeepTauBase.cc
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: analysis-pending, backport-ok, comparison-available, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved

#27206 GENSIM strings for 10_6_X
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#26814 Adapting MVAVariableHelper to new E/gamma UL format and removal of MultiToken
  PhysicsTools/NanoAOD/python/nano_cff.py
  RecoEgamma/EgammaTools/interface/MVAValueMapProducer.h
  RecoEgamma/EgammaTools/interface/MVAVariableHelper.h
  RecoEgamma/EgammaTools/interface/MVAVariableManager.h
  RecoEgamma/EgammaTools/interface/MultiToken.h
  RecoEgamma/EgammaTools/interface/Utils.h
  RecoEgamma/EgammaTools/src/MVAVariableHelper.cc
  RecoEgamma/ElectronIdentification/interface/ElectronMVAEstimatorRun2.h
  RecoEgamma/ElectronIdentification/plugins/ElectronIDValueMapProducer.cc
  RecoEgamma/ElectronIdentification/plugins/ElectronMVAEstimatorRun2.cc
  RecoEgamma/ElectronIdentification/plugins/ElectronMVANtuplizer.cc
  RecoEgamma/ElectronIdentification/plugins/ElectronMVAValueMapProducer.cc
  RecoEgamma/ElectronIdentification/plugins/VersionedGsfElectronIdProducer.cc
  RecoEgamma/ElectronIdentification/plugins/VersionedPatElectronIdProducer.cc
  RecoEgamma/ElectronIdentification/plugins/plugins.cc
  RecoEgamma/ElectronIdentification/python/ElectronMVAValueMapProducer_cfi.py
  RecoEgamma/ElectronIdentification/python/FWLite.py
  RecoEgamma/ElectronIdentification/test/testElectronMVA_cfg.py
  RecoEgamma/ElectronIdentification/test/test_eleid_fwlite.py
  RecoEgamma/PhotonIdentification/interface/PhotonMVAEstimator.h
  RecoEgamma/PhotonIdentification/plugins/PhotonIDSimpleAnalyzer.cc
  RecoEgamma/PhotonIdentification/plugins/PhotonIDSimpleAnalyzer.h
  RecoEgamma/PhotonIdentification/plugins/PhotonIDValueMapProducer.cc
  RecoEgamma/PhotonIdentification/plugins/PhotonMVAEstimator.cc
  RecoEgamma/PhotonIdentification/plugins/PhotonMVANtuplizer.cc
  RecoEgamma/PhotonIdentification/plugins/PhotonMVAValueMapProducer.cc
  RecoEgamma/PhotonIdentification/plugins/SealModules.cc
  RecoEgamma/PhotonIdentification/plugins/VersionedPhotonIdProducer.cc
  RecoEgamma/PhotonIdentification/plugins/plugins.cc
  RecoEgamma/PhotonIdentification/python/PhotonMVAValueMapProducer_cfi.py
  RecoEgamma/PhotonIdentification/python/photonIDValueMapProducer_cff.py
  RecoEgamma/PhotonIdentification/test/testPhotonMVA_cfg.py
  RecoParticleFlow/PFProducer/python/particleFlowEGamma_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#27116 Validation fixes
  Validation/EventGenerator/plugins/TauValidation.cc
  Validation/EventGenerator/src/HepMCValidationHelper.cc
  Validation/MuonGEMHits/plugins/MuonGEMHitsHarvestor.cc
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, fully-signed, generators-approved, orp-approved, tests-approved

#27159 Merger the .h and .cc of all plugins in RecoParlicleFlow/PFProducer
  RecoParticleFlow/PFProducer/plugins/PFCandidateChecker.cc
  RecoParticleFlow/PFProducer/plugins/PFCandidateChecker.h
  RecoParticleFlow/PFProducer/plugins/PFConcretePFCandidateProducer.cc
  RecoParticleFlow/PFProducer/plugins/PFConcretePFCandidateProducer.h
  RecoParticleFlow/PFProducer/plugins/PFElectronTranslator.cc
  RecoParticleFlow/PFProducer/plugins/PFElectronTranslator.h
  RecoParticleFlow/PFProducer/plugins/PFLinker.cc
  RecoParticleFlow/PFProducer/plugins/PFLinker.h
  RecoParticleFlow/PFProducer/plugins/PFPhotonTranslator.cc
  RecoParticleFlow/PFProducer/plugins/PFPhotonTranslator.h
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerPSEcal.cc
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerPSEcal.h
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackEcal.cc
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackEcal.h
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackHcal.cc
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackHcal.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27174 Reco vertex adjustments
  RecoVertex/NuclearInteractionProducer/src/NuclearLikelihood.cc
  RecoVertex/V0Producer/src/V0Fitter.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27181 update Pixel digitizer thresholds for Run3
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27182 zeroing PF clustering uncertainty
  RecoParticleFlow/PFClusterProducer/interface/PFClusterEMEnergyCorrector.h
  RecoParticleFlow/PFClusterProducer/plugins/CorrectedECALPFClusterProducer.cc
  RecoParticleFlow/PFClusterProducer/src/PFClusterEMEnergyCorrector.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27186 Remove redundant unique_ptr constructor call from DDAlgorithmHandler
  DetectorDescription/Core/src/DDAlgorithmHandler.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#27188 Remove redundant unique_ptr constructor call from InputSourceFactory
  FWCore/Framework/src/InputSourceFactory.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27193 Remove redundant unique_ptr constructor calls from PhysicsTools
  PhysicsTools/IsolationAlgos/plugins/CandIsoDepositProducer.cc
  PhysicsTools/UtilAlgos/interface/Selections.h
  PhysicsTools/UtilAlgos/plugins/ConfigurableAnalysis.cc
  PhysicsTools/UtilAlgos/plugins/NTuplingDevice.cc
  PhysicsTools/UtilAlgos/plugins/PlottingDevice.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27195 Remove redundant unique_ptr constructor call from DigiAccumulatorMixModFactory
  SimGeneral/MixingModule/src/DigiAccumulatorMixModFactory.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27198 Blacklisted more plots from DQM/TimerServices in DQM bin by bin tool
  DQMServices/FileIO/scripts/blacklist.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27199 Adjust clang-format after CMSSW_11_0_X_2019-06-13-1100
  DQM/TrackingMonitor/interface/GetLumi.h
  DataFormats/Math/interface/GeantUnits.h
  DataFormats/MuonDetId/src/CSCDetId.cc
  DataFormats/MuonDetId/src/CSCTriggerNumbering.cc
  DataFormats/MuonDetId/src/DTChamberId.cc
  EventFilter/SiPixelRawToDigi/test/SiPixelRawDumper.cc
  FastSimulation/Tracking/src/SeedFinderSelector.cc
  Geometry/CaloTopology/src/CaloTowerTopology.cc
  PhysicsTools/PatAlgos/plugins/TrackAndVertexUnpacker.cc
  RecoPixelVertexing/PixelTrackFitting/interface/PixelTrackBuilder.h
  RecoPixelVertexing/PixelTrackFitting/src/KFBasedPixelFitter.cc
  RecoPixelVertexing/PixelVertexFinding/src/FastPrimaryVertexWithWeightsProducer.cc
  RecoPixelVertexing/PixelVertexFinding/src/PixelVertexProducer.cc
  RecoTracker/FinalTrackSelectors/plugins/CosmicTrackSplitter.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackCollectionMerger.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackCutClassifier.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackLwtnnClassifier.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackerTrackHitFilter.cc
  SimTracker/SiPhase2Digitizer/plugins/PSPDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/SSDigitizerAlgorithm.cc
Labels: analysis-approved, code-checks-approved, comparison-available, dqm-approved, fastsim-approved, geometry-pending, orp-approved, pending-signatures, reconstruction-approved, simulation-pending, tests-approved, upgrade-approved

#27208 zeroing PF clustering uncertainty : 106X
  RecoParticleFlow/PFClusterProducer/interface/PFClusterEMEnergyCorrector.h
  RecoParticleFlow/PFClusterProducer/plugins/CorrectedECALPFClusterProducer.cc
  RecoParticleFlow/PFClusterProducer/src/PFClusterEMEnergyCorrector.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27209 Fix python3 interface problem in RecoTauTag/RecoTau
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27218 Fix compilation problems with gcc 9 in FWCore/ParameterSet
  FWCore/ParameterSet/src/Entry.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27204 Bug fix in the alternative Geant4 physics list for exotic particles
  SimG4Core/CustomPhysics/interface/CustomPhysicsListSS.h
  SimG4Core/CustomPhysics/src/CustomPhysicsListSS.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#27202 [Backport] Blacklisted more plots from DQM/TimerServices in DQM bin by bin tool
  DQMServices/FileIO/scripts/blacklist.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27211 FWCore/Framework: Move function call outside of assert
  FWCore/Framework/test/stubs/TestModuleChangeLooper.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27212 FWCore/MessageService: Run standAloneTest script with testRunner.cpp
  FWCore/MessageService/test/BuildFile.xml
  FWCore/MessageService/test/standAloneTest.cpp
  FWCore/MessageService/test/testRunner.cpp
  FWCore/MessageService/test/unit_test_outputs/standAloneWithMessageLogger.cerr
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#27154 Avoid shared_ptr in RecoParticleFlow/PFProducer and remove PFSCEnergyCalibration
  RecoParticleFlow/PFClusterTools/interface/PFSCEnergyCalibration.h
  RecoParticleFlow/PFClusterTools/src/PFSCEnergyCalibration.cc
  RecoParticleFlow/PFProducer/interface/PFAlgo.h
  RecoParticleFlow/PFProducer/interface/PFEGammaAlgo.h
  RecoParticleFlow/PFProducer/plugins/PFEGammaProducer.cc
  RecoParticleFlow/PFProducer/plugins/PFProducer.cc
  RecoParticleFlow/PFProducer/python/particleFlow_cfi.py
  RecoParticleFlow/PFProducer/src/PFAlgo.cc
  RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc
  RecoParticleFlow/PFProducer/test/PFEGCandidateTreeMaker.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27049 Merged KDTreeLinkerAlgo and KDTreeLinkerAlgoT
  CommonTools/RecoAlgos/interface/KDTreeLinkerAlgo.h
  CommonTools/RecoAlgos/interface/KDTreeLinkerTools.h
  RecoLocalCalo/HGCalRecAlgos/interface/HGCal3DClustering.h
  RecoLocalCalo/HGCalRecAlgos/interface/KDTreeLinkerAlgoT.h
  RecoLocalCalo/HGCalRecAlgos/interface/KDTreeLinkerToolsT.h
  RecoLocalCalo/HGCalRecAlgos/src/HGCal3DClustering.cc
  RecoLocalCalo/HGCalRecProducers/interface/HGCalImagingAlgo.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalImagingAlgo.cc
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerPSEcal.cc
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackEcal.cc
  RecoParticleFlow/PFProducer/plugins/kdtrees/KDTreeLinkerTrackHcal.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletHLTGenerator.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletLargeTipGenerator.cc
  RecoTracker/TkSeedGenerator/plugins/MultiHitGeneratorFromChi2.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#26875 Add pLHE relvals to standard relval campaign
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#27185 Remove redundant unique_ptr constructor calls from AlCa
  Alignment/CommonAlignmentProducer/interface/AlignmentProducerBase.h
  Alignment/CommonAlignmentProducer/src/AlignmentProducerBase.cc
  Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc
  CalibMuon/DTCalibration/plugins/DTTPAnalyzer.cc
  CalibMuon/DTCalibration/plugins/DTTTrigCalibration.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#27129 Phase2-hcx209 Enable RecHits for HFNose
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalRecHitSimpleAlgo.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalUncalibRecHitWorkerBaseClass.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitProducer.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitWorkerSimple.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitWorkerSimple.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalUncalibRecHitProducer.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalUncalibRecHitProducer.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalUncalibRecHitWorkerWeights.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalUncalibRecHitWorkerWeights.h
  RecoLocalCalo/HGCalRecProducers/python/HGCalUncalibRecHit_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#27131 PF tracks to HF extrapolation for Phase2 (and suppress unnecessary warnings)
  DataFormats/ParticleFlowReco/interface/PFTrajectoryPoint.h
  DataFormats/ParticleFlowReco/src/PFTrack.cc
  RecoParticleFlow/PFTracking/interface/PFTrackTransformer.h
  RecoParticleFlow/PFTracking/src/PFTrackTransformer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#27221 Bugfix after "Adapting MVAVariableHelper to new E/gamma UL format and removal of MultiToken"
  DQMOffline/Trigger/python/EgammaMonitoring_cff.py
  DQMOffline/Trigger/python/HLTEGTnPMonitor_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#27191 Optional python parameters
  Configuration/StandardSequences/python/earlyDeleteSettings_cff.py
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_cfi.py
  FWCore/ParameterSet/interface/ANDGroupDescription.h
  FWCore/ParameterSet/interface/AllowedLabelsDescriptionBase.h
  FWCore/ParameterSet/interface/EmptyGroupDescription.h
  FWCore/ParameterSet/interface/IfExistsDescription.h
  FWCore/ParameterSet/interface/ORGroupDescription.h
  FWCore/ParameterSet/interface/ParameterDescriptionBase.h
  FWCore/ParameterSet/interface/ParameterDescriptionNode.h
  FWCore/ParameterSet/interface/ParameterSetDescription.h
  FWCore/ParameterSet/interface/ParameterSwitch.h
  FWCore/ParameterSet/interface/ParameterWildcardBase.h
  FWCore/ParameterSet/interface/PluginDescription.h
  FWCore/ParameterSet/interface/XORGroupDescription.h
  FWCore/ParameterSet/python/Config.py
  FWCore/ParameterSet/python/MassReplace.py
  FWCore/ParameterSet/python/Mixins.py
  FWCore/ParameterSet/python/Types.py
  FWCore/ParameterSet/src/ANDGroupDescription.cc
  FWCore/ParameterSet/src/AllowedLabelsDescriptionBase.cc
  FWCore/ParameterSet/src/EmptyGroupDescription.cc
  FWCore/ParameterSet/src/IfExistsDescription.cc
  FWCore/ParameterSet/src/ORGroupDescription.cc
  FWCore/ParameterSet/src/ParameterDescriptionBase.cc
  FWCore/ParameterSet/src/ParameterSetDescription.cc
  FWCore/ParameterSet/src/ParameterWildcardBase.cc
  FWCore/ParameterSet/src/XORGroupDescription.cc
  PhysicsTools/PatAlgos/python/tools/helpers.py
  RecoTauTag/RecoTau/test/rerunTauRecoOnMiniAOD.py
Labels: analysis-pending, code-checks-approved, comparison-available, core-approved, operations-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#27229 Confine run_TestSwitchProducer.sh to FWCore
  FWCore/Integration/test/run_TestSwitchProducer.sh
  FWCore/Integration/test/testSwitchProducerMerge_cfg.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved
