Repository cms-sw/cmssw, pull requests merged in 2020-08, with the labels that each got.

#30970 Clean up L1TTrackMatch producers
  L1Trigger/L1TTrackMatch/plugins/L1TkElectronTrackProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkEmParticleProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkFastVertexProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkMuonProducer.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#30996 Phase2-hgx257 Fix the error in workflow 29034.0
  Geometry/HGCalCommonData/test/HGCalNumberingTester.cc
  Geometry/HGCalCommonData/test/python/testHGCalParametersDDD_cfg.py
  Geometry/HGCalGeometry/interface/HGCalGeometry.h
  Geometry/HGCalGeometry/interface/HGCalGeometryLoader.h
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
  Geometry/HGCalGeometry/src/HGCalGeometryLoader.cc
  Geometry/HGCalGeometry/test/HGCalGeomLocatorTester.cc
  Geometry/HGCalGeometry/test/HGCalGeometryCheck.cc
  Geometry/HGCalGeometry/test/HGCalGeometryTester.cc
  Geometry/HGCalGeometry/test/HGCalSizeTester.cc
  Geometry/HGCalGeometry/test/HGCalTestNeighbor.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved, urgent

#30667 cmsRun: By default use jemalloc for non-x86_64 archs too
  FWCore/Framework/bin/BuildFile.xml
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30924 Add DB utilties for SiPixelVCal
  CondCore/SiPixelPlugins/plugins/BuildFile.xml
  CondCore/SiPixelPlugins/plugins/SiPixelVCal_PayloadInspector.cc
  CondCore/SiPixelPlugins/test/testSiPixelPayloadInspector.cpp
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
  CondFormats/SiPixelObjects/interface/SiPixelVCal.h
  CondFormats/SiPixelObjects/src/SiPixelVCal.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30942 Clean BuildFiles in ALCA
  Alignment/CommonAlignmentMonitor/plugins/BuildFile.xml
  Alignment/CommonAlignmentProducer/BuildFile.xml
  Alignment/CommonAlignmentProducer/plugins/BuildFile.xml
  Alignment/LaserAlignment/plugins/BuildFile.xml
  Alignment/LaserAlignmentSimulation/plugins/BuildFile.xml
  Alignment/LaserDQM/plugins/BuildFile.xml
  Alignment/MuonAlignment/BuildFile.xml
  Alignment/TrackerAlignment/plugins/BuildFile.xml
  CalibCalorimetry/EcalCorrectionModules/test/BuildFile.xml
  CalibFormats/SiStripObjects/test/BuildFile.xml
  CalibMuon/DTCalibration/test/BuildFile.xml
  CalibTracker/SiPixelGainCalibration/plugins/BuildFile.xml
  CalibTracker/SiPixelTools/plugins/BuildFile.xml
  CalibTracker/SiStripDCS/test/BuildFile.xml
  CalibTracker/SiStripESProducers/plugins/real/SiStripQualityESProducer.cc
  Calibration/TkAlCaRecoProducers/plugins/BuildFile.xml
  Calibration/Tools/bin/BuildFile.xml
  CaloOnlineTools/EcalTools/bin/BuildFile.xml
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30971 Run3-gem45 Make GEM geometry tp be built from either DDD or DD4Hep
  Geometry/GEMGeometry/interface/GEMChamber.h
  Geometry/GEMGeometry/src/GEMChamber.cc
  Geometry/GEMGeometryBuilder/python/gemGeometry_cff.py
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.cc
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.h
  Geometry/GEMGeometryBuilder/test/BuildFile.xml
  Geometry/GEMGeometryBuilder/test/GEMGeometryDump.cc
  Geometry/GEMGeometryBuilder/test/python/dumpGEMGeometryDD4Hep_cfg.py
  Geometry/GEMGeometryBuilder/test/python/dumpGEMGeometryDDD_cfg.py
  Geometry/GEMGeometryBuilder/test/python/validateGEMGeometryDD4Hep_cfg.py
  Geometry/GEMGeometryBuilder/test/python/validateGEMGeometryDDD_cfg.py
  Geometry/MuonCommonData/data/dd4hep/testGE0XML.xml
  Geometry/MuonCommonData/data/dd4hep/testGEMXML.xml
  Geometry/MuonCommonData/python/testGE0XML_cfi.py
  Geometry/MuonCommonData/python/testGEMXML_cfi.py
  Geometry/MuonNumbering/interface/CSCNumberingScheme.h
  Geometry/MuonNumbering/interface/DTNumberingScheme.h
  Geometry/MuonNumbering/interface/GEMNumberingScheme.h
  Geometry/MuonNumbering/interface/ME0NumberingScheme.h
  Geometry/MuonNumbering/interface/MuonNumberingScheme.h
  Geometry/MuonNumbering/interface/MuonSimHitNumberingScheme.h
  Geometry/MuonNumbering/interface/RPCNumberingScheme.h
  Geometry/MuonNumbering/src/CSCNumberingScheme.cc
  Geometry/MuonNumbering/src/DTNumberingScheme.cc
  Geometry/MuonNumbering/src/GEMNumberingScheme.cc
  Geometry/MuonNumbering/src/ME0NumberingScheme.cc
  Geometry/MuonNumbering/src/MuonGeometryNumbering.cc
  Geometry/MuonNumbering/src/MuonNumberingScheme.cc
  Geometry/MuonNumbering/src/MuonSimHitNumberingScheme.cc
  Geometry/MuonNumbering/src/RPCNumberingScheme.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30985 modernized modules in Calibration/EcalAlCaRecoProducers
  Calibration/EcalAlCaRecoProducers/plugins/AlCaECALRecHitReducer.cc
  Calibration/EcalAlCaRecoProducers/plugins/AlCaECALRecHitReducer.h
  Calibration/EcalAlCaRecoProducers/plugins/AlCaElectronTracksReducer.cc
  Calibration/EcalAlCaRecoProducers/plugins/AlCaElectronTracksReducer.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30987 Modernized HLTMuonPointingFilter
  HLTrigger/special/plugins/HLTMuonPointingFilter.cc
  HLTrigger/special/plugins/HLTMuonPointingFilter.h
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#31007 Modernize MuonTrackProducer
  SimMuon/MCTruth/plugins/MuonTrackProducer.cc
  SimMuon/MCTruth/plugins/MuonTrackProducer.h
  SimMuon/MCTruth/plugins/SealModule.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30994 Made AlignmentMuonSelectorModule a stream module
  Alignment/CommonAlignmentProducer/plugins/AlignmentMuonSelectorModule.cc
  CommonTools/RecoAlgos/interface/MuonSelector.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31001 make LSNumberFilter a stream module
  Alignment/CommonAlignmentProducer/plugins/LSNumberFilter.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31008 Replace snprintf() and string copies with fmt::format() in Validation/Mixing/src/GlobalTest.cc
  Validation/Mixing/BuildFile.xml
  Validation/Mixing/interface/GlobalTest.h
  Validation/Mixing/src/GlobalTest.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31022 Update OscarMTProducer initialisation
  SimG4Core/Application/plugins/OscarMTProducer.cc
  SimG4Core/Application/plugins/OscarMTProducer.h
  SimG4Core/Application/plugins/OscarProducer.cc
  SimG4Core/Application/plugins/OscarProducer.h
  SimG4Core/Application/src/RunManagerMTWorker.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31014 HCAL MC: adding pulse shape 208 for signal reconstruction
  CalibCalorimetry/HcalAlgos/interface/HcalPulseShapes.h
  CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc
  SimCalorimetry/HcalSimAlgos/src/HcalShapes.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31011 Modernize modules in CalibTracker/SiStripCommon
  CalibTracker/SiStripCommon/interface/ShallowEventDataProducer.h
  CalibTracker/SiStripCommon/interface/ShallowGainCalibration.h
  CalibTracker/SiStripCommon/interface/ShallowTracksProducer.h
  CalibTracker/SiStripCommon/plugins/ShallowEventDataProducer.cc
  CalibTracker/SiStripCommon/plugins/ShallowGainCalibration.cc
  CalibTracker/SiStripCommon/plugins/ShallowTracksProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30696 Add DMQ FakeBeamMonitor plugin and clients - backport to 11_1_X
  DQM/BeamMonitor/plugins/BuildFile.xml
  DQM/BeamMonitor/plugins/FakeBeamMonitor.cc
  DQM/BeamMonitor/plugins/FakeBeamMonitor.h
  DQM/BeamMonitor/python/FakeBeamMonitor_cff.py
  DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhltfake_dqm_sourceclient-live_cfg.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31017 Update HLT jet energy corrections in offline GTs [11_1_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30999 Conditions needed to introduce pedestal correlation coefficient for HB and HE channels and update pedestal widths for 2023/2024
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30989 Moving to Digi Geometry for L1 Hitless Seeding
  RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromL1TTracksEDProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30951 Add packed TDC information to HBHERecHit
  DataFormats/HcalRecHit/interface/HBHERecHit.h
  DataFormats/HcalRecHit/src/classes_def.xml
  DataFormats/HcalRecHit/test/HcalRecHitDump.cc
  RecoLocalCalo/HcalRecProducers/src/HBHEPhase1Reconstructor.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30982 Clean up L1TTrackMatch producers [11_1_X]
  L1Trigger/L1TTrackMatch/plugins/L1TkElectronTrackProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkEmParticleProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkFastVertexProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkMuonProducer.cc
Labels: backport-ok, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#31025 Remove unnecessary includes to FWCore/ParameterSet
  DataFormats/Provenance/src/Provenance.cc
  DataFormats/Provenance/src/StableProvenance.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31028 Revert #29562 and use only low-quality ALCTs in ME2/1
  L1Trigger/CSCCommonTrigger/interface/CSCConstants.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCBaseboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/python/cscTriggerPrimitiveDigis_cfi.py
  L1Trigger/CSCTriggerPrimitives/src/CSCAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCBaseboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeCathodeLCTProcessor.cc
Labels: code-checks-approved, comparison-pending, l1-pending, orp-approved, pending-signatures, tests-approved

#31027 Revert #29562 and use only low-quality ALCTs in ME2/1
  L1Trigger/CSCCommonTrigger/interface/CSCConstants.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCBaseboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/python/cscTriggerPrimitiveDigis_cfi.py
  L1Trigger/CSCTriggerPrimitives/src/CSCAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCBaseboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeCathodeLCTProcessor.cc
Labels: comparison-pending, l1-pending, orp-approved, pending-signatures, tests-approved

#30935 106X backport of: Pile-Up ID training and WPs for 2017 UL samples
  RecoJets/JetProducers/interface/PileupJetIdAlgo.h
  RecoJets/JetProducers/python/PileupJetIDCutParams_cfi.py
  RecoJets/JetProducers/python/PileupJetIDParams_cfi.py
  RecoJets/JetProducers/python/PileupJetID_cfi.py
  RecoJets/JetProducers/src/PileupJetIdAlgo.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#30983 Modernize modules in Calibration/HcalAlCaRecoProducers
  Calibration/HcalAlCaRecoProducers/interface/AlCaEcalHcalReadoutsProducer.h
  Calibration/HcalAlCaRecoProducers/plugins/PrescalerFHN.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaEcalHcalReadoutsProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaGammaJetProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaHOCalibProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31016 Minor updates to Sonic (Core and Triton)
  HeterogeneousCore/SonicCore/src/SonicClientBase.cc
  HeterogeneousCore/SonicTriton/README.md
  HeterogeneousCore/SonicTriton/interface/TritonData.h
  HeterogeneousCore/SonicTriton/interface/triton_utils.h
  HeterogeneousCore/SonicTriton/src/TritonClient.cc
  HeterogeneousCore/SonicTriton/src/TritonData.cc
  HeterogeneousCore/SonicTriton/src/triton_utils.cc
  HeterogeneousCore/SonicTriton/test/TritonGraphProducer.cc
  HeterogeneousCore/SonicTriton/test/TritonImageProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#30892 106X backport of #30738 (Use dxy sign of GSF track instead of IPTools for pat::Electron)
  PhysicsTools/PatAlgos/plugins/PATElectronProducer.cc
  PhysicsTools/PatAlgos/plugins/PATElectronProducer.h
  PhysicsTools/PatAlgos/python/producersLayer1/electronProducer_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
Labels: analysis-pending, backport-ok, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#30896 [10_6_X] Validate GsfElectron before running MVA to avoid reading wrong DataFormat (#30052)
  PhysicsTools/PatAlgos/plugins/ModifiedObjectProducers.cc
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoEgamma/EgammaTools/interface/MVAValueMapProducer.h
  RecoEgamma/EgammaTools/interface/validateEgammaCandidate.h
  RecoEgamma/EgammaTools/python/gedGsfElectronsTo106X_cff.py
  RecoEgamma/EgammaTools/src/validateEgammaCandidate.cc
Labels: analysis-pending, backport-ok, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#30936 PFProducer fix for PFMuonAlgo's fillPSetDescription
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoHI/Configuration/python/Reconstruction_hiPF_cff.py
  RecoParticleFlow/PFProducer/interface/PFMuonAlgo.h
  RecoParticleFlow/PFProducer/plugins/PFProducer.cc
  RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporterWithVeto.cc
  RecoParticleFlow/PFProducer/python/particleFlowBlock_cfi.py
  RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#30291 Add DeepMET into NanoAOD
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/PatAlgos/plugins/RecoMETExtractor.cc
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#30665 Clang tidy checks - add new checks to .clang-tidy
  .clang-tidy
Labels: code-checks-approved, comparison-pending, core-approved, fully-signed, orp-approved, tests-approved

#30990 Moving to Digi Geometry
  RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromL1TTracksEDProducer.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31004 Improvements for the DB credentials infrastructure
  CondCore/CondDB/interface/Auth.h
  CondCore/CondDB/interface/CredentialStore.h
  CondCore/CondDB/plugins/BuildFile.xml
  CondCore/CondDB/plugins/CondDBPyBind11Wrappers.cc
  CondCore/CondDB/src/CredentialStore.cc
  CondCore/Utilities/bin/cmscond_authentication_manager.cpp
  CondCore/Utilities/python/conddblib.py
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#31042 Add SiPixelGenErrorDBObject payload inspector
  CondCore/SiPixelPlugins/interface/SiPixelPayloadInspectorHelper.h
  CondCore/SiPixelPlugins/plugins/BuildFile.xml
  CondCore/SiPixelPlugins/plugins/SiPixelGenErrorDBObject_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelTemplateDBObject_PayloadInspector.cc
  CondCore/SiPixelPlugins/test/testSiPixelPayloadInspector.cpp
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30934 add centrality bin to HI miniAOD
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  RecoHI/HiCentralityAlgos/plugins/CentralityBinProducer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#30967 Moving boost dependency to c++ stl alternatives in CommonTools/Utils
  CommonTools/Utils/src/AnyMethodArgument.h
  CommonTools/Utils/src/MethodInvoker.cc
  CommonTools/Utils/src/findMethod.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#30988 Shorten upgrade workflow names, reorganize premixing workflow setup and add to PR tests for phase 2
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/MatrixReader.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
  Configuration/StandardSequences/python/Mixing.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, pdmv-approved, requires-external, tests-approved, upgrade-approved

#31032 Run3-hcx262 Modify the material budget analysis code for HCAL
  Validation/Geometry/interface/MaterialBudgetHcalHistos.h
  Validation/Geometry/src/MaterialBudgetHcalHistos.cc
  Validation/Geometry/test/MatBudgetHcal.C
  Validation/Geometry/test/runP_HCAL_Debug_cfg.py
  Validation/Geometry/test/runP_HCAL_Debug_dd4hep_cfg.py
  Validation/Geometry/test/runP_HCAL_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#30857 Migrate DQM from boost::format to {fmt}
  DQM/HLTEvF/plugins/TriggerBxMonitor.cc
  DQM/HLTEvF/plugins/TriggerRatesMonitor.cc
  DQMServices/FileIO/plugins/DQMFileSaverPB.cc
  DQMServices/StreamerIO/plugins/DQMFileIterator.cc
  DQMServices/StreamerIO/plugins/DQMMonitoringService.cc
  DQMServices/StreamerIO/plugins/JsonWritingTimeoutPoolOutputModule.cc
  DQMServices/StreamerIO/plugins/RamdiskMonitor.cc
  DQMServices/StreamerIO/test/DQMStreamerOutputRepackerTest.cc
  DQMServices/StreamerIO/test/DQMStreamerWriteJsonAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#30992 phase-2 reco CPU hotspot: PFElecTkProducer
  DataFormats/ParticleFlowReco/interface/PFRecTrack.h
  RecoParticleFlow/PFTracking/plugins/PFElecTkProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31029 Don't use an uninitialized edm::Hande in GEDPhotonProducer
  RecoEgamma/EgammaPhotonProducers/interface/GEDPhotonProducer.h
  RecoEgamma/EgammaPhotonProducers/src/GEDPhotonProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31035 Don't use uninitialized edm::Handle in AnalyticalTrackSelector
  RecoTracker/FinalTrackSelectors/plugins/AnalyticalTrackSelector.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31041 Add ghost LCTs in CSC stub matcher
  Validation/MuonCSCDigis/interface/CSCStubMatcher.h
  Validation/MuonCSCDigis/python/muonCSCStubPSet.py
  Validation/MuonCSCDigis/src/CSCDigiMatcher.cc
  Validation/MuonCSCDigis/src/CSCStubMatcher.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31024 Remove data folder of SimG4CMS/Forward
  SimG4CMS/Forward/data/download.url
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31018 Fix circular dependencies between Geometry packages
  DataFormats/GeometryCommonDetAlgo/interface/ErrorFrameTransformer.h
  DataFormats/GeometryCommonDetAlgo/interface/LocalErrorBaseExtended.h
  DataFormats/GeometryCommonDetAlgo/interface/LocalErrorExtended.h
  Geometry/CommonTopologies/interface/MuonGeomDet.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#31039 Fix improper static_cast in HcalAmplifier (part 2)
  SimCalorimetry/HcalSimAlgos/src/HcalAmplifier.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30965 Online BeamSpot ESProducer for Run3 workflow
  CondFormats/DataRecord/interface/BeamSpotTransientObjectsRcd.h
  RecoVertex/BeamSpotProducer/plugins/BuildFile.xml
  RecoVertex/BeamSpotProducer/plugins/OfflineToTransientBeamSpotESProducer.cc
  RecoVertex/BeamSpotProducer/plugins/OnlineBeamSpotESProducer.cc
  RecoVertex/BeamSpotProducer/plugins/OnlineBeamSpotFromDB.cc
  RecoVertex/BeamSpotProducer/test/readOnlineBeamSpotFromDB.py
Labels: alca-pending, code-checks-approved, comparison-available, db-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#30866 Clean BuildFiles in GeneratorInterface
  GeneratorInterface/AMPTInterface/test/BuildFile.xml
  GeneratorInterface/BeamHaloGenerator/BuildFile.xml
  GeneratorInterface/CascadeInterface/BuildFile.xml
  GeneratorInterface/CascadeInterface/plugins/BuildFile.xml
  GeneratorInterface/Core/plugins/BuildFile.xml
  GeneratorInterface/CosmicMuonGenerator/BuildFile.xml
  GeneratorInterface/ExhumeInterface/BuildFile.xml
  GeneratorInterface/ExhumeInterface/test/BuildFile.xml
  GeneratorInterface/ExternalDecays/BuildFile.xml
  GeneratorInterface/ExternalDecays/test/BuildFile.xml
  GeneratorInterface/Herwig6Interface/BuildFile.xml
  GeneratorInterface/Herwig6Interface/plugins/BuildFile.xml
  GeneratorInterface/Herwig7Interface/BuildFile.xml
  GeneratorInterface/HiGenCommon/BuildFile.xml
  GeneratorInterface/HiGenCommon/plugins/BuildFile.xml
  GeneratorInterface/Hydjet2Interface/BuildFile.xml
  GeneratorInterface/Hydjet2Interface/test/BuildFile.xml
  GeneratorInterface/HydjetInterface/test/BuildFile.xml
  GeneratorInterface/LHEInterface/BuildFile.xml
  GeneratorInterface/LHEInterface/plugins/BuildFile.xml
  GeneratorInterface/MCatNLOInterface/plugins/BuildFile.xml
  GeneratorInterface/MCatNLOInterface/test/BuildFile.xml
  GeneratorInterface/PartonShowerVeto/BuildFile.xml
  GeneratorInterface/PomwigInterface/BuildFile.xml
  GeneratorInterface/PomwigInterface/plugins/BuildFile.xml
  GeneratorInterface/PomwigInterface/test/BuildFile.xml
  GeneratorInterface/PyquenInterface/test/BuildFile.xml
  GeneratorInterface/Pythia6Interface/BuildFile.xml
  GeneratorInterface/Pythia6Interface/test/BuildFile.xml
  GeneratorInterface/Pythia8Interface/test/BuildFile.xml
  GeneratorInterface/RivetInterface/BuildFile.xml
  GeneratorInterface/RivetInterface/plugins/BuildFile.xml
  GeneratorInterface/SherpaInterface/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#31048 Add missing pair dictionaries in DataFormats/GEMDigi
  DataFormats/GEMDigi/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#31031 Don't use uninitialized edm::Handle in TrackstersProducer
  RecoHGCal/TICL/plugins/TrackstersProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#30698 DQM: Use ProcessBlock in Harvesting
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.cc
  CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.h
  CalibTracker/SiStripChannelGain/interface/SiStripGainsPCLWorker.h
  CalibTracker/SiStripChannelGain/src/SiStripGainsPCLWorker.cc
  DQM/SiPixelPhase1Summary/python/SiPixelPhase1Summary_cfi.py
  DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
  DQMOffline/CalibTracker/src/StatisticsFilter.cc
  DQMOffline/Trigger/interface/DQMOfflineHLTEventInfoClient.h
  DQMOffline/Trigger/interface/HLTInclusiveVBFClient.h
  DQMOffline/Trigger/plugins/DQMOfflineHLTEventInfoClient.cc
  DQMOffline/Trigger/plugins/HLTInclusiveVBFClient.cc
  DQMOffline/Trigger/plugins/HLTOverallSummary.cc
  DQMServices/Components/plugins/DQMDaqInfo.cc
  DQMServices/Components/plugins/DQMDaqInfo.h
  DQMServices/Components/plugins/DQMFileSaver.cc
  DQMServices/Components/plugins/DQMLumiMonitor.cc
  DQMServices/Components/plugins/DQMLumiMonitor.h
  DQMServices/Components/plugins/DQMMessageLoggerClient.cc
  DQMServices/Components/plugins/DQMMessageLoggerClient.h
  DQMServices/Components/plugins/EDMtoMEConverter.h
  DQMServices/Components/plugins/MEtoEDMConverter.cc
  DQMServices/Components/plugins/MEtoEDMConverter.h
  DQMServices/Core/README.md
  DQMServices/Core/interface/DQMEDHarvester.h
  DQMServices/Demo/test/TestHarvester.cc
  DQMServices/Demo/test/runtests.sh
  Validation/RecoTau/plugins/DQMHistNormalizer.cc
  Validation/RecoTau/plugins/DQMHistPlotter.h
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30867 Memory efficient implementation of timing information for HGCDigitizer module for Premix Workflow.
  SimCalorimetry/HGCalSimProducers/interface/HGCDigitizer.h
  SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#31006 Phase2-hgx258 Correct V14 geometry for dd4hep
  Geometry/HGCalCommonData/data/dd4hep/testHGCalV12.xml
  Geometry/HGCalCommonData/data/dd4hep/testHGCalV13.xml
  Geometry/HGCalCommonData/data/dd4hep/testHGCalV14.xml
  Geometry/HGCalCommonData/data/hgcalEE/v14/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v14/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v14/hgcalHEsil.xml
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalHEFileAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31020 Introduce Run 3 cosmics workflow using express GT
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31050 Fix HLT JEC conditions for 2018 MC
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31058 Run3-gem46 Make 2 constants public (used in GeometryBuilder)
  DataFormats/MuonDetId/interface/GEMDetId.h
  DataFormats/MuonDetId/interface/ME0DetId.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31062 HCAL MC: adding pulse shape 208 for signal reconstruction (11_1_X)
  CalibCalorimetry/HcalAlgos/interface/HcalPulseShapes.h
  CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc
  SimCalorimetry/HcalSimAlgos/src/HcalShapes.cc
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30674 Major updates for Custom JME NanoAODs
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/PatAlgos/python/tools/jetCollectionTools.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#30928 Throw if dereference an unset edm::Handle
  DataFormats/Common/src/HandleBase.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31060 fix premix nano step
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31036 New ParticleNet training for UL
  RecoBTag/ONNXRuntime/python/pfParticleNet_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#30906 Refactor parts of the thinning code
  DataFormats/Common/interface/EDProductGetter.h
  DataFormats/Common/interface/Ptr.h
  DataFormats/Common/interface/RefCore.h
  DataFormats/Common/interface/RefCoreGet.h
  DataFormats/Common/interface/RefItemGet.h
  DataFormats/Common/interface/ThinnedAssociation.h
  DataFormats/Common/interface/getThinned_implementation.h
  DataFormats/Common/src/RefCore.cc
  DataFormats/Common/src/ThinnedAssociation.cc
  DataFormats/Common/test/DetSetVector_t.cpp
  DataFormats/Common/test/SimpleEDProductGetter.h
  DataFormats/Common/test/ptr_t.cppunit.cc
  DataFormats/Common/test/ptrvector_t.cppunit.cc
  DataFormats/Common/test/ref_t.cppunit.cc
  DataFormats/Common/test/reftobaseprod_t.cppunit.cc
  DataFormats/FWLite/interface/ChainEvent.h
  DataFormats/FWLite/interface/DataGetterHelper.h
  DataFormats/FWLite/interface/Event.h
  DataFormats/FWLite/interface/MultiChainEvent.h
  DataFormats/FWLite/src/ChainEvent.cc
  DataFormats/FWLite/src/DataGetterHelper.cc
  DataFormats/FWLite/src/Event.cc
  DataFormats/FWLite/src/MultiChainEvent.cc
  DataFormats/Provenance/interface/ThinnedAssociationsHelper.h
  DataFormats/Provenance/src/ThinnedAssociationsHelper.cc
  DataFormats/Provenance/src/classes_def.xml
  FWCore/FWLite/src/BareRootProductGetter.cc
  FWCore/FWLite/src/BareRootProductGetter.h
  FWCore/Framework/interface/EventPrincipal.h
  FWCore/Framework/interface/Principal.h
  FWCore/Framework/interface/stream/ThinningProducer.h
  FWCore/Framework/src/EventPrincipal.cc
  FWCore/Framework/src/Principal.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Integration/test/ThinningThingProducer.cc
  IOPool/Streamer/interface/StreamerInputSource.h
  IOPool/Streamer/src/StreamerInputSource.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30430 Trackjets as seeds of JetPlusTrack at RECO and MINIAOD
  CommonTools/RecoAlgos/plugins/TrackFromPackedCandidateProducer.cc
  RecoJets/JetPlusTracks/plugins/BuildFile.xml
  RecoJets/JetPlusTracks/plugins/JetPlusTrackAddonSeedProducer.cc
  RecoJets/JetPlusTracks/plugins/JetPlusTrackCorrector.cc
  RecoJets/JetPlusTracks/plugins/JetPlusTrackCorrector.h
  RecoJets/JetPlusTracks/plugins/JetPlusTrackProducer.cc
  RecoJets/JetPlusTracks/plugins/JetPlusTrackProducer.h
  RecoJets/JetPlusTracks/plugins/JetPlusTrackProducerAA.cc
  RecoJets/JetPlusTracks/plugins/JetPlusTrackProducerAA.h
  RecoJets/JetPlusTracks/plugins/SimpleZSPJPTJetCorrector.cc
  RecoJets/JetPlusTracks/plugins/ZSPJPTJetCorrector.cc
  RecoJets/JetPlusTracks/python/JetPlusTrackCorrectionsAA_cff.py
  RecoJets/JetPlusTracks/python/JetPlusTrackCorrections_cff.py
  RecoJets/JetPlusTracks/python/JetPlusTrackCorrections_cfi.py
  RecoJets/JetPlusTracks/python/PATJetPlusTrackCorrections_cff.py
  RecoJets/JetPlusTracks/test/JetShapeJPTAnalysis_mc_s_sql_qcd_pat2.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-pending, reconstruction-approved, tests-approved

#31057 Remove L1Tk paths defined in L1TkObjectProducers_cff.py
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/L1TTrackMatch/python/L1TkObjectProducers_cff.py
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#30883 [HGCAL trigger] Updated trigger towers (+minor updates)
  L1Trigger/L1THGCal/interface/HGCalProcessorBase.h
  L1Trigger/L1THGCal/interface/HGCalProcessorBaseT.h
  L1Trigger/L1THGCal/interface/HGCalTriggerTowerGeometryHelper.h
  L1Trigger/L1THGCal/interface/backend/HGCalHistoClusteringImpl.h
  L1Trigger/L1THGCal/interface/backend/HGCalTowerMap2DImpl.h
  L1Trigger/L1THGCal/plugins/HGCalBackendLayer2Producer.cc
  L1Trigger/L1THGCal/plugins/HGCalTowerMapProducer.cc
  L1Trigger/L1THGCal/plugins/HGCalTowerProducer.cc
  L1Trigger/L1THGCal/plugins/backend/HGCalBackendLayer2Processor3DClustering.cc
  L1Trigger/L1THGCal/plugins/backend/HGCalTowerMapProcessor.cc
  L1Trigger/L1THGCal/plugins/backend/HGCalTowerProcessor.cc
  L1Trigger/L1THGCal/python/customTowers.py
  L1Trigger/L1THGCal/python/hgcalConcentratorProducer_cfi.py
  L1Trigger/L1THGCal/python/hgcalTowerMapProducer_cfi.py
  L1Trigger/L1THGCal/python/hgcalTowerProducer_cfi.py
  L1Trigger/L1THGCal/src/HGCalTriggerTowerGeometryHelper.cc
  L1Trigger/L1THGCal/src/backend/HGCalHistoClusteringImpl.cc
  L1Trigger/L1THGCal/src/backend/HGCalTowerMap2DImpl.cc
  L1Trigger/L1THGCalUtilities/plugins/ntuples/HGCalTriggerNtupleHGCDigis.cc
  L1Trigger/L1THGCalUtilities/python/hgcalTriggerNtuples_cfi.py
  L1Trigger/L1THGCalUtilities/python/hgcalTriggerValidation_cff.py
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#31091 fix upgrade workflow steps for wf introduced in #30976
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-pending, orp-approved, pdmv-pending, pending-signatures, tests-started, upgrade-pending

#30995 Modernize modules in SUSYBSMAnalysis/HSCP
  SUSYBSMAnalysis/HSCP/plugins/Skim_HSCPFilter.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_HighPtTrackEcalDetIdProducer.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_ProduceIsolationMap.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_ReduceHcalRecHitCollectionProducer.cc
  SUSYBSMAnalysis/HSCP/plugins/Skim_UpdatedMuonInnerTrackRef.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31026 Modernize modules in HeavyFlavorAnalysis/Onia2MuMu
  HeavyFlavorAnalysis/Onia2MuMu/interface/Onia2MuMuPAT.h
  HeavyFlavorAnalysis/Onia2MuMu/interface/OniaAddV0TracksProducer.h
  HeavyFlavorAnalysis/Onia2MuMu/interface/OniaVtxReProducer.h
  HeavyFlavorAnalysis/Onia2MuMu/src/Onia2MuMuPAT.cc
  HeavyFlavorAnalysis/Onia2MuMu/src/OniaAddV0TracksProducer.cc
  HeavyFlavorAnalysis/Onia2MuMu/src/OniaVtxReProducer.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31049 MillePede alignment: add resubmission option
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_fire.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31075 PPS: adding missing IO rule for class TotemRPUVPattern
  DataFormats/CTPPSReco/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31072 migrate from run2_miniAOD_devel to run2_miniAOD_UL for miniAOD setup UL workflows
  CommonTools/PileupAlgos/python/Puppi_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/lostTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
  RecoCTPPS/ProtonReconstruction/python/ctppsProtons_cff.py
  RecoEgamma/EgammaPhotonProducers/python/reducedEgamma_cfi.py
  RecoEgamma/EgammaTools/python/calibratedEgammas_cff.py
  RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py
  RecoJets/JetProducers/python/PileupJetID_cfi.py
  RecoMET/METProducers/python/METSignificanceParams_cfi.py
  RecoTauTag/Configuration/python/boostedHPSPFTaus_cff.py
Labels: analysis-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31013 added esConsumes to modules in RecoHGCal/TICL and related packages
  RecoEgamma/EgammaTools/interface/HGCalEgammaIDHelper.h
  RecoEgamma/EgammaTools/src/HGCalEgammaIDHelper.cc
  RecoHGCal/TICL/plugins/FilteredLayerClustersProducer.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.cc
  RecoHGCal/TICL/plugins/SeedingRegionByTracks.cc
  RecoHGCal/TICL/plugins/SeedingRegionByTracks.h
  RecoHGCal/TICL/plugins/TICLLayerTileProducer.cc
  RecoHGCal/TICL/plugins/TrackstersMergeProducer.cc
  RecoLocalCalo/HGCalRecAlgos/interface/HGCal3DClustering.h
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalDepthPreClusterer.h
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalRecHitAbsAlgo.h
  RecoLocalCalo/HGCalRecAlgos/interface/RecHitTools.h
  RecoLocalCalo/HGCalRecAlgos/src/ClusterTools.cc
  RecoLocalCalo/HGCalRecAlgos/src/RecHitTools.cc
  RecoLocalCalo/HGCalRecProducers/interface/HGCalClusteringAlgoBase.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitWorkerSimple.cc
  RecoParticleFlow/PFClusterProducer/interface/PFHGCalRecHitCreator.h
  RecoParticleFlow/PFClusterProducer/plugins/SimMappers/RealisticSimClusterMapper.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/LayerClusterAssociatorByEnergyScoreProducer.cc
  Validation/HGCalValidation/plugins/HGCalHitCalibration.cc
  Validation/HGCalValidation/plugins/HGCalShowerSeparation.cc
  Validation/HGCalValidation/plugins/HGCalValidator.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#31079 runTheMatrix.py: Change confusing message about number of threads.
  Configuration/PyReleaseValidation/python/MatrixRunner.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31093 Do not deref unset edm::Handle in OtherThingAlgorithm
  FWCore/Integration/test/OtherThingAlgorithm.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31103 fixed some special comments for clang-format in FastTimerService
  HLTrigger/Timer/plugins/FastTimerService.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#31094 Phase2-gem49 Use constants defined in DataFormats
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.cc
  Geometry/GEMGeometryBuilder/src/ME0GeometryBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31092 Phase2-gex08 Rearrange the sequencing of the xml files for dd4hep
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D49.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D50.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D51.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D53.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D54.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D56.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D57.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D58.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D59.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D60.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D61.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D62.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D63.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D64.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D65.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D49XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D50XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D51XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D53XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D54XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D56XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D57XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D58XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D59XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D60XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D61XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D62XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D63XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D64XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D65XML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31083 SimTracker/TrackerMaterialAnalysis Unit test
  SimTracker/TrackerMaterialAnalysis/test/BuildFile.xml
  SimTracker/TrackerMaterialAnalysis/test/genTrackerPlots.sh
  SimTracker/TrackerMaterialAnalysis/test/listIds.py
  SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseII.py
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseII.py
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino_ForPhaseII.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31110 Patatrack integration - common tools updates (3/N)
  HeterogeneousCore/CUDAServices/plugins/CUDAMonitoringService.cc
  HeterogeneousCore/CUDAServices/scripts/cmsCudaRebuild.sh
  HeterogeneousCore/CUDAServices/scripts/cmsCudaSetup.sh
  HeterogeneousCore/CUDAUtilities/interface/copyAsync.h
  HeterogeneousCore/CUDAUtilities/interface/cudaCompat.h
  HeterogeneousCore/CUDAUtilities/interface/cuda_cxx17.h
  HeterogeneousCore/CUDAUtilities/interface/deviceAllocatorStatus.h
  HeterogeneousCore/CUDAUtilities/interface/prefixScan.h
  HeterogeneousCore/CUDAUtilities/src/CachingDeviceAllocator.h
  HeterogeneousCore/CUDAUtilities/src/deviceAllocatorStatus.cc
  HeterogeneousCore/CUDAUtilities/src/getCachingDeviceAllocator.h
Labels: code-checks-approved, comparison-available, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#31111 Modify HCAL reco pulse shape for Run 3
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31082 Run3-gex07 Create Run3 geometry with zero tracker material
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2021ZeroMaterialReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021ZeroMaterial_cff.py
  Configuration/Geometry/python/GeometryExtended2021ZeroMaterialReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021ZeroMaterial_cff.py
  Configuration/Geometry/python/dict2021Geometry.py
  Configuration/Geometry/python/generateGeometry.py
  Configuration/Geometry/scripts/generate2021Geometry.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/data/materials/2021ZeroMaterial/v1/materials.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, tests-approved, upgrade-approved

#31119 Fix HLT JEC conditions for 2018 MC [11_1_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#31116 Define (GEN) only eventcontent
  Configuration/EventContent/python/EventContent_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#31108 Clean up CondTools/DQM configurations and add unit tests
  CondTools/DQM/python/DQMXMLFileEventSetupAnalyzer_cfi.py
  CondTools/DQM/src/DQMXMLFileSourceHandler.cc
  CondTools/DQM/test/BuildFile.xml
  CondTools/DQM/test/DQMUploadXMLFile.py
  CondTools/DQM/test/DQMXMLFileEventSetupAnalyzer_cfg.py
  CondTools/DQM/test/testPayloadReading.cpp
  CondTools/DQM/test/testPayloadWriting.cpp
  CondTools/DQM/test/test_read.sh
  CondTools/DQM/test/test_write.sh
Labels: code-checks-approved, comparison-available, db-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#31076 backporting of the Online ESProducer code for next MWGR
  CondFormats/DataRecord/interface/BeamSpotTransientObjectsRcd.h
  RecoVertex/BeamSpotProducer/plugins/BuildFile.xml
  RecoVertex/BeamSpotProducer/plugins/OfflineToTransientBeamSpotESProducer.cc
  RecoVertex/BeamSpotProducer/plugins/OnlineBeamSpotESProducer.cc
  RecoVertex/BeamSpotProducer/plugins/OnlineBeamSpotFromDB.cc
  RecoVertex/BeamSpotProducer/test/readOnlineBeamSpotFromDB.py
Labels: alca-approved, comparison-available, db-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31066 update comment about concurrency
  CondCore/ESSources/plugins/CondDBESSource.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#31098 convert L1TkMuon to stream producer
  L1Trigger/L1TTrackMatch/plugins/L1TkMuonProducer.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#31122 Move "wmsplit" dict build to a static method, remove circular import
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31064 code updates to add a noise correlation factor between adjacent time slices for HB and HE channels
  DataFormats/HcalRecHit/interface/HBHEChannelInfo.h
  DataFormats/HcalRecHit/src/classes_def.xml
  DataFormats/HcalRecHit/test/test_hcal_reco.cu
  RecoLocalCalo/HcalRecAlgos/interface/MahiFit.h
  RecoLocalCalo/HcalRecAlgos/src/MahiFit.cc
  RecoLocalCalo/HcalRecProducers/src/HBHEPhase1Reconstructor.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31055 Selector by region
  RecoTracker/FinalTrackSelectors/plugins/TrackSelectorByRegion.cc
  RecoTracker/SpecialSeedGenerators/interface/CosmicTrackingRegion.h
  RecoTracker/SpecialSeedGenerators/src/CosmicTrackingRegion.cc
  RecoTracker/TkTrackingRegions/interface/GlobalTrackingRegion.h
  RecoTracker/TkTrackingRegions/interface/RectangularEtaPhiTrackingRegion.h
  RecoTracker/TkTrackingRegions/interface/TrackingRegion.h
  RecoTracker/TkTrackingRegions/src/GlobalTrackingRegion.cc
  RecoTracker/TkTrackingRegions/src/RectangularEtaPhiTrackingRegion.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31118 Make CentralityProducer a global module
  RecoHI/HiCentralityAlgos/plugins/CentralityProducer.cc
  RecoHI/HiCentralityAlgos/python/HiCentrality_cfi.py
  RecoHI/HiCentralityAlgos/python/pACentrality_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31117 Hlt tau validation conditional plotting4
  DQMOffline/Trigger/interface/HLTTauDQML1Plotter.h
  DQMOffline/Trigger/interface/HLTTauDQMOfflineSource.h
  DQMOffline/Trigger/interface/HLTTauDQMPathPlotter.h
  DQMOffline/Trigger/interface/HLTTauDQMPathSummaryPlotter.h
  DQMOffline/Trigger/interface/HLTTauDQMTagAndProbePlotter.h
  DQMOffline/Trigger/interface/HistoWrapper.h
  DQMOffline/Trigger/plugins/HLTTauDQMOfflineSource.cc
  DQMOffline/Trigger/plugins/HLTTauRefProducer.cc
  DQMOffline/Trigger/python/HLTTauDQMOffline_cfi.py
  DQMOffline/Trigger/src/HLTTauDQML1Plotter.cc
  DQMOffline/Trigger/src/HLTTauDQMPathPlotter.cc
  DQMOffline/Trigger/src/HLTTauDQMPathSummaryPlotter.cc
  DQMOffline/Trigger/src/HLTTauDQMTagAndProbePlotter.cc
  DQMOffline/Trigger/src/HistoWrapper.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31133 Run3-ft30 Cleanup a few buildfiles with duplicate use
  SimDataFormats/Associations/BuildFile.xml
  TrackingTools/TransientTrackingRecHit/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#31045 Adding an HLT filter for matching between PPS local tracks and central jet properties
  HLTrigger/special/plugins/BuildFile.xml
  HLTrigger/special/plugins/HLTPPSJetComparisonFilter.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#31134 Fix undefined behavior in MTVHistoProducerAlgoForTracker
  Validation/RecoTrack/src/MTVHistoProducerAlgoForTracker.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30457 TCDS multi-fed support in DAQ and unpacker
  DataFormats/TCDS/interface/TCDSRecord.h
  DataFormats/TCDS/src/TCDSRecord.cc
  DataFormats/TCDS/src/classes_def.xml
  EventFilter/Utilities/interface/FedRawDataInputSource.h
  EventFilter/Utilities/plugins/DaqFakeReader.cc
  EventFilter/Utilities/plugins/DaqFakeReader.h
  EventFilter/Utilities/plugins/TcdsRawToDigi.cc
  EventFilter/Utilities/src/FedRawDataInputSource.cc
  EventFilter/Utilities/test/startBU.py
  EventFilter/Utilities/test/startFU.py
  EventFilter/Utilities/test/unittest_FU.py
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31109 Nano: add workflows for run2_nanoAOD_106Xv1
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31132 Selector by region ( 11.1.x backport )
  RecoTracker/FinalTrackSelectors/plugins/TrackSelectorByRegion.cc
  RecoTracker/SpecialSeedGenerators/interface/CosmicTrackingRegion.h
  RecoTracker/SpecialSeedGenerators/src/CosmicTrackingRegion.cc
  RecoTracker/TkTrackingRegions/interface/GlobalTrackingRegion.h
  RecoTracker/TkTrackingRegions/interface/RectangularEtaPhiTrackingRegion.h
  RecoTracker/TkTrackingRegions/interface/TrackingRegion.h
  RecoTracker/TkTrackingRegions/src/GlobalTrackingRegion.cc
  RecoTracker/TkTrackingRegions/src/RectangularEtaPhiTrackingRegion.cc
Labels: comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31044 Fix to enable hpsPFTauDiscriminationByDeadECALElectronRejection in run2 reminiAODs (10_6_X)
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/Configuration/python/HPSPFTaus_cff.py
Labels: analysis-pending, backport, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#31145 Fix gcc10 warning in KDTreeLinkerAlgo
  CommonTools/RecoAlgos/interface/KDTreeLinkerAlgo.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31146 Fix gcc10 warning in prepareMagneticFieldGrid
  MagneticField/Interpolation/test/BinaryTablesGeneration/prepareMagneticFieldGrid.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31140 Run3-TB60 Update and correct HCAL TB06 simulation
  SimG4CMS/HcalTestBeam/python/TB2006Analysis_cfi.py
  SimG4CMS/HcalTestBeam/test/python/anal_tb06_cfg.py
  SimG4CMS/HcalTestBeam/test/python/run2006_33_cfg.py
  SimG4CMS/HcalTestBeam/test/python/run2006_37_cfg.py
  SimG4CMS/HcalTestBeam/test/python/run2006_77_cfg.py
  SimG4CMS/HcalTestBeam/test/python/run2006_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31112 DD4hep: SimTracker/TrackerMaterialAnalysis SpecPars Groups
  Configuration/Geometry/python/dict2021Geometry.py
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D49.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D50.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D53.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D60.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D63.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D64.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D65.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D49XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D50XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D53XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D60XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D63XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D64XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D65XML_cfi.py
  SimTracker/TrackerMaterialAnalysis/test/listGroups_dd4hep.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#31142 DD4hep: SimTracker/TrackerMaterialAnalysis code update
  SimTracker/TrackerMaterialAnalysis/TODO
  SimTracker/TrackerMaterialAnalysis/doc/bugs
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/BoundingBox.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/BoundingBox.h
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_ListGroups.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_ListIds.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_MaterialAccountingGroup.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_MaterialAccountingGroup.h
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_TrackingMaterialAnalyser.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_TrackingMaterialAnalyser.h
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_TrackingMaterialPlotter.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_TrackingMaterialPlotter.h
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_XHistogram.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_XHistogram.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31150 Remove boost::phoenix dependency
  FWCore/Modules/src/PathStatusFilter.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31153 add missing dep on FWCore/Utilities
  FWCore/Concurrency/BuildFile.xml
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31157 Added Z of the central detector for very forward simulation
  SimG4Core/Application/interface/StackingAction.h
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/StackingAction.cc
  SimG4Core/Application/src/SteppingAction.cc
  SimG4Core/Generators/interface/Generator.h
  SimG4Core/Generators/src/Generator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31115 Basic2D PFCluster for each rechit seed
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoParticleFlow/PFClusterProducer/plugins/Basic2DClusterForEachSeed.cc
  RecoParticleFlow/PFClusterProducer/plugins/Basic2DClusterForEachSeed.h
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#31152 Phase2-hgx259 Change the validation code for HGCal to make it work for DDD as well as for DD4hep
  Validation/HGCalValidation/plugins/BuildFile.xml
  Validation/HGCalValidation/plugins/HGCalDigiClient.cc
  Validation/HGCalValidation/plugins/HGCalDigiValidation.cc
  Validation/HGCalValidation/plugins/HGCalRecHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalRecHitsClient.cc
  Validation/HGCalValidation/plugins/HGCalSimHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalSimHitsClient.cc
  Validation/HGCalValidation/python/simhitValidation_cff.py
  Validation/HGCalValidation/test/BuildFile.xml
  Validation/HGCalValidation/test/HGCalDigiStudy.cc
  Validation/HGCalValidation/test/HGCalRecHitStudy.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31149 Remove or make const few PFCluster obsolete data members
  DataFormats/ParticleFlowReco/interface/PFCluster.h
  DataFormats/ParticleFlowReco/src/PFCluster.cc
  DataFormats/ParticleFlowReco/src/classes_def_2.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31047 Fix to enable hpsPFTauDiscriminationByDeadECALElectronRejection in run2 reminiAODs
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-pending, pending-signatures, reconstruction-approved, tests-approved

#31063 NanoAODv7 code updates [106X]
  DataFormats/NanoAOD/interface/MergeableCounterTable.h
  DataFormats/NanoAOD/src/classes_def.xml
  PhysicsTools/NanoAOD/BuildFile.xml
  PhysicsTools/NanoAOD/plugins/BuildFile.xml
  PhysicsTools/NanoAOD/plugins/CandMCMatchTableProducer.cc
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/plugins/LHETablesProducer.cc
  PhysicsTools/NanoAOD/plugins/LeptonInJetProducer.cc
  PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc
  PhysicsTools/NanoAOD/plugins/SummaryTableOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/SummaryTableOutputBranches.h
  PhysicsTools/NanoAOD/plugins/TriggerObjectTableProducer.cc
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.h
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/genparticles_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
  PhysicsTools/NanoAOD/test/inspectNanoFile.py
  PhysicsTools/PatAlgos/plugins/LeptonUpdater.cc
  RecoJets/JetProducers/plugins/BetaStarVarProducer.cc
Labels: analysis-pending, backport-ok, comparison-available, orp-pending, pending-signatures, reconstruction-approved, requires-external, tests-approved, xpog-approved

#30947 drop type specs in RecoTracker
  RecoMuon/MuonIdentification/python/cosmics_id.py
  RecoTracker/CkfPattern/python/CkfTrackCandidatesCombinedSeeds_cff.py
  RecoTracker/CkfPattern/python/CkfTrackCandidatesNoOverlaps_cff.py
  RecoTracker/CkfPattern/python/CkfTrackCandidatesP5_cff.py
  RecoTracker/Configuration/python/RecoTrackerNotStandard_cff.py
  RecoTracker/Configuration/python/RecoTrackerP5_cff.py
  RecoTracker/Configuration/python/RecoTrackerTopBottom_cff.py
  RecoTracker/SiTrackerMRHTools/python/GroupedMultiRecHitCollector_cff.py
  RecoTracker/SiTrackerMRHTools/python/SimpleMultiRecHitCollector_cff.py
  RecoTracker/SpecialSeedGenerators/python/CombinatorialSeedGeneratorForCosmicsP5_cff.py
  RecoTracker/SpecialSeedGenerators/python/CosmicSeedP5Pairs_cff.py
  RecoTracker/SpecialSeedGenerators/python/CosmicSeedP5Triplets_cff.py
  RecoTracker/TkSeedGenerator/python/SeedGeneratorFromProtoTracksEDProducer_cff.py
  RecoTracker/TrackProducer/python/CTFFinalFitWithMaterialDAF_cff.py
  RecoTracker/TrackProducer/python/CTFFinalFitWithMaterialP5_cff.py
  RecoTracker/TrackProducer/python/CTFFinalFitWithMaterial_cfi.py
  RecoTracker/TrackProducer/python/CTFNoOverlaps_cff.py
  RecoTracker/TrackProducer/python/CTFPixelLess_cff.py
  RecoTracker/TrackProducer/python/CosmicFinalFitWithMaterialP5_cff.py
  RecoTracker/TrackProducer/python/RSFinalFitAnalytical_cff.py
  RecoTracker/TrackProducer/python/RSFinalFitWithMaterialP5_cff.py
  RecoTracker/TrackProducer/python/RSFinalFitWithMaterial_cff.py
  RecoTracker/TrackProducer/python/TrackRefitterBHM_cfi.py
  RecoTracker/TrackProducer/python/TrackRefitterP5_cfi.py
  RecoTracker/TransientTrackingRecHit/python/TTRHBuilderWithFake_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31077 Add the anti-electron-in-deadECal tauID to NanoAOD
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved, xpog-approved

#31141 Update Alignment/OfflineValidation package
  Alignment/OfflineValidation/plugins/BuildFile.xml
  Alignment/OfflineValidation/plugins/DMRChecker.cc
  Alignment/OfflineValidation/plugins/GeneralPurposeTrackAnalyzer.cc
  Alignment/OfflineValidation/plugins/PrimaryVertexValidation.cc
  Alignment/OfflineValidation/plugins/PrimaryVertexValidation.h
  Alignment/OfflineValidation/test/PrimaryVertexResolution_cfg.py
  Alignment/OfflineValidation/test/inspectData_cfg.py
  Alignment/OfflineValidation/test/test_all_cfg.py
  CondCore/SiPixelPlugins/interface/Phase1PixelMaps.h
  CondCore/SiPixelPlugins/interface/PixelRegionContainers.h
  CondCore/SiPixelPlugins/interface/SiPixelPayloadInspectorHelper.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#31151 Cleanup of the PFTrack class
  DataFormats/ParticleFlowReco/interface/PFTrack.h
  DataFormats/ParticleFlowReco/src/GsfPFRecTrack.cc
  DataFormats/ParticleFlowReco/src/PFTrack.cc
  DataFormats/ParticleFlowReco/src/classes_def_2.xml
  RecoParticleFlow/PFTracking/src/ConvBremPFTrackFinder.cc
  RecoParticleFlow/PFTracking/src/PFTrackTransformer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31148 Remove dead assignments in EventFilter/Utilities/DirManager and Validation/RecoTrack/SiStripTrackingRecHitsValid
  EventFilter/Utilities/src/DirManager.cc
  Validation/RecoTrack/src/SiStripTrackingRecHitsValid.cc
Labels: code-checks-approved, comparison-available, daq-approved, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31128 Refine RuInfo payload inspector
  CondCore/RunInfoPlugins/interface/RunInfoPayloadInspectoHelper.h
  CondCore/RunInfoPlugins/plugins/RunInfo_PayloadInspector.cc
  CondCore/RunInfoPlugins/test/plot2JsonTimeSeries.py
  CondCore/Utilities/interface/PayloadInspector.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#31144 Run3-gem51 Add a tool to compare DDD vs DD4HEP for CSC geometry
  Geometry/CSCGeometryBuilder/src/CSCGeometryParsFromDD.cc
  Geometry/CSCGeometryBuilder/test/BuildFile.xml
  Geometry/CSCGeometryBuilder/test/CSCGeometryDump.cc
  Geometry/CSCGeometryBuilder/test/python/dumpCSCGeometryDD4hep_cfg.py
  Geometry/CSCGeometryBuilder/test/python/dumpCSCGeometryDDD_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31056 [RPC] Changing the RPCDcsInfo* about an issue of the DQM legacy module
  DQM/RPCMonitorClient/interface/RPCDcsInfoClient.h
  DQM/RPCMonitorClient/python/RPCDcsInfoClient_cfi.py
  DQM/RPCMonitorClient/python/RPCTier0Source_cff.py
  DQM/RPCMonitorClient/src/RPCDcsInfoClient.cc
  DQM/RPCMonitorDigi/interface/RPCDcsInfo.h
  DQM/RPCMonitorDigi/src/RPCDcsInfo.cc
  DQM/RPCMonitorDigi/src/SealModule.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31155 Add a service to handle MPI initialisation
  HeterogeneousCore/MPIServices/plugins/BuildFile.xml
  HeterogeneousCore/MPIServices/plugins/MPIService.cc
  HeterogeneousCore/MPIServices/test/BuildFile.xml
  HeterogeneousCore/MPIServices/test/testMPIService.py
Labels: code-checks-approved, comparison-available, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#31080 LowPtElectrons: updated BDT model and code base for ID
  RecoEgamma/EgammaElectronProducers/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/interface/LowPtGsfElectronFeatures.h
  RecoEgamma/EgammaElectronProducers/plugins/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronIDProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedHeavyObjectCache.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedHeavyObjectCache.h
  RecoEgamma/EgammaElectronProducers/src/LowPtGsfElectronFeatures.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#31138 Move "wmsplit" dict build to a static method, remove circular import (backport to 10_6_X)
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31137 Move "wmsplit" dict build to a static method, remove circular import (backport to 11_1_X)
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31131 Run3-gem50 Simplify access to fv and a dump utility
  DataFormats/MuonDetId/interface/ME0DetId.h
  DataFormats/MuonDetId/interface/RPCDetId.h
  Geometry/GEMGeometryBuilder/BuildFile.xml
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.h
  Geometry/GEMGeometryBuilder/src/ME0GeometryBuilder.cc
  Geometry/GEMGeometryBuilder/src/ME0GeometryBuilder.h
  Geometry/GEMGeometryBuilder/test/ME0GeometryDump.cc
  Geometry/GEMGeometryBuilder/test/python/dumpME0GeometryDDD_cfg.py
  Geometry/RPCGeometryBuilder/BuildFile.xml
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilder.cc
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilder.h
  Geometry/RPCGeometryBuilder/test/BuildFile.xml
  Geometry/RPCGeometryBuilder/test/RPCGeometryDump.cc
  Geometry/RPCGeometryBuilder/test/python/dumpRPCGeometryDD4hep_cfg.py
  Geometry/RPCGeometryBuilder/test/python/dumpRPCGeometryDDD_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#31166 Apply necessary changes to work with python3
  CondTools/SiPixel/test/SiPixelGenErrorDBObjectUploader_cfg.py
  CondTools/SiPixel/test/SiPixelTemplateDBObjectUploader_cfg.py
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#31125 Switch to UL jet ID in NanoAOD
  PhysicsTools/NanoAOD/python/jets_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved, xpog-approved

#31167 Moved boost includes to the implementation file
  CommonTools/CandAlgos/interface/decayParser.h
  CommonTools/CandAlgos/src/decayParser.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31168 DD4hep: SimTracker/TrackerMaterialAnalysis Update migrated test ph1
  SimTracker/TrackerMaterialAnalysis/test/TrackingMaterialAnalyser_dd4hep.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31169 SimG4Core/Configuration: hardcoded GTs do not age well
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step2_cfg.py
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step3_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step2_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step3_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31170 Fix undefined behavior in EgammaTowerIsolation
  RecoEgamma/EgammaIsolationAlgos/interface/EgammaTowerIsolation.h
  RecoEgamma/EgammaIsolationAlgos/src/EgammaTowerIsolation.cc
  RecoEgamma/EgammaIsolationAlgos/test/EgammaTowerIso_t.cpp
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31177 Fix UL jet ID working point in DQM
  DQMOffline/JetMET/python/jetAnalyzer_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31179 Remove a duplicate line in FastjetJetProducer.cc
  RecoJets/JetProducers/plugins/FastjetJetProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31121 optimize PFDisplacedVertexCandidateFinder::link
  CommonTools/Utils/interface/KinematicTables.h
  RecoParticleFlow/PFTracking/interface/PFDisplacedVertexCandidateFinder.h
  RecoParticleFlow/PFTracking/src/PFDisplacedVertexCandidateFinder.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-pending, pending-signatures, reconstruction-approved, tests-approved

#31053 Add missing GEN fragment for relvals
  Configuration/Generator/python/H125GGgluonfusion_13TeV_TuneCP5_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#31183 Geometry: Remove Custom SpecPars from T23 Dict
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D65.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D65XML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31162 drop type specs in RecoJets
  RecoJets/Configuration/python/CaloTowersES_cfi.py
  RecoJets/Configuration/python/GenJetParticles_cff.py
  RecoJets/Configuration/python/RecoGenJets_cff.py
  RecoJets/Configuration/python/RecoJets_cff.py
  RecoJets/Configuration/python/RecoPFJets_cff.py
  RecoJets/JetPlusTracks/python/JetPlusTrackCorrections_cff.py
  RecoJets/JetProducers/python/CaloTowerSchemeBWithHO_cfi.py
  RecoJets/JetProducers/python/CaloTowerSchemeB_cfi.py
  RecoJets/JetProducers/python/ECF_cff.py
  RecoJets/JetProducers/python/PileupJetID_cfi.py
  RecoJets/JetProducers/python/ak4PFCaloJets_cfi.py
  RecoJets/JetProducers/python/ak4PFJets_cfi.py
  RecoJets/JetProducers/python/ak8GenJets_cfi.py
  RecoJets/JetProducers/python/ak8PFJets_cfi.py
  RecoJets/JetProducers/python/ca15PFJets_cfi.py
  RecoJets/JetProducers/python/caTopTaggers_cff.py
  RecoJets/JetProducers/python/caloJetsForTrk_cff.py
  RecoJets/JetProducers/python/hltMVAJetPuId_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31135 Fix undefined behavior in CaloPoint
  FastSimulation/CaloGeometryTools/interface/CaloPoint.h
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#31147 Initialize members in FastSimulation Crystal class
  FastSimulation/CaloGeometryTools/interface/Crystal.h
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, orp-approved, tests-approved

#31196 change return type of geomTracker to derived class (TrackerGeometry vs TrackingGeometry)
  RecoEgamma/EgammaPhotonAlgos/interface/ConversionSeedFinder.h
  RecoEgamma/EgammaPhotonAlgos/interface/ConversionTrackFinder.h
  RecoEgamma/EgammaPhotonAlgos/src/ConversionSeedFinder.cc
  RecoEgamma/EgammaPhotonAlgos/src/ConversionTrackFinder.cc
  RecoMuon/L3TrackFinder/src/MuonCkfTrajectoryBuilder.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGForOI.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGForOIFromL2.cc
  RecoTracker/MeasurementDet/interface/MeasurementTracker.h
  RecoTracker/MeasurementDet/interface/MeasurementTrackerEvent.h
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.h
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#31175 Add GEM plus/minus HV states
  DataFormats/OnlineMetaData/interface/DCSRecord.h
  DataFormats/OnlineMetaData/src/DCSRecord.cc
  DataFormats/OnlineMetaData/src/classes_def.xml
  DataFormats/StdDictionaries/src/classes_def_others.xml
Labels: code-checks-approved, comparison-available, core-approved, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31207 Bugfix for JMENano backport PR #31124
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
Labels: analysis-pending, backport-ok, bug-fix, comparison-available, orp-approved, pending-signatures, tests-approved, xpog-approved

#31107 Add weights config for 2018 Run Dependent MC
  Configuration/StandardSequences/python/RunsAndWeights.py
  SimGeneral/Configuration/python/RunsAndWeights_Run2018_ABCD.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#31210 Adding protection against for empty Primary Vertices in DQM/TrackingMonitorSource/src/TrackToTrackComparisonHists.cc a
  DQM/TrackingMonitorSource/src/TrackToTrackComparisonHists.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved, urgent

#31187 add missing Rtypes.h include in hcalCalibUtils.h
  Calibration/HcalCalibAlgos/interface/hcalCalibUtils.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31173 [DD4hep] Migrate to a new version of DD4hep
  DetectorDescription/DDCMS/interface/DDCompactView.h
  DetectorDescription/DDCMS/interface/DDDetector.h
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/interface/DDSpecParRegistry.h
  DetectorDescription/DDCMS/interface/DDVolumeProcessor.h
  DetectorDescription/DDCMS/interface/Filter.h
  DetectorDescription/DDCMS/plugins/DDSpecParRegistryESProducer.cc
  DetectorDescription/DDCMS/plugins/DDVectorRegistryESProducer.cc
  DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
  DetectorDescription/DDCMS/plugins/test/DDTestSpecPars.cc
  DetectorDescription/DDCMS/plugins/test/DDTestSpecParsFilter.cc
  DetectorDescription/DDCMS/src/DDAlgoArguments.cc
  DetectorDescription/DDCMS/src/DDCompactView.cc
  DetectorDescription/DDCMS/src/DDDetector.cc
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  DetectorDescription/DDCMS/src/DDSpecparRegistry.cc
  DetectorDescription/DDCMS/src/ES_DDDetector.cc
  DetectorDescription/DDCMS/src/Filter.cc
  DetectorDescription/DDCMS/test/Filter.cppunit.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryBuilder.cc
  Geometry/DTGeometryBuilder/plugins/dd4hep/DTGeometryBuilder.h
  Geometry/EcalCommonData/src/EcalSimParametersFromDD.cc
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.cc
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.h
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
  Geometry/HcalCommonData/src/HcalSimParametersFromDD.cc
  Geometry/HcalTestBeamData/src/HcalTB02ParametersFromDD.cc
  Geometry/HcalTestBeamData/src/HcalTB06BeamParametersFromDD.cc
  Geometry/MTDCommonData/test/DD4hep_TestMTDIdealGeometry.cc
  Geometry/MTDGeometryBuilder/src/MTDParametersFromDD.cc
  Geometry/MTDNumberingBuilder/test/DD4hep_MTDTopologyAnalyzer.cc
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilder.h
  Geometry/TrackerGeometryBuilder/src/TrackerParametersFromDD.cc
  SimG4CMS/CherenkovAnalysis/src/DreamSD.cc
  SimG4Core/DD4hepGeometry/test/plugins/DD4hepTestDDDWorld.cc
  SimG4Core/Geometry/interface/DDG4ProductionCuts.h
  SimG4Core/Geometry/src/DD4hep_DDG4Builder.cc
  SimG4Core/Geometry/src/DDG4ProductionCuts.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_ListGroups.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_MaterialAccountingGroup.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_MaterialAccountingGroup.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, requires-external, simulation-approved, tests-approved, upgrade-approved

#31160 Run3-hcx263 Remove unwanted DDD reference fro the code and test the used scripts
  Geometry/HGCalCommonData/python/hgcalV6ParametersInitialization_cfi.py
  Geometry/HcalCommonData/test/HcalRecNumberingTester.cc
  Geometry/HcalCommonData/test/HcalSimNumberingTester.cc
  Geometry/HcalCommonData/test/python/runHcalParametersFromDDDAnalyzer_cfg.py
  Geometry/HcalCommonData/test/python/runHcalRecNumberingDD4hepTester_cfg.py
  Geometry/HcalCommonData/test/python/runHcalRecNumberingDDDTester_cfg.py
  Geometry/HcalCommonData/test/python/runHcalSimNumberingDD4hepTester_cfg.py
  Geometry/HcalCommonData/test/python/runHcalSimNumberingDDDTester_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31216 Very forward full simulation
  SimG4Core/Application/interface/RunManagerMTWorker.h
  SimG4Core/Application/interface/StackingAction.h
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/RunManager.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/Application/src/StackingAction.cc
  SimG4Core/Application/src/SteppingAction.cc
  SimG4Core/Generators/interface/Generator.h
  SimG4Core/Generators/src/Generator.cc
  SimPPS/PPSSimTrackProducer/plugins/PPSSimTrackProducer.cc
  SimTransport/HectorProducer/src/Hector.cc
  SimTransport/HectorProducer/src/HectorProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31164 improving performance of PuppiProducer
  CommonTools/PileupAlgos/BuildFile.xml
  CommonTools/PileupAlgos/interface/PuppiAlgo.h
  CommonTools/PileupAlgos/interface/PuppiCandidate.h
  CommonTools/PileupAlgos/interface/PuppiContainer.h
  CommonTools/PileupAlgos/plugins/PuppiProducer.cc
  CommonTools/PileupAlgos/src/PuppiAlgo.cc
  CommonTools/PileupAlgos/src/PuppiCandidate.cc
  CommonTools/PileupAlgos/src/PuppiContainer.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved
