Repository cms-sw/cmssw, pull requests merged in 2020-10, with the labels that each got.

#31565 [HGCal] Add unit test for HGCal material budget plots
  Validation/Geometry/test/BuildFile.xml
  Validation/Geometry/test/genHGCalPlots.sh
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#31630 [DD4hep] Filtered View Performance Step 1
  DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  DetectorDescription/DDCMS/test/DDFilteredView.goto.cppunit.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31541 Phase2-gex13 Add a scenario where ME0 is replaced by GE0
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2026D67Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D67_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D67.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D67XML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31620 [102X] NanoAOD: add flag to keep all PS weights
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: analysis-pending, comparison-available, orp-approved, pending-signatures, tests-approved, xpog-approved

#31616 SonicTriton tests with Singularity
  HeterogeneousCore/SonicTriton/test/README.md
  HeterogeneousCore/SonicTriton/test/fetch_model.sh
  HeterogeneousCore/SonicTriton/test/triton
Labels: code-checks-approved, comparison-available, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#31642 Avoid dangling reference in edm::ConsumesCollectorWithTagESAdaptor
  FWCore/Framework/interface/ConsumesCollector.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31582 Protect against ill-defined track momenta and reffited tau vertices for tauReco@mini
  RecoTauTag/RecoTau/plugins/PFTauMiniAODPrimaryVertexProducer.cc
  RecoTauTag/RecoTau/src/PFTauPrimaryVertexProducerBase.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31586 [Tk Alignment] Fix validation macro when reading luminosity from external file
  Alignment/OfflineValidation/data/lumiPerRun_Run2.txt
  Alignment/OfflineValidation/macros/MultiRunAndPlotPVValidation.C
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30898 Switch to heavy-ion jets in HI miniAOD
  PhysicsTools/PatAlgos/python/mcMatchLayer0/jetFlavourId_cff.py
  PhysicsTools/PatAlgos/python/mcMatchLayer0/jetMatch_cfi.py
  PhysicsTools/PatAlgos/python/producersHeavyIons/heavyIonJetSetup.py
  PhysicsTools/PatAlgos/python/producersHeavyIons/heavyIonJets_cff.py
  PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cff.py
  PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cfi.py
  PhysicsTools/PatAlgos/python/producersLayer1/patCandidates_cff.py
  PhysicsTools/PatAlgos/python/recoLayer0/jetCorrFactors_cfi.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/applySubstructure_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/slimming/packedPFCandidates_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimmedCaloJets_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimmedGenJets_cfi.py
  RecoBTag/ImpactParameter/python/impactParameterTagInfos_cfi.py
  RecoHI/HiJetAlgos/python/HiRecoPFJets_cff.py
  RecoHI/HiTracking/python/highPurityGeneralTracks_cfi.py
  RecoJets/Configuration/python/RecoPFJets_cff.py
  RecoJets/JetAssociationProducers/python/ak5JTA_cff.py
  RecoJets/JetProducers/python/ak4PFJets_cfi.py
  RecoJets/JetProducers/python/ak8PFJets_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#31646 Bugfix for PackedCandidateMuonSelectorProducer (HI re-miniAOD)
  PhysicsTools/PatAlgos/plugins/PackedCandidateMuonSelectorProducer.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#31378 Move PhysicsTools/PatAlgos/plugins/BaseMVAValueMapProducer.h to interface/
  PhysicsTools/NanoAOD/plugins/BJetEnergyRegressionMVA.cc
  PhysicsTools/NanoAOD/plugins/BuildFile.xml
  PhysicsTools/PatAlgos/BuildFile.xml
  PhysicsTools/PatAlgos/interface/BaseMVAValueMapProducer.h
  PhysicsTools/PatAlgos/plugins/BaseMVAValueMapProducer.cc
  PhysicsTools/PatAlgos/plugins/BuildFile.xml
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#31622 Decoupling charge reweighting from SiPixelDigitizerAlgorithm
  SimTracker/SiPixelDigitizer/plugins/SiPixelChargeReweightingAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelChargeReweightingAlgorithm.h
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31609 Migrate dqmEnvSiPixelQuality from DQMEventInfo to DQMHarvestingMetadata
  CalibTracker/SiPixelQuality/python/DQMEventInfoSiPixelQuality_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31309 Initial Changes for Incoporating GEM GE0 into the Reco Pipeline
  Configuration/Eras/python/Era_Phase2C11M9_cff.py
  Configuration/Eras/python/Modifier_phase2_GE0_cff.py
  Configuration/StandardSequences/python/Eras.py
  DQMOffline/Muon/interface/GEMOfflineDQMBase.h
  L1Trigger/L1TGEM/python/me0TriggerDigis_cff.py
  L1Trigger/L1TMuon/python/simDigis_cff.py
  RecoLocalMuon/Configuration/python/RecoLocalMuon_cff.py
  RecoMuon/MuonIdentification/python/muons1stStep_cfi.py
  RecoMuon/MuonSeedGenerator/python/ancientMuonSeed_cfi.py
  RecoMuon/StandAloneMuonProducer/python/standAloneMuons_cfi.py
  RecoMuon/TrackingTools/python/MuonServiceProxy_cff.py
  SimGeneral/MixingModule/python/mixObjects_cfi.py
  SimGeneral/MixingModule/python/trackingTruthProducer_cfi.py
  SimMuon/Configuration/python/SimMuon_cff.py
  SimMuon/GEMDigitizer/python/muonME0Digi_cff.py
  TrackingTools/TrackAssociator/python/DetIdAssociatorESProducer_cff.py
  Validation/Configuration/python/globalValidation_cff.py
  Validation/Configuration/python/postValidation_cff.py
  Validation/RecoMuon/python/MuonTrackValidator_cfi.py
  Validation/RecoMuon/python/muonValidation_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, l1-pending, operations-approved, orp-approved, pending-signatures, reconstruction-approved, requires-external, simulation-pending, tests-approved, upgrade-approved

#31585 Protect against ill-defined track momenta and reffited tau vertices for tauReco@mini (10_6_X)
  RecoTauTag/RecoTau/plugins/PFTauMiniAODPrimaryVertexProducer.cc
  RecoTauTag/RecoTau/src/PFTauPrimaryVertexProducerBase.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31651 MF regression IB tests
  MagneticField/Engine/test/BuildFile.xml
  MagneticField/Engine/test/regressionTestHelper.cpp
  MagneticField/Engine/test/runTest.sh
  MagneticField/Engine/test/testMagneticField.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31573 DD4hep: Introduces functional Tracker navigation + DetIds building
  CondTools/Geometry/plugins/PGeometricDetBuilder.cc
  Geometry/TrackerGeometryBuilder/src/TrackerGeomBuilderFromGeometricDet.cc
  Geometry/TrackerGeometryBuilder/test/ModuleInfo.cc
  Geometry/TrackerNumberingBuilder/BuildFile.xml
  Geometry/TrackerNumberingBuilder/interface/GeometricDet.h
  Geometry/TrackerNumberingBuilder/plugins/BuildFile.xml
  Geometry/TrackerNumberingBuilder/plugins/CmsDetConstruction.cc
  Geometry/TrackerNumberingBuilder/plugins/CmsDetConstruction.h
  Geometry/TrackerNumberingBuilder/plugins/CmsTrackerDetIdBuilder.cc
  Geometry/TrackerNumberingBuilder/plugins/CmsTrackerLevelBuilder.cc
  Geometry/TrackerNumberingBuilder/plugins/CmsTrackerPhase1DiskBuilder.cc
  Geometry/TrackerNumberingBuilder/plugins/CmsTrackerRingBuilder.cc
  Geometry/TrackerNumberingBuilder/plugins/CmsTrackerRingBuilder.h
  Geometry/TrackerNumberingBuilder/plugins/DDDCmsTrackerContruction.cc
  Geometry/TrackerNumberingBuilder/plugins/DDDCmsTrackerContruction.h
  Geometry/TrackerNumberingBuilder/plugins/TrackerGeometricDetExtraESModule.cc
  Geometry/TrackerNumberingBuilder/src/GeometricDet.cc
  Geometry/TrackerNumberingBuilder/src/TrackerShapeToBounds.cc
  Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc
  Geometry/TrackerNumberingBuilder/test/trackerModuleNumberingDD4hep_cfg.py
  Geometry/TrackerNumberingBuilder/test/trackerModuleNumbering_cfg.py
  RecoRomanPot/RecoFP420/plugins/ClusterizerFP420.cc
  RecoTracker/TkDetLayers/src/Phase2EndcapRingBuilder.cc
  RecoTracker/TkDetLayers/src/Phase2OTBarrelRodBuilder.cc
  RecoTracker/TkDetLayers/src/PixelBladeBuilder.h
  RecoTracker/TkDetLayers/src/PixelRodBuilder.cc
  RecoTracker/TkDetLayers/src/TECWedgeBuilder.cc
  RecoTracker/TkDetLayers/src/TIBRingBuilder.cc
  RecoTracker/TkDetLayers/src/TIDRingBuilder.cc
  RecoTracker/TkDetLayers/src/TOBRodBuilder.cc
  SLHCUpgradeSimulations/Geometry/test/ModuleInfo_Phase2.cc
  SimG4CMS/Tracker/src/TrackerG4SimHitNumberingScheme.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, geometry-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#31663 Clean BuildFiles in DetectorDescription
  DetectorDescription/DDCMS/BuildFile.xml
  DetectorDescription/DDCMS/plugins/BuildFile.xml
  DetectorDescription/Parser/BuildFile.xml
  DetectorDescription/Parser/test/BuildFile.xml
  DetectorDescription/RegressionTest/test/BuildFile.xml
  ElectroWeakAnalysis/ZEE/BuildFile.xml
  Geometry/HcalAlgo/plugins/BuildFile.xml
Labels: analysis-pending, code-checks-approved, comparison-available, geometry-approved, orp-approved, pending-signatures, tests-approved

#31674 Use akCs4PFJets for candidate-based tagInfos for HI workflows
  DQMOffline/RecoB/python/dqmAnalyzer_cff.py
  PhysicsTools/PatAlgos/python/producersHeavyIons/heavyIonJets_cff.py
  RecoBTag/ImpactParameter/python/pfImpactParameterTagInfos_cfi.py
  RecoBTag/SoftLepton/python/softPFElectronTagInfos_cfi.py
  RecoBTag/SoftLepton/python/softPFMuonTagInfos_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, dqm-pending, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved, urgent

#31649 Remove dependency from DDCMS/interface/DDShapes.h
  MagneticField/GeomBuilder/src/DD4hep_volumeHandle.cc
  MagneticField/GeomBuilder/src/DD4hep_volumeHandle.h
  MagneticField/GeomBuilder/src/buildBox.icc
  MagneticField/GeomBuilder/src/buildCons.icc
  MagneticField/GeomBuilder/src/buildPseudoTrap.icc
  MagneticField/GeomBuilder/src/buildTrap.icc
  MagneticField/GeomBuilder/src/buildTruncTubs.icc
  MagneticField/GeomBuilder/src/buildTubs.icc
  MagneticField/GeomBuilder/src/volumeHandle.cc
  MagneticField/GeomBuilder/src/volumeHandle.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31581 [DD4hep] Remove Shape Wrapper Classes
  DetectorDescription/DDCMS/interface/DDShapes.h
  DetectorDescription/DDCMS/src/DDShapes.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, requires-external, tests-approved

#31652 [DD4hep] Remove Spurious Include
  Geometry/VeryForwardGeometryBuilder/src/DetGeomDesc.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, requires-external, tests-approved

#31675 Phase2-hcx265 Address the warnings reported in #31672
  Geometry/ForwardCommonData/data/hfnose/v4/hfnose.xml
  Geometry/ForwardCommonData/data/hfnoseLayer/v2/hfnoseLayer.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31635 Update PPS tags in Run 2 offline GTs for re-miniAOD
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31655 Add a customisation to run the "GRun" HLT menu on Run 2 data/MC
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#31691 [DD4hep] Filtered View is not a Shape
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/test/DDFilteredView.cppunit.cc
  DetectorDescription/DDCMS/test/DDSolid.cppunit.cc
  Geometry/EcalCommonData/src/EcalSimParametersFromDD.cc
  Geometry/HcalCommonData/src/HcalGeomParameters.cc
  Geometry/HcalTestBeamData/src/HcalTB02ParametersFromDD.cc
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilder.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31690 [DD4hep] Filtered View Performance - Step 4
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/src/DDFilteredView.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31638 Backport of code changes to 106X for PR 30922 : Enabling re-application of Type1 Corrections for PuppiMET and adding PUPPI MET Uncertainties
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: analysis-pending, comparison-available, orp-approved, pending-signatures, tests-approved, xpog-approved

#31615 [10_6_X] ParticleNetAK4 jet tagger
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/Configuration/python/RecoBTag_cff.py
  RecoBTag/FeatureTools/plugins/DeepBoostedJetTagInfoProducer.cc
  RecoBTag/ONNXRuntime/python/pfParticleNetAK4DiscriminatorsJetTags_cfi.py
  RecoBTag/ONNXRuntime/python/pfParticleNetAK4_cff.py
  RecoBTag/ONNXRuntime/test/test_particle_net_ak4_cfg.py
Labels: analysis-pending, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved

#31673 Removal of phase2 Tracker geometries T17, T19, T20 and migrations
  Configuration/AlCa/python/autoCondPhase2.py
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2026D51Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D51_cff.py
  Configuration/Geometry/python/GeometryExtended2026D56_cff.py
  Configuration/Geometry/python/GeometryExtended2026D58Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D58_cff.py
  Configuration/Geometry/python/GeometryExtended2026D59Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D61_cff.py
  Configuration/Geometry/python/GeometryExtended2026D62Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D62_cff.py
  Configuration/Geometry/python/GeometryExtended2026D63Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D68Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D68_cff.py
  Configuration/Geometry/python/GeometryExtended2026D69Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D69_cff.py
  Configuration/Geometry/python/GeometryExtended2026D70Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D70_cff.py
  Configuration/Geometry/python/GeometryExtended2026D71Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D71_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D68.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D69.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D70.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D71.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D51XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D54XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D57XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D61XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D62XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D68XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D69XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D70XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D71XML_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31627 move std dictionaries to DataFormats/StdDictionaries
  CondFormats/Common/src/classes_def.xml
  DataFormats/StdDictionaries/src/classes_def_map.xml
  DataFormats/StdDictionaries/src/classes_def_pair.xml
Labels: alca-approved, code-checks-approved, comparison-available, core-approved, db-approved, fully-signed, orp-approved, tests-approved

#31683 SubtractionSolid Vs UnionSolid For Muon Barrel
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
  Geometry/MuonCommonData/data/mb1/2021/v1/mb1.xml
  Geometry/MuonCommonData/data/mb2/2021/v1/mb2.xml
  Geometry/MuonCommonData/data/mb3/2021/v1/mb3.xml
  Geometry/MuonCommonData/data/mbCommon/2021/v2/mbCommon.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31695 Fix HGCalValidation for different Tracksers collections
  Validation/HGCalValidation/python/hgcalPlots.py
  Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31693 fix MF regression test in the Py3 case
  MagneticField/Engine/test/regression.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31677 Fix handling of XML paths (SpecPar) by DD4hep FilteredView
  Geometry/TrackerNumberingBuilder/interface/GeometricDet.h
  Geometry/TrackerNumberingBuilder/plugins/DDDCmsTrackerContruction.cc
  Geometry/TrackerNumberingBuilder/plugins/DDDCmsTrackerContruction.h
  Geometry/TrackerNumberingBuilder/src/GeometricDet.cc
  Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc
  Geometry/TrackerNumberingBuilder/test/trackerModuleNumberingDD4hep_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31705 remove inexistent pythia8 parameter from config
  Configuration/Generator/python/Pythia8CommonSettings_cfi.py
  GeneratorInterface/EvtGenInterface/test/Py8_bplus_evtgen1_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#31709 Added low energy positron parameterisation
  SimG4Core/Application/src/LowEnergyFastSimModel.cc
  SimG4Core/Application/src/ParametrisedEMPhysics.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31602 Include the HF filters used in heavy ions using struct in the MiniAOD content
  DataFormats/HeavyIonEvent/interface/HFFilterInfo.h
  DataFormats/HeavyIonEvent/src/classes.h
  DataFormats/HeavyIonEvent/src/classes_def.xml
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  RecoHI/HiCentralityAlgos/plugins/HiHFFilterProducer.cc
  RecoHI/HiCentralityAlgos/python/hiHFfilters_cfi.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31692 update of "DisplacedSUSY" relvals for TRK and EXO validation of displaced tracks, for Run 3 and Phase 2
  Configuration/Generator/python/DisplacedSUSY_stopToBottom_M_800_500mm_TuneCP5_13TeV_pythia8_cff.py
  Configuration/Generator/python/DisplacedSUSY_stopToBottom_M_800_500mm_TuneCP5_14TeV_pythia8_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31708 update HGCal unit test for new geometry
  Validation/Geometry/test/genHGCalPlots.sh
Labels: code-checks-approved, comparison-available, dqm-approved, geometry-pending, orp-approved, pending-signatures, tests-approved

#31712 fix DDFilteredView::parameters() crashing with a pseudotrapezoid
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  MagneticField/GeomBuilder/src/DD4hep_volumeHandle.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, reconstruction-approved, tests-approved

#31701 Avoid calling the wrong constructor for EDGetTokenT
  FWCore/Utilities/interface/EDGetToken.h
  FWCore/Utilities/interface/ESGetToken.h
  FWCore/Utilities/test/BuildFile.xml
  FWCore/Utilities/test/EDGetToken_t.cpp
  FWCore/Utilities/test/test_catch2_EDGetToken.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-rejected

#31703 Patatrack integration - common data formats (5/N)
  CUDADataFormats/Common/interface/HeterogeneousSoA.h
  CUDADataFormats/Common/interface/HostProduct.h
  CUDADataFormats/StdDictionaries/BuildFile.xml
  CUDADataFormats/StdDictionaries/src/classes.h
  CUDADataFormats/StdDictionaries/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, heterogeneous-approved, orp-approved, requires-external, tests-rejected

#31713 Introduce TrackingEffFromHitPatternClientConfigZeroBias and use it for the trackingZeroBias DQM Harvesting sequence
  DQM/TrackingMonitorClient/python/TrackingClientConfig_Tier0_cff.py
  DQM/TrackingMonitorClient/python/TrackingEffFromHitPatternClientConfigZeroBias_cff.py
  DQM/TrackingMonitorClient/python/TrackingEffFromHitPatternClientConfig_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31718 Run3-gex16 Correct numbering scheme for ECAL
  Geometry/CaloEventSetup/interface/CaloGeometryLoader.icc
  Geometry/EcalAlgo/src/EcalPreshowerGeometry.cc
  Geometry/EcalCommonData/interface/EcalBaseNumber.h
  Geometry/EcalCommonData/src/EcalBaseNumber.cc
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step2_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#31706 Fix compilation warning about usage of "const" on return value
  DataFormats/EcalDigi/interface/EcalMatacqDigi.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31639 PPS: xangle-beta* distributions
  CalibPPS/ESProducers/plugins/CTPPSLHCInfoRandomXangleESSource.cc
  Validation/CTPPS/plugins/CTPPSLHCInfoPlotter.cc
  Validation/CTPPS/python/simu_config/base_cff.py
  Validation/CTPPS/python/simu_config/year_2016_postTS2_cff.py
  Validation/CTPPS/python/simu_config/year_2016_preTS2_cff.py
  Validation/CTPPS/python/simu_config/year_2017_cff.py
  Validation/CTPPS/python/simu_config/year_2017_postTS2_cff.py
  Validation/CTPPS/python/simu_config/year_2017_preTS2_cff.py
  Validation/CTPPS/python/simu_config/year_2018_TS1_TS2_cff.py
  Validation/CTPPS/python/simu_config/year_2018_cff.py
  Validation/CTPPS/python/simu_config/year_2018_postTS2_cff.py
  Validation/CTPPS/python/simu_config/year_2018_preTS1_cff.py
  Validation/CTPPS/test/simu/template_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31711 [DD4hep] Introduce FilteredView nextChild
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  DetectorDescription/DDCMS/test/BuildFile.xml
  DetectorDescription/DDCMS/test/DDFilteredView.firstChild.cppunit.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31738 static const -> const for thread safety in DeepMETProducer::produce variable
  RecoMET/METPUSubtraction/plugins/DeepMETProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31740 static const -> const for thread safety in DeepMETProducer::produce variable (bp of #31738)
  RecoMET/METPUSubtraction/plugins/DeepMETProducer.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31741 static const -> const for thread safety in DeepMETProducer::produce variable (bp of #31738)
  RecoMET/METPUSubtraction/plugins/DeepMETProducer.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31725 Fix initialisation of maxChi2 data member in PVClusterComparer
  RecoPixelVertexing/PixelVertexFinding/src/PVClusterComparer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31653 Phase2-hgx263 Try to resolve the orientation index issue for HGCal V13/V14
  Geometry/ForwardCommonData/data/hfnoseCons/v1/hfnoseCons.xml
  Geometry/ForwardCommonData/data/hfnoseCons/v1m/hfnoseCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v10/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v11/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v11m/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v12/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v13/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v14/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v9/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v9a/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v9ap/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v9p/hgcalCons.xml
  Geometry/HGCalCommonData/interface/HGCalParameters.h
  Geometry/HGCalCommonData/interface/HGCalTypes.h
  Geometry/HGCalCommonData/interface/HGCalWaferMask.h
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
  Geometry/HGCalCommonData/src/HGCalParametersFromDD.cc
  Geometry/HGCalCommonData/src/HGCalWaferMask.cc
Labels: code-checks-approved, comparison-available, geometry-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#31748 drop type specs in RecoTauTag
  RecoTauTag/Configuration/python/HPSPFTaus_cff.py
  RecoTauTag/Configuration/python/RecoPFTauTag_cff.py
  RecoTauTag/Configuration/python/boostedHPSPFTaus_cff.py
  RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py
  RecoTauTag/HLTProducers/python/CandidateSeededTrackingRegionsProducer_cff.py
  RecoTauTag/HLTProducers/python/PixelTracksL2Tau_cfi.py
  RecoTauTag/RecoTau/python/HLTPFRecoTauDiscriminationByIsolation_cfi.py
  RecoTauTag/RecoTau/python/PATTauDiscriminationByMVAIsolationRun2_cff.py
  RecoTauTag/RecoTau/python/PFRecoTauChargedHadronBuilderPlugins_cfi.py
  RecoTauTag/RecoTau/python/PFRecoTauChargedHadronProducer_cff.py
  RecoTauTag/RecoTau/python/PFRecoTauChargedHadronQualityPlugins_cfi.py
  RecoTauTag/RecoTau/python/PFRecoTauDiscriminationByIsolation_cfi.py
  RecoTauTag/RecoTau/python/PFRecoTauDiscriminationByLeadingTrackFinding_cfi.py
  RecoTauTag/RecoTau/python/PFRecoTauDiscriminationByMVAIsolation2_cff.py
  RecoTauTag/RecoTau/python/PFRecoTauDiscriminationByMVAIsolationRun2_cff.py
  RecoTauTag/RecoTau/python/RecoTauPiZeroBuilderPlugins_cfi.py
  RecoTauTag/RecoTau/python/RecoTauPiZeroProducer_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#31747 [DD4hep] Replace TBB Containers with std Ones
  DetectorDescription/DDCMS/interface/DDNamespace.h
  DetectorDescription/DDCMS/interface/DDParsingContext.h
  DetectorDescription/DDCMS/interface/DDXMLTags.h
  DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
  DetectorDescription/DDCMS/src/DDAlgoArguments.cc
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  DetectorDescription/DDCMS/src/DDNamespace.cc
  DetectorDescription/DDCMS/test/python/testGeometry2021.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31618 feat: switch to DDXv2 as baseline
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#31734 Run3-gex17 Remove CASTOR geometry from Run3 scenario
  Configuration/Geometry/python/GeometryExtended2021Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2021ZeroMaterialReco_cff.py
  Configuration/Geometry/python/dict2021Geometry.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31755 Run4-hgx263 Take care of Static Analyzer Issues
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalHEFileAlgo.cc
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
  Geometry/HGCalCommonData/test/python/dumpExtendedHGCalGeometryDDD_cfg.py
  Geometry/HGCalCommonData/test/python/hgcalV11_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31681 Update NHitCuts_byTrackAlgo for hgcalTrack
  RecoParticleFlow/PFTracking/python/hgcalTrackCollection_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#31702 Update PPS tags in Run 2 offline GTs for re-miniAOD [10_6_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31666 Phase2 IT RechHit DQM and Validation modules
  DQM/SiTrackerPhase2/interface/TrackerPhase2DQMUtil.h
  DQM/SiTrackerPhase2/plugins/BuildFile.xml
  DQM/SiTrackerPhase2/plugins/Phase2ITMonitorRecHit.cc
  DQM/SiTrackerPhase2/python/Phase2ITMonitorRecHit_cff.py
  DQM/SiTrackerPhase2/python/Phase2TrackerDQMFirstStep_cff.py
  DQM/SiTrackerPhase2/src/BuildFile.xml
  DQM/SiTrackerPhase2/src/TrackerPhase2DQMUtil.cc
  Validation/SiTrackerPhase2V/interface/TrackerPhase2ValidationUtil.h
  Validation/SiTrackerPhase2V/plugins/BuildFile.xml
  Validation/SiTrackerPhase2V/plugins/Phase2ITValidateRecHit.cc
  Validation/SiTrackerPhase2V/python/Phase2ITValidateRecHit_cff.py
  Validation/SiTrackerPhase2V/python/Phase2TrackerValidationFirstStep_cff.py
  Validation/SiTrackerPhase2V/src/BuildFile.xml
  Validation/SiTrackerPhase2V/src/TrackerPhase2ValidationUtil.cc
  Validation/SiTrackerPhase2V/test/ValidateRecHit_TrackerPhase2Standalone_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved, upgrade-approved

#31645 Update 2018 heavy ion data and MC GTs for HI re-miniAOD
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, requires-external, tests-approved, urgent

#31764 Migrate rest of SiStripMonitorDigi to EventSetup consumes
  DQM/SiStripMonitorDigi/interface/SiStripMonitorDigi.h
  DQM/SiStripMonitorDigi/src/SiStripMonitorDigi.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31762 Migrate rest of MuonIdProducer to EventSetup consumes
  RecoMuon/MuonIdentification/interface/MuonShowerDigiFiller.h
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.cc
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.h
  RecoMuon/MuonIdentification/src/MuonShowerDigiFiller.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31742 Change input jet collection for b2g validation in HI wfs
  HLTriggerOffline/B2G/python/b2gHadronicHLTEventValidation_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31758 PPS: theta*_x and theta*_y histograms in DQM
  DQM/CTPPS/plugins/CTPPSCommonDQMSource.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31751 PF validation script update for 11_2 (and some directory cleanup)
  Validation/RecoParticleFlow/Makefile
  Validation/RecoParticleFlow/README.md
  Validation/RecoParticleFlow/plugins/PFClusterValidation.cc
  Validation/RecoParticleFlow/test/DeltaEt.C
  Validation/RecoParticleFlow/test/QCDForPFFast_cfg.py
  Validation/RecoParticleFlow/test/ZTTFastSim_cfg.py
  Validation/RecoParticleFlow/test/castorMerge.py
  Validation/RecoParticleFlow/test/castorSyncOutputs.py
  Validation/RecoParticleFlow/test/copy_aod_QCDForPF_1.sh
  Validation/RecoParticleFlow/test/copy_aod_QCDForPF_2.sh
  Validation/RecoParticleFlow/test/copy_aod_QCDForPF_3.sh
  Validation/RecoParticleFlow/test/copy_aod_QCDForPF_4.sh
  Validation/RecoParticleFlow/test/copy_aod_QCDForPF_5.sh
  Validation/RecoParticleFlow/test/copy_cfg.py
  Validation/RecoParticleFlow/test/copy_display_QCDForPF_1.sh
  Validation/RecoParticleFlow/test/copy_display_QCDForPF_2.sh
  Validation/RecoParticleFlow/test/copy_display_QCDForPF_3.sh
  Validation/RecoParticleFlow/test/copy_display_QCDForPF_4.sh
  Validation/RecoParticleFlow/test/copy_display_QCDForPF_5.sh
  Validation/RecoParticleFlow/test/copy_reco_QCDForPF_1.sh
  Validation/RecoParticleFlow/test/copy_reco_QCDForPF_2.sh
  Validation/RecoParticleFlow/test/copy_reco_QCDForPF_3.sh
  Validation/RecoParticleFlow/test/crab/multicrab.py
  Validation/RecoParticleFlow/test/crab/multicrab_phase2.py
  Validation/RecoParticleFlow/test/datasets.py
  Validation/RecoParticleFlow/test/drop.sh
  Validation/RecoParticleFlow/test/drop_aod_QCDForPF_1.sh
  Validation/RecoParticleFlow/test/drop_aod_QCDForPF_2.sh
  Validation/RecoParticleFlow/test/drop_aod_QCDForPF_3.sh
  Validation/RecoParticleFlow/test/drop_display_QCDForPF_1.sh
  Validation/RecoParticleFlow/test/drop_display_QCDForPF_2.sh
  Validation/RecoParticleFlow/test/drop_display_QCDForPF_3.sh
  Validation/RecoParticleFlow/test/drop_reco_QCDForPF_1.sh
  Validation/RecoParticleFlow/test/drop_reco_QCDForPF_2.sh
  Validation/RecoParticleFlow/test/drop_reco_QCDForPF_3.sh
  Validation/RecoParticleFlow/test/filelist_QCD.txt
  Validation/RecoParticleFlow/test/getHists.py
  Validation/RecoParticleFlow/test/launch_QCDFastSim.sh
  Validation/RecoParticleFlow/test/launch_QCDForPF_FastSim.sh
  Validation/RecoParticleFlow/test/launch_QCDForPF_FullSim.sh
  Validation/RecoParticleFlow/test/launch_QCDFullSim.sh
  Validation/RecoParticleFlow/test/launch_ZTTFastSim.sh
  Validation/RecoParticleFlow/test/launch_ZTTFullSim.sh
  Validation/RecoParticleFlow/test/launch_copy.sh
  Validation/RecoParticleFlow/test/launch_ttbarFastSim.sh
  Validation/RecoParticleFlow/test/launch_ttbarFullSim.sh
  Validation/RecoParticleFlow/test/run_relval.sh
  Validation/RecoParticleFlow/test/setup_cmssw.sh
  Validation/RecoParticleFlow/test/singleTauPt50FastSim.py
  Validation/RecoParticleFlow/test/testTH2Analyzer.C
  Validation/RecoParticleFlow/test/ttbarFastSim_cfg.py
  Validation/RecoParticleFlow/test/ttbar_copy_Fast_cfg.py
  Validation/RecoParticleFlow/test/ttbar_copy_Full_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31767 Run4-hgx264 Changes in view of changed scenario numbering [Validation/HGCalValidation/test]
  Validation/HGCalValidation/test/HGCalWaferStudy.cc
  Validation/HGCalValidation/test/python/protoHGCalSimWatcher_cfg.py
  Validation/HGCalValidation/test/python/protoSimValid_cfg.py
  Validation/HGCalValidation/test/python/protoValid_cfg.py
  Validation/HGCalValidation/test/python/runHFNoseDigiStudy_cfg.py
  Validation/HGCalValidation/test/python/runHFNoseRecHitStudy_cfg.py
  Validation/HGCalValidation/test/python/runHFNoseSimHitStudy_cfg.py
  Validation/HGCalValidation/test/python/runHGCGeomCheck_cfg.py
  Validation/HGCalValidation/test/python/runHGCHitAnalyzer_cfg.py
  Validation/HGCalValidation/test/python/runHGCalDigiStudy_cfg.py
  Validation/HGCalValidation/test/python/runHGCalHitCalibration_cfg.py
  Validation/HGCalValidation/test/python/runHGCalRecHitStudy_cfg.py
  Validation/HGCalValidation/test/python/runHGCalSimHitStudy_cfg.py
  Validation/HGCalValidation/test/python/runHGCalWaferHitCheck_cfg.py
  Validation/HGCalValidation/test/python/runHGCalWaferStudy_cfg.py
  Validation/HGCalValidation/test/python/testHFNoseSimHitStudy_cfg.py
  Validation/HGCalValidation/test/python/testHGCalBHValid_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimHitStudy_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV12_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV13_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV14_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31752 TrackingMaterialProducer fix in volume accounting
  SimTracker/TrackerMaterialAnalysis/plugins/TrackingMaterialProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, urgent

#31686 Run3-alca172 Add PU correction method for isotrack calibration
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibSort.C
  Calibration/HcalCalibAlgos/macros/isotrackApplyRegressor.py
  Calibration/HcalCalibAlgos/macros/isotrackRootTreeMaker.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31737 Run3-gex18 Fix a part of DDEcalBarrelNewAlgo to add the missing volumes in dd4hep
  Geometry/EcalCommonData/data/dd4hep/cms-ecal-geometry.xml
  Geometry/EcalCommonData/plugins/DDEcalBarrelNewAlgo.cc
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalBarrelNewAlgo.cc
  Geometry/EcalCommonData/test/python/runEcalSimParameterDD4Hep_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31776 GEM - fed data size
  EventFilter/GEMRawToDigi/plugins/GEMDigiToRawModule.cc
  EventFilter/GEMRawToDigi/plugins/GEMRawToDigiModule.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31665 Added extar parameters for Geant4 tracking in field
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/MagneticField/interface/CMSFieldManager.h
  SimG4Core/MagneticField/src/CMSFieldManager.cc
  SimG4Core/PhysicsLists/src/MonopoleTransportation.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31777 Fix code-checks errors in FWCore and DataFormats/Common
  DataFormats/Common/interface/Wrapper.h
  FWCore/Concurrency/interface/LimitedTaskQueue.h
  FWCore/Concurrency/interface/SerialTaskQueue.h
  FWCore/Concurrency/interface/WaitingTaskList.h
  FWCore/Framework/interface/ComponentMaker.h
  FWCore/Framework/interface/ModuleChanger.h
  FWCore/Framework/interface/ProcessingController.h
  FWCore/Framework/interface/stream/EDAnalyzerAdaptor.h
  FWCore/Framework/interface/stream/EDAnalyzerAdaptorBase.h
  FWCore/Framework/interface/stream/EDAnalyzerBase.h
  FWCore/Framework/interface/stream/EDFilterAdaptorBase.h
  FWCore/Framework/interface/stream/EDFilterBase.h
  FWCore/Framework/interface/stream/EDProducerAdaptorBase.h
  FWCore/Framework/interface/stream/EDProducerBase.h
  FWCore/Framework/interface/stream/ProducingModuleAdaptor.h
  FWCore/Framework/interface/stream/ProducingModuleAdaptorBase.h
  FWCore/Framework/src/SharedResourcesRegistry.h
  FWCore/Framework/src/UnscheduledConfigurator.h
  FWCore/MessageLogger/interface/MessageDrop.h
  FWCore/MessageLogger/interface/MessageLogger.h
  FWCore/MessageLogger/interface/MessageLoggerQ.h
  FWCore/ParameterSet/interface/ParameterSetDescriptionFiller.h
  FWCore/ParameterSet/interface/ParameterSetDescriptionFillerBase.h
  FWCore/PluginManager/interface/PluginFactory.h
  FWCore/PluginManager/interface/PluginFactoryBase.h
  FWCore/PluginManager/interface/PluginManager.h
  FWCore/PluginManager/interface/SharedLibrary.h
  FWCore/PythonFramework/interface/PythonEventProcessor.h
  FWCore/ServiceRegistry/interface/ServiceMakerBase.h
  FWCore/ServiceRegistry/interface/ServiceRegistry.h
  FWCore/ServiceRegistry/interface/ServiceWrapper.h
  FWCore/ServiceRegistry/interface/ServiceWrapperBase.h
  FWCore/ServiceRegistry/interface/ServicesManager.h
  FWCore/Utilities/interface/ProcessBlockIndex.h
  FWCore/Utilities/interface/RandomNumberGenerator.h
  FWCore/Utilities/interface/TimingServiceBase.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31715 Update SonicTriton client to Triton version 2.3
  HeterogeneousCore/SonicTriton/README.md
  HeterogeneousCore/SonicTriton/interface/TritonClient.h
  HeterogeneousCore/SonicTriton/interface/TritonData.h
  HeterogeneousCore/SonicTriton/interface/triton_utils.h
  HeterogeneousCore/SonicTriton/src/TritonClient.cc
  HeterogeneousCore/SonicTriton/src/TritonData.cc
  HeterogeneousCore/SonicTriton/src/triton_utils.cc
  HeterogeneousCore/SonicTriton/test/TritonGraphProducer.cc
  HeterogeneousCore/SonicTriton/test/fetch_model.sh
  HeterogeneousCore/SonicTriton/test/triton
  HeterogeneousCore/SonicTriton/test/tritonTest_cfg.py
Labels: code-checks-rejected, comparison-available, fully-signed, heterogeneous-approved, orp-approved, requires-external, tests-approved

#31786 fix: adjust jme_nano cff for changes in #31618
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
Labels: analysis-pending, bug-fix, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved, xpog-approved

#31608 Pr 112 x Displaced muon in BMTF and uGMT ( unpacker/emulator/packer)
  DQM/L1TMonitor/interface/L1TStage2BMTF.h
  DQM/L1TMonitor/interface/L1TStage2RegionalMuonCandComp.h
  DQM/L1TMonitor/src/L1TStage2BMTF.cc
  DQM/L1TMonitor/src/L1TStage2RegionalMuonCandComp.cc
  DataFormats/L1TMuon/interface/RegionalMuonCand.h
  DataFormats/L1TMuon/src/RegionalMuonCand.cc
  DataFormats/L1TMuon/src/classes_def.xml
  DataFormats/L1Trigger/interface/Muon.h
  DataFormats/L1Trigger/src/Muon.cc
  DataFormats/L1Trigger/src/classes_def.xml
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFPackerOutput.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFPackerOutput.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFUnpackerOutput.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GMTSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/IntermediateMuonUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/MuonPacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/MuonPacker.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/MuonUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTPacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTPacker.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTUnpacker.h
  EventFilter/L1TRawToDigi/python/bmtfStage2Raw_cfi.py
  EventFilter/L1TRawToDigi/python/gmtStage2Raw_cfi.py
  EventFilter/L1TRawToDigi/python/gtStage2Raw_cfi.py
  L1Trigger/Configuration/python/L1Trigger_EventContent_cff.py
  L1Trigger/Configuration/python/customiseReEmul.py
  L1Trigger/L1TMuon/interface/GMTInternalMuon.h
  L1Trigger/L1TMuon/interface/MicroGMTCancelOutUnit.h
  L1Trigger/L1TMuon/interface/MuonRawDigiTranslator.h
  L1Trigger/L1TMuon/interface/RegionalMuonRawDigiTranslator.h
  L1Trigger/L1TMuon/plugins/L1TMuonProducer.cc
  L1Trigger/L1TMuon/python/simDigis_cff.py
  L1Trigger/L1TMuon/python/simGmtStage2Digis_cfi.py
  L1Trigger/L1TMuon/src/MicroGMTCancelOutUnit.cc
  L1Trigger/L1TMuon/src/MuonRawDigiTranslator.cc
  L1Trigger/L1TMuon/src/RegionalMuonRawDigiTranslator.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanAlgo.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanSectorProcessor.cc
  L1Trigger/L1TMuonBarrel/test/kalmanTools/kmtfAnalysis.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/validation.py
  L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeDataFormat.h
  L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeTfMuonDataFormat.h
  L1Trigger/L1TNtuples/src/L1AnalysisL1Upgrade.cc
  L1Trigger/L1TNtuples/src/L1AnalysisL1UpgradeTfMuon.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#31784 drop type specs in RecoVertex RecoPixelVertexing
  RecoPixelVertexing/PixelLowPtUtilities/python/ClusterShapeExtractor_cfi.py
  RecoPixelVertexing/PixelLowPtUtilities/python/MinBiasCkfTrajectoryFilter_cfi.py
  RecoPixelVertexing/PixelTriplets/python/PixelTripletHLTGenerator_cfi.py
  RecoVertex/Configuration/python/RecoVertex_cff.py
  RecoVertex/Configuration/python/RecoVertex_phase2_timing_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31793 [Geometry] remove unused headers
  Geometry/CaloGeometry/interface/EZMgrVL.h
  Geometry/CommonDetUnit/interface/DetPositioner.h
  Geometry/CommonDetUnit/interface/ModifiedSurfaceGenerator.h
  Geometry/CommonDetUnit/interface/MuonGeomDet.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31775 EventSetupRecord::doGet uses prefetching
  FWCore/Framework/interface/DataProxy.h
  FWCore/Framework/interface/EDConsumerBase.h
  FWCore/Framework/interface/ESRecordsToProxyIndices.h
  FWCore/Framework/interface/EventSetupRecord.h
  FWCore/Framework/interface/EventSetupRecordImpl.h
  FWCore/Framework/src/DataProxy.cc
  FWCore/Framework/src/EDConsumerBase.cc
  FWCore/Framework/src/ESRecordsToProxyIndices.cc
  FWCore/Framework/src/EventSetupRecord.cc
  FWCore/Framework/src/EventSetupRecordImpl.cc
  FWCore/Framework/test/eventsetuprecord_t.cppunit.cc
  FWCore/Integration/test/unit_test_outputs/testSubProcess.grep2.txt
  FWCore/Modules/src/EventSetupRecordDataGetter.cc
  FWCore/Utilities/interface/ESGetTokenGeneric.h
  FWCore/Utilities/interface/TypeIDBase.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31791 Run3-gex19 Make the ECAL numbering scheme compatible between DDD and DD4Hep
  Geometry/EcalCommonData/src/EcalBarrelNumberingScheme.cc
  Geometry/EcalCommonData/src/EcalEndcapNumberingScheme.cc
  Geometry/EcalCommonData/src/EcalPreshowerNumberingScheme.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31749 Moved ClusterRemovalRefSetter to TrackingTools/PatternTools
  DataFormats/TrackerRecHit2D/BuildFile.xml
  RecoTracker/FinalTrackSelectors/plugins/DuplicateListMerger.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackCollectionFilterCloner.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc
  RecoTracker/TkSeedGenerator/plugins/SeedCombiner.cc
  RecoTracker/TrackProducer/src/KfTrackProducerBase.cc
  TrackingTools/PatternTools/interface/ClusterRemovalRefSetter.h
  TrackingTools/PatternTools/interface/ClusterRemovalRefSetter.icc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31779 Migrate rest of {Cosmic,GlobalCosmic,Global,L2,L3,Standalone}MuonProduer to EventSetup consumes
  RecoMuon/CosmicMuonProducer/src/CosmicMuonProducer.cc
  RecoMuon/CosmicMuonProducer/src/GlobalCosmicMuonProducer.cc
  RecoMuon/GlobalMuonProducer/src/GlobalMuonProducer.cc
  RecoMuon/GlobalMuonProducer/src/GlobalMuonProducer.h
  RecoMuon/L2MuonProducer/src/L2MuonProducer.cc
  RecoMuon/L3MuonProducer/src/L3MuonProducer.cc
  RecoMuon/StandAloneMuonProducer/src/StandAloneMuonProducer.cc
  RecoMuon/TrackingTools/interface/MuonTrackFinder.h
  RecoMuon/TrackingTools/src/MuonTrackFinder.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#31794 Run3-gex20 Take care of dd4hep flag to initiate GEM geometry in RECO+dd4hep context
  Configuration/Geometry/python/GeometryExtended2021Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2021ZeroMaterialReco_cff.py
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/GEMGeometryBuilder/plugins/GEMGeometryESModule.cc
  Geometry/GEMGeometryBuilder/plugins/ME0GeometryESModule.cc
  Geometry/GEMGeometryBuilder/python/gemGeometry_cff.py
Labels: code-checks-approved, comparison-available, geometry-approved, orp-approved, pending-signatures, tests-approved, upgrade-pending

#31799 Add ConfigurationDescriptions and ParameterSetDescription to framework forward declarations
  FWCore/Framework/interface/Frameworkfwd.h
  FWCore/Framework/interface/FrameworkfwdMostUsed.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31787 DD4hep workflow: Fix issue at step 2
  Geometry/TrackerGeometryBuilder/src/TrackerGeomBuilderFromGeometricDet.cc
  Geometry/TrackerGeometryBuilder/src/TrackerParametersFromDD.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31792 Removed use of boost::any in edmNew::DetSetVector
  DataFormats/Common/interface/DetSetVectorNew.h
  DataFormats/Common/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31804 [DD] remove unused headers
  DetectorDescription/Core/interface/DDPath.h
  DetectorDescription/Core/interface/DDRegistry.h
  DetectorDescription/RegressionTest/interface/DDExpandedViewDump.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31774 Phase2-hgx264x Correct a small issue in HGCalGeometry and update some test codes
  Geometry/CaloTopology/src/HGCalTopology.cc
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
  Geometry/HGCalGeometry/test/HGCalGeometryCheck.cc
  Geometry/HGCalGeometry/test/HGCalWaferInFileCheck.cc
  Geometry/HGCalGeometry/test/HGCalWaferInFileTest.cc
  Geometry/HGCalGeometry/test/python/hgcGeomAnalyzer_cfg.py
  Geometry/HGCalGeometry/test/python/runCaloCellGeometryTest_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalCellDumpDD4Hep_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalCellDumpDDD_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalCorner_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalGeometryCheck_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalGeometryMouseBite_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalGeometry_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalNeighbor_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalRecHitTool_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalSize_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalWafer_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31772 fix for displaced susy relval production (TRK and EXO validation of displaced tracks)
  Configuration/Generator/python/DisplacedSUSY_stopToBottom_M_300_1000mm_TuneCUETP8M1_13TeV_pythia8_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31803 [HGCAL] Updating RelVal campaign scripts
  Validation/HGCalValidation/python/html.py
  Validation/HGCalValidation/scripts/hgcalPerformanceValidation.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31790 Removed unused DQM headers
  DQM/HcalCommon/interface/ContainerD.h
  DQM/HcalTasks/interface/TestTask.h
  DQMOffline/JetMET/interface/GlobalVariables.h
  DQMOffline/JetMET/interface/SusyDQM/GenericPlotter.h
  DQMOffline/JetMET/interface/SusyDQM/Indexed.h
  DQMOffline/JetMET/interface/SusyDQM/Overlayer.h
  DQMOffline/JetMET/interface/SusyDQM/round_string.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31800 Bug fix hector
  SimTransport/PPSProtonTransport/src/HectorTransport.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31710 MTD geometry: add scenarios D72 (ETL v4) and D73 (ETL v5), remove D53
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2026D72Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D72_cff.py
  Configuration/Geometry/python/GeometryExtended2026D73Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D73_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D72.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D73.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D72XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D73XML_cfi.py
  Geometry/MTDCommonData/data/etl/v4/etl.xml
  Geometry/MTDCommonData/data/etl/v5/etl.xml
  Geometry/MTDCommonData/data/mtdParameters/v3/mtdStructureTopology.xml
  Geometry/MTDCommonData/interface/MTDTopologyMode.h
  Geometry/MTDCommonData/src/ETLNumberingScheme.cc
  Geometry/MTDCommonData/src/MTDTopologyMode.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#31813 Run3-gex21 Correct ECAL numbering schemes to work for dd4hep
  Geometry/EcalCommonData/src/EcalBarrelNumberingScheme.cc
  Geometry/EcalCommonData/src/EcalEndcapNumberingScheme.cc
  Geometry/EcalCommonData/src/EcalPreshowerNumberingScheme.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31785 Tracking Validation: fix some more warnings (Tracking/TrackBHadron)
  Validation/RecoTrack/python/PostProcessorTracker_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31736 Removed vdt dependency on DataFormats/ParticleFlowReco
  DataFormats/ParticleFlowReco/BuildFile.xml
  DataFormats/ParticleFlowReco/src/PFCluster.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31495 nanoAOD: fix electron IP sign
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/PatAlgos/plugins/LeptonUpdater.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-approved

#31809 MF standard sequences cleanup
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/StandardSequences/python/MagneticField_38T_PostLS1_cff.py
  SimMuon/RPCDigitizer/test/runRPCDigiProducer_cfg.py
  Validation/HGCalValidation/test/python/digiValidation_cfg.py
  Validation/HGCalValidation/test/python/rechitValidation_cfg.py
  Validation/HGCalValidation/test/python/simHitValidation_cfg.py
  Validation/MuonGEMHits/test/runGEMRecHitProducer_GE21v7_10deg_cfg.py
  Validation/MuonGEMHits/test/runGEMRecHitProducer_GE21v7_cfg.py
  Validation/RecoJets/test/sequence_validation_cfg.py
  Validation/RecoMET/test/sequence_validation_cfg.py
  Validation/TrackerRecHits/test/stripClusterMCanalysis_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#31660 Legacy csvV2 calibrations for 2018 PbPb data
  PhysicsTools/PatAlgos/python/producersHeavyIons/heavyIonJets_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoBTag/Combined/BuildFile.xml
  RecoBTag/Combined/interface/HeavyIonCSVTagger.h
  RecoBTag/Combined/plugins/HeavyIonCSVESProducer.cc
  RecoBTag/Combined/python/heavyIonCSVComputer_cfi.py
  RecoBTag/Combined/python/heavyIonCSVJetTags_cfi.py
  RecoBTag/Combined/python/heavyIonCSV_trainingSettings.py
  RecoBTag/Combined/src/HeavyIonCSVTagger.cc
  RecoBTag/SecondaryVertex/python/combinedSecondaryVertexV2BJetTags_cfi.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved

#31806 Don't hardcode the global tag in the unit test
  CondCore/ESSources/test/TestConcurrentIOVsCondCore_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, tests-approved

#31750 Removed Framework depencency from L1MuBMTrack
  DataFormats/L1TMuon/interface/L1MuBMTrack.h
  DataFormats/L1TMuon/src/L1MuBMTrack.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#31685 Clean more BuildFiles in DataFormats
  DataFormats/L1GlobalCaloTrigger/test/BuildFile.xml
  DataFormats/L1GlobalTrigger/BuildFile.xml
  DataFormats/L1TCalorimeter/BuildFile.xml
  DataFormats/L1TCalorimeterPhase2/BuildFile.xml
  DataFormats/L1TGlobal/BuildFile.xml
  DataFormats/L1TMuon/BuildFile.xml
  GeometryReaders/XMLIdealGeometryESSource/BuildFile.xml
  HLTriggerOffline/Btag/BuildFile.xml
  L1Trigger/L1TMuon/BuildFile.xml
  L1Trigger/L1TMuonOverlap/BuildFile.xml
Labels: code-checks-approved, comparison-available, dqm-approved, geometry-approved, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#31707 Cleanup the inclusion of CUDAService and other central services
  Configuration/StandardSequences/python/Services_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#31820 [SLHCUpgradeSimulations/Geometry] update writeFile_phase2_cfg.py and use it for unit tests
  SLHCUpgradeSimulations/Geometry/test/BuildFile.xml
  SLHCUpgradeSimulations/Geometry/test/phase2_skimmed_geometry.sh
  SLHCUpgradeSimulations/Geometry/test/testPhase2SkimmedGeometry.cpp
  SLHCUpgradeSimulations/Geometry/test/writeFile_phase2_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31818 Update GEM offline DQM sequences
  DQMOffline/Configuration/python/DQMOfflineCosmics_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOfflineCosmics_cff.py
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Muon/python/gemEfficiencyAnalyzer_cfi.py
  DQMOffline/Muon/python/gemEfficiencyHarvester_cfi.py
  DQMOffline/Muon/python/gem_dqm_offline_client_cff.py
  DQMOffline/Muon/python/gem_dqm_offline_source_cff.py
  DQMOffline/Muon/python/muonMonitors_cff.py
  DQMOffline/Muon/python/muonQualityTests_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31814 Run3-gex22 Update the 2 Reco configuration files for dd4hep
  Configuration/Geometry/python/GeometryDD4hepExtended2021Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021ZeroMaterialReco_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31819 Add GEM offline DQM, backport to 11_1_X
  DQMOffline/Configuration/python/DQMOfflineCosmics_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOfflineCosmics_cff.py
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Muon/interface/GEMEfficiencyAnalyzer.h
  DQMOffline/Muon/interface/GEMEfficiencyHarvester.h
  DQMOffline/Muon/interface/GEMOfflineDQMBase.h
  DQMOffline/Muon/interface/GEMOfflineMonitor.h
  DQMOffline/Muon/python/gemEfficiencyAnalyzer_cfi.py
  DQMOffline/Muon/python/gemEfficiencyHarvester_cfi.py
  DQMOffline/Muon/python/gem_dqm_offline_client_cff.py
  DQMOffline/Muon/python/gem_dqm_offline_source_cff.py
  DQMOffline/Muon/src/GEMEfficiencyAnalyzer.cc
  DQMOffline/Muon/src/GEMEfficiencyHarvester.cc
  DQMOffline/Muon/src/GEMOfflineDQMBase.cc
  DQMOffline/Muon/src/GEMOfflineMonitor.cc
  DQMOffline/Muon/src/SealModule.cc
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31811 SimG4CMS/Tracker: Revert "Additional logs for Validation purposes"
  SimG4CMS/Tracker/src/TrackerG4SimHitNumberingScheme.cc
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step1_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31730 [HGCAL] CLUE and regional factors
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalCLUEAlgo.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalCLUEAlgo.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitWorkerSimple.cc
  RecoLocalCalo/HGCalRecProducers/python/hgcalLayerClusters_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#31778 Migrate rest of {HBHEPhase1,HcalHit,HcalSimple}Reconstructor to EventSetup consumes
  CalibCalorimetry/HcalAlgos/interface/HcalPulseContainmentManager.h
  CalibCalorimetry/HcalAlgos/interface/HcalPulseShapes.h
  CalibCalorimetry/HcalAlgos/src/HcalPulseContainmentManager.cc
  CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc
  RecoLocalCalo/HcalRecAlgos/interface/HcalSimpleRecAlgo.h
  RecoLocalCalo/HcalRecAlgos/interface/SimpleHBHEPhase1Algo.h
  RecoLocalCalo/HcalRecAlgos/interface/parseHBHEPhase1AlgoDescription.h
  RecoLocalCalo/HcalRecAlgos/src/HcalSimpleRecAlgo.cc
  RecoLocalCalo/HcalRecAlgos/src/SimpleHBHEPhase1Algo.cc
  RecoLocalCalo/HcalRecAlgos/src/parseHBHEPhase1AlgoDescription.cc
  RecoLocalCalo/HcalRecProducers/src/HBHEPhase1Reconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/HcalHitReconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/HcalSimpleReconstructor.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31643 Fix issue with Strip CalibTree production and improve unit tests
  CalibTracker/SiStripCommon/BuildFile.xml
  CalibTracker/SiStripCommon/plugins/BuildFile.xml
  CalibTracker/SiStripCommon/plugins/ShallowGainCalibration.cc
  CalibTracker/SiStripCommon/plugins/ShallowGainCalibration.h
  CalibTracker/SiStripCommon/plugins/ShallowTree.cc
  CalibTracker/SiStripCommon/plugins/ShallowTree.h
  CalibTracker/SiStripCommon/test/testProduceCalibrationTree_cfg.py
  CalibTracker/SiStripCommon/test/test_all.sh
Labels: alca-approved, bug-fix, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31727 Require highPurity for isolated tracks in heavy-ion workflows
  PhysicsTools/PatAlgos/plugins/PATIsolatedTrackProducer.cc
  PhysicsTools/PatAlgos/python/slimming/isolatedTracks_cfi.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31658 use standard libuuid functions, add binary uuid option
  FWCore/Framework/src/InputSource.cc
  FWCore/Utilities/interface/GlobalIdentifier.h
  FWCore/Utilities/src/GlobalIdentifier.cc
  FWCore/Utilities/src/Guid.cc
  FWCore/Utilities/src/Guid.h
  FWCore/Utilities/test/Guid_t.cpp
  PhysicsTools/Utilities/plugins/PileUpFilter.cc
Labels: analysis-approved, code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31805 [106X] nanoAOD: fix electron IP sign
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/PatAlgos/plugins/LeptonUpdater.cc
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#31834 Migrate some Muon helper classes and EDProducers to EventSetup consumes
  RecoMuon/GlobalMuonProducer/src/TevMuonProducer.cc
  RecoMuon/GlobalMuonProducer/src/TevMuonProducer.h
  RecoMuon/GlobalTrackingTools/interface/GlobalMuonRefitter.h
  RecoMuon/GlobalTrackingTools/interface/GlobalTrajectoryBuilderBase.h
  RecoMuon/GlobalTrackingTools/plugins/GlobalTrackQualityProducer.cc
  RecoMuon/GlobalTrackingTools/plugins/GlobalTrackQualityProducer.h
  RecoMuon/GlobalTrackingTools/src/GlobalMuonRefitter.cc
  RecoMuon/GlobalTrackingTools/src/GlobalTrajectoryBuilderBase.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31835 Complete EventSetup-consumes migration for HBHEIsolatedNoiseReflagger
  RecoLocalCalo/HcalRecAlgos/interface/HBHEIsolatedNoiseAlgos.h
  RecoLocalCalo/HcalRecAlgos/src/HBHEIsolatedNoiseAlgos.cc
  RecoLocalCalo/HcalRecProducers/src/HBHEIsolatedNoiseReflagger.cc
  RecoLocalCalo/HcalRecProducers/src/HBHEIsolatedNoiseReflagger.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31780 Remove obsolete records
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, requires-external, tests-approved

#31839 Fixed Non Planar Trapezoids
  Geometry/MuonCommonData/data/muonYoke/2021/v5/muonYoke.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#31838 Run3-gem55 Add analyzer to dump content of Muon SimHits
  SimG4CMS/Muon/test/BuildFile.xml
  SimG4CMS/Muon/test/MuonSimHitDump.cc
  SimG4CMS/Muon/test/runMuonSimHitDump_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#31732 Removed unnecessary dependency on sigc++
  CondFormats/PhysicsToolsObjects/BuildFile.xml
  GeneratorInterface/LHEInterface/BuildFile.xml
  HLTrigger/Timer/BuildFile.xml
  SimG4Core/Physics/BuildFile.xml
  SimG4Core/Watcher/BuildFile.xml
  SimMuon/DTDigitizer/test/BuildFile.xml
Labels: alca-approved, code-checks-approved, comparison-available, db-pending, generators-approved, hlt-approved, orp-approved, pending-signatures, simulation-approved, tests-approved

#31626 PPS: removal of obsolete alignment data
  Alignment/CTPPS/data/RPixGeometryCorrections.xml
  Alignment/RPData/LHC/2015_10_18_fill4511/version2/sr/45.xml
  Alignment/RPData/LHC/2015_10_18_fill4511/version2/sr/56.xml
  Alignment/RPData/alignment_tb_run9509_45_no20.xml
  Alignment/RPData/alignment_tb_run9509_56.xml
Labels: alca-approved, code-checks-approved, comparison-available, new-package-pending, orp-approved, pending-signatures, tests-approved

#31696 Add ntracks associated to each SV
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/vertices_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved, xpog-approved

#31099 convert L1TkMuon to stream producer [11_1_X]
  L1Trigger/L1TTrackMatch/plugins/L1TkMuonProducer.cc
Labels: backport-ok, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#31848 [DataFormats/L1TMuon] Fix version in iorules of l1t::RegionalMuonCand
  DataFormats/L1TMuon/src/classes_def.xml
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#31689 Fix to allow concurrent processing of lumisections with ECAL DQM
  DQM/EcalCommon/interface/EcalDQMonitor.h
  DQM/EcalCommon/src/EcalDQMonitor.cc
  DQM/EcalMonitorTasks/interface/ClusterTask.h
  DQM/EcalMonitorTasks/interface/DQWorkerTask.h
  DQM/EcalMonitorTasks/interface/EcalDQMonitorTask.h
  DQM/EcalMonitorTasks/interface/EnergyTask.h
  DQM/EcalMonitorTasks/interface/IntegrityTask.h
  DQM/EcalMonitorTasks/interface/LaserTask.h
  DQM/EcalMonitorTasks/interface/LedTask.h
  DQM/EcalMonitorTasks/interface/OccupancyTask.h
  DQM/EcalMonitorTasks/interface/PresampleTask.h
  DQM/EcalMonitorTasks/interface/RawDataTask.h
  DQM/EcalMonitorTasks/interface/SelectiveReadoutTask.h
  DQM/EcalMonitorTasks/interface/TimingTask.h
  DQM/EcalMonitorTasks/interface/TrigPrimTask.h
  DQM/EcalMonitorTasks/plugins/EcalDQMonitorTask.cc
  DQM/EcalMonitorTasks/src/ClusterTask.cc
  DQM/EcalMonitorTasks/src/EnergyTask.cc
  DQM/EcalMonitorTasks/src/IntegrityTask.cc
  DQM/EcalMonitorTasks/src/LaserTask.cc
  DQM/EcalMonitorTasks/src/LedTask.cc
  DQM/EcalMonitorTasks/src/OccupancyTask.cc
  DQM/EcalMonitorTasks/src/PresampleTask.cc
  DQM/EcalMonitorTasks/src/RawDataTask.cc
  DQM/EcalMonitorTasks/src/SelectiveReadoutTask.cc
  DQM/EcalMonitorTasks/src/TimingTask.cc
  DQM/EcalMonitorTasks/src/TrigPrimTask.cc
Labels: code-checks-approved, comparison-notrun, dqm-approved, fully-signed, orp-approved, requires-external, tests-rejected

#31769 New ETL Geometry Validation
  Validation/MtdValidation/plugins/EtlDigiHitsValidation.cc
  Validation/MtdValidation/plugins/EtlLocalRecoValidation.cc
  Validation/MtdValidation/plugins/EtlSimHitsValidation.cc
  Validation/MtdValidation/plugins/MtdGlobalRecoHarvester.cc
  Validation/MtdValidation/plugins/MtdGlobalRecoValidation.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31841 Added PSetTemplate to allow description of a PSet
  FWCore/ParameterSet/python/Config.py
  FWCore/ParameterSet/python/Mixins.py
  FWCore/ParameterSet/python/Types.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-rejected

#31846 Introduce scenario for 2016 cosmics with realistic conditions
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-rejected

#31845 Update HCAL channel quality for Run 3
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-rejected

#31815 Added LogFwk* logging levels to be used by the framework
  AnalysisDataFormats/TopObjects/interface/TtEvent.h
  AnalysisDataFormats/TopObjects/src/TtEvent.cc
  AnalysisDataFormats/TopObjects/src/TtFullHadronicEvent.cc
  AnalysisDataFormats/TopObjects/src/TtFullLeptonicEvent.cc
  AnalysisDataFormats/TopObjects/src/TtSemiLeptonicEvent.cc
  AnalysisDataFormats/TopObjects/src/printParticle.cc
  AnalysisDataFormats/TopObjects/src/printParticle.h
  FWCore/Framework/src/InputSource.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/MessageLogger/interface/ELseverityLevel.h
  FWCore/MessageLogger/interface/ELseverityLevel.icc
  FWCore/MessageLogger/interface/MessageDrop.h
  FWCore/MessageLogger/interface/MessageLogger.h
  FWCore/MessageLogger/interface/MessageSender.h
  FWCore/MessageLogger/src/ELseverityLevel.cc
  FWCore/MessageLogger/src/MessageDrop.cc
  FWCore/MessageLogger/src/MessageLogger.cc
  FWCore/MessageService/doc/cfg_validation.txt
  FWCore/MessageService/python/MessageLogger_ReleaseValidation_cfi.py
  FWCore/MessageService/python/MessageLogger_cfi.py
  FWCore/MessageService/src/MessageLogger.cc
  FWCore/MessageService/src/MessageLoggerScribe.cc
  FWCore/MessageService/src/MessageServicePSetValidation.cc
  FWCore/MessageService/src/MessageServicePSetValidation.h
  FWCore/MessageService/src/ThreadSafeLogMessageLoggerScribe.cc
  FWCore/MessageService/test/standAloneTest.cpp
  FWCore/MessageService/test/u14_cfg.py
  FWCore/MessageService/test/u21_cfg.py
  FWCore/MessageService/test/unit_test_outputs/infos.log
  FWCore/MessageService/test/unit_test_outputs/standAloneWithMessageLogger.cerr
  FWCore/MessageService/test/unit_test_outputs/u17_all.log
  FWCore/MessageService/test/unit_test_outputs/u23_infos.log
  FWCore/MessageService/test/unit_test_outputs/u25_only.log
  FWCore/MessageService/test/unit_test_outputs/u27FJR.xml
  FWCore/MessageService/test/unit_test_outputs/u27_infos.log
  FWCore/MessageService/test/unit_test_outputs/u31_infos.log
  FWCore/MessageService/test/unit_test_outputs/u33_all.log
  FWCore/MessageService/test/unit_test_outputs/u33d_all.log
  FWCore/MessageService/test/unit_test_outputs/u36_only.log
  FWCore/MessageService/test/unit_test_outputs/u3_statistics.log
  FWCore/MessageService/test/unit_test_outputs/u4_another.log
  FWCore/MessageService/test/unit_test_outputs/u5_default.log
  FWCore/MessageService/test/unit_test_outputs/u5_noreset.log
  FWCore/MessageService/test/unit_test_outputs/u5_reset.log
  FWCore/Modules/test/test_catch2_LogErrorFilter.cc
  Geometry/MTDCommonData/test/testMTDGeometry.py
  Geometry/MTDCommonData/test/testMTDinDD4hep.py
  Geometry/MTDCommonData/test/testMTDinDDD.py
  Geometry/MTDGeometryBuilder/test/dd4hep_mtd_cfg.py
  Geometry/MTDGeometryBuilder/test/mtd_cfg.py
  Geometry/MTDNumberingBuilder/test/dd4hep_mtd_cfg.py
  Geometry/MTDNumberingBuilder/test/mtd_cfg.py
Labels: analysis-approved, code-checks-approved, comparison-available, core-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31860 Removed unused fwkJobReports from MessageLogger in IOMC Subsystem
  IOMC/Input/test/testWriter_cfg.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#31470 Add anti-electron tauID for phase2
  CommonTools/RecoAlgos/plugins/ElectronCollectionMerger.cc
  PhysicsTools/PatAlgos/plugins/PATTauProducer.cc
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py
  RecoTauTag/RecoTau/BuildFile.xml
  RecoTauTag/RecoTau/interface/AntiElectronDeadECAL.h
  RecoTauTag/RecoTau/interface/AntiElectronIDMVA6.h
  RecoTauTag/RecoTau/interface/PositionAtECalEntranceComputer.h
  RecoTauTag/RecoTau/plugins/TauDiscriminationAgainstElectronDeadECAL.cc
  RecoTauTag/RecoTau/plugins/TauDiscriminationAgainstElectronMVA6.cc
  RecoTauTag/RecoTau/python/PATTauDiscriminationAgainstElectronMVA6Phase2_cff.py
  RecoTauTag/RecoTau/python/PFRecoTauDiscriminationAgainstElectronMVA6Phase2_cff.py
  RecoTauTag/RecoTau/python/tauDiscriminationAgainstElectronMVA6Phase2_mvaDefs_cff.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/src/AntiElectronDeadECAL.cc
  RecoTauTag/RecoTau/src/AntiElectronIDMVA6.cc
  RecoTauTag/RecoTau/src/PositionAtECalEntranceComputer.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#31861 Removed unused fwkJobReports from MessageLogger in SLHCUpgradeSimulations Subsystem
  SLHCUpgradeSimulations/Geometry/test/print_geominfo_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31858 Removed unused fwkJobReports from MessageLogger in Geometry Subsystem
  Geometry/CMSCommonData/test/runPrint_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#31831 Add maximum of pileup pT hats in JME custom NanoAOD
  PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/NanoAOD/python/globals_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved, xpog-approved

#31698 Sub-event aware genJet and parton matching for HI miniAOD
  Configuration/ProcessModifiers/python/genJetSubEvent_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  PhysicsTools/PatAlgos/plugins/PATGenJetSlimmer.cc
  PhysicsTools/PatAlgos/python/mcMatchLayer0/jetMatch_cfi.py
  PhysicsTools/PatAlgos/python/producersHeavyIons/heavyIonJets_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/slimming/slimmedGenJets_cfi.py
  RecoHI/HiJetAlgos/plugins/HiSignalGenJetProducer.cc
  RecoHI/HiJetAlgos/plugins/HiSignalParticleProducer.cc
  RecoJets/JetProducers/plugins/SubEventGenJetProducer.cc
  RecoJets/JetProducers/plugins/SubEventGenJetProducer.h
Labels: analysis-pending, code-checks-approved, comparison-available, operations-approved, orp-approved, pdmv-approved, pending-signatures, reconstruction-approved, tests-approved, upgrade-approved

#31857 Removed unused fwkJobReports from MessageLogger in GeneratorInterface Subsystem
  GeneratorInterface/ExternalDecays/test/Py6EvtGenFilter_cfg.py
  GeneratorInterface/ExternalDecays/test/Py6GenFilter_Photos_cfg.py
  GeneratorInterface/ExternalDecays/test/Py6GenFilter_W2TauNu_Tauola_cfg.py
  GeneratorInterface/ExternalDecays/test/Py8GenFilter_Onia_EvtGen_cfg.py
  GeneratorInterface/ExternalDecays/test/Py8GenFilter_Photos_cfg.py
  GeneratorInterface/ExternalDecays/test/Py8GenFilter_W2TauNu_Tauola_cfg.py
  GeneratorInterface/ExternalDecays/test/Py8_Z2tautau_tauolacxx_cfg.py
  GeneratorInterface/ExternalDecays/test/TauSpinnerWTest.py
  GeneratorInterface/ExternalDecays/test/TauSpinnerZTest.py
  GeneratorInterface/GenExtensions/test/EDDE_cfg.py
  GeneratorInterface/GenFilters/test/comphep_singletop_Py8.py
  GeneratorInterface/GenFilters/test/test_EMJetHeep_cfg.py
  GeneratorInterface/GenFilters/test/test_EMJetMB_cfg.py
  GeneratorInterface/Pythia6Interface/test/AlpgenSource_Py6Had_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6EvtGenFilter_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_CSAMode_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_ElectronProtonInitialState_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_EvtGenTest_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_PDG_convert_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_Photos_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_SLHA_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_Ztautau_Tauola_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_gluino_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6GenFilter_stophadrons_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6HadFilter_RestoreRNDM_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6HadFilter_cfg.py
  GeneratorInterface/Pythia6Interface/test/Py6HadFilter_mgmatching_cfg.py
  GeneratorInterface/TauolaInterface/test/TauSpinnerWTest.py
  GeneratorInterface/TauolaInterface/test/TauSpinnerZTest.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#31855 Removed unused fwkJobReports from MessageLogger from DQMServices Subsystem
  DQMServices/Components/python/MessageLogger_cfi.py
  DQMServices/Examples/python/test/MessageLogger_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31862 Removed unused fwkJobReports from MessageLogger in Validation Subsystem
  Validation/GlobalDigis/python/MessageLogger_cfi.py
  Validation/GlobalHits/python/MessageLogger_cfi.py
  Validation/GlobalRecHits/python/MessageLogger_cfi.py
  Validation/RecoParticleFlow/Benchmarks/ElectronBenchmarkGeneric/benchmark_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#31829 ES DQM: Enable concurrent processing of lumisections
  DQM/EcalPreshowerMonitorModule/interface/ESIntegrityTask.h
  DQM/EcalPreshowerMonitorModule/src/ESIntegrityTask.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, requires-external, tests-approved

#31591 Nano gen dqm
  Configuration/Generator/python/Hadronizer_TuneCP5_13TeV_MLM_5f_max4j_LHE_pythia8_cff.py
  Configuration/Generator/python/Hadronizer_TuneCP5_13TeV_powhegEmissionVeto2p_pythia8_cff.py
  Configuration/PyReleaseValidation/python/relval_generator.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Configuration/python/autoDQM.py
  PhysicsTools/NanoAOD/python/NanoAODEDMEventContent_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nanogenDQM_cff.py
  PhysicsTools/NanoAOD/python/nanogen_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, generators-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved, urgent, xpog-approved

#31656 Partially fix CLCT position bias after CCLUT (CCLUT-8)
  DataFormats/CSCDigi/interface/CSCCLCTDigi.h
  DataFormats/CSCDigi/interface/CSCCorrelatedLCTDigi.h
  DataFormats/CSCDigi/src/CSCCLCTDigi.cc
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/test/macros/CCLUTLinearFitWriter.cpp
  Validation/MuonGEMDigis/src/GEMDigiMatcher.cc
  Validation/MuonHits/interface/CSCSimHitMatcher.h
  Validation/MuonHits/interface/MuonSimHitMatcher.h
  Validation/MuonHits/src/CSCSimHitMatcher.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved, urgent

#31763 Complete EventSetup migration for bunch of L1 modules
  DQM/L1TMonitor/interface/L1TMenuHelper.h
  DQM/L1TMonitor/interface/L1TRate.h
  DQM/L1TMonitor/interface/L1TSync.h
  DQM/L1TMonitor/src/L1TMenuHelper.cc
  DQM/L1TMonitor/src/L1TRate.cc
  DQM/L1TMonitor/src/L1TSync.cc
  DQMOffline/L1Trigger/interface/L1TRate_Offline.h
  DQMOffline/L1Trigger/interface/L1TSync_Offline.h
  DQMOffline/L1Trigger/src/L1TRate_Offline.cc
  DQMOffline/L1Trigger/src/L1TSync_Offline.cc
  L1Trigger/GlobalTrigger/interface/L1GlobalTriggerGTL.h
  L1Trigger/GlobalTrigger/src/L1GlobalTriggerGTL.cc
  L1Trigger/GlobalTriggerAnalyzer/src/L1GtUtils.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#31801 Migrate rest of CSCTFTrackProducer to EventSetup consumes
  L1Trigger/CSCTrackFinder/interface/CSCTFPtLUT.h
  L1Trigger/CSCTrackFinder/interface/CSCTFSectorProcessor.h
  L1Trigger/CSCTrackFinder/plugins/CSCTFTrackProducer.cc
  L1Trigger/CSCTrackFinder/plugins/CSCTFTrackProducer.h
  L1Trigger/CSCTrackFinder/src/CSCTFPtLUT.cc
  L1Trigger/CSCTrackFinder/src/CSCTFSectorProcessor.cc
  L1Trigger/CSCTrackFinder/src/CSCTFTrackBuilder.cc
  L1Trigger/CSCTrackFinder/src/CSCTFTrackBuilder.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#31844 remove hgcal local reco from reconstruction_trackingOnlyTask for trackingPhase2PU140
  Configuration/StandardSequences/python/Reconstruction_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#31853 Removed unused fwkJobReports from MessageLogger in Calibration Subsystem
  Calibration/LumiAlCaRecoProducers/test/PCC_Random_Event_Integrator_cfg.py
  Calibration/LumiAlCaRecoProducers/test/PCC_Random_Event_cfg.py
  Calibration/LumiAlCaRecoProducers/test/PCC_Random_cfg.py
  Calibration/LumiAlCaRecoProducers/test/PCC_ZeroBias_cfg.py
  Calibration/LumiAlCaRecoProducers/test/raw_ZeroBias_cfg.py
  Calibration/LumiAlCaRecoProducers/test/raw_corr_Random_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31852 Removed unused fwkJobReports from MessageLogger in Alignment Subsystem
  Alignment/LaserAlignmentSimulation/test/LaserSimulation_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#31781 Clean up a few dead assignments from CalibCalorimetry/HcalAlgos and RecoMuon/TrackingTools
  CalibCalorimetry/HcalAlgos/src/HcalLogicalMapGenerator.cc
  CalibCalorimetry/HcalAlgos/src/HcalPedestalAnalysis.cc
  RecoMuon/TrackingTools/src/MuonErrorMatrix.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, urgent

#31850 Run3-alca173 Use ESGetToken and LogVerbatim
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksProducerFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsolatedBunchFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsolatedBunchSelector.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaLowPUHBHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaDiJetsProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaHBHEMuonProducer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaIsoTracksProducer.cc
  Calibration/HcalAlCaRecoProducers/src/ProducerAnalyzer.cc
  Calibration/HcalAlCaRecoProducers/src/ProducerAnalyzer.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved
