Repository cms-sw/cmssw, pull requests merged in 2020-07, with the labels that each got.

#30454 fix stacked efficiency plots
  Validation/RecoTrack/test/publicPlots/plot.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30363 New Package - Phase2 L1TTrackMatch
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/L1TTrackMatch/BuildFile.xml
  L1Trigger/L1TTrackMatch/interface/L1TkElectronEtComparator.h
  L1Trigger/L1TTrackMatch/interface/L1TkElectronTrackMatchAlgo.h
  L1Trigger/L1TTrackMatch/interface/L1TkMuCorrDynamicWindows.h
  L1Trigger/L1TTrackMatch/interface/L1TkMuMantra.h
  L1Trigger/L1TTrackMatch/interface/MuMatchWindow.h
  L1Trigger/L1TTrackMatch/interface/pTFrom2Stubs.h
  L1Trigger/L1TTrackMatch/plugins/BuildFile.xml
  L1Trigger/L1TTrackMatch/plugins/L1TkElectronTrackProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkEmParticleProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkFastVertexProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkMuonProducer.cc
  L1Trigger/L1TTrackMatch/python/L1TkElectronTrackProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/L1TkEmParticleProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/L1TkMuonProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/L1TkObjectProducers_cff.py
  L1Trigger/L1TTrackMatch/python/L1TkPrimaryVertexProducer_cfi.py
  L1Trigger/L1TTrackMatch/src/L1TkElectronTrackMatchAlgo.cc
  L1Trigger/L1TTrackMatch/src/L1TkMuCorrDynamicWindows.cc
  L1Trigger/L1TTrackMatch/src/L1TkMuMantra.cc
  L1Trigger/L1TTrackMatch/src/MuMatchWindow.cc
  L1Trigger/L1TTrackMatch/src/pTFrom2Stubs.cc
Labels: code-checks-approved, comparison-pending, l1-pending, orp-approved, pending-signatures, tests-pending, upgrade-pending, urgent

#30479 Turn on L1 track trigger in Phase2C8 and later
  Configuration/Eras/python/Era_Phase2C8_cff.py
  Configuration/Eras/python/Modifier_phase2_trackerV14_cff.py
  Configuration/StandardSequences/python/Eras.py
  Configuration/StandardSequences/python/L1TrackTrigger_cff.py
Labels: code-checks-approved, comparison-pending, operations-pending, orp-approved, pending-signatures, tests-approved

#30480 Move L1TrackTrigger step before L1 step
  Configuration/PyReleaseValidation/python/relval_steps.py
  Validation/Geometry/test/runMaterialDumpAnalyser_PhaseII.sh
Labels: code-checks-approved, comparison-pending, dqm-approved, geometry-pending, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#30473 Restore "Run4-hgx247 Add some new features for HGCal" (#30323)
  Geometry/CaloTopology/interface/HGCalTopology.h
  Geometry/CaloTopology/src/HGCalTopology.cc
  Geometry/HGCalCommonData/interface/HGCalDDDConstants.h
  Geometry/HGCalCommonData/interface/HGCalGeomTools.h
  Geometry/HGCalCommonData/interface/HGCalTypes.h
  Geometry/HGCalCommonData/python/testHGCalV13XML_cfi.py
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalCommonData/src/HGCalGeomTools.cc
  Geometry/HGCalGeometry/test/HGCalGeomLocatorTester.cc
  Geometry/HGCalGeometry/test/python/testHGCalGeomLocator_cfg.py
Labels: code-checks-approved, comparison-available, geometry-pending, orp-approved, pending-signatures, requires-external, tests-approved, upgrade-pending

#30470 [HGC trigger] Update mapping for V11
  L1Trigger/L1THGCal/python/customTriggerGeometry.py
  L1Trigger/L1THGCal/python/hgcalTriggerPrimitives_cff.py
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, requires-external, tests-approved, upgrade-pending

#30344 DT TPG for Phase-2
  L1Trigger/DTTriggerPhase2/BuildFile.xml
  L1Trigger/DTTriggerPhase2/doc/qualities.txt
  L1Trigger/DTTriggerPhase2/interface/CandidateGroup.h
  L1Trigger/DTTriggerPhase2/interface/DTPattern.h
  L1Trigger/DTTriggerPhase2/interface/DTprimitive.h
  L1Trigger/DTTriggerPhase2/interface/HoughGrouping.h
  L1Trigger/DTTriggerPhase2/interface/InitialGrouping.h
  L1Trigger/DTTriggerPhase2/interface/MPFilter.h
  L1Trigger/DTTriggerPhase2/interface/MPQualityEnhancerFilter.h
  L1Trigger/DTTriggerPhase2/interface/MPRedundantFilter.h
  L1Trigger/DTTriggerPhase2/interface/MotherGrouping.h
  L1Trigger/DTTriggerPhase2/interface/MuonPath.h
  L1Trigger/DTTriggerPhase2/interface/MuonPathAnalyzer.h
  L1Trigger/DTTriggerPhase2/interface/MuonPathAnalyzerInChamber.h
  L1Trigger/DTTriggerPhase2/interface/MuonPathAnalyzerPerSL.h
  L1Trigger/DTTriggerPhase2/interface/MuonPathAssociator.h
  L1Trigger/DTTriggerPhase2/interface/PseudoBayesGrouping.h
  L1Trigger/DTTriggerPhase2/interface/RPCIntegrator.h
  L1Trigger/DTTriggerPhase2/interface/constants.h
  L1Trigger/DTTriggerPhase2/plugins/BuildFile.xml
  L1Trigger/DTTriggerPhase2/plugins/CalibratedDigis.cc
  L1Trigger/DTTriggerPhase2/plugins/DTTrigPhase2Prod.cc
  L1Trigger/DTTriggerPhase2/python/CalibratedDigis_cfi.py
  L1Trigger/DTTriggerPhase2/python/CalibratedDigishlt_cfi.py
  L1Trigger/DTTriggerPhase2/python/HoughGrouping_cfi.py
  L1Trigger/DTTriggerPhase2/python/PseudoBayesGrouping_cfi.py
  L1Trigger/DTTriggerPhase2/python/dtTriggerPhase2PrimitiveDigis_cfi.py
  L1Trigger/DTTriggerPhase2/src/CandidateGroup.cc
  L1Trigger/DTTriggerPhase2/src/DTPattern.cc
  L1Trigger/DTTriggerPhase2/src/DTprimitive.cc
  L1Trigger/DTTriggerPhase2/src/HoughGrouping.cc
  L1Trigger/DTTriggerPhase2/src/InitialGrouping.cc
  L1Trigger/DTTriggerPhase2/src/MPFilter.cc
  L1Trigger/DTTriggerPhase2/src/MPQualityEnhancerFilter.cc
  L1Trigger/DTTriggerPhase2/src/MPRedundantFilter.cc
  L1Trigger/DTTriggerPhase2/src/MotherGrouping.cc
  L1Trigger/DTTriggerPhase2/src/MuonPath.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAnalyzer.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAnalyzerInChamber.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAnalyzerPerSL.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc
  L1Trigger/DTTriggerPhase2/src/PseudoBayesGrouping.cc
  L1Trigger/DTTriggerPhase2/src/RPCIntegrator.cc
  L1Trigger/DTTriggerPhase2/test/primitivesPhase2Prod_over_dTDigis_and_4Dsegments_cfg.py
  L1Trigger/DTTriggerPhase2/test/primitivesPhase2Prod_over_dTDigis_and_4Dsegments_cfg_withRPC.py
  L1Trigger/DTTriggerPhase2/test/primitivesPhase2Prod_over_hlt_parallel_cfg.py
  L1Trigger/DTTriggerPhase2/test/primitivesPhase2Prod_over_mc_cfg.py
  L1Trigger/DTTriggerPhase2/test/primitivesPhase2Prod_over_unpacked_cfg.py
  L1Trigger/DTTriggerPhase2/test/prod_Zmu_digis_segments_cfg.py
  L1Trigger/DTTriggerPhase2/test/test_primitivesPhase2Prod_over_dTDigis_and_4Dsegments_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, requires-external, tests-approved, upgrade-approved, urgent

#30423 Phase2-hgx250 Comparison of results from flat file and from insitu checks
  Geometry/CaloTopology/interface/HGCalTopology.h
  Geometry/CaloTopology/src/HGCalTopology.cc
  Geometry/HGCalCommonData/data/hgcal/v13/hgcal.xml
  Geometry/HGCalCommonData/interface/HGCalDDDConstants.h
  Geometry/HGCalCommonData/python/testHGCalV13XML_cfi.py
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalGeometry/test/HGCalWaferInFileCheck.cc
  Geometry/HGCalGeometry/test/python/testHGCalWaferInFile_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30476 Reduce boost dependency in DQM/TrackingMonitor
  DQM/TrackingMonitor/src/PackedCandidateTrackValidator.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30475 added esConsumes to modules in EventFilter/SiStripRawToDigi
  EventFilter/SiStripRawToDigi/plugins/ExcludedFEDListProducer.cc
  EventFilter/SiStripRawToDigi/plugins/ExcludedFEDListProducer.h
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRawModule.cc
  EventFilter/SiStripRawToDigi/plugins/SiStripDigiToRawModule.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30474 added esConsumes to modules on EventFilter/SiPixelRawToDigi
  EventFilter/SiPixelRawToDigi/interface/PixelUnpackingRegions.h
  EventFilter/SiPixelRawToDigi/plugins/SiPixelDigiToRaw.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.h
  EventFilter/SiPixelRawToDigi/src/PixelUnpackingRegions.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30459 added esConsumes to modules in EventFilter/RPCRawToDigi
  EventFilter/RPCRawToDigi/interface/RPCPackingModule.h
  EventFilter/RPCRawToDigi/plugins/RPCAMCRawToDigi.cc
  EventFilter/RPCRawToDigi/plugins/RPCAMCUnpacker.cc
  EventFilter/RPCRawToDigi/plugins/RPCAMCUnpacker.h
  EventFilter/RPCRawToDigi/plugins/RPCAMCUnpackerFactory.h
  EventFilter/RPCRawToDigi/plugins/RPCCPPFUnpacker.cc
  EventFilter/RPCRawToDigi/plugins/RPCCPPFUnpacker.h
  EventFilter/RPCRawToDigi/plugins/RPCTwinMuxDigiToRaw.cc
  EventFilter/RPCRawToDigi/plugins/RPCTwinMuxDigiToRaw.h
  EventFilter/RPCRawToDigi/plugins/RPCTwinMuxRawToDigi.cc
  EventFilter/RPCRawToDigi/plugins/RPCTwinMuxRawToDigi.h
  EventFilter/RPCRawToDigi/src/RPCPackingModule.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30127 TBLayer computeCrossings doesn't allow for some displaced starting points
  RecoTracker/TkDetLayers/src/TBLayer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30236 Modified photon selection for heavy-ion miniAOD
  RecoEgamma/EgammaPhotonProducers/python/reducedEgamma_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#30446 [Pixel 3D Digitizer] Fix wrong channel assignation
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#30496 Added missing include to fix the ROOT IBs build errors
  L1Trigger/L1TTrackMatch/interface/L1TkMuMantra.h
Labels: code-checks-approved, comparison-pending, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-pending

#30255 embed hi photon isolation in pat::photon userdata
  RecoEgamma/EgammaTools/interface/EGExtraInfoModifierFromValueMaps.h
  RecoEgamma/EgammaTools/plugins/EGExtraInfoModifierFromValueMaps.cc
  RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py
Labels: code-checks-approved, comparison-pending, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30498 Fix modifiers in Phase2 L1T sequences and add Phase2 L1T objects to FEVTDEBUG EventContent
  Configuration/StandardSequences/python/L1TrackTrigger_cff.py
  L1Trigger/Configuration/python/L1Trigger_EventContent_cff.py
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/L1TMuon/python/simDigis_cff.py
Labels: code-checks-approved, comparison-available, l1-pending, operations-pending, orp-approved, pending-signatures, tests-approved

#30484 Include full Phase-2 L1Trigger in TestOldDigi workflows
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/L1TrackTrigger_cff.py
  L1Trigger/Configuration/python/customisePhase2TTNoMC.py
Labels: code-checks-pending, comparison-available, l1-pending, operations-pending, orp-approved, pdmv-pending, pending-signatures, tests-approved, upgrade-pending

#30516 [HGC trigger] Update mapping for V11 (backport 11_1_X)
  L1Trigger/L1THGCal/python/customTriggerGeometry.py
  L1Trigger/L1THGCal/python/hgcalTriggerPrimitives_cff.py
Labels: backport-ok, comparison-pending, l1-pending, orp-approved, pending-signatures, requires-external, tests-approved, upgrade-pending

#30528 Bug-fix in L1Trigger/Phase2L1ParticleFlow/python/l1pfJetMet_cff.py
  L1Trigger/Phase2L1ParticleFlow/python/l1pfJetMet_cff.py
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-pending

#30497 TkAl: Add pool check to condor submission (11_1_X backport)
  Alignment/MillePedeAlignmentAlgorithm/scripts/mps_fire.py
  Alignment/OfflineValidation/scripts/validateAlignments.py
Labels: alca-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30237 Modified muon selection for heavy-ion miniAOD
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30253 Add muon ID selectors for packed candidate collections
  DataFormats/PatCandidates/src/classes_def_objects.xml
  PhysicsTools/PatAlgos/plugins/PackedCandidateMuonSelectorProducer.cc
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30318 Sonic client for Triton server
  HeterogeneousCore/SonicCore/README.md
  HeterogeneousCore/SonicCore/interface/SonicClientBase.h
  HeterogeneousCore/SonicTriton/BuildFile.xml
  HeterogeneousCore/SonicTriton/interface/TritonClient.h
  HeterogeneousCore/SonicTriton/src/TritonClient.cc
  HeterogeneousCore/SonicTriton/test/BuildFile.xml
  HeterogeneousCore/SonicTriton/test/README.md
  HeterogeneousCore/SonicTriton/test/TritonImageProducer.cc
  HeterogeneousCore/SonicTriton/test/fetch_model.sh
  HeterogeneousCore/SonicTriton/test/imageTest_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#30456 added esConsumes to modules in SimMuon/RPCDigitizer
  SimMuon/RPCDigitizer/src/RPCDigiProducer.cc
  SimMuon/RPCDigitizer/src/RPCDigiProducer.h
  SimMuon/RPCDigitizer/src/RPCSimAsymmetricCls.cc
  SimMuon/RPCDigitizer/src/RPCSimAverage.cc
  SimMuon/RPCDigitizer/src/RPCSimAverageNoise.cc
  SimMuon/RPCDigitizer/src/RPCSimAverageNoiseEff.cc
  SimMuon/RPCDigitizer/src/RPCSimAverageNoiseEffCls.cc
  SimMuon/RPCDigitizer/src/RPCSimModelTiming.cc
  SimMuon/RPCDigitizer/src/RPCSimSetUp.cc
  SimMuon/RPCDigitizer/src/RPCSynchronizer.cc
  SimMuon/RPCDigitizer/src/RPCandIRPCDigiProducer.cc
  SimMuon/RPCDigitizer/src/RPCandIRPCDigiProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30364 Revision of tau quality cut configuration
  RecoTauTag/RecoTau/interface/PFTauPrimaryVertexProducerBase.h
  RecoTauTag/RecoTau/interface/RecoTauQualityCuts.h
  RecoTauTag/RecoTau/plugins/PFRecoTauChargedHadronProducer.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByIsolation.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByIsolationContainer.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByNProngs.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroProducer.cc
  RecoTauTag/RecoTau/plugins/RecoTauProducer.cc
  RecoTauTag/RecoTau/python/PFRecoTauQualityCuts_cfi.py
  RecoTauTag/RecoTau/src/PFTauPrimaryVertexProducerBase.cc
  RecoTauTag/RecoTau/src/RecoTauQualityCuts.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30513 fix compilation with EDM_ML_DEBUG in Geometry/HGCalGeometry/src/HGCalGeometry.cc
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30514 Remove boost::ptr_map dependency in DQM/EcalCommon
  DQM/EcalCommon/interface/MESet.h
  DQM/EcalCommon/plugins/EcalMEFormatter.cc
  DQM/EcalCommon/src/MESet.cc
  DQM/EcalMonitorClient/src/DQWorkerClient.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30488 Phase2-geox03 Correct the overlap in forward region
  Geometry/ForwardCommonData/data/brm/2026/v1/brm.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30481 Concurrent ExternalLHEProducer (backport #28899)
  GeneratorInterface/LHEInterface/plugins/BuildFile.xml
  GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc
  GeneratorInterface/LHEInterface/test/BuildFile.xml
  GeneratorInterface/LHEInterface/test/run_dummy_script.sh
  GeneratorInterface/LHEInterface/test/test_catch2_ExternalLHEProducer.cc
  GeneratorInterface/LHEInterface/test/test_catch2_main.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#30531 Turnon L1T TrackTrigger, TrackMatch, PF, update TestOldDigiWorkflow, add objects in FEVTDEBUG (11_1_X backport)
  Configuration/Eras/python/Era_Phase2C8_cff.py
  Configuration/Eras/python/Modifier_phase2_trackerV14_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/L1TrackTrigger_cff.py
  DataFormats/L1TrackTrigger/interface/TTDTC.h
  DataFormats/L1TrackTrigger/src/TTDTC.cc
  L1Trigger/Configuration/python/L1Trigger_EventContent_cff.py
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/Configuration/python/customisePhase2TTNoMC.py
  L1Trigger/L1TMuon/python/simDigis_cff.py
  Validation/Geometry/test/runMaterialDumpAnalyser_PhaseII.sh
Labels: comparison-pending, dqm-pending, geometry-pending, l1-pending, operations-pending, orp-approved, pdmv-pending, pending-signatures, requires-external, tests-started, upgrade-pending

#30452 PPS: re-alignment module
  RecoPPS/Local/plugins/PPSLocalTrackLiteReAligner.cc
  RecoPPS/Local/test/re_alignment/align_base.xml
  RecoPPS/Local/test/re_alignment/align_corr.xml
  RecoPPS/Local/test/re_alignment/reco_align_corr_cfg.py
  RecoPPS/Local/test/re_alignment/reco_base_align_cfg.py
  RecoPPS/Local/test/re_alignment/reco_full_align_cfg.py
  RecoPPS/Local/test/re_alignment/run_all
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30464 HCAL: more Validation wfs cleaning
  Validation/Configuration/python/globalValidation_cff.py
  Validation/Configuration/python/noiseSimValid_cff.py
  Validation/RecoHI/python/globalValidationHeavyIons_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#30468 Re-add modules for GEM offline DQM
  DQMOffline/Muon/interface/GEMEfficiencyAnalyzer.h
  DQMOffline/Muon/interface/GEMEfficiencyHarvester.h
  DQMOffline/Muon/interface/GEMOfflineDQMBase.h
  DQMOffline/Muon/interface/GEMOfflineMonitor.h
  DQMOffline/Muon/python/gemEfficiencyAnalyzer_cfi.py
  DQMOffline/Muon/python/gemEfficiencyHarvester_cfi.py
  DQMOffline/Muon/python/muonMonitors_cff.py
  DQMOffline/Muon/python/muonQualityTests_cff.py
  DQMOffline/Muon/src/GEMEfficiencyAnalyzer.cc
  DQMOffline/Muon/src/GEMEfficiencyHarvester.cc
  DQMOffline/Muon/src/GEMOfflineDQMBase.cc
  DQMOffline/Muon/src/GEMOfflineMonitor.cc
  DQMOffline/Muon/src/SealModule.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30485 added esConsumes to modules in IMOC/EventVertexGenerators
  IOMC/EventVertexGenerators/interface/BetafuncEvtVtxGenerator.h
  IOMC/EventVertexGenerators/src/BeamDivergenceVtxGenerator.cc
  IOMC/EventVertexGenerators/src/BetafuncEvtVtxGenerator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30489 Validation/Geometry: Fix TTree Option
  Validation/Geometry/interface/MaterialBudgetTree.h
  Validation/Geometry/src/MaterialBudgetTree.cc
  Validation/Geometry/test/runP_Tracker.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#30492 Add workflow 158.181 as 158.0 with concurrent lumis enabled
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#30499 [DataFormats/PatCandidates] Rework statics in header file.
  DataFormats/PatCandidates/interface/PATObject.h
  DataFormats/PatCandidates/src/PATObject.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30524 add missing header guards to ColinsSoperVariables.h
  PhysicsTools/TagAndProbe/interface/ColinsSoperVariables.h
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30522 Added Geant4 "general process" option
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/PhysicsLists/interface/CMSEmNoDeltaRay.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysics95.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysics95msc93.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysicsLPM.h
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_ATL_EMM.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EML.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EMM.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsLPM.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsXS.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30509 Fix clang tidy mistakes
  DQM/CSCMonitorModule/plugins/CSCDQM_Collection.cc
  RecoPPS/Local/plugins/TotemRPUVPatternFinder.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30502 Remove boost binding in Fireworks
  Fireworks/Calo/src/FWFromTEveCaloDataSelector.cc
  Fireworks/FWInterface/src/FWFFLooper.cc
  Fireworks/FWInterface/src/FWFFService.cc
  Fireworks/ParticleFlow/plugins/FWPFCandidateDetailView.cc
  Fireworks/Tracks/plugins/FWTrackHitsDetailView.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, tests-approved, visualization-approved

#30501 Protected mutex locking with RAII.
  HeterogeneousCore/CUDAUtilities/src/CachingDeviceAllocator.h
  HeterogeneousCore/CUDAUtilities/src/CachingHostAllocator.h
Labels: code-checks-approved, comparison-available, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#30536 Use --customise instead of --customise_unsc in TestOldDigi workflow
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-pending, orp-approved, pdmv-pending, pending-signatures, tests-approved, upgrade-pending

#30511 Run4-hgx250 Backport the corrections to HGCal geometry most relevant for partial wafers from 3 PR's #30323 #30413 #30425
  Geometry/CaloTopology/interface/HGCalTopology.h
  Geometry/CaloTopology/src/HGCalTopology.cc
  Geometry/HGCalCommonData/data/hgcalCons/v10/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v11/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v11m/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v12/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcalCons/v9/hgcalCons.xml
  Geometry/HGCalCommonData/interface/HGCalDDDConstants.h
  Geometry/HGCalCommonData/interface/HGCalGeomParameters.h
  Geometry/HGCalCommonData/interface/HGCalGeomTools.h
  Geometry/HGCalCommonData/interface/HGCalParameters.h
  Geometry/HGCalCommonData/interface/HGCalParametersFromDD.h
  Geometry/HGCalCommonData/interface/HGCalTileIndex.h
  Geometry/HGCalCommonData/interface/HGCalTypes.h
  Geometry/HGCalCommonData/interface/HGCalWaferMask.h
  Geometry/HGCalCommonData/plugins/HGCalNumberingInitialization.cc
  Geometry/HGCalCommonData/python/testHGCalV11XML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalV12XML_cfi.py
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
  Geometry/HGCalCommonData/src/HGCalGeomTools.cc
  Geometry/HGCalCommonData/src/HGCalParametersFromDD.cc
  Geometry/HGCalCommonData/src/HGCalTileIndex.cc
  Geometry/HGCalCommonData/src/HGCalWaferMask.cc
  Geometry/HGCalCommonData/src/HGCalWaferType.cc
  Geometry/HGCalCommonData/test/HGCalNumberingTester.cc
  Geometry/HGCalCommonData/test/HGCalParameterTester.cc
  Geometry/HGCalGeometry/interface/HGCalGeometry.h
  Geometry/HGCalGeometry/plugins/HGCalGeometryESProducer.cc
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
Labels: comparison-pending, geometry-pending, orp-approved, pending-signatures, requires-external, tests-started, upgrade-pending

#30537 Use --customise instead of --customise_unsc in TestOldDigi workflow (backport)
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: comparison-pending, orp-approved, pdmv-pending, pending-signatures, requires-external, tests-started, upgrade-pending

#30532 Removed obsolete script from TB2006 analysis
  Geometry/HcalTestBeamData/python/hcalDDDSimConstants_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30483 Changes to ape tool for python 3 compatibility and reduced bloat
  Alignment/APEEstimation/test/SkimProducer/skimProducer_cfg.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitter.py
  Alignment/APEEstimation/test/autoSubmitter/config.ini
  Alignment/APEEstimation/test/autoSubmitter/helpers.py
  Alignment/APEEstimation/test/plottingTools/resultPlotter.py
  Alignment/APEEstimation/test/plottingTools/trendPlotter.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30543 Move edm::defaultModuleLabel() body out-of-line
  FWCore/ParameterSet/interface/defaultModuleLabel.h
  FWCore/ParameterSet/src/defaultModuleLabel.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30455 Fix TSGFromPropagation
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromPropagation.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromPropagation.h
Labels: bug-fix, code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#30342 Add L1 hitless seeding for tracking @ HLT upgrade
  RecoTracker/TkSeedGenerator/BuildFile.xml
  RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromL1TTracksEDProducer.cc
  TrackingTools/TrajectoryState/BuildFile.xml
  TrackingTools/TrajectoryState/interface/TrajectoryStateTransform.h
  TrackingTools/TrajectoryState/src/TrajectoryStateTransform.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30527 integrate 0T workflows for Cosmics and Collisions
  Configuration/AlCa/python/autoCond.py
  Configuration/AlCa/python/autoCondModifiers.py
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#30548 Rel val add qcd pt 1800 2400
  Configuration/Generator/python/QCD_Pt_1800_2400_13TeV_TuneCP5_cfi.py
  Configuration/Generator/python/QCD_Pt_1800_2400_14TeV_TuneCP5_cfi.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#30552 Clean up unused boost dependencies on RecoTracker/CkfPattern
  RecoTracker/CkfPattern/BuildFile.xml
  RecoTracker/CkfPattern/interface/CkfTrajectoryBuilder.h
  RecoTracker/CkfPattern/src/IntermediateTrajectoryCleaner.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30555 added esConsumes to modules in RecoBTag/SecondaryVertex
  RecoBTag/SecondaryVertex/plugins/BoostedDoubleSVProducer.cc
  RecoBTag/SecondaryVertex/plugins/TemplatedSecondaryVertexProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30556 drop type specs in RecoTracker/{DeDx,FinalTrackSelectors}
  RecoTracker/DeDx/python/dedxEstimatorsFromRefitter_cff.py
  RecoTracker/DeDx/python/dedxEstimators_Cosmics_cff.py
  RecoTracker/DeDx/python/dedxEstimators_cff.py
  RecoTracker/DeDx/python/hltDeDxEstimatorProducer_cfi.py
  RecoTracker/FinalTrackSelectors/python/MergeTrackCollections_cff.py
  RecoTracker/FinalTrackSelectors/python/classifierTest_cff.py
  RecoTracker/FinalTrackSelectors/python/earlyGeneralTracks_cfi.py
  RecoTracker/FinalTrackSelectors/python/multiTrackSelector_cfi.py
  RecoTracker/FinalTrackSelectors/python/preDuplicateMergingGeneralTracks_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30559 Reduce boost dependency in EventFilter/Utilities
  EventFilter/Utilities/interface/MicroStateServiceClassic.h
  EventFilter/Utilities/src/MicroStateServiceClassic.cc
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30448 BeamSpotOnline in DQM beamspot clients
  DQM/BeamMonitor/plugins/BeamMonitor.cc
  DQM/BeamMonitor/plugins/BeamMonitor.h
  DQM/BeamMonitor/plugins/BuildFile.xml
  DQM/BeamMonitor/python/BeamMonitor_Cosmics_cff.py
  DQM/BeamMonitor/python/BeamMonitor_MC_cff.py
  DQM/BeamMonitor/python/BeamMonitor_PixelLess_cff.py
  DQM/BeamMonitor/python/BeamMonitor_Pixel_cff.py
  DQM/BeamMonitor/python/BeamMonitor_cff.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/config/fileinputsource_cfi.py
  DQM/Integration/python/config/inputsource_cfi.py
  DQM/Integration/python/config/unittestinputsource_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29932 Apply missed clang-tidy checks
  CondFormats/HcalObjects/src/HBHEDarkening.cc
  Fireworks/Core/src/FWDialogBuilder.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, orp-approved, pending-signatures, tests-approved, visualization-pending

#30567 Remove obsolete files from FWCore/Framework/doc
  FWCore/Framework/doc/EventSelector-behavior.doc
  FWCore/Framework/doc/EventSelector.cc-with-cerr-traces
  FWCore/Framework/doc/Framework.doc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30016 Introduce DeepDoubleX V2
  DataFormats/BTauReco/interface/ChargedCandidateFeatures.h
  DataFormats/BTauReco/interface/DeepDoubleXFeatures.h
  DataFormats/BTauReco/interface/NeutralCandidateFeatures.h
  DataFormats/BTauReco/interface/SecondaryVertexFeatures.h
  DataFormats/BTauReco/src/classes_def.xml
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  RecoBTag/FeatureTools/interface/ChargedCandidateConverter.h
  RecoBTag/FeatureTools/interface/NeutralCandidateConverter.h
  RecoBTag/FeatureTools/plugins/DeepDoubleXTagInfoProducer.cc
  RecoBTag/FeatureTools/src/ChargedCandidateConverter.cc
  RecoBTag/FeatureTools/src/SecondaryVertexConverter.cc
  RecoBTag/ONNXRuntime/plugins/DeepDoubleXONNXJetTagsProducer.cc
  RecoBTag/ONNXRuntime/python/pfDeepDoubleX_cff.py
  RecoBTag/ONNXRuntime/python/pfMassIndependentDeepDoubleXJetTags_cff.py
  RecoBTag/ONNXRuntime/python/pfMassIndependentDeepDoubleXV2JetTags_cff.py
  RecoBTag/ONNXRuntime/test/README.md
  RecoBTag/ONNXRuntime/test/plotDDX.py
  RecoBTag/ONNXRuntime/test/test_deep_doublex_cfg.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-approved

#30466 PPS: direct simulation update A
  CalibPPS/ESProducers/plugins/CTPPSBeamParametersESSource.cc
  CondFormats/PPSObjects/interface/CTPPSBeamParameters.h
  CondFormats/PPSObjects/src/CTPPSBeamParameters.cc
  Configuration/Eras/python/Era_Run3_cff.py
  IOMC/EventVertexGenerators/src/BeamDivergenceVtxGenerator.cc
  Validation/CTPPS/alignment/2018_TS1_TS2.xml
  Validation/CTPPS/alignment/2018_postTS2.xml
  Validation/CTPPS/alignment/2018_preTS1.xml
  Validation/CTPPS/plugins/CTPPSBeamSmearingValidator.cc
  Validation/CTPPS/plugins/CTPPSDirectProtonSimulation.cc
  Validation/CTPPS/plugins/CTPPSHepMCDistributionPlotter.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionPlotter.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionSimulationValidator.cc
  Validation/CTPPS/python/simu_config/base_cff.py
  Validation/CTPPS/python/simu_config/year_2016_cff.py
  Validation/CTPPS/python/simu_config/year_2017_cff.py
  Validation/CTPPS/python/simu_config/year_2017_postTS2_cff.py
  Validation/CTPPS/python/simu_config/year_2017_preTS2_cff.py
  Validation/CTPPS/python/simu_config/year_2018_TS1_TS2_cff.py
  Validation/CTPPS/python/simu_config/year_2018_cff.py
  Validation/CTPPS/python/simu_config/year_2018_postTS2_cff.py
  Validation/CTPPS/python/simu_config/year_2018_preTS1_cff.py
  Validation/CTPPS/test/simu/run_multiple
  Validation/CTPPS/test/simu/template_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#30541 [HGC trigger] Replace exception with warning for missing wafer in module mapping
  L1Trigger/L1THGCal/plugins/BuildFile.xml
  L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryV9Imp2.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved, urgent

#30418 Add all direct deps to BuildFile for SimTracker/TrackTriggerAssociation
  SimTracker/TrackTriggerAssociation/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved

#30394 Add all direct deps to BuildFile for L1Trigger/L1TNtuples
  L1Trigger/L1TNtuples/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30103 CLCT comparator code calculation (CCLUT-5)
  L1Trigger/CSCTriggerPrimitives/README.md
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCComparatorCodeLUT.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCMotherboard.h
  L1Trigger/CSCTriggerPrimitives/python/cscTriggerPrimitiveDigis_cfi.py
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCComparatorCodeLUT.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeCathodeLCTProcessor.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, requires-external, tests-approved

#30104 Rewrite ALCT trigger patterns as 2D vector
  L1Trigger/CSCCommonTrigger/interface/CSCConstants.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCAnodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCPatternBank.h
  L1Trigger/CSCTriggerPrimitives/plugins/CSCAnodeLCTAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCPatternBank.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30169 GE2/1 pads with 16 eta partitions & option to send overflow GEM clusters
  L1Trigger/CSCTriggerPrimitives/src/GEMCoPadProcessor.cc
  L1Trigger/L1TGEM/plugins/GEMPadDigiClusterProducer.cc
  L1Trigger/L1TGEM/plugins/GEMPadDigiProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30283 added esConsumes to modules in EventFilter/GctRawToDigi
  EventFilter/GctRawToDigi/plugins/L1GctInternJetProducer.cc
  EventFilter/GctRawToDigi/plugins/L1GctInternJetProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30554 added esConsumes to modules in RecoVertex/BeamSpotProducer
  RecoVertex/BeamSpotProducer/interface/BeamSpotFromDB.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotOnlineProducer.h
  RecoVertex/BeamSpotProducer/interface/BeamSpotProducer.h
  RecoVertex/BeamSpotProducer/plugins/BeamSpotFromDB.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotOnlineProducer.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30469 added esConsumes to modules in L1Trigger/RPCTechnicalTrigger
  L1Trigger/RPCTechnicalTrigger/interface/RPCTechnicalTrigger.h
  L1Trigger/RPCTechnicalTrigger/src/RPCTechnicalTrigger.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30434 added esConsumes to modules in L1Trigger/L1TTwinMux
  L1Trigger/L1TTwinMux/plugins/L1TTwinMuxProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30433 added esConsumes to modules in L1Trigger/L1TCalorimeter
  L1Trigger/L1TCalorimeter/plugins/L1TCaloParamsWriter.cc
  L1Trigger/L1TCalorimeter/plugins/L1TCaloRCTToUpgradeConverter.cc
  L1Trigger/L1TCalorimeter/plugins/L1TCaloStage1LutWriter.cc
  L1Trigger/L1TCalorimeter/plugins/L1TCaloStage2ParamsESProducer.cc
  L1Trigger/L1TCalorimeter/plugins/L1TCaloUpgradeToGCTConverter.cc
  L1Trigger/L1TCalorimeter/plugins/L1TCaloUpgradeToGCTConverter.h
  L1Trigger/L1TCalorimeter/plugins/L1TPhysicalEtAdder.cc
  L1Trigger/L1TCalorimeter/plugins/L1TPhysicalEtAdder.h
  L1Trigger/L1TCalorimeter/plugins/L1TStage1Layer2Producer.cc
  L1Trigger/L1TCalorimeter/plugins/L1TStage2Layer1Producer.cc
  L1Trigger/L1TCalorimeter/plugins/L1TStage2Layer2Producer.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30431 added esConsumes to modules in L1Trigger/L1TMuon
  L1Trigger/L1TMuon/plugins/L1TMicroGMTLUTDumper.cc
  L1Trigger/L1TMuon/plugins/L1TMuonGlobalParamsESProducer.cc
  L1Trigger/L1TMuon/plugins/L1TMuonProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30427 added esConsumes to modules in L1Trigger/L1TGlobal
  L1Trigger/L1TGlobal/plugins/BXVectorInputProducer.cc
  L1Trigger/L1TGlobal/plugins/FakeInputProducer.cc
  L1Trigger/L1TGlobal/plugins/GtInputDump.cc
  L1Trigger/L1TGlobal/plugins/GtRecordDump.cc
  L1Trigger/L1TGlobal/plugins/L1TExtCondLegacyToStage2.cc
  L1Trigger/L1TGlobal/plugins/L1TExtCondProducer.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalPrescaler.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalPrescalesVetosESProducer.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.h
  L1Trigger/L1TGlobal/plugins/L1TGlobalSummary.cc
  L1Trigger/L1TGlobal/plugins/L1TUtmTriggerMenuDumper.cc
  L1Trigger/L1TGlobal/plugins/L1TUtmTriggerMenuESProducer.cc
  L1Trigger/L1TGlobal/plugins/StableParametersTrivialProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30421 added esConsumes to modules in L1Trigger/RegionalCaloTrigger
  L1Trigger/RegionalCaloTrigger/interface/L1RCTInputProducer.h
  L1Trigger/RegionalCaloTrigger/plugins/L1RCTInputProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30360 added esConsumes to modules in L1Trigger/GlobalMuonTrigger
  L1Trigger/GlobalMuonTrigger/interface/L1MuGlobalMuonTrigger.h
  L1Trigger/GlobalMuonTrigger/src/L1MuGlobalMuonTrigger.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30336 added esConsumes to modules in L1Trigger /L1ExtraFromDigis
  L1Trigger/L1ExtraFromDigis/interface/L1ExtraParticlesProd.h
  L1Trigger/L1ExtraFromDigis/src/L1ExtraParticlesProd.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30345 added esConsumes to modules in EventFilter/1GlobalTriggerRawToDigi
  EventFilter/L1GlobalTriggerRawToDigi/interface/L1GTDigiToRaw.h
  EventFilter/L1GlobalTriggerRawToDigi/interface/L1GTEvmDigiToRaw.h
  EventFilter/L1GlobalTriggerRawToDigi/interface/L1GlobalTriggerEvmRawToDigi.h
  EventFilter/L1GlobalTriggerRawToDigi/interface/L1GlobalTriggerRawToDigi.h
  EventFilter/L1GlobalTriggerRawToDigi/interface/L1GlobalTriggerRecordProducer.h
  EventFilter/L1GlobalTriggerRawToDigi/interface/L1GtTriggerMenuLiteProducer.h
  EventFilter/L1GlobalTriggerRawToDigi/src/L1GTDigiToRaw.cc
  EventFilter/L1GlobalTriggerRawToDigi/src/L1GTEvmDigiToRaw.cc
  EventFilter/L1GlobalTriggerRawToDigi/src/L1GlobaTriggerEvmRawToDigi.cc
  EventFilter/L1GlobalTriggerRawToDigi/src/L1GlobaTriggerRawToDigi.cc
  EventFilter/L1GlobalTriggerRawToDigi/src/L1GlobaTriggerRecordProducer.cc
  EventFilter/L1GlobalTriggerRawToDigi/src/L1GtTriggerMenuLiteProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30348 added esConsumes to modules in L1Trigger/GlobalCaloTrigger
  L1Trigger/GlobalCaloTrigger/plugins/L1GctEmulator.cc
  L1Trigger/GlobalCaloTrigger/plugins/L1GctEmulator.h
  L1Trigger/GlobalCaloTrigger/plugins/L1GctPrintLuts.cc
  L1Trigger/GlobalCaloTrigger/plugins/L1GctPrintLuts.h
  L1Trigger/GlobalCaloTrigger/plugins/L1GctValidation.cc
  L1Trigger/GlobalCaloTrigger/plugins/L1GctValidation.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30358 added esConsumes to modules in L1Trigger/GlobalTrigger
  L1Trigger/GlobalTrigger/plugins/L1GlobalTrigger.cc
  L1Trigger/GlobalTrigger/plugins/L1GlobalTrigger.h
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30565 Reduce boost dependency in FWCore/MessageService
  FWCore/MessageService/BuildFile.xml
  FWCore/MessageService/interface/MessageServicePresence.h
  FWCore/MessageService/src/MessageServicePresence.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30449 Reduce boost dependency in OnlineDB/EcalCondDB
  OnlineDB/EcalCondDB/interface/LMFUnique.h
  OnlineDB/EcalCondDB/src/LMFColor.cc
  OnlineDB/EcalCondDB/src/LMFDefFabric.cc
  OnlineDB/EcalCondDB/src/LMFUnique.cc
  OnlineDB/EcalCondDB/test/TestLMF2010-write.cpp
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30393 Add all direct deps to BuildFile for L1Trigger/L1TGlobal
  L1Trigger/L1TGlobal/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30380 Add all direct deps to BuildFile for CondFormats/L1TObjects
  CondFormats/L1TObjects/BuildFile.xml
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#30356 fix typo in provenance access by L1TTauOffline
  DQMOffline/L1Trigger/src/L1TTauOffline.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#30472 added esConsumes to modules in L1Trigger/RPCTrigger
  L1Trigger/RPCTrigger/interface/RPCTrigger.h
  L1Trigger/RPCTrigger/plugins/RPCConeBuilder.cc
  L1Trigger/RPCTrigger/plugins/RPCTrigger.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#30447 [HGC trigger] Clean deprecated files
  DataFormats/L1THGCal/interface/HGCalClusterT.h
  DataFormats/L1THGCal/src/classes_def.xml
  L1Trigger/L1THGCal/interface/HGCalTriggerBackendAlgorithmBase.h
  L1Trigger/L1THGCal/interface/HGCalTriggerBackendProcessor.h
  L1Trigger/L1THGCal/interface/HGCalTriggerFECodecBase.h
  L1Trigger/L1THGCal/interface/HGCalTriggerGeometryGenericMapping.h
  L1Trigger/L1THGCal/plugins/HGCalTriggerDigiFEReproducer.cc
  L1Trigger/L1THGCal/plugins/backend/HGCalTowerMapProcessor.cc
  L1Trigger/L1THGCal/plugins/backend/HGCalTowerProcessor.cc
  L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryHexImp1.cc
  L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryHexImp2.cc
  L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryImp1.cc
  L1Trigger/L1THGCal/plugins/geometries/NullGeometry.cc
  L1Trigger/L1THGCal/plugins/geometries/README.md
  L1Trigger/L1THGCal/plugins/geometries/TrivialGeometry.cc
  L1Trigger/L1THGCal/src/HGCalTriggerBackendAlgorithmBase.cc
  L1Trigger/L1THGCal/src/HGCalTriggerBackendProcessor.cc
  L1Trigger/L1THGCal/src/HGCalTriggerFECodecBase.cc
  L1Trigger/L1THGCal/src/HGCalTriggerGeometryGenericMapping.cc
  L1Trigger/L1THGCal/test/BuildFile.xml
  L1Trigger/L1THGCal/test/HGCalTriggerBestChoiceTester.cc
  L1Trigger/L1THGCal/test/HGCalTriggerBestChoiceTriggerCellTester.cc
  L1Trigger/L1THGCal/test/HGCalTriggerThresholdTriggerCellTester.cc
  L1Trigger/L1THGCal/test/L1Clustering_cfg.py
  L1Trigger/L1THGCal/test/L1TC_CalibWeightExt_cfg.py
  L1Trigger/L1THGCal/test/calib/testCalibration.cc
  L1Trigger/L1THGCal/test/macros/DrawingUtilities.py
  L1Trigger/L1THGCal/test/macros/drawTriggerCells.py
  L1Trigger/L1THGCal/test/macros/drawTriggerModules.py
  L1Trigger/L1THGCal/test/macros/drawTriggerModulesHex.py
  L1Trigger/L1THGCal/test/macros/waferGeometry.py
  L1Trigger/L1THGCal/test/testTriggerSimCluster.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#30494 Backport to 111X of ESGetToken update in L1T O2O producer
  CondTools/L1TriggerExt/interface/L1ConfigOnlineProdBaseExt.h
  CondTools/L1TriggerExt/interface/L1ObjectKeysOnlineProdBaseExt.h
  CondTools/L1TriggerExt/plugins/L1CondDBPayloadWriterExt.cc
  CondTools/L1TriggerExt/plugins/L1CondDBPayloadWriterExt.h
  CondTools/L1TriggerExt/plugins/L1TriggerKeyOnlineProdExt.cc
  CondTools/L1TriggerExt/plugins/L1TriggerKeyOnlineProdExt.h
  CondTools/L1TriggerExt/src/L1ObjectKeysOnlineProdBaseExt.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TCaloParamsOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TGlobalPrescalesVetosOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonBarrelParamsOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonEndCapForestOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonEndCapForestOnlineProxy.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonEndCapParamsOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonGlobalParamsOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonOverlapParamsOnlineProd.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonOverlapParamsOnlineProxy.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TUtmTriggerMenuOnlineProd.cc
Labels: comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#30500 Run3-hcx261 Update the material budget study code for HCAL
  Validation/Geometry/interface/MaterialBudgetHcalHistos.h
  Validation/Geometry/src/MaterialBudgetHcalHistos.cc
  Validation/Geometry/test/MatBudgetHcal.C
  Validation/Geometry/test/runP_HCAL_Debug_cfg.py
  Validation/Geometry/test/runP_HCAL_cfg.py
  Validation/Geometry/test/single_neutrino_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#30526 Run3-gem42 Remove reference to GE21 from Run3 scenario
  Geometry/MuonCommonData/data/muonNumbering/2021/v2/muonNumbering.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30534 Run4-hgx251 Small update to the code
  Geometry/HGCalCommonData/plugins/DDHGCalEEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalEEAlgo.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalHEAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30547 Remove old duplicate vfatstatusdigi
  DataFormats/GEMDigi/interface/GEMVfatStatusDigi.h
  DataFormats/GEMDigi/interface/GEMVfatStatusDigiCollection.h
  DataFormats/GEMDigi/src/GEMVfatStatusDigi.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#30530 Modify MkFitInputWrapper and to take moved-in parameters by value
  RecoTracker/MkFit/interface/MkFitInputWrapper.h
  RecoTracker/MkFit/plugins/MkFitInputConverter.cc
  RecoTracker/MkFit/src/MkFitInputWrapper.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30551 Cleanup: Remove Geometry/MTCCTrackerCommonData
  Geometry/MTCCTrackerCommonData/data/tec_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tecsupport_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tecwheeld_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tib_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tibemptymodule2_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tibemptystring2_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tibemptystring2lr_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tibemptystring2ur_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tibemptystringss_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tiblayer1_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tiblayer2_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tibstring1_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tibstring2_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tob_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod0_a_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod0_b_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod0_c_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod0_d_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod0_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod1_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod2_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod3_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod4_a_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod4_b_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod4_c_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod4_d_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod4_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobrod5_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tobsupport_mtcc.xml
  Geometry/MTCCTrackerCommonData/data/tracker.xml
  Geometry/MTCCTrackerCommonData/data/trackerStructureTopology_mtcc.xml
  Geometry/MTCCTrackerCommonData/doc/MTCCTrackerCommonData.doc
  Geometry/MTCCTrackerCommonData/plugins/BuildFile.xml
  Geometry/MTCCTrackerCommonData/plugins/DDTIBLayerAlgo_MTCC.cc
  Geometry/MTCCTrackerCommonData/plugins/DDTIBLayerAlgo_MTCC.h
  Geometry/MTCCTrackerCommonData/plugins/DDTIBRadCableAlgo_MTCC.cc
  Geometry/MTCCTrackerCommonData/plugins/DDTIBRadCableAlgo_MTCC.h
  Geometry/MTCCTrackerCommonData/plugins/module.cc
  Geometry/MTCCTrackerCommonData/python/testConfiguration_cfi.py
  Geometry/MTCCTrackerCommonData/test/runP_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30568 Fix L1T bugs and add workflows
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  L1Trigger/Configuration/python/customisePhase2TTNoMC.py
  L1Trigger/L1CaloTrigger/plugins/BuildFile.xml
  L1Trigger/L1CaloTrigger/python/L1EGammaCrystalsEmulatorProducer_cfi.py
  L1Trigger/Phase2L1ParticleFlow/src/RegionMapper.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-approved

#30507 Port COCOA to rely on DD4hep
  Alignment/CocoaApplication/BuildFile.xml
  Alignment/CocoaApplication/README.md
  Alignment/CocoaApplication/interface/CocoaAnalyzer.h
  Alignment/CocoaApplication/src/CocoaAnalyzer.cc
  Alignment/CocoaApplication/src/SealModule.cc
  Alignment/CocoaApplication/test/OpticalAlignments.db
  Alignment/CocoaApplication/test/cmsCocoaTable2DWithMirror.xml
  Alignment/CocoaApplication/test/cocoaAnalyzer_cfg.py
  Alignment/CocoaApplication/test/table2DWithMirror.xml
  Alignment/CocoaFit/src/CocoaDBMgr.cc
  Alignment/CocoaUtilities/interface/ALIUtils.h
  Alignment/CocoaUtilities/src/ALIUtils.cc
  Alignment/CocoaUtilities/src/GlobalOptionMgr.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30569 Fix L1T bugs and add workflows [11_1_X]
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  L1Trigger/Configuration/python/customisePhase2TTNoMC.py
  L1Trigger/L1CaloTrigger/plugins/BuildFile.xml
  L1Trigger/L1CaloTrigger/python/L1EGammaCrystalsEmulatorProducer_cfi.py
  L1Trigger/Phase2L1ParticleFlow/src/RegionMapper.cc
Labels: backport-ok, comparison-available, l1-pending, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-approved

#30574 Add L1 hitless seeding for tracking @ HLT (11_1_X)
  RecoTracker/TkSeedGenerator/BuildFile.xml
  RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromL1TTracksEDProducer.cc
  TrackingTools/TrajectoryState/BuildFile.xml
  TrackingTools/TrajectoryState/interface/TrajectoryStateTransform.h
  TrackingTools/TrajectoryState/src/TrajectoryStateTransform.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30503 BeamSpotOnline in DQM beamspot clients - backport to 11_1_X
  DQM/BeamMonitor/plugins/BeamMonitor.cc
  DQM/BeamMonitor/plugins/BeamMonitor.h
  DQM/BeamMonitor/plugins/BuildFile.xml
  DQM/BeamMonitor/python/BeamMonitor_Cosmics_cff.py
  DQM/BeamMonitor/python/BeamMonitor_MC_cff.py
  DQM/BeamMonitor/python/BeamMonitor_PixelLess_cff.py
  DQM/BeamMonitor/python/BeamMonitor_Pixel_cff.py
  DQM/BeamMonitor/python/BeamMonitor_cff.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/config/fileinputsource_cfi.py
  DQM/Integration/python/config/inputsource_cfi.py
  DQM/Integration/python/config/unittestinputsource_cfi.py
Labels: comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30601 added esConsumes to modules in RecoLocalMuon/ CSCSegment
  RecoLocalMuon/CSCSegment/src/CSCSegmentProducer.cc
  RecoLocalMuon/CSCSegment/src/CSCSegmentProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30576 Drop 'drop*' as not necessary for MicroEventContent (MiniAOD)
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#30579 Phase2-gex04 Fix some 2026 geometries by removing interfering duplicate file
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D49.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D50.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D51.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D53.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D54.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D55.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D56.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D49XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D50XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D51XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D53XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D54XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D55XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D56XML_cfi.py
Labels: code-checks-approved, comparison-available, geometry-approved, orp-approved, pending-signatures, tests-approved, upgrade-pending

#30610 More L1T bug fixes [11.1.x]
  DataFormats/L1Trigger/src/classes_def.xml
  L1Trigger/Configuration/python/L1Trigger_EventContent_cff.py
  L1Trigger/L1CaloTrigger/plugins/L1EGammaEEProducer.cc
Labels: backport, bug-fix, comparison-pending, l1-pending, orp-approved, pending-signatures, tests-started, upgrade-pending, urgent

#30606 More L1T bug fixes
  DataFormats/L1Trigger/src/classes_def.xml
  L1Trigger/Configuration/python/L1Trigger_EventContent_cff.py
  L1Trigger/L1CaloTrigger/plugins/L1EGammaEEProducer.cc
Labels: bug-fix, code-checks-approved, comparison-pending, l1-pending, orp-approved, pending-signatures, tests-started, upgrade-pending

#30585 Drop unnecessary 'drop *'
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
Labels: analysis-pending, backport, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#30603 Phase2-gex05 Bug fix to Phase2 geometries D49 and higher versions
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D49.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D50.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D51.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D52.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D49XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D50XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D51XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D53XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D54XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D55XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D56XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D57XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D58XML_cfi.py
Labels: comparison-pending, geometry-pending, orp-approved, pending-signatures, tests-started, upgrade-pending

#30573 fix typo in provenance access by L1TTauOffline (backport to 11_1_X)
  DQMOffline/L1Trigger/src/L1TTauOffline.cc
Labels: comparison-available, dqm-approved, l1-pending, orp-approved, pending-signatures, tests-approved

#30596 [Backport HGC trigger] Replace exception with warning for missing wafer in module mapping
  L1Trigger/L1THGCal/plugins/BuildFile.xml
  L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryV9Imp2.cc
Labels: backport-ok, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#30460 Enable L1Tracks to run and be included in L1T DQM
  Configuration/EventContent/python/EventContent_cff.py
  DQM/SiOuterTracker/plugins/OuterTrackerMonitorTTStub.cc
  DQM/SiOuterTracker/plugins/OuterTrackerMonitorTTTrack.cc
  DQM/SiOuterTracker/python/OuterTrackerMonitorTTCluster_cfi.py
  DQM/SiOuterTracker/python/OuterTrackerMonitorTTStub_cfi.py
  DQM/SiOuterTracker/python/OuterTrackerMonitorTTTrack_cfi.py
  Validation/SiOuterTrackerV/plugins/OuterTrackerMCHarvester.cc
  Validation/SiOuterTrackerV/plugins/OuterTrackerMonitorTrackingParticles.cc
  Validation/SiOuterTrackerV/plugins/OuterTrackerMonitorTrackingParticles.h
  Validation/SiOuterTrackerV/python/OuterTrackerMonitorTrackingParticles_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#30607 Fix out-of-bound issue in call to LUT in GEM-CSC trigger [11_1_X]
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMotherboard.h
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/GEMCoPadProcessor.cc
Labels: comparison-pending, fully-signed, l1-approved, orp-approved, tests-approved, urgent

#30564 Fix out-of-bound issue in call to LUT in GEM-CSC trigger
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMotherboard.h
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
Labels: code-checks-approved, comparison-pending, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30615 PR 11_2_X L1T TrackTrigger Hybrid Extended ONE Producer.
  L1Trigger/TrackFindingTracklet/plugins/L1FPGATrackProducer.cc
Labels: code-checks-approved, comparison-pending, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30616 PR 11_1_X (backport) L1T TrackTrigger Hybrid Extended ONE Producer.
  L1Trigger/TrackFindingTracklet/plugins/L1FPGATrackProducer.cc
Labels: comparison-pending, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30621 added esConsumes to modules in RecoPPS/ProtonReconstruction
  RecoPPS/ProtonReconstruction/plugins/CTPPSProtonProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30562 added esConsumes to modules in RecoMET/METProducers
  RecoMET/METProducers/interface/CSCHaloDataProducer.h
  RecoMET/METProducers/interface/EcalHaloDataProducer.h
  RecoMET/METProducers/interface/GlobalHaloDataProducer.h
  RecoMET/METProducers/interface/HcalHaloDataProducer.h
  RecoMET/METProducers/interface/HcalNoiseInfoProducer.h
  RecoMET/METProducers/interface/MuonMETValueMapProducer.h
  RecoMET/METProducers/interface/MuonTCMETValueMapProducer.h
  RecoMET/METProducers/src/CSCHaloDataProducer.cc
  RecoMET/METProducers/src/EcalHaloDataProducer.cc
  RecoMET/METProducers/src/GlobalHaloDataProducer.cc
  RecoMET/METProducers/src/HcalHaloDataProducer.cc
  RecoMET/METProducers/src/HcalNoiseInfoProducer.cc
  RecoMET/METProducers/src/MuonMETValueMapProducer.cc
  RecoMET/METProducers/src/MuonTCMETValueMapProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30605 added esConsumes to modules in RecoPPS/Local
  RecoPPS/Local/interface/CTPPSPixelClusterProducer.h
  RecoPPS/Local/plugins/CTPPSDiamondRecHitProducer.cc
  RecoPPS/Local/plugins/CTPPSPixelClusterProducer.cc
  RecoPPS/Local/plugins/CTPPSPixelLocalTrackProducer.cc
  RecoPPS/Local/plugins/TotemRPLocalTrackFitter.cc
  RecoPPS/Local/plugins/TotemRPUVPatternFinder.cc
  RecoPPS/Local/plugins/TotemTimingRecHitProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30602 Replace boost filesystem in EventFilter/Utilities
  DQMServices/FileIO/plugins/DQMFileSaverBase.cc
  EventFilter/Utilities/BuildFile.xml
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/interface/FastMonitoringService.h
  EventFilter/Utilities/interface/FedRawDataInputSource.h
  EventFilter/Utilities/plugins/BuildFile.xml
  EventFilter/Utilities/plugins/RawEventFileWriterForBU.cc
  EventFilter/Utilities/plugins/RecoEventOutputModuleForFU.h
  EventFilter/Utilities/src/EvFDaqDirector.cc
  EventFilter/Utilities/src/EvFOutputModule.cc
  EventFilter/Utilities/src/FastMonitoringService.cc
  EventFilter/Utilities/src/FedRawDataInputSource.cc
Labels: code-checks-approved, comparison-available, daq-approved, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30595 Reduce boost dependency in DQM/PixelLumi
  DQM/PixelLumi/plugins/BrilClient.cc
  DQM/PixelLumi/plugins/BuildFile.xml
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30589 Minimal cleanup of PFClusterValidation code
  Validation/RecoParticleFlow/plugins/PFClusterValidation.cc
  Validation/RecoParticleFlow/plugins/PFClusterValidation.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30518 Add some function calls for fmt external as unittest
  FWCore/MessageService/test/BuildFile.xml
  FWCore/MessageService/test/fmt_test.cppunit.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30313 Add Pixel Tracks in Heavy Ions MiniAOD
  PhysicsTools/PatAlgos/plugins/PATTracksToPackedCandidates.cc
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/hiPixelTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30619 added esConsumes to modules in EventFilter/CTPPSRawToDigi
  EventFilter/CTPPSRawToDigi/interface/CTPPSPixelRawToDigi.h
  EventFilter/CTPPSRawToDigi/plugins/CTPPSPixelDigiToRaw.cc
  EventFilter/CTPPSRawToDigi/plugins/CTPPSPixelRawToDigi.cc
  EventFilter/CTPPSRawToDigi/plugins/CTPPSTotemDigiToRaw.cc
  EventFilter/CTPPSRawToDigi/plugins/TotemTriggerRawToDigi.cc
  EventFilter/CTPPSRawToDigi/plugins/TotemVFATRawToDigi.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30626 Add support of std::format()-like formatting to MessageLogger
  FWCore/MessageLogger/BuildFile.xml
  FWCore/MessageLogger/interface/ErrorObj.h
  FWCore/MessageLogger/interface/ErrorObj.icc
  FWCore/MessageLogger/interface/MessageLogger.h
  FWCore/MessageLogger/interface/MessageSender.h
  FWCore/MessageService/test/UnitTestClient_C.cc
  FWCore/MessageService/test/unit_test_outputs/u10_warnings.log
  FWCore/MessageService/test/unit_test_outputs/u6_warnings.log
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30633 fakeEmtfParams name update
  L1TriggerConfig/L1TConfigProducers/python/L1TMuonEndCapForestOnline_cfi.py
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30634 fakeEmtfParams name update - Backport to CMSSW_11_1_X
  L1TriggerConfig/L1TConfigProducers/python/L1TMuonEndCapForestOnline_cfi.py
Labels: comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30631 Update of the Tracker Online DQM client for Run3 conditions (backport of #30630)
  DQM/Integration/python/clients/pixel_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
Labels: comparison-available, dqm-pending, orp-approved, pending-signatures, tests-approved, urgent

#30630 Update of the Tracker Online DQM client for Run3 conditions
  DQM/Integration/python/clients/pixel_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-pending, orp-approved, pending-signatures, tests-approved, urgent

#30561 Remove boost mutex in GeneratorInterface
  GeneratorInterface/Herwig7Interface/src/Proxy.cc
  GeneratorInterface/LHEInterface/src/LHEProxy.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#30577 Run4-hgx252 Test several test scenarios in DDD/DD4Hep and rename files more rationally
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalEE-algorithm.xml
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalHEmix-algorithm.xml
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalHEsil-algorithm.xml
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalNoTaperEndcap-algorithm.xml
  Geometry/HGCalCommonData/data/dd4hep/testHGCalV10.xml
  Geometry/HGCalCommonData/data/dd4hep/testHGCalV11.xml
  Geometry/HGCalCommonData/data/dd4hep/testHGCalV12.xml
  Geometry/HGCalCommonData/data/dd4hep/testHGCalV13.xml
  Geometry/HGCalCommonData/data/v6/noTaper.xml
  Geometry/HGCalCommonData/data/v6/noTaperElement.xml
  Geometry/HGCalCommonData/data/v6/noTaperEndcap.xml
  Geometry/HGCalCommonData/plugins/DDHGCalNoTaperEndcap.cc
  Geometry/HGCalCommonData/python/testHGCalEEXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalHEmixXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalHEsilXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalNoTaperEndcapXML_cfi.py
  Geometry/HGCalCommonData/test/python/dumpAHcalModuleDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpAHcalModuleDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpExtendedHGCalGeometryDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpExtendedHGCalGeometryDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalCellDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalCellDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalEEDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalEEDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalGeometryDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalGeometryDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalHEmixDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalHEmixDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalHEsilDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalHEsilDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalModuleAlgoDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalModuleAlgoDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalModuleDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalModuleDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalNoTaperEndcapDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalNoTaperEndcapDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalTBGeometryDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalTBModuleDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalTBModuleDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalTBModuleXDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalTBModuleXDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWafer8DD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWafer8DDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWaferAlgoDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWaferAlgoDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWaferDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWaferDDD_cfg.py
  Geometry/HGCalCommonData/test/python/dumpTBGeometryDDD_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30580 Reduce boost dependency in CondCore/CondDB
  CondCore/CondDB/BuildFile.xml
  CondCore/CondDB/plugins/RelationalAuthenticationService.cc
  CondCore/CondDB/plugins/XMLAuthenticationService.cc
  CondCore/CondDB/src/ConnectionPool.cc
  CondCore/CondDB/src/CredentialStore.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30628 add missing dependency in CondFormats/RPCObjects
  CondFormats/RPCObjects/BuildFile.xml
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30625 added esConsumes to modules in RecoBTag/ImpactParameter
  RecoBTag/ImpactParameter/plugins/IPProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30623 Phase2-hgx253 Fix error reported from static analyzer
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30611 DependencyGraph: change default file name
  FWCore/Services/plugins/DependencyGraph.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30642 added esConsumes to modules in RecoHI/HiCentralityAlgos
  RecoHI/HiCentralityAlgos/plugins/CentralityBinProducer.cc
  RecoHI/HiCentralityAlgos/plugins/CentralityProducer.cc
  RecoHI/HiCentralityAlgos/plugins/CentralityTableProducer.cc
  RecoHI/HiCentralityAlgos/plugins/ClusterCompatibilityProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30641 added esConsumes to modules in RecoLocalCalo/Castor
  RecoLocalCalo/Castor/src/CastorTowerProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30640 added esConsumes to modules in RecoLocalCalo/CastorCalo
  RecoLocalCalo/CastorReco/plugins/CastorSimpleReconstructor.cc
  RecoLocalCalo/CastorReco/plugins/CastorSimpleReconstructor.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30639 added esConsumes to modules in RecoVertex/AdaptiveVertexFilter
  RecoVertex/AdaptiveVertexFinder/plugins/InclusiveVertexFinder.h
  RecoVertex/AdaptiveVertexFinder/plugins/TemplatedVertexArbitrator.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30563 Pixel template making code update
  CondTools/SiPixel/data/phaseI_mapping.csv
  CondTools/SiPixel/test/BuildFile.xml
  CondTools/SiPixel/test/SiPixel2DTemplateDBObjectUploader.cc
  CondTools/SiPixel/test/SiPixel2DTemplateDBObjectUploader.h
  CondTools/SiPixel/test/SiPixel2DTemplateDBObjectUploader_cfg.py
  CondTools/SiPixel/test/SiPixelGenErrorDBObjectReader.cc
  CondTools/SiPixel/test/SiPixelGenErrorDBObjectUploader.cc
  CondTools/SiPixel/test/SiPixelGenErrorDBObjectUploader.h
  CondTools/SiPixel/test/SiPixelGenErrorDBObjectUploader_cfg.py
  CondTools/SiPixel/test/SiPixelTemplateDBObjectReader_cfg.py
  CondTools/SiPixel/test/SiPixelTemplateDBObjectUploader.cc
  CondTools/SiPixel/test/SiPixelTemplateDBObjectUploader.h
  CondTools/SiPixel/test/SiPixelTemplateDBObjectUploader_cfg.py
  CondTools/SiPixel/test/run_0T_BoR3.sh
  CondTools/SiPixel/test/testPixelDBs.cpp
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, requires-external, tests-approved

#30598 added esConsumes to modules in RecoLocalMuon/CSCRecHitD
  CalibMuon/CSCCalibration/interface/CSCConditions.h
  CalibMuon/CSCCalibration/src/CSCConditions.cc
  RecoLocalMuon/CSCRecHitD/src/CSCRecHitDProducer.cc
  RecoLocalMuon/CSCRecHitD/src/CSCRecHitDProducer.h
  RecoLocalMuon/CSCRecHitD/src/CSCRecoBadChannelsAnalyzer.cc
  RecoLocalMuon/CSCRecHitD/src/CSCRecoConditions.cc
  RecoLocalMuon/CSCRecHitD/src/CSCRecoConditions.h
  SimMuon/CSCDigitizer/src/CSCDbStripConditions.cc
  SimMuon/CSCDigitizer/src/CSCDbStripConditions.h
  SimMuon/CSCDigitizer/src/CSCDigiProducer.cc
  SimMuon/CSCDigitizer/test/CSCNoiseMatrixTest.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#30600 APE tool change of configuration, additional python3 compatibility changes
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitter.py
  Alignment/APEEstimation/test/autoSubmitter/config.ini
  Alignment/APEEstimation/test/plottingTools/iterationsPlotter.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30636 Add PFCluster validation to ECAL-only and HCAL-only workflows
  Validation/CaloTowers/test/CaloScan/template_2018_since_1010pre2.py
  Validation/Configuration/python/globalValidation_cff.py
  Validation/RecoParticleFlow/python/PFClusterValidation_cff.py
  Validation/RecoParticleFlow/python/PFCluster_cfi.py
  Validation/RecoParticleFlow/python/pfClusterValidation_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#30622 added esConsumes to modules in RecoLocalCalo/CaloTowersCreator
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersCreator.cc
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersCreator.h
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersReCreator.cc
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersReCreator.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30660 TrackletEventProcessor: properly initialise and check settings
  L1Trigger/TrackFindingTracklet/interface/TrackletEventProcessor.h
  L1Trigger/TrackFindingTracklet/plugins/L1FPGATrackProducer.cc
  L1Trigger/TrackFindingTracklet/src/TrackletEventProcessor.cc
  L1Trigger/TrackFindingTracklet/test/fpga.cc
Labels: backport, bug-fix, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30659 TrackletEventProcessor: properly initialise and check settings
  L1Trigger/TrackFindingTracklet/interface/TrackletEventProcessor.h
  L1Trigger/TrackFindingTracklet/plugins/L1FPGATrackProducer.cc
  L1Trigger/TrackFindingTracklet/src/TrackletEventProcessor.cc
  L1Trigger/TrackFindingTracklet/test/fpga.cc
Labels: bug-fix, code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30657 Convert the CSCTriggerPrimitivesProducer to a "one" module
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.cc
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.h
Labels: backport, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30656 Convert the CSCTriggerPrimitivesProducer to a "one" module
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.cc
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.h
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30535 Clean BuildFiles in reco plugins
  DQM/BeamMonitor/plugins/BeamSpotProblemMonitor.cc
  RecoBTag/CTagging/plugins/BuildFile.xml
  RecoBTag/Combined/plugins/BuildFile.xml
  RecoBTag/FeatureTools/plugins/BuildFile.xml
  RecoBTag/PerformanceDB/plugins/BuildFile.xml
  RecoBTag/PixelCluster/plugins/BuildFile.xml
  RecoBTag/SecondaryVertex/plugins/BuildFile.xml
  RecoBTag/SoftLepton/plugins/BuildFile.xml
  RecoBTau/JetTagComputer/plugins/BuildFile.xml
  RecoEcal/EgammaClusterProducers/test/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/test/BuildFile.xml
  RecoEgamma/EgammaTools/test/BuildFile.xml
  RecoEgamma/PhotonIdentification/BuildFile.xml
  RecoHI/HiEgammaAlgos/plugins/BuildFile.xml
  RecoHI/HiEgammaAlgos/test/BuildFile.xml
  RecoHI/HiTracking/test/BuildFile.xml
  RecoHI/HiTracking/test/HIPixelClusterVtxAnalyzer.cc
  RecoJets/FFTJetProducers/plugins/BuildFile.xml
  RecoJets/JetAssociationProducers/test/BuildFile.xml
  RecoJets/JetPlusTracks/plugins/BuildFile.xml
  RecoJets/JetProducers/plugins/BuildFile.xml
  RecoLocalCalo/CastorReco/plugins/BuildFile.xml
  RecoLocalCalo/EcalRecAlgos/test/BuildFile.xml
  RecoLocalTracker/SiPixelRecHits/BuildFile.xml
  RecoLocalTracker/SubCollectionProducers/test/BuildFile.xml
  RecoLuminosity/LumiProducer/plugins/BuildFile.xml
  RecoLuminosity/LumiProducer/test/BuildFile.xml
  RecoMET/METFilters/plugins/BuildFile.xml
  RecoMET/METPUSubtraction/plugins/BuildFile.xml
  RecoMTD/DetLayers/test/BuildFile.xml
  RecoMTD/TimingIDTools/plugins/BuildFile.xml
  RecoMTD/TrackExtender/plugins/BuildFile.xml
  RecoMuon/DetLayers/test/BuildFile.xml
  RecoMuon/GlobalTrackingTools/plugins/BuildFile.xml
  RecoMuon/L3TrackFinder/plugins/BuildFile.xml
  RecoMuon/MuonIdentification/plugins/BuildFile.xml
  RecoMuon/MuonIsolation/plugins/BuildFile.xml
  RecoMuon/TrackerSeedGenerator/plugins/BuildFile.xml
  RecoMuon/TransientTrackingRecHit/plugins/BuildFile.xml
  RecoParticleFlow/Configuration/plugins/BuildFile.xml
  RecoParticleFlow/PFClusterProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFSimProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFTracking/plugins/BuildFile.xml
  RecoPixelVertexing/PixelTriplets/test/BuildFile.xml
  RecoRomanPot/RecoFP420/plugins/BuildFile.xml
  RecoTBCalo/EcalTBAnalysisCoreTools/test/BuildFile.xml
  RecoTauTag/RecoTau/plugins/BuildFile.xml
  RecoTauTag/RecoTau/test/BuildFile.xml
  RecoTracker/MkFit/plugins/BuildFile.xml
  RecoVertex/BeamSpotProducer/interface/BeamSpotOnlineProducer.h
  RecoVertex/BeamSpotProducer/plugins/BeamSpotOnlineProducer.cc
  RecoVertex/ConfigurableVertexReco/test/BuildFile.xml
Labels: alca-approved, analysis-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved
