Repository cms-sw/cmssw, pull requests merged in 2020-04, with the labels that each got.

#29354 Update BasicGenValidation_cff.py
  Validation/EventGenerator/python/BasicGenValidation_cff.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, generators-approved, orp-approved, tests-approved

#29350 Update BasicGenValidation_cff.py
  Validation/EventGenerator/python/BasicGenValidation_cff.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, generators-approved, orp-approved, tests-approved

#29312 Phase2-hgx233 Correct the HGCal code for working with dd4hep
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcal-algorithm.xml
  Geometry/HGCalCommonData/interface/HGCalGeomParameters.h
  Geometry/HGCalCommonData/python/testHGCXML_cfi.py
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
  Geometry/HGCalCommonData/src/HGCalParametersFromDD.cc
  Geometry/HGCalCommonData/test/python/testHGCalParametersDD4Hep_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#29330 Fix PUPPI MET unclustered energy computation [10_6_X]
  CommonTools/CandAlgos/plugins/CandPtrProjector.cc
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
  RecoMET/METAlgorithms/interface/METSignificance.h
  RecoMET/METAlgorithms/src/METSignificance.cc
  RecoMET/METProducers/python/METSignificanceParams_cfi.py
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29351 DQM: Fix fallback in DQMRootSource
  DQMServices/FwkIO/plugins/DQMRootSource.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29360 Run3-TB54 First step of transition to dd4hep for HCal TB simulation
  Geometry/HcalTestBeamData/BuildFile.xml
  Geometry/HcalTestBeamData/data/dd4hep/cms-test-ddTB2004-algorithm.xml
  Geometry/HcalTestBeamData/data/world.xml
  Geometry/HcalTestBeamData/interface/HcalTB02Parameters.h
  Geometry/HcalTestBeamData/interface/HcalTB02ParametersFromDD.h
  Geometry/HcalTestBeamData/interface/HcalTB06BeamParameters.h
  Geometry/HcalTestBeamData/interface/HcalTB06BeamParametersFromDD.h
  Geometry/HcalTestBeamData/plugins/BuildFile.xml
  Geometry/HcalTestBeamData/plugins/HcalTB02ParametersESModule.cc
  Geometry/HcalTestBeamData/plugins/HcalTB06BeamParametersESModule.cc
  Geometry/HcalTestBeamData/plugins/HcalTBParameterTester.cc
  Geometry/HcalTestBeamData/python/hcalDDDSimConstants_cff.py
  Geometry/HcalTestBeamData/python/hcalTB02Parameters_cff.py
  Geometry/HcalTestBeamData/python/hcalTB06Parameters_cff.py
  Geometry/HcalTestBeamData/src/HcalTB02Parameters.cc
  Geometry/HcalTestBeamData/src/HcalTB02ParametersFromDD.cc
  Geometry/HcalTestBeamData/src/HcalTB06BeamParameters.cc
  Geometry/HcalTestBeamData/src/HcalTB06BeamParametersFromDD.cc
  Geometry/HcalTestBeamData/test/python/run2004_cfg.py
  Geometry/HcalTestBeamData/test/python/testHcalTBParameterDD4Hep_cfg.py
  Geometry/HcalTestBeamData/test/python/testHcalTBParameterDDD_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#29356 Update BasicGenValidation_cff.py
  Validation/EventGenerator/python/BasicGenValidation_cff.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, generators-approved, orp-approved, tests-approved

#29352 Update BasicGenValidation_cff.py
  Validation/EventGenerator/python/BasicGenValidation_cff.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, generators-approved, orp-approved, tests-approved

#29301 Make some HLT modules into global modules
  ElectroWeakAnalysis/WENu/interface/GenPurposeSkimmer.h
  ElectroWeakAnalysis/WENu/interface/GenPurposeSkimmerAcceptance.h
  ElectroWeakAnalysis/WENu/interface/GenPurposeSkimmerData.h
  EventFilter/ScalersRawToDigi/src/ScalersRawToDigi.cc
  HLTrigger/HLTcore/interface/TriggerSummaryAnalyzerAOD.h
  HLTrigger/HLTcore/interface/TriggerSummaryAnalyzerRAW.h
  HLTrigger/HLTcore/interface/TriggerSummaryProducerAOD.h
  HLTrigger/HLTcore/interface/TriggerSummaryProducerRAW.h
  HLTrigger/HLTcore/plugins/SealModule.cc
  HLTrigger/HLTcore/plugins/TriggerSummaryAnalyzerAOD.cc
  HLTrigger/HLTcore/plugins/TriggerSummaryAnalyzerRAW.cc
  HLTrigger/HLTcore/plugins/TriggerSummaryProducerAOD.cc
  HLTrigger/HLTcore/plugins/TriggerSummaryProducerRAW.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#29259 Changed boost::scoped_ptr for std::unique_ptr
  Fireworks/Core/interface/FWConfiguration.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved, visualization-approved

#29371 Run3-sim63 Remove reference to DetectorDescription in some packages
  SimG4CMS/Calo/interface/ECalSD.h
  SimG4CMS/Calo/interface/HFShowerLibrary.h
  SimG4CMS/FP420/BuildFile.xml
  SimG4CMS/ShowerLibraryProducer/BuildFile.xml
  SimG4CMS/ShowerLibraryProducer/src/FiberSD.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#29361 Particle Flow generator truth information
  SimGeneral/CaloAnalysis/plugins/CaloTruthAccumulator.cc
  SimGeneral/MixingModule/python/caloTruthProducer_cfi.py
  Validation/RecoParticleFlow/plugins/BuildFile.xml
  Validation/RecoParticleFlow/plugins/PFAnalysis.cc
  Validation/RecoParticleFlow/python/customize_pfanalysis.py
  Validation/RecoParticleFlow/test/pfanalysis_ntuple.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#29343 DQM: fix some autoDQM.py harvesting sequences
  Configuration/Applications/python/ConfigBuilder.py
  DQMOffline/Configuration/python/DQMOfflineCosmics_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOfflineCosmics_cff.py
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#29378 Remove use of TSG internal GTs
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-pending, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-pending

#29377 fix miniaod_devel modifier use for pileupJetId.algos
  RecoJets/JetProducers/python/PileupJetID_cfi.py
Labels: comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29376 fix miniaod_devel modifier use for pileupJetId.algos
  RecoJets/JetProducers/python/PileupJetID_cfi.py
Labels: comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29335 New Service for Updating online Conditions for HLT
  CalibTracker/SiStripLorentzAngle/BuildFile.xml
  CondCore/CondDB/BuildFile.xml
  CondCore/CondDB/test/testConditionDatabase_2.cpp
  CondCore/CondDB/test/testConditionDatabase_3.cpp
  CondCore/CondDB/test/testGroupSelection.cpp
  CondCore/DBOutputService/BuildFile.xml
  CondCore/DBOutputService/interface/OnlineDBOutputService.h
  CondCore/DBOutputService/interface/PoolDBOutputService.h
  CondCore/DBOutputService/plugins/SealModule.cc
  CondCore/DBOutputService/src/OnlineDBOutputService.cc
  CondCore/DBOutputService/src/PoolDBOutputService.cc
  CondCore/DBOutputService/test/BuildFile.xml
  CondCore/DBOutputService/test/python/testLumiBasedUpdateAnalyzer_cfg.py
  CondCore/DBOutputService/test/python/testLumiBasedUpdateAnalyzer_oracle.cfg.py
  CondCore/DBOutputService/test/stubs/IOVPayloadAnalyzer.cc
  CondCore/DBOutputService/test/stubs/LumiBasedUpdateAnalyzer.cc
  CondCore/DBOutputService/test/stubs/LumiBasedUpdateAnalyzer.h
  CondCore/DBOutputService/test/stubs/MyDataAnalyzer.cc
  CondCore/DBOutputService/test/stubs/Timestamp.cc
  CondCore/PopCon/interface/PopCon.h
  CondCore/PopCon/src/PopCon.cc
  CondTools/L1Trigger/src/DataWriter.cc
  CondTools/L1TriggerExt/src/DataWriterExt.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, l1-approved, orp-approved, tests-approved

#29383 Era modifiers L1T for Phase2, Run3, and Run2_2018.
  Configuration/Eras/python/Era_Phase2_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Era_Run3_cff.py
  Configuration/Eras/python/Modifier_phase2_trigger_cff.py
  Configuration/Eras/python/Modifier_stage2L1Trigger_2018_cff.py
  Configuration/Eras/python/Modifier_stage2L1Trigger_2021_cff.py
  Configuration/StandardSequences/python/Eras.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, operations-approved, orp-approved, tests-approved

#29380 Run3-TB55 Remove direct access to DDCompactView in the SIM code for HCAL TB
  Geometry/HcalTestBeamData/test/python/run2004_cfg.py
  SimG4CMS/HcalTestBeam/plugins/BuildFile.xml
  SimG4CMS/HcalTestBeam/plugins/HcalTB02Analysis.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB02SD.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB02SD.h
  SimG4CMS/HcalTestBeam/plugins/HcalTB04Analysis.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB04XtalNumberingScheme.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB06BeamSD.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB06BeamSD.h
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#29366 Solve all overlaps detected in Phase I Tracker
  Geometry/MTCCTrackerCommonData/data/tecwheeld_mtcc.xml
  Geometry/TrackerCommonData/data/tecservices.xml
  Geometry/TrackerCommonData/data/tecwheel.xml
  Geometry/TrackerCommonData/data/tecwheel/2021/v1/tecwheel.xml
  Geometry/TrackerCommonData/data/tecwheel6.xml
  Geometry/TrackerCommonData/data/tecwheela.xml
  Geometry/TrackerCommonData/data/tecwheelb.xml
  Geometry/TrackerCommonData/data/tecwheelc.xml
  Geometry/TrackerCommonData/data/tecwheeld.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#29368 [DD4hep] Children by Name and CopyNo on a Path
  DetectorDescription/DDCMS/data/cms-geometry-2021.xml
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/interface/Filter.h
  DetectorDescription/DDCMS/src/DDFilteredView.cc
  DetectorDescription/DDCMS/test/Filter.cppunit.cc
  DetectorDescription/DDCMS/test/python/testDDSpecParsFilter.py
  SimTracker/TrackerMaterialAnalysis/data/dd4hep_trackingMaterialGroups.xml
  SimTracker/TrackerMaterialAnalysis/plugins/BuildFile.xml
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_Listgroups.cc
  SimTracker/TrackerMaterialAnalysis/test/listGroups_dd4hep.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#29379 Fixed all the "hidden" overlaps inside the CSC subsystem
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/MuonCommonData/data/csc/2021/v2/csc.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#29384 Test inter process random state transfers
  DataFormats/Common/interface/RandomNumberGeneratorState.h
  DataFormats/Common/src/classes.h
  DataFormats/Common/src/classes_def.xml
  DataFormats/TestObjects/src/classes.h
  DataFormats/TestObjects/src/classes_def.xml
  FWCore/Integration/bin/BuildFile.xml
  FWCore/Integration/bin/interprocess_random.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/RandomIntProducer.cc
  FWCore/Integration/test/RandomIntProducer_t.cpp
  FWCore/Integration/test/TestInterProcessRandomProd.cc
  FWCore/Services/BuildFile.xml
  FWCore/Services/interface/ExternalRandomNumberGeneratorService.h
  FWCore/Services/src/ExternalRandomNumberGeneratorService.cc
  FWCore/Services/test/BuildFile.xml
  FWCore/Services/test/test_catch2_ExternalRandomNumberGeneratorService.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#29364 Phase2-hgx234 Transfer the constants for HGCal and also HGCalTB for DDD/DD4Hep
  Geometry/HGCalCommonData/data/TB160/16Module/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB160/4Module/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB160/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB161/1Module/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB161/8Module/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB161/TimingLayer/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB170/July17/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB170/Sep17/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB170/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB180/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB181/June18/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB181/Oct181/hgcalCons.xml
  Geometry/HGCalCommonData/data/TB181/Test/hgcalCons.xml
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalTB181V1-algorithm.xml
  Geometry/HGCalCommonData/interface/HGCalParameters.h
  Geometry/HGCalCommonData/python/testTB181V1XML_cfi.py
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
  Geometry/HGCalCommonData/src/HGCalParameters.cc
  Geometry/HGCalCommonData/src/HGCalParametersFromDD.cc
  Geometry/HGCalCommonData/test/python/testHGCalTBParametersDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalTBParametersDDD_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#29375 PFEGammaProducer to global producer
  RecoParticleFlow/PFProducer/interface/PFEGammaAlgo.h
  RecoParticleFlow/PFProducer/plugins/PFEGammaProducer.cc
  RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29388 Run3-sim64 Allow CherenkovAnalysis to work with DDD as well as DD4Hep
  SimG4CMS/CherenkovAnalysis/BuildFile.xml
  SimG4CMS/CherenkovAnalysis/interface/DreamSD.h
  SimG4CMS/CherenkovAnalysis/plugins/BuildFile.xml
  SimG4CMS/CherenkovAnalysis/plugins/CherenkovAnalysis.cc
  SimG4CMS/CherenkovAnalysis/plugins/XtalDedxAnalysis.cc
  SimG4CMS/CherenkovAnalysis/src/DreamSD.cc
  SimG4CMS/CherenkovAnalysis/test/BuildFile.xml
  SimG4CMS/CherenkovAnalysis/test/runSingleDREAM_cfg.py
  SimG4CMS/CherenkovAnalysis/test/testMuon_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#29394 Run cuda tests only if cuda supports gcc version
  DataFormats/GeometrySurface/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#29395 added unit test to check for clang-tidy changes
  Utilities/ReleaseScripts/test/BuildFile.xml
  Utilities/ReleaseScripts/test/test-clang-tidy.cc
  Utilities/ReleaseScripts/test/test-clang-tidy.cc.yaml
  Utilities/ReleaseScripts/test/test-clang-tidy.sh
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#29169 Fireworks: Auto detect geometry version from global tag.
  Fireworks/Core/interface/CmsShowNavigator.h
  Fireworks/Core/interface/Context.h
  Fireworks/Core/interface/FWFileEntry.h
  Fireworks/Core/interface/FWGeometry.h
  Fireworks/Core/src/CmsShowMain.cc
  Fireworks/Core/src/CmsShowMain.h
  Fireworks/Core/src/CmsShowMainBase.cc
  Fireworks/Core/src/CmsShowNavigator.cc
  Fireworks/Core/src/FWFileEntry.cc
  Fireworks/Core/src/FWGeometry.cc
  Fireworks/Core/src/FWRPZViewGeometry.cc
Labels: code-checks-approved, comparison-notrun, fully-signed, orp-approved, requires-external, tests-approved, visualization-approved

#29279 Update relvals of JME customised Nano for 2016,17,18
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
Labels: analysis-approved, code-checks-pending, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved, xpog-approved

#29393 Replace validationHarvestingNoHLT with validationHarvesting in HI workflows
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#29318 Add EventsPerLumi for relvals workflows and prod-like concurrentLS relvals
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#29230 added module used to insert ECAL laser correction sets into the condi…
  CalibCalorimetry/EcalTrivialCondModules/interface/EcalLaserCondTools.h
  CalibCalorimetry/EcalTrivialCondModules/src/EcalLaserCondTools.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#29339 Fix Tracker Alignment all-in-one tool for py3 (again)
  Alignment/OfflineValidation/python/TkAlAllInOneTool/alignment.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/helperFunctions.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#29363 Support of condition updates per-lumisection
  CondCore/ESSources/interface/DataProxy.h
  CondCore/ESSources/plugins/CondDBESSource.cc
  CondCore/ESSources/plugins/CondDBESSource.h
  CondCore/ESSources/src/ProxyFactory.cc
  CondCore/ESSources/test/BuildFile.xml
  CondCore/ESSources/test/python/loadall_from_one_record_empty_source_cfg.py
  CondCore/ESSources/test/stubs/LumiTestReadAnalyzer.cc
  CondCore/Utilities/plugins/BuildFile.xml
  CondCore/Utilities/plugins/FileBasedEmptySource.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#29370 DQM: Syncing MEData with DQMNet MEData before asserting
  DQMServices/Core/src/MonitorElement.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#28313 Run3-sim47 Remove reference to trackermaterial in materials.xml
  Geometry/CMSCommonData/data/materials.xml
  Geometry/CMSCommonData/data/materials/2015/v1/materials.xml
  Geometry/CMSCommonData/data/materials/2017ZeroMaterial/v1/materials.xml
  Geometry/CMSCommonData/data/materials/2021/v1/materials.xml
  Geometry/TrackerCommonData/data/2016/FlatMinus05Percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/2016/FlatMinus10Percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/2016/FlatPlus05Percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/2016/FlatPlus10Percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/PhaseI/pixbarmaterial.xml
  Geometry/TrackerCommonData/data/Run2/trackermaterial.xml
  Geometry/TrackerCommonData/data/flat10percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/flat10services30percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/flat20percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/flat20services30percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/flat30percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/pixbarmaterial/2017ZeroMaterial/v1/pixbarmaterial.xml
  Geometry/TrackerCommonData/data/services30percent/trackermaterial.xml
  Geometry/TrackerCommonData/data/test2014/trackermaterial.xml
  Geometry/TrackerCommonData/data/trackermaterial.xml
  Geometry/TrackerCommonData/data/trackermaterial/2017ZeroMaterial/v1/trackermaterial.xml
  Geometry/TrackerCommonData/data/zeroMaterial/trackermaterial.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#29403 [Heppy] drop unnecessary dependency on rootpy
  PhysicsTools/Heppy/BuildFile.xml
  PhysicsTools/HeppyCore/BuildFile.xml
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#29396 Drop rootpy related unit tests
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/testRootpy.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#29424 Running code-format for dqm
  DQM/SiStripMonitorHardware/src/SiStripSpyEventMatcher.cc
  DQMOffline/RecoB/interface/FlavourHistorgrams.h
  DQMServices/Core/src/ROOTFilePB.pb.h
  Validation/HGCalValidation/plugins/HGCalBHValidation.cc
  Validation/RecoParticleFlow/plugins/OffsetDQMPostProcessor.cc
  Validation/RecoParticleFlow/plugins/PFAnalysis.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29081 [HGCAL] TICL in reconstruction
  Configuration/EventContent/python/EventContent_cff.py
  Configuration/StandardSequences/python/Reconstruction_cff.py
  DataFormats/HGCalReco/BuildFile.xml
  DataFormats/HGCalReco/interface/Trackster.h
  DataFormats/HGCalReco/src/classes_def.xml
  RecoHGCal/Configuration/python/RecoHGCal_EventContent_cff.py
  RecoHGCal/Configuration/python/recoHGCAL_cff.py
  RecoHGCal/TICL/plugins/ClusterFilterBase.h
  RecoHGCal/TICL/plugins/ClusterFilterByAlgo.h
  RecoHGCal/TICL/plugins/ClusterFilterByAlgoAndSize.h
  RecoHGCal/TICL/plugins/ClusterFilterBySize.h
  RecoHGCal/TICL/plugins/FilteredLayerClustersProducer.cc
  RecoHGCal/TICL/plugins/HGCDoublet.cc
  RecoHGCal/TICL/plugins/HGCGraph.cc
  RecoHGCal/TICL/plugins/HGCGraph.h
  RecoHGCal/TICL/plugins/MultiClustersFromTrackstersProducer.cc
  RecoHGCal/TICL/plugins/PFTICLProducer.cc
  RecoHGCal/TICL/plugins/PatternRecognitionAlgoBase.h
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.h
  RecoHGCal/TICL/plugins/PatternRecognitionbyMultiClusters.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyMultiClusters.h
  RecoHGCal/TICL/plugins/TICLCandidateFromTrackstersProducer.cc
  RecoHGCal/TICL/plugins/TICLSeedingRegionProducer.cc
  RecoHGCal/TICL/plugins/TracksterGeneralTrackPlugin.cc
  RecoHGCal/TICL/plugins/TracksterP4FromEnergySumPlugin.cc
  RecoHGCal/TICL/plugins/TracksterP4FromTrackAndPCA.cc
  RecoHGCal/TICL/plugins/TrackstersMergeProducer.cc
  RecoHGCal/TICL/plugins/TrackstersPCA.cc
  RecoHGCal/TICL/plugins/TrackstersPCA.h
  RecoHGCal/TICL/plugins/TrackstersProducer.cc
  RecoHGCal/TICL/python/EMStep_cff.py
  RecoHGCal/TICL/python/HADStep_cff.py
  RecoHGCal/TICL/python/MIPStep_cff.py
  RecoHGCal/TICL/python/TICLSeedingRegions_cff.py
  RecoHGCal/TICL/python/TrkStep_cff.py
  RecoHGCal/TICL/python/iterativeTICL_cff.py
  Validation/HGCalValidation/python/HGCalValidator_cfi.py
  Validation/HGCalValidation/python/PostProcessorHGCAL_cfi.py
  Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#29425 Running code-format for reconstruction-upgrade
  RecoMTD/TrackExtender/plugins/TrackExtenderWithMTD.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#29423 Running code-format for geometry-upgrade
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#29422 Running code-format for geometry
  Geometry/CaloEventSetup/interface/CaloGeometryLoader.icc
  Geometry/HcalTestBeamData/src/HcalTB02ParametersFromDD.cc
  Geometry/HcalTestBeamData/src/HcalTB06BeamParametersFromDD.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#29428 Running code-format for reconstructio
  RecoBTag/SecondaryVertex/plugins/TemplatedSecondaryVertexProducer.cc
  RecoHI/HiJetAlgos/src/MultipleAlgoIterator.cc
  RecoJets/JetProducers/plugins/CATopJetProducer.cc
  RecoJets/JetProducers/plugins/CSJetProducer.cc
  RecoJets/JetProducers/plugins/ECFAdder.cc
  RecoJets/JetProducers/plugins/FastjetJetProducer.cc
  RecoJets/JetProducers/plugins/HTTTopJetProducer.cc
  RecoJets/JetProducers/plugins/NjettinessAdder.cc
  RecoJets/JetProducers/plugins/SubEventGenJetProducer.cc
  RecoJets/JetProducers/plugins/VirtualJetProducer.cc
  RecoJets/JetProducers/src/PileUpSubtractor.cc
  RecoLuminosity/LumiProducer/plugins/LumiProducerFromBrilcalc.cc
  RecoTauTag/RecoTau/src/RecoTauConstructor.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29426 Running code-format for simulation
  IOMC/EventVertexGenerators/src/BeamDivergenceVtxGenerator.cc
  SimG4CMS/CherenkovAnalysis/plugins/XtalDedxAnalysis.cc
  SimG4Core/Geometry/src/DDG4ProductionCuts.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#29427 Running code-format for simulation-upgrade
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#29433 fixed bug in UL16 PU profile
  SimGeneral/MixingModule/python/mix_2016_25ns_UltraLegacy_PoissonOOTPU_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, urgent

#29409 Run3-sim65 Try to fix 0 TrackID for saved tracks
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Calo/src/CaloTrkProcessing.cc
  SimG4CMS/Calo/test/python/runHGC4_cfg.py
  SimG4Core/Application/src/TrackingAction.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#29309 TOP DQM: Fixed MuonRelIso
  DQM/Physics/python/singleTopDQM_cfi.py
  DQM/Physics/python/singleTopDQM_miniAOD_cfi.py
  DQM/Physics/python/topSingleLeptonDQM_cfi.py
  DQM/Physics/python/topSingleLeptonDQM_miniAOD_cfi.py
  DQM/Physics/src/TopSingleLeptonDQM_miniAOD.cc
  DQM/Physics/test/topDQM_production_cfg.py
  DQM/Physics/test/topDQM_production_miniAOD.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29387 [DD4hep] Expose Full Geo History on Request
  DetectorDescription/DDCMS/interface/DDFilteredView.h
  DetectorDescription/DDCMS/src/DDFilteredView.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#29401 Define proper BS for 2018 premixing workflow if starting from scratch
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#29438 DQM: Add a local vs. global section to the README
  DQMServices/Core/README.md
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29432 add missing initializations in pat::Muon (minimal catch up to #28212 and #29324)
  DataFormats/PatCandidates/src/Muon.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29431 fixed bug in UL16 PU profile
  SimGeneral/MixingModule/python/mix_2016_25ns_UltraLegacy_PoissonOOTPU_cfi.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, urgent

#29402 [10_6 backport] Define proper BS for 2018 premixing workflow if starting from scratch
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#29374 Restrict timestamps in PFCandidates to reliable cases
  RecoParticleFlow/PFProducer/plugins/importers/TrackTimingImporter.cc
  RecoParticleFlow/PFProducer/python/particleFlowBlock_cfi.py
  RecoParticleFlow/PFProducer/python/simPFProducer_cfi.py
  RecoParticleFlow/PFSimProducer/plugins/SimPFProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#29407 MTD Geometry: DD4hep migration, preliminary update and cleaning of ideal geometry test
  DataFormats/ForwardDetId/interface/ETLDetId.h
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D50.xml
  Geometry/MTDCommonData/data/dd4hep/cms-mtdD50-geometry.xml
  Geometry/MTDCommonData/data/dd4hep/cms-mtdD53-geometry.xml
  Geometry/MTDCommonData/src/ETLNumberingScheme.cc
  Geometry/MTDCommonData/test/BuildFile.xml
  Geometry/MTDCommonData/test/DD4hep_TestMTDIdealGeometry.cc
  Geometry/MTDCommonData/test/DD4hep_TestMTDNumbering.cc
  Geometry/MTDCommonData/test/testMTDinDD4hep.py
  SimG4CMS/Forward/src/MtdSD.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#29355 Additional Tracker DQM residual plots
  DQM/SiPixelPhase1Summary/interface/SiPixelPhase1Summary.h
  DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
  DQMServices/Core/interface/MonitorElement.h
  DQMServices/Core/src/MonitorElement.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#28978 GEM online DQM bug fix - full GE1/1
  DQM/GEM/plugins/GEMDQMHarvester.cc
  DQM/GEM/plugins/GEMDQMSource.cc
  DQM/GEM/plugins/GEMDQMStatusDigi.cc
  DQM/GEM/test/test.py
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/config/FrontierCondition_GT_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29418 Running code-format for analysis
  PhysicsTools/Heppy/src/ReclusterJets.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#29437 Reenable relval wfs 310, 311 and 312
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#29459 Use LogTrace in IsolatedPixelTrackCandidateL1TProducer
  Calibration/HcalIsolatedTrackReco/src/IsolatedPixelTrackCandidateL1TProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#29429 Add a DDFilteredView test in DetectorDescription/DDCMS
  DetectorDescription/DDCMS/plugins/test/DDTestFilteredView.cc
  DetectorDescription/DDCMS/test/python/testDDFilteredView.py
  DetectorDescription/DDCMS/test/runTest.sh
Labels: code-checks-approved, comparison-notrun, fully-signed, geometry-approved, orp-approved, tests-rejected

#29453 improve exception reporting in HLTTauRefProducer
  DQMOffline/Trigger/plugins/HLTTauRefProducer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29417 Running code-format for alca
  CalibCalorimetry/EcalTrivialCondModules/interface/EcalLaserCondTools.h
  CalibCalorimetry/EcalTrivialCondModules/src/EcalLaserCondTools.cc
  Calibration/IsolatedParticles/plugins/StudyCaloResponse.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#29440 Run3-gem34 Add a GE21 version with 16 eta partitions
  DataFormats/MuonDetId/interface/GEMDetId.h
  Geometry/MuonCommonData/data/gem21/TDR_Eta16/gem21.xml
  Geometry/MuonCommonData/plugins/DDGEMAngular.cc
  Geometry/MuonCommonData/python/testExtendedGeometry2026D54XML_cfi.py
  Geometry/MuonCommonData/python/testGEMXML_cfi.py
  Geometry/MuonCommonData/test/dumpGEM_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#29413 pr11x L1T Configure EMTF using stage2L1Trigger modifiers
  L1Trigger/L1TMuonEndCap/python/simEmtfDigis_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#29461 Re-add SiPixelPhase1TrackResidualsAnalyzer to HI scenario
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OfflineDQM_source_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29300 Apply puppi weight in BoostedDoubleSV btaginfo for packedPFCandidates
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/SecondaryVertex/plugins/BoostedDoubleSVProducer.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29369 Protect L1T producers against ME0 hits
  L1Trigger/CSCTriggerPrimitives/src/GEMCoPadProcessor.cc
  L1Trigger/L1TGEM/plugins/GEMPadDigiClusterProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#29247 Interface for high multiplicity triggers in CSC
  L1Trigger/CSCTriggerPrimitives/interface/CSCAnodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCMotherboard.h
  L1Trigger/CSCTriggerPrimitives/python/cscTriggerPrimitiveDigis_cfi.py
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME21.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboard.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#29466 [DT] DQM Validation extension
  DQM/DTMonitorModule/plugins/plugins.cc
  DQM/DTMonitorModule/python/dtDQMOfflineSources_Cosmics_cff.py
  DQM/DTMonitorModule/python/dtDQMOfflineSources_HI_cff.py
  DQM/DTMonitorModule/python/dtDQMOfflineSources_cff.py
  DQM/DTMonitorModule/python/dtOccupancyEfficiency_cfi.py
  DQM/DTMonitorModule/src/DTOccupancyEfficiency.cc
  DQM/DTMonitorModule/src/DTOccupancyEfficiency.h
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29469 Run3-hcx253 Make additional tests for DetId setting in SIM/RECO
  Geometry/HcalTowerAlgo/test/HcalGeometryDetIdTester.cc
  Geometry/HcalTowerAlgo/test/runHcalGeometryDetIdTester_cfg.py
  SimG4CMS/Calo/plugins/HcalTestSimHitID.cc
  SimG4CMS/Calo/test/python/runDetID_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#29465 Update PR #28417, TauSkimPFTausSelectedForMuTau reading anti-muon ID from new data format
  DPGAnalysis/Skims/python/MuTauSkim_cff.py
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationAgainstMuon2Container.cc
Labels: code-checks-approved, comparison-available, orp-approved, pdmv-pending, pending-signatures, reconstruction-approved, tests-approved, urgent

#29151 New EDProducer emulating the Stub processing of the Phase 2 Outer Tracker DTC board
  Configuration/AlCa/python/autoCondPhase2.py
  Configuration/EventContent/python/EventContent_cff.py
  Configuration/StandardSequences/python/L1TrackTrigger_cff.py
  DataFormats/L1TrackTrigger/interface/TTBV.h
  DataFormats/L1TrackTrigger/interface/TTDTC.h
  DataFormats/L1TrackTrigger/interface/TTTypes.h
  DataFormats/L1TrackTrigger/src/TTDTC.cc
  DataFormats/L1TrackTrigger/src/classes.h
  DataFormats/L1TrackTrigger/src/classes_def.xml
  L1Trigger/TrackerDTC/BuildFile.xml
  L1Trigger/TrackerDTC/interface/DTC.h
  L1Trigger/TrackerDTC/interface/Module.h
  L1Trigger/TrackerDTC/interface/Settings.h
  L1Trigger/TrackerDTC/interface/SettingsHybrid.h
  L1Trigger/TrackerDTC/interface/SettingsTMTT.h
  L1Trigger/TrackerDTC/interface/Stub.h
  L1Trigger/TrackerDTC/interface/TTDTCConverter.h
  L1Trigger/TrackerDTC/plugins/BuildFile.xml
  L1Trigger/TrackerDTC/plugins/Producer.cc
  L1Trigger/TrackerDTC/python/Format_Hybrid_cfi.py
  L1Trigger/TrackerDTC/python/Format_TMTT_cfi.py
  L1Trigger/TrackerDTC/python/Producer_Customize_cff.py
  L1Trigger/TrackerDTC/python/Producer_Defaults_cfi.py
  L1Trigger/TrackerDTC/python/Producer_cff.py
  L1Trigger/TrackerDTC/src/DTC.cc
  L1Trigger/TrackerDTC/src/Module.cc
  L1Trigger/TrackerDTC/src/Settings.cc
  L1Trigger/TrackerDTC/src/SettingsHybrid.cc
  L1Trigger/TrackerDTC/src/SettingsTMTT.cc
  L1Trigger/TrackerDTC/src/Stub.cc
  L1Trigger/TrackerDTC/test/test_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, l1-approved, operations-approved, orp-approved, tests-approved, upgrade-approved

#29451 Remove PhysicsTools/RooStatsCms
  ElectroWeakAnalysis/ZMuMu/bin/BuildFile.xml
  ElectroWeakAnalysis/ZMuMu/bin/hltEffwithCPError.cpp
  ElectroWeakAnalysis/ZMuMu/bin/hltEffwithCPErrorMCvsDATA.cpp
  ElectroWeakAnalysis/ZMuMu/plugins/BuildFile.xml
  ElectroWeakAnalysis/ZMuMu/plugins/MuTriggerAnalyzer.cc
  PhysicsTools/RooStatsCms/BuildFile.xml
  PhysicsTools/RooStatsCms/Makefile.standalone
  PhysicsTools/RooStatsCms/doc/html/index.html
  PhysicsTools/RooStatsCms/doc/html/overview.html
  PhysicsTools/RooStatsCms/interface/BinomialInterval.h
  PhysicsTools/RooStatsCms/interface/BinomialNoncentralInterval.h
  PhysicsTools/RooStatsCms/interface/BinomialProbHelper.h
  PhysicsTools/RooStatsCms/interface/ClopperPearsonBinomialInterval.h
  PhysicsTools/RooStatsCms/interface/ExclusionBandPlot.h
  PhysicsTools/RooStatsCms/interface/FeldmanCousinsBinomialInterval.h
  PhysicsTools/RooStatsCms/interface/LEPBandPlot.h
  PhysicsTools/RooStatsCms/interface/StatisticalPlot.h
  PhysicsTools/RooStatsCms/interface/SterneBinomialInterval.h
  PhysicsTools/RooStatsCms/macros/examples/LEP_band_plot.cxx
  PhysicsTools/RooStatsCms/macros/examples/example_qqhtt.rsc
  PhysicsTools/RooStatsCms/macros/examples/gaussian_on_expo.rsc
  PhysicsTools/RooStatsCms/macros/examples/profilelikelihood_htt.cxx
  PhysicsTools/RooStatsCms/macros/examples/qqhtt_-2lnQ_distributions.cxx
  PhysicsTools/RooStatsCms/macros/examples/simple_counting.rsc
  PhysicsTools/RooStatsCms/macros/examples/simple_counting_systematics.rsc
  PhysicsTools/RooStatsCms/scripts/Doxygen.cfg
  PhysicsTools/RooStatsCms/scripts/RSCenv.sh
  PhysicsTools/RooStatsCms/src/BinomialInterval.cc
  PhysicsTools/RooStatsCms/src/ClopperPearsonBinomialInterval.cc
  PhysicsTools/RooStatsCms/src/ExclusionBandPlot.cc
  PhysicsTools/RooStatsCms/src/FeldmanCousinsBinomialInterval.cc
  PhysicsTools/RooStatsCms/src/LEPBandPlot.cc
  PhysicsTools/RooStatsCms/src/StatisticalPlot.cc
  PhysicsTools/RooStatsCms/src/SterneBinomialInterval.cc
  PhysicsTools/RooStatsCms/src/classes.h
  PhysicsTools/RooStatsCms/src/classes_def.xml
  PhysicsTools/RooStatsCms/src/makefile
  PhysicsTools/RooStatsCms/test/BuildFile.xml
  PhysicsTools/RooStatsCms/test/testCrabToyMC.cfg
  PhysicsTools/RooStatsCms/test/testCrabToyMC.cpp
  PhysicsTools/RooStatsCms/test/testCrabToyMC.sh
  PhysicsTools/RooStatsCms/test/testCrabToyMC_summary.py
  PhysicsTools/RooStatsCms/test/testFeldmanCousinsBinomial.cpp
  PhysicsTools/TagAndProbe/plugins/BuildFile.xml
  Utilities/ReleaseScripts/scripts/git-publish
Labels: analysis-approved, code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#29467 Update PR #28417, add era modifier to TauRefProducer to read old data format from existing files
  Configuration/ProcessModifiers/python/tau_readOldDiscriminatorFormat_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  DQMOffline/Trigger/python/HLTTauDQMOffline_cfi.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved, urgent

#29434 [Fireworks] Backport of auto detect geometry version from global tag
  Fireworks/Core/interface/CmsShowNavigator.h
  Fireworks/Core/interface/Context.h
  Fireworks/Core/interface/FWFileEntry.h
  Fireworks/Core/interface/FWGeometry.h
  Fireworks/Core/src/CmsShowMain.cc
  Fireworks/Core/src/CmsShowMain.h
  Fireworks/Core/src/CmsShowMainBase.cc
  Fireworks/Core/src/CmsShowNavigator.cc
  Fireworks/Core/src/FWFileEntry.cc
  Fireworks/Core/src/FWGeometry.cc
  Fireworks/Core/src/FWRPZViewGeometry.cc
Labels: comparison-notrun, fully-signed, orp-approved, requires-external, tests-approved, visualization-approved

#29321 DQM: Allow per-lumi MEs in DQMOneEDAnalyzer
  DQMOffline/JetMET/interface/METAnalyzer.h
  DQMServices/Core/README.md
  DQMServices/Core/interface/DQMOneEDAnalyzer.h
  DQMServices/Demo/test/TestDQMEDAnalyzer.cc
  DQMServices/Demo/test/runtests.sh
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29346 New package DataFormats/L1TCorrelator for Phase2 L1Trigger
  DataFormats/L1TCorrelator/BuildFile.xml
  DataFormats/L1TCorrelator/interface/L1CaloTkTau.h
  DataFormats/L1TCorrelator/interface/L1TrkTau.h
  DataFormats/L1TCorrelator/interface/TkBsCandidate.h
  DataFormats/L1TCorrelator/interface/TkBsCandidateFwd.h
  DataFormats/L1TCorrelator/interface/TkEGTau.h
  DataFormats/L1TCorrelator/interface/TkElectron.h
  DataFormats/L1TCorrelator/interface/TkElectronFwd.h
  DataFormats/L1TCorrelator/interface/TkEm.h
  DataFormats/L1TCorrelator/interface/TkEmFwd.h
  DataFormats/L1TCorrelator/interface/TkEtMiss.h
  DataFormats/L1TCorrelator/interface/TkEtMissFwd.h
  DataFormats/L1TCorrelator/interface/TkGlbMuon.h
  DataFormats/L1TCorrelator/interface/TkGlbMuonFwd.h
  DataFormats/L1TCorrelator/interface/TkHTMiss.h
  DataFormats/L1TCorrelator/interface/TkHTMissFwd.h
  DataFormats/L1TCorrelator/interface/TkJet.h
  DataFormats/L1TCorrelator/interface/TkJetFwd.h
  DataFormats/L1TCorrelator/interface/TkMuon.h
  DataFormats/L1TCorrelator/interface/TkMuonFwd.h
  DataFormats/L1TCorrelator/interface/TkPhiCandidate.h
  DataFormats/L1TCorrelator/interface/TkPhiCandidateFwd.h
  DataFormats/L1TCorrelator/interface/TkPrimaryVertex.h
  DataFormats/L1TCorrelator/interface/TkTau.h
  DataFormats/L1TCorrelator/interface/TkTauFwd.h
  DataFormats/L1TCorrelator/src/L1CaloTkTau.cc
  DataFormats/L1TCorrelator/src/L1TrkTau.cc
  DataFormats/L1TCorrelator/src/TkBsCandidate.cc
  DataFormats/L1TCorrelator/src/TkEGTau.cc
  DataFormats/L1TCorrelator/src/TkElectron.cc
  DataFormats/L1TCorrelator/src/TkEm.cc
  DataFormats/L1TCorrelator/src/TkEtMiss.cc
  DataFormats/L1TCorrelator/src/TkGlbMuon.cc
  DataFormats/L1TCorrelator/src/TkHTMiss.cc
  DataFormats/L1TCorrelator/src/TkJet.cc
  DataFormats/L1TCorrelator/src/TkMuon.cc
  DataFormats/L1TCorrelator/src/TkPhiCandidate.cc
  DataFormats/L1TCorrelator/src/TkTau.cc
  DataFormats/L1TCorrelator/src/classes.h
  DataFormats/L1TCorrelator/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#29348 New package DataFormats/L1TCalorimeterPhase2 for Phase2 L1T
  DataFormats/L1TCalorimeterPhase2/BuildFile.xml
  DataFormats/L1TCalorimeterPhase2/interface/CaloCrystalCluster.h
  DataFormats/L1TCalorimeterPhase2/interface/CaloJet.h
  DataFormats/L1TCalorimeterPhase2/interface/CaloTower.h
  DataFormats/L1TCalorimeterPhase2/src/classes.h
  DataFormats/L1TCalorimeterPhase2/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#29347 New package DataFormats/L1TParticleFlow for Phase2 L1Trigger
  DataFormats/L1TParticleFlow/BuildFile.xml
  DataFormats/L1TParticleFlow/interface/PFCandidate.h
  DataFormats/L1TParticleFlow/interface/PFCluster.h
  DataFormats/L1TParticleFlow/interface/PFJet.h
  DataFormats/L1TParticleFlow/interface/PFTau.h
  DataFormats/L1TParticleFlow/interface/PFTrack.h
  DataFormats/L1TParticleFlow/src/PFCandidate.cc
  DataFormats/L1TParticleFlow/src/PFCluster.cc
  DataFormats/L1TParticleFlow/src/PFJet.cc
  DataFormats/L1TParticleFlow/src/PFTau.cc
  DataFormats/L1TParticleFlow/src/PFTrack.cc
  DataFormats/L1TParticleFlow/src/classes.h
  DataFormats/L1TParticleFlow/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#29450 Remove TICL dedicated wfs, and adjust the name for the pfTICLProducer automatic config
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  RecoHGCal/TICL/plugins/PFTICLProducer.cc
  RecoHGCal/TICL/python/iterativeTICL_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, reconstruction-approved, tests-approved, upgrade-approved

#29457 Clean up Run-Dependent workflows, MultiRun harvesting for Run-Dependent MC, and update/bug fix for runTheMatrix
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/relval_premix.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-pending, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#29233 [L1Trigger/CSCTriggerPrimitives] Store comparator hits in the CLCT (CCLUT-4)
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeCathodeLCTProcessor.cc
Labels: code-checks-approved, comparison-available, fully-signed, l1-approved, orp-approved, tests-approved

#29473 PoolSource's firstLuminosityBlockForEachRun properly skips Lumis
  IOPool/Input/src/RootFile.cc
  IOPool/Input/test/TestPoolInput.sh
  IOPool/Input/test/firstLuminosityBlockForEachRun_skipLumis_Test_cfg.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#29475 updated lost dictionaries mapping for L1T Phase2
  Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py
Labels: code-checks-approved, comparison-pending, core-approved, fully-signed, orp-approved, tests-started

#29442 Migration to Geant4 10.6p01
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/PhysicsLists/interface/CMSHadronPhysicsFTFP_BERT.h
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMM.cc
  SimG4Core/PhysicsLists/src/CMSHadronPhysicsFTFP_BERT.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, requires-external, simulation-approved, tests-approved

#29477 [PY3] Fix duplicate dictionary checker for python3
  Utilities/ReleaseScripts/scripts/XML2Python.py
  Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#29478 L1Trigger/TrackerDTC fix for SLHCUpgradeSimulations/Geometry unit test failure (#29474)
  L1Trigger/TrackerDTC/python/Producer_Defaults_cfi.py
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-pending, urgent

#29385 Fix MET Significance, Covariance Matrix and unclustered energy lepton subtraction
  CommonTools/CandAlgos/plugins/CandPtrProjector.cc
  PhysicsTools/PatUtils/plugins/PFEGammaToCandidate.cc
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
  RecoMET/METAlgorithms/src/METSignificance.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#29399 vavilov parameters kappa fix
  CondFormats/SiPixelTransient/src/SiPixelTemplate.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29420 Running code-format for alca-db
  CondCore/DBOutputService/interface/OnlineDBOutputService.h
  CondCore/DBOutputService/src/OnlineDBOutputService.cc
  CondFormats/HcalObjects/interface/HcalLUTCorrs.h
  CondFormats/HcalObjects/interface/HcalPedestals.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#29419 Running code-format for db
  CondCore/CondDB/src/IOVEditor.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#29063 [10_2_X] MXNet-based implementation of the ParticleNet tagger
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/Configuration/python/RecoBTag_cff.py
  RecoBTag/FeatureTools/plugins/DeepBoostedJetTagInfoProducer.cc
  RecoBTag/MXNet/plugins/BoostedJetMXNetJetTagsProducer.cc
  RecoBTag/MXNet/plugins/BuildFile.xml
  RecoBTag/MXNet/plugins/DeepBoostedJetTagsProducer.cc
  RecoBTag/MXNet/python/Parameters/ParticleNet/V00/pfParticleNetPreprocessParams_cfi.py
  RecoBTag/MXNet/python/pfDeepBoostedJet_cff.py
  RecoBTag/MXNet/python/pfMassDecorrelatedParticleNetDiscriminatorsJetTags_cfi.py
  RecoBTag/MXNet/python/pfParticleNetDiscriminatorsJetTags_cfi.py
  RecoBTag/MXNet/python/pfParticleNet_cff.py
  RecoBTag/MXNet/test/test_particle_net_cfg.py
Labels: analysis-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#29411 Run3 hcx252 Add provision of having dd4hep in saving geometry to DB
  CondTools/Geometry/plugins/HcalParametersDBBuilder.cc
  CondTools/Geometry/plugins/PHGCalParametersDBBuilder.cc
  CondTools/Geometry/python/HGCalParametersWriter_cff.py
  CondTools/Geometry/python/HcalParametersWriter_cff.py
  CondTools/Geometry/test/calogeometry2026writer.py
  CondTools/Geometry/test/calogeometrywriter.py
  CondTools/Geometry/test/writehelpers/geometryExtended2016_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2017Plan1_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2017_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2018_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2019_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2021_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2026_writer.py
  CondTools/Geometry/test/writehelpers/geometryrun2devwriter.py
  CondTools/Geometry/test/writehelpers/geometryrun2writer.py
  CondTools/Geometry/test/writehelpers/geometrywriter.py
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#29240 Added dictionary classes in EcalCondDB to be used in pyroot for the laser monitoring analysis
  OnlineDB/EcalCondDB/bin/test_db_connect.py
  OnlineDB/EcalCondDB/interface/IODConfig.h
  OnlineDB/EcalCondDB/src/classes.h
  OnlineDB/EcalCondDB/src/classes_def.xml
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#29454 Speed up filesFromList and filesFromDASQuery in ConfigBuilder.py
  Configuration/Applications/python/ConfigBuilder.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#28977 GEM online DQM bug fix - full GE1/1, backport to 11_0_X
  DQM/GEM/plugins/GEMDQMHarvester.cc
  DQM/GEM/plugins/GEMDQMSource.cc
  DQM/GEM/plugins/GEMDQMStatusDigi.cc
  DQM/GEM/test/test.py
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/config/FrontierCondition_GT_cfi.py
Labels: backport-ok, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29436 Add a persistent class for PPS geometry as well as a database geometry builder
  CondCore/GeometryPlugins/plugins/plugin.cc
  CondFormats/GeometryObjects/interface/PDetGeomDesc.h
  CondFormats/GeometryObjects/src/T_EventSetup_PDetGeomDesc.cc
  CondFormats/GeometryObjects/src/classes.h
  CondFormats/GeometryObjects/src/classes_def.xml
  CondFormats/GeometryObjects/test/testSerializationGeometryObjects.cpp
  CondTools/Geometry/plugins/BuildFile.xml
  CondTools/Geometry/plugins/PPSGeometryBuilder.cc
  CondTools/Geometry/test/ppsgeometrywriter.py
  Geometry/Records/interface/VeryForwardIdealGeometryRecord.h
  Geometry/Records/src/VeryForwardIdealGeometryRecord.cc
  Geometry/VeryForwardGeometry/python/geometryIdealPPSFromDD_2016_cfi.py
  Geometry/VeryForwardGeometry/python/geometryIdealPPSFromDD_2017_cfi.py
  Geometry/VeryForwardGeometry/python/geometryIdealPPSFromDD_2018_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#29458 Small fixes to special DB payload scripts
  CondTools/Geometry/test/writehelpers/createExtended2017Plan1Payloads.sh
  CondTools/Geometry/test/writehelpers/createExtended2018Payloads.sh
  CondTools/Geometry/test/writehelpers/createExtended2021Payloads.sh
  CondTools/Geometry/test/writehelpers/createExtended2026Payloads.sh
  CondTools/Geometry/test/writehelpers/createRun1Payloads.sh
  Validation/Geometry/test/dddvsdb/runDDDvsDBGeometryValidation.sh
Labels: code-checks-approved, comparison-available, db-approved, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#29489 Add link to cub::CachingDeviceAllocator documentation
  HeterogeneousCore/CUDACore/README.md
Labels: code-checks-approved, comparison-available, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#29303 Removing GEDGsfElectronProducer - No inheriting electron producers anymore
  Calibration/EcalAlCaRecoProducers/python/ALCARECOEcalUncalIsolElectron_Output_cff.py
  RecoEgamma/EgammaElectronProducers/plugins/GEDGsfElectronProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/GEDGsfElectronValueMapProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronBaseProducer.h
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGSFToTrackLinker.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSCProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedProducer.cc
  RecoEgamma/EgammaElectronProducers/python/gedGsfElectronSequence_cff.py
  RecoEgamma/EgammaElectronProducers/python/gedGsfElectrons_cfi.py
  RecoEgamma/EgammaElectronProducers/python/gsfElectrons_cfi.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectrons_cfi.py
  RecoEgamma/EgammaIsolationAlgos/plugins/ParticleBasedIsoProducer.cc
  RecoParticleFlow/PFProducer/plugins/PFProducer.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29410 Don't include forward headers in cc files in RecoParticleFlow/PFProducer package
  DataFormats/EgammaReco/interface/BasicCluster.h
  DataFormats/EgammaReco/interface/BasicClusterFwd.h
  DataFormats/EgammaReco/interface/PreshowerCluster.h
  DataFormats/ParticleFlowReco/interface/PFConversion.h
  DataFormats/ParticleFlowReco/interface/PFV0.h
  DataFormats/VertexReco/interface/Vertex.h
  RecoHI/HiCentralityAlgos/plugins/CentralityProducer.cc
  RecoParticleFlow/PFProducer/plugins/ChargedHadronPFTrackIsolationProducer.cc
  RecoParticleFlow/PFProducer/plugins/PFCandidateChecker.cc
  RecoParticleFlow/PFProducer/plugins/PFEGammaProducer.cc
  RecoParticleFlow/PFProducer/plugins/PFElectronTranslator.cc
  RecoParticleFlow/PFProducer/plugins/PFLinker.cc
  RecoParticleFlow/PFProducer/plugins/PFPhotonTranslator.cc
  RecoParticleFlow/PFProducer/plugins/PFProducer.cc
  RecoParticleFlow/PFProducer/plugins/importers/ConversionTrackImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/EGPhotonImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/GSFTrackImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporterWithVeto.cc
  RecoParticleFlow/PFProducer/plugins/importers/GenericClusterImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/SpecialClusterImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/SuperClusterImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/TrackFromParentImporter.h
  RecoParticleFlow/PFProducer/plugins/importers/TrackTimingImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/V0TrackImporter.cc
  RecoParticleFlow/PFProducer/plugins/plugins.cc
  RecoParticleFlow/PFProducer/src/PFCandConnector.cc
  RecoParticleFlow/PFProducer/test/EgGEDPhotonAnalyzer.cc
  RecoParticleFlow/PFProducer/test/GsfGEDElectronAnalyzer.cc
  RecoParticleFlow/PFProducer/test/PFBlockComparator.cc
  RecoParticleFlow/PFProducer/test/PFEGCandidateTreeMaker.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29441 Phase1 Tracker: Added rails, Shrinked outermost shield, Added TBPX inter-flanges support tubs
  DetectorDescription/DDCMS/data/cms-geometry-2021.xml
  DetectorDescription/DDCMS/data/cms-tracker-2021.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/TrackerCommonData/data/PhaseI/v1/pixbar.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#29421 Running code-format for generators
  SimDataFormats/GeneratorProducts/src/GenEventInfoProduct.cc
Labels: code-checks-approved, comparison-available, generators-pending, orp-approved, pending-signatures, tests-approved

#29499 Speed up filesFromList and filesFromDASQuery in ConfigBuilder.py [106X]
  Configuration/Applications/python/ConfigBuilder.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#29492 Decrease begin Run startup time for HLT
  DataFormats/Common/src/classes.h
  DataFormats/Common/src/classes_def.xml
  DataFormats/Provenance/src/classes_def.xml
  EventFilter/Utilities/interface/EvFOutputModule.h
  EventFilter/Utilities/src/EvFOutputModule.cc
  IOPool/Streamer/interface/StreamSerializer.h
  IOPool/Streamer/interface/StreamerOutputModuleBase.h
  IOPool/Streamer/interface/StreamerOutputModuleCommon.h
  IOPool/Streamer/plugins/BuildFile.xml
  IOPool/Streamer/plugins/ParameterSetBlobProducer.cc
  IOPool/Streamer/src/StreamSerializer.cc
  IOPool/Streamer/src/StreamerOutputModuleBase.cc
  IOPool/Streamer/src/StreamerOutputModuleCommon.cc
Labels: code-checks-approved, comparison-available, core-approved, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29324 Backport of inverse beta variable in pat::Muons for 10_6_X
  DataFormats/PatCandidates/interface/Muon.h
  DataFormats/PatCandidates/src/Muon.cc
  DataFormats/PatCandidates/src/classes_def_objects.xml
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc
  PhysicsTools/PatAlgos/plugins/PATMuonProducer.h
  PhysicsTools/PatAlgos/python/producersLayer1/muonProducer_cfi.py
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29304 Remove unused SeedFilter class in EgammaElectronAlgos to simplify ElectronSeedProducer
  DPGAnalysis/Skims/python/singleElectronSkim_cff.py
  RecoEgamma/EgammaElectronAlgos/interface/SeedFilter.h
  RecoEgamma/EgammaElectronAlgos/src/ElectronSeedGenerator.cc
  RecoEgamma/EgammaElectronAlgos/src/SeedFilter.cc
  RecoEgamma/EgammaElectronProducers/plugins/ElectronSeedProducer.cc
  RecoEgamma/EgammaElectronProducers/python/ecalDrivenElectronSeeds_cff.py
  RecoHI/Configuration/python/Reconstruction_HI_cff.py
  RecoHI/HiEgammaAlgos/python/HiElectronSequence_cff.py
  RecoParticleFlow/PFTracking/interface/ElectronSeedMerger.h
  RecoParticleFlow/PFTracking/interface/PFElecTkProducer.h
  RecoParticleFlow/PFTracking/plugins/ElectronSeedMerger.cc
  RecoParticleFlow/PFTracking/plugins/GoodSeedProducer.cc
  RecoParticleFlow/PFTracking/plugins/GoodSeedProducer.h
  RecoParticleFlow/PFTracking/plugins/PFElecTkProducer.cc
  RecoParticleFlow/PFTracking/plugins/modules.cc
  RecoTracker/TrackProducer/plugins/GsfTrackProducer.cc
  RecoTracker/TrackProducer/plugins/GsfTrackProducer.h
  RecoTracker/TrackProducer/plugins/SealModules.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, reconstruction-approved, tests-approved

#29482 Phase2-hgx235 Rearrange the files to enable both DDD and DD4Hep to work
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D35XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D41XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D43XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D44XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D45XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D46XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D47XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D48XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D49XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D50XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D51XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D52XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D53XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D54XML_cfi.py
  Geometry/ForwardCommonData/data/hfnose/v1a/hfnose.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#29483 Phase2-hgx236 Remove the ERROR message from the algos
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalCell.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalEEAlgo.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalWafer.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalWafer8.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalWaferAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#29468 Run3-alca163 Modify the code for IsoTrack analysis to get it adapted for 2017 data
  Calibration/HcalCalibAlgos/macros/CalibSort.C
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkAnalyzer.cc
  Calibration/HcalCalibAlgos/test/python/isoTrackRecoAnalysis_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#29062 [10_6_X] MXNet-based implementation of the ParticleNet tagger
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/Configuration/python/RecoBTag_cff.py
  RecoBTag/FeatureTools/plugins/DeepBoostedJetTagInfoProducer.cc
  RecoBTag/MXNet/plugins/BoostedJetMXNetJetTagsProducer.cc
  RecoBTag/MXNet/plugins/BuildFile.xml
  RecoBTag/MXNet/plugins/DeepBoostedJetTagsProducer.cc
  RecoBTag/MXNet/python/Parameters/ParticleNet/V00/pfParticleNetPreprocessParams_cfi.py
  RecoBTag/MXNet/python/pfDeepBoostedJet_cff.py
  RecoBTag/MXNet/python/pfMassDecorrelatedParticleNetDiscriminatorsJetTags_cfi.py
  RecoBTag/MXNet/python/pfParticleNetDiscriminatorsJetTags_cfi.py
  RecoBTag/MXNet/python/pfParticleNet_cff.py
  RecoBTag/MXNet/test/test_particle_net_cfg.py
Labels: analysis-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#29333 pixel mc gain calibration scheme: new GTs for MC Run3, modified Clusterizer conditions for Run3
  Configuration/AlCa/python/autoCond.py
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29495 re-add also SiPixelPhase1RecHitsAnalyzer to DQM offline for HI scenario
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OfflineDQM_harvesting_cff.py
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OfflineDQM_source_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29500 Speed up filesFromList and filesFromDASQuery in ConfigBuilder.py [102X]
  Configuration/Applications/python/ConfigBuilder.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#29502 Speed up filesFromList and filesFromDASQuery in ConfigBuilder.py [80X]
  Configuration/Applications/python/ConfigBuilder.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#29501 Speed up filesFromList and filesFromDASQuery in ConfigBuilder.py [94X]
  Configuration/Applications/python/ConfigBuilder.py
Labels: backport-ok, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#29514 Fix HLT Integration Tests
  HLTrigger/Configuration/test/runIntegration.csh
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, tests-approved

#29443 Add possibility to specify GBT Id only to DTC cabling map producer
  CondTools/SiPhase2Tracker/plugins/DTCCablingMapProducer.cc
  CondTools/SiPhase2Tracker/test/DTCCablingMapProducer_write.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved, upgrade-approved

#29511 pps geometry (pps.xml) for Run3
  Geometry/VeryForwardData/data/2021/v1/pps.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#29225 Update eventcontent structure and remove drop
  RecoEgamma/Configuration/python/RecoEgamma_EventContent_cff.py
  RecoLocalCalo/Configuration/python/RecoLocalCalo_EventContent_cff.py
  RecoLocalCalo/Configuration/python/ecalLocalReco_EventContent_cff.py
  RecoMuon/Configuration/python/RecoMuon_EventContent_cff.py
  RecoMuon/MuonIsolationProducers/python/muIsolation_EventContent_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29372 DQM: Added unit test support for most online DQM clients
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/castor_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/csc_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/ctpps_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/dt4ml_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/dt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/es_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/fed_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hcal2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hcal_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hlt_dqm_clientPB-live_cfg.py
  DQM/Integration/python/clients/hlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/info_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/mutracking_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/pixel_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/pixellumi_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/rpc_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/scal_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/visualization-live-secondInstance_cfg.py
  DQM/Integration/python/clients/visualization-live_cfg.py
  DQM/Integration/python/config/unittestinputsource_cfi.py
  DQM/Integration/test/BuildFile.xml
  DQM/Integration/test/README.md
  DQM/Integration/test/runtest.sh
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, requires-external, tests-approved

#29435 Fix SwitchProducer for products from earlier processes
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/WorkerMaker.cc
  FWCore/Integration/test/run_TestSwitchProducer.sh
  FWCore/Integration/test/testSwitchProducerTaskInput_cfg.py
  FWCore/Modules/src/SwitchProducer.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#29484 Fixed BUS error due to uninitialized MEs
  DQM/RPCMonitorDigi/src/RPCMonitorDigi.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, requires-external, tests-approved

#29493 DQM BeamPixel Online client ME double reset fix
  DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, requires-external, tests-approved

#29494 Modify DQMHarvestUnit to multiRun when RD MC runs
  Configuration/PyReleaseValidation/python/MatrixInjector.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#29506 DQM Checking if ME exists after getting it in harvesting
  DQM/GEM/plugins/GEMDQMHarvester.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, requires-external, tests-approved

#29505 New PCC producer for collecting PCC/lumiblock
  Calibration/LumiAlCaRecoProducers/plugins/AlcaPCCIntegrator.cc
  Calibration/LumiAlCaRecoProducers/plugins/BuildFile.xml
  Calibration/LumiAlCaRecoProducers/test/PCC_Random_Event_Integrator_cfg.py
  DataFormats/Luminosity/interface/PixelClusterCounts.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29452 Add DeepJet scores for gluon and light quark tagging in JME Custom-NanoAODs
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved, xpog-approved

#29392 Fix MET Significance, Covariance Matrix and unclustered energy lepton subtraction [10_6_X]
  CommonTools/CandAlgos/plugins/CandPtrProjector.cc
  PhysicsTools/PatUtils/plugins/PFEGammaToCandidate.cc
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
  RecoMET/METAlgorithms/src/METSignificance.cc
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29487 Run3-hcx254 Add test to compare cell parameters for HCAL geometry by DDD vs DD4Hep
  Geometry/HcalAlgo/data/cmsExtendedGeometry2021.xml
  Geometry/HcalTowerAlgo/test/HcalCellParameterDump.cc
  Geometry/HcalTowerAlgo/test/runHcalCellDumpDD4Hep_cfg.py
  Geometry/HcalTowerAlgo/test/runHcalCellDumpDDD_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#29497 Created a new Phase2 Scenario (2026D55 ) with an updated Phase2 Muon Geometry (M5)
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryExtended2026D55Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D55_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D55XML_cfi.py
  Geometry/MuonCommonData/data/mf/2026/v3/mf.xml
  Geometry/MuonCommonData/data/muonNumbering/TDR_DeV/v1/muonNumbering.xml
  Geometry/MuonCommonData/data/rpcf/2026/v3/rpcf.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#29503 Handle retries in SONIC
  HeterogeneousCore/SonicCore/README.md
  HeterogeneousCore/SonicCore/interface/SonicClientBase.h
  HeterogeneousCore/SonicCore/test/DummyClient.h
  HeterogeneousCore/SonicCore/test/sonicTest_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#29389 Update of the lostTrack collection for MUO
  PhysicsTools/PatAlgos/plugins/PATLostTracks.cc
  PhysicsTools/PatAlgos/plugins/PATMuonMerger.cc
  PhysicsTools/PatAlgos/python/patMuonMerger_cfi.py
  PhysicsTools/PatAlgos/python/slimming/lostTracks_cfi.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29299 Update event content structure in RecoEcal and RecoVertex
  RecoEcal/Configuration/python/RecoEcal_EventContent_cff.py
  RecoVertex/BeamSpotProducer/python/BeamSpot_EventContent_cff.py
  RecoVertex/Configuration/python/RecoVertex_EventContent_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29463 Phase2-gem35 First step to move ME0 to GE0
  Geometry/GEMGeometryBuilder/data/v9/GEMSpecs.xml
  Geometry/GEMGeometryBuilder/data/v9/GEMSpecsFilter.xml
  Geometry/MuonCommonData/data/ge0/TDR_Dev/v2/ge0.xml
  Geometry/MuonCommonData/data/mf/2026/v4/mf.xml
  Geometry/MuonCommonData/data/mfshield/2026/v2/mfshield.xml
  Geometry/MuonCommonData/data/muonNumbering/TDR_DeV/v2/muonNumbering.xml
  Geometry/MuonCommonData/python/testExtendedGeometry2026D54GE0XML_cfi.py
  Geometry/MuonCommonData/python/testGE0XML_cfi.py
  Geometry/MuonCommonData/test/dumpGE0_cfg.py
  Geometry/MuonSimData/data/PhaseII/v2/muonSens.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#29481 SiPixel Payload Inspector: Gain Calibration
  CondCore/SiPixelPlugins/interface/SiPixelGainCalibHelper.h
  CondCore/SiPixelPlugins/interface/SiPixelPayloadInspectorHelper.h
  CondCore/SiPixelPlugins/plugins/BuildFile.xml
  CondCore/SiPixelPlugins/plugins/SiPixelGainCalibrationForHLT_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelGainCalibrationOffline_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelLorentzAngle_PayloadInspector.cc
  CondCore/SiPixelPlugins/test/testSiPixelGainCalibrationForHLT.sh
  CondCore/SiPixelPlugins/test/testSiPixelGainCalibrationOffline.sh
  CondCore/SiPixelPlugins/test/testSiPixelPayloadInspector.cpp
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#29521 keeping METsumPtUnclustered (backport of #28370)
  DataFormats/PatCandidates/interface/MET.h
  DataFormats/PatCandidates/src/MET.cc
  DataFormats/PatCandidates/src/classes_def_objects.xml
  PhysicsTools/PatAlgos/plugins/PATMETProducer.cc
  PhysicsTools/PatAlgos/plugins/PATMETProducer.h
  RecoMET/METAlgorithms/interface/METSignificance.h
  RecoMET/METAlgorithms/src/METSignificance.cc
  RecoMET/METProducers/src/METSignificanceProducer.cc
  RecoMET/METProducers/src/PFMETProducer.cc
Labels: analysis-approved, backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29525 Fix skipping of LuminosityBlock with firstLuminosityBlockForEachRun
  FWCore/Modules/src/EventIDChecker.cc
  FWCore/Sources/src/EventSkipperByID.cc
  IOPool/Input/src/RootFile.cc
  IOPool/Input/test/RunPerLumiTest_cfg.py
  IOPool/Input/test/TestPoolInput.sh
  IOPool/Input/test/firstLuminosityBlockForEachRun_skipLumis2_Test_cfg.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#29515 Run3-alca165 Update all scripts for IsoTrack calibration
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibSort.C
  Calibration/HcalCalibAlgos/macros/CalibTree.C
  Calibration/HcalCalibAlgos/macros/isotrackApplyRegressor.py
  Calibration/HcalCalibAlgos/macros/isotrackTrainRegressor.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#29523 Change Herwig7Interface to be consistent with Herwig 7.2.0
  GeneratorInterface/Herwig7Interface/interface/Herwig7Interface.h
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#29534 Fix DQM/Integration unit test in PY3
  DQM/Integration/python/config/unittestinputsource_cfi.py
Labels: code-checks-approved, comparison-pending, dqm-approved, fully-signed, orp-approved, tests-approved

#29510 Fix ONNX model file version in the unittest
  PhysicsTools/ONNXRuntime/test/data/model.onnx
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-started

#29535 Update eventcontent structure in RecoPixelVertexing
  RecoPixelVertexing/Configuration/python/RecoPixelVertexing_EventContent_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29530 Run3-sim66 Make ECAL geometry builder dd4hep ERA dependent
  Geometry/EcalAlgo/python/EcalBarrelGeometry_cfi.py
  Geometry/EcalAlgo/python/EcalEndcapGeometry_cfi.py
  Geometry/EcalAlgo/python/EcalGeometry_cfi.py
  Geometry/EcalAlgo/python/EcalPreshowerGeometry_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#29539 Herwig 7.2 Interface backport to CMSSW_10_6_X
  GeneratorInterface/Herwig7Interface/interface/Herwig7Interface.h
Labels: comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#29536 Herwig 7.2 Interface backport to CMSSW_10_2_X
  GeneratorInterface/Herwig7Interface/interface/Herwig7Interface.h
Labels: comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved
