Repository cms-sw/cmssw, pull requests merged in 2020-06, with the labels that each got.

#30003 PyReleaseValidation: move DD4hep test workflow into upgrade special wf section
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Geometry/CMSCommonData/test/dd4hep/runDD4hepTestWF.sh
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#30062 Davix unit test fix: use google instead of cern.ch
  Utilities/DavixAdaptor/test/http.cpp
Labels: comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30053 ConcurrentHadronizerFilter (106X)
  FWCore/Utilities/interface/RandomNumberGenerator.h
  GeneratorInterface/Core/interface/ConcurrentHadronizerFilter.h
  GeneratorInterface/ExternalDecays/interface/ConcurrentExternalDecayDriver.h
  GeneratorInterface/ExternalDecays/src/ConcurrentExternalDecayDriver.cc
  GeneratorInterface/ExternalDecays/src/ExternalDecayDriver.cc
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  IOMC/RandomEngine/src/RandomNumberGeneratorService.cc
  IOMC/RandomEngine/src/RandomNumberGeneratorService.h
  IOMC/RandomEngine/test/TestRandomNumberServiceGlobal.cc
Labels: comparison-available, core-approved, fully-signed, generators-approved, orp-approved, tests-approved

#30002 Do not apply the "const" modifier to the return type (11.1.x)
  CondFormats/EcalObjects/interface/EcalXtalGroupId.h
Labels: alca-approved, backport-ok, comparison-available, db-pending, orp-approved, pending-signatures, tests-approved

#30014 [11.1.X] Add CDC Tracks to TkAlCosmics0T ALCARECO
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlCosmics0T_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlCosmics0T_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
  DQMOffline/Alignment/python/ALCARECOTkAlDQM_cff.py
Labels: alca-approved, backport, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#30013 add CDC Tracks to TkAlCosmics0T ALCARECO
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlCosmics0T_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlCosmics0T_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
  DQMOffline/Alignment/python/ALCARECOTkAlDQM_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#30054 optimize: rely on Candidate pt,eta,phi without casting in MuonPFIsolationWithConeVeto
  PhysicsTools/IsolationAlgos/plugins/CITKPFIsolationSumProducerForPUPPI.cc
  RecoMuon/MuonIsolation/plugins/MuonPFIsolationWithConeVeto.cc
Labels: analysis-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#29630 Deprecate convertToUnscheduled() customize function and --runUnscheduled argument of cmsDriver
  CalibMuon/DTCalibration/python/ALCARECODtCalib_cff.py
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalHO_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalZeroBiasHI_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalZeroBias_cff.py
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/DataProcessing/python/Reco.py
  Configuration/PyReleaseValidation/python/MatrixReader.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_unsch.py
  Configuration/Skimming/test/test_MONOPOLEskim.py
  Configuration/StandardSequences/python/AlCaRecoStream_SpecialsHI_cff.py
  Configuration/StandardSequences/python/AlCaRecoStream_Specials_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreamsHeavyIons_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
  Configuration/StandardSequences/python/Validation_cff.py
  DQM/DTMonitorModule/python/ALCARECODTCalibSynchCosmicsDQM_cff.py
  DQM/DTMonitorModule/python/ALCARECODTCalibSynchDQM_cff.py
  DQM/DTMonitorModule/python/ALCARECODTCalibSynchHIDQM_cff.py
  DQM/Integration/python/clients/dt4ml_dqm_sourceclient-live_cfg.py
  DQM/RPCMonitorDigi/test/rpcdqm_cfg.py
  DQM/SiStripMonitorClient/python/SiStripSourceConfigTier0_HeavyIons_cff.py
  DQM/SiStripMonitorClient/python/SiStripSourceConfigTier0_cff.py
  DQMOffline/Alignment/python/ALCARECOTkAlDQM_cff.py
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalMinBiasDQMHI_cff.py
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalMinBiasDQM_cff.py
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalZeroBiasDQMHI_cff.py
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalZeroBiasDQM_cff.py
  DQMOffline/Configuration/scripts/cmsswConfigtrace.py
  DQMOffline/Configuration/scripts/cmsswSequenceInfo.py
  DQMServices/Demo/test/rundemo_cfg.py
  FWCore/ParameterSet/python/Utilities.py
  FastSimulation/Validation/test/TrackRecoAndValidation_FullSim_cfg.py
  FastSimulation/Validation/test/TrackRecoAndValidation_cfg.py
  HLTrigger/Configuration/test/cmsDriver.csh
  RecoMuon/MuonIdentification/test/TestMuonIdProducer_cfg.py
  RecoPixelVertexing/PixelLowPtUtilities/test/clusterShapeExtractor_phase1_cfg.py
  RecoPixelVertexing/PixelLowPtUtilities/test/clusterShapeExtractor_phase2_cfg.py
  SLHCUpgradeSimulations/Geometry/test/phase2_digi_reco_pixelntuple_cfg.py
  SLHCUpgradeSimulations/Geometry/test/phase2_reco_pixelntuple_cfg.py
  TauAnalysis/MCEmbeddingTools/python/customisers.py
  TauAnalysis/MCEmbeddingTools/test/runtests.sh
  Validation/Configuration/python/globalValidation_cff.py
  Validation/Geometry/test/runMaterialDumpAnalyser_PhaseII.sh
  Validation/RecoEgamma/python/photonMiniAODValidationTask_cff.py
  Validation/RecoMuon/python/RelValCustoms.py
  Validation/RecoParticleFlow/test/run_relval.sh
  Validation/RecoTrack/python/TrackValidation_cff.py
  Validation/TrackerConfiguration/test/ValidationChainOnly_cfg.py
Labels: alca-approved, analysis-approved, code-checks-approved, comparison-available, core-approved, dqm-approved, fastsim-approved, fully-signed, geometry-approved, hlt-approved, operations-approved, orp-approved, pdmv-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#30022 [L1] fixes UBSAN build errors
  L1Trigger/L1TMuon/BuildFile.xml
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#30005 Some build files relocated to the right directory
  L1Trigger/L1TCalorimeter/BuildFile.xml
  L1Trigger/L1TGlobal/BuildFile.xml
  L1Trigger/L1TMuonBarrel/BuildFile.xml
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#29990 Cleaning Cosmic and HI event content structures
  Configuration/EventContent/python/EventContentCosmics_cff.py
  Configuration/EventContent/python/EventContentHeavyIons_cff.py
  RecoLocalMuon/Configuration/python/RecoLocalMuonCosmics_EventContent_cff.py
  RecoLocalTracker/Configuration/python/RecoLocalTracker_Cosmics_EventContent_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved

#29976 bug fix to runTauIdMVA.py tool
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
  RecoTauTag/RecoTau/test/runtests.sh
Labels: analysis-approved, code-checks-approved, comparison-available, orp-approved, pending-signatures, reconstruction-approved, tests-approved, xpog-pending

#29898 MTD simulation: ETL update
  SimFastTiming/FastTimingCommon/interface/ETLElectronicsSim.h
  SimFastTiming/FastTimingCommon/python/mtdDigitizer_cfi.py
  SimFastTiming/FastTimingCommon/src/ETLElectronicsSim.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#30006 DbOutputService: Clean up of commented out code and printouts
  CondCore/DBOutputService/interface/PoolDBOutputService.h
  CondCore/DBOutputService/src/PoolDBOutputService.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#29965 ECAL : Tools to include EcalPFRecHitThresholds in Cond DB
  CalibCalorimetry/EcalTrivialCondModules/src/EcalTrivialConditionRetriever.cc
  CondTools/Ecal/interface/EcalPFRecHitThresholdsHandler.h
  CondTools/Ecal/plugins/TestEcalPFRecHitThresholdsAnalyzer.cc
  CondTools/Ecal/python/updatePFRecHitThresholds.py
  CondTools/Ecal/src/EcalPFRecHitThresholdsHandler.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30008 Fix one more CondCore unit test
  CondCore/Utilities/test/BuildFile.xml
  CondCore/Utilities/test/testPngHistograms.cpp
Labels: bug-fix, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30042 Remove mcdb and libhepml dependencies
  GeneratorInterface/LHEInterface/BuildFile.xml
  GeneratorInterface/LHEInterface/plugins/BuildFile.xml
  GeneratorInterface/MCatNLOInterface/plugins/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#30043 Run3-gem39 Modify the ESProducer for GEM/ME0 to work better for ddd/dd4hep
  Geometry/CSCGeometry/test/testCSCGeometry_cfg.py
  Geometry/GEMGeometryBuilder/plugins/GEMGeometryESModule.cc
  Geometry/GEMGeometryBuilder/plugins/ME0GeometryESModule.cc
  Geometry/GEMGeometryBuilder/python/gemGeometry_cff.py
  Geometry/GEMGeometryBuilder/python/gemGeometry_cfi.py
  Geometry/GEMGeometryBuilder/python/me0Geometry_cff.py
  Geometry/GEMGeometryBuilder/python/me0Geometry_cfi.py
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.cc
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.h
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromCondDB.cc
  Geometry/GEMGeometryBuilder/test/python/validateGEMGeometry2_cfg.py
  Geometry/GEMGeometryBuilder/test/python/validateGEMGeometry_cfg.py
  Geometry/GEMGeometryBuilder/test/python/validateME0GeometryDD4hep_cfg.py
  Geometry/GEMGeometryBuilder/test/python/validateME0GeometryOldDD_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30050 Initialize FileBlob data members
  CondFormats/Common/interface/FileBlob.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30067 reduced boost use in PhysicsTools/Utilities
  PhysicsTools/Utilities/interface/Factorize.h
  PhysicsTools/Utilities/interface/Fraction.h
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30084 Move Alignment DQM modules back to Sequences
  DQMOffline/Alignment/python/ALCARECOTkAlDQM_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#29946 Minor changes in beampixel_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30039 add packages used by headers in CondFormats
  CondFormats/BeamSpotObjects/BuildFile.xml
  CondFormats/RecoMuonObjects/BuildFile.xml
Labels: alca-pending, code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, tests-rejected

#30064 Fix bug affecting boosted tau isolation
  RecoJets/JetProducers/plugins/BoostedTauSeedsProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30088 Adding new R9 plots to ECAL
  DQM/EcalMonitorTasks/python/ClusterTask_cfi.py
  DQM/EcalMonitorTasks/src/ClusterTask.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30065 Fix bug affecting boosted tau isolation (11_1_X)
  RecoJets/JetProducers/plugins/BoostedTauSeedsProducer.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30077 [Tracker Alignment] All-in-one tool support of multiple tags in user-inputed sqlite file
  Alignment/OfflineValidation/python/TkAlAllInOneTool/helperFunctions.py
  Alignment/OfflineValidation/test/test_all.sh
Labels: alca-pending, bug-fix, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#30078 11.1.X [Tracker Alignment] All-in-one tool support of multiple tags in user-inputed sqlite file
  Alignment/OfflineValidation/python/TkAlAllInOneTool/helperFunctions.py
  Alignment/OfflineValidation/test/test_all.sh
Labels: alca-pending, backport, bug-fix, comparison-available, orp-approved, pending-signatures, tests-approved

#30076 Move DT calibration DQM modules back to Sequence
  CalibMuon/DTCalibration/python/ALCARECODtCalib_cff.py
  DQM/DTMonitorModule/python/ALCARECODTCalibSynchCosmicsDQM_cff.py
  DQM/DTMonitorModule/python/ALCARECODTCalibSynchDQM_cff.py
  DQM/DTMonitorModule/python/ALCARECODTCalibSynchHIDQM_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved, urgent

#30017 Allow running PUPPI v14 customizer on data
  CommonTools/PileupAlgos/python/customizePuppiTune_cff.py
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30083 Move SiStrip calibration DQM modules back to Sequence
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalZeroBiasHI_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalZeroBias_cff.py
  DQM/SiStripMonitorClient/python/SiStripSourceConfigTier0_HeavyIons_cff.py
  DQM/SiStripMonitorClient/python/SiStripSourceConfigTier0_cff.py
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalMinBiasDQMHI_cff.py
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalMinBiasDQM_cff.py
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalZeroBiasDQMHI_cff.py
  DQMOffline/CalibTracker/python/ALCARECOSiStripCalZeroBiasDQM_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30092 fix cmssw patch version for non-standard IBs e.g ROOT6, DEVEL
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29952 [DD4HEP] common and muon alignment DD4HEP migration
  Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorAsAnalyzer.cc
  Alignment/CommonAlignmentProducer/BuildFile.xml
  Alignment/CommonAlignmentProducer/interface/AlignmentProducerBase.h
  Alignment/CommonAlignmentProducer/plugins/AlignmentProducer.cc
  Alignment/CommonAlignmentProducer/plugins/AlignmentProducer.h
  Alignment/CommonAlignmentProducer/python/AlignmentProducerAsAnalyzer_cff.py
  Alignment/CommonAlignmentProducer/python/AlignmentProducer_cff.py
  Alignment/CommonAlignmentProducer/src/AlignmentProducerBase.cc
  Alignment/MuonAlignment/interface/MuonAlignmentInputDB.h
  Alignment/MuonAlignment/interface/MuonAlignmentInputMethod.h
  Alignment/MuonAlignment/interface/MuonAlignmentInputSurveyDB.h
  Alignment/MuonAlignment/interface/MuonAlignmentInputXML.h
  Alignment/MuonAlignment/interface/MuonAlignmentOutputXML.h
  Alignment/MuonAlignment/plugins/BuildFile.xml
  Alignment/MuonAlignment/plugins/MuonGeometryArrange.cc
  Alignment/MuonAlignment/plugins/MuonGeometryArrange.h
  Alignment/MuonAlignment/plugins/MuonGeometryDBConverter.cc
  Alignment/MuonAlignment/plugins/MuonMisalignedProducer.cc
  Alignment/MuonAlignment/python/MisalignedMuon_cfi.py
  Alignment/MuonAlignment/python/convertSQLitetoXML_cfg.py
  Alignment/MuonAlignment/python/convertXMLtoSQLite_cfg.py
  Alignment/MuonAlignment/python/convertXMLtoXML_cfg.py
  Alignment/MuonAlignment/src/MuonAlignmentInputDB.cc
  Alignment/MuonAlignment/src/MuonAlignmentInputMethod.cc
  Alignment/MuonAlignment/src/MuonAlignmentInputSurveyDB.cc
  Alignment/MuonAlignment/src/MuonAlignmentInputXML.cc
  Alignment/MuonAlignment/src/MuonAlignmentOutputXML.cc
  Alignment/MuonAlignment/test/MuonGeometryArrange.py
  Alignment/MuonAlignment/test/TestReader.cpp
  Alignment/MuonAlignment/test/muonGeometryDBConverter_cfg.py
  Alignment/MuonAlignment/test/test-db-read_cfg.py
  Alignment/MuonAlignment/test/test-misalign_cfg.py
  Geometry/CommonTopologies/interface/GeometryAligner.h
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30101 Add a plugin that can depend on any product
  FWCore/Modules/src/GenericConsumer.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30096 Add GEM to MuonRecoAnalyzer
  DQMOffline/Muon/interface/MuonRecoAnalyzer.h
  DQMOffline/Muon/python/muonRecoAnalyzer_cfi.py
  DQMOffline/Muon/src/MuonRecoAnalyzer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30066 Fix bug affecting boosted tau isolation (10_6_X)
  RecoJets/JetProducers/plugins/BoostedTauSeedsProducer.cc
  RecoTauTag/Configuration/python/boostedHPSPFTaus_cff.py
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30073 Fixing missing pointer between lumi boundaries [Backport]
  GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.cc
Labels: comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#30086 Move calorimeter calibration DQM modules back to Sequences
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalHO_cff.py
  Configuration/StandardSequences/python/AlCaRecoStream_SpecialsHI_cff.py
  Configuration/StandardSequences/python/AlCaRecoStream_Specials_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreamsHeavyIons_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, tests-approved

#30087 Move EDProducers in HLT tracking validation sequences to Tasks
  Configuration/StandardSequences/python/Validation_cff.py
  FastSimulation/Validation/test/TrackRecoAndValidation_FullSim_cfg.py
  FastSimulation/Validation/test/TrackRecoAndValidation_cfg.py
  HLTriggerOffline/Egamma/python/HLTmultiTrackValidatorGsfTracks_cff.py
  HLTriggerOffline/Muon/python/HLTmultiTrackValidatorMuonTracks_cff.py
  Validation/Configuration/python/globalValidation_cff.py
  Validation/RecoMuon/python/RelValCustoms.py
  Validation/RecoTrack/python/HLTmultiTrackValidator_cff.py
  Validation/RecoTrack/python/TrackValidation_cff.py
  Validation/RecoVertex/python/HLTmultiPVvalidator_cff.py
  Validation/TrackerConfiguration/test/ValidationChainOnly_cfg.py
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, fastsim-pending, operations-approved, orp-approved, pending-signatures, simulation-pending, tests-approved, urgent

#30089 Move EDProducers from Sequences to Tasks in L1T DQM and Validation configurations
  DQM/L1TMonitor/python/L1TEmulatorMonitor_cff.py
  DQM/L1TMonitor/python/L1TMonitor_cff.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_cff.py
  L1Trigger/Configuration/python/ValL1Emulator_cff.py
  L1Trigger/HardwareValidation/python/L1HardwareValidation_cff.py
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, l1-pending, orp-approved, pending-signatures, tests-approved, urgent

#30041 Drop DtCalib AlCaReco Stream
  Configuration/AlCa/python/autoAlca.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaRecoStreamsHeavyIons_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, code-checks-approved, comparison-available, operations-approved, orp-approved, pdmv-pending, pending-signatures, tests-approved, upgrade-approved

#30090 Fix in popcon workflow: handling of empty files
  CondCore/PopCon/src/PopCon.cc
  CondCore/Utilities/python/popcon2dropbox.py
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30075 Replaced boost for stl alternatives in TrackingTools/TrajectoryCleaning
  TrackingTools/TrajectoryCleaning/src/OtherHashMaps.h
  TrackingTools/TrajectoryCleaning/src/TrajectoryCleanerBySharedHits.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30069 Removed usage of DDVectorGetter from production code
  DetectorDescription/Core/interface/DDCompactView.h
  DetectorDescription/Core/interface/DDExpandedView.h
  DetectorDescription/Core/interface/DDFilteredView.h
  DetectorDescription/Core/interface/DDVectorGetter.h
  DetectorDescription/Core/src/DDCompactView.cc
  DetectorDescription/Core/src/DDExpandedView.cc
  DetectorDescription/RegressionTest/test/const_dump.cpp
  Geometry/HGCalCommonData/src/HGCalGeomParameters.cc
  Geometry/HcalCommonData/src/HcalGeomParameters.cc
  Geometry/HcalCommonData/src/HcalParametersFromDD.cc
  Geometry/MTDGeometryBuilder/src/MTDParametersFromDD.cc
  Geometry/MTDNumberingBuilder/plugins/MTDGeometricTimingDetESModule.cc
  Geometry/TrackerGeometryBuilder/src/TrackerParametersFromDD.cc
  Geometry/TrackerNumberingBuilder/plugins/TrackerGeometricDetESModule.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30105 Add ECAL-only workflows for 2018 data
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#30082 Remove redundant product validity check from ConversionTrackProducer and modernize it
  RecoEgamma/EgammaPhotonProducers/interface/ConversionTrackProducer.h
  RecoEgamma/EgammaPhotonProducers/src/ConversionTrackProducer.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30110 Removed boost dependency in RecoLocalMuon/DTSegment
  RecoLocalMuon/DTSegment/src/DTCombinatorialPatternReco.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30116 Avoid similar file names in DPGAnalysis/HcalTools
  DPGAnalysis/HcalTools/scripts/cmt/Readme2
Labels: code-checks-approved, comparison-pending, dqm-approved, fully-signed, orp-approved, tests-started

#30097 Fix for the recently updated HI event content
  Configuration/EventContent/python/EventContentHeavyIons_cff.py
  RecoHI/Configuration/python/RecoHI_EventContent_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved

#30094 Move EDProducers to Task from electron MiniAOD validation sequence
  Configuration/StandardSequences/python/Validation_cff.py
  Validation/RecoEgamma/python/electronValidationSequenceMiniAOD_cff.py
  Validation/RecoEgamma/python/photonMiniAODValidationSequence_cff.py
Labels: bug-fix, code-checks-approved, comparison-available, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved, urgent

#30113 Changed legacy modules in L1Trigger/TrackTrigger
  L1Trigger/TrackTrigger/plugins/TTClusterBuilder.h
  L1Trigger/TrackTrigger/plugins/TTStubBuilder.h
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#30058 [Phase2 Pixel3D digitizer] add new histos and fix entry angles for tracks to test beam validator
  SimTracker/SiPhase2Digitizer/python/PixelTestBeamValidation_cfi.py
  SimTracker/SiPhase2Digitizer/test/PixelTestBeamValidation.cc
  SimTracker/SiPhase2Digitizer/test/PixelTestBeamValidation.h
  SimTracker/SiPhase2Digitizer/test/PixelTestBeamValidator_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#30102 WireDigi container in ALCT
  DataFormats/CSCDigi/interface/CSCALCTDigi.h
  DataFormats/CSCDigi/src/CSCALCTDigi.cc
  DataFormats/CSCDigi/src/classes_def.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30134 Geant4 hyperon physics initialisation
  SimG4Core/PhysicsLists/interface/CMSHyperonFTFPBuilder.h
  SimG4Core/PhysicsLists/src/CMSHadronPhysicsFTFP_BERT.cc
  SimG4Core/PhysicsLists/src/CMSHyperonFTFPBuilder.cc
  SimG4Core/PhysicsLists/src/HadronPhysicsQGSPCMS_FTFP_BERT.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30125 DD4hep: SimTracker/TrackerMaterialAnalysis Migrated plugin Test
  SimTracker/TrackerMaterialAnalysis/data/dd4hep_trackingMaterialGroups.xml
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_TrackingMaterialAnalyser.cc
  SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_TrackingMaterialAnalyser.h
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseII_dd4hep_cff.py
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseII_dd4hep_cfi.py
  SimTracker/TrackerMaterialAnalysis/test/TrackingMaterialAnalyser.py
  SimTracker/TrackerMaterialAnalysis/test/listIds_dd4hep.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30132 Update offline GT for Run 1 and Run 2 data, including special runs. [10_6_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#30131 Update offline GT for Run 1 and Run 2 data, including special runs. [11_0_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#30141 Import ClusterShapeHitFilterESProducer_cfi explicitly in SiPixelPhase1OfflineDQM_source_cff
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OfflineDQM_source_cff.py
Labels: code-checks-approved, comparison-available, dqm-pending, orp-approved, pending-signatures, tests-approved

#30068 replace boost::hash for std::hash
  CondCore/CondDB/interface/Types.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30146 Add edm::Principal::getByToken to skipped functions regex
  Utilities/StaticAnalyzers/scripts/statics.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30063 MTD reco geometry: revision of DetLayers verbosity and test
  Geometry/MTDGeometryBuilder/test/MTDDigiGeometryAnalyzer.cc
  RecoMTD/DetLayers/plugins/BTLDetLayerGeometryBuilder.cc
  RecoMTD/DetLayers/plugins/ETLDetLayerGeometryBuilder.cc
  RecoMTD/DetLayers/plugins/MTDDetLayerGeometryESProducer.cc
  RecoMTD/DetLayers/src/MTDDetRing.cc
  RecoMTD/DetLayers/src/MTDDetTray.cc
  RecoMTD/DetLayers/src/MTDRingForwardDoubleLayer.cc
  RecoMTD/DetLayers/src/MTDRingForwardLayer.cc
  RecoMTD/DetLayers/src/MTDTrayBarrelLayer.cc
  RecoMTD/DetLayers/test/MTDRecoGeometryAnalyzer.cc
  RecoMTD/DetLayers/test/mtd_cfg.py
  RecoMTD/DetLayers/test/testRecoGeometry.cfg
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#30156 added esConsumes to modules in SimMuonCSCDigitizer
  SimMuon/CSCDigitizer/plugins/CSCChamberMasker.cc
  SimMuon/CSCDigitizer/src/CSCDbStripConditions.cc
  SimMuon/CSCDigitizer/src/CSCDigiProducer.cc
  SimMuon/CSCDigitizer/src/CSCDigiProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30124 make DetStatus a stream module
  DPGAnalysis/Skims/interface/DetStatus.h
  DPGAnalysis/Skims/src/DetStatus.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, pdmv-approved, tests-approved

#30108 Run3-alca167 Update the analyzer to study low luminosity collision data
  Calibration/IsolatedParticles/plugins/StudyCaloResponse.cc
  Calibration/IsolatedParticles/plugins/StudyTriggerHLT.cc
  Calibration/IsolatedParticles/test/proto_runStudyCaloResponse_cfg.py
  Calibration/IsolatedParticles/test/proto_runStudyTriggerHLT_cfg.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30079 Phase2-hgx242 First step to use ASCII file due to Philippe and Katja to define HGCal geometry
  Geometry/HGCalCommonData/interface/HGCalDDDConstants.h
  Geometry/HGCalCommonData/interface/HGCalGeomTools.h
  Geometry/HGCalCommonData/interface/HGCalTypes.h
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalCommonData/src/HGCalGeomTools.cc
  Geometry/HGCalCommonData/src/HGCalWaferMask.cc
  Geometry/HGCalCommonData/test/BuildFile.xml
  Geometry/HGCalCommonData/test/HGCalConvert.cpp
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30051 EMTF: Prevent out-of-bounds access in BDT event data
  L1Trigger/L1TMuonEndCap/src/bdt/Node.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#30106 fix direct access to tau ID container
  PhysicsTools/PatAlgos/plugins/PATTauProducer.cc
  Validation/RecoTau/src/TauTagValidation.cc
Labels: analysis-pending, bug-fix, code-checks-approved, comparison-available, dqm-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#30048 Removed boost::uit64_t , they are now built-in c++
  CondCore/Utilities/bin/cmscond_from_lumiid.cpp
Labels: code-checks-approved, comparison-available, db-pending, orp-approved, pending-signatures, tests-approved

#30151 Updated L1T tags to address CMSSW issue #29237
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30152 Run3-hcx260 Update the material budget study code for HCAL
  Validation/Geometry/interface/MaterialBudgetHcal.h
  Validation/Geometry/interface/MaterialBudgetHcalHistos.h
  Validation/Geometry/src/MaterialBudgetHcal.cc
  Validation/Geometry/src/MaterialBudgetHcalHistos.cc
  Validation/Geometry/test/runP_HCAL_Debug_cfg.py
  Validation/Geometry/test/runP_HCAL_cfg.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#30135 [DD4hep] Allow Assembly Registration in the Namespace
  DetectorDescription/DDCMS/interface/DDNamespace.h
  DetectorDescription/DDCMS/interface/DDParsingContext.h
  DetectorDescription/DDCMS/src/DDNamespace.cc
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalPreshowerAlgo.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30060 Hcal calibration cache
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalCalo/Configuration/python/RecoLocalCalo_Cosmics_cff.py
  RecoLocalCalo/Configuration/python/hcalLocalReco_cff.py
  RecoLocalCalo/HcalRecAlgos/interface/HFPreRecAlgo.h
  RecoLocalCalo/HcalRecAlgos/interface/HcalChannelProperties.h
  RecoLocalCalo/HcalRecAlgos/interface/HcalChannelPropertiesAuxRecord.h
  RecoLocalCalo/HcalRecAlgos/interface/HcalChannelPropertiesRecord.h
  RecoLocalCalo/HcalRecAlgos/interface/HcalPipelinePedestalAndGain.h
  RecoLocalCalo/HcalRecAlgos/plugins/HcalChannelPropertiesEP.cc
  RecoLocalCalo/HcalRecAlgos/python/hcalChannelPropertiesESProd_cfi.py
  RecoLocalCalo/HcalRecAlgos/src/HFPreRecAlgo.cc
  RecoLocalCalo/HcalRecAlgos/src/HcalChannelPropertiesAuxRecord.cc
  RecoLocalCalo/HcalRecAlgos/src/HcalChannelPropertiesRecord.cc
  RecoLocalCalo/HcalRecAlgos/src/HcalChannelPropertiesVec.cc
  RecoLocalCalo/HcalRecProducers/src/HBHEPhase1Reconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/HFPreReconstructor.cc
Labels: code-checks-approved, comparison-available, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#30175 [DB] Fixes needed for GCC 10
  CondCore/Utilities/interface/PayloadInspector.h
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#29995 adapt Pythia8Interface to pythia8 302 (PR cmsdist #5869, to be tested together)
  GeneratorInterface/Pythia8Interface/BuildFile.xml
  GeneratorInterface/Pythia8Interface/interface/BiasedTauDecayer.h
  GeneratorInterface/Pythia8Interface/interface/MultiUserHook.h
  GeneratorInterface/Pythia8Interface/interface/Py8InterfaceBase.h
  GeneratorInterface/Pythia8Interface/plugins/JetMatchingHook.cc
  GeneratorInterface/Pythia8Interface/plugins/JetMatchingHook.h
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/src/BiasedTauDecayer.cc
  GeneratorInterface/Pythia8Interface/test/pythia8ex13_cfg.py
  GeneratorInterface/Pythia8Interface/test/pythia8ex14_cfg.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#30173 [FASTSIM] Fixes needed for GCC 10
  FastSimulation/TrackingRecHitProducer/interface/PixelResolutionHistograms.h
Labels: code-checks-approved, comparison-available, fastsim-pending, orp-approved, pending-signatures, tests-approved

#30172 [ALCA] Fixes needed for GCC 10
  CondFormats/PPSObjects/src/PPSTimingCalibration.cc
Labels: alca-pending, code-checks-approved, comparison-available, orp-approved, pending-signatures, tests-approved

#30178 Drop ALCARECOEcalCalElectronCalibDQM
  DQMOffline/Configuration/python/ALCARECOEcalCalDQM_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30181 Reduce boost use in EventFilter/Utilities
  EventFilter/Utilities/plugins/RawEventFileWriterForBU.cc
  EventFilter/Utilities/plugins/RawEventFileWriterForBU.h
  EventFilter/Utilities/plugins/RawEventOutputModuleForBU.h
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30118 Run3 hcx259: Change names of classes which are not dependent on DDD/DD4Hep package
  Configuration/Geometry/python/GeometrySLHCSimDB_cff.py
  Configuration/Geometry/python/GeometrySimDB_cff.py
  FastSimulation/ShowerDevelopment/src/FastHFShowerLibrary.cc
  Geometry/HcalCommonData/interface/CaloSimulationConstants.h
  Geometry/HcalCommonData/interface/HcalSimulationConstants.h
  Geometry/HcalCommonData/plugins/CaloSimulationConstantsESModule.cc
  Geometry/HcalCommonData/plugins/HcalSimulationConstantsESModule.cc
  Geometry/HcalCommonData/python/hcalDDConstants_cff.py
  Geometry/HcalCommonData/python/hcalDDDSimConstants_cff.py
  Geometry/HcalCommonData/src/CaloDDDSimulationConstants.cc
  Geometry/HcalCommonData/src/CaloSimulationConstants.cc
  Geometry/HcalCommonData/src/ES_HcalDDDConstants.cc
  Geometry/HcalCommonData/src/HcalDDDSimulationConstants.cc
  Geometry/HcalCommonData/src/HcalSimulationConstants.cc
  SimG4CMS/Calo/interface/HCalSD.h
  SimG4CMS/Calo/src/HCalSD.cc
  SimG4CMS/ShowerLibraryProducer/src/FiberSD.cc
Labels: code-checks-approved, comparison-available, fastsim-approved, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#30179 Move creation of vector outside a loop to avoid useless (de)allocations
  RecoEgamma/EgammaElectronAlgos/src/PixelHitMatcher.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30170 [Phase2 3D digitizer] Fix digi links
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#30130 Replaced boost use in CalibFormats/SiStripObjects
  CalibFormats/SiStripObjects/BuildFile.xml
  CalibFormats/SiStripObjects/src/SiStripQuality.cc
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#29992 Allow InputTag and ESInputTag in a PSet to be assigned from a sequence of strings
  FWCore/ParameterSet/python/Mixins.py
  FWCore/ParameterSet/python/Types.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30122 Update of the CSC migration to DD4HEP
  Geometry/CSCGeometryBuilder/plugins/CSCGeometryESModule.cc
  Geometry/CSCGeometryBuilder/plugins/CSCGeometryESModule.h
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilderFromDDD.cc
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilderFromDDD.h
  Geometry/CSCGeometryBuilder/src/CSCGeometryParsFromDD.cc
  Geometry/CSCGeometryBuilder/src/CSCGeometryParsFromDD.h
  Geometry/CSCGeometryBuilder/test/python/validateCSCGeometryDD4hep_cfg.py
  Geometry/MuonNumbering/interface/DD4hep_CSCNumberingScheme.h
  Geometry/MuonNumbering/src/DD4hep_CSCNumberingScheme.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30190 Updated L1T tags to address CMSSW issue #29237 [11_1_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#30201 added esConsumes to modules in EventFilter/EcalDigiToRaw
  EventFilter/EcalDigiToRaw/src/EcalDigiToRaw.cc
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, tests-approved

#30196 Herwig7p2 mpi settings
  Configuration/Generator/python/Herwig7Settings/Herwig7CH2TuneSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7CH3TuneSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7_7p1SettingsFor7p2_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#30195 Updates to HCAL Run 3 conditions
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30164 Make mass replace work with proxy types
  FWCore/ParameterSet/python/MassReplace.py
  FWCore/ParameterSet/python/Mixins.py
  FWCore/ParameterSet/python/Types.py
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, requires-external, tests-started

#30138 HCAL Run3: removing redundant hbhereco=HBHEIsolatedNoiseReflagger from wf's
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Hcal/python/HcalDQMOfflineSequence_cff.py
  RecoJets/JetProducers/python/caloJetsForTrk_cff.py
  RecoLocalCalo/Configuration/python/hcalGlobalReco_cff.py
  RecoLocalCalo/Configuration/python/hcalLocalReco_cff.py
  Validation/HcalRecHits/python/hcalRecHitsValidationSequence_cff.py
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30197 added esConsumes to modules in SimMuon/DTDigitizer
  SimMuon/DTDigitizer/plugins/DTChamberMasker.cc
  SimMuon/DTDigitizer/src/DTDigitizer.cc
  SimMuon/DTDigitizer/src/DTDigitizer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30162 added esConsumes to modules in EventFilter/CastorRawToDigi
  EventFilter/CastorRawToDigi/plugins/CastorDigiToRaw.cc
  EventFilter/CastorRawToDigi/plugins/CastorDigiToRaw.h
  EventFilter/CastorRawToDigi/plugins/CastorRawToDigi.cc
  EventFilter/CastorRawToDigi/plugins/CastorRawToDigi.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30153 added esConsumes to modules in EventFilter/CSCRawToDigi
  EventFilter/CSCRawToDigi/plugins/CSCDCCUnpacker.cc
  EventFilter/CSCRawToDigi/plugins/CSCDCCUnpacker.h
  EventFilter/CSCRawToDigi/plugins/CSCDigiToRawModule.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiValidator.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiValidator.h
  EventFilter/CSCRawToDigi/plugins/module.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30202 Have Geometry/DTGeometryBuilder test ignore irrelevant diffs
  Geometry/DTGeometryBuilder/test/dtGeometry.log.org
  Geometry/DTGeometryBuilder/test/runTest.sh
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30203 Updated L1T tags to address CMSSW issue #29237 [11_0_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#30182 Removed unused ELmapDump() in FWCore/MessageLogger
  FWCore/MessageLogger/src/ELmap.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30183 Reduce boost dependency in IOPool/Streamer
  IOPool/Streamer/bin/BuildFile.xml
  IOPool/Streamer/bin/CalcAdler32.cpp
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30192 clean buildFile in Alignment/TwoBodyDecay
  Alignment/TwoBodyDecay/BuildFile.xml
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30222 Removed unused boost dependency in DQMOffline/RecoB
  DQMOffline/RecoB/BuildFile.xml
  DQMOffline/RecoB/src/MVAJetTagPlotter.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30220 Removed boost use in DQM/SiStripMonitorHardware
  DQM/SiStripMonitorHardware/BuildFile.xml
  DQM/SiStripMonitorHardware/src/SiStripFEDEmulator.cc
  DQM/SiStripMonitorHardware/src/SiStripSpyEventSummaryProducer.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30210 add missing dependencies to DataFormats/EgammaTrackReco
  DataFormats/EgammaTrackReco/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#29948 Changes to jet pileup subtraction
  RecoHI/HiJetAlgos/interface/MultipleAlgoIterator.h
  RecoHI/HiJetAlgos/interface/ParticleTowerProducer.h
  RecoHI/HiJetAlgos/plugins/ParticleTowerProducer.cc
  RecoHI/HiJetAlgos/plugins/plugins.cc
  RecoHI/HiJetAlgos/python/HiRecoPFJets_cff.py
  RecoHI/HiJetAlgos/python/ParticleTowerProducer_cfi.py
  RecoHI/HiJetAlgos/src/MultipleAlgoIterator.cc
  RecoHI/HiJetAlgos/src/ParametrizedSubtractor.cc
  RecoHI/HiJetAlgos/src/ParticleTowerProducer.cc
  RecoJets/JetProducers/plugins/VirtualJetProducer.cc
  RecoJets/JetProducers/src/PileUpSubtractor.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30225 Reduce boost dependency in GeneratorInterface/LHEInterface
  GeneratorInterface/LHEInterface/plugins/ExternalLHEAsciiDumper.cc
  GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc
  GeneratorInterface/LHEInterface/plugins/LHESource.cc
  GeneratorInterface/LHEInterface/src/LHEReader.cc
  GeneratorInterface/LHEInterface/src/LHERunInfo.cc
Labels: code-checks-approved, comparison-available, fully-signed, generators-approved, orp-approved, tests-approved

#30223 add missing dependencies to SimDataFormats packages
  SimDataFormats/Associations/BuildFile.xml
  SimDataFormats/EcalTestBeam/BuildFile.xml
  SimDataFormats/RPCDigiSimLink/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30226 Reduce boost dependency in PerfTools/EdmEvent
  PerfTools/EdmEvent/src/EdmEventSize.cc
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30147 drop type specs in RecoLocalCalo and RecoLocalTracker
  RecoLocalCalo/HGCalRecProducers/python/HGCalRecHit_cfi.py
  RecoLocalCalo/HGCalRecProducers/python/hgcalLayerClusters_cff.py
  RecoLocalCalo/HcalRecAlgos/python/hcalRecAlgoESProd_cfi.py
  RecoLocalCalo/HcalRecProducers/python/HBHEIsolatedNoiseReflagger_cfi.py
  RecoLocalCalo/HcalRecProducers/python/HBHEPhase1Reconstructor_cfi.py
  RecoLocalTracker/Phase2TrackerRecHits/python/Phase2StripCPEGeometricESProducer_cfi.py
  RecoLocalTracker/SiStripClusterizer/python/SiStripClusterizer_RealData_cfi.py
  RecoLocalTracker/SiStripRecHitConverter/python/StripCPE_cfi.py
  RecoLocalTracker/SiStripRecHitConverter/python/StripCPEfromTrackAngle_cfi.py
  RecoLocalTracker/SiStripRecHitConverter/python/StripCPEgeometric_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#30224 Cleaned build file in DataFormats/EcalDigi/test
  DataFormats/EcalDigi/test/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30231 [RECONSTRUCTION] Fixes needed for UBSAN
  RecoLocalCalo/HcalRecAlgos/plugins/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30221 Modified conditions to fix incorrect HLT JEC
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30233 Updates to HCAL Run 3 conditions [11_1_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, comparison-available, fully-signed, orp-approved, tests-approved

#30232 [GEOMETRY] Fixes needed for UBSAN
  Geometry/EcalAlgo/test/EcalPreshowerParameterDump.cc
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved

#30235 Reduce boost dependency in RecoBTag/ImpactParameter
  RecoBTag/ImpactParameter/plugins/BuildFile.xml
  RecoBTag/ImpactParameter/plugins/IPProducer.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30244 Reduce boost dependency in RecoTracker/MeasurementDet
  RecoTracker/MeasurementDet/plugins/TkGluedMeasurementDet.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30239 Reduce boost use in RecoLocalTracker/SiStripRecHitConverter
  RecoLocalTracker/SiStripRecHitConverter/interface/SiStripRecHitMatcher.h
  RecoLocalTracker/SiStripRecHitConverter/src/SiStripRecHitMatcher.cc
  RecoLocalTracker/SiStripRecHitConverter/src/StripCPE.cc
  RecoLocalTracker/SiStripRecHitConverter/src/VVIObj.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30246 Reduce boost dependency in RecoTracker/TkDetLayers
  RecoTracker/TkDetLayers/src/CompositeTECPetal.cc
  RecoTracker/TkDetLayers/src/CompositeTECWedge.cc
  RecoTracker/TkDetLayers/src/GeometricSearchTrackerBuilder.cc
  RecoTracker/TkDetLayers/src/Phase2EndcapRing.cc
  RecoTracker/TkDetLayers/src/TIDRing.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30241 Reduce boost dependency in RecoTauTag/RecoTau
  RecoTauTag/RecoTau/plugins/RecoTauGenericJetRegionProducer.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroStripPlugin.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroStripPlugin2.cc
  RecoTauTag/RecoTau/plugins/RecoTauPiZeroStripPlugin3.cc
  RecoTauTag/RecoTau/plugins/RecoTauProducer.cc
  RecoTauTag/RecoTau/plugins/TauDiscriminantCutMultiplexer.cc
  RecoTauTag/RecoTau/src/RecoTauVertexAssociator.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30166 added esConsumes to modules in EventFilter/DTRawToDigi
  EventFilter/DTRawToDigi/plugins/DTDigiToRawModule.cc
  EventFilter/DTRawToDigi/plugins/DTDigiToRawModule.h
  EventFilter/DTRawToDigi/plugins/DTUnpackingModule.cc
  EventFilter/DTRawToDigi/plugins/DTUnpackingModule.h
  EventFilter/DTRawToDigi/plugins/DTuROSDigiToRaw.cc
  EventFilter/DTRawToDigi/plugins/DTuROSDigiToRaw.h
  EventFilter/DTRawToDigi/plugins/DTuROSRawToDigi.cc
  EventFilter/DTRawToDigi/plugins/DTuROSRawToDigi.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30206 DAQ: support for FRD file header with file locking
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/src/EvFDaqDirector.cc
  EventFilter/Utilities/src/FedRawDataInputSource.cc
Labels: code-checks-approved, comparison-available, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30061 Use HGCalRecHitMapProducer
  DataFormats/HGCRecHit/src/classes_def.xml
  Fireworks/Calo/interface/FWHeatmapProxyBuilderTemplate.h
  Fireworks/Calo/plugins/FWCaloClusterProxyBuilder.cc
  Fireworks/Calo/plugins/FWHGCalMultiClusterProxyBuilder.cc
  Fireworks/SimData/plugins/FWCaloParticleProxyBuilder.cc
  RecoEgamma/EgammaTools/interface/EgammaPCAHelper.h
  RecoEgamma/EgammaTools/interface/HGCalEgammaIDHelper.h
  RecoEgamma/EgammaTools/plugins/HGCalElectronIDValueMapProducer.cc
  RecoEgamma/EgammaTools/plugins/HGCalPhotonIDValueMapProducer.cc
  RecoEgamma/EgammaTools/python/slimmedEgammaFromMultiCl_cff.py
  RecoEgamma/EgammaTools/src/EgammaPCAHelper.cc
  RecoEgamma/EgammaTools/src/HGCalEgammaIDHelper.cc
  RecoLocalCalo/Configuration/python/hgcalLocalReco_cff.py
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalRecHitMapProducer.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/LayerClusterAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/LayerClusterAssociatorByEnergyScoreImpl.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/LayerClusterAssociatorByEnergyScoreProducer.cc
  SimCalorimetry/HGCalSimProducers/python/hgcHitAssociation_cfi.py
  Validation/Configuration/python/hgcalSimValid_cff.py
  Validation/HGCalValidation/interface/HGCalValidator.h
  Validation/HGCalValidation/interface/HGVHistoProducerAlgo.h
  Validation/HGCalValidation/plugins/CaloParticleValidation.cc
  Validation/HGCalValidation/plugins/HGCalShowerSeparation.cc
  Validation/HGCalValidation/plugins/HGCalValidator.cc
  Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved, visualization-approved

#30247 Make CSC{AL,CL}CTDigi::getHits() to return by const reference instead of a copy
  DataFormats/CSCDigi/interface/CSCALCTDigi.h
  DataFormats/CSCDigi/interface/CSCCLCTDigi.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30249 Improve Pixel Templates Payload Inspector messages
  CondCore/SiPixelPlugins/interface/SiPixelPayloadInspectorHelper.h
  CondCore/SiPixelPlugins/plugins/SiPixelTemplateDBObject_PayloadInspector.cc
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30219 Reduce boost dependency in CondFormats/SiStripObjects
  CondFormats/SiStripObjects/interface/SiStripBaseDelay.h
  CondFormats/SiStripObjects/src/SiStripBaseDelay.cc
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30250 Reduce boost dependency in DQM/CSCMonitorModule
  DQM/CSCMonitorModule/plugins/CSCDQM_Configuration.h
  DQM/CSCMonitorModule/plugins/CSCDQM_Dispatcher.cc
Labels: code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, tests-approved

#30218 Reduce boost dependency in CondCore/PopCon
  CondCore/PopCon/interface/PopCon.h
  CondCore/PopCon/interface/PopConSourceHandler.h
Labels: alca-approved, code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30139 Clean BuildFiles before DataFormats
  Alignment/APEEstimation/BuildFile.xml
  AnalysisAlgos/SiStripClusterInfoProducer/plugins/BuildFile.xml
  AnalysisAlgos/TrackInfoProducer/BuildFile.xml
  AnalysisAlgos/TrackInfoProducer/test/BuildFile.xml
  AnalysisDataFormats/EWK/BuildFile.xml
  AnalysisDataFormats/SUSYBSMObjects/BuildFile.xml
  AnalysisDataFormats/TopObjects/BuildFile.xml
  AnalysisDataFormats/TrackInfo/BuildFile.xml
  CalibTracker/SiStripCommon/interface/ShallowClustersProducer.h
  CalibTracker/SiStripCommon/plugins/SealModules.cc
  CalibTracker/SiStripCommon/plugins/ShallowClustersProducer.cc
  CalibTracker/SiStripHitEfficiency/src/HitEff.cc
  CaloOnlineTools/HcalOnlineDb/BuildFile.xml
  CaloOnlineTools/HcalOnlineDb/plugins/BuildFile.xml
  CommonTools/Clustering1D/test/BuildFile.xml
  CommonTools/MVAUtils/plugins/BuildFile.xml
  CommonTools/PileupAlgos/BuildFile.xml
  CommonTools/RecoAlgos/BuildFile.xml
  CommonTools/RecoAlgos/plugins/BuildFile.xml
  CommonTools/RecoUtils/BuildFile.xml
  CommonTools/Utils/plugins/BuildFile.xml
  CondCore/PopCon/BuildFile.xml
  CondCore/SiPixelPlugins/BuildFile.xml
  CondTools/DQM/BuildFile.xml
  Configuration/Skimming/BuildFile.xml
  DPGAnalysis/HcalTools/BuildFile.xml
  DPGAnalysis/SiStripTools/plugins/BuildFile.xml
  DPGAnalysis/Skims/BuildFile.xml
  DQM/SiOuterTracker/BuildFile.xml
  DQM/SiOuterTracker/interface/OuterTrackerMonitorTTCluster.h
  DQM/SiOuterTracker/interface/OuterTrackerMonitorTTStub.h
  DQM/SiOuterTracker/interface/OuterTrackerMonitorTTTrack.h
  DQM/SiOuterTracker/plugins/OuterTrackerMonitorTTCluster.cc
  DQM/SiOuterTracker/plugins/OuterTrackerMonitorTTStub.cc
  DQM/SiOuterTracker/plugins/OuterTrackerMonitorTTTrack.cc
  DQM/TrackingMonitorSource/interface/StandaloneTrackMonitor.h
  DQM/TrackingMonitorSource/plugins/StandaloneTrackMonitor.cc
  DQMServices/Core/BuildFile.xml
  EgammaAnalysis/ElectronTools/BuildFile.xml
  EgammaAnalysis/ElectronTools/plugins/BuildFile.xml
  ElectroWeakAnalysis/Utilities/BuildFile.xml
  ElectroWeakAnalysis/WENu/BuildFile.xml
  ElectroWeakAnalysis/WMuNu/BuildFile.xml
  ElectroWeakAnalysis/WMuNu/bin/BuildFile.xml
  ElectroWeakAnalysis/ZEE/BuildFile.xml
  ElectroWeakAnalysis/ZMuMu/bin/BuildFile.xml
Labels: alca-approved, analysis-approved, code-checks-approved, comparison-available, db-approved, dqm-approved, fully-signed, orp-approved, pdmv-approved, reconstruction-approved, tests-approved

#30180 Improvements to SiStrip Payload Inspector
  CondCore/SiStripPlugins/plugins/SiStripLorentzAngle_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripNoises_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripPedestals_PayloadInspector.cc
  CondCore/SiStripPlugins/test/test.sh
  CondCore/SiStripPlugins/test/testNoisePayloadInspector.sh
  CondCore/SiStripPlugins/test/testPedestalsPayloadInspector.sh
  CondCore/SiStripPlugins/test/testSiStripPayloadInspector.cpp
Labels: code-checks-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30214 Generate 2021 Scenario Automatically
  Configuration/Geometry/python/GeometryExtended2021Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2021_cff.py
  Configuration/Geometry/python/dict2021Geometry.py
  Configuration/Geometry/scripts/generate2021Geometry.py
  Configuration/Geometry/test/runtests.sh
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30121 Update of the RPC migration to DD4hep
  Geometry/MuonNumbering/interface/DD4hep_RPCNumberingScheme.h
  Geometry/MuonNumbering/src/DD4hep_RPCNumberingScheme.cc
  Geometry/RPCGeometry/python/rpcGeometryInMTCC_cfi.py
  Geometry/RPCGeometry/python/rpcGeometry_cfi.py
  Geometry/RPCGeometryBuilder/plugins/RPCGeometryESModule.cc
  Geometry/RPCGeometryBuilder/plugins/RPCGeometryESModule.h
  Geometry/RPCGeometryBuilder/python/rpcGeometryDB_cfi.py
  Geometry/RPCGeometryBuilder/python/rpcGeometry_cfi.py
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilder.cc
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilder.h
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilderFromCondDB.cc
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilderFromCondDB.h
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilderFromDDD.h
  Geometry/RPCGeometryBuilder/test/python/validateRPCGeometry_cfg.py
  RecoLocalMuon/GEMRecHit/test/SingleMuPt100_cfi_GEM-SIM-DIGI_Extended2015MuonGEMDev.py
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#30211 add missing dependency to SimDataFormats/GEMDigiSimLink
  SimDataFormats/GEMDigiSimLink/BuildFile.xml
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#30194 [Payload Inspector] Remove PY3 check as boost will be built with python3
  CondCore/AlignmentPlugins/test/BuildFile.xml
  CondCore/HLTPlugins/test/BuildFile.xml
  CondCore/RunInfoPlugins/test/BuildFile.xml
  CondCore/SiPixelPlugins/test/BuildFile.xml
  CondCore/SiPixelPlugins/test/testSiPixelPayloadInspector.cpp
  CondCore/SiStripPlugins/test/BuildFile.xml
  CondCore/SiStripPlugins/test/testSiStripPayloadInspector.cpp
  CondCore/Utilities/test/BuildFile.xml
Labels: code-checks-approved, comparison-pending, db-approved, fully-signed, hlt-approved, orp-approved, requires-external, tests-rejected

#30261 Cleaning build files in Alignment
  Alignment/CommonAlignment/BuildFile.xml
  Alignment/LaserAlignment/plugins/BuildFile.xml
  Alignment/LaserAlignmentSimulation/plugins/BuildFile.xml
  Alignment/LaserAlignmentSimulation/test/BuildFile.xml
  Alignment/LaserDQM/plugins/BuildFile.xml
  Alignment/OfflineValidation/plugins/BuildFile.xml
  Alignment/OfflineValidation/plugins/MuonAlignmentAnalyzer.cc
  Alignment/SurveyAnalysis/test/TestConverter.cpp
  Alignment/SurveyAnalysis/test/TestConverter2.cpp
Labels: alca-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30238 Fix in PopCon worklow for empy files + DBOuputService clean up: back-port
  CondCore/DBOutputService/BuildFile.xml
  CondCore/DBOutputService/interface/PoolDBOutputService.h
  CondCore/DBOutputService/src/PoolDBOutputService.cc
  CondCore/DBOutputService/test/BuildFile.xml
  CondCore/PopCon/src/PopCon.cc
  CondCore/Utilities/python/popcon2dropbox.py
Labels: alca-approved, comparison-available, db-approved, fully-signed, orp-approved, tests-approved

#30229 Reduce boost dependency in PhysicsTools/TagAndProbe
  PhysicsTools/TagAndProbe/interface/BaseTreeFiller.h
  PhysicsTools/TagAndProbe/plugins/ProbeTreeProducer.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30227 Reduce boost dependency in PhysicsTools/MVAComputer
  PhysicsTools/MVAComputer/interface/MVAModuleHelper.h
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30191 Reduce boost dependency in AnalysisAlgos/SiStripClusterInfoProducer
  AnalysisAlgos/SiStripClusterInfoProducer/plugins/SiStripProcessedRawDigiProducer.cc
Labels: analysis-approved, code-checks-approved, comparison-available, fully-signed, orp-approved, tests-approved

#30071 skip complicated checks for PFCandidate-on-PFCandidate TopProjector
  CommonTools/ParticleFlow/plugins/TopProjector.h
  CommonTools/ParticleFlow/python/TopProjectors/pfNoElectron_cfi.py
  CommonTools/ParticleFlow/python/TopProjectors/pfNoJet_cfi.py
  CommonTools/ParticleFlow/python/TopProjectors/pfNoMuon_cfi.py
  CommonTools/ParticleFlow/python/TopProjectors/pfNoPileUp_cfi.py
  CommonTools/ParticleFlow/python/TopProjectors/pfNoTau_cfi.py
  PhysicsTools/PatAlgos/python/tools/helpers.py
  PhysicsTools/PatAlgos/test/patTuple_PF2PAT_cfg.py
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
  RecoMET/METFilters/test/filters_cfg.py
  Validation/RecoParticleFlow/Benchmarks/ElectronBenchmarkGeneric/benchmark_cfg.py
  Validation/RecoParticleFlow/test/pflowValidationStep1_Template_cfg.py
  Validation/RecoParticleFlow/test/pflowValidationStep1_cfg.py
  Validation/RecoParticleFlow/test/pflowValidationStep1_test_cfg.py
Labels: analysis-approved, code-checks-approved, comparison-available, dqm-approved, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#30207 Hcal event setup tokenize
  RecoLocalCalo/HcalRecAlgos/interface/HBHEStatusBitSetter.h
  RecoLocalCalo/HcalRecAlgos/plugins/HcalChannelPropertiesEP.cc
  RecoLocalCalo/HcalRecAlgos/plugins/HcalRecAlgoESProducer.cc
  RecoLocalCalo/HcalRecProducers/src/HBHEIsolatedNoiseReflagger.cc
  RecoLocalCalo/HcalRecProducers/src/HBHEIsolatedNoiseReflagger.h
  RecoLocalCalo/HcalRecProducers/src/HBHEPhase1Reconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/HBHEPlan1Combiner.cc
  RecoLocalCalo/HcalRecProducers/src/HFPhase1Reconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/HFPreReconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/HcalHitReconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/HcalHitReconstructor.h
  RecoLocalCalo/HcalRecProducers/src/HcalHitSelection.cc
  RecoLocalCalo/HcalRecProducers/src/HcalSimpleReconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/HcalSimpleReconstructor.h
  RecoLocalCalo/HcalRecProducers/src/ZdcHitReconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/ZdcHitReconstructor.h
  RecoLocalCalo/HcalRecProducers/src/ZdcSimpleReconstructor.cc
  RecoLocalCalo/HcalRecProducers/src/ZdcSimpleReconstructor.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30119 added esConsumes to modules in L1Trigger/TrackTrigger
  L1Trigger/TrackTrigger/plugins/TTClusterBuilder.cc
  L1Trigger/TrackTrigger/plugins/TTClusterBuilder.h
  L1Trigger/TrackTrigger/plugins/TTStubBuilder.cc
  L1Trigger/TrackTrigger/plugins/TTStubBuilder.h
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#30259 [Pixel 3D digitizer] Boundary row/col check in digitizer
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.cc
Labels: code-checks-approved, comparison-pending, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#30128 Update accessor in CLCT and LCT data formats
  DQM/CSCMonitorModule/plugins/CSCDQM_EventProcessor_processCSC.cc
  DQMOffline/Muon/interface/CSCOfflineMonitor.h
  DQMOffline/Muon/src/CSCOfflineMonitor.cc
  DataFormats/CSCDigi/interface/CSCCLCTDigi.h
  DataFormats/CSCDigi/src/CSCCLCTDigi.cc
  DataFormats/CSCDigi/src/CSCComparatorDigi.cc
  DataFormats/CSCDigi/src/CSCCorrelatedLCTDigi.cc
  EventFilter/CSCRawToDigi/interface/CSCComparatorData.h
  EventFilter/CSCRawToDigi/interface/CSCEventData.h
  EventFilter/CSCRawToDigi/interface/CSCTMBData.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader.h
  EventFilter/CSCRawToDigi/plugins/CSCDCCUnpacker.cc
  EventFilter/CSCRawToDigi/src/CSCComparatorData.cc
  EventFilter/CSCRawToDigi/src/CSCEventData.cc
  EventFilter/CSCRawToDigi/src/CSCTMBData.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader.cc
  EventFilter/CSCRawToDigi/test/cscRawToDigiTest.cpp
  EventFilter/CSCRawToDigi/test/csc_unpack_rundqm.cfg
  EventFilter/CSCRawToDigi/test/digiToPat.cfg
  EventFilter/CSCRawToDigi/test/dropper.cfg
  EventFilter/CSCRawToDigi/test/fuunpacker.cfg
  EventFilter/CSCRawToDigi/test/packer.cfg
  EventFilter/CSCRawToDigi/test/rawunpacker.cfg
  EventFilter/CSCRawToDigi/test/reunpacker.cfg
  EventFilter/CSCRawToDigi/test/stream.cfg
  EventFilter/CSCRawToDigi/test/unpacker.cfg
  EventFilter/CSCRawToDigi/test/validation_with_selective_unpacking.cfg
  RecoLocalMuon/CSCValidation/src/CSCValidation.cc
  RecoLocalMuon/CSCValidation/src/CSCValidation.h
Labels: code-checks-approved, comparison-pending, dqm-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#30213 HCAL - HB TDC digi default to non-packed
  EventFilter/HcalRawToDigi/plugins/HcalDigiToRawuHTR.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30167 Basic infrastructure for GEMs in CSC packer/unpacker
  EventFilter/CSCRawToDigi/BuildFile.xml
  EventFilter/CSCRawToDigi/interface/CSCEventData.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader.h
  EventFilter/CSCRawToDigi/interface/CSCViewDigi.h
  EventFilter/CSCRawToDigi/interface/DigiAnalyzer.h
  EventFilter/CSCRawToDigi/plugins/CSCDCCUnpacker.cc
  EventFilter/CSCRawToDigi/plugins/CSCDCCUnpacker.h
  EventFilter/CSCRawToDigi/plugins/CSCDigiToPattern.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiToRawModule.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiValidator.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiValidator.h
  EventFilter/CSCRawToDigi/plugins/CSCViewDigi.cc
  EventFilter/CSCRawToDigi/plugins/DigiAnalyzer.cc
  EventFilter/CSCRawToDigi/plugins/module.cc
  EventFilter/CSCRawToDigi/python/cscPacker_cfi.py
  EventFilter/CSCRawToDigi/python/cscUnpacker_cfi.py
  EventFilter/CSCRawToDigi/src/CSCDigiToPattern.h
  EventFilter/CSCRawToDigi/src/CSCDigiToRaw.cc
  EventFilter/CSCRawToDigi/src/CSCDigiToRaw.h
  EventFilter/CSCRawToDigi/src/CSCEventData.cc
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30257 Keep GEMDigiSimLinks after the DIGI step
  SimMuon/Configuration/python/SimMuon_EventContent_cff.py
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, simulation-approved, tests-approved

#30268 Including PPS into cmsExtended 2021
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/VeryForwardData/data/pps/2021/v1/pps.xml
Labels: code-checks-approved, comparison-available, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#30217 HCAL - HB TDC digi default to non-packed backport to 11_0_X
  EventFilter/HcalRawToDigi/plugins/HcalDigiToRawuHTR.cc
Labels: backport-ok, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30285 Add SA checker to report calls to edm::eventsetup::EventSetupRecord::<>get() function template instantiations.
  Utilities/StaticAnalyzers/src/ClangCmsCheckerPluginRegister.cpp
  Utilities/StaticAnalyzers/src/ESRecordGetChecker.cpp
  Utilities/StaticAnalyzers/src/ESRecordGetChecker.h
Labels: code-checks-approved, comparison-available, core-approved, fully-signed, orp-approved, tests-approved

#30279 added esConsumes to modules in EventFIlter/GEMRawToDigi
  EventFilter/GEMRawToDigi/plugins/GEMDigiToRawModule.cc
  EventFilter/GEMRawToDigi/plugins/GEMDigiToRawModule.h
Labels: code-checks-approved, comparison-available, fully-signed, orp-approved, reconstruction-approved, tests-approved

#30148 added esConsumes to modules in L1Trigger/CSCTriggerPrimitives
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.cc
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.h
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesReader.cc
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesReader.h
  L1Trigger/CSCTriggerPrimitives/plugins/L1CSCTPEmulatorConfigAnalyzer.cc
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#30149 added esConsumes to modules in L1Trigger/CSCTrackFinder
  L1Trigger/CSCTrackFinder/plugins/CSCTFTrackProducer.cc
  L1Trigger/CSCTrackFinder/plugins/CSCTFTrackProducer.h
  L1Trigger/CSCTrackFinder/plugins/CSCTFanalyzer.cc
  L1Trigger/CSCTrackFinder/plugins/CSCTFanalyzer.h
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved

#30216 added esConsumes to modules in SimCalorimetry/ EcalEBTrigPrimProducers
  SimCalorimetry/EcalEBTrigPrimProducers/plugins/EcalEBTrigPrimProducer.cc
  SimCalorimetry/EcalEBTrigPrimProducers/plugins/EcalEBTrigPrimProducer.h
Labels: code-checks-approved, comparison-available, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved
