Repository cms-sw/cmssw, pull requests merged in 2021-09, with the labels that each got.

#35097 Run endStream concurrently as part of endJob
  FWCore/Framework/src/EventProcessor.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35088 Run3-sim108 Fully resolve the issue of usinng dd4hep in CherenkovAnalysis
  SimG4CMS/CherenkovAnalysis/data/SingleDREAMDD4Hep.xml
  SimG4CMS/CherenkovAnalysis/data/cms.xml
  SimG4CMS/CherenkovAnalysis/data/singleDREAM.xml
  SimG4CMS/CherenkovAnalysis/python/SingleDREAMXML_cfi.py
  SimG4CMS/CherenkovAnalysis/src/DreamSD.cc
  SimG4CMS/CherenkovAnalysis/test/runSingleDREAMDD4Hep_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34988 Updates to the TTTrack/TTTrack_TrackWord DataFormats
  DataFormats/L1TrackTrigger/BuildFile.xml
  DataFormats/L1TrackTrigger/interface/TTTrack.h
  DataFormats/L1TrackTrigger/interface/TTTrack_TrackWord.h
  DataFormats/L1TrackTrigger/src/TTTrack_TrackWord.cc
  DataFormats/L1TrackTrigger/test/BuildFile.xml
  DataFormats/L1TrackTrigger/test/TestDataFormatsTTTrackTrackWord.cc
  DataFormats/L1TrackTrigger/test/testDataFormatsTTTrackTrackWord_cfg.py
  L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#34714 NANO: rework for Prompt (part3)
  Configuration/Eras/python/Modifier_run3_nanoAOD_devel_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/nano_eras_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved

#34898 [EventFilter] Move private headers in plugins dir; merge plugins cc/h files
  EventFilter/CSCTFRawToDigi/interface/CSCTFAnalyzer.h
  EventFilter/CSCTFRawToDigi/interface/CSCTFPacker.h
  EventFilter/CSCTFRawToDigi/interface/CSCTFUnpacker.h
  EventFilter/CSCTFRawToDigi/plugins/CSCTFAnalyzer.cc
  EventFilter/CSCTFRawToDigi/plugins/CSCTFPacker.cc
  EventFilter/CSCTFRawToDigi/plugins/CSCTFUnpacker.cc
  EventFilter/CSCTFRawToDigi/plugins/SealModule.cc
  EventFilter/EcalRawToDigi/interface/MatacqProducer.h
  EventFilter/EcalRawToDigi/plugins/EcalDumpRaw.cc
  EventFilter/EcalRawToDigi/plugins/EcalRawToDigi.cc
  EventFilter/EcalRawToDigi/plugins/EcalRawToDigi.h
  EventFilter/EcalRawToDigi/plugins/EcalRegionCablingESProducer.cc
  EventFilter/EcalRawToDigi/plugins/EcalRegionCablingESProducer.h
  EventFilter/EcalRawToDigi/plugins/MatacqProducer.cc
  EventFilter/EcalRawToDigi/plugins/SealModules.cc
Labels: l1-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35092 Fix 2021 Reco Geometry Config files
  Configuration/Geometry/python/GeometryDD4hepExtended2021FlatMinus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021FlatMinus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021FlatPlus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021FlatPlus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021ZeroMaterialReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021FlatMinus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021FlatMinus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021FlatPlus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021FlatPlus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2021ZeroMaterialReco_cff.py
  Configuration/Geometry/python/dict2021Geometry.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, trk-dpg-approved

#35049 [EGM HLT] Phase out calotower & use HCAL recHits directly
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTHcalVarProducerFromRecHit.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34895 [L1Trigger] Move public headers in to interface directory
  L1Trigger/DTTrackFinder/interface/L1MuDTAddressArray.h
  L1Trigger/DTTrackFinder/interface/L1MuDTSecProcId.h
  L1Trigger/DTTrackFinder/interface/L1MuDTTrack.h
  L1Trigger/DTTrackFinder/interface/L1MuDTTrackAssParam.h
  L1Trigger/DTTrackFinder/interface/L1MuDTTrackSegEta.h
  L1Trigger/DTTrackFinder/interface/L1MuDTTrackSegLoc.h
  L1Trigger/DTTrackFinder/interface/L1MuDTTrackSegPhi.h
  L1Trigger/DTTrackFinder/src/L1MuDTAddressArray.cc
  L1Trigger/DTTrackFinder/src/L1MuDTAssignmentUnit.cc
  L1Trigger/DTTrackFinder/src/L1MuDTAssignmentUnit.h
  L1Trigger/DTTrackFinder/src/L1MuDTDataBuffer.cc
  L1Trigger/DTTrackFinder/src/L1MuDTERS.cc
  L1Trigger/DTTrackFinder/src/L1MuDTEUX.cc
  L1Trigger/DTTrackFinder/src/L1MuDTEtaProcessor.cc
  L1Trigger/DTTrackFinder/src/L1MuDTEtaProcessor.h
  L1Trigger/DTTrackFinder/src/L1MuDTExtrapolationUnit.cc
  L1Trigger/DTTrackFinder/src/L1MuDTMuonSorter.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSEU.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSecProcId.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSecProcMap.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSecProcMap.h
  L1Trigger/DTTrackFinder/src/L1MuDTSectorProcessor.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSectorProcessor.h
  L1Trigger/DTTrackFinder/src/L1MuDTSectorReceiver.cc
  L1Trigger/DTTrackFinder/src/L1MuDTTrack.cc
  L1Trigger/DTTrackFinder/src/L1MuDTTrackAssParam.cc
  L1Trigger/DTTrackFinder/src/L1MuDTTrackAssembler.h
  L1Trigger/DTTrackFinder/src/L1MuDTTrackFinder.cc
  L1Trigger/DTTrackFinder/src/L1MuDTTrackSegEta.cc
  L1Trigger/DTTrackFinder/src/L1MuDTTrackSegLoc.cc
  L1Trigger/DTTrackFinder/src/L1MuDTTrackSegPhi.cc
  L1Trigger/DTTrackFinder/src/L1MuDTWedgeSorter.cc
  L1Trigger/GlobalCaloTrigger/interface/L1GctHfBitCountsLut.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctHfEtSumsLut.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctHtMissLut.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctJetCount.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctJetEtCalibrationLut.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctJetFinderBase.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctJetLeafCard.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctLut.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctTwosComplement.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctUnsignedInt.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctWheelEnergyFpga.h
  L1Trigger/GlobalCaloTrigger/interface/L1GctWheelJetFpga.h
  L1Trigger/GlobalCaloTrigger/interface/L1GlobalCaloTrigger.h
  L1Trigger/GlobalCaloTrigger/src/L1GctJetCount.cc
  L1Trigger/GlobalCaloTrigger/src/L1GctLut.cc
  L1Trigger/GlobalCaloTrigger/src/L1GctTwosComplement.cc
  L1Trigger/GlobalCaloTrigger/src/L1GctUnsignedInt.cc
  L1Trigger/GlobalCaloTrigger/test/L1GctLutFromFile.h
  L1Trigger/GlobalCaloTrigger/test/testEtTypes.cpp
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34805 HCAL: fixing pulse containment correction algorithm for Run3 trigger primitives
  CalibCalorimetry/HcalTPGAlgos/interface/HcaluLUTTPGCoder.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  CalibCalorimetry/HcalTPGEventSetup/src/HcalTPGCoderULUT.cc
  SimCalorimetry/HcalTrigPrimProducers/python/hcaltpdigi_cff.py
Labels: alca-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35101 Migrate module configuration in PhysicsTools{PatUtils} to use default cfipython
  PhysicsTools/PatUtils/python/patPFMETCorrections_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34902 Migrate BMixingModule and EcalShapeBase-derived classes to esConsumes
  CalibCalorimetry/EcalSRTools/interface/EcalDccWeightBuilder.h
  CalibCalorimetry/EcalSRTools/src/EcalDccWeightBuilder.cc
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.h
  Mixing/Base/interface/BMixingModule.h
  Mixing/Base/interface/PileUp.h
  Mixing/Base/src/BMixingModule.cc
  Mixing/Base/src/PileUp.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerGlobal.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerGlobal.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerWeights.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerWeights.h
  RecoTBCalo/EcalTBRecProducers/src/EcalTBWeightUncalibRecHitProducer.cc
  SimCalorimetry/EcalSimAlgos/interface/APDShape.h
  SimCalorimetry/EcalSimAlgos/interface/EBShape.h
  SimCalorimetry/EcalSimAlgos/interface/EEShape.h
  SimCalorimetry/EcalSimAlgos/src/APDShape.cc
  SimCalorimetry/EcalSimAlgos/src/EBShape.cc
  SimCalorimetry/EcalSimAlgos/src/EEShape.cc
  SimCalorimetry/EcalSimAlgos/test/testEcalShape.cpp
  SimCalorimetry/EcalSimProducers/interface/EcalDigiProducer.h
  SimCalorimetry/EcalSimProducers/interface/EcalDigiProducer_Ph2.h
  SimCalorimetry/EcalSimProducers/src/EcalDigiProducer.cc
  SimCalorimetry/EcalSimProducers/src/EcalDigiProducer_Ph2.cc
  SimGeneral/MixingModule/plugins/MixingModule.cc
  SimGeneral/MixingModule/plugins/MixingModule.h
  SimGeneral/MixingModule/plugins/MixingWorker.h
  SimGeneral/MixingModule/plugins/MixingWorkerBase.h
  SimGeneral/MixingModule/plugins/SecSourceAnalyzer.cc
  SimGeneral/MixingModule/plugins/SecSourceAnalyzer.h
  Validation/EcalDigis/plugins/EcalMixingModuleValidation.cc
  Validation/EcalDigis/plugins/EcalMixingModuleValidation.h
Labels: alca-approved, dqm-approved, l1-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34933 Delete unused headers/test files (DB packages)
  CondCore/DTPlugins/interface/DTCompactMapPluginHandler.h
  CondCore/DTPlugins/interface/DTConfigPluginHandler.h
  CondFormats/CastorObjects/interface/AllClasses.h
  CondFormats/Common/interface/Constants.h
  CondFormats/DataRecord/interface/SiStripBadChannelRcd.h
  CondFormats/DataRecord/interface/SiStripBadFiberRcd.h
  CondFormats/DataRecord/interface/SiStripBadModuleRcd.h
  CondFormats/DataRecord/interface/SiStripModuleHVRcd.h
  CondFormats/DataRecord/interface/SiStripPerformanceSummaryRcd.h
  CondFormats/DataRecord/interface/SiStripRunSummaryRcd.h
  CondFormats/HcalObjects/interface/HcalItemArrayColl.h
  CondFormats/HcalObjects/interface/HcalItemArrayCollById.h
  CondFormats/Serialization/interface/eos/polymorphic_portable_archive.hpp
  CondFormats/Serialization/interface/eos/portable_archive.hpp
  CondFormats/SiPixelObjects/interface/MapPathTodetUnit.h
  CondTools/Ecal/interface/EcalIntercalibConstantsHandler.h
  CondTools/Ecal/interface/EcalIntercalibConstantsMCHandler.h
  CondTools/Ecal/interface/EcalIntercalibErrorsHandler.h
  CondTools/Ecal/interface/EcalIntercalibErrorsXMLTranslator.h
  CondTools/Ecal/interface/EcalPFRecHitThresholdsXMLTranslator.h
  CondTools/Ecal/interface/EcalTimeCalibConstantsHandler.h
  CondTools/Ecal/interface/EcalTimeCalibConstantsXMLTranslator.h
  CondTools/Ecal/interface/EcalTimeCalibErrorsHandler.h
  CondTools/Ecal/interface/EcalTimeCalibErrorsXMLTranslator.h
  CondTools/Ecal/test/testXMLTranslators.cc
  CondTools/L1Trigger/interface/Interval.h
  CondTools/RPC/interface/L1RPCHwConfigDBWriter.h
  CondTools/RPC/interface/RPCEMapDBWriter.h
  CondTools/SiStrip/interface/SiStripCondObjBuilderBase.h
  CondTools/SiStrip/interface/SiStripDepCondObjBuilderBase.h
  OnlineDB/CSCCondDB/interface/AutoCorrMat.h
  OnlineDB/CSCCondDB/interface/CSCCableReadTest.h
  OnlineDB/CSCCondDB/interface/CSCxTalk.h
  OnlineDB/CSCCondDB/interface/SaturationFcn.h
  OnlineDB/EcalCondDB/interface/IConfig.h
  OnlineDB/EcalCondDB/interface/IRunIOV.h
  OnlineDB/EcalCondDB/interface/ITimeIOV.h
  OnlineDB/EcalCondDB/interface/all_cali_types.h
  OnlineDB/EcalCondDB/interface/all_dcu_types.h
  OnlineDB/EcalCondDB/interface/all_mod_types.h
  OnlineDB/EcalCondDB/test/InsertDCUIdarkPed.cpp
  OnlineDB/EcalCondDB/test/TestChannelView.cpp
  OnlineDB/EcalCondDB/test/TestDCU.cpp
  OnlineDB/EcalCondDB/test/TestMOD.cpp
Labels: alca-approved, l1-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#35102 Get rid of the unneeded conf_ class member in SiPixelPhase1EfficiencyExtras
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1EfficiencyExtras.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34615 Merge .h and .cc files of plugins in several PhysicsTools packages
  PhysicsTools/IsolationAlgos/plugins/CandIsoDepositProducer.cc
  PhysicsTools/IsolationAlgos/plugins/CandIsoDepositProducer.h
  PhysicsTools/IsolationAlgos/plugins/CandIsolatorFromDeposits.cc
  PhysicsTools/IsolationAlgos/plugins/CandIsolatorFromDeposits.h
  PhysicsTools/IsolationAlgos/plugins/CandViewExtractor.cc
  PhysicsTools/IsolationAlgos/plugins/CandViewExtractor.h
  PhysicsTools/IsolationAlgos/plugins/CandViewExtractor.icc
  PhysicsTools/IsolationAlgos/plugins/PFTauExtractor.cc
  PhysicsTools/IsolationAlgos/plugins/PFTauExtractor.h
  PhysicsTools/TagAndProbe/interface/ElectronMatchedCandidateProducer.h
  PhysicsTools/TagAndProbe/plugins/ElectronMatchedCandidateProducer.cc
Labels: analysis-pending, reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved

#35021 Modernize some EGamma Reco modules
  RecoEcal/EgammaClusterProducers/src/EgammaSCCorrectionMaker.cc
  RecoEcal/EgammaCoreTools/interface/EcalClusterFunctionBaseClass.h
  RecoEcal/EgammaCoreTools/interface/EcalClusterFunctionFactory.h
  RecoEcal/EgammaCoreTools/interface/EcalClusterLazyTools.h
  RecoEcal/EgammaCoreTools/plugins/EcalClusterCrackCorrection.cc
  RecoEcal/EgammaCoreTools/plugins/EcalClusterEnergyCorrection.cc
  RecoEcal/EgammaCoreTools/plugins/EcalClusterEnergyCorrectionObjectSpecific.cc
  RecoEcal/EgammaCoreTools/plugins/EcalClusterEnergyUncertainty.cc
  RecoEcal/EgammaCoreTools/test/testEcalClusterFunctions.cc
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronIDProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedProducer.cc
  RecoEgamma/EgammaPhotonAlgos/interface/PhotonEnergyCorrector.h
  RecoEgamma/EgammaPhotonAlgos/src/PhotonEnergyCorrector.cc
  RecoEgamma/EgammaPhotonProducers/src/GEDPhotonProducer.cc
  TrackingTools/GsfTracking/BuildFile.xml
  TrackingTools/GsfTracking/interface/GsfConstraintAtVertex.h
  TrackingTools/GsfTracking/src/GsfConstraintAtVertex.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35017 Adapt CAConstants for HIon
  RecoPixelVertexing/PixelTriplets/plugins/CAConstants.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#35087 Adding protections to PATTriggerProducer when the path has zero filters: 12_0
  PhysicsTools/PatAlgos/plugins/PATTriggerProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok

#35078 Modernized JetTagProducer
  RecoBTau/JetTagComputer/plugins/JetTagProducer.cc
  RecoBTau/JetTagComputer/plugins/JetTagProducer.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34970 Updates to the TTTrack/TTTrack_TrackWord DataFormats
  DataFormats/L1TrackTrigger/BuildFile.xml
  DataFormats/L1TrackTrigger/interface/TTTrack.h
  DataFormats/L1TrackTrigger/interface/TTTrack_TrackWord.h
  DataFormats/L1TrackTrigger/src/TTTrack_TrackWord.cc
  DataFormats/L1TrackTrigger/test/BuildFile.xml
  DataFormats/L1TrackTrigger/test/TestDataFormatsTTTrackTrackWord.cc
  DataFormats/L1TrackTrigger/test/testDataFormatsTTTrackTrackWord_cfg.py
  L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#35112 [GCC11] Fix comopiler warnings for LumiProducer
  RecoLuminosity/LumiProducer/plugins/ExpressLumiProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35113 [GCC11] Fix compiler warnings for RecoPPS
  RecoPPS/ProtonReconstruction/plugins/CTPPSProtonProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34801 Correct RegionalMuon (un)packer when running on EMTF data
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFPackerOutput.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFUnpackerOutput.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GMTSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTPacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTPacker.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTUnpacker.h
  EventFilter/L1TRawToDigi/python/gmtStage2Raw_cfi.py
  L1Trigger/L1TMuon/interface/RegionalMuonRawDigiTranslator.h
  L1Trigger/L1TMuon/src/RegionalMuonRawDigiTranslator.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35093 Run3-hcx314 Reorganize the files in SimCalorimetry/CastorTechTrigProducer and merge .h files
  SimCalorimetry/CastorTechTrigProducer/plugins/BuildFile.xml
  SimCalorimetry/CastorTechTrigProducer/plugins/CastorTTRecord.cc
  SimCalorimetry/CastorTechTrigProducer/src/CastorTTRecord.h
  SimCalorimetry/CastorTechTrigProducer/src/SealModule.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35121 disable 136.72413 in relval_standard
  Configuration/PyReleaseValidation/python/relval_standard.py
Labels: fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, urgent, upgrade-approved, code-checks-approved

#35119 Adding fake alignment to make tracker geometry test work
  Geometry/TrackerGeometryBuilder/test/python/testTrackerHierarchy_cfg.py
  Geometry/TrackerGeometryBuilder/test/python/testTracker_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, requires-external, code-checks-approved

#35120 Enable services in concurrent endJob processing
  FWCore/Framework/src/EventProcessor.cc
Labels: core-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, requires-external, code-checks-approved

#35110 [GCC11] Fix warnings for EgammaHLTProducers
  RecoEgamma/EgammaHLTProducers/plugins/HLTCaloObjInRegionsProducer.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35054 Removed undefined use of union in libminifloat
  DataFormats/Math/interface/libminifloat.h
  FWCore/Utilities/interface/bit_cast.h
Labels: core-approved, reconstruction-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#35122 Remove duplicate include statements
  EventFilter/EcalRawToDigi/interface/EcalElectronicsMapper.h
  EventFilter/EcalRawToDigi/plugins/EcalCPUDigisProducer.cc
  EventFilter/EcalRawToDigi/plugins/EcalRawToDigi.cc
  EventFilter/EcalRawToDigi/plugins/MatacqProducer.cc
  EventFilter/EcalRawToDigi/src/MatacqDataFormatter.cc
Labels: reconstruction-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#35068 [UBSAN] DataFormats/CaloTowers initialization fix
  DataFormats/CaloTowers/interface/CaloTower.h
Labels: reconstruction-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#34779 Move CSC trigger and GEM-CSC trigger lookup tables into eventsetup objects (CCLUT-17)
  CalibMuon/CSCCalibration/plugins/CSCL1TPLookupTableEP.cc
  CalibMuon/CSCCalibration/python/CSCL1TPLookupTableEP_cff.py
  CondFormats/CSCObjects/interface/CSCL1TPLookupTableCCLUT.h
  CondFormats/CSCObjects/interface/CSCL1TPLookupTableME11ILT.h
  CondFormats/CSCObjects/interface/CSCL1TPLookupTableME21ILT.h
  CondFormats/CSCObjects/src/CSCL1TPLookupTableCCLUT.cc
  CondFormats/CSCObjects/src/CSCL1TPLookupTableME11ILT.cc
  CondFormats/CSCObjects/src/CSCL1TPLookupTableME21ILT.cc
  CondFormats/CSCObjects/src/T_EventSetup_CSCL1TPLookupTableCCLUT.cc
  CondFormats/CSCObjects/src/T_EventSetup_CSCL1TPLookupTableME11ILT.cc
  CondFormats/CSCObjects/src/T_EventSetup_CSCL1TPLookupTableME21ILT.cc
  CondFormats/CSCObjects/src/classes_def.xml
  CondFormats/CSCObjects/src/headers.h
  CondFormats/CSCObjects/test/testSerializationCSCObjects.cpp
  CondFormats/DataRecord/interface/CSCL1TPLookupTableCCLUTRcd.h
  CondFormats/DataRecord/interface/CSCL1TPLookupTableME11ILTRcd.h
  CondFormats/DataRecord/interface/CSCL1TPLookupTableME21ILTRcd.h
  CondFormats/DataRecord/src/CSCL1TPLookupTableCCLUTRcd.cc
  CondFormats/DataRecord/src/CSCL1TPLookupTableME11ILTRcd.cc
  CondFormats/DataRecord/src/CSCL1TPLookupTableME21ILTRcd.cc
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
  L1Trigger/CSCTriggerPrimitives/interface/CSCALCTCrossCLCT.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCBaseboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMatcher.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCLUTReader.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCTriggerPrimitivesBuilder.h
  L1Trigger/CSCTriggerPrimitives/interface/ComparatorCodeLUT.h
  L1Trigger/CSCTriggerPrimitives/interface/GEMClusterProcessor.h
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.cc
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.h
  L1Trigger/CSCTriggerPrimitives/plugins/SealModule.cc
  L1Trigger/CSCTriggerPrimitives/python/cscTriggerPrimitiveDigis_cfi.py
  L1Trigger/CSCTriggerPrimitives/python/params/cclutParams.py
  L1Trigger/CSCTriggerPrimitives/python/params/gemcscParams.py
  L1Trigger/CSCTriggerPrimitives/python/params/tmbParams.py
  L1Trigger/CSCTriggerPrimitives/src/CSCALCTCrossCLCT.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMatcher.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCLUTReader.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCTriggerPrimitivesBuilder.cc
  L1Trigger/CSCTriggerPrimitives/src/ComparatorCodeLUT.cc
  L1Trigger/CSCTriggerPrimitives/src/GEMClusterProcessor.cc
  L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveProducer_cfg.py
  L1Trigger/CSCTriggerPrimitives/test/runL1CSCTPEmulatorConfigAnalyzer_cfg.py
  L1Trigger/Configuration/python/L1MuonEmulator_cff.py
  L1Trigger/Configuration/python/ValL1Emulator_cff.py
  L1Trigger/Configuration/python/customiseReEmul.py
  L1Trigger/L1TMuon/python/simDigis_cff.py
Labels: alca-approved, dqm-approved, l1-approved, fully-signed, tests-approved, db-approved, orp-approved, requires-external, code-checks-approved

#35139 [DBG] Fixed compilation errors
  Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35129 Fix filling and multiplicity ranges
  DQMOffline/Muon/interface/CSCOfflineMonitor.h
  DQMOffline/Muon/src/CSCOfflineMonitor.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35107 ECAL esConsumes migration of Calibration packages
  Calibration/EcalAlCaRecoProducers/plugins/SelectedElectronFEDListProducer.cc
  Calibration/EcalAlCaRecoProducers/plugins/SelectedElectronFEDListProducer.h
  Calibration/EcalCalibAlgos/interface/ECALpedestalPCLHarvester.h
  Calibration/EcalCalibAlgos/interface/ECALpedestalPCLworker.h
  Calibration/EcalCalibAlgos/interface/EcalEleCalibLooper.h
  Calibration/EcalCalibAlgos/interface/ElectronCalibrationUniv.h
  Calibration/EcalCalibAlgos/interface/InvRingCalib.h
  Calibration/EcalCalibAlgos/interface/PhiSymmetryCalibration.h
  Calibration/EcalCalibAlgos/interface/Pi0FixedMassWindowCalibration.h
  Calibration/EcalCalibAlgos/interface/ZeeCalibration.h
  Calibration/EcalCalibAlgos/src/ECALpedestalPCLHarvester.cc
  Calibration/EcalCalibAlgos/src/ECALpedestalPCLworker.cc
  Calibration/EcalCalibAlgos/src/EcalEleCalibLooper.cc
  Calibration/EcalCalibAlgos/src/ElectronCalibrationUniv.cc
  Calibration/EcalCalibAlgos/src/InvRingCalib.cc
  Calibration/EcalCalibAlgos/src/PhiSymmetryCalibration.cc
  Calibration/EcalCalibAlgos/src/PhiSymmetryCalibration_step2.cc
  Calibration/EcalCalibAlgos/src/PhiSymmetryCalibration_step2.h
  Calibration/EcalCalibAlgos/src/PhiSymmetryCalibration_step2_SM.cc
  Calibration/EcalCalibAlgos/src/PhiSymmetryCalibration_step2_SM.h
  Calibration/EcalCalibAlgos/src/Pi0FixedMassWindowCalibration.cc
  Calibration/EcalCalibAlgos/src/ZeeCalibration.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35131 Fix the TriggerResultsFilter default configuration to skip the current process
  HLTrigger/HLTfilters/plugins/TriggerResultsFilter.cc
  HLTrigger/HLTfilters/test/triggerResultsFilter.py
  HLTrigger/HLTfilters/test/triggerResultsFilter_producer.py
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#35089 PPS: fix of isPixelHit
  CalibPPS/ESProducers/plugins/PPSPixelTopologyESSource.cc
  CondFormats/PPSObjects/src/PPSPixelTopology.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#35144 [GCC11] Fix compilation warning for CommonTools
  CommonTools/Utils/test/testDynArray.cpp
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35143 [GCC11] Fix compilation warning for FW/ToyIntProducers
  FWCore/Framework/test/stubs/ToyIntProducers.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35128 improve math in broken-line fit
  RecoPixelVertexing/PixelTrackFitting/interface/BrokenLine.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35133 ECAL esConsumes migration of CaloOnlineTools/EcalTools
  CaloOnlineTools/EcalTools/plugins/EcalCosmicsHists.cc
  CaloOnlineTools/EcalTools/plugins/EcalCosmicsHists.h
  CaloOnlineTools/EcalTools/plugins/EcalDigiDisplay.cc
  CaloOnlineTools/EcalTools/plugins/EcalDigiDisplay.h
  CaloOnlineTools/EcalTools/plugins/EcalDisplaysByEvent.cc
  CaloOnlineTools/EcalTools/plugins/EcalDisplaysByEvent.h
  CaloOnlineTools/EcalTools/plugins/EcalMipGraphs.cc
  CaloOnlineTools/EcalTools/plugins/EcalMipGraphs.h
  CaloOnlineTools/EcalTools/plugins/EcalPedHists.cc
  CaloOnlineTools/EcalTools/plugins/EcalPedHists.h
  CaloOnlineTools/EcalTools/plugins/EcalTPGAnalyzer.cc
  CaloOnlineTools/EcalTools/plugins/EcalTPGAnalyzer.h
  CaloOnlineTools/EcalTools/plugins/EcalURecHitHists.cc
  CaloOnlineTools/EcalTools/plugins/EcalURecHitHists.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35115 Run3-gex90X Clean up a few cfi's for HCAL and SimDB geometry
  Configuration/Geometry/python/GeometryDDDSimDB_cff.py
  Geometry/HcalCommonData/python/hcalSimDBConstants_cff.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#35147 Run3-hcx316 Add a few collection for carrying out AlCaReco studies
  DataFormats/HcalCalibObjects/interface/HcalHBHEMuonVariables.h
  DataFormats/HcalCalibObjects/interface/HcalIsoTrkCalibVariables.h
  DataFormats/HcalCalibObjects/interface/HcalIsoTrkEventVariables.h
  DataFormats/HcalCalibObjects/src/classes.h
  DataFormats/HcalCalibObjects/src/classes_def.xml
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35136 Run3-hcx315 Rearrange the files properly in the plugins directory and define the python scripts from the code in Calibration/HcalIsolatedTrackReco
  Calibration/HcalIsolatedTrackReco/interface/ECALRegFEDSelector.h
  Calibration/HcalIsolatedTrackReco/interface/EcalIsolatedParticleCandidateProducer.h
  Calibration/HcalIsolatedTrackReco/interface/IPTCorrector.h
  Calibration/HcalIsolatedTrackReco/interface/IsolatedEcalPixelTrackCandidateProducer.h
  Calibration/HcalIsolatedTrackReco/interface/IsolatedPixelTrackCandidateL1TProducer.h
  Calibration/HcalIsolatedTrackReco/interface/IsolatedPixelTrackCandidateProducer.h
  Calibration/HcalIsolatedTrackReco/interface/SiStripRegFEDSelector.h
  Calibration/HcalIsolatedTrackReco/interface/SubdetFEDSelector.h
  Calibration/HcalIsolatedTrackReco/plugins/BuildFile.xml
  Calibration/HcalIsolatedTrackReco/plugins/ECALRegFEDSelector.cc
  Calibration/HcalIsolatedTrackReco/plugins/EcalIsolatedParticleCandidateProducer.cc
  Calibration/HcalIsolatedTrackReco/plugins/HITRegionalPixelSeedGenerator.cc
  Calibration/HcalIsolatedTrackReco/plugins/IPTCorrector.cc
  Calibration/HcalIsolatedTrackReco/plugins/IsolatedEcalPixelTrackCandidateProducer.cc
  Calibration/HcalIsolatedTrackReco/plugins/IsolatedPixelTrackCandidateL1TProducer.cc
  Calibration/HcalIsolatedTrackReco/plugins/IsolatedPixelTrackCandidateProducer.cc
  Calibration/HcalIsolatedTrackReco/plugins/SiStripRegFEDSelector.cc
  Calibration/HcalIsolatedTrackReco/plugins/SubdetFEDSelector.cc
  Calibration/HcalIsolatedTrackReco/python/ecalFED_cfi.py
  Calibration/HcalIsolatedTrackReco/python/ecalIsolPartProd_cfi.py
  Calibration/HcalIsolatedTrackReco/python/stripFED_cfi.py
  Calibration/HcalIsolatedTrackReco/python/subdetFED_cfi.py
  Calibration/HcalIsolatedTrackReco/src/SealModule.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35067 PPS Pixel data unpacking
  EventFilter/CTPPSRawToDigi/interface/CTPPSPixelDataFormatter.h
  EventFilter/CTPPSRawToDigi/interface/CTPPSPixelRawToDigi.h
  EventFilter/CTPPSRawToDigi/plugins/CTPPSPixelDigiToRaw.cc
  EventFilter/CTPPSRawToDigi/plugins/CTPPSPixelRawToDigi.cc
  EventFilter/CTPPSRawToDigi/python/ctppsRawToDigi_cff.py
  EventFilter/CTPPSRawToDigi/src/CTPPSPixelDataFormatter.cc
  EventFilter/CTPPSRawToDigi/test/test_pixels_only_cfg_eraRun3_562.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35132 Fix the TriggerResultsFilter default configuration to skip the current process [12.0.x]
  HLTrigger/HLTfilters/plugins/TriggerResultsFilter.cc
  HLTrigger/HLTfilters/test/triggerResultsFilter.py
  HLTrigger/HLTfilters/test/triggerResultsFilter_producer.py
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#35134 Added esConsumes to modules in SimMuon/MCTruth
  SimMuon/MCTruth/interface/CSCHitAssociator.h
  SimMuon/MCTruth/interface/DTHitAssociator.h
  SimMuon/MCTruth/interface/GEMHitAssociator.h
  SimMuon/MCTruth/interface/MuonAssociatorByHits.h
  SimMuon/MCTruth/interface/MuonAssociatorByHitsHelper.h
  SimMuon/MCTruth/interface/RPCHitAssociator.h
  SimMuon/MCTruth/interface/TrackerMuonHitExtractor.h
  SimMuon/MCTruth/plugins/MuonToTrackingParticleAssociatorByHitsImpl.cc
  SimMuon/MCTruth/plugins/MuonToTrackingParticleAssociatorByHitsImpl.h
  SimMuon/MCTruth/plugins/MuonToTrackingParticleAssociatorEDProducer.cc
  SimMuon/MCTruth/plugins/SeedToTrackProducer.cc
  SimMuon/MCTruth/plugins/SeedToTrackProducer.h
  SimMuon/MCTruth/src/CSCHitAssociator.cc
  SimMuon/MCTruth/src/DTHitAssociator.cc
  SimMuon/MCTruth/src/GEMHitAssociator.cc
  SimMuon/MCTruth/src/MuonAssociatorByHits.cc
  SimMuon/MCTruth/src/RPCHitAssociator.cc
  SimMuon/MCTruth/src/TrackerMuonHitExtractor.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35135 Add CSC TP efficiency producer in standard DQM sequence
  Validation/Configuration/python/postValidation_cff.py
  Validation/MuonCSCDigis/src/CSCStubEfficiencyValidation.cc
Labels: dqm-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35153 Run3-hcx318 Correct a few analyzers in Calibration/HcalCalibAlgos aganist static analyzers
  Calibration/HcalCalibAlgos/interface/TCell.h
  Calibration/HcalCalibAlgos/interface/hcalCalib.h
  Calibration/HcalCalibAlgos/interface/hcalCalibUtils.h
  Calibration/HcalCalibAlgos/plugins/HcalCalibrator.cc
  Calibration/HcalCalibAlgos/plugins/HcalCalibrator.h
  Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HitReCalibrator.cc
  Calibration/HcalCalibAlgos/plugins/HitReCalibrator.h
  Calibration/HcalCalibAlgos/src/classes.h
  Calibration/HcalCalibAlgos/src/hcalCalib.cc
  Calibration/HcalCalibAlgos/src/hcalCalibUtils.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35155 Run3-371X Use of ESGetToken in Calibration/HcalCalibAlgos
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkAnalyzer.cc
  Calibration/HcalCalibAlgos/test/HcalIsoTrackStudy.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35156 Run3-hcx319 Make use of ESGetToken in SimCalorimetry/HcalSimProducers
  SimCalorimetry/HcalSimAlgos/interface/HcalSignalGenerator.h
  SimCalorimetry/HcalSimAlgos/src/HcalShapes.cc
  SimCalorimetry/HcalSimAlgos/test/CaloSamplesAnalyzer.cc
  SimCalorimetry/HcalSimAlgos/test/HcalDigitizerTest.cc
  SimCalorimetry/HcalSimAlgos/test/HcalSignalGeneratorTest.cpp
  SimCalorimetry/HcalSimProducers/plugins/PreMixingHcalWorker.cc
  SimGeneral/DataMixingModule/plugins/DataMixingHcalDigiWorkerProd.cc
  SimGeneral/DataMixingModule/plugins/DataMixingHcalDigiWorkerProd.h
  SimGeneral/DataMixingModule/plugins/DataMixingModule.cc
  SimGeneral/DataMixingModule/plugins/DataMixingModule.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35103 Disabled duplicate GEM TP warnings in EMTF GEM unpacker [11_3_X]
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockGEM.cc
Labels: l1-pending, pending-signatures, tests-approved, orp-approved, urgent, backport-ok

#35029 PCL of diamond sampic offset calibration
  CalibPPS/TimingCalibration/plugins/BuildFile.xml
  CalibPPS/TimingCalibration/plugins/PPSDiamondSampicTimingCalibrationPCLHarvester.cc
  CalibPPS/TimingCalibration/plugins/PPSDiamondSampicTimingCalibrationPCLWorker.cc
  CalibPPS/TimingCalibration/python/ALCARECOPPSCalTrackBasedSel_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSDiamondSampicTimingCalibHarvester_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSDiamondSampicTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSDiamondSampicTimingCalib_cff.py
  CalibPPS/TimingCalibration/test/DiamondSampicCalibrationHarvester_cfg.py
  CalibPPS/TimingCalibration/test/DiamondSampicCalibrationWorker_cfg.py
  CalibPPS/TimingCalibration/test/runDiamondSampicCalibration
  Configuration/AlCa/python/autoPCL.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
  DQM/CTPPS/plugins/BuildFile.xml
  DQM/CTPPS/plugins/DiamondSampicCalibrationDQMSource.cc
Labels: alca-approved, dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35140 Disable JME Nano workflows due to Nano-prompt dev
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_pileup.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#35159 Update README Configuration/Geometry
  Configuration/Geometry/README.md
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#35091 Removed lexical_cast boost dependency in CondFormats
  CondFormats/MFObjects/src/MagFieldConfig.cc
  CondFormats/Serialization/interface/eos/portable_archive_exception.hpp
  CondFormats/SiStripObjects/src/SiStripDetSummary.cc
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#35096 Migrate `CondTools/RunInfo` to esConsumes
  CondTools/RunInfo/interface/BTransitionAnalyzer.h
  CondTools/RunInfo/plugins/FillInfoESAnalyzer.cc
  CondTools/RunInfo/plugins/LHCInfoESAnalyzer.cc
  CondTools/RunInfo/plugins/RunInfoESAnalyzer.cc
  CondTools/RunInfo/plugins/RunSummaryESAnalyzer.cc
  CondTools/RunInfo/plugins/XangleBetaStarFilter.cc
  CondTools/RunInfo/src/FillInfoPopConSourceHandler.cc
  CondTools/RunInfo/src/RunInfoRead.cc
  CondTools/RunInfo/src/RunSummaryHandler.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#35157 Migrate CondTools-Ecal modules to use esconsumes
  CondTools/Geometry/plugins/CSCRecoIdealDBLoader.cc
  CondTools/Geometry/plugins/DTRecoIdealDBLoader.cc
  CondTools/Geometry/plugins/GEMRecoIdealDBLoader.cc
  CondTools/Geometry/plugins/HcalParametersDBBuilder.cc
  CondTools/Geometry/plugins/ME0RecoIdealDBLoader.cc
  CondTools/Geometry/plugins/PCaloGeometryBuilder.cc
  CondTools/Geometry/plugins/PGeometricDetBuilder.cc
  CondTools/Geometry/plugins/PHGCalParametersDBBuilder.cc
  CondTools/Geometry/plugins/PTrackerParametersDBBuilder.cc
  CondTools/Geometry/plugins/RPCRecoIdealDBLoader.cc
  CondTools/Geometry/plugins/XMLGeometryReader.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#35148 [GCC11] Fix compilation warning for EcalMatacqDigi
  DataFormats/EcalDigi/interface/EcalMatacqDigi.h
  DataFormats/EcalDigi/src/classes_def.xml
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35154 HCAL Simulation : reformatted HF Shower Library for Run3
  Geometry/HcalSimData/python/HFParameters_cff.py
  SimCalorimetry/HcalSimProducers/python/hcalSimParameters_cfi.py
  SimG4CMS/Calo/src/HFShowerLibrary.cc
  SimG4CMS/ShowerLibraryProducer/interface/HcalForwardLibWriter.h
  SimG4CMS/ShowerLibraryProducer/plugins/HcalForwardLibWriter.cc
  SimG4CMS/ShowerLibraryProducer/test/README_SL_production_recipe.txt
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#35163 Fix laser correction timing error in Ecal DQM
  DQM/EcalMonitorTasks/interface/OccupancyTask.h
  DQM/EcalMonitorTasks/src/OccupancyTask.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#34932 Removed lexical_cast boost dependency in CondCore
  CondCore/AlignmentPlugins/test/testTrackerAlignmentPayloadInspector.cpp
  CondCore/BeamSpotPlugins/test/testBeamSpotPayloadInspector.cpp
  CondCore/DBOutputService/src/OnlineDBOutputService.cc
  CondCore/HLTPlugins/test/testAlCaRecoTriggerBitsPayloadInspector.cpp
  CondCore/RunInfoPlugins/test/testRunInfoPayloadInspector.cpp
  CondCore/SiPixelPlugins/interface/SiPixelGainCalibHelper.h
  CondCore/SiPixelPlugins/plugins/SiPixelFEDChannelContainer_PayloadInspector.cc
  CondCore/SiPixelPlugins/test/testSiPixelPayloadInspector.cpp
  CondCore/SiStripPlugins/plugins/SiStripApvGain_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripNoises_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripPedestals_PayloadInspector.cc
  CondCore/SiStripPlugins/test/testSiStripPayloadInspector.cpp
  CondCore/Utilities/bin/conddb_test_read.cpp
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/test/testPngHistograms.cpp
Labels: alca-approved, hlt-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#35172 Removed lexical_cast boost dependency in DQM
  DQM/HcalCommon/interface/HcalCommonHeaders.h
  DQM/L1TMonitor/interface/L1ExtraDQM.h
  DQM/SiStripCommissioningSources/src/PedsFullNoiseTask.cc
  DQMOffline/CalibTracker/plugins/SiStripBadComponentsDQMServiceReader.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35085 PPS: update scoring plane z positions
  Validation/CTPPS/python/simu_config/profile_2016_postTS2_cff.py
  Validation/CTPPS/python/simu_config/profile_2016_preTS2_cff.py
  Validation/CTPPS/python/simu_config/year_2017_cff.py
  Validation/CTPPS/python/simu_config/year_2018_cff.py
  Validation/CTPPS/python/simu_config/year_2021_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35106 Modernize `Configuration/Skimming` and `DPGAnalysis/Skims`
  Configuration/Skimming/interface/LeptonRecoSkim.h
  Configuration/Skimming/src/LeptonRecoSkim.cc
  Configuration/Skimming/src/LeptonSkimming.cc
  DPGAnalysis/Skims/interface/BeamSplash.h
  DPGAnalysis/Skims/interface/CSCSkim.h
  DPGAnalysis/Skims/interface/ECALActivity.h
  DPGAnalysis/Skims/interface/EcalSkim.h
  DPGAnalysis/Skims/interface/EcalTangentFilter.h
  DPGAnalysis/Skims/interface/FilterOutScraping.h
  DPGAnalysis/Skims/interface/FilterScrapingPixelProbability.h
  DPGAnalysis/Skims/interface/HLTInspect.h
  DPGAnalysis/Skims/interface/MatchedProbeMaker.h
  DPGAnalysis/Skims/interface/MuonPtFilter.h
  DPGAnalysis/Skims/interface/PhysDecl.h
  DPGAnalysis/Skims/interface/SelectHFMinBias.h
  DPGAnalysis/Skims/interface/TagProbeMassEDMFilter.h
  DPGAnalysis/Skims/interface/TagProbeMassProducer.h
  DPGAnalysis/Skims/src/CSCSkim.cc
  DPGAnalysis/Skims/src/EcalTangentFilter.cc
  DPGAnalysis/Skims/src/HCALHighEnergyFilter.cc
  DPGAnalysis/Skims/src/HcalHPDFilter.cc
  DPGAnalysis/Skims/src/NMaxPerLumi.cc
  DPGAnalysis/Skims/src/PickEvents.cc
  DPGAnalysis/Skims/src/RPCNoise.cc
  DPGAnalysis/Skims/src/RPCRecHitFilter.cc
  DPGAnalysis/Skims/src/RPCRecHitFilter.h
  DPGAnalysis/Skims/src/RecHitEnergyFilter.cc
  DPGAnalysis/Skims/src/SecondaryVertexFilter.cc
  DPGAnalysis/Skims/src/SelectHFMinBias.cc
  DPGAnalysis/Skims/src/SimpleJetFilter.cc
  DPGAnalysis/Skims/src/TagProbeMassProducer.cc
  DPGAnalysis/Skims/src/WZInterestingEventSelector.cc
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#35071 Remove unused headers in DataFormats package
  DataFormats/BTauReco/interface/PFCombinedTauTagInfo.h
  DataFormats/BTauReco/interface/PFIsolatedTauTagInfo.h
  DataFormats/BTauReco/interface/TrackIPData.h
  DataFormats/Common/interface/NewPolicy.h
  DataFormats/Common/interface/OwnArray.h
  DataFormats/Common/interface/TransientDataFrame.h
  DataFormats/Common/interface/debugging_allocator.h
  DataFormats/Common/test/OwnArray_t.cpp
  DataFormats/Common/test/testOwnArray.cc
  DataFormats/GeometrySurface/interface/private/extTkRotation.h
  DataFormats/GeometrySurface/interface/private/newTkRotation.h
  DataFormats/GeometryVector/interface/OnePiRange.h
  DataFormats/GeometryVector/interface/private/extBasic2DVector.h
  DataFormats/METReco/interface/PFClusterMETCollection.h
  DataFormats/Math/interface/SSEArray.h
  DataFormats/Math/interface/private/AVXVec.h
  DataFormats/ParticleFlowReco/interface/PFBlockElementFwd.h
  DataFormats/ParticleFlowReco/interface/PFBlockElementSuperClusterFwd.h
  DataFormats/ParticleFlowReco/interface/PFClusterShapeAssociation.h
  DataFormats/ParticleFlowReco/interface/PFParticleFwd.h
  DataFormats/ParticleFlowReco/interface/PFSuperClusterFwd.h
  DataFormats/ParticleFlowReco/interface/PFTrajectoryPointFwd.h
  DataFormats/Provenance/interface/BranchDescriptionIndex.h
  DataFormats/Provenance/interface/TypeInBranchType.h
  DataFormats/RPCDigi/interface/RPCDigiL1Linkfwd.h
  DataFormats/SiPixelDigi/interface/PixelDigiCollectionfwd.h
  DataFormats/SiStripCommon/interface/ConstantsForSummaryPlots.h
  DataFormats/SiStripDigi/interface/SiStripDigifwd.h
  DataFormats/TrackerRecHit2D/interface/SiPixelRecHitfwd.h
  DataFormats/TrajectorySeed/interface/BasicTrajectorySeed.h
Labels: core-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35104 [HGCAL] Adding comments in HGCAL associators
  SimCalorimetry/HGCalAssociatorProducers/plugins/LCToCPAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/LCToCPAssociatorByEnergyScoreImpl.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/LCToSCAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/LCToSCAssociatorByEnergyScoreImpl.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/TSToSimTSAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/TSToSimTSAssociatorByEnergyScoreImpl.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved

#35164 Fix laser correction timing error in Ecal DQM [CMSSW_11_3_X]
  DQM/EcalMonitorTasks/interface/OccupancyTask.h
  DQM/EcalMonitorTasks/src/OccupancyTask.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok

#35171 Fix laser correction timing error in Ecal DQM [CMSSW_12_0_X]
  DQM/EcalMonitorTasks/interface/OccupancyTask.h
  DQM/EcalMonitorTasks/src/OccupancyTask.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#35146 Run3-sim109 Temporary fix to switch off GeneralProcess for Run3
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/ParametrisedEMPhysics.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved

#35170 Run3-trk08X Provides namespace to all created solids/volumes (backport #35065)
  Geometry/TrackerCommonData/plugins/dd4hep/DDCutTubsFromPoints.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDPixBarLayerAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDPixBarLayerUpgradeAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDPixFwdDiskAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDPixPhase1FwdDiskAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECCoolAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECModuleAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECOptoHybAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECPhiAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTECPhiAltAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIBLayerAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIDAxialCableAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIDModuleAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIDModulePosAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTIDRingAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTOBAxCableAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTOBRadCableAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTOBRodAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerLinear.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerPhiAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerPhiAltAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerRingAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerXYZPosAlgo.cc
  Geometry/TrackerCommonData/plugins/dd4hep/DDTrackerZPosAlgo.cc
  Geometry/TrackerCommonData/test/python/dd4hepRun3_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved

#35166 [backport] Update generateGeometry script to python3
  Configuration/Geometry/python/generateGeometry.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#35169 Run3-sim91X Backport the xml files needed for a more correct Run3 geometry scenario definition
  Geometry/CMSCommonData/data/materials/2021/v3/materials.xml
  Geometry/TrackerCommonData/data/PhaseI/v3/pixbarmaterial.xml
  Geometry/VeryForwardData/data/CTPPS_2021/Stations/Simu/v3/CTPPS_210_Left_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2021/Stations/Simu/v3/CTPPS_210_Right_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2021/Stations/Simu/v3/CTPPS_220_Left_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2021/Stations/Simu/v3/CTPPS_220_Right_Station.xml
  Geometry/VeryForwardData/data/CTPPS_2021/Stations/Simu/v3/CTPPS_Stations_Assembly.xml
  Geometry/VeryForwardData/data/CTPPS_Diamond_2021/CTPPS_Diamond_Detector_Assembly/v1/CTPPS_Diamond_Detector_Assembly.xml
  Geometry/VeryForwardData/data/CTPPS_Pixel_2021/Modules/v2/PPS_Pixel_Module_2x2_Run3.xml
  Geometry/VeryForwardData/data/CTPPS_Pixel_2021/Modules/v2/PPS_Pixel_Sens.xml
  Geometry/VeryForwardData/data/CTPPS_Pixel_2021/Modules/v2/ppstrackerMaterials.xml
  Geometry/VeryForwardData/data/CTPPS_Timing_Horizontal_Pot/v2/CTPPS_Timing_Horizontal_Pot.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_000.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_001.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_002.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_003.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_004.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_005.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_020.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_021.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_022.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_023.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_024.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_025.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_100.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_101.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_102.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_103.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_104.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_105.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_120.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_121.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_122.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_123.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_124.xml
  Geometry/VeryForwardData/data/RP_Box/v3/RP_Box_125.xml
  Geometry/VeryForwardData/data/RP_Device/v1/RP_Device.xml
  Geometry/VeryForwardData/data/RP_Horizontal_Device/2021/Simu/v2/RP_Horizontal_Device.xml
  Geometry/VeryForwardData/data/RP_Hybrid/v2/RP_Hybrid.xml
  Geometry/VeryForwardData/data/RP_Materials/v4/RP_Materials.xml
  Geometry/VeryForwardData/data/RP_Vertical_Device/2021/Simu/v2/RP_Vertical_Device.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#35180 [10_6_X] Have embedded root files send close reports
  IOPool/Input/src/RootEmbeddedFileSequence.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, backport-ok

#35149 ECAL esConsumes migration various packages
  CondTools/Ecal/interface/ESDBCopy.h
  CondTools/Ecal/src/ESDBCopy.cc
  RecoEcal/EgammaCoreTools/interface/EcalClusterPUCleaningTools.h
  RecoEcal/EgammaCoreTools/src/EcalClusterPUCleaningTools.cc
  RecoHI/HiEgammaAlgos/interface/EcalClusterIsoCalculator.h
  RecoHI/HiEgammaAlgos/src/EcalClusterIsoCalculator.cc
  RecoTBCalo/EcalSimpleTBAnalysis/interface/EcalSimple2007H4TBAnalyzer.h
  RecoTBCalo/EcalSimpleTBAnalysis/src/EcalSimple2007H4TBAnalyzer.cc
  RecoTBCalo/EcalTBRecProducers/interface/EcalTBWeightUncalibRecHitProducer.h
  RecoTBCalo/EcalTBRecProducers/src/EcalTBWeightUncalibRecHitProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#35175 Removed boost lexical_cast dependency in OnlineDB
  OnlineDB/EcalCondDB/src/RunCrystalErrorsDat.cc
  OnlineDB/EcalCondDB/src/RunMemChErrorsDat.cc
  OnlineDB/EcalCondDB/src/RunMemTTErrorsDat.cc
  OnlineDB/EcalCondDB/src/RunPNErrorsDat.cc
  OnlineDB/EcalCondDB/src/RunTTErrorsDat.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#35190 Restore DataFormats/GeometrySurface/interface/private/extTkRotation.h
  DataFormats/GeometrySurface/interface/private/extTkRotation.h
Labels: simulation-pending, pending-signatures, tests-pending, orp-pending, code-checks-approved

#35165 Updating the radiation map to be used with GeometryExtended2026D86Reco
  SimCalorimetry/HGCalSimAlgos/test/HGCHEbackSignalScalerAnalyzer.cc
  SimCalorimetry/HGCalSimAlgos/test/hgchebacksignalscaler_cfg.py
  SimCalorimetry/HGCalSimAlgos/test/hgcsiNoiseMapTester_cfg.py
  SimCalorimetry/HGCalSimProducers/data/doseParams_3000fb_fluka-6.2.0.1.txt
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#35189 Remove boost lexical_cast dependency in CalibTracker
  CalibTracker/SiStripLorentzAngle/plugins/EnsembleCalibrationLA.cc
  CalibTracker/SiStripLorentzAngle/plugins/MeasureLA.cc
  CalibTracker/SiStripLorentzAngle/src/LA_Results.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35158 [HGCAL] Introduce SimTracksters linking
  RecoHGCal/TICL/plugins/SimTrackstersProducer.cc
  RecoHGCal/TICL/plugins/TrackstersFromCaloParticlesProducer.cc
  RecoHGCal/TICL/python/SimTracksters_cff.py
  Validation/HGCalValidation/python/HGCalValidator_cfi.py
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#35196 Migrate module config in Validation{RecoVertex} to use default cfipython
  Validation/RecoVertex/python/pvRecoSequence_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35191 Parallelize SeparateValidation
  Validation/RecoTrack/python/plotting/validation.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35183 Add TrackerAdditionalParametersPerDet_cfi to prevent exception in Tracker test script
  Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDDD_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#35176 ECAL esConsumes migration for remaining SimCalorimetry occurrences
  SimCalorimetry/EcalElectronicsEmulation/interface/EcalFEtoDigi.h
  SimCalorimetry/EcalElectronicsEmulation/src/EcalFEtoDigi.cc
  SimCalorimetry/EcalSelectiveReadoutProducers/interface/EcalSRCondTools.h
  SimCalorimetry/EcalSelectiveReadoutProducers/src/EcalSRCondTools.cc
  SimCalorimetry/EcalSimAlgos/interface/EcalSignalGenerator.h
  SimCalorimetry/EcalSimProducers/plugins/PreMixingEcalWorker.cc
  SimCalorimetry/EcalZeroSuppressionProducers/interface/EcalZeroSuppressionProducer.h
  SimCalorimetry/EcalZeroSuppressionProducers/src/EcalZeroSuppressionProducer.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35145 Add esConsumes to modules that inherit from TrackProducerBase
  RecoEgamma/EgammaPhotonProducers/src/TrackProducerWithSCAssociation.cc
  RecoTracker/TrackProducer/interface/KfTrackProducerBase.h
  RecoTracker/TrackProducer/interface/TrackProducerBase.h
  RecoTracker/TrackProducer/interface/TrackProducerBase.icc
  RecoTracker/TrackProducer/plugins/DAFTrackProducer.cc
  RecoTracker/TrackProducer/plugins/GsfTrackProducer.cc
  RecoTracker/TrackProducer/plugins/GsfTrackRefitter.cc
  RecoTracker/TrackProducer/plugins/TrackProducer.cc
  RecoTracker/TrackProducer/plugins/TrackProducer.h
  RecoTracker/TrackProducer/plugins/TrackRefitter.cc
  RecoTracker/TrackProducer/plugins/TrackRefitter.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35203 Susy gen fragment for trigger validation
  Configuration/Generator/python/SMS-Higgsino_mN2-170_mC1-160_mN1-150_HT60_TuneCP5_13TeV_pythia8_cfi.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35187 Run3-gex92X Add the modified scenarios for Run3
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2021FlatMinus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021FlatMinus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021FlatPlus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021FlatPlus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2021ZeroMaterialReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021FlatMinus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021FlatMinus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021FlatPlus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021FlatPlus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2021Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2021ZeroMaterialReco_cff.py
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#35186 Run3-hcx330 Make use of ESGetToken in DPGAnalysis/HcalTools
  DPGAnalysis/HcalTools/interface/CMTRawAnalyzer.h
  DPGAnalysis/HcalTools/plugins/BuildFile.xml
  DPGAnalysis/HcalTools/plugins/CMTRawAnalyzer.cc
  DPGAnalysis/HcalTools/test/remoteMonitoring_LED_eraTEST2019_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35151 esConsumes for PhotonProducer/GsfPhotonProducer
  RecoEgamma/EgammaPhotonAlgos/interface/PhotonEnergyCorrector.h
  RecoEgamma/EgammaPhotonAlgos/src/PhotonEnergyCorrector.cc
  RecoEgamma/EgammaPhotonProducers/src/PhotonProducer.cc
  RecoEgamma/EgammaTools/interface/EGEnergyCorrector.h
  RecoEgamma/EgammaTools/interface/EGEnergyCorrectorFactoryFromEventSetup.h
  RecoEgamma/EgammaTools/interface/egEnergyCorrectorFactoryFromRootFile.h
  RecoEgamma/EgammaTools/plugins/EGEnergyAnalyzer.cc
  RecoEgamma/EgammaTools/src/EGEnergyCorrector.cc
  RecoEgamma/EgammaTools/src/EGEnergyCorrectorFactoryFromEventSetup.cc
  RecoEgamma/EgammaTools/src/egEnergyCorrectorFactoryFromRootFile.cc
  RecoEgamma/PhotonIdentification/interface/PhotonIsolationCalculator.h
  RecoEgamma/PhotonIdentification/src/PhotonIsolationCalculator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35207 Update of HLT GTs for Run3
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35214 Revert "[10_6_X] Have embedded root files send close reports"
  IOPool/Input/src/RootEmbeddedFileSequence.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#35201 Handle more generator problems in external generator
  GeneratorInterface/Core/bin/externalGenerator.cc
  GeneratorInterface/Core/plugins/ExternalGeneratorFilter.cc
  GeneratorInterface/Core/test/BuildFile.xml
  GeneratorInterface/Core/test/FailingGeneratorFilter.cc
  GeneratorInterface/Core/test/test_FailingGeneratorFilter.sh
  GeneratorInterface/Core/test/test_FailingGeneratorFilter_cfg.py
Labels: generators-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#35204 Fixed exceptional case handling in SherpaHadronizer
  GeneratorInterface/SherpaInterface/src/SherpaHadronizer.cc
Labels: generators-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#35198 [Backport] Add fake alignment to tracker geometry test
  Geometry/TrackerGeometryBuilder/test/python/testTrackerHierarchy_cfg.py
  Geometry/TrackerGeometryBuilder/test/python/testTracker_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved

#35213 Revert "Have embedded root files send close reports"
  IOPool/Input/src/RootEmbeddedFileSequence.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35208 Cleanup of DTRecoUncertainties/DTRecoUncertaintiesRcd
  CalibMuon/DTCalibration/test/DBTools/DumpDBToFile.cc
  CalibMuon/DTCalibration/test/DBTools/DumpDBToFile.h
  CalibMuon/DTCalibration/test/DBTools/DumpFileToDB.cc
  CalibMuon/DTCalibration/test/DumpDBToFile_cfg.py
  CalibMuon/DTCalibration/test/DumpFileToDB_cfg.py
  Validation/DTRecHits/test/DTValidation_RelVal_fromRECO_local_cfg.py
Labels: alca-approved, dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35224 Remove throwing of test Exception in SherpaHadronizer
  GeneratorInterface/SherpaInterface/src/SherpaHadronizer.cc
Labels: generators-pending, pending-signatures, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#35173 Tracker Phase2 Digitizer framework update for BrickedPixel
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizer.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizer.h
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PixelBrickedDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PixelBrickedDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#35223 Fixed exceptional case handling in SherpaHadronizer [10_6]
  GeneratorInterface/SherpaInterface/src/SherpaHadronizer.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved

#35219 Fix signal in external generator [backport to 10_6]
  GeneratorInterface/Core/bin/externalGenerator.cc
  GeneratorInterface/Core/plugins/ExternalGeneratorFilter.cc
  GeneratorInterface/Core/test/BuildFile.xml
  GeneratorInterface/Core/test/FailingGeneratorFilter.cc
  GeneratorInterface/Core/test/test_FailingGeneratorFilter.sh
  GeneratorInterface/Core/test/test_FailingGeneratorFilter_cfg.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#35195 Migrate module configuration in RecoVertex to use default cfipython v2
  RecoVertex/BeamSpotProducer/python/BeamSpotOnline_cfi.py
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35052 Make GenHIEventProducer edm::global
  GeneratorInterface/HiGenCommon/plugins/GenHIEventProducer.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35057 Modernize BetaBoostEvtVtxGenerator
  GeneratorInterface/HiGenCommon/plugins/BetaBoostEvtVtxGenerator.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35218 DAQ optimized usage of FU file locking
  EventFilter/Utilities/interface/AuxiliaryMakers.h
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/interface/FedRawDataInputSource.h
  EventFilter/Utilities/plugins/DaqFakeReader.cc
  EventFilter/Utilities/plugins/DaqFakeReader.h
  EventFilter/Utilities/src/AuxiliaryMakers.cc
  EventFilter/Utilities/src/EvFDaqDirector.cc
  EventFilter/Utilities/src/FedRawDataInputSource.cc
  EventFilter/Utilities/test/LocalRunBUFU.sh
  EventFilter/Utilities/test/startBU.py
Labels: daq-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35200 [Backport] Add TrackerAdditionalParametersPerDet_cfi to prevent exception in Tracker test script
  Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDDD_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#35217 Run3-hcx331 Rearrange all plugins to the plugins directory in Calibration/HcalAlCaRecoProducers
  Calibration/HcalAlCaRecoProducers/BuildFile.xml
  Calibration/HcalAlCaRecoProducers/interface/AlCaEcalHcalReadoutsProducer.h
  Calibration/HcalAlCaRecoProducers/interface/AlCaHcalNoiseProducer.h
  Calibration/HcalAlCaRecoProducers/plugins/AlCaDiJetsProducer.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaEcalHcalReadoutsProducer.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaGammaJetProducer.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonProducer.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHOCalibProducer.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalNoiseProducer.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksProducer.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksProducerFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/BuildFile.xml
  Calibration/HcalAlCaRecoProducers/plugins/ProducerAnalyzer.cc
  Calibration/HcalAlCaRecoProducers/src/AlCaEcalHcalReadoutsProducer.cc
  Calibration/HcalAlCaRecoProducers/src/ProducerAnalyzer.h
  Calibration/HcalAlCaRecoProducers/src/SealModule.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35202 New Run3 offline GT
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#35137 Partial esConsumes migration for TrajectorySeedProducer
  FastSimulation/Tracking/interface/SeedFinderSelector.h
  FastSimulation/Tracking/plugins/TrajectorySeedProducer.cc
  FastSimulation/Tracking/src/SeedFinderSelector.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromOrderedHits.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGFromOrderedHits.h
  RecoMuon/TrackerSeedGenerator/plugins/TSGSmart.cc
  RecoMuon/TrackerSeedGenerator/plugins/TSGSmart.h
  RecoPixelVertexing/PixelLowPtUtilities/interface/LowPtClusterShapeSeedComparitor.h
  RecoPixelVertexing/PixelLowPtUtilities/plugins/ClusterShapeSeedComparitor.cc
  RecoPixelVertexing/PixelLowPtUtilities/src/LowPtClusterShapeSeedComparitor.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletLargeTipGenerator.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletLargeTipGenerator.h
  RecoTracker/SpecialSeedGenerators/interface/CosmicSeedCreator.h
  RecoTracker/SpecialSeedGenerators/src/CosmicSeedCreator.cc
  RecoTracker/TkSeedGenerator/interface/MultiHitGeneratorFromPairAndLayersFactory.h
  RecoTracker/TkSeedGenerator/interface/SeedCreator.h
  RecoTracker/TkSeedGenerator/interface/SeedCreatorFactory.h
  RecoTracker/TkSeedGenerator/interface/SeedCreatorFromRegionHitsEDProducerT.h
  RecoTracker/TkSeedGenerator/plugins/CombinedMultiHitGenerator.cc
  RecoTracker/TkSeedGenerator/plugins/MultiHitFromChi2EDProducer.cc
  RecoTracker/TkSeedGenerator/plugins/MultiHitGeneratorFromChi2.cc
  RecoTracker/TkSeedGenerator/plugins/MultiHitGeneratorFromChi2.h
  RecoTracker/TkSeedGenerator/plugins/SeedFromConsecutiveHitsCreator.cc
  RecoTracker/TkSeedGenerator/plugins/SeedFromConsecutiveHitsCreator.h
  RecoTracker/TkSeedGenerator/plugins/SeedFromConsecutiveHitsStraightLineCreator.cc
  RecoTracker/TkSeedGenerator/plugins/SeedFromConsecutiveHitsStraightLineCreator.h
  RecoTracker/TkSeedGenerator/plugins/SeedFromConsecutiveHitsTripletOnlyCreator.cc
  RecoTracker/TkSeedGenerator/plugins/SeedFromConsecutiveHitsTripletOnlyCreator.h
  RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromProtoTracksEDProducer.cc
  RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromProtoTracksEDProducer.h
  RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromRegionHitsEDProducer.cc
Labels: fastsim-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35199 Update of mkFit for 12_1_0_pre3
  RecoTracker/MkFit/README.md
  RecoTracker/MkFit/plugins/BuildFile.xml
  RecoTracker/MkFit/plugins/MkFitEventOfHitsProducer.cc
  RecoTracker/MkFit/plugins/createPhase1TrackerGeometry.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#35209 [HGCAL] Updates for dEdx weights calculation
  SimTracker/TrackerMaterialAnalysis/plugins/TrackingMaterialProducer.cc
  SimTracker/TrackerMaterialAnalysis/python/trackingMaterialProducerHGCal_cfi.py
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino_ForHGCalPhaseII.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35211 removed boost lexical_cast dependency
  Fireworks/Core/src/FWGeometryTableManagerBase.cc
  MagneticField/Engine/test/testMagneticField.cc
  MagneticField/GeomBuilder/src/volumeHandle.cc
Labels: reconstruction-approved, visualization-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35205 Update TrackReco HitPattern in light of GEM now including GE0
  DataFormats/TrackReco/interface/HitPattern.h
  DataFormats/TrackReco/src/HitPattern.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35197 [UBSAN] Fix overloaded enum in TemplatedSecondaryVertexTagInfo
  DataFormats/BTauReco/interface/TemplatedSecondaryVertexTagInfo.h
  DataFormats/BTauReco/src/classes_def.xml
  RecoBTag/SecondaryVertex/plugins/TemplatedSecondaryVertexProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35221 DAQ optimized usage of FU file locking (12_0_X backport)
  EventFilter/Utilities/interface/AuxiliaryMakers.h
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/interface/FedRawDataInputSource.h
  EventFilter/Utilities/plugins/DaqFakeReader.cc
  EventFilter/Utilities/plugins/DaqFakeReader.h
  EventFilter/Utilities/src/AuxiliaryMakers.cc
  EventFilter/Utilities/src/EvFDaqDirector.cc
  EventFilter/Utilities/src/FedRawDataInputSource.cc
  EventFilter/Utilities/test/LocalRunBUFU.sh
  EventFilter/Utilities/test/startBU.py
Labels: daq-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok

#35238 Properly set L1 and L2 values in CSCL1TPLookupTableEP
  CalibMuon/CSCCalibration/plugins/CSCL1TPLookupTableEP.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#35055 Utilities/StaticAnalyzer: Add base classes of producers to list of producers for a module
  Utilities/StaticAnalyzers/scripts/callgraph.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35168 Remove boost lexical_cast dependency in EventFilter
  EventFilter/L1TRawToDigi/src/MP7FileReader.cc
  EventFilter/Utilities/src/EvFDaqDirector.cc
  EventFilter/Utilities/src/FedRawDataInputSource.cc
Labels: l1-pending, daq-approved, reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved

#35230 Concurrently run beginStreams
  FWCore/Framework/src/EventProcessor.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#35220 Clear unrequired headers of boost lexical_cast
  GeneratorInterface/AMPTInterface/src/AMPTHadronizer.cc
  GeneratorInterface/HijingInterface/src/HijingHadronizer.cc
  GeneratorInterface/Hydjet2Interface/src/Hydjet2Hadronizer.cc
  GeneratorInterface/HydjetInterface/src/HydjetHadronizer.cc
  Geometry/CommonTopologies/test/ValidateRadial.cc
  HLTriggerOffline/Egamma/interface/EmDQM.h
  HLTriggerOffline/Egamma/src/EmDQM.cc
  MuonAnalysis/MomentumScaleCalibration/test/Macros/CompareRecoGenPt.C
  PhysicsTools/SelectorUtils/bin/testSelection_wplusjets.C
Labels: analysis-pending, dqm-approved, generators-approved, geometry-approved, reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved

#35056 Migrate FastSimulation modules to use esConsumes
  FastSimulation/Calorimetry/interface/CalorimetryManager.h
  FastSimulation/Calorimetry/src/CalorimetryManager.cc
  FastSimulation/EventProducer/interface/FamosManager.h
  FastSimulation/EventProducer/src/FamosManager.cc
  FastSimulation/EventProducer/src/FamosProducer.cc
  FastSimulation/MuonSimHitProducer/plugins/MuonSimHitProducer.cc
  FastSimulation/ShowerDevelopment/interface/FastHFShowerLibrary.h
  FastSimulation/ShowerDevelopment/src/FastHFShowerLibrary.cc
  FastSimulation/SimplifiedGeometryPropagator/interface/Geometry.h
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastTrackDeDxProducer.cc
  FastSimulation/SimplifiedGeometryPropagator/src/Geometry.cc
  FastSimulation/Tracking/plugins/TrackCandidateProducer.cc
  FastSimulation/TrackingRecHitProducer/interface/TrackingRecHitAlgorithm.h
  FastSimulation/TrackingRecHitProducer/plugins/FastTrackerRecHitMatcher.cc
  FastSimulation/TrackingRecHitProducer/plugins/TrackingRecHitProducer.cc
  FastSimulation/TrackingRecHitProducer/src/TrackingRecHitAlgorithm.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35242 [DEVEL] Delete unused FWCore/PyDevParameterSet/BuildFile.xml
  FWCore/PyDevParameterSet/BuildFile.xml
Labels: core-pending, pending-signatures, orp-pending, tests-started

#35081 Move "inverse of Bz at origin in GeV" from PixelRecoUtilities to MagneticField
  FastSimulation/Tracking/src/SeedFinderSelector.cc
  FastSimulation/TrajectoryManager/interface/LocalMagneticField.h
  FastSimulation/TrajectoryManager/src/LocalMagneticField.cc
  MagneticField/Engine/interface/MagneticField.h
  MagneticField/Engine/src/MagneticField.cc
  MagneticField/ParametrizedEngine/src/OAEParametrizedMagneticField.cc
  MagneticField/ParametrizedEngine/src/OAEParametrizedMagneticField.h
  MagneticField/ParametrizedEngine/src/ParabolicParametrizedMagneticField.cc
  MagneticField/ParametrizedEngine/src/ParabolicParametrizedMagneticField.h
  MagneticField/ParametrizedEngine/src/PolyFit2DParametrizedMagneticField.cc
  MagneticField/ParametrizedEngine/src/PolyFit2DParametrizedMagneticField.h
  MagneticField/UniformEngine/interface/UniformMagneticField.h
  MagneticField/VolumeBasedEngine/interface/VolumeBasedMagneticField.h
  MagneticField/VolumeBasedEngine/src/VolumeBasedMagneticField.cc
  MagneticField/VolumeGeometry/interface/MagCylinder.h
  MagneticField/VolumeGeometry/interface/MagVolume6Faces.h
  MagneticField/VolumeGeometry/src/MagCylinder.cc
  MagneticField/VolumeGeometry/src/MagVolume6Faces.cc
  RecoMuon/TrackerSeedGenerator/src/L1MuonPixelTrackFitter.cc
  RecoPixelVertexing/PixelLowPtUtilities/src/TrackFitter.cc
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelNtupletsFitterProducer.cc
  RecoPixelVertexing/PixelTrackFitting/src/KFBasedPixelFitter.cc
  RecoPixelVertexing/PixelTrackFitting/src/PixelFitterByConformalMappingAndLine.cc
  RecoPixelVertexing/PixelTrackFitting/src/PixelFitterByHelixProjections.cc
  RecoPixelVertexing/PixelTriplets/interface/CAHitQuadrupletGenerator.h
  RecoPixelVertexing/PixelTriplets/interface/CAHitTripletGenerator.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletCUDA.cc
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletEDProducerT.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletHLTGenerator.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletLargeTipGenerator.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletNoTipGenerator.cc
  RecoPixelVertexing/PixelTriplets/plugins/ThirdHitCorrection.cc
  RecoPixelVertexing/PixelTriplets/src/CAHitQuadrupletGenerator.cc
  RecoPixelVertexing/PixelTriplets/src/CAHitTripletGenerator.cc
  RecoTracker/ConversionSeedGenerators/plugins/HitPairGeneratorFromLayerPairForPhotonConversion.cc
  RecoTracker/ConversionSeedGenerators/plugins/HitPairGeneratorFromLayerPairForPhotonConversion.h
  RecoTracker/TkHitPairs/src/InnerDeltaPhi.cc
  RecoTracker/TkMSParametrization/interface/LongitudinalBendingCorrection.h
  RecoTracker/TkMSParametrization/interface/PixelRecoUtilities.h
  RecoTracker/TkMSParametrization/src/PixelRecoUtilities.cc
  RecoTracker/TkSeedGenerator/plugins/MultiHitGeneratorFromChi2.cc
  RecoTracker/TkTrackingRegions/interface/RectangularEtaPhiTrackingRegion.h
  RecoTracker/TkTrackingRegions/src/RectangularEtaPhiTrackingRegion.cc
  RecoVertex/KinematicFitPrimitives/test/KinematicState_t.cpp
  TrackPropagation/RungeKutta/interface/defaultRKPropagator.h
  TrackPropagation/RungeKutta/test/RKTest.cc
  TrackingTools/KalmanUpdators/test/KFUpdator_t.cpp
  TrackingTools/PatternTools/test/ClosestApproachInRPhi_t.cpp
  TrackingTools/TrajectoryState/test/testTSOS.cpp
Labels: fastsim-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35231 [CMSSW_12_0_X] Add new Run3 offline GT in autoCond and its relval workflow
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, backport-ok

#35232 [CMSSW_11_3_X] Add new Run3 offline GT in autoCond and its relval workflow
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#35233 Add new ECAL PF RecHit thresholds for 2021 Run 3 MC
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#35245 Cleanup Geant4 termination
  SimG4Core/Application/interface/RunManagerMT.h
  SimG4Core/Application/src/RunManagerMT.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35244 Miscellaneous graphical payload inspector fixes
  CondCore/AlignmentPlugins/plugins/TrackerAlignment_PayloadInspector.cc
  CondCore/HLTPlugins/plugins/AlCaRecoTriggerBits_PayloadInspector.cc
  CondCore/HLTPlugins/test/test.sh
  CondCore/SiPixelPlugins/interface/SiPixelTemplateHelper.h
Labels: hlt-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#35254 modernize `Alignment/TrackerAlignment`
  Alignment/TrackerAlignment/plugins/AlignmentPrescaler.cc
  Alignment/TrackerAlignment/plugins/AlignmentPrescaler.h
  Alignment/TrackerAlignment/plugins/BuildFile.xml
  Alignment/TrackerAlignment/plugins/TkAlCaOverlapTagger.cc
  Alignment/TrackerAlignment/plugins/TkAlCaSkimTreeMerger.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35239 [HGCAL] Updates on validation scripts
  Validation/Geometry/python/plot_hgcal_utils.py
  Validation/Geometry/test/runP_FromVertexUpToInFrontOfMuonStations_cfg.py
  Validation/HGCalValidation/python/html.py
  Validation/HGCalValidation/scripts/hgcalPerformanceValidation.py
Labels: dqm-approved, geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35080 Added missing esConsumes to DTTrackFinder
  L1Trigger/DTTrackFinder/interface/L1AbstractProcessor.h
  L1Trigger/DTTrackFinder/src/L1MuDTAssignmentUnit.cc
  L1Trigger/DTTrackFinder/src/L1MuDTAssignmentUnit.h
  L1Trigger/DTTrackFinder/src/L1MuDTERS.h
  L1Trigger/DTTrackFinder/src/L1MuDTEUX.h
  L1Trigger/DTTrackFinder/src/L1MuDTEtaProcessor.cc
  L1Trigger/DTTrackFinder/src/L1MuDTEtaProcessor.h
  L1Trigger/DTTrackFinder/src/L1MuDTExtrapolationUnit.cc
  L1Trigger/DTTrackFinder/src/L1MuDTExtrapolationUnit.h
  L1Trigger/DTTrackFinder/src/L1MuDTMuonSorter.h
  L1Trigger/DTTrackFinder/src/L1MuDTSEU.h
  L1Trigger/DTTrackFinder/src/L1MuDTSectorProcessor.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSectorProcessor.h
  L1Trigger/DTTrackFinder/src/L1MuDTSectorReceiver.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSectorReceiver.h
  L1Trigger/DTTrackFinder/src/L1MuDTTrackAssembler.h
  L1Trigger/DTTrackFinder/src/L1MuDTWedgeSorter.h
Labels: l1-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#35079 Migrate CondTools-Ecal modules to use esconsumes
  CondTools/Ecal/interface/EcalDBCopy.h
  CondTools/Ecal/interface/EcalGetLaserData.h
  CondTools/Ecal/interface/EcalPFRecHitThresholdsMaker.h
  CondTools/Ecal/plugins/TestEcalChannelStatusAnalyzer.cc
  CondTools/Ecal/src/EcalDBCopy.cc
  CondTools/Ecal/src/EcalGetLaserData.cc
  CondTools/Ecal/src/EcalPFRecHitThresholdsMaker.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#35023 Migrate Condtools-DT modules to esConsumes
  CondTools/DT/plugins/DTKeyedConfigDBDump.cc
  CondTools/DT/plugins/DTKeyedConfigDBDump.h
  CondTools/DT/plugins/DTKeyedConfigDBInit.h
  CondTools/DT/plugins/DTKeyedConfigPopConAnalyzer.cc
  CondTools/DT/plugins/DTUserKeyedConfigPopConAnalyzer.cc
  CondTools/DT/test/stubs/DTGeometryDump.cc
  CondTools/DT/test/stubs/DTGeometryDump.h
  CondTools/DT/test/stubs/DTHVDump.cc
  CondTools/DT/test/stubs/DTHVDump.h
  CondTools/DT/test/validate/DTCCBConfigValidateDBRead.cc
  CondTools/DT/test/validate/DTCCBConfigValidateDBRead.h
  CondTools/DT/test/validate/DTCompMapValidateDBRead.cc
  CondTools/DT/test/validate/DTCompMapValidateDBRead.h
  CondTools/DT/test/validate/DTDeadFlagValidateDBRead.cc
  CondTools/DT/test/validate/DTDeadFlagValidateDBRead.h
  CondTools/DT/test/validate/DTHVStatusValidateDBRead.cc
  CondTools/DT/test/validate/DTHVStatusValidateDBRead.h
  CondTools/DT/test/validate/DTLVStatusValidateDBRead.cc
  CondTools/DT/test/validate/DTLVStatusValidateDBRead.h
  CondTools/DT/test/validate/DTMtimeValidateDBRead.cc
  CondTools/DT/test/validate/DTMtimeValidateDBRead.h
  CondTools/DT/test/validate/DTPerformanceValidateDBRead.cc
  CondTools/DT/test/validate/DTPerformanceValidateDBRead.h
  CondTools/DT/test/validate/DTROMapValidateDBRead.cc
  CondTools/DT/test/validate/DTROMapValidateDBRead.h
  CondTools/DT/test/validate/DTRangeT0ValidateDBRead.cc
  CondTools/DT/test/validate/DTRangeT0ValidateDBRead.h
  CondTools/DT/test/validate/DTStatusFlagValidateDBRead.cc
  CondTools/DT/test/validate/DTStatusFlagValidateDBRead.h
  CondTools/DT/test/validate/DTT0ValidateDBRead.cc
  CondTools/DT/test/validate/DTT0ValidateDBRead.h
  CondTools/DT/test/validate/DTTPGParametersValidateDBRead.cc
  CondTools/DT/test/validate/DTTPGParametersValidateDBRead.h
  CondTools/DT/test/validate/DTTtrigValidateDBRead.cc
  CondTools/DT/test/validate/DTTtrigValidateDBRead.h
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#33885 Unify vertex association between CHS and PUPPI
  CommonTools/ParticleFlow/plugins/PFNoPileUpPacked.cc
  CommonTools/ParticleFlow/plugins/PFPileUp.cc
  CommonTools/ParticleFlow/plugins/PFPileUp.h
  CommonTools/ParticleFlow/plugins/SealModule.cc
  CommonTools/ParticleFlow/python/pfCHS_cff.py
  CommonTools/ParticleFlow/python/pfNoPileUpJME_cff.py
  CommonTools/ParticleFlow/python/pfPileUp_cfi.py
  CommonTools/PileupAlgos/plugins/PuppiProducer.cc
  CommonTools/PileupAlgos/plugins/PuppiProducer.h
  CommonTools/PileupAlgos/python/Puppi_cff.py
  CommonTools/PileupAlgos/test/recomputePuppiOnMiniAOD.py
  CommonTools/RecoAlgos/interface/PrimaryVertexAssignment.h
  CommonTools/RecoAlgos/plugins/PrimaryVertexSorter.cc
  CommonTools/RecoAlgos/plugins/PrimaryVertexSorter.h
  CommonTools/RecoAlgos/python/primaryVertexAssociation_cfi.py
  CommonTools/RecoAlgos/python/sortedPFPrimaryVertices_cfi.py
  CommonTools/RecoAlgos/python/sortedPackedPrimaryVertices_cfi.py
  CommonTools/RecoAlgos/python/sortedPrimaryVertices_cfi.py
  CommonTools/RecoAlgos/src/PrimaryVertexAssignment.cc
  PhysicsTools/PatAlgos/python/slimming/lostTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/slimming/puppiForMET_cff.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  PhysicsTools/PatAlgos/python/tools/jetCollectionTools.py
  PhysicsTools/PatAlgos/test/miniAOD/example_addJet.py
  PhysicsTools/PatAlgos/test/miniAOD/example_ei.py
  PhysicsTools/PatAlgos/test/miniAOD/example_jet_and_met.py
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
  RecoBTag/ONNXRuntime/python/pfDeepBoostedJet_cff.py
  RecoBTag/ONNXRuntime/python/pfDeepFlavour_cff.py
  RecoBTag/ONNXRuntime/python/pfParticleNetAK4_cff.py
  RecoBTag/ONNXRuntime/python/pfParticleNet_cff.py
  RecoJets/JetProducers/python/hepTopTaggerV2_cff.py
  RecoMET/Configuration/python/RecoPFMET_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35192 /validation/RecoEgamma PHASE2 modifications
  Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcFakeValidator.h
  Validation/RecoEgamma/plugins/ElectronMcMiniAODSignalValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcMiniAODSignalValidator.h
  Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcSignalValidator.h
  Validation/RecoEgamma/python/ElectronMcFakeValidator_gedGsfElectrons_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidatorMiniAOD_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidatorPt1000_gedGsfElectrons_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidator_gedGsfElectrons_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35182 Set numberOfConcurrentLuminosityBlocks to 1 for GEN steps that have EDModules that are not going to support concurrent lumis
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/Generator/python/concurrentLumisDisable.py
Labels: generators-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35215 Clean unused dependencies from BuildFiles
  CalibMuon/DTDigiSync/BuildFile.xml
  DQM/Physics/BuildFile.xml
  DataFormats/L1THGCal/BuildFile.xml
  FastSimulation/Utilities/BuildFile.xml
  L1Trigger/L1THGCal/BuildFile.xml
  L1Trigger/L1THGCal/test/BuildFile.xml
  L1Trigger/L1TTrackMatch/plugins/BuildFile.xml
  RecoLocalTracker/SiPixelDigiReProducers/plugins/BuildFile.xml
  RecoMuon/GlobalMuonProducer/test/BuildFile.xml
  SimCalorimetry/HcalZeroSuppressionProducers/BuildFile.xml
  SimG4CMS/EcalTestBeam/BuildFile.xml
  SimG4CMS/EcalTestBeam/plugins/BuildFile.xml
  SimG4CMS/FP420/BuildFile.xml
  SimG4CMS/FP420/plugins/BuildFile.xml
  SimG4CMS/Forward/BuildFile.xml
  SimG4CMS/Forward/plugins/BuildFile.xml
  SimG4CMS/ShowerLibraryProducer/BuildFile.xml
  SimG4CMS/ShowerLibraryProducer/plugins/BuildFile.xml
  SimGeneral/TrackingAnalysis/BuildFile.xml
  SimGeneral/TrackingAnalysis/plugins/BuildFile.xml
  SimMuon/MCTruth/test/BuildFile.xml
  SimTracker/TrackAssociation/BuildFile.xml
Labels: alca-approved, dqm-approved, fastsim-approved, l1-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#35253 Change current path in cmsExternalGenerator not cmsRun
  GeneratorInterface/Core/bin/externalGenerator.cc
  GeneratorInterface/Core/plugins/ExternalGeneratorFilter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35095 Finish esConsumes migration for L1TMuonBarrelTrackProducer
  L1Trigger/L1TMuonBarrel/interface/L1AbstractProcessor.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMAssignmentUnit.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMERS.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMEUX.cc
  L1Trigger/L1TMuonBarrel/src/L1MuBMEUX.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMEtaProcessor.cc
  L1Trigger/L1TMuonBarrel/src/L1MuBMEtaProcessor.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMExtrapolationUnit.cc
  L1Trigger/L1TMuonBarrel/src/L1MuBMExtrapolationUnit.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMMuonSorter.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMSEU.cc
  L1Trigger/L1TMuonBarrel/src/L1MuBMSEU.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMSectorProcessor.cc
  L1Trigger/L1TMuonBarrel/src/L1MuBMSectorReceiver.cc
  L1Trigger/L1TMuonBarrel/src/L1MuBMSectorReceiver.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMTrackAssembler.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMWedgeSorter.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35184 Added esConsumes calls to code in RecoLocalMuon
  CalibMuon/DTCalibration/plugins/DTTPAnalyzer.cc
  CalibMuon/DTCalibration/plugins/DTTTrigCalibration.cc
  CalibMuon/DTCalibration/plugins/DTTTrigCalibration.h
  CalibMuon/DTCalibration/plugins/DTVDriftCalibration.cc
  CalibMuon/DTCalibration/plugins/DTVDriftCalibration.h
  CalibMuon/DTDigiSync/interface/DTTTrigSyncFactory.h
  CalibMuon/DTDigiSync/plugins/DTTTrigSyncFromDB.cc
  CalibMuon/DTDigiSync/plugins/DTTTrigSyncT0Only.cc
  CalibMuon/DTDigiSync/plugins/DTTTrigSyncTOFCorr.cc
  DQM/DTMonitorModule/src/DTLocalTriggerSynchTask.cc
  L1Trigger/DTTriggerPhase2/plugins/CalibratedDigis.cc
  RecoLocalMuon/DTRecHit/BuildFile.xml
  RecoLocalMuon/DTRecHit/interface/DTRecHitAlgoFactory.h
  RecoLocalMuon/DTRecHit/interface/DTRecHitBaseAlgo.h
  RecoLocalMuon/DTRecHit/plugins/DTLinearDriftAlgo.cc
  RecoLocalMuon/DTRecHit/plugins/DTLinearDriftAlgo.h
  RecoLocalMuon/DTRecHit/plugins/DTLinearDriftFromDBAlgo.cc
  RecoLocalMuon/DTRecHit/plugins/DTLinearDriftFromDBAlgo.h
  RecoLocalMuon/DTRecHit/plugins/DTNoDriftAlgo.cc
  RecoLocalMuon/DTRecHit/plugins/DTNoDriftAlgo.h
  RecoLocalMuon/DTRecHit/plugins/DTParametrizedDriftAlgo.cc
  RecoLocalMuon/DTRecHit/plugins/DTParametrizedDriftAlgo.h
  RecoLocalMuon/DTRecHit/plugins/DTRecHitProducer.cc
  RecoLocalMuon/DTRecHit/plugins/DTRecHitProducer.h
  RecoLocalMuon/DTRecHit/src/DTRecHitBaseAlgo.cc
  RecoLocalMuon/DTSegment/src/DTCombinatorialExtendedPatternReco.cc
  RecoLocalMuon/DTSegment/src/DTCombinatorialExtendedPatternReco.h
  RecoLocalMuon/DTSegment/src/DTCombinatorialPatternReco.cc
  RecoLocalMuon/DTSegment/src/DTCombinatorialPatternReco.h
  RecoLocalMuon/DTSegment/src/DTCombinatorialPatternReco4D.cc
  RecoLocalMuon/DTSegment/src/DTCombinatorialPatternReco4D.h
  RecoLocalMuon/DTSegment/src/DTMeantimerPatternReco.cc
  RecoLocalMuon/DTSegment/src/DTMeantimerPatternReco.h
  RecoLocalMuon/DTSegment/src/DTMeantimerPatternReco4D.cc
  RecoLocalMuon/DTSegment/src/DTMeantimerPatternReco4D.h
  RecoLocalMuon/DTSegment/src/DTRecSegment2DAlgoFactory.h
  RecoLocalMuon/DTSegment/src/DTRecSegment2DExtendedProducer.cc
  RecoLocalMuon/DTSegment/src/DTRecSegment2DExtendedProducer.h
  RecoLocalMuon/DTSegment/src/DTRecSegment2DProducer.cc
  RecoLocalMuon/DTSegment/src/DTRecSegment2DProducer.h
  RecoLocalMuon/DTSegment/src/DTRecSegment4DAlgoFactory.h
  RecoLocalMuon/DTSegment/src/DTRecSegment4DProducer.cc
  RecoLocalMuon/DTSegment/src/DTRefitAndCombineReco4D.cc
  RecoLocalMuon/DTSegment/src/DTRefitAndCombineReco4D.h
  RecoLocalMuon/DTSegment/src/DTSegment4DT0Corrector.cc
  RecoLocalMuon/DTSegment/src/DTSegmentUpdator.cc
  RecoLocalMuon/DTSegment/src/DTSegmentUpdator.h
  RecoLocalMuon/DTSegment/test/DTAnalyzerDetailed.cc
  RecoLocalMuon/DTSegment/test/DTAnalyzerDetailed.h
  RecoLocalMuon/DTSegment/test/DTMeanTimer.cc
  RecoLocalMuon/DTSegment/test/DTMeanTimer.h
  RecoLocalMuon/DTSegment/test/DTSegAnalyzer.cc
  RecoLocalMuon/DTSegment/test/DTSegAnalyzer.h
Labels: alca-approved, dqm-approved, l1-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#35228 Added esConsumes to HBHERecHitProducerGPU
  RecoLocalCalo/HcalRecProducers/src/HBHERecHitProducerGPU.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35241 Run3-hcx320 Use of ESGetToken in RecoLocalCalo/HcalRecAlgos (replacing #35234)
  RecoLocalCalo/HcalRecAlgos/src/HBHEIsolatedNoiseAlgos.cc
  RecoLocalCalo/HcalRecAlgos/test/HcalRecHitReflagger.cc
  RecoLocalCalo/HcalRecAlgos/test/HcalSevLvlAnalyzer.cc
  RecoLocalCalo/HcalRecAlgos/test/MahiDebugger.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35179 ECAL esConsumes migration of remaining file in RecoMET
  RecoMET/METFilters/plugins/EcalDeadCellDeltaRFilter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35266 `Alignment/OfflineValidation` improvements from CRUZET'21 data analysis
  Alignment/OfflineValidation/plugins/BuildFile.xml
  Alignment/OfflineValidation/plugins/DMRChecker.cc
  Alignment/OfflineValidation/plugins/GeneralPurposeTrackAnalyzer.cc
  DQM/TrackerRemapper/interface/Phase1PixelMaps.h
  DQM/TrackerRemapper/src/Phase1PixelMaps.cc
  DQM/TrackerRemapper/src/Phase1PixelROCMaps.cc
  DQM/TrackerRemapper/src/Phase1PixelSummaryMap.cc
Labels: alca-approved, dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35265 modernize `SiStripDetInfoFileWriter`
  CalibTracker/SiStripCommon/plugins/SealModules.cc
  CalibTracker/SiStripCommon/plugins/SiStripDetInfoFileWriter.cc
  CalibTracker/SiStripCommon/plugins/SiStripDetInfoFileWriter.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35240 Run3-alca199 Split HOCalibAnalyzer.cc to take out the post analysis part in separate macros
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksFilter.cc
  Calibration/HcalCalibAlgos/macros/hocalib_pl18.C
  Calibration/HcalCalibAlgos/macros/hocalib_tmpfit.C
  Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35167 Remove unused headers for RECO & SIM packages
  RecoEgamma/EgammaTools/interface/ConversionTools.h
  RecoEgamma/EgammaTools/interface/EffectiveAreas.h
  RecoHI/HiJetAlgos/interface/UECalibration.h
  RecoJets/JetAnalyzers/doc/myJetAna.html
  RecoJets/JetAnalyzers/interface/CaloTowerBoundries.h
  RecoJets/JetAnalyzers/interface/MyCluster.h
  RecoJets/JetAnalyzers/interface/myFilter.h
  RecoJets/JetAnalyzers/interface/myJetAna.h
  RecoJets/JetAnalyzers/test/myFilter.cc
  RecoJets/JetAnalyzers/test/myJetAna.cc
  RecoLocalCalo/EcalRecAlgos/interface/EcalUncalibRecHitLeadingEdgeAlgo.h
  RecoMuon/TrackingTools/interface/MuonSeedDetLayer.h
  RecoTracker/SpecialSeedGenerators/interface/EtaPhiMeasurementEstimator.h
  RecoTracker/TkMSParametrization/interface/rangesIntersect.h
  RecoTracker/TrackProducer/interface/GsfTrackProducerAlgorithm.h
  RecoTracker/TransientTrackingRecHit/interface/GSTransientTrackingRecHit.h
  RecoVertex/ConfigurableVertexReco/interface/ReconstructorFromLinPtFinder.h
  RecoVertex/KinematicFit/interface/CombinedKinematicConstraintT.h
  RecoVertex/LinearizationPointFinders/interface/MonteCarloLinearizationPointFinder.h
  RecoVertex/LinearizationPointFinders/src/MonteCarloLinearizationPointFinder.cc
  SimCalorimetry/CaloSimAlgos/interface/CaloVNoisifier.h
  SimDataFormats/RPCDigiSimLink/interface/RPCDigiSimLinkfwd.h
  SimDataFormats/TrackerDigiSimLink/interface/PixelDigiSimLinkfwd.h
  SimDataFormats/TrackerDigiSimLink/interface/StripCompactDigiSimLinksfwd.h
  SimDataFormats/TrackerDigiSimLink/interface/StripDigiSimLinkfwd.h
  SimG4CMS/Calo/interface/HcalTestHistoClass.h
  SimG4Core/Application/interface/DDDWorldObserver.h
  SimG4Core/Notification/interface/ComponentBuilder.h
  SimG4Core/Notification/interface/ComponentFactoryByName.h
  SimG4Core/Notification/interface/DispatchableG4Step.h
  SimG4Core/Notification/interface/OwnIt.h
Labels: reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35086 fix undefined behavior in `MultiTrackValidator`
  Validation/RecoTrack/plugins/MultiTrackValidator.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35267 [12_0_X] Add new ECAL PF RecHit thresholds for 2021 Run 3 MC
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#35210 Run3-gex92Z Small fixes and adding several material files in view of G4 testing with new reference versions
  Configuration/Geometry/README.md
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/EcalCommonData/data/ectkcablemat/2026/v2/ectkcablemat.xml
  Geometry/TrackerCommonData/data/tecmaterial/2021/v2/tecmaterial.xml
  Geometry/TrackerCommonData/data/tibmaterial/2021/v2/tibmaterial.xml
  Geometry/TrackerCommonData/data/tibtidcommonmaterial/2021/v2/tibtidcommonmaterial.xml
  Geometry/TrackerCommonData/data/tidmaterial/2021/v2/tidmaterial.xml
  Geometry/TrackerCommonData/data/tobmaterial/2021/v2/tobmaterial.xml
  Geometry/TrackerCommonData/data/trackermaterial/2021/v2/trackermaterial.xml
  Geometry/TrackerCommonData/data/trackermaterial/2026/v1/trackermaterial.xml
  Geometry/TrackerCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/TrackerCommonData/python/cmsExtendedGeometry2026D77XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#34985 Add SiStripCalCosmics ALCANANO
  CalibTracker/SiStripCommon/BuildFile.xml
  CalibTracker/SiStripCommon/interface/SiStripOnTrackClusterTableProducerBase.h
  CalibTracker/SiStripCommon/plugins/BuildFile.xml
  CalibTracker/SiStripCommon/plugins/SealModules.cc
  CalibTracker/SiStripCommon/plugins/SiStripLorentzAngleRunInfoTableProducer.cc
  CalibTracker/SiStripCommon/plugins/SiStripPositionCorrectionsTableProducer.cc
  CalibTracker/SiStripCommon/src/SiStripOnTrackClusterTableProducerBase.cc
  CalibTracker/SiStripCommon/test/MakeCalibrationTrees/produceCalibrationTree_CosmicsLABP_cfg.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalCosmicsNano_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalCosmicsNano_cff.py
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/DataProcessing/test/run_CfgTest.sh
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
  PhysicsTools/NanoAOD/test/inspectNanoFile.py
Labels: alca-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved

#35271 complete esConsumes migration of `Alignment/CommonAlignmentProducer`
  Alignment/CommonAlignmentProducer/interface/AlignmentTrackSelector.h
  Alignment/CommonAlignmentProducer/plugins/AlignmentMuonHIPTrajectorySelector.cc
  Alignment/CommonAlignmentProducer/plugins/GlobalTrackerMuonAlignment.cc
  Alignment/CommonAlignmentProducer/src/AlignmentTrackSelector.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved
