Repository cms-sw/cmssw, pull requests merged in 2021-12, with the labels that each got.

#36305 Modernize `CalibMuon/CSCCalibration`
  CalibMuon/CSCCalibration/test/stubs/CSCIndexerAnalyzer.cc
  CalibMuon/CSCCalibration/test/stubs/CSCIndexerAnalyzer2.cc
  CalibMuon/CSCCalibration/test/stubs/CSCMapperTestPostls1.cc
  CalibMuon/CSCCalibration/test/stubs/CSCMapperTestStartup.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36254 Modification on r-phi distribution plots and fix on under/overflow bins in GEM onlineDQM, a backport to 12_0_X
  DQM/GEM/interface/GEMDQMBase.h
  DQM/GEM/interface/GEMDigiSource.h
  DQM/GEM/plugins/GEMDQMHarvester.cc
  DQM/GEM/plugins/GEMDigiSource.cc
  DQM/GEM/plugins/GEMRecHitSource.cc
  DQM/GEM/src/GEMDQMBase.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#36292 Bugfix for Egamma PFID with DNNs
  RecoParticleFlow/PFProducer/src/PFEGammaFilters.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36286 [121X] Add label for SiPixelQualityRcd in RawToDigi
  CalibTracker/SiPixelESProducers/plugins/SiPixelQualityESProducer.cc
  CalibTracker/SiPixelESProducers/python/SiPixelQualityESProducer_cfi.py
  Configuration/ProcessModifiers/python/siPixelQualityRawToDigi_cff.py
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc
  EventFilter/SiPixelRawToDigi/python/SiPixelRawToDigi_cfi.py
Labels: alca-approved, operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#36304 Add new PF Calibration to mcRun3 and mcRun4 GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36275 First version of nanoDQMIO content
  DQM/CTPPS/plugins/CTPPSDiamondDQMSource.cc
  DQM/CTPPS/python/ctppsDQM_cff.py
  DQM/CTPPS/python/diamondSampicDQMSource_cfi.py
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36122 Fix for FastSim decays of exotic-descendent SM particles decaying outside pipe
  FastSimulation/SimplifiedGeometryPropagator/interface/ParticleManager.h
  FastSimulation/SimplifiedGeometryPropagator/src/ParticleManager.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36297 Updated SimProducer for ECAL
  Validation/EcalHits/interface/EcalPreshowerSimHitsValidation.h
  Validation/EcalHits/interface/EcalSimHitsValidation.h
  Validation/EcalHits/python/ecalPreshowerSimHitsValidation_cfi.py
  Validation/EcalHits/python/ecalSimHitsValidation_cfi.py
  Validation/EcalHits/src/EcalPreshowerSimHitsValidation.cc
  Validation/EcalHits/src/EcalSimHitsValidProducer.cc
  Validation/EcalHits/src/EcalSimHitsValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#36312 Avoid nested dead assignments, as reported by the static analyzer
  Validation/EcalHits/src/EcalBarrelSimHitsValidation.cc
  Validation/EcalHits/src/EcalEndcapSimHitsValidation.cc
  Validation/EcalHits/src/EcalSimHitsValidProducer.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36174 Changes in HGCal geometry vs flatfile comparison
  Validation/HGCalValidation/plugins/HGCalWaferValidation.cc
  Validation/HGCalValidation/test/python/testHGCalWaferValidation_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36215 Fully implement fishbone in patatrack
  CUDADataFormats/Track/interface/TrackSoAHeterogeneousT.h
  DataFormats/Math/interface/choleskyInversion.h
  DataFormats/Math/test/BuildFile.xml
  DataFormats/Math/test/CholeskyInvert_t.cpp
  DataFormats/Math/test/CholeskyInvert_t.cu
  DataFormats/Math/test/simpleCholeskyTest.cu
  Geometry/TrackerGeometryBuilder/interface/phase1PixelTopology.h
  Geometry/TrackerGeometryBuilder/test/BuildFile.xml
  Geometry/TrackerGeometryBuilder/test/phase1PixelTopology_t.cu
  RecoPixelVertexing/PixelTrackFitting/interface/BrokenLine.h
  RecoPixelVertexing/PixelTriplets/plugins/BrokenLineFitOnGPU.cc
  RecoPixelVertexing/PixelTriplets/plugins/BrokenLineFitOnGPU.cu
  RecoPixelVertexing/PixelTriplets/plugins/BrokenLineFitOnGPU.h
  RecoPixelVertexing/PixelTriplets/plugins/CAConstants.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.cc
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.cu
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernelsImpl.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorOnGPU.cc
  RecoPixelVertexing/PixelTriplets/plugins/GPUCACell.h
  RecoPixelVertexing/PixelTriplets/plugins/HelixFitOnGPU.h
  RecoPixelVertexing/PixelTriplets/plugins/RiemannFitOnGPU.cc
  RecoPixelVertexing/PixelTriplets/plugins/RiemannFitOnGPU.cu
  RecoPixelVertexing/PixelTriplets/plugins/gpuFishbone.h
  RecoPixelVertexing/PixelTriplets/plugins/gpuPixelDoubletsAlgos.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuVertexFinder.cc
  Validation/RecoTrack/python/TrackValidation_cff.py
Labels: dqm-approved, geometry-approved, reconstruction-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved, heterogeneous-approved

#36293 ECAL : corrections in the condition tools code : ThreadSafety, Dead store
  CondTools/Ecal/interface/EcalChannelStatusHandler.h
  CondTools/Ecal/interface/EcalErrorMask.h
  CondTools/Ecal/src/EcalChannelStatusHandler.cc
  CondTools/Ecal/src/EcalDAQHandler.cc
  CondTools/Ecal/src/EcalDCSHandler.cc
  CondTools/Ecal/src/EcalErrorMask.cc
  CondTools/Ecal/src/EcalTPGBadStripHandler.cc
  CondTools/Ecal/src/EcalTPGBadTTHandler.cc
  CondTools/Ecal/src/EcalTPGBadXTHandler.cc
  CondTools/Ecal/src/EcalTPGFineGrainEBGroupHandler.cc
  CondTools/Ecal/src/EcalTPGFineGrainEBIdMapHandler.cc
  CondTools/Ecal/src/EcalTPGFineGrainStripEEHandler.cc
  CondTools/Ecal/src/EcalTPGFineGrainTowerEEHandler.cc
  CondTools/Ecal/src/EcalTPGLinConstHandler.cc
  CondTools/Ecal/src/EcalTPGLutGroupHandler.cc
  CondTools/Ecal/src/EcalTPGLutIdMapHandler.cc
  CondTools/Ecal/src/EcalTPGOddWeightGroupHandler.cc
  CondTools/Ecal/src/EcalTPGOddWeightIdMapHandler.cc
  CondTools/Ecal/src/EcalTPGPedestalsHandler.cc
  CondTools/Ecal/src/EcalTPGPhysicsConstHandler.cc
  CondTools/Ecal/src/EcalTPGSlidingWindowHandler.cc
  CondTools/Ecal/src/EcalTPGSpikeThresholdHandler.cc
  CondTools/Ecal/src/EcalTPGTPModeHandler.cc
  CondTools/Ecal/src/EcalTPGWeightGroupHandler.cc
  CondTools/Ecal/src/EcalTPGWeightIdMapHandler.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36307 [DD4hep] Remove unused PPS materials from Run 3 2021 (replaces #36163)
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
  Geometry/TrackerCommonData/data/FlatMinus05Percent/2021/v1/pixbarmaterial.xml
  Geometry/TrackerCommonData/data/FlatMinus10Percent/2021/v1/pixbarmaterial.xml
  Geometry/TrackerCommonData/data/FlatPlus05Percent/2021/v1/pixbarmaterial.xml
  Geometry/TrackerCommonData/data/FlatPlus10Percent/2021/v1/pixbarmaterial.xml
  Geometry/TrackerCommonData/data/zeroMaterial/2021/v2/pixbarmaterial.xml
  Geometry/VeryForwardData/data/RP_Materials/v5/RP_Materials.xml
  Geometry/VeryForwardData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/VeryForwardGeometry/data/dd4hep/v5/geometryRPFromDD_2021.xml
  Geometry/VeryForwardGeometry/python/dd4hep/geometryRPFromDD_2021_cfi.py
  Geometry/VeryForwardGeometry/python/dd4hep/v5/geometryRPFromDD_2021_cfi.py
  Geometry/VeryForwardGeometry/python/geometryRPFromDD_2021_cfi.py
  Geometry/VeryForwardGeometry/python/geometryRPFromDD_2022_cfi.py
  Geometry/VeryForwardGeometry/python/v3/geometryRPFromDD_2021_cfi.py
  Geometry/VeryForwardGeometry/python/v3/geometryRPFromDD_2022_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36324 FastSim LL fix missing ! in beam pipe radius check.
  FastSimulation/SimplifiedGeometryPropagator/src/ParticleManager.cc
Labels: fastsim-approved, fully-signed, tests-started, orp-approved, code-checks-approved

#36318 Bug fix: Issue with nVertices in L2NNTagTauProducer
  RecoTauTag/HLTProducers/src/L2TauTagNNProducer.cc
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36285 update working point for new DNN
  RecoTracker/IterativeTracking/python/dnnQualityCuts.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#36223 Read out the CSC cathode shower in TMB/OTMB (HadronicShowerTrigger-9)
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCTriggerPrimitivesBuilder.h
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCTriggerPrimitivesBuilder.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36046 Minor update in the CSC/GEM-CSC trigger for Run-3: split regular ALCT-CLCT off from ALCT-CLCT-GEM matching
  DQM/L1TMonitorClient/src/L1TdeCSCTPGClient.cc
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/GEMClusterProcessor.h
  L1Trigger/CSCTriggerPrimitives/python/params/tmbParams.py
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/GEMClusterProcessor.cc
  L1Trigger/CSCTriggerPrimitives/test/CSCTriggerPrimitivesAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveProducer_cfg.py
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36216 Fix the slope return value in CSCGEMMatcher::calculateGEMCSCBending
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMatcher.cc
Labels: l1-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#36317 Updating ECAL Module Class Inheritance
  CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/interface/EcnaAnalyzer.h
  CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/EcnaAnalyzer.cc
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalLaserAnalyzerYousi.cc
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalMatacqAnalyzer.h
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalPerEvtMatacqAnalyzer.h
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalStatusAnalyzer.h
  CalibCalorimetry/EcalLaserSorting/interface/LaserSorter.h
  CalibCalorimetry/EcalLaserSorting/src/LaserSorter.cc
  CalibCalorimetry/EcalPedestalOffsets/interface/testChannel.h
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamReaderFromDB.cc
  CalibCalorimetry/EcalTPGTools/plugins/testEcalTPGScale.h
  Calibration/EcalAlCaRecoProducers/plugins/PUDumper.cc
  Calibration/EcalAlCaRecoProducers/plugins/PUDumper.h
  Calibration/EcalAlCaRecoProducers/src/ValueMapTraslator.cc
  Calibration/EcalCalibAlgos/interface/ElectronCalibration.h
  Calibration/EcalCalibAlgos/interface/ElectronRecalibSuperClusterAssociator.h
  Calibration/EcalCalibAlgos/interface/miscalibExample.h
  Calibration/EcalCalibAlgos/plugins/SealModule.cc
  Calibration/EcalCalibAlgos/python/electronRecalibSCAssociator_cfi.py
  Calibration/EcalCalibAlgos/src/ElectronRecalibSuperClusterAssociator.cc
  Calibration/EcalCalibAlgos/src/miscalibExample.cc
  CondTools/Ecal/plugins/EcalPedestalHistory.cc
  CondTools/Ecal/plugins/EcalPedestalHistory.h
Labels: l1-pending, alca-approved, pending-signatures, tests-approved, db-approved, orp-approved, code-checks-approved

#36309 fix handling of nano steps in Patatrack workflows
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#36328 CSC L1T DQM 2D summary plots: Flip the two endcaps on the y-axis
  DQM/L1TMonitor/src/L1TStage2Shower.cc
  DQM/L1TMonitor/src/L1TdeCSCTPG.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36331 [DQM] nanoDQMIO change in V0.1
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36332 `SiPixelFakeLorentzAngleESSource`: use built-in `appendToDataLabel` mechanism
  CalibTracker/SiPixelESProducers/plugins/SiPixelFakeLorentzAngleESSource.cc
  CalibTracker/SiPixelESProducers/test/testSiPixelFakeLorentzAngleESSource_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36330 Static Analyzer: Update EventSetupRecord::get report to included modules not mapped to packages.
  Utilities/StaticAnalyzers/scripts/callgraph.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36340 empty line cleanup in /IterativeTracking dnnQualityCuts.py
  RecoTracker/IterativeTracking/python/dnnQualityCuts.py
Labels: reconstruction-pending, pending-signatures, tests-pending, orp-pending, code-checks-approved

#36314 Fixed static analysis warnings in SimG4Core
  SimG4Core/Application/interface/GFlashEMShowerModel.h
  SimG4Core/Application/interface/RunManagerMT.h
  SimG4Core/Application/interface/RunManagerMTWorker.h
  SimG4Core/Application/src/GFlashEMShowerModel.cc
  SimG4Core/Application/src/GFlashHadronShowerModel.cc
  SimG4Core/Application/src/RunManagerMT.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/CustomPhysics/interface/CustomParticleFactory.h
  SimG4Core/CustomPhysics/src/CustomParticleFactory.cc
  SimG4Core/CustomPhysics/src/CustomPhysicsList.cc
  SimG4Core/CustomPhysics/src/CustomPhysicsListSS.cc
  SimG4Core/CustomPhysics/src/G4ProcessHelper.cc
  SimG4Core/GFlash/interface/GflashEMShowerModel.h
  SimG4Core/GFlash/src/GflashEMShowerModel.cc
  SimG4Core/GFlash/src/GflashHadronShowerModel.cc
  SimG4Core/Geometry/interface/CustomUIsession.h
  SimG4Core/Geometry/src/CustomUIsession.cc
  SimG4Core/Geometry/src/DDDWorld.cc
  SimG4Core/Geometry/src/DDG4ProductionCuts.cc
  SimG4Core/MagneticField/src/Field.cc
  SimG4Core/PhysicsLists/src/MonopoleTransportation.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36326 Update Run3 offline data GT and mcRun3 GTs with final DD4HEP
  Configuration/AlCa/python/autoCond.py
  Configuration/AlCa/python/autoCondModifiers.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, code-checks-approved, trk-dpg-approved

#36334 Update miscalibration tools in `CondTools/SiStrip`
  CondTools/SiStrip/plugins/SiStripChannelGainFromDBMiscalibrator.cc
  CondTools/SiStrip/plugins/SiStripNoisesFromDBMiscalibrator.cc
  CondTools/SiStrip/test/SiStripChannelGainFromDBMiscalibrator_cfg.py
  CondTools/SiStrip/test/SiStripNoiseFromDBMiscalibrator_cfg.py
  CondTools/SiStrip/test/testBuildersReaders.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36315 [12.1.X] Update of mkFit as in 12_2_0_pre3 (backport of PR #36246)
  RecoTracker/MkFit/plugins/MkFitIterationConfigESProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external, backport-ok

#36341 implement step skipping more consistently for Patatrack workflows
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, urgent, upgrade-approved, code-checks-approved

#36327 backport DNN cuts for mkFit 12_2_0_pre3
  RecoTracker/IterativeTracking/python/dnnQualityCuts.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external, backport-ok

#36308 First version of nanoDQMIO content [12_1_X]
  DQM/CTPPS/plugins/CTPPSDiamondDQMSource.cc
  DQM/CTPPS/python/ctppsDQM_cff.py
  DQM/CTPPS/python/diamondSampicDQMSource_cfi.py
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent

#36329 [12_1_X] Add PilotBeam data in relval matrix and update Run3 data offline GT
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_cff.py
Labels: l1-pending, alca-approved, dqm-approved, operations-approved, pending-signatures, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, backport-ok

#36268 [GEM] GEMAMC13 DataFormats bugfix
  DataFormats/GEMDigi/interface/GEMAMC13.h
  DataFormats/GEMDigi/interface/GEMAMCStatus.h
Labels: simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#36214 Migrate JetMET and PF codes to new PoolDBOutputService methods
  CondTools/JetMET/plugins/BuildFile.xml
  CondTools/JetMET/plugins/JetCorrectorDBReader.cc
  CondTools/JetMET/plugins/JetCorrectorDBWriter.cc
  CondTools/JetMET/plugins/JetResolutionDBReader.cc
  CondTools/JetMET/plugins/JetResolutionDBWriter.cc
  CondTools/JetMET/plugins/METCorrectorDBReader.cc
  CondTools/JetMET/plugins/METCorrectorDBWriter.cc
  CondTools/JetMET/plugins/QGLikelihoodDBReader.cc
  CondTools/JetMET/plugins/QGLikelihoodDBWriter.cc
  CondTools/JetMET/plugins/QGLikelihoodSystematicsDBReader.cc
  CondTools/JetMET/plugins/QGLikelihoodSystematicsDBWriter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36294 DAQ - adding DCS validity bitfield for high voltage in FED 1022
  DataFormats/OnlineMetaData/interface/DCSRecord.h
  DataFormats/OnlineMetaData/interface/OnlineMetaDataRaw.h
  DataFormats/OnlineMetaData/src/DCSRecord.cc
  DataFormats/OnlineMetaData/src/classes_def.xml
  DataFormats/OnlineMetaData/test/dump_run000001_event1350583585_fed1022.txt
  DataFormats/OnlineMetaData/test/onlineMetaDataRecord_t.cpp
  EventFilter/OnlineMetaDataRawToDigi/plugins/OnlineMetaDataRawToDigi.cc
Labels: daq-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36342 Phase2-hgx297A Simplify and correct the test script for validation against the flat file
  Validation/HGCalValidation/test/python/testHGCalWaferValidation_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36345 Clean-up of BeamSpot PCL configs
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProd_cff.py
  Calibration/TkAlCaRecoProducers/python/AlcaBeamSpotProducerHP_cfi.py
  Calibration/TkAlCaRecoProducers/python/AlcaBeamSpotProducer_cfi.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36333 Phase2 tracker cabling map: add IT cabling map
  CondTools/SiPhase2Tracker/plugins/DTCCablingMapProducer.cc
  CondTools/SiPhase2Tracker/test/DTCCablingMapProducer_dump.py
  CondTools/SiPhase2Tracker/test/DTCCablingMapProducer_retrieve.py
  CondTools/SiPhase2Tracker/test/DTCCablingMapProducer_write.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved

#36301 Run3-sim99 Make use of unique_ptr in the codes of SimG4CMS/Calo
  SimG4CMS/Calo/interface/HFGflash.h
  SimG4CMS/Calo/interface/HFShowerLibrary.h
  SimG4CMS/Calo/src/EvolutionECAL.cc
  SimG4CMS/Calo/src/HCalSD.cc
  SimG4CMS/Calo/src/HFGflash.cc
  SimG4CMS/Calo/src/HFShowerLibrary.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36361 fix `CondDB` connection in `CondTools/SiStrip` miscalibration tools
  CondTools/SiStrip/test/SiStripChannelGainFromDBMiscalibrator_cfg.py
  CondTools/SiStrip/test/SiStripNoiseFromDBMiscalibrator_cfg.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36362 `CondTools/HLT` fix mistake done in #36129
  CondTools/HLT/plugins/AlCaRecoTriggerBitsRcdRead.cc
  CondTools/HLT/test/AlCaRecoTriggerBitsRcdRead_TEMPL_cfg.py
Labels: hlt-approved, fully-signed, tests-approved, db-approved, bug-fix, orp-approved, code-checks-approved

#36346 Initialisation of CaloParticle data members
  SimDataFormats/CaloAnalysis/interface/CaloParticle.h
  SimDataFormats/CaloAnalysis/interface/SimCluster.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36350 More Nano step-related fixes for Run3/Phase2 workflows
  Configuration/Eras/python/Era_Run3_cff.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, urgent, upgrade-approved, code-checks-approved

#36379 Set RootInputFileSequence::usedFallback_ properly
  IOPool/Input/src/RootInputFileSequence.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36367 DB output migration of RPCReadOutMapBuilder
  CondFormats/RPCObjects/test/RPCReadOutMapBuilder.cc
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36202 MTD reconstruction: time back-propagation accounting for variable speed along trajectory
  RecoMTD/TimingIDTools/plugins/TOFPIDProducer.cc
  RecoMTD/TrackExtender/plugins/TrackExtenderWithMTD.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36238 Factory for adding UserHooks to PythiaHadronizer and SUEP decay pythia Hook
  GeneratorInterface/Pythia8Interface/interface/CustomHook.h
  GeneratorInterface/Pythia8Interface/interface/SuepShower.h
  GeneratorInterface/Pythia8Interface/plugins/BuildFile.xml
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/plugins/SuepDecay.cc
  GeneratorInterface/Pythia8Interface/plugins/SuepDecay.h
  GeneratorInterface/Pythia8Interface/src/CustomHookFactory.cc
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36365 [ASAN] fix unit tests by setting NO_TEST_PREFIX flag for ASAN IB
  CondCore/Utilities/test/BuildFile.xml
Labels: fully-signed, tests-rejected, db-approved, orp-approved, code-checks-approved

#36377 Inclusion of new ECAL PF cluster corrections in Run-3 MC GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#36321 Use thread safe modules in DPGAnalysis/SiStripTools
  DPGAnalysis/SiStripTools/plugins/APVCyclePhaseDebuggerFromL1TS.cc
  DPGAnalysis/SiStripTools/plugins/APVCyclePhaseMonitor.cc
  DPGAnalysis/SiStripTools/plugins/APVCyclePhaseProducerFromL1ABC.cc
  DPGAnalysis/SiStripTools/plugins/APVShotsAnalyzer.cc
  DPGAnalysis/SiStripTools/plugins/APVShotsFilter.cc
  DPGAnalysis/SiStripTools/plugins/BigEventsDebugger.cc
  DPGAnalysis/SiStripTools/plugins/CommonModeAnalyzer.cc
  DPGAnalysis/SiStripTools/plugins/ConfigurableAPVCyclePhaseProducer.cc
  DPGAnalysis/SiStripTools/plugins/DetIdSelectorTest.cc
  DPGAnalysis/SiStripTools/plugins/DuplicateRecHits.cc
  DPGAnalysis/SiStripTools/plugins/EventTimeDistribution.cc
  DPGAnalysis/SiStripTools/plugins/EventWithHistoryProducer.cc
  DPGAnalysis/SiStripTools/plugins/FEDBadModuleFilter.cc
  DPGAnalysis/SiStripTools/plugins/FromClusterSummaryMultiplicityProducer.cc
  DPGAnalysis/SiStripTools/plugins/L1ABCDebugger.cc
  DPGAnalysis/SiStripTools/plugins/LargeEvents.cc
  DPGAnalysis/SiStripTools/plugins/MultiplicityCorrelator.cc
  DPGAnalysis/SiStripTools/plugins/MultiplicityInvestigator.cc
  DPGAnalysis/SiStripTools/plugins/MultiplicityProducer.cc
  DPGAnalysis/SiStripTools/plugins/MultiplicityTimeCorrelations.cc
  DPGAnalysis/SiStripTools/plugins/OccupancyPlots.cc
  DPGAnalysis/SiStripTools/plugins/OverlapProblemTPAnalyzer.cc
  DPGAnalysis/SiStripTools/plugins/OverlapProblemTSOSAnalyzer.cc
  DPGAnalysis/SiStripTools/plugins/OverlapProblemTSOSPositionFilter.cc
  DPGAnalysis/SiStripTools/plugins/SeedMultiplicityAnalyzer.cc
  DPGAnalysis/SiStripTools/plugins/SiPixelQualityHistory.cc
  DPGAnalysis/SiStripTools/plugins/SiStripDetWithSomething.cc
  DPGAnalysis/SiStripTools/plugins/SiStripQualityHistory.cc
  DPGAnalysis/SiStripTools/plugins/TrackCount.cc
  DPGAnalysis/SiStripTools/plugins/TrackerDpgAnalysis.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#36180 PPS fixes in using DBOutputService followup
  CondTools/CTPPS/plugins/PPSTimingCalibrationWriter.cc
  CondTools/CTPPS/plugins/WriteCTPPSBeamParameters.cc
  CondTools/CTPPS/src/CTPPSRPAlignmentInfoAnalyzer.cc
  CondTools/CTPPS/src/WriteCTPPSPixGainCalibrations.cc
  CondTools/CTPPS/src/WriteCTPPSPixelAnalysisMask.cc
  CondTools/CTPPS/src/WriteCTPPSPixelDAQMapping.cc
  CondTools/Geometry/plugins/PPSGeometryBuilder.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36371 ECAL - Fix static analyzer issues in CalibCalorimetry/EcalLaserAnalyzer
  CalibCalorimetry/EcalLaserAnalyzer/interface/ME.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/MEEEGeom.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/MEGeom.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/MELaserPrim.h
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalLaserAnalyzer.cc
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalLaserAnalyzer.h
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalLaserAnalyzer2.cc
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalLaserAnalyzer2.h
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalLaserAnalyzerYousi.cc
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalPerEvtLaserAnalyzer.cc
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalTestPulseAnalyzer.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/ME.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/MEEEGeom.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/MEGeom.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/MELaserPrim.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/PulseFitWithFunction.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/PulseFitWithShape.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/TFParams.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/TMatacq.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/TPNCor.cc
  CalibCalorimetry/EcalLaserAnalyzer/src/TShapeAnalysis.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36348 Apply Naming Rules to `BeamSpotOnlineObjects` methods
  CondCore/BeamSpotPlugins/plugins/BeamSpotOnline_PayloadInspector.cc
  CondFormats/BeamSpotObjects/interface/BeamSpotOnlineObjects.h
  CondFormats/BeamSpotObjects/src/BeamSpotOnlineObjects.cc
  CondTools/BeamSpot/plugins/BeamSpotOnlineRecordsReader.cc
  CondTools/BeamSpot/plugins/BeamSpotOnlineRecordsWriter.cc
  CondTools/BeamSpot/src/BeamSpotOnlinePopConSourceHandler.cc
  DQM/BeamMonitor/plugins/BeamMonitor.cc
  DQM/BeamMonitor/plugins/BeamSpotDipServer.cc
  DQM/BeamMonitor/plugins/FakeBeamMonitor.cc
  RecoVertex/BeamSpotProducer/plugins/OnlineBeamSpotESProducer.cc
Labels: alca-approved, dqm-approved, reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36373 Remove import test for qtconsole
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#36389 Conddb tools: fix for authorization settings
  CondCore/Utilities/scripts/conddb
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, code-checks-approved

#36376 Run3-hcx329 move std::cout to edm::LogVerbatim for the codes of Geometry/HcalTowerAlgo amd also update the cfg's
  Geometry/HcalTowerAlgo/src/CaloTowerHardcodeGeometryLoader.cc
  Geometry/HcalTowerAlgo/src/HcalDDDGeometry.cc
  Geometry/HcalTowerAlgo/src/HcalDDDGeometryLoader.cc
  Geometry/HcalTowerAlgo/src/HcalFlexiHardcodeGeometryLoader.cc
  Geometry/HcalTowerAlgo/src/HcalGeometry.cc
  Geometry/HcalTowerAlgo/src/HcalHardcodeGeometryLoader.cc
  Geometry/HcalTowerAlgo/test/CaloTowerGeometryAnalyzer.cc
  Geometry/HcalTowerAlgo/test/HcalCellParameterDump.cc
  Geometry/HcalTowerAlgo/test/HcalCellSizeCheck.cc
  Geometry/HcalTowerAlgo/test/HcalDetIdTester.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryAnalyzer.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryDetIdAnalyzer.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryDetIdTester.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryDump.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryPlan1Tester.cc
  Geometry/HcalTowerAlgo/test/HcalGeometryTester.cc
  Geometry/HcalTowerAlgo/test/python/runCaloTowerGeometryAnalyzer_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalCellDumpDD4hep_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalCellDumpDDD_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalCellSizeCheck_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalDetIdTester_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalGeometryAnalyzer_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalGeometryDBAnalyzer_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalGeometryDetIdAnalyzer_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalGeometryDetIdTester_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalGeometryDump_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalGeometryPlan1Tester_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalGeometryTester_cfg.py
  Geometry/HcalTowerAlgo/test/python/runHcalTransGeometryAnalyzer_cfg.py
  Geometry/HcalTowerAlgo/test/runHcalCellDumpDD4hep_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36384 Run3-gex102A Replace std:cout with LogVerbatim in Geometry/EcalCommonData
  Geometry/EcalCommonData/plugins/DDEcalBarrelAlgo.cc
  Geometry/EcalCommonData/plugins/DDEcalBarrelNewAlgo.cc
  Geometry/EcalCommonData/src/DDEcalEndcapTrap.cc
  Geometry/EcalCommonData/src/EcalBarrelNumberingScheme.cc
  Geometry/EcalCommonData/test/EcalSimParametersAnalyzer.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36392 add PixelTrack quality monitoring to `SiPixelPhase1MonitorTrackSoA`
  DQM/SiPixelPhase1Heterogeneous/plugins/SiPixelPhase1MonitorTrackSoA.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36382 Modernize HcalPatternSource.cc and HtrXmlPattern.cc
  IORawData/CaloPatterns/src/HcalPatternSource.cc
  IORawData/CaloPatterns/src/HcalPatternSource.h
  IORawData/CaloPatterns/src/HtrXmlPattern.cc
  IORawData/CaloPatterns/src/HtrXmlPattern.h
  IORawData/CaloPatterns/src/Module.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36296 DAQ - adding DCS validity bitfield for high voltage in FED 1022 (12_1_X backport)
  DataFormats/OnlineMetaData/interface/DCSRecord.h
  DataFormats/OnlineMetaData/interface/OnlineMetaDataRaw.h
  DataFormats/OnlineMetaData/src/DCSRecord.cc
  DataFormats/OnlineMetaData/src/classes_def.xml
  DataFormats/OnlineMetaData/test/dump_run000001_event1350583585_fed1022.txt
  DataFormats/OnlineMetaData/test/onlineMetaDataRecord_t.cpp
  EventFilter/OnlineMetaDataRawToDigi/plugins/OnlineMetaDataRawToDigi.cc
Labels: daq-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved

#35967 Concurrently run beginStreams
  FWCore/Framework/src/EventProcessor.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36370 PR12_2 L1T Correlation Conditions in uGT with overlap removal logic - original design
  L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondition.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36380 [12_2_X] Inclusion of new ECAL PF cluster corrections in Run-3 MC GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#36402 Replace Candidate GT by named GT in conddb script unit tests and update offline Run-3 data GT
  CondCore/Utilities/test/test_conddb.sh
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36257 PPS global alignment - reformat
  CalibPPS/AlignmentGlobal/BuildFile.xml
  CalibPPS/AlignmentGlobal/README.md
  CalibPPS/AlignmentGlobal/interface/utils.h
  CalibPPS/AlignmentGlobal/plugins/BuildFile.xml
  CalibPPS/AlignmentGlobal/plugins/PPSAlignmentHarvester.cc
  CalibPPS/AlignmentGlobal/plugins/PPSAlignmentWorker.cc
  CalibPPS/AlignmentGlobal/src/utils.cc
  CalibPPS/AlignmentGlobal/test/README.md
  CalibPPS/AlignmentGlobal/test/run_analysis_cfg.py
  CalibPPS/ESProducers/plugins/BuildFile.xml
  CalibPPS/ESProducers/plugins/PPSAlignmentConfigESSource.cc
  CalibPPS/ESProducers/plugins/PPSAlignmentConfigurationESSource.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondFormats/PPSObjects/interface/PPSAlignmentConfig.h
  CondFormats/PPSObjects/src/PPSAlignmentConfig.cc
  CondTools/CTPPS/plugins/RetrievePPSAlignmentConfig.cc
  CondTools/CTPPS/plugins/WritePPSAlignmentConfig.cc
  CondTools/CTPPS/test/retrieve_PPSAlignmentConfig_cfg.py
  CondTools/CTPPS/test/write_PPSAlignmentConfig_cfg.py
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36018 uGT framework and L1 ntuples for showers in the muon system for Run-3 (HadronicShowerTrigger-8)
  DataFormats/L1TGlobal/interface/GlobalObject.h
  DataFormats/L1TGlobal/src/GlobalObject.cc
  L1Trigger/CSCTriggerPrimitives/README.md
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMatcher.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/GEMClusterProcessor.cc
  L1Trigger/L1TGlobal/interface/GlobalBoard.h
  L1Trigger/L1TGlobal/interface/GlobalDefinitions.h
  L1Trigger/L1TGlobal/interface/MuonShowerCondition.h
  L1Trigger/L1TGlobal/interface/MuonShowerTemplate.h
  L1Trigger/L1TGlobal/interface/TriggerMenu.h
  L1Trigger/L1TGlobal/plugins/BXVectorInputProducer.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.h
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.h
  L1Trigger/L1TGlobal/python/simGtStage2Digis_cfi.py
  L1Trigger/L1TGlobal/src/GlobalBoard.cc
  L1Trigger/L1TGlobal/src/GlobalCondition.cc
  L1Trigger/L1TGlobal/src/MuonShowerCondition.cc
  L1Trigger/L1TGlobal/src/MuonShowerTemplate.cc
  L1Trigger/L1TGlobal/src/TriggerMenu.cc
  L1Trigger/L1TGlobal/src/classes.h
  L1Trigger/L1TGlobal/src/classes_def.xml
  L1Trigger/L1TNtuples/interface/L1AnalysisL1Upgrade.h
  L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeDataFormat.h
  L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeTfMuonShower.h
  L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeTfMuonShowerDataFormat.h
  L1Trigger/L1TNtuples/plugins/L1UpgradeTfMuonShowerTreeProducer.cc
  L1Trigger/L1TNtuples/plugins/L1UpgradeTreeProducer.cc
  L1Trigger/L1TNtuples/python/L1NtupleRAW_cff.py
  L1Trigger/L1TNtuples/python/l1UpgradeTfMuonShowerTree_cfi.py
  L1Trigger/L1TNtuples/python/l1UpgradeTree_cfi.py
  L1Trigger/L1TNtuples/src/L1AnalysisL1Upgrade.cc
  L1Trigger/L1TNtuples/src/L1AnalysisL1UpgradeTfMuonShower.cc
  L1Trigger/L1TNtuples/src/classes.h
  L1Trigger/L1TNtuples/src/classes_def.xml
Labels: l1-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#36403 Silence file closuring printouts in StatisticsSenderService by default
  Utilities/StorageFactory/src/StatisticsSenderService.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36287 forward compression settings if fast cloning is disabled on first file of a merge
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
  IOPool/Output/interface/PoolOutputModule.h
  IOPool/Output/src/PoolOutputModule.cc
  IOPool/Output/src/RootOutputFile.cc
  IOPool/Output/src/RootOutputTree.cc
  IOPool/Output/src/RootOutputTree.h
Labels: core-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36385 Improve many SwitchProducer unit tests
  FWCore/Integration/test/run_TestSwitchProducer.sh
  FWCore/Integration/test/testSwitchProducerAliasToNonExistent_cfg.py
  FWCore/Integration/test/testSwitchProducerPathFilter_cfg.py
  FWCore/Integration/test/testSwitchProducerPath_cfg.py
  FWCore/Integration/test/testSwitchProducerTaskInput_cfg.py
  FWCore/Integration/test/testSwitchProducerTask_cfg.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36412 Fixing bug in case last file is bad
  IOPool/Input/src/RootPrimaryFileSequence.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36394 Run3-sim100 Update a few dumping code and several cfg's in SimG4CMS/Calo
  SimG4CMS/Calo/src/EcalDumpGeometry.cc
  SimG4CMS/Calo/src/HcalDumpGeometry.cc
  SimG4CMS/Calo/test/python/ddd_SingleMuon_Step1_cfg.py
  SimG4CMS/Calo/test/python/runEcalGeom_cfg.py
  SimG4CMS/Calo/test/python/runEcalSimHitStudy_cfg.py
  SimG4CMS/Calo/test/python/runEta13_cfg.py
  SimG4CMS/Calo/test/python/runEta2_cfg.py
  SimG4CMS/Calo/test/python/runEta37_cfg.py
  SimG4CMS/Calo/test/python/runEta7_cfg.py
  SimG4CMS/Calo/test/python/runHF6_cfg.py
  SimG4CMS/Calo/test/python/runHFDDD_cfg.py
  SimG4CMS/Calo/test/python/runHcalGeom_cfg.py
  SimG4CMS/Calo/test/python/runHcalSimHitAnalysis_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36407 Run3-sim100A Modify the cfg's in SimG4Core test areas in view of change in the Era definition
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step2_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step3_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step4_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step5_cfg.py
  SimG4Core/PhysicsLists/test/minbias_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36413 Modernize `OnlineDB/SiStrip*`
  OnlineDB/SiStripESSources/test/stubs/SealModule.cc
  OnlineDB/SiStripESSources/test/stubs/testSiStripGainBuilderFromDb.cc
  OnlineDB/SiStripESSources/test/stubs/testSiStripGainBuilderFromDb.h
  OnlineDB/SiStripESSources/test/stubs/test_AnalyzeCabling.cc
  OnlineDB/SiStripESSources/test/stubs/test_AnalyzeCabling.h
  OnlineDB/SiStripESSources/test/stubs/test_FedCablingBuilder.cc
  OnlineDB/SiStripESSources/test/stubs/test_FedCablingBuilder.h
  OnlineDB/SiStripESSources/test/stubs/test_NoiseBuilder.cc
  OnlineDB/SiStripESSources/test/stubs/test_NoiseBuilder.h
  OnlineDB/SiStripESSources/test/stubs/test_PedestalsBuilder.cc
  OnlineDB/SiStripESSources/test/stubs/test_PedestalsBuilder.h
  OnlineDB/SiStripO2O/plugins/SiStripPayloadHandler.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36399 Moved modules in PhysicsTools/PatExamples to be thread-friendly
  PhysicsTools/PatExamples/plugins/JetEnergyShift.cc
  PhysicsTools/PatExamples/plugins/MuonAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatBJetTagAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatBJetTrackAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatBJetVertexAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatBTagAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatBasicAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatElectronAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatJPsiProducer.cc
  PhysicsTools/PatExamples/plugins/PatJetAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatMCMatching.cc
  PhysicsTools/PatExamples/plugins/PatMCMatchingExtended.cc
  PhysicsTools/PatExamples/plugins/PatTauAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatTopSelectionAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatTrackAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatTriggerAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatTriggerTagAndProbe.cc
  PhysicsTools/PatExamples/plugins/PatVertexAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatZToMuMuAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatZjetsElectronAnalyzer.cc
  PhysicsTools/PatExamples/plugins/PatZjetsJetAnalyzer.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#36396 Add data-vs-emulator plots for L1T shower DQM
  DQM/L1TMonitor/interface/L1TdeCSCTPGShower.h
  DQM/L1TMonitor/interface/L1TdeStage2Shower.h
  DQM/L1TMonitor/plugins/SealModule.cc
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
  DQM/L1TMonitor/python/L1TdeCSCTPGShower_cfi.py
  DQM/L1TMonitor/python/L1TdeStage2EMTF_cff.py
  DQM/L1TMonitor/python/L1TdeStage2Shower_cfi.py
  DQM/L1TMonitor/src/L1TdeCSCTPGShower.cc
  DQM/L1TMonitor/src/L1TdeStage2Shower.cc
  DQM/L1TMonitorClient/interface/L1TdeCSCTPGShowerClient.h
  DQM/L1TMonitorClient/interface/L1TdeStage2ShowerClient.h
  DQM/L1TMonitorClient/python/L1TStage2EMTFEmulatorClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2EmulatorMonitorClient_cff.py
  DQM/L1TMonitorClient/python/L1TdeCSCTPGShowerClient_cfi.py
  DQM/L1TMonitorClient/python/L1TdeStage2ShowerClient_cfi.py
  DQM/L1TMonitorClient/src/L1TdeCSCTPGShowerClient.cc
  DQM/L1TMonitorClient/src/L1TdeStage2ShowerClient.cc
  DQM/L1TMonitorClient/src/SealModule.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36393 Validation/RecoEgamma Code simplification v1
  Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcMiniAODSignalValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcSignalPostValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc
  Validation/RecoEgamma/test/ElectronMcFakePostValidation_cfg.py
  Validation/RecoEgamma/test/ElectronMcFakeValidation_gedGsfElectrons_cfg.py
  Validation/RecoEgamma/test/ElectronMcSignalPostValidationMiniAOD_cfg.py
  Validation/RecoEgamma/test/ElectronMcSignalPostValidationPt1000_cfg.py
  Validation/RecoEgamma/test/ElectronMcSignalPostValidation_cfg.py
  Validation/RecoEgamma/test/ElectronMcSignalValidationMiniAOD_cfg.py
  Validation/RecoEgamma/test/ElectronMcSignalValidationPt1000_gedGsfElectrons_cfg.py
  Validation/RecoEgamma/test/ElectronMcSignalValidation_gedGsfElectrons_cfg.py
  Validation/RecoEgamma/test/electronValidationCheck_Env.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#35627 (Un)packers for hadronic showers at the uGMT input and output
  DQM/L1TMonitor/src/L1TStage2Shower.cc
  DataFormats/L1TMuon/interface/RegionalMuonShower.h
  DataFormats/L1TMuon/src/RegionalMuonShower.cc
  DataFormats/L1TMuon/src/classes_def.xml
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/CommonTokens.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GMTCollections.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GMTCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GMTSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GMTTokens.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GMTTokens.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/L1TObjectCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/MuonPacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/MuonPacker.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTPacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTPacker.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTUnpacker.h
  EventFilter/L1TRawToDigi/python/gmtStage2Raw_cfi.py
  L1Trigger/L1TMuon/interface/MuonRawDigiTranslator.h
  L1Trigger/L1TMuon/interface/RegionalMuonRawDigiTranslator.h
  L1Trigger/L1TMuon/python/simDigis_cff.py
  L1Trigger/L1TMuon/src/MuonRawDigiTranslator.cc
  L1Trigger/L1TMuon/src/RegionalMuonRawDigiTranslator.cc
  L1Trigger/L1TMuonEndCap/interface/SectorProcessorShower.h
  L1Trigger/L1TMuonEndCap/src/SectorProcessorShower.cc
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36176 Improve buffer allocation and copies for SiPixelDigisCUDA
  CUDADataFormats/SiPixelCluster/interface/SiPixelClustersCUDA.h
  CUDADataFormats/SiPixelCluster/src/SiPixelClustersCUDA.cc
  CUDADataFormats/SiPixelDigi/interface/SiPixelDigiErrorsCUDA.h
  CUDADataFormats/SiPixelDigi/interface/SiPixelDigisCUDA.h
  CUDADataFormats/SiPixelDigi/interface/SiPixelDigisCUDASOAView.h
  CUDADataFormats/SiPixelDigi/src/SiPixelDigiErrorsCUDA.cc
  CUDADataFormats/SiPixelDigi/src/SiPixelDigisCUDA.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelDigiErrorsSoAFromCUDA.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelDigisSoAFromCUDA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterCUDA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHitGPUKernel.cu
  RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitSoAFromLegacy.cc
  RecoLocalTracker/SiPixelRecHits/plugins/gpuPixelRecHits.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#36409 [12_2_X] Replace Candidate GT by named GT in conddb script unit tests and update offline Run-3 data GT
  CondCore/Utilities/test/test_conddb.sh
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved

#36417 [12_1_X] Replace Candidate GT in conddb unit test and update run3 data GT
  CondCore/Utilities/test/test_conddb.sh
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, backport-ok

#36418 [12_0_X] Replace Candidate GT in conddb script unit tests
  CondCore/Utilities/test/test_conddb.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, backport-ok

#36425 [12_2_X] Set usedFallback properly, silence file closing printouts in StatisticsSenderService
  IOPool/Input/src/RootInputFileSequence.cc
  Utilities/StorageFactory/src/StatisticsSenderService.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36410 remove CMSDEPRECATED_X warnings from DPGAnalysis/Skims
  DPGAnalysis/Skims/src/FilterOutScraping.cc
  DPGAnalysis/Skims/src/RPCRecHitFilter.h
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#36338 Run3-gex101 Add the geometry version with the added GE21 demonstrator
  Geometry/GEMGeometryBuilder/data/GEMSpecs/2021/v1/GEMSpecs.xml
  Geometry/GEMGeometryBuilder/data/GEMSpecs/2021/v2/GEMSpecs.xml
  Geometry/GEMGeometryBuilder/data/GEMSpecsFilter/2021/v1/GEMSpecsFilter.xml
  Geometry/GEMGeometryBuilder/data/GEMSpecsFilter/2021/v2/GEMSpecsFilter.xml
  Geometry/MuonCommonData/data/gem21/2021/v1/gem21.xml
  Geometry/MuonCommonData/data/mf/2021/v3/mf.xml
  Geometry/MuonCommonData/data/muonNumbering/2021/v4/muonNumbering.xml
  Geometry/MuonCommonData/python/testExtendedGeometry2021XML_cfi.py
  Geometry/MuonCommonData/test/python/g4OverlapCheck2021_cfg.py
  Geometry/MuonSimData/data/muonProdCuts/2021/v3/muonProdCuts.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36427 [12_1_X] Set usedFallback properly, silence file closing printouts in StatisticsSenderService
  IOPool/Input/src/RootInputFileSequence.cc
  Utilities/StorageFactory/src/StatisticsSenderService.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36400 Remove usedFallback argument from (pre|post)(Open|Close)File
  FWCore/Framework/interface/InputSource.h
  FWCore/Framework/src/InputSource.cc
  FWCore/Integration/test/unit_test_outputs/testGetBy2.log
  FWCore/MessageService/plugins/MessageLogger.cc
  FWCore/MessageService/plugins/MessageLogger.h
  FWCore/ServiceRegistry/interface/ActivityRegistry.h
  FWCore/Services/plugins/CheckTransitions.cc
  FWCore/Services/plugins/CondorStatusUpdater.cc
  FWCore/Services/plugins/Timing.cc
  FWCore/Services/plugins/Tracer.cc
  HeterogeneousCore/CUDAServices/plugins/NVProfilerService.cc
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IgTools/IgProf/plugins/IgProfService.cc
  IgTools/IgProf/plugins/IgProfService.h
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#36398 Added FinalPath implementation
  FWCore/Framework/interface/EDConsumerBase.h
  FWCore/Framework/interface/EventProcessor.h
  FWCore/Framework/interface/OutputModuleCore.h
  FWCore/Framework/interface/Schedule.h
  FWCore/Framework/interface/StreamSchedule.h
  FWCore/Framework/interface/SubProcess.h
  FWCore/Framework/interface/global/OutputModuleBase.h
  FWCore/Framework/interface/limited/OutputModuleBase.h
  FWCore/Framework/interface/one/OutputModuleBase.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/OutputModuleCore.cc
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/src/global/OutputModuleBase.cc
  FWCore/Framework/src/limited/OutputModuleBase.cc
  FWCore/Framework/src/one/OutputModuleBase.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/test_finalpath.sh
  FWCore/Integration/test/test_finalpath_cfg.py
  FWCore/Modules/src/GetProductCheckerOutputModule.cc
  FWCore/ParameterSet/python/Config.py
  FWCore/ParameterSet/python/SequenceTypes.py
  FWCore/ParameterSet/python/SequenceVisitors.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36428 Fix WF 139.002 for muon showers (HadronicShowerTrigger-10)
  EventFilter/CSCRawToDigi/python/cscUnpacker_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36435 Temporarily restore sector and endcap accessors to RegionalMuonShower
  DataFormats/L1TMuon/interface/RegionalMuonShower.h
Labels: l1-pending, pending-signatures, tests-approved, bug-fix, orp-approved, code-checks-approved

#36431 More changes in `CondTools/SiStrip` unit tests
  CondTools/SiStrip/plugins/SiStripNoisesFromDBMiscalibrator.cc
  CondTools/SiStrip/test/SiStripChannelGainFromDBMiscalibrator_cfg.py
  CondTools/SiStrip/test/SiStripNoiseFromDBMiscalibrator_cfg.py
  CondTools/SiStrip/test/testBuildersReaders.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36424 Static Analyzers: Add checker for use of edm::ParameterSet::exists or ::existsAs<T>.
  Utilities/StaticAnalyzers/src/ClangCmsCheckerPluginRegister.cpp
  Utilities/StaticAnalyzers/src/PsetExistsFCallChecker.cpp
  Utilities/StaticAnalyzers/src/PsetExistsFCallChecker.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36432 Enhance PixelTrack SoA DQM monitoring
  DQM/SiPixelPhase1Heterogeneous/plugins/SiPixelPhase1MonitorTrackSoA.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36355 [12_0_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files
  IOPool/Input/src/EmbeddedRootSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/BuildFile.xml
  Utilities/StorageFactory/test/make_2nd_file_cfg.py
  Utilities/StorageFactory/test/make_test_files_cfg.py
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
  Utilities/StorageFactory/test/test_multi_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_multiple_files_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_secondary_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_single_file_statistics_sender_cfg.py
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36356 [11_3_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files
  IOPool/Input/src/EmbeddedRootSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/BuildFile.xml
  Utilities/StorageFactory/test/make_2nd_file_cfg.py
  Utilities/StorageFactory/test/make_test_files_cfg.py
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
  Utilities/StorageFactory/test/test_multi_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_multiple_files_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_secondary_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_single_file_statistics_sender_cfg.py
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36357 [11_1_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files
  IOPool/Input/src/EmbeddedRootSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/BuildFile.xml
  Utilities/StorageFactory/test/make_2nd_file_cfg.py
  Utilities/StorageFactory/test/make_test_files_cfg.py
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
  Utilities/StorageFactory/test/test_multi_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_multiple_files_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_secondary_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_single_file_statistics_sender_cfg.py
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36358 [11_0_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files
  IOPool/Input/src/EmbeddedRootSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/BuildFile.xml
  Utilities/StorageFactory/test/make_2nd_file_cfg.py
  Utilities/StorageFactory/test/make_test_files_cfg.py
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
  Utilities/StorageFactory/test/test_multi_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_multiple_files_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_secondary_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_single_file_statistics_sender_cfg.py
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36360 [10_6_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files
  IOPool/Input/src/EmbeddedRootSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/BuildFile.xml
  Utilities/StorageFactory/test/make_2nd_file_cfg.py
  Utilities/StorageFactory/test/make_test_files_cfg.py
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
  Utilities/StorageFactory/test/test_multi_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_multiple_files_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_secondary_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_single_file_statistics_sender_cfg.py
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36378 handle FakeHLT steps in trackingOnly workflows
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#36439 Add VtxSmearing scenario for 2021 PilotBeams
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealistic25ns900GeV2021Collision_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36445 remove legacy EDModules: FlatEGunASCIIWriter
  IOMC/ParticleGuns/interface/FlatEGunASCIIWriter.h
  IOMC/ParticleGuns/src/FlatEGunASCIIWriter.cc
  IOMC/ParticleGuns/src/SealModule.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36364 check both algo and originalAlgo in electron track isolation calculators
  RecoEgamma/EgammaIsolationAlgos/src/EleTkIsolFromCands.cc
  RecoEgamma/EgammaIsolationAlgos/src/ElectronTkIsolation.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36416 Fix assert in ExternalGeneratorFilter
  GeneratorInterface/Core/plugins/ExternalGeneratorFilter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36453 Comment out #define EDM_ML_DEBUG in HcalHBHENewMuonAnalyzer
  Calibration/HcalCalibAlgos/plugins/HcalHBHENewMuonAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36443 [10_3_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files
  IOPool/Input/src/EmbeddedRootSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/BuildFile.xml
  Utilities/StorageFactory/test/make_2nd_file_cfg.py
  Utilities/StorageFactory/test/make_test_files_cfg.py
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
  Utilities/StorageFactory/test/test_multi_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_multiple_files_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_secondary_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_single_file_statistics_sender_cfg.py
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36438 Added FinalPath implementation [12_2]
  FWCore/Framework/interface/EDConsumerBase.h
  FWCore/Framework/interface/EventProcessor.h
  FWCore/Framework/interface/OutputModuleCore.h
  FWCore/Framework/interface/Schedule.h
  FWCore/Framework/interface/StreamSchedule.h
  FWCore/Framework/interface/SubProcess.h
  FWCore/Framework/interface/global/OutputModuleBase.h
  FWCore/Framework/interface/limited/OutputModuleBase.h
  FWCore/Framework/interface/one/OutputModuleBase.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/OutputModuleCore.cc
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/src/global/OutputModuleBase.cc
  FWCore/Framework/src/limited/OutputModuleBase.cc
  FWCore/Framework/src/one/OutputModuleBase.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/test_finalpath.sh
  FWCore/Integration/test/test_finalpath_cfg.py
  FWCore/Modules/src/GetProductCheckerOutputModule.cc
  FWCore/ParameterSet/python/Config.py
  FWCore/ParameterSet/python/SequenceTypes.py
  FWCore/ParameterSet/python/SequenceVisitors.py
Labels: core-approved, fully-signed, tests-rejected, orp-approved

#36436 `Alignment/OfflineValidation`: modernize `EopTreeWriter`
  Alignment/OfflineValidation/plugins/EopTreeWriter.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36406 Moved modules in RecoJets/JetAnalyzers to thread-friendly types
  RecoJets/JetAnalyzers/interface/CMSDAS11DijetAnalyzer.h
  RecoJets/JetAnalyzers/interface/CMSDAS11DijetTestAnalyzer.h
  RecoJets/JetAnalyzers/interface/CaloTowersExample.h
  RecoJets/JetAnalyzers/interface/DijetMass.h
  RecoJets/JetAnalyzers/interface/DijetRatio.h
  RecoJets/JetAnalyzers/interface/JetAnaPythia.h
  RecoJets/JetAnalyzers/interface/JetCorExample.h
  RecoJets/JetAnalyzers/interface/JetPlotsExample.h
  RecoJets/JetAnalyzers/interface/JetToDigiDump.h
  RecoJets/JetAnalyzers/interface/JetValidation.h
  RecoJets/JetAnalyzers/interface/SimpleJetDump.h
  RecoJets/JetAnalyzers/interface/myFastSimVal.h
  RecoJets/JetAnalyzers/interface/myRawAna.h
  RecoJets/JetAnalyzers/interface/ptHatFilter.h
  RecoJets/JetAnalyzers/src/CMSDAS11DijetAnalyzer.cc
  RecoJets/JetAnalyzers/src/CMSDAS11DijetTestAnalyzer.cc
  RecoJets/JetAnalyzers/src/CalcTopMassExample.cc
  RecoJets/JetAnalyzers/src/FFTJetImageRecorder.cc
  RecoJets/JetAnalyzers/src/FFTJetPileupAnalyzer.cc
  RecoJets/JetAnalyzers/src/FlavorJetCorrectionExample.cc
  RecoJets/JetAnalyzers/src/JetIdSelector.cc
  RecoJets/JetAnalyzers/src/PartonJetCorrectionExample.cc
  RecoJets/JetAnalyzers/src/myRawAna.cc
  RecoJets/JetAnalyzers/src/ptHatFilter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36444 [12.2.X] Enhance PixelTrack SoA DQM monitoring
  DQM/SiPixelPhase1Heterogeneous/plugins/SiPixelPhase1MonitorTrackSoA.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#36231 Migrate BTV pacakges to new PoolDBOutputService
  RecoBTag/PerformanceDB/plugins/BTagPerformaceRootProducerFromSQLITE.cc
  RecoBTag/PerformanceDB/plugins/PhysicsPerformanceDBWriterFromFile_WPandPayload.cc
  RecoBTag/PerformanceDB/plugins/PhysicsPerformanceDBWriterFromFile_WPandPayload_IOV.cc
  RecoBTag/PerformanceDB/plugins/PhysicsPerformanceDBWriterTFormula_fromfile_WPandPL.cc
  RecoBTag/TrackProbability/test/CalibrationSkeleton.cc
  RecoBTag/TrackProbability/test/TrackProbabilityXMLtoDB.cc
Labels: reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36414 modernize `EventFilter/Phase2TrackerRawToDigi`
  EventFilter/Phase2TrackerRawToDigi/plugins/Phase2TrackerCommissioningDigiProducer.cc
  EventFilter/Phase2TrackerRawToDigi/plugins/Phase2TrackerDigiProducer.cc
Labels: daq-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36449 `OverlapValidation`: bugfix to `esConsumes` migration
  Alignment/OfflineValidation/plugins/OverlapValidation.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36430 Functional changes as follow-up to 36176
  CUDADataFormats/SiPixelDigi/interface/SiPixelDigisCUDASOAView.h
  CUDADataFormats/SiPixelDigi/src/SiPixelDigisCUDA.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#36454 update legacy module: DummyLHEAnalyzer
  GeneratorInterface/LHEInterface/test/DummyLHEAnalyzer.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34169 Storing Generator Filter Information in NanoAOD
  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
  PhysicsTools/NanoAOD/plugins/LumiOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/LumiOutputBranches.h
  PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/python/globals_cff.py
  PhysicsTools/NanoAOD/python/nanogen_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#36450 [12.2.X] `OverlapValidation`: bugfix to `esConsumes` migration
  Alignment/OfflineValidation/plugins/OverlapValidation.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#36451 [12.1.X] `OverlapValidation`: bugfix to `esConsumes` migration
  Alignment/OfflineValidation/plugins/OverlapValidation.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#36452 [12.0.X] `OverlapValidation`: bugfix to `esConsumes` migration
  Alignment/OfflineValidation/plugins/OverlapValidation.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#36440 [12_2_X] Add VtxSmearing scenario for 2021 PilotBeams
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealistic25ns900GeV2021Collision_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#35588 Enforce EventSetup products can be obtained only with ESGetToken
  FWCore/Framework/interface/Callback.h
  FWCore/Framework/interface/DataProxyTemplate.h
  FWCore/Framework/interface/DependentRecordImplementation.h
  FWCore/Framework/interface/ESConsumesCollector.h
  FWCore/Framework/interface/EventSetup.h
  FWCore/Framework/interface/EventSetupRecord.h
  FWCore/Framework/interface/stream/EDAnalyzerAdaptor.h
  FWCore/Framework/interface/stream/ProducingModuleAdaptor.h
  FWCore/Framework/src/EDAnalyzer.cc
  FWCore/Framework/src/EDFilter.cc
  FWCore/Framework/src/EDLooperBase.cc
  FWCore/Framework/src/EDProducer.cc
  FWCore/Framework/src/EventSetupRecord.cc
  FWCore/Framework/src/global/EDAnalyzerBase.cc
  FWCore/Framework/src/global/EDFilterBase.cc
  FWCore/Framework/src/global/EDProducerBase.cc
  FWCore/Framework/src/limited/EDAnalyzerBase.cc
  FWCore/Framework/src/limited/EDFilterBase.cc
  FWCore/Framework/src/limited/EDProducerBase.cc
  FWCore/Framework/src/one/EDAnalyzerBase.cc
  FWCore/Framework/src/one/EDFilterBase.cc
  FWCore/Framework/src/one/EDProducerBase.cc
  FWCore/Framework/src/stream/EDAnalyzerAdaptorBase.cc
  FWCore/Framework/src/stream/EDFilterAdaptorBase.cc
  FWCore/Framework/src/stream/EDProducerAdaptorBase.cc
  FWCore/Framework/src/stream/ProducingModuleAdaptorBase.cc
  FWCore/Framework/test/callback_t.cppunit.cc
  FWCore/Framework/test/dependentrecord_t.cppunit.cc
  FWCore/Framework/test/esproducer_t.cppunit.cc
  FWCore/Framework/test/eventsetup_t.cppunit.cc
  FWCore/Framework/test/eventsetuprecord_t.cppunit.cc
  FWCore/Framework/test/fullchain_t.cppunit.cc
  FWCore/Framework/test/run_test_1_thread_es_prefetching.sh
  FWCore/Framework/test/stubs/TestESDummyDataAnalyzer.cc
  FWCore/Framework/test/test_1_thread_es_mixed_prefetch_cfg.py
  FWCore/Framework/test/test_1_thread_es_no_prefetch_cfg.py
Labels: core-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36290 [10_6_X] Add epsilon in comparison of probabilities in SiPixelRecHitQuality
  DataFormats/TrackerRecHit2D/interface/SiPixelRecHitQuality.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved

#36447 Remove test of h5py_cache
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#36455 Use correct accessors for RegionalMuonShower data type
  DQM/L1TMonitor/src/L1TdeStage2Shower.cc
  DataFormats/L1TMuon/interface/RegionalMuonShower.h
  L1Trigger/L1TNtuples/src/L1AnalysisL1UpgradeTfMuonShower.cc
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36422 ensure `HLTProcess` adds all `(End)Path`s to the schedule
  HLTrigger/Configuration/python/Tools/confdb.py
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36419 Apply Naming Rules to `BeamSpotObjects` methods
  Alignment/OfflineValidation/plugins/PixelBaryCentreAnalyzer.cc
  Calibration/TkAlCaRecoProducers/plugins/AlcaBeamSpotFromDB.cc
  Calibration/TkAlCaRecoProducers/plugins/AlcaBeamSpotHarvester.cc
  CondCore/BeamSpotPlugins/interface/BeamSpotPayloadInspectorHelper.h
  CondCore/BeamSpotPlugins/plugins/BeamSpot_PayloadInspector.cc
  CondCore/DBOutputService/test/stubs/LumiBasedUpdateAnalyzer.cc
  CondCore/ESSources/test/stubs/LumiTestReadAnalyzer.cc
  CondCore/ESSources/test/stubs/TestConcurrentIOVsCondCore.cc
  CondFormats/BeamSpotObjects/interface/BeamSpotObjects.h
  CondFormats/BeamSpotObjects/src/BeamSpotObjects.cc
  CondFormats/BeamSpotObjects/src/BeamSpotOnlineObjects.cc
  CondTools/BeamSpot/plugins/BeamSpotOnlineRecordsReader.cc
  CondTools/BeamSpot/plugins/BeamSpotOnlineRecordsWriter.cc
  CondTools/BeamSpot/plugins/BeamSpotRcdReader.cc
  DQM/BeamMonitor/plugins/AlcaBeamMonitor.cc
  DQM/BeamMonitor/plugins/BeamConditionsMonitor.cc
  DQM/BeamMonitor/plugins/BeamMonitor.cc
  DQM/BeamMonitor/plugins/BeamSpotDipServer.cc
  DQM/BeamMonitor/plugins/FakeBeamMonitor.cc
  DQM/BeamMonitor/plugins/OnlineBeamMonitor.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotFakeConditions.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotOnlineProducer.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotProducer.cc
  RecoVertex/BeamSpotProducer/plugins/BeamSpotWrite2DB.cc
  RecoVertex/BeamSpotProducer/plugins/OnlineBeamSpotESProducer.cc
  RecoVertex/BeamSpotProducer/src/BeamFitter.cc
  SimTransport/PPSProtonTransport/src/HectorTransport.cc
  SimTransport/PPSProtonTransport/src/OpticalFunctionsTransport.cc
Labels: alca-approved, dqm-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36366 Modernize / DB output migration of GBRWrapperMaker.cc
  RecoEgamma/EgammaTools/test/GBRWrapperMaker.cc
Labels: reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36343 Transition from sigcpp-2 to sigcpp-3
  Fireworks/Core/interface/CSGAction.h
  Fireworks/Core/interface/CSGContinuousAction.h
  Fireworks/Core/interface/CmsShowCommon.h
  Fireworks/Core/interface/CmsShowMainBase.h
  Fireworks/Core/interface/CmsShowNavigator.h
  Fireworks/Core/interface/CmsShowTaskExecutorBase.h
  Fireworks/Core/interface/CmsShowViewPopup.h
  Fireworks/Core/interface/FWColorManager.h
  Fireworks/Core/interface/FWEventItemsManager.h
  Fireworks/Core/interface/FWGLEventHandler.h
  Fireworks/Core/interface/FWGUIManager.h
  Fireworks/Core/interface/FWGUISubviewArea.h
  Fireworks/Core/interface/FWGenericParameter.h
  Fireworks/Core/interface/FWIntValueListener.h
  Fireworks/Core/interface/FWItemChangeSignal.h
  Fireworks/Core/interface/FWJobMetadataManager.h
  Fireworks/Core/interface/FWModelChangeManager.h
  Fireworks/Core/interface/FWModelChangeSignal.h
  Fireworks/Core/interface/FWNavigatorBase.h
  Fireworks/Core/interface/FWSelectionManager.h
  Fireworks/Core/interface/FWViewBase.h
  Fireworks/Core/interface/FWViewContext.h
  Fireworks/Core/interface/FWViewEnergyScale.h
  Fireworks/Core/src/FWGUIEventDataAdder.cc
  Fireworks/Core/src/FWGUIManager.cc
  Fireworks/Core/src/FWModelChangeManager.cc
  Fireworks/Electrons/plugins/FWConvTrackHitsDetailView.cc
  Fireworks/ParticleFlow/plugins/FWPFCandidateDetailView.cc
  Fireworks/Tracks/plugins/FWTrackHitsDetailView.cc
Labels: visualization-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#36463 Run3-alca212 Update the macros and move the fileservice variable from class member to a local variable in Calibration/HcalCalibAlgos
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/plugins/Analyzer_minbias.cc
  Calibration/HcalCalibAlgos/plugins/Analyzer_minbias.h
  Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalHBHENewMuonAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrackAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkSimAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36171 Sibling Doublets for the HGCal Pattern Recoginition by CA
  RecoHGCal/TICL/plugins/HGCDoublet.cc
  RecoHGCal/TICL/plugins/HGCDoublet.h
  RecoHGCal/TICL/plugins/HGCGraph.cc
  RecoHGCal/TICL/plugins/HGCGraph.h
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36458 [9_4_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files
  IOPool/Input/src/EmbeddedRootSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/BuildFile.xml
  Utilities/StorageFactory/test/make_2nd_file_cfg.py
  Utilities/StorageFactory/test/make_test_files_cfg.py
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
  Utilities/StorageFactory/test/test_multi_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_multiple_files_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_secondary_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_single_file_statistics_sender_cfg.py
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36472 migrate away from deprecated `EDAnalyzer` in `OnlineDB/SiStripESSources`
  OnlineDB/SiStripESSources/test/stubs/test_PedestalsBuilder.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36474 ensure `HLTProcess` adds all `(End)Path`s to the schedule [12.2.X]
  HLTrigger/Configuration/python/Tools/confdb.py
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#36448 [DQM] DT Fixing FEDFatal
  DQM/DTMonitorClient/src/DTDataIntegrityTest.cc
  DQM/DTMonitorClient/src/DTSegmentAnalysisTest.cc
  DQM/DTMonitorModule/interface/DTDataIntegrityTask.h
  DQM/DTMonitorModule/interface/DTDataIntegrityUrosOffline.h
  DQM/DTMonitorModule/plugins/plugins.cc
  DQM/DTMonitorModule/python/dtDataIntegrityTask_cfi.py
  DQM/DTMonitorModule/src/DTDataIntegrityTask.cc
  DQM/DTMonitorModule/src/DTDataIntegrityUrosOffline.cc
  DQMServices/Components/plugins/DQMFEDIntegrityClient.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36476 Drop type specs in Validation/MuonIdentification
  Validation/MuonIdentification/python/muonIdVal_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36391 Remove deprecation warnings from `TrackingTools`
  RecoLocalMuon/RPCRecHit/plugins/TracktoRPC.cc
  TrackingTools/PatternTools/plugins/TSCBLBuilderWithPropagatorESProducer.cc
  TrackingTools/TrackAssociator/test/CaloMatchingExample.cc
  TrackingTools/TrackAssociator/test/TestTrackAssociator.cc
  TrackingTools/TrackRefitter/interface/TrackTransformerForCosmicMuons.h
  TrackingTools/TrackRefitter/interface/TrackTransformerForGlobalCosmicMuons.h
  TrackingTools/TrackRefitter/plugins/TracksToTrajectories.cc
  TrackingTools/TrackRefitter/src/TrackTransformerForCosmicMuons.cc
  TrackingTools/TrackRefitter/src/TrackTransformerForGlobalCosmicMuons.cc
  TrackingTools/TrackRefitter/test/TrackReader.cc
  TrackingTools/TrackRefitter/test/TrackReader.h
  TrackingTools/TrackRefitter/test/TrajectoryReader.cc
  TrackingTools/TrackRefitter/test/TrajectoryReader.h
  TrackingTools/TrajectoryCleaning/test/TrajectoryCleanerAnalyzer.cc
  TrackingTools/TrajectoryFiltering/test/TrajectoryFilterAnalyzer.cc
  TrackingTools/TransientTrack/test/TransientTrackBuilderTest.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36479 Drop type specs in RecoB and RecoEgamma
  Validation/RecoB/python/BDHadronTrackMonitoring_cfi.py
  Validation/RecoB/python/BDHadronTrackValidation_cff.py
  Validation/RecoEgamma/python/electronIsoFromDeps_cff.py
  Validation/RecoEgamma/python/electronValidationSequenceMiniAOD_cff.py
  Validation/RecoEgamma/python/tkConvValidator_cfi.py
  Validation/RecoEgamma/python/tpSelection_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36475 Static Analyzers: Fix capitalization of category name for ParameterSet::exists check
  Utilities/StaticAnalyzers/src/PsetExistsFCallChecker.cpp
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36464 Run3-sim100B Move the fileservice variable from class member to a local variable in SimG4CMS/Calo
  SimG4CMS/Calo/interface/HcalTestHistoManager.h
  SimG4CMS/Calo/plugins/HcalTestAnalyzer.cc
  SimG4CMS/Calo/src/HcalTestHistoManager.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36456 [10_2_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files
  IOPool/Input/src/EmbeddedRootSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/BuildFile.xml
  Utilities/StorageFactory/test/make_2nd_file_cfg.py
  Utilities/StorageFactory/test/make_test_files_cfg.py
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
  Utilities/StorageFactory/test/test_multi_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_multiple_files_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_secondary_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_single_file_statistics_sender_cfg.py
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36420 Update all other guns
  GeneratorInterface/Pythia8Interface/plugins/Py8JetGun.cc
  GeneratorInterface/Pythia8Interface/plugins/Py8MassGun.cc
  GeneratorInterface/Pythia8Interface/plugins/Py8PtAndDxyGun.cc
  GeneratorInterface/Pythia8Interface/plugins/Py8PtGun.cc
  GeneratorInterface/Pythia8Interface/plugins/Py8PtotGun.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36467 [GCC11] Fix warning "strncmp ... evaluates to nonzero"
  FWCore/Utilities/src/MallocOpts.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36483 [DQM] DT Fixing FEDFatal 12_2_X
  DQM/DTMonitorClient/src/DTDataIntegrityTest.cc
  DQM/DTMonitorClient/src/DTSegmentAnalysisTest.cc
  DQM/DTMonitorModule/interface/DTDataIntegrityTask.h
  DQM/DTMonitorModule/interface/DTDataIntegrityUrosOffline.h
  DQM/DTMonitorModule/plugins/plugins.cc
  DQM/DTMonitorModule/python/dtDataIntegrityTask_cfi.py
  DQM/DTMonitorModule/src/DTDataIntegrityTask.cc
  DQM/DTMonitorModule/src/DTDataIntegrityUrosOffline.cc
  DQMServices/Components/plugins/DQMFEDIntegrityClient.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#36460 Introduce flag for particles generation with max energy spread
  Configuration/Generator/python/CE_E_Front_120um_cfi.py
  Configuration/Generator/python/CE_E_Front_200um_cfi.py
  Configuration/Generator/python/CE_E_Front_300um_cfi.py
  Configuration/Generator/python/CE_H_Coarse_300um_cfi.py
  Configuration/Generator/python/CE_H_Coarse_Scint_cfi.py
  Configuration/Generator/python/CE_H_Fine_120um_cfi.py
  Configuration/Generator/python/CE_H_Fine_200um_cfi.py
  Configuration/Generator/python/CE_H_Fine_300um_cfi.py
  Configuration/Generator/python/CloseByParticle_Photon_ERZRanges_cfi.py
  IOMC/ParticleGuns/interface/CloseByParticleGunProducer.h
  IOMC/ParticleGuns/src/CloseByParticleGunProducer.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36495 get rid of CMS deprecation warnings in `Validation/*Track`
  Validation/RecoPixelVertexing/test/PixelTrackVal.cc
  Validation/RecoTrack/interface/SiStripTrackingRecHitsValid.h
  Validation/SiOuterTrackerV/plugins/OuterTrackerMonitorTrackingParticles.cc
  Validation/SiOuterTrackerV/plugins/OuterTrackerMonitorTrackingParticles.h
  Validation/TrackerHits/interface/TrackerHitAnalyzer.h
  Validation/TrackerRecHits/interface/SiPixelRecHitsValid.h
  Validation/TrackerRecHits/interface/SiStripRecHitsValid.h
  Validation/TrackerRecHits/src/SiPixelRecHitsValid.cc
  Validation/TrackerRecHits/test/StripClusterMCanalysis.cc
  Validation/TrackingMCTruth/interface/TrackingTruthValid.h
  Validation/TrackingMCTruth/plugins/TrackingTruthValid.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36498 Phase2-hgx297B Move FileService variable in the code rather than as a class member for Validation/HGCalValidation
  Validation/HGCalValidation/test/FTSimHitTest.cc
  Validation/HGCalValidation/test/HGCalSiliconValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36489 Bug fix in HiPuRhoProducer.cc
  RecoHI/HiJetAlgos/plugins/HiPuRhoProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36470 Run3-gem64 Update the GEM demontrator gemetry
  Geometry/MuonCommonData/data/gem21/2021/v1/gem21.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36225 Adding Disappearing Tracks Cuts (EXO-19-010) to List of saved DeDxHitInfo Cuts in Isolated Tracks Slimming
  DataFormats/PatCandidates/interface/IsolatedTrack.h
  PhysicsTools/PatAlgos/python/slimming/isolatedTracks_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#36497 Run3-sim101 Move FileService variable in the code rather than as a class member and use fillDescription in SimG4CMS/ShowerLibraryProducer and SimG4CMS/Calo
  SimG4CMS/Calo/plugins/HcalTestNumberingTest.cc
  SimG4CMS/Calo/test/python/runHcalTestNumberingTester_cfg.py
  SimG4CMS/ShowerLibraryProducer/interface/HcalForwardLibWriter.h
  SimG4CMS/ShowerLibraryProducer/plugins/HcalForwardAnalysis.cc
  SimG4CMS/ShowerLibraryProducer/plugins/HcalForwardLibWriter.cc
  SimG4CMS/ShowerLibraryProducer/python/writelibraryfile_cfg.py
  SimG4CMS/ShowerLibraryProducer/test/AnalyzeTuples.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved
