Repository cms-sw/cmssw, pull requests merged in 2021-08, with the labels that each got.

#34668 [DataFormats][clang-tidy] make deleted function public
  DataFormats/Common/interface/ContainerMaskTraits.h
  DataFormats/Common/interface/PtrVectorBase.h
  DataFormats/FWLite/interface/DataGetterHelper.h
  DataFormats/FWLite/interface/Event.h
  DataFormats/FWLite/interface/EventHistoryGetter.h
  DataFormats/FWLite/interface/EventSetup.h
  DataFormats/FWLite/interface/HistoryGetterBase.h
  DataFormats/FWLite/interface/LumiHistoryGetter.h
  DataFormats/FWLite/interface/LuminosityBlock.h
  DataFormats/FWLite/interface/Record.h
  DataFormats/FWLite/interface/Run.h
  DataFormats/FWLite/interface/RunFactory.h
  DataFormats/FWLite/interface/RunHistoryGetter.h
  DataFormats/ForwardDetId/interface/MTDChannelIdentifier.h
  DataFormats/Math/interface/GraphWalker.h
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-rejected, upgrade-approved

#34674 Run3-hcx305 Update some of the cfg's in Validation/HcalHits in view of changes to SD classes
  Validation/HcalHits/python/testGeometryPMTXML_cfi.py
  Validation/HcalHits/test/HF_high-e_test_cfg.py
  Validation/HcalHits/test/HcalSimHitStudy_cfg.py
  Validation/HcalHits/test/run_HB_cfg.py
  Validation/HcalHits/test/run_HE_cfg.py
  Validation/HcalHits/test/run_HFV2_cfg.py
  Validation/HcalHits/test/run_HF_cfg.py
  Validation/HcalHits/test/testHFPMT_cfg.py
  Validation/HcalHits/test/testHF_cfg.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#34680 Fireworks 9_4_X: Fix bug in scaling after projected view destruction
  Fireworks/Calo/interface/FWTauProxyBuilderBase.h
  Fireworks/Calo/plugins/FWJetProxyBuilder.cc
  Fireworks/Calo/plugins/FWMETProxyBuilder.cc
  Fireworks/Calo/src/FWTauProxyBuilderBase.cc
Labels: fully-signed, orp-approved, tests-approved, visualization-approved

#34715 Remove unused header for Alignment/LaserAlignment and Alignment/MuonAlignmentAlgorithms
  Alignment/LaserAlignment/interface/OrderedLaserHitPair.h
  Alignment/LaserAlignment/interface/OrderedLaserHitPairs.h
  Alignment/LaserAlignment/interface/SeedLayerPairs.h
  Alignment/MuonAlignmentAlgorithms/interface/MuonInfoTuple.h
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#34643 Changing Commissioning 2020 to Commissioning 2021 with new run # and dataset.
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#34599 finecalo: No longer count reentries into the calorimeter as boundary crossings
  SimG4CMS/Calo/src/CaloTrkProcessing.cc
  SimG4Core/Notification/interface/TrackInformation.h
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-rejected, upgrade-approved

#34709 Run3-alca190 Modify the AlCaRecoProducer for HBHEMuon
  Calibration/HcalAlCaRecoProducers/BuildFile.xml
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonFilter.cc
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalHBHEMuonFilter_cff.py
  Calibration/HcalAlCaRecoProducers/python/alcaHBHEMuonFilter_cfi.py
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#34725 Fix uploading EventSetup conditions from multiple CUDA streams
  HeterogeneousCore/CUDACore/interface/ESProduct.h
Labels: bug-fix, code-checks-approved, fully-signed, heterogeneous-approved, orp-approved, tests-rejected

#34682 [Cond][clang-tidy] make deleted function public
  CondCore/CondDB/plugins/XMLAuthenticationService.h
  CondCore/ESSources/interface/DataProxy.h
  CondFormats/DTObjects/interface/DTBufferTree.h
  CondFormats/DTObjects/interface/DTCCBConfig.h
  CondFormats/DTObjects/interface/DTDeadFlag.h
  CondFormats/DTObjects/interface/DTHVStatus.h
  CondFormats/DTObjects/interface/DTLVStatus.h
  CondFormats/DTObjects/interface/DTMtime.h
  CondFormats/DTObjects/interface/DTPerformance.h
  CondFormats/DTObjects/interface/DTRangeT0.h
  CondFormats/DTObjects/interface/DTReadOutMapping.h
  CondFormats/DTObjects/interface/DTStatusFlag.h
  CondFormats/DTObjects/interface/DTTPGParameters.h
  CondFormats/DTObjects/interface/DTTtrig.h
  CondFormats/JetMETObjects/interface/FactorizedJetCorrector.h
  CondFormats/JetMETObjects/interface/FactorizedJetCorrectorCalculator.h
  CondFormats/JetMETObjects/interface/JetCorrectionUncertainty.h
  CondFormats/JetMETObjects/interface/SimpleJetCorrectionUncertainty.h
  CondTools/DT/interface/DTKeyedConfigCache.h
  CondTools/Hcal/interface/StreamOutFormatTarget.h
  CondTools/Hcal/plugins/BufferedBoostIODBWriter.cc
  CondTools/L1Trigger/interface/OMDSReader.h
Labels: alca-approved, code-checks-approved, db-approved, l1-pending, orp-approved, pending-signatures, tests-approved

#34683 [Sim][clang-tidy] make deleted function public
  SimDataFormats/Associations/interface/LayerClusterToCaloParticleAssociator.h
  SimDataFormats/Associations/interface/LayerClusterToSimTracksterAssociator.h
  SimDataFormats/Associations/interface/MultiClusterToCaloParticleAssociator.h
  SimDataFormats/Associations/interface/MuonToTrackingParticleAssociator.h
  SimDataFormats/Associations/interface/TrackToGenParticleAssociator.h
  SimDataFormats/Associations/interface/TrackToGenParticleAssociatorBaseImpl.h
  SimDataFormats/Associations/interface/TrackToTrackingParticleAssociator.h
  SimDataFormats/Associations/interface/TracksterToSimClusterAssociator.h
  SimDataFormats/Associations/interface/TracksterToSimTracksterAssociator.h
  SimDataFormats/Associations/interface/VertexToTrackingVertexAssociator.h
  SimDataFormats/GeneratorProducts/interface/LHECommonBlocks.h
  SimG4CMS/Calo/interface/HFNoseNumberingScheme.h
  SimG4CMS/Calo/interface/HGCNumberingScheme.h
  SimG4CMS/Calo/interface/HGCalNumberingScheme.h
  SimG4CMS/Calo/interface/HcalTestNumberingScheme.h
  SimG4CMS/Forward/plugins/SimG4FluxProducer.h
  SimG4CMS/HGCalTestBeam/interface/AHCalGeometry.h
  SimG4CMS/HGCalTestBeam/plugins/HGCPassive.h
  SimG4CMS/HGCalTestBeam/plugins/HGCalTBMB.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB02Analysis.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB04Analysis.cc
  SimG4CMS/ShowerLibraryProducer/interface/HcalForwardAnalysis.h
  SimG4Core/CheckSecondary/interface/CheckSecondary.h
  SimG4Core/CheckSecondary/interface/StoreSecondary.h
  SimG4Core/CheckSecondary/interface/TreatSecondary.h
  SimG4Core/HelpfulWatchers/src/BeginOfTrackCounter.h
  SimGeneral/MixingModule/interface/DigiAccumulatorMixMod.h
  SimMuon/MCTruth/plugins/MuonToTrackingParticleAssociatorByHitsImpl.h
  SimTracker/Common/interface/SiG4UniversalFluctuation.h
  SimTracker/TrackerMaterialAnalysis/plugins/MaterialAccountingGroup.h
Labels: code-checks-approved, generators-pending, orp-approved, pending-signatures, simulation-approved, tests-approved, upgrade-pending

#34691 [Misc2][clang-tidy] make deleted function public
  CalibCalorimetry/EcalTrivialCondModules/interface/ESTrivialConditionRetriever.h
  CalibCalorimetry/EcalTrivialCondModules/interface/EcalTrivialConditionRetriever.h
  CalibCalorimetry/HcalTPGAlgos/interface/XMLProcessor.h
  CalibTracker/SiStripESProducers/interface/Phase2TrackerCablingESProducer.h
  CalibTracker/SiStripESProducers/interface/SiStripGainESSource.h
  CalibTracker/SiStripESProducers/interface/SiStripNoiseESSource.h
  CalibTracker/SiStripESProducers/interface/SiStripPedestalsESSource.h
  CalibTracker/SiStripESProducers/plugins/fake/SiStripTemplateEmptyFakeESSource.h
  CaloOnlineTools/HcalOnlineDb/interface/XMLLUTLoader.h
  DQM/SiStripCommissioningSources/interface/SiStripCommissioningSource.h
  DQM/SiStripCommissioningSources/plugins/tracking/SiStripFineDelayTOF.h
  DQM/SiStripCommon/interface/SiStripHistoId.h
  DQMOffline/Trigger/interface/EgHLTOffHelper.h
  DQMOffline/Trigger/interface/EgHLTOfflineSource.h
  DQMServices/FwkIO/plugins/DQMRootSource.cc
  EventFilter/GctRawToDigi/src/GctUnpackCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/UCTCTP7RawData.h
  EventFilter/L1TXRawToDigi/interface/UCTAMCRawData.h
  EventFilter/L1TXRawToDigi/interface/UCTCTP7RawData.h
  EventFilter/L1TXRawToDigi/interface/UCTDAQRawData.h
  EventFilter/RctRawToDigi/src/RctUnpackCollections.h
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.h
  GeneratorInterface/Herwig7Interface/interface/Proxy.h
  GeneratorInterface/HiGenCommon/plugins/BetaBoostEvtVtxGenerator.cc
  GeneratorInterface/HiGenCommon/plugins/MixBoostEvtVtxGenerator.cc
  GeneratorInterface/LHEInterface/interface/LHEProxy.h
  GeneratorInterface/LHEInterface/src/XMLUtils.h
  GeometryReaders/XMLIdealGeometryESSource/interface/XMLIdealGeometryESSource.h
  IOMC/EventVertexGenerators/interface/BeamProfileVtxGenerator.h
  IOMC/EventVertexGenerators/interface/BetafuncEvtVtxGenerator.h
  IOMC/EventVertexGenerators/interface/FlatEvtVtxGenerator.h
  IOMC/EventVertexGenerators/interface/GaussEvtVtxGenerator.h
  IOMC/EventVertexGenerators/interface/HLLHCEvtVtxGenerator.h
  IOPool/Output/src/RootOutputTree.cc
Labels: alca-approved, code-checks-approved, core-approved, db-approved, dqm-approved, generators-pending, geometry-approved, l1-pending, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved

#34688 [L1][clang-tidy] make deleted function public
  L1Trigger/L1GctAnalyzer/src/GctErrorAnalyzer.cc
  L1Trigger/L1TCaloLayer1/src/UCTCard.hh
  L1Trigger/L1TCaloLayer1/src/UCTCrate.hh
  L1Trigger/L1TCaloLayer1/src/UCTLayer1.hh
  L1Trigger/L1TCaloLayer1/src/UCTRegion.hh
  L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.hh
  L1Trigger/L1TCaloLayer1/src/UCTTower.hh
  L1Trigger/L1TMuonEndCap/interface/bdt/Node.h
  L1Trigger/RPCTrigger/interface/MuonsGrabber.h
  L1Trigger/RegionalCaloTrigger/interface/L1RCTCrate.h
  L1Trigger/RegionalCaloTrigger/interface/L1RCTElectronIsolationCard.h
  L1Trigger/RegionalCaloTrigger/interface/L1RCTJetSummaryCard.h
  L1Trigger/RegionalCaloTrigger/interface/L1RCTReceiverCard.h
Labels: code-checks-approved, l1-pending, orp-approved, pending-signatures, tests-rejected

#34720 TkDQM: Fill barycenter plots at EndRun
  DQM/SiPixelPhase1Summary/interface/SiPixelBarycenter.h
  DQM/SiPixelPhase1Summary/src/SiPixelBarycenter.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#34681 Disable vertex smearing for workflows using CloseByParticleGun
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedHGCALCloseBy_cfi.py
Labels: code-checks-approved, operations-approved, orp-approved, pdmv-pending, pending-signatures, simulation-approved, tests-rejected, upgrade-approved

#34712 Fix integer division after migration to python 3
  Validation/RecoTrack/python/plotting/plotting.py
Labels: backport-ok, bug-fix, dqm-approved, fully-signed, orp-approved, tests-rejected

#34738 Run3-hcx306 Bug fix to get back the same hit energy distribution for HCAL
  SimG4CMS/Calo/src/HCalSD.cc
  SimG4CMS/Calo/test/python/minbias_cfg.py
Labels: bug-fix, code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-rejected

#34664 Adapted EcalRawToDigi and SiPixelRawToCluster GPU code for HIon
  EventFilter/EcalRawToDigi/plugins/EcalRawToDigiGPU.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterCUDA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.h
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClustering.h
Labels: code-checks-approved, fully-signed, heterogeneous-approved, orp-approved, reconstruction-approved, tests-approved

#34719 Update DQM onlinebeammonitor
  DQM/Integration/python/clients/onlinebeammonitor_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#34713 GEM dataformat - fix classversion
  DataFormats/GEMDigi/src/classes_def.xml
  EventFilter/GEMRawToDigi/plugins/GEMPackingTester.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#34734 [Sim] Move public headers on to interface directory
  DQM/SiTrackerPhase2/plugins/Phase2TrackerMonitorDigi.cc
  GeneratorInterface/AMPTInterface/src/HepEvt.F
  GeneratorInterface/BeamHaloGenerator/interface/chepevt.inc
  GeneratorInterface/Hydjet2Interface/src/HepEvt.F
  GeneratorInterface/HydjetInterface/src/HepEvt.F
  SimCalorimetry/EcalElectronicsEmulation/interface/EcalSimRawData.h
  SimCalorimetry/EcalSelectiveReadoutAlgos/interface/EcalSelectiveReadout.h
  SimCalorimetry/EcalSelectiveReadoutAlgos/interface/EcalSelectiveReadoutSuppressor.h
  SimCalorimetry/EcalSelectiveReadoutAlgos/src/EcalSelectiveReadout.cc
  SimCalorimetry/EcalSelectiveReadoutAlgos/src/EcalSelectiveReadoutSuppressor.cc
  SimDataFormats/GeneratorProducts/interface/hepev4.inc
  SimDataFormats/GeneratorProducts/interface/stdhep.inc
  SimDataFormats/GeneratorProducts/src/HepEvt.F
  SimMuon/DTDigitizer/interface/Histograms.h
  SimMuon/DTDigitizer/test/DTDigiAnalyzer.cc
  SimMuon/DTDigitizer/test/DTDigiAnalyzer.h
  SimTracker/SiPhase2Digitizer/test/TBeamTest.cc
  Validation/DTRecHits/test/plotAllWStrue.r
  Validation/DTRecHits/test/plotValidation.r
  Validation/DTRecHits/test/writeSummaryTable.r
  Validation/MuonDTDigis/src/MuonDTDigis.cc
  Validation/MuonDTDigis/src/MuonDTDigis.h
  Validation/SiTrackerPhase2V/plugins/Phase2OTValidateRecHit.cc
  Validation/SiTrackerPhase2V/plugins/Phase2OTValidateTrackingRecHit.cc
Labels: code-checks-approved, dqm-approved, fully-signed, generators-approved, orp-approved, simulation-approved, tests-rejected, upgrade-approved

#34723 Remove unused headers of Calib- packages
  CalibCalorimetry/EcalLaserAnalyzer/interface/TMCORLin.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TMCORSat.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TMCReader.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TMConfig.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TMEGeom.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TPEDestalAnalysis.h
  CalibCalorimetry/HcalAlgos/interface/DoublePadeDelay.h
  CalibCalorimetry/HcalAlgos/interface/equalADCSignalTime.h
  CalibFormats/SiPixelObjects/interface/PixelAliasList.h
  CalibFormats/SiPixelObjects/interface/PixelConfig.h
  CalibFormats/SiPixelObjects/interface/PixelConfigAlias.h
  CalibFormats/SiPixelObjects/interface/PixelConfigFile.h
  CalibFormats/SiPixelObjects/interface/PixelConfigList.h
  CalibFormats/SiPixelObjects/interface/PixelMaskOverride.h
  CalibFormats/SiPixelObjects/interface/PixelTrimOverride.h
  CalibFormats/SiPixelObjects/interface/PixelVersionAlias.h
  CalibMuon/CSCCalibration/interface/CSCFakeCrosstalkMap.h
  CalibMuon/CSCCalibration/interface/CSCFakeDBCrosstalkPopCon.h
  CalibMuon/CSCCalibration/interface/CSCFakeDBGainsPopCon.h
  Calibration/IsolatedParticles/interface/CaloSimInfoExtra.h
  Calibration/IsolatedParticles/interface/eECALMatrixExtra.h
  Calibration/Tools/interface/TrackDetMatchInfoCollection.h
  Calibration/Tools/interface/smartSelector.h
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#34732 Fix uploading EventSetup conditions from multiple CUDA streams [11.2.x]
  HeterogeneousCore/CUDACore/interface/ESProduct.h
Labels: backport-ok, bug-fix, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#34730 Fix uploading EventSetup conditions from multiple CUDA streams [12.0.x]
  HeterogeneousCore/CUDACore/interface/ESProduct.h
Labels: backport-ok, bug-fix, fully-signed, heterogeneous-approved, orp-approved, tests-rejected

#34731 Fix uploading EventSetup conditions from multiple CUDA streams [11.3.x]
  HeterogeneousCore/CUDACore/interface/ESProduct.h
Labels: backport-ok, bug-fix, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#34726 Update DQM onlinebeammonitor [12_0_X]
  DQM/Integration/python/clients/onlinebeammonitor_dqm_sourceclient-live_cfg.py
Labels: backport-ok, dqm-approved, fully-signed, orp-approved, tests-rejected

#34721 Update DQM onlinebeammonitor [11_3_X]
  DQM/Integration/python/clients/onlinebeammonitor_dqm_sourceclient-live_cfg.py
Labels: backport-ok, dqm-approved, fully-signed, orp-approved, tests-approved

#34739 [EventFilter] header cleanup to avoid private header usage
  DQMServices/StreamerIO/test/DQMStreamerOutputRepackerTest.cc
  HLTrigger/special/plugins/HLTDummyCollections.cc
Labels: code-checks-approved, dqm-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#34751 NANO: rework for Prompt (part2) backport
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/lowPtElectrons_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: backport-ok, fully-signed, orp-approved, tests-rejected, xpog-approved

#34747 Run3-hcx306X Bug fix (backport #34738) to HCAL SD class
  SimG4CMS/Calo/src/HCalSD.cc
  SimG4CMS/Calo/test/python/minbias_cfg.py
Labels: backport-ok, bug-fix, fully-signed, orp-approved, simulation-approved, tests-rejected

#34572 Allow HcalPulseContainment timePhase definition as in SIM
  CalibCalorimetry/HcalAlgos/interface/HcalPulseContainmentCorrection.h
  CalibCalorimetry/HcalAlgos/interface/HcalPulseContainmentManager.h
  CalibCalorimetry/HcalAlgos/plugins/HcalPulseContainmentTest.cc
  CalibCalorimetry/HcalAlgos/src/HcalPulseContainmentAlgo.cc
  CalibCalorimetry/HcalAlgos/src/HcalPulseContainmentAlgo.h
  CalibCalorimetry/HcalAlgos/src/HcalPulseContainmentCorrection.cc
  CalibCalorimetry/HcalAlgos/src/HcalPulseContainmentManager.cc
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  RecoLocalCalo/HcalRecAlgos/src/HcalSimpleRecAlgo.cc
  RecoLocalCalo/HcalRecAlgos/src/SimpleHBHEPhase1Algo.cc
  RecoLocalCalo/HcalRecAlgos/src/ZdcSimpleRecAlgo.cc
Labels: alca-approved, code-checks-approved, fully-signed, l1-approved, orp-approved, reconstruction-approved, tests-approved

#34765 Fix crash of ECAL GPU reco when ECAL is out of the run.
  EventFilter/EcalRawToDigi/plugins/EcalRawToDigiGPU.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
Labels: bug-fix, code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, urgent

#34736 enforce memory order to avoid crash on Ampere [11.3.x]
  RecoPixelVertexing/PixelTriplets/plugins/GPUCACell.h
Labels: backport-ok, bug-fix, fully-signed, orp-approved, reconstruction-approved, tests-approved, urgent

#34768 Fix crash of ECAL GPU reco when ECAL is out of the run - 11_3_X
  EventFilter/EcalRawToDigi/plugins/EcalRawToDigiGPU.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
Labels: bug-fix, fully-signed, orp-approved, reconstruction-approved, tests-approved, urgent

#34766 Fix crash of ECAL GPU reco when ECAL is out of the run - 12_0_X
  EventFilter/EcalRawToDigi/plugins/EcalRawToDigiGPU.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
Labels: bug-fix, fully-signed, orp-approved, reconstruction-approved, tests-rejected

#34585 [Backport] - GEM unpacker - updated DAQ dataformat and new DAQ status collections
  CondFormats/GEMObjects/interface/GEMROMapping.h
  CondFormats/GEMObjects/interface/GEMeMap.h
  CondFormats/GEMObjects/src/GEMeMap.cc
  DataFormats/GEMDigi/interface/AMC13Event.h
  DataFormats/GEMDigi/interface/AMCdata.h
  DataFormats/GEMDigi/interface/GEBdata.h
  DataFormats/GEMDigi/interface/GEMAMC13Status.h
  DataFormats/GEMDigi/interface/GEMAMC13StatusCollection.h
  DataFormats/GEMDigi/interface/GEMAMCStatus.h
  DataFormats/GEMDigi/interface/GEMAMCStatusCollection.h
  DataFormats/GEMDigi/interface/GEMOHStatus.h
  DataFormats/GEMDigi/interface/GEMOHStatusCollection.h
  DataFormats/GEMDigi/interface/GEMVFATStatus.h
  DataFormats/GEMDigi/interface/GEMVFATStatusCollection.h
  DataFormats/GEMDigi/interface/VFATdata.h
  DataFormats/GEMDigi/src/AMCdata.cc
  DataFormats/GEMDigi/src/VFATdata.cc
  DataFormats/GEMDigi/src/classes.h
  DataFormats/GEMDigi/src/classes_def.xml
  EventFilter/GEMRawToDigi/plugins/BuildFile.xml
  EventFilter/GEMRawToDigi/plugins/GEMDigiToRawModule.cc
  EventFilter/GEMRawToDigi/plugins/GEMPackingTester.cc
  EventFilter/GEMRawToDigi/plugins/GEMRawToDigiModule.cc
  EventFilter/GEMRawToDigi/python/muonGEMDigis_cfi.py
  EventFilter/GEMRawToDigi/src/GEMRawToDigi.cc
  EventFilter/GEMRawToDigi/test/gemUnPackerTester.py
Labels: backport-ok, db-pending, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved, urgent

#34743 [Backport] GEM dataformat - fix classversion
  DataFormats/GEMDigi/src/classes_def.xml
  EventFilter/GEMRawToDigi/plugins/GEMPackingTester.cc
Labels: backport-ok, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-rejected, upgrade-approved

#34764 [GCC 11] Fix error: 'this' pointer is null in Fireworks/Geometry
  Fireworks/Geometry/plugins/DisplayGeom.cc
Labels: code-checks-approved, fully-signed, orp-approved, tests-approved, visualization-approved

#34755 [Geometry] Move public headers to interface directory
  CondTools/Geometry/plugins/CSCRecoIdealDBLoader.cc
  CondTools/Geometry/plugins/DTRecoIdealDBLoader.cc
  CondTools/Geometry/plugins/GEMRecoIdealDBLoader.cc
  CondTools/Geometry/plugins/ME0RecoIdealDBLoader.cc
  CondTools/Geometry/plugins/RPCRecoIdealDBLoader.cc
  Geometry/CSCGeometry/interface/CSCWireGroupPackage.h
  Geometry/CSCGeometry/interface/CSCWireTopology.h
  Geometry/CSCGeometry/src/CSCChamberSpecs.cc
  Geometry/CSCGeometry/src/CSCLayerGeometry.cc
  Geometry/CSCGeometryBuilder/interface/CSCGeometryParsFromDD.h
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilder.cc
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilder.h
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilderFromDDD.cc
  Geometry/CSCGeometryBuilder/src/CSCGeometryParsFromDD.cc
  Geometry/DTGeometry/test/DTRecoIdealDBLoader.cc
  Geometry/DTGeometryBuilder/interface/DTGeometryParsFromDD.h
  Geometry/DTGeometryBuilder/src/DTGeometryParsFromDD.cc
  Geometry/ForwardGeometry/interface/ZdcHardcodeGeometryData.h
  Geometry/ForwardGeometry/src/ZdcGeometry.cc
  Geometry/GEMGeometryBuilder/interface/GEMGeometryParsFromDD.h
  Geometry/GEMGeometryBuilder/interface/ME0GeometryParsFromDD.h
  Geometry/GEMGeometryBuilder/src/GEMGeometryParsFromDD.cc
  Geometry/GEMGeometryBuilder/src/ME0GeometryParsFromDD.cc
  Geometry/RPCGeometryBuilder/interface/RPCGeometryParsFromDD.h
  Geometry/RPCGeometryBuilder/src/RPCGeometryParsFromDD.cc
  SimG4CMS/Forward/interface/ZdcShowerLibrary.h
Labels: code-checks-approved, db-pending, geometry-approved, orp-approved, pending-signatures, simulation-approved, tests-approved, upgrade-approved

#34748 Protect HCAL GPU-related modules against empty events
  RecoLocalCalo/HcalRecProducers/src/HcalCPURecHitsProducer.cc
  RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu
Labels: bug-fix, code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, urgent

#34744 [TrackingTools] Move public headers to interface directory
  RecoTracker/TkDetLayers/src/TIBLayer.cc
  RecoTracker/TkNavigation/plugins/BeamHaloNavigationSchool.cc
  RecoTracker/TkNavigation/plugins/CosmicNavigationSchool.cc
  RecoTracker/TkNavigation/plugins/SimpleNavigationSchool.cc
  TrackingTools/DetLayers/interface/DetLessZ.h
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#34745 [RecoParticleFlow] Cleanup for unused/private header
  RecoParticleFlow/PFTracking/src/PFDisplacedVertexFinder.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-rejected

#34772 [GCC 11] Fix "this pointer is null" in RecoJets/JetProducers PileupJetIdAlgo
  RecoJets/JetProducers/src/PileupJetIdAlgo.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#34729 [CommonTools] move public header to interface directory
  CommonTools/RecoAlgos/interface/TrackToRefCandidate.h
  CommonTools/RecoAlgos/plugins/ChargedRefCandidateProducer.cc
  CommonTools/RecoAlgos/plugins/ConcreteChargedRefCandidateProducer.cc
  CommonTools/Utils/interface/ExpressionBase.h
  CommonTools/Utils/interface/ExpressionPtr.h
  CommonTools/Utils/interface/Grammar.h
  CommonTools/Utils/interface/SelectorBase.h
  CommonTools/Utils/interface/SelectorPtr.h
  CommonTools/Utils/interface/StringCutObjectSelector.h
  CommonTools/Utils/interface/StringObjectFunction.h
  CommonTools/Utils/interface/cutParser.h
  CommonTools/Utils/interface/expressionParser.h
  CommonTools/Utils/interface/returnType.h
  CommonTools/Utils/src/AndCombiner.h
  CommonTools/Utils/src/AnyObjSelector.h
  CommonTools/Utils/src/BinarySelector.h
  CommonTools/Utils/src/CutSetter.h
  CommonTools/Utils/src/ExpressionBinaryOperator.h
  CommonTools/Utils/src/ExpressionCondition.h
  CommonTools/Utils/src/ExpressionNumber.h
  CommonTools/Utils/src/ExpressionQuaterOperator.h
  CommonTools/Utils/src/ExpressionSetter.h
  CommonTools/Utils/src/ExpressionUnaryOperator.h
  CommonTools/Utils/src/ExpressionVar.h
  CommonTools/Utils/src/ExpressionVarSetter.cc
  CommonTools/Utils/src/LogicalBinaryOperator.h
  CommonTools/Utils/src/LogicalUnaryOperator.h
  CommonTools/Utils/src/MethodInvoker.cc
  CommonTools/Utils/src/MethodSetter.cc
  CommonTools/Utils/src/NotCombiner.h
  CommonTools/Utils/src/OrCombiner.h
  CommonTools/Utils/src/SelectorStack.h
  CommonTools/Utils/src/TrinarySelector.h
  CommonTools/Utils/src/cutParser.cc
  CommonTools/Utils/src/expressionParser.cc
  CommonTools/Utils/src/returnType.cc
  DQM/Physics/src/QcdUeDQM.cc
  Fireworks/Core/interface/FWExpressionEvaluator.h
  Fireworks/Core/interface/FWItemValueGetter.h
  Fireworks/Core/interface/FWModelFilter.h
  Fireworks/Core/src/FWExpressionEvaluator.cc
  Fireworks/Core/src/FWExpressionValidator.cc
  Fireworks/Core/src/FWGUIManager.cc
  Fireworks/Core/src/FWItemValueGetter.cc
  Fireworks/Core/src/FWModelExpressionSelector.cc
  Fireworks/Core/src/FWModelFilter.cc
  PhysicsTools/FWLite/interface/ScannerHelpers.h
  PhysicsTools/FWLite/src/ScannerHelpers.cc
  PhysicsTools/FWLite/src/classes.h
Labels: analysis-pending, code-checks-approved, dqm-approved, orp-approved, pending-signatures, reconstruction-approved, tests-rejected, visualization-approved

#34750 Protect HCAL GPU-related modules against empty events [11.3.x]
  RecoLocalCalo/HcalRecProducers/src/HcalCPURecHitsProducer.cc
  RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu
Labels: backport-ok, bug-fix, fully-signed, orp-approved, reconstruction-approved, tests-approved, urgent

#34749 Protect HCAL GPU-related modules against empty events [12.0.x]
  RecoLocalCalo/HcalRecProducers/src/HcalCPURecHitsProducer.cc
  RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu
Labels: backport-ok, bug-fix, fully-signed, orp-approved, reconstruction-approved, tests-rejected

#34762 [DataFormat] Cleanup unnecessary includes of DF private headers
  CondFormats/DTObjects/src/DTRecoUncertainties.cc
  EventFilter/Phase2TrackerRawToDigi/plugins/Phase2TrackerDigiProducer.cc
  EventFilter/SiStripRawToDigi/plugins/ExcludedFEDListProducer.cc
Labels: alca-approved, code-checks-approved, daq-approved, db-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#34754 Modernization of several simulation standalone test EDAnalyzers
  IOMC/EventVertexGenerators/test/BuildFile.xml
  IOMC/EventVertexGenerators/test/VtxTester.cc
  IOMC/EventVertexGenerators/test/VtxTester.h
  IOMC/EventVertexGenerators/test/test_vertex_cfg.py
  PhysicsTools/HepMCCandAlgos/test/BuildFile.xml
  PhysicsTools/HepMCCandAlgos/test/DummyHepMCAnalyzer.cc
  PhysicsTools/HepMCCandAlgos/test/dumpHepMC_cfg.py
  SimG4Core/Application/test/BuildFile.xml
  SimG4Core/Application/test/SimHitCaloHitDumper.cc
  SimG4Core/Application/test/SimTrackSimVertexDumper.cc
  SimG4Core/Application/test/runSimHitCaloHitDumper_cfg.py
  SimG4Core/Application/test/runSimTrackSimVertexDumper_cfg.py
  SimGeneral/Debugging/test/BuildFile.xml
  SimGeneral/Debugging/test/SimDigiDumper.cc
  SimGeneral/Debugging/test/SimDigiDumper.h
  SimGeneral/Debugging/test/runSimDigiDumper_cfg.py
Labels: analysis-pending, code-checks-approved, orp-approved, pending-signatures, simulation-approved, tests-approved

#34782 Updates on GEM onlineDQM due to the updates of DAQ dataformat, backport to CMSSW_11_3_X
  DQM/GEM/interface/GEMDAQStatusSource.h
  DQM/GEM/interface/GEMDQMBase.h
  DQM/GEM/interface/GEMDigiSource.h
  DQM/GEM/interface/GEMRecHitSource.h
  DQM/GEM/plugins/GEMDAQStatusSource.cc
  DQM/GEM/plugins/GEMDQMHarvester.cc
  DQM/GEM/plugins/GEMDigiSource.cc
  DQM/GEM/plugins/GEMRecHitSource.cc
  DQM/GEM/python/GEMDQM_cff.py
  DQM/GEM/src/GEMDQMBase.cc
  DQM/GEM/test/test.py
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
  Validation/MuonGEMHits/interface/GEMValidationUtils.h
  Validation/MuonGEMHits/src/GEMValidationUtils.cc
Labels: backport-ok, dqm-approved, fully-signed, orp-approved, requires-external, tests-approved, urgent

#34763 [MagneticField] Move public headers to interface directory
  Configuration/Skimming/interface/LeptonSkimming.h
  MagneticField/Layers/interface/MagBRod.h
  MagneticField/Layers/interface/MagBinFinders.h
  MagneticField/VolumeBasedEngine/interface/MagGeometry.h
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, reconstruction-approved, tests-approved

#34631 fix incomplete esconsumes migration
  SimMuon/CSCDigitizer/src/CSCDigiProducer.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#34722 Allow multiple "--command" in runTheMatrix
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#34727 [Firework] Cleanup for public headers
  Fireworks/Core/bin/cmsShow.cc
  Fireworks/Core/interface/CmsShowMain.h
  Fireworks/Core/interface/CmsShowMainBase.h
  Fireworks/Core/interface/CmsShowTaskExecutor.h
  Fireworks/Core/interface/FWDialogBuilder.h
  Fireworks/Core/interface/FWItemSingleAccessor.h
  Fireworks/Core/src/CmsShowCommonPopup.cc
  Fireworks/Core/src/CmsShowEDI.cc
  Fireworks/Core/src/CmsShowMain.cc
  Fireworks/Core/src/CmsShowMainBase.cc
  Fireworks/Core/src/CmsShowModelPopup.cc
  Fireworks/Core/src/CmsShowNavigator.cc
  Fireworks/Core/src/CmsShowTaskExecutor.cc
  Fireworks/Core/src/CmsShowViewPopup.cc
  Fireworks/Core/src/FWDialogBuilder.cc
  Fireworks/Core/src/FWGUIEventDataAdder.cc
  Fireworks/Core/src/FWGUIManager.cc
  Fireworks/Core/src/FWGeometryTableManagerBase.cc
  Fireworks/Core/src/FWItemAccessorFactory.cc
  Fireworks/Core/src/FWItemSingleAccessor.cc
  Fireworks/Core/src/classes.h
  Fireworks/FWInterface/src/FWFFLooper.cc
  Fireworks/FWInterface/src/FWFFService.cc
  Fireworks/FWInterface/src/FWPSetTableManager.cc
  Fireworks/FWInterface/src/FWPathsPopup.cc
  Fireworks/ParticleFlow/plugins/FWPFCandidate3DProxyBuilder.cc
  Fireworks/TableWidget/interface/FWTabularWidget.h
  Fireworks/TableWidget/interface/FWTextTreeCellRenderer.h
  Fireworks/TableWidget/src/FWTableWidget.cc
  Fireworks/TableWidget/src/FWTabularWidget.cc
  Fireworks/TableWidget/src/FWTextTableCellRenderer.cc
  Fireworks/TableWidget/src/classes.h
  Fireworks/Tracks/plugins/FWItemTrackAccessors.cc
Labels: visualization-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34769 [GCC 11] Fix error "this pointer is null" in PhysicsTools/FWLite
  PhysicsTools/FWLite/interface/Scanner.h
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#34802 Create abstract XrdStatistics class
  FWCore/Framework/src/defaultCmsRunServices.cc
  FWCore/Services/plugins/CondorStatusUpdater.cc
  Utilities/XrdAdaptor/interface/XrdStatistics.h
  Utilities/XrdAdaptor/plugins/XrdStorageMaker.cc
  Utilities/XrdAdaptor/src/XrdStatistics.cc
  Utilities/XrdAdaptor/src/XrdStatistics.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34798 Fix loop in PFJetIDSelectionFunctor
  PhysicsTools/SelectorUtils/interface/PFJetIDSelectionFunctor.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34786 HCAL: HF SimHits timing fix
  Geometry/HcalSimData/python/HFParameters_cff.py
  SimCalorimetry/HcalSimProducers/python/hcalSimParameters_cfi.py
  SimG4CMS/Calo/interface/HFShower.h
  SimG4CMS/Calo/interface/HFShowerLibrary.h
  SimG4CMS/Calo/interface/HFShowerParam.h
  SimG4CMS/Calo/src/HFShower.cc
  SimG4CMS/Calo/src/HFShowerLibrary.cc
  SimG4CMS/Calo/src/HFShowerParam.cc
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34746 [L1] Move public headers to interface directory
  DQM/L1TMonitor/interface/L1TdeCSCTF.h
  EventFilter/GctRawToDigi/src/GctFormatTranslateBase.h
  L1Trigger/CSCTrackFinder/interface/CSCTFDTReceiver.h
  L1Trigger/CSCTrackFinder/plugins/CSCTFTrackProducer.h
  L1Trigger/CSCTrackFinder/src/CSCTFDTReceiver.cc
  L1Trigger/DTTrackFinder/interface/L1MuDTTFConfig.h
  L1Trigger/DTTrackFinder/plugins/DTTrackFinder.cc
  L1Trigger/DTTrackFinder/src/L1MuDTAssignmentUnit.cc
  L1Trigger/DTTrackFinder/src/L1MuDTDataBuffer.cc
  L1Trigger/DTTrackFinder/src/L1MuDTERS.cc
  L1Trigger/DTTrackFinder/src/L1MuDTEUX.cc
  L1Trigger/DTTrackFinder/src/L1MuDTEtaProcessor.cc
  L1Trigger/DTTrackFinder/src/L1MuDTExtrapolationUnit.cc
  L1Trigger/DTTrackFinder/src/L1MuDTMuonSorter.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSEU.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSectorProcessor.cc
  L1Trigger/DTTrackFinder/src/L1MuDTSectorReceiver.cc
  L1Trigger/DTTrackFinder/src/L1MuDTTFConfig.cc
  L1Trigger/DTTrackFinder/src/L1MuDTTrackAssembler.cc
  L1Trigger/DTTrackFinder/src/L1MuDTTrackFinder.cc
  L1Trigger/DTTrackFinder/src/L1MuDTWedgeSorter.cc
  L1Trigger/TextToDigi/interface/SourceCardRouting.h
  L1Trigger/TextToDigi/plugins/RctDigiToSourceCardText.h
  L1Trigger/TextToDigi/plugins/SourceCardTextToRctDigi.h
  L1Trigger/TextToDigi/src/SourceCardRouting.cc
  L1Trigger/TextToDigi/test/testSourceCardRouting.cpp
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34796 Run3-sim94 Rearranging the files in SimG4CMS/Forward
  SimG4CMS/Forward/interface/SimG4FluxProducer.h
  SimG4CMS/Forward/plugins/module.cc
  SimG4CMS/Forward/src/BscTest.cc
  SimG4CMS/Forward/src/SimG4FluxProducer.cc
  SimG4CMS/Forward/src/TimingSD.cc
  SimG4CMS/Forward/src/TotemRPNumberingScheme.cc
  SimG4CMS/Forward/src/TotemRPOrganization.cc
  SimG4CMS/Forward/src/TotemT1NumberingScheme.cc
  SimG4CMS/Forward/src/TotemT1Organization.cc
  SimG4CMS/Forward/src/TotemT2NumberingSchemeGem.cc
  SimG4CMS/Forward/src/TotemT2OrganizationGem.cc
  SimG4CMS/Forward/src/TotemTestGem.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34808 [BUGFIX] CocoaModel/src/Model.cc gcc11 compile error fix (issues #34756)
  Alignment/CocoaModel/src/Model.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#34814 Run3-Sim95 Collapse .h and .cc files if possible in SimG4CMS/Calo
  SimG4CMS/Calo/interface/CaloSteppingAction.h
  SimG4CMS/Calo/interface/HcalTestAnalysis.h
  SimG4CMS/Calo/plugins/CaloSteppingAction.cc
  SimG4CMS/Calo/plugins/HcalTestAnalysis.cc
  SimG4CMS/Calo/plugins/module.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34737 Run3-alca191 Stop using cout in the codes of Calibration/HcalCalibAlgos
  Calibration/HcalCalibAlgos/plugins/AnalyzerMinbias.cc
  Calibration/HcalCalibAlgos/plugins/Analyzer_minbias.cc
  Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalCalibrator.cc
  Calibration/HcalCalibAlgos/plugins/ValidIsoTrkCalib.cc
  Calibration/HcalCalibAlgos/src/HcalConstantsXMLWriter.cc
  Calibration/HcalCalibAlgos/test/DiJetAnalyzer.cc
  Calibration/HcalCalibAlgos/test/GammaJetAnalysis.cc
  Calibration/HcalCalibAlgos/test/HcalConstantsASCIIWriter.cc
  Calibration/HcalCalibAlgos/test/HcalCorrPFCalculation.cc
  Calibration/HcalCalibAlgos/test/HcalIsoTrackStudy.cc
  Calibration/HcalCalibAlgos/test/ValidationHcalIsoTrackAlCaReco.cc
  Calibration/HcalCalibAlgos/test/ValidationHcalIsoTrackAlCaReco.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34793 Add additional paths to customizeHLTIter0ToMkFit
  RecoTracker/MkFit/python/customizeHLTIter0ToMkFit.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34799 [12_0_X] backport : HF SimHits timing fix
  Geometry/HcalSimData/python/HFParameters_cff.py
  SimCalorimetry/HcalSimProducers/python/hcalSimParameters_cfi.py
  SimG4CMS/Calo/interface/HFShower.h
  SimG4CMS/Calo/interface/HFShowerLibrary.h
  SimG4CMS/Calo/interface/HFShowerParam.h
  SimG4CMS/Calo/src/HFShower.cc
  SimG4CMS/Calo/src/HFShowerLibrary.cc
  SimG4CMS/Calo/src/HFShowerParam.cc
Labels: geometry-approved, simulation-approved, fully-signed, tests-rejected, orp-approved

#34597 Fixed finecalo performance
  SimG4CMS/Calo/interface/CaloG4Hit.h
  SimG4CMS/Calo/interface/CaloHitID.h
  SimG4CMS/Calo/interface/CaloSD.h
  SimG4CMS/Calo/src/CaloHitID.cc
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Calo/src/CaloTrkProcessing.cc
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, upgrade-approved, code-checks-approved

#34608 [HGCal trigger] Remove deprecated v8 geometry code + Add new trigger geometry class
  DataFormats/ForwardDetId/interface/HGCalTriggerBackendCommon.h
  DataFormats/ForwardDetId/interface/HGCalTriggerBackendDetId.h
  DataFormats/ForwardDetId/interface/HGCalTriggerModuleDetId.h
  DataFormats/ForwardDetId/src/HGCalTriggerBackendDetId.cc
  DataFormats/ForwardDetId/src/HGCalTriggerModuleDetId.cc
  DataFormats/L1THGCal/interface/HGCalClusterT.h
  L1Trigger/L1THGCal/BuildFile.xml
  L1Trigger/L1THGCal/interface/HGCalCoarseTriggerCellMapping.h
  L1Trigger/L1THGCal/interface/HGCalTriggerGeometryBase.h
  L1Trigger/L1THGCal/interface/HGCalTriggerTools.h
  L1Trigger/L1THGCal/plugins/HGCalTriggerGeometryESProducer.cc
  L1Trigger/L1THGCal/plugins/concentrator/HGCalConcentratorProcessorSelection.cc
  L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryHexLayerBasedImp1.cc
  L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryV9Imp1.cc
  L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryV9Imp2.cc
  L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryV9Imp3.cc
  L1Trigger/L1THGCal/plugins/geometries/README.md
  L1Trigger/L1THGCal/plugins/veryfrontend/HGCalVFEProcessorSums.cc
  L1Trigger/L1THGCal/python/customTriggerGeometry.py
  L1Trigger/L1THGCal/python/egammaIdentification.py
  L1Trigger/L1THGCal/python/hgcalBackEndLayer1Producer_cfi.py
  L1Trigger/L1THGCal/python/hgcalBackEndLayer2Producer_cfi.py
  L1Trigger/L1THGCal/python/hgcalConcentratorProducer_cfi.py
  L1Trigger/L1THGCal/python/hgcalTriggerGeometryESProducer_cfi.py
  L1Trigger/L1THGCal/python/hgcalTriggerPrimitives_cff.py
  L1Trigger/L1THGCal/src/HGCalCoarseTriggerCellMapping.cc
  L1Trigger/L1THGCal/src/HGCalTriggerCellCalibration.cc
  L1Trigger/L1THGCal/src/HGCalTriggerTools.cc
  L1Trigger/L1THGCal/src/concentrator/HGCalConcentratorAutoEncoderImpl.cc
  L1Trigger/L1THGCal/src/concentrator/HGCalConcentratorCoarsenerImpl.cc
  L1Trigger/L1THGCal/src/concentrator/HGCalConcentratorSuperTriggerCellImpl.cc
  L1Trigger/L1THGCal/test/BuildFile.xml
  L1Trigger/L1THGCal/test/HGCalTriggerGeomTester.cc
  L1Trigger/L1THGCal/test/HGCalTriggerGeomTesterV9Imp3.cc
  L1Trigger/L1THGCal/test/testHGCalL1TGeometryV11Imp3_cfg.py
  L1Trigger/L1THGCalUtilities/plugins/CaloTruthCellsProducer.cc
  L1Trigger/L1THGCalUtilities/plugins/ntuples/HGCalTriggerNtupleHGCDigis.cc
  L1Trigger/L1THGCalUtilities/plugins/ntuples/HGCalTriggerNtupleHGCPanels.cc
  L1Trigger/L1THGCalUtilities/plugins/ntuples/HGCalTriggerNtupleHGCTriggerCells.cc
  L1Trigger/L1THGCalUtilities/plugins/ntuples/HGCalTriggerNtupleHGCTriggerSums.cc
  L1Trigger/L1THGCalUtilities/python/customNtuples.py
  L1Trigger/L1THGCalUtilities/python/hgcalTriggerNtuples_cff.py
  L1Trigger/L1THGCalUtilities/python/hgcalTriggerNtuples_cfi.py
Labels: l1-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved

#34452 Fix when neither "data" nor "MC" is specified in the cmsDriver.
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/Applications/python/cmsDriverOptions.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#34813 Run3-alca192A Utilize edm::LogVerbatim instead of cout in a number of classes of Calibration/IsolatedParticles
  Calibration/IsolatedParticles/interface/DebugInfo.h
  Calibration/IsolatedParticles/interface/eCone.icc
  Calibration/IsolatedParticles/interface/eHCALMatrix.icc
  Calibration/IsolatedParticles/plugins/IsolatedTracksCone.cc
  Calibration/IsolatedParticles/src/CaloPropagateTrack.cc
  Calibration/IsolatedParticles/src/DebugInfo.cc
  Calibration/IsolatedParticles/src/MatrixECALDetIds.cc
  Calibration/IsolatedParticles/test/CaloPropagationTest.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34819 Run3-sim97 Rearrange the files in SimG4CMS/ShowerLibraryProducer and collapse .h and .cc files
  SimG4CMS/ShowerLibraryProducer/interface/CastorShowerLibraryMaker.h
  SimG4CMS/ShowerLibraryProducer/interface/HcalForwardAnalysis.h
  SimG4CMS/ShowerLibraryProducer/plugins/CastorShowerLibraryMaker.cc
  SimG4CMS/ShowerLibraryProducer/plugins/HcalForwardAnalysis.cc
  SimG4CMS/ShowerLibraryProducer/plugins/module.cc
  SimG4CMS/Tracker/plugins/module.cc
  SimG4CMS/Tracker/src/TrackerG4SimHitNumberingScheme.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34820 OscarMTProducer clean-up
  SimG4Core/Application/plugins/OscarMTProducer.cc
  SimG4Core/Application/plugins/OscarMTProducer.h
  SimG4Core/Application/src/OscarMTMasterThread.cc
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#34574 [Backport] Track-gen matching passing through TrackingParticle (11_2_X)
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/Digi_cff.py
  Configuration/StandardSequences/python/RecoSim_cff.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/genParticleAssociation_cff.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  PhysicsTools/PatAlgos/python/tools/coreTools.py
  SimTracker/Configuration/python/SimTrackerLinks_cff.py
  SimTracker/Configuration/python/SimTracker_EventContent_cff.py
  SimTracker/TrackAssociation/plugins/BuildFile.xml
  SimTracker/TrackAssociation/plugins/DigiSimLinkPruner.cc
  SimTracker/TrackAssociation/plugins/MCTrackMatcher.cc
  SimTracker/TrackAssociation/plugins/PackedCandidateGenAssociationProducer.cc
  SimTracker/TrackAssociation/plugins/TrackingParticleSelectorByGen.cc
  SimTracker/TrackAssociation/python/digiSimLinkPruner_cfi.py
  SimTracker/TrackAssociation/python/trackMCMatch_cfi.py
  SimTracker/TrackAssociation/python/trackPrunedMCMatchTask_cff.py
  SimTracker/TrackAssociation/python/trackingParticlePrunerByGen_cfi.py
  SimTracker/TrackerHitAssociation/plugins/ClusterTPAssociationProducer.cc
Labels: operations-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#34606 Pixel cluster repair by morphing
  Configuration/ProcessModifiers/python/siPixelDigiMorphing_cff.py
  RecoLocalTracker/Configuration/python/RecoLocalTracker_cff.py
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.h
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizerPreSplitting_cfi.py
  RecoLocalTracker/SiPixelDigiReProducers/doc/SiPixelDigiReProducers.doc
  RecoLocalTracker/SiPixelDigiReProducers/plugins/BuildFile.xml
  RecoLocalTracker/SiPixelDigiReProducers/plugins/SiPixelDigiMorphing.cc
  RecoLocalTracker/SiPixelDigiReProducers/python/siPixelDigisMorphed_cfi.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34776 Run3-alca192 Add a few methods in Calibration/IsolatedParticles
  Calibration/IsolatedParticles/interface/CaloSimInfo.h
  Calibration/IsolatedParticles/interface/CaloSimInfo.icc
  Calibration/IsolatedParticles/interface/CaloSimInfoExtra.icc
  Calibration/IsolatedParticles/interface/ChargeIsolation.h
  Calibration/IsolatedParticles/interface/ChargeIsolationExtra.h
  Calibration/IsolatedParticles/interface/eECALMatrix.h
  Calibration/IsolatedParticles/interface/eECALMatrix.icc
  Calibration/IsolatedParticles/interface/eECALMatrixExtra.icc
  Calibration/IsolatedParticles/src/CaloSimInfo.cc
  Calibration/IsolatedParticles/src/ChargeIsolation.cc
  Calibration/IsolatedParticles/src/ChargeIsolationExtra.cc
Labels: alca-pending, pending-signatures, tests-rejected, orp-approved, code-checks-approved

#34773 [DQM] Cleanup for private header usage
  DQMOffline/Ecal/plugins/EcalZmassClient.cc
  DQMOffline/Ecal/plugins/EcalZmassTask.cc
  DQMServices/Components/bin/fastHadd.cc
  DQMServices/Core/interface/ROOTFilePB.pb.h
  DQMServices/Core/src/ROOTFilePB.pb.cc
  DQMServices/FileIO/plugins/DQMFileSaverPB.cc
  DQMServices/StreamerIO/plugins/DQMProtobufReader.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34794 Remove dead code and apply one fix in DQM/L1TMonitor
  DQM/L1TMonitor/src/L1TBPTX.cc
  DQM/L1TMonitor/src/L1TdeGCT.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34758 [GCC 11] Fix error "this pointer is null" in DQM/SiStripCommissioningDbClients
  DQM/SiStripCommissioningDbClients/src/FastFedCablingHistosUsingDb.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34784 Run3-alca193 Add DQM for HcalIterativePhiSymAlCaReco
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
  DQMOffline/CalibCalo/interface/DQMHcalIterativePhiSymAlCaReco.h
  DQMOffline/CalibCalo/plugins/SealModule.cc
  DQMOffline/CalibCalo/python/MonitorAlCaHcalIterativePhisym_cfi.py
  DQMOffline/CalibCalo/src/DQMHcalIterativePhiSymAlCaReco.cc
  DQMOffline/Configuration/python/ALCARECOHcalCalDQMHI_cff.py
  DQMOffline/Configuration/python/ALCARECOHcalCalDQM_cff.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34735 Rewrote checkForModuleDependencyCorrectness
  FWCore/Framework/src/PathsAndConsumesOfModules.cc
  FWCore/Framework/src/throwIfImproperDependencies.cc
  FWCore/Framework/src/throwIfImproperDependencies.h
  FWCore/Framework/test/BuildFile.xml
  FWCore/Framework/test/checkForModuleDependencyCorrectness_t.cppunit.cc
  FWCore/Framework/test/test_bad_schedule_exception_message_cfg.py
  FWCore/Framework/test/unit_test_outputs/test_bad_schedule_0.log
  FWCore/Framework/test/unit_test_outputs/test_bad_schedule_1.log
  FWCore/Framework/test/unit_test_outputs/test_bad_schedule_2.log
  FWCore/Framework/test/unit_test_outputs/test_bad_schedule_3.log
  FWCore/Framework/test/unit_test_outputs/test_bad_schedule_4.log
  FWCore/Framework/test/unit_test_outputs/test_bad_schedule_5.log
  FWCore/Framework/test/unit_test_outputs/test_bad_schedule_6.log
  FWCore/Framework/test/unit_test_outputs/test_bad_schedule_7.log
Labels: core-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#34816 Run3-sim96 Rearrange the files in SimG4CMS/Forward and collaspse some of the .h and .cc files
  SimG4CMS/Forward/interface/BscTest.h
  SimG4CMS/Forward/interface/CastorTestAnalysis.h
  SimG4CMS/Forward/interface/DoCastorAnalysis.h
  SimG4CMS/Forward/interface/SimG4FluxProducer.h
  SimG4CMS/Forward/interface/TotemTestGem.h
  SimG4CMS/Forward/interface/ZdcTestAnalysis.h
  SimG4CMS/Forward/plugins/BscTest.cc
  SimG4CMS/Forward/plugins/CastorTestAnalysis.cc
  SimG4CMS/Forward/plugins/DoCastorAnalysis.cc
  SimG4CMS/Forward/plugins/SimG4FluxProducer.cc
  SimG4CMS/Forward/plugins/TotemTestGem.cc
  SimG4CMS/Forward/plugins/ZdcTestAnalysis.cc
  SimG4CMS/Forward/plugins/module.cc
  SimG4CMS/Forward/src/BSCG4Hit.cc
  SimG4CMS/Forward/src/TotemG4Hit.cc
  SimG4CMS/Forward/src/ZdcNumberingScheme.cc
  SimG4CMS/Forward/src/ZdcSD.cc
  SimG4CMS/Forward/src/ZdcShowerLibrary.cc
  SimG4CMS/Forward/test/SimG4FluxAnalyzer.cc
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#34804 Fix the mergeLHE.py script
  GeneratorInterface/LHEInterface/scripts/mergeLHE.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#34757 [GCC 11] Fix error "array subscript outside array bounds"
  CondCore/EcalPlugins/plugins/EcalFloatCondObjectContainer_PayloadInspector.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#34439 Clean/rename FromMultiCl HGCal egamma collections
  DQMOffline/EGamma/python/egammaDQMOffline_cff.py
  DQMOffline/EGamma/python/electronAnalyzerSequence_cff.py
  DQMOffline/EGamma/python/electronOfflineClientSequence_cff.py
  DQMOffline/EGamma/python/photonOfflineDQMClient_cff.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoEcal/Configuration/python/RecoEcal_EventContent_cff.py
  RecoEcal/EgammaClusterProducers/python/particleFlowSuperClusteringSequence_cff.py
  RecoEgamma/Configuration/python/RecoEgamma_EventContent_cff.py
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronCoreEcalDrivenProducer.cc
  RecoEgamma/EgammaElectronProducers/python/ecalDrivenElectronSeeds_cff.py
  RecoEgamma/EgammaElectronProducers/python/ecalDrivenGsfElectronCoresFromMultiCl_cff.py
  RecoEgamma/EgammaElectronProducers/python/ecalDrivenGsfElectronCoresHGC_cff.py
  RecoEgamma/EgammaElectronProducers/python/gsfElectronSequence_cff.py
  RecoEgamma/EgammaElectronProducers/python/gsfElectrons_cfi.py
  RecoEgamma/EgammaElectronProducers/python/uncleanedOnlyElectronSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/photonCore_cfi.py
  RecoEgamma/EgammaPhotonProducers/python/photonSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/photons_cfi.py
  RecoEgamma/EgammaPhotonProducers/src/PhotonCoreProducer.cc
  RecoEgamma/EgammaTools/plugins/HGCalElectronFilter.cc
  RecoEgamma/EgammaTools/plugins/HGCalElectronIDValueMapProducer.cc
  RecoEgamma/EgammaTools/plugins/HGCalPhotonIDValueMapProducer.cc
  RecoEgamma/EgammaTools/python/slimmedEgammaHGC_cff.py
  RecoLocalCalo/Configuration/python/hgcalLocalReco_cff.py
  RecoParticleFlow/Configuration/python/RecoParticleFlow_EventContent_cff.py
  RecoParticleFlow/Configuration/python/RecoParticleFlow_cff.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHGC_cfi.py
  RecoParticleFlow/PFSimProducer/plugins/SimPFProducer.cc
  RecoParticleFlow/PFTracking/python/mergedElectronSeeds_cfi.py
  RecoTauTag/RecoTau/python/PATTauDiscriminationAgainstElectronMVA6Phase2_cff.py
  RecoTauTag/RecoTau/python/PFRecoTauDiscriminationAgainstElectronMVA6Phase2_cff.py
  TrackingTools/Configuration/python/TrackingTools_EventContent_cff.py
  TrackingTools/GsfTracking/python/CkfElectronCandidateMaker_cff.py
  TrackingTools/GsfTracking/python/GsfElectronGsfFit_cff.py
  TrackingTools/GsfTracking/python/GsfElectronTracking_cff.py
  Validation/HGCalValidation/plugins/HGCalHitCalibration.cc
  Validation/RecoEgamma/python/ElectronMcFakeValidator_gedGsfElectrons_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidatorMiniAOD_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidatorPt1000_gedGsfElectrons_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidator_gedGsfElectrons_cfi.py
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-rejected, orp-approved, upgrade-approved, code-checks-approved

#34728 Fix params for Payload Inspector
  CondCore/Utilities/scripts/getPayloadData.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#34823 Run3-alca192B Change std::cout to edm::LogVerbatim in a number of classes in Calibration/IsolatedParticles
  Calibration/IsolatedParticles/src/DetIdFromEtaPhi.cc
  Calibration/IsolatedParticles/src/FindCaloHitCone.cc
  Calibration/IsolatedParticles/src/FindDistCone.cc
  Calibration/IsolatedParticles/src/FindEtaPhi.cc
  Calibration/IsolatedParticles/src/GenSimInfo.cc
  Calibration/IsolatedParticles/src/MatchingSimTrack.cc
  Calibration/IsolatedParticles/src/MatrixHCALDetIds.cc
  Calibration/IsolatedParticles/src/TrackSelection.cc
  Calibration/IsolatedParticles/src/eECALMatrix.cc
  Calibration/IsolatedParticles/src/eHCALMatrix.cc
Labels: alca-approved, fully-signed, tests-started, orp-approved, code-checks-approved

#34571 Migrate module configuration in RecoMET to use default cfipython
  RecoMET/METPUSubtraction/python/mvaPFMET_leptons_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34612 Update DT DQM, calibration scripts, and local reco code to allow using "new" DB format
  CalibMuon/DTCalibration/plugins/DTTTrigResidualCorrection.cc
  CalibMuon/DTCalibration/plugins/DTTTrigResidualCorrection.h
  CalibMuon/DTCalibration/plugins/DTVDriftCalibration.cc
  CalibMuon/DTCalibration/plugins/DTVDriftCalibration.h
  CalibMuon/DTCalibration/python/dtTTrigResidualCorrection_cfi.py
  CalibMuon/DTCalibration/python/dtVDriftAnalyzer_cfg.py
  CalibMuon/DTCalibration/python/dtVDriftMeanTimerCalibration_cfi.py
  CalibMuon/DTCalibration/python/dtVDriftMeanTimerCalibration_cosmics_cfi.py
  CalibMuon/DTCalibration/python/dtVDriftMeanTimerWriter_cfi.py
  CalibMuon/DTCalibration/test/DBTools/DTVDriftAnalyzer.cc
  CalibMuon/DTCalibration/test/DBTools/DTVDriftAnalyzer.h
  CondTools/DT/test/validate/DTMtimeValidateDBRead.cc
  CondTools/DT/test/validate/DTMtimeValidateDBRead.h
  DQM/DTMonitorClient/python/dtRunConditionVarClient_cfi.py
  DQM/DTMonitorClient/src/DTRunConditionVarClient.cc
  DQM/DTMonitorClient/src/DTRunConditionVarClient.h
  DQM/DTMonitorModule/python/dtRunConditionVar_cfi.py
  DQM/DTMonitorModule/src/DTRunConditionVar.cc
  DQM/DTMonitorModule/src/DTRunConditionVar.h
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalMuon/DTRecHit/plugins/DTLinearDriftFromDBAlgo.cc
  RecoLocalMuon/DTRecHit/plugins/DTLinearDriftFromDBAlgo.h
  RecoLocalMuon/DTRecHit/python/DTLinearDriftFromDBAlgo_CosmicData_cfi.py
  RecoLocalMuon/DTRecHit/python/DTLinearDriftFromDBAlgo_cfi.py
Labels: alca-approved, dqm-approved, hlt-approved, reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#34847 CondCore/Utilities: cleaned up dependencies from CondCore/CondDB details
  CondCore/Utilities/bin/conddb_test_gt_perf.cpp
  CondCore/Utilities/src/CondDBTools.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#34836 Run3-sim99 Collapse .h and .cc files in SimG4CMS/EcalTestBeam
  SimG4CMS/EcalTestBeam/interface/EcalTBH4Trigger.h
  SimG4CMS/EcalTestBeam/interface/EcalTBMCInfoProducer.h
  SimG4CMS/EcalTestBeam/interface/FakeTBEventHeaderProducer.h
  SimG4CMS/EcalTestBeam/interface/FakeTBHodoscopeRawInfoProducer.h
  SimG4CMS/EcalTestBeam/interface/TBHodoActiveVolumeRawInfoProducer.h
  SimG4CMS/EcalTestBeam/plugins/EcalTBH4Trigger.cc
  SimG4CMS/EcalTestBeam/plugins/EcalTBMCInfoProducer.cc
  SimG4CMS/EcalTestBeam/plugins/FakeTBEventHeaderProducer.cc
  SimG4CMS/EcalTestBeam/plugins/FakeTBHodoscopeRawInfoProducer.cc
  SimG4CMS/EcalTestBeam/plugins/SealModule.cc
  SimG4CMS/EcalTestBeam/plugins/TBHodoActiveVolumeRawInfoProducer.cc
  SimG4CMS/PPS/plugins/module.cc
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#34830 Run3-sim98 Collapse .h and .cc files in SimG4CMS/FP420
  SimG4CMS/FP420/interface/FP420Test.h
  SimG4CMS/FP420/plugins/FP420Test.cc
  SimG4CMS/FP420/plugins/module.cc
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#34761 [Calib] Move public headers to interface directory
  CalibCalorimetry/CaloTPG/interface/CaloTPGTranscoderULUT.h
  CalibCalorimetry/CaloTPG/plugins/CaloTPGTranscoderULUTs.cc
  CalibCalorimetry/CaloTPG/src/CaloTPGTranscoderULUT.cc
  CalibMuon/DTDigiSync/interface/DTTTrigSyncFromDB.h
  CalibMuon/DTDigiSync/interface/DTTTrigSyncT0Only.h
  CalibMuon/DTDigiSync/interface/DTTTrigSyncTOFCorr.h
  CalibMuon/DTDigiSync/plugins/BuildFile.xml
  CalibMuon/DTDigiSync/plugins/SealModule.cc
  CalibMuon/DTDigiSync/src/DTTTrigSyncFromDB.cc
  CalibMuon/DTDigiSync/src/DTTTrigSyncT0Only.cc
  CalibMuon/DTDigiSync/src/DTTTrigSyncTOFCorr.cc
  CaloOnlineTools/HcalOnlineDb/interface/HcalLutManager.h
  L1TriggerConfig/L1ScalesProducers/src/L1CaloHcalScaleConfigOnlineProd.cc
  RecoLocalMuon/DTRecHit/plugins/SealModule.cc
Labels: l1-pending, alca-approved, reconstruction-approved, pending-signatures, tests-approved, db-approved, orp-approved, code-checks-approved

#34446 Adding LUT approach for PackedCandidates
  DataFormats/PatCandidates/interface/PackedCandidate.h
  PhysicsTools/PatUtils/plugins/PackedCandidatesTrackLiteModifier.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34576 Enable boosted tau reco to run at miniAOD
  PhysicsTools/PatAlgos/python/tools/helpers.py
  RecoJets/JetProducers/plugins/BoostedTauSeedsProducer.cc
  RecoTauTag/Configuration/python/tools/adaptToRunAtMiniAOD.py
  RecoTauTag/RecoTau/test/rerunTauRecoOnMiniAOD.py
Labels: reconstruction-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#34824 [GCC11] Fix "this pointer is null" in class FWRecoGeometryESProducer of Fireworks/Geometry
  Fireworks/Geometry/src/FWRecoGeometryESProducer.cc
Labels: visualization-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34817 Migrate module configuration in RecoPixelVertexing to use default cfipython
  RecoPixelVertexing/PixelLowPtUtilities/python/AllPixelTracks_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34818 Migrate module configuration in RecoVertex to use default cfipython
  RecoVertex/PrimaryVertexProducer/python/OfflinePixel3DPrimaryVertices_cfi.py
  RecoVertex/PrimaryVertexProducer/python/OfflinePrimaryVerticesFromCosmicTracks_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34825 [GCC11] Add missing #include for std::size_t definition
  HeterogeneousCore/CUDAUtilities/interface/deviceAllocatorStatus.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#34848 o2o tools fixes and improvements for python3
  CondCore/Utilities/python/o2olib.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#34855 Coderule script: fixes needed for python3
  Utilities/ReleaseScripts/python/cmsCodeRules/Formatter.py
  Utilities/ReleaseScripts/python/cmsCodeRules/pickleFileCreater.py
  Utilities/ReleaseScripts/python/cmsCodeRules/pickleFileParser.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34849 [SimCalorimetry] Avoid using private CondFormats/EcalObjects/src/classes.h
  SimCalorimetry/EcalSimProducers/plugins/EcalCATIAGainRatiosESProducer.cc
  SimCalorimetry/EcalSimProducers/plugins/EcalLiteDTUPedestalsESProducer.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34842 Run3-sim100 Take Vladimir's comments for include statements of CLHEP headers
  SimG4CMS/Calo/plugins/HFPMTHitAnalyzer.cc
  SimG4CMS/Calo/plugins/HOSimHitStudy.cc
  SimG4CMS/Calo/plugins/HcalTestAnalysis.cc
  SimG4CMS/Forward/plugins/BscTest.cc
  SimG4CMS/Forward/plugins/CastorTestAnalysis.cc
  SimG4CMS/Forward/plugins/DoCastorAnalysis.cc
  SimG4CMS/Forward/plugins/SimG4FluxProducer.cc
  SimG4CMS/Forward/plugins/TotemTestGem.cc
  SimG4CMS/Forward/plugins/ZdcTestAnalysis.cc
  SimG4CMS/HGCalTestBeam/plugins/HGCalTimingAnalyzer.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB02Analysis.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB04Analysis.cc
  SimG4CMS/HcalTestBeam/plugins/HcalTB06Analysis.cc
  SimG4CMS/ShowerLibraryProducer/plugins/CastorShowerLibraryMaker.cc
  SimG4CMS/ShowerLibraryProducer/plugins/HcalForwardAnalysis.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#34826 Replace boost::regex with std::regex
  CondCore/CondDB/interface/Utils.h
  CondCore/Utilities/interface/PayloadInspector.h
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#34852 [GCC11] Fix warning: loop variable binds to a temporary
  PhysicsTools/PatAlgos/plugins/PATObjectUserDataEmbedder.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34832 [RFC] add `commissioning_run` as DQM runType and use it in SiStrip online DQM client
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/config/dqmPythonTypes.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34837 Performance improvements for DQM startup
  DQMServices/Core/interface/MonitorElement.h
  DataFormats/Histograms/interface/MonitorElementCollection.h
  DataFormats/Histograms/test/BuildFile.xml
  DataFormats/Histograms/test/MonitorElementData_Path_catch.cc
Labels: core-approved, dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34856 Run3-gex87 Modify material budget code relevant to study XML vs DB
  Validation/Geometry/macros/MatBudgetVolume.C
  Validation/Geometry/test/runMaterialBudgetVolumeDB_cfg.py
  Validation/Geometry/test/runMaterialBudgetVolumeXML_cfg.py
Labels: dqm-approved, geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34851 Pixel cluster repair by morphing backport to 12_0_X
  Configuration/ProcessModifiers/python/siPixelDigiMorphing_cff.py
  RecoLocalTracker/Configuration/python/RecoLocalTracker_cff.py
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.h
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizerPreSplitting_cfi.py
  RecoLocalTracker/SiPixelDigiReProducers/doc/SiPixelDigiReProducers.doc
  RecoLocalTracker/SiPixelDigiReProducers/plugins/BuildFile.xml
  RecoLocalTracker/SiPixelDigiReProducers/plugins/SiPixelDigiMorphing.cc
  RecoLocalTracker/SiPixelDigiReProducers/python/siPixelDigisMorphed_cfi.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-rejected, orp-approved, backport-ok

#34857 Run3-sim101 Modified the examination of geometry in XML and DB
  SimG4Core/PrintGeomInfo/test/SimFileCompare.cpp
  SimG4Core/PrintGeomInfo/test/python/g4DumpGeometry_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck2026_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckCalo_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckDD4Hep_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckEcal_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckHGCal_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckMuon_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckTracker_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck_dd4hep_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runDD4HepDB_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runDD4HepXML_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runDDDDB_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runDDDXML_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runSens_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runSummary_cfg.py
  SimG4Core/PrintGeomInfo/test/python/run_MaterialBudgeInfo_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34829 Run3-alca196 Collapse .h and .cc files in DQMOffline/CalibCalo and reorganize the files
  DQMOffline/CalibCalo/BuildFile.xml
  DQMOffline/CalibCalo/interface/DQMHcalIterativePhiSymAlCaReco.h
  DQMOffline/CalibCalo/interface/DQMSourceEleCalib.h
  DQMOffline/CalibCalo/plugins/BuildFile.xml
  DQMOffline/CalibCalo/plugins/DQMHOAlCaRecoStream.cc
  DQMOffline/CalibCalo/plugins/DQMHcalDiJetsAlCaReco.cc
  DQMOffline/CalibCalo/plugins/DQMHcalIsoTrackAlCaReco.cc
  DQMOffline/CalibCalo/plugins/DQMHcalIsoTrackPostProcessor.cc
  DQMOffline/CalibCalo/plugins/DQMHcalIsolatedBunchAlCaReco.cc
  DQMOffline/CalibCalo/plugins/DQMHcalIterativePhiSymAlCaReco.cc
  DQMOffline/CalibCalo/plugins/DQMHcalPhiSymAlCaReco.cc
  DQMOffline/CalibCalo/plugins/DQMSourceEleCalib.cc
  DQMOffline/CalibCalo/plugins/DQMSourcePi0.cc
  DQMOffline/CalibCalo/plugins/SealModule.cc
  DQMOffline/CalibCalo/src/DQMHOAlCaRecoStream.h
  DQMOffline/CalibCalo/src/DQMHcalDiJetsAlCaReco.h
  DQMOffline/CalibCalo/src/DQMHcalIsoTrackAlCaReco.h
  DQMOffline/CalibCalo/src/DQMHcalIsolatedBunchAlCaReco.h
  DQMOffline/CalibCalo/src/DQMHcalPhiSymAlCaReco.h
  DQMOffline/CalibCalo/src/DQMSourcePi0.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34833 Remove dead assignments for ZToMuMuGammaAnalyzer and HGCalSimHitValidation
  DQMOffline/EGamma/plugins/SealModule.cc
  DQMOffline/EGamma/plugins/ZToMuMuGammaAnalyzer.cc
  DQMOffline/EGamma/plugins/ZToMuMuGammaAnalyzer.h
  Validation/HGCalValidation/plugins/HGCalSimHitValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34862 [DQM] Remove unnecessary include statements to avoid private header dep
  DQM/CastorMonitor/interface/CastorRecHitMonitor.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34844 PPS Alignment - bug fix
  CondCore/CTPPSPlugins/src/plugin.cc
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
  CondFormats/PPSObjects/interface/PPSAlignmentConfig.h
  CondFormats/PPSObjects/src/PPSAlignmentConfig.cc
  CondFormats/PPSObjects/src/T_EventSetup_PPSAlignmentConfig.cc
  CondFormats/PPSObjects/src/classes_def.xml
  CondFormats/PPSObjects/src/headers.h
  CondFormats/PPSObjects/test/BuildFile.xml
  CondFormats/PPSObjects/test/testSerializationPPSAlignmentConfig.cc
  CondTools/CTPPS/plugins/RetrievePPSAlignmentConfig.cc
  CondTools/CTPPS/plugins/WritePPSAlignmentConfig.cc
  CondTools/CTPPS/test/retrieve_PPSAlignmentConfig_cfg.py
  CondTools/CTPPS/test/write_PPSAlignmentConfig_cfg.py
Labels: alca-approved, fully-signed, tests-approved, db-approved, bug-fix, orp-approved, code-checks-approved

#34869 Add missing include in CondDBTools.cc
  CondCore/Utilities/src/CondDBTools.cc
Labels: db-pending, pending-signatures, tests-started, orp-approved, code-checks-approved

#34871 [Validation] Removed unnecessary include statements
  Validation/RecoMuon/plugins/MuonTrackValidator.cc
  Validation/RecoTrack/plugins/MultiTrackValidator.cc
  Validation/RecoTrack/plugins/MultiTrackValidatorGenPs.cc
  Validation/SiTrackerPhase2V/plugins/Phase2TrackerValidateDigi.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34870 [TkTrackingRegions] Move public headers to interface directory
  RecoTracker/ConversionSeedGenerators/plugins/PhotonConversionTrajectorySeedProducerFromQuadrupletsAlgo.h
  RecoTracker/ConversionSeedGenerators/plugins/PhotonConversionTrajectorySeedProducerFromSingleLegAlgo.h
  RecoTracker/TkTrackingRegions/interface/GlobalTrackingRegionProducerFromBeamSpot.h
  RecoTracker/TkTrackingRegions/plugins/SealModule.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34868 [RecoTracker] Move public headers to interface directory
  RecoTracker/FinalTrackSelectors/interface/getBestVertex.h
  RecoTracker/FinalTrackSelectors/plugins/DefaultTrackMVAClassifier.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackCutClassifier.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackLwtnnClassifier.cc
  RecoTracker/FinalTrackSelectors/plugins/TrackTfClassifier.cc
  Validation/RecoTrack/plugins/TrackingNtuple.cc
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34867 [RecoPixelVertexing] Move public headers to interface directory
  RecoPixelVertexing/PixelTriplets/interface/ThirdHitRZPrediction.h
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletHLTGenerator.cc
  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletLargeTipGenerator.cc
  RecoTracker/TkSeedGenerator/plugins/MultiHitGeneratorFromChi2.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34864 [RecoMuon] Remove unnecessary include statements to avoid private hdr deps
  RecoMuon/MuonIdentification/test/MuonTimingValidator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34828 Validation plots for APE and bug fixes
  Alignment/APEEstimation/plugins/ApeEstimatorSummary.cc
  Alignment/APEEstimation/python/AlignmentTrackSelector_cff.py
  Alignment/APEEstimation/python/TrackRefitter_38T_cff.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitter.py
  Alignment/APEEstimation/test/autoSubmitter/config.ini
  Alignment/APEEstimation/test/cfgTemplate/apeEstimator_cfg.py
  Alignment/APEEstimation/test/plottingTools/drawResults.py
  Alignment/APEEstimation/test/plottingTools/drawValidation.py
  Alignment/APEEstimation/test/plottingTools/resultPlotter.py
  Alignment/APEEstimation/test/plottingTools/validationPlotter.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34759 Diamond Sampic reco
  RecoPPS/Local/interface/TotemTimingConversions.h
  RecoPPS/Local/interface/TotemTimingRecHitProducerAlgorithm.h
  RecoPPS/Local/plugins/TotemTimingLocalTrackFitter.cc
  RecoPPS/Local/plugins/TotemTimingRecHitProducer.cc
  RecoPPS/Local/python/totemTimingLocalReconstruction_cff.py
  RecoPPS/Local/src/TotemTimingConversions.cc
  RecoPPS/Local/src/TotemTimingRecHitProducerAlgorithm.cc
  RecoPPS/Local/test/DiamondSampicDigiProducer.cc
  RecoPPS/Local/test/totemTiming_digiConverter_reco_cfg.py
  RecoPPS/Local/test/totemTiming_reco_cfg.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34876 [Tracker Alignment] Miscellaneous fixes in `Alignment/OfflineValidation` all-in-one tool
  Alignment/OfflineValidation/python/TkAlAllInOneTool/offlineValidationTemplates.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexResolutionTemplates.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/zMuMuValidationTemplates.py
  Alignment/OfflineValidation/test/test_all.sh
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#34853 [CalibMuon] Move and merge .h and .cc files used by plugin
  CalibMuon/DTCalibration/python/PlottingTools/plotT0FromHistos.py
  CalibMuon/DTDigiSync/BuildFile.xml
  CalibMuon/DTDigiSync/interface/DTTTrigSyncFromDB.h
  CalibMuon/DTDigiSync/interface/DTTTrigSyncT0Only.h
  CalibMuon/DTDigiSync/interface/DTTTrigSyncTOFCorr.h
  CalibMuon/DTDigiSync/plugins/BuildFile.xml
  CalibMuon/DTDigiSync/plugins/DTTTrigSyncFromDB.cc
  CalibMuon/DTDigiSync/plugins/DTTTrigSyncT0Only.cc
  CalibMuon/DTDigiSync/plugins/DTTTrigSyncTOFCorr.cc
  CalibMuon/DTDigiSync/plugins/SealModule.cc
  RecoLocalMuon/DTRecHit/BuildFile.xml
  RecoLocalMuon/DTRecHit/plugins/BuildFile.xml
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34821 GEM Validation update
  DQM/GEM/interface/GEMDigiSource.h
  DQM/GEM/plugins/GEMDigiSource.cc
  DQM/GEM/python/GEMDQM_cff.py
  DQM/GEM/src/GEMDQMBase.cc
  Validation/Configuration/python/gemSimValid_cff.py
  Validation/MuonGEMDigis/plugins/GEMCoPadDigiValidation.cc
  Validation/MuonGEMDigis/plugins/GEMPadDigiClusterValidation.cc
  Validation/MuonGEMDigis/plugins/GEMPadDigiValidation.cc
  Validation/MuonGEMDigis/plugins/GEMStripDigiValidation.cc
  Validation/MuonGEMDigis/plugins/GEMStripDigiValidation.h
  Validation/MuonGEMDigis/plugins/MuonGEMDigisHarvestor.cc
  Validation/MuonGEMDigis/python/PostProcessor_cff.py
  Validation/MuonGEMHits/interface/GEMBaseValidation.h
  Validation/MuonGEMHits/plugins/GEMSimHitValidation.cc
  Validation/MuonGEMRecHits/plugins/GEMRecHitValidation.cc
  Validation/MuonGEMRecHits/plugins/GEMRecHitValidation.h
  Validation/MuonGEMRecHits/plugins/MuonGEMRecHitsHarvestor.cc
  Validation/MuonGEMRecHits/python/PostProcessor_cff.py
Labels: dqm-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34505 Adding the codes for ECAL Phase2 amplitude local reconstruction
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitPhase2WeightsProducer.cc
  RecoLocalCalo/EcalRecProducers/python/ecalUncalibRecHitPhase2_cff.py
  RecoLocalCalo/EcalRecProducers/python/ecalUncalibRecHitPhase2_cfi.py
  RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRecHitPhase2WeightsProducer.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34809 Clean unused dependencies from BuildFiles
  Alignment/LaserAlignment/BuildFile.xml
  CommonTools/CandAlgos/plugins/BuildFile.xml
  Configuration/Skimming/BuildFile.xml
  DQM/GEM/plugins/BuildFile.xml
  IOMC/EventVertexGenerators/test/BuildFile.xml
  L1Trigger/L1TGEM/test/BuildFile.xml
  PhysicsTools/HepMCCandAlgos/test/BuildFile.xml
  SimG4CMS/Calo/BuildFile.xml
  SimG4CMS/Calo/plugins/BuildFile.xml
  SimG4CMS/HGCalTestBeam/BuildFile.xml
  SimG4CMS/HGCalTestBeam/plugins/BuildFile.xml
  SimG4CMS/HcalTestBeam/BuildFile.xml
  SimG4CMS/HcalTestBeam/plugins/BuildFile.xml
  SimG4CMS/Muon/BuildFile.xml
  SimG4CMS/Muon/plugins/BuildFile.xml
  SimG4CMS/ShowerLibraryProducer/plugins/BuildFile.xml
  SimG4CMS/Tracker/BuildFile.xml
  SimG4CMS/Tracker/plugins/BuildFile.xml
  SimG4Core/Application/test/BuildFile.xml
  SimGeneral/Debugging/test/BuildFile.xml
Labels: l1-pending, analysis-pending, alca-approved, dqm-approved, reconstruction-approved, simulation-approved, pending-signatures, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#34881 [Alignment/HIPAlignmentAlgorithm] modernize `LhcTrackAnalyzer`
  Alignment/HIPAlignmentAlgorithm/interface/LhcTrackAnalyzer.h
  Alignment/HIPAlignmentAlgorithm/plugins/LhcTrackAnalyzer.cc
  Alignment/HIPAlignmentAlgorithm/src/HIPAlignmentAlgorithm.cc
  Alignment/HIPAlignmentAlgorithm/src/LhcTrackAnalyzer.cc
  Alignment/HIPAlignmentAlgorithm/test/LHCAnalyzer_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34877 [12.0.X] Miscellaneous fixes to `Alignment/OflineValidation` all-in-one tool
  Alignment/OfflineValidation/python/TkAlAllInOneTool/offlineValidationTemplates.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexResolutionTemplates.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/zMuMuValidationTemplates.py
  Alignment/OfflineValidation/test/test_all.sh
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#34875 more Python3 fixes for geometry script
  Configuration/Geometry/python/generateGeometry.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#34878 [11.3.X] Miscellaneous fixes to `Alignment/OfflineValidation` all-in-one tool
  Alignment/OfflineValidation/python/TkAlAllInOneTool/offlineValidationTemplates.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/primaryVertexResolutionTemplates.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/zMuMuValidationTemplates.py
  Alignment/OfflineValidation/test/test_all.sh
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#34879 Run3-gex88 Make P5 as the default for 2021 scenarios
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#34874 [DBG] Fixes needed for 08-12-2300 DBG IB
  Calibration/HcalCalibAlgos/test/GammaJetAnalysis.cc
  SimG4CMS/Forward/src/ZdcSD.cc
  SimG4CMS/Tracker/src/TrackerG4SimHitNumberingScheme.cc
Labels: alca-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34846 Fix rare crash in pixel template interpolation
  CondFormats/SiPixelTransient/src/SiPixelTemplate.cc
  CondFormats/SiPixelTransient/src/SiPixelTemplate2D.cc
Labels: reconstruction-approved, fully-signed, tests-approved, db-approved, bug-fix, orp-approved, code-checks-approved

#34845 PPS Alignment - bug fix (backport)
  CondCore/CTPPSPlugins/src/plugin.cc
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
  CondFormats/PPSObjects/interface/PPSAlignmentConfig.h
  CondFormats/PPSObjects/src/PPSAlignmentConfig.cc
  CondFormats/PPSObjects/src/T_EventSetup_PPSAlignmentConfig.cc
  CondFormats/PPSObjects/src/classes_def.xml
  CondFormats/PPSObjects/src/headers.h
  CondFormats/PPSObjects/test/BuildFile.xml
  CondFormats/PPSObjects/test/testSerializationPPSAlignmentConfig.cc
  CondTools/CTPPS/plugins/RetrievePPSAlignmentConfig.cc
  CondTools/CTPPS/plugins/WritePPSAlignmentConfig.cc
  CondTools/CTPPS/test/retrieve_PPSAlignmentConfig_cfg.py
  CondTools/CTPPS/test/write_PPSAlignmentConfig_cfg.py
Labels: alca-approved, fully-signed, tests-approved, db-approved, bug-fix, orp-approved, backport-ok

#34886 BuildFile: use py3-sqlalchemy
  CondTools/RunInfo/test/BuildFile.xml
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#34892 Fix typo in the RelMon category
  Utilities/RelMon/python/definitions.py
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#34883 Buildfile cleanup: remove non-existing module.cc file
  SimG4CMS/ShowerLibraryProducer/plugins/BuildFile.xml
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34897 [Calib] Move private header in to src directory
  Calibration/HcalCalibAlgos/src/hcalCalib.cc
  Calibration/HcalCalibAlgos/src/hcalCalibUtils.cc
  Calibration/HcalCalibAlgos/src/hcalCalibUtils.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34896 [Fireworks] Move public headers in to interface directory
  Fireworks/Calo/interface/FWCaloDataHistProxyBuilder.h
  Fireworks/Calo/interface/FWECALDetailViewBase.h
  Fireworks/Calo/interface/FWECALDetailViewBase.icc
  Fireworks/Calo/interface/FWFromSliceSelector.h
  Fireworks/Calo/interface/FWFromTEveCaloDataSelector.h
  Fireworks/Calo/interface/FWHistSliceSelector.h
  Fireworks/Calo/plugins/FWCaloTowerProxyBuilder.h
  Fireworks/Calo/plugins/FWHFTowerProxyBuilder.h
  Fireworks/Calo/plugins/FWHFTowerSliceSelector.h
  Fireworks/Calo/plugins/FWHGTowerProxyBuilder.h
  Fireworks/Calo/plugins/FWHGTowerSliceSelector.h
  Fireworks/Calo/src/FWCaloDataProxyBuilderBase.cc
  Fireworks/Calo/src/FWFromSliceSelector.cc
  Fireworks/Calo/src/FWFromTEveCaloDataSelector.cc
  Fireworks/Core/interface/CmsShowTaskExecutor.h
  Fireworks/Core/interface/CmsShowTaskExecutorBase.h
  Fireworks/Core/interface/FWDetailViewCanvas.h
  Fireworks/Core/interface/FWDetailViewCanvas.icc
  Fireworks/Core/interface/FWDetailViewGL.h
  Fireworks/Core/interface/FWDetailViewGL.icc
  Fireworks/Core/interface/FWHLTValidator.h
  Fireworks/Core/interface/FWItemAccessorRegistry.h
  Fireworks/Core/interface/FWTEventList.h
  Fireworks/Core/interface/FWValidatorBase.h
  Fireworks/Core/interface/FWXMLConfigParser.h
  Fireworks/Core/interface/SimpleSAXParser.h
  Fireworks/Core/src/CmsShowMainBase.cc
  Fireworks/Core/src/CmsShowTaskExecutorBase.cc
  Fireworks/Core/src/CmsShowTaskTimer.cc
  Fireworks/Core/src/FWConfigurationManager.cc
  Fireworks/Core/src/FWExpressionValidator.h
  Fireworks/Core/src/FWGeometryTableView.cc
  Fireworks/Core/src/FWOverlapTableView.cc
  Fireworks/Core/src/FWPartialConfig.cc
  Fireworks/Core/src/SimpleSAXParser.cc
Labels: visualization-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34697 Apply task chains to more code in FWCore/Framework
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/SubProcess.cc
  FWCore/Framework/src/globalTransitionAsync.h
  FWCore/Framework/src/streamTransitionAsync.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34900 Do not produce NaNs in `SiPixelActionExecutor`
  DQM/SiPixelMonitorClient/src/SiPixelActionExecutor.cc
  DQM/SiPixelMonitorDigi/src/SiPixelDigiSource.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34834 Migrate module configuration in RecoTauTag to use default cfipython
  RecoTauTag/RecoTau/python/PATTauDiscriminationByMVAIsolationRun2_cff.py
  RecoTauTag/RecoTau/python/PFRecoTauDiscriminationByMVAIsolation2_cff.py
  RecoTauTag/RecoTau/python/PFRecoTauTagInfoProducer_cfi.py
  RecoTauTag/RecoTau/python/PFTauPrimaryVertexProducer_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34903 [GCC10] Use constexpr which fixes gcc10/ASAN build error
  Alignment/HIPAlignmentAlgorithm/plugins/LhcTrackAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34909 [HGCAL] make makeHGCalValidationPlots.py executable again
  Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py
Labels: dqm-pending, pending-signatures, tests-pending, orp-approved, code-checks-approved

#34894 [Generator] Move public headers in to interface directory
  GeneratorInterface/CosmicMuonGenerator/interface/Point5MaterialMap.h
  GeneratorInterface/CosmicMuonGenerator/interface/SingleParticleEvent.h
  GeneratorInterface/Hydjet2Interface/interface/EquationSolver.h
  GeneratorInterface/Hydjet2Interface/interface/EquationSolver.icc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34888 [12_0_X] Fix rare crash in pixel template interpolation
  CondFormats/SiPixelTransient/src/SiPixelTemplate.cc
  CondFormats/SiPixelTransient/src/SiPixelTemplate2D.cc
Labels: reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, backport-ok

#34915 Created setupSiteLocalConfig
  FWCore/Services/bin/cmsGetFnConnect.cc
  FWCore/Services/interface/setupSiteLocalConfig.h
  FWCore/Services/src/setupSiteLocalConfig.cc
  IOPool/Common/bin/EdmCopyUtil.cpp
  IOPool/Common/bin/EdmFileUtil.cpp
  IOPool/Common/bin/EdmProvDump.cc
  IOPool/Streamer/test/ReadStreamerFile.cpp
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34891 Moved headers from src to interface in FWCore/Framework
  FWCore/Framework/interface/EventSetupsController.h
  FWCore/Framework/interface/ModuleRegistry.h
  FWCore/Framework/interface/ProductPutterBase.h
  FWCore/Framework/interface/SharedResourcesRegistry.h
  FWCore/Framework/interface/globalTransitionAsync.h
  FWCore/Framework/interface/streamTransitionAsync.h
  FWCore/Framework/src/EDAnalyzer.cc
  FWCore/Framework/src/EDFilter.cc
  FWCore/Framework/src/EDProducer.cc
  FWCore/Framework/src/ESProducer.cc
  FWCore/Framework/src/Event.cc
  FWCore/Framework/src/EventPrincipal.cc
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/EventSetupProvider.cc
  FWCore/Framework/src/EventSetupsController.cc
  FWCore/Framework/src/LuminosityBlock.cc
  FWCore/Framework/src/LuminosityBlockPrincipal.cc
  FWCore/Framework/src/ModuleFactory.cc
  FWCore/Framework/src/ModuleRegistry.cc
  FWCore/Framework/src/Principal.cc
  FWCore/Framework/src/ProcessBlock.cc
  FWCore/Framework/src/ProcessBlockPrincipal.cc
  FWCore/Framework/src/ProductResolvers.h
  FWCore/Framework/src/Run.cc
  FWCore/Framework/src/RunPrincipal.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/SharedResourcesRegistry.cc
  FWCore/Framework/src/SourceFactory.cc
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/src/SubProcess.cc
  FWCore/Framework/src/SynchronousEventSetupsController.h
  FWCore/Framework/src/WorkerRegistry.cc
  FWCore/Framework/src/one/implementorsMethods.h
  FWCore/Framework/test/eventsetupplugin_t.cppunit.cc
  FWCore/Framework/test/eventsetupscontroller_t.cppunit.cc
  FWCore/Framework/test/sharedresourcesregistry_t.cppunit.cc
  FWCore/TestProcessor/interface/TestProcessor.h
  FWCore/TestProcessor/src/TestProcessor.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootDelayedReader.cc
  IOPool/Input/src/RootFile.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34905 [Validation] Use correct header for ParametersDefinerForTP
  Validation/RecoTrack/plugins/TrackingNtuple.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34911 [HLTriggerOffline] Move Higgs sources in to plugins dir
  HLTriggerOffline/Higgs/plugins/BuildFile.xml
  HLTriggerOffline/Higgs/plugins/EVTColContainer.h
  HLTriggerOffline/Higgs/plugins/HLTHiggsPlotter.cc
  HLTriggerOffline/Higgs/plugins/HLTHiggsPlotter.h
  HLTriggerOffline/Higgs/plugins/HLTHiggsSubAnalysis.cc
  HLTriggerOffline/Higgs/plugins/HLTHiggsSubAnalysis.h
  HLTriggerOffline/Higgs/plugins/HLTHiggsValidator.cc
  HLTriggerOffline/Higgs/plugins/HLTHiggsValidator.h
  HLTriggerOffline/Higgs/plugins/MatchStruct.h
  HLTriggerOffline/Higgs/plugins/SealModules.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34916 Move Guid.h to interface
  FWCore/Utilities/interface/Guid.h
  FWCore/Utilities/src/GlobalIdentifier.cc
  FWCore/Utilities/src/Guid.cc
  FWCore/Utilities/test/Guid_t.cpp
  Utilities/StorageFactory/src/StatisticsSenderService.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34912 (DAQ) input source - minimum starting lumisection
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/src/EvFDaqDirector.cc
  EventFilter/Utilities/src/FedRawDataInputSource.cc
Labels: daq-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#34858 initialize Trackster::iterationIndex_
  DataFormats/HGCalReco/interface/Trackster.h
Labels: reconstruction-approved, pending-signatures, tests-approved, orp-approved, upgrade-pending, code-checks-approved
