Repository cms-sw/cmssw, pull requests merged in 2021-01, with the labels that each got.

#32583 Run3-gex45 Use of ESGetToken in EcalAlgo examples
  Geometry/EcalAlgo/test/EcalBarrelCellParameterDump.cc
  Geometry/EcalAlgo/test/EcalEndcapCellParameterDump.cc
  Geometry/EcalAlgo/test/EcalPreshowerParameterDump.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#32048 MLPF: first integration of EDProducer and training code
  Configuration/ProcessModifiers/python/mlpf_cff.py
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  RecoParticleFlow/Configuration/python/RecoParticleFlow_EventContent_cff.py
  RecoParticleFlow/Configuration/python/RecoParticleFlow_cff.py
  RecoParticleFlow/PFProducer/interface/MLPFModel.h
  RecoParticleFlow/PFProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFProducer/plugins/MLPFProducer.cc
  RecoParticleFlow/PFProducer/python/mlpf_EventContent_cff.py
  RecoParticleFlow/PFProducer/src/MLPFModel.cc
  RecoParticleFlow/PFProducer/test/mlpf_training/generate.sh
  RecoParticleFlow/PFProducer/test/mlpf_training/preprocessing.py
  RecoParticleFlow/PFProducer/test/mlpf_training/run.sh
  RecoParticleFlow/PFProducer/test/mlpf_training/tf_data.py
  RecoParticleFlow/PFProducer/test/mlpf_training/tf_model.py
  Validation/RecoParticleFlow/plugins/PFAnalysisNtuplizer.cc
  Validation/RecoParticleFlow/python/customize_pfanalysis.py
  Validation/RecoParticleFlow/test/pfanalysis_ntuple.py
Labels: code-checks-approved, dqm-approved, fully-signed, operations-approved, orp-approved, pdmv-approved, reconstruction-approved, tests-approved, upgrade-approved

#32584 CT-PPS DQM: Minor bug fix and improved readability
  DQM/CTPPS/plugins/CTPPSPixelDQMSource.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32595 Run3-sim80 Make the Cherenkov example working for DDD
  Geometry/HcalCommonData/src/CaloSimParametersFromDD.cc
  SimG4CMS/CherenkovAnalysis/data/SingleDREAMDD4Hep.xml
  SimG4CMS/CherenkovAnalysis/data/singleDREAM.xml
  SimG4CMS/CherenkovAnalysis/python/SingleDREAMXML_cfi.py
  SimG4CMS/CherenkovAnalysis/src/DreamSD.cc
  SimG4CMS/CherenkovAnalysis/test/runSingleDREAMDD4Hep_cfg.py
  SimG4CMS/CherenkovAnalysis/test/runSingleDREAMDDD_cfg.py
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#32589 Fix incorrect cast in CastorShowerLibrary
  SimG4CMS/Forward/interface/CastorShowerLibrary.h
  SimG4CMS/Forward/src/CastorShowerLibrary.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#32590 Run3-hcx280 Use ESGetToken in CalibCalorimetry/HcalAlgos
  CalibCalorimetry/HcalAlgos/interface/HcalLedAnalysis.h
  CalibCalorimetry/HcalAlgos/interface/HcalPedestalAnalysis.h
  CalibCalorimetry/HcalAlgos/plugins/HcalPulseContainmentTest.cc
  CalibCalorimetry/HcalAlgos/test/MapTester.cc
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#32538 Make units dd4hep-dependent in PPS
  Geometry/VeryForwardGeometryBuilder/interface/DetGeomDesc.h
  Geometry/VeryForwardGeometryBuilder/src/DetGeomDesc.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#32602 PPS direct simulation: add 2021 profile
  Geometry/VeryForwardData/data/2021/v1/RP_Dist_Beam_Cent.xml
  Geometry/VeryForwardGeometry/python/geometryRPFromDD_2021_cfi.py
  Validation/CTPPS/alignment/2021.xml
  Validation/CTPPS/python/simu_config/profile_2021_default_cff.py
  Validation/CTPPS/python/simu_config/year_2021_cff.py
  Validation/CTPPS/test/simu/run_multiple
Labels: code-checks-approved, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#32607 Reduce use of Worker::doWork
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/test/global_filter_t.cppunit.cc
  FWCore/Framework/test/global_outputmodule_t.cppunit.cc
  FWCore/Framework/test/global_producer_t.cppunit.cc
  FWCore/Framework/test/limited_filter_t.cppunit.cc
  FWCore/Framework/test/limited_outputmodule_t.cppunit.cc
  FWCore/Framework/test/limited_producer_t.cppunit.cc
  FWCore/Framework/test/one_outputmodule_t.cppunit.cc
  FWCore/Framework/test/stream_filter_t.cppunit.cc
  FWCore/Framework/test/stream_producer_t.cppunit.cc
  FWCore/Framework/test/unit_test_outputs/test_deepCall_unscheduled.log
  FWCore/Framework/test/unit_test_outputs/test_onPath_unscheduled.log
  FWCore/Integration/test/unit_test_outputs/testGetBy1.log
  FWCore/Integration/test/unit_test_outputs/testGetBy2.log
  FWCore/Integration/test/unit_test_outputs/testSubProcess.grep2.txt
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#32452 Update to evtgen 2.0
  Configuration/Generator/python/BsToMuMu_forSTEAM_13TeV_cfi.py
  Configuration/Generator/python/BuToKstarJPsiToMuMu_forSTEAM_13TeV_cfi.py
  GeneratorInterface/EvtGenInterface/data/DECAY.DEC
  GeneratorInterface/EvtGenInterface/data/DECAY_2010.DEC
  GeneratorInterface/EvtGenInterface/data/DECAY_NOLONGLIFE.DEC
  GeneratorInterface/EvtGenInterface/data/evt.pdl
  GeneratorInterface/EvtGenInterface/plugins/EvtGen/EvtGenInterface.cc
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtLb2plnuLCSR.cpp
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtLb2plnuLCSR.hh
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtLb2plnuLCSRFF.cpp
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtLb2plnuLCSRFF.hh
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtModelUserReg.cpp
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtSLBaryonAmp.cpp
  GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtSLBaryonAmp.hh
  GeneratorInterface/EvtGenInterface/plugins/test/Py8_lambadb_evtgen1_Lb2plnuLCSR_cfg.py
  GeneratorInterface/EvtGenInterface/test/Py8_bplus_evtgen1_cfg.py
  GeneratorInterface/EvtGenInterface/test/Py8_tt_evtgen1_cfg.py
  SimDataFormats/GeneratorProducts/src/classes_def.xml
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#32603 PPS: fix z sign in diamond geometry
  Geometry/VeryForwardData/data/2021/v1/CTPPS_Timing_Stations_Assembly.xml
  Geometry/VeryForwardGeometryBuilder/interface/DetGeomDesc.h
  Geometry/VeryForwardGeometryBuilder/src/DetGeomDescBuilder.cc
  RecoPPS/ProtonReconstruction/plugins/CTPPSProtonProducer.cc
  Validation/CTPPS/plugins/CTPPSDirectProtonSimulation.cc
Labels: code-checks-approved, dqm-approved, fully-signed, geometry-approved, orp-approved, reconstruction-approved, tests-approved

#32599 Phase2-hgx273 Zeroth Step for going to V15 geometry of HGCal
  Geometry/HGCalCommonData/interface/HGCalParameters.h
  Geometry/HGCalCommonData/interface/HGCalProperty.h
  Geometry/HGCalCommonData/interface/HGCalTileIndex.h
  Geometry/HGCalCommonData/interface/HGCalWaferMask.h
  Geometry/HGCalCommonData/src/HGCalTileIndex.cc
  Geometry/HGCalCommonData/src/HGCalWaferMask.cc
  Geometry/HGCalCommonData/test/HGCalConvert.cpp
  Geometry/HGCalCommonData/test/HGCalParameterTester.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32608 add root histpainter deps to fix UBSAN issue
  CondCore/SiStripPlugins/plugins/BuildFile.xml
Labels: code-checks-approved, db-pending, orp-approved, pending-signatures, tests-approved

#32606 [PPS] Thread-safe ES condition retrieval
  RecoPPS/Local/interface/CTPPSPixelClusterProducer.h
  RecoPPS/Local/interface/CTPPSPixelGainCalibrationDBService.h
  RecoPPS/Local/interface/RPixDetClusterizer.h
  RecoPPS/Local/plugins/CTPPSPixelClusterProducer.cc
  RecoPPS/Local/plugins/TotemRPUVPatternFinder.cc
  RecoPPS/Local/src/CTPPSPixelGainCalibrationDBService.cc
  SimPPS/PPSPixelDigiProducer/interface/RPixDetDigitizer.h
  SimPPS/PPSPixelDigiProducer/interface/RPixDummyROCSimulator.h
  SimPPS/PPSPixelDigiProducer/plugins/PPSPixelDigiProducer.cc
  Validation/CTPPS/plugins/CTPPSHepMCDistributionPlotter.cc
  Validation/CTPPS/plugins/CTPPSLHCInfoPlotter.cc
  Validation/CTPPS/plugins/CTPPSOpticsPlotter.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionEfficiencyEstimatorData.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionEfficiencyEstimatorMC.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionPlotter.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionSimulationValidator.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionValidator.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#32588 Migrate EcalBasicClusterLocalContCorrection to ESTokens
  RecoEcal/EgammaClusterAlgos/interface/EgammaSCEnergyCorrectionAlgo.h
  RecoEcal/EgammaClusterAlgos/src/EgammaSCEnergyCorrectionAlgo.cc
  RecoEcal/EgammaClusterProducers/interface/EcalBasicClusterLocalContCorrection.h
  RecoEcal/EgammaClusterProducers/interface/EgammaSCCorrectionMaker.h
  RecoEcal/EgammaClusterProducers/python/correctedHybridSuperClusters_cfi.py
  RecoEcal/EgammaClusterProducers/python/correctedMulti5x5SuperClustersWithPreshower_cfi.py
  RecoEcal/EgammaClusterProducers/src/EcalBasicClusterLocalContCorrection.cc
  RecoEcal/EgammaClusterProducers/src/EgammaSCCorrectionMaker.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32519 HGCal ID variables
  RecoEgamma/EgammaHLTProducers/plugins/BuildFile.xml
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTHGCalIDVarProducer.cc
  RecoEgamma/EgammaHLTProducers/plugins/HLTHGCalLayerClusterIsolationProducer.cc
  RecoEgamma/EgammaHLTProducers/python/HLTEgPhaseIITestSequence_cff.py
  RecoEgamma/EgammaTools/interface/HGCalClusterTools.h
  RecoEgamma/EgammaTools/interface/HGCalShowerShapeHelper.h
  RecoEgamma/EgammaTools/src/HGCalClusterTools.cc
  RecoEgamma/EgammaTools/src/HGCalShowerShapeHelper.cc
Labels: code-checks-approved, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved, urgent

#32593 Run3-hcx281 Make showerlibrary producer work
  BigProducts/Simulation/BuildFile.xml
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/ShowerLibraryProducer/src/FiberSD.cc
  SimG4CMS/ShowerLibraryProducer/src/HFChamberSD.cc
  SimG4CMS/ShowerLibraryProducer/src/HFWedgeSD.cc
  SimG4CMS/ShowerLibraryProducer/src/HcalForwardAnalysis.cc
  SimG4CMS/ShowerLibraryProducer/test/python/runHFShowerTMP_cfg.py
  SimG4CMS/ShowerLibraryProducer/test/python/runHFShower_cfg.py
Labels: code-checks-approved, core-pending, orp-approved, pending-signatures, simulation-approved, tests-approved

#32612 Fix ProdCuts and Sensitive detectors lists creation in DD4hep workflow
  SimG4Core/Geometry/src/DD4hep_DDG4Builder.cc
  SimG4Core/Geometry/src/DDG4ProductionCuts.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#32623 drop type specifications in RecoLocalMuon
  RecoLocalMuon/DTSegment/python/DTSegment2DProducer_CombPatternReco2D_NoDrift_CosmicData_cfi.py
  RecoLocalMuon/DTSegment/python/DTSegment4DProducer_CombPatternReco4D_NoDrift_CosmicData_cfi.py
  RecoLocalMuon/DTSegment/python/dt4DExtendedSegments_CombPatternReco4D_LinearDriftFromDB_cfi.py
  RecoLocalMuon/DTSegment/python/dt4DExtendedSegments_CombPatternReco4D_LinearDrift_cfi.py
  RecoLocalMuon/DTSegment/python/dt4DExtendedSegments_CombPatternReco4D_ParamDrift_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32624 drop type specifications in RecoLocalCalo
  RecoLocalCalo/CaloTowersCreator/python/calotowerremaker_cfi.py
  RecoLocalCalo/HcalRecAlgos/python/hcalRecAlgoESProd_cfi.py
  RecoLocalCalo/HcalRecProducers/python/HBHEPhase1Reconstructor_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32621 Avoid seg fault in HTXSRivetProducer
  GeneratorInterface/RivetInterface/plugins/HTXSRivetProducer.cc
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#32520 HGCal ID variables
  RecoEgamma/EgammaHLTProducers/plugins/BuildFile.xml
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTHGCalIDVarProducer.cc
  RecoEgamma/EgammaHLTProducers/plugins/HLTHGCalLayerClusterIsolationProducer.cc
  RecoEgamma/EgammaHLTProducers/python/HLTEgPhaseIITestSequence_cff.py
  RecoEgamma/EgammaTools/interface/HGCalClusterTools.h
  RecoEgamma/EgammaTools/interface/HGCalShowerShapeHelper.h
  RecoEgamma/EgammaTools/src/HGCalClusterTools.cc
  RecoEgamma/EgammaTools/src/HGCalShowerShapeHelper.cc
Labels: backport-ok, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#32587 SimCluster-LayerCluster associator implementation
  SimCalorimetry/HGCalAssociatorProducers/plugins/SimClusterAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/SimClusterAssociatorByEnergyScoreImpl.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/SimClusterAssociatorByEnergyScoreProducer.cc
  SimDataFormats/Associations/interface/LayerClusterToSimClusterAssociator.h
  SimDataFormats/Associations/interface/LayerClusterToSimClusterAssociatorBaseImpl.h
  SimDataFormats/Associations/plugins/LCToSCAssociatorEDProducer.cc
  SimDataFormats/Associations/src/LayerClusterToSimClusterAssociator.cc
  SimDataFormats/Associations/src/LayerClusterToSimClusterAssociatorBaseImpl.cc
  SimDataFormats/Associations/src/classes.h
  SimDataFormats/Associations/src/classes_def.xml
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#32494 Better destructor behavior for SiPixelTemplateStore
  CondFormats/SiPixelTransient/interface/SiPixelTemplate.h
  CondFormats/SiPixelTransient/src/SiPixelTemplate.cc
  FastSimulation/TrackingRecHitProducer/plugins/TrackingRecHitProducer.cc
  FastSimulation/TrackingRecHitProducer/src/PixelTemplateSmearerBase.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPETemplateReco.cc
Labels: code-checks-approved, db-approved, fastsim-pending, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#32617 MTD geometry: fix mtd.xml for scenario D49 for DD4hep compatibility
  Geometry/MTDCommonData/data/CrystalBarPhiFlat/v3/mtd.xml
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32575 Bug fix for coral MessageService wrapper
  CondCore/CondDB/interface/ConnectionPool.h
  CondCore/CondDB/interface/Logger.h
  CondCore/CondDB/src/ConnectionPool.cc
  CondCore/CondDB/src/CoralMsgReporter.cc
  CondCore/CondDB/src/CoralMsgReporter.h
  CondCore/CondDB/src/Logger.cc
  CondCore/DBOutputService/src/PoolDBOutputService.cc
Labels: alca-approved, db-approved, fully-signed, orp-approved, tests-approved

#32611 Run4-hgx283 Next step for V15 geometry of HGCal
  Geometry/HGCalCommonData/data/hgcalcell/v15/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalcell/v15/hgcalcell.xml
  Geometry/HGCalCommonData/python/testHGCalCellXML_cfi.py
  Geometry/HGCalSimData/data/hgcProdCuts.xml
  Geometry/HGCalSimData/data/hgcProdCutsv9.xml
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32604 Run3-hcx282 Use ESGetToken in CalibCalorimetry/CastorCalib
  CalibCalorimetry/CastorCalib/interface/CastorLedAnalysis.h
  CalibCalorimetry/CastorCalib/interface/CastorPedestalAnalysis.h
  CalibCalorimetry/CastorCalib/interface/CastorPedestalsAnalysis.h
  CalibCalorimetry/CastorCalib/plugins/CastorPedestalsAnalysis.cc
  CalibCalorimetry/CastorCalib/src/CastorPedestalAnalysis.cc
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-started

#32391 LowPtElectrons: final energy regression and ID
  PhysicsTools/PatAlgos/python/producersLayer1/lowPtElectronProducer_cff.py
  PhysicsTools/PatAlgos/python/selectionLayer1/lowPtElectronSelector_cfi.py
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronFinalizer.cc
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronIDProducer.cc
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSequence_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronsPreRegression_cfi.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectrons_cfi.py
Labels: analysis-pending, code-checks-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#32622 Added include of cassert to Migration.h
  DataFormats/CLHEP/interface/Migration.h
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#32629 Removed unnecessary dependency from RecoParticleFlow/PFProducer
  RecoParticleFlow/PFProducer/plugins/BuildFile.xml
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32610 Also fix SpecPars names in ZDC
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
  Geometry/ForwardSimData/data/zdcProdCuts/2021/v2/zdcProdCuts.xml
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32615 Phase2-hgx283x Correct earlier versions for orientations of the depleted layers
  Geometry/HGCalCommonData/data/hgcalEE/v10/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalEE/v12/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalEE/v14/hgcalEE.xml
  Geometry/HGCalCommonData/plugins/DDHGCalEEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalEEFileAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalHEFileAlgo.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32627 Run4-hgx283x Second step for V15 geometry of HGCal
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalwaferF-algorithm.xml
  Geometry/HGCalCommonData/data/hgcalwafer/v15/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalwafer/v15/hgcalpos.xml
  Geometry/HGCalCommonData/data/hgcalwafer/v15/hgcalwafer.xml
  Geometry/HGCalCommonData/plugins/DDHGCalWaferF.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalWaferF.cc
  Geometry/HGCalCommonData/python/testHGCalWaferFXML_cfi.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWaferFDD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/dumpHGCalWaferFDDD_cfg.py
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32620 Implement support for Event::getByToken for a GenericHandle
  FWCore/Framework/interface/GenericHandle.h
  FWCore/Framework/src/GenericHandle.cc
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#32636 Fix the ExternalGeneratorFilter argument passing to python config
  GeneratorInterface/Core/python/ExternalGeneratorFilter.py
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#32639 [11_2_X] Fix the ExternalGeneratorFilter argument passing to python config
  GeneratorInterface/Core/python/ExternalGeneratorFilter.py
Labels: fully-signed, generators-approved, orp-approved, tests-approved

#32638 [11_1_X] Fix the ExternalGeneratorFilter argument passing to python config
  GeneratorInterface/Core/python/ExternalGeneratorFilter.py
Labels: fully-signed, generators-approved, orp-approved, tests-approved

#32637 [10_6_X] Fix the ExternalGeneratorFilter argument passing to python config
  GeneratorInterface/Core/python/ExternalGeneratorFilter.py
Labels: fully-signed, generators-approved, orp-approved, tests-approved

#32549 Clean-up of L1 Tracker cluster, stub & track truth-reco association code
  DataFormats/L1TrackTrigger/interface/TTTypes.h
  SimDataFormats/TrackingAnalysis/interface/TrackingParticleFwd.h
  SimTracker/TrackTriggerAssociation/interface/TTClusterAssociationMap.h
  SimTracker/TrackTriggerAssociation/interface/TTStubAssociationMap.h
  SimTracker/TrackTriggerAssociation/interface/TTTrackAssociationMap.h
  SimTracker/TrackTriggerAssociation/plugins/TTClusterAssociator.cc
  SimTracker/TrackTriggerAssociation/plugins/TTClusterAssociator.h
  SimTracker/TrackTriggerAssociation/plugins/TTStubAssociator.cc
  SimTracker/TrackTriggerAssociation/plugins/TTStubAssociator.h
  SimTracker/TrackTriggerAssociation/plugins/TTTrackAssociator.cc
  SimTracker/TrackTriggerAssociation/plugins/TTTrackAssociator.h
  SimTracker/TrackTriggerAssociation/src/TTTrackAssociationMap.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#32649 Remove legacy memory barriers
  FWCore/Concurrency/test/limitedtaskqueue_t.cppunit.cpp
  FWCore/Concurrency/test/serialtaskqueue_t.cppunit.cpp
  FWCore/Concurrency/test/waitingtasklist_t.cppunit.cpp
  FWCore/Utilities/src/InputTag.cc
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#32635 Update DeepCore wf from 11634.17 (TTbar) to 11723.17 (QCD_Pt_1800_2400_14)
  Configuration/PyReleaseValidation/python/relval_2017.py
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#32613 Merge .h with .cc files of plugins in EgammaHFProducers
  RecoEgamma/EgammaHFProducers/plugins/HFClusterAlgo.cc
  RecoEgamma/EgammaHFProducers/plugins/HFClusterAlgo.h
  RecoEgamma/EgammaHFProducers/plugins/HFEGammaSLCorrector.cc
  RecoEgamma/EgammaHFProducers/plugins/HFEMClusterProducer.cc
  RecoEgamma/EgammaHFProducers/plugins/HFEMClusterProducer.h
  RecoEgamma/EgammaHFProducers/plugins/HFRecoEcalCandidateProducer.cc
  RecoEgamma/EgammaHFProducers/plugins/HFRecoEcalCandidateProducer.h
  RecoEgamma/EgammaHFProducers/plugins/HFValueStruct.cc
  RecoEgamma/EgammaHFProducers/plugins/HFValueStruct.h
  RecoEgamma/EgammaHFProducers/plugins/HLTHFRecoEcalCandidateProducer.cc
  RecoEgamma/EgammaHFProducers/plugins/HLTHFRecoEcalCandidateProducer.h
  RecoEgamma/EgammaHFProducers/plugins/SealModule.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32517 HGCal ID variables
  RecoEgamma/EgammaHLTProducers/plugins/BuildFile.xml
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTHGCalIDVarProducer.cc
  RecoEgamma/EgammaHLTProducers/plugins/HLTHGCalLayerClusterIsolationProducer.cc
  RecoEgamma/EgammaHLTProducers/python/HLTEgPhaseIITestSequence_cff.py
  RecoEgamma/EgammaTools/interface/HGCalClusterTools.h
  RecoEgamma/EgammaTools/interface/HGCalShowerShapeHelper.h
  RecoEgamma/EgammaTools/src/HGCalClusterTools.cc
  RecoEgamma/EgammaTools/src/HGCalShowerShapeHelper.cc
Labels: backport-ok, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved, urgent

#32645 ETL v5 (D73) units of measurement moved to constant section
  Geometry/MTDCommonData/data/etl/v5/etl.xml
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32648 Update input of nanoULremini wf
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#32650 Remove gpu workflows from runTheMatrix defaults
  Configuration/PyReleaseValidation/python/MatrixReader.py
Labels: code-checks-approved, orp-approved, pdmv-pending, pending-signatures, tests-started, upgrade-pending

#32614 Principal::getProvenance can no longer trigger unscheduled execution
  DQMOffline/L1Trigger/src/L1TTauOffline.cc
  DQMOffline/Trigger/plugins/HLTTauRefProducer.cc
  FWCore/Common/interface/Provenance.h
  FWCore/Common/src/Provenance.cc
  FWCore/Framework/interface/Event.h
  FWCore/Framework/interface/EventPrincipal.h
  FWCore/Framework/interface/LuminosityBlock.h
  FWCore/Framework/interface/Principal.h
  FWCore/Framework/interface/Run.h
  FWCore/Framework/src/Event.cc
  FWCore/Framework/src/EventPrincipal.cc
  FWCore/Framework/src/LuminosityBlock.cc
  FWCore/Framework/src/OccurrenceForOutput.cc
  FWCore/Framework/src/Principal.cc
  FWCore/Framework/src/Run.cc
  FWCore/Framework/test/eventprincipal_t.cppunit.cc
  FWCore/Framework/test/stubs/TestTriggerNames.cc
  FWCore/Modules/src/EventContentAnalyzer.cc
  HLTrigger/HLTcore/plugins/TriggerSummaryProducerAOD.cc
  HLTrigger/HLTfilters/plugins/HLTDoublet.cc
  HLTrigger/HLTfilters/plugins/HLTDoubletDZ.cc
  HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc
  HLTrigger/btau/plugins/HLTJetTag.cc
  HLTrigger/btau/plugins/HLTJetTagWithMatching.cc
  HeavyFlavorAnalysis/Onia2MuMu/src/OniaVtxReProducer.cc
  PhysicsTools/JetMCAlgos/plugins/HadronAndPartonSelector.cc
  PhysicsTools/PatAlgos/plugins/PATTauProducer.cc
  RecoBTag/FeatureTools/plugins/DeepFlavourTagInfoProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/GsfElectronProducer.cc
  RecoMuon/GlobalTrackingTools/plugins/GlobalTrackQualityProducer.cc
  RecoMuon/L3MuonProducer/src/L3TkMuonProducer.cc
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByMVAIsolationRun2.cc
  RecoTauTag/RecoTau/plugins/PFTauSelectorDefinition.h
  RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc
  SimCalorimetry/EcalSelectiveReadoutProducers/src/EcalSelectiveReadoutProducer.cc
  TopQuarkAnalysis/TopEventProducers/src/TopDecaySubset.cc
  Validation/RecoTau/src/TauTagValidation.cc
Labels: analysis-pending, code-checks-approved, core-approved, dqm-approved, hlt-approved, l1-approved, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved

#32618 Nano modifiers in 112X
  Configuration/Eras/python/Modifier_run2_nanoAOD_106Xv2_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/nano_eras_cff.py
  PhysicsTools/NanoAOD/python/nanogen_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
Labels: analysis-pending, backport-ok, operations-approved, orp-approved, pdmv-approved, pending-signatures, tests-approved, upgrade-approved, xpog-approved

#32619 [11_2_X] Correctly add HIPhotonIsolation to pat::photon
  RecoEgamma/EgammaPhotonProducers/interface/ReducedEGProducer.h
  RecoEgamma/EgammaPhotonProducers/python/reducedEgamma_cfi.py
  RecoEgamma/EgammaPhotonProducers/src/ReducedEGProducer.cc
  RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py
Labels: backport-ok, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32644 E/gamma HLT L1 Track Isolation Producer & TTTrack typedef: 11_1_X
  DataFormats/L1TrackTrigger/interface/L1Track.h
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTEleL1TrackIsolProducer.cc
  RecoEgamma/EgammaIsolationAlgos/interface/EgammaL1TkIsolation.h
  RecoEgamma/EgammaIsolationAlgos/src/EgammaL1TkIsolation.cc
Labels: fully-signed, hlt-approved, l1-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#32594 E/gamma HLT L1 Track Isolation Producer & TTTrack typedef: 11_3_X
  DataFormats/L1TrackTrigger/interface/L1Track.h
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTEleL1TrackIsolProducer.cc
  RecoEgamma/EgammaIsolationAlgos/interface/EgammaL1TkIsolation.h
  RecoEgamma/EgammaIsolationAlgos/src/EgammaL1TkIsolation.cc
Labels: allow-Sam-Harper, code-checks-approved, fully-signed, hlt-approved, l1-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#32658 Do not allow unscheduled execution after prefetching
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Framework/src/Worker.h
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#32664 RUn3-gex46 Make printouts more friendly in dumping geometry for firework
  Fireworks/Geometry/plugins/TGeoMgrFromDdd.cc
Labels: code-checks-approved, fully-signed, orp-approved, tests-approved, visualization-approved

#32665 Set TrackMerger::debug_ in the constructor
  RecoTracker/FinalTrackSelectors/plugins/TrackMerger.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32631 Added missing ROOT dependency for test in CondCore/SiStripPlugins
  CondCore/SiStripPlugins/test/BuildFile.xml
Labels: code-checks-approved, db-pending, orp-approved, pending-signatures, tests-approved

#32598 Migrate to esConsumes two Cond* packages
  CondFormats/PCLConfig/plugins/AlignPCLThresholdsReader.cc
  CondTools/SiPhase2Tracker/plugins/DTCCablingMapTestReader.cc
  CondTools/SiPhase2Tracker/plugins/SiPhase2OuterTrackerLorentzAngleWriter.cc
Labels: alca-approved, code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved, upgrade-approved

#32600 Set all member data in SiPixelGenError constructor
  CondFormats/SiPixelTransient/interface/SiPixelGenError.h
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32609 Tracker Alignment Payload Inspector: migration to new class templates
  CondCore/AlignmentPlugins/plugins/TrackerAlignmentErrorExtended_PayloadInspector.cc
  CondCore/AlignmentPlugins/plugins/TrackerAlignment_PayloadInspector.cc
  CondCore/AlignmentPlugins/plugins/TrackerSurfaceDeformations_PayloadInspector.cc
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#32640 PPS: fix/improvement of CompositeESSource
  CalibPPS/ESProducers/plugins/CTPPSCompositeESSource.cc
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#32579 tobTecStepTrackCandidates.onlyPixelHitsForSeedCleaner False
  RecoTracker/IterativeTracking/python/TobTecStep_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32667 [DD4hep] Fix PPS simulation so physical volume names are recognized
  SimG4CMS/PPS/src/PPSDiamondOrganization.cc
  SimG4CMS/PPS/src/PPSPixelOrganization.cc
  SimG4CMS/PPS/src/PPSStripOrganization.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#32591 Rename local variables according to the coding rules
  CondFormats/SiPixelTransient/src/SiPixelUtils.cc
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEGeneric.h
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEGeneric.cc
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32661 PF validation update 11_3_0_pre1
  Validation/RecoParticleFlow/README.md
  Validation/RecoParticleFlow/test/crab/multicrab.py
  Validation/RecoParticleFlow/test/crab/multicrab_phase2.py
  Validation/RecoParticleFlow/test/datasets.py
  Validation/RecoParticleFlow/test/run_relval.sh
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32663 L1 Tk DQM, plot range
  DQM/SiOuterTracker/plugins/OuterTrackerMonitorTTStub.cc
  DQM/SiOuterTracker/python/OuterTrackerMonitorTTStub_cfi.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32625 drop type spec in RecoLocalTracker
  RecoLocalTracker/Phase2TrackerRecHits/python/Phase2StripCPEGeometricESProducer_cfi.py
  RecoLocalTracker/SiStripZeroSuppression/python/SiStripZeroSuppression_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#32605 Run3-hcx283 Use ESGetToken in CalibCalorimetry/HcalPlugins
  CalibCalorimetry/HcalPlugins/src/HBHEDarkeningEP.h
  CalibCalorimetry/HcalPlugins/src/HcalDbProducer.cc
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
  CalibCalorimetry/HcalPlugins/src/HcalTextCalibrations.cc
  CalibCalorimetry/HcalPlugins/src/HcalTimeSlewEP.h
  CalibCalorimetry/HcalPlugins/test/HBHEDarkeningAnalyzer.cc
  CalibCalorimetry/HcalPlugins/test/HcalDbAnalyzer.cc
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#32669 Run4-hgx284x Modify the conversion code to make titles for HGCal
  Geometry/HGCalCommonData/test/HGCalConvert.cpp
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32651 Some modernization of plugins in EgammaIsolationAlgos
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaEcalPFClusterIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaEcalRecHitIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaElectronTkIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaElectronTkNumIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaHcalPFClusterIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaIsoESDetIdCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaIsoHcalDetIdCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EleIsoDetIdCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/GamIsoDetIdCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/ParticleBasedIsoProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/iso_deposit_extractors/EgammaEcalExtractor.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/iso_deposit_extractors/EgammaHcalExtractor.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/iso_deposit_extractors/EgammaRecHitExtractor.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/iso_deposit_extractors/EgammaTowerExtractor.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/iso_deposit_extractors/EgammaTrackExtractor.cc
  RecoEgamma/EgammaIsolationAlgos/python/electronEcalRecHitIsolationLcone_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32616 Pps nano aod backport106 x
  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
  PhysicsTools/NanoAOD/plugins/BuildFile.xml
  PhysicsTools/NanoAOD/plugins/LHCInfoProducer.cc
  PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc
  PhysicsTools/NanoAOD/plugins/ProtonProducer.cc
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/protons_cff.py
  RecoCTPPS/ProtonReconstruction/plugins/PPSFilteredProtonProducer.cc
Labels: backport-ok, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#32662 HBHE: avoid double counting of correlated term
  RecoLocalCalo/HcalRecAlgos/src/MahiFit.cc
Labels: backport-ok, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32671 Revert #25298; memory leak fix for HepPDT::HeavyIonUnknownID
  SimGeneral/HepPDTESSource/BuildFile.xml
  SimGeneral/HepPDTESSource/src/HepPDTESSource.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#32633 Update 2021 relval matrix for IB test
  Configuration/PyReleaseValidation/python/relval_2017.py
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#32675 fix in PixelTrackBuilder and MuonIdProducer to get debug build work for static ana
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.cc
  RecoPixelVertexing/PixelTrackFitting/src/PixelTrackBuilder.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32673 finecalo patches v1 (rebased)
  Configuration/ProcessModifiers/python/fineCalo_cff.py
  SimCalorimetry/EcalElectronicsEmulation/src/EcalSimpleProducer.cc
  SimDataFormats/CaloHit/src/PCaloHit.cc
  SimDataFormats/Track/interface/SimTrack.h
  SimDataFormats/Track/src/SimTrack.cc
  SimDataFormats/Track/src/classes_def.xml
  SimG4CMS/Calo/interface/CaloG4Hit.h
  SimG4CMS/Calo/interface/CaloHitID.h
  SimG4CMS/Calo/interface/CaloSD.h
  SimG4CMS/Calo/interface/CaloTrkProcessing.h
  SimG4CMS/Calo/src/CaloHitID.cc
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Calo/src/CaloTrkProcessing.cc
  SimG4Core/Application/interface/EventAction.h
  SimG4Core/Application/interface/TrackingAction.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/TrackingAction.cc
  SimG4Core/Notification/interface/G4SimTrack.h
  SimG4Core/Notification/interface/SimTrackManager.h
  SimG4Core/Notification/interface/TrackInformation.h
  SimG4Core/Notification/interface/TrackWithHistory.h
  SimG4Core/Notification/src/G4SimEvent.cc
  SimG4Core/Notification/src/NewTrackAction.cc
  SimG4Core/Notification/src/SimTrackManager.cc
  SimG4Core/Notification/src/TrackWithHistory.cc
Labels: code-checks-approved, fully-signed, operations-approved, orp-approved, simulation-approved, tests-approved

#32679 Switching MCSmartSingleParticleFilter to use an input tag (11.1.x)
  GeneratorInterface/GenFilters/plugins/MCSmartSingleParticleFilter.cc
Labels: backport-ok, bug-fix, fully-signed, generators-approved, orp-approved, tests-approved, urgent

#32674 Avoid writing off beginning of arrays in RPCMonitorClient
  DQM/RPCMonitorClient/interface/RPCDCSSummary.h
  DQM/RPCMonitorClient/interface/RPCDaqInfo.h
  DQM/RPCMonitorClient/interface/RPCDataCertification.h
  DQM/RPCMonitorClient/src/RPCDCSSummary.cc
  DQM/RPCMonitorClient/src/RPCDaqInfo.cc
  DQM/RPCMonitorClient/src/RPCDataCertification.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32626 Use EDPutToken in ReducedEGProducer and modernize GEDPhotonCoreProducer
  CommonTools/Egamma/src/ConversionTools.cc
  CommonTools/ParticleFlow/interface/ElectronIDPFCandidateSelectorDefinition.h
  DataFormats/EgammaCandidates/interface/GsfElectron.h
  PhysicsTools/PatAlgos/plugins/PATElectronProducer.cc
  RecoEgamma/EgammaPhotonProducers/src/GEDPhotonCoreProducer.cc
  RecoEgamma/EgammaPhotonProducers/src/ReducedEGProducer.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32682 Fix a couple of sparse issues in reco pointed out by the static analyzer
  RecoLocalCalo/Castor/src/CastorTowerProducer.cc
  RecoMuon/DetLayers/src/MuonGEMDetLayerGeometryBuilder.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32668 Maintain access to genParticles from signal event in packed collection for HI miniAOD
  DataFormats/PatCandidates/src/classes_def_objects.xml
  PhysicsTools/PatAlgos/plugins/PackedGenParticleSignalProducer.cc
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/genParticles_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#32695 Move parameters inside the modifier
  RecoEcal/EgammaClusterProducers/python/particleFlowSuperClusterECAL_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32571 L1 Phase2 for HLT TDR - Multy Primary Vtx, TkMuons Fix for low-pt
  DataFormats/L1TCorrelator/interface/TkMuon.h
  DataFormats/L1TCorrelator/src/TkMuon.cc
  DataFormats/L1TCorrelator/src/classes_def.xml
  L1Trigger/L1TTrackMatch/plugins/L1TkFastVertexProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkMuonProducer.cc
  L1Trigger/L1TTrackMatch/python/L1TkMuonProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/L1TkPrimaryVertexProducer_cfi.py
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved, urgent

#32696 [11_2_X] Maintain access to genParticles from signal event in packed collection for HI miniAOD
  DataFormats/PatCandidates/src/classes_def_objects.xml
  PhysicsTools/PatAlgos/plugins/PackedGenParticleSignalProducer.cc
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/genParticles_cff.py
Labels: backport-ok, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#32647 Deepvertex and DeepJet+DeepVertex combination backport to 10_6_x
  DataFormats/BTauReco/interface/DeepFlavourFeatures.h
  DataFormats/BTauReco/interface/JetFeatures.h
  DataFormats/BTauReco/interface/SeedingTrackFeatures.h
  DataFormats/BTauReco/interface/TrackPairFeatures.h
  DataFormats/BTauReco/src/classes.h
  DataFormats/BTauReco/src/classes_def.xml
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  RecoBTag/FeatureTools/BuildFile.xml
  RecoBTag/FeatureTools/interface/JetConverter.h
  RecoBTag/FeatureTools/interface/SeedingTrackInfoBuilder.h
  RecoBTag/FeatureTools/interface/SeedingTracksConverter.h
  RecoBTag/FeatureTools/interface/TrackPairInfoBuilder.h
  RecoBTag/FeatureTools/plugins/BuildFile.xml
  RecoBTag/FeatureTools/plugins/DeepFlavourTagInfoProducer.cc
  RecoBTag/FeatureTools/src/SeedingTrackInfoBuilder.cc
  RecoBTag/FeatureTools/src/SeedingTracksConverter.cc
  RecoBTag/FeatureTools/src/TrackPairInfoBuilder.cc
  RecoBTag/ONNXRuntime/BuildFile.xml
  RecoBTag/ONNXRuntime/interface/tensor_configs.h
  RecoBTag/ONNXRuntime/interface/tensor_fillers.h
  RecoBTag/ONNXRuntime/plugins/BuildFile.xml
  RecoBTag/ONNXRuntime/plugins/DeepCombinedONNXJetTagsProducer.cc
  RecoBTag/ONNXRuntime/plugins/DeepVertexONNXJetTagsProducer.cc
  RecoBTag/ONNXRuntime/python/pfDeepFlavour_cff.py
  RecoBTag/ONNXRuntime/src/tensor_fillers.cc
  RecoBTag/ONNXRuntime/test/test_deep_vertexcomb_cfg.py
  RecoBTag/TensorFlow/BuildFile.xml
  RecoBTag/TensorFlow/interface/tensor_fillers.h
  RecoBTag/TensorFlow/src/tensor_fillers.cc
Labels: fully-signed, orp-approved, reconstruction-approved, tests-approved

#32681 (11_1_X) L1 Phase2 for HLT TDR - Multy Primary Vtx, TkMuons Fix for low-pt
  DataFormats/L1TCorrelator/interface/TkMuon.h
  DataFormats/L1TCorrelator/src/TkMuon.cc
  DataFormats/L1TCorrelator/src/classes_def.xml
  L1Trigger/L1TTrackMatch/plugins/L1TkFastVertexProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TkMuonProducer.cc
  L1Trigger/L1TTrackMatch/python/L1TkMuonProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/L1TkPrimaryVertexProducer_cfi.py
Labels: l1-approved, orp-approved, pending-signatures, tests-approved, upgrade-pending, urgent

#32699 New producers and filters for the Phase 2 Muon HLT
  HLTrigger/HLTfilters/plugins/BuildFile.xml
  HLTrigger/HLTfilters/plugins/HLT2L1TkMuonL1TkMuonMuRefDR.cc
  HLTrigger/HLTfilters/plugins/HLT2L1TkMuonL1TkMuonMuRefDR.h
  HLTrigger/Muon/plugins/HLTMuonTrkL1TkMuFilter.cc
  HLTrigger/Muon/plugins/HLTMuonTrkL1TkMuFilter.h
  RecoMuon/L2MuonSeedGenerator/BuildFile.xml
  RecoMuon/L2MuonSeedGenerator/src/L2MuonSeedGeneratorFromL1TkMu.cc
  RecoMuon/L2MuonSeedGenerator/src/L2MuonSeedGeneratorFromL1TkMu.h
  RecoMuon/L2MuonSeedGenerator/src/SealModule.cc
Labels: code-checks-approved, hlt-approved, orp-approved, pending-signatures, reconstruction-pending, tests-approved, urgent

#32700 (11.1.X) New producers and filters for the Phase 2 Muon HLT
  HLTrigger/HLTfilters/plugins/BuildFile.xml
  HLTrigger/HLTfilters/plugins/HLT2L1TkMuonL1TkMuonMuRefDR.cc
  HLTrigger/HLTfilters/plugins/HLT2L1TkMuonL1TkMuonMuRefDR.h
  HLTrigger/Muon/plugins/HLTMuonTrkL1TkMuFilter.cc
  HLTrigger/Muon/plugins/HLTMuonTrkL1TkMuFilter.h
  RecoMuon/L2MuonSeedGenerator/BuildFile.xml
  RecoMuon/L2MuonSeedGenerator/src/L2MuonSeedGeneratorFromL1TkMu.cc
  RecoMuon/L2MuonSeedGenerator/src/L2MuonSeedGeneratorFromL1TkMu.h
  RecoMuon/L2MuonSeedGenerator/src/SealModule.cc
Labels: backport, hlt-approved, orp-approved, pending-signatures, reconstruction-pending, tests-approved, urgent

#32693 Minor updates to improve performance of METSignificance::getCovariance
  RecoMET/METAlgorithms/interface/METSignificance.h
  RecoMET/METAlgorithms/src/METSignificance.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32701 Update ECAL spike killer settings for Run 3
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#32702 [DD4hep] Fix switched names of ECal volumes, first step
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalBarrelNewAlgo.cc
Labels: bug-fix, code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, urgent

#32688 Clean BuildFiles in CUDADataFormats and HeterogeneousCore
  CUDADataFormats/CaloCommon/BuildFile.xml
  CUDADataFormats/EcalDigi/BuildFile.xml
  CUDADataFormats/HcalDigi/BuildFile.xml
  HeterogeneousCore/CUDACore/BuildFile.xml
  HeterogeneousCore/CUDACore/test/BuildFile.xml
  HeterogeneousCore/CUDAServices/BuildFile.xml
  HeterogeneousCore/CUDAServices/plugins/BuildFile.xml
  HeterogeneousCore/CUDATest/BuildFile.xml
  HeterogeneousCore/CUDATest/plugins/BuildFile.xml
  HeterogeneousCore/MPIServices/plugins/BuildFile.xml
Labels: code-checks-approved, fully-signed, heterogeneous-approved, orp-approved, reconstruction-approved, tests-approved

#32698 [Phase2 3D Digitizer] Fix several bugs related with charge migration
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#32708 Phase2-gex46 Update the FineCalo path for the Phas2 detectors
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D49.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D50.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D60.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D64.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D65.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D66.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D67.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D68.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D69.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D70.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D71.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D72.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D73.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D74.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D49XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D50XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D60XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D64XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D65XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D66XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D67XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D68XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D69XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D70XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D71XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D72XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D73XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D74XML_cfi.py
  Geometry/HcalSimData/data/CaloUtil/2026/v5/CaloUtil.xml
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32715 Remove a dead assignment in DQMFEDIntegrityClient, and some little additional cleanup
  DQMServices/Components/plugins/DQMFEDIntegrityClient.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32687 Some modernization of EgammaPhotonProducers
  RecoEgamma/EgammaPhotonProducers/src/ConversionProducer.cc
  RecoEgamma/EgammaPhotonProducers/src/ConvertedPhotonProducer.cc
  RecoEgamma/EgammaPhotonProducers/src/GEDPhotonProducer.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32716 Phase2-hgx274 Use constexpr rather than const in Geometry/HGCalCommonData
  Geometry/HGCalCommonData/interface/HGCalGeomTools.h
  Geometry/HGCalCommonData/interface/HGCalParameters.h
  Geometry/HGCalCommonData/interface/HGCalWaferMask.h
  Geometry/HGCalCommonData/plugins/DDHGCalCell.cc
  Geometry/HGCalCommonData/src/FastTimeDDDConstants.cc
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalCommonData/src/HGCalWaferMask.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32705 Phase2-sim81 Give an example with no tracker simulation for HGCal
  Geometry/HGCalCommonData/python/testGeometryV14_cff.py
  Geometry/HGCalCommonData/test/python/runHGCalTestV14_cfg.py
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32721 [DD4hep] Fix DDFilteredView unit test for DD4hep with Geant4 units
  DetectorDescription/DDCMS/test/DDFilteredView.cppunit.cc
Labels: bug-fix, code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#32720 Add setStatOverflows to get the mean value including the overflow
  Validation/RecoParticleFlow/plugins/OffsetAnalyzerDQM.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32711 Run3-sim82 Define fine calorimeters thrugh python
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Calo/src/CaloTrkProcessing.cc
  SimG4CMS/Calo/test/python/runHGC4_cfg.py
  SimG4Core/Application/python/g4SimHits_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#32719 Update ECAL spike killer settings for Run 3, backport of #32701
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, backport-ok, fully-signed, orp-approved, tests-approved

#32694 drop type specifications in RecoTracker
  RecoTracker/Configuration/python/RecoTrackerTopBottom_cff.py
  RecoTracker/ConversionSeedGenerators/python/ConversionStep2_cff.py
  RecoTracker/ConversionSeedGenerators/python/ConversionStep_cff.py
  RecoTracker/DeDx/python/dedxEstimatorsFromRefitter_cff.py
  RecoTracker/FinalTrackSelectors/python/preDuplicateMergingGeneralTracks_cfi.py
  RecoTracker/IterativeTracking/python/InitialStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtForwardTripletStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtQuadStep_cff.py
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoTracker/MeasurementDet/python/MeasurementTrackerEventProducer_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32718 Gem validation update
  Validation/MuonGEMDigis/plugins/GEMCoPadDigiValidation.cc
  Validation/MuonGEMDigis/plugins/GEMCoPadDigiValidation.h
  Validation/MuonGEMDigis/plugins/GEMPadDigiClusterValidation.cc
  Validation/MuonGEMDigis/plugins/GEMPadDigiClusterValidation.h
  Validation/MuonGEMDigis/plugins/GEMPadDigiValidation.cc
  Validation/MuonGEMDigis/plugins/GEMPadDigiValidation.h
  Validation/MuonGEMDigis/plugins/GEMStripDigiValidation.cc
  Validation/MuonGEMDigis/plugins/GEMStripDigiValidation.h
  Validation/MuonGEMDigis/plugins/MuonGEMDigisHarvestor.cc
  Validation/MuonGEMDigis/plugins/MuonGEMDigisHarvestor.h
  Validation/MuonGEMDigis/python/MuonGEMDigis_cff.py
  Validation/MuonGEMDigis/python/PostProcessor_cff.py
  Validation/MuonGEMHits/BuildFile.xml
  Validation/MuonGEMHits/interface/GEMBaseValidation.h
  Validation/MuonGEMHits/plugins/GEMSimHitValidation.cc
  Validation/MuonGEMHits/plugins/GEMSimHitValidation.h
  Validation/MuonGEMHits/python/MuonGEMCommonParameters_cfi.py
  Validation/MuonGEMHits/python/MuonGEMHits_cff.py
  Validation/MuonGEMHits/src/GEMBaseValidation.cc
  Validation/MuonGEMHits/src/GEMValidationUtils.cc
  Validation/MuonGEMHits/src/MuonGEMBaseHarvestor.cc
  Validation/MuonGEMRecHits/plugins/GEMRecHitValidation.cc
  Validation/MuonGEMRecHits/plugins/GEMRecHitValidation.h
  Validation/MuonGEMRecHits/plugins/MuonGEMRecHitsHarvestor.cc
  Validation/MuonGEMRecHits/plugins/MuonGEMRecHitsHarvestor.h
  Validation/MuonGEMRecHits/python/MuonGEMRecHits_cff.py
  Validation/MuonGEMRecHits/python/PostProcessor_cff.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32704 removed circular dependence that blocked Ecal Phase 2 Sim workflow
  SimCalorimetry/EcalSimProducers/plugins/EcalLiteDTUPedestalsESProducer.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#32726 FastTimerService: removed explicit calls to MonitorElement::getTH1
  HLTrigger/Timer/plugins/FastTimerService.cc
Labels: code-checks-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#32725 Run3-gex48 Remove elementary materials from PPS material file
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
  Geometry/VeryForwardData/data/RP_Hybrid/v1/RP_Hybrid.xml
  Geometry/VeryForwardData/data/RP_Materials/v1/RP_Materials.xml
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved, urgent

#32735 fix undefined behavior in fmt_test.cppunit
  FWCore/MessageService/test/fmt_test.cppunit.cpp
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#32736 update of GT with HLT JECs for Phase-2
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, orp-approved, tests-approved

#32737 DQM: setStatOverflows to use bool
  DQMServices/Core/interface/MonitorElement.h
  DQMServices/Core/src/MonitorElement.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32685 Fix memory problems in SiPixelTemplateDBObjectUploader
  CondTools/SiPixel/test/SiPixelTemplateDBObjectUploader.cc
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#32659 Have JetCorrectorParameter::Record::operator< handle more cases
  CondFormats/JetMETObjects/interface/JetCorrectorParameters.h
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#32690 Ecal laser hdf5 support
  CalibCalorimetry/EcalTrivialCondModules/BuildFile.xml
  CalibCalorimetry/EcalTrivialCondModules/interface/EcalLaserCondTools.h
  CalibCalorimetry/EcalTrivialCondModules/python/EcalLaserCondTools_cfi.py
  CalibCalorimetry/EcalTrivialCondModules/src/EcalLaserCondTools.cc
  CalibCalorimetry/EcalTrivialCondModules/test/ecalLaserCondTools_cfg.py
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#32707 TotemDAQMappingESSourceXML Xerces thread safety
  CalibPPS/ESProducers/plugins/TotemDAQMappingESSourceXML.cc
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#32712 Updated phase 2 templates with extended angle space, backport of #32220
  CondFormats/SiPixelTransient/interface/SiPixelTemplateDefs.h
  Configuration/AlCa/python/autoCondPhase2.py
Labels: alca-approved, backport-ok, bug-fix, db-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32748 add missing dependency on FWCore/Concurrency in DataFormats/Provenance
  DataFormats/Provenance/BuildFile.xml
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#32723 Run3-gex47 Help cpmparison of geometries created by DDD/DD4Hep with PrintGeomInfo
  SimG4Core/PrintGeomInfo/interface/PrintGeomInfoAction.h
  SimG4Core/PrintGeomInfo/src/PrintGeomInfoAction.cc
  SimG4Core/PrintGeomInfo/test/BuildFile.xml
  SimG4Core/PrintGeomInfo/test/SimFileCompare.cpp
  SimG4Core/PrintGeomInfo/test/python/runDD4HEP_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runDDD_cfg.py
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#32730 (Backport) Hcal: Fix the TDC Simulation Algorithm
  SimCalorimetry/HcalSimAlgos/src/HcalTDC.cc
Labels: fully-signed, orp-approved, simulation-approved, tests-rejected

#32729 Hcal: Fix the TDC Simulation Algorithm
  SimCalorimetry/HcalSimAlgos/src/HcalTDC.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-rejected

#32713 Follow-up of #32699 (Phase 2 Muon HLT)
  HLTrigger/HLTfilters/plugins/HLT2L1TkMuonL1TkMuonMuRefDR.cc
  HLTrigger/HLTfilters/plugins/HLT2L1TkMuonL1TkMuonMuRefDR.h
  HLTrigger/Muon/plugins/HLTMuonTrkL1TkMuFilter.cc
  RecoMuon/L2MuonSeedGenerator/BuildFile.xml
  RecoMuon/L2MuonSeedGenerator/plugins/BuildFile.xml
  RecoMuon/L2MuonSeedGenerator/plugins/L2MuonSeedGeneratorFromL1TkMu.cc
  RecoMuon/L2MuonSeedGenerator/src/L2MuonSeedGeneratorFromL1TkMu.h
  RecoMuon/L2MuonSeedGenerator/src/SealModule.cc
Labels: code-checks-approved, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-rejected

#32684 New HGCal silicon module rotation class
  Geometry/HGCalCommonData/interface/HGCalGeomRotation.h
  Geometry/HGCalCommonData/src/HGCalGeomRotation.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-rejected, upgrade-approved

#32291 Improving the boundary between PFAlgo and PFTICL (or simPF) for phase2
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoHGCal/TICL/BuildFile.xml
  RecoHGCal/TICL/plugins/PFTICLProducer.cc
  RecoHGCal/TICL/python/iterativeTICL_cff.py
  RecoHI/Configuration/python/Reconstruction_hiPF_cff.py
  RecoParticleFlow/PFProducer/interface/BlockElementImporterBase.h
  RecoParticleFlow/PFProducer/interface/PFAlgo.h
  RecoParticleFlow/PFProducer/interface/PFMuonAlgo.h
  RecoParticleFlow/PFProducer/plugins/PFProducer.cc
  RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporter.cc
  RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporterWithVeto.cc
  RecoParticleFlow/PFProducer/plugins/importers/TrackFromParentImporter.h
  RecoParticleFlow/PFProducer/python/particleFlowBlock_cfi.py
  RecoParticleFlow/PFProducer/src/PFAlgo.cc
  RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc
  RecoParticleFlow/PFTracking/interface/PFTrackAlgoTools.h
Labels: code-checks-approved, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#32749 Phase2-gex49 Update the test scripts to evaluate dd4hep
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/dd4hep_ttbar_2026D49_Step1_cfg.py
  SimG4Core/Configuration/test/dd4hep_ttbar_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step1_cfg.py
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#32752 Add missing FWCore/Utilities dependency to RecoLocalTracker/SiPixelClusterizer plugins and test
  RecoLocalTracker/SiPixelClusterizer/plugins/BuildFile.xml
  RecoLocalTracker/SiPixelClusterizer/test/BuildFile.xml
  RecoLocalTracker/SiPixelClusterizer/test/ReadPixClusters.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32751 (11.1.X) Follow-up of #32700 (Phase 2 Muon HLT)
  HLTrigger/HLTfilters/plugins/HLT2L1TkMuonL1TkMuonMuRefDR.cc
  HLTrigger/HLTfilters/plugins/HLT2L1TkMuonL1TkMuonMuRefDR.h
  HLTrigger/Muon/plugins/HLTMuonTrkL1TkMuFilter.cc
  RecoMuon/L2MuonSeedGenerator/BuildFile.xml
  RecoMuon/L2MuonSeedGenerator/plugins/BuildFile.xml
  RecoMuon/L2MuonSeedGenerator/plugins/L2MuonSeedGeneratorFromL1TkMu.cc
  RecoMuon/L2MuonSeedGenerator/src/L2MuonSeedGeneratorFromL1TkMu.h
  RecoMuon/L2MuonSeedGenerator/src/SealModule.cc
Labels: backport-ok, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#32727 Run3-trk05 Remove unused solids, LV, PV in tob.xml
  Geometry/TrackerCommonData/data/tob/v1/tob.xml
  Geometry/TrackerCommonData/data/tob/v3/tob.xml
  Geometry/TrackerCommonData/python/cmsExtendedGeometry2017XML_cfi.py
  Geometry/TrackerCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/TrackerCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/TrackerCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
  Geometry/TrackerCommonData/test/python/run17.py
  Geometry/TrackerCommonData/test/python/run21.py
  Geometry/TrackerCommonData/test/python/run21Zero.py
  Geometry/TrackerCommonData/test/python/run_cfg.py
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#32750 Run3-gex50 Match the namespace between ddd and dd4hep for ECAL barrel algo
  Geometry/EcalCommonData/plugins/DDEcalBarrelNewAlgo.cc
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalBarrelNewAlgo.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#32732 Added support of Authorization for Tag access
  CondCore/CondDB/interface/Auth.h
  CondCore/CondDB/interface/ConnectionPool.h
  CondCore/CondDB/interface/DecodingKey.h
  CondCore/CondDB/interface/IOVEditor.h
  CondCore/CondDB/plugins/RelationalAuthenticationService.cc
  CondCore/CondDB/plugins/RelationalAuthenticationService.h
  CondCore/CondDB/src/ConnectionPool.cc
  CondCore/CondDB/src/CredentialStore.cc
  CondCore/CondDB/src/DbCore.h
  CondCore/CondDB/src/DecodingKey.cc
  CondCore/CondDB/src/IDbAuthentication.h
  CondCore/CondDB/src/IDbSchema.h
  CondCore/CondDB/src/IOVEditor.cc
  CondCore/CondDB/src/IOVProxy.cc
  CondCore/CondDB/src/IOVSchema.cc
  CondCore/CondDB/src/IOVSchema.h
  CondCore/CondDB/src/SessionImpl.cc
  CondCore/CondDB/src/SessionImpl.h
  CondCore/DBOutputService/interface/PoolDBOutputService.h
  CondCore/DBOutputService/src/PoolDBOutputService.cc
  CondCore/DBOutputService/test/python/testIOVPayloadAnalyzer_cfg.py
  CondCore/DBOutputService/test/python/testLumiBasedUpdateAnalyzer_oracle.cfg.py
  CondCore/DBOutputService/test/stubs/IOVPayloadAnalyzer.cc
  CondCore/DBOutputService/test/stubs/LumiBasedUpdateAnalyzer.cc
  CondCore/DBOutputService/test/stubs/LumiBasedUpdateAnalyzer.h
Labels: alca-approved, code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#32601 Add PixelBaryCentreAnalyzer in Alignment offline validation tool
  Alignment/OfflineValidation/plugins/BuildFile.xml
  Alignment/OfflineValidation/plugins/PixelBaryCentreAnalyzer.cc
  Alignment/OfflineValidation/scripts/PixelBaryCentrePlotConfig.json
  Alignment/OfflineValidation/scripts/plotBaryCentre_VS_BeamSpot.py
  Alignment/OfflineValidation/test/PixelBaryCentreAnalyzer_cfg.py
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#32753 add missing dependencies to DataFormats/DTDigi
  DataFormats/DTDigi/BuildFile.xml
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#32724 Implement fillDescriptions in ConversionTrackCandidateProducer
  RecoEgamma/EgammaElectronProducers/python/uncleanedOnlyElectronSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/conversionTrackCandidates_cff.py
  RecoEgamma/EgammaPhotonProducers/python/conversionTrackCandidates_cfi.py
  RecoEgamma/EgammaPhotonProducers/python/conversionTrackSequenceForReReco_cff.py
  RecoEgamma/EgammaPhotonProducers/python/conversionTrackSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/conversionTracks_cff.py
  RecoEgamma/EgammaPhotonProducers/python/cosmicConversionTrackSequence_cff.py
  RecoEgamma/EgammaPhotonProducers/python/trajectoryBuilderForConversions_cfi.py
  RecoEgamma/EgammaPhotonProducers/src/ConversionTrackCandidateProducer.cc
  RecoEgamma/EgammaPhotonProducers/src/GEDPhotonCoreProducer.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32678 Some cleanup and modernization in EgammaIsolationAlgos plugins
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaEcalPFClusterIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaEcalRecHitIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaElectronTkNumIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaHcalPFClusterIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaIsoDetIdCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaIsoESDetIdCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaPhotonTkIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaPhotonTkNumIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaTowerIsolationProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EleIsoDetIdCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/ParticleBasedIsoProducer.cc
  RecoEgamma/EgammaIsolationAlgos/python/particleBasedIsoProducer_cff.py
  RecoEgamma/EgammaIsolationAlgos/python/particleBasedIsoProducer_cfi.py
  RecoEgamma/EgammaIsolationAlgos/python/pfBlockBasedIsolation_cfi.py
  RecoParticleFlow/PFProducer/python/particleFlowEGamma_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#32761 StatOverflows on PixelPhase1 DQM
  DQM/SiPixelPhase1Common/interface/HistogramManager.h
  DQM/SiPixelPhase1Common/python/HistogramManager_cfi.py
  DQM/SiPixelPhase1Common/src/HistogramManager.cc
  DQMServices/Core/interface/MonitorElement.h
  DQMServices/Core/src/MonitorElement.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32722 [JME NanoAOD] Changes for event size reduction
  PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/PatAlgos/python/tools/jetCollectionTools.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#32758 Add L1T fractional prescale record
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#32738 Phase2-gex48 Add 2 new scenarios D75 and D76 using I13 for D71 and D74. Also remove some overlaps
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2026D75Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D75_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D76Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D76_cff.py
  Configuration/Geometry/python/GeometryExtended2026D75Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D75_cff.py
  Configuration/Geometry/python/GeometryExtended2026D76Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D76_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D75.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D76.xml
  Geometry/CMSCommonData/data/muonBase/2026/v3/muonBase.xml
  Geometry/CMSCommonData/data/muonBase/2026/v4/muonBase.xml
  Geometry/CMSCommonData/data/muonBase/2026/v5/muonBase.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D75XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D76XML_cfi.py
  Geometry/MTDCommonData/data/etl/v4/etl.xml
  Geometry/MTDCommonData/data/etl/v5/etl.xml
Labels: code-checks-approved, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#32739 include missing dependencies
  DataFormats/HLTReco/BuildFile.xml
  DataFormats/L1TParticleFlow/BuildFile.xml
Labels: code-checks-approved, hlt-approved, l1-pending, orp-approved, pending-signatures, tests-approved, upgrade-approved

#32036 DisplacedGeneralStep in tracking
  Configuration/ProcessModifiers/python/displacedTracking_cff.py
  DQM/TrackingMonitorSource/python/EDModules2monitor_cfi.py
  DQM/TrackingMonitorSource/python/IterTrackingModules4seedMonitoring_cfi.py
  DataFormats/TrackReco/interface/TrackBase.h
  DataFormats/TrackReco/src/TrackBase.cc
  RecoTracker/FinalTrackSelectors/python/earlyGeneralTracks_cfi.py
  RecoTracker/FinalTrackSelectors/src/trackAlgoPriorityOrder.h
  RecoTracker/IterativeTracking/python/DisplacedGeneralStep_cff.py
  RecoTracker/IterativeTracking/python/iterativeTkConfig.py
  RecoTracker/IterativeTracking/python/iterativeTk_cff.py
  RecoTracker/TkSeedingLayers/python/DisplacedGeneralLayerTriplet_cfi.py
  Validation/RecoTrack/python/plotting/html.py
  Validation/RecoTrack/python/plotting/ntupleEnum.py
  Validation/RecoTrack/python/plotting/trackingPlots.py
  Validation/RecoTrack/test/trackingPerformanceValidation.py
Labels: code-checks-approved, dqm-approved, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved

#32157 Displaced tracking validation for Run 3 and Phase 2
  Configuration/ProcessModifiers/python/displacedTrackValidation_cff.py
  Validation/RecoTrack/python/PostProcessorTracker_cfi.py
  Validation/RecoTrack/python/TrackValidation_cff.py
  Validation/RecoTrack/python/plotting/html.py
  Validation/RecoTrack/python/plotting/trackingPlots.py
  Validation/RecoTrack/scripts/makeTrackValidationPlots.py
  Validation/RecoTrack/test/trackingCompare.py
  Validation/RecoTrack/test/trackingPerformanceValidation.py
Labels: code-checks-approved, dqm-approved, fully-signed, operations-approved, orp-approved, tests-approved

#32652 HGCAL validation at SimCluster level
  SimCalorimetry/HGCalSimProducers/python/hgcHitAssociation_cfi.py
  SimDataFormats/Associations/python/LCToCPAssociation_cfi.py
  SimDataFormats/Associations/python/LCToSCAssociation_cfi.py
  Validation/Configuration/python/hgcalSimValid_cff.py
  Validation/HGCalValidation/interface/HGCalValidator.h
  Validation/HGCalValidation/interface/HGVHistoProducerAlgo.h
  Validation/HGCalValidation/plugins/HGCalValidator.cc
  Validation/HGCalValidation/python/HGCalPostProcessor_cff.py
  Validation/HGCalValidation/python/HGCalValidator_cfi.py
  Validation/HGCalValidation/python/HGVHistoProducerAlgoBlock_cfi.py
  Validation/HGCalValidation/python/PostProcessorHGCAL_cfi.py
  Validation/HGCalValidation/python/hgcalPlots.py
  Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py
  Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#32771 fix wrong es consumes transitions in SiStripAnalyser
  DQM/SiStripMonitorClient/plugins/SiStripAnalyser.cc
  DQM/SiStripMonitorClient/plugins/SiStripAnalyser.h
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#32767 Run3-gex50X Match name/namespace and the geometry parameters in DDD/DD4Hep for EE
  Geometry/EcalCommonData/plugins/DDEcalEndcapAlgo.cc
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalEndcapAlgo.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#32774 Use correct fractional prescale tag in data global tags
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#32775 add missing dependency on DataFormats/Common to CUDADataFormats/CaloCommon
  CUDADataFormats/CaloCommon/BuildFile.xml
Labels: code-checks-approved, fully-signed, heterogeneous-approved, orp-approved, reconstruction-approved, tests-approved

#32769 update MultiUserHook.h to include P8.240 in 7_1_X
  GeneratorInterface/Pythia8Interface/interface/MultiUserHook.h
Labels: generators-pending, pending-signatures, tests-rejected
