Repository cms-sw/cmssw, pull requests merged in 2021-05, with the labels that each got.

#33559 Provide access to HLTPathStatus in TriggerResultsFilter
  HLTrigger/Configuration/python/customizeHLTforNewDatasetDefinition.py
  HLTrigger/HLTcore/interface/TriggerExpressionData.h
  HLTrigger/HLTcore/src/TriggerExpressionData.cc
  HLTrigger/HLTcore/src/TriggerExpressionPathReader.cc
  HLTrigger/HLTfilters/plugins/TriggerResultsFilter.cc
Labels: code-checks-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#33499 Displaced muon with new parameters for the Phase2 L1 tracker studies
  Configuration/Generator/python/DoubleElectronFlatPt1p5To8_cfi.py
  Configuration/Generator/python/DoubleMuFlatPt1p5To8Dxy100GunProducer_cfi.py
  Configuration/Generator/python/DoubleMuFlatPt1p5To8_cfi.py
  Configuration/Generator/python/DoubleMuFlatPt2To100Dxy100GunProducer_cfi.py
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33579 Update for cmsswSequenceInfo without extra sequences
  DQMOffline/Configuration/scripts/cmsswSequenceInfo.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33593 fix handling of air/iron in DD4hep MF construction
  MagneticField/GeomBuilder/src/DD4hep_volumeHandle.cc
Labels: bug-fix, code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33586 Use genTauJet modules coherently across different nanoAOD cffs
  PhysicsTools/NanoAOD/python/nanogen_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
Labels: bug-fix, code-checks-approved, fully-signed, orp-approved, tests-approved, xpog-approved

#33590 Use genTauJet modules coherently across different nanoAOD cffs (106X)
  PhysicsTools/NanoAOD/python/nanogen_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
Labels: bug-fix, fully-signed, orp-approved, tests-approved, xpog-approved

#33594 fix handling of air/iron in DD4hep MF construction
  MagneticField/GeomBuilder/src/DD4hep_volumeHandle.cc
Labels: backport-ok, bug-fix, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33580 All daughter decay filter
  GeneratorInterface/GenFilters/plugins/PythiaAllDauVFilter.cc
Labels: fully-signed, generators-approved, orp-approved, tests-approved

#33376 EGamma: add scale & systematics variables to electron and photon table backport
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/nano_eras_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, orp-approved, tests-approved, xpog-approved

#33527 Fixes of anti-mu cff for tauReco at miniAOD
  RecoTauTag/RecoTau/python/hpsPFTauDiscriminationByMuonRejectionSimple_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33537 Phase2-hgx282X Change the use of ESHandle to ESGetToken
  Validation/HGCalValidation/plugins/HGCGeometryValidation.cc
  Validation/HGCalValidation/plugins/HGCalBHValidation.cc
  Validation/HGCalValidation/plugins/HGCalDigiClient.cc
  Validation/HGCalValidation/plugins/HGCalDigiValidation.cc
  Validation/HGCalValidation/plugins/HGCalSimHitStudy.cc
  Validation/HGCalValidation/plugins/HGCalSimHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalSimHitsClient.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33534 Remove confusing use of None from _TypedParameterizable constructor
  FWCore/ParameterSet/python/Mixins.py
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#33526 Pixel local reco: reduce code duplication between SiPixelDigiErrorsFromSoA and SiPixelRawToDigi
  EventFilter/SiPixelRawToDigi/interface/PixelDataFormatter.h
  EventFilter/SiPixelRawToDigi/plugins/SiPixelDigiErrorsFromSoA.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.h
  EventFilter/SiPixelRawToDigi/python/SiPixelDigiToRaw_cfi.py
  EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc
  EventFilter/SiPixelRawToDigi/test/runHotPixels_cfg.py
  EventFilter/SiPixelRawToDigi/test/runRawDumper_cfg.py
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
Labels: allow-czangela, code-checks-approved, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#33611 Phase2-hgx285 Get rid of HCAL option from most of the code in Validation/HGCalValidation/plugins
  Validation/HGCalValidation/plugins/HGCalDigiClient.cc
  Validation/HGCalValidation/plugins/HGCalDigiValidation.cc
  Validation/HGCalValidation/plugins/HGCalRecHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalRecHitsClient.cc
  Validation/HGCalValidation/plugins/HGCalSimHitStudy.cc
  Validation/HGCalValidation/plugins/HGCalSimHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalSimHitsClient.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33566 FWCore/Framework: Add cmsRunGP which links against Google perftools profiler library.
  FWCore/Framework/bin/BuildFile.xml
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#33569 EMTF and uGMT shower triggers (HadronicShowerTrigger-5)
  DataFormats/CSCDigi/interface/CSCConstants.h
  L1Trigger/Configuration/python/L1Trigger_EventContent_cff.py
  L1Trigger/L1TMuon/plugins/L1TMuonShowerProducer.cc
  L1Trigger/L1TMuon/python/simDigis_cff.py
  L1Trigger/L1TMuon/python/simGmtStage2Digis_cfi.py
  L1Trigger/L1TMuonEndCap/interface/SectorProcessorShower.h
  L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapShowerProducer.cc
  L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapShowerProducer.h
  L1Trigger/L1TMuonEndCap/python/simEmtfShowers_cfi.py
  L1Trigger/L1TMuonEndCap/src/SectorProcessorShower.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved

#33407 add WToLNu and WprimeToLNu genFragments at 14 TeV
  Configuration/Generator/python/WToLNu_14TeV_TuneCP5_pythia8_cfi.py
  Configuration/Generator/python/WToMuNu_14TeV_TuneCP5_pythia8_cfi.py
  Configuration/Generator/python/WprimeToLNu_M2000_14TeV_TuneCP5_pythia8_cfi.py
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, pdmv-approved, tests-approved

#33596 add WToLNu and WprimeToLNu genFragments at 14 TeV [backport #33407]
  Configuration/Generator/python/WToLNu_14TeV_TuneCP5_pythia8_cfi.py
  Configuration/Generator/python/WToMuNu_14TeV_TuneCP5_pythia8_cfi.py
  Configuration/Generator/python/WprimeToLNu_M2000_14TeV_TuneCP5_pythia8_cfi.py
Labels: fully-signed, generators-approved, orp-approved, pdmv-approved, tests-approved

#33461 Add new workflows to upgradeWorkflowComponents.py for HLT
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33601 Phase2-hgx282Z Remove the HCAL option in the validation codes in HGCalValidation/test
  Validation/HGCalValidation/test/HGCGeometryCheck.cc
  Validation/HGCalValidation/test/HGCHitValidation.cc
  Validation/HGCalValidation/test/HGCalDigiStudy.cc
  Validation/HGCalValidation/test/HGCalRecHitStudy.cc
  Validation/HGCalValidation/test/HGCalWaferStudy.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33597 Validation/Geometry apply futurize stage1; use six.iteritems; use python3 for matplotlib
  Validation/Geometry/test/MaterialBudget.py
  Validation/Geometry/test/MaterialBudgetHGCal.py
  Validation/Geometry/test/genHGCalPlots.sh
  Validation/Geometry/test/runMaterialMapForReco_fromReco.py
  Validation/Geometry/test/runP_FromVertexUpToInFrontOfMuonStations_cfg.py
  Validation/Geometry/test/runP_HGCal_cfg.py
Labels: code-checks-approved, dqm-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#33614 Run4-hgx285 Update some of the remaining validation classes in Validation/HGCalValidation
  Validation/Configuration/python/hgcalSimValid_cff.py
  Validation/HGCalValidation/plugins/HGCalBHValidation.cc
  Validation/HGCalValidation/plugins/HGCalHitValidation.cc
  Validation/HGCalValidation/python/hgcalHitValidation_cff.py
  Validation/HGCalValidation/python/hgcalHitValidation_cfi.py
  Validation/HGCalValidation/test/python/protoHGCalSimWatcher_cfg.py
  Validation/HGCalValidation/test/python/protoSimValid_cfg.py
  Validation/HGCalValidation/test/python/protoValid_cfg.py
  Validation/HGCalValidation/test/python/standalone_fromRECO.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33523 Merge ShallowGainCalibration logic in SiStripGainsPCLWorker and a minor bugfix
  CalibTracker/SiStripChannelGain/interface/SiStripGainsPCLWorker.h
  CalibTracker/SiStripChannelGain/python/SiStripGainsPCLWorker_cfi.py
  CalibTracker/SiStripChannelGain/src/SiStripGainsPCLWorker.cc
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiStripGainsAAG_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiStripGains_cff.py
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#33595 Run4-hgx282Z Remove overlaps in the V15 geometry of HGCal
  Geometry/HGCalCommonData/plugins/DDHGCalWaferP.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalWaferP.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#33474 Changes required to compile with TBB 2021.2
  CondCore/Utilities/bin/conddb_test_gt_perf.cpp
  DetectorDescription/Core/interface/DDName.h
  DetectorDescription/Core/interface/DDValue.h
  DetectorDescription/Core/src/StoresInstantiation.cc
  FWCore/Framework/test/dependentrecord_t.cppunit.cc
  FWCore/PluginManager/interface/PluginFactoryBase.h
  FWCore/Services/plugins/InitRootHandlers.cc
  FWCore/Services/plugins/StallMonitor.cc
  FWCore/Utilities/interface/StdPairHasher.h
  FWCore/Utilities/interface/hash_combine.h
  FWCore/Utilities/interface/zero_allocator.h
  HLTrigger/Timer/plugins/FastTimerService.cc
  PhysicsTools/TensorFlow/interface/TBBThreadPool.h
Labels: code-checks-approved, core-approved, db-approved, fully-signed, geometry-approved, hlt-approved, orp-approved, reconstruction-approved, requires-external, tests-approved

#33618 Fix typo in the fillDescriptions method of RecoParticleFlow/PFClusterProducer/interface/HGCRecHitNavigator.h
  RecoParticleFlow/PFClusterProducer/interface/HGCRecHitNavigator.h
Labels: bug-fix, code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33625 fix missing leftover Timing parameter in fed_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/fed_dqm_sourceclient-live_cfg.py
Labels: bug-fix, code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved, urgent

#33517 Adding HtoZZ UL ID configs
  RecoEgamma/ElectronIdentification/python/ElectronMVAValueMapProducer_cfi.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Summer16UL_ID_ISO_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Summer17UL_ID_ISO_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Summer18UL_ID_ISO_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#33628 Set generateConcurrently to False to fix Herwig workflow issue
  Configuration/Generator/python/TT_13TeV_Pow_Herwig7_cff.py
Labels: bug-fix, code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33488 [HGCAL] Deprecate MultiCluster
  RecoHGCal/Configuration/python/RecoHGCal_EventContent_cff.py
  RecoHGCal/TICL/python/EMStep_cff.py
  RecoHGCal/TICL/python/HADStep_cff.py
  RecoHGCal/TICL/python/MIPStep_cff.py
  RecoHGCal/TICL/python/SimTracksters_cff.py
  RecoHGCal/TICL/python/TrkEMStep_cff.py
  RecoHGCal/TICL/python/TrkStep_cff.py
  RecoHGCal/TICL/python/iterativeTICL_cff.py
  RecoHGCal/TICL/python/ticl_iterations.py
  RecoParticleFlow/PFClusterProducer/plugins/PFClusterFromHGCalTrackster.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFClusterFromHGCalTrackster.h
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHGC_cfi.py
  Validation/HGCalValidation/interface/HGCalValidator.h
  Validation/HGCalValidation/interface/HGVHistoProducerAlgo.h
  Validation/HGCalValidation/plugins/HGCalValidator.cc
  Validation/HGCalValidation/python/HGCalPostProcessor_cff.py
  Validation/HGCalValidation/python/HGCalValidator_cfi.py
  Validation/HGCalValidation/python/HGVHistoProducerAlgoBlock_cfi.py
  Validation/HGCalValidation/python/PostProcessorHGCAL_cfi.py
  Validation/HGCalValidation/python/hgcalPlots.py
  Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py
  Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc
Labels: code-checks-approved, dqm-approved, fully-signed, hgcal-dpg-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#33627 Phase2-hgx285X Clean up a few classes for the use of ESGetToken and add a script for plots
  Validation/HGCalValidation/interface/HGCalValidator.h
  Validation/HGCalValidation/plugins/HGCalShowerSeparation.cc
  Validation/HGCalValidation/plugins/HeterogeneousHGCalRecHitsValidator.cc
  Validation/HGCalValidation/plugins/HeterogeneousHGCalRecHitsValidator.h
  Validation/HGCalValidation/test/MakePlots.C
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33573 EcalCondObject container iteration fix
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.h
  CondFormats/EcalObjects/interface/EcalCondObjectContainer.h
  CondFormats/EcalObjects/src/EcalIntercalibConstantsGPU.cc
  CondFormats/EcalObjects/src/EcalLaserAPDPNRatiosRefGPU.cc
  CondFormats/EcalObjects/src/EcalLaserAlphasGPU.cc
  RecoLocalCalo/EcalRecProducers/test/sourceFromRawCmggpu_cff.py
  RecoLocalCalo/EcalRecProducers/test/testEcalRechitProducer_cfg.py
Labels: alca-approved, code-checks-approved, db-approved, fully-signed, l1-approved, orp-approved, reconstruction-approved, tests-approved

#33582 Cleanup of data/simulation analyzer modules in CSCTriggerPrimitives
  L1Trigger/CSCTriggerPrimitives/test/BuildFile.xml
  L1Trigger/CSCTriggerPrimitives/test/CSCTriggerPrimitivesAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/test/L1CSCTPEmulatorConfigAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/test/README.md
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCAnodeLCTAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCAnodeLCTAnalyzer.h
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCCathodeLCTAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCCathodeLCTAnalyzer.h
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCTriggerPrimitivesReader.cc
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCTriggerPrimitivesReader.h
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCTriggerPrimitivesReader_cfi.py
  L1Trigger/CSCTriggerPrimitives/test/macros/README.md
  L1Trigger/CSCTriggerPrimitives/test/runCSCL1TDQM_cfg.py
  L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveAnalyzer_cfg.py
  L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveProducer_cfg.py
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33631 Initialize id variable to silence warning
  EventFilter/Utilities/src/FedRawDataInputSource.cc
Labels: code-checks-approved, daq-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33624 Allow to suppress ExternalLHEProducer exception if not all events were processed
  GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33634 avoiding trailing whitespaces in config dump
  FWCore/ParameterSet/python/Mixins.py
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#33640 Fix unit test in PhysicsTools/UtilAlgos (11_2_X)
  PhysicsTools/UtilAlgos/test/fwliteWithPythonConfig_cfg.py
Labels: analysis-pending, orp-approved, pending-signatures, tests-approved

#33574 EcalCondObject container iteration fix
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.h
  CondFormats/EcalObjects/interface/EcalCondObjectContainer.h
  CondFormats/EcalObjects/src/EcalIntercalibConstantsGPU.cc
  CondFormats/EcalObjects/src/EcalLaserAPDPNRatiosRefGPU.cc
  CondFormats/EcalObjects/src/EcalLaserAlphasGPU.cc
  RecoLocalCalo/EcalRecProducers/test/sourceFromRawCmggpu_cff.py
  RecoLocalCalo/EcalRecProducers/test/testEcalRechitProducer_cfg.py
Labels: alca-approved, backport-ok, db-approved, fully-signed, l1-approved, orp-approved, reconstruction-approved, tests-approved

#33528 Add boosted taus to NanoAOD
  PhysicsTools/NanoAOD/python/boostedTaus_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, tests-approved, xpog-approved

#33513 Clean up tau related nanoAOD content
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, tests-approved, xpog-approved

#33603 Bug fix for tag lock clean up at session closing time
  CondCore/CondDB/src/IOVEditor.cc
  CondCore/CondDB/src/SessionImpl.cc
  CondCore/DBOutputService/test/stubs/LumiBasedUpdateAnalyzer.cc
  CondCore/DBOutputService/test/stubs/LumiBasedUpdateAnalyzer.h
Labels: alca-approved, code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#33649 MTD validation: update standalone test configuration to scenario D76, use up-to-date fragments
  Validation/MtdValidation/test/mtdValidation_cfg.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33647 Mtd parameters update for D49 and D60 geometries (Bug fix)
  Geometry/MTDCommonData/data/CrystalBarPhiFlat/mtdParameters.xml
  Geometry/MTDCommonData/data/mtdParameters/v1/mtdParameters.xml
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#33483 Add ParticleNet mass regression
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
  RecoBTag/ONNXRuntime/python/pfParticleNet_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved, xpog-approved

#33617 More prep work for the Run-3 GEM-CSC integrated local trigger
  L1Trigger/CSCTriggerPrimitives/interface/CSCBaseboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMotherboardME11.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCMotherboardME11.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCUpgradeMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCUpgradeMotherboardLUT.h
  L1Trigger/CSCTriggerPrimitives/interface/GEMCoPadProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/GEMInternalCluster.h
  L1Trigger/CSCTriggerPrimitives/interface/LCTQualityAssignment.h
  L1Trigger/CSCTriggerPrimitives/python/params/tmbParams.py
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboardLUT.cc
  L1Trigger/CSCTriggerPrimitives/src/GEMCoPadProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/GEMInternalCluster.cc
  L1Trigger/CSCTriggerPrimitives/src/LCTQualityAssignment.cc
  L1Trigger/CSCTriggerPrimitives/test/GEMCSCLUTAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/test/runGEMCSCLUTAnalyzer_cfg.py
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, requires-external, tests-approved

#33599 Renaming cfgs and cffs
  Configuration/Generator/python/DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7_cff.py
  Configuration/Generator/python/DYToLL012Jets_5FS_TuneCH3_13TeV_amcatnloFxFx_herwig7_cff.py
  GeneratorInterface/Herwig7Interface/python/DYToLL_TuneCH3_13TeV_herwig7_cff.py
  GeneratorInterface/Herwig7Interface/python/PPToEE_LO_TuneCH3_13TeV_herwig7_matchbox_cff.py
  GeneratorInterface/Herwig7Interface/test/DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7_cfg.py
  GeneratorInterface/Herwig7Interface/test/DYToLL012Jets_5FS_TuneCH3_13TeV_amcatnloFxFx_herwig7_cfg.py
  GeneratorInterface/Herwig7Interface/test/DYToLL_TuneCH3_13TeV_herwig7_cfg.py
  GeneratorInterface/Herwig7Interface/test/PPToEE_LO_TuneCH3_13TeV_herwig7_matchbox_cfg.py
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33635 Addition to PixelDQM of Template correction to cluster charge
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_cff.py
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1TrackClusters.cc
  DQM/SiPixelPhase1Track/python/SiPixelPhase1TrackClusters_cfi.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_TrackCluster_cff.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33633 Updated physics configurations for Geant4
  SimG4Core/Application/src/StackingAction.cc
  SimG4Core/Application/src/SteppingAction.cc
  SimG4Core/PhysicsLists/interface/CMSHadronPhysicsFTFP_BERT.h
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EML.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMM_TRK.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMN.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMY.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMZ.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
  SimG4Core/PhysicsLists/src/CMSHadronPhysicsFTFP_BERT.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33669 Pixel DQM: post PR #33635 merge fixes
  DQM/SiPixelPhase1Track/plugins/BuildFile.xml
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1TrackClusters.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33638 [HGCAL] SimTracksters from Caloparticles
  DataFormats/HGCalReco/interface/Trackster.h
  DataFormats/HGCalReco/src/classes_def.xml
  RecoHGCal/TICL/plugins/TrackstersFromSimClustersProducer.cc
  RecoHGCal/TICL/python/SimTracksters_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#33662 MTD validation: optional histograms of BTL and ETL uncalibrated RecHits
  Validation/MtdValidation/macros/makeTimeResPlots.C
  Validation/MtdValidation/plugins/BtlLocalRecoValidation.cc
  Validation/MtdValidation/plugins/EtlLocalRecoValidation.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33551 Remove hard-coded dphi value
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromCondDB.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#33646 move another set of python tool unit tests to python3
  PhysicsTools/MXNet/test/test_mxnet.py
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/testNumExpr.py
  PhysicsTools/PythonAnalysis/test/testTheano.sh
  PhysicsTools/PythonAnalysis/test/testhep_ml.py
Labels: analysis-pending, code-checks-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#33679 Turn-off GEM-CSC integrated local trigger in valCscStage2Digis [11_3_X]
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
Labels: dqm-approved, fully-signed, orp-approved, tests-approved, urgent

#33678 Turn-off GEM-CSC integrated local trigger in valCscStage2Digis [12_0_X]
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved, urgent

#33674 Use std::getenv in ExternalLHEProducer
  GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33632 esConsumes migration for SiStripFedZeroSuppression, SiStripHitEffFromCalibTree, and SiStripClusterToDigiProducer
  CalibTracker/SiStripHitEfficiency/plugins/SiStripHitEffFromCalibTree.cc
  RecoLocalTracker/SiStripClusterizer/plugins/SiStripClusterToDigiProducer.cc
  RecoLocalTracker/SiStripZeroSuppression/interface/SiStripFedZeroSuppression.h
  RecoLocalTracker/SiStripZeroSuppression/interface/SiStripRawProcessingFactory.h
  RecoLocalTracker/SiStripZeroSuppression/src/SiStripFedZeroSuppression.cc
  RecoLocalTracker/SiStripZeroSuppression/src/SiStripRawProcessingFactory.cc
  SimTracker/SiStripDigitizer/plugins/DigiSimLinkAlgorithm.cc
  SimTracker/SiStripDigitizer/plugins/PreMixingSiStripWorker.cc
  SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc
Labels: alca-pending, code-checks-approved, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved

#33621 [HGCAL trigger] Fixing phi smoothing in cluster seeding
  L1Trigger/L1THGCal/interface/backend/HGCalHistoSeedingImpl.h
  L1Trigger/L1THGCal/python/hgcalBackEndLayer2Producer_cfi.py
  L1Trigger/L1THGCal/src/backend/HGCalHistoSeedingImpl.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#33500 MTV fast cleaning
  Validation/RecoTrack/interface/MTVHistoProducerAlgoForTracker.h
  Validation/RecoTrack/python/MTVHistoProducerAlgoForTrackerBlock_cfi.py
  Validation/RecoTrack/src/MTVHistoProducerAlgoForTracker.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33563 Migrate module config in RecoMuon to use automatically generated cfipython default
  RecoMuon/L2MuonIsolationProducer/python/hltL2MuonIsolationsCR_cfi.py
  RecoMuon/L2MuonProducer/python/L2Muons_cfi.py
  RecoMuon/L3MuonProducer/python/L3Muons_cfi.py
  RecoMuon/L3MuonProducer/src/L3MuonProducer.cc
  RecoMuon/L3MuonProducer/test/newL3.py
  RecoMuon/MuonIsolation/python/muonIsolationPUPPI_cff.py
  RecoMuon/MuonSeedGenerator/plugins/MuonSeedGenerator.cc
  RecoMuon/MuonSeedGenerator/python/ancientMuonSeed_cfi.py
Labels: code-checks-approved, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved

#33697 Work around an inaccurate error message in TTreeCache::FillBuffer()
  FWCore/Services/plugins/InitRootHandlers.cc
Labels: core-approved, fully-signed, orp-approved, tests-approved, urgent

#33696 PrimaryVertexMonitoring: don't use HP flag for Alignment plots at HLT
  DQMOffline/RecoB/plugins/PrimaryVertexMonitor.cc
  DQMOffline/RecoB/plugins/PrimaryVertexMonitor.h
  DQMOffline/RecoB/python/PrimaryVertexMonitor_cff.py
  DQMOffline/Trigger/python/PrimaryVertexMonitoring_cff.py
Labels: bug-fix, code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33587 Add boosted taus to nanoAOD (backport of #33528)
  PhysicsTools/NanoAOD/python/boostedTaus_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
Labels: fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#33620 Backport of #33517: Adding HtoZZ UL ID configs
  RecoEgamma/ElectronIdentification/python/ElectronMVAValueMapProducer_cfi.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Summer16UL_ID_ISO_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Summer17UL_ID_ISO_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Summer18UL_ID_ISO_cff.py
Labels: fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved

#33693 2D Maps of Impact Parameters for TkDQM
  DQMOffline/RecoB/plugins/PrimaryVertexMonitor.cc
  DQMOffline/RecoB/plugins/PrimaryVertexMonitor.h
  DQMOffline/RecoB/python/PrimaryVertexMonitor_cff.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, requires-external, tests-approved

#33688 Mass precision in NanoGen + NanoAod, fix customization functions (10_6_X)
  PhysicsTools/NanoAOD/python/genparticles_cff.py
  PhysicsTools/NanoAOD/python/nanogen_cff.py
Labels: fully-signed, orp-approved, tests-approved, xpog-approved

#33651 L1T Phase-2: add various L1 Tk objects
  L1Trigger/L1TTrackMatch/BuildFile.xml
  L1Trigger/L1TTrackMatch/interface/L1TrackJetProducer.h
  L1Trigger/L1TTrackMatch/plugins/L1TkHTMissProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackFastJetProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackJetProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackObjectNtupleMaker.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackerEtMissProducer.cc
  L1Trigger/L1TTrackMatch/python/L1TkHTMissProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/L1TrackFastJetProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/L1TrackJetProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/L1TrackObjectNtupleMaker_cfg.py
  L1Trigger/L1TTrackMatch/python/L1TrackerEtMissProducer_cfi.py
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#33677 Subdirectories for GEM-CSC LUTs
  L1Trigger/CSCTriggerPrimitives/python/params/gemcscParams.py
  L1Trigger/CSCTriggerPrimitives/test/CCLUTLinearFitWriter.cpp
  L1Trigger/CSCTriggerPrimitives/test/README.md
  L1Trigger/CSCTriggerPrimitives/test/macros/README.md
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, requires-external, tests-approved

#33659 added the possibility to lock a record
  DQM/BeamMonitor/plugins/BeamMonitor.cc
  DQM/BeamMonitor/plugins/BeamMonitor.h
  DQM/BeamMonitor/plugins/FakeBeamMonitor.cc
  DQM/BeamMonitor/plugins/FakeBeamMonitor.h
  DQM/BeamMonitor/python/BeamMonitor_Cosmics_cff.py
  DQM/BeamMonitor/python/BeamMonitor_MC_cff.py
  DQM/BeamMonitor/python/BeamMonitor_PixelLess_cff.py
  DQM/BeamMonitor/python/BeamMonitor_Pixel_cff.py
  DQM/BeamMonitor/python/BeamMonitor_cff.py
  DQM/BeamMonitor/python/FakeBeamMonitor_cff.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhltfake_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/last_lumi.txt
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33619 L1T Phase-2: Quantized Puppi MET emulators
  L1Trigger/Phase2L1ParticleFlow/plugins/L1METPFProducer.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#33671 Migrate module config in RecoEcal to use default cfipython
  RecoEcal/EgammaClusterProducers/python/islandBasicClusters_cfi.py
  RecoEcal/EgammaClusterProducers/python/particleFlowSuperClusterECALBox_cfi.py
  RecoEcal/EgammaClusterProducers/src/PFECALSuperClusterProducer.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33681 L1T: add HPS taus
  DataFormats/L1TParticleFlow/BuildFile.xml
  DataFormats/L1TParticleFlow/interface/HPSPFTau.h
  DataFormats/L1TParticleFlow/interface/HPSPFTauFwd.h
  DataFormats/L1TParticleFlow/src/HPSPFTau.cc
  DataFormats/L1TParticleFlow/src/classes_def.xml
  L1Trigger/Phase2L1Taus/BuildFile.xml
  L1Trigger/Phase2L1Taus/interface/L1HPSPFTauBuilder.h
  L1Trigger/Phase2L1Taus/interface/L1HPSPFTauQualityCut.h
  L1Trigger/Phase2L1Taus/plugins/BuildFile.xml
  L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.cc
  L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.h
  L1Trigger/Phase2L1Taus/python/HPSPFTauProducerPF_cfi.py
  L1Trigger/Phase2L1Taus/python/HPSPFTauProducerPuppi_cfi.py
  L1Trigger/Phase2L1Taus/python/l1emulator_cff.py
  L1Trigger/Phase2L1Taus/src/L1HPSPFTauBuilder.cc
  L1Trigger/Phase2L1Taus/src/L1HPSPFTauQualityCut.cc
  L1Trigger/Phase2L1Taus/test/produceHPSPFTaus_cfg.py
Labels: code-checks-approved, fully-signed, l1-approved, orp-pending, tests-approved, upgrade-approved

#33689 migrate SLHCUpgradeSimulations/Geometry to esConsumes
  SLHCUpgradeSimulations/Geometry/test/ModuleInfo_Phase2.cc
  SLHCUpgradeSimulations/Geometry/test/Phase2PixelNtuple.cc
  SLHCUpgradeSimulations/Geometry/test/StdHitNtuplizer.cc
  SLHCUpgradeSimulations/Geometry/test/StdHitNtuplizer.h
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#33722 Remove a deprecated "Timing" parameter from SiPixelDigiToRaw (and some header cleaning)
  EventFilter/SiPixelRawToDigi/plugins/SiPixelDigiToRaw.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33701 EGamma: Remove Fall17V1 variables from electron table for v9 NanoAOD
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, tests-approved, xpog-approved

#33707 Remove tests for root_numpy and root_pandas
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/testRootNumpy.py
Labels: analysis-pending, code-checks-approved, orp-approved, pending-signatures, tests-approved

#33684 Introducing the beamspot tag lock systems
  DQM/BeamMonitor/plugins/BeamMonitor.cc
  DQM/BeamMonitor/plugins/BeamMonitor.h
  DQM/BeamMonitor/plugins/FakeBeamMonitor.cc
  DQM/BeamMonitor/plugins/FakeBeamMonitor.h
  DQM/BeamMonitor/python/BeamMonitor_Cosmics_cff.py
  DQM/BeamMonitor/python/BeamMonitor_MC_cff.py
  DQM/BeamMonitor/python/BeamMonitor_PixelLess_cff.py
  DQM/BeamMonitor/python/BeamMonitor_Pixel_cff.py
  DQM/BeamMonitor/python/BeamMonitor_cff.py
  DQM/BeamMonitor/python/FakeBeamMonitor_cff.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhltfake_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/last_lumi.txt
Labels: dqm-approved, fully-signed, orp-approved, tests-approved

#33708 implements UPT invariant mass triggers in uGT emulator
  L1Trigger/L1TGlobal/interface/GlobalScales.h
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.h
  L1Trigger/L1TGlobal/src/CorrCondition.cc
  L1Trigger/L1TGlobal/src/GlobalScales.cc
  L1Trigger/L1TGlobal/src/MuonTemplate.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33700 Updated import TUNECP5
  Configuration/Generator/python/QQToHToTauTau_mh125_TuneCP5_14TeV_pythia8_cfi.py
  Configuration/Generator/python/TTbarToDilepton_mt172p5_TuneCP5_14TeV_pythia8_cfi.py
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33721 NanoAOD:migrate modules to ESConsumes
  PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc
  PhysicsTools/NanoAOD/plugins/LHCInfoProducer.cc
Labels: code-checks-approved, fully-signed, orp-approved, tests-approved, xpog-approved

#33660 Setting of Tag access restrictions in command line tools
  CondCore/CondDB/interface/Auth.h
  CondCore/CondDB/interface/CredentialStore.h
  CondCore/CondDB/plugins/CondDBPyBind11Wrappers.cc
  CondCore/CondDB/src/CredentialStore.cc
  CondCore/Utilities/python/conddblib.py
  CondCore/Utilities/scripts/conddb
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#33709 introduce DiMuonVertexValidation in Alignment validation suite
  Alignment/OfflineValidation/plugins/DiMuonVertexValidation.cc
  Alignment/OfflineValidation/test/DiMuonVertexValidation_cfg.py
  Alignment/OfflineValidation/test/test_all.sh
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#33724 EGamma NanoAOD: Backport of removal of Fall17v1 variables from electron Table
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: fully-signed, orp-approved, tests-approved, xpog-approved

#33658 backport tau pog nanoAOD clean up to 10_6_X
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
Labels: fully-signed, orp-approved, tests-approved, xpog-approved

#33699 Moved ProductProvenanceRetriever to FWCore/Framework
  DataFormats/Common/interface/ProductData.h
  DataFormats/Provenance/BuildFile.xml
  DataFormats/Provenance/interface/ProductProvenanceLookup.h
  DataFormats/Provenance/interface/Provenance.h
  DataFormats/Provenance/interface/ProvenanceFwd.h
  DataFormats/Provenance/src/ProductProvenanceLookup.cc
  DataFormats/Provenance/src/ProductProvenanceRetriever.cc
  DataFormats/Provenance/src/Provenance.cc
  FWCore/Framework/interface/EventPrincipal.h
  FWCore/Framework/interface/ProductProvenanceRetriever.h
  FWCore/Framework/src/ProductProvenanceRetriever.cc
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Integration/test/TestParentage.cc
  FWCore/TFWLiteSelector/src/TFWLiteSelectorBasic.cc
  IOPool/Output/src/PoolOutputModule.cc
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#33705 user-defined floating-point literals return double instead of long double
  DataFormats/Math/interface/CMSUnits.h
  DataFormats/Math/interface/GeantUnits.h
  DataFormats/Math/interface/angle_units.h
  DetectorDescription/Core/test/BuildFile.xml
  DetectorDescription/DDCMS/test/BuildFile.xml
  DetectorDescription/DDCMS/test/DDUnits.cppunit.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, reconstruction-approved, tests-approved

#33733 Improvements of O2O steering tools
  CondCore/Utilities/python/o2olib.py
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#33718 Fix compilation failure in DBG in RecoPixelVertexing/PixelVertexFinding
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuClusterTracksByDensity.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuClusterTracksDBSCAN.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuClusterTracksIterative.h
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33598 MTD geometry and reconstruction: store ETL layout logic into MTDTopology, use for ETL layers navigation in reconstruction
  Geometry/MTDCommonData/data/CrystalBarPhiFlat/mtdParameters.xml
  Geometry/MTDCommonData/data/etl/v5/etl.xml
  Geometry/MTDCommonData/data/mtdParameters/v2/mtdParameters.xml
  Geometry/MTDCommonData/test/testMTDinDD4hep.py
  Geometry/MTDCommonData/test/testMTDinDDD.py
  Geometry/MTDGeometryBuilder/interface/MTDPixelTopologyBuilder.h
  Geometry/MTDGeometryBuilder/src/MTDGeomBuilderFromGeometricTimingDet.cc
  Geometry/MTDGeometryBuilder/src/MTDParametersFromDD.cc
  Geometry/MTDGeometryBuilder/src/MTDPixelTopologyBuilder.cc
  Geometry/MTDGeometryBuilder/src/MTDTopologyBuilder.cc
  Geometry/MTDGeometryBuilder/test/dd4hep_mtd_cfg.py
  Geometry/MTDGeometryBuilder/test/mtd_cfg.py
  Geometry/MTDNumberingBuilder/interface/MTDTopology.h
  Geometry/MTDNumberingBuilder/plugins/MTDTopologyEP.cc
  Geometry/MTDNumberingBuilder/src/MTDTopology.cc
  Geometry/MTDNumberingBuilder/test/dd4hep_mtd_cfg.py
  Geometry/MTDNumberingBuilder/test/mtd_cfg.py
  RecoMTD/DetLayers/BuildFile.xml
  RecoMTD/DetLayers/interface/ETLDetLayerGeometryBuilder.h
  RecoMTD/DetLayers/interface/MTDDetSector.h
  RecoMTD/DetLayers/src/ETLDetLayerGeometryBuilder.cc
  RecoMTD/DetLayers/src/MTDDetLayerGeometry.cc
  RecoMTD/DetLayers/src/MTDDetSector.cc
  RecoMTD/DetLayers/test/BuildFile.xml
  RecoMTD/DetLayers/test/TestETLNavigation.cc
  RecoMTD/DetLayers/test/mtd_cfg.py
  RecoMTD/DetLayers/test/runTest.sh
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, reconstruction-approved, requires-external, tests-approved, upgrade-approved

#33739 Added link needed for debug build of SimTransport/PPSProtonTransport
  SimTransport/PPSProtonTransport/BuildFile.xml
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33704 Run3-gex74N Bug fix for the material budget code and add a macro for getting the plots
  SimDataFormats/CaloHit/interface/MaterialInformation.h
  Validation/Geometry/macros/MatBudgetVolume.C
  Validation/Geometry/python/materialBudgetVolume_cfi.py
  Validation/Geometry/src/MaterialBudgetVolume.cc
  Validation/Geometry/src/MaterialBudgetVolumeAnalysis.cc
  Validation/Geometry/test/runMaterialBudgetVolume_cfg.py
  Validation/Geometry/test/single_neutrino_cfg.py
Labels: code-checks-approved, dqm-approved, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved

#33747 Fix import in Phase1L1TJetProducer_cfi for python 3
  L1Trigger/L1CaloTrigger/python/Phase1L1TJetProducer_cfi.py
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#33741 Avoid type punning in L1Trigger/CSCTrackFinder
  L1Trigger/CSCTrackFinder/src/CSCSectorReceiverLUT.cc
  L1Trigger/CSCTrackFinder/src/CSCTFPtLUT.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33740 Fix debug build of L1Trigger/DTTriggerPhase2
  L1Trigger/DTTriggerPhase2/interface/DTPattern.h
  L1Trigger/DTTriggerPhase2/src/DTPattern.cc
  L1Trigger/DTTriggerPhase2/src/PseudoBayesGrouping.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#33731 speedup of trackValidatorJetCore and TrackAssociatorByChi2
  SimTracker/TrackAssociation/interface/trackAssociationChi2.h
  SimTracker/TrackAssociation/src/trackAssociationChi2.cc
  SimTracker/TrackAssociatorProducers/plugins/BuildFile.xml
  SimTracker/TrackAssociatorProducers/plugins/TrackAssociatorByChi2Impl.cc
  SimTracker/TrackAssociatorProducers/plugins/TrackAssociatorByChi2Impl.h
  Validation/RecoTrack/python/TrackValidation_cff.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33504 Vertex smearing and beamspot for PP ref UL MC
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedFixed_EmitRealistic5TeVppCollision2017_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
Labels: alca-approved, backport-ok, fully-signed, operations-approved, orp-approved, pdmv-approved, simulation-approved, tests-approved, upgrade-approved

#33680 MTD reconstruction: code cleaning for old comments (issue #24452)
  Configuration/StandardSequences/python/Reconstruction_cff.py
  DataFormats/FTLRecHit/interface/FTLCluster.h
  DataFormats/FTLRecHit/src/FTLCluster.cc
  RecoLocalFastTime/FTLClusterizer/BuildFile.xml
  RecoLocalFastTime/FTLClusterizer/interface/MTDCPEBase.h
  RecoLocalFastTime/FTLClusterizer/interface/MTDThresholdClusterizer.h
  RecoLocalFastTime/FTLClusterizer/plugins/MTDClusterProducer.cc
  RecoLocalFastTime/FTLClusterizer/src/MTDCPEBase.cc
  RecoLocalFastTime/FTLClusterizer/src/MTDThresholdClusterizer.cc
  RecoLocalFastTime/FTLRecProducers/plugins/MTDTrackingRecHitProducer.cc
  RecoMTD/Configuration/python/mtdGlobalReco_cff.py
  RecoMTD/MeasurementDet/interface/MTDDetLayerMeasurements.h
  RecoMTD/MeasurementDet/src/MTDDetLayerMeasurements.cc
  TrackingTools/RecoGeometry/plugins/GlobalDetLayerGeometryESProducer.cc
  TrackingTools/TrackRefitter/interface/TrackTransformer.h
  TrackingTools/TrackRefitter/src/TrackTransformer.cc
Labels: code-checks-approved, fully-signed, operations-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#33711 Remove hardcoded number (255) about the L1 prefiring
  L1Trigger/L1TGlobal/plugins/L1TExtCondProducer.cc
  PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, xpog-approved

#33746 Added a new run time protection for Full Sim
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/python/NeutronBGforMuons_cff.py
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/SteppingAction.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33717 Cleaning up PF contents in AOD.
  RecoParticleFlow/Configuration/python/RecoParticleFlow_EventContent_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33736 Delay assert until after secondary file ancestor check
  DataFormats/Provenance/interface/BranchIDListHelper.h
  DataFormats/Provenance/src/BranchIDListHelper.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootFile.cc
  IOPool/Input/src/RootFile.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#33735 [DD4hep] use assembly instead of complex union shapes
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalPreshowerAlgo.cc
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalPreshowerNewAlgo.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#33753 bugfix RPCSeedGenerator wrong nullptr check
  RecoMuon/MuonSeedGenerator/src/RPCSeedOverlapper.cc
Labels: bug-fix, code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33751 Remove use of root_numpy in DQM BinByBin tool
  DQMServices/FileIO/scripts/compareHistograms.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33723 CondTools/HLT: migrate to esConsumes
  CondTools/HLT/src/AlCaRecoTriggerBitsRcdRead.cc
  CondTools/HLT/src/AlCaRecoTriggerBitsRcdUpdate.cc
Labels: code-checks-approved, db-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#33694 Fix valEmtfStage2Digis for unpacked GEM clusters in GEN-SIM-RAW
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33643 CondDB frontierKey update
  CondCore/DBOutputService/src/OnlineDBOutputService.cc
  CondCore/DBOutputService/test/python/testLumiBasedUpdateAnalyzer_oracle.cfg.py
  CondCore/ESSources/plugins/CondDBESSource.cc
  CondCore/ESSources/test/python/loadall_from_one_record_empty_source_cfg.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhltfake_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/config/fileinputsource_cfi.py
  DQM/Integration/python/config/inputsource_cfi.py
  DQM/Integration/python/config/pbsource_cfi.py
  DQM/Integration/python/config/unittestinputsource_cfi.py
Labels: alca-approved, code-checks-approved, db-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33728 Add source_only flag for source-only dependencies in calibration
  CalibTracker/SiPhase2TrackerESProducers/plugins/BuildFile.xml
  CalibTracker/SiPhase2TrackerESProducers/plugins/SiPhase2OuterTrackerFakeLorentzAngleESSource.cc
  CalibTracker/SiPixelConnectivity/BuildFile.xml
  CalibTracker/SiPixelErrorEstimation/BuildFile.xml
  CalibTracker/SiPixelQuality/BuildFile.xml
  CalibTracker/SiPixelQuality/plugins/BuildFile.xml
  CalibTracker/SiPixelTools/BuildFile.xml
  CalibTracker/SiPixelTools/plugins/BuildFile.xml
  CalibTracker/SiStripChannelGain/BuildFile.xml
  CalibTracker/SiStripHitEfficiency/BuildFile.xml
  CalibTracker/SiStripHitEfficiency/plugins/BuildFile.xml
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved, upgrade-approved

#33730 Add source_only flag for source-only dependencies in reco
  RecoBTag/PixelCluster/plugins/BuildFile.xml
  RecoCaloTools/Navigation/test/BuildFile.xml
  RecoCaloTools/Navigation/test/stubs/CaloNavigationAnalyzer.cc
  RecoCaloTools/Selectors/test/BuildFile.xml
  RecoEgamma/EgammaIsolationAlgos/BuildFile.xml
  RecoEgamma/EgammaIsolationAlgos/plugins/BuildFile.xml
  RecoEgamma/EgammaPhotonProducers/BuildFile.xml
  RecoEgamma/Examples/plugins/BuildFile.xml
  RecoHGCal/TICL/plugins/BuildFile.xml
  RecoHI/HiTracking/plugins/BuildFile.xml
  RecoHI/HiTracking/test/BuildFile.xml
  RecoJets/JetProducers/BuildFile.xml
  RecoLocalMuon/GEMCSCSegment/test/BuildFile.xml
  RecoLocalMuon/GEMRecHit/test/BuildFile.xml
  RecoLocalTracker/Phase2TrackerRecHits/test/BuildFile.xml
  RecoLocalTracker/SiPhase2Clusterizer/test/BuildFile.xml
  RecoLocalTracker/SiPhase2VectorHitBuilder/BuildFile.xml
  RecoLocalTracker/SiStripRecHitConverter/BuildFile.xml
  RecoLocalTracker/SubCollectionProducers/BuildFile.xml
  RecoMTD/TransientTrackingRecHit/BuildFile.xml
  RecoMTD/TransientTrackingRecHit/plugins/BuildFile.xml
  RecoMuon/CosmicMuonProducer/BuildFile.xml
  RecoMuon/GlobalTrackingTools/BuildFile.xml
  RecoMuon/L2MuonSeedGenerator/BuildFile.xml
  RecoMuon/L2MuonSeedGenerator/plugins/BuildFile.xml
  RecoMuon/MuonIdentification/BuildFile.xml
  RecoMuon/MuonIdentification/plugins/BuildFile.xml
  RecoMuon/MuonSeedGenerator/BuildFile.xml
  RecoMuon/StandAloneTrackFinder/BuildFile.xml
  RecoMuon/TrackerSeedGenerator/plugins/BuildFile.xml
  RecoMuon/TrackingTools/BuildFile.xml
  RecoMuon/TransientTrackingRecHit/BuildFile.xml
  RecoMuon/TransientTrackingRecHit/plugins/BuildFile.xml
  RecoPPS/Local/BuildFile.xml
  RecoParticleFlow/PFSimProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFTracking/BuildFile.xml
  RecoPixelVertexing/PixelLowPtUtilities/test/BuildFile.xml
  RecoPixelVertexing/PixelTrackFitting/BuildFile.xml
  RecoTracker/ConversionSeedGenerators/plugins/BuildFile.xml
  RecoTracker/FinalTrackSelectors/plugins/BuildFile.xml
  RecoTracker/SpecialSeedGenerators/BuildFile.xml
  RecoTracker/TkDetLayers/test/BuildFile.xml
  RecoTracker/TkNavigation/test/BuildFile.xml
  RecoTracker/TkSeedGenerator/BuildFile.xml
  RecoTracker/TkSeedGenerator/plugins/BuildFile.xml
  RecoTracker/TkSeedingLayers/BuildFile.xml
  RecoTracker/TrackProducer/BuildFile.xml
  RecoVertex/V0Producer/BuildFile.xml
  RecoVertex/V0Producer/test/BuildFile.xml
  TrackingTools/GsfTools/BuildFile.xml
  TrackingTools/KalmanUpdators/BuildFile.xml
  TrackingTools/PatternTools/BuildFile.xml
  TrackingTools/TrackAssociator/BuildFile.xml
  TrackingTools/TrackAssociator/test/BuildFile.xml
  TrackingTools/TransientTrack/BuildFile.xml
  TrackingTools/TransientTrack/plugins/BuildFile.xml
  TrackingTools/TransientTrackingRecHit/BuildFile.xml
Labels: code-checks-approved, fully-signed, hlt-approved, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#33755 Remove dependencies in FWCore BuildFiles
  CalibTracker/SiStripLorentzAngle/BuildFile.xml
  CommonTools/Utils/BuildFile.xml
  CondCore/ESSources/plugins/BuildFile.xml
  DQMServices/StreamerIO/plugins/BuildFile.xml
  DataFormats/PatCandidates/BuildFile.xml
  EventFilter/L1TRawToDigi/BuildFile.xml
  FWCore/Concurrency/BuildFile.xml
  FWCore/PluginManager/BuildFile.xml
  FWCore/Reflection/BuildFile.xml
  FWCore/Utilities/BuildFile.xml
  HLTrigger/Timer/plugins/BuildFile.xml
  RecoLocalTracker/SiPixelRecHits/BuildFile.xml
  RecoLuminosity/LumiProducer/plugins/BuildFile.xml
  RecoLuminosity/LumiProducer/test/BuildFile.xml
Labels: alca-approved, code-checks-approved, core-approved, db-approved, dqm-approved, fully-signed, hlt-approved, l1-approved, orp-approved, reconstruction-approved, tests-approved

#33729 Add source_only flag for source-only dependencies in alignment
  Alignment/APEEstimation/plugins/BuildFile.xml
  Alignment/CommonAlignment/BuildFile.xml
  Alignment/CommonAlignmentAlgorithm/plugins/BuildFile.xml
  Alignment/CommonAlignmentMonitor/plugins/BuildFile.xml
  Alignment/CommonAlignmentProducer/plugins/BuildFile.xml
  Alignment/LaserAlignmentSimulation/test/BuildFile.xml
  Alignment/MillePedeAlignmentAlgorithm/BuildFile.xml
  Alignment/MuonAlignmentAlgorithms/BuildFile.xml
  Alignment/MuonAlignmentAlgorithms/plugins/BuildFile.xml
  Alignment/MuonAlignmentAlgorithms/test/BuildFile.xml
  Alignment/OfflineValidation/BuildFile.xml
  Alignment/OfflineValidation/plugins/BuildFile.xml
  Alignment/ReferenceTrajectories/BuildFile.xml
  Alignment/TrackerAlignment/BuildFile.xml
  Alignment/TrackerAlignment/plugins/BuildFile.xml
  Alignment/TrackerAlignment/test/BuildFile.xml
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#33748 Missing files for ECAL trigger double weights O2O scripts
  CondTools/Ecal/plugins/TestEcalTPGOddWeightGroupAnalyzer.cc
  CondTools/Ecal/plugins/TestEcalTPGOddWeightIdMapAnalyzer.cc
  CondTools/Ecal/plugins/TestEcalTPGTPModeAnalyzer.cc
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#33764 Support of db keys for O2O commands
  CondCore/CondDB/plugins/CondDBPyBind11Wrappers.cc
  CondCore/Utilities/python/conddblib.py
  CondCore/Utilities/python/credentials.py
  CondCore/Utilities/python/o2olib.py
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#33767 new VFAT status plots and recHit wheel occupancy plots on GEM onlineDQM
  DQM/GEM/interface/GEMDQMBase.h
  DQM/GEM/plugins/GEMDAQStatusSource.cc
  DQM/GEM/plugins/GEMDQMHarvester.cc
  DQM/GEM/plugins/GEMDigiSource.cc
  DQM/GEM/plugins/GEMRecHitSource.cc
  DQM/GEM/src/GEMDQMBase.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33752 L1T phase-2: Add the Phase2 L1T VertexFinder (corrected version)
  DataFormats/L1Trigger/BuildFile.xml
  DataFormats/L1Trigger/interface/Vertex.h
  DataFormats/L1Trigger/src/Vertex.cc
  DataFormats/L1Trigger/src/classes.h
  DataFormats/L1Trigger/src/classes_def.xml
  L1Trigger/VertexFinder/BuildFile.xml
  L1Trigger/VertexFinder/interface/AlgoSettings.h
  L1Trigger/VertexFinder/interface/AnalysisSettings.h
  L1Trigger/VertexFinder/interface/InputData.h
  L1Trigger/VertexFinder/interface/L1Track.h
  L1Trigger/VertexFinder/interface/L1TrackTruthMatched.h
  L1Trigger/VertexFinder/interface/RecoVertex.h
  L1Trigger/VertexFinder/interface/Stub.h
  L1Trigger/VertexFinder/interface/TP.h
  L1Trigger/VertexFinder/interface/Vertex.h
  L1Trigger/VertexFinder/interface/VertexFinder.h
  L1Trigger/VertexFinder/interface/VertexProducer.h
  L1Trigger/VertexFinder/interface/selection.h
  L1Trigger/VertexFinder/interface/utility.h
  L1Trigger/VertexFinder/plugins/BuildFile.xml
  L1Trigger/VertexFinder/plugins/VertexAnalyzer.cc
  L1Trigger/VertexFinder/plugins/VertexNTupler.cc
  L1Trigger/VertexFinder/plugins/VertexProducer.cc
  L1Trigger/VertexFinder/python/VertexAnalyzer_cff.py
  L1Trigger/VertexFinder/python/VertexNTupler_cff.py
  L1Trigger/VertexFinder/python/VertexProducer_cff.py
  L1Trigger/VertexFinder/src/AlgoSettings.cc
  L1Trigger/VertexFinder/src/AnalysisSettings.cc
  L1Trigger/VertexFinder/src/InputData.cc
  L1Trigger/VertexFinder/src/RecoVertex.cc
  L1Trigger/VertexFinder/src/Stub.cc
  L1Trigger/VertexFinder/src/TP.cc
  L1Trigger/VertexFinder/src/Vertex.cc
  L1Trigger/VertexFinder/src/VertexFinder.cc
  L1Trigger/VertexFinder/src/selection.cc
  L1Trigger/VertexFinder/src/utility.cc
  L1Trigger/VertexFinder/test/vertexFinder_cfg.py
  L1Trigger/VertexFinder/test/vertexNTupler_cfg.py
  SimDataFormats/TrackingAnalysis/interface/TrackingParticle.h
  SimTracker/Common/interface/TrackingParticleSelector.h
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved

#33775 DTValidation migration to ESConsume
  Validation/DTRecHits/interface/DTHitQualityUtils.h
  Validation/DTRecHits/plugins/DTRecHitQuality.cc
  Validation/DTRecHits/plugins/DTRecHitQuality.h
  Validation/DTRecHits/plugins/DTSegment2DQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DQuality.h
  Validation/DTRecHits/plugins/DTSegment2DSLPhiQuality.cc
  Validation/DTRecHits/plugins/DTSegment2DSLPhiQuality.h
  Validation/DTRecHits/plugins/DTSegment4DQuality.cc
  Validation/DTRecHits/plugins/DTSegment4DQuality.h
  Validation/DTRecHits/src/DTHitQualityUtils.cc
  Validation/MuonDTDigis/src/MuonDTDigis.cc
  Validation/MuonDTDigis/src/MuonDTDigis.h
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33760 Run3-gex74X Try to resolve the overlap in PPS
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
  Geometry/VeryForwardData/data/CTPPS_Diamond_2018/CTPPS_Diamond_Detector_Assembly/2021/v1/CTPPS_Diamond_Detector_Assembly.xml
  SimG4Core/Geometry/src/DDG4Builder.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#33772 Fix valEmtfStage2Digis for unpacked GEM clusters in GEN-SIM-RAW [11_3_X]
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
Labels: dqm-approved, fully-signed, orp-approved, tests-approved

#33762 MTD reconstruction: set fixed precision for floating point printed in unit test
  RecoMTD/DetLayers/test/MTDRecoGeometryAnalyzer.cc
  RecoMTD/DetLayers/test/TestETLNavigation.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved, upgrade-approved

#33779 [backport] MTD geometry and reconstruction: synchronise with master up to PR 33762
  Geometry/MTDCommonData/data/etl/v5/etl.xml
  Geometry/MTDCommonData/data/mtdParameters/v2/mtdParameters.xml
  Geometry/MTDCommonData/test/testMTDinDD4hep.py
  Geometry/MTDCommonData/test/testMTDinDDD.py
  Geometry/MTDGeometryBuilder/interface/MTDPixelTopologyBuilder.h
  Geometry/MTDGeometryBuilder/interface/RectangularMTDTopology.h
  Geometry/MTDGeometryBuilder/src/MTDGeomBuilderFromGeometricTimingDet.cc
  Geometry/MTDGeometryBuilder/src/MTDParametersFromDD.cc
  Geometry/MTDGeometryBuilder/src/MTDPixelTopologyBuilder.cc
  Geometry/MTDGeometryBuilder/src/MTDTopologyBuilder.cc
  Geometry/MTDGeometryBuilder/src/RectangularMTDTopology.cc
  Geometry/MTDGeometryBuilder/test/dd4hep_mtd_cfg.py
  Geometry/MTDGeometryBuilder/test/mtd_cfg.py
  Geometry/MTDNumberingBuilder/interface/MTDTopology.h
  Geometry/MTDNumberingBuilder/plugins/MTDTopologyEP.cc
  Geometry/MTDNumberingBuilder/src/MTDTopology.cc
  Geometry/MTDNumberingBuilder/test/dd4hep_mtd_cfg.py
  Geometry/MTDNumberingBuilder/test/mtd_cfg.py
  RecoMTD/DetLayers/BuildFile.xml
  RecoMTD/DetLayers/interface/ETLDetLayerGeometryBuilder.h
  RecoMTD/DetLayers/interface/MTDDetSector.h
  RecoMTD/DetLayers/src/ETLDetLayerGeometryBuilder.cc
  RecoMTD/DetLayers/src/MTDDetLayerGeometry.cc
  RecoMTD/DetLayers/src/MTDDetSector.cc
  RecoMTD/DetLayers/test/BuildFile.xml
  RecoMTD/DetLayers/test/MTDRecoGeometryAnalyzer.cc
  RecoMTD/DetLayers/test/TestETLNavigation.cc
  RecoMTD/DetLayers/test/mtd_cfg.py
  RecoMTD/DetLayers/test/runTest.sh
  SimFastTiming/FastTimingCommon/src/ETLDeviceSim.cc
  Validation/MtdValidation/test/mtdValidation_cfg.py
Labels: dqm-pending, geometry-pending, orp-approved, pending-signatures, reconstruction-pending, requires-external, simulation-pending, tests-started, upgrade-pending

#33644 CondDB frontierKey update (11_3_X)
  CondCore/DBOutputService/src/OnlineDBOutputService.cc
  CondCore/DBOutputService/test/python/testLumiBasedUpdateAnalyzer_oracle.cfg.py
  CondCore/ESSources/plugins/CondDBESSource.cc
  CondCore/ESSources/test/python/loadall_from_one_record_empty_source_cfg.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhltfake_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/config/fileinputsource_cfi.py
  DQM/Integration/python/config/inputsource_cfi.py
  DQM/Integration/python/config/pbsource_cfi.py
  DQM/Integration/python/config/unittestinputsource_cfi.py
Labels: alca-approved, db-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33749 Missing files for ECAL trigger double weights O2O scripts: backport 11_3_X
  CondTools/Ecal/plugins/TestEcalTPGOddWeightGroupAnalyzer.cc
  CondTools/Ecal/plugins/TestEcalTPGOddWeightIdMapAnalyzer.cc
  CondTools/Ecal/plugins/TestEcalTPGTPModeAnalyzer.cc
Labels: backport-ok, db-approved, fully-signed, orp-approved, tests-approved

#33768 new VFAT status plots and recHit wheel occupancy plots on GEM onlineDQM, a backport to CMSSW_11_3_X
  DQM/GEM/interface/GEMDQMBase.h
  DQM/GEM/plugins/GEMDAQStatusSource.cc
  DQM/GEM/plugins/GEMDQMHarvester.cc
  DQM/GEM/plugins/GEMDigiSource.cc
  DQM/GEM/plugins/GEMRecHitSource.cc
  DQM/GEM/src/GEMDQMBase.cc
Labels: dqm-approved, fully-signed, orp-approved, tests-approved

#33782 DQMOffline/CalibMuon migration to esConsumes
  DQMOffline/CalibMuon/interface/DTnoiseDBValidation.h
  DQMOffline/CalibMuon/interface/DTt0DBValidation.h
  DQMOffline/CalibMuon/interface/DTtTrigDBValidation.h
  DQMOffline/CalibMuon/src/DTnoiseDBValidation.cc
  DQMOffline/CalibMuon/src/DTt0DBValidation.cc
  DQMOffline/CalibMuon/src/DTtTrigDBValidation.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33719 Fix compilation in Validation/HGCalValidation
  Validation/HGCalValidation/plugins/HGCalHitValidation.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33793 Revert "[backport] MTD geometry and reconstruction: synchronise with master up to PR 33762"
  Geometry/MTDCommonData/data/etl/v5/etl.xml
  Geometry/MTDCommonData/data/mtdParameters/v2/mtdParameters.xml
  Geometry/MTDCommonData/test/testMTDinDD4hep.py
  Geometry/MTDCommonData/test/testMTDinDDD.py
  Geometry/MTDGeometryBuilder/interface/MTDTopologyBuilder.h
  Geometry/MTDGeometryBuilder/interface/RectangularMTDTopology.h
  Geometry/MTDGeometryBuilder/src/MTDGeomBuilderFromGeometricTimingDet.cc
  Geometry/MTDGeometryBuilder/src/MTDParametersFromDD.cc
  Geometry/MTDGeometryBuilder/src/MTDPixelTopologyBuilder.cc
  Geometry/MTDGeometryBuilder/src/MTDTopologyBuilder.cc
  Geometry/MTDGeometryBuilder/src/RectangularMTDTopology.cc
  Geometry/MTDGeometryBuilder/test/dd4hep_mtd_cfg.py
  Geometry/MTDGeometryBuilder/test/mtd_cfg.py
  Geometry/MTDNumberingBuilder/interface/MTDTopology.h
  Geometry/MTDNumberingBuilder/plugins/MTDTopologyEP.cc
  Geometry/MTDNumberingBuilder/src/MTDTopology.cc
  Geometry/MTDNumberingBuilder/test/dd4hep_mtd_cfg.py
  Geometry/MTDNumberingBuilder/test/mtd_cfg.py
  RecoMTD/DetLayers/BuildFile.xml
  RecoMTD/DetLayers/interface/ETLDetLayerGeometryBuilder.h
  RecoMTD/DetLayers/interface/MTDDetSector.h
  RecoMTD/DetLayers/src/ETLDetLayerGeometryBuilder.cc
  RecoMTD/DetLayers/src/MTDDetLayerGeometry.cc
  RecoMTD/DetLayers/src/MTDDetSector.cc
  RecoMTD/DetLayers/test/BuildFile.xml
  RecoMTD/DetLayers/test/MTDRecoGeometryAnalyzer.cc
  RecoMTD/DetLayers/test/TestETLNavigation.cc
  RecoMTD/DetLayers/test/mtd_cfg.py
  RecoMTD/DetLayers/test/runTest.sh
  SimFastTiming/FastTimingCommon/src/ETLDeviceSim.cc
  Validation/MtdValidation/test/mtdValidation_cfg.py
Labels: dqm-pending, geometry-pending, orp-approved, pending-signatures, reconstruction-pending, simulation-pending, tests-pending, upgrade-pending

#33706 Pixel local reco: reduce code duplication between PixelCPEGeneric and PixelCPEFast
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEFast.h
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEGeneric.h
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEGenericBase.h
  RecoLocalTracker/SiPixelRecHits/plugins/PixelCPEFastESProducer.cc
  RecoLocalTracker/SiPixelRecHits/python/PixelCPEGeneric_cfi.py
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEFast.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEGeneric.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEGenericBase.cc
Labels: allow-czangela, code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33771 DQMGenericClient to not maintain state between fit calls
  DQMServices/Components/plugins/DQMGenericClient.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33796 DQMOffline/Hcal : finalizing migration to ESGetToken
  DQMOffline/Hcal/interface/HcalRecHitsDQMClient.h
  DQMOffline/Hcal/src/HcalCollapseAnalyzer.cc
  DQMOffline/Hcal/src/HcalRecHitsDQMClient.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33742 Add init values for struct members to silence Arm warning
  L1Trigger/L1TTrackMatch/plugins/L1TrackJetProducer.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#33785 RPC-validation migration to use ESGetToken
  Validation/MuonRPCDigis/interface/RPCDigiValid.h
  Validation/MuonRPCDigis/src/RPCDigiValid.cc
  Validation/RPCRecHits/interface/RPCPointVsRecHit.h
  Validation/RPCRecHits/interface/RPCRecHitValid.h
  Validation/RPCRecHits/src/RPCPointVsRecHit.cc
  Validation/RPCRecHits/src/RPCRecHitValid.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33787 RPC DQM migration to use ESGetToken
  DQM/RPCMonitorClient/interface/RPCDCSSummary.h
  DQM/RPCMonitorClient/interface/RPCDaqInfo.h
  DQM/RPCMonitorClient/interface/RPCDataCertification.h
  DQM/RPCMonitorClient/interface/RPCDqmClient.h
  DQM/RPCMonitorClient/interface/RPCEventSummary.h
  DQM/RPCMonitorClient/interface/RPCMonitorLinkSynchro.h
  DQM/RPCMonitorClient/src/RPCDCSSummary.cc
  DQM/RPCMonitorClient/src/RPCDaqInfo.cc
  DQM/RPCMonitorClient/src/RPCDataCertification.cc
  DQM/RPCMonitorClient/src/RPCDqmClient.cc
  DQM/RPCMonitorClient/src/RPCEventSummary.cc
  DQM/RPCMonitorClient/src/RPCMonitorLinkSynchro.cc
  DQM/RPCMonitorDigi/interface/RPCMonitorDigi.h
  DQM/RPCMonitorDigi/src/RPCMonitorDigi.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33765 Test ECAL pedestals in next MWGR
  Calibration/EcalCalibAlgos/python/ecalPedestalPCLworker_cfi.py
Labels: alca-approved, fully-signed, orp-approved, tests-approved

#33804 modified the fillDescriptions method to create the cfi file automatically
  DQM/BeamMonitor/plugins/OnlineBeamMonitor.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33777 Making miniAOD low pt tracks threshold tunable
  PhysicsTools/PatAlgos/plugins/PATLostTracks.cc
  PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc
  PhysicsTools/PatAlgos/python/slimming/lostTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/packedPFCandidates_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#33800 Upt invariant mass backport 11 3 x
  L1Trigger/L1TGlobal/interface/GlobalScales.h
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.h
  L1Trigger/L1TGlobal/src/CorrCondition.cc
  L1Trigger/L1TGlobal/src/GlobalScales.cc
  L1Trigger/L1TGlobal/src/MuonTemplate.cc
Labels: fully-signed, l1-approved, orp-approved, tests-approved

#33807 L1T backport HPS taus
  DataFormats/L1TParticleFlow/BuildFile.xml
  DataFormats/L1TParticleFlow/interface/HPSPFTau.h
  DataFormats/L1TParticleFlow/interface/HPSPFTauFwd.h
  DataFormats/L1TParticleFlow/src/HPSPFTau.cc
  DataFormats/L1TParticleFlow/src/classes_def.xml
  L1Trigger/Phase2L1Taus/BuildFile.xml
  L1Trigger/Phase2L1Taus/interface/L1HPSPFTauBuilder.h
  L1Trigger/Phase2L1Taus/interface/L1HPSPFTauQualityCut.h
  L1Trigger/Phase2L1Taus/plugins/BuildFile.xml
  L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.cc
  L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.h
  L1Trigger/Phase2L1Taus/python/HPSPFTauProducerPF_cfi.py
  L1Trigger/Phase2L1Taus/python/HPSPFTauProducerPuppi_cfi.py
  L1Trigger/Phase2L1Taus/python/l1emulator_cff.py
  L1Trigger/Phase2L1Taus/src/L1HPSPFTauBuilder.cc
  L1Trigger/Phase2L1Taus/src/L1HPSPFTauQualityCut.cc
  L1Trigger/Phase2L1Taus/test/produceHPSPFTaus_cfg.py
Labels: fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#33809 fixed esConsumes call in L1TriggerJSONMonitoring
  HLTrigger/JSONMonitoring/plugins/L1TriggerJSONMonitoring.cc
Labels: code-checks-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#33788 Run3-gex74Z Take care of the preshower numbering scheme in view of changes in preshower algorithm for dd4hep
  Geometry/EcalCommonData/interface/EcalPreshowerNumberingScheme.h
  Geometry/EcalCommonData/src/EcalPreshowerNumberingScheme.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#33805 modified the fillDescriptions method to create the cfi file automatically
  DQM/BeamMonitor/plugins/OnlineBeamMonitor.cc
Labels: dqm-approved, fully-signed, orp-approved, tests-approved

#33799 IORawData/CSCCommissioning file reader fixes
  IORawData/CSCCommissioning/src/CSCFileReader.cc
  IORawData/CSCCommissioning/src/FileReaderDCC.cc
  IORawData/CSCCommissioning/test/readFile_b904_Run3.py
Labels: code-checks-approved, daq-approved, fully-signed, orp-approved, tests-approved

#33814 [11_3_X] fixed esConsumes call in L1TriggerJSONMonitoring
  HLTrigger/JSONMonitoring/plugins/L1TriggerJSONMonitoring.cc
Labels: fully-signed, hlt-approved, orp-approved, tests-approved

#33789 Run3-gex74Y Backport #33760 to remove overlap in PPS
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
  Geometry/VeryForwardData/data/CTPPS_Diamond_2018/CTPPS_Diamond_Detector_Assembly/2021/v1/CTPPS_Diamond_Detector_Assembly.xml
Labels: fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#32930 Add nConstituents to fat jets.
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: fully-signed, orp-approved, tests-approved, xpog-approved

#33531 update deepCore for Run3
  DQM/TrackingMonitorSource/python/IterTrackingModules4seedMonitoring_cfi.py
  DQM/TrackingMonitorSource/python/TrackingSourceConfig_Tier0_cff.py
  RecoTracker/IterativeTracking/python/JetCoreRegionalStep_cff.py
  RecoTracker/IterativeTracking/python/iterativeTkConfig.py
  RecoTracker/TkSeedGenerator/plugins/DeepCoreSeedGenerator.cc
  Validation/RecoTrack/python/TrackValidation_cff.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33819 [DT DQM] Fixes IB crash in DT DQM modules
  DQM/DTMonitorClient/src/DTDataIntegrityTest.cc
  DQM/DTMonitorModule/src/DTLocalTriggerLutTask.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33808 Fix EMTF unpacker crash by changing GEM station assignment.
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockGEM.cc
Labels: bug-fix, code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33811 Fix EMTF unpacker crash by changing GEM station assignment [11_3_X]
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockGEM.cc
Labels: bug-fix, fully-signed, l1-approved, orp-approved, tests-approved

#33816 HcalDQM - esConsumes Migration
  DQM/HcalCommon/interface/DQClient.h
  DQM/HcalCommon/interface/DQHarvester.h
  DQM/HcalCommon/interface/HcalCommonHeaders.h
  DQM/HcalCommon/src/DQClient.cc
  DQM/HcalCommon/src/DQHarvester.cc
  DQM/HcalTasks/interface/DigiComparisonTask.h
  DQM/HcalTasks/interface/DigiRunSummary.h
  DQM/HcalTasks/interface/DigiTask.h
  DQM/HcalTasks/interface/FCDTask.h
  DQM/HcalTasks/interface/LEDTask.h
  DQM/HcalTasks/interface/LaserTask.h
  DQM/HcalTasks/interface/NoCQTask.h
  DQM/HcalTasks/interface/PedestalRunSummary.h
  DQM/HcalTasks/interface/PedestalTask.h
  DQM/HcalTasks/interface/QIE10Task.h
  DQM/HcalTasks/interface/QIE11Task.h
  DQM/HcalTasks/interface/RawRunSummary.h
  DQM/HcalTasks/interface/RawTask.h
  DQM/HcalTasks/interface/RecHitTask.h
  DQM/HcalTasks/interface/RecoRunSummary.h
  DQM/HcalTasks/interface/TPComparisonTask.h
  DQM/HcalTasks/interface/TPRunSummary.h
  DQM/HcalTasks/interface/TPTask.h
  DQM/HcalTasks/interface/UMNioTask.h
  DQM/HcalTasks/plugins/DigiComparisonTask.cc
  DQM/HcalTasks/plugins/DigiTask.cc
  DQM/HcalTasks/plugins/FCDTask.cc
  DQM/HcalTasks/plugins/HcalOfflineHarvesting.cc
  DQM/HcalTasks/plugins/HcalOnlineHarvesting.cc
  DQM/HcalTasks/plugins/LEDTask.cc
  DQM/HcalTasks/plugins/LaserTask.cc
  DQM/HcalTasks/plugins/NoCQTask.cc
  DQM/HcalTasks/plugins/PedestalTask.cc
  DQM/HcalTasks/plugins/QIE10Task.cc
  DQM/HcalTasks/plugins/QIE11Task.cc
  DQM/HcalTasks/plugins/RawTask.cc
  DQM/HcalTasks/plugins/RecHitTask.cc
  DQM/HcalTasks/plugins/TPComparisonTask.cc
  DQM/HcalTasks/plugins/TPTask.cc
  DQM/HcalTasks/plugins/UMNioTask.cc
  DQM/HcalTasks/src/DigiRunSummary.cc
  DQM/HcalTasks/src/PedestalRunSummary.cc
  DQM/HcalTasks/src/RawRunSummary.cc
  DQM/HcalTasks/src/RecoRunSummary.cc
  DQM/HcalTasks/src/TPRunSummary.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33754 [HGCAL trigger] Auto-encoder for ECON-T data compression
  DataFormats/L1THGCal/interface/HGCalConcentratorData.h
  DataFormats/L1THGCal/src/HGCalConcentratorData.cc
  DataFormats/L1THGCal/src/classes.h
  DataFormats/L1THGCal/src/classes_def.xml
  L1Trigger/L1THGCal/BuildFile.xml
  L1Trigger/L1THGCal/interface/HGCalProcessorBase.h
  L1Trigger/L1THGCal/interface/concentrator/HGCalConcentratorAutoEncoderImpl.h
  L1Trigger/L1THGCal/interface/concentrator/HGCalConcentratorProcessorSelection.h
  L1Trigger/L1THGCal/plugins/HGCalConcentratorProducer.cc
  L1Trigger/L1THGCal/plugins/concentrator/HGCalConcentratorProcessorSelection.cc
  L1Trigger/L1THGCal/python/customTriggerCellSelect.py
  L1Trigger/L1THGCal/python/hgcalConcentratorProducer_cfi.py
  L1Trigger/L1THGCal/src/concentrator/HGCalConcentratorAutoEncoderImpl.cc
  L1Trigger/L1THGCalUtilities/plugins/ntuples/HGCalTriggerNtupleHGCConcentratorData.cc
  L1Trigger/L1THGCalUtilities/python/concentrator.py
  L1Trigger/L1THGCalUtilities/python/hgcalTriggerNtuples_cfi.py
  L1Trigger/L1THGCalUtilities/python/vfe.py
  L1Trigger/L1THGCalUtilities/test/testHGCalL1T_multialgo_V11_cfg.py
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, requires-external, tests-approved, upgrade-approved
