Repository cms-sw/cmssw, pull requests merged in 2021-04, with the labels that each got.

#33315 Refactoring RootFile
  IOPool/Input/src/RootFile.cc
  IOPool/Input/src/RootFile.h
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#33306 add missing dependencies to CUDADataFormats
  CUDADataFormats/BeamSpot/BuildFile.xml
  CUDADataFormats/TrackingRecHit/BuildFile.xml
Labels: code-checks-approved, fully-signed, heterogeneous-approved, orp-approved, reconstruction-approved, tests-approved

#33290 [HGCAL] TICL iteration data member for tracksters
  DataFormats/HGCalReco/interface/Trackster.h
  DataFormats/HGCalReco/src/classes_def.xml
  RecoHGCal/TICL/plugins/TrackstersMergeProducer.cc
  RecoHGCal/TICL/plugins/TrackstersProducer.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#33295 One more fix on the indexing of VFATs in GEM onlineDQM
  DQM/GEM/plugins/GEMDAQStatusSource.cc
  DQM/GEM/plugins/GEMDigiSource.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33264 Change binning of TP occupancy vs BX plot and update BX plot descriptions
  DQM/EcalMonitorTasks/interface/TrigPrimTask.h
  DQM/EcalMonitorTasks/python/TimingTask_cfi.py
  DQM/EcalMonitorTasks/python/TrigPrimTask_cfi.py
  DQM/EcalMonitorTasks/src/TrigPrimTask.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33310 cleanup PhysicsTools/PatUtils data files
  PhysicsTools/PatUtils/data/JEC11_V12_AK5PF_UncertaintySources.txt
  PhysicsTools/PatUtils/data/Summer12_V2_DATA_AK5PF_UncertaintySources.txt
  PhysicsTools/PatUtils/data/Summer13_V1_DATA_UncertaintySources_AK5PF.txt
  PhysicsTools/PatUtils/data/Summer13_V1_DATA_UncertaintySources_AK5PFchs.txt
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33316 Throw when no resolution fits are available in ObjectResolutionCalc
  PhysicsTools/PatUtils/interface/ObjectResolutionCalc.h
  PhysicsTools/PatUtils/src/ObjectResolutionCalc.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33210 [Backport to 11_2_X] Change DBS url to cmsweb-prod in MatrixInjector
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33211 [Backport to 10_6_X] Change DBS url to cmsweb-prod in MatrixInjector
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33317 removing data files from interface
  GeneratorInterface/EvtGenInterface/data/DECAY.DEC
  GeneratorInterface/EvtGenInterface/data/DECAY_NOLONGLIFE.DEC
  GeneratorInterface/EvtGenInterface/data/LambdaB_pmunu_LCSR.dec
  GeneratorInterface/EvtGenInterface/data/README
  GeneratorInterface/EvtGenInterface/data/evt.pdl
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, requires-external, tests-approved

#33223 MTD local reconstruction: new parameterizations for the RecHits time uncertainty
  RecoLocalFastTime/FTLCommonAlgos/BuildFile.xml
  RecoLocalFastTime/FTLCommonAlgos/plugins/BTLUncalibRecHitAlgo.cc
  RecoLocalFastTime/FTLCommonAlgos/plugins/ETLUncalibRecHitAlgo.cc
  RecoLocalFastTime/FTLRecProducers/python/mtdUncalibratedRecHits_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved, upgrade-approved

#33283 GEM cluster data vs emulator plots in L1T DQM [11_3_X]
  DQM/L1TMonitor/interface/L1TdeGEMTPG.h
  DQM/L1TMonitor/plugins/SealModule.cc
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
  DQM/L1TMonitor/python/L1TdeGEMTPG_cfi.py
  DQM/L1TMonitor/src/L1TdeGEMTPG.cc
  DQM/L1TMonitorClient/interface/L1TdeGEMTPGClient.h
  DQM/L1TMonitorClient/python/L1TStage2EmulatorMonitorClient_cff.py
  DQM/L1TMonitorClient/python/L1TdeGEMTPGClient_cfi.py
  DQM/L1TMonitorClient/src/L1TdeGEMTPGClient.cc
  DQM/L1TMonitorClient/src/SealModule.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33298 Run4-hgx280X Update some of the test codes for HGCal Geometry description
  Geometry/HGCalCommonData/test/HGCalValidHexTester.cc
  Geometry/HGCalCommonData/test/HGCalWaferTester.cc
  Geometry/HGCalCommonData/test/python/testHGCalValidHex_cfg.py
  Geometry/HGCalCommonData/test/python/testHGCalWafer_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalCellDumpDD4Hep_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalCellDumpDDD_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalWaferInFileCheck_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalWaferInFileTest_cfg.py
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#33030 EGamma: systematics + UL2016 scale and smearing corrections
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/nano_eras_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  RecoEgamma/EgammaTools/python/calibratedEgammas_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, xpog-approved

#33282 Clean BuildFiles and add source_only flags to fix warnings
  CondCore/SiPixelPlugins/plugins/BuildFile.xml
  DataFormats/CSCDigi/BuildFile.xml
  DataFormats/GEMDigi/BuildFile.xml
  DataFormats/RPCDigi/BuildFile.xml
  Geometry/MTDGeometryBuilder/test/BuildFile.xml
  HLTrigger/Egamma/plugins/BuildFile.xml
  HLTrigger/HLTcore/BuildFile.xml
  HLTrigger/HLTcore/plugins/BuildFile.xml
  HeterogeneousCore/SonicTriton/test/BuildFile.xml
  L1Trigger/L1TNtuples/BuildFile.xml
  L1Trigger/L1TNtuples/plugins/BuildFile.xml
  PhysicsTools/JetExamples/test/BuildFile.xml
  PhysicsTools/JetMCAlgos/plugins/BuildFile.xml
  PhysicsTools/PatAlgos/plugins/BuildFile.xml
  RecoEgamma/PhotonIdentification/BuildFile.xml
  RecoEgamma/PhotonIdentification/plugins/BuildFile.xml
  RecoHGCal/TICL/plugins/BuildFile.xml
  RecoHGCal/TICL/test/BuildFile.xml
  RecoTracker/FinalTrackSelectors/BuildFile.xml
  RecoTracker/FinalTrackSelectors/plugins/BuildFile.xml
  RecoVertex/PrimaryVertexProducer/BuildFile.xml
  RecoVertex/PrimaryVertexProducer/plugins/BuildFile.xml
  Validation/CSCRecHits/BuildFile.xml
  Validation/CSCRecHits/plugins/BuildFile.xml
Labels: analysis-pending, code-checks-approved, db-pending, dqm-approved, geometry-approved, heterogeneous-approved, hlt-approved, l1-approved, orp-approved, pending-signatures, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#33281 [L1TMuonBarrel] KMTF fixes on propagation coefficients (CMSSW_11_2_X)
  L1Trigger/L1TMuonBarrel/BuildFile.xml
  L1Trigger/L1TMuonBarrel/interface/L1TMuonBarrelKalmanAlgo.h
  L1Trigger/L1TMuonBarrel/interface/L1TMuonBarrelKalmanLUTs.h
  L1Trigger/L1TMuonBarrel/python/simKBmtfDigis_cfi.py
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanAlgo.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanLUTs.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanRegionModule.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanSectorProcessor.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanStubProcessor.cc
  L1Trigger/L1TMuonBarrel/test/kalmanTools/createGains.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/packGainsLUT.py
  L1Trigger/L1TMuonBarrel/test/kalmanTools/parseGainsLUT.py
Labels: fully-signed, l1-approved, orp-approved, requires-external, tests-approved

#33296 One more fix on the indexing of VFATs in GEM onlineDQM, a backport to CMSSW_11_2_X
  DQM/GEM/plugins/GEMDAQStatusSource.cc
  DQM/GEM/plugins/GEMDigiSource.cc
Labels: dqm-approved, fully-signed, orp-approved, tests-approved

#33275 Change binning of TP occupnacy vs BX plot and edit BX plot descriptions
  DQM/EcalMonitorTasks/interface/TrigPrimTask.h
  DQM/EcalMonitorTasks/python/TimingTask_cfi.py
  DQM/EcalMonitorTasks/python/TrigPrimTask_cfi.py
  DQM/EcalMonitorTasks/src/TrigPrimTask.cc
Labels: dqm-approved, fully-signed, orp-approved, tests-approved

#33304 move kalmanLUTs.root to cms-data external
  L1Trigger/L1TMuon/data/bmtf_luts/kalmanLUTs.root
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, requires-external, tests-approved

#33326 Move to D76 in HGCal geometry unit test
  Validation/Geometry/test/genHGCalPlots.sh
Labels: code-checks-approved, dqm-pending, geometry-pending, orp-approved, pending-signatures, tests-approved

#33329 PPS Pixel charge share bug fix
  SimPPS/PPSPixelDigiProducer/src/RPixChargeShare.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33082 Add interactive option to runTheMatrix
  Configuration/PyReleaseValidation/scripts/README.md
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33309 [HGCAL] CaloParticleSelector selects non-converted CP
  Validation/HGCalValidation/interface/CaloParticleSelector.h
  Validation/HGCalValidation/plugins/HGCalValidator.cc
  Validation/HGCalValidation/python/CaloParticleSelectionForEfficiency_cfi.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33330 Use ServiceWeakToken with asynchronous tasks
  FWCore/Framework/interface/Callback.h
  FWCore/Framework/src/GlobalSchedule.h
  FWCore/Framework/src/Path.cc
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/src/StreamSchedule.h
  FWCore/Framework/src/Worker.cc
  FWCore/Framework/src/Worker.h
  FWCore/Framework/test/callback_t.cppunit.cc
  FWCore/Framework/test/dependentrecord_t.cppunit.cc
  FWCore/Framework/test/eventsetuprecord_t.cppunit.cc
  FWCore/Framework/test/global_filter_t.cppunit.cc
  FWCore/Framework/test/global_outputmodule_t.cppunit.cc
  FWCore/Framework/test/global_producer_t.cppunit.cc
  FWCore/Framework/test/limited_filter_t.cppunit.cc
  FWCore/Framework/test/limited_outputmodule_t.cppunit.cc
  FWCore/Framework/test/limited_producer_t.cppunit.cc
  FWCore/Framework/test/one_outputmodule_t.cppunit.cc
  FWCore/Framework/test/stream_filter_t.cppunit.cc
  FWCore/Framework/test/stream_producer_t.cppunit.cc
  FWCore/ServiceRegistry/interface/ServiceToken.h
  FWCore/Services/plugins/InitRootHandlers.cc
  HLTrigger/Timer/plugins/FastTimerService.cc
Labels: code-checks-approved, core-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#33319 Introduce PixelTopologyMap
  Geometry/TrackerGeometryBuilder/interface/PixelTopologyMap.h
  Geometry/TrackerGeometryBuilder/src/PixelTopologyMap.cc
  Geometry/TrackerGeometryBuilder/test/BuildFile.xml
  Geometry/TrackerGeometryBuilder/test/PixelTopologyMapTest.cc
  Geometry/TrackerGeometryBuilder/test/python/testPixelTopologyMapTest_cfg.py
  Geometry/TrackerGeometryBuilder/test/runTest.sh
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#33243 Updates to the Phase-2 DT Trigger primitive generation code
  DataFormats/L1DTTrackFinder/interface/L1Phase2MuDTThContainer.h
  DataFormats/L1DTTrackFinder/interface/L1Phase2MuDTThDigi.h
  DataFormats/L1DTTrackFinder/src/L1Phase2MuDTThContainer.cc
  DataFormats/L1DTTrackFinder/src/L1Phase2MuDTThDigi.cc
  L1Trigger/DTTriggerPhase2/interface/GlobalCoordsObtainer.h
  L1Trigger/DTTriggerPhase2/interface/MuonPathAnalyticAnalyzer.h
  L1Trigger/DTTriggerPhase2/interface/MuonPathAnalyzer.h
  L1Trigger/DTTriggerPhase2/interface/MuonPathAnalyzerInChamber.h
  L1Trigger/DTTriggerPhase2/interface/MuonPathAnalyzerPerSL.h
  L1Trigger/DTTriggerPhase2/interface/MuonPathAssociator.h
  L1Trigger/DTTriggerPhase2/interface/RPCIntegrator.h
  L1Trigger/DTTriggerPhase2/interface/constants.h
  L1Trigger/DTTriggerPhase2/plugins/DTTrigPhase2Prod.cc
  L1Trigger/DTTriggerPhase2/python/dtTriggerPhase2PrimitiveDigis_cfi.py
  L1Trigger/DTTriggerPhase2/src/GlobalCoordsObtainer.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAnalyticAnalyzer.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAnalyzerInChamber.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAnalyzerPerSL.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved

#33322 Explicitly using CPUExecutionProvider in ONNXRuntime python test
  PhysicsTools/ONNXRuntime/test/plot_load_and_predict.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33331 Update geometry tags in mcRun3 GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#33246 Annotate cms::cuda::HostAllocator::allocate() as thread safe
  HeterogeneousCore/CUDAUtilities/interface/HostAllocator.h
Labels: code-checks-approved, fully-signed, heterogeneous-approved, orp-approved, tests-approved

#33308 Add a generator filter based on properties of mother and long-lived sister of a gen particle
  GeneratorInterface/GenFilters/plugins/PythiaFilterMotherSister.cc
  GeneratorInterface/GenFilters/plugins/PythiaFilterMotherSister.h
  GeneratorInterface/GenFilters/plugins/SealModule.cc
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33311 (Backport for 11_2_X) Add displaced muon info from EMTF to RegionalMuonCand (un)packing and to uGMT DQM
  DQM/L1TMonitor/interface/L1TStage2RegionalMuonCandComp.h
  DQM/L1TMonitor/interface/L1TStage2uGMT.h
  DQM/L1TMonitor/python/L1TStage2BMTF_cff.py
  DQM/L1TMonitor/python/L1TStage2uGMT_cff.py
  DQM/L1TMonitor/python/L1TdeStage2BMTFSecond_cff.py
  DQM/L1TMonitor/python/L1TdeStage2BMTF_cfi.py
  DQM/L1TMonitor/python/L1TdeStage2uGMT_cff.py
  DQM/L1TMonitor/src/L1TStage2MuonComp.cc
  DQM/L1TMonitor/src/L1TStage2RegionalMuonCandComp.cc
  DQM/L1TMonitor/src/L1TStage2uGMT.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GMTSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTPacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTPacker.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/RegionalMuonGMTUnpacker.h
  L1Trigger/L1TMuon/interface/RegionalMuonRawDigiTranslator.h
  L1Trigger/L1TMuon/src/RegionalMuonRawDigiTranslator.cc
Labels: dqm-approved, fully-signed, l1-approved, orp-approved, tests-approved

#31723 Patatrack integration - Pixel vertex reconstruction (11/N)
  CUDADataFormats/Vertex/BuildFile.xml
  CUDADataFormats/Vertex/interface/ZVertexHeterogeneous.h
  CUDADataFormats/Vertex/interface/ZVertexSoA.h
  CUDADataFormats/Vertex/src/classes.h
  CUDADataFormats/Vertex/src/classes_def.xml
  DQM/TrackingMonitorClient/python/pixelVertexResolutionClient_cfi.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/RecoB/python/PixelVertexMonitor_cff.py
  RecoPixelVertexing/Configuration/python/RecoPixelVertexing_cff.py
  RecoPixelVertexing/Configuration/python/customizePixelTracksSoAonCPU.py
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelTrackDumpCUDA.cc
  RecoPixelVertexing/PixelVertexFinding/plugins/BuildFile.xml
  RecoPixelVertexing/PixelVertexFinding/plugins/PixelVertexProducerCUDA.cc
  RecoPixelVertexing/PixelVertexFinding/plugins/PixelVertexProducerFromSoA.cc
  RecoPixelVertexing/PixelVertexFinding/plugins/PixelVertexSoAFromCUDA.cc
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuClusterTracksByDensity.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuClusterTracksDBSCAN.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuClusterTracksIterative.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuFitVertices.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuSortByPt2.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuSplitVertices.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuVertexFinder.cc
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuVertexFinder.cu
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuVertexFinder.h
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuVertexFinderImpl.h
  RecoPixelVertexing/PixelVertexFinding/python/PixelVertexes_cfi.py
  RecoPixelVertexing/PixelVertexFinding/test/BuildFile.xml
  RecoPixelVertexing/PixelVertexFinding/test/VertexFinder_t.h
  RecoPixelVertexing/PixelVertexFinding/test/cpuVertexFinder_t.cpp
  RecoPixelVertexing/PixelVertexFinding/test/gpuVertexFinder_t.cu
Labels: code-checks-approved, dqm-pending, heterogeneous-approved, orp-approved, pending-signatures, reconstruction-approved, tests-approved

#33351 [DD4hep] Re-enable DD4hep workflow 11634.911 for PR tests
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33332 RepeatingCachedRootSource
  FWCore/Framework/interface/DelayedReader.h
  FWCore/Framework/src/DelayedReader.cc
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Framework/src/ProductResolvers.h
  FWCore/TFWLiteSelector/src/TFWLiteSelectorBasic.cc
  IOPool/Input/src/RepeatingCachedRootSource.cc
  IOPool/Input/src/RootDelayedReader.cc
  IOPool/Input/src/RootDelayedReader.h
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/test/BuildFile.xml
  IOPool/Input/test/testRepeatingCachedRootSource.sh
  IOPool/Input/test/test_repeating_cfg.py
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#33120 Data vs emulator plots in CSC DQM [11_2_X]
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
  DQM/Integration/test/runtest.sh
  DQM/L1TMonitor/interface/L1TdeCSCTPG.h
  DQM/L1TMonitor/plugins/SealModule.cc
  DQM/L1TMonitor/python/L1TEmulatorMonitor_cff.py
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
  DQM/L1TMonitor/python/L1TdeCSCTPG_cfi.py
  DQM/L1TMonitor/src/L1TdeCSCTPG.cc
  DQM/L1TMonitorClient/interface/L1TdeCSCTPGClient.h
  DQM/L1TMonitorClient/python/L1TMonitorClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2EmulatorMonitorClient_cff.py
  DQM/L1TMonitorClient/python/L1TdeCSCTPGClient_cfi.py
  DQM/L1TMonitorClient/src/L1TdeCSCTPGClient.cc
  DQM/L1TMonitorClient/src/SealModule.cc
Labels: dqm-approved, fully-signed, orp-approved, tests-approved

#33085 Data vs emulator plots in CSC DQM [11_3_X]
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
  DQM/Integration/test/runtest.sh
  DQM/L1TMonitor/interface/L1TdeCSCTPG.h
  DQM/L1TMonitor/plugins/SealModule.cc
  DQM/L1TMonitor/python/L1TEmulatorMonitor_cff.py
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
  DQM/L1TMonitor/python/L1TdeCSCTPG_cfi.py
  DQM/L1TMonitor/src/L1TdeCSCTPG.cc
  DQM/L1TMonitorClient/interface/L1TdeCSCTPGClient.h
  DQM/L1TMonitorClient/python/L1TMonitorClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2EmulatorMonitorClient_cff.py
  DQM/L1TMonitorClient/python/L1TdeCSCTPGClient_cfi.py
  DQM/L1TMonitorClient/src/L1TdeCSCTPGClient.cc
  DQM/L1TMonitorClient/src/SealModule.cc
Labels: code-checks-approved, dqm-pending, orp-approved, pending-signatures, tests-approved

#33346 L1T Bugfix for Quad Muon OS condition
  L1Trigger/L1TGlobal/src/MuCondition.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33321 Fix non-optimized builds of SiStripApvGain_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripApvGain_PayloadInspector.cc
Labels: code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved

#33363 PixelToplogyMap declare overloaded operator << as inline
  Geometry/TrackerGeometryBuilder/interface/PixelTopologyMap.h
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#33353 Put CSC validation plot titles back in CSCDigiTask
  Validation/MuonCSCDigis/src/CSCALCTDigiValidation.cc
  Validation/MuonCSCDigis/src/CSCCLCTDigiValidation.cc
  Validation/MuonCSCDigis/src/CSCComparatorDigiValidation.cc
  Validation/MuonCSCDigis/src/CSCStripDigiValidation.cc
  Validation/MuonCSCDigis/src/CSCWireDigiValidation.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33344 [DD4hep] Set material temperature and pressure to NTP instead of default STP
  DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
  DetectorDescription/DDCMS/src/DDDetector.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#33280 Add DQM/TrackerRemapper package
  Alignment/OfflineValidation/plugins/BuildFile.xml
  Alignment/OfflineValidation/plugins/DMRChecker.cc
  Alignment/OfflineValidation/plugins/GeneralPurposeTrackAnalyzer.cc
  CondCore/SiPixelPlugins/BuildFile.xml
  CondCore/SiPixelPlugins/interface/Phase1PixelMaps.h
  CondCore/SiPixelPlugins/interface/SiPixelGainCalibHelper.h
  CondCore/SiPixelPlugins/interface/SiPixelPayloadInspectorHelper.h
  CondCore/SiPixelPlugins/interface/SiPixelTemplateHelper.h
  CondCore/SiPixelPlugins/plugins/BuildFile.xml
  CondCore/SiPixelPlugins/plugins/SiPixel2DTemplateDBObject_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelFEDChannelContainer_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelGenErrorDBObject_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelLorentzAngle_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelQuality_PayloadInspector.cc
  CondCore/SiPixelPlugins/plugins/SiPixelTemplateDBObject_PayloadInspector.cc
  CondCore/SiPixelPlugins/test/BuildFile.xml
  CondCore/SiPixelPlugins/test/testLorentzAngleMap.sh
  CondCore/SiPixelPlugins/test/testMiscellanea.sh
  CondCore/SiPixelPlugins/test/testSiPixelPayloadInspector.cpp
  CondCore/SiStripPlugins/interface/SiStripTkMaps.h
  CondCore/SiStripPlugins/plugins/BuildFile.xml
  CondCore/SiStripPlugins/plugins/SiStripBadStrip_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripLorentzAngle_PayloadInspector.cc
  CondCore/SiStripPlugins/test/BuildFile.xml
  CondCore/SiStripPlugins/test/testSiStripPayloadInspector.cpp
  DQM/TrackerRemapper/BuildFile.xml
  DQM/TrackerRemapper/README.md
  DQM/TrackerRemapper/interface/Phase1PixelMaps.h
  DQM/TrackerRemapper/interface/Phase1PixelROCMaps.h
  DQM/TrackerRemapper/interface/Phase1PixelSummaryMap.h
  DQM/TrackerRemapper/interface/SiPixelPhase1Analyzer.h
  DQM/TrackerRemapper/interface/SiStripTkMaps.h
  DQM/TrackerRemapper/interface/mat4.h
  DQM/TrackerRemapper/plugins/BuildFile.xml
  DQM/TrackerRemapper/plugins/SiPixelPhase1Analyzer.cc
  DQM/TrackerRemapper/plugins/TrackerRemapper.cc
  DQM/TrackerRemapper/src/Phase1PixelMaps.cc
  DQM/TrackerRemapper/src/Phase1PixelROCMaps.cc
  DQM/TrackerRemapper/src/Phase1PixelSummaryMap.cc
  DQM/TrackerRemapper/src/SiStripTkMaps.cc
  DQM/TrackerRemapper/test/PrintTkMap.py
  DQM/TrackerRemapper/test/SiPixelPhase1Analyzer_cfg.py
  DQM/TrackerRemapper/test/TrackerRemapper_cfg.py
Labels: alca-approved, code-checks-approved, db-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33320 move #defines into static constexprs inside class to avoid conflicts in cmssw
  CalibCalorimetry/EcalLaserAnalyzer/interface/TFParams.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TMCReader.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TMConfig.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TMEGeom.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TMatacq.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TPEDestalAnalysis.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TPNFit.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TSFit.h
  CalibCalorimetry/EcalLaserAnalyzer/interface/TShapeAnalysis.h
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#33348 Use LuminosityBlockCache in AlcaPCCProducer
  Calibration/LumiAlCaRecoProducers/plugins/AlcaPCCProducer.cc
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#33352 Migrate module configurations in RecoLocalCalo to use automatically generated cfi default configurations
  RecoLocalCalo/HcalRecProducers/python/hfQIE10Reco_cfi.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33301 Run3-alca182 Update some of the calibration code/scripts using IsoTracks for HCAL
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibPlotProperties.C
  Calibration/HcalCalibAlgos/macros/CalibTree.C
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkAnalyzer.cc
  Calibration/HcalCalibAlgos/test/HcalIsoTrackStudy.cc
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#33334 Added extra type of dark photon
  SimG4Core/CustomPhysics/data/particle_darkphoton.txt
  SimG4Core/CustomPhysics/interface/CMSDarkPairProductionProcess.h
  SimG4Core/CustomPhysics/src/CMSDarkPairProductionProcess.cc
  SimG4Core/CustomPhysics/src/CustomPDGParser.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33299 Fix to prevent propagation of heavy neutrino from Geant4
  SimG4Core/Generators/src/Generator.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33335 Accessors for CLCT and LCT BX as defined in RAW data [11_3_X]
  DataFormats/CSCDigi/interface/CSCCLCTDigi.h
  DataFormats/CSCDigi/interface/CSCCorrelatedLCTDigi.h
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33342 MTD geometry: add test and unit test to probe the BTL pixel structure provided by RectanbgularMTDTopology
  Geometry/MTDGeometryBuilder/test/BuildFile.xml
  Geometry/MTDGeometryBuilder/test/DD4hep_TestBTLPixelTopology.cc
  Geometry/MTDGeometryBuilder/test/dd4hep_mtd_cfg.py
  SimFastTiming/FastTimingCommon/src/BTLDeviceSim.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, simulation-approved, tests-approved, upgrade-approved

#33368 Replace last LinkDef.h file with XML selection file
  SimTransport/TotemRPProtonTransportParametrization/src/SimTransportTotemRPProtTranspParLinkDef.h
  SimTransport/TotemRPProtonTransportParametrization/src/classes.h
  SimTransport/TotemRPProtonTransportParametrization/src/classes_def.xml
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33370 PPS: direct simulation uses 14 TeV for Run3
  Validation/CTPPS/python/simu_config/year_2021_cff.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33355 Solve vectorization issue by forcing inlining and Silence CLANG Warning by making pragma optional
  DataFormats/Math/interface/choleskyInversion.h
  DataFormats/Math/test/CholeskyInvert_t.cpp
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33259 GPU pixel local reconstruction: make the pixel cluster thresholds configurable
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelClusterThresholds.h
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterCUDA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.h
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClusterChargeCut.h
  RecoLocalTracker/SiPixelClusterizer/test/gpuClustering_t.h
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33357 Accessors for CLCT and LCT BX as defined in RAW data [11_2_X]
  DataFormats/CSCDigi/interface/CSCCLCTDigi.h
  DataFormats/CSCDigi/interface/CSCCorrelatedLCTDigi.h
Labels: fully-signed, orp-approved, simulation-approved, tests-approved

#33359 UL2016 Scale and smearing corrections (backport to 106X)
  RecoEgamma/EgammaTools/python/calibratedEgammas_cff.py
Labels: fully-signed, orp-approved, reconstruction-approved, tests-approved

#33343 Phase2-gex64 Make a scenario with V14 version of HGCal and HFNose
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2026D82Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D82_cff.py
  Configuration/Geometry/python/GeometryExtended2026D82Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D82_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D82.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D82XML_cfi.py
  Geometry/ForwardCommonData/data/brm/2026/v3/brm.xml
Labels: code-checks-approved, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33362 Finalising esConsumes migration of HLTrigger/
  CalibCalorimetry/EcalTPGTools/interface/EcalReadoutTools.h
  CalibCalorimetry/EcalTPGTools/src/EcalReadoutTools.cc
  HLTrigger/HLTcore/interface/TriggerExpressionData.h
  HLTrigger/HLTcore/src/TriggerExpressionData.cc
  HLTrigger/special/plugins/HLTRechitsToDigis.cc
  RecoParticleFlow/PFClusterProducer/interface/PFClusterEMEnergyCorrector.h
  RecoParticleFlow/PFClusterProducer/src/PFClusterEMEnergyCorrector.cc
Labels: alca-approved, code-checks-approved, fully-signed, hlt-approved, l1-approved, orp-approved, reconstruction-approved, tests-approved

#33378 fix beam*_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33336 [HGCAL] Update TICL iterations naming
  RecoHGCal/TICL/plugins/TrackstersProducer.cc
  RecoHGCal/TICL/python/HADStep_cff.py
  RecoHGCal/TICL/python/TrkStep_cff.py
  RecoHGCal/TICL/python/iterativeTICL_cff.py
  Validation/HGCalValidation/python/HGCalValidator_cfi.py
  Validation/HGCalValidation/python/PostProcessorHGCAL_cfi.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#33372 Remove a dead initialization, and a few other cleanings in EcalTPGParamBuilder
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
Labels: alca-approved, code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33337 Allow consumes declarations in EDLooper
  FWCore/Framework/interface/EDLooperBase.h
  FWCore/Framework/src/EDLooperBase.cc
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/test/BuildFile.xml
  FWCore/Framework/test/run_esproducerlooper.sh
  FWCore/Framework/test/stubs/IntTestLooper.cc
  FWCore/Framework/test/stubs/TestModuleChangeLooper.cc
  FWCore/Framework/test/test_edlooper_consumes_cfg.py
Labels: code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#33382 Added time info to the displaced vertexes for muon guns
  IOMC/ParticleGuns/src/FlatRandomPtAndDxyGunProducer.cc
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33383 TkDQM remove getTH1()
  DQM/SiStripMonitorCluster/src/SiStripMonitorCluster.cc
  DQM/SiStripMonitorDigi/src/SiStripMonitorDigi.cc
  DQM/SiStripMonitorSummary/src/SiStripApvGainsDQM.cc
  DQM/SiStripMonitorSummary/src/SiStripBackPlaneCorrectionDQM.cc
  DQM/SiStripMonitorSummary/src/SiStripBaseCondObjDQM.cc
  DQM/SiStripMonitorSummary/src/SiStripCablingDQM.cc
  DQM/SiStripMonitorSummary/src/SiStripLorentzAngleDQM.cc
  DQM/SiStripMonitorSummary/src/SiStripPedestalsDQM.cc
  DQM/SiStripMonitorSummary/src/SiStripQualityDQM.cc
  DQM/SiStripMonitorTrack/src/SiStripMonitorTrack.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33385 Update histogram title and binning in CSC validation
  Validation/MuonCSCDigis/src/CSCALCTDigiValidation.cc
  Validation/MuonCSCDigis/src/CSCCLCTDigiValidation.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33341 modified merging scheme and tighter outlier suppression in primary vertex reconstruction
  RecoVertex/PrimaryVertexProducer/interface/DAClusterizerInZ_vect.h
  RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZ_vect.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33379 Phase2-hgx281 Compare DDD against DD4Hep scenario for 2026D76 scenario
  Geometry/HGCalCommonData/data/dd4hep/cms-test-ddhgcalWafer8-algorithm.xml
  Geometry/HGCalCommonData/plugins/DDHGCalCell.cc
  Geometry/HGCalCommonData/plugins/DDHGCalEEFileAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalHEFileAlgo.cc
  Geometry/HGCalCommonData/plugins/DDHGCalWafer8.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalCell.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalHEFileAlgo.cc
  Geometry/HGCalCommonData/python/testHGCalWafer8XML_cfi.py
  Geometry/HGCalCommonData/test/cms.xml
  Geometry/HGCalCommonData/test/python/runHGCalD76DD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/runHGCalD76DDD_cfg.py
  Geometry/HGCalCommonData/test/python/runHGCalWafer8DD4Hep_cfg.py
  Geometry/HGCalCommonData/test/python/runHGCalWafer8DDD_cfg.py
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#33392 GEM bug in packing GE0 digis
  EventFilter/GEMRawToDigi/plugins/GEMDigiToRawModule.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33387 Change "eight" to "eighth" in the CSC CLCT and LCT data format (CCLUT-14)
  DataFormats/CSCDigi/interface/CSCCLCTDigi.h
  DataFormats/CSCDigi/interface/CSCCorrelatedLCTDigi.h
  DataFormats/CSCDigi/src/CSCCLCTDigi.cc
  DataFormats/CSCDigi/src/CSCCorrelatedLCTDigi.cc
  L1Trigger/CSCTriggerPrimitives/interface/LCTQualityControl.h
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/LCTQualityControl.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved

#33380 New binning of Run-3 CLCT slope (CCLUT-13)
  DataFormats/CSCDigi/interface/CSCCLCTDigi.h
  DataFormats/CSCDigi/interface/CSCCorrelatedLCTDigi.h
  DataFormats/CSCDigi/src/CSCCLCTDigi.cc
  DataFormats/CSCDigi/src/CSCCorrelatedLCTDigi.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/test/macros/CCLUTLinearFitWriter.cpp
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, simulation-approved, tests-approved

#33338 Add the possibility to run multiple matrices in runTheMatrix.py
  Configuration/PyReleaseValidation/python/MatrixReader.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: code-checks-approved, fully-signed, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33360 [HGCAL] EDAnalyzer for TICL tracksters validation
  RecoHGCal/TICL/plugins/HGCDoublet.cc
  Validation/Configuration/python/hgcalSimValid_cff.py
  Validation/HGCalValidation/interface/HGCalValidator.h
  Validation/HGCalValidation/interface/HGVHistoProducerAlgo.h
  Validation/HGCalValidation/plugins/HGCalValidator.cc
  Validation/HGCalValidation/plugins/TICLTrackstersEdgesValidation.cc
  Validation/HGCalValidation/python/CaloParticleSelectionForEfficiency_cfi.py
  Validation/HGCalValidation/python/HGCalValidator_cfi.py
  Validation/HGCalValidation/python/hgcalPlots.py
  Validation/HGCalValidation/python/ticlTrackstersEdgesValidation_cfi.py
  Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py
  Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc
  Validation/RecoTrack/python/plotting/plotting.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#33374 MTD geometry, digitization, reconstruction and validation: technical cleaning of code
  Geometry/MTDCommonData/test/DD4hep_TestMTDIdealGeometry.cc
  Geometry/MTDCommonData/test/TestMTDIdealGeometry.cc
  Geometry/MTDCommonData/test/testMTDinDDD.py
  Geometry/MTDGeometryBuilder/test/MTDDigiGeometryAnalyzer.cc
  Geometry/MTDNumberingBuilder/src/CmsMTDStringToEnum.cc
  Geometry/MTDNumberingBuilder/test/BuildFile.xml
  Geometry/MTDNumberingBuilder/test/DD4hep_MTDTopologyAnalyzer.cc
  Geometry/MTDNumberingBuilder/test/GeometricTimingDetAnalyzer.cc
  Geometry/MTDNumberingBuilder/test/MTDTopologyAnalyzer.cc
  Geometry/MTDNumberingBuilder/test/dd4hep_mtd_cfg.py
  Geometry/MTDNumberingBuilder/test/mtd_cfg.py
  RecoLocalFastTime/FTLClusterizer/plugins/MTDClusterProducer.cc
  RecoLocalFastTime/FTLCommonAlgos/interface/RecHitTools.h
  RecoLocalFastTime/FTLCommonAlgos/plugins/MTDRecHitAlgo.cc
  RecoLocalFastTime/FTLCommonAlgos/src/RecHitTools.cc
  RecoLocalFastTime/FTLRecProducers/plugins/MTDRecHitProducer.cc
  RecoLocalFastTime/FTLRecProducers/plugins/MTDTrackingRecHitProducer.cc
  RecoLocalFastTime/FTLRecProducers/test/MTDRecoDump.cc
  RecoMTD/DetLayers/test/MTDRecoGeometryAnalyzer.cc
  RecoMTD/Navigation/BuildFile.xml
  RecoMTD/Navigation/interface/BTLNavigableLayer.h
  RecoMTD/Navigation/interface/DirectMTDNavigation.h
  RecoMTD/Navigation/interface/ETLNavigableLayer.h
  RecoMTD/Navigation/interface/MTDDetLayerMap.h
  RecoMTD/Navigation/interface/MTDEtaRange.h
  RecoMTD/Navigation/interface/MTDNavigableLayer.h
  RecoMTD/Navigation/interface/MTDNavigationPrinter.h
  RecoMTD/Navigation/interface/MTDNavigationSchool.h
  RecoMTD/Navigation/src/BTLNavigableLayer.cc
  RecoMTD/Navigation/src/DirectMTDNavigation.cc
  RecoMTD/Navigation/src/ETLNavigableLayer.cc
  RecoMTD/Navigation/src/MTDEtaRange.cc
  RecoMTD/Navigation/src/MTDNavigableLayer.cc
  RecoMTD/Navigation/src/MTDNavigationPrinter.cc
  RecoMTD/Navigation/src/MTDNavigationSchool.cc
  RecoMTD/Navigation/test/BuildFile.xml
  RecoMTD/Navigation/test/MTDNavigationTest.cc
  RecoMTD/TrackExtender/plugins/TrackExtenderWithMTD.cc
  SimFastTiming/FastTimingCommon/interface/BTLDeviceSim.h
  SimFastTiming/FastTimingCommon/interface/BTLElectronicsSim.h
  SimFastTiming/FastTimingCommon/interface/ETLDeviceSim.h
  SimFastTiming/FastTimingCommon/interface/ETLElectronicsSim.h
  SimFastTiming/FastTimingCommon/interface/MTDDigitizer.h
  SimFastTiming/FastTimingCommon/interface/MTDDigitizerBase.h
  SimFastTiming/FastTimingCommon/plugins/MTDDigiProducer.cc
  SimFastTiming/FastTimingCommon/plugins/MTDDigiProducer.h
  SimFastTiming/FastTimingCommon/plugins/PreMixingMTDWorker.cc
  SimFastTiming/FastTimingCommon/src/BTLDeviceSim.cc
  SimFastTiming/FastTimingCommon/src/BTLElectronicsSim.cc
  SimFastTiming/FastTimingCommon/src/ETLDeviceSim.cc
  SimFastTiming/FastTimingCommon/src/ETLElectronicsSim.cc
  SimFastTiming/FastTimingCommon/test/MTDDigiDump.cc
  Validation/MtdValidation/plugins/BtlDigiHitsValidation.cc
  Validation/MtdValidation/plugins/BtlLocalRecoValidation.cc
  Validation/MtdValidation/plugins/BtlSimHitsValidation.cc
  Validation/MtdValidation/plugins/EtlDigiHitsValidation.cc
  Validation/MtdValidation/plugins/EtlLocalRecoValidation.cc
  Validation/MtdValidation/plugins/EtlSimHitsValidation.cc
  Validation/MtdValidation/plugins/MtdTracksValidation.cc
Labels: code-checks-approved, dqm-approved, fully-signed, geometry-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#33394 CSC/GEM validation fix for HLT tests
  HLTrigger/Configuration/test/cmsDriver.csh
Labels: bug-fix, code-checks-approved, fully-signed, hlt-approved, orp-approved, tests-approved

#33272 Addition of the MTD to the tracker Navigation
  RecoMTD/DetLayers/BuildFile.xml
  RecoMTD/DetLayers/interface/BTLDetLayerGeometryBuilder.h
  RecoMTD/DetLayers/interface/ETLDetLayerGeometryBuilder.h
  RecoMTD/DetLayers/interface/MTDDetLayerGeometry.h
  RecoMTD/DetLayers/plugins/MTDDetLayerGeometryESProducer.cc
  RecoMTD/DetLayers/src/BTLDetLayerGeometryBuilder.cc
  RecoMTD/DetLayers/src/ETLDetLayerGeometryBuilder.cc
  RecoMTD/DetLayers/src/MTDDetLayerGeometry.cc
  RecoTracker/GeometryESProducer/plugins/TrackerMTDRecoGeometryESProducer.cc
  RecoTracker/GeometryESProducer/python/TrackerMTDRecoGeometryESProducer_cfi.py
  RecoTracker/MkFit/plugins/MkFitOutputConverter.cc
  RecoTracker/Record/interface/TrackerRecoGeometryRecord.h
  RecoTracker/TkDetLayers/BuildFile.xml
  RecoTracker/TkDetLayers/interface/GeometricSearchTracker.h
  RecoTracker/TkDetLayers/interface/GeometricSearchTrackerBuilder.h
  RecoTracker/TkDetLayers/src/GeometricSearchTracker.cc
  RecoTracker/TkDetLayers/src/GeometricSearchTrackerBuilder.cc
  RecoTracker/TkNavigation/plugins/SimpleBarrelNavigableLayer.cc
  RecoTracker/TkNavigation/plugins/SimpleNavigationSchool.cc
  RecoTracker/TkNavigation/test/NavigationSchoolAnalyzer.cc
  RecoTracker/TkNavigation/test/NavigationSchoolAnalyzer_cfg.py
  TrackingTools/RecoGeometry/src/GlobalDetLayerGeometry.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved, upgrade-approved

#33307 Migrate module configurations in {JetMETCorrections,PhysicsTools} to use automatically generated cfi default/reference configurations
  JetMETCorrections/Type1MET/python/cleanJetFromEEnoise_cfi.py
  PhysicsTools/PatAlgos/python/patMuonMerger_cfi.py
  PhysicsTools/PatUtils/python/tools/muonRecoMitigation.py
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33375 Patatrack Shared Hit Cleaner Fix & Update
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.cc
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.cu
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernelsImpl.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorOnGPU.cc
Labels: code-checks-approved, fully-signed, heterogeneous-approved, orp-approved, reconstruction-approved, tests-approved

#33390 Run3-gex65 Update EB to adjust overlaps: work for DDD, need more work for DD4Hep
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
  Geometry/EcalCommonData/data/ebcon/2021/v1/ebcon.xml
  Geometry/EcalCommonData/src/EcalBarrelNumberingScheme.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved, urgent

#33367 Migrate RecoParticleFlow/PFTracking to esConsumes
  RecoParticleFlow/PFTracking/interface/LightPFTrackProducer.h
  RecoParticleFlow/PFTracking/interface/PFNuclearProducer.h
  RecoParticleFlow/PFTracking/interface/PFTrackProducer.h
  RecoParticleFlow/PFTracking/plugins/GoodSeedProducer.cc
  RecoParticleFlow/PFTracking/plugins/HGCalTrackCollectionProducer.cc
  RecoParticleFlow/PFTracking/plugins/LightPFTrackProducer.cc
  RecoParticleFlow/PFTracking/plugins/PFConversionProducer.cc
  RecoParticleFlow/PFTracking/plugins/PFConversionProducer.h
  RecoParticleFlow/PFTracking/plugins/PFDisplacedTrackerVertexProducer.cc
  RecoParticleFlow/PFTracking/plugins/PFDisplacedTrackerVertexProducer.h
  RecoParticleFlow/PFTracking/plugins/PFDisplacedVertexCandidateProducer.cc
  RecoParticleFlow/PFTracking/plugins/PFDisplacedVertexCandidateProducer.h
  RecoParticleFlow/PFTracking/plugins/PFDisplacedVertexProducer.cc
  RecoParticleFlow/PFTracking/plugins/PFDisplacedVertexProducer.h
  RecoParticleFlow/PFTracking/plugins/PFElecTkProducer.cc
  RecoParticleFlow/PFTracking/plugins/PFNuclearProducer.cc
  RecoParticleFlow/PFTracking/plugins/PFTrackProducer.cc
  RecoParticleFlow/PFTracking/plugins/PFV0Producer.cc
  RecoParticleFlow/PFTracking/plugins/PFV0Producer.h
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#31854 Patatrack integration - Pixel workflows (12/N)
  Configuration/PyReleaseValidation/README.md
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: code-checks-approved, heterogeneous-approved, orp-pending, pdmv-pending, pending-signatures, requires-external, tests-approved, upgrade-approved

#33397 Run4-hgx281 Update D82 geometry version for HFNose
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D82.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D82XML_cfi.py
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved, urgent

#33389 CSCShowerDigi data format (HadronicShowerTrigger-1)
  DataFormats/CSCDigi/interface/CSCShowerDigi.h
  DataFormats/CSCDigi/interface/CSCShowerDigiCollection.h
  DataFormats/CSCDigi/src/CSCShowerDigi.cc
  DataFormats/CSCDigi/src/classes.h
  DataFormats/CSCDigi/src/classes_def.xml
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33388 Run3-alca183 Update the calibration codes for IsoTrack analysis
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibPlotProperties.C
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#33400 Geant4 10.7 physics configurations update
  Alignment/LaserAlignmentSimulation/plugins/LaserOpticalPhysics.cc
  SimG4Core/Application/interface/LowEnergyFastSimModel.h
  SimG4Core/Application/interface/RunManagerMT.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/LowEnergyFastSimModel.cc
  SimG4Core/Application/src/ParametrisedEMPhysics.cc
  SimG4Core/Application/src/RunManagerMT.cc
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysics.h
  SimG4Core/PhysicsLists/interface/CMSHadronPhysicsFTFP_BERT.h
  SimG4Core/PhysicsLists/interface/CMSHadronPhysicsFTFP_BERT106.h
  SimG4Core/PhysicsLists/plugins/DummyPhysics.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EML.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMM_TRK.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_HP_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_HP_EMM.cc
  SimG4Core/PhysicsLists/plugins/QBBCCMS.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_BERT_EML.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_BERT_HP_EML.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EML.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EMM.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
  SimG4Core/PhysicsLists/src/CMSHadronPhysicsFTFP_BERT.cc
  SimG4Core/PhysicsLists/src/CMSHadronPhysicsFTFP_BERT106.cc
  SimG4Core/Watcher/interface/SimWatcher.h
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved, urgent

#33401 Run3-gex66 Remove 2 unused solids, logical & physical volumes of PPS
  Geometry/VeryForwardData/data/RP_Horizontal_Device/2021/v1/RP_Horizontal_Device.xml
  Geometry/VeryForwardData/data/RP_Vertical_Device/2021/v1/RP_Vertical_Device.xml
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, urgent

#33410 Run4-hgx281z Fix the debug statements for algorithms of HGCAL
  Geometry/HGCalCommonData/plugins/DDHGCalCell.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalCell.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#33403 Ecal Phase 2 TP algo EcalFenix class renames
  SimCalorimetry/EcalEBTrigPrimAlgos/interface/EcalEBFenixAmplitudeFilter.h
  SimCalorimetry/EcalEBTrigPrimAlgos/interface/EcalEBFenixLinearizer.h
  SimCalorimetry/EcalEBTrigPrimAlgos/interface/EcalEBFenixPeakFinder.h
  SimCalorimetry/EcalEBTrigPrimAlgos/interface/EcalEBFenixStripFormatEB.h
  SimCalorimetry/EcalEBTrigPrimAlgos/interface/EcalEBFenixTcpFormat.h
  SimCalorimetry/EcalEBTrigPrimAlgos/interface/EcalEBTrigPrimTestAlgo.h
  SimCalorimetry/EcalEBTrigPrimAlgos/src/EcalEBFenixAmplitudeFilter.cc
  SimCalorimetry/EcalEBTrigPrimAlgos/src/EcalEBFenixLinearizer.cc
  SimCalorimetry/EcalEBTrigPrimAlgos/src/EcalEBFenixPeakFinder.cc
  SimCalorimetry/EcalEBTrigPrimAlgos/src/EcalEBFenixStripFormatEB.cc
  SimCalorimetry/EcalEBTrigPrimAlgos/src/EcalEBFenixTcpFormat.cc
  SimCalorimetry/EcalEBTrigPrimAlgos/src/EcalEBTrigPrimTestAlgo.cc
  SimCalorimetry/EcalEBTrigPrimProducers/plugins/EcalEBTrigPrimProducer.cc
  SimCalorimetry/EcalEBTrigPrimProducers/plugins/EcalEBTrigPrimProducer.h
Labels: bug-fix, code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved, upgrade-approved, urgent

#33333 [HGCAL] Tracksters to SimClusters associator
  DataFormats/HGCalReco/interface/Trackster.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/TracksterAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/TracksterAssociatorByEnergyScoreImpl.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/TracksterAssociatorByEnergyScoreProducer.cc
  SimCalorimetry/HGCalAssociatorProducers/python/TSToSCAssociation_cfi.py
  SimDataFormats/Associations/interface/TracksterToSimClusterAssociator.h
  SimDataFormats/Associations/interface/TracksterToSimClusterAssociatorBaseImpl.h
  SimDataFormats/Associations/plugins/BuildFile.xml
  SimDataFormats/Associations/plugins/TSToSCAssociatorEDProducer.cc
  SimDataFormats/Associations/src/TracksterToSimClusterAssociator.cc
  SimDataFormats/Associations/src/TracksterToSimClusterAssociatorBaseImpl.cc
  SimDataFormats/Associations/src/classes.h
  SimDataFormats/Associations/src/classes_def.xml
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#33364 Mini-PR: Remove duplicated fm and mum constants
  DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#33415 PPS: add Run-3 reco, add geometry to GTs, update era modifier
  Configuration/AlCa/python/autoCond.py
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Modifier_ctpps_cff.py
  Configuration/EventContent/python/EventContent_cff.py
  Configuration/HLT/python/addOnTestsHLT.py
  Configuration/StandardSequences/python/Eras.py
  Configuration/StandardSequences/python/RawToDigi_cff.py
  Configuration/StandardSequences/python/Reconstruction_cff.py
  DQM/CTPPS/python/ctppsDQM_cff.py
  DQM/CTPPS/test/all_ctpps_dqm_test_from_aod_cfg.py
  DQM/CTPPS/test/all_ctpps_dqm_test_from_dat_cfg.py
  DQM/CTPPS/test/all_ctpps_dqm_test_from_raw_cfg.py
  HLTrigger/Configuration/python/CustomConfigs.py
  HLTrigger/Configuration/test/cmsDriver.csh
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoPPS/Configuration/python/recoCTPPS_cff.py
  RecoPPS/Configuration/test/raw_data_test.py
  RecoPPS/Local/plugins/CTPPSLocalTrackLiteProducer.cc
  RecoPPS/Local/python/ctppsLocalTrackLiteProducer_cff.py
  RecoPPS/ProtonReconstruction/python/ctppsProtons_cff.py
Labels: alca-approved, code-checks-approved, dqm-approved, fully-signed, hlt-approved, operations-approved, orp-approved, reconstruction-approved, tests-approved, urgent

#33404 Add PPS geometry and simulation tags to GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-pending, code-checks-approved, orp-pending, pending-signatures, requires-external, tests-rejected, urgent

#33266 Re-enable ctppsProtons from recoCTPPSTask in Run-3
  RecoPPS/Configuration/python/recoCTPPS_cff.py
Labels: code-checks-approved, orp-pending, pending-signatures, reconstruction-rejected, requires-external, tests-rejected

#33398 Run4-hgx281X Update the test codes for HFNose
  Geometry/ForwardCommonData/data/hfnose/v0/hfnose.xml
  Geometry/ForwardCommonData/data/hfnose/v1/hfnose.xml
  Geometry/ForwardCommonData/data/hfnose/v2/hfnose.xml
  Geometry/ForwardCommonData/python/hfnoseAloneXML_cfi.py
  Geometry/ForwardCommonData/python/hfnoseWaferXML_cfi.py
  Geometry/ForwardCommonData/python/hfnoseXML_cfi.py
  Geometry/ForwardCommonData/python/testHFNoseXML_cfi.py
  Geometry/ForwardCommonData/test/dumpHFNoseCell_cfg.py
  Geometry/ForwardCommonData/test/dumpHFNoseWafer_cfg.py
  Geometry/ForwardCommonData/test/testHFNoseParameters_cfg.py
Labels: code-checks-approved, geometry-pending, orp-approved, pending-signatures, tests-approved, urgent

#33417 Use 11_2_X geometry in online and offline data global tags
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, tests-approved

#33381 Remove BX comparisons for CLCT and LCT in CSC L1T DQM [11_3_X]
  DQM/L1TMonitor/python/L1TdeCSCTPG_cfi.py
  DQM/L1TMonitor/src/L1TdeCSCTPG.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33422 Remove trackingMaterialGroups_ForPhaseII.xml from T25/T26 dict
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D80.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D81.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D80XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D81XML_cfi.py
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#33441 Phase2-sim84 Utilize a phase2 scenario for testing dd4hep
  SimG4Core/Configuration/test/dd4hep_ttbar_2026D77_Step1_cfg.py
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33318 [HGCAL] TICL SimTracksters
  DataFormats/HGCalReco/interface/Trackster.h
  RecoHGCal/Configuration/python/RecoHGCal_EventContent_cff.py
  RecoHGCal/TICL/plugins/BuildFile.xml
  RecoHGCal/TICL/plugins/TrackstersFromSimClustersProducer.cc
  RecoHGCal/TICL/python/SimTracksters_cff.py
  RecoHGCal/TICL/python/iterativeTICL_cff.py
  SimDataFormats/Associations/interface/LayerClusterToSimClusterAssociator.h
  Validation/Configuration/python/globalValidation_cff.py
  Validation/Configuration/python/hgcalSimValid_cff.py
  Validation/HGCalValidation/python/HGCalValidator_cfi.py
  Validation/HGCalValidation/python/PostProcessorHGCAL_cfi.py
  Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#33424 Run3-gex67 Modify Run3 workflows with changed version of RP devices
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved, upgrade-approved

#33423 Phase2-gex67 Add a new workflow with V15 version of HGCal Geometry
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2026D83Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D83_cff.py
  Configuration/Geometry/python/GeometryExtended2026D83Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D83_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D83.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D83XML_cfi.py
Labels: code-checks-approved, fully-signed, geometry-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33439 DT DQM slice-test updates
  DQM/DTMonitorModule/python/dtDigiTask_TP_cfi.py
  DQM/DTMonitorModule/python/dtDigiTask_cfi.py
  DQM/DTMonitorModule/python/dtTriggerBaseTask_cfi.py
  DQM/DTMonitorModule/python/slice_test_customizations_cff.py
  DQM/DTMonitorModule/python/test/dt_dqm_sourceclient-live_cfg.py
  DQM/DTMonitorModule/python/test/inputsource_live_cfi.py
  DQM/DTMonitorModule/src/DTDigiTask.cc
  DQM/DTMonitorModule/src/DTLocalTriggerBaseTask.cc
  DQM/DTMonitorModule/src/DTLocalTriggerBaseTask.h
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33438 [backport] Prevent propagation of heavy neutrino by Geant4
  SimG4Core/Generators/src/Generator.cc
Labels: fully-signed, orp-approved, simulation-approved, tests-approved

#33408 All daughter decay filter
  GeneratorInterface/GenFilters/plugins/PythiaAllDauVFilter.cc
  GeneratorInterface/GenFilters/plugins/PythiaAllDauVFilter.h
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33416 Hit counters for Run-3 shower CSC trigger (HadronicShowerTrigger-2)
  L1Trigger/CSCTriggerPrimitives/interface/CSCAnodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCBaseboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCTriggerPrimitivesBuilder.h
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.cc
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesProducer.h
  L1Trigger/CSCTriggerPrimitives/python/cscTriggerPrimitiveDigis_cfi.py
  L1Trigger/CSCTriggerPrimitives/python/params/showerParams.py
  L1Trigger/CSCTriggerPrimitives/src/CSCAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCBaseboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME21.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCTriggerPrimitivesBuilder.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboard.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33434 migrate DQM/TrackingMonitor to esConsumes
  DQM/TrackingMonitor/interface/TrackEfficiencyMonitor.h
  DQM/TrackingMonitor/interface/TrackSplittingMonitor.h
  DQM/TrackingMonitor/src/LogMessageMonitor.cc
  DQM/TrackingMonitor/src/PrimaryVertexResolution.cc
  DQM/TrackingMonitor/src/TrackAnalyzer.cc
  DQM/TrackingMonitor/src/TrackEfficiencyMonitor.cc
  DQM/TrackingMonitor/src/TrackSplittingMonitor.cc
  DQM/TrackingMonitor/src/TrackingMonitor.cc
  DQM/TrackingMonitor/src/TrackingRecoMaterialAnalyser.cc
  DQM/TrackingMonitor/src/V0Monitor.cc
  DQM/TrackingMonitor/src/VertexMonitor.cc
  DQM/TrackingMonitor/src/dEdxAnalyzer.cc
  DQM/TrackingMonitor/src/dEdxHitAnalyzer.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33431 Migrate EcalTPCondAnalyzer to use esConsumes
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTPCondAnalyzer.cc
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTPCondAnalyzer.h
  SimCalorimetry/EcalTrigPrimProducers/test/readDBTPConds_GlobalTag_cfg.py
  SimCalorimetry/EcalTrigPrimProducers/test/readDBTPConds_beamv5_ideal_cfg.py
  SimCalorimetry/EcalTrigPrimProducers/test/readDBTPConds_beamv5_startup_cfg.py
  SimCalorimetry/EcalTrigPrimProducers/test/readDBTPConds_cfg.py
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33445 More BuildFiles cleaning
  Alignment/LaserAlignmentSimulation/plugins/BuildFile.xml
  CUDADataFormats/HGCal/BuildFile.xml
  DQM/TrackerRemapper/plugins/BuildFile.xml
  RecoLocalCalo/HGCalRecProducers/BuildFile.xml
  RecoLocalCalo/HGCalRecProducers/plugins/BuildFile.xml
  RecoLocalFastTime/FTLCommonAlgos/BuildFile.xml
  RecoLocalFastTime/FTLCommonAlgos/plugins/BuildFile.xml
  RecoMTD/DetLayers/BuildFile.xml
  RecoTracker/TkSeedGenerator/plugins/BuildFile.xml
  SimCalorimetry/EcalEBTrigPrimAlgos/BuildFile.xml
  SimDataFormats/Associations/BuildFile.xml
  SimDataFormats/Associations/plugins/BuildFile.xml
  Validation/HGCalValidation/plugins/BuildFile.xml
Labels: alca-approved, code-checks-approved, dqm-approved, fully-signed, heterogeneous-approved, l1-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#33443 Run3-gex68 Check in more detail the contents of the geometry
  SimG4Core/PrintGeomInfo/interface/PrintGeomInfoAction.h
  SimG4Core/PrintGeomInfo/src/PrintGeomInfoAction.cc
  SimG4Core/PrintGeomInfo/test/SimFileCompare.cpp
  SimG4Core/PrintGeomInfo/test/python/runDD4HEP_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runDDD_cfg.py
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33384 [HGCAL] MultiCluster to CaloParticle associator
  DataFormats/ParticleFlowReco/interface/HGCalMultiCluster.h
  SimCalorimetry/HGCalAssociatorProducers/interface/AssociatorTools.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/LayerClusterAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/MCToCPAssociatorEDProducer.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreImpl.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreProducer.cc
  SimCalorimetry/HGCalAssociatorProducers/python/MCToCPAssociation_cfi.py
  SimDataFormats/Associations/interface/MultiClusterToCaloParticleAssociator.h
  SimDataFormats/Associations/interface/MultiClusterToCaloParticleAssociatorBaseImpl.h
  SimDataFormats/Associations/src/MultiClusterToCaloParticleAssociator.cc
  SimDataFormats/Associations/src/MultiClusterToCaloParticleAssociatorBaseImpl.cc
  SimDataFormats/Associations/src/classes.h
  SimDataFormats/Associations/src/classes_def.xml
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#33457 Cleanup Geant4 physics sub-libraries for version 10.7 and beyond
  SimG4Core/Application/src/ParametrisedEMPhysics.cc
  SimG4Core/CustomPhysics/interface/CMSSIMPInelasticProcess.h
  SimG4Core/CustomPhysics/interface/CMSSIMPInelasticXS.h
  SimG4Core/CustomPhysics/interface/DummyChargeFlipProcess.h
  SimG4Core/CustomPhysics/interface/G4ProcessHelper.h
  SimG4Core/CustomPhysics/src/CMSSIMPInelasticProcess.cc
  SimG4Core/CustomPhysics/src/CustomPhysics.cc
  SimG4Core/CustomPhysics/src/CustomPhysicsList.cc
  SimG4Core/CustomPhysics/src/DummyChargeFlipProcess.cc
  SimG4Core/CustomPhysics/src/FullModelHadronicProcess.cc
  SimG4Core/CustomPhysics/src/FullModelReactionDynamics.cc
  SimG4Core/GFlash/plugins/GFlash.cc
  SimG4Core/PhysicsLists/doc/PhysicsLists.doc
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysics.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysics95.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysics95msc93.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysicsLPM.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysicsXS.h
  SimG4Core/PhysicsLists/interface/CMSFTFPNeutronBuilder.hh
  SimG4Core/PhysicsLists/interface/CMSFTFPPiKBuilder.hh
  SimG4Core/PhysicsLists/interface/CMSFTFPProtonBuilder.hh
  SimG4Core/PhysicsLists/interface/CMSHadronPhysicsFTFP_BERT.h
  SimG4Core/PhysicsLists/interface/HadronPhysicsQGSPCMS_FTFP_BERT.h
  SimG4Core/PhysicsLists/interface/UrbanMscModel93.h
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMN.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_HP_EML.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_XS_EML.cc
  SimG4Core/PhysicsLists/plugins/QGSPCMS_FTFP_BERT_EMN.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics95.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics95msc93.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsXS.cc
  SimG4Core/PhysicsLists/src/CMSFTFPNeutronBuilder.cc
  SimG4Core/PhysicsLists/src/CMSFTFPPiKBuilder.cc
  SimG4Core/PhysicsLists/src/CMSFTFPProtonBuilder.cc
  SimG4Core/PhysicsLists/src/HadronPhysicsQGSPCMS_FTFP_BERT.cc
  SimG4Core/PhysicsLists/src/UrbanMscModel93.cc
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33449 Fix indentation in EDAlias python dump
  FWCore/ParameterSet/python/Modules.py
  FWCore/ParameterSet/python/Types.py
Labels: bug-fix, code-checks-approved, core-approved, fully-signed, orp-approved, tests-approved

#33450 Fix indentation in EDAlias python dump
  FWCore/ParameterSet/python/Modules.py
  FWCore/ParameterSet/python/Types.py
Labels: backport, bug-fix, core-approved, fully-signed, orp-approved, tests-approved

#33430 TkDQM: introduce new harvester module for creating 2D folded occupancy maps
  DQM/TrackingMonitor/interface/TrackAnalyzer.h
  DQM/TrackingMonitor/interface/TrackEfficiencyClient.h
  DQM/TrackingMonitor/interface/TrackFoldedOccupancyClient.h
  DQM/TrackingMonitor/interface/TrackingMonitor.h
  DQM/TrackingMonitor/python/TrackFoldedOccupancyClient_cfi.py
  DQM/TrackingMonitor/src/GetLumi.cc
  DQM/TrackingMonitor/src/TrackAnalyzer.cc
  DQM/TrackingMonitor/src/TrackBuildingAnalyzer.cc
  DQM/TrackingMonitor/src/TrackEfficiencyClient.cc
  DQM/TrackingMonitor/src/TrackFoldedOccupancyClient.cc
  DQM/TrackingMonitorClient/python/TrackingClientConfig_Tier0_Cosmic_cff.py
  DQM/TrackingMonitorClient/python/TrackingClientConfig_Tier0_cff.py
  DQM/TrackingMonitorClient/python/TrackingDQMClientHeavyIons_cfi.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33420 Modernize code and simplify GeometricSearchTrackerBuilder
  RecoTracker/TkDetLayers/src/GeometricSearchTrackerBuilder.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33399 Split SiPixelCalSingleMuon into two separate ALCARECO producers
  Calibration/TkAlCaRecoProducers/plugins/BuildFile.xml
  Calibration/TkAlCaRecoProducers/plugins/NearbyPixelClustersAnalyzer.cc
  Calibration/TkAlCaRecoProducers/plugins/NearbyPixelClustersProducer.cc
  Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonLoose_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonLoose_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonTight_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonTight_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuon_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuon_cff.py
  Calibration/TkAlCaRecoProducers/python/NearbyPixelClustersProducer_cfi.py
  Calibration/TkAlCaRecoProducers/python/TrackDistanceValueMapProducer_cfi.py
  Calibration/TkAlCaRecoProducers/test/inspectNearByPixelClusters_cfg.py
  Configuration/AlCa/python/autoAlca.py
  Configuration/EventContent/python/AlCaRecoOutput_RelVal_cff.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaRecoStreamsHeavyIons_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, code-checks-approved, fully-signed, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33447 [HGCAL] TICL SimTracksters - backport 11_3_X
  DataFormats/HGCalReco/interface/Trackster.h
  RecoHGCal/Configuration/python/RecoHGCal_EventContent_cff.py
  RecoHGCal/TICL/plugins/BuildFile.xml
  RecoHGCal/TICL/plugins/TrackstersFromSimClustersProducer.cc
  RecoHGCal/TICL/python/SimTracksters_cff.py
  RecoHGCal/TICL/python/iterativeTICL_cff.py
  SimDataFormats/Associations/interface/LayerClusterToSimClusterAssociator.h
  Validation/Configuration/python/globalValidation_cff.py
  Validation/Configuration/python/hgcalSimValid_cff.py
  Validation/HGCalValidation/python/HGCalValidator_cfi.py
  Validation/HGCalValidation/python/PostProcessorHGCAL_cfi.py
  Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py
Labels: backport-ok, dqm-approved, fully-signed, orp-approved, reconstruction-approved, simulation-approved, tests-approved, upgrade-approved

#33215 [PPS] Prompt calibration loop component for timing detector
  CalibPPS/TimingCalibration/interface/TimingCalibrationStruct.h
  CalibPPS/TimingCalibration/plugins/BuildFile.xml
  CalibPPS/TimingCalibration/plugins/PPSTimingCalibrationPCLHarvester.cc
  CalibPPS/TimingCalibration/plugins/PPSTimingCalibrationPCLWorker.cc
  CalibPPS/TimingCalibration/python/ALCARECOPPSCalTrackBasedSel_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSCalTrackBasedSel_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSTimingCalib_cff.py
  CalibPPS/TimingCalibration/python/PPSTimingCalibrationHarvester_cff.py
  Configuration/AlCa/python/autoPCL.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_production.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
  HLTrigger/special/plugins/HLTPPSPerPotTrackFilter.cc
Labels: alca-approved, code-checks-approved, fully-signed, hlt-approved, operations-approved, orp-approved, pdmv-approved, tests-approved, upgrade-approved

#33413 Make BadHcalMitigation enabled by default
  Configuration/Eras/python/Era_Run2_2018_pp_on_AA_cff.py
  Configuration/Eras/python/Era_Run2_2018_pp_on_AA_noHCALmitigation_cff.py
  Configuration/Eras/python/Modifier_pf_badHcalMitigationOff_cff.py
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/Eras.py
  RecoJets/JetProducers/python/caloJetsForTrk_cff.py
  RecoParticleFlow/PFClusterProducer/plugins/PFBadHcalPseudoClusterProducer.cc
  RecoParticleFlow/PFClusterProducer/python/particleFlowBadHcalPseudoCluster_cff.py
  RecoParticleFlow/PFProducer/python/particleFlow_cff.py
  RecoParticleFlow/PFProducer/src/PFEGammaFilters.cc
Labels: code-checks-approved, fully-signed, operations-approved, orp-approved, pdmv-approved, reconstruction-approved, tests-approved, upgrade-approved

#33471 Run3-gex71 Modified version of EB numbering scheme code which will work with modified EB algorithm
  Geometry/EcalCommonData/interface/EcalBarrelNumberingScheme.h
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalBarrelNewAlgoSubtraction.cc
  Geometry/EcalCommonData/src/EcalBarrelNumberingScheme.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#33464 Fix unit test in PhysicsTools/UtilAlgos
  PhysicsTools/UtilAlgos/test/fwliteWithPythonConfig_cfg.py
Labels: analysis-pending, code-checks-approved, orp-approved, pending-signatures, tests-approved

#33472 Deal with FastSim issue raised from #33430
  DQM/TrackingMonitorClient/python/TrackingClientConfig_Tier0_cff.py
Labels: bug-fix, code-checks-approved, dqm-pending, orp-approved, pending-signatures, tests-started

#33473 Update python tests - py3 only
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
Labels: analysis-pending, code-checks-approved, orp-approved, pending-signatures, tests-approved

#33465 Remove dead assignments from L1Trigger/CSCTrackFinder
  L1Trigger/CSCTrackFinder/src/CSCTFPtLUT.cc
  L1Trigger/CSCTrackFinder/src/CSCTFPtMethods.cc
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33453 MTD geometry and digitization: move check for pixel active area into RectangularMTDTopology, make it usable for BTL as well
  Geometry/MTDCommonData/data/mtdParameters/v2/mtdParameters.xml
  Geometry/MTDGeometryBuilder/interface/RectangularMTDTopology.h
  Geometry/MTDGeometryBuilder/src/RectangularMTDTopology.cc
  SimFastTiming/FastTimingCommon/src/ETLDeviceSim.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, requires-external, simulation-approved, tests-approved, upgrade-approved

#33432 [backport] Added new filter, thought for a B -> l HNL X analysis
  GeneratorInterface/GenFilters/interface/PythiaFilterMotherSister.h
  GeneratorInterface/GenFilters/src/PythiaFilterMotherSister.cc
  GeneratorInterface/GenFilters/src/SealModule.cc
Labels: fully-signed, generators-approved, orp-approved, tests-approved

#33300 [Upgrade Phase-2 Pixel 3D Digitizer] Fix misevaluation of charge when migrating due to diffusion
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/python/PixelTestBeamValidation_cfi.py
  SimTracker/SiPhase2Digitizer/test/PixelTestBeamValidation.cc
  SimTracker/SiPhase2Digitizer/test/PixelTestBeamValidation.h
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved, upgrade-approved

#33463 TkDQM: backport of PR 33430
  DQM/TrackingMonitor/interface/TrackAnalyzer.h
  DQM/TrackingMonitor/interface/TrackEfficiencyClient.h
  DQM/TrackingMonitor/interface/TrackFoldedOccupancyClient.h
  DQM/TrackingMonitor/interface/TrackingMonitor.h
  DQM/TrackingMonitor/python/TrackFoldedOccupancyClient_cfi.py
  DQM/TrackingMonitor/src/GetLumi.cc
  DQM/TrackingMonitor/src/TrackAnalyzer.cc
  DQM/TrackingMonitor/src/TrackBuildingAnalyzer.cc
  DQM/TrackingMonitor/src/TrackEfficiencyClient.cc
  DQM/TrackingMonitor/src/TrackFoldedOccupancyClient.cc
  DQM/TrackingMonitorClient/python/TrackingClientConfig_Tier0_Cosmic_cff.py
  DQM/TrackingMonitorClient/python/TrackingClientConfig_Tier0_cff.py
  DQM/TrackingMonitorClient/python/TrackingDQMClientHeavyIons_cfi.py
Labels: backport-ok, bug-fix, dqm-approved, fully-signed, orp-approved, tests-approved

#33429 Use CSCConstants in CSC trigger, packer, unpacker and track-finders
  DataFormats/CSCDigi/interface/CSCComparatorDigi.h
  DataFormats/CSCDigi/interface/CSCConstants.h
  DataFormats/CSCDigi/interface/CSCStripDigi.h
  DataFormats/CSCDigi/src/CSCComparatorDigi.cc
  DataFormats/CSCDigi/src/CSCStripDigi.cc
  DataFormats/L1TMuon/interface/CSCConstants.h
  DataFormats/L1TMuon/src/EMTFHit.cc
  EventFilter/CSCRawToDigi/interface/CSCAnodeData.h
  EventFilter/CSCRawToDigi/interface/CSCAnodeDataFormat.h
  EventFilter/CSCRawToDigi/interface/CSCEventData.h
  EventFilter/CSCRawToDigi/interface/CSCVTMBHeaderFormat.h
  EventFilter/CSCRawToDigi/plugins/CSCDCCUnpacker.cc
  EventFilter/CSCRawToDigi/src/CSCAnodeData.cc
  EventFilter/CSCRawToDigi/src/CSCAnodeData2006.cc
  EventFilter/CSCRawToDigi/src/CSCAnodeData2007.cc
  EventFilter/CSCRawToDigi/src/CSCCFEBData.cc
  EventFilter/CSCRawToDigi/src/CSCCFEBTimeSlice.cc
  EventFilter/CSCRawToDigi/src/CSCComparatorData.cc
  EventFilter/CSCRawToDigi/src/CSCDMBHeader2013.cc
  EventFilter/CSCRawToDigi/src/CSCDigiToRaw.cc
  EventFilter/CSCRawToDigi/src/CSCEventData.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader2007_rev0x50c3.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader2013.cc
  EventFilter/L1TRawToDigi/src/OmtfCscPacker.cc
  EventFilter/L1TRawToDigi/src/OmtfCscUnpacker.cc
  L1Trigger/CSCTrackFinder/src/CSCSectorReceiverLUT.cc
  L1Trigger/CSCTrackFinder/src/CSCSectorReceiverMiniLUT.cc
  L1Trigger/CSCTrackFinder/src/CSCTFDTReceiver.cc
  L1Trigger/CSCTrackFinder/src/CSCTFMuonSorter.cc
  L1Trigger/CSCTriggerPrimitives/interface/CSCAnodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCBaseboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCPatternBank.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCUpgradeCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCUpgradeMotherboardLUT.h
  L1Trigger/CSCTriggerPrimitives/interface/LCTContainer.h
  L1Trigger/CSCTriggerPrimitives/plugins/CSCAnodeLCTAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/plugins/CSCCathodeLCTAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/plugins/CSCCathodeLCTAnalyzer.h
  L1Trigger/CSCTriggerPrimitives/plugins/CSCTriggerPrimitivesReader.h
  L1Trigger/CSCTriggerPrimitives/src/CSCAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMuonPortCard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboardLUT.cc
  L1Trigger/CSCTriggerPrimitives/src/LCTQualityControl.cc
  L1Trigger/L1TMuon/src/GeometryTranslator.cc
  L1Trigger/L1TMuonEndCap/test/tools/MakeAngleLUT.cc
  L1Trigger/L1TMuonEndCap/test/tools/MakeCoordLUT.cc
  L1Trigger/L1TMuonOverlap/src/AngleConverter.cc
  L1Trigger/L1TMuonOverlap/src/OMTFinputMaker.cc
  Validation/MuonCSCDigis/src/CSCStubMatcher.cc
Labels: code-checks-approved, dqm-approved, fully-signed, l1-approved, orp-approved, reconstruction-approved, simulation-approved, tests-approved

#33433 Added ZpEE and ZpMM GEN fragments for release validation
  Configuration/Generator/python/ZpToEE_m6000_TuneCP5_14TeV_pythia8_cfi.py
  Configuration/Generator/python/ZpToMM_m6000_TuneCP5_14TeV_pythia8_cfi.py
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33414 Additional 14 TeV gen fragments for SUSY release validation
  Configuration/Generator/python/SMS-T1tttt_mGl-1500_mLSP-100_TuneCP5_14TeV_pythia8_cfi.py
  Configuration/Generator/python/VBFHZZ4Nu_TuneCP5_14TeV_pythia8_cfi.py
Labels: code-checks-approved, fully-signed, generators-approved, orp-approved, tests-approved

#33405 Changing the proton propagator to the Optical Function method
  SimPPS/Configuration/test/gluglu_step1_GEN_SIM_2021.py
  SimPPS/Configuration/test/gluglu_step2_DIGI_DIGI2RAW_2021.py
  SimPPS/Configuration/test/gluglu_step3_RAW2DIGI_L1Reco_RECO_2021.py
  SimPPS/Configuration/test/pg_step1_GEN_SIM_2021.py
  SimPPS/Configuration/test/pg_step2_DIGI_DIGI2RAW_2021.py
  SimPPS/Configuration/test/pg_step3_MCDB_RAW2DIGI_RECO_2021.py
  SimTransport/PPSProtonTransport/python/OpticalFunctionsConfig_cfi.py
  SimTransport/PPSProtonTransport/python/PPSTransportESSources_cfi.py
  SimTransport/PPSProtonTransport/python/PPSTransport_cff.py
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33418 Remove deprecated usages of isnan or isinf
  CalibCalorimetry/HcalAlgos/interface/HcalPulseShapes.h
  DQMOffline/Muon/src/GEMEfficiencyHarvester.cc
  FastSimulation/CTPPSFastTrackingProducer/plugins/CTPPSFastTrackingProducer.cc
  RecoBTag/FeatureTools/src/deep_helpers.cc
  RecoParticleFlow/PFProducer/src/MLPFModel.cc
  RecoTracker/SpecialSeedGenerators/src/SeedGeneratorForCosmics.cc
Labels: alca-approved, code-checks-approved, dqm-approved, fastsim-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33481 Phase2-hgx281z Update validation scripts to do validation of V15 geometry of HGCal
  Validation/HGCalValidation/test/python/runHFNoseDigiStudy_cfg.py
  Validation/HGCalValidation/test/python/runHFNoseRecHitStudy_cfg.py
  Validation/HGCalValidation/test/python/runHFNoseSimHitStudy_cfg.py
  Validation/HGCalValidation/test/python/runHGCGeomCheck_cfg.py
  Validation/HGCalValidation/test/python/runHGCalDigiStudy_cfg.py
  Validation/HGCalValidation/test/python/runHGCalRecHitStudy_cfg.py
  Validation/HGCalValidation/test/python/runHGCalSimHitStudy_cfg.py
  Validation/HGCalValidation/test/python/runHGCalWaferHitCheck_cfg.py
  Validation/HGCalValidation/test/python/runHGCalWaferStudy_cfg.py
  Validation/HGCalValidation/test/python/testHGCalBHValid_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimHitStudy_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV10_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV11_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV12_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV13_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV14_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV15_cfg.py
  Validation/HGCalValidation/test/python/testHGCalSimWatcherV9_cfg.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33477 run3-hcx296 Add a new testing code and rearrange some of the files
  Validation/HcalHits/plugins/BuildFile.xml
  Validation/HcalHits/plugins/HcalGeomCheck.cc
  Validation/HcalHits/plugins/HcalHitValidation.cc
  Validation/HcalHits/plugins/HcalSimHitCheck.cc
  Validation/HcalHits/test/HcalHitValidation.h
  Validation/HcalHits/test/plotHcalSimHit.C
  Validation/HcalHits/test/run_SimHitCheck_cfg.py
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33489 add missing dependencies to SimDataFormats/Association
  SimDataFormats/Associations/BuildFile.xml
  SimDataFormats/Associations/plugins/BuildFile.xml
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33339 [DD4hep] Ecal Barrel algorithm - use assemblies. Fix all overlaps in EBAR.
  Geometry/EcalCommonData/data/ebcon.xml
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalBarrelNewAlgo.cc
Labels: code-checks-approved, fully-signed, geometry-approved, orp-approved, tests-approved

#33487 Fix unit test in PhysicsTools/UtilAlgos (11_3_X)
  PhysicsTools/UtilAlgos/test/fwliteWithPythonConfig_cfg.py
Labels: analysis-pending, orp-approved, pending-signatures, tests-approved

#33484 Remove CLCT-centric matching option in CSC trigger primitives
  L1Trigger/CSCTriggerPrimitives/interface/CSCAnodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMotherboardME11.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCGEMMotherboardME21.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCMotherboard.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCMotherboardME11.h
  L1Trigger/CSCTriggerPrimitives/interface/CSCUpgradeMotherboard.h
  L1Trigger/CSCTriggerPrimitives/python/CSCTriggerPrimitivesReader_cfi.py
  L1Trigger/CSCTriggerPrimitives/python/params/tmbParams.py
  L1Trigger/CSCTriggerPrimitives/src/CSCAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME21.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME11.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeAnodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeCathodeLCTProcessor.cc
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboard.cc
  L1Trigger/CSCTriggerPrimitives/test/CSCTPEmulator_cfg.py
  L1Trigger/CSCTriggerPrimitives/test/CSCTriggerPrimitivesProducerTest_cfg.py
  L1Trigger/CSCTriggerPrimitives/test/CSCTriggerPrimitivesReader_cfg.py
  L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveProducer_cfg.py
Labels: code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33496 93X Backport, Add number of events, beginLumi's, and beginRun's to JobReport
  FWCore/Services/plugins/Timing.cc
Labels: core-approved, fully-signed, orp-approved, tests-approved

#33497 80X Backport, Add number of events, beginLumi's, and beginRun's to Jo…
  FWCore/Services/plugins/Timing.cc
Labels: core-approved, fully-signed, orp-approved, tests-approved

#33494 Backport, Add number of events, beginLumi's, and beginRun's to JobReport
  FWCore/Services/plugins/Timing.cc
Labels: core-approved, fully-signed, orp-approved, tests-approved

#33458 Move PFClusterWidthAlgo into CommonTools/ParticleFlow
  CommonTools/ParticleFlow/interface/PFClusterWidthAlgo.h
  CommonTools/ParticleFlow/src/PFClusterWidthAlgo.cc
  RecoEcal/EgammaClusterAlgos/BuildFile.xml
  RecoEcal/EgammaClusterAlgos/src/PFECALSuperClusterAlgo.cc
  RecoEcal/EgammaClusterProducers/src/SCEnergyCorrectorProducer.cc
  RecoEgamma/EgammaElectronProducers/plugins/BuildFile.xml
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSCProducer.cc
  RecoEgamma/EgammaTools/interface/HGCalShowerShapeHelper.h
  RecoEgamma/EgammaTools/src/HGCalShowerShapeHelper.cc
  RecoParticleFlow/PFProducer/BuildFile.xml
  RecoParticleFlow/PFProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFProducer/plugins/PFElectronTranslator.cc
  RecoParticleFlow/PFProducer/plugins/PFPhotonTranslator.cc
  RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc
Labels: code-checks-approved, fully-signed, orp-approved, reconstruction-approved, tests-approved

#33506 Added forgotten const
  SimDataFormats/EncodedEventId/interface/EncodedEventId.h
Labels: code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33493 Run3-gee71x Correct EB geometry and numbering scheme (backport #33339 and #33471)
  Geometry/EcalCommonData/interface/EcalBarrelNumberingScheme.h
  Geometry/EcalCommonData/plugins/dd4hep/DDEcalBarrelNewAlgo.cc
  Geometry/EcalCommonData/src/EcalBarrelNumberingScheme.cc
Labels: fully-signed, geometry-approved, orp-approved, tests-approved

#33490 PPS: fix two validation plots
  Validation/CTPPS/plugins/CTPPSProtonReconstructionSimulationValidator.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, tests-approved

#33462 Speedup Track Validation
  SimDataFormats/Track/interface/UniqueSimTrackId.h
  SimGeneral/TrackingAnalysis/interface/SimHitTPAssociationProducer.h
  SimGeneral/TrackingAnalysis/plugins/SimHitTPAssociationProducer.cc
  SimTracker/TrackAssociation/interface/CosmicParametersDefinerForTP.h
  SimTracker/TrackAssociation/interface/ParametersDefinerForTP.h
  SimTracker/TrackAssociation/src/ParametersDefinerForTP.cc
  SimTracker/TrackerHitAssociation/plugins/ClusterTPAssociationProducer.cc
  Validation/RecoTrack/plugins/MultiTrackValidator.cc
Labels: code-checks-approved, dqm-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33503 PPS Pixel charge share bug fix - part 2
  CalibPPS/ESProducers/plugins/PPSPixelTopologyESSource.cc
  SimPPS/PPSPixelDigiProducer/src/RPixChargeShare.cc
Labels: alca-approved, code-checks-approved, fully-signed, orp-approved, simulation-approved, tests-approved

#33507 Add ECAL TPG double weight tags and remove GEMELMapRcd from GTs
  Configuration/AlCa/python/autoCond.py
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTrigPrimESDoubleWeights_cff.py
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTriggerPrimitiveDigis_cff.py
Labels: alca-approved, code-checks-approved, fully-signed, l1-approved, orp-approved, tests-approved

#33509 Add ECAL TPG double weight tags and remove GEMELMapRcd from GTs [11_3_X]
  Configuration/AlCa/python/autoCond.py
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTrigPrimESDoubleWeights_cff.py
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTriggerPrimitiveDigis_cff.py
Labels: alca-approved, backport, fully-signed, l1-approved, orp-approved, tests-approved

#33505 Support of private frontier Key for workflow-specific caching
  CondCore/DBOutputService/interface/OnlineDBOutputService.h
  CondCore/DBOutputService/src/OnlineDBOutputService.cc
  CondCore/DBOutputService/test/python/testLumiBasedUpdateAnalyzer_oracle.cfg.py
  CondCore/ESSources/plugins/CondDBESSource.cc
  CondCore/ESSources/plugins/CondDBESSource.h
  CondCore/ESSources/test/python/loadall_from_one_record_empty_source_cfg.py
Labels: alca-approved, code-checks-approved, db-approved, fully-signed, orp-approved, tests-approved
