Repository cms-sw/cmssw, pull requests merged in 2022-04, with the labels that each got.

#37420 add DB ntuplizer and SiStripCondVisualizer, introduce analysis macros and add unit tests
  CondTools/SiStrip/macros/compareFiles.C
  CondTools/SiStrip/macros/makeNoisePedestalScatterPlot.C
  CondTools/SiStrip/macros/noise_analysis.C
  CondTools/SiStrip/macros/plotHistogramsTogether.C
  CondTools/SiStrip/macros/readSiStripDBTrees.C
  CondTools/SiStrip/plugins/SiStripCondVisualizer.cc
  CondTools/SiStrip/plugins/SiStripDB2Tree.cc
  CondTools/SiStrip/test/SiStripCondVisualizer_cfg.py
  CondTools/SiStrip/test/db_tree_dump.py
  CondTools/SiStrip/test/db_tree_dump_wrapper.py
  CondTools/SiStrip/test/testBuildersReaders.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#37404 Change quality criteria for some supercrystals in the Ecal Endcaps for LED Quality plots [CMSSW_12_3_X]
  DQM/EcalMonitorClient/interface/LedClient.h
  DQM/EcalMonitorClient/src/LedClient.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#37380 Change quality criteria for some supercrystals in the Ecal Endcaps for LED Quality plots [CMSSW_12_2_X]
  DQM/EcalMonitorClient/interface/LedClient.h
  DQM/EcalMonitorClient/src/LedClient.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#37421 Fixing FastTimerClient Hist Remaking Issue : 12_3_X
  HLTrigger/Timer/plugins/FastTimerServiceClient.cc
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#37419 Enable concurrent IOVs by default in ConfigBuilder
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37424 Added new muon-tau-jet OvRm filter
  HLTrigger/HLTfilters/plugins/plugins.cc
Labels: hlt-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#37382 L1T vertex finder phase2 developments
  L1Trigger/VertexFinder/BuildFile.xml
  L1Trigger/VertexFinder/interface/AlgoSettings.h
  L1Trigger/VertexFinder/interface/RecoVertex.h
  L1Trigger/VertexFinder/interface/VertexFinder.h
  L1Trigger/VertexFinder/interface/VertexProducer.h
  L1Trigger/VertexFinder/plugins/TPStubValueMapProducer.cc
  L1Trigger/VertexFinder/plugins/VertexNTupler.cc
  L1Trigger/VertexFinder/plugins/VertexProducer.cc
  L1Trigger/VertexFinder/python/VertexNTupler_cff.py
  L1Trigger/VertexFinder/python/VertexProducer_cff.py
  L1Trigger/VertexFinder/src/AlgoSettings.cc
  L1Trigger/VertexFinder/src/InputData.cc
  L1Trigger/VertexFinder/src/VertexFinder.cc
  L1Trigger/VertexFinder/test/vertexNTupler_cfg.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37383 L1T phase-2: modify HPS taus
  DataFormats/L1TParticleFlow/interface/HPSPFTau.h
  DataFormats/L1TParticleFlow/src/classes_def.xml
  L1Trigger/Phase2L1Taus/BuildFile.xml
  L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.cc
  L1Trigger/Phase2L1Taus/python/HPSPFTauProducerPF_cfi.py
  L1Trigger/Phase2L1Taus/python/HPSPFTauProducerPuppi_cfi.py
  L1Trigger/Phase2L1Taus/src/L1HPSPFTauBuilder.cc
  L1Trigger/Phase2L1Taus/test/produceHPSPFTaus_cfg.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37415 [12_4_X] Fix writing of int8_t flat table columns in nanoAOD flat ntuples
  PhysicsTools/NanoAOD/plugins/TableOutputBranches.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#37355 Phase-2 L1: code for L1 demonstrators
  L1Trigger/DemonstratorTools/BuildFile.xml
  L1Trigger/DemonstratorTools/interface/BoardData.h
  L1Trigger/DemonstratorTools/interface/BoardDataReader.h
  L1Trigger/DemonstratorTools/interface/BoardDataWriter.h
  L1Trigger/DemonstratorTools/interface/ChannelSpec.h
  L1Trigger/DemonstratorTools/interface/EventData.h
  L1Trigger/DemonstratorTools/interface/FileFormat.h
  L1Trigger/DemonstratorTools/interface/Frame.h
  L1Trigger/DemonstratorTools/interface/LinkId.h
  L1Trigger/DemonstratorTools/interface/codecs/tracks.h
  L1Trigger/DemonstratorTools/interface/codecs/vertices.h
  L1Trigger/DemonstratorTools/interface/utilities.h
  L1Trigger/DemonstratorTools/notes.md
  L1Trigger/DemonstratorTools/plugins/BuildFile.xml
  L1Trigger/DemonstratorTools/plugins/GTTFileReader.cc
  L1Trigger/DemonstratorTools/plugins/GTTFileWriter.cc
  L1Trigger/DemonstratorTools/python/GTTFileReader_cff.py
  L1Trigger/DemonstratorTools/python/GTTFileWriter_cff.py
  L1Trigger/DemonstratorTools/src/BoardData.cc
  L1Trigger/DemonstratorTools/src/BoardDataReader.cc
  L1Trigger/DemonstratorTools/src/BoardDataWriter.cc
  L1Trigger/DemonstratorTools/src/EventData.cc
  L1Trigger/DemonstratorTools/src/FileFormat.cc
  L1Trigger/DemonstratorTools/src/Frame.cc
  L1Trigger/DemonstratorTools/src/LinkId.cc
  L1Trigger/DemonstratorTools/src/codecs_tracks.cc
  L1Trigger/DemonstratorTools/src/codecs_vertices.cc
  L1Trigger/DemonstratorTools/src/utilities.cc
  L1Trigger/DemonstratorTools/test/gtt/createFirmwareInputFiles_cfg.py
  L1Trigger/DemonstratorTools/test/gtt/example_vertex_apx.txt
  L1Trigger/DemonstratorTools/test/gtt/example_vertex_emp.txt
  L1Trigger/DemonstratorTools/test/gtt/verifyFirmwareOutput_cfg.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37358 Phase 2 L1: add code for Phase 2 L1 GMT
  L1Trigger/Phase2L1GMT/BuildFile.xml
  L1Trigger/Phase2L1GMT/interface/Constants.h
  L1Trigger/Phase2L1GMT/interface/ConvertedTTTrack.h
  L1Trigger/Phase2L1GMT/interface/Isolation.h
  L1Trigger/Phase2L1GMT/interface/L1TPhase2GMTBarrelStubProcessor.h
  L1Trigger/Phase2L1GMT/interface/L1TPhase2GMTEndcapStubProcessor.h
  L1Trigger/Phase2L1GMT/interface/MuonROI.h
  L1Trigger/Phase2L1GMT/interface/Node.h
  L1Trigger/Phase2L1GMT/interface/PreTrackMatchedMuon.h
  L1Trigger/Phase2L1GMT/interface/ROITempAssociator.h
  L1Trigger/Phase2L1GMT/interface/Tauto3Mu.h
  L1Trigger/Phase2L1GMT/interface/TopologicalAlgorithm.h
  L1Trigger/Phase2L1GMT/interface/TrackConverter.h
  L1Trigger/Phase2L1GMT/interface/TrackMuonMatchAlgorithm.h
  L1Trigger/Phase2L1GMT/plugins/BuildFile.xml
  L1Trigger/Phase2L1GMT/plugins/Phase2L1TGMTProducer.cc
  L1Trigger/Phase2L1GMT/plugins/Phase2L1TGMTSAMuonProducer.cc
  L1Trigger/Phase2L1GMT/plugins/Phase2L1TGMTStubProducer.cc
  L1Trigger/Phase2L1GMT/python/gmt_cff.py
  L1Trigger/Phase2L1GMT/python/gmt_cfi.py
  L1Trigger/Phase2L1GMT/src/L1TPhase2GMTBarrelStubProcessor.cc
  L1Trigger/Phase2L1GMT/src/L1TPhase2GMTEndcapStubProcessor.cc
  L1Trigger/Phase2L1GMT/test/gmtStudy.py
  L1Trigger/Phase2L1GMT/test/makeTrackConversionLUTs.py
  L1Trigger/Phase2L1GMT/test/runGMT.py
  L1Trigger/Phase2L1GMT/test/submitCrab.py
  L1Trigger/Phase2L1GMT/test/test.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37367 remove duplicate of `PropagateToMuon` class
  HLTriggerOffline/Muon/BuildFile.xml
  HLTriggerOffline/Muon/doc/Muon.doc
  HLTriggerOffline/Muon/interface/HLTMuonPlotter.h
  HLTriggerOffline/Muon/interface/L1MuonMatcherAlgo.h
  HLTriggerOffline/Muon/interface/PropagateToMuon.h
  HLTriggerOffline/Muon/python/hltMuonValidator_cfi.py
  HLTriggerOffline/Muon/src/HLTMuonPlotter.cc
  HLTriggerOffline/Muon/src/HLTMuonValidator.cc
  HLTriggerOffline/Muon/src/L1MuonMatcherAlgo.cc
  HLTriggerOffline/Muon/src/PropagateToMuon.cc
  MuonAnalysis/MuonAssociators/interface/L1MuonMatcherAlgo.h
  MuonAnalysis/MuonAssociators/interface/PropagateToMuonSetup.h
  MuonAnalysis/MuonAssociators/src/L1MuonMatcherAlgo.cc
  MuonAnalysis/MuonAssociators/src/PropagateToMuonSetup.cc
Labels: analysis-pending, dqm-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved

#37426 [12_3_X] Added muon-tau-jet OvRm Filter
  HLTrigger/HLTfilters/plugins/plugins.cc
Labels: hlt-approved, fully-signed, tests-rejected, orp-approved, backport-ok

#37431 Fixed overlaps in M10 Phase2 Scenario (D86, D88, D91)
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D86.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D88.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D91.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D86XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D88XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D91XML_cfi.py
  Geometry/MuonCommonData/data/muonYoke/2026/v3/muonYoke.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37417 Set concurrent lumis/IOVs in ConfigBuilder if their value is different from default regardless of the number of threads
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37440 Update of L1T menu in TSG GTs to `L1Menu_Collisions2022_v1_0_0_xml`
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37398 Stabilize Fishbone
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.cc
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.cu
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernelsImpl.h
  RecoPixelVertexing/PixelTriplets/plugins/GPUCACell.h
  RecoPixelVertexing/PixelTriplets/plugins/gpuFishbone.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37442 Update final L1T menu tag for Run 3 start up
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37330 Phase2-hg302 Bug fix for the corners and replacing cout with message logger services
  Geometry/HGCalCommonData/interface/HGCalDDDConstants.h
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalGeometry/interface/HGCalGeometry.h
  Geometry/HGCalGeometry/plugins/FastTimeGeometryESProducer.cc
  Geometry/HGCalGeometry/src/FastTimeGeometry.cc
  Geometry/HGCalGeometry/src/FastTimeGeometryLoader.cc
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
  Geometry/HGCalGeometry/test/FastTimeGeometryTester.cc
  Geometry/HGCalGeometry/test/HGCalGeometryNewCornersTest.cc
  Geometry/HGCalGeometry/test/python/testHGCalGeometryNewCorners_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#37430 ECAL GPU unpacker - Add detection of corrupted DCC tower headers and recovery
  EventFilter/EcalRawToDigi/plugins/UnpackGPU.cu
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, allow-thomreis

#37446 [12_3_X] Set concurrent lumis/IOVs in ConfigBuilder if their value is different from default regardless of the number of threads
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved

#37445 [12_2_X] Set concurrent lumis/IOVs in ConfigBuilder if their value is different from default regardless of the number of threads
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved

#37441 Update of L1T menu in TSG GTs to `L1Menu_Collisions2022_v1_0_0_xml` [`12_3_X`]
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37443 [12_3_X] Update final L1T menu tag for Run 3 start up
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37449 bugfix - xml tag in PPS strips mapping
  CondFormats/PPSObjects/xml/mapping_tracking_strip_2022.xml
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37423 [GEM] bugfix - BC and OrbitCounter in AMC13 - backport
  DataFormats/GEMDigi/interface/GEMAMC13.h
  DataFormats/GEMDigi/interface/GEMAMCStatus.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, backport-ok

#37422 [GEM] bugfix - BC and OrbitCounter in AMC13 - backport
  DataFormats/GEMDigi/interface/GEMAMC13.h
  DataFormats/GEMDigi/interface/GEMAMCStatus.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, backport-ok

#37428 Run3-gex126X Utilize messagelogger instead of cout in SimG4CMS/Muon and SimG4CMS/ShowerLibraryProducer
  SimG4CMS/Muon/src/MuonG4Numbering.cc
  SimG4CMS/ShowerLibraryProducer/plugins/CastorShowerLibraryMaker.cc
  SimG4CMS/ShowerLibraryProducer/plugins/HcalForwardLibWriter.cc
  SimG4CMS/ShowerLibraryProducer/test/AnalyzeTuples.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37436 ECAL GPU unpacker - Add detection of corrupted DCC tower headers and recovery - backport 12_2_X
  EventFilter/EcalRawToDigi/plugins/UnpackGPU.cu
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#37447 Run3-sim116 Make use of printing and creating root tree compatible with multithreaded jobs in a number of packages of SimG4Core
  SimG4Core/GFlash/TB/TreeMatrixCalib.cc
  SimG4Core/GFlash/TB/TreeMatrixCalib.h
  SimG4Core/GFlash/TB/TreeProducerCalibSimul.cc
  SimG4Core/GFlash/TB/TreeProducerCalibSimul.h
  SimG4Core/GFlash/src/GflashHadronWrapperProcess.cc
  SimG4Core/Geometry/src/DDG4SolidConverter.cc
  SimG4Core/PrintTrackNumber/src/PrintTrackNumberAction.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37450 [12_3_X] Fix xml tag in PPS strips mapping
  CondFormats/PPSObjects/xml/mapping_tracking_strip_2022.xml
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#37438 HCAL finegrain bit fix to account for TDC packing, and SOI alignment
  SimCalorimetry/HcalTrigPrimAlgos/interface/HcalFinegrainBit.h
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalFinegrainBit.cc
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalTriggerPrimitiveAlgo.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37347 Run-3 FastSim modifier and workflows in runTheMatrix
  Configuration/Eras/python/Era_Run3_FastSim_cff.py
  Configuration/PyReleaseValidation/README.md
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/Eras.py
  SimGeneral/MixingModule/python/aliases_cfi.py
  SimGeneral/MixingModule/python/digitizers_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#37434 Add AlCaLumiPixels_Run3 scenario
  Configuration/DataProcessing/python/Impl/AlCaLumiPixels_Run3.py
  Configuration/DataProcessing/test/run_CfgTest.sh
Labels: operations-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37397 introduce SiPhase2BadStrip format for phase-2 simulation
  CalibTracker/SiPhase2TrackerESProducers/plugins/BuildFile.xml
  CalibTracker/SiPhase2TrackerESProducers/plugins/SiPhase2BadStripConfigurableFakeESSource.cc
  CondCore/SiPhase2TrackerPlugins/BuildFile.xml
  CondCore/SiPhase2TrackerPlugins/src/plugin.cc
  CondFormats/DataRecord/interface/SiPhase2OuterTrackerCondDataRecords.h
  CondFormats/DataRecord/src/SiPhase2OuterTrackerCondDataRecords.cc
  CondFormats/SiStripObjects/interface/SiStripBadStrip.h
  CondFormats/SiStripObjects/test/BuildFile.xml
  CondFormats/SiStripObjects/test/test_catch2_SiStripBadStripForPhase2.cpp
  CondFormats/SiStripObjects/test/test_catch2_main.cpp
  CondTools/SiPhase2Tracker/plugins/BuildFile.xml
  CondTools/SiPhase2Tracker/plugins/SiPhase2BadStripChannelBuilder.cc
  CondTools/SiPhase2Tracker/plugins/SiPhase2BadStripChannelReader.cc
  CondTools/SiPhase2Tracker/test/SiPhase2BadStripChannelBuilder_cfg.py
  CondTools/SiPhase2Tracker/test/SiPhase2BadStripChannelReader_cfg.py
  CondTools/SiPhase2Tracker/test/test_CondToolsSiPhase2Tracker.sh
  Configuration/Geometry/python/GeometryDD4hepExtended2026D49_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D60_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D68_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D70_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D76_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D77_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D78_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D79_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D80_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D81_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D82_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D83_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D84_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D85_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D86_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D87_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D88_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D89_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D90_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D91_cff.py
  Configuration/Geometry/python/GeometryExtended2026D49_cff.py
  Configuration/Geometry/python/GeometryExtended2026D53_cff.py
  Configuration/Geometry/python/GeometryExtended2026D60_cff.py
  Configuration/Geometry/python/GeometryExtended2026D68_cff.py
  Configuration/Geometry/python/GeometryExtended2026D70_cff.py
  Configuration/Geometry/python/GeometryExtended2026D76_cff.py
  Configuration/Geometry/python/GeometryExtended2026D77_cff.py
  Configuration/Geometry/python/GeometryExtended2026D78_cff.py
  Configuration/Geometry/python/GeometryExtended2026D79_cff.py
  Configuration/Geometry/python/GeometryExtended2026D80_cff.py
  Configuration/Geometry/python/GeometryExtended2026D81_cff.py
  Configuration/Geometry/python/GeometryExtended2026D82_cff.py
  Configuration/Geometry/python/GeometryExtended2026D83_cff.py
  Configuration/Geometry/python/GeometryExtended2026D84_cff.py
  Configuration/Geometry/python/GeometryExtended2026D85_cff.py
  Configuration/Geometry/python/GeometryExtended2026D86_cff.py
  Configuration/Geometry/python/GeometryExtended2026D87_cff.py
  Configuration/Geometry/python/GeometryExtended2026D88_cff.py
  Configuration/Geometry/python/GeometryExtended2026D89_cff.py
  Configuration/Geometry/python/GeometryExtended2026D90_cff.py
  Configuration/Geometry/python/GeometryExtended2026D91_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  DataFormats/SiStripCommon/interface/ConstantsForCondObjects.h
  SLHCUpgradeSimulations/Geometry/python/fakePhase2OuterTrackerConditions_cff.py
Labels: alca-approved, geometry-approved, reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, upgrade-approved, code-checks-approved

#37411 Update all GPU workflows
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#37455 minor changes to SiPixelLorentzAnglePCL modules
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLHarvester.cc
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLWorker.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37395 Adding option to disable resetting L1 PS counters on ls change
  L1Trigger/L1TGlobal/interface/GlobalBoard.h
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.h
  L1Trigger/L1TGlobal/src/GlobalBoard.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37444 Backport to `12_3_X` of Patatrack pixel-reco updates (pT-clamping in vertex sorting + stabilized Fishbone)
  CUDADataFormats/Track/interface/TrackSoAHeterogeneousT.h
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelTrackProducerFromSoA.cc
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelTrackSoAFromCUDA.cc
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.cc
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.cu
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernels.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernelsImpl.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorOnGPU.cc
  RecoPixelVertexing/PixelTriplets/plugins/GPUCACell.h
  RecoPixelVertexing/PixelTriplets/plugins/gpuFishbone.h
  RecoPixelVertexing/PixelVertexFinding/plugins/PixelVertexProducerCUDA.cc
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuVertexFinder.cc
  RecoPixelVertexing/PixelVertexFinding/plugins/gpuVertexFinder.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok, heterogeneous-approved

#37462 Adding option to disable resetting L1 PS counters on ls change [`12_3_X`]
  L1Trigger/L1TGlobal/interface/GlobalBoard.h
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.h
  L1Trigger/L1TGlobal/src/GlobalBoard.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#37459 minor changes to SiPixelLorentzAnglePCL modules [12.3.X]
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLHarvester.cc
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLWorker.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#37439 [Backport of] HCAL finegrain bit fix to account for TDC packing, and SOI alignment
  SimCalorimetry/HcalTrigPrimAlgos/interface/HcalFinegrainBit.h
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalFinegrainBit.cc
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalTriggerPrimitiveAlgo.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37219 Bug fix for multiple detectors in PFRecHitQTestHCALThresholdVsDepth test
  RecoParticleFlow/PFClusterProducer/interface/PFRecHitQTests.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37464 get rid of CMSDEPRECATED_X warnings in `HeavyFlavorAnalysis/SpecificDecay`
  HeavyFlavorAnalysis/SpecificDecay/plugins/BPHHistoSpecificDecay.cc
  HeavyFlavorAnalysis/SpecificDecay/plugins/BPHHistoSpecificDecay.h
  HeavyFlavorAnalysis/SpecificDecay/plugins/BPHWriteSpecificDecay.cc
  HeavyFlavorAnalysis/SpecificDecay/plugins/BPHWriteSpecificDecay.h
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#37413 Update all GPU workflows [12.3.x]
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, backport-ok

#37279 CSC Run3 data format unpacking/packing update (12_4_X)
  EventFilter/CSCRawToDigi/interface/CSCALCTHeader.h
  EventFilter/CSCRawToDigi/interface/CSCDCCExaminer.h
  EventFilter/CSCRawToDigi/interface/CSCDigiToRaw.h
  EventFilter/CSCRawToDigi/interface/CSCEventData.h
  EventFilter/CSCRawToDigi/interface/CSCGEMData.h
  EventFilter/CSCRawToDigi/interface/CSCTMBData.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2006.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2007.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2007_rev0x50c3.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2013.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2020_CCLUT.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2020_GEM.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2020_Run2.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2020_TMB.h
  EventFilter/CSCRawToDigi/interface/CSCVTMBHeaderFormat.h
  EventFilter/CSCRawToDigi/plugins/CSCDCCUnpacker.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiAnalyzer.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiToPattern.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiToRawModule.cc
  EventFilter/CSCRawToDigi/plugins/CSCViewDigi.cc
  EventFilter/CSCRawToDigi/python/cscPacker_cfi.py
  EventFilter/CSCRawToDigi/python/cscUnpacker_cfi.py
  EventFilter/CSCRawToDigi/python/viewDigi_cfi.py
  EventFilter/CSCRawToDigi/src/CSCALCTHeader.cc
  EventFilter/CSCRawToDigi/src/CSCCFEBData.cc
  EventFilter/CSCRawToDigi/src/CSCDCCEventData.cc
  EventFilter/CSCRawToDigi/src/CSCDCCExaminer.cc
  EventFilter/CSCRawToDigi/src/CSCDMBHeader.cc
  EventFilter/CSCRawToDigi/src/CSCDigiToRaw.cc
  EventFilter/CSCRawToDigi/src/CSCEventData.cc
  EventFilter/CSCRawToDigi/src/CSCGEMData.cc
  EventFilter/CSCRawToDigi/src/CSCTMBData.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader2020_CCLUT.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader2020_GEM.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader2020_TMB.cc
  EventFilter/CSCRawToDigi/test/README.md
  EventFilter/CSCRawToDigi/test/cscRawToDigiTest.cpp
  EventFilter/CSCRawToDigi/test/testCSCDigi2Raw_cfg.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37465 EMTF Unpacker Update to Add HMT and Displaced Muon Information [12_3_X]
  DataFormats/L1TMuon/interface/EMTF/SP.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockSP.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFCollections.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFTokens.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFTokens.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37437 Update to DNN-based strategy for outside-in seed generation in Muon HLT
  RecoMuon/TrackerSeedGenerator/plugins/TSGForOIDNN.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#37468 [12_3_X] Add AlCaLumiPixels_Run3 scenario and unit test
  Configuration/DataProcessing/python/Impl/AlCaLumiPixels_Run3.py
  Configuration/DataProcessing/test/run_CfgTest.sh
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#37480 Utilities/StaticAnaylzers: Add check to postprocess-scan-build.py for empty cells to avoid index out of range error.
  Utilities/StaticAnalyzers/scripts/postprocess-scan-build.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37471 HCAL: fix on HCAL TP saturation algorithm to synchronize s/w TP algorithm with f/w
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalTriggerPrimitiveAlgo.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37360 Improve autoAlca dictionaries layout
  Configuration/AlCa/python/autoAlca.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37427 MuonAlignment GEM phase2 geometry
  Alignment/MuonAlignment/interface/AlignableMuon.h
  Alignment/MuonAlignment/src/AlignableMuon.cc
  Alignment/MuonAlignment/src/MuonAlignmentInputXML.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37458 [Backport 123X] pT dependent ROI producers for Muon HLT
  RecoMuon/GlobalTrackingTools/interface/MuonTrackingRegionByPtBuilder.h
  RecoMuon/GlobalTrackingTools/plugins/Module.cc
  RecoMuon/GlobalTrackingTools/src/MuonTrackingRegionByPtBuilder.cc
  RecoTracker/TkTrackingRegions/plugins/BuildFile.xml
  RecoTracker/TkTrackingRegions/plugins/L1MuonSeededTrackingRegionsProducer.h
  RecoTracker/TkTrackingRegions/plugins/SealModule.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#37467 [Backport 12_3_X] Update to DNN-based strategy for outside-in seed generation in Muon HLT
  RecoMuon/TrackerSeedGenerator/plugins/TSGForOIDNN.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external

#37460 Phase2-hgx306 Make a trivial change to reduce number of methods in Geometry/HGcalGeometry
  Geometry/HGCalGeometry/interface/HGCalGeometry.h
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37473 Run3-sim116X Clean up the codes in SimG4Core/GFlash/TB as suggested by Andrea
  SimG4Core/GFlash/TB/TreeMatrixCalib.cc
  SimG4Core/GFlash/TB/TreeMatrixCalib.h
  SimG4Core/GFlash/TB/TreeProducerCalibSimul.cc
  SimG4Core/GFlash/TB/TreeProducerCalibSimul.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37305 Added ConditionalTask
  DataFormats/Provenance/interface/ProductResolverIndexHelper.h
  DataFormats/Provenance/src/ProductResolverIndexHelper.cc
  FWCore/Framework/interface/Path.h
  FWCore/Framework/interface/StreamSchedule.h
  FWCore/Framework/interface/TriggerNamesService.h
  FWCore/Framework/interface/WorkerInPath.h
  FWCore/Framework/src/Path.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/src/TriggerNamesService.cc
  FWCore/Framework/src/TriggerReport.h
  FWCore/Framework/test/BuildFile.xml
  FWCore/Framework/test/stubs/ToyAnalyzers.cc
  FWCore/Framework/test/stubs/ToyIntProducers.cc
  FWCore/Framework/test/stubs/ToyModules.cc
  FWCore/Framework/test/test_conditionaltasks_cfg.py
  FWCore/ParameterSet/python/Config.py
  FWCore/ParameterSet/python/SequenceTypes.py
  FWCore/ParameterSet/python/SequenceVisitors.py
  FWCore/Utilities/interface/path_configuration.h
  FWCore/Utilities/src/path_configuration.cc
  HLTrigger/HLTcore/src/HLTConfigData.cc
  HLTrigger/HLTcore/test/BuildFile.xml
  HLTrigger/HLTcore/test/test_catch2_HLTConfigData.cc
Labels: core-approved, hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37453 New set of files coherent with the new v1_0_0 L1Menu
  L1Trigger/Configuration/python/customiseUtils.py
  L1Trigger/L1TGlobal/python/PrescalesVetosFract_cff.py
  L1Trigger/L1TGlobal/python/PrescalesVetos_cff.py
  L1Trigger/L1TGlobal/test/runGlobalFakeInputProducer.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#37448 Phase2-hgx305 Update the hgcalcell xml files in view of foressen corrections
  Geometry/HGCalCommonData/data/hgcalcell/v15/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalcell/v15/hgcalcell.xml
  Geometry/HGCalCommonData/data/hgcalcell/v16/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalcell/v16/hgcalcell.xml
  Geometry/HGCalCommonData/data/hgcalcell/v17/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalcell/v9/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalcell/v9/hgcalcell.xml
  Geometry/HGCalCommonData/data/hgcalcell/vtest/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalcell/vtest/hgcalcell.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37479 Backport to 12_3_X for CSC unpacking update PR#37279
  EventFilter/CSCRawToDigi/interface/CSCALCTHeader.h
  EventFilter/CSCRawToDigi/interface/CSCDCCExaminer.h
  EventFilter/CSCRawToDigi/interface/CSCDigiToRaw.h
  EventFilter/CSCRawToDigi/interface/CSCEventData.h
  EventFilter/CSCRawToDigi/interface/CSCGEMData.h
  EventFilter/CSCRawToDigi/interface/CSCTMBData.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2006.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2007.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2007_rev0x50c3.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2013.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2020_CCLUT.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2020_GEM.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2020_Run2.h
  EventFilter/CSCRawToDigi/interface/CSCTMBHeader2020_TMB.h
  EventFilter/CSCRawToDigi/interface/CSCVTMBHeaderFormat.h
  EventFilter/CSCRawToDigi/plugins/CSCDCCUnpacker.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiAnalyzer.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiToPattern.cc
  EventFilter/CSCRawToDigi/plugins/CSCDigiToRawModule.cc
  EventFilter/CSCRawToDigi/plugins/CSCViewDigi.cc
  EventFilter/CSCRawToDigi/python/cscPacker_cfi.py
  EventFilter/CSCRawToDigi/python/cscUnpacker_cfi.py
  EventFilter/CSCRawToDigi/python/viewDigi_cfi.py
  EventFilter/CSCRawToDigi/src/CSCALCTHeader.cc
  EventFilter/CSCRawToDigi/src/CSCCFEBData.cc
  EventFilter/CSCRawToDigi/src/CSCDCCEventData.cc
  EventFilter/CSCRawToDigi/src/CSCDCCExaminer.cc
  EventFilter/CSCRawToDigi/src/CSCDMBHeader.cc
  EventFilter/CSCRawToDigi/src/CSCDigiToRaw.cc
  EventFilter/CSCRawToDigi/src/CSCEventData.cc
  EventFilter/CSCRawToDigi/src/CSCGEMData.cc
  EventFilter/CSCRawToDigi/src/CSCTMBData.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader2020_CCLUT.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader2020_GEM.cc
  EventFilter/CSCRawToDigi/src/CSCTMBHeader2020_TMB.cc
  EventFilter/CSCRawToDigi/test/README.md
  EventFilter/CSCRawToDigi/test/cscRawToDigiTest.cpp
  EventFilter/CSCRawToDigi/test/testCSCDigi2Raw_cfg.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37498 bugfix XML for PPS strips mapping
  CondFormats/PPSObjects/xml/mapping_tracking_strip_2022.xml
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#37463 Customize for OT inefficiency
  CondTools/SiPhase2Tracker/plugins/SiPhase2BadStripChannelBuilder.cc
  SimTracker/SiPhase2Digitizer/python/customizeForOTInefficiency.py
Labels: alca-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37472 [Backport of] HCAL: fix on HCAL TP saturation algorithm to synchronize s/w TP algorithm with f/w
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalTriggerPrimitiveAlgo.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37489 fix edm module warnings
  EventFilter/CSCTFRawToDigi/plugins/CSCTFAnalyzer.cc
  EventFilter/CSCTFRawToDigi/test/CSCTFSingleGen.cc
  EventFilter/CSCTFRawToDigi/test/CSCTFSingleGen.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37178 Add GE1/1 detection efficiency monitor using GEMCSCSegment
  DQM/GEM/interface/GEMDQMEfficiencyCalculator.h
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentClient.cc
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentClient.h
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentSource.cc
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentSource.h
  DQM/GEM/plugins/SealModule.cc
  DQM/GEM/python/gemEffByGEMCSCSegment_cff.py
  DQM/GEM/src/GEMDQMEfficiencyCalculator.cc
  DQM/GEM/test/testGEMEffByGEMCSCSegment.py
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37266 Update CLCT thresholds for hadronic showers in CSC
  L1Trigger/CSCTriggerPrimitives/python/params/showerParams.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37491 Added the switch for the inclusion of PS energy
  RecoEcal/EgammaClusterAlgos/interface/SCEnergyCorrectorSemiParm.h
  RecoEcal/EgammaClusterAlgos/src/SCEnergyCorrectorSemiParm.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#37503 Fix L1T MuonShowers for HLT
  Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py
  HLTrigger/HLTfilters/plugins/HLTL1TSeed.cc
Labels: hlt-approved, operations-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport

#37502 Fix L1T MuonShowers for HLT
  Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py
  HLTrigger/HLTfilters/plugins/HLTL1TSeed.cc
Labels: hlt-approved, operations-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37497 [Backport] New set of files coherent with the new v1_0_0 L1Menu
  L1Trigger/Configuration/python/customiseUtils.py
  L1Trigger/L1TGlobal/python/PrescalesVetosFract_cff.py
  L1Trigger/L1TGlobal/python/PrescalesVetos_cff.py
  L1Trigger/L1TGlobal/test/runGlobalFakeInputProducer.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#37485 Properly close file using fclose; fixes CS9 compilation warning
  CalibCalorimetry/EcalLaserAnalyzer/plugins/EcalABAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37499 [12_3_X] bugfix XML for PPS strips mapping
  CondFormats/PPSObjects/xml/mapping_tracking_strip_2022.xml
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#37466 Run4-hgx306 Backport the bugfix to HGCal geometry from the PR's 37330 and 37460
  Geometry/HGCalCommonData/interface/HGCalDDDConstants.h
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalGeometry/interface/HGCalGeometry.h
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
  Geometry/HGCalGeometry/test/HGCalGeometryNewCornersTest.cc
  Geometry/HGCalGeometry/test/python/testHGCalGeometryNewCorners_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, backport-ok

#37501 Add GE1/1 detection efficiency monitor using GEMCSCSegment (backport of #37178, 12_3_X)
  DQM/GEM/interface/GEMDQMEfficiencyCalculator.h
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentClient.cc
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentClient.h
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentSource.cc
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentSource.h
  DQM/GEM/plugins/SealModule.cc
  DQM/GEM/python/gemEffByGEMCSCSegment_cff.py
  DQM/GEM/src/GEMDQMEfficiencyCalculator.cc
  DQM/GEM/test/testGEMEffByGEMCSCSegment.py
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37476 Add GE1/1 detection efficiency monitor using GEMCSCSegment (backport of #37178, 12_2_X)
  DQM/GEM/interface/GEMDQMEfficiencyCalculator.h
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentClient.cc
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentClient.h
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentSource.cc
  DQM/GEM/plugins/GEMEffByGEMCSCSegmentSource.h
  DQM/GEM/plugins/SealModule.cc
  DQM/GEM/python/gemEffByGEMCSCSegment_cff.py
  DQM/GEM/src/GEMDQMEfficiencyCalculator.cc
  DQM/GEM/test/testGEMEffByGEMCSCSegment.py
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37494 [12_3_X] Added the switch for the inclusion of PS energy
  RecoEcal/EgammaClusterAlgos/interface/SCEnergyCorrectorSemiParm.h
  RecoEcal/EgammaClusterAlgos/src/SCEnergyCorrectorSemiParm.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#37504 Run3-alca222 Update some of the macros usedin calibrating HCAL with isotrack or muon
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/PlotMPV.C
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37508 Change the way to match "mg_reweighting" in production of NanoAOD MC samples
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#37519 removed deprecated HLT plugin `PFJetsMatchedToFilteredCaloJetsProducer`
  HLTrigger/JetMET/interface/PFJetsMatchedToFilteredCaloJetsProducer.h
  HLTrigger/JetMET/plugins/SealModule.cc
  HLTrigger/JetMET/src/PFJetsMatchedToFilteredCaloJetsProducer.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37387 Change prescaled dedx calculation to exclude pixels for Run3
  RecoTracker/DeDx/interface/GenericTruncatedAverageDeDxEstimator.h
  RecoTracker/DeDx/plugins/DeDxEstimatorProducer.cc
  RecoTracker/DeDx/plugins/DeDxHitInfoProducer.cc
  RecoTracker/DeDx/python/dedxEstimators_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37518 add HLT customisation for Run-2 CTPPS
  HLTrigger/Configuration/python/CustomConfigs.py
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37514 Update cmsLHEtoEOSManager.py to use python used by cmsRun
  GeneratorInterface/LHEInterface/scripts/cmsLHEtoEOSManager.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37492 SiStrip Payload Inspector: refinements to `SiStripCondObjectRepresent`
  CondCore/AlignmentPlugins/plugins/TrackerAlignment_PayloadInspector.cc
  CondCore/SiStripPlugins/BuildFile.xml
  CondCore/SiStripPlugins/interface/SiStripPayloadInspectorHelper.h
  CondCore/SiStripPlugins/plugins/SiStripApvGain_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripCondObjectRepresent.h
  CondCore/SiStripPlugins/plugins/SiStripDetVOff_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripLorentzAngle_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripNoises_PayloadInspector.cc
  CondCore/SiStripPlugins/plugins/SiStripPedestals_PayloadInspector.cc
  CondCore/SiStripPlugins/scripts/testCompare.sh
  CondTools/SiStrip/plugins/BuildFile.xml
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#37495 rename duplicated class TrackQuality
  L1Trigger/TrackFindingTracklet/plugins/L1FPGATrackProducer.cc
  L1Trigger/TrackTrigger/interface/L1TrackQuality.h
  L1Trigger/TrackTrigger/src/L1TrackQuality.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37394 Run2-gex125 Attempt to make 2017 scenario compatible with dd4hep
  Geometry/CMSCommonData/data/materials/2017/v2/materials.xml
  Geometry/DTGeometryBuilder/data/dtSpecsFilter/2017/v1/dtSpecsFilter.xml
  Geometry/EcalCommonData/data/eefixed/2017/v1/eefixed.xml
  Geometry/HcalCommonData/data/cmsExtendedGeometry2017.xml
  Geometry/HcalCommonData/data/hcalsens/2017/v1/hcalsenspmf.xml
  Geometry/HcalCommonData/python/GeometryDD4HepExtended2017Reco_cff.py
  Geometry/HcalCommonData/python/GeometryDD4HepExtended2017_cff.py
  Geometry/HcalCommonData/python/cmsExtendedGeometry2017XML_cfi.py
  Geometry/HcalCommonData/test/python/TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_10024.py
  Geometry/HcalCommonData/test/python/dump2017DD4hep_cfg.py
  Geometry/HcalCommonData/test/python/dump2017DDD_cfg.py
  Geometry/HcalCommonData/test/python/step2_DIGI_L1_DIGI2RAW_HLT_10024.py
  Geometry/HcalCommonData/test/python/step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_VALIDATION_DQM_10024.py
  Geometry/HcalSimData/data/CaloUtil/2017/v1/CaloUtil.xml
  Geometry/HcalSimData/data/HcalProdCuts/2017/v1/HcalProdCuts.xml
  Geometry/MuonCommonData/data/muonNumbering/2017/v2/muonNumbering.xml
  Geometry/TrackerCommonData/data/pixbarmaterial/2017/v1/pixbarmaterial.xml
  Geometry/TrackerCommonData/data/pixfwdMaterials/2017/v2/pixfwdMaterials.xml
  Geometry/TrackerCommonData/data/tecwheel/2017/v1/tecwheel.xml
  Geometry/TrackerCommonData/data/tibmaterial/2017/v2/tibmaterial.xml
  Geometry/TrackerCommonData/data/tibtidcommonmaterial/2017/v2/tibtidcommonmaterial.xml
  Geometry/TrackerCommonData/data/tidmaterial/2017/v2/tidmaterial.xml
  Geometry/TrackerCommonData/data/tobmaterial/2017/v2/tobmaterial.xml
  Geometry/TrackerCommonData/data/trackermaterial/2017/v2/trackermaterial.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37470 Add LHCTransport to Run3 GEN content
  GeneratorInterface/Configuration/python/GeneratorInterface_EventContent_cff.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37511 Phase2-hgx307X Change xml file in view of changed algorithms in PR's #37505 and #37510
  Geometry/ForwardCommonData/data/hfnose/v0/hfnose.xml
  Geometry/ForwardCommonData/data/hfnose/v1/hfnose.xml
  Geometry/ForwardCommonData/data/hfnose/v1a/hfnose.xml
  Geometry/ForwardCommonData/data/hfnose/v2/hfnose.xml
  Geometry/ForwardCommonData/data/hfnoseCell/v1/hfnose.xml
  Geometry/ForwardCommonData/data/hfnoseCell/v1/hfnoseCell.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37521 add HLT customisation for Run-2 CTPPS [`12_3_X`]
  HLTrigger/Configuration/python/CustomConfigs.py
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37361 Cell XY to UV conversion fo HGCal wafers
  Geometry/HGCalCommonData/interface/HGCalCellUV.h
  Geometry/HGCalCommonData/src/HGCalCellUV.cc
  Geometry/HGCalCommonData/test/HGCalCellUVTester.cc
  Geometry/HGCalCommonData/test/python/testHGCalCellUVTester_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37505 Cell correction
  Geometry/HGCalCommonData/data/hgcalcell/v17/hgcalcell.xml
  Geometry/HGCalCommonData/plugins/DDHGCalCell.cc
  Geometry/HGCalCommonData/plugins/DDHGCalWaferFullRotated.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved

#37517 Phase2-gex127M Make some protection in accessing inpu collections for MTD so that some FasTsim tests can proceed
  RecoLocalFastTime/FTLClusterizer/plugins/MTDClusterProducer.cc
  RecoLocalFastTime/FTLRecProducers/plugins/MTDRecHitProducer.cc
  RecoLocalFastTime/FTLRecProducers/plugins/MTDTrackingRecHitProducer.cc
  RecoLocalFastTime/FTLRecProducers/plugins/MTDUncalibratedRecHitProducer.cc
  SimFastTiming/FastTimingCommon/interface/MTDDigitizer.h
  SimFastTiming/FastTimingCommon/plugins/PreMixingMTDWorker.cc
Labels: reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37456 Fixes to the tauID configuration tool
  RecoTauTag/Configuration/python/tools/adaptToRunAtMiniAOD.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#37541 Link cmsRunGP with libtcmalloc.so so that heap profiling can be run.
  FWCore/Framework/bin/BuildFile.xml
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37543 [12_3_X] Update CLCT thresholds for hadronic showers
  L1Trigger/CSCTriggerPrimitives/python/params/showerParams.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37546 Simplify usage of constants in HGCalCellUV
  Geometry/HGCalCommonData/interface/HGCalCellUV.h
  Geometry/HGCalCommonData/src/HGCalCellUV.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37510 Phase2-hgx307 Update HGCal cell defintion using PR #37505
  Geometry/HGCalCommonData/data/hgcalwafer/v15/cms.xml
  Geometry/HGCalCommonData/data/hgcalwafer/v8/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalwafer/v8/hgcalpos.xml
  Geometry/HGCalCommonData/data/hgcalwafer/v8/hgcalwafer.xml
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalCell.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalWaferFullRotated.cc
  Geometry/HGCalCommonData/python/testHGCalWaferFXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalWaferPXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalWaferXML_cfi.py
  Geometry/HGCalCommonData/test/python/g4OverlapCheckWafer_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37540 Remove some dead assignments in L1Trigger/DTTriggerPhase2/src/HoughGrouping.cc
  L1Trigger/DTTriggerPhase2/src/HoughGrouping.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37545 Added exception to HepMCValidationHelper
  Validation/EventGenerator/src/HepMCValidationHelper.cc
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37535 Add import test for professor2
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, requires-external, code-checks-approved

#37531 added new Utilities/OpenSSL and move unit tests to it
  OnlineDB/SiStripO2O/plugins/BuildFile.xml
  OnlineDB/SiStripO2O/plugins/SiStripPayloadHandler.cc
  Utilities/General/test/BuildFile.xml
  Utilities/OpenSSL/BuildFile.xml
  Utilities/OpenSSL/interface/openssl_init.h
  Utilities/OpenSSL/src/openssl_init.cc
  Utilities/OpenSSL/test/BuildFile.xml
  Utilities/OpenSSL/test/test_openssl_evp_digest.cpp
  Utilities/OpenSSL/test/test_openssl_sha1.cpp
Labels: core-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#37561 mkFit update to standalone build/test scripts
  RecoTracker/MkFitCore/interface/Hit.h
  RecoTracker/MkFitCore/standalone/README_buildFromCMSSW.txt
  RecoTracker/MkFitCore/standalone/xeon_scripts/init-env.sh
  RecoTracker/MkFitCore/standalone/xeon_scripts/init-gcc10-env.sh
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37565 Change tracks to optional requirement in HLTDisplacedEgammaFilter
  HLTrigger/Egamma/plugins/HLTDisplacedEgammaFilter.cc
  HLTrigger/Egamma/plugins/HLTDisplacedEgammaFilter.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37544 Enable EMTF regional showers with unpacked info
  DQM/L1TMonitor/python/L1TStage2RegionalShower_cfi.py
  DQM/L1TMonitor/python/L1TStage2_cff.py
  DQM/L1TMonitor/python/L1TdeStage2RegionalShower_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37562 Move pixelTracksCPU module definition inside SwitchProducerCUDA
  RecoPixelVertexing/PixelTrackFitting/python/PixelTracks_cff.py
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#37575 Fix CS8/EL8/CS9 openssl build error
  Utilities/OpenSSL/interface/openssl_init.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37500 Introduce `PtMaxTrackCountFilter`
  CommonTools/RecoAlgos/plugins/PtMaxTrackCountFilter.cc
  CommonTools/RecoAlgos/plugins/PtMinTrackCountFilter.cc
  CommonTools/UtilAlgos/interface/PtMaxSelector.h
  CommonTools/Utils/interface/PtMaxSelector.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37573 Fixed dead assign
  CalibFormats/SiStripObjects/src/SiStripQuality.cc
  CalibTracker/SiStripHitEfficiency/src/HitEff.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37570 B2G HLT DQM cleanup
  DQMOffline/Trigger/python/B2GMonitoring_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37557 Add PPS and EGM tags to dataRun3 GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37509 Skim for Delayed Jets and DTClusters
  Configuration/Skimming/python/PDWG_EXODTCluster_cff.py
  Configuration/Skimming/python/PDWG_EXODelayedJet_cff.py
  Configuration/Skimming/python/Skims_PDWG_cff.py
  Configuration/Skimming/test/test_DTCluster_cfg.py
  Configuration/Skimming/test/test_DelayedJet_cfg.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#37587 modernize `SiStripPayloadMapTableCreator`
  OnlineDB/SiStripO2O/plugins/SiStripPayloadMapTableCreator.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#37555 Eta phi search in tile
  DataFormats/HGCalReco/interface/TICLLayerTile.h
  DataFormats/HGCalReco/test/BuildFile.xml
  DataFormats/HGCalReco/test/EtaPhiSearchInTile_t.cpp
  RecoLocalCalo/HGCalRecProducers/interface/HGCalLayerTiles.h
  RecoLocalCalo/HGCalRecProducers/interface/HGCalTilesConstants.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalCLUEAlgo.cc
  RecoLocalCalo/HGCalRecProducers/test/BuildFile.xml
  RecoLocalCalo/HGCalRecProducers/test/EtaPhiSearchInTile_t.cpp
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37577 Run2-gex125C Make the 2017 version to work till end of step3 for both dd4hep and ddd variants
  Geometry/HcalCommonData/data/cmsExtendedGeometry2017.xml
  Geometry/HcalCommonData/python/GeometryExtended2017Reco_cff.py
  Geometry/HcalCommonData/python/GeometryExtended2017_cff.py
  Geometry/HcalCommonData/python/cmsExtendedGeometry2017XML_cfi.py
  Geometry/HcalCommonData/test/python/TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_10024.0.py
  Geometry/HcalCommonData/test/python/TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_10024.911.py
  Geometry/HcalCommonData/test/python/step2_DIGI_L1_DIGI2RAW_HLT_10024.0.py
  Geometry/HcalCommonData/test/python/step2_DIGI_L1_DIGI2RAW_HLT_10024.911.py
  Geometry/HcalCommonData/test/python/step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_VALIDATION_DQM_10024.0.py
  Geometry/HcalCommonData/test/python/step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_VALIDATION_DQM_10024.911.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37558 [123X] Add PPS and EGM tags to dataRun3 GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37539 Add HFJetCleaner module for HLT
  HLTrigger/JetMET/plugins/HLTJetHFCleaner.h
  HLTrigger/JetMET/plugins/SealModule.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37589 Better Tau failure messages
  PhysicsTools/HepMCCandAlgos/interface/GenParticlesHelper.h
  PhysicsTools/HepMCCandAlgos/src/GenParticlesHelper.cc
  PhysicsTools/JetMCAlgos/plugins/TauGenJetProducer.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#37568 Fixing missing Buildfile dependencies on hepmc
  FastSimulation/SimplifiedGeometryPropagator/BuildFile.xml
  Fireworks/Core/BuildFile.xml
  GeneratorInterface/AMPTInterface/BuildFile.xml
  GeneratorInterface/BeamHaloGenerator/BuildFile.xml
  GeneratorInterface/Core/BuildFile.xml
  GeneratorInterface/CosmicMuonGenerator/BuildFile.xml
  GeneratorInterface/ExhumeInterface/BuildFile.xml
  GeneratorInterface/Herwig6Interface/BuildFile.xml
  GeneratorInterface/HijingInterface/BuildFile.xml
  GeneratorInterface/Hydjet2Interface/BuildFile.xml
  GeneratorInterface/HydjetInterface/BuildFile.xml
  GeneratorInterface/PartonShowerVeto/BuildFile.xml
  GeneratorInterface/PomwigInterface/BuildFile.xml
  GeneratorInterface/PyquenInterface/BuildFile.xml
  GeneratorInterface/Pythia6Interface/BuildFile.xml
  GeneratorInterface/ReggeGribovPartonMCInterface/BuildFile.xml
  HLTriggerOffline/Egamma/BuildFile.xml
  IOMC/EventVertexGenerators/BuildFile.xml
Labels: dqm-approved, fastsim-approved, generators-approved, visualization-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37582 Fix typo in L1T prescales files
  L1Trigger/L1TGlobal/python/PrescalesVetosFract_cff.py
  L1Trigger/L1TGlobal/python/PrescalesVetos_cff.py
Labels: l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#37574 feat: update TopMuEG skim to latest HLT paths in BTV
  DPGAnalysis/Skims/python/TopMuEGSkim_cff.py
  DPGAnalysis/Skims/test/test_TopMuEG_SKIM.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#37309 mpiCudaGeneric is a program transfer data from a machine to another with GPU using MPI and CUDA.
  HeterogeneousCore/CUDACore/test/BuildFile.xml
  HeterogeneousCore/CUDACore/test/mpiCudaGeneric.cu
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#37576 Phase2 digitizer updated to exclude badchannel in Strip like detectors
  SimTracker/SiPhase2Digitizer/plugins/PSPDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PSPDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PSSDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PSSDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/SSDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/SSDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#37578 [OT inefficiency] add 0% bad strip scenario to customization function and generate new RelVal workflows
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  SimTracker/SiPhase2Digitizer/python/customizeForOTInefficiency.py
Labels: simulation-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, requires-external, code-checks-approved

#37591 Better exception messages from ROOT delayed reading
  FWCore/Integration/test/DelayedReaderThrowingSource.cc
  IOPool/Input/src/RootDelayedReader.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37607 Disable fork handler in XrootD
  Utilities/XrdAdaptor/plugins/XrdStorageMaker.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#37605 Updates to the MPIService
  HeterogeneousCore/MPIServices/BuildFile.xml
  HeterogeneousCore/MPIServices/interface/MPIService.h
  HeterogeneousCore/MPIServices/plugins/BuildFile.xml
  HeterogeneousCore/MPIServices/plugins/MPIService.cc
  HeterogeneousCore/MPIServices/src/MPIService.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#37583 [12_3_X] Fix typo in L1T prescales files
  L1Trigger/L1TGlobal/python/PrescalesVetosFract_cff.py
  L1Trigger/L1TGlobal/python/PrescalesVetos_cff.py
Labels: l1-pending, pending-signatures, tests-approved, bug-fix, orp-approved, urgent, backport-ok

#37547 Phase2-hgx308 Add the new conversion code of Flat file to XML
  Geometry/HGCalCommonData/interface/HGCalCell.h
  Geometry/HGCalCommonData/interface/HGCalProperty.h
  Geometry/HGCalCommonData/interface/HGCalTypes.h
  Geometry/HGCalCommonData/src/HGCalProperty.cc
  Geometry/HGCalCommonData/test/HGCalConvert.cpp
  Validation/HGCalValidation/plugins/HGCalWaferValidation.cc
Labels: dqm-approved, geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37566 Phase2-hgx308X Avoid compilation warnings in L1Trigger/L1THGCal
  L1Trigger/L1CaloTrigger/test/ntuples/L1TriggerNtupleTrackTrigger.cc
  L1Trigger/L1THGCal/interface/HGCalTriggerTools.h
  L1Trigger/L1THGCal/src/HGCalTriggerTools.cc
  L1Trigger/L1THGCal/src/backend/HGCalClusteringImpl.cc
  L1Trigger/L1THGCal/test/HGCalTriggerGeomTesterV9Imp2.cc
  L1Trigger/L1THGCal/test/HGCalTriggerGeomTesterV9Imp3.cc
  Validation/HGCalValidation/plugins/HGCalTriggerValidator.cc
  Validation/HGCalValidation/src/classes.h
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37604 Phase2-hgx309 Add possibility of adding shift due to cassette positioning
  Geometry/HGCalCommonData/interface/HGCalCassette.h
  Geometry/HGCalCommonData/interface/HGCalGeometryMode.h
  Geometry/HGCalCommonData/src/HGCalCassette.cc
  Geometry/HGCalCommonData/src/HGCalGeometryMode.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37606 add HLT-EGM customisation for 2018 Data
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#37324 Add HLT75e33 step to Phase-2 workflows
  Configuration/PyReleaseValidation/README.md
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved

#37187 Add generator hepmc3 products
  SimDataFormats/GeneratorProducts/BuildFile.xml
  SimDataFormats/GeneratorProducts/interface/GenEventInfoProduct3.h
  SimDataFormats/GeneratorProducts/interface/HepMC3Product.h
  SimDataFormats/GeneratorProducts/src/GenEventInfoProduct3.cc
  SimDataFormats/GeneratorProducts/src/HepMC3Product.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37609 Move framework test modules away from legacy types
  FWCore/Framework/test/edproducer_productregistry_callback.cc
  FWCore/Framework/test/maker2_t.cppunit.cc
  FWCore/Framework/test/stubs/TestBeginEndJobAnalyzer.h
  FWCore/Framework/test/stubs/TestFailuresAnalyzer.cc
  FWCore/Framework/test/stubs/TestFailuresAnalyzer.h
  FWCore/Integration/test/HierarchicalEDProducer.cc
  FWCore/Integration/test/HierarchicalEDProducer.h
  FWCore/Integration/test/ProdigalAnalyzer.cc
  FWCore/Integration/test/ProdigalAnalyzer.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37537 HCalDQM: Fix for issue #37486 collection tag correction
  DQM/HcalTasks/python/OfflineSourceSequence_pp.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37533 Simplify `VVIObjF` object so it takes `kappa` only in the constructor
  RecoLocalTracker/SiPixelRecHits/interface/VVIObjF.h
  RecoLocalTracker/SiPixelRecHits/src/SiPixelTemplateReco.cc
  RecoLocalTracker/SiPixelRecHits/src/SiPixelTemplateReco2D.cc
  RecoLocalTracker/SiPixelRecHits/src/SiPixelTemplateSplit.cc
  RecoLocalTracker/SiPixelRecHits/src/VVIObjF.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, performance-improvements

#37626 add HLT-EGM customisation for 2018 Data [`12_3_X`]
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37610 Remove Configuration/Generator/data/download.url
  Configuration/Generator/data/download.url
Labels: generators-approved, fully-signed, tests-approved, orp-approved

#37608 Disable fork handler in XrootD [12_3]
  Utilities/XrdAdaptor/plugins/XrdStorageMaker.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#37627 Add new scenario for ECAL ALCANANO and update the unit test
  Configuration/DataProcessing/python/Impl/AlCaPhiSymEcal_Nano.py
  Configuration/DataProcessing/test/run_CfgTest.sh
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#37631 get rid of more deprecation warnings in `OnlineDB`
  OnlineDB/SiStripConfigDb/test/plugins/module.cc
  OnlineDB/SiStripConfigDb/test/plugins/testSiStripConfigDb.cc
  OnlineDB/SiStripConfigDb/test/plugins/testSiStripConfigDb.h
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#37613 fix the cms EDModule type of `GenParticleMatchMerger`
  SimTracker/TrackAssociation/python/allTrackMCMatch_cfi.py
  SimTracker/TrackAssociation/python/globalMuonsMCMatch_cfi.py
  SimTracker/TrackAssociation/python/standAloneMuonsMCMatch_cfi.py
  SimTracker/TrackAssociation/python/trackMCMatch_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37634 small fix to enable CSC unpacker in L1T DQM sequence
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#37625 [12_3_X] Change regTrainedWithPS to true and update EGM HLT supercluster regression tags for Run 3 in MC
  Configuration/AlCa/python/autoCond.py
  RecoEcal/EgammaClusterAlgos/src/SCEnergyCorrectorSemiParm.cc
Labels: alca-approved, hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37638 Use a time window when comparing results for stall graph
  FWCore/Concurrency/scripts/edmStreamStallGrapher.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37571 LogVerbatim to LogDebug for GE0SegAlgoRU
  RecoLocalMuon/GEMSegment/plugins/GE0SegAlgoRU.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, performance-improvements

#37643 Run3-gex130 Add debug statement which heps in adding new geometries
  Fireworks/Geometry/plugins/TGeoMgrFromDdd.cc
Labels: visualization-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37621 Update track analysers used for Alignment input data inspection
  Alignment/OfflineValidation/plugins/DMRChecker.cc
  Alignment/OfflineValidation/plugins/GeneralPurposeTrackAnalyzer.cc
  Alignment/OfflineValidation/test/BuildFile.xml
  Alignment/OfflineValidation/test/inspectData_cfg.py
  Alignment/OfflineValidation/test/testTrackAnalyzers.cc
  Alignment/OfflineValidation/test/test_all.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#37581 Add min pT filter in mkFit iterations during track building
  RecoTracker/IterativeTracking/python/DetachedQuadStep_cff.py
  RecoTracker/IterativeTracking/python/DetachedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/HighPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/InitialStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtQuadStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/MixedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/IterativeTracking/python/TobTecStep_cff.py
  RecoTracker/MkFit/plugins/MkFitIterationConfigESProducer.cc
  RecoTracker/MkFitCore/interface/IterationConfig.h
  RecoTracker/MkFitCore/src/MkBuilder.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#37641 [10.6.X] fix the cms EDModule type of `GenParticleMatchMerger`
  SimTracker/TrackAssociation/python/allTrackMCMatch_cfi.py
  SimTracker/TrackAssociation/python/globalMuonsMCMatch_cfi.py
  SimTracker/TrackAssociation/python/standAloneMuonsMCMatch_cfi.py
  SimTracker/TrackAssociation/python/trackMCMatch_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok
