Repository cms-sw/cmssw, pull requests merged in 2022-12, with the labels that each got.

#40194 [ANALYSIS] [LLVM14] Apply code checks
  CommonTools/RecoUtils/src/PF_PU_AssoMapAlgos.cc
  DPGAnalysis/SiStripTools/plugins/APVShotsAnalyzer.cc
  DPGAnalysis/SiStripTools/plugins/APVShotsFilter.cc
  PhysicsTools/JetMCAlgos/plugins/GenHFHadronMatcher.cc
  PhysicsTools/JetMCAlgos/plugins/JetFlavourClustering.cc
  PhysicsTools/PatExamples/src/AnalysisTasksAnalyzerBTag.cc
  TopQuarkAnalysis/TopKinFitter/interface/TtSemiLepKinFitter.h
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#40185 [SIMULATION] [LLVM14] Apply code checks
  SimGeneral/MixingModule/plugins/TestMix.cc
  SimMuon/Neutron/src/AsciiNeutronWriter.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40206 Fix for TTRHBuilders with PixelCPEFast
  RecoTracker/TransientTrackingRecHit/python/TTRHBuilders_cff.py
Labels: reconstruction-pending, pending-signatures, tests-approved, bug-fix, orp-approved, urgent, requires-external, code-checks-approved

#40166 Add missing dependence on DataFormats/MuonReco to RecoLocalMuon/GEMCSCSegment/test/BuildFile.xml
  RecoLocalMuon/GEMCSCSegment/test/BuildFile.xml
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#40199 [VISUALIZATION] [LLVM14] Apply code checks
  Fireworks/Core/src/FWEveViewManager.cc
  Fireworks/ParticleFlow/plugins/FWPFPatJet3DProxyBuilder.cc
  Fireworks/ParticleFlow/plugins/FWPFPatJetLegoProxyBuilder.cc
Labels: visualization-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40169 NanoDQM: remove consumesMany, plot bits in bitsets
  PhysicsTools/NanoAOD/plugins/NanoAODDQM.cc
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nanoDQM_tools_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#40207 provide a record for `cond::BasicPayload`
  CondCore/BasicCondPlugins/BuildFile.xml
  CondCore/BasicCondPlugins/src/plugin.cc
  CondFormats/Common/src/T_EventSetup_BasicPayload.cc
  CondFormats/DataRecord/interface/BasicPayloadRcd.h
  CondFormats/DataRecord/src/BasicPayloadRcd.cc
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#40184 [12_6_X] update input dataset and fix step
  Configuration/PyReleaseValidation/python/relval_nano.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, backport, upgrade-approved

#40195 [DB] [LLVM14] Apply code checks
  CondCore/PhysicsToolsPlugins/interface/DropBoxMetaDataPayloadInspectorHelper.h
  CondCore/SiPixelPlugins/plugins/SiPixelDynamicInefficiency_PayloadInspector.cc
  CondFormats/JetMETObjects/src/FactorizedJetCorrectorCalculator.cc
  CondTools/SiStrip/plugins/SiStripBadChannelPatcher.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#39847 JetCorrector migration in DQM/Physics
  DQM/Physics/interface/TopDQMHelpers.h
  DQM/Physics/src/SingleTopTChannelLeptonDQM.cc
  DQM/Physics/src/SingleTopTChannelLeptonDQM.h
  DQM/Physics/src/SingleTopTChannelLeptonDQM_miniAOD.cc
  DQM/Physics/src/SingleTopTChannelLeptonDQM_miniAOD.h
  DQM/Physics/src/TopDiLeptonOfflineDQM.cc
  DQM/Physics/src/TopDiLeptonOfflineDQM.h
  DQM/Physics/src/TopSingleLeptonDQM.cc
  DQM/Physics/src/TopSingleLeptonDQM.h
  DQM/Physics/src/TopSingleLeptonDQM_miniAOD.cc
  DQM/Physics/src/TopSingleLeptonDQM_miniAOD.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40193 [ALCA] [LLVM14] Apply code checks
  Alignment/CocoaModel/src/EntryMgr.cc
  Alignment/CocoaModel/src/Model.cc
  Alignment/CommonAlignmentAlgorithm/src/TkModuleGroupSelector.cc
  Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorMuonResiduals.cc
  Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorTemplate.cc
  Alignment/CommonAlignmentParametrization/src/CompositeAlignmentParameters.cc
  Alignment/CommonAlignmentProducer/plugins/AlignmentMuonHIPTrajectorySelector.cc
  Alignment/LaserAlignment/plugins/TkLasBeamFitter.cc
  Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc
  Alignment/MuonAlignmentAlgorithms/src/MuonResidualsFromTrack.cc
  Alignment/OfflineValidation/plugins/EopElecTreeWriter.cc
  Alignment/OfflineValidation/plugins/JetHTAnalyzer.cc
  Alignment/OfflineValidation/plugins/SplitVertexResolution.cc
  CalibFormats/SiPixelObjects/src/PixelCalibConfiguration.cc
  Calibration/EcalAlCaRecoProducers/plugins/SelectedElectronFEDListProducer.cc
  Calibration/HcalIsolatedTrackReco/plugins/SiStripRegFEDSelector.cc
  Calibration/IsolatedParticles/plugins/IsolatedTracksNxN.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40186 [DQM] [LLVM14] Apply code checks
  DQM/EcalPreshowerMonitorModule/src/ESFEDIntegrityTask.cc
  DQM/EcalPreshowerMonitorModule/src/ESIntegrityTask.cc
  DQM/EcalPreshowerMonitorModule/src/ESRawDataTask.cc
  DQM/EcalPreshowerMonitorModule/src/ESTrendTask.cc
  DQM/L1TMonitorClient/src/L1TOccupancyClientHistogramService.cc
  DQM/Physics/src/SingleTopTChannelLeptonDQM_miniAOD.cc
  DQM/Physics/src/TopSingleLeptonDQM_miniAOD.cc
  DQM/RPCMonitorDigi/src/RPCMonitorDigi.cc
  DQM/SiStripMonitorClient/src/SiStripHistoPlotter.cc
  DQM/SiStripMonitorHardware/src/SiStripSpyDisplayModule.cc
  DQM/TrackingMonitorClient/src/TrackingUtility.cc
  DQMOffline/RecoB/plugins/MiniAODTaggerAnalyzer.cc
  DQMOffline/Trigger/plugins/HLTMuonOfflineAnalyzer.cc
  HLTriggerOffline/Exotica/src/HLTExoticaSubAnalysis.cc
  HLTriggerOffline/Higgs/plugins/HLTHiggsSubAnalysis.cc
  HLTriggerOffline/Muon/src/HLTMuonValidator.cc
  Validation/CSCRecHits/src/CSCRecHitMatcher.cc
  Validation/HGCalValidation/plugins/HGCalBHValidation.cc
  Validation/MtdValidation/plugins/MtdTracksValidation.cc
  Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc
  Validation/RecoEgamma/plugins/PhotonValidator.cc
  Validation/RecoEgamma/plugins/TkConvValidator.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40187 [DQM-L1] [LLVM14] Apply code checks
  DQMOffline/L1Trigger/src/L1TCommon.cc
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40190 [ALCA-L1] [LLVM14] Apply code checks
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
Labels: alca-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40196 [L1] [LLVM14] Apply code checks
  L1Trigger/L1TCalorimeter/src/JetCalibrationMethods.cc
  L1Trigger/L1TCalorimeter/src/PUSubtractionMethods.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanRegionModule.cc
  L1Trigger/TrackFindingTMTT/src/DupFitTrkKiller.cc
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTrigPrimAnalyzer.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40165 HCAL: Remove the MIP fine grain bit logic from the HCAL endcap
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
Labels: alca-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40172 Adding "hcal2" DQM to "rerecoCommon" in autoDQM.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, hcal

#40117 HcalDQM: Add protection to collection non-exist case for GPUTask
  DQM/HcalTasks/plugins/DigiTask.cc
  DQM/HcalTasks/plugins/HcalGPUComparisonTask.cc
  DQM/Integration/python/clients/hcalgpu_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, hcal

#40179 Make two function-static variables const
  FWCore/Framework/src/DataProxy.cc
  FWCore/Framework/src/ExceptionActions.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40216 Update SiPixel bad components in Run 3 MC GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40139 JetCorrector migration in DiJetAnalyzer, GammaJetAnalysis
  Calibration/HcalCalibAlgos/python/diJetAnalyzer_cfi.py
  Calibration/HcalCalibAlgos/python/gammaJetAnalysis_cfi.py
  Calibration/HcalCalibAlgos/test/DiJetAnalyzer.cc
  Calibration/HcalCalibAlgos/test/GammaJetAnalysis.cc
  Calibration/HcalCalibAlgos/test/python/dijetanalysis_cfg.py
  Calibration/HcalCalibAlgos/test/python/dijetanalyzer_cfg.py
  Calibration/HcalCalibAlgos/test/python/gammaJetAnalysis_cfg.py
  Calibration/HcalCalibAlgos/test/python/gammaJetAnalysis_data2012_cfg.py
  Calibration/HcalCalibAlgos/test/python/gammaJetAnalysis_data2012_noGJetProd_cfg.py
  Calibration/HcalCalibAlgos/test/python/gammaJetAnalysis_noGJetProd_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39019 [12_4_X] Update Run3 MC GTs + swap update Vertex smearing + update offline Run3 GTs
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  EventFilter/CSCRawToDigi/test/testPackingUnpackingPreTriggers_cfg.py
  Geometry/CMSCommonData/test/run3.py
  Geometry/HcalCommonData/test/python/testPhase1_cfg.py
  Geometry/HcalCommonData/test/python/testPhase2_cfg.py
  Geometry/TrackerCommonData/test/python/run21.py
  Geometry/TrackerCommonData/test/python/run21Zero.py
  Geometry/TrackerCommonData/test/python/run21flat.py
  Geometry/VeryForwardData/test/testRun3_cfg.py
  SimG4CMS/Calo/test/python/dd4hep_SingleMuon_Step1_cfg.py
  SimG4CMS/Calo/test/python/ddd_SingleMuon_Step1_cfg.py
  SimG4CMS/Calo/test/python/runHF6_cfg.py
  SimG4CMS/Calo/test/python/runHFDD4HEP_cfg.py
  SimG4CMS/Calo/test/python/runHFDDD_cfg.py
  SimG4CMS/ShowerLibraryProducer/test/python/runHFShowerAnalyzer_cfg.py
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step1_cfg.py
Labels: alca-approved, geometry-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, requires-external

#40228 HCAL: Modifications to the LUT validation script
  CaloOnlineTools/HcalOnlineDb/bin/hcalLUT.cc
  CaloOnlineTools/HcalOnlineDb/test/genLUT.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#40168 Phase2-hgx332 Add debug tools to investigate shortcomings of V16/V17 geometries of HGCal
  Geometry/HGCalCommonData/data/cellIDHEF.txt
  Geometry/HGCalCommonData/python/hgcalWaferIDTester_cff.py
  Geometry/HGCalCommonData/test/HGCalWaferIDTester.cc
  Geometry/HGCalCommonData/test/python/testHGCalWaferID_cfg.py
  SimG4CMS/Calo/interface/HGCScintSD.h
  SimG4CMS/Calo/interface/HGCalSD.h
  SimG4CMS/Calo/plugins/HGCalTestPartialWaferHits.cc
  SimG4CMS/Calo/python/hgcalHitPartial_cff.py
  SimG4CMS/Calo/src/HGCScintSD.cc
  SimG4CMS/Calo/src/HGCalSD.cc
  SimG4Core/Application/python/g4SimHits_cfi.py
  Validation/HGCalValidation/scripts/testHGCalReco_cfg.py
  Validation/HGCalValidation/scripts/testHGCalSimSingleMuonPt100_cfg.py
  Validation/HGCalValidation/test/HGCMissingRecHit.cc
Labels: dqm-approved, geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, hgcal

#40106 short names for matrix workflows
  Configuration/PyReleaseValidation/python/MatrixReader.py
  Configuration/PyReleaseValidation/python/WorkFlow.py
  Configuration/PyReleaseValidation/python/WorkFlowRunner.py
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/relval_nano.py
  Configuration/PyReleaseValidation/python/relval_premix.py
  Configuration/PyReleaseValidation/python/relval_standard.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved

#40229 [106X] Rename modifier run2_final_state_rad
  Configuration/ProcessModifiers/python/run2_final_state_rad_cff.py
  SimG4Core/Application/python/g4SimHits_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved

#40209 Nano: restore Run2/3 consistency between electron/photon IDs; remove scale+smearing correction for Run3
  Configuration/Eras/python/Era_Run3_cff.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_eras_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, egamma

#40181 Clean unused dependencies from BuildFiles
  Calibration/EcalCalibAlgos/plugins/BuildFile.xml
  CondCore/PCLConfigPlugins/BuildFile.xml
  DQM/CTPPS/BuildFile.xml
  DQM/CTPPS/plugins/BuildFile.xml
  DQMOffline/CalibTracker/plugins/BuildFile.xml
  DQMOffline/EGamma/BuildFile.xml
  DQMOffline/EGamma/plugins/BuildFile.xml
  DQMOffline/JetMET/BuildFile.xml
  DataFormats/L1TParticleFlow/BuildFile.xml
  HLTrigger/HLTfilters/plugins/BuildFile.xml
  JetMETCorrections/TauJet/BuildFile.xml
  L1Trigger/L1TTrackMatch/BuildFile.xml
  L1Trigger/L1TTrackMatch/plugins/BuildFile.xml
  L1Trigger/Phase2L1GMT/BuildFile.xml
  L1Trigger/TrackFindingTracklet/plugins/BuildFile.xml
  L1Trigger/TrackFindingTracklet/test/BuildFile.xml
  L1Trigger/TrackTrigger/BuildFile.xml
  L1Trigger/TrackTrigger/plugins/BuildFile.xml
  L1Trigger/TrackerDTC/BuildFile.xml
  L1Trigger/TrackerDTC/test/BuildFile.xml
  L1Trigger/TrackerTFP/BuildFile.xml
  L1Trigger/TrackerTFP/test/BuildFile.xml
  PhysicsTools/NanoAOD/BuildFile.xml
  RecoEgamma/EgammaTools/BuildFile.xml
  RecoLocalMuon/GEMRecHit/test/BuildFile.xml
  RecoLocalMuon/GEMSegment/test/BuildFile.xml
  RecoMET/METPUSubtraction/plugins/BuildFile.xml
  RecoTauTag/HLTProducers/BuildFile.xml
  RecoTracker/TransientTrackingRecHit/BuildFile.xml
  Validation/HGCalValidation/plugins/BuildFile.xml
  Validation/HLTrigger/BuildFile.xml
  Validation/HLTrigger/plugins/BuildFile.xml
Labels: analysis-pending, alca-approved, dqm-approved, hlt-approved, l1-approved, reconstruction-approved, pending-signatures, tests-approved, db-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved

#40197 [RECONSTRUCTION-UPGRADE] [LLVM14] Apply code checks
  RecoHGCal/TICL/plugins/PFTICLProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#40189 [RECONSTRUCTION] [LLVM14] Apply code checks
  JetMETCorrections/Modules/plugins/JetResolutionDemo.cc
  MagneticField/ParametrizedEngine/src/poly2d_base.cc
  PhysicsTools/SelectorUtils/interface/VersionedSelector.h
  RecoBTag/SecondaryVertex/plugins/TemplatedSecondaryVertexProducer.cc
  RecoEcal/EgammaClusterProducers/src/EcalDigiSelector.cc
  RecoEcal/EgammaClusterProducers/src/HybridClusterProducer.cc
  RecoEcal/EgammaClusterProducers/src/UncleanSCRecoveryProducer.cc
  RecoEcal/EgammaClusterProducers/src/UnifiedSCCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/ParticleBasedIsoProducer.cc
  RecoEgamma/EgammaMCTools/src/ElectronMCTruthFinder.cc
  RecoEgamma/EgammaMCTools/src/PhotonMCTruthFinder.cc
  RecoEgamma/EgammaMCTools/src/PizeroMCTruthFinder.cc
  RecoHI/HiTracking/plugins/HIMultiTrackSelector.cc
  RecoJets/JetAlgorithms/src/HEPTopTaggerV2.cc
  RecoJets/JetAnalyzers/src/myFastSimVal.cc
  RecoJets/JetProducers/plugins/QjetsAdder.cc
  RecoJets/JetProducers/src/PileupJetIdAlgo.cc
  RecoLocalMuon/DTSegment/src/DTSegment4DT0Corrector.cc
  RecoLocalMuon/DTSegment/src/DTSegmentUpdator.cc
  RecoLuminosity/LumiProducer/src/NormDML.cc
  RecoMET/METAlgorithms/src/MuonMETAlgo.cc
  RecoMET/METProducers/src/HcalNoiseInfoProducer.cc
  RecoMuon/CosmicMuonProducer/src/CosmicMuonSmoother.cc
  RecoMuon/MuonSeedGenerator/src/MuonSeedOrcaPatternRecognition.cc
  RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporter.cc
  RecoTauTag/RecoTau/interface/RecoTauCommonUtilities.h
  RecoTracker/DeDx/interface/TruncatedAverageDeDxEstimator.h
  RecoTracker/FinalTrackSelectors/plugins/MultiTrackSelector.cc
  RecoTracker/NuclearSeedGenerator/plugins/NuclearTrackCorrector.cc
  RecoTracker/SpecialSeedGenerators/src/CtfSpecialSeedGenerator.cc
  TrackingTools/GsfTools/interface/MultiGaussianStateCombiner.icc
  TrackingTools/GsfTools/src/MultiGaussianStateCombiner1D.cc
  TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc
  TrackingTools/PatternTools/src/TempTrajectory.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40224 [12_6_X] Nano: restore Run2/3 consistency between electron/photon IDs; remove scale+smearing correction for Run3
  Configuration/Eras/python/Era_Run3_cff.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_eras_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved, egamma

#40222 minor improvements to `Alignment/OfflineValidation`
  Alignment/CommonAlignment/python/tools/trackselectionRefitting.py
  Alignment/OfflineValidation/bin/exceptions.h
  Alignment/OfflineValidation/bin/jetHtPlotter.cc
  Alignment/OfflineValidation/interface/PlotAlignmentValidation.h
  Alignment/OfflineValidation/plugins/DMRChecker.cc
  Alignment/OfflineValidation/plugins/GeneralPurposeTrackAnalyzer.cc
  Alignment/OfflineValidation/plugins/JetHTAnalyzer.cc
  Alignment/OfflineValidation/src/PlotAlignmentValidation.cc
  Alignment/OfflineValidation/src/PreparePVTrends.cc
  Alignment/OfflineValidation/test/PVValidation_TEMPL_cfg.py
  Alignment/OfflineValidation/test/PVValidation_T_cfg.py
  Alignment/OfflineValidation/test/PrimaryVertexResolution_templ_cfg.py
  Alignment/OfflineValidation/test/testTrackAnalyzers.cc
  Alignment/OfflineValidation/test/test_all_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40133 Revived being able to run modules inside a mixing module
  FWCore/ServiceRegistry/interface/ServiceRegistry.h
  FWCore/ServiceRegistry/interface/ServicesManager.h
  IOMC/RandomEngine/interface/cloneEngine.h
  IOMC/RandomEngine/plugins/BuildFile.xml
  IOMC/RandomEngine/plugins/Module.cc
  IOMC/RandomEngine/plugins/RandomEngineStateProducer.cc
  IOMC/RandomEngine/plugins/RandomEngineStateProducer.h
  IOMC/RandomEngine/plugins/RandomFilter.cc
  IOMC/RandomEngine/plugins/RandomFilter.h
  IOMC/RandomEngine/plugins/RandomNumberGeneratorService.cc
  IOMC/RandomEngine/plugins/RandomNumberGeneratorService.h
  IOMC/RandomEngine/src/cloneEngine.cc
  Mixing/Base/BuildFile.xml
  Mixing/Base/interface/BMixingModule.h
  Mixing/Base/interface/PileUp.h
  Mixing/Base/src/BMixingModule.cc
  Mixing/Base/src/PileUp.cc
  Mixing/Base/src/PileupRandomNumberGenerator.cc
  Mixing/Base/src/PileupRandomNumberGenerator.h
  Mixing/Base/src/SecondaryEventProvider.cc
  SimGeneral/MixingModule/plugins/MixingModule.cc
Labels: core-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40160 Phase2-hgx331 Transfer HGCal TB related stuff to Geometry/HGCalTestBeam and modify these accordingly
  Geometry/HGCalTBCommonData/data/hgcalMaterial/v1/hgcalMaterial.xml
  Geometry/HGCalTBCommonData/data/hgcalMaterial/v2/hgcalMaterial.xml
  Geometry/HGCalTBCommonData/data/hgcalwafer/v7/hgcal.xml
  Geometry/HGCalTBCommonData/data/hgcalwafer/v7/hgcalpos.xml
  Geometry/HGCalTBCommonData/data/hgcalwafer/v7/hgcalwafer.xml
  SimG4CMS/HGCalTestBeam/python/HGCalTB160Module16XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB160Module4XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB160XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB161Module1XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB161Module8V2XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB161Module8XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB161TimingLayerXML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB170FH6SqueezeXML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB170FH6XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB170JulyXML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB170SepXML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB170ShiftedXML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB170XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB180A12XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB180A16XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB180A20XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB180A22XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB181JuneXML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB181Oct0XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB181Oct1PC1mmXML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB181Oct1XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB181Oct2XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB181Oct3XML_cfi.py
  SimG4CMS/HGCalTestBeam/python/HGCalTB181Oct4XML_cfi.py
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#40188 [GEOMETRY-UPGRADE] [LLVM14] Apply code checks
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromCondDB.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#40215 Avoid CPE Fast ES Producers Renaming
  RecoLocalTracker/SiPixelRecHits/python/PixelCPEESProducers_cff.py
  RecoTracker/TransientTrackingRecHit/python/TTRHBuilders_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, requires-external, code-checks-approved, trk

#40227 Run-sim137 Correct the code in the analysis code of Simulation
  SimG4CMS/Calo/plugins/CaloSimHitStudy.cc
  SimG4CMS/Calo/src/HCalSD.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40232 [JMENanoAOD] Setup DQM and increase precision of PileUp ID & QGL input variables
  DQMOffline/Configuration/python/DQMOfflineMC_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Configuration/python/autoDQM.py
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/NanoAOD/python/nanojmeDQM_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#40162 Nano: fix and additions to collection matching, remove cross-cleaning
  PhysicsTools/NanoAOD/python/boostedTaus_cff.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_CHS_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_Puppi_cff.py
  PhysicsTools/NanoAOD/python/lowPtElectrons_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/vertices_cff.py
  PhysicsTools/PatAlgos/plugins/PATObjectCrossLinker.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#40208 Phase2-hgx333 Bug fix for invalid DetID declaration for SimHits n V16/V17 geometry versions of HGCal
  Geometry/HGCalCommonData/interface/HGCalTypes.h
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalCommonData/src/HGCalWaferMask.cc
Labels: geometry-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#40240 [12_4_X] Backport of adding "hcal2" DQM to "rerecoCommon" in autoDQM.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#40213 [12_6_X] Add missing dependence on DataFormats/MuonReco
  RecoLocalMuon/GEMCSCSegment/test/BuildFile.xml
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#40217 [12_6_X] Backport of adding "hcal2" DQM to "rerecoCommon" in autoDQM.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, hcal

#40233 Update of HLT-specific MC GT for frozen "V1.4" HLT menu to "postEE" scenario [`12_4_X` only]
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved

#40238 revert change of vertex smearing for 2022 HI , 2023 and 2024 relvals
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, upgrade-approved

#40252 Updated Geant4 user actions
  SimG4Core/Application/interface/StackingAction.h
  SimG4Core/Application/src/StackingAction.cc
  SimG4Core/Application/src/SteppingAction.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40246 Phase2-hgx333A Modify the test code to spot the issue for V17 Geometry of HGCal
  Geometry/HGCalCommonData/data/cellIDHEF.txt
  Geometry/HGCalCommonData/python/hgcalWaferIDTester_cff.py
  Geometry/HGCalCommonData/test/HGCalWaferIDTester.cc
  Geometry/HGCalCommonData/test/python/testHGCalWaferID_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#40100 Add Run 3 muon process using proper DNN b-tagger
  PhysicsTools/PatAlgos/python/producersLayer1/displacedMuonProducer_cff.py
  PhysicsTools/PatAlgos/python/producersLayer1/muonProducer_cfi.py
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#40210 [LTO] Add default initialization to fix LTO build warnings
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEGenericBase.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40119 HcalDQM: Add protection to collection non-exist case for GPUTask, backport of PR #40117
  DQM/HcalTasks/plugins/DigiTask.cc
  DQM/HcalTasks/plugins/HcalGPUComparisonTask.cc
  DQM/Integration/python/clients/hcalgpu_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, hcal

#40118 HcalDQM: Add protection to collection non-exist case for GPUTask, backport of PR #40117
  DQM/HcalTasks/plugins/DigiTask.cc
  DQM/HcalTasks/plugins/HcalGPUComparisonTask.cc
  DQM/Integration/python/clients/hcalgpu_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, hcal

#40225 FakeHistos V1 : plugins part
  Validation/RecoEgamma/plugins/ElectronMcFakePostValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcFakeValidator.h
  Validation/RecoEgamma/python/ElectronMcFakeValidator_gedGsfElectrons_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40230 Electron MVA-based ID for Run3 from EGamma POG
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py
  RecoEgamma/ElectronIdentification/data/ElectronIDVariablesRun3.txt
  RecoEgamma/ElectronIdentification/python/ElectronMVAValueMapProducer_cfi.py
  RecoEgamma/ElectronIdentification/python/FWLite.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_RunIIIWinter22_iso_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_RunIIIWinter22_noIso_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_tools.py
  RecoEgamma/ElectronIdentification/test/testElectronMVARun3_cfg.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, xpog-approved, egamma

#40242 [SIMULATION] [LLVM 14] bitwise-instead-of-logical warnings fixed
  DataFormats/GeometrySurface/interface/GloballyPositioned.h
  DataFormats/GeometrySurface/interface/RectangularPlaneBounds.h
  DataFormats/GeometrySurface/interface/SimpleDiskBounds.h
  DataFormats/GeometrySurface/src/DiskSectorBounds.cc
  DataFormats/GeometrySurface/src/TrapezoidalPlaneBounds.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40249 Replace old cms_test_conditions schema with cms_cond_general_w; use C…
  CondTools/SiStrip/python/o2o_db_manager.py
  OnlineDB/SiStripO2O/plugins/SiStripPayloadHandler.cc
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, code-checks-approved, trk

#40253 Remove last use of tbb::task::suspend
  FWCore/Concurrency/interface/include_first_syncWait.h
  FWCore/Concurrency/src/SerialTaskQueue.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40255 `SiStripHitEfficiencyHarvester`: Hit efficiency summary saved in dqm files
  CalibTracker/SiStripHitEfficiency/plugins/SiStripHitEfficiencyHarvester.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40247 [JMENanoAOD] Backport of #40232 (Setup DQM and increase precision of PileUp ID & QGL input variables) to 12_6_X
  DQMOffline/Configuration/python/DQMOfflineMC_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Configuration/python/autoDQM.py
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/NanoAOD/python/nanojmeDQM_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#40265 Add all PDs from 2022 in AlCaReco Matrix
  Configuration/AlCa/python/autoAlca.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40223 update of `hltDumpStream` for Run-3 HLT menus
  HLTrigger/Configuration/scripts/hltDumpStream
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40219 Phase2-hgx333X Bug fix for wrongly classifying good Hits as invalid in HGCal V16/V17 geometries (backport of #40208)
  Geometry/HGCalCommonData/interface/HGCalTypes.h
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  Geometry/HGCalCommonData/src/HGCalWaferMask.cc
Labels: geometry-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved

#40043 Add Run 3 patjet process with supported b-taggers
  PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cfi.py
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#40250 [Backport of PR #40230] Electron MVA-based ID for Run3 from EGamma POG
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py
  RecoEgamma/ElectronIdentification/data/ElectronIDVariablesRun3.txt
  RecoEgamma/ElectronIdentification/python/ElectronMVAValueMapProducer_cfi.py
  RecoEgamma/ElectronIdentification/python/FWLite.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_RunIIIWinter22_iso_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_RunIIIWinter22_noIso_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_tools.py
  RecoEgamma/ElectronIdentification/test/testElectronMVARun3_cfg.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok, xpog-approved, egamma

#40191 [GENERATORS] [LLVM14] Apply code checks
  GeneratorInterface/GenFilters/plugins/EMEnrichingFilterAlgo.cc
Labels: generators-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#40192 [RECONSTRUCTION-XPOG] [LLVM14] Apply code checks
  PhysicsTools/PatAlgos/plugins/PATJetProducer.cc
Labels: reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved, xpog-pending

#40278 Allow caching of HFShowerLibrary
  SimDataFormats/CaloHit/interface/HFShowerPhoton.h
  SimDataFormats/CaloHit/src/HFShowerPhoton.cc
  SimG4CMS/Calo/interface/HFFibre.h
  SimG4CMS/Calo/interface/HFShower.h
  SimG4CMS/Calo/interface/HFShowerLibrary.h
  SimG4CMS/Calo/interface/HFShowerParam.h
  SimG4CMS/Calo/src/HFFibre.cc
  SimG4CMS/Calo/src/HFShower.cc
  SimG4CMS/Calo/src/HFShowerLibrary.cc
  SimG4CMS/Calo/src/HFShowerParam.cc
  SimG4CMS/Calo/test/BuildFile.xml
  SimG4CMS/Calo/test/test_catch2_hffibre.cc
  SimG4CMS/Calo/test/test_catch2_hfshowerlibrary.cc
  SimG4CMS/Calo/test/test_catch2_main.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40282 Remove obsolete tf session const_cast's in RecoHGCal
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyCLUE3D.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyFastJet.cc
  RecoHGCal/TICL/plugins/TrackstersMergeProducer.cc
  RecoHGCal/TICL/plugins/TrackstersMergeProducerV3.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39953 Remove deprecated JetCorrector and related files
  DQM/Physics/python/DQMPhysics_cff.py
  DQM/Physics/python/topJetCorrectionHelper_cfi.py
  JetMETCorrections/Algorithms/interface/L1FastjetCorrector.h
  JetMETCorrections/Algorithms/interface/L1JPTOffsetCorrector.h
  JetMETCorrections/Algorithms/interface/L1OffsetCorrector.h
  JetMETCorrections/Algorithms/interface/L6SLBCorrector.h
  JetMETCorrections/Algorithms/interface/LXXXCorrector.h
  JetMETCorrections/Algorithms/src/L1FastjetCorrector.cc
  JetMETCorrections/Algorithms/src/L1JPTOffsetCorrector.cc
  JetMETCorrections/Algorithms/src/L1OffsetCorrector.cc
  JetMETCorrections/Algorithms/src/L6SLBCorrector.cc
  JetMETCorrections/Algorithms/src/LXXXCorrector.cc
  JetMETCorrections/Configuration/python/DefaultJEC_cff.py
  JetMETCorrections/Configuration/python/JetCorrectionProducersAllAlgos_cff.py
  JetMETCorrections/Configuration/python/JetCorrectionProducers_cff.py
  JetMETCorrections/Configuration/python/JetCorrectionServicesAllAlgos_cff.py
  JetMETCorrections/Configuration/python/JetCorrectionServices_cff.py
  JetMETCorrections/Modules/interface/JetCorrectionESProducer.h
  JetMETCorrections/Modules/interface/JetCorrectionESSource.h
  JetMETCorrections/Modules/interface/JetCorrectionProducer.h
  JetMETCorrections/Modules/plugins/JetCorrectionESChain.cc
  JetMETCorrections/Modules/plugins/SealModule.cc
  JetMETCorrections/Modules/python/hltJetCorrectionESChain_cfi.py
  JetMETCorrections/Modules/python/hltL1FastjetCorrectionESProducer_cfi.py
  JetMETCorrections/Modules/python/hltLXXXCorrectionESProducer_cfi.py
  JetMETCorrections/Objects/interface/ChainedJetCorrector.h
  JetMETCorrections/Objects/interface/JetCorrector.h
  JetMETCorrections/Objects/src/ChainedJetCorrector.cc
  JetMETCorrections/Objects/src/JetCorrector.cc
  JetMETCorrections/Objects/src/T_EventSetup_JetCorrector.cc
  PhysicsTools/PatAlgos/python/recoLayer0/jetCorrections_cff.py
  RecoHI/HiJetAlgos/python/hiCaloJetsForTrk_cff.py
Labels: analysis-pending, dqm-approved, reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved, xpog-approved

#40272 [124X] Add all PDs from 2022 in AlCaReco Matrix
  Configuration/AlCa/python/autoAlca.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40270 [126X] Add all PDs from 2022 in AlCaReco Matrix
  Configuration/AlCa/python/autoAlca.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40275 Set nullptr for L1TParticleFlow classes
  DataFormats/L1TParticleFlow/interface/layer1_emulator.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#40274 Update VertexWord.h sumPt to 12b format, 10b int.
  DataFormats/L1Trigger/interface/VertexWord.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40138 Addition of WFs for postEE scenario [12_4_X]
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#40244 Adding Running PU ProdLike Wfs
  Configuration/PyReleaseValidation/README.md
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/Mixing.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#40263 Turn off Tauolapp output redirection
  GeneratorInterface/TauolaInterface/plugins/Tauolapp/TauolappInterface.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40254 add filter for intermediate resonance particles
  GeneratorInterface/GenFilters/plugins/LHEIntermediateParticlePtFilter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40297 Avoid short-circuiting ESWatchers in FastSimProducer
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40267 New Run3 pileup scenarios for max PU studies
  Configuration/StandardSequences/python/Mixing.py
  SimGeneral/MixingModule/python/Run3_2023_LHC_Simulation_11h_8h_hybrid2p40_cfi.py
  SimGeneral/MixingModule/python/Run3_2023_LHC_Simulation_12p5h_9h_hybrid2p23_cfi.py
  SimGeneral/MixingModule/python/Run3_2023_LHC_Simulation_14h_10h_hybrid2p05_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40303 Avoid short-circuiting ESWatchers in ElectronSeedGenerator
  RecoEgamma/EgammaElectronAlgos/src/ElectronSeedGenerator.cc
Labels: reconstruction-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#40302 Avoid short-circuiting ESWatchers in SiStripCorrelateBadStripAndNoise
  DQM/SiStripMonitorSummary/plugins/SiStripCorrelateBadStripAndNoise.cc
Labels: dqm-pending, pending-signatures, tests-started, orp-approved, code-checks-approved

#40300 Avoid short-circuiting ESWatchers in PFCandidateRecalibrator
  CommonTools/ParticleFlow/plugins/PFCandidateRecalibrator.cc
Labels: reconstruction-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#40284 Move TF session in DeepMETProducer to global cache
  PhysicsTools/TensorFlow/interface/TensorFlow.h
  PhysicsTools/TensorFlow/src/TensorFlow.cc
  PhysicsTools/TensorFlow/test/BuildFile.xml
  PhysicsTools/TensorFlow/test/testBase.h
  PhysicsTools/TensorFlow/test/testSessionCache.cc
  RecoMET/METPUSubtraction/plugins/DeepMETProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40288 add unit test for `TriggerEvent*` analyzers
  HLTrigger/HLTcore/interface/HLTEventAnalyzerAOD.h
  HLTrigger/HLTcore/interface/HLTEventAnalyzerRAW.h
  HLTrigger/HLTcore/plugins/HLTEventAnalyzerAOD.cc
  HLTrigger/HLTcore/plugins/HLTEventAnalyzerRAW.cc
  HLTrigger/HLTcore/test/BuildFile.xml
  HLTrigger/HLTcore/test/testTriggerEventAnalyzers.sh
  HLTrigger/HLTcore/test/testTriggerEventAnalyzers_cfg.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40279 Addition of postEE Wfs [12_6_X]
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#40280 addition of WFs with post-EE conditions [12_5_X]
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#40293 Fix `PostDQMOffline*` sequences in cmsDriver.py
  Configuration/Applications/python/ConfigBuilder.py
Labels: dqm-approved, operations-approved, fully-signed, tests-rejected, bug-fix, orp-approved, urgent, code-checks-approved

#40269 New Run3 pileup scenarios for max PU studies (12_4 backport)
  Configuration/StandardSequences/python/Mixing.py
  SimGeneral/MixingModule/python/Run3_2023_LHC_Simulation_11h_8h_hybrid2p40_cfi.py
  SimGeneral/MixingModule/python/Run3_2023_LHC_Simulation_12p5h_9h_hybrid2p23_cfi.py
  SimGeneral/MixingModule/python/Run3_2023_LHC_Simulation_14h_10h_hybrid2p05_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40268 New Run3 pileup scenarios for max PU studies (12_6 backport)
  Configuration/StandardSequences/python/Mixing.py
  SimGeneral/MixingModule/python/Run3_2023_LHC_Simulation_11h_8h_hybrid2p40_cfi.py
  SimGeneral/MixingModule/python/Run3_2023_LHC_Simulation_12p5h_9h_hybrid2p23_cfi.py
  SimGeneral/MixingModule/python/Run3_2023_LHC_Simulation_14h_10h_hybrid2p05_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40266 modify nanoDQMIO configuration
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
  DQMServices/Core/src/DQMStore.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40289 Enable Phase-2 HLT wf which runs together with DIGI+L1
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#40276 Initialize variables for SiStripMonitorDigi::SubDetMEs
  DQM/SiStripMonitorDigi/interface/SiStripMonitorDigi.h
  DQM/SiStripMonitorDigi/src/SiStripMonitorDigi.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40257 HcalDQM: Add protection to collection non-exist case for GPUTask, backport of PR #40117
  DQM/HcalTasks/plugins/DigiTask.cc
  DQM/HcalTasks/plugins/HcalGPUComparisonTask.cc
  DQM/Integration/python/clients/hcalgpu_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, hcal

#40264 template `DQM/SiPixelPhase1Heterogenous` class to be able to handle the Phase-2 SoA objects
  DQM/SiPixelHeterogeneous/plugins/BuildFile.xml
  DQM/SiPixelHeterogeneous/plugins/SiPixelCompareRecHitsSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelCompareTrackSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelCompareVertexSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelMonitorRecHitsSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelMonitorTrackSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelMonitorVertexSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelTrackComparisonHarvester.cc
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQMHarvesting_cff.py
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQM_FirstStep_cff.py
  DQM/SiPixelPhase1Heterogeneous/python/SiPixelPhase1HeterogenousDQMHarvesting_cff.py
  DQM/SiPixelPhase1Heterogeneous/python/SiPixelPhase1HeterogenousDQM_FirstStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
Labels: dqm-approved, hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40306 [UBSAN] Add missing dependence to Calibration/HcalCalibAlgos/test/BuildFile.xml
  Calibration/HcalCalibAlgos/test/BuildFile.xml
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40286 [backport to 12_4_X] modify nanoDQMIO configuration
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
  DQMServices/Core/src/DQMStore.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#40310 Utilities/StaticAnalysers: Fix assert in ConstCast and ConstCastAway checkers.
  Utilities/StaticAnalyzers/src/ConstCastAwayChecker.cpp
  Utilities/StaticAnalyzers/src/ConstCastChecker.cpp
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40309 Add filter for intermediate resonance particles [10_6_X]
  GeneratorInterface/GenFilters/plugins/LHEIntermediateParticlePtFilter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40313 Geant4 physics config for 11.1
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMM.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40305 adding new per lumi plots to Jetmet DQM
  DQMOffline/JetMET/src/METAnalyzer.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40295 Add basic `SiStripApproximateCluster` Monitoring
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
  DQM/SiStripMonitorApproximateCluster/plugins/BuildFile.xml
  DQM/SiStripMonitorApproximateCluster/plugins/SiStripMonitorApproximateCluster.cc
  DQM/SiStripMonitorApproximateCluster/python/SiStripMonitorApproximateCluster_cfi.py
  DQM/SiStripMonitorClient/python/SiStripSourceConfigTier0_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#40281 Phase2-hgx333B Fix issues of wrong DetID assignment for V17 geometry of HGCal
  Geometry/HGCalCommonData/src/HGCalCellUV.cc
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  SimG4CMS/Calo/src/HGCScintSD.cc
  SimG4CMS/Calo/src/HGCalSD.cc
  Validation/HGCalValidation/scripts/testHGCalSimTTBar_cfg.py
Labels: dqm-approved, geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#40317 Typo: Fix the correct object to Clone
  PhysicsTools/FWLite/interface/Scanner.h
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#40318 Update Run3 offline and offline_relval GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40261 fine tune LS to be run for data WFs
  Configuration/PyReleaseValidation/python/MatrixInjector.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#40182 [TkAl] Fix EoP Validation plotting macros
  Alignment/OfflineValidation/macros/momentumBiasValidation.C
  Alignment/OfflineValidation/macros/momentumElectronBiasValidation.C
  Alignment/OfflineValidation/python/TkAlAllInOneTool/defaultInputFiles_cff.py
  Alignment/OfflineValidation/test/BuildFile.xml
  Alignment/OfflineValidation/test/eopElecTreeWriter_cfg.py
  Alignment/OfflineValidation/test/eopTreeWriter_cfg.py
  Alignment/OfflineValidation/test/testEoPPlotting.cpp
  Alignment/OfflineValidation/test/test_unitEoP.sh
  Alignment/OfflineValidation/test/test_unitEoPElectron.sh
  Alignment/OfflineValidation/test/test_unitEoPPion.sh
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#40283 Remove obsolete tf session const_cast's in RecoTracker
  RecoTracker/FinalTrackSelectors/plugins/TrackTfClassifier.cc
  RecoTracker/MkFit/plugins/MkFitOutputConverter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40327 Save iEta/iPhi & iX/iY indices of ECAL crystals in nanoAOD
  PhysicsTools/NanoAOD/plugins/EGMSeedLocationProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, urgent, code-checks-approved, xpog-approved, egamma

#40352 Utilities/StaticAnalyzer: Update cms.NonFiniteMath optional.getParamDumper checkers
  Utilities/StaticAnalyzers/src/ArgSizeChecker.cpp
  Utilities/StaticAnalyzers/src/ClassChecker.cpp
  Utilities/StaticAnalyzers/src/ESRecordGetChecker.cpp
  Utilities/StaticAnalyzers/src/FiniteMathChecker.cc
  Utilities/StaticAnalyzers/src/FiniteMathChecker.h
  Utilities/StaticAnalyzers/src/PsetExistsFCallChecker.cpp
  Utilities/StaticAnalyzers/src/ThrUnsafeFCallChecker.cpp
  Utilities/StaticAnalyzers/src/getByChecker.cpp
  Utilities/StaticAnalyzers/src/getParamDumper.cpp
  Utilities/StaticAnalyzers/src/getParamDumper.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40337 [126X] Update Run3 offline and offline RelVal GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved

#40330 Move files from CalibTracker/SiStripDCS to cms-data
  CalibTracker/SiStripDCS/data/ExcludedSiStripDetInfo.dat
  CalibTracker/SiStripDCS/data/PixelPsuDetIdMap.dat
  CalibTracker/SiStripDCS/data/StripDetIDAlias.pkl
  CalibTracker/SiStripDCS/data/StripPSUDetIDMap_BeforeJan132010.dat
  CalibTracker/SiStripDCS/data/StripPSUDetIDMap_FromJan132010.dat
  CalibTracker/SiStripDCS/data/StripPsuDetIdMap.dat
  CalibTracker/SiStripDCS/data/StripPsuDetIdMapDecember.dat
Labels: alca-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#40316 Can now run multiple OscarMTProducers in the same job
  SimG4Core/Application/plugins/OscarMTProducer.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40323 Adjust collections of Tracker clusters to be saved for Phase-2 ALCARECO
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlBeamHalo_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlDiMuonAndVertex_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlJetHT_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlJpsiMuMuHI_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlJpsiMuMu_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlMinBiasHI_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlMinBias_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlMuonIsolatedHI_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlMuonIsolatedPA_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlMuonIsolated_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlUpsilonMuMuHI_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlUpsilonMuMuPA_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlUpsilonMuMu_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlWMuNu_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlZMuMuHI_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlZMuMuPA_Output_cff.py
  Alignment/CommonAlignmentProducer/python/ALCARECOTkAlZMuMu_Output_cff.py
  CommonTools/RecoAlgos/BuildFile.xml
  CommonTools/RecoAlgos/interface/ClusterStorer.h
  CommonTools/RecoAlgos/interface/MuonSelector.h
  CommonTools/RecoAlgos/interface/TrackSelector.h
  CommonTools/RecoAlgos/src/ClusterStorer.cc
  CommonTools/RecoAlgos/src/MuonSelector.cc
  CommonTools/RecoAlgos/src/TrackSelector.cc
  DataFormats/TrackerRecHit2D/interface/Phase2TrackerRecHit1D.h
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#40315 Allow throwing of edm::Exceptions from python
  FWCore/Framework/bin/cmsRun.cpp
  FWCore/ParameterSet/python/Config.py
  FWCore/PythonParameterSet/src/PyBind11Wrapper.cc
  FWCore/PythonParameterSet/test/makeprocess_t.cppunit.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40067 Changing abs(eta) cut for tracks in ALCARECOEcalESAlign_cff.py
  Calibration/EcalAlCaRecoProducers/python/ALCARECOEcalESAlign_cff.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40345 Fix Geant4 physics configuration
  SimG4Core/Application/src/ParametrisedEMPhysics.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40341 add heavy-ion Run 3 data RelVal workflows
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#40354 Initialize member data in LumiOutputBranches
  PhysicsTools/NanoAOD/plugins/LumiOutputBranches.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#40342 Moved DeepCoreSeedGenerator TF session to global cache
  RecoTracker/TkSeedGenerator/plugins/DeepCoreSeedGenerator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40356 [126X] Save iEta/iPhi & iX/iY indices of ECAL crystals in nanoAOD
  PhysicsTools/NanoAOD/plugins/EGMSeedLocationProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved, egamma

#40357 HCAL: configurable option to use actual Run3 HF ShowerLibrary for Run2 MC
  Configuration/ProcessModifiers/python/applyHFLibraryFix_cff.py
  Geometry/HcalSimData/python/HFParameters_cff.py
  SimCalorimetry/HcalSimProducers/python/hcalSimParameters_cfi.py
Labels: geometry-approved, operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40350 Set member data in l1t::TkJet
  DataFormats/L1TCorrelator/src/TkJet.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#40355 Initialize member data in RPCTBMuon
  L1Trigger/RPCTrigger/src/RPCTBMuon.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40333 Move TF session in L1Trigger/L1NNTauProducer to global cache
  L1Trigger/Phase2L1ParticleFlow/interface/TauNNId.h
  L1Trigger/Phase2L1ParticleFlow/plugins/L1NNTauProducer.cc
  L1Trigger/Phase2L1ParticleFlow/src/TauNNId.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#40332 Add filter for intermediate resonance particles [12_6_X]
  GeneratorInterface/GenFilters/plugins/LHEIntermediateParticlePtFilter.cc
Labels: generators-pending, pending-signatures, tests-approved, orp-approved, backport-ok

#40351 Set all member data of RegionalMuonShower
  DataFormats/L1TMuon/src/RegionalMuonShower.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37831 Implement ResourceInformationService
  FWCore/Framework/src/ScheduleItems.cc
  FWCore/Framework/src/defaultCmsRunServices.cc
  FWCore/Integration/test/testSubProcess_cfg.py
  FWCore/MessageService/test/u10_cfg.py
  FWCore/MessageService/test/u14_cfg.py
  FWCore/MessageService/test/u16_cfg.py
  FWCore/MessageService/test/u1_cfg.py
  FWCore/MessageService/test/u1d_cfg.py
  FWCore/MessageService/test/u20_cfg.py
  FWCore/MessageService/test/u27_cfg.py
  FWCore/MessageService/test/u7_cfg.py
  FWCore/MessageService/test/u9_cfg.py
  FWCore/Services/plugins/CPU.cc
  FWCore/Services/plugins/CondorStatusUpdater.cc
  FWCore/Services/plugins/ResourceInformationService.cc
  FWCore/Services/test/BuildFile.xml
  FWCore/Services/test/test_resourceInformationService.sh
  FWCore/Services/test/test_resourceInformationService_cfg.py
  FWCore/Utilities/interface/CPUServiceBase.h
  FWCore/Utilities/interface/ResourceInformation.h
  FWCore/Utilities/src/CPUServiceBase.cc
  FWCore/Utilities/src/ResourceInformation.cc
  HeterogeneousCore/CUDAServices/interface/CUDAService.h
  HeterogeneousCore/CUDAServices/plugins/plugins.cc
  HeterogeneousCore/CUDAServices/src/CUDAService.cc
  IOPool/Common/test/FastMergeTestRL_cfg.py
  IOPool/Common/test/FastMergeTestR_cfg.py
  IOPool/Common/test/FastMergeTest_cfg.py
  IOPool/Common/test/FastMergeTest_x_cfg.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#40338 [125X] Update Run3 offline and offline RelVal GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved

#40367 Update online data GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40325 initialise pointers in subclasses of `FastTimerService`
  HLTrigger/Timer/plugins/FastTimerService.cc
  HLTrigger/Timer/plugins/FastTimerService.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40346 Add `DiMuonValidation` to the TkAl "new" all-in-one tool
  Alignment/OfflineValidation/bin/BuildFile.xml
  Alignment/OfflineValidation/bin/FitWithRooFit.cc
  Alignment/OfflineValidation/bin/Zmumumerge.cc
  Alignment/OfflineValidation/plugins/DiMuonValidation.cc
  Alignment/OfflineValidation/python/TkAlAllInOneTool/Zmumu.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/Zmumu_cfg.py
  Alignment/OfflineValidation/scripts/validateAlignments.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#40364 Utilities/StaticAnalysers: Fix segfault in FiniteMathChecker. Fix garbage values in CMS code rules checkers category.
  Utilities/StaticAnalyzers/BuildFile.xml
  Utilities/StaticAnalyzers/src/ArgSizeChecker.cpp
  Utilities/StaticAnalyzers/src/ClassChecker.cpp
  Utilities/StaticAnalyzers/src/ESRecordGetChecker.cpp
  Utilities/StaticAnalyzers/src/FiniteMathChecker.cc
  Utilities/StaticAnalyzers/src/FiniteMathChecker.h
  Utilities/StaticAnalyzers/src/PsetExistsFCallChecker.cpp
  Utilities/StaticAnalyzers/src/ThrUnsafeFCallChecker.cpp
  Utilities/StaticAnalyzers/src/TrunCastChecker.h
  Utilities/StaticAnalyzers/src/getByChecker.cpp
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40349 Refactor SiPixel Charge Reweighting code
  SimTracker/Common/BuildFile.xml
  SimTracker/Common/interface/DigitizerUtility.h
  SimTracker/Common/interface/SiPixelChargeReweightingAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PSPDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PSPDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PSSDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PSSDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizer.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/Pixel3DDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PixelBrickedDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PixelBrickedDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/SSDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/SSDigitizerAlgorithm.h
  SimTracker/SiPixelDigitizer/plugins/SiPixelChargeReweightingAlgorithm.h
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, trk

#40365 add unit test to check availability of EDM files used in HLT tests
  HLTrigger/Configuration/test/BuildFile.xml
  HLTrigger/Configuration/test/cmsDriver.csh
  HLTrigger/Configuration/test/readme.md
  HLTrigger/Configuration/test/testAccessToEDMInputsOfHLTTests.sh
  HLTrigger/Configuration/test/testAccessToEDMInputsOfHLTTests_cfg.py
  HLTrigger/Configuration/test/testAccessToEDMInputsOfHLTTests_filelist.txt
  HLTrigger/Configuration/test/testAccessToEDMInputsOfHLTTests_update_filelist.sh
Labels: hlt-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#40343 Fix -1 precision in SimpleFlatTableProducer
  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#40366 [124X] Update Run3 offline and online data GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40369 [126X] Update online data GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40370 [125X] Update online data GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40371 `Zmumumerge`: post-merge comments to #40346
  Alignment/OfflineValidation/bin/Zmumumerge.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40348 Delete commented out imports of deprecated JetCorrector cffs
  L1Trigger/L1TNtuples/test/test_JetRecoProducer.py
  PhysicsTools/PatAlgos/python/recoLayer0/metCorrections_cff.py
  PhysicsTools/TagAndProbe/test/Electron_TagProbeTreeProducer_cfg.py
  Validation/RecoJets/python/JetValidation_cff.py
Labels: reconstruction-pending, dqm-pending, l1-pending, analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved, xpog-pending

#40083 Add TaggedProton filter for analysis with tagged protons
  GeneratorInterface/Core/interface/TaggedProtonHepMCFilter.h
  GeneratorInterface/Core/src/HepMCFilterDriver.cc
  GeneratorInterface/Core/src/TaggedProtonHepMCFilter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40379 Add dictionaries for AtomicPtrCache
  DataFormats/Candidate/src/classes.h
  DataFormats/Candidate/src/classes_def.xml
  DataFormats/ParticleFlowCandidate/src/classes.h
  DataFormats/ParticleFlowCandidate/src/classes_def.xml
  DataFormats/TauReco/src/classes_2.h
  DataFormats/TauReco/src/classes_def_2.xml
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40373 Backport of changes to LHEGenericMassFilter
  GeneratorInterface/GenFilters/plugins/LHEGenericMassFilter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40363 Fix `ClusterStorer` for `VectorHit`s
  CommonTools/RecoAlgos/interface/ClusterStorer.h
  CommonTools/RecoAlgos/src/ClusterStorer.cc
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  DataFormats/TrackerRecHit2D/interface/VectorHit.h
Labels: reconstruction-approved, fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved, trk

#40388 [L1T] remove deprecated L1 CSC files
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCAnodeLCTAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCAnodeLCTAnalyzer.h
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCCathodeLCTAnalyzer.cc
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCCathodeLCTAnalyzer.h
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCTriggerPrimitivesReader.cc
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCTriggerPrimitivesReader.h
  L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCTriggerPrimitivesReader_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40390 Fix TestIOPoolInputNoParentDictionary to use original dev area env
  IOPool/Input/test/testNoParentDictionary.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40385 update/add customisations for HIon HLT menus
  Configuration/HLT/python/addOnTestsHLT.py
  HLTrigger/Configuration/python/CustomConfigs.py
  HLTrigger/Configuration/python/Tools/confdb.py
  HLTrigger/Configuration/python/customizeHLTforALL.py
  HLTrigger/Configuration/test/OnLine_HLT_HIon.py
  HLTrigger/Configuration/test/cmsDriver.csh
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40241 [RECONSTRUCTION] [LLVM 14] bitwise-instead-of-logical warnings fixed
  DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h
  DataFormats/VertexReco/interface/Vertex.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40386 update/add customisations for HIon HLT menus [`12_6_X`]
  Configuration/HLT/python/addOnTestsHLT.py
  HLTrigger/Configuration/python/CustomConfigs.py
  HLTrigger/Configuration/python/Tools/confdb.py
  HLTrigger/Configuration/python/customizeHLTforALL.py
  HLTrigger/Configuration/test/OnLine_HLT_HIon.py
  HLTrigger/Configuration/test/cmsDriver.csh
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok

#40393 Fix incorrect keyword in JetCorrector dictionary
  JetMETCorrections/JetCorrector/src/classes_def.xml
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40399 [FASTSIM] [CLANG] Fixed unused-but-set-variable warnings
  FastSimulation/ShowerDevelopment/src/EMShower.cc
  FastSimulation/ShowerDevelopment/src/HDRShower.cc
  FastSimulation/ShowerDevelopment/src/HFShower.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved
