Repository cms-sw/cmssw, pull requests merged in 2022-01, with the labels that each got.

#36602 Run3-Sim101E Remove warnings in a few classes of SimTracker/SiPixelDigitizer
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.cc
  SimTracker/SiPixelDigitizer/test/PixelDigisTest.cc
  SimTracker/SiPixelDigitizer/test/PixelMixedSimHitsTest.cc
  SimTracker/SiPixelDigitizer/test/PixelSimHitsTest.cc
  SimTracker/SiPixelDigitizer/test/PixelSimHitsTestForward.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36601 Run3-Sim101D Remove the compilation warnings in SimMuon/MCTruth
  SimMuon/MCTruth/interface/CSCTruthTest.h
  SimMuon/MCTruth/interface/MuonTruth.h
  SimMuon/MCTruth/src/CSCTruthTest.cc
  SimMuon/MCTruth/src/MuonTruth.cc
  SimMuon/MCTruth/test/testReader.h
  SimTransport/HectorProducer/interface/Hector.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36599 Run3-sim101B Remove some compilation warnings in SimGeneral/TrackingAnalysis
  SimGeneral/TrackingAnalysis/interface/MuonPSimHitSelector.h
  SimGeneral/TrackingAnalysis/interface/PSimHitSelector.h
  SimGeneral/TrackingAnalysis/interface/PixelPSimHitSelector.h
  SimGeneral/TrackingAnalysis/interface/TrackerPSimHitSelector.h
  SimGeneral/TrackingAnalysis/src/MuonPSimHitSelector.cc
  SimGeneral/TrackingAnalysis/src/PSimHitSelector.cc
  SimGeneral/TrackingAnalysis/src/PixelPSimHitSelector.cc
  SimGeneral/TrackingAnalysis/src/TrackerPSimHitSelector.cc
  SimGeneral/TrackingAnalysis/test/TrackingTruthOutputTest.cc
  SimGeneral/TrackingAnalysis/test/TrackingTruthOutputTest.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36619 Converted modules to thread efficient types in HLTrigger/special
  HLTrigger/special/plugins/BuildFile.xml
  HLTrigger/special/plugins/EcalMIPRecHitFilter.cc
  HLTrigger/special/plugins/EcalSimpleUncalibRecHitFilter.cc
  HLTrigger/special/plugins/HLTCountNumberOfObject.h
  HLTrigger/special/plugins/HLTDTROMonitorFilter.cc
  HLTrigger/special/plugins/HLTDTROMonitorFilter.h
  HLTrigger/special/plugins/HLTDummyCollections.cc
  HLTrigger/special/plugins/HLTDynamicPrescaler.cc
  HLTrigger/special/plugins/HLTEcalResonanceFilter.cc
  HLTrigger/special/plugins/HLTEcalResonanceFilter.h
  HLTrigger/special/plugins/HLTEventNumberFilter.cc
  HLTrigger/special/plugins/HLTEventNumberFilter.h
  HLTrigger/special/plugins/HLTHFAsymmetryFilter.cc
  HLTrigger/special/plugins/HLTHFAsymmetryFilter.h
  HLTrigger/special/plugins/HLTLogMonitorFilter.cc
  HLTrigger/special/plugins/HLTPhysicsDeclared.cc
  HLTrigger/special/plugins/HLTTrackWithHits.h
  HLTrigger/special/test/ArbitraryLogError.cc
  HLTrigger/special/test/BuildFile.xml
  HLTrigger/special/test/testLogMonitorFilter.sh
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36622 Run3-alca212B Remove compilation warnings in the clases of EcalAlCaRecoProducers|EcalCalibAlgos within Calibration
  Calibration/EcalAlCaRecoProducers/src/AlCaElectronsTest.h
  Calibration/EcalCalibAlgos/interface/ZeeKinematicTools.h
  Calibration/EcalCalibAlgos/interface/ZeePlots.h
  Calibration/EcalCalibAlgos/interface/ZeeRescaleFactorPlots.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36618 Initialize variables, and a few other trivial adjustments in RecoRomanPot/RecoFP420
  RecoRomanPot/RecoFP420/interface/TrackProducerFP420.h
  RecoRomanPot/RecoFP420/src/RecoProducerFP420.cc
  RecoRomanPot/RecoFP420/src/TrackProducerFP420.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36623 Phase2-hgx297E Update the test configuration in Geometry/HGCalGeometry
  Geometry/HGCalGeometry/test/HGCalWaferCheck.cc
  Geometry/HGCalGeometry/test/python/testHGCalGeometryMouseBite_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalGeometryRotCheck_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalGeometryRotTest_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalSize_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalWaferCell_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalWaferTypeTester_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalWafer_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36588 Drop type specs for L1TMonitor and L1TMonitorClient
  DQM/L1TMonitor/python/L1ExtraDQM_cff.py
  DQM/L1TMonitor/python/L1TEmulatorMonitor_cff.py
  DQM/L1TMonitor/python/L1TMonitor_cff.py
  DQM/L1TMonitor/python/L1TStage2BMTF_cff.py
  DQM/L1TMonitor/python/L1TStage2FED_cff.py
  DQM/L1TMonitor/python/L1TStage2uGMT_cff.py
  DQM/L1TMonitor/python/L1TStage2uGTBoardComp_cff.py
  DQM/L1TMonitor/python/L1TSync_cff.py
  DQM/L1TMonitor/python/L1TdeStage2uGMT_cff.py
  DQM/L1TMonitorClient/python/L1TStage2BMTFClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2MuonQualityTests_cff.py
  DQM/L1TMonitorClient/python/L1TStage2uGMTClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2uGTClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2uGTEmulatorClient_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36565 Further optimization of the SiPixel LA PCL workflow
  CalibTracker/SiPixelLorentzAngle/interface/SiPixelLorentzAngleCalibrationStruct.h
  CalibTracker/SiPixelLorentzAngle/python/SiPixelLorentzAnglePCLHarvester_cfi.py
  CalibTracker/SiPixelLorentzAngle/python/SiPixelLorentzAnglePCLWorker_cfi.py
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAngle.cc
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLHarvester.cc
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLWorker.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36589 PPS transport update
  SimTransport/PPSProtonTransport/interface/BaseProtonTransport.h
  SimTransport/PPSProtonTransport/interface/HectorTransport.h
  SimTransport/PPSProtonTransport/interface/OpticalFunctionsTransport.h
  SimTransport/PPSProtonTransport/interface/TotemTransport.h
  SimTransport/PPSProtonTransport/src/BaseProtonTransport.cc
  SimTransport/PPSProtonTransport/src/HectorTransport.cc
  SimTransport/PPSProtonTransport/src/OpticalFunctionsTransport.cc
  SimTransport/PPSProtonTransport/src/ProtonTransport.cc
  SimTransport/PPSProtonTransport/src/TotemTransport.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36478 Add early delete customisation for mkFit temporary data products
  Configuration/StandardSequences/python/earlyDeleteSettings_cff.py
  RecoTracker/Configuration/python/customiseEarlyDeleteForMkFit.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36620 Fix CMS deprecated warnings in L1Trigger/GlobalCaloTrigger
  L1Trigger/GlobalCaloTrigger/plugins/L1GctEmulator.cc
  L1Trigger/GlobalCaloTrigger/plugins/L1GctPrintLuts.h
  L1Trigger/GlobalCaloTrigger/plugins/L1GctValidation.cc
  L1Trigger/GlobalCaloTrigger/plugins/L1GctValidation.h
  L1Trigger/GlobalCaloTrigger/test/L1GctTest.cc
  L1Trigger/GlobalCaloTrigger/test/L1GctTest.h
  L1Trigger/GlobalCaloTrigger/test/L1GctTestAnalyzer.cc
  L1Trigger/GlobalCaloTrigger/test/L1GctTestAnalyzer.h
  L1Trigger/GlobalCaloTrigger/test/gctTestFunctions.cc
  L1Trigger/GlobalCaloTrigger/test/gctTestFunctions.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36626 Migrate module config in DPGAnalysis to use default cfipy
  Configuration/EcalTB/python/reco_application_2006h2rawdata_ecalLocalReco_cfg.py
  DPGAnalysis/HcalTools/python/remoteMonitoring_LASER_era2018_cfg.py
  DPGAnalysis/HcalTools/python/remoteMonitoring_LASER_era2019_cfg.py
  DPGAnalysis/HcalTools/python/remoteMonitoring_LED_IterMethod_cfg.py
  DPGAnalysis/HcalTools/python/remoteMonitoring_LED_era2018_cfg.py
  DPGAnalysis/HcalTools/python/remoteMonitoring_LED_era2019_cfg.py
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36594 Run3-gex109B Avoid compilation warnings in some Validation code
  Validation/EcalRecHits/interface/EcalBarrelRecHitsValidation.h
  Validation/EcalRecHits/interface/EcalEndcapRecHitsValidation.h
  Validation/EcalRecHits/interface/EcalPreshowerRecHitsValidation.h
  Validation/EcalRecHits/interface/EcalRecHitsValidation.h
  Validation/EcalRecHits/interface/EcalTBValidation.h
  Validation/EcalTriggerPrimitives/src/TPGCheck.cc
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36625 removed dummy `python/` dirs in `HLTrigger/`
  HLTrigger/Egamma/python/_dummy.py
  HLTrigger/HLTfilters/python/_dummy.py
  HLTrigger/JetMET/python/_dummy.py
  HLTrigger/Muon/python/_dummy.py
  HLTrigger/btau/python/_dummy.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36636 Use proper long long type when validating Parameter
  FWCore/ParameterSet/src/Entry.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36637 initialize members of TableOutputBranches
  PhysicsTools/NanoAOD/plugins/TableOutputBranches.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#36634 Run3-gex109F Try to avoid compilation warnings in some Validation codes in RecoPixelVertexing, RecoVertex, TrackerDigis
  Validation/RecoPixelVertexing/test/BuildFile.xml
  Validation/RecoPixelVertexing/test/PixelVertexVal.cc
  Validation/RecoVertex/interface/PrimaryVertexAnalyzer4PUSlimmed.h
  Validation/TrackerDigis/plugins/SiPixelDigiValid.h
  Validation/TrackerDigis/plugins/SiStripDigiValid.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36629 Run3-alca212C Make edm::Service<TFileService> as a local variable in the methods used in the classes of Calibration/HcalCalibAlgos
  Calibration/HcalCalibAlgos/plugins/RecAnalyzerHF.cc
  Calibration/HcalCalibAlgos/plugins/RecAnalyzerMinbias.cc
  Calibration/HcalCalibAlgos/plugins/SimAnalyzerMinbias.cc
  Calibration/HcalCalibAlgos/test/HcalHBHEMuonSimAnalyzer.cc
  Calibration/HcalCalibAlgos/test/HcalIsoTrackAnalysis.cc
  Calibration/HcalCalibAlgos/test/HcalIsoTrackStudy.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36600 Run3-Sim101C Avoid compilation warnings in SimMuon/GEMDigitizer and SimMuon/RPCDigitizer
  SimMuon/GEMDigitizer/plugins/GEMDigiProducer.cc
  SimMuon/GEMDigitizer/plugins/ME0DigiProducer.cc
  SimMuon/GEMDigitizer/test/GEMDigiReader.cc
  SimMuon/GEMDigitizer/test/GEMFakeEvent.cc
  SimMuon/RPCDigitizer/src/RPCDigiProducer.cc
  SimMuon/RPCDigitizer/src/RPCSimAsymmetricCls.cc
  SimMuon/RPCDigitizer/src/RPCSimAverage.cc
  SimMuon/RPCDigitizer/src/RPCSimAverageNoise.cc
  SimMuon/RPCDigitizer/src/RPCSimAverageNoiseEff.cc
  SimMuon/RPCDigitizer/src/RPCSimAverageNoiseEffCls.cc
  SimMuon/RPCDigitizer/src/RPCSimModelTiming.cc
  SimMuon/RPCDigitizer/src/RPCSimSetUp.cc
  SimMuon/RPCDigitizer/src/RPCSimSetUp.h
  SimMuon/RPCDigitizer/src/RPCSynchronizer.cc
  SimMuon/RPCDigitizer/src/RPCSynchronizer.h
  SimMuon/RPCDigitizer/src/RPCandIRPCDigiProducer.cc
  SimMuon/RPCDigitizer/test/RPCEventDump.h
  SimMuon/RPCDigitizer/test/RPCFakeEvent.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36598 Run3-sim101A Remove some compilation warnings in classes from SimCalorimetry and SimGeneral
  SimCalorimetry/EcalEBTrigPrimProducers/plugins/EcalEBTrigPrimAnalyzer.cc
  SimCalorimetry/EcalSimProducers/test/ESDigisReferenceDistrib.h
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTPInputAnalyzer.cc
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTPInputAnalyzer.h
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTrigPrimAnalyzer.cc
  SimGeneral/MixingModule/plugins/InputAnalyzer.cc
  SimGeneral/MixingModule/plugins/SecSourceAnalyzer.cc
  SimGeneral/MixingModule/plugins/TestMix.cc
  SimGeneral/MixingModule/plugins/TestMixedSource.cc
  SimGeneral/NoiseGenerators/test/GaussianTailNoiseGeneratorTest.cc
  SimGeneral/PileupInformation/plugins/PileupVertexAccumulator.cc
Labels: l1-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36608 Run3-Sim101F Avoid compilation warnings in some of the codes of Validation/RecoTau
  Validation/RecoTau/interface/TauTagValidation.h
  Validation/RecoTau/interface/TauValidationMiniAOD.h
  Validation/RecoTau/plugins/DQMHistEffProducer.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36559 Correcting a JEC indexing bug for the pat::Jet class in association to scaleEnergy function calls
  DataFormats/PatCandidates/src/Jet.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#36627 Move GEM offline DQM files from DQMOffline/Muon to DQM/GEM
  DQM/GEM/BuildFile.xml
  DQM/GEM/interface/GEMDQMBase.h
  DQM/GEM/interface/GEMOfflineDQMBase.h
  DQM/GEM/plugins/GEMEfficiencyAnalyzer.cc
  DQM/GEM/plugins/GEMEfficiencyAnalyzer.h
  DQM/GEM/plugins/GEMEfficiencyHarvester.cc
  DQM/GEM/plugins/GEMEfficiencyHarvester.h
  DQM/GEM/plugins/SealModule.cc
  DQM/GEM/python/gemEfficiencyAnalyzerCosmics_cfi.py
  DQM/GEM/python/gemEfficiencyAnalyzer_cfi.py
  DQM/GEM/python/gemEfficiencyHarvesterCosmics_cfi.py
  DQM/GEM/python/gemEfficiencyHarvester_cfi.py
  DQM/GEM/python/gem_dqm_offline_client_cff.py
  DQM/GEM/python/gem_dqm_offline_client_cosmics_cff.py
  DQM/GEM/python/gem_dqm_offline_source_cff.py
  DQM/GEM/python/gem_dqm_offline_source_cosmics_cff.py
  DQM/GEM/src/GEMDQMBase.cc
  DQM/GEM/src/GEMOfflineDQMBase.cc
  DQMOffline/Configuration/python/DQMOfflineCosmics_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOfflineCosmics_cff.py
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Muon/interface/GEMOfflineMonitor.h
  DQMOffline/Muon/src/GEMOfflineMonitor.cc
  DQMOffline/Muon/src/SealModule.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36529 Fixing Patatrak pixelTracking only wfs
  RecoLocalTracker/SiPixelRecHits/python/SiPixelRecHits_cfi.py
  RecoPixelVertexing/PixelTrackFitting/python/PixelTracks_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36648 Run3-gex110 Recover BHM placements in the dd4hep scenario
  Geometry/ForwardCommonData/data/dd4hep/testForwardGeometry.xml
  Geometry/ForwardCommonData/data/pixfwd.xml
  Geometry/ForwardCommonData/plugins/dd4hep/DDBHMAngular.cc
  Geometry/ForwardCommonData/python/testForwardXML_cfi.py
  Geometry/ForwardCommonData/test/g4OverlapCheckForwardDD4hep_cfg.py
  Geometry/ForwardCommonData/test/g4OverlapCheckForwardDDD_cfg.py
  Geometry/ForwardCommonData/test/g4OverlapCheckTotemT2_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36578 Phase2-gex106 Remove BSC from Phase2 scenario and will be used in any new scenarios from now on
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2026D89Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D90Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D89Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D90Reco_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D89.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D90.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D89XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D90XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36653 Run3-gex111 Modify xml's to enable the dd4hep version to work in Geometry/ForwardCommonData and Geometry/MuonCommonData
  Geometry/ForwardCommonData/data/bcm1f/2021/v1/bcm1f.xml
  Geometry/ForwardCommonData/data/plt/2021/v1/plt.xml
  Geometry/ForwardCommonData/data/pltbcm/2021/v1/pltbcm.xml
  Geometry/MuonCommonData/data/muonNumbering/2021/v5/muonNumbering.xml
  Geometry/MuonCommonData/data/rpcf/2021/v1/rpcf.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36656 [DQM] Fixing currdir for Validation/RecoVertex/src/BeamSpotHistogramMaker.cc
  Validation/RecoVertex/src/BeamSpotHistogramMaker.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36635 Drop type specs for Alignment and EGamma
  DQMOffline/Alignment/python/ALCARECOTkAlDQM_cff.py
  DQMOffline/EGamma/python/cosmicPhotonAnalyzer_cfi.py
  DQMOffline/EGamma/python/egammaDQMOffline_cff.py
  DQMOffline/EGamma/python/electronAnalyzerSequence_cff.py
  DQMOffline/EGamma/python/electronOfflineClientSequence_cff.py
  DQMOffline/EGamma/python/photonAnalyzer_cfi.py
  DQMOffline/EGamma/python/photonOfflineDQMClient_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36638 Use thread safe module types in PhysicsTools/JetMCAlgos
  PhysicsTools/JetMCAlgos/plugins/CandOneToOneDeltaRMatcher.cc
  PhysicsTools/JetMCAlgos/test/jetMatch.cc
  PhysicsTools/JetMCAlgos/test/matchGenHFHadrons.cc
  PhysicsTools/JetMCAlgos/test/matchOneToOne.cc
  PhysicsTools/JetMCAlgos/test/printEvent.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#36651 Drop type specs for JetMET
  DQMOffline/JetMET/python/dataCertificationJetMET_cfi.py
  DQMOffline/JetMET/python/goodOfflinePrimaryVerticesDQM_cfi.py
  DQMOffline/JetMET/python/jetAnalyzer_cfi.py
  DQMOffline/JetMET/python/jetMETAnalyzer_cfi.py
  DQMOffline/JetMET/python/jetMETDQMOfflineSourceCosmic_cff.py
  DQMOffline/JetMET/python/jetMETDQMOfflineSourceMC_cff.py
  DQMOffline/JetMET/python/jetMETDQMOfflineSource_cff.py
  DQMOffline/JetMET/python/metDQMConfig_cfi.py
  DQMOffline/JetMET/python/pfCandidateDQMConfig_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36621 Run3-alca213 Complete the validation of the new AlCaReco for HcalIsoTrackFilter
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalIsotrkProducer.cc
  Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalIsoTrkProducerFilter_cff.py
  Calibration/HcalAlCaRecoProducers/python/alcaHcalIsotrkProducer_cff.py
  Calibration/HcalAlCaRecoProducers/test/AlCaIsoTrackFilterNoHLT_cfg.py
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrackAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkAnalyzer.cc
  Calibration/HcalCalibAlgos/test/python/isoTrackAlCaAnalysis_cfg.py
  Calibration/HcalCalibAlgos/test/python/isoTrackNewAlCaAnalysis_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36547 Add a unit test for correctionlib external
  PhysicsTools/Utilities/test/BuildFile.xml
  PhysicsTools/Utilities/test/corrections.json
  PhysicsTools/Utilities/test/test_correctionlib.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, requires-external

#36657 technical fix for value of L1T's `caloParams.jetPUSUsePhiRing`
  L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_4_1_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_4_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParams_2019_v1_0_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParams_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36607 Fixing Phase-II Patatrack Failures
  CUDADataFormats/TrackingRecHit/test/TrackingRecHit2DCUDA_t.cpp
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelPhase2DigiToClusterCUDA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuCalibPixel.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, heterogeneous-approved

#35481 For async calls always store XrdCl::FileSystem with the response-handler.
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
  Utilities/XrdAdaptor/src/XrdSource.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok, code-checks-approved

#34991 Backport XrootD 5.3.1 PR to master from DEVEL
  Utilities/XrdAdaptor/BuildFile.xml
  Utilities/XrdAdaptor/plugins/BuildFile.xml
  Utilities/XrdAdaptor/plugins/XrdStorageMaker.cc
  Utilities/XrdAdaptor/src/XrdHostHandler.hh
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#36624 Run3-gex109E Avoid compilation warnings in some Validation classes in EventGenerator, Mixing and MtdValidation
  Validation/EventGenerator/interface/DuplicationChecker.h
  Validation/EventGenerator/interface/WValidation.h
  Validation/Mixing/interface/TestSuite.h
  Validation/Mixing/src/GlobalTest.cc
  Validation/Mixing/src/MixCollectionValidation.cc
  Validation/MtdValidation/plugins/Primary4DVertexValidation.cc
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36663 Run3-gex110X Take care of Carl's comment for PR #36648
  Geometry/ForwardCommonData/data/dd4hep/testForwardGeometry.xml
  Geometry/ForwardCommonData/data/pixfwd/2021/v1/pixfwd.xml
  Geometry/ForwardCommonData/python/testForwardXML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36664 Run3-gex111X Small fix for muon numbering to be used for Run3 MC with demo chambers
  Geometry/MuonCommonData/data/muonNumbering/2021/v5/muonNumbering.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36659 Fixed INCLXX physics configurations
  SimG4Core/Geometry/src/DDG4ProductionCuts.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_EMM.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_INCLXX_HP_EMM.cc
  SimG4Core/SaveSimTrackAction/src/SaveSimTrack.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36172 HGCAL Pattern Recognition using FastJet
  Configuration/ProcessModifiers/python/fastJetTICL_cff.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  RecoHGCal/TICL/plugins/BuildFile.xml
  RecoHGCal/TICL/plugins/PatternRecognitionPluginFactory.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyFastJet.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyFastJet.h
  RecoHGCal/TICL/plugins/TrackstersProducer.cc
  RecoHGCal/TICL/python/FastJetStep_cff.py
  RecoHGCal/TICL/python/iterativeTICL_cff.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, hgcal-dpg-approved

#36658 fixes for recent updates to `CkfTrackCandidateMaker`
  RecoHI/HiTracking/python/hiDetachedQuadStep_cff.py
  RecoHI/HiTracking/python/hiDetachedTripletStep_cff.py
  RecoHI/HiTracking/python/hiHighPtTripletStep_cff.py
  RecoHI/HiTracking/python/hiJetCoreRegionalStep_cff.py
  RecoHI/HiTracking/python/hiLowPtQuadStep_cff.py
  RecoHI/HiTracking/python/hiLowPtTripletStep_cff.py
  RecoHI/HiTracking/python/hiPixelPairStep_cff.py
  RecoTracker/CkfPattern/python/GroupedCkfTrajectoryBuilder_cfi.py
  RecoTracker/ConversionSeedGenerators/python/ConversionStep2_cff.py
  RecoTracker/IterativeTracking/python/DetachedQuadStep_cff.py
  RecoTracker/IterativeTracking/python/DetachedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/DisplacedGeneralStep_cff.py
  RecoTracker/IterativeTracking/python/HighPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/InitialStepPreSplitting_cff.py
  RecoTracker/IterativeTracking/python/InitialStep_cff.py
  RecoTracker/IterativeTracking/python/JetCoreRegionalStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtBarrelTripletStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtForwardTripletStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtQuadStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/MixedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/MuonSeededStep_cff.py
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoTracker/IterativeTracking/python/TobTecStep_cff.py
  RecoTracker/SpecialSeedGenerators/python/cosmicDC_cff.py
  TrackingTools/GsfTracking/python/CkfElectronCandidateMaker_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36668 fix axis label titles in `Phase2ITValidateRecHitBase`
  Validation/SiTrackerPhase2V/src/Phase2ITValidateRecHitBase.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36323 Include FSR for electrons (in addition to muons)
  CommonTools/RecoUtils/plugins/LeptonFSRProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/fsrPhotons_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved, xpog-approved

#36645 [HGCAL] Updates due to V16 geometry
  SimTracker/TrackerMaterialAnalysis/test/dEdxWeights.ipynb
  Validation/Geometry/data/hgcalMaterials.l0
  Validation/Geometry/data/hgcalMaterials.x0
  Validation/Geometry/interface/MaterialBudgetData.h
  Validation/Geometry/python/plot_hgcal_utils.py
  Validation/Geometry/src/MaterialBudgetCategorizer.cc
  Validation/Geometry/src/MaterialBudgetData.cc
  Validation/Geometry/src/MaterialBudgetHGCalHistos.cc
  Validation/HGCalValidation/python/hgcalHtml.py
  Validation/HGCalValidation/scripts/hgcalPerformanceValidation.py
Labels: dqm-approved, geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36672 Drop type specs for GEM
  DQM/GEM/python/gemEfficiencyAnalyzerCosmics_cfi.py
  DQM/GEM/python/gemEfficiencyAnalyzer_cfi.py
  DQM/GEM/python/gemEfficiencyHarvesterCosmics_cfi.py
  DQM/GEM/python/gemEfficiencyHarvester_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36633 EventSetupInitTrait can now have state
  CommonTools/CandAlgos/interface/CandCombiner.h
  CommonTools/RecoAlgos/interface/CandidateProducer.h
  CommonTools/UtilAlgos/interface/AssociatedVariableCollectionSelector.h
  CommonTools/UtilAlgos/interface/EventSetupInitTrait.h
  CommonTools/UtilAlgos/interface/ObjectSelectorBase.h
  CommonTools/UtilAlgos/interface/ObjectSelectorProducer.h
  CommonTools/UtilAlgos/interface/SingleElementCollectionRefSelector.h
  CommonTools/UtilAlgos/interface/SingleElementCollectionSelector.h
  PhysicsTools/RecoAlgos/interface/MassKinFitterCandProducer.h
  PhysicsTools/RecoAlgos/plugins/CandCommonVertexFitter.h
  PhysicsTools/RecoAlgos/plugins/CandKinematicVertexFitter.h
  PhysicsTools/RecoAlgos/plugins/ConstrainedFitCandProducer.h
Labels: analysis-pending, reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved

#36687 Move HeterogeneousCore code to use oneapi/tbb headers
  HeterogeneousCore/CUDAServices/plugins/NVProfilerService.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#36688 Moved Mixing code to use oneapi/tbb headers
  Mixing/Base/src/SecondaryEventProvider.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36683 Move HLTrigger to use oneapi/tbb headers
  HLTrigger/HLTcore/interface/TriggerSummaryProducerAOD.h
  HLTrigger/Timer/plugins/FastTimerService.h
  HLTrigger/Timer/plugins/ThroughputService.h
  HLTrigger/special/plugins/HLTLogMonitorFilter.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36677 Removed unnecessary headers in SimG4Core/Application
  SimG4Core/Application/interface/RunManagerMTWorker.h
  SimG4Core/Application/src/RunManagerMTWorker.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36681 Move GeneratorInterface to use oneapi/tbb headers
  GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36678 Move PhysicsTools to use oneapi/tbb headers
  PhysicsTools/MVAComputer/interface/ProcessRegistry.h
  PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc
  PhysicsTools/TensorFlow/interface/TBBThreadPool.h
Labels: analysis-pending, reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved, xpog-approved

#36652 Run3-sim102 Make runtime variables to allow/disallow creation of SimHits for demonstration chambers
  SimG4CMS/Muon/interface/MuonSensitiveDetector.h
  SimG4CMS/Muon/plugins/MuonSensitiveDetectorBuilder.cc
  SimG4CMS/Muon/src/MuonSensitiveDetector.cc
  SimG4Core/Application/python/g4SimHits_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36690 Added a unique ID to ComponentDescription
  FWCore/Framework/interface/ComponentDescription.h
  FWCore/Framework/src/ComponentMaker.cc
  FWCore/Framework/src/EventSetupProviderMaker.cc
  FWCore/Framework/test/dependentrecord_t.cppunit.cc
  FWCore/Framework/test/eventsetup_t.cppunit.cc
  FWCore/Framework/test/eventsetupplugin_t.cppunit.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36689 Move Reco code to use oneapi/tbb headers
  RecoHGCal/TICL/plugins/PatternRecognitionbyCLUE3D.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalCLUEAlgo.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalImagingAlgo.cc
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTracker/CkfPattern/src/CkfTrackCandidateMakerBase.cc
  RecoTracker/MkFit/plugins/MkFitProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36686 Move common code to use oneapi/tbb headers
  CommonTools/Utils/interface/MethodInvoker.h
  DataFormats/PatCandidates/src/TriggerObjectStandAlone.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36682 Move EventFilter to use oneapi/tbb headers
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/interface/FedRawDataInputSource.h
  EventFilter/Utilities/src/DataPoint.cc
Labels: daq-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36674 Drop type specs for Muon and RecoB
  DQMOffline/Muon/python/muonCosmicAnalyzer_cff.py
  DQMOffline/Muon/python/muonTestSummaryCosmics_cfi.py
  DQMOffline/RecoB/python/PixelVertexMonitor_cff.py
  DQMOffline/RecoB/python/bTagMiniDQM_cff.py
  DQMOffline/RecoB/python/dqmAnalyzer_cff.py
  DQMOffline/RecoB/python/dqmCollector_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36508 `CondTools/SiStrip` unit tests: introduce gain rescaler tool in unit tests
  CondTools/SiStrip/plugins/SiStripApvGainRescaler.cc
  CondTools/SiStrip/test/SiStripApvGainRescaler_cfg.py
  CondTools/SiStrip/test/testBuildersReaders.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36628 Migrate to EventSetup with ESGetToken in GEMCSCSegmentProducer
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentProducer.cc
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentProducer.h
  RecoLocalMuon/GEMCSCSegment/test/TestGEMCSCSegmentAnalyzer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36675 Move DQM to use oneapi/tbb headers
  DQM/EcalCommon/interface/DQWorker.h
  DQMServices/Core/interface/MonitorElement.h
  DQMServices/FwkIO/plugins/DQMRootOutputModule.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#36680 Run3-gex112 Correction to some of the Forward detector SD's for the dd4hep scenarios
  SimG4CMS/Forward/interface/ForwardName.h
  SimG4CMS/Forward/src/BHMNumberingScheme.cc
  SimG4CMS/Forward/src/Bcm1fSD.cc
  SimG4CMS/Forward/src/BscNumberingScheme.cc
  SimG4CMS/Forward/src/ForwardName.cc
  SimG4CMS/Forward/src/PltSD.cc
  SimG4CMS/Forward/src/TotemT1Organization.cc
  SimG4CMS/Forward/src/TotemT2OrganizationGem.cc
  SimG4CMS/Forward/src/ZdcNumberingScheme.cc
  SimG4CMS/Forward/src/ZdcSD.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36632 [8_0_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files
  IOPool/Input/src/EmbeddedRootSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootInputFileSequence.cc
  IOPool/Input/src/RootInputFileSequence.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/SecondaryInput/test/SecondaryProducer.h
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
  Utilities/StorageFactory/interface/StatisticsSenderService.h
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/BuildFile.xml
  Utilities/StorageFactory/test/make_2nd_file_cfg.py
  Utilities/StorageFactory/test/make_test_files_cfg.py
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
  Utilities/StorageFactory/test/test_multi_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_multiple_files_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_secondary_file_statistics_sender_cfg.py
  Utilities/StorageFactory/test/test_single_file_statistics_sender_cfg.py
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36696 Fix TEST_DIR in a CalibPPS/TimingCalibration unit test
  CalibPPS/TimingCalibration/test/test_timing_LUT_cal.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36695 get rid of CMSDEPRECATED_X warnings from `EventFilter/Si*RawToDigi`
  EventFilter/SiPixelRawToDigi/test/FedErrorDumper.cc
  EventFilter/SiPixelRawToDigi/test/SiPixelRawDumper.cc
  EventFilter/SiPixelRawToDigi/test/findHotPixels.cc
  EventFilter/SiStripRawToDigi/test/plugins/SiStripDigiAnalyzer.cc
  EventFilter/SiStripRawToDigi/test/plugins/SiStripDigiAnalyzer.h
  EventFilter/SiStripRawToDigi/test/plugins/SiStripFEDRawDataAnalyzer.cc
  EventFilter/SiStripRawToDigi/test/plugins/SiStripFEDRawDataAnalyzer.h
  EventFilter/SiStripRawToDigi/test/plugins/SiStripTrivialClusterSource.cc
  EventFilter/SiStripRawToDigi/test/plugins/SiStripTrivialClusterSource.h
  EventFilter/SiStripRawToDigi/test/plugins/SiStripTrivialDigiSource.cc
  EventFilter/SiStripRawToDigi/test/plugins/SiStripTrivialDigiSource.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36676 Moved DetectorDescription/Core to use oneapi/tbb headers
  DetectorDescription/Core/interface/DDName.h
  DetectorDescription/Core/interface/DDValue.h
  DetectorDescription/Core/src/StoresInstantiation.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#36580 [8_0_X] Support vector<string> data products in friendly class name
  FWCore/Utilities/src/FriendlyName.cc
  FWCore/Utilities/test/friendlyname_t.cppunit.cpp
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36701 use std::isnan to avoid cs8 + boost1.78.0 build errors
  CondTools/RunInfo/src/LHCInfoPopConSourceHandler.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36643 L1T run-3: Store EMTF displacement info in L1TNtuples TFTree
  L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeTfMuon.h
  L1Trigger/L1TNtuples/plugins/L1UpgradeTfMuonTreeProducer.cc
  L1Trigger/L1TNtuples/src/L1AnalysisL1UpgradeTfMuon.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36446 ECAL TPG Parameter Builder changes for double weights mechanism
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGDBApp.cc
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGDBApp.h
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.h
  CalibCalorimetry/EcalTPGTools/test/fillOfflineTPGDBfromFile_beamv7.py
  CalibCalorimetry/EcalTPGTools/test/produceTPGParameters_beamv7.py
  OnlineDB/EcalCondDB/sql/trigger_add_doubleweights.sql
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTrigPrimESProducer.cc
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTrigPrimESProducer.h
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTrigPrimESProducer_cff.py
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTrigPrimESProducer_craft_cff.py
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTrigPrimESProducer_mc_cff.py
Labels: alca-approved, l1-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36642 L1T run-3: updated L1T boosted jets
  L1Trigger/L1TCaloLayer1/plugins/L1TCaloSummary.cc
  L1Trigger/L1TCaloLayer1/python/uct2016EmulatorDigis_cfi.py
  L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36671 Run3-alca213X Modify many of the loops as Range based loops in Calibration/HcalCalibAlgos
  Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonHighEtaAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalHBHENewMuonAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrackAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkSimAnalyzer.cc
  Calibration/HcalCalibAlgos/test/HcalHBHEMuonSimAnalyzer.cc
  Calibration/HcalCalibAlgos/test/HcalIsoTrackAnalysis.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36641 Run3-alca214 Test automatic setting ECAL RecHit thresholds as defined by PFlow group
  Calibration/HcalCalibAlgos/python/hcalTestThreshold_cff.py
  Calibration/HcalCalibAlgos/test/BuildFile.xml
  Calibration/HcalCalibAlgos/test/HcalTestThreshold.cc
  Calibration/HcalCalibAlgos/test/python/hcalTestThreshold_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36685 Move conditions code to use oneapi/tbb headers
  CalibCalorimetry/EcalLaserCorrection/interface/EcalLaserDbService.h
  CondCore/Utilities/bin/conddb_test_gt_perf.cpp
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#36710 Include PF HLT Calibration and new EGM Regression in mcRun3 and mcRun4 GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36711 [12.2.X] Further optimization of the SiPixel LA PCL workflow
  CalibTracker/SiPixelLorentzAngle/interface/SiPixelLorentzAngleCalibrationStruct.h
  CalibTracker/SiPixelLorentzAngle/python/SiPixelLorentzAnglePCLHarvester_cfi.py
  CalibTracker/SiPixelLorentzAngle/python/SiPixelLorentzAnglePCLWorker_cfi.py
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAngle.cc
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLHarvester.cc
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLWorker.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#36579 Removed CMS deprecated warnings from `RecoLocalTracker`
  RecoLocalTracker/Phase2TrackerRecHits/test/RecHitsValidation.cc
  RecoLocalTracker/SiPhase2Clusterizer/test/ClustersValidation.cc
  RecoLocalTracker/SiPhase2VectorHitBuilder/test/ClustersValidationTGraph.cc
  RecoLocalTracker/SiPhase2VectorHitBuilder/test/VectorHitsBuilderValidation.cc
  RecoLocalTracker/SiPhase2VectorHitBuilder/test/VectorHitsBuilderValidation.h
  RecoLocalTracker/SiPixelClusterizer/test/ReadPixClusters.cc
  RecoLocalTracker/SiPixelClusterizer/test/TestClusters.cc
  RecoLocalTracker/SiPixelClusterizer/test/TestPixTracks.cc
  RecoLocalTracker/SiPixelClusterizer/test/TestWithTracks.cc
  RecoLocalTracker/SiPixelClusterizer/test/Triplet.cc
  RecoLocalTracker/SiPixelRecHits/test/CPEAccessTester.cc
  RecoLocalTracker/SiPixelRecHits/test/ReadPixelRecHit.cc
  RecoLocalTracker/SiPixelRecHits/test/ReadPixelRecHit.h
  RecoLocalTracker/SiStripClusterizer/test/ClusterRefinerTagMCmerged.cc
  RecoLocalTracker/SiStripClusterizer/test/ClusterRefinerTagMCmerged.h
  RecoLocalTracker/SiStripClusterizer/test/ClusterizerUnitTester.cc
  RecoLocalTracker/SiStripClusterizer/test/ClusterizerUnitTester.h
  RecoLocalTracker/SiStripClusterizer/test/ClusterizerUnitTesterESProducer.cc
  RecoLocalTracker/SiStripClusterizer/test/ClusterizerUnitTesterESProducer.h
  RecoLocalTracker/SiStripClusterizer/test/CompareClusters.cc
  RecoLocalTracker/SiStripClusterizer/test/CompareClusters.h
  RecoLocalTracker/SiStripClusterizer/test/SealModules.cc
  RecoLocalTracker/SiStripClusterizer/test/SiStripApproximatedClustersDump.cc
  RecoLocalTracker/SiStripClusterizer/test/SiStripApproximatedClustersDump.h
  RecoLocalTracker/SiStripClusterizer/test/StripByStripTestDriver.cc
  RecoLocalTracker/SiStripClusterizer/test/StripByStripTestDriver.h
  RecoLocalTracker/SiStripZeroSuppression/interface/SiStripAPVRestorer.h
  RecoLocalTracker/SiStripZeroSuppression/src/SiStripAPVRestorer.cc
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripBaselineAnalyzer.cc
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripBaselineComparator.cc
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripHybridFormatAnalyzer.cc
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripMeanCMExtractor.cc
  RecoLocalTracker/SubCollectionProducers/test/ClusterAnalyzer.cc
  RecoLocalTracker/SubCollectionProducers/test/ClusterMCsplitStrips.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36691 Drop type specs for L1Trigger
  DQMOffline/L1Trigger/python/L1TEGammaEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TEGammaOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TEmulatorMonitorOffline_cff.py
  DQMOffline/L1Trigger/python/L1TEtSumEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TEtSumJetOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TJetEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TMuonDQMEfficiency_cff.py
  DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TSync_Harvest_cff.py
  DQMOffline/L1Trigger/python/L1TSync_Offline_cff.py
  DQMOffline/L1Trigger/python/L1TTauEfficiency_cfi.py
  DQMOffline/L1Trigger/python/L1TTauOffline_cfi.py
  DQMOffline/L1Trigger/python/L1TriggerDqmOffline_cff.py
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36717 Updated Exceptions for SIM step
  SimG4Core/Application/interface/ExceptionHandler.h
  SimG4Core/Application/plugins/OscarMTProducer.cc
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/ExceptionHandler.cc
  SimG4Core/Application/src/OscarMTMasterThread.cc
  SimG4Core/Application/src/RunManagerMT.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/Notification/interface/TrackInformationExtractor.h
  SimG4Core/Notification/src/GenParticleInfoExtractor.cc
  SimG4Core/Notification/src/NewTrackAction.cc
  SimG4Core/Notification/src/TrackInformationExtractor.cc
  SimG4Core/Notification/src/TrackWithHistory.cc
  SimG4Core/SensitiveDetector/src/SensitiveDetector.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36714 Fix to 39434.502/501
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelRecHits/python/SiPixelRecHits_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#36553 Expand L1T Shower data vs emulator comparison DQM
  DQM/L1TMonitor/interface/L1TStage2RegionalShower.h
  DQM/L1TMonitor/interface/L1TdeCSCTPGShower.h
  DQM/L1TMonitor/interface/L1TdeStage2RegionalShower.h
  DQM/L1TMonitor/plugins/SealModule.cc
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
  DQM/L1TMonitor/python/L1TStage2RegionalShower_cfi.py
  DQM/L1TMonitor/python/L1TStage2_cff.py
  DQM/L1TMonitor/python/L1TdeStage2EMTF_cff.py
  DQM/L1TMonitor/python/L1TdeStage2RegionalShower_cfi.py
  DQM/L1TMonitor/src/L1TStage2RegionalShower.cc
  DQM/L1TMonitor/src/L1TdeCSCTPGShower.cc
  DQM/L1TMonitor/src/L1TdeStage2RegionalShower.cc
  DQM/L1TMonitor/src/L1TdeStage2Shower.cc
  DQM/L1TMonitorClient/interface/L1TdeCSCTPGShowerClient.h
  DQM/L1TMonitorClient/interface/L1TdeStage2RegionalShowerClient.h
  DQM/L1TMonitorClient/python/L1TStage2EMTFEmulatorClient_cff.py
  DQM/L1TMonitorClient/python/L1TStage2EmulatorMonitorClient_cff.py
  DQM/L1TMonitorClient/python/L1TdeStage2RegionalShowerClient_cfi.py
  DQM/L1TMonitorClient/src/L1TdeCSCTPGShowerClient.cc
  DQM/L1TMonitorClient/src/L1TdeStage2ShowerRegionalClient.cc
  DQM/L1TMonitorClient/src/SealModule.cc
  L1Trigger/L1TMuonEndCap/src/SectorProcessorShower.cc
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36719 [12_2_X] Include PF HLT Calibration and new EGM Regression in mcRun3 and mcRun4 GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved

#36704 Drop type specs for RecoMuon
  Validation/RecoMuon/python/PostProcessorHLT_cff.py
  Validation/RecoMuon/python/PostProcessor_RecoMuonValidator_cff.py
  Validation/RecoMuon/python/RecoMuonValidator_cff.py
  Validation/RecoMuon/python/associators_cff.py
  Validation/RecoMuon/python/histoParameters_cff.py
  Validation/RecoMuon/python/muonValidationHLT_cff.py
  Validation/RecoMuon/python/muonValidation_cff.py
  Validation/RecoMuon/python/selectors_cff.py
  Validation/RecoMuon/python/track_selectors_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36722 bug fix for hltIntegration tests when using a setup menu : 12_3_X
  HLTrigger/Configuration/scripts/hltIntegrationTests
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36666 Add HLT filter to select online pf taus based on their impact parameter
  RecoTauTag/HLTProducers/src/HLTPFTauIPFilter.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36720 Run3-alca215 Provide possibility of using ECAL RecHit thresholds used by particle flow group in Hcal Calibration code
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalIsotrkProducer.cc
  Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksFilter.cc
  Calibration/HcalAlCaRecoProducers/python/alcaHcalIsotrkProducer_cff.py
  Calibration/HcalAlCaRecoProducers/python/alcaIsoTracksFilter_cff.py
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalIsoTrkSimAnalyzer.cc
  Calibration/HcalCalibAlgos/python/hcalIsoTrackStudy_cff.py
  Calibration/HcalCalibAlgos/python/hcalIsoTrkAnalyzer_cff.py
  Calibration/HcalCalibAlgos/python/hcalTestThreshold_cff.py
  Calibration/HcalCalibAlgos/test/HcalIsoTrackAnalysis.cc
  Calibration/HcalCalibAlgos/test/HcalIsoTrackStudy.cc
  Calibration/HcalCalibAlgos/test/python/isoTrackAlCaAnalysis_cfg.py
  Calibration/HcalCalibAlgos/test/python/isoTrackAlCaRecoAnalysis_cfg.py
  Calibration/HcalCalibAlgos/test/python/isoTrackNoHLTAnalysis_cfg.py
  Calibration/HcalCalibAlgos/test/python/isoTrackRecoAnalysis_cfg.py
  Configuration/Eras/python/Modifier_run2_ECAL_2018_cff.py
Labels: alca-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36715 Updated GEMGeometryBuilder to allow GE2/1 demonstrator to be built - Alternative Method
  DQM/GEM/src/GEMDQMBase.cc
  Geometry/GEMGeometry/test/testGE0Geometry_cfg.py
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.cc
  Geometry/GEMGeometryBuilder/test/GEMGeometryDump.cc
  Geometry/GEMGeometryBuilder/test/python/dumpGEMGeometryDDD_cfg.py
Labels: dqm-approved, geometry-approved, fully-signed, tests-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#36354 Backport of "Fix for FastSim decays of exotic-descendent SM particles decaying outside pipe" to 9_4_X
  Configuration/ProcessModifiers/python/fastSimFixLongLivedBug_cff.py
  FastSimulation/SimplifiedGeometryPropagator/interface/Decayer.h
  FastSimulation/SimplifiedGeometryPropagator/interface/ParticleManager.h
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
  FastSimulation/SimplifiedGeometryPropagator/python/fastSimProducer_cff.py
  FastSimulation/SimplifiedGeometryPropagator/src/Decayer.cc
  FastSimulation/SimplifiedGeometryPropagator/src/ParticleManager.cc
Labels: fastsim-approved, operations-approved, fully-signed, tests-approved, orp-approved

#36353 Backport of "Fix for FastSim decays of exotic-descendent SM particles decaying outside pipe" to 10_2_X
  Configuration/ProcessModifiers/python/fastSimFixLongLivedBug_cff.py
  FastSimulation/SimplifiedGeometryPropagator/interface/Decayer.h
  FastSimulation/SimplifiedGeometryPropagator/interface/ParticleManager.h
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
  FastSimulation/SimplifiedGeometryPropagator/python/fastSimProducer_cff.py
  FastSimulation/SimplifiedGeometryPropagator/src/Decayer.cc
  FastSimulation/SimplifiedGeometryPropagator/src/ParticleManager.cc
Labels: fastsim-approved, operations-approved, fully-signed, tests-approved, orp-approved

#36745 Minor recommended changes to GEMGeometryBuilder
  DQM/GEM/src/GEMDQMBase.cc
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.cc
Labels: dqm-approved, geometry-approved, fully-signed, tests-rejected, orp-approved, upgrade-approved, code-checks-approved

#36738 Fix accessing one-past-the-end element
  HLTrigger/special/plugins/HLTLogMonitorFilter.cc
Labels: hlt-approved, fully-signed, tests-rejected, bug-fix, orp-approved, code-checks-approved

#36746 Remove unnecessary edm ParameterSet existAs or exist in RecoMuon/{L2MuonProducer}
  RecoMuon/L2MuonProducer/plugins/L2MuonProducer.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36755 Run3-gex112Z Try to address missing chambers for RPC
  Geometry/MuonCommonData/data/rpcf/2021/v1/rpcf.xml
Labels: geometry-approved, fully-signed, tests-started, orp-approved, code-checks-approved

#36767 Fix HcalTestThreshold.cc: validId is used before declaration
  Calibration/HcalCalibAlgos/test/HcalTestThreshold.cc
Labels: alca-approved, fully-signed, tests-rejected, bug-fix, orp-approved, code-checks-approved

#36756 Fix of the L1CaloTowerTreeProducer and L1uGTTreeProducer to avoid an exception MustUseESGetToken
  L1Trigger/L1TNtuples/README.md
  L1Trigger/L1TNtuples/plugins/L1CaloTowerTreeProducer.cc
  L1Trigger/L1TNtuples/plugins/L1uGTTreeProducer.cc
Labels: l1-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36766 Update final Run3 MC geometry (reprise)
  Configuration/AlCa/python/autoCond.py
  Configuration/AlCa/python/autoCondModifiers.py
Labels: alca-approved, fully-signed, tests-rejected, orp-approved, urgent, requires-external, code-checks-approved

#36750 Run3-gex112Y Make the default creation of Simhits for Demo chambers to be true as required by the respective DPG's
  SimG4Core/Application/python/g4SimHits_cfi.py
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, urgent, requires-external, code-checks-approved

#36654 Run3-gex108x Modify all Run3 geometry scenarios by including demonstration chambers of GE21 & RPC, and detectors in the forrward region (BHM, PLT, BCMF) plus removing BSC
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
Labels: geometry-approved, pending-signatures, tests-rejected, orp-approved, urgent, upgrade-pending, requires-external, code-checks-approved

#36765 Turn off warnings for missing chamber in GEM GE2/1 demonstrator geometry
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.cc
  Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.h
Labels: geometry-approved, fully-signed, tests-rejected, orp-approved, urgent, upgrade-approved, code-checks-approved

#36743 Improve exception message from a ROOT read
  IOPool/Input/src/RootDelayedReader.cc
  IOPool/Input/src/RootTree.cc
Labels: core-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36741 Handle all exception types in Path::workerFinished
  FWCore/Framework/src/Path.cc
Labels: core-approved, fully-signed, tests-rejected, bug-fix, orp-approved, code-checks-approved

#36739 Properly propate exception from DelayedReader
  FWCore/Framework/interface/EventPrincipal.h
  FWCore/Framework/src/EventPrincipal.cc
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Framework/test/stubs/ToyModules.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/DelayedReaderThrowingSource.cc
  FWCore/Integration/test/delayedreader_throw_cfg.py
  FWCore/Integration/test/delayedreader_throw_test.sh
  FWCore/Sources/interface/IDGeneratorSourceBase.h
Labels: core-approved, fully-signed, tests-rejected, bug-fix, orp-approved, code-checks-approved

#36736 Run3-gex113A Remove compilation warnings in CaloOnlineTools/EcalTools
  CaloOnlineTools/EcalTools/plugins/EcalBxOrbitNumberGrapher.h
  CaloOnlineTools/EcalTools/plugins/EcalDCCHeaderDisplay.h
  CaloOnlineTools/EcalTools/plugins/EcalExclusiveTrigFilter.h
  CaloOnlineTools/EcalTools/plugins/EcalFEDWithCRCErrorProducer.cc
  CaloOnlineTools/EcalTools/plugins/EcalHexDisplay.h
  CaloOnlineTools/EcalTools/plugins/EcalPnGraphs.cc
  CaloOnlineTools/EcalTools/plugins/EcalPnGraphs.h
  CaloOnlineTools/EcalTools/plugins/EcalPulseShapeGrapher.h
  CaloOnlineTools/EcalTools/plugins/EcalRecHitsFilter.cc
  CaloOnlineTools/EcalTools/plugins/EcalRecHitsFilter.h
Labels: alca-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36752 get rid of `CMSDEPRECATED_X` warnings from `DQM/Track*`
  DQM/TrackerMonitorTrack/interface/MonitorTrackResiduals.h
  DQM/TrackingMonitor/interface/GetLumi.h
  DQM/TrackingMonitor/interface/TrackAnalyzer.h
  DQM/TrackingMonitor/interface/TrackBuildingAnalyzer.h
  DQM/TrackingMonitor/interface/TrackEfficiencyMonitor.h
  DQM/TrackingMonitor/interface/TrackSplittingMonitor.h
  DQM/TrackingMonitor/interface/VertexMonitor.h
  DQM/TrackingMonitor/interface/dEdxAnalyzer.h
  DQM/TrackingMonitor/interface/dEdxHitAnalyzer.h
  DQM/TrackingMonitor/src/GetLumi.cc
  DQM/TrackingMonitor/src/TrackSplittingMonitor.cc
  DQM/TrackingMonitor/src/VertexMonitor.cc
  DQM/TrackingMonitor/src/dEdxAnalyzer.cc
  DQM/TrackingMonitorSource/interface/TrackToTrackComparisonHists.h
  DQM/TrackingMonitorSource/interface/TrackTypeMonitor.h
  DQM/TrackingMonitorSource/plugins/StandaloneTrackMonitor.cc
Labels: dqm-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36655 Fixing issue of PS cluster matched to >1 EE cluster in DBG_X IBs
  RecoEcal/EgammaClusterAlgos/src/PFECALSuperClusterAlgo.cc
  RecoTracker/TrackProducer/src/TrackProducerAlgorithm.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36762 Move Pixel Bad FED Channel simulation related plugins to `CondTools`
  CondTools/SiPixel/plugins/FastSiPixelFEDChannelContainerFromQuality.cc
  CondTools/SiPixel/plugins/SiPixelBadFEDChannelSimulationSanityChecker.cc
  CondTools/SiPixel/plugins/SiPixelFEDChannelContainerFromQualityConverter.cc
  CondTools/SiPixel/plugins/SiPixelFEDChannelContainerTestReader.cc
  CondTools/SiPixel/plugins/SiPixelFEDChannelContainerWriteFromASCII.cc
  CondTools/SiPixel/plugins/SiPixelQualityProbabilitiesTestReader.cc
  CondTools/SiPixel/plugins/SiPixelQualityProbabilitiesTestWriter.cc
  CondTools/SiPixel/plugins/SiPixelQualityProbabilitiesWriteFromASCII.cc
  CondTools/SiPixel/test/BuildFile.xml
  CondTools/SiPixel/test/FastSiPixelFEDChannelContainerFromQuality_cfg.py
  CondTools/SiPixel/test/SiPixelBadFEDChannelSimulationSanityChecker_cfg.py
  CondTools/SiPixel/test/SiPixelFEDChannelContainerFromQualityConverter_cfg.py
  CondTools/SiPixel/test/SiPixelFEDChannelContainerTestReader_cfg.py
  CondTools/SiPixel/test/SiPixelFEDChannelContainerWriteFromASCII_cfg.py
  CondTools/SiPixel/test/SiPixelQualityProbabilitiesTestReader_cfg.py
  CondTools/SiPixel/test/SiPixelQualityProbabilitiesTestWriter_cfg.py
  CondTools/SiPixel/test/SiPixelQualityProbabilitiesWriteFromASCII_cfg.py
  CondTools/SiPixel/test/createTestDBObjects.sh
Labels: alca-approved, fully-signed, tests-rejected, db-approved, orp-approved, code-checks-approved

#36702 PPS renaming AlCa Prompt producers and PPSCalTrackBasedSel AlCa Reco to autoAlca.py
  CalibPPS/AlignmentGlobal/python/ALCARECOPPSAlignment_Output_cff.py
  CalibPPS/AlignmentGlobal/python/ALCARECOPromptCalibProdPPSAlignment_Output_cff.py
  CalibPPS/AlignmentGlobal/python/ALCARECOPromptCalibProdPPSAlignment_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSDiamondSampicTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPromptCalibProdPPSDiamondSampicTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPromptCalibProdPPSDiamondSampicTimingCalib_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPromptCalibProdPPSTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPromptCalibProdPPSTimingCalib_cff.py
  Configuration/AlCa/python/autoAlca.py
  Configuration/AlCa/python/autoPCL.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, operations-approved, fully-signed, tests-rejected, pdmv-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#36732 Support arbitrary path names in the TriggerResultsFilter in HLTPathStatus mode
  HLTrigger/HLTcore/interface/TriggerExpressionConstant.h
  HLTrigger/HLTcore/interface/TriggerExpressionData.h
  HLTrigger/HLTcore/interface/TriggerExpressionEvaluator.h
  HLTrigger/HLTcore/interface/TriggerExpressionOperators.h
  HLTrigger/HLTcore/interface/TriggerExpressionPathReader.h
  HLTrigger/HLTcore/src/TriggerExpressionData.cc
  HLTrigger/HLTfilters/plugins/TriggerResultsFilter.cc
  HLTrigger/HLTfilters/plugins/TriggerResultsFilter.h
  HLTrigger/HLTfilters/test/BuildFile.xml
  HLTrigger/HLTfilters/test/triggerResultsFilter_by_PathStatus.py
  HLTrigger/HLTfilters/test/triggerResultsFilter_by_TriggerResults.py
Labels: hlt-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36759 Unify bin-edge handling in JetResolutionObject and JetCorrectorParameters
  CondFormats/JetMETObjects/interface/JetResolutionObject.h
Labels: fully-signed, tests-rejected, db-approved, orp-approved, code-checks-approved

#36735 rename `dqmEnv` in `ALCARECOPPSDiamondSampicTimingCalibHarvester_cff`
  CalibPPS/TimingCalibration/python/ALCARECOPPSDiamondSampicTimingCalibHarvester_cff.py
Labels: alca-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36778 [DQM] Fix for DQM merging exception due to duplicated labels
  DQM/DTMonitorModule/src/DTDataIntegrityTask.cc
Labels: dqm-approved, fully-signed, tests-rejected, bug-fix, orp-approved, code-checks-approved

#36775 Run3-sim107A Modify the cfg's in SimG4Core/PrintGeomInfo for an esay operation
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck2026_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckBigXML_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckBigXMLdd4hep_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckCalo_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckEcal_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckHGCal_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckMuon_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckTracker_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck_cfg.py
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36760 Backport to 12_2_X: ECAL TPG Parameter Builder changes for double weights
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGDBApp.cc
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGDBApp.h
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.h
  CalibCalorimetry/EcalTPGTools/test/fillOfflineTPGDBfromFile_beamv7.py
  CalibCalorimetry/EcalTPGTools/test/produceTPGParameters_beamv7.py
  OnlineDB/EcalCondDB/sql/trigger_add_doubleweights.sql
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTrigPrimESProducer.cc
  SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTrigPrimESProducer.h
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTrigPrimESProducer_cff.py
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTrigPrimESProducer_craft_cff.py
  SimCalorimetry/EcalTrigPrimProducers/python/ecalTrigPrimESProducer_mc_cff.py
Labels: alca-approved, l1-approved, fully-signed, tests-rejected, db-approved, orp-approved, backport-ok

#36747 SiStrip Gain2 PCL: Introduce new gain fitting procedure
  CalibTracker/SiStripChannelGain/BuildFile.xml
  CalibTracker/SiStripChannelGain/interface/APVGainStruct.h
  CalibTracker/SiStripChannelGain/interface/SiStripGainsPCLHarvester.h
  CalibTracker/SiStripChannelGain/interface/SiStripGainsPCLWorker.h
  CalibTracker/SiStripChannelGain/plugins/SiStripGainFromCalibTree.cc
  CalibTracker/SiStripChannelGain/plugins/SiStripGainFromData.cc
  CalibTracker/SiStripChannelGain/plugins/SiStripGainsCalibTreeWorker.cc
  CalibTracker/SiStripChannelGain/src/SiStripGainsPCLHarvester.cc
  CalibTracker/SiStripChannelGain/src/SiStripGainsPCLWorker.cc
  CalibTracker/SiStripChannelGain/test/BuildFile.xml
  CalibTracker/SiStripChannelGain/test/Gains_CT_step1.py
  CalibTracker/SiStripChannelGain/test/Gains_CT_step2.py
  CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromCalibTree.cpp
  CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromCalibTree.sh
Labels: alca-approved, fully-signed, tests-rejected, orp-approved, requires-external, code-checks-approved

#36763 Run3-sim107 Modify the test for SimHit comparisons
  SimG4CMS/Calo/macros/MakeHitStudyPlots.C
  SimG4CMS/Calo/plugins/CaloSimHitStudy.cc
  SimG4CMS/Calo/test/python/caloSimHitStudy_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckDD4hep_cfg.py
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36770 Fix to remove object order dependence and update test cfg files
  DQM/Physics/src/ExoticaDQM.cc
  DQM/Physics/test/ExoticaDQM_cfg.py
  DQM/Physics/test/ExoticaDQM_harvesting_cfg.py
Labels: dqm-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36777 Add forgotten SharedResources for TFileService in L1Trigger/L1TNtuples
  L1Trigger/L1TNtuples/plugins/L1CaloTowerTreeProducer.cc
  L1Trigger/L1TNtuples/plugins/L1uGTTreeProducer.cc
Labels: l1-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36772 Fix to allow G4 simulation of the long-lived susy-tau (1000015) decay products
  SimG4Core/Generators/src/Generator.cc
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36784 PPS renaming alca reco producers - backport of PR#36702 to 12_2_X
  CalibPPS/AlignmentGlobal/python/ALCARECOPPSAlignment_Output_cff.py
  CalibPPS/AlignmentGlobal/python/ALCARECOPromptCalibProdPPSAlignment_Output_cff.py
  CalibPPS/AlignmentGlobal/python/ALCARECOPromptCalibProdPPSAlignment_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSDiamondSampicTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPPSTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPromptCalibProdPPSDiamondSampicTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPromptCalibProdPPSDiamondSampicTimingCalib_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPromptCalibProdPPSTimingCalib_Output_cff.py
  CalibPPS/TimingCalibration/python/ALCARECOPromptCalibProdPPSTimingCalib_cff.py
  Configuration/AlCa/python/autoAlca.py
  Configuration/AlCa/python/autoPCL.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: operations-pending, alca-approved, pending-signatures, tests-rejected, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#36737 Fixed static analyzer warnings in SimG4Core/Notification and clean-up Alignment/LaserAlignmentSimulation
  Alignment/LaserAlignmentSimulation/src/LaserOpticalPhysicsList.cc
  SimG4Core/Notification/src/GenParticleInfoExtractor.cc
  SimG4Core/Notification/src/NewTrackAction.cc
  SimG4Core/Notification/src/TrackInformationExtractor.cc
Labels: alca-approved, simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36779 [DQM] Fix for DQM merging exception due to duplicated labels 12_2_X
  DQM/DTMonitorModule/src/DTDataIntegrityTask.cc
Labels: dqm-approved, fully-signed, tests-rejected, bug-fix, orp-approved, backport-ok

#36733 Support arbitrary path names in the TriggerResultsFilter in HLTPathStatus mode [12.2.x]
  HLTrigger/HLTcore/interface/TriggerExpressionConstant.h
  HLTrigger/HLTcore/interface/TriggerExpressionData.h
  HLTrigger/HLTcore/interface/TriggerExpressionEvaluator.h
  HLTrigger/HLTcore/interface/TriggerExpressionOperators.h
  HLTrigger/HLTcore/interface/TriggerExpressionPathReader.h
  HLTrigger/HLTcore/src/TriggerExpressionData.cc
  HLTrigger/HLTfilters/plugins/TriggerResultsFilter.cc
  HLTrigger/HLTfilters/plugins/TriggerResultsFilter.h
  HLTrigger/HLTfilters/test/BuildFile.xml
  HLTrigger/HLTfilters/test/triggerResultsFilter_by_PathStatus.py
  HLTrigger/HLTfilters/test/triggerResultsFilter_by_TriggerResults.py
Labels: hlt-approved, fully-signed, tests-rejected, orp-approved, backport-ok

#36465 Remove Event Interpretation (EI) from relval steps
  Calibration/IsolatedParticles/test/python/HLT_IsoTrig_Data_New1.py
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/DataProcessing/python/Impl/hcalnzs.py
  Configuration/DataProcessing/python/Impl/hcalnzsEra_Run2_2016.py
  Configuration/DataProcessing/python/Impl/hcalnzsEra_Run2_2017.py
  Configuration/DataProcessing/python/Impl/hcalnzsEra_Run2_2018.py
  Configuration/DataProcessing/python/Impl/hcalnzsEra_Run2_2018_highBetaStar.py
  Configuration/DataProcessing/python/Impl/hcalnzsEra_Run2_25ns.py
  Configuration/DataProcessing/python/Impl/hcalnzsEra_Run3.py
  Configuration/DataProcessing/python/Impl/pp.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2016.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2016_pA.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2016_trackingLowPU.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2017.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2017_ppRef.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2017_pp_on_XeXe.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2017_trackingLowPU.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2017_trackingOnly.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2018.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2018_highBetaStar.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_2018_pp_on_AA.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_25ns.py
  Configuration/DataProcessing/python/Impl/ppEra_Run2_50ns.py
  Configuration/DataProcessing/python/Impl/ppEra_Run3.py
  Configuration/DataProcessing/python/Impl/trackingOnly.py
  Configuration/DataProcessing/python/Impl/trackingOnlyEra_Run2_2017.py
  Configuration/DataProcessing/python/Impl/trackingOnlyEra_Run2_2018.py
  Configuration/DataProcessing/python/Impl/trackingOnlyEra_Run2_2018_highBetaStar.py
  Configuration/DataProcessing/python/Impl/trackingOnlyEra_Run3.py
  Configuration/DataProcessing/python/Reco.py
  Configuration/EventContent/python/EventContent_cff.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/EventInterpretation.py
  DQMOffline/Trigger/python/BTaggingMonitor_cfi.py
  DQMOffline/Trigger/python/DiJetMonitor_cfi.py
  DQMOffline/Trigger/python/HTMonitor_cfi.py
  DQMOffline/Trigger/python/HiggsMonitoring_cfi.py
  DQMOffline/Trigger/python/METMonitor_cfi.py
  DQMOffline/Trigger/python/METplusTrackMonitor_cfi.py
  DQMOffline/Trigger/python/MjjMonitor_cfi.py
  DQMOffline/Trigger/python/MssmHbbMonitoring_cfi.py
  DQMOffline/Trigger/python/MuonMonitor_cfi.py
  DQMOffline/Trigger/python/PhotonMonitor_cfi.py
  DQMOffline/Trigger/python/RazorMonitor_cfi.py
  DQMOffline/Trigger/python/SoftdropMonitor_cfi.py
  DQMOffline/Trigger/python/SusyMonitor_cfi.py
  DQMOffline/Trigger/python/TopMonitor_cfi.py
  HLTrigger/Configuration/test/cmsDriver.csh
  Utilities/ReleaseScripts/scripts/addOnTests.py
Labels: alca-approved, core-approved, dqm-approved, hlt-approved, operations-approved, fully-signed, tests-rejected, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#36757 get rid of `CMSDEPRECATED_X` warnings from `TrackPropagation`
  TrackPropagation/Geant4e/test/Geant4ePropagatorAnalyzer.cc
  TrackPropagation/RungeKutta/test/RKTest.cc
  TrackPropagation/SteppingHelixPropagator/test/SteppingHelixPropagatorAnalyzer.cc
Labels: reconstruction-approved, simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36639 CHS and PUPPI track-vertex-association for Run3
  CommonTools/ParticleFlow/interface/PFPileUpAlgo.h
  CommonTools/ParticleFlow/plugins/PFNoPileUpPacked.cc
  CommonTools/ParticleFlow/plugins/PFPileUp.cc
  CommonTools/ParticleFlow/python/PFBRECO_cff.py
  CommonTools/ParticleFlow/python/Tools/enablePileUpCorrection.py
  CommonTools/ParticleFlow/python/pfCHS_cff.py
  CommonTools/ParticleFlow/python/pfNoPileUpJME_cff.py
  CommonTools/ParticleFlow/python/pfPileUp_cfi.py
  CommonTools/ParticleFlow/src/PFPileUpAlgo.cc
  CommonTools/PileupAlgos/plugins/PuppiProducer.cc
  CommonTools/PileupAlgos/python/Puppi_cff.py
  CommonTools/RecoAlgos/interface/PrimaryVertexAssignment.h
  CommonTools/RecoAlgos/plugins/PrimaryVertexSorter.h
  CommonTools/RecoAlgos/python/sortedPFPrimaryVertices_cfi.py
  CommonTools/RecoAlgos/python/sortedPackedPrimaryVertices_cfi.py
  CommonTools/RecoAlgos/python/sortedPrimaryVertices_cfi.py
  CommonTools/RecoAlgos/src/PrimaryVertexAssignment.cc
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/slimming/puppiForMET_cff.py
  PhysicsTools/PatAlgos/python/tools/jetCollectionTools.py
  PhysicsTools/PatAlgos/test/miniAOD/example_jet_and_met.py
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
  RecoHI/Configuration/python/Reconstruction_hiPF_cff.py
  RecoMET/Configuration/python/RecoPFMET_cff.py
  RecoMET/METFilters/test/filters_cfg.py
  RecoParticleFlow/Configuration/python/RecoParticleFlow_cff.py
Labels: reconstruction-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#35953 Restructure VID Python/FWLite code and avoid generating dictionaries for `Reco*/*Identification` packages
  FWCore/Utilities/interface/thread_safety_macros.h
  PhysicsTools/SelectorUtils/interface/MakePtrFromCollection.h
  PhysicsTools/SelectorUtils/interface/MakePyVIDClassBuilder.h
  PhysicsTools/SelectorUtils/interface/PrintVIDToString.h
  PhysicsTools/SelectorUtils/python/VIDSelectorBase.py
  PhysicsTools/SelectorUtils/src/classes.h
  PhysicsTools/SelectorUtils/src/classes_def.xml
  PhysicsTools/SelectorUtils/test/BuildFile.xml
  PhysicsTools/SelectorUtils/test/runPythonTests.sh
  PhysicsTools/SelectorUtils/test/testPhysicsToolsSelectorUtilsPythonTestsDriver.cpp
  PhysicsTools/SelectorUtils/test/test_vid_selectors.py
  RecoEgamma/EgammaTools/interface/AnyMVAEstimatorRun2Base.h
  RecoEgamma/EgammaTools/interface/AnyMVAEstimatorRun2Factory.h
  RecoEgamma/EgammaTools/interface/MVAValueMapProducer.h
  RecoEgamma/EgammaTools/src/AnyMVAEstimatorRun2Base.cc
  RecoEgamma/ElectronIdentification/interface/ElectronMVAEstimatorRun2.h
  RecoEgamma/ElectronIdentification/python/FWLite.py
  RecoEgamma/ElectronIdentification/python/VIDElectronSelector.py
  RecoEgamma/ElectronIdentification/src/ElectronMVAEstimatorRun2.cc
  RecoEgamma/ElectronIdentification/src/classes.h
  RecoEgamma/ElectronIdentification/src/classes_def.xml
  RecoEgamma/PhotonIdentification/plugins/PhotonMVAEstimator.cc
  RecoEgamma/PhotonIdentification/python/VIDPhotonSelector.py
  RecoEgamma/PhotonIdentification/src/classes.h
  RecoEgamma/PhotonIdentification/src/classes_def.xml
  RecoMuon/MuonIdentification/interface/VersionedMuonSelector.h
  RecoMuon/MuonIdentification/python/VIDMuonSelector.py
  RecoMuon/MuonIdentification/src/classes.h
  RecoMuon/MuonIdentification/src/classes_def.xml
Labels: core-approved, reconstruction-approved, fully-signed, tests-rejected, orp-approved, requires-external, code-checks-approved

#36758 Updated PR for CorrWithOverlapRemovalCondition.cc
  L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondition.cc
Labels: l1-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36184 Extending SeedingHitSet & SeedGeneratorFromProtoTracksEDProducer
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletEDProducerT.cc
  RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromProtoTracksEDProducer.cc
  RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromProtoTracksEDProducer.h
  RecoTracker/TkSeedingLayers/interface/SeedingHitSet.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36796 Fix crash when reporting an unrunnable schedule [12_2]
  FWCore/Framework/src/PathsAndConsumesOfModules.cc
  FWCore/Framework/test/checkForModuleDependencyCorrectness_t.cppunit.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#36795 Backport fix to allow G4 propagation of the long-lived susy-tau (1000015) decay products to CMSSW_10_6_X
  SimG4Core/Generators/src/Generator.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved

#36802 Fix calling methods on nullptr in Concurrent*Filter modules
  GeneratorInterface/Core/interface/ConcurrentGeneratorFilter.h
  GeneratorInterface/Core/interface/ConcurrentHadronizerFilter.h
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36801 Add more module transitions to MessageLogger
  FWCore/MessageService/plugins/MessageLogger.cc
  FWCore/MessageService/plugins/MessageLogger.h
Labels: core-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36713 PPS RecHit nonlinearities compensation for diamond-hptdc
  RecoPPS/Local/interface/CTPPSDiamondRecHitProducerAlgorithm.h
  RecoPPS/Local/plugins/CTPPSDiamondRecHitProducer.cc
  RecoPPS/Local/python/ctppsDiamondLocalReconstruction_cff.py
  RecoPPS/Local/src/CTPPSDiamondRecHitProducerAlgorithm.cc
Labels: alca-approved, reconstruction-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36693 pre-select high purity tracks as input for muon reco in pp_on_AA era
  RecoMuon/Configuration/python/RecoMuonPPonly_cff.py
  RecoMuon/Configuration/python/RecoMuon_cff.py
  RecoMuon/Configuration/python/SETRecoMuon_cff.py
  RecoMuon/GlobalMuonProducer/python/globalMuons_cfi.py
  RecoMuon/GlobalMuonProducer/src/GlobalMuonProducer.cc
  RecoMuon/GlobalTrackFinder/interface/GlobalMuonTrajectoryBuilder.h
  RecoMuon/GlobalTrackFinder/src/GlobalMuonTrajectoryBuilder.cc
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.cc
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.h
  RecoMuon/MuonIdentification/python/earlyMuons_cfi.py
  RecoMuon/MuonIdentification/python/muons1stStep_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36798 Add ESModule tracking to StallMonitor
  FWCore/Concurrency/scripts/edmStreamStallGrapher.py
  FWCore/Concurrency/test/streamGrapher_stallMonitor_cfg.py
  FWCore/Framework/src/EventSetupProvider.cc
  FWCore/ServiceRegistry/interface/ActivityRegistry.h
  FWCore/ServiceRegistry/src/ActivityRegistry.cc
  FWCore/Services/plugins/StallMonitor.cc
Labels: core-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#36805 added VersionedSelector dict mapping to PhysicsTools/SelectorUtils
  Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36794 keep relvals input file order
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36768 ECAL : correction of a minor bug in a Ecal laser tool
  CalibCalorimetry/EcalTrivialCondModules/src/EcalLaserCondTools.cc
  CalibCalorimetry/EcalTrivialCondModules/test/ecalLaserCondTools_cfg.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36812 Update of binning in L1T Shower comparison DQM
  DQM/L1TMonitor/src/L1TdeCSCTPGShower.cc
  DQM/L1TMonitor/src/L1TdeStage2RegionalShower.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36799 Phase2-gex114 Remove duplicate declaration of the constants in Geometry/MTDCommonData
  Geometry/MTDCommonData/data/etl/v6/etl.xml
  Geometry/MTDCommonData/data/etl/v7/etl.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36803 Fix of a check on the geometry in the RPCConeBuilder
  L1Trigger/RPCTrigger/plugins/RPCConeBuilder.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#36789 get rid of deprecation warnings from `RecoVertex` subsystem
  RecoVertex/AdaptiveVertexFinder/interface/TracksClusteringFromDisplacedSeed.h
  RecoVertex/AdaptiveVertexFinder/interface/VertexMerging.h
  RecoVertex/ConfigurableVertexReco/test/CVRTest.cc
  RecoVertex/ConfigurableVertexReco/test/CVRTest.h
  RecoVertex/GaussianSumVertexFit/test/GsfTest.cc
  RecoVertex/GaussianSumVertexFit/test/GsfTest.h
  RecoVertex/GaussianSumVertexFit/test/SealModule.cc
  RecoVertex/GaussianSumVertexFit/test/TrackMix.cc
  RecoVertex/GaussianSumVertexFit/test/TrackMix.h
  RecoVertex/KinematicFit/plugins/KineExample.cc
  RecoVertex/KinematicFit/plugins/KineExample.h
  RecoVertex/PrimaryVertexProducer/interface/PrimaryVertexProducerAlgorithm.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36724 Changing tensorflow implementation in RecoHGCal/TICL
  RecoHGCal/TICL/BuildFile.xml
  RecoHGCal/TICL/interface/PatternRecognitionAlgoBase.h
  RecoHGCal/TICL/plugins/PatternRecognitionPluginFactory.h
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyCA.h
  RecoHGCal/TICL/plugins/PatternRecognitionbyCLUE3D.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyCLUE3D.h
  RecoHGCal/TICL/plugins/PatternRecognitionbyFastJet.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyFastJet.h
  RecoHGCal/TICL/plugins/TrackstersMergeProducer.cc
  RecoHGCal/TICL/plugins/TrackstersProducer.cc
  RecoHGCal/TICL/python/iterativeTICL_cff.py
  RecoHGCal/TICL/python/tracksterSelectionTf_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#36817 ED_RPConeBuilderFix222 Backport the fix of a check on the geometry in RPCConeBuilder due to elfontan in #36803
  L1Trigger/RPCTrigger/plugins/RPCConeBuilder.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#36824 Run3-alca216X Bug fix to HcalHBHEMuonANalyzer code in Calibration/HCalCalibAlgos
  Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36554 [HGCAL] Closeby Particle gun - uniform eta generation
  Configuration/Generator/python/CE_E_Front_120um_cfi.py
  Configuration/Generator/python/CE_E_Front_200um_cfi.py
  Configuration/Generator/python/CE_E_Front_300um_cfi.py
  Configuration/Generator/python/CE_H_Coarse_300um_cfi.py
  Configuration/Generator/python/CE_H_Coarse_Scint_cfi.py
  Configuration/Generator/python/CE_H_Fine_120um_cfi.py
  Configuration/Generator/python/CE_H_Fine_200um_cfi.py
  Configuration/Generator/python/CE_H_Fine_300um_cfi.py
  Configuration/Generator/python/CloseByParticle_Photon_ERZRanges_cfi.py
  IOMC/ParticleGuns/interface/CloseByParticleGunProducer.h
  IOMC/ParticleGuns/src/CloseByParticleGunProducer.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36822 Migrate legacy EDModules DataFormats/L1TrackTrigger
  DataFormats/L1TrackTrigger/test/TestDataFormatsTTTrackTrackWord.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved
