Repository cms-sw/cmssw, pull requests merged in 2022-03, with the labels that each got.

#37053 memory leak fixes for Hydjets
  GeneratorInterface/Hydjet2Interface/src/Hydjet2Hadronizer.cc
  GeneratorInterface/Hydjet2Interface/test/Hydjet2Analyzer.cc
  GeneratorInterface/Hydjet2Interface/test/testHydjet.py
  GeneratorInterface/HydjetInterface/src/HydjetHadronizer.cc
  GeneratorInterface/HydjetInterface/test/HydjetAnalyzer.cc
  GeneratorInterface/PyquenInterface/test/PyquenAnalyzer.h
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37089 Add new L1T menu for Run-3 MC GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37085 Fix `BeamSpotAnalyzer::fillDescriptions`
  RecoVertex/BeamSpotProducer/plugins/BeamSpotAnalyzer.cc
  RecoVertex/BeamSpotProducer/test/BuildFile.xml
  RecoVertex/BeamSpotProducer/test/testBeamSpotAnalyzer.cc
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37066 introduce `SiStripApvGainFromFileBuilder` (reprise)
  CondTools/SiStrip/README.md
  CondTools/SiStrip/plugins/SiStripApvGainFromFileBuilder.cc
  CondTools/SiStrip/test/README.md
  CondTools/SiStrip/test/SiStripApvGainFromASCIIFile_cfg.py
  CondTools/SiStrip/test/testBuildersReaders.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, requires-external, code-checks-approved

#37104 [HETEROGENEOUS] Update all the scripts to use python3
  HeterogeneousCore/CUDAServices/scripts/cudaPreallocate.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#37032 Add missing init in default constructor
  DataFormats/METReco/src/CSCHaloData.cc
  DataFormats/METReco/src/GlobalHaloData.cc
  DataFormats/ParticleFlowReco/interface/PFCluster.h
  DataFormats/TauReco/interface/PFTauTransverseImpactParameter.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport, code-checks-approved

#37095 Fix AllStepsToTree option to runP_Trackery.py script
  Validation/Geometry/interface/MaterialBudgetTree.h
  Validation/Geometry/src/MaterialBudgetTree.cc
Labels: dqm-approved, geometry-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37099 [12.2.X] Fix `BeamSpotAnalyzer::fillDescriptions`
  RecoVertex/BeamSpotProducer/plugins/BeamSpotAnalyzer.cc
  RecoVertex/BeamSpotProducer/test/BuildFile.xml
  RecoVertex/BeamSpotProducer/test/testBeamSpotAnalyzer.cc
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#37083 introduce `GenericTriggerEventFlag::fillPSetDescription` and use it in several clients
  CommonTools/TriggerUtils/interface/GenericTriggerEventFlag.h
  CommonTools/TriggerUtils/src/GenericTriggerEventFlag.cc
  DQM/TrackingMonitorSource/src/TrackToTrackComparisonHists.cc
  DQMOffline/Trigger/plugins/BPHMonitor.cc
  DQMOffline/Trigger/plugins/DiDispStaMuonMonitor.cc
  DQMOffline/Trigger/plugins/DiJetMonitor.cc
  DQMOffline/Trigger/plugins/HTMonitor.cc
  DQMOffline/Trigger/plugins/JetMonitor.cc
  DQMOffline/Trigger/plugins/METMonitor.cc
  DQMOffline/Trigger/plugins/METplusTrackMonitor.cc
  DQMOffline/Trigger/plugins/MuonMonitor.cc
  DQMOffline/Trigger/plugins/NoBPTXMonitor.cc
  DQMOffline/Trigger/plugins/ObjMonitor.cc
  DQMOffline/Trigger/plugins/PhotonMonitor.cc
  DQMOffline/Trigger/plugins/RazorMonitor.cc
  DQMOffline/Trigger/plugins/Tau3MuMonitor.cc
  DQMOffline/Trigger/plugins/TopMonitor.cc
Labels: dqm-approved, hlt-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37090 Update selection for HLT tracking validation
  Validation/RecoTrack/python/HLTmultiTrackValidator_cff.py
  Validation/RecoTrack/python/HLTmultiTrackValidator_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37106 [DB] Update all the scripts to use python3
  CondTools/SiStrip/scripts/readSiStripApvGain.py
  RecoLuminosity/LumiDB/scripts/makePileupJSON.py
  RecoLuminosity/LumiDB/scripts/pileupReCalc_HLTpaths.py
  RecoLuminosity/LumiDB/scripts/pileupReCalc_Lumis.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#37108 [ANALYSIS] Update all the scripts to use python3
  PhysicsTools/FWLite/scripts/newFWLiteAna.py
  PhysicsTools/Heppy/scripts/cmsBatch.py
  PhysicsTools/Heppy/scripts/cmsStageWithFailover.py
  PhysicsTools/Heppy/scripts/heppy_report.py
  PhysicsTools/HeppyCore/python/utils/das.py
  PhysicsTools/HeppyCore/python/utils/dataset.py
  PhysicsTools/HeppyCore/python/utils/edmIntegrityCheck.py
  PhysicsTools/HeppyCore/scripts/das.py
  PhysicsTools/HeppyCore/scripts/dataset.py
  PhysicsTools/HeppyCore/scripts/edmIntegrityCheck.py
  PhysicsTools/HeppyCore/scripts/heppy_batch.py
  PhysicsTools/HeppyCore/scripts/heppy_check.py
  PhysicsTools/HeppyCore/scripts/heppy_hadd.py
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#37111 [MkFit] round up size arguments to aligned_alloc upwards to align value.
  RecoTracker/MkFitCore/src/HitStructures.cc
  RecoTracker/MkFitCore/src/Matriplex/MatriplexCommon.h
  RecoTracker/MkFitCore/src/Matriplex/MatriplexVector.h
  RecoTracker/MkFitCore/src/Matriplex/Memory.h
  RecoTracker/MkFitCore/src/Pool.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37103 [PDMV-UPGRADE] Update all the scripts to use python3
  Configuration/PyReleaseValidation/scripts/das-selected-lumis.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#36952 AlCaLumiPixelsCountsExpress and AlCaLumiPixelsCountsPrompt PCL and PromptReco
  Calibration/LumiAlCaRecoProducers/plugins/CorrPCCProducer.cc
  Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc
  Calibration/LumiAlCaRecoProducers/python/ALCARECOAlCaPCCRandom_Output_cff.py
  Calibration/LumiAlCaRecoProducers/python/ALCARECOAlCaPCCRandom_cff.py
  Calibration/LumiAlCaRecoProducers/python/ALCARECOAlCaPCCZeroBias_Output_cff.py
  Calibration/LumiAlCaRecoProducers/python/ALCARECOAlCaPCCZeroBias_cff.py
  Calibration/LumiAlCaRecoProducers/python/ALCARECORawPCCProducer_Output_cff.py
  Calibration/LumiAlCaRecoProducers/python/ALCARECORawPCCProducer_cff.py
  Calibration/LumiAlCaRecoProducers/python/alcaPCCIntegrator_cfi.py
  Calibration/LumiAlCaRecoProducers/python/alcaRawPCCProducer_cfi.py
  Configuration/PyReleaseValidation/python/relval_production.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#37112 [DD4hep] Add error message for undefined solid
  DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36968 SiPixelClusterizer: No digis to clusterize warning into error
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizerForBricked.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#37078 Fix dtSpecsFilter XML used by Phase-2 wf for DD4hep
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D86.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D88.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D91.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D86XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D88XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D91XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37110 fix L1 candidate matching in HLTMuonL1TFilter
  HLTrigger/Muon/plugins/HLTMuonL1TFilter.cc
  HLTrigger/Muon/plugins/HLTMuonL1TFilter.h
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37118 Removed excess printing in FWCore/ParameterSet tests
  FWCore/ParameterSet/python/Mixins.py
  FWCore/ParameterSet/python/OrderedSet.py
  FWCore/ParameterSet/python/printPaths.py
  FWCore/ParameterSet/python/usedOutput.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37084 migration to `DCSRecord` of `GenericTriggerEventFlag`
  CommonTools/TriggerUtils/BuildFile.xml
  CommonTools/TriggerUtils/interface/GenericTriggerEventFlag.h
  CommonTools/TriggerUtils/src/GenericTriggerEventFlag.cc
  DQM/HLTEvF/python/HLTSiStripMonitoring_cff.py
  DQM/SiPixelPhase1Common/python/TriggerEventFlag_cfi.py
  DQM/SiStripMonitorClient/python/SiStripSourceConfigTier0_HeavyIons_cff.py
  DQM/SiStripMonitorCluster/python/SiStripMonitorCluster_cfi.py
  DQM/TrackingMonitorSource/python/pset4GenericTriggerEventFlag_cfi.py
  DQMOffline/JetMET/python/jetMETDQMCleanup_cff.py
  DQMOffline/Trigger/interface/HLTDQMTagAndProbeEff.h
  DQMOffline/Trigger/python/BPHMonitor_cfi.py
  DQMOffline/Trigger/python/BTaggingMonitor_cfi.py
  DQMOffline/Trigger/python/DiDispStaMuonMonitor_cfi.py
  DQMOffline/Trigger/python/DiJetMonitor_cfi.py
  DQMOffline/Trigger/python/HTMonitor_cfi.py
  DQMOffline/Trigger/python/HiggsMonitoring_cfi.py
  DQMOffline/Trigger/python/JetMonitor_cfi.py
  DQMOffline/Trigger/python/LepHTMonitor_cff.py
  DQMOffline/Trigger/python/METMonitor_cfi.py
  DQMOffline/Trigger/python/METplusTrackMonitor_cfi.py
  DQMOffline/Trigger/python/MjjMonitor_cfi.py
  DQMOffline/Trigger/python/MssmHbbBtagTriggerMonitor_cfi.py
  DQMOffline/Trigger/python/MssmHbbMonitoring_cfi.py
  DQMOffline/Trigger/python/MuonMonitor_cfi.py
  DQMOffline/Trigger/python/NoBPTXMonitor_cfi.py
  DQMOffline/Trigger/python/ObjMonitor_cfi.py
  DQMOffline/Trigger/python/PhotonMonitor_cfi.py
  DQMOffline/Trigger/python/RazorMonitor_cfi.py
  DQMOffline/Trigger/python/SiStrip_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/SoftdropMonitor_cfi.py
  DQMOffline/Trigger/python/SusyMonitor_cfi.py
  DQMOffline/Trigger/python/TopMonitor_cfi.py
Labels: dqm-approved, hlt-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37005 Update L1TrackTrigger step to DD4hep
  L1Trigger/TrackerDTC/interface/Setup.h
  L1Trigger/TrackerDTC/plugins/ProducerES.cc
  L1Trigger/TrackerDTC/python/ProducerES_cff.py
  L1Trigger/TrackerDTC/python/ProducerES_cfi.py
  L1Trigger/TrackerDTC/src/Setup.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37100 Adapt to new range for BDT output for Run3 Saturated regression
  Configuration/Eras/python/Era_Run3_cff.py
  Configuration/Eras/python/Modifier_run3_egamma_cff.py
  RecoEgamma/EgammaTools/python/regressionModifier_cfi.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external, code-checks-approved

#37102 Add saturated EGM regression tags to Run-3 MC GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external, code-checks-approved

#36901 Implementation of beam halo tagger algorithm for the endcap photons
  DataFormats/EgammaCandidates/interface/Photon.h
  DataFormats/EgammaCandidates/src/Photon.cc
  DataFormats/EgammaCandidates/src/classes_def.xml
  DataFormats/PatCandidates/src/classes_def_objects.xml
  RecoEgamma/EgammaPhotonProducers/python/gedPhotons_cfi.py
  RecoEgamma/EgammaPhotonProducers/python/photons_cfi.py
  RecoEgamma/EgammaPhotonProducers/src/GEDPhotonProducer.cc
  RecoEgamma/EgammaPhotonProducers/src/PhotonProducer.cc
  RecoEgamma/PhotonIdentification/BuildFile.xml
  RecoEgamma/PhotonIdentification/interface/PhotonMVABasedHaloTagger.h
  RecoEgamma/PhotonIdentification/python/mvaHaloVariable_cfi.py
  RecoEgamma/PhotonIdentification/src/PhotonMVABasedHaloTagger.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#37116 Add PFDiJetCorrCheckerWithDiTau producer for DoubleTau+VBF-jets HLT paths
  RecoTauTag/HLTProducers/src/HLTPFDiJetCorrCheckerWithDiTau.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36961 Add HiGenEvent object to heavy-ion miniAOD event content
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#37088 properly treat averaging with self in GhostTrackVertexFinder::vtxMean
  RecoVertex/GhostTrackFitter/BuildFile.xml
  RecoVertex/GhostTrackFitter/src/GhostTrackVertexFinder.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37132 Update of L1T menu in TSG GTs to L1Menu_Collisions2022_v0_1_6_xml
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37060 Fixes for SiStripCalCosmicsNano
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#37128 Add an option to cmsDriver for selecting the accelerators to use
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/Applications/python/Options.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#37105 [GENERATORS] Update all the scripts to use python3
  GeneratorInterface/Herwig7Interface/scripts/parallelization.py
  GeneratorInterface/LHEInterface/scripts/cmsLHEtoEOSManager.py
  GeneratorInterface/LHEInterface/scripts/mergeLHE.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37127 modernize `TriggerHelper` and migrate to usage of `DCSRecord`
  DQM/TrackerCommon/BuildFile.xml
  DQM/TrackerCommon/interface/TriggerHelper.h
  DQM/TrackerCommon/src/TriggerHelper.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37124 Migrate deprecated EDAnalyzers in CondTools/DT to the One version.
  CondTools/DT/test/stubs/DTCompactMapDump.cc
  CondTools/DT/test/stubs/DTCompactMapDump.h
  CondTools/DT/test/stubs/DTFullMapDump.cc
  CondTools/DT/test/stubs/DTFullMapDump.h
  CondTools/DT/test/stubs/DTGeometryDump.cc
  CondTools/DT/test/stubs/DTGeometryDump.h
  CondTools/DT/test/stubs/DTHVDump.cc
  CondTools/DT/test/stubs/DTHVDump.h
  CondTools/DT/test/stubs/DTKeyedConfigDump.h
  CondTools/DT/test/stubs/DTTimeUtility.cc
  CondTools/DT/test/stubs/DTTimeUtility.h
  CondTools/DT/test/validate/DTCCBConfigValidateDBRead.cc
  CondTools/DT/test/validate/DTCCBConfigValidateDBRead.h
  CondTools/DT/test/validate/DTCompMapValidateDBRead.cc
  CondTools/DT/test/validate/DTCompMapValidateDBRead.h
  CondTools/DT/test/validate/DTDeadFlagValidateDBRead.cc
  CondTools/DT/test/validate/DTDeadFlagValidateDBRead.h
  CondTools/DT/test/validate/DTHVStatusValidateDBRead.cc
  CondTools/DT/test/validate/DTHVStatusValidateDBRead.h
  CondTools/DT/test/validate/DTLVStatusValidateDBRead.cc
  CondTools/DT/test/validate/DTLVStatusValidateDBRead.h
  CondTools/DT/test/validate/DTMtimeValidateDBRead.cc
  CondTools/DT/test/validate/DTMtimeValidateDBRead.h
  CondTools/DT/test/validate/DTPerformanceValidateDBRead.cc
  CondTools/DT/test/validate/DTPerformanceValidateDBRead.h
  CondTools/DT/test/validate/DTROMapValidateDBRead.cc
  CondTools/DT/test/validate/DTROMapValidateDBRead.h
  CondTools/DT/test/validate/DTRangeT0ValidateDBRead.cc
  CondTools/DT/test/validate/DTRangeT0ValidateDBRead.h
  CondTools/DT/test/validate/DTStatusFlagValidateDBRead.cc
  CondTools/DT/test/validate/DTStatusFlagValidateDBRead.h
  CondTools/DT/test/validate/DTT0ValidateDBRead.cc
  CondTools/DT/test/validate/DTT0ValidateDBRead.h
  CondTools/DT/test/validate/DTTPGParametersValidateDBRead.cc
  CondTools/DT/test/validate/DTTPGParametersValidateDBRead.h
  CondTools/DT/test/validate/DTTtrigValidateDBRead.cc
  CondTools/DT/test/validate/DTTtrigValidateDBRead.h
Labels: fully-signed, tests-approved, db-approved, orp-approved, requires-external, code-checks-approved

#37145 Added unit test to run pede from millepede
  Alignment/MillePedeAlignmentAlgorithm/test/BuildFile.xml
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37144 Include HLT JEC and L1T Menu tags in data, mcRun3 and mcRun4 GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37130 Add `AlcaPCCIntegrator` modules to the AlCa no ConcurrentLumis list
  Configuration/AlCa/python/autoAlca.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37093 Revert "Revert "Add D88 DD4hep wf to relval_2026""
  Configuration/PyReleaseValidation/python/relval_2026.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, requires-external, code-checks-approved

#37148 Add warning to add DD4hep in GeometryConf
  Configuration/Geometry/python/generateGeometry.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37143 `BeamSpot` Payload Inspector: introduce payload parameters comparator
  CondCore/BeamSpotPlugins/interface/BeamSpotPayloadInspectorHelper.h
  CondCore/BeamSpotPlugins/plugins/BeamSpotOnline_PayloadInspector.cc
  CondCore/BeamSpotPlugins/plugins/BeamSpot_PayloadInspector.cc
  CondCore/BeamSpotPlugins/test/testBeamSpotPayloadInspector.cpp
  CondCore/BeamSpotPlugins/test/testBeamSpotPayloadInspector.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#37153 Remove dead assignments from BTagSF.cc
  PhysicsTools/Heppy/src/BTagSF.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#37101 [123X] Migrate DQM clients to Run3 era
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamspotdip_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/bril_dqm_clientPB-live_cfg.py
  DQM/Integration/python/clients/castor_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/csc_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/dt4ml_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/dt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/es_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/fed_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hlt_dqm_clientPB-live_cfg.py
  DQM/Integration/python/clients/hltrates_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hlx_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/info_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1t_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1temulator_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage1_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage1emulator_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/lumi_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/mutracking_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/physics_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/pixellumi_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/ramdisk_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/rpc_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/scal_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistriplas_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37141 Cuda time measurements
  HeterogeneousCore/CUDACore/test/BuildFile.xml
  HeterogeneousCore/CUDACore/test/cudaTimeMeasurement.cu
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#37139 add quality selections in MkFitOutputConverter
  RecoTracker/MkFit/plugins/MkFitOutputConverter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#37160 Use ZSTD and default compression for PoolOutputModule
  IOPool/Output/src/PoolOutputModule.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36994 Add GEN/LHE weight validation subdirectories for GEN Relval
  Configuration/Generator/python/Hadronizer_TuneCP5_13TeV_aMCatNLO_FXFX_5f_max2j_max1p_LHE_pythia8_cff.py
  Validation/EventGenerator/interface/GenWeightValidation.h
  Validation/EventGenerator/interface/HepMCValidationHelper.h
  Validation/EventGenerator/interface/LheWeightValidation.h
  Validation/EventGenerator/interface/WeightManager.h
  Validation/EventGenerator/plugins/GenWeightValidation.cc
  Validation/EventGenerator/plugins/LheWeightValidation.cc
  Validation/EventGenerator/plugins/Module.cc
  Validation/EventGenerator/plugins/WeightManager.cc
  Validation/EventGenerator/python/BasicGenValidation_cff.py
  Validation/EventGenerator/python/GenWeightValidation_cff.py
  Validation/EventGenerator/python/LheWeightValidation_cff.py
  Validation/EventGenerator/python/PostProcessor_cff.py
  Validation/EventGenerator/src/WeightManager.cc
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36954 Electron and photon masses are set to zero
  RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc
  RecoEgamma/EgammaElectronAlgos/src/RegressionHelper.cc
  RecoEgamma/EgammaPhotonProducers/src/GEDPhotonProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36985 A few possible bug fixes in the L1T code
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/BMTFPackerInputs.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage1Layer2EtSumAlgorithmImpPP.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2JetAlgorithmFirmwareImp1.cc
  L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2TauAlgorithmFirmwareImp1.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37142 Fix dtSpecFilter of M9 and add DD4hep wf for D77
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D76.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D77.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D78.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D79.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D80.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D81.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D82.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D83.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D85.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D87.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D89.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D90.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D76XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D77XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D78XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D79XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D80XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D81XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D82XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D83XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D85XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D87XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D89XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D90XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#36526 Hgg photons variables in nanoAODs
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#37156 Fix for the access of haloMVATaggerVal in the Run 1+2 files
  DataFormats/EgammaCandidates/interface/Photon.h
  DataFormats/EgammaCandidates/src/Photon.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#36890 [MiniAOD] Lower AK4 Puppi jets pT cut for Run 3
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#37091 Removal of depreciated tauIDs
  PhysicsTools/NanoAOD/python/boostedTaus_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/PatAlgos/python/producersLayer1/tauProducer_cfi.py
  RecoTauTag/Configuration/python/HPSPFTaus_cff.py
  RecoTauTag/Configuration/python/RecoTauTag_EventContent_cff.py
  RecoTauTag/Configuration/python/boostedHPSPFTaus_cfi.py
  Validation/RecoTau/python/RecoTauValidationMiniAOD_cfi.py
  Validation/RecoTau/python/RecoTauValidation_cfi.py
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#37154 Use externally produced trajectory in ExtenderWithMTD, customise needed TrajectoryInEvent also for PixelLess iteration
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#37164 Migrate deprecated EDModule for CondFormats/DTObjects
  CondFormats/DTObjects/test/stubs/DTConfigPrint.cc
  CondFormats/DTObjects/test/stubs/DTConfigPrint.h
  CondFormats/DTObjects/test/stubs/DTConfigWrite.cc
  CondFormats/DTObjects/test/stubs/DTConfigWrite.h
  CondFormats/DTObjects/test/stubs/DTDeadPrint.cc
  CondFormats/DTObjects/test/stubs/DTDeadPrint.h
  CondFormats/DTObjects/test/stubs/DTDeadUpdate.h
  CondFormats/DTObjects/test/stubs/DTDeadWrite.cc
  CondFormats/DTObjects/test/stubs/DTDeadWrite.h
  CondFormats/DTObjects/test/stubs/DTFullMapPrint.cc
  CondFormats/DTObjects/test/stubs/DTFullMapPrint.h
  CondFormats/DTObjects/test/stubs/DTMapPrint.cc
  CondFormats/DTObjects/test/stubs/DTMapPrint.h
  CondFormats/DTObjects/test/stubs/DTMapWrite.cc
  CondFormats/DTObjects/test/stubs/DTMapWrite.h
  CondFormats/DTObjects/test/stubs/DTRangeT0Print.cc
  CondFormats/DTObjects/test/stubs/DTRangeT0Print.h
  CondFormats/DTObjects/test/stubs/DTRangeT0Write.cc
  CondFormats/DTObjects/test/stubs/DTRangeT0Write.h
  CondFormats/DTObjects/test/stubs/DTT0Print.cc
  CondFormats/DTObjects/test/stubs/DTT0Print.h
  CondFormats/DTObjects/test/stubs/DTT0Write.cc
  CondFormats/DTObjects/test/stubs/DTT0Write.h
  CondFormats/DTObjects/test/stubs/DTTtrigPrint.cc
  CondFormats/DTObjects/test/stubs/DTTtrigPrint.h
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#37117 DQM HLT Muon cleaning
  DQMOffline/Configuration/python/DQMOfflineHeavyIons_cff.py
  DQMOffline/Trigger/python/HLTMuonOfflineAnalyzer_cff.py
  DQMOffline/Trigger/python/HLTMuonOfflineAnalyzer_cfi.py
  DQMOffline/Trigger/src/HLTMuonMatchAndPlot.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37159 Define HOST_DEVICE_CONSTANT to implement constexpr aggregate host/device constants
  FWCore/Utilities/interface/HostDeviceConstant.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37171 Update autoCond.py to include GTs with fixed L1 Menu for Run3
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#37122 Speed-up seed/dup. cleaning mkFit
  RecoTracker/MkFitCMS/src/MkStdSeqs.cc
  RecoTracker/MkFitCore/interface/binnor.h
  RecoTracker/MkFitCore/standalone/test/binnor_demo.cxx
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved, tracking-pog-approved

#37176 Add std::move to std::vector member of Run3ScoutingMuon
  DataFormats/Scouting/interface/Run3ScoutingMuon.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#37158 Adding optionality for MTD timing in PFTICLProducer
  RecoHGCal/TICL/plugins/PFTICLProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37177 Update DQM (offline + HLTEvF) HLT track monitoring for Run3 era
  DQM/HLTEvF/python/HLTTrackingMonitoring_Client_cff.py
  DQM/HLTEvF/python/HLTTrackingMonitoring_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_Client_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_cff.py
Labels: dqm-approved, hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37182 fix thinnedAssociationsHelperPtr scope error
  IOPool/Input/src/RootFile.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37147 XML and FedId configuration update for PPS
  CondFormats/PPSObjects/xml/mapping_timing_diamond_2022.xml
  CondFormats/PPSObjects/xml/mapping_totem_timing_2022.xml
  CondFormats/PPSObjects/xml/mapping_tracking_strip_2022.xml
  EventFilter/CTPPSRawToDigi/python/ctppsDiamondRawToDigi_cfi.py
  EventFilter/CTPPSRawToDigi/python/ctppsRawToDigi_cff.py
  EventFilter/CTPPSRawToDigi/python/totemRPRawToDigi_cfi.py
  EventFilter/CTPPSRawToDigi/python/totemTimingRawToDigi_cfi.py
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37181 handle inverted filters in `TriggerObjectStandAlone`
  DataFormats/PatCandidates/src/TriggerObjectStandAlone.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#37123 ECAL DQM - Add WF .513 for ECAL GPU vs. CPU validation
  Configuration/PyReleaseValidation/README.md
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  DQM/EcalMonitorTasks/python/EcalMonitorTask_cff.py
Labels: dqm-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved, heterogeneous-approved

#37185 Tighten check for the number of weights in GenWeightValidation
  Validation/EventGenerator/plugins/GenWeightValidation.cc
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#37183 Run3-hcx331 Cleanup some of the codes in Validation/HcalRecHits
  Validation/HcalRecHits/interface/HcalRecHitsValidation.h
  Validation/HcalRecHits/interface/NoiseRates.h
  Validation/HcalRecHits/src/HcalRecHitsValidation.cc
  Validation/HcalRecHits/src/NoiseRates.cc
  Validation/HcalRecHits/test/HcalDumpHits.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37165 Run3-hcx330 Cleanup some of the codes in Validation/HcalHits
  Validation/HcalHits/interface/HcalSimHitsClient.h
  Validation/HcalHits/interface/HcalSimHitsValidation.h
  Validation/HcalHits/interface/SimG4HcalHitCluster.h
  Validation/HcalHits/interface/SimHitsValidationHcal.h
  Validation/HcalHits/plugins/HcalGeomCheck.cc
  Validation/HcalHits/plugins/HcalHitValidation.cc
  Validation/HcalHits/plugins/HcalSimHitCheck.cc
  Validation/HcalHits/plugins/HcalSimHitStudy.cc
  Validation/HcalHits/plugins/ZdcSimHitStudy.cc
  Validation/HcalHits/src/HcalSimHitsClient.cc
  Validation/HcalHits/src/HcalSimHitsValidation.cc
  Validation/HcalHits/src/SimG4HcalHitCluster.cc
  Validation/HcalHits/src/SimG4HcalHitJetFinder.cc
  Validation/HcalHits/src/SimHitsValidationHcal.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37170 Adding MacroPixel inefficiency in Tracker Phase2Digitizer
  SimTracker/SiPhase2Digitizer/plugins/PSPDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PSPDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#37188 Make both ME1a and ME1b LCT (A/CLCT) sorted into ring 1.
  Validation/MuonCSCDigis/src/CSCStubMatcher.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37190 Run3-gex119A Avoid compilation warnings in Validation/L1T and RecoJets
  Validation/L1T/interface/L1Validator.h
  Validation/RecoJets/plugins/JetTester.h
  Validation/RecoJets/plugins/JetTesterPostProcessor.h
  Validation/RecoJets/plugins/JetTester_HeavyIons.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37191 Run3-gex119B Avoid compilation warnings in Validation/RecoMuon
  Validation/RecoMuon/plugins/MuonTrackValidator.h
  Validation/RecoMuon/src/GlobalMuonMatchAnalyzer.cc
  Validation/RecoMuon/src/GlobalMuonMatchAnalyzer.h
  Validation/RecoMuon/src/MuonSeedTrack.h
  Validation/RecoMuon/src/MuonTrackAnalyzer.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37146 [MkFit] Fix UBSAN error - skip processing of layers with no hits.
  RecoTracker/MkFit/plugins/MkFitProducer.cc
  RecoTracker/MkFitCMS/standalone/Makefile
  RecoTracker/MkFitCore/src/MatriplexPackers.h
  RecoTracker/MkFitCore/src/MkBuilder.cc
  RecoTracker/MkFitCore/src/MkFinder.cc
  RecoTracker/MkFitCore/src/MkFitter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37184 Update TSG tests and Relval Steps to use new run3_[hlt|data]_relval GTs
  Configuration/PyReleaseValidation/python/relval_steps.py
  HLTrigger/Configuration/python/Tools/options.py
Labels: hlt-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#37200 Run3-gem68 Take care of deprecated codes in Geometry/CSCGeometry
  Geometry/CSCGeometry/test/stubs/CSCDetIdAnalyzer.cc
  Geometry/CSCGeometry/test/stubs/CSCGACwithB.cc
  Geometry/CSCGeometry/test/stubs/CSCGeometryAsChambers.cc
  Geometry/CSCGeometry/test/stubs/CSCGeometryAsLayers.cc
  Geometry/CSCGeometry/test/stubs/CSCGeometryOfStrips.cc
  Geometry/CSCGeometry/test/stubs/CSCGeometryOfWires.cc
  Geometry/CSCGeometry/test/stubs/CSCLayerGeometryInside.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37125 Add tests for Skeleton templates
  FWCore/Skeletons/mkTemplates/DQMEDAnalyzer/DQMEDAnalyzer.cc
  FWCore/Skeletons/mkTemplates/EDAnalyzer/EDAnalyzer.cc
  FWCore/Skeletons/mkTemplates/EDFilter/EDFilter.cc
  FWCore/Skeletons/mkTemplates/EDLooper/EDLooper.cc
  FWCore/Skeletons/mkTemplates/EDProducer/EDProducer.cc
  FWCore/Skeletons/mkTemplates/ESProducer/ESProducer.cc
  FWCore/Skeletons/mkTemplates/TSelector/BuildFile.xml
  FWCore/Skeletons/mkTemplates/TSelector/TSelector.cc
  FWCore/Skeletons/mkTemplates/TSelector/TSelector.h
  FWCore/Skeletons/python/pkg.py
  FWCore/Skeletons/test/BuildFile.xml
  FWCore/Skeletons/test/runtests.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37217 Make both ME1a and ME1b LCT (A/CLCT) sorted into ring 1.
  Validation/MuonCSCDigis/src/CSCStubMatcher.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37179 Make both ME1a and ME1b LCT (A/CLCT) sorted into ring 1.
  Validation/MuonCSCDigis/src/CSCStubMatcher.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37216 Extended handling of geometry exceptions for SIM
  SimG4Core/Application/src/ExceptionHandler.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37161 ECAL - Make EcalConstants constexpr arrays compatible with CUDA code
  DataFormats/EcalDigi/interface/EcalConstants.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37192 Update of Exotica HLT validation monitored paths and removal of l1MET from code
  HLTriggerOffline/Exotica/interface/HLTExoticaSubAnalysis.h
  HLTriggerOffline/Exotica/python/analyses/hltExoticaCaloHT_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaDSTJets_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaDSTMuons_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaDiPhoton_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaDisplacedDimuon_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaDisplacedMuEG_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaEleMu_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaHTDisplacedJets_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaHighPtDielectron_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaHighPtDimuon_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaHighPtElectron_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaHighPtPhoton_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaJetNoBptx_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaLowPtDielectron_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaLowPtDimuon_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaLowPtElectron_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaLowPtTrimuon_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaMETplusTrack_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaMonojetBackup_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaMonojet_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaMuonNoBptx_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaPFHT_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaPhotonMET_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaPureMET_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaSingleMuon_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaTracklessJets_cff.py
  HLTriggerOffline/Exotica/python/hltExoticaPostProcessors_cff.py
  HLTriggerOffline/Exotica/python/hltExoticaValidator_cfi.py
  HLTriggerOffline/Exotica/src/EVTColContainer.cc
  HLTriggerOffline/Exotica/src/HLTExoticaSubAnalysis.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37196 HCAL: fix on HCAL TP saturation algorithm to recover a saturation threshold for HE with |ieta| >= 21
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalTriggerPrimitiveAlgo.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37135 Lumi-based status plots on GEM onlineDQM
  DQM/GEM/interface/GEMDAQStatusSource.h
  DQM/GEM/plugins/BuildFile.xml
  DQM/GEM/plugins/GEMDAQStatusSource.cc
  DQM/GEM/plugins/GEMDQMHarvester.cc
  DQM/GEM/test/decomposeStatus.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37230 Bugfix for strips O2O reported in #37228
  CondTools/SiStrip/scripts/o2oRun_SiStripDAQ.py
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, urgent, code-checks-approved

#37214 Modernize `DQM/BeamMonitor/plugins/TKStatus` plugin
  DQM/BeamMonitor/plugins/BuildFile.xml
  DQM/BeamMonitor/plugins/TKStatus.cc
  DQM/BeamMonitor/plugins/TKStatus.h
  DQM/BeamMonitor/test/2011_44X_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/2012_PixelTracksVertices_44XOnwards_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/2012_ReducedTrackingSteps_44XOnwards_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/42X_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/44X_HI_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/44X_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/DQM_RECO_cfg.py
  DQM/BeamMonitor/test/HeavyIonTest_cfg.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37206 Update TSG tests and Relval Steps to use new run3_[hlt|data]_relval GTs
  Configuration/PyReleaseValidation/python/relval_steps.py
  HLTrigger/Configuration/python/Tools/options.py
Labels: hlt-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#37235 [12.3.X] Bugfix for Strips O2O
  CondTools/SiStrip/scripts/o2oRun_SiStripDAQ.py
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, backport-ok

#37236 [12.2.X] Bugfix for Strips O2O
  CondTools/SiStrip/scripts/o2oRun_SiStripDAQ.py
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, urgent, backport-ok

#37204 Lumi-based status plots on GEM onlineDQM, backport to CMSSW_12_2_X
  DQM/GEM/interface/GEMDAQStatusSource.h
  DQM/GEM/plugins/BuildFile.xml
  DQM/GEM/plugins/GEMDAQStatusSource.cc
  DQM/GEM/plugins/GEMDQMHarvester.cc
  DQM/GEM/test/decomposeStatus.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37213 Lumi-based status plots, backport to CMSSW_12_3_X
  DQM/GEM/interface/GEMDAQStatusSource.h
  DQM/GEM/plugins/BuildFile.xml
  DQM/GEM/plugins/GEMDAQStatusSource.cc
  DQM/GEM/plugins/GEMDQMHarvester.cc
  DQM/GEM/test/decomposeStatus.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37239 [12_2_X] Merged central modules at L3&L4 in SiPixelLorentzAngle PCL workflow
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLHarvester.cc
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLWorker.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37211 introduce alignment campaign-like unit test for `pede`
  Alignment/MillePedeAlignmentAlgorithm/test/BuildFile.xml
  Alignment/MillePedeAlignmentAlgorithm/test/TestDriver.cpp
  Alignment/MillePedeAlignmentAlgorithm/test/test_pede.py
  Alignment/MillePedeAlignmentAlgorithm/test/test_pede.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37232 Run3-gex119C Take care of compilation warnings in Validation/RecoMET
  Validation/RecoMET/plugins/METTesterPostProcessor.h
  Validation/RecoMET/plugins/METTesterPostProcessorHarvesting.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37224 [12_2_X] Modernize `DQM/BeamMonitor/plugins/TKStatus` plugin
  DQM/BeamMonitor/plugins/BuildFile.xml
  DQM/BeamMonitor/plugins/TKStatus.cc
  DQM/BeamMonitor/plugins/TKStatus.h
  DQM/BeamMonitor/test/2011_44X_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/2012_PixelTracksVertices_44XOnwards_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/2012_ReducedTrackingSteps_44XOnwards_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/42X_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/44X_HI_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/44X_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/DQM_RECO_cfg.py
  DQM/BeamMonitor/test/HeavyIonTest_cfg.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37223 [12_3_X] Modernize `DQM/BeamMonitor/plugins/TKStatus` plugin
  DQM/BeamMonitor/plugins/BuildFile.xml
  DQM/BeamMonitor/plugins/TKStatus.cc
  DQM/BeamMonitor/plugins/TKStatus.h
  DQM/BeamMonitor/test/2011_44X_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/2012_PixelTracksVertices_44XOnwards_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/2012_ReducedTrackingSteps_44XOnwards_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/42X_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/44X_HI_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/44X_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/DQM_RECO_cfg.py
  DQM/BeamMonitor/test/HeavyIonTest_cfg.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37229 `HLTDeDxFilter`: prevent variable length array bound evaluates to non-positive value
  RecoTracker/DeDx/plugins/HLTDeDxFilter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37244 Fix typos in MessageLogger tests
  FWCore/MessageService/bin/Standalone.cpp
  FWCore/MessageService/test/UnitTestClient_C.cc
  FWCore/MessageService/test/UnitTestClient_G.cc
  FWCore/MessageService/test/unit_test_outputs/infos.log
  FWCore/MessageService/test/unit_test_outputs/u10_warnings.log
  FWCore/MessageService/test/unit_test_outputs/u20_cerr.log
  FWCore/MessageService/test/unit_test_outputs/u6_warnings.log
  FWCore/MessageService/test/unit_test_outputs/warnings.log
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37222 Run3-gex121 Take care of deprecrated codes in GeneratorInterface/EvtGenInterface
  GeneratorInterface/EvtGenInterface/interface/DataCardFileWriter.h
  GeneratorInterface/EvtGenInterface/plugins/EvtGen/EvtGenInterface.h
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37248 Ed modules migration v1
  DQMOffline/EGamma/interface/ElectronDqmAnalyzerBase.h
  DQMOffline/EGamma/plugins/ElectronAnalyzer.cc
  DQMOffline/EGamma/plugins/ElectronGeneralAnalyzer.cc
  DQMOffline/EGamma/plugins/ElectronTagProbeAnalyzer.cc
  Validation/RecoEgamma/test/ElectronMcFakePostValidation_cfg.py
  Validation/RecoEgamma/test/ElectronMcSignalPostValidationMiniAOD_cfg.py
  Validation/RecoEgamma/test/ElectronMcSignalPostValidationPt1000_cfg.py
  Validation/RecoEgamma/test/ElectronMcSignalPostValidation_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37226 [12.3.X] Introduce alignment campaign-like unit test for `pede`
  Alignment/MillePedeAlignmentAlgorithm/test/BuildFile.xml
  Alignment/MillePedeAlignmentAlgorithm/test/TestDriver.cpp
  Alignment/MillePedeAlignmentAlgorithm/test/test_pede.py
  Alignment/MillePedeAlignmentAlgorithm/test/test_pede.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#37212 [12.2.X] Introduce alignment campaign-like unit test for `pede`
  Alignment/MillePedeAlignmentAlgorithm/test/BuildFile.xml
  Alignment/MillePedeAlignmentAlgorithm/test/TestDriver.cpp
  Alignment/MillePedeAlignmentAlgorithm/test/test_pede.py
  Alignment/MillePedeAlignmentAlgorithm/test/test_pede.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37246 Run3-Sim115X Bug fix to avoid crashes in using CaloSimHitStudy
  SimG4CMS/Calo/plugins/CaloSimHitStudy.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37251 Run3-gex122Y Take care of compilation warnings in GeneratorInterface/MCatNLOInterface
  GeneratorInterface/MCatNLOInterface/test/BuildFile.xml
  GeneratorInterface/MCatNLOInterface/test/ZeeAnalyzer.cc
  GeneratorInterface/MCatNLOInterface/test/analyzeEvents_cfg.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37210 [HGCAL] Update validation scripts
  Validation/HGCalValidation/python/hgcalHtml.py
  Validation/HGCalValidation/python/hgcalPlots.py
  Validation/HGCalValidation/scripts/hgcalPerformanceValidation.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37255 Fix edmPickEvents.py unit test
  PhysicsTools/Utilities/scripts/edmPickEvents.py
  PhysicsTools/Utilities/test/test_edmPickEvents.sh
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#37220 Add CMSSW version to StatisticsSenderService
  Utilities/StorageFactory/BuildFile.xml
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37218 Make sure all dictionaries in CUDADataFormats are transient
  CUDADataFormats/CaloCommon/src/classes_def.xml
  CUDADataFormats/HcalDigi/src/classes_def.xml
  CUDADataFormats/HcalRecHitSoA/src/classes_def.xml
  CUDADataFormats/StdDictionaries/src/classes_def.xml
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#37252 move from `int64_t` to `uint64_t` to avoid bit shifting negative numbers (UB in C++)
  RecoTracker/TkSeedGenerator/plugins/DeepCoreSeedGenerator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37231 Style changes in `RecoTracker/DeDx`
  CalibTracker/SiStripChannelGain/plugins/DeDxDiscriminatorLearner.cc
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastTrackDeDxProducer.cc
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  PhysicsTools/PatAlgos/plugins/PATIsolatedTrackProducer.cc
  RecoTracker/DeDx/interface/ASmirnovDeDxDiscriminator.h
  RecoTracker/DeDx/interface/BTagLikeDeDxDiscriminator.h
  RecoTracker/DeDx/interface/DeDxTools.h
  RecoTracker/DeDx/interface/ProductDeDxDiscriminator.h
  RecoTracker/DeDx/interface/SmirnovDeDxDiscriminator.h
  RecoTracker/DeDx/interface/TruncatedAverageDeDxEstimator.h
  RecoTracker/DeDx/plugins/DeDxEstimatorProducer.cc
  RecoTracker/DeDx/plugins/DeDxHitInfoProducer.cc
  RecoTracker/DeDx/plugins/DeDxHitInfoProducer.h
  RecoTracker/DeDx/python/dedxEstimators_cff.py
  RecoTracker/DeDx/src/DeDxTools.cc
Labels: fastsim-pending, alca-approved, hlt-approved, reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved

#37199 Run3-gex120 Take care of deprecated codes in RecoParticleFlow/PFSimProducer
  RecoParticleFlow/PFSimProducer/plugins/TauHadronDecayFilter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#36884 Add SV variables to BTV OfflineDQM
  DQMOffline/RecoB/interface/FlavourHistorgrams.h
  DQMOffline/RecoB/plugins/BuildFile.xml
  DQMOffline/RecoB/plugins/MiniAODSVAnalyzer.cc
  DQMOffline/RecoB/plugins/MiniAODSVAnalyzer.h
  DQMOffline/RecoB/plugins/MiniAODTaggerAnalyzer.cc
  DQMOffline/RecoB/python/bTagMiniDQM_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37257 L1T ASAN heap-buffer-overflow fix resulting from PR #36919 (12_4_X)
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/CaloLayer1Packer.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37260 use git init instead of git cms-init which creates a sparse checkout area
  FWCore/Skeletons/test/runtests.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37267 Cleaning code recently added in DQMOffline/RecoB
  DQMOffline/RecoB/plugins/MiniAODSVAnalyzer.cc
  DQMOffline/RecoB/plugins/MiniAODSVAnalyzer.h
  DQMOffline/RecoB/plugins/MiniAODTaggerAnalyzer.cc
  DQMOffline/RecoB/plugins/MiniAODTaggerAnalyzer.h
  DQMOffline/RecoB/python/bTagMiniDQM_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37197 Run3-sim110 Take care of deprecated usage in FastSimulation/CaloHitMakers
  FastSimulation/CaloHitMakers/test/testEcalHitMaker.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37198 Run3-sim111 Take car of deprecated codes in FastSimulation/CaloGeometryTools
  FastSimulation/CaloGeometryTools/test/testCaloGeometryTools.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37201 Run3-sim112 Take care of deprecated code in FastSimulation/ForwardDetectors
  FastSimulation/ForwardDetectors/plugins/CastorFastClusterProducer.cc
  FastSimulation/ForwardDetectors/plugins/CastorFastClusterProducer.h
  FastSimulation/ForwardDetectors/plugins/CastorFastTowerProducer.cc
  FastSimulation/ForwardDetectors/plugins/CastorFastTowerProducer.h
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37194 EMTF Unpacker Update to Add HMT and Displaced Muon information
  DataFormats/L1TMuon/interface/EMTF/SP.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockSP.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFCollections.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFTokens.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFTokens.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37264 Migrate to D88 wfs and clean up
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#37263 edmPickEvent: print the actual das output instead of json parsing error
  PhysicsTools/Utilities/scripts/edmPickEvents.py
  PhysicsTools/Utilities/test/test_edmPickEvents.sh
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#37254 [MkFit] Fix UBSAN error in (almost) empty events (backport of #37146)
  RecoTracker/MkFit/plugins/MkFitProducer.cc
  RecoTracker/MkFitCMS/standalone/Makefile
  RecoTracker/MkFitCore/src/MatriplexPackers.h
  RecoTracker/MkFitCore/src/MkBuilder.cc
  RecoTracker/MkFitCore/src/MkFinder.cc
  RecoTracker/MkFitCore/src/MkFitter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37253 L1T ASAN heap-buffer-overflow fix resulting from PR #36919
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/CaloLayer1Packer.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37272 (DAQ) Streamer output unit test and removal of the old output module (master/12_4_X)
  DQM/SiStripCommissioningSources/python/OnlineOutput_cfi.py
  EventFilter/Utilities/plugins/RecoEventOutputModuleForFU.h
  EventFilter/Utilities/plugins/RecoEventWriterForFU.cc
  EventFilter/Utilities/plugins/RecoEventWriterForFU.h
  EventFilter/Utilities/plugins/modules.cc
  EventFilter/Utilities/python/ShmStreamConsumer_cfi.py
  EventFilter/Utilities/src/FastMonitoringService.cc
  EventFilter/Utilities/test/LocalRunBUFU.sh
  EventFilter/Utilities/test/RunBUFU.sh
  EventFilter/Utilities/test/startFU.py
  EventFilter/Utilities/test/test_dqmstream.py
  EventFilter/Utilities/test/unittest_FU.py
Labels: daq-approved, dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37270 Run3-gex123X Avoide compilation warnings in GeneratorInterface/HiGenCommon and eratorInterface/PomwigInterfaceGen
  GeneratorInterface/HiGenCommon/plugins/HiCentralityBiasFilter.cc
  GeneratorInterface/HiGenCommon/plugins/HighMultiplicityGenFilter.cc
  GeneratorInterface/HiGenCommon/plugins/MixBoostEvtVtxGenerator.cc
  GeneratorInterface/PomwigInterface/test/PomwigAnalyzer.cc
  GeneratorInterface/PomwigInterface/test/PomwigAnalyzer.h
  GeneratorInterface/PomwigInterface/test/SDDYAnalyzer.cc
  GeneratorInterface/PomwigInterface/test/SDDijetsAnalyzer.cc
  GeneratorInterface/PomwigInterface/test/Z2muAnalyzer.cc
  GeneratorInterface/PomwigInterface/test/Z2muAnalyzer.h
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37271 Run3-gex123Y Take care of compilation warnings in GeneratorInterface/ce and GeneratorInterface/LHEInterface
  GeneratorInterface/ExhumeInterface/test/ExhumeAnalyzer.cc
  GeneratorInterface/LHEInterface/plugins/ExternalLHEAsciiDumper.cc
  GeneratorInterface/LHEInterface/plugins/LHE2HepMCConverter.cc
  GeneratorInterface/LHEInterface/plugins/LHECOMWeightProducer.cc
  GeneratorInterface/LHEInterface/plugins/LHEFilter.cc
  GeneratorInterface/LHEInterface/plugins/LHEWriter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37241 Make TrackWithVertexSelector able to run without vertex inputTag
  CommonTools/RecoAlgos/src/TrackWithVertexSelector.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37274 [12_3_X] Add CMSSW version to StatisticsSenderService
  Utilities/StorageFactory/BuildFile.xml
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37275 [12_2_X] Add CMSSW version to StatisticsSenderService
  Utilities/StorageFactory/BuildFile.xml
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37277 [12_1_X] Add CMSSW version to StatisticsSenderService
  Utilities/StorageFactory/BuildFile.xml
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, backport-ok

#37293 [Core][RH8] Fix unit test to use python3
  IOPool/Common/test/run_TestEdmConfigDump.sh
Labels: core-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#37180 Refactore PropagateToMuon and add propagation to L3 muon filters at HLT
  DQMOffline/L1Trigger/interface/L1TMuonDQMOffline.h
  DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py
  DQMOffline/L1Trigger/src/L1TMuonDQMOffline.cc
  HLTrigger/Muon/plugins/BuildFile.xml
  HLTrigger/Muon/plugins/HLTMuonDimuonL3Filter.cc
  HLTrigger/Muon/plugins/HLTMuonDimuonL3Filter.h
  HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc
  HLTrigger/Muon/plugins/HLTMuonL3PreFilter.h
  HLTrigger/Muon/plugins/HLTMuonTrkFilter.cc
  HLTrigger/Muon/plugins/HLTMuonTrkFilter.h
  HLTrigger/Muon/plugins/HLTMuonTrkL1TFilter.cc
  HLTrigger/Muon/plugins/HLTMuonTrkL1TFilter.h
  L1Trigger/L1TNtuples/interface/L1AnalysisRecoMuon2.h
  L1Trigger/L1TNtuples/plugins/L1Muon2RecoTreeProducer.cc
  L1Trigger/L1TNtuples/python/l1MuonRecoTree_cfi.py
  L1Trigger/L1TNtuples/src/L1AnalysisRecoMuon2.cc
  MuonAnalysis/MuonAssociators/interface/L1MuonMatcherAlgo.h
  MuonAnalysis/MuonAssociators/interface/PropagateToMuon.h
  MuonAnalysis/MuonAssociators/interface/PropagateToMuonSetup.h
  MuonAnalysis/MuonAssociators/interface/trackStateEnums.h
  MuonAnalysis/MuonAssociators/plugins/TriggerMatcherToHLTDebug.cc
  MuonAnalysis/MuonAssociators/src/L1MuonMatcherAlgo.cc
  MuonAnalysis/MuonAssociators/src/PropagateToMuon.cc
  MuonAnalysis/MuonAssociators/src/PropagateToMuonSetup.cc
Labels: dqm-pending, l1-pending, hlt-pending, analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#37282 Fix resolution validation plots after moving ME1a CLCT from ring 4 to ring 1
  Validation/MuonCSCDigis/src/CSCStubResolutionValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37288 Cosmetic improvement in printout of Payload Inspector plots for DropBoxMetaData
  CondCore/PhysicsToolsPlugins/interface/DropBoxMetaDataPayloadInspectorHelper.h
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#37174 DQM modules to monitor Pixel RecHits for heterogenous workflows
  DQM/SiPixelPhase1Heterogeneous/plugins/BuildFile.xml
  DQM/SiPixelPhase1Heterogeneous/plugins/SiPixelPhase1MonitorRecHitsSoA.cc
  DQM/SiPixelPhase1Heterogeneous/python/SiPixelPhase1HeterogenousDQM_FirstStep_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved, heterogeneous-approved

#37311 [11_0_X] Add CMSSW version to StatisticsSenderService
  Utilities/StorageFactory/BuildFile.xml
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved

#37300 [11_3_X] Add CMSSW version to StatisticsSenderService
  Utilities/StorageFactory/BuildFile.xml
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved

#37273 [12_3_X] Make sure all dictionaries in CUDADataFormats are transient
  CUDADataFormats/CaloCommon/src/classes_def.xml
  CUDADataFormats/HcalDigi/src/classes_def.xml
  CUDADataFormats/HcalRecHitSoA/src/classes_def.xml
  CUDADataFormats/StdDictionaries/src/classes_def.xml
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, heterogeneous-approved

#37296 Run3-hcx331 Replace cout with messagelogger commands
  Validation/HcalDigis/interface/ZDCDigiStudy.h
  Validation/HcalDigis/src/HcalDigisClient.cc
  Validation/HcalDigis/src/ZDCDigiStudy.cc
  Validation/HcalDigis/test/ZdcSimHitStudy_cfg.py
  Validation/HcalRecHits/src/HcalRecHitsValidation.cc
  Validation/HcalRecHits/src/NoiseRatesClient.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37202 Run3-sim113 Take care of deprecated codes in FastSimulation/Validation
  FastSimulation/Validation/plugins/EmptySimHits.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37283 update of `hltIntegrationTests` and path of Run-3 Data file for TSG tests
  Configuration/HLT/python/addOnTestsHLT.py
  HLTrigger/Configuration/scripts/hltCompareResults
  HLTrigger/Configuration/scripts/hltIntegrationTests
  HLTrigger/Configuration/scripts/hltListPaths
  HLTrigger/Configuration/test/cmsDriver.csh
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37299 Backport the refactoring of the PropagateToMuon class and add the propagating to some HLT filters
  DQMOffline/L1Trigger/interface/L1TMuonDQMOffline.h
  DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py
  DQMOffline/L1Trigger/src/L1TMuonDQMOffline.cc
  HLTrigger/Muon/plugins/BuildFile.xml
  HLTrigger/Muon/plugins/HLTMuonDimuonL3Filter.cc
  HLTrigger/Muon/plugins/HLTMuonDimuonL3Filter.h
  HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc
  HLTrigger/Muon/plugins/HLTMuonL3PreFilter.h
  HLTrigger/Muon/plugins/HLTMuonTrkFilter.cc
  HLTrigger/Muon/plugins/HLTMuonTrkFilter.h
  HLTrigger/Muon/plugins/HLTMuonTrkL1TFilter.cc
  HLTrigger/Muon/plugins/HLTMuonTrkL1TFilter.h
  L1Trigger/L1TNtuples/interface/L1AnalysisRecoMuon2.h
  L1Trigger/L1TNtuples/plugins/L1Muon2RecoTreeProducer.cc
  L1Trigger/L1TNtuples/python/l1MuonRecoTree_cfi.py
  L1Trigger/L1TNtuples/src/L1AnalysisRecoMuon2.cc
  MuonAnalysis/MuonAssociators/interface/L1MuonMatcherAlgo.h
  MuonAnalysis/MuonAssociators/interface/PropagateToMuon.h
  MuonAnalysis/MuonAssociators/interface/PropagateToMuonSetup.h
  MuonAnalysis/MuonAssociators/interface/trackStateEnums.h
  MuonAnalysis/MuonAssociators/plugins/TriggerMatcherToHLTDebug.cc
  MuonAnalysis/MuonAssociators/src/L1MuonMatcherAlgo.cc
  MuonAnalysis/MuonAssociators/src/PropagateToMuon.cc
  MuonAnalysis/MuonAssociators/src/PropagateToMuonSetup.cc
Labels: analysis-pending, dqm-approved, hlt-approved, l1-approved, pending-signatures, tests-approved, orp-approved, backport-ok

#37172 Clue3D absolute metric
  RecoHGCal/TICL/plugins/PatternRecognitionbyCLUE3D.cc
  RecoHGCal/TICL/plugins/PatternRecognitionbyCLUE3D.h
  RecoHGCal/TICL/python/CLUE3DHighStep_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37303 [11_1_X] Add CMSSW version to StatisticsSenderService
  Utilities/StorageFactory/BuildFile.xml
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved

#37295 [12_0_X] Add CMSSW version to StatisticsSenderService
  Utilities/StorageFactory/BuildFile.xml
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved

#37310 loose indirect dependency on obsolete stage-1 L1T records in `DQMOffline/JetMET`
  DQMOffline/JetMET/python/metDQMConfig_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#37306 Change ALCALUMIPIXELSEXPRESS to ALCALumiPixelsCountsExpress in autoAlCa.py
  Configuration/AlCa/python/autoAlca.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#37320 [10_6_X] Add CMSSW version to StatisticsSenderService
  Utilities/StorageFactory/BuildFile.xml
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved

#37304 update of `hltIntegrationTests` and path of Run-3 Data file for TSG tests [`12_3_X`]
  Configuration/HLT/python/addOnTestsHLT.py
  HLTrigger/Configuration/scripts/hltCompareResults
  HLTrigger/Configuration/scripts/hltIntegrationTests
  HLTrigger/Configuration/scripts/hltListPaths
  HLTrigger/Configuration/test/cmsDriver.csh
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#37292 updated path to EDM file for TSG tests on Run-3 Data [`12_2_X`]
  Configuration/HLT/python/addOnTestsHLT.py
  HLTrigger/Configuration/test/cmsDriver.csh
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok
