Repository cms-sw/cmssw, pull requests merged in 2022-08, with the labels that each got.

#38883 Clamp the number of pixel tracks to the capacity of the SoA
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelTrackSoAFromCUDA.cc
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernelsImpl.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorOnGPU.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#38905 ignore input file location characters in `IBooker::bookME` ME path check
  DQMServices/Core/src/DQMStore.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#38913 Update of L1T menu in TSG GTs to `L1Menu_Collisions2022_v1_3_0-d1_xml`
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38910 HCAL: small fix of HcalTBSource
  IORawData/HcalTBInputService/plugins/HcalTBSource.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, hcal

#38896 HCAL: Group 0 LUT edited to set LLP bits in HB only, not HE
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
Labels: alca-approved, l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, hcal

#38884 Clamp the number of pixel tracks to the capacity of the SoA [12.4.x]
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelTrackSoAFromCUDA.cc
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernelsImpl.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorOnGPU.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok

#38875 Throw GetByLabelWithoutRegistration exception also when no module in a job registered consumption of a given branch
  FWCore/Framework/src/Principal.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/TestGetByLabelAnalyzer.cc
  FWCore/Integration/test/run_TestGetByLabel.sh
  FWCore/Integration/test/testGetByLabelStep1_cfg.py
  FWCore/Integration/test/testGetByLabelStep2_cfg.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38914 Update of L1T menu in TSG GTs to `L1Menu_Collisions2022_v1_3_0-d1_xml` [`12_4_X`]
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok

#38848 HLT release validation and offline DQM for EXO-LLP Run 3 HLT paths, updated to HLT menu V1.3 (2022)
  DQMOffline/Trigger/python/DiDispStaMuonMonitor_cff.py
  DQMOffline/Trigger/python/DisplacedJet_Monitor_cff.py
  DQMOffline/Trigger/python/MuonMonitor_cff.py
  DQMOffline/Trigger/python/PhotonMonitor_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaDisplacedDiPhoton_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaDisplacedDimuon_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaDisplacedL2Dimuon_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaHTDisplacedJets_cff.py
  HLTriggerOffline/Exotica/python/analyses/hltExoticaHighPtPhoton_cff.py
  HLTriggerOffline/Exotica/python/hltExoticaPostProcessors_cff.py
  HLTriggerOffline/Exotica/python/hltExoticaValidator_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38818 GEM Timing Plots
  DQM/L1TMonitor/interface/L1TStage2EMTF.h
  DQM/L1TMonitor/src/L1TStage2EMTF.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, new-feature, code-checks-approved, gem

#38911 [NanoAOD] Correct filter name for Run3 Isomu triggers
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#38868 Automatically size the Pixel FED buffer used by SiPixelRawToClusterCUDA
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterCUDA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.h
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClusterChargeCut.h
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClustering.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#38930 Fixed PPS Global Alignment paths
  CalibPPS/AlignmentGlobal/plugins/PPSAlignmentHarvester.cc
  CalibPPS/AlignmentGlobal/plugins/PPSAlignmentWorker.cc
  CalibPPS/ESProducers/plugins/PPSAlignmentConfigurationESSource.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, ctpps

#38918 Bug Fix In PatternRecognitionByFastJet
  RecoHGCal/TICL/plugins/PatternRecognitionbyFastJet.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#38926 limit the number of seeds, same as in CkfTrackCandidateMakerBase
  RecoTracker/MkFit/plugins/MkFitSeedConverter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38923 [124X backport] HCAL: Group 0 LUT edited to set LLP bits in HB only, not HE
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
Labels: alca-approved, l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, hcal

#38912 [Backport 124X] [NanoAOD] Correct filter name for Run3 Isomu triggers
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#38920 Various fixes for pixel clustering on GPU
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernelsImpl.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#38900 Fix L1GtUtilsHelper's search for data products to consume
  L1Trigger/GlobalTriggerAnalyzer/interface/L1GtUtilsHelper.h
  L1Trigger/GlobalTriggerAnalyzer/src/L1GtUtilsHelper.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38891 DQM for PFMETMHT paths with HF Filter
  DQMOffline/Trigger/python/METMonitor_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38908 Fixed codes which causes memory issue by GEM onlineDQM
  DQM/GEM/interface/GEMDQMBase.h
  DQM/GEM/plugins/GEMDigiSource.cc
  DQM/GEM/plugins/GEMRecHitSource.cc
  DQM/GEM/src/GEMDQMBase.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38915 Add new class PPSTimingCalibration for Payload Inspector
  CalibPPS/TimingCalibration/test/visualization/graph.py
  CondCore/CTPPSPlugins/interface/PPSTimingCalibrationPayloadInspectorHelper.h
  CondCore/CTPPSPlugins/plugins/BuildFile.xml
  CondCore/CTPPSPlugins/plugins/PPSTimingCalibration_PayloadInspector.cc
  CondCore/CTPPSPlugins/test/BuildFile.xml
  CondCore/CTPPSPlugins/test/graph_check.py
  CondCore/CTPPSPlugins/test/testPPSTimingCalibration.cpp
  CondCore/CTPPSPlugins/test/testPPSTimingCalibration.sh
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, new-feature, code-checks-approved, ctpps

#38931 [124X] Fixed PPS Global Alignment path
  CalibPPS/AlignmentGlobal/plugins/PPSAlignmentHarvester.cc
  CalibPPS/AlignmentGlobal/plugins/PPSAlignmentWorker.cc
  CalibPPS/ESProducers/plugins/PPSAlignmentConfigurationESSource.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, ctpps

#38927 limit the number of seeds, same as in CkfTrackCandidateMakerBase (backport of #38926)
  RecoTracker/MkFit/plugins/MkFitSeedConverter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#38849 Optimized version of G4 Dormand Prince RK stepper
  SimG4Core/MagneticField/interface/Field.h
  SimG4Core/MagneticField/src/CMSTDormandPrince45.h
  SimG4Core/MagneticField/src/CMSTMagFieldEquation.h
  SimG4Core/MagneticField/src/Field.cc
  SimG4Core/MagneticField/src/FieldBuilder.cc
  SimG4Core/MagneticField/src/FieldStepper.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38834 Add NANO step and Mini+Nano validations to FastSim workflows
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/relval_upgrade.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/Harvesting_cff.py
  DQMOffline/Configuration/python/DQMOfflineFS_cff.py
  DQMOffline/Muon/python/muonAnalyzer_cff.py
  Validation/RecoTau/python/DQMMCValidation_cfi.py
  Validation/RecoTau/python/RecoTauValidation_cff.py
Labels: dqm-approved, fastsim-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#38949 Removed obsolete PrintInfo() function from G4muDarkBremsstrahlung
  SimG4Core/CustomPhysics/interface/G4muDarkBremsstrahlung.h
  SimG4Core/CustomPhysics/interface/G4muDarkBremsstrahlungModel.h
  SimG4Core/CustomPhysics/src/G4muDarkBremsstrahlung.cc
  SimG4Core/CustomPhysics/src/G4muDarkBremsstrahlungModel.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38921 Various fixes for pixel clustering on GPU [12.4.x]
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletGeneratorKernelsImpl.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent

#38872 Call callWhenNewProductsRegistered() callbacks only for branches that are present
  DataFormats/Provenance/interface/ProductRegistry.h
  FWCore/Framework/src/SignallingProductRegistry.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38603 Concurrently construct Source while making Modules
  DataFormats/Provenance/interface/ProductRegistry.h
  DataFormats/Provenance/src/ProductRegistry.cc
  FWCore/Framework/interface/GlobalSchedule.h
  FWCore/Framework/interface/InputSource.h
  FWCore/Framework/interface/Schedule.h
  FWCore/Framework/interface/ScheduleItems.h
  FWCore/Framework/interface/StreamSchedule.h
  FWCore/Framework/interface/UnscheduledCallProducer.h
  FWCore/Framework/interface/WorkerManager.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/GlobalSchedule.cc
  FWCore/Framework/src/Schedule.cc
  FWCore/Framework/src/ScheduleItems.cc
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/src/WorkerManager.cc
  FWCore/Integration/test/DelayedReaderThrowingSource.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38847 Phase2-hgx319C Modify the test scrpts to check if all wafers in the flat file are in the list of valid modules
  Geometry/HGCalGeometry/test/HGCalWaferInFileCheck.cc
  Geometry/HGCalGeometry/test/HGCalWaferTypeTester.cc
  Geometry/HGCalGeometry/test/python/testHGCalWaferInFileCheck_cfg.py
  Geometry/HGCalGeometry/test/python/testHGCalWaferTypeTester_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#37695 ECAL Phase 2 weights method amplitude reconstruction on GPU
  CUDADataFormats/EcalRecHitSoA/interface/EcalUncalibratedRecHit.h
  RecoLocalCalo/EcalRecProducers/plugins/DeclsForKernelsPhase2.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalCPUUncalibRecHitProducer.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalPhase2DigiToGPUProducer.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitConvertGPU2CPUFormat.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitPhase2WeightsAlgoGPU.cu
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitPhase2WeightsAlgoGPU.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitPhase2WeightsKernels.cu
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitPhase2WeightsKernels.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitPhase2WeightsProducer.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitPhase2WeightsProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/python/ecalUncalibRecHitPhase2GPU_cfi.py
  RecoLocalCalo/EcalRecProducers/python/ecalUncalibRecHitPhase2_cff.py
  RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRecHitPhase2WeightsProducerGPU.py
  RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRecHitPhase2WeightsProducerGPU_harvesting.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved, ecal

#38280 [PPS] Direct simulation as sequence
  Configuration/Eras/python/Era_Phase2_cff.py
  Configuration/Eras/python/Era_Run3_cff.py
  Configuration/Eras/python/Modifier_ctpps_2022_cff.py
  Configuration/StandardSequences/python/Eras.py
  EventFilter/CTPPSRawToDigi/python/ctppsDigiToRaw_cff.py
  EventFilter/RawDataCollector/python/rawDataCollector_cfi.py
  Geometry/VeryForwardGeometry/python/commons_cff.py
  RecoPPS/Configuration/python/recoCTPPS_cff.py
  RecoPPS/Local/python/ctppsLocalTrackLiteProducer_cff.py
  SimGeneral/MixingModule/python/mixObjects_cfi.py
  SimPPS/Configuration/python/GenPPS_cff.py
  SimPPS/Configuration/python/SimPPS_cff.py
  SimPPS/Configuration/python/Utils.py
  SimPPS/Configuration/python/directSimPPS_cff.py
  SimPPS/DirectSimProducer/plugins/BuildFile.xml
  SimPPS/DirectSimProducer/plugins/PPSDirectProtonSimulation.cc
  SimPPS/DirectSimProducer/python/matching_cff.py
  SimPPS/DirectSimProducer/python/ppsDirectProtonSimulation_cff.py
  SimPPS/DirectSimProducer/python/profile_base_cff.py
  SimPPS/DirectSimProducer/python/profiles_2016_cff.py
  SimPPS/DirectSimProducer/python/profiles_2017_cff.py
  SimPPS/DirectSimProducer/python/profiles_2018_cff.py
  SimPPS/DirectSimProducer/python/profiles_2022_cff.py
  SimPPS/DirectSimProducer/python/simPPS2016_cfi.py
  SimPPS/DirectSimProducer/python/simPPS2017_cfi.py
  SimPPS/DirectSimProducer/python/simPPS2018_cfi.py
  SimPPS/DirectSimProducer/python/simPPS2022_cfi.py
  SimPPS/DirectSimProducer/test/test_miniAOD_cfg.py
  SimTransport/PPSProtonTransport/python/PPSTransport_cff.py
  Validation/CTPPS/python/base_cff.py
  Validation/CTPPS/python/simu_config/base_cff.py
  Validation/CTPPS/python/simu_config/profile_2016_postTS2_cff.py
  Validation/CTPPS/python/simu_config/profile_2016_preTS2_cff.py
  Validation/CTPPS/python/simu_config/profile_2017_postTS2_cff.py
  Validation/CTPPS/python/simu_config/profile_2017_preTS2_cff.py
  Validation/CTPPS/python/simu_config/profile_2018_TS1_TS2_cff.py
  Validation/CTPPS/python/simu_config/profile_2018_postTS2_cff.py
  Validation/CTPPS/python/simu_config/profile_2018_preTS1_cff.py
  Validation/CTPPS/python/simu_config/profile_2021_default_cff.py
  Validation/CTPPS/python/simu_config/profile_2022_default_cff.py
  Validation/CTPPS/python/simu_config/year_2016_cff.py
  Validation/CTPPS/python/simu_config/year_2017_cff.py
  Validation/CTPPS/python/simu_config/year_2018_cff.py
  Validation/CTPPS/python/simu_config/year_2021_cff.py
  Validation/CTPPS/python/simu_config/year_2022_cff.py
  Validation/CTPPS/test/simu/run_multiple
  Validation/CTPPS/test/simu/template_cfg.py
Labels: daq-approved, dqm-approved, geometry-approved, operations-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38901 Dark Bremsstrahlung backport to 10_6_X
  SimG4Core/CustomPhysics/BuildFile.xml
  SimG4Core/CustomPhysics/interface/APrimePhysics.h
  SimG4Core/CustomPhysics/interface/DBremWatcher.h
  SimG4Core/CustomPhysics/interface/G4APrime.h
  SimG4Core/CustomPhysics/interface/G4muDarkBremsstrahlung.h
  SimG4Core/CustomPhysics/interface/G4muDarkBremsstrahlungModel.h
  SimG4Core/CustomPhysics/python/DarkBrem_SIM_cfi.py
  SimG4Core/CustomPhysics/src/APrimePhysics.cc
  SimG4Core/CustomPhysics/src/CustomPhysics.cc
  SimG4Core/CustomPhysics/src/DBremWatcher.cc
  SimG4Core/CustomPhysics/src/G4APrime.cc
  SimG4Core/CustomPhysics/src/G4muDarkBremsstrahlung.cc
  SimG4Core/CustomPhysics/src/G4muDarkBremsstrahlungModel.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved

#38961 Added protection against out-of-range BX values in EMTF unpacker blocks
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockGEM.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockME.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockRPC.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockSP.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38963 HLTrigger/Timer: add function FastTimerService::fix_for_dqm which replaces check for illegal dqm characters for path so it can be used on paths and labels.
  HLTrigger/Timer/plugins/FastTimerService.cc
  HLTrigger/Timer/plugins/FastTimerService.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38965 Remove obsolete printInfo from G4muDarkBremsstrahlung
  SimG4Core/CustomPhysics/interface/G4muDarkBremsstrahlung.h
  SimG4Core/CustomPhysics/interface/G4muDarkBremsstrahlungModel.h
  SimG4Core/CustomPhysics/src/G4muDarkBremsstrahlung.cc
  SimG4Core/CustomPhysics/src/G4muDarkBremsstrahlungModel.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved

#38946 Detect and remove all duplicate pixels
  DataFormats/SiPixelDigi/interface/SiPixelDigiConstants.h
  HeterogeneousCore/CUDAUtilities/interface/cudaCompat.h
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClusterChargeCut.h
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClustering.h
  RecoLocalTracker/SiPixelClusterizer/test/gpuClustering_t.h
Labels: reconstruction-approved, simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, heterogeneous-approved

#38871 [124X backport] Keep Run2 EGamma IDs in Run3 nano(v10)
  PhysicsTools/NanoAOD/plugins/VIDNestedWPBitmapProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/PatAlgos/plugins/PATObjectUserDataEmbedder.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#38726 DeepTau v2p5 in nanoAOD
  PhysicsTools/NanoAOD/python/boostedTaus_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/RecoTau/python/tauIdWPsDefs.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#38951 Update alcareco matrix
  Configuration/AlCa/python/autoAlca.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38947 Detect and remove all duplicate pixels [12.4.x]
  DataFormats/SiPixelDigi/interface/SiPixelDigiConstants.h
  HeterogeneousCore/CUDAUtilities/interface/cudaCompat.h
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClusterChargeCut.h
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClustering.h
  RecoLocalTracker/SiPixelClusterizer/test/gpuClustering_t.h
Labels: reconstruction-approved, simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, heterogeneous-approved

#38966 Improve the handling of module labels unsafe for DQM
  HLTrigger/Timer/plugins/FastTimerService.cc
  HLTrigger/Timer/plugins/FastTimerService.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38870 Addition of saturated flag in SiStrip Approximate Clusters
  DataFormats/SiStripCluster/interface/SiStripApproximateCluster.h
  DataFormats/SiStripCluster/src/SiStripApproximateCluster.cc
  DataFormats/SiStripCluster/src/classes_def.xml
  RecoLocalTracker/SiStripClusterizer/plugins/SiStripApprox2ApproxClusters.cc
  RecoLocalTracker/SiStripClusterizer/plugins/SiStripClusters2ApproxClusters.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38893 Add run3 PPS TDC and SAMPIC relvals
  CalibPPS/TimingCalibration/plugins/PPSDiamondSampicTimingCalibrationPCLHarvester.cc
  CondFormats/PPSObjects/src/PPSTimingCalibration.cc
  Configuration/PyReleaseValidation/python/relval_production.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, new-feature, urgent, upgrade-approved, code-checks-approved, ctpps

#38957 Adding a random seed for random number generator of HGCAL MC generation
  Validation/HGCalValidation/scripts/testHGCalSingleMuonPt100_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38751 DeepTau v2p5 in nanoAOD [12_4_X]
  PhysicsTools/NanoAOD/python/boostedTaus_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  RecoTauTag/RecoTau/python/tauIdWPsDefs.py
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, xpog-approved, tau

#38886 TOTEM nT2 unpacker
  CalibPPS/ESProducers/plugins/TotemDAQMappingESSourceXML.cc
  CalibPPS/ESProducers/python/totemT2DAQMapping_cff.py
  CondFormats/PPSObjects/xml/mapping_totem_nt2_2021.xml
  DataFormats/CTPPSDetId/interface/CTPPSDetId.h
  DataFormats/CTPPSDetId/interface/TotemT2DetId.h
  DataFormats/CTPPSDetId/src/CTPPSDetId.cc
  DataFormats/CTPPSDetId/src/TotemT2DetId.cc
  DataFormats/FEDRawData/interface/FEDNumbering.h
  DataFormats/TotemReco/BuildFile.xml
  DataFormats/TotemReco/interface/TotemT2Digi.h
  DataFormats/TotemReco/src/TotemT2Digi.cc
  DataFormats/TotemReco/src/classes.h
  DataFormats/TotemReco/src/classes_def.xml
  EventFilter/CTPPSRawToDigi/BuildFile.xml
  EventFilter/CTPPSRawToDigi/interface/RawToDigiConverter.h
  EventFilter/CTPPSRawToDigi/interface/TotemT2VFATFrame.h
  EventFilter/CTPPSRawToDigi/plugins/TotemTriggerRawToDigi.cc
  EventFilter/CTPPSRawToDigi/plugins/TotemVFATRawToDigi.cc
  EventFilter/CTPPSRawToDigi/python/ctppsRawToDigi_cff.py
  EventFilter/CTPPSRawToDigi/python/totemT2Digis_cfi.py
  EventFilter/CTPPSRawToDigi/src/RawToDigiConverter.cc
Labels: alca-approved, daq-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, new-feature, code-checks-approved, ctpps

#38981 Fix PPS timing detectors record and tag names for PCL
  CalibPPS/TimingCalibration/plugins/PPSDiamondSampicTimingCalibrationPCLHarvester.cc
  CalibPPS/TimingCalibration/plugins/PPSTimingCalibrationPCLHarvester.cc
  CalibPPS/TimingCalibration/test/DiamondSampicCalibrationHarvester_cfg.py
  CalibPPS/TimingCalibration/test/DiamondSampicCalibrationWorker_cfg.py
  CondFormats/Common/data/PPSTimingCalibrationRcd_Sampic_prep.json
  CondFormats/Common/data/PPSTimingCalibrationRcd_Sampic_prod.json
  CondFormats/Common/test/ProduceDropBoxMetadata.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
Labels: alca-approved, operations-approved, fully-signed, tests-approved, db-approved, bug-fix, orp-approved, urgent, requires-external, code-checks-approved, ctpps

#38925 Update run for DQM beamhlt client unitTest
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#38933 Update the autoSkim.py for new HLT menu v1.3
  Configuration/DataProcessing/test/run_CfgTest.sh
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/Skimming/python/autoSkim.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#38982 [124X] Fix PPS timing detectors record and tag names for PCL, fix further bugs for SAMPIC wf
  CalibPPS/TimingCalibration/plugins/PPSDiamondSampicTimingCalibrationPCLHarvester.cc
  CalibPPS/TimingCalibration/plugins/PPSTimingCalibrationPCLHarvester.cc
  CalibPPS/TimingCalibration/test/DiamondSampicCalibrationHarvester_cfg.py
  CalibPPS/TimingCalibration/test/DiamondSampicCalibrationWorker_cfg.py
  CondFormats/Common/data/PPSTimingCalibrationRcd_Sampic_prep.json
  CondFormats/Common/data/PPSTimingCalibrationRcd_Sampic_prod.json
  CondFormats/Common/test/ProduceDropBoxMetadata.py
  CondFormats/PPSObjects/src/PPSTimingCalibration.cc
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
Labels: alca-approved, operations-approved, fully-signed, tests-approved, db-approved, bug-fix, orp-approved, urgent, backport-ok, ctpps

#38909 Update the autoSkim.py for new HLT menu v1.3
  Configuration/Skimming/python/autoSkim.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved

#38916 Adding JECs, PF and L1T menu to Run-3 MC GTs and data relval GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, hlt-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#38994 Moved DBremWatcher to plugins directory
  SimG4Core/CustomPhysics/plugins/DBremWatcher.cc
  SimG4Core/CustomPhysics/plugins/DBremWatcher.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38917 Fix L1TGlobalUtilsHelper's search for data products to consume
  L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h
  L1Trigger/L1TGlobal/src/L1TGlobalUtilHelper.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38955 Replace_Geometry_cff with GeometryDB_cff in TrackingTools
  TrackingTools/TrackAssociator/test/TestTrackAssociator.py
  TrackingTools/TrackRefitter/test/CosmicTrajectoryReader_cfg.py
  TrackingTools/TrackRefitter/test/TrackReader_cfg.py
  TrackingTools/TrackRefitter/test/TrajectoryReader_cfg.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38748 Integration of ParticleNET-HLT AK4 and AK8 DQM Monitoring
  DQMOffline/Trigger/plugins/BuildFile.xml
  DQMOffline/Trigger/plugins/ParticleNetJetTagMonitor.cc
  DQMOffline/Trigger/python/DQMOffline_HLT_Client_cff.py
  DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py
  DQMOffline/Trigger/python/ParticleNetJetTagMonitoring_cfi.py
  DQMOffline/Trigger/python/ParticleNetJetTag_Client_cfi.py
  L1Trigger/Configuration/python/customiseUtils.py
  RecoBTag/Configuration/python/RecoBTag_cff.py
  RecoBTag/ONNXRuntime/python/pfParticleNetAK4_cff.py
Labels: dqm-approved, l1-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, btv

#38952 Replace Geometry_cff with GeometryDB_cff in PhysicsTools
  PhysicsTools/HepMCCandAlgos/test/testFlavorHistoryProducer.py
  PhysicsTools/PatAlgos/test/btag-from-packedPat.py
  PhysicsTools/PatAlgos/test/miniAOD/example_addJet.py
  PhysicsTools/PatAlgos/test/miniAOD/example_ei.py
  PhysicsTools/PatAlgos/test/miniAOD/example_jet_and_met.py
  PhysicsTools/PatAlgos/test/private/patLayer1_fromAOD-minimal.cfg.py
  PhysicsTools/PatAlgos/test/private/testPATUserDataExternal.py
  PhysicsTools/PatExamples/test/MuonAnalyzer_cfg.py
  PhysicsTools/PatExamples/test/analyzePatAnalysisTasks_cfg.py
  PhysicsTools/PatExamples/test/analyzePatBJetTags_cfg.py
  PhysicsTools/PatExamples/test/analyzePatBJetTracks_cfg.py
  PhysicsTools/PatExamples/test/analyzePatBJetVertex_cfg.py
  PhysicsTools/PatExamples/test/analyzePatBTag_cfg.py
  PhysicsTools/PatExamples/test/analyzePatElectron_cfg.py
  PhysicsTools/PatExamples/test/analyzePatTau_fromAOD_cfg.py
  PhysicsTools/PatExamples/test/analyzePatTau_fromPatTuple_cfg.py
  PhysicsTools/PatExamples/test/analyzePatTracks_cfg.py
  PhysicsTools/PatExamples/test/analyzePatTrigger_onTheFly_cfg.py
  PhysicsTools/PatExamples/test/analyzePatVertex_cfg.py
  PhysicsTools/TagAndProbe/test/Electron_TagProbeTreeProducer_cfg.py
  PhysicsTools/TagAndProbe/test/testTagProbeFitTreeProducer_JPsi.py
Labels: analysis-pending, reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved

#38988 Handle pixel modules with all invalid pixels
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClusterChargeCut.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#38989 Handle pixel modules with all invalid pixels [12.4.x]
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClusterChargeCut.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport

#38992 Re-add class version SiStripApproximateCluster
  DataFormats/SiStripCluster/src/classes_def.xml
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39002 move `PCLMetadataWriter` from `Calibration/TkAlCaRecoProducers` to `CommonTools/ConditionDBWriter`
  Calibration/TkAlCaRecoProducers/plugins/BuildFile.xml
  CommonTools/ConditionDBWriter/plugins/BuildFile.xml
  CommonTools/ConditionDBWriter/plugins/PCLMetadataWriter.cc
  CommonTools/ConditionDBWriter/python/PCLMetadataWriter_cfi.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
Labels: alca-approved, operations-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#39004 Moved DBremWatcher to plugins directory
  SimG4Core/CustomPhysics/plugins/DBremWatcher.cc
  SimG4Core/CustomPhysics/plugins/DBremWatcher.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39003 Moved DBremWatcher to plugins directory
  SimG4Core/CustomPhysics/plugins/DBremWatcher.cc
  SimG4Core/CustomPhysics/plugins/DBremWatcher.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39013 add support for `ALCARECOTkAlJetHT` to `trackselectionRefitting`
  Alignment/CommonAlignment/python/tools/trackselectionRefitting.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#39009 Fix unit test scenario issue
  Configuration/DataProcessing/test/run_CfgTest.sh
  Configuration/Skimming/python/autoSkim.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved

#39010 Vertex smearing for 2022 PbPb based on pp centroid and 2018 PbPb width
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedNominal2022PbPbCollision_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38991 Cleanup of totemTriggerRawToDigi sequence remnants
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#38985 PPS naming anonymous namespace
  CondFormats/PPSObjects/interface/CTPPSPixelIndices.h
  CondFormats/PPSObjects/src/PPSPixelTopology.cc
  DQM/CTPPS/plugins/CTPPSPixelDQMSource.cc
  EventFilter/CTPPSRawToDigi/src/CTPPSPixelDataFormatter.cc
Labels: alca-approved, dqm-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, ctpps

#38959 Add tracking efficiencies w.r.t. offline to HLT monitoring client
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#39015 [12.4.X] add support for `ALCARECOTkAlJetHT` to `trackselectionRefitting`
  Alignment/CommonAlignment/python/tools/trackselectionRefitting.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#39022 Backport option to override GEN decays with FastSim decays
  FastSimulation/SimplifiedGeometryPropagator/interface/Decayer.h
  FastSimulation/SimplifiedGeometryPropagator/interface/ParticleManager.h
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
  FastSimulation/SimplifiedGeometryPropagator/python/fastSimProducer_cff.py
  FastSimulation/SimplifiedGeometryPropagator/src/Decayer.cc
  FastSimulation/SimplifiedGeometryPropagator/src/ParticleManager.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved

#39018 Utilities/StaticAnalyzer: Add TFileServer:: functions to list of known thread unsafe functions.
  Utilities/StaticAnalyzers/scripts/create_statics_esd_reports.sh
  Utilities/StaticAnalyzers/scripts/statics.py
  Utilities/StaticAnalyzers/src/CmsSupport.cpp
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38973 Adding tracking efficiencies w.r.t. offline to HLT monitoring client [124X]
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#39014 Delete deprecated scripts accessing geometry with prior-run2 GT in Calibration/Hcal
  Calibration/HcalAlCaRecoProducers/test/di_cfg.py
  Calibration/HcalAlCaRecoProducers/test/phi_sym_cfg.py
  Calibration/HcalCalibAlgos/test/batchjob_analisotrk.csh
  Calibration/HcalCalibAlgos/test/batchjob_calib_valid.csh
  Calibration/HcalCalibAlgos/test/batchjob_pf_corrs.csh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, hcal

#39024 Add remaining plots for PPSTimingCalibration for Payload Inspector
  CondCore/CTPPSPlugins/interface/PPSTimingCalibrationPayloadInspectorHelper.h
  CondCore/CTPPSPlugins/plugins/PPSTimingCalibration_PayloadInspector.cc
  CondCore/CTPPSPlugins/test/testPPSTimingCalibration.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#39025 Adjustments to `SiPixelCalSingleMuon` producers
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonLoose_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonTight_cff.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#39020 Added new bit for mu+tau+jet filter
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#38950 Remove duplicate pixels [12.4.x]
  DataFormats/SiPixelCluster/interface/SiPixelCluster.h
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok

#38974 Fix the delay of the CPPF DAQ data
  EventFilter/RPCRawToDigi/plugins/RPCAMCUnpacker.cc
  EventFilter/RPCRawToDigi/plugins/RPCCPPFUnpacker.cc
  EventFilter/RPCRawToDigi/plugins/RPCCPPFUnpacker.h
  EventFilter/RPCRawToDigi/python/RPCCPPFRawToDigi_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39023 Fix configuration for BPHMonitor
  DQMOffline/Trigger/plugins/BPHMonitor.cc
  HLTrigger/HLTcore/interface/HLTPrescaleProvider.h
  HLTrigger/HLTcore/src/HLTPrescaleProvider.cc
  L1Trigger/L1TGlobal/interface/L1TGlobalUtil.h
  L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h
  L1Trigger/L1TGlobal/src/L1TGlobalUtilHelper.cc
Labels: dqm-approved, hlt-approved, l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#39032 Extend CMS protections in Geant4 exception handling
  SimG4Core/Application/src/ExceptionHandler.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39036 Update MPI tools and tests
  HeterogeneousCore/CUDACore/test/BuildFile.xml
  HeterogeneousCore/CUDACore/test/mpiCudaGeneric.cu
  HeterogeneousCore/MPICore/scripts/cmsenv_mpirun
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#39039 Utilities/StaticAnalyzers: fix errors found in IB static analyzer jobs
  Utilities/StaticAnalyzers/scripts/class-composition.py
  Utilities/StaticAnalyzers/scripts/run_class_dumper.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39029 implement event consumes in `MuScleFit`
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFit.cc
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFitMuonSelector.cc
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFitMuonSelector.h
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, trk

#39035 Fix Tracker Alignment overlap validation
  Alignment/OfflineValidation/python/overlapValidationPlot.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#38723 Tracker Alignment: revamp E/P validation tools
  Alignment/OfflineValidation/interface/EopElecVariables.h
  Alignment/OfflineValidation/macros/momentumElectronBiasValidation.C
  Alignment/OfflineValidation/plugins/BuildFile.xml
  Alignment/OfflineValidation/plugins/EopElecTreeWriter.cc
  Alignment/OfflineValidation/plugins/EopTreeWriter.cc
  Alignment/OfflineValidation/python/eopElecTreeWriter_cfi.py
  Alignment/OfflineValidation/src/classes.h
  Alignment/OfflineValidation/src/classes_def.xml
  Alignment/OfflineValidation/test/BuildFile.xml
  Alignment/OfflineValidation/test/eopElecTreeWriter_cfg.py
  Alignment/OfflineValidation/test/eopTreeWriter_cfg.py
  Alignment/OfflineValidation/test/inspectData_cfg.py
  Alignment/OfflineValidation/test/testEoP.sh
  Alignment/OfflineValidation/test/testPVValidation.sh
  Alignment/OfflineValidation/test/testSubmitters.sh
  Alignment/OfflineValidation/test/test_all-in-one.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#38979 fix the delay of the CPPF DAQ data for backport to 12_4_X
  EventFilter/RPCRawToDigi/plugins/RPCAMCUnpacker.cc
  EventFilter/RPCRawToDigi/plugins/RPCCPPFUnpacker.cc
  EventFilter/RPCRawToDigi/plugins/RPCCPPFUnpacker.h
  EventFilter/RPCRawToDigi/python/RPCCPPFRawToDigi_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved

#39027 [12.4.X] Adjustments to `SiPixelCalSingleMuon` producers
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonLoose_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonTight_cff.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#38945 Phase2-sim125 Try to address good cell definition for V17 version of HGCal Geometry
  Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
  SimG4CMS/Calo/data/missingWafers.txt
  SimG4CMS/Calo/interface/CaloSimUtils.h
  SimG4CMS/Calo/interface/HGCalNumberingScheme.h
  SimG4CMS/Calo/interface/HGCalSD.h
  SimG4CMS/Calo/plugins/HGCalHitPartial.cc
  SimG4CMS/Calo/src/CaloSimUtils.cc
  SimG4CMS/Calo/src/HGCScintSD.cc
  SimG4CMS/Calo/src/HGCalNumberingScheme.cc
  SimG4CMS/Calo/src/HGCalSD.cc
  SimG4CMS/Calo/test/python/runHGC7_cfg.py
  SimG4Core/Application/python/g4SimHits_cfi.py
  Validation/HGCalValidation/plugins/SimG4HGCalValidation.cc
Labels: dqm-approved, geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39037 Update MPI tools and tests [12.4.x]
  HeterogeneousCore/CUDACore/test/BuildFile.xml
  HeterogeneousCore/CUDACore/test/mpiCudaGeneric.cu
  HeterogeneousCore/MPICore/scripts/cmsenv_mpirun
Labels: fully-signed, tests-approved, orp-approved, backport-ok, heterogeneous-approved

#39042 [12.4.X] Fix Tracker Alignment overlap validation
  Alignment/OfflineValidation/python/overlapValidationPlot.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#39033 [12_4_X] Extend CMS protections in Geant4 exception handling
  SimG4Core/Application/src/ExceptionHandler.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved

#39030 [12.4.X] implement event consumes in `MuScleFit`
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFit.cc
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFitMuonSelector.cc
  MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFitMuonSelector.h
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, trk

#39021 [12_4_X] Added new bit for mu+tau+jet filter
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#38978 [12_4_X] Add run3 PPS TDC and SAMPIC relvals
  Configuration/PyReleaseValidation/python/relval_production.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, ctpps

#39046 Add compressed size to edmFileUtil output
  IOPool/Common/bin/CollUtil.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38785 L1T Left Shift Error
  L1Trigger/DTTrackFinder/src/L1MuDTAssignmentUnit.cc
  L1Trigger/DTTrackFinder/src/L1MuDTEUX.cc
  L1Trigger/DTTrackFinder/src/L1MuDTEUX.h
  L1Trigger/L1TCommon/interface/BitShift.h
  L1Trigger/L1TMuonBarrel/src/L1MuBMAssignmentUnit.cc
  L1Trigger/L1TMuonBarrel/src/L1MuBMEUX.cc
  L1Trigger/L1TTwinMux/src/RPCtoDTTranslator.cc
  L1Trigger/TrackFindingTracklet/interface/imath.h
  L1Trigger/TrackFindingTracklet/src/TrackletCalculatorBase.cc
  L1Trigger/TrackFindingTracklet/src/TrackletLUT.cc
  L1Trigger/TrackFindingTracklet/src/imath_calculate.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39034 Update of HLT-specific `12_4_X` GTs for Run-3 MC
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved

#36335 Adding JPTjets to MiniAOD
  DataFormats/JetReco/interface/JPTJet.h
  DataFormats/JetReco/src/JPTJet.cc
  DataFormats/JetReco/src/classes_def_1.xml
  DataFormats/PatCandidates/interface/Jet.h
  JetMETCorrections/Algorithms/src/L1JPTOffsetCorrector.cc
  JetMETCorrections/Algorithms/src/L1JPTOffsetCorrectorImpl.cc
  PhysicsTools/PatAlgos/plugins/JPTJetSlimmer.cc
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/slimmedJPTJets_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  RecoJets/JetPlusTracks/plugins/JetPlusTrackAddonSeedProducer.cc
  RecoJets/JetPlusTracks/plugins/JetPlusTrackProducer.cc
  RecoJets/JetPlusTracks/plugins/JetPlusTrackProducerAA.cc
  RecoJets/JetProducers/src/PileupJPTJetIdAlgo.cc
Labels: analysis-pending, reconstruction-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved, xpog-approved, allow-clacaputo

#38738 update unit tests for G4e refitter package
  TrackPropagation/Geant4e/test/BuildFile.xml
  TrackPropagation/Geant4e/test/Geant4ePropagatorAnalyzer.cc
  TrackPropagation/Geant4e/test/Geant4e_example_cfg.py
  TrackPropagation/Geant4e/test/SimpleGeant4ePropagatorTest.cc
  TrackPropagation/Geant4e/test/simpleTestPropagator_cfg.py
  TrackPropagation/Geant4e/test/testPropagatorAnalyzer_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39047 Update the `convertToRaw` script
  HLTrigger/Tools/scripts/convertToRaw
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39052 Added optional Geant4 tracking cut for charged particles
  SimG4Core/Application/interface/ExceptionHandler.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/ExceptionHandler.cc
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysicsEMZ.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysicsLPM.h
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMZ.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsEMZ.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsLPM.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsXS.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39016 Implement the alpaka-based accelerator framework for CMSSW
  DataFormats/Portable/interface/PortableCollection.h
  DataFormats/Portable/interface/PortableDeviceCollection.h
  DataFormats/Portable/interface/PortableHostCollection.h
  DataFormats/Portable/interface/Product.h
  DataFormats/Portable/interface/ProductBase.h
  DataFormats/PortableTestObjects/src/alpaka/classes_cuda.h
  DataFormats/PortableTestObjects/src/alpaka/classes_cuda_def.xml
  DataFormats/PortableTestObjects/src/alpaka/classes_serial.h
  DataFormats/PortableTestObjects/src/alpaka/classes_serial_def.xml
  FWCore/Utilities/src/FriendlyName.cc
  FWCore/Utilities/test/friendlyname_t.cppunit.cpp
  HeterogeneousCore/AlpakaCore/interface/ContextState.h
  HeterogeneousCore/AlpakaCore/interface/EventCache.h
  HeterogeneousCore/AlpakaCore/interface/QueueCache.h
  HeterogeneousCore/AlpakaCore/interface/ScopedContext.h
  HeterogeneousCore/AlpakaCore/interface/chooseDevice.h
  HeterogeneousCore/AlpakaInterface/BuildFile.xml
  HeterogeneousCore/AlpakaInterface/interface/AllocatorConfig.h
  HeterogeneousCore/AlpakaInterface/interface/AllocatorPolicy.h
  HeterogeneousCore/AlpakaInterface/interface/AlpakaServiceFwd.h
  HeterogeneousCore/AlpakaInterface/interface/CachedBufAlloc.h
  HeterogeneousCore/AlpakaInterface/interface/CachingAllocator.h
  HeterogeneousCore/AlpakaInterface/interface/HostOnlyTask.h
  HeterogeneousCore/AlpakaInterface/interface/ScopedContextFwd.h
  HeterogeneousCore/AlpakaInterface/interface/devices.h
  HeterogeneousCore/AlpakaInterface/interface/getDeviceCachingAllocator.h
  HeterogeneousCore/AlpakaInterface/interface/getHostCachingAllocator.h
  HeterogeneousCore/AlpakaInterface/interface/host.h
  HeterogeneousCore/AlpakaInterface/interface/memory.h
  HeterogeneousCore/AlpakaInterface/interface/traits.h
  HeterogeneousCore/AlpakaServices/interface/alpaka/AlpakaService.h
  HeterogeneousCore/AlpakaServices/src/alpaka/AlpakaService.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlgo.dev.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaProducer.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaTranscriber.cc
  HeterogeneousCore/AlpakaTest/test/reader.py
  HeterogeneousCore/AlpakaTest/test/writer.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#39043 fix_photon_trigger_filters_nanoAOD
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#39053 [12_4_X] Reduced length of Geant4 warning printout in production runs
  SimG4Core/Application/interface/ExceptionHandler.h
  SimG4Core/Application/src/ExceptionHandler.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved

#39048 Update the `convertToRaw` script [12.4.x]
  HLTrigger/Tools/scripts/convertToRaw
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39065 fix compilation errors in `MomentumScaleCalibration` macros
  MuonAnalysis/MomentumScaleCalibration/test/Macros/RooFit/FitSlices.cc
  MuonAnalysis/MomentumScaleCalibration/test/Macros/RooFit/FitXslices.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#38996 miscellaneous updates to SiPixel Lorentz Angle Calibration harvesting
  CalibTracker/SiPixelLorentzAngle/interface/SiPixelLorentzAngleCalibrationStruct.h
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLHarvester.cc
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLWorker.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, new-feature, code-checks-approved, trk

#39066 Avoid creation of invalid RooFit proxies in RooFitFunction
  PhysicsTools/Utilities/interface/RooFitFunction.h
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39067 Add missing include for Alpaka CachingAllocator
  HeterogeneousCore/AlpakaInterface/interface/CachingAllocator.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#39060 A safe guard on GEM DQM harvester
  DQM/GEM/plugins/GEMDQMHarvester.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#39051 exclude HLT-PNET DQM from HIon workflows
  DQMOffline/Trigger/python/DQMOffline_HLT_Client_cff.py
  DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py
  DQMOffline/Trigger/python/ParticleNetAK4BTagClient_cfi.py
  DQMOffline/Trigger/python/ParticleNetAK4BTagMonitoring_cfi.py
  DQMOffline/Trigger/python/ParticleNetAK8HbbTagClient_cfi.py
  DQMOffline/Trigger/python/ParticleNetAK8HbbTagMonitoring_cfi.py
  DQMOffline/Trigger/python/ParticleNetJetTagMonitoring_cff.py
  DQMOffline/Trigger/python/ParticleNetJetTag_Client_cff.py
  DQMOffline/Trigger/python/ParticleNetJetTag_Client_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39054 fixup reading histograms in TrackTimingTable in trackingPlots
  Validation/RecoTrack/python/plotting/trackingPlots.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39028 Raise pT threshold for low pT GSF electron seeds in PbPb era
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSeeds_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39070 introduce G4e refitter in the tracker alignment machinery
  Alignment/CommonAlignment/python/tools/trackselectionRefitting.py
  Alignment/OfflineValidation/test/BuildFile.xml
  Alignment/OfflineValidation/test/testEoP.sh
  Alignment/OfflineValidation/test/testG4Refitter_cfg.py
  Alignment/OfflineValidation/test/testMiscellanea.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, new-feature, code-checks-approved, trk

#38967 switch pixelLess iteration to use CKF instead of mkFit
  Configuration/Eras/python/Era_Run3_ckfPixelLessStep_cff.py
  Configuration/Eras/python/ModifierChain_trackingMkFitProd_cff.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/Eras.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#38829 Add DY option to Embedding HepMC filter
  GeneratorInterface/Core/interface/EmbeddingHepMCFilter.h
  GeneratorInterface/Core/src/EmbeddingHepMCFilter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39073 Add more profile dump points to IgProfService
  IgTools/IgProf/plugins/IgProfService.cc
  IgTools/IgProf/plugins/IgProfService.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39056 add states to `GsfMultiStateUpdator` MultiState only if the localError matrix is valid
  TrackingTools/GsfTracking/src/GsfMultiStateUpdator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, tracking, egamma

#39061 A safe guard on GEM DQM harvester, a backport to 12_4_X
  DQM/GEM/plugins/GEMDQMHarvester.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#39068 [12.4.X] fix compilation errors in MomentumScaleCalibration macros
  MuonAnalysis/MomentumScaleCalibration/test/Macros/RooFit/FitSlices.cc
  MuonAnalysis/MomentumScaleCalibration/test/Macros/RooFit/FitXslices.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, trk

#39083 `SiPixelLorentzAnglePCLHarvester`: protect the computation of the LA error in case of missing covariance matrix
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLHarvester.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, trk

#39072 Utilities/StaticAnalyzers: Only skip edm::one modules for use of TFileService functions in statics2modules reports.
  Utilities/StaticAnalyzers/scripts/statics.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39074 [12.4.X] add states to `GsfMultiStateUpdator` MultiState only if the localError matrix is valid
  TrackingTools/GsfTracking/src/GsfMultiStateUpdator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, tracking, egamma

#39063 Run3-alca226 Update the macros to e used for Run3 analysis of hadron calorimeter calibration data with isolated muons
  Calibration/HcalCalibAlgos/macros/AnalyzeLepTree.C
  Calibration/HcalCalibAlgos/macros/HBHEMuonHighEta.C
  Calibration/HcalCalibAlgos/macros/HBHEMuonOfflineAnalyzer.C
  Calibration/HcalCalibAlgos/macros/HBHEMuonOfflineSimAnalyzer.C
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, hcal

#38904 Rename inline c++ files to .icc
  DataFormats/L1Trigger/interface/BXVector.h
  DataFormats/L1Trigger/interface/BXVector.icc
  EventFilter/Utilities/interface/json_internalarray.inl
  EventFilter/Utilities/interface/json_internalmap.inl
  EventFilter/Utilities/src/json_internalarray.icc
  EventFilter/Utilities/src/json_internalmap.icc
  EventFilter/Utilities/src/json_value.cpp
  EventFilter/Utilities/src/json_valueiterator.icc
  FWCore/Skeletons/mkTemplates/c++11/Driver.dir
  FWCore/Skeletons/mkTemplates/c++11/c++11Tmpl.h
  FWCore/Skeletons/mkTemplates/c++11/c++11Tmpl.icc
Labels: core-approved, daq-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38954 Replace Geometry_cff with GeometryDB_cff in RecoHI
  RecoHI/HiEgammaAlgos/test/testSpike_cfg.py
  RecoHI/HiJetAlgos/test/testRegionalJetTracking_cfg.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38786 Replace Geometry_cff with GeometryDB_cff in RecoEcal
  RecoEcal/EgammaClusterProducers/test/testRecoEcal_cfg.py
  RecoEcal/EgammaClusterProducers/test/testRecoEcal_cfgV2.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38806 Initialize BranchDescription from Dictionary only if the branch is present
  DataFormats/Common/src/setIsMergeable.cc
  DataFormats/Provenance/interface/BranchDescription.h
  DataFormats/TestObjects/interface/ToyProducts.h
  DataFormats/TestObjects/test/BuildFile_extra.xml
  DataFormats/TestObjects/test/classes.h
  DataFormats/TestObjects/test/classes_def_parent1.xml
  DataFormats/TestObjects/test/classes_def_parent2.xml
  FWCore/Framework/interface/stream/ThinningProducer.h
  FWCore/Framework/test/stubs/ToyIntProducers.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/RootFile.cc
  IOPool/Input/test/BuildFile.xml
  IOPool/Input/test/PoolNoParentDictionaryTestStep1_cfg.py
  IOPool/Input/test/PoolNoParentDictionaryTestStep2_cfg.py
  IOPool/Input/test/testNoParentDictionary.sh
Labels: core-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#39055 mkFit updates aiming to improve pixelLess iteration and related
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/MkFitCMS/interface/MkStdSeqs.h
  RecoTracker/MkFitCMS/src/MkStdSeqs.cc
  RecoTracker/MkFitCMS/src/runFunctions.cc
  RecoTracker/MkFitCMS/standalone/buildtestMPlex.cc
  RecoTracker/MkFitCore/interface/TrackStructures.h
  RecoTracker/MkFitCore/src/CandCloner.cc
  RecoTracker/MkFitCore/src/CandCloner.h
  RecoTracker/MkFitCore/src/KalmanUtilsMPlex.cc
  RecoTracker/MkFitCore/src/KalmanUtilsMPlex.h
  RecoTracker/MkFitCore/src/MkBuilder.cc
  RecoTracker/MkFitCore/src/MkFinder.cc
  RecoTracker/MkFitCore/src/MkFinder.h
  RecoTracker/MkFitCore/src/PropagationMPlex.icc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#39091 fix run-by-run TkAlignment PV Validation submission script in case of extra conditions
  Alignment/OfflineValidation/scripts/submitPVValidationJobs.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#39090 [Fix] Make `IncludeDY` optional
  GeneratorInterface/Core/src/EmbeddingHepMCFilter.cc
  TauAnalysis/MCEmbeddingTools/python/EmbeddingPythia8Hadronizer_cfi.py
Labels: simulation-pending, generators-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39095 [12.4.X] fix run-by-run TkAlignment PV Validation submission script in case of extra conditions
  Alignment/OfflineValidation/scripts/submitPVValidationJobs.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#39093 DQM for DiPhoton Paths in EXO/HIG PAGs
  DQMOffline/Trigger/python/HiggsMonitoring_Client_cff.py
  DQMOffline/Trigger/python/PhotonMonitor_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39076 Fix PPSDiamondDQM histogram of rechits in the last lumisection
  DQM/CTPPS/plugins/CTPPSDiamondDQMSource.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, ctpps

#39000 [JMENanoAOD] Updates for Run-3
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/PatAlgos/python/tools/jetCollectionTools.py
Labels: reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved

#38938 [124X backport] Add DY option to Embedding HepMC filter
  GeneratorInterface/Core/interface/EmbeddingHepMCFilter.h
  GeneratorInterface/Core/src/EmbeddingHepMCFilter.cc
  TauAnalysis/MCEmbeddingTools/python/EmbeddingPythia8Hadronizer_cfi.py
Labels: generators-approved, simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#38968 switch pixelLess iteration to use CKF instead of mkFit
  Configuration/Eras/python/Era_Run3_ckfPixelLessStep_cff.py
  Configuration/Eras/python/ModifierChain_trackingMkFitProd_cff.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/Eras.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#38907 Migration of input collection parameters to untracked for CTPPS and DTMonitorModule
  DQM/CTPPS/plugins/CTPPSCommonDQMSource.cc
  DQM/CTPPS/plugins/CTPPSDiamondDQMSource.cc
  DQM/CTPPS/plugins/CTPPSPixelDQMSource.cc
  DQM/CTPPS/plugins/DiamondSampicCalibrationDQMSource.cc
  DQM/CTPPS/plugins/DiamondSampicDQMSource.cc
  DQM/CTPPS/plugins/ElasticPlotDQMSource.cc
  DQM/CTPPS/plugins/TotemDAQTriggerDQMSource.cc
  DQM/CTPPS/plugins/TotemRPDQMSource.cc
  DQM/CTPPS/plugins/TotemTimingDQMSource.cc
  DQM/CTPPS/python/ctppsCommonDQMSource_cfi.py
  DQM/CTPPS/python/ctppsDiamondDQMSource_cfi.py
  DQM/CTPPS/python/ctppsPixelDQMSource_cfi.py
  DQM/CTPPS/python/diamondSampicDQMSource_cfi.py
  DQM/CTPPS/python/elasticPlotDQMSource_cfi.py
  DQM/CTPPS/python/totemDAQTriggerDQMSource_cfi.py
  DQM/CTPPS/python/totemRPDQMSource_cfi.py
  DQM/CTPPS/python/totemTimingDQMSource_cfi.py
  DQM/DTMonitorModule/python/dtChamberEfficiencyHI_cfi.py
  DQM/DTMonitorModule/python/dtChamberEfficiencyTask_cfi.py
  DQM/DTMonitorModule/python/dtChamberEfficiency_Cosmics_cfi.py
  DQM/DTMonitorModule/python/dtChamberEfficiency_cfi.py
  DQM/DTMonitorModule/python/dtDataIntegrityTask_cfi.py
  DQM/DTMonitorModule/python/dtDigiTask_TP_cfi.py
  DQM/DTMonitorModule/python/dtDigiTask_cfi.py
  DQM/DTMonitorModule/python/dtEfficiencyTask_cfi.py
  DQM/DTMonitorModule/python/dtNoiseTask_cfi.py
  DQM/DTMonitorModule/python/dtOccupancyEfficiency_cfi.py
  DQM/DTMonitorModule/python/dtResolutionTask_cfi.py
  DQM/DTMonitorModule/python/dtResolutionTask_hlt_cfi.py
  DQM/DTMonitorModule/python/dtRunConditionVar_cfi.py
  DQM/DTMonitorModule/python/dtSegmentTask_cfi.py
  DQM/DTMonitorModule/python/dtSegmentTask_hlt_cfi.py
  DQM/DTMonitorModule/python/dtTriggerSynchTask_cfi.py
  DQM/DTMonitorModule/src/DTChamberEfficiency.cc
  DQM/DTMonitorModule/src/DTChamberEfficiencyTask.cc
  DQM/DTMonitorModule/src/DTDataIntegrityROSOffline.cc
  DQM/DTMonitorModule/src/DTDataIntegrityTask.cc
  DQM/DTMonitorModule/src/DTDigiTask.cc
  DQM/DTMonitorModule/src/DTEfficiencyTask.cc
  DQM/DTMonitorModule/src/DTLocalTriggerSynchTask.cc
  DQM/DTMonitorModule/src/DTNoiseTask.cc
  DQM/DTMonitorModule/src/DTOccupancyEfficiency.cc
  DQM/DTMonitorModule/src/DTResolutionAnalysisTask.cc
  DQM/DTMonitorModule/src/DTRunConditionVar.cc
  DQM/DTMonitorModule/src/DTSegmentAnalysisTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#38948 change Selector from bit pattern to bit number for the pattern [12.5]
  DQM/GEM/python/gemEfficiencyAnalyzer_cff.py
  DataFormats/MuonReco/interface/Muon.h
  DataFormats/MuonReco/src/MuonSelectors.cc
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, xpog-approved

#39099 Fix nanoAOD trigger bits for e+tau overlap filter
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#38943 change Selector from bit pattern to bit number for the pattern
  DQM/GEM/python/gemEfficiencyAnalyzer_cff.py
  DataFormats/MuonReco/interface/Muon.h
  DataFormats/MuonReco/src/MuonSelectors.cc
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#39103 Backport of #39043 and #39099: fixing e+tau cross trigger and photon trigger filters in nanoAOD
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#38666 Run3 GEMGeometryBuilder Run3 modifier
  Geometry/GEMGeometryBuilder/python/gemGeometryDB_cfi.py
  Geometry/GEMGeometryBuilder/python/gemGeometry_cff.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, new-feature, urgent, upgrade-approved, requires-external, code-checks-approved, gem

#39089 Run3-alca226A Modify HOCalibAnalyzer as suggested by ALCA reviewer
  Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc
  Calibration/HcalCalibAlgos/test/python/test_hosignal_collision_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, hcal

#39109 Fix resolution/offset order in the PPS calibration payload
  CalibPPS/TimingCalibration/plugins/PPSTimingCalibrationPCLHarvester.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, ctpps

#39059 Add run3 PCL pps alignment relval
  Configuration/PyReleaseValidation/python/relval_production.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, new-feature, upgrade-approved, code-checks-approved, ctpps

#39122 Fix for `SiPixelLorentzAnglePCLHarvester` after #38996
  CalibTracker/SiPixelLorentzAngle/interface/SiPixelLorentzAngleCalibrationStruct.h
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLHarvester.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, trk
