Repository cms-sw/cmssw, pull requests merged in 2022-10, with the labels that each got.

#39535 fix failing unit tests after #38702 merge (Drop of geometry D49)
  Geometry/TrackerGeometryBuilder/test/python/testPixelTopologyMapTest_cfg.py
  Geometry/TrackerGeometryBuilder/test/runTest.sh
  SLHCUpgradeSimulations/Geometry/test/phase2_digi_reco_pixelntuple_cfg.py
  SLHCUpgradeSimulations/Geometry/test/writeFile_phase2_cfg.py
  SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseII.py
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseII.py
  SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino_ForPhaseII.py
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#39555 Use unique_ptr in edm::Factory::MakerMap
  FWCore/Framework/src/Factory.cc
  FWCore/Framework/src/Factory.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39484 [12_4_X] Release dependent modules only after the worker has finished for scheduled modules
  FWCore/Framework/interface/maker/Worker.h
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Framework/src/ProductResolvers.h
  FWCore/Framework/src/StreamSchedule.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#39529 [12_5_X] Use "best matching" EDAlias in module dependence checks when placing ConditionalTask modules in Path
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Integration/test/run_TestSwitchProducer.sh
  FWCore/Integration/test/testSwitchProducerConditionalTaskEDAliasWildcard_cfg.py
Labels: core-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#39495 PPS lhcInfo split: LHCInfoPerLS and LHCInfoPerFill records
  CondCore/RunInfoPlugins/src/plugin.cc
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondFormats.h
  CondFormats/DataRecord/interface/LHCInfoPerFillRcd.h
  CondFormats/DataRecord/interface/LHCInfoPerLSRcd.h
  CondFormats/DataRecord/src/LHCInfoPerFillRcd.cc
  CondFormats/DataRecord/src/LHCInfoPerLSRcd.cc
  CondFormats/RunInfo/BuildFile.xml
  CondFormats/RunInfo/interface/LHCInfoPerFill.h
  CondFormats/RunInfo/interface/LHCInfoPerLS.h
  CondFormats/RunInfo/interface/LHCInfoVectorizedFields.h
  CondFormats/RunInfo/src/LHCInfoPerFill.cc
  CondFormats/RunInfo/src/LHCInfoPerLS.cc
  CondFormats/RunInfo/src/LHCInfoVectorizedFields.cc
  CondFormats/RunInfo/src/T_EventSetup_LHCInfoPerFill.cc
  CondFormats/RunInfo/src/T_EventSetup_LHCInfoPerLS.cc
  CondFormats/RunInfo/src/headers.h
  CondFormats/RunInfo/test/testSerializationRunInfo.cpp
  CondTools/RunInfo/plugins/BuildFile.xml
  CondTools/RunInfo/plugins/LHCInfoPerFillAnalyzer.cc
  CondTools/RunInfo/plugins/LHCInfoPerFillWriter.cc
  CondTools/RunInfo/plugins/LHCInfoPerLSAnalyzer.cc
  CondTools/RunInfo/plugins/LHCInfoPerLSWriter.cc
  CondTools/RunInfo/test/BuildFile.xml
  CondTools/RunInfo/test/LHCInfoPerFillAnalyzer_cfg.py
  CondTools/RunInfo/test/LHCInfoPerFillWriter_cfg.py
  CondTools/RunInfo/test/LHCInfoPerLSAnalyzer_cfg.py
  CondTools/RunInfo/test/LHCInfoPerLSWriter_cfg.py
  CondTools/RunInfo/test/test_lhcInfo.sh
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, performance-improvements, ctpps

#39550 Update to sqrt(s) in the PV alignment validation plotting macros
  Alignment/OfflineValidation/macros/CMS_lumi.h
  Alignment/OfflineValidation/macros/FitPVResiduals.C
  Alignment/OfflineValidation/macros/FitPVResolution.C
  Alignment/OfflineValidation/test/BuildFile.xml
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39552 `MillePedeDQMModule`: add string MonitorElement to signal if the update was vetoed
  Alignment/MillePedeAlignmentAlgorithm/interface/MillePedeFileReader.h
  Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.cc
  Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39553 Change LG and HG Tk PCL output tags
  CondFormats/Common/data/SiPixelAliHGRcd_prod.json
  CondFormats/Common/data/SiPixelAliRcd_prod.json
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#39567 [12.4.X] Update to sqrt(s) in the PV alignment validation plotting macros
  Alignment/OfflineValidation/macros/CMS_lumi.h
  Alignment/OfflineValidation/macros/FitPVResiduals.C
  Alignment/OfflineValidation/macros/FitPVResolution.C
  Alignment/OfflineValidation/test/BuildFile.xml
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39566 [12.5.X] Update to sqrt(s) in the PV alignment validation plotting macros
  Alignment/OfflineValidation/macros/CMS_lumi.h
  Alignment/OfflineValidation/macros/FitPVResiduals.C
  Alignment/OfflineValidation/macros/FitPVResolution.C
  Alignment/OfflineValidation/test/BuildFile.xml
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39563 [12.4.X] `MillePedeDQMModule`: add string MonitorElement to signal if the update was vetoed
  Alignment/MillePedeAlignmentAlgorithm/interface/MillePedeFileReader.h
  Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.cc
  Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39562 [12.5.X] `MillePedeDQMModule`: add string MonitorElement to signal if the update was vetoed
  Alignment/MillePedeAlignmentAlgorithm/interface/MillePedeFileReader.h
  Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.cc
  Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39561 [12.4.X] add protection against missing input histograms in L1Tde* clients
  DQM/L1TMonitorClient/src/L1TdeCSCTPGClient.cc
  DQM/L1TMonitorClient/src/L1TdeCSCTPGShowerClient.cc
  DQM/L1TMonitorClient/src/L1TdeStage2ShowerRegionalClient.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#39499 [L1T] fixes to l1t module names
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/L1TTrackMatch/plugins/L1TrackSelectionProducer.cc
  L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39569 Move ESHandle headers where needed in CondTools/RunInfo/plugins
  CondTools/RunInfo/plugins/FillInfoESAnalyzer.cc
  CondTools/RunInfo/plugins/LHCInfoESAnalyzer.cc
  CondTools/RunInfo/plugins/LHCInfoPerFillAnalyzer.cc
  CondTools/RunInfo/plugins/LHCInfoPerFillWriter.cc
  CondTools/RunInfo/plugins/LHCInfoPerLSAnalyzer.cc
  CondTools/RunInfo/plugins/LHCInfoPerLSWriter.cc
  CondTools/RunInfo/plugins/RunInfoESAnalyzer.cc
  CondTools/RunInfo/plugins/RunSummaryESAnalyzer.cc
  CondTools/RunInfo/plugins/XangleBetaStarFilter.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#39565 [124X] Change LG and HG Tk PCL output tags
  CondFormats/Common/data/SiPixelAliHGRcd_prod.json
  CondFormats/Common/data/SiPixelAliRcd_prod.json
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, backport-ok

#39564 [125X] Change LG and HG Tk PCL output tags
  CondFormats/Common/data/SiPixelAliHGRcd_prod.json
  CondFormats/Common/data/SiPixelAliRcd_prod.json
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, backport-ok

#39416 [12_5_X] [L1T] Backport of: phase-2, update trackjet simulation
  L1Trigger/L1TTrackMatch/interface/L1Clustering.h
  L1Trigger/L1TTrackMatch/interface/L1TrackJetProducer.h
  L1Trigger/L1TTrackMatch/plugins/L1TrackJetProducer.cc
  L1Trigger/L1TTrackMatch/python/l1tTrackJets_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, backport-ok

#39541 Migrate DummyReadDQMStore from legacy to one type
  DQMServices/FwkIO/test/DummyReadDQMStore.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39581 Removed unnecessary header in GlobalTrackerMuonAlignment
  Alignment/CommonAlignmentProducer/plugins/GlobalTrackerMuonAlignment.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39479 Bug fix on L1TrackJetEmulator
  L1Trigger/L1TTrackMatch/plugins/L1TrackJetEmulationProducer.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39572 Change Phase-2 CPE unit test to use T21 geom
  CondTools/SiPixel/data/phase2_T21_mapping.csv
  CondTools/SiPixel/data/phase2_T21_mapping_den.csv
  CondTools/SiPixel/test/SiPixel2DTemplateDBObjectUploader_Phase2_cfg.py
  CondTools/SiPixel/test/SiPixelGenErrorDBObjectUploader_Phase2_cfg.py
  CondTools/SiPixel/test/SiPixelTemplateDBObjectUploader_Phase2_cfg.py
  CondTools/SiPixel/test/createTestDBObjects.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, requires-external, code-checks-approved

#39401 [L1T] Phase-2, include missing collections in outputs
  DataFormats/L1Trigger/interface/TkJetWord.h
  DataFormats/L1Trigger/src/TkJetWord.cc
  DataFormats/L1Trigger/src/classes_def.xml
  L1Trigger/Configuration/python/L1Trigger_EventContent_cff.py
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/L1CaloTrigger/plugins/Phase1L1TJetSumsProducer.cc
  L1Trigger/L1CaloTrigger/python/Phase1L1TJets_9x9_cff.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#39545 Use thread-friendly modules in Validation/RecoTau
  Validation/RecoTau/plugins/DQMFileLoader.cc
  Validation/RecoTau/plugins/DQMFileLoader.h
  Validation/RecoTau/plugins/DQMHistNormalizer.cc
  Validation/RecoTau/plugins/DQMHistPlotter.cc
  Validation/RecoTau/plugins/DQMHistPlotter.h
  Validation/RecoTau/plugins/DQMSimpleFileSaver.cc
  Validation/RecoTau/plugins/DQMSimpleFileSaver.h
  Validation/RecoTau/plugins/Selectors.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39546 Add helper functions for alpaka kernels
  HeterogeneousCore/AlpakaInterface/interface/vec.h
  HeterogeneousCore/AlpakaInterface/interface/workdivision.h
  HeterogeneousCore/AlpakaInterface/test/BuildFile.xml
  HeterogeneousCore/AlpakaInterface/test/alpaka/testVec.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlgo.dev.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#39538 Fix deprecation warnings in PhysicsTools/UtilAlgos
  PhysicsTools/UtilAlgos/interface/EDAnalyzerWrapper.h
  PhysicsTools/UtilAlgos/interface/NTupler.h
  PhysicsTools/UtilAlgos/interface/VariableNTupler.h
  PhysicsTools/UtilAlgos/plugins/ConfigurableAnalysis.cc
  PhysicsTools/UtilAlgos/plugins/ErrorSummaryFilter.cc
  PhysicsTools/UtilAlgos/plugins/NTuplingDevice.cc
  PhysicsTools/UtilAlgos/plugins/PlottingDevice.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39577 Reduce the ECAL and HCAL GPU memory usage
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalCalo/EcalRecProducers/plugins/DeclsForKernels.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/python/ecalRecHitGPU_cfi.py
  RecoLocalCalo/HcalRecProducers/src/DeclsForKernels.h
  RecoLocalCalo/HcalRecProducers/src/HBHERecHitProducerGPU.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#39534 SiStrip Conditions tools: add `SiStripBadChannelPatcher` and related configurations
  CondTools/SiStrip/plugins/SiStripBadChannelPatcher.cc
  CondTools/SiStrip/test/SiStripBadChannelPatcher_cfg.py
  CondTools/SiStrip/test/testBuildersReaders.sh
Labels: fully-signed, tests-rejected, db-approved, orp-approved, code-checks-approved

#39578 Use parabolic magnetic field in track final fit and modify min N(hits) condition in track duplicate merge
  RecoTracker/IterativeTracking/python/DetachedQuadStep_cff.py
  RecoTracker/IterativeTracking/python/DetachedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/HighPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/InitialStepPreSplitting_cff.py
  RecoTracker/IterativeTracking/python/InitialStep_cff.py
  RecoTracker/IterativeTracking/python/JetCoreRegionalStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtBarrelTripletStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtForwardTripletStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtQuadStep_cff.py
  RecoTracker/IterativeTracking/python/LowPtTripletStep_cff.py
  RecoTracker/IterativeTracking/python/MixedTripletStep_cff.py
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoTracker/IterativeTracking/python/TobTecStep_cff.py
  RecoTracker/TrackProducer/python/TrackProducerIterativeDefault_cfi.py
  TrackingTools/TrackFitters/plugins/KFFittingSmootherESProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-pending, urgent, code-checks-approved

#39604 Moved RawDataSelector to a stream module
  EventFilter/RawDataCollector/src/RawDataSelector.cc
Labels: daq-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39576 [12_5_X] [L1T] Backport of : Bug fix on L1TrackJetEmulator
  L1Trigger/L1TTrackMatch/plugins/L1TrackJetEmulationProducer.cc
Labels: l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, backport-ok

#39547 Add helper functions for alpaka kernels [12.5.x]
  HeterogeneousCore/AlpakaInterface/interface/vec.h
  HeterogeneousCore/AlpakaInterface/interface/workdivision.h
  HeterogeneousCore/AlpakaInterface/test/BuildFile.xml
  HeterogeneousCore/AlpakaInterface/test/alpaka/testVec.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlgo.dev.cc
Labels: fully-signed, tests-approved, orp-approved, backport-ok, heterogeneous-approved

#39611 [Fix] Decrease cut on min number of hits only in RKFittingSmoother
  TrackingTools/TrackFitters/plugins/KFFittingSmootherESProducer.cc
  TrackingTools/TrackFitters/python/RungeKuttaFitters_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, requires-external, code-checks-approved, tracking

#39610 Moved ConeIsolation to global module type
  HLTrigger/btau/plugins/ConeIsolation.cc
  HLTrigger/btau/plugins/ConeIsolation.h
  HLTrigger/btau/plugins/ConeIsolationAlgorithm.cc
  HLTrigger/btau/plugins/ConeIsolationAlgorithm.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39418 [L1T] Update track z0 in the fastHistoEmulation algorithm of VertexFinder
  L1Trigger/DemonstratorTools/test/gtt/createFirmwareInputFiles_cfg.py
  L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker_cfg.py
  L1Trigger/VertexFinder/interface/VertexFinder.h
  L1Trigger/VertexFinder/python/l1tVertexProducer_cfi.py
  L1Trigger/VertexFinder/src/VertexFinder.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39590 Migrate Validation/Geometry to D92
  Validation/Geometry/test/genHGCalPlots.sh
  Validation/Geometry/test/runP_HGCal_cfg.py
Labels: dqm-pending, geometry-approved, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39411 L1 DT AM - heap-buffer-overflow fix + slight logic improvement in confirmed TPs
  L1Trigger/DTTriggerPhase2/src/MPQualityEnhancerFilter.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39592 Phase 2 tracker: adding tracker T31
  Configuration/Geometry/README.md
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_OT800_IT615_2022_10/pixbar.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39613 Use thread-friendly modules in IORawData/DTCommissioning
  IORawData/DTCommissioning/plugins/DTDDUFileReader.h
  IORawData/DTCommissioning/plugins/DTNewROS8FileReader.h
  IORawData/DTCommissioning/plugins/DTROS25FileReader.h
  IORawData/DTCommissioning/plugins/DTROS8FileReader.h
  IORawData/DTCommissioning/plugins/DTSpyReader.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39559 [12_6_X] RPCOccupancyTest crash protection for 0 LS
  DQM/RPCMonitorClient/src/RPCOccupancyTest.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39614 Made JetMETCorrections/JetVertexAssociation modules thread-friendly
  JetMETCorrections/JetVertexAssociation/interface/JetVertexAssociation.h
  JetMETCorrections/JetVertexAssociation/interface/JetVertexMain.h
  JetMETCorrections/JetVertexAssociation/src/JetVertexAssociation.cc
  JetMETCorrections/JetVertexAssociation/src/JetVertexMain.cc
  JetMETCorrections/JetVertexAssociation/test/AnalysisJV.cc
  JetMETCorrections/JetVertexAssociation/test/AnalysisJV.h
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39573 Bugfix to the destructor of two TkDQM scripts
  DQM/SiStripMonitorClient/scripts/PhaseITreeProducer.py
  DQM/SiStripMonitorClient/scripts/TH2PolyOfflineMaps.py
  DQM/SiStripMonitorClient/test/BuildFile.xml
  DQM/SiStripMonitorClient/test/test_TreeAndTkMapProducer.sh
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, trk

#39579 Reduce the ECAL and HCAL GPU memory usage [12.5.x]
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalCalo/EcalRecProducers/plugins/DeclsForKernels.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/python/ecalRecHitGPU_cfi.py
  RecoLocalCalo/HcalRecProducers/src/DeclsForKernels.h
  RecoLocalCalo/HcalRecProducers/src/HBHERecHitProducerGPU.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39580 Reduce the ECAL and HCAL GPU memory usage [12.4.x]
  RecoLocalCalo/EcalRecProducers/plugins/DeclsForKernels.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/python/ecalRecHitGPU_cfi.py
  RecoLocalCalo/HcalRecProducers/src/DeclsForKernels.h
  RecoLocalCalo/HcalRecProducers/src/HBHERecHitProducerGPU.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved

#39560 [12_5_X] RPCOccupancyTest crash protection for 0 LS
  DQM/RPCMonitorClient/src/RPCOccupancyTest.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39634 Removed commented out deprecated header in L1TMuonCPPFDigiProducer
  L1Trigger/L1TMuonCPPF/plugins/L1TMuonCPPFDigiProducer.h
Labels: l1-pending, pending-signatures, tests-pending, orp-approved, code-checks-approved

#39638 Removed unnecessary deprecated header from VertexProducer.cc
  L1Trigger/VertexFinder/plugins/VertexProducer.cc
Labels: l1-pending, pending-signatures, tests-pending, orp-approved, code-checks-approved

#39612 Removed unused headers from IOMC/ParticleGuns
  IOMC/ParticleGuns/src/BaseFlatGunProducer.cc
  IOMC/ParticleGuns/src/BaseRandomtXiGunProducer.cc
Labels: generators-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39607 Removed unused headers from GeneratorInterface/HydjetInterface
  GeneratorInterface/HydjetInterface/interface/HydjetHadronizer.h
  GeneratorInterface/HydjetInterface/test/HydjetAnalyzer.cc
Labels: generators-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39608 Removed unused headers from GeneratorInterface/PyquenInterface
  GeneratorInterface/PyquenInterface/interface/PyquenHadronizer.h
  GeneratorInterface/PyquenInterface/test/PyquenAnalyzer.h
Labels: generators-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39605 Removed unused headers from GeneratorInterface/Hydjet2Interface
  GeneratorInterface/Hydjet2Interface/interface/Hydjet2Hadronizer.h
  GeneratorInterface/Hydjet2Interface/test/Hydjet2Analyzer.cc
Labels: generators-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39582 Removed unnecessary includes in CommonTools/ParticleFlow
  CommonTools/ParticleFlow/interface/PFMETAlgo.h
  CommonTools/ParticleFlow/interface/PFPileUpAlgo.h
Labels: reconstruction-pending, pending-signatures, tests-rejected, orp-approved, code-checks-approved

#39583 Removed unused deprecated headers from CommonTools/RecoAlgos
  CommonTools/RecoAlgos/interface/PrimaryVertexAssignment.h
  CommonTools/RecoAlgos/interface/PrimaryVertexSorting.h
Labels: reconstruction-pending, pending-signatures, tests-rejected, orp-approved, code-checks-approved

#39617 Fix overflow in ECAL GPU unpacking
  EventFilter/EcalRawToDigi/plugins/UnpackGPU.cu
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39574 [125X] Bugfix to the destructor of two TkDQM scripts
  DQM/SiStripMonitorClient/scripts/PhaseITreeProducer.py
  DQM/SiStripMonitorClient/scripts/TH2PolyOfflineMaps.py
  DQM/SiStripMonitorClient/test/BuildFile.xml
  DQM/SiStripMonitorClient/test/test_TreeAndTkMapProducer.sh
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#39575 [124X] Bugfix to the destructor of two TkDQM scripts
  DQM/SiStripMonitorClient/scripts/PhaseITreeProducer.py
  DQM/SiStripMonitorClient/scripts/TH2PolyOfflineMaps.py
  DQM/SiStripMonitorClient/test/BuildFile.xml
  DQM/SiStripMonitorClient/test/test_TreeAndTkMapProducer.sh
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, trk

#39619 Fix overflow in ECAL GPU unpacking [12.4.x]
  EventFilter/EcalRawToDigi/plugins/UnpackGPU.cu
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved

#39618 Fix overflow in ECAL GPU unpacking [12.5.x]
  EventFilter/EcalRawToDigi/plugins/UnpackGPU.cu
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved

#39594 [12.4.X] zeroing error of Pixel barycenter ME and other optimizations
  DQM/SiPixelPhase1Summary/interface/SiPixelBarycenter.h
  DQM/SiPixelPhase1Summary/src/SiPixelBarycenter.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39593 [12.5.X] zeroing error of Pixel barycenter ME and other optimizations
  DQM/SiPixelPhase1Summary/interface/SiPixelBarycenter.h
  DQM/SiPixelPhase1Summary/src/SiPixelBarycenter.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39412 [12_5_X] L1 DT AM - heap-buffer-overflow fix + slight logic improvement in confirmed TPs
  L1Trigger/DTTriggerPhase2/src/MPQualityEnhancerFilter.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc
Labels: l1-approved, fully-signed, tests-rejected, orp-approved, upgrade-approved, backport-ok

#39658 Moved BasicToPFJet to global::EDProducer
  RecoJets/JetProducers/plugins/BasicToPFJet.cc
  RecoJets/JetProducers/plugins/BasicToPFJet.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-pending, code-checks-approved

#39657 Convert RecoJets/JetAssociationProducers to thread friendly types
  RecoJets/JetAssociationProducers/src/JetSignalVertexCompatibility.cc
  RecoJets/JetAssociationProducers/src/JetSignalVertexCompatibility.h
  RecoJets/JetAssociationProducers/test/PileupJetAnalyzer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-pending, code-checks-approved

#39640 Made GenericSelectorByValueMap a global::EDProducer
  RecoBTag/SoftLepton/interface/GenericSelectorByValueMap.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-pending, code-checks-approved

#39639 Made EventShapeVarsProducer thread-friendly
  PhysicsTools/CandAlgos/plugins/EventShapeVarsProducer.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-pending, code-checks-approved

#39616 Migrate legacy type modules to one type
  DQM/EcalPreshowerMonitorModule/interface/ESDaqInfoTask.h
  DQM/EcalPreshowerMonitorModule/interface/ESDataCertificationTask.h
  DQM/EcalPreshowerMonitorModule/interface/ESDcsInfoTask.h
  DQM/EcalPreshowerMonitorModule/src/ESDaqInfoTask.cc
  DQM/EcalPreshowerMonitorModule/src/ESDataCertificationTask.cc
  DQM/EcalPreshowerMonitorModule/src/ESDcsInfoTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-pending, code-checks-approved

#39586 Moved DQM/DataScouting modules to thread friendly types
  DQM/DataScouting/interface/AlphaTVarProducer.h
  DQM/DataScouting/interface/DiJetVarProducer.h
  DQM/DataScouting/interface/RazorVarProducer.h
  DQM/DataScouting/src/AlphaTVarProducer.cc
  DQM/DataScouting/src/DiJetVarProducer.cc
  DQM/DataScouting/src/RazorVarProducer.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-pending, code-checks-approved

#39585 Moved test modules in DataFormat/Math to thread friendly types
  DataFormats/Math/test/ReadMath.h
  DataFormats/Math/test/WriteMath.cc
  DataFormats/Math/test/WriteMath.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-pending, code-checks-approved

#39675 Removed unused deprecated header from TauRegionalPixelSeedGenerator.h
  RecoTauTag/HLTProducers/src/TauRegionalPixelSeedGenerator.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39517 Phase2-hgx325I Remove reference to 6 inch HGCal silicon wafers in 3 codes in Validation/HGCalValidation/plugins
  Validation/HGCalValidation/plugins/HGCalDigiValidation.cc
  Validation/HGCalValidation/plugins/HGCalHitValidation.cc
  Validation/HGCalValidation/plugins/HGCalRecHitValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39551 Phase2-hgx325J Remove reference to 6-inch wafers in 5 classes of Validation/HGCalValidation
  Validation/HGCalValidation/interface/HGVHistoProducerAlgo.h
  Validation/HGCalValidation/plugins/HGCalHitCalibration.cc
  Validation/HGCalValidation/plugins/HGCalShowerSeparation.cc
  Validation/HGCalValidation/plugins/HGCalTriggerValidator.cc
  Validation/HGCalValidation/plugins/HeterogeneousHGCalRecHitsValidator.cc
  Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39584 Modernized modules in CommonTools/RecoUtils
  CommonTools/RecoUtils/interface/PFCand_NoPU_WithAM.h
  CommonTools/RecoUtils/interface/PF_PU_FirstVertexTracks.h
  CommonTools/RecoUtils/plugins/PFCand_NoPU_WithAM.cc
  CommonTools/RecoUtils/plugins/PF_PU_FirstVertexTracks.cc
Labels: analysis-pending, pending-signatures, tests-started, orp-approved, code-checks-approved

#39656 [GSF tracking] Add full Sylvester criterion for positive definite check
  TrackingTools/GsfTracking/src/GsfMultiStateUpdator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking, egamma

#39649 `AlignPCLThresholds_PayloadInspector`: reduce code duplication, move similar classes to a template and specialize them in the plugins
  CondCore/PCLConfigPlugins/interface/SiPixelAliPCLThresholdsPayloadInspectorHelper.h
  CondCore/PCLConfigPlugins/plugins/AlignPCLThresholdsHG_PayloadInspector.cc
  CondCore/PCLConfigPlugins/plugins/AlignPCLThresholds_PayloadInspector.cc
  CondCore/PCLConfigPlugins/test/test.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#39596 [MUO] Suppress excessive warnings in muon tracking at HLT
  RecoMuon/GlobalTrackingTools/src/GlobalTrajectoryBuilderBase.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39660 Made HcalLaserReco a global::EDProducer
  RecoLocalCalo/HcalLaserReco/src/HcalLaserReco.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39663 Fixed deprecation warnings in RecoMuon/GlobalTrackingTools
  RecoMuon/GlobalTrackingTools/plugins/GlobalTrackQualityProducer.cc
  RecoMuon/GlobalTrackingTools/test/DYTTuner.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39598 [HGCAL] Fix search box eta phi
  DataFormats/HGCalReco/interface/TICLLayerTile.h
  DataFormats/HGCalReco/test/BuildFile.xml
  DataFormats/HGCalReco/test/EtaPhiSearchInTile_t.cpp
  RecoLocalCalo/HGCalRecProducers/interface/HGCalLayerTiles.h
  RecoLocalCalo/HGCalRecProducers/test/BuildFile.xml
  RecoLocalCalo/HGCalRecProducers/test/EtaPhiSearchInTile_t.cpp
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, hgcal

#39556 Move EventSetup module PSet validation to be called from ComponentMaker
  FWCore/Framework/interface/ComponentFactory.h
  FWCore/Framework/interface/ComponentMaker.h
  FWCore/Framework/interface/EventSetupsController.h
  FWCore/Framework/interface/LooperFactory.h
  FWCore/Framework/interface/ModuleFactory.h
  FWCore/Framework/interface/SourceFactory.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/EventSetupProvider.cc
  FWCore/Framework/src/EventSetupProviderMaker.cc
  FWCore/Framework/src/EventSetupProviderMaker.h
  FWCore/Framework/src/EventSetupsController.cc
  FWCore/Framework/src/LooperFactory.cc
  FWCore/Framework/src/ModuleFactory.cc
  FWCore/Framework/src/SourceFactory.cc
  FWCore/Framework/test/eventsetupscontroller_t.cppunit.cc
  FWCore/ParameterSet/interface/ParameterSetDescriptionFiller.h
  FWCore/ParameterSet/interface/ParameterSetDescriptionFillerBase.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39665 Run3-sim128 Use token rather than label for accessing collections in FastSimulation/Calorimetry
  FastSimulation/Calorimetry/plugins/TreeWriterForEcalCorrection.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39655 Phase2-gex139 Avoid compilation warning coming from DataFormats/ForwardDetId
  DataFormats/ForwardDetId/interface/HGCalDetId.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39636 Add Service type in an exception message from ServiceRegistry
  FWCore/ServiceRegistry/interface/ServiceRegistry.h
  FWCore/ServiceRegistry/interface/ServicesManager.h
Labels: core-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#39664 Removed unnecessary deprecated header from L3MuonProducer.cc
  RecoMuon/L3MuonProducer/src/L3MuonProducer.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39662 Fix deprecation warnings in RecoMuon/GlobalMuonProducer
  RecoMuon/GlobalMuonProducer/src/GlobalMuonProducer.cc
  RecoMuon/GlobalMuonProducer/test/GLBMuonAnalyzer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39661 Moved RecoMuon/CosmicMuonProducer modules to thread-friendly types
  RecoMuon/CosmicMuonProducer/src/CosmicMuonLinksProducer.h
  RecoMuon/CosmicMuonProducer/test/CosmicMuonValidator.cc
  RecoMuon/CosmicMuonProducer/test/RealCosmicDataAnalyzer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39659 Removed unused header from EcalRecHitWorkerRecover.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitWorkerRecover.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#39641 Removed unnecessary headers in HiEvtPlaneFlatten
  RecoHI/HiEvtPlaneAlgos/interface/HiEvtPlaneFlatten.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39628 Changed Type1PFMET to global::EDProducer
  JetMETCorrections/Type1MET/plugins/Type1PFMET.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39601 [Backport 124X] [MUO] Suppress excessive warnings in muon tracking at HLT
  RecoMuon/GlobalTrackingTools/src/GlobalTrajectoryBuilderBase.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved

#39602 [Backport 125X] [MUO] Suppress excessive warnings in muon tracking at HLT
  RecoMuon/GlobalTrackingTools/src/GlobalTrajectoryBuilderBase.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved

#39682 [125X][GSF tracking] Add full Sylvester criterion for positive definite check
  TrackingTools/GsfTracking/src/GsfMultiStateUpdator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, egamma

#39681 [124X][GSF tracking] Add full Sylvester criterion for positive definite check
  TrackingTools/GsfTracking/src/GsfMultiStateUpdator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, egamma

#39521 [RECONSTRUCTION] [GCC12] Fix build warnings
  CommonTools/RecoAlgos/src/ClusterStorer.cc
  RecoMuon/MuonIdentification/src/MuonShowerInformationFiller.cc
  TrackingTools/PatternTools/src/TempTrajectory.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39230 [NanoAOD] Adding correct Iso filter name (without cut values) for Run3
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-pending, code-checks-approved, xpog-approved

#39587 Made MatacqProducer a one module
  EventFilter/EcalRawToDigi/plugins/MatacqProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39633 [12_6_X] RPCDqmClient crash fix for 0 LS runs
  DQM/RPCMonitorClient/plugins/RPCDqmClient.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39648 Updates in TOP-HLT DQM : Deepjet HLT path monitoring & flag to enable/disable production of 2d histos (backport of #39205))
  DQMOffline/Trigger/plugins/TopMonitor.cc
  DQMOffline/Trigger/python/TopMonitor_cfi.py
  DQMOffline/Trigger/python/TopMonitoring_Client_cff.py
  DQMOffline/Trigger/python/TopMonitoring_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39650 Add flag to enable/disable production of 2d histos & added deepjet HLT monitoring (backport of #39205)
  DQMOffline/Trigger/plugins/TopMonitor.cc
  DQMOffline/Trigger/python/TopMonitor_cfi.py
  DQMOffline/Trigger/python/TopMonitoring_Client_cff.py
  DQMOffline/Trigger/python/TopMonitoring_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39518 Modernize SiStripMonitorClient
  DQM/SiStripMonitorClient/plugins/SiStripAnalyser.cc
  DQM/SiStripMonitorClient/plugins/SiStripAnalyser.h
  DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.h
  DQM/SiStripMonitorClient/plugins/SiStripDaqInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripDaqInfo.h
  DQM/SiStripMonitorClient/plugins/SiStripDcsInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripDcsInfo.h
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk-dpg-approved, trk

#39606 Update fine calo proc modifier
  SimG4Core/Application/python/g4SimHits_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39688 Run3-sim132 Use token rather than label in some of te classes in FastSimulation/Tracking
  FastSimulation/Tracking/src/TrackingLayer.cc
  FastSimulation/Tracking/test/testGeneralTracks.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39631 [12_5_X] RPCDqmClient crash fix for 0 LS runs #39630
  DQM/RPCMonitorClient/plugins/RPCDqmClient.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#39571 Reset Phase-2 workflow ID
  Configuration/AlCa/python/autoCondPhase2.py
  Configuration/Geometry/README.md
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: alca-approved, geometry-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#39588 Made L1GctInternJetProducer a global module
  EventFilter/GctRawToDigi/plugins/L1GctInternJetProducer.cc
  EventFilter/GctRawToDigi/plugins/L1GctInternJetProducer.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39589 Changed L1GtTextToRaw to thread-friendly module type
  EventFilter/L1GlobalTriggerRawToDigi/interface/L1GtTextToRaw.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39629 Made L1Trigger/GlobalCaloTrigger test modules thread-friendly
  L1Trigger/GlobalCaloTrigger/test/FakeGctInputProducer.cc
  L1Trigger/GlobalCaloTrigger/test/FakeGctInputProducer.h
  L1Trigger/GlobalCaloTrigger/test/FakeGctInputTester.cc
  L1Trigger/GlobalCaloTrigger/test/FakeGctInputTester.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39630 [12_4_X] RPCDqmClient crash fix for 0 LS runs
  DQM/RPCMonitorClient/plugins/RPCDqmClient.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#39637 Moved modules in L1Trigger/TextToDigi to be thread friendly
  L1Trigger/TextToDigi/plugins/GctDigiToPsbText.h
  L1Trigger/TextToDigi/plugins/GtPsbTextToDigi.h
  L1Trigger/TextToDigi/plugins/RctDigiToSourceCardText.h
  L1Trigger/TextToDigi/plugins/RctTextToRctDigi.h
  L1Trigger/TextToDigi/plugins/SourceCardTextToRctDigi.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39632 Made L1Trigger/L1ExtraFromDigis modules thread safe
  L1Trigger/L1ExtraFromDigis/interface/L1ExtraParticleMapProd.h
  L1Trigger/L1ExtraFromDigis/src/L1ExtraParticleMapProd.cc
  L1Trigger/L1ExtraFromDigis/src/L1ExtraTestAnalyzer.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39626 Make L1Filter thread friendly
  L1Trigger/Skimmer/src/L1Filter.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39451 [12_5_X] [L1T] Backport of: Phase-2, include missing collections in outputs
  DataFormats/L1Trigger/interface/TkJetWord.h
  DataFormats/L1Trigger/src/TkJetWord.cc
  DataFormats/L1Trigger/src/classes_def.xml
  L1Trigger/Configuration/python/L1Trigger_EventContent_cff.py
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/L1CaloTrigger/plugins/Phase1L1TJetSumsProducer.cc
  L1Trigger/L1CaloTrigger/python/Phase1L1TJets_9x9_cff.py
  L1Trigger/L1TTrackMatch/plugins/L1TrackSelectionProducer.cc
  L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, backport-ok

#39704 [L1T] bug-fix: rename l1ctLayer1 objects
  L1Trigger/Phase2L1ParticleFlow/plugins/DeregionizerProducer.cc
  L1Trigger/Phase2L1ParticleFlow/test/make_l1ctLayer1_dumpFiles_cfg.py
  L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.cc
Labels: l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#39700 JetMETCorrections/MinBias legacy migration
  JetMETCorrections/MinBias/interface/MinBias.h
  JetMETCorrections/MinBias/src/MinBias.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39643 Changed HiL1Subtractor to global::EDProducer
  RecoHI/HiJetAlgos/plugins/HiL1Subtractor.cc
  RecoHI/HiJetAlgos/plugins/HiL1Subtractor.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39671 Run3-sim130 Use of tokens instead of labels for accessing collections in FastSimulation/Muons
  FastSimulation/Muons/plugins/FastTSGFromL2Muon.cc
  FastSimulation/Muons/plugins/FastTSGFromL2Muon.h
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39487 [GEM] Unpacker update for the vfat making information
  DQM/GEM/plugins/GEMDAQStatusSource.cc
  DataFormats/GEMDigi/interface/GEMOHStatus.h
  DataFormats/GEMDigi/interface/GEMOptoHybrid.h
  DataFormats/GEMDigi/interface/GEMVFATStatus.h
  DataFormats/GEMDigi/src/classes_def.xml
  EventFilter/GEMRawToDigi/plugins/GEMRawToDigiModule.cc
Labels: dqm-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, gem

#39687 Run3-alca231 Update some of the defaults for Muon analysis code in HCalAlCaRecoProducers and HcalCalibAlgos
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalHBHEMuonProducer.cc
  Calibration/HcalCalibAlgos/macros/HBHEMuonHighEta.C
  Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonHighEtaAnalyzer.cc
  Calibration/HcalCalibAlgos/plugins/HcalHBHENewMuonAnalyzer.cc
  Calibration/HcalCalibAlgos/test/HcalHBHEMuonSimAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39689 NanoAOD: move producers to new event getter methods
  PhysicsTools/NanoAOD/plugins/BJetEnergyRegressionVarProducer.cc
  PhysicsTools/NanoAOD/plugins/CandMCMatchTableProducer.cc
  PhysicsTools/NanoAOD/plugins/EGMSeedGainProducer.cc
  PhysicsTools/NanoAOD/plugins/GenJetFlavourTableProducer.cc
  PhysicsTools/NanoAOD/plugins/GenJetGenPartMerger.cc
  PhysicsTools/NanoAOD/plugins/GenJetTauTaggerProducer.cc
  PhysicsTools/NanoAOD/plugins/IsFromLostTrackMapProducer.cc
  PhysicsTools/NanoAOD/plugins/IsoValueMapProducer.cc
  PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc
  PhysicsTools/NanoAOD/plugins/LeptonInJetProducer.cc
  PhysicsTools/NanoAOD/plugins/LeptonJetVarProducer.cc
  PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc
  PhysicsTools/NanoAOD/plugins/NanoAODBaseCrossCleaner.cc
  PhysicsTools/NanoAOD/plugins/PileupJetIDVarProducer.cc
  PhysicsTools/NanoAOD/plugins/ProtonProducer.cc
  PhysicsTools/NanoAOD/plugins/TriggerObjectTableProducer.cc
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/V10/isotracks_cff.py
  PhysicsTools/NanoAOD/python/V10/jetsAK4_CHS_cff.py
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/NanoAOD/python/isotracks_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_CHS_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#39721 Made class static variable const in L1SeedConePFJetEmulator
  L1Trigger/Phase2L1ParticleFlow/interface/jetmet/L1SeedConePFJetEmulator.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39707 Fix number of aligned modules for HG PCL Tracker alignment
  Alignment/MillePedeAlignmentAlgorithm/src/MillePedeFileReader.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#39674 Remove use of deprecated header from RecoMuon subsystem
  RecoMuon/MuonIdentification/plugins/MuonLinksProducer.cc
  RecoMuon/MuonIdentification/plugins/MuonRefProducer.cc
  RecoMuon/MuonIdentification/plugins/MuonTimingProducer.cc
  RecoMuon/MuonIsolation/plugins/MuPFIsoEmbedder.cc
  RecoMuon/MuonIsolationProducers/plugins/MuIsolatorResultProducer.h
  RecoMuon/MuonIsolationProducers/test/IsolationExample.cc
  RecoMuon/MuonIsolationProducers/test/MuIsoDepositAnalyzer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39698 Fix CMS deprecation warnings in RecoTracker & RecoVertex
  RecoTracker/DebugTools/plugins/CkfDebugTrackCandidateMaker.h
  RecoTracker/DebugTools/plugins/CkfDebugger.cc
  RecoTracker/DebugTools/plugins/CkfDebugger.h
  RecoTracker/SpecialSeedGenerators/interface/CosmicRegionalSeedGenerator.h
  RecoVertex/AdaptiveVertexFinder/interface/TrackVertexArbitration.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39719 Better array initialization in L1TrackJetEmulationProducer
  L1Trigger/L1TTrackMatch/interface/L1TrackJetEmulationProducer.h
  L1Trigger/L1TTrackMatch/plugins/L1TrackJetEmulationProducer.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#39716 Thread safe fitting in EcalUncalibRecHitRecAnalFitAlgo
  RecoLocalCalo/EcalRecAlgos/interface/EcalUncalibRecHitRecAnalFitAlgo.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39709 [12.5.X] Fix number of aligned modules for HG PCL
  Alignment/MillePedeAlignmentAlgorithm/src/MillePedeFileReader.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#39708 [12.4.X] Fix number of aligned modules for HG PCL Tracker alignment
  Alignment/MillePedeAlignmentAlgorithm/src/MillePedeFileReader.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#39472 Nano test in runthematrix
  Configuration/PyReleaseValidation/python/MatrixReader.py
  Configuration/PyReleaseValidation/python/MatrixUtil.py
  Configuration/PyReleaseValidation/python/relval_nano.py
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved

#39701 Changed TopQuarkAnalysis/TopEventProducers modules to thread-friendly
  TopQuarkAnalysis/TopEventProducers/src/TtDilepEvtSolutionMaker.cc
  TopQuarkAnalysis/TopEventProducers/src/TtHadEvtSolutionMaker.cc
  TopQuarkAnalysis/TopEventProducers/src/TtSemiEvtSolutionMaker.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39711 Fix `SiPixelRawToClusterGPUKernel` for spurious ROCs
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk-dpg-approved

#39712 Fix `SiPixelRawToClusterGPUKernel` for spurious ROCs [12.5.x]
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#39713 Fix `SiPixelRawToClusterGPUKernel` for spurious ROCs [12.4.x]
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok

#39729 Resume stream queue later in releaseBeginRunResources
  FWCore/Framework/src/EventProcessor.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39609 Removed unused headers from GeneratorInterface/Pythia6Interface
  GeneratorInterface/Pythia6Interface/plugins/Pythia6ParticleGun.cc
  GeneratorInterface/Pythia6Interface/plugins/Pythia6ParticleGun.h
  GeneratorInterface/Pythia6Interface/plugins/Pythia6PartonGun.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39652 PPS automatic workflows for timing calibration
  CalibPPS/TimingCalibration/test/BuildFile.xml
  CalibPPS/TimingCalibration/test/DiamondCalibrationHarvester_cfg.py
  CalibPPS/TimingCalibration/test/DiamondCalibrationWorker_cfg.py
  CalibPPS/TimingCalibration/test/DiamondSampicCalibrationHarvester_cfg.py
  CalibPPS/TimingCalibration/test/DiamondSampicCalibrationWorker_cfg.py
  CalibPPS/TimingCalibration/test/crabConfig.py
  CalibPPS/TimingCalibration/test/runAutoHarvester.py
  CalibPPS/TimingCalibration/test/runWorkerCrab.py
  CalibPPS/TimingCalibration/test/test_hptdc_pcl.sh
  DQM/CTPPS/test/diamond_re_reco_dqm_test_cfg.py
  DQM/CTPPS/test/runCrab.py
  DQM/CTPPS/test/runCrabPerRun.py
Labels: alca-approved, dqm-approved, fully-signed, tests-approved, orp-approved, new-feature, code-checks-approved, ctpps

#39683 Phase2-hgx327 Modify the scripts needed to produce samples for muon tomography for HGCal
  Validation/HGCalValidation/scripts/testHGCalDigi_cfg.py
  Validation/HGCalValidation/scripts/testHGCalReco_cfg.py
  Validation/HGCalValidation/scripts/testHGCalSimSingleMuonPt100_cfg.py
  Validation/HGCalValidation/scripts/testHGCalSimTTBar_cfg.py
  Validation/HGCalValidation/test/HGCMissingRecHit.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39723 add `edm::one::SharedResources` to `DQM/SiStripMonitorClient` plugins
  DQM/SiStripMonitorClient/plugins/SiStripAnalyser.cc
  DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripDaqInfo.cc
  DQM/SiStripMonitorClient/plugins/SiStripDcsInfo.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39691 Fix trigger matching issues in L1Trigger DQMOffline
  DQMOffline/L1Trigger/interface/L1TMuonDQMOffline.h
  DQMOffline/L1Trigger/python/L1TEtSumJetOffline_cfi.py
  DQMOffline/L1Trigger/src/L1TCommon.cc
  DQMOffline/L1Trigger/src/L1TMuonDQMOffline.cc
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39557 Added transformAsync ability to modules
  FWCore/Framework/interface/TransformerBase.h
  FWCore/Framework/interface/global/EDFilterBase.h
  FWCore/Framework/interface/global/EDProducerBase.h
  FWCore/Framework/interface/global/implementors.h
  FWCore/Framework/interface/limited/EDFilterBase.h
  FWCore/Framework/interface/limited/EDProducerBase.h
  FWCore/Framework/interface/limited/implementors.h
  FWCore/Framework/interface/maker/Worker.h
  FWCore/Framework/interface/maker/WorkerT.h
  FWCore/Framework/interface/one/EDFilterBase.h
  FWCore/Framework/interface/one/EDProducerBase.h
  FWCore/Framework/interface/one/implementors.h
  FWCore/Framework/interface/stream/EDProducerBase.h
  FWCore/Framework/interface/stream/ProducingModuleAdaptorBase.h
  FWCore/Framework/interface/stream/implementors.h
  FWCore/Framework/src/TransformerBase.cc
  FWCore/Framework/src/Worker.cc
  FWCore/Framework/src/WorkerT.cc
  FWCore/Framework/src/global/EDFilterBase.cc
  FWCore/Framework/src/global/EDProducerBase.cc
  FWCore/Framework/src/limited/EDFilterBase.cc
  FWCore/Framework/src/limited/EDProducerBase.cc
  FWCore/Framework/src/one/EDFilterBase.cc
  FWCore/Framework/src/one/EDProducerBase.cc
  FWCore/Framework/src/stream/EDProducerAdaptorBase.cc
  FWCore/Framework/src/stream/EDProducerBase.cc
  FWCore/Framework/src/stream/ProducingModuleAdaptorBase.cc
  FWCore/Framework/test/global_filter_t.cppunit.cc
  FWCore/Framework/test/global_producer_t.cppunit.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/TransformAsyncIntProducer.cc
  FWCore/Integration/test/TransformAsyncIntStreamProducer.cc
  FWCore/Integration/test/transformTest_cfg.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39733 Update Phase-2 Tracker and HGCAL HLT config files
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  HLTrigger/Configuration/python/HLT_75e33/modules/siPhase2Clusters_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/psets/HGCAL_noise_fC_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/psets/HGCAL_noise_heback_cfi.py
Labels: hlt-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#39666 Run3-sim129 Use token rather than label for accessing collections in FastSimulation/ForwardDetectors
  FastSimulation/ForwardDetectors/plugins/FastSimDataFilter.cc
  FastSimulation/ForwardDetectors/plugins/FastSimDataFilter.h
  FastSimulation/ForwardDetectors/plugins/ProtonTaggerFilter.cc
  FastSimulation/ForwardDetectors/plugins/ProtonTaggerFilter.h
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39690 Add new LumiCorrectionsSummary plot for Payload Inspector
  CondCore/LuminosityPlugins/plugins/BuildFile.xml
  CondCore/LuminosityPlugins/plugins/LumiCorrections_PayloadInspector.cc
  CondCore/LuminosityPlugins/test/BuildFile.xml
  CondCore/LuminosityPlugins/test/testLumiCorrections.cpp
  CondCore/LuminosityPlugins/test/testLumiCorrections.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#39718 Fix thread safety issues in L1Trigger/Phase2L1GMT
  L1Trigger/Phase2L1GMT/plugins/Isolation.h
  L1Trigger/Phase2L1GMT/plugins/TopologicalAlgorithm.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39699 Fixed CMS deprecation warnings in SimPPS/RPDigiProducer
  SimPPS/RPDigiProducer/plugins/RPDetDigitizer.cc
  SimPPS/RPDigiProducer/plugins/RPDetDigitizer.h
  SimPPS/RPDigiProducer/plugins/RPDigiProducer.cc
  SimPPS/RPDigiProducer/plugins/RPDisplacementGenerator.cc
  SimPPS/RPDigiProducer/plugins/RPDisplacementGenerator.h
Labels: simulation-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39731 Run3-alca232 Update the scripts to make offline analysis of muon data in calibrating HCAL
  Calibration/HcalCalibAlgos/macros/AnalyzeLepTree.C
  Calibration/HcalCalibAlgos/macros/AnalyzeMain.C
  Calibration/HcalCalibAlgos/macros/HBHEMuonOfflineAnalyzer.C
  Calibration/HcalCalibAlgos/macros/OfflineMain.C
  Calibration/HcalCalibAlgos/macros/install_AnalyzeLepTree.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#39753 Add missing include to TransformerBase.cc
  FWCore/Framework/src/TransformerBase.cc
Labels: core-approved, fully-signed, tests-started, orp-approved, code-checks-approved

#39747 Fix deprecation warnings in PhysicsTools sub-system
  PhysicsTools/JetCharge/test/JetChargeAnalyzer.cc
  PhysicsTools/JetExamples/test/printGenJetRatio.cc
  PhysicsTools/JetExamples/test/printJetFlavour.cc
  PhysicsTools/JetExamples/test/printJetFlavourInfo.cc
  PhysicsTools/JetExamples/test/printPartonJet.cc
  PhysicsTools/JetExamples/test/printTrackJet.cc
  PhysicsTools/MVAComputer/test/testReadMVAComputerCondDB.cc
  PhysicsTools/MVAComputer/test/testWriteMVAComputerCondDB.cc
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#39468 [124X] Fix double counting in HepMC to G4 handoff
  SimG4Core/Generators/src/Generator.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#39738 Skip invalid channels in the GPU HCAL RecHit producer
  RecoLocalCalo/HcalRecProducers/src/HcalCPURecHitsProducer.cc
  RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, hcal-dpg-approved

#39439 [125X] Fix double counting in HepMC to G4 handoff
  SimG4Core/Generators/src/Generator.cc
Labels: simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#39703 Run3-sim133 Use token instead of label in accessing collection and use TFileService for ROOT histograms in FastSimulation/Validation
  FastSimulation/Validation/test/BuildFile.xml
  FastSimulation/Validation/test/JetComparison.cc
  FastSimulation/Validation/test/JetComparison.h
  FastSimulation/Validation/test/runJetPlotFast_cfg.py
  FastSimulation/Validation/test/runJetPlotFull_cfg.py
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved
