Repository cms-sw/cmssw, pull requests merged in 2023-06, with the labels that each got.

#41825 improved file size/buffer size checks in DAQ input source (13_0_X)
  EventFilter/Utilities/interface/FedRawDataInputSource.h
  EventFilter/Utilities/src/FedRawDataInputSource.cc
Labels: daq-approved, fully-signed, tests-approved, orp-approved

#41824 improved file size/buffer size checks in DAQ input source (13_1_X)
  EventFilter/Utilities/interface/DAQSource.h
  EventFilter/Utilities/interface/FedRawDataInputSource.h
  EventFilter/Utilities/src/DAQSource.cc
  EventFilter/Utilities/src/FedRawDataInputSource.cc
Labels: daq-approved, fully-signed, tests-approved, orp-approved

#41823 [13.0.X] Online DQM configure `timeThreshold` appropriately when running in 'offline' mode
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/onlinebeammonitor_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/pixel_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41822 [13.1.X] Online DQM configure `timeThreshold` appropriately when running in 'offline' mode
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/onlinebeammonitor_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/pixel_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41837 [DAQ] silence ExceptionGenerator gcc12 warning
  EventFilter/Utilities/plugins/ExceptionGenerator.cc
Labels: daq-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41833 Utilities/StaticAnalyzers: Remove postprocess-scan-build.py script no longer needed.
  Utilities/StaticAnalyzers/scripts/postprocess-scan-build.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41836 Update 13000 to 13600 in ReweightUserHooks.h for Run3
  GeneratorInterface/Pythia8Interface/plugins/ReweightUserHooks.h
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41835 New EMTF BDT pT scale for 2023
  L1Trigger/L1TMuonEndCap/src/PtAssignmentEngine2017.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41850 Update ReweightUserHooks.h
  GeneratorInterface/Pythia8Interface/plugins/ReweightUserHooks.h
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41848 Update ReweightUserHooks.h to be able to handle 13.6 TeV
  GeneratorInterface/Pythia8Interface/plugins/ReweightUserHooks.h
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41847 Update ReweightUserHooks.h to be able to handle 13.6 TeV, backport of…
  GeneratorInterface/Pythia8Interface/plugins/ReweightUserHooks.h
Labels: generators-pending, pending-signatures, tests-rejected, orp-approved, backport-ok

#41852 Convert also DOMException to cms::Exception in TotemDAQMappingESSourceXML
  CalibPPS/ESProducers/plugins/TotemDAQMappingESSourceXML.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41834 Add unit test for Run 3 Scouting formats
  DataFormats/Scouting/README.md
  DataFormats/Scouting/test/BuildFile.xml
  DataFormats/Scouting/test/TestReadRun3Scouting.cc
  DataFormats/Scouting/test/TestRun3ScoutingFormats.sh
  DataFormats/Scouting/test/TestWriteRun3Scouting.cc
  DataFormats/Scouting/test/create_Run3Scouting_test_file_cfg.py
  DataFormats/Scouting/test/test_readRun3Scouting_CMSSW_12_4_0_cfg.py
  DataFormats/Scouting/test/test_readRun3Scouting_cfg.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#41860 Add a unit test for `SiStripHashedDetId`
  CalibFormats/SiStripObjects/test/BuildFile.xml
  CalibFormats/SiStripObjects/test/testSiStripHashedDetId.sh
  CalibFormats/SiStripObjects/test/testSiStripHashedDetId_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#41842 [13_0_X] New EMTF BDT pT scale for 2023
  L1Trigger/L1TMuonEndCap/src/PtAssignmentEngine2017.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41840 [13_1_X] New EMTF BDT pT scale for 2023
  L1Trigger/L1TMuonEndCap/src/PtAssignmentEngine2017.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41832 Fix logical error in the check of mask flag bits [13_0_X]
  DQM/EcalMonitorClient/src/MLClient.cc
  DQM/EcalMonitorTasks/src/EnergyTask.cc
  DQM/EcalMonitorTasks/src/OccupancyTask.cc
  DQM/EcalMonitorTasks/src/TimingTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, ecal

#41831 Fix logical error in the check of mask flag bits [13_1_X]
  DQM/EcalMonitorClient/src/MLClient.cc
  DQM/EcalMonitorTasks/src/EnergyTask.cc
  DQM/EcalMonitorTasks/src/OccupancyTask.cc
  DQM/EcalMonitorTasks/src/TimingTask.cc
Labels: dqm-approved, fully-signed, tests-rejected, orp-approved, backport-ok, ecal

#41819 Undefine _Float16
  RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#41792 Fix gcc 12 error: result of pointer addition is never NULL
  EventFilter/HGCalRawToDigi/plugins/HGCalRawToDigi.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#41854 [PileUpJetID] Move average calculations outside of jet constituents loop
  RecoJets/JetProducers/src/PileupJetIdAlgo.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, performance-improvements, jetmet

#38226 Integration of the first version of muon DPG nanoAOD ntuples
  DPGAnalysis/MuonTools/BuildFile.xml
  DPGAnalysis/MuonTools/interface/MuBaseFlatTableProducer.h
  DPGAnalysis/MuonTools/interface/MuDigiBaseProducer.h
  DPGAnalysis/MuonTools/interface/MuLocalRecoBaseProducer.h
  DPGAnalysis/MuonTools/interface/MuNtupleUtils.h
  DPGAnalysis/MuonTools/plugins/BuildFile.xml
  DPGAnalysis/MuonTools/plugins/MuCSCTnPFlatTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuDTMuonExtTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuDTSegmentExtTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuDTTPGPhiFlatTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuDTTPGThetaFlatTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuDigiFlatTableProducers.cc
  DPGAnalysis/MuonTools/plugins/MuGEMMuonExtTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuLocalRecoFlatTableProducers.cc
  DPGAnalysis/MuonTools/python/common_cff.py
  DPGAnalysis/MuonTools/python/customiseMuNtuples_cff.py
  DPGAnalysis/MuonTools/python/muNtupleProducerBkg_cff.py
  DPGAnalysis/MuonTools/python/muNtupleProducerRaw_cff.py
  DPGAnalysis/MuonTools/python/muNtupleProducer_cff.py
  DPGAnalysis/MuonTools/python/nano_mu_digi_cff.py
  DPGAnalysis/MuonTools/python/nano_mu_l1t_cff.py
  DPGAnalysis/MuonTools/python/nano_mu_local_reco_cff.py
  DPGAnalysis/MuonTools/python/nano_mu_reco_cff.py
  DPGAnalysis/MuonTools/src/MuBaseFlatTableProducer.cc
  DPGAnalysis/MuonTools/src/MuNtupleUtils.cc
  DPGAnalysis/MuonTools/test/muDpgNtuplesRaw_cfg.py
  DPGAnalysis/MuonTools/test/muDpgNtuplesZMu_cfg.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#41855 [13_0_X] Update muon (un)packer with support for fixed uGMT firmware
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/MuonUnpacker.cc
  L1Trigger/L1TMuon/interface/MuonRawDigiTranslator.h
  L1Trigger/L1TMuon/src/MuonRawDigiTranslator.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41856 [13_1_X] Update muon (un)packer with support for fixed uGMT firmware
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/MuonUnpacker.cc
  L1Trigger/L1TMuon/interface/MuonRawDigiTranslator.h
  L1Trigger/L1TMuon/src/MuonRawDigiTranslator.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41849 Tracker Alignment: all in one Zmumu fixes
  Alignment/OfflineValidation/bin/Zmumumerge.cc
  Alignment/OfflineValidation/python/TkAlAllInOneTool/Zmumu_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#41868 add L1nano NANO in Prompt/Tier0 configuration
  Configuration/DataProcessing/python/Reco.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41875 Remove stripTrackerHVOn check for BeamSpotLegacy client
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41874 Move events/LS counter to LuminosityBlockCache in DTDataIntegrityTask
  DQM/DTMonitorModule/interface/DTDataIntegrityTask.h
  DQM/DTMonitorModule/src/DTDataIntegrityTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41876 Adding automated thread controls for fallback triton servers
  HeterogeneousCore/SonicTriton/interface/TritonService.h
  HeterogeneousCore/SonicTriton/scripts/cmsTriton
  HeterogeneousCore/SonicTriton/src/TritonService.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#41871 Cleaning code recently added to RecoLocalCalo/HGCalRecProducers
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalCLUEAlgo.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalLayerClusterProducer.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalMultiClusterProducer.cc
  RecoLocalCalo/HGCalRecProducers/plugins/MergeClusterProducer.cc
  RecoLocalCalo/HGCalRecProducers/python/hgcalLayerClusters_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#41877 Run3-alca244X Make use of PF thresholds for ECAL/HCAL in insolated tracks of hadron/muon studies
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalHBHEMuonProducer.cc
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMain.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibPlotProperties.C
  Calibration/HcalCalibAlgos/macros/CalibTree.C
  Calibration/IsolatedParticles/interface/eECALMatrix.h
  Calibration/IsolatedParticles/src/eECALMatrix.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40802 [PileupJetId, Puppi] Backport of #40762 (Pileup ID input variable fix, puppi weight ValueMap access, optional photon protection for existing puppi weights) to CMSSW_12_6_X
  CommonTools/PileupAlgos/plugins/PuppiProducer.cc
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  RecoJets/JetProducers/interface/PileupJetIdAlgo.h
  RecoJets/JetProducers/plugins/PileupJetIdProducer.cc
  RecoJets/JetProducers/plugins/PileupJetIdProducer.h
  RecoJets/JetProducers/python/PileupJetID_cfi.py
  RecoJets/JetProducers/src/PileupJetIdAlgo.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#41870 [PileUpJetID] Backport of #41854 (Move average calculations outside of jet constituents loop) to 13_0_X
  RecoJets/JetProducers/src/PileupJetIdAlgo.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41869 [PileUpJetID] Backport of #41854 (Move average calculations outside of jet constituents loop) to 13_1_X
  RecoJets/JetProducers/src/PileupJetIdAlgo.cc
Labels: reconstruction-approved, fully-signed, tests-rejected, orp-approved, backport-ok

#41873 CMSSW changes for Eigen API changes
  HeterogeneousCore/AlpakaTest/plugins/TestAlpakaAnalyzer.cc
  HeterogeneousCore/CUDATest/plugins/TestPortableAnalyzer.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#41882 [13_1_X] Remove stripTrackerHVOn check for BeamSpotLegacy client
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41883 [13_0_X] Remove stripTrackerHVOn check for BeamSpotLegacy client
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41879 [13.0.X] add ME-s needed for per-LS certification of Tracking at HLT in `nanoDQMIO` output
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41878 [13.1.X] add ME-s needed for per-LS certification of Tracking at HLT in `nanoDQMIO` output
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41861 Utilities/StaticAnalyzers: updates to address changes in number of reports with llvm 14/16
  Utilities/StaticAnalyzers/src/ConstCastAwayChecker.cpp
  Utilities/StaticAnalyzers/src/ConstCastChecker.cpp
  Utilities/StaticAnalyzers/src/FunctionChecker.cpp
  Utilities/StaticAnalyzers/src/GlobalStaticChecker.cpp
  Utilities/StaticAnalyzers/src/GlobalStaticChecker.h
  Utilities/StaticAnalyzers/src/MutableMemberChecker.cpp
  Utilities/StaticAnalyzers/src/MutableMemberChecker.h
  Utilities/StaticAnalyzers/src/StaticLocalChecker.cpp
  Utilities/StaticAnalyzers/src/StaticLocalChecker.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#41896 Added Push ability to edm::mpl::Vector
  FWCore/Utilities/interface/mplVector.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41889 Add L1NANO in Prompt/Tier0 configuration [13_1_X]
  Configuration/DataProcessing/python/Reco.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41872 Fix a race condition in StMeasurementDetSet
  RecoTracker/MeasurementDet/src/TkMeasurementDetSet.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#41710 Fix ak8PFJetsPuppiConstituents module configuration at PAT-level
  PhysicsTools/PatAlgos/python/slimming/applySubstructure_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, xpog-approved

#41827 Add CaloIdL_MW unseeded filter to nanoAOD filterBits
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, egamma

#41904 Utilities/StaticAnalyzers: Remove postprocess-scan-build.py script no longer needed [13_1_X]
  Utilities/StaticAnalyzers/scripts/postprocess-scan-build.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41890 Update HLT menu for D98 and D99 from Fake to RelVal2026
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#41912 [13.0.X] Tracker Alignment: all in one Zmumu fixes
  Alignment/OfflineValidation/bin/Zmumumerge.cc
  Alignment/OfflineValidation/python/TkAlAllInOneTool/Zmumu_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#41911 [13.1.X] Tracker Alignment: all in one Zmumu fixes
  Alignment/OfflineValidation/bin/Zmumumerge.cc
  Alignment/OfflineValidation/python/TkAlAllInOneTool/Zmumu_cfg.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#41907 Run3-gex163 Try to address the issue of RPC geometry
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilder.cc
  Geometry/RPCGeometryBuilder/src/RPCGeometryParsFromDD.cc
  Geometry/RPCGeometryBuilder/test/python/dumpRPCGeometryDD4hep_cfg.py
  Geometry/RPCGeometryBuilder/test/python/dumpRPCGeometryDDD_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41906 Adding a comparison plot on two tags for JetMET JEC PI
  CondCore/JetMETPlugins/plugins/JetCorrector_PayloadInspector.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#41885 Automated thread control with ensemble models
  HeterogeneousCore/SonicTriton/scripts/cmsTriton
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#41892 Small fix to DTDataIntegrityTask.cc
  DQM/DTMonitorModule/interface/DTDataIntegrityTask.h
  DQM/DTMonitorModule/src/DTDataIntegrityTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41893 Fix dqm-* scripts for python3.
  DQMServices/Components/python/HTTP.py
  DQMServices/Components/python/ROOTData.py
  DQMServices/Components/scripts/dqm-access
  DQMServices/Components/scripts/dqm-grep
  DQMServices/Components/scripts/dqm-ls
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41900 update unit tests for `CondTools/SiPhase2Tracker` package such that it registers failures
  CondTools/SiPhase2Tracker/plugins/SiPhase2BadStripChannelBuilder.cc
  CondTools/SiPhase2Tracker/test/SiPhase2BadStripChannelBuilder_cfg.py
  CondTools/SiPhase2Tracker/test/SiPhase2BadStripChannelReader_cfg.py
  CondTools/SiPhase2Tracker/test/SiPhase2OuterTrackerLorentzAngleReader_cfg.py
  CondTools/SiPhase2Tracker/test/SiPhase2OuterTrackerLorentzAngleWriter_cfg.py
  CondTools/SiPhase2Tracker/test/test_CondToolsSiPhase2Tracker.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#41629 Add 2023 data relval workflows
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#41909 [13_1_X] Fix a race condition in StMeasurementDetSet
  RecoTracker/MeasurementDet/src/TkMeasurementDetSet.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, tracking

#41910 [13_0_X] Fix a race condition in StMeasurementDetSet
  RecoTracker/MeasurementDet/src/TkMeasurementDetSet.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, tracking

#41921 Run3-gex164 Try to address the issue of RPC geometry for Run3 applications
  Geometry/MuonCommonData/data/rpcf/2021/v2/rpcf.xml
  Geometry/MuonCommonData/python/GeometryExtended2021Reco_cff.py
  Geometry/MuonCommonData/python/testExtendedGeometry2021XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41908 No need to check into base classes of std classes in DictionaryTools.
  FWCore/Reflection/src/DictionaryTools.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41931 [13_1_X] Add isAvailable() function to RefToBaseProd
  DataFormats/Common/interface/Ptr.h
  DataFormats/Common/interface/Ref.h
  DataFormats/Common/interface/RefCoreWithIndex.h
  DataFormats/Common/interface/RefProd.h
  DataFormats/Common/interface/RefToBase.h
  DataFormats/Common/interface/RefToBaseProd.h
  DataFormats/Common/test/reftobaseprod_t.cppunit.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41933 [13_0_X] Add isAvailable() function to RefToBaseProd
  DataFormats/Common/interface/Ptr.h
  DataFormats/Common/interface/Ref.h
  DataFormats/Common/interface/RefCoreWithIndex.h
  DataFormats/Common/interface/RefProd.h
  DataFormats/Common/interface/RefToBase.h
  DataFormats/Common/interface/RefToBaseProd.h
  DataFormats/Common/test/reftobaseprod_t.cppunit.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41913 Add unit test for Run 2 Scouting data formats
  DataFormats/Scouting/README.md
  DataFormats/Scouting/src/classes_def.xml
  DataFormats/Scouting/test/BuildFile.xml
  DataFormats/Scouting/test/TestReadRun2Scouting.cc
  DataFormats/Scouting/test/TestRun2ScoutingFormats.sh
  DataFormats/Scouting/test/TestRun3ScoutingFormats.sh
  DataFormats/Scouting/test/TestWriteRun2Scouting.cc
  DataFormats/Scouting/test/create_Run2Scouting_test_file_cfg.py
  DataFormats/Scouting/test/test_readRun2Scouting_cfg.py
  DataFormats/Scouting/test/test_readRun3Scouting_CMSSW_12_4_0_cfg.py
  DataFormats/Scouting/test/test_readRun3Scouting_cfg.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#41924 Add comparison plots for JetResolution and SF
  CondCore/JetMETPlugins/plugins/JetResolution_PayloadInspector.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#41926 drop --catalog option from edmFileUtil check in unittestinputsource (online DQM unit tests)
  DQM/Integration/python/config/unittestinputsource_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41930 add protection to `ParticleNetJetTagMonitor`, removed unused struct
  DQMOffline/Trigger/plugins/ParticleNetJetTagMonitor.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#41920 Add `SiPixelRawDataError` monitoring for `gpuValidation` setup
  DQM/SiPixelHeterogeneous/plugins/SiPixelCompareRecHitsSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelPhase1RawDataErrorComparator.cc
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQMHarvesting_cff.py
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQM_FirstStep_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#41917 Add Phase-2 MET and Muon trigger paths to DQM
  HLTriggerOffline/Common/python/HLTValidation_cff.py
  HLTriggerOffline/JetMET/python/Validation/SingleJetValidation_cfi.py
  HLTriggerOffline/Muon/python/hltMuonValidator_cfi.py
Labels: dqm-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#41905 Fix CLUE3D data hazard
  RecoHGCal/TICL/plugins/PatternRecognitionbyCLUE3D.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#41937 remove tracking efficiency and fake rate w.r.t. offline plots from list of ME to be outputed by LS
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41323 Filter tracks extrapolated to the muon system
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.cc
  RecoMuon/MuonIdentification/python/muons1stStep_cfi.py
  TrackingTools/TrackAssociator/BuildFile.xml
  TrackingTools/TrackAssociator/interface/TrackAssociatorParameters.h
  TrackingTools/TrackAssociator/interface/TrackDetectorAssociator.h
  TrackingTools/TrackAssociator/python/default_cfi.py
  TrackingTools/TrackAssociator/src/TrackAssociatorParameters.cc
  TrackingTools/TrackAssociator/src/TrackDetectorAssociator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, performance-improvements, tracking, muon

#41934 CSC Unpacker fix for handling of rare CSC data corruption
  EventFilter/CSCRawToDigi/src/CSCDDUEventData.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, muon

#41897 Heavy ions: Added flow modulated CS jets for miniAOD data
  RecoHI/HiJetAlgos/plugins/HiFJRhoFlowModulationProducer.cc
  RecoJets/JetProducers/plugins/CSJetProducer.cc
  RecoJets/JetProducers/plugins/CSJetProducer.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, jetmet

#41951 Update of L1T pp menu in TSG GTs to `L1Menu_Collisions2023_v1_2_0_xml`
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41954 Change EMTF Primitive Conversion LUT Assignment for MC
  L1Trigger/L1TMuonEndCap/src/SectorProcessorLUT.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external, code-checks-approved

#41958 Add new L1T menu to relval/ideal/2024/run4 GTs and re-snapshot data GTS
  Configuration/AlCa/python/autoCond.py
  Configuration/AlCa/python/autoCondModifiers.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41966 remove tracking efficiency and fake rate w.r.t. offline plots from list of ME to be outputed by LS [13.0.X]
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
Labels: dqm-approved, fully-signed, tests-rejected, orp-approved, backport-ok

#41965 remove tracking efficiency and fake rate w.r.t. offline plots from list of ME to be outputed by LS [13.1.X]
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
Labels: dqm-approved, fully-signed, tests-rejected, orp-approved, backport-ok

#41939 [13.0.X] Add `SiPixelRawDataError` monitoring for `gpuValidation` setup
  DQM/SiPixelHeterogeneous/plugins/SiPixelCompareRecHitsSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelPhase1RawDataErrorComparator.cc
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQMHarvesting_cff.py
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQM_FirstStep_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#41938 [13.1.X] Add `SiPixelRawDataError` monitoring for `gpuValidation` setup
  DQM/SiPixelHeterogeneous/plugins/SiPixelCompareRecHitsSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelPhase1RawDataErrorComparator.cc
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQMHarvesting_cff.py
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQM_FirstStep_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#41949 [13_0_X] backport. CSC Unpacker fix for handling of rare CSC data corruption
  EventFilter/CSCRawToDigi/src/CSCDDUEventData.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, muon

#41948 [13_1_X] backport. CSC Unpacker fix for handling of rare CSC data corruption
  EventFilter/CSCRawToDigi/src/CSCDDUEventData.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, muon

#41953 Update of L1T pp menu in TSG GTs to `L1Menu_Collisions2023_v1_2_0_xml` [`13_0_X`]
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41952 Update of L1T pp menu in TSG GTs to `L1Menu_Collisions2023_v1_2_0_xml` [`13_1_X`]
  Configuration/HLT/python/autoCondHLT.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41955 [13_1_X] Change EMTF Primitive Conversion LUT Assignment for MC
  L1Trigger/L1TMuonEndCap/src/SectorProcessorLUT.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41956 [13_0_X] Change EMTF Primitive Conversion LUT Assignment for MC
  L1Trigger/L1TMuonEndCap/src/SectorProcessorLUT.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41947 Add preliminary GTs for 2023 MC
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external, code-checks-approved

#41945 Enable feature to recycle GEN for FastSim
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#41944 Definition of a new DQM Offline sequence to be run on Express Stream
  Configuration/StandardSequences/python/Harvesting_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41950 Remove tests for removed packages (see cms-sw/cmsdist#8533)
  PhysicsTools/PythonAnalysis/test/BuildFile.xml
  PhysicsTools/PythonAnalysis/test/testDownhill.py
  PhysicsTools/PythonAnalysis/test/testTheano.py
  PhysicsTools/PythonAnalysis/test/testTheano.sh
  PhysicsTools/PythonAnalysis/test/testhep_ml.py
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#41943 Phase2-hgx341A One step to resolve cassette shift issue for V18 where the shift will move the passive elements as well
  Geometry/HGCalCommonData/data/hgcalPassive/v18/hgcalPassive.xml
  Geometry/HGCalCommonData/data/hgcalPassive/v18/hgcalpos.xml
  Geometry/HGCalCommonData/plugins/DDHGCalPassiveFull.cc
  Geometry/HGCalCommonData/plugins/DDHGCalPassivePartial.cc
  Geometry/HGCalCommonData/python/testHGCalPassiveXML_cfi.py
  Geometry/HGCalCommonData/test/python/dumpHGCalPassive_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#41959 [13_1_X] Add preliminary GTs for 2023 MC and new L1T menu to relval/ideal/2024/run4 GTs and re-snapshot data GTS
  Configuration/AlCa/python/autoCond.py
  Configuration/AlCa/python/autoCondModifiers.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#41960 [13_0_X] Add preliminary GTs for 2023 MC and new L1T menu to relval/ideal/2024/run4 GTs and re-snapshot data GTS
  Configuration/AlCa/python/autoCond.py
  Configuration/AlCa/python/autoCondModifiers.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#41967 Miscellaneous improvements to `SimBeamSpotObjects` handling utilities
  CondCore/BeamSpotPlugins/interface/BeamSpotPayloadInspectorHelper.h
  CondCore/BeamSpotPlugins/plugins/SimBeamSpot_PayloadInspector.cc
  CondCore/BeamSpotPlugins/test/testBeamSpotPayloadInspector.cpp
  CondTools/BeamSpot/plugins/BeamProfile2DBReader.cc
  CondTools/BeamSpot/plugins/BeamProfile2DBWriter.cc
  CondTools/BeamSpot/plugins/BeamSpotRcdReader.cc
  CondTools/BeamSpot/python/BeamProfile2DBRead_cfi.py
  CondTools/BeamSpot/python/BeamSpotRcdRead_cfi.py
  CondTools/BeamSpot/test/BeamProfile2DBReader_cfg.py
  CondTools/BeamSpot/test/BeamProfile2DBWriterAll_cfg.py
  CondTools/BeamSpot/test/BeamProfile2DBWriter_cfg.py
  CondTools/BeamSpot/test/extractAndUploadAll.py
  IOMC/EventVertexGenerators/src/BetafuncEvtVtxGenerator.cc
Labels: alca-approved, simulation-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, tracking

#41224 implement fw-based Phase2 EG standalone barrel
  DataFormats/L1TCalorimeterPhase2/BuildFile.xml
  DataFormats/L1TCalorimeterPhase2/interface/CaloCrystalCluster.h
  DataFormats/L1TCalorimeterPhase2/interface/DigitizedClusterCorrelator.h
  DataFormats/L1TCalorimeterPhase2/interface/DigitizedClusterGT.h
  DataFormats/L1TCalorimeterPhase2/interface/DigitizedTowerCorrelator.h
  DataFormats/L1TCalorimeterPhase2/src/classes.h
  DataFormats/L1TCalorimeterPhase2/src/classes_def.xml
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/L1CaloTrigger/BuildFile.xml
  L1Trigger/L1CaloTrigger/interface/Phase2L1CaloEGammaUtils.h
  L1Trigger/L1CaloTrigger/interface/Phase2L1GCT.h
  L1Trigger/L1CaloTrigger/interface/Phase2L1RCT.h
  L1Trigger/L1CaloTrigger/plugins/L1EGammaCrystalsEmulatorProducer.cc
  L1Trigger/L1CaloTrigger/plugins/Phase2L1CaloEGammaEmulator.cc
  L1Trigger/L1CaloTrigger/python/l1tPhase2L1CaloEGammaEmulator_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#41880 Phase 2 tracker: realistic description of 3D modules in inner tracker
  Configuration/AlCa/python/autoCondPhase2.py
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2026D100Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D100_cff.py
  Configuration/Geometry/python/GeometryExtended2026D100Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D100_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  DataFormats/TrackerCommon/interface/TrackerTopology.h
  DataFormats/TrackerCommon/src/TrackerTopology.cc
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D100.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D100XML_cfi.py
  Geometry/CommonDetUnit/interface/DoubleSensGeomDet.h
  Geometry/CommonTopologies/interface/DoubleSensGeomDet.h
  Geometry/CommonTopologies/src/DoubleSensGeomDet.cc
  Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05/pixel.xml
  Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05/pixelStructureTopology.xml
  Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml
  Geometry/TrackerGeometryBuilder/src/TrackerGeomBuilderFromGeometricDet.cc
  Geometry/TrackerGeometryBuilder/src/TrackerGeometry.cc
  Geometry/TrackerNumberingBuilder/interface/GeometricDet.h
  Geometry/TrackerNumberingBuilder/plugins/CmsDetConstruction.cc
  Geometry/TrackerNumberingBuilder/plugins/CmsDetConstruction.h
  Geometry/TrackerNumberingBuilder/plugins/DDDCmsTrackerContruction.cc
  Geometry/TrackerNumberingBuilder/plugins/TrackerTopologyEP.cc
  Geometry/TrackerNumberingBuilder/src/CmsTrackerStringToEnum.cc
  Geometry/TrackerNumberingBuilder/src/GeometricDet.cc
  Geometry/TrackerRecoData/data/PhaseII/Tracker_DD4hep_compatible_IT710_2023_04/trackerRecoMaterial.xml
  Geometry/TrackerRecoData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05/trackerRecoMaterial.xml
  Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05/pixelProdCuts.xml
  Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05/pixelsens.xml
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.cc
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.h
  RecoTracker/MeasurementDet/plugins/TkDoubleSensMeasurementDet.cc
  RecoTracker/MeasurementDet/plugins/TkDoubleSensMeasurementDet.h
  RecoTracker/PixelLowPtUtilities/src/ClusterShapeHitFilter.cc
  RecoTracker/TkDetLayers/src/PixelRodBuilder.cc
Labels: alca-approved, geometry-approved, operations-approved, reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, tracking, trk

#41996 Run3-gex164Y Add a test script to utilize Geometry.MuonCommonData.GeometryExtended2021_cff which helps in resolving rpc geometry issue
  Geometry/MuonCommonData/test/python/runSim_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#40828 Backport FastSim refiner network for NANO (DeepJet for AK4 CHS Jets)
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  PhysicsTools/NanoAOD/plugins/BJetEnergyRegressionMVA.cc
  PhysicsTools/NanoAOD/plugins/BuildFile.xml
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/ONNXRuntime/interface/ONNXRuntime.h
  PhysicsTools/PatAlgos/BuildFile.xml
  PhysicsTools/PatAlgos/interface/BaseMVAValueMapProducer.h
  PhysicsTools/PatAlgos/plugins/BaseMVAValueMapProducer.cc
  PhysicsTools/PatAlgos/plugins/BaseMVAValueMapProducer.h
  PhysicsTools/PatAlgos/plugins/BuildFile.xml
Labels: reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, requires-external, backport-ok, xpog-approved

#41978 SIM: MC truth interfaces clean-up
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4Core/Application/interface/RunManagerMTWorker.h
  SimG4Core/Application/interface/SimRunInterface.h
  SimG4Core/Application/src/EventAction.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/Application/src/SimRunInterface.cc
  SimG4Core/Application/src/TrackingAction.cc
  SimG4Core/GeometryProducer/src/GeometryProducer.cc
  SimG4Core/Notification/interface/G4TrackToParticleID.h
  SimG4Core/Notification/interface/SimTrackManager.h
  SimG4Core/Notification/interface/TrackInformation.h
  SimG4Core/Notification/interface/TrackWithHistory.h
  SimG4Core/Notification/src/G4TrackToParticleID.cc
  SimG4Core/Notification/src/MCTruthUtil.cc
  SimG4Core/Notification/src/SimTrackManager.cc
  SimG4Core/Notification/src/TrackWithHistory.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41982 Run3-gex164X One more alternative suggestion for addressing RPC issue
  Geometry/MuonCommonData/data/rpcf/2021/v3/rpcf.xml
  Geometry/MuonCommonData/python/testExtendedGeometry2021XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41986 Online DQM: replace the hard-coded output directory name of event display clients with an input argument
  DQM/Integration/python/clients/visualization-live-secondInstance_cfg.py
  DQM/Integration/python/clients/visualization-live_cfg.py
  DQM/Integration/python/config/inputsource_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41993 EMTF muon shower unpacker update
  DataFormats/L1TMuon/interface/EMTF/ME.h
  DataFormats/L1TMuon/interface/EMTF/SP.h
  DataFormats/L1TMuon/interface/EMTFHit.h
  DataFormats/L1TMuon/src/EMTFHit.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockME.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockSP.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFUnpackerTools.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41972 Change L1 2023 Relval Single Jet Bits to Current Menu Bits
  DQM/L1TMonitor/python/L1TStage2uGTTiming_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42000 fix how `HLTDeDxFilter` fills `TriggerFilterObjectWithRefs` output product
  RecoTracker/DeDx/plugins/HLTDeDxFilter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, tracking

#42004 [13_0_X] EMTF muon shower unpacker update
  DataFormats/L1TMuon/interface/EMTF/ME.h
  DataFormats/L1TMuon/interface/EMTF/SP.h
  DataFormats/L1TMuon/interface/EMTFHit.h
  DataFormats/L1TMuon/src/EMTFHit.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockME.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockSP.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFUnpackerTools.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41999 Run3-gex164B Fix the bug in the RPC geometry - backport of the PRs #41907, #41921, #41990 from 13_2_X to 13_0_X
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021ZeroMaterial.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023ZeroMaterialXML_cfi.py
  Geometry/MuonCommonData/data/rpcf/2021/v2/rpcf.xml
  Geometry/RPCGeometryBuilder/src/RPCGeometryBuilder.cc
  Geometry/RPCGeometryBuilder/src/RPCGeometryParsFromDD.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#41992 [13.0.X] zeroed mono/stereo cluster counts in `SiStripMonitorTrack` at each event loop
  DQM/SiStripMonitorTrack/src/SiStripMonitorTrack.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#42008 Initialize values for all members of PixelBarrelValues
  DataFormats/TrackReco/test/testHitPattern.cpp
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#42019 Remove obsolete FinalStateReconOption from Herwig7 shower settings
  Configuration/Generator/python/Herwig7Settings/Herwig7LHEMG5aMCatNLOSettings_cfi.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42017 Fix `AlignmentStats` and `TkAlCaOverlapTagger`
  Alignment/CommonAlignmentMonitor/plugins/AlignmentStats.cc
  Alignment/CommonAlignmentMonitor/plugins/AlignmentStats.h
  Alignment/CommonAlignmentMonitor/test/BuildFile.xml
  Alignment/CommonAlignmentMonitor/test/testAlignmentStats.sh
  Alignment/CommonAlignmentMonitor/test/testAlignmentStats_cfg.py
  Alignment/TrackerAlignment/plugins/TkAlCaOverlapTagger.cc
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#41979 Improved *NumberingScheme code for Forward detectors
  SimG4CMS/Forward/interface/BHMNumberingScheme.h
  SimG4CMS/Forward/interface/BHMSD.h
  SimG4CMS/Forward/interface/BscNumberingScheme.h
  SimG4CMS/Forward/interface/BscSD.h
  SimG4CMS/Forward/interface/ZdcNumberingScheme.h
  SimG4CMS/Forward/interface/ZdcSD.h
  SimG4CMS/Forward/plugins/BscTest.cc
  SimG4CMS/Forward/plugins/ZdcTestAnalysis.cc
  SimG4CMS/Forward/src/BHMNumberingScheme.cc
  SimG4CMS/Forward/src/BHMSD.cc
  SimG4CMS/Forward/src/BscNumberingScheme.cc
  SimG4CMS/Forward/src/BscSD.cc
  SimG4CMS/Forward/src/ZdcNumberingScheme.cc
  SimG4CMS/Forward/src/ZdcSD.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41971 Add HI mixing wfs for 2023 MC
  Configuration/Generator/python/Pyquen_DiJet_pt80to120_5362GeV_cfi.py
  Configuration/Generator/python/Pyquen_GammaJet_pt20_5362GeV_cfi.py
  Configuration/Generator/python/Pyquen_ZeemumuJets_pt10_5362GeV_cfi.py
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: generators-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#42026 Make EZArrayFL and EZMgrFL compile with C++20
  Geometry/CaloGeometry/interface/EZArrayFL.h
  Geometry/CaloGeometry/interface/EZMgrFL.h
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#41662 MC Truth information for MTD
  Geometry/MTDGeometryBuilder/BuildFile.xml
  Geometry/MTDGeometryBuilder/interface/MTDGeomUtil.h
  Geometry/MTDGeometryBuilder/src/MTDGeomUtil.cc
  SimCalorimetry/Configuration/python/SimCalorimetry_EventContent_cff.py
  SimDataFormats/CaloAnalysis/BuildFile.xml
  SimDataFormats/CaloAnalysis/interface/CaloParticle.h
  SimDataFormats/CaloAnalysis/interface/MtdCaloParticle.h
  SimDataFormats/CaloAnalysis/interface/MtdCaloParticleFwd.h
  SimDataFormats/CaloAnalysis/interface/MtdSimCluster.h
  SimDataFormats/CaloAnalysis/interface/MtdSimClusterFwd.h
  SimDataFormats/CaloAnalysis/interface/MtdSimLayerCluster.h
  SimDataFormats/CaloAnalysis/interface/MtdSimLayerClusterFwd.h
  SimDataFormats/CaloAnalysis/interface/MtdSimTrackster.h
  SimDataFormats/CaloAnalysis/interface/MtdSimTracksterFwd.h
  SimDataFormats/CaloAnalysis/interface/SimCluster.h
  SimDataFormats/CaloAnalysis/src/MtdCaloParticle.cc
  SimDataFormats/CaloAnalysis/src/MtdSimCluster.cc
  SimDataFormats/CaloAnalysis/src/MtdSimLayerCluster.cc
  SimDataFormats/CaloAnalysis/src/MtdSimTrackster.cc
  SimDataFormats/CaloAnalysis/src/classes.h
  SimDataFormats/CaloAnalysis/src/classes_def.xml
  SimGeneral/CaloAnalysis/plugins/BuildFile.xml
  SimGeneral/CaloAnalysis/plugins/CaloTruthAccumulator.cc
  SimGeneral/CaloAnalysis/plugins/MtdTruthAccumulator.cc
  SimGeneral/MixingModule/interface/DecayGraph.h
  SimGeneral/MixingModule/python/digitizers_cfi.py
  SimGeneral/MixingModule/python/mtdTruthProducer_cfi.py
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#41997 Phase2-hgx340X Add a new scenario for a v17-like HGCal layout without the gaps
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2026D101Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D101_cff.py
  Configuration/Geometry/python/GeometryExtended2026D101Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D101_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D101.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D101XML_cfi.py
Labels: geometry-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#42020 Revert "Powheg+Vincia matching"
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
Labels: generators-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#42003 [13_1_X] EMTF muon shower unpacker update
  DataFormats/L1TMuon/interface/EMTF/ME.h
  DataFormats/L1TMuon/interface/EMTF/SP.h
  DataFormats/L1TMuon/interface/EMTFHit.h
  DataFormats/L1TMuon/src/EMTFHit.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockME.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockSP.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFUnpackerTools.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#41991 [13.1.X] zeroed mono/stereo cluster counts in `SiStripMonitorTrack` at each event loop
  DQM/SiStripMonitorTrack/src/SiStripMonitorTrack.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#42010 Fixed channel decoding for the timeout error in SiPixel RawToDigi
  EventFilter/SiPixelRawToDigi/interface/ErrorChecker.h
  EventFilter/SiPixelRawToDigi/src/ErrorChecker.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, trk

#42044 Revert "Remove SharedResources"
  GeneratorInterface/RivetInterface/interface/ParticleLevelProducer.h
  GeneratorInterface/RivetInterface/interface/RivetAnalyzer.h
  GeneratorInterface/RivetInterface/plugins/HTXSRivetProducer.cc
  GeneratorInterface/RivetInterface/plugins/ParticleLevelProducer.cc
  GeneratorInterface/RivetInterface/plugins/RivetAnalyzer.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42031 add specialized ZeroBias relval steps and use them for 2022 and 2023 data workflows, in order to employ `@rerecoZeroBias` DQM sequence
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#42027 Make EDAlias_t test to compile with C++20
  FWCore/Integration/test/EDAlias_t.cpp
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42015 Validation RecoEgamma h2_scl_EoEtrueVsrecOfflineVertices_Extended histogram correction
  Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42002 fix how `HLTDeDxFilter` fills `TriggerFilterObjectWithRefs` output product [`13_0_X`]
  RecoTracker/DeDx/plugins/HLTDeDxFilter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, tracking

#41492 Retrained L1 Tau Trigger Integration
  DataFormats/L1TParticleFlow/interface/PFTau.h
  DataFormats/L1TParticleFlow/interface/gt_datatypes.h
  DataFormats/L1TParticleFlow/interface/taus.h
  DataFormats/L1TParticleFlow/src/PFTau.cc
  DataFormats/L1TParticleFlow/src/classes_def.xml
  L1Trigger/Phase2L1ParticleFlow/interface/TauNNId.h
  L1Trigger/Phase2L1ParticleFlow/interface/taus/TauNNIdHW.h
  L1Trigger/Phase2L1ParticleFlow/interface/taus/weights/b1.h
  L1Trigger/Phase2L1ParticleFlow/interface/taus/weights/b2.h
  L1Trigger/Phase2L1ParticleFlow/interface/taus/weights/b3.h
  L1Trigger/Phase2L1ParticleFlow/interface/taus/weights/b4.h
  L1Trigger/Phase2L1ParticleFlow/interface/taus/weights/w1.h
  L1Trigger/Phase2L1ParticleFlow/interface/taus/weights/w2.h
  L1Trigger/Phase2L1ParticleFlow/interface/taus/weights/w3.h
  L1Trigger/Phase2L1ParticleFlow/interface/taus/weights/w4.h
  L1Trigger/Phase2L1ParticleFlow/plugins/L1NNTauProducer.cc
  L1Trigger/Phase2L1ParticleFlow/python/L1NNTauProducer_cff.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#42018 Backport of New definition of the DQM offline sequence to be run on Express strea…
  Configuration/StandardSequences/python/Harvesting_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, backport-ok

#42036 TH2Poly Tracker Maps
  CommonTools/TrackerMap/src/TrackerMap.cc
  DQM/SiStripMonitorClient/scripts/TH2PolyOfflineMaps.py
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#41946 Migrate Phase-2 geometry to D98
  Configuration/Geometry/README.md
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: geometry-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#42060 Changed 'type' to 'read_type' to avoid keyword class in UDP message
  Utilities/StorageFactory/src/StatisticsSenderService.cc
  Utilities/StorageFactory/test/test_file_statistics_sender.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42035 Add EMTF unconstrained pT and dxy to unpacked EMTFTrack collections
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFUnpackerTools.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42028 Make churn_allocator to compile with C++20
  TrackingTools/TrajectoryState/interface/ChurnAllocator.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#41607 Add prototype HcalNanoAOD
  Configuration/PyReleaseValidation/python/relval_production.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  DPGAnalysis/HcalNanoAOD/BuildFile.xml
  DPGAnalysis/HcalNanoAOD/README.md
  DPGAnalysis/HcalNanoAOD/interface/HFPreRecHitSortedTable.h
  DPGAnalysis/HcalNanoAOD/interface/HODigiSortedTable.h
  DPGAnalysis/HcalNanoAOD/interface/QIE10DigiSortedTable.h
  DPGAnalysis/HcalNanoAOD/interface/QIE11DigiSortedTable.h
  DPGAnalysis/HcalNanoAOD/plugins/BuildFile.xml
  DPGAnalysis/HcalNanoAOD/plugins/HcalDetIdTableProducer.cc
  DPGAnalysis/HcalNanoAOD/plugins/HcalDigiSortedTableProducer.cc
  DPGAnalysis/HcalNanoAOD/plugins/HcalRecHitTableProducer.cc
  DPGAnalysis/HcalNanoAOD/plugins/HcalUHTRTableProducer.cc
  DPGAnalysis/HcalNanoAOD/plugins/HcalUMNioTableProducer.cc
  DPGAnalysis/HcalNanoAOD/python/customiseHcalCalib_cff.py
  DPGAnalysis/HcalNanoAOD/python/customiseHcalLocal_cff.py
  DPGAnalysis/HcalNanoAOD/python/hcalDetIdTable_cff.py
  DPGAnalysis/HcalNanoAOD/python/hcalDigiSortedTable_cff.py
  DPGAnalysis/HcalNanoAOD/python/hcalNano_cff.py
  DPGAnalysis/HcalNanoAOD/python/hcalRecHitTable_cff.py
  DPGAnalysis/HcalNanoAOD/python/hcalUHTRTable_cff.py
  DPGAnalysis/HcalNanoAOD/python/hcalUMNioTable_cff.py
  DPGAnalysis/HcalNanoAOD/src/HFPreRecHitSortedTable.cc
  DPGAnalysis/HcalNanoAOD/src/HODigiSortedTable.cc
  DPGAnalysis/HcalNanoAOD/src/QIE10DigiSortedTable.cc
  DPGAnalysis/HcalNanoAOD/src/QIE11DigiSortedTable.cc
  DPGAnalysis/HcalNanoAOD/src/classes.h
  DPGAnalysis/HcalNanoAOD/src/classes_def.xml
  DPGAnalysis/HcalNanoAOD/test/testhcalnano_cfg.py
  DataFormats/HcalDetId/src/classes.h
  DataFormats/HcalDetId/src/classes_def.xml
Labels: simulation-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved, hcal

#42067 New DQM Offline sequence to be run on Express Stream 13_1_X
  Configuration/StandardSequences/python/Harvesting_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: dqm-pending, operations-approved, pending-signatures, tests-approved, orp-approved, backport-ok

#42030 Make ProcessRegistryImpl to compile with C++20
  PhysicsTools/MVAComputer/interface/ProcessRegistry.h
Labels: analysis-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#42073 Remove pessimizing std::move from ModuleHolder and OutputModuleCommunicatorT
  FWCore/Framework/interface/OutputModuleCommunicatorT.h
  FWCore/Framework/interface/maker/ModuleHolder.h
Labels: core-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#41815 Adding filter flag to SiStripApproximateClusters
  Configuration/StandardSequences/python/DigiToRaw_Repack_cff.py
  DataFormats/SiStripCluster/interface/SiStripApproximateCluster.h
  DataFormats/SiStripCluster/interface/SiStripCluster.h
  DataFormats/SiStripCluster/src/SiStripApproximateCluster.cc
  DataFormats/SiStripCluster/src/SiStripCluster.cc
  DataFormats/SiStripCluster/src/classes_def.xml
  DataFormats/SiStripCommon/interface/ConstantsForHardwareSystems.h
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalTracker/SiStripClusterizer/plugins/BuildFile.xml
  RecoLocalTracker/SiStripClusterizer/plugins/SiStripApprox2ApproxClusters.cc
  RecoLocalTracker/SiStripClusterizer/plugins/SiStripClusters2ApproxClusters.cc
  RecoLocalTracker/SiStripClusterizer/python/SiStripClusters2ApproxClusters_cff.py
  RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
  RecoTracker/IterativeTracking/python/TobTecStep_cff.py
  RecoTracker/PixelLowPtUtilities/interface/SlidingPeakFinder.h
  RecoTracker/PixelLowPtUtilities/src/StripSubClusterShapeTrajectoryFilter.cc
Labels: hlt-approved, operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking, trk

#42068 add timestamp dates in human readable form in the BeamSpot `DisplayParameters` template class
  CondCore/BeamSpotPlugins/interface/BeamSpotPayloadInspectorHelper.h
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, tracking

#42012 APE measurement tool: Resolved python3 compatibility issues, added unit test functionality, removed dependency on other package
  Alignment/APEEstimation/python/ApeEstimator_cfi.py
  Alignment/APEEstimation/python/samples/MC_UnitTest_TkAlMuonIsolated_cff.py
  Alignment/APEEstimation/scripts/initialise.bash
  Alignment/APEEstimation/test/BuildFile.xml
  Alignment/APEEstimation/test/SkimProducer/skimProducer_cfg.py
  Alignment/APEEstimation/test/SkimProducer/startSkim.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitter.py
  Alignment/APEEstimation/test/autoSubmitter/autoSubmitterTemplates.py
  Alignment/APEEstimation/test/autoSubmitter/helpers.py
  Alignment/APEEstimation/test/autoSubmitter/unitTest.ini
  Alignment/APEEstimation/test/testApeestimatorSummary_cfg.py
  Alignment/APEEstimation/test/testApeestimator_cfg.py
  Alignment/APEEstimation/test/trackerTreeGenerator_cfg.py
  Alignment/APEEstimation/test/unitTest.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#41901 Prevent copy construction of `TrackerGeometry`
  Geometry/TrackerGeometryBuilder/interface/TrackerGeometry.h
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#42047 [Bug-fix] Add NANOAOD output to RECONANORUN3 step
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#42069 addition of 2023C WFs and modifications 2023B WFs to run with era Run3
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#42080 Phase2-hgx341C Second step to go toward the V18 version of HGCal geometry which involve nonzero cassette shifts
  Geometry/HGCalCommonData/data/hgcalEE/v18/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v18/hgcalHEsil.xml
  Geometry/HGCalCommonData/data/hgcalPassive/v18/hgcalPassive.xml
  Geometry/HGCalCommonData/plugins/DDHGCalPassiveFull.cc
  Geometry/HGCalCommonData/plugins/DDHGCalPassivePartial.cc
  Geometry/HGCalCommonData/plugins/DDHGCalSiliconRotatedCassette.cc
  Geometry/HGCalCommonData/python/testHGCV16XML_cfi.py
  Geometry/HGCalCommonData/python/testHGCV17XML_cfi.py
  Geometry/HGCalCommonData/python/testHGCV17nXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalV16XML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalV17ShiftXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalV17XML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalV17nXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalV17ngXML_cfi.py
  Geometry/HGCalCommonData/python/testHGCalV18XML_cfi.py
  Geometry/HGCalCommonData/test/python/g4OverlapCheck_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#42046 Phase2-gex165 Remove the BSC detector from the description of all phase2 scenarios
  Configuration/Geometry/python/GeometryDD4hepExtended2026D100Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D101Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D86Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D88Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D91Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D92Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D93Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D95Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D96Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D97Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D98Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D99Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D100Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D101Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D86Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D88Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D91Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D92Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D93Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D95Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D96Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D97Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D98Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D99Reco_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D100.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D101.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D86.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D88.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D91.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D92.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D93.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D95.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D96.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D97.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D98.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D99.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D100XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D101XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D86XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D88XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D91XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D92XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D93XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D95XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D96XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D97XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D98XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D99XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#41977 ECAL - Add integrity checks for strip and xtal ids to GPU unpacker
  EventFilter/EcalRawToDigi/plugins/UnpackGPU.cu
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, ecal

#42033 [13.0.X] Fixed channel decoding for the timeout error in SiPixel RawToDigi
  EventFilter/SiPixelRawToDigi/interface/ErrorChecker.h
  EventFilter/SiPixelRawToDigi/src/ErrorChecker.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, trk

#42034 [13.1.X] Fixed channel decoding for the timeout error in SiPixel RawToDigi
  EventFilter/SiPixelRawToDigi/interface/ErrorChecker.h
  EventFilter/SiPixelRawToDigi/src/ErrorChecker.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#42062 [13.1.X] add specialized ZeroBias relval steps and use them for 2022 data workflows, in order to employ `@rerecoZeroBias` DQM sequence
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#42063 [13.0.X] add specialized ZeroBias relval steps and use them for 2022 data workflows, in order to employ `@rerecoZeroBias` DQM sequence
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#41970 Recovery of missing hits for Strip Hit Efficiency
  CalibTracker/SiStripHitEfficiency/plugins/HitEff.cc
  CalibTracker/SiStripHitEfficiency/plugins/HitEff.h
  CalibTracker/SiStripHitEfficiency/python/SiStripHitEff_cff.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#42065 Making a new Secondary Dataset ReserveDMu
  Configuration/Skimming/python/PDWG_ReserveDMu_SD_cff.py
  Configuration/Skimming/python/Skims_PDWG_cff.py
  Configuration/Skimming/python/autoSkim.py
  Configuration/Skimming/test/test_ReserveDMu_SD_cfg.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved
