Repository cms-sw/cmssw, pull requests merged in 2023-09, with the labels that each got.

#42634 L1T ZDC and uGT Emulator to CMSSW_13_3_X
  DataFormats/L1TGlobal/interface/GlobalObject.h
  DataFormats/L1TGlobal/src/GlobalObject.cc
  DataFormats/L1Trigger/interface/EtSum.h
  L1Trigger/L1TCalorimeter/interface/CaloParamsHelper.h
  L1Trigger/L1TCalorimeter/plugins/L1TCaloStage2ParamsESProducer.cc
  L1Trigger/L1TCalorimeter/python/caloParams_cfi.py
  L1Trigger/L1TGlobal/interface/EnergySumZdcCondition.h
  L1Trigger/L1TGlobal/interface/EnergySumZdcTemplate.h
  L1Trigger/L1TGlobal/interface/GlobalBoard.h
  L1Trigger/L1TGlobal/interface/GlobalDefinitions.h
  L1Trigger/L1TGlobal/interface/TriggerMenu.h
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.h
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.h
  L1Trigger/L1TGlobal/python/simGtStage2Digis_cfi.py
  L1Trigger/L1TGlobal/src/EnergySumCondition.cc
  L1Trigger/L1TGlobal/src/EnergySumZdcCondition.cc
  L1Trigger/L1TGlobal/src/EnergySumZdcTemplate.cc
  L1Trigger/L1TGlobal/src/GlobalBoard.cc
  L1Trigger/L1TGlobal/src/GlobalCondition.cc
  L1Trigger/L1TGlobal/src/GlobalDefinitions.cc
  L1Trigger/L1TGlobal/src/TriggerMenu.cc
  L1Trigger/L1TGlobal/src/classes_def.xml
  L1Trigger/L1TNtuples/interface/L1AnalysisL1Upgrade.h
  L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeDataFormat.h
  L1Trigger/L1TNtuples/plugins/L1UpgradeTreeProducer.cc
  L1Trigger/L1TNtuples/python/L1NtupleEMU_cff.py
  L1Trigger/L1TNtuples/python/L1NtupleRAW_cff.py
  L1Trigger/L1TNtuples/python/l1UpgradeTree_cfi.py
  L1Trigger/L1TNtuples/src/L1AnalysisL1Upgrade.cc
  L1Trigger/L1TZDC/BuildFile.xml
  L1Trigger/L1TZDC/README.md
  L1Trigger/L1TZDC/plugins/BuildFile.xml
  L1Trigger/L1TZDC/plugins/L1TZDCAnalyzer.cc
  L1Trigger/L1TZDC/plugins/L1TZDCProducer.cc
  L1Trigger/L1TZDC/test/createLUT.C
  L1Trigger/L1TZDC/test/l1ZDCProducerTest.py
  L1Trigger/L1TZDC/test/runEmulator-ZDC.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#42675 make `trigger::TriggerEvent::filterLabel` return `std::string_view`
  Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalIsotrkProducer.cc
  DataFormats/HLTReco/interface/TriggerEvent.h
  PhysicsTools/PatAlgos/plugins/PATTriggerProducer.cc
Labels: alca-approved, hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#42682 revert DeepMET TensorFlow workaround
  RecoMET/METPUSubtraction/plugins/DeepMETProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#42689 Phase2-TB72 Try to complete a simulation version for the HGCal TB setup of August 2023
  Geometry/HGCalTBCommonData/data/TB230/Jul230/cms.xml
  Geometry/HGCalTBCommonData/data/TB230/Jul230/hgcal.xml
  Geometry/HGCalTBCommonData/data/TB230/Jul230/hgcalBeam.xml
  Geometry/HGCalTBCommonData/data/TB230/Jul230/hgcalEE.xml
  Geometry/HGCalTBCommonData/data/TB230/Jul230/hgcalwafer.xml
  Geometry/HGCalTBCommonData/python/testTB230JulXML_cfi.py
  Geometry/HGCalTBCommonData/test/python/g4OverlapCheck_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42691 Phase2-TB73 Update the cfg files for the old TB runs of HGCal
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN170_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1PC1mm_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1el100_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct2_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct3_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct4_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimCERNMB_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimCERN_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimDigiReco_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimDigi_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimMBNew_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimMB_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBTimingGenSim_cfg.py
  SimG4CMS/HGCalTestBeam/test/runTBAnalCERN181Oct1_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#42647 Moved creating SiPixelTemplateStore from DB to an ESProducer [13_1]
  Alignment/OfflineValidation/python/TkAlAllInOneTool/JetHT_cfg.py
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLWorker.cc
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiPixelLorentzAngleMCS_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiPixelLorentzAngle_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiStripGainsAAG_cff.py
  CondFormats/SiPixelTransient/src/T_EventSetup_SiPixelTemplateStore.cc
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OfflineDQM_source_cff.py
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_Timing_cff.py
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_cff.py
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1TrackClusters.cc
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/SiStrip_OfflineMonitoring_cff.py
  FastSimulation/Configuration/python/Reconstruction_BefMix_cff.py
  FastSimulation/TrackingRecHitProducer/interface/PixelTemplateSmearerBase.h
  FastSimulation/TrackingRecHitProducer/interface/TrackingRecHitAlgorithm.h
  FastSimulation/TrackingRecHitProducer/plugins/TrackingRecHitProducer.cc
  FastSimulation/TrackingRecHitProducer/src/PixelTemplateSmearerBase.cc
  FastSimulation/TrackingRecHitProducer/src/TrackingRecHitAlgorithm.cc
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoHI/HiTracking/python/HighPtTracking_PbPb_cff.py
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEClusterRepair.h
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPETemplateReco.h
  RecoLocalTracker/SiPixelRecHits/plugins/BuildFile.xml
  RecoLocalTracker/SiPixelRecHits/plugins/PixelCPEClusterRepairESProducer.cc
  RecoLocalTracker/SiPixelRecHits/plugins/PixelCPETemplateRecoESProducer.cc
  RecoLocalTracker/SiPixelRecHits/plugins/SiPixelTemplateStoreESProducer.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPETemplateReco.cc
  RecoTracker/FinalTrackSelectors/python/MergeTrackCollections_cff.py
  RecoTracker/TrackProducer/test/refitFromAOD.py
  RecoTracker/TrackProducer/test/refitFromMINIAOD.py
  RecoTracker/TransientTrackingRecHit/python/TTRHBuilders_cff.py
Labels: alca-approved, dqm-approved, fastsim-approved, hlt-approved, reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, backport-ok, tracking, trk

#42648 Moved creating SiPixelTemplateStore from DB to an ESProducer [13_0]
  Alignment/OfflineValidation/python/TkAlAllInOneTool/JetHT_cfg.py
  CalibTracker/SiPixelLorentzAngle/src/SiPixelLorentzAnglePCLWorker.cc
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiPixelLorentzAngleMCS_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiPixelLorentzAngle_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiStripGainsAAG_cff.py
  CondFormats/SiPixelTransient/src/T_EventSetup_SiPixelTemplateStore.cc
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OfflineDQM_source_cff.py
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_Timing_cff.py
  DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_cff.py
  DQM/SiPixelPhase1Track/plugins/SiPixelPhase1TrackClusters.cc
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/SiStrip_OfflineMonitoring_cff.py
  FastSimulation/Configuration/python/Reconstruction_BefMix_cff.py
  FastSimulation/TrackingRecHitProducer/interface/PixelTemplateSmearerBase.h
  FastSimulation/TrackingRecHitProducer/interface/TrackingRecHitAlgorithm.h
  FastSimulation/TrackingRecHitProducer/plugins/TrackingRecHitProducer.cc
  FastSimulation/TrackingRecHitProducer/src/PixelTemplateSmearerBase.cc
  FastSimulation/TrackingRecHitProducer/src/TrackingRecHitAlgorithm.cc
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoHI/HiTracking/python/HighPtTracking_PbPb_cff.py
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEClusterRepair.h
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPETemplateReco.h
  RecoLocalTracker/SiPixelRecHits/plugins/BuildFile.xml
  RecoLocalTracker/SiPixelRecHits/plugins/PixelCPEClusterRepairESProducer.cc
  RecoLocalTracker/SiPixelRecHits/plugins/PixelCPETemplateRecoESProducer.cc
  RecoLocalTracker/SiPixelRecHits/plugins/SiPixelTemplateStoreESProducer.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc
  RecoLocalTracker/SiPixelRecHits/src/PixelCPETemplateReco.cc
  RecoTracker/FinalTrackSelectors/python/MergeTrackCollections_cff.py
  RecoTracker/TrackProducer/test/refitFromAOD.py
  RecoTracker/TrackProducer/test/refitFromMINIAOD.py
  RecoTracker/TransientTrackingRecHit/python/TTRHBuilders_cff.py
Labels: alca-approved, dqm-approved, fastsim-approved, hlt-approved, reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, backport-ok, tracking, trk

#42693 [13.1.X] add information on first hit from HitPattern to LostTracks
  PhysicsTools/PatAlgos/plugins/PATLostTracks.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved, tracking

#42688 [13.2.X] add information on first hit from HitPattern to LostTracks
  PhysicsTools/PatAlgos/plugins/PATLostTracks.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved, tracking

#42706 L1T ZDC and uGT Emulator Backport
  DataFormats/L1TGlobal/interface/GlobalObject.h
  DataFormats/L1TGlobal/src/GlobalObject.cc
  DataFormats/L1Trigger/interface/EtSum.h
  L1Trigger/L1TCalorimeter/interface/CaloParamsHelper.h
  L1Trigger/L1TCalorimeter/plugins/L1TCaloStage2ParamsESProducer.cc
  L1Trigger/L1TCalorimeter/python/caloParams_cfi.py
  L1Trigger/L1TGlobal/interface/EnergySumZdcCondition.h
  L1Trigger/L1TGlobal/interface/EnergySumZdcTemplate.h
  L1Trigger/L1TGlobal/interface/GlobalBoard.h
  L1Trigger/L1TGlobal/interface/GlobalDefinitions.h
  L1Trigger/L1TGlobal/interface/TriggerMenu.h
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.h
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.h
  L1Trigger/L1TGlobal/python/simGtStage2Digis_cfi.py
  L1Trigger/L1TGlobal/src/EnergySumCondition.cc
  L1Trigger/L1TGlobal/src/EnergySumZdcCondition.cc
  L1Trigger/L1TGlobal/src/EnergySumZdcTemplate.cc
  L1Trigger/L1TGlobal/src/GlobalBoard.cc
  L1Trigger/L1TGlobal/src/GlobalCondition.cc
  L1Trigger/L1TGlobal/src/GlobalDefinitions.cc
  L1Trigger/L1TGlobal/src/TriggerMenu.cc
  L1Trigger/L1TGlobal/src/classes_def.xml
  L1Trigger/L1TNtuples/interface/L1AnalysisL1Upgrade.h
  L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeDataFormat.h
  L1Trigger/L1TNtuples/plugins/L1UpgradeTreeProducer.cc
  L1Trigger/L1TNtuples/python/L1NtupleEMU_cff.py
  L1Trigger/L1TNtuples/python/L1NtupleRAW_cff.py
  L1Trigger/L1TNtuples/python/l1UpgradeTree_cfi.py
  L1Trigger/L1TNtuples/src/L1AnalysisL1Upgrade.cc
  L1Trigger/L1TZDC/BuildFile.xml
  L1Trigger/L1TZDC/README.md
  L1Trigger/L1TZDC/plugins/BuildFile.xml
  L1Trigger/L1TZDC/plugins/L1TZDCAnalyzer.cc
  L1Trigger/L1TZDC/plugins/L1TZDCProducer.cc
  L1Trigger/L1TZDC/test/createLUT.C
  L1Trigger/L1TZDC/test/l1ZDCProducerTest.py
  L1Trigger/L1TZDC/test/runEmulator-ZDC.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external, backport-ok

#42707 add support for L1T `EtSum`s of type `kZDC{P,M}` as trigger objects at HLT
  DataFormats/HLTReco/interface/TriggerTypeDefs.h
  HLTrigger/HLTfilters/plugins/HLTL1TSeed.cc
  HLTrigger/HLTfilters/plugins/HLTL1TSeed.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#42708 add support for L1T `EtSum`s of type `kZDC{P,M}` as trigger objects at HLT [`13_2_X`]
  DataFormats/HLTReco/interface/TriggerTypeDefs.h
  HLTrigger/HLTfilters/plugins/HLTL1TSeed.cc
  HLTrigger/HLTfilters/plugins/HLTL1TSeed.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, urgent, backport, requires-external

#42255 Add 4 Isolation variables for Photon to NanoAOD
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, egamma

#42670 [NanoAOD] Fix typos in jetsAK4 CHS and Puppi tables
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_CHS_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_Puppi_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#42677 [13_3_X] remove duplicate monitoring of FB at layer1 data-emulator workspace
  DQM/L1TMonitor/src/L1TdeStage2CaloLayer1.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, hcal, l1t

#42692 Phase2-TB74 Enable Simulation Runs for 6 inch wafers as well
  Geometry/HGCalTBCommonData/python/hgcalParametersInitialization_cfi.py
  SimG4CMS/Calo/BuildFile.xml
  SimG4CMS/Calo/interface/HGCNumberingScheme.h
  SimG4CMS/Calo/interface/HGCSD.h
  SimG4CMS/Calo/plugins/BuildFile.xml
  SimG4CMS/Calo/plugins/HGCSensitiveDetectorBuilder.cc
  SimG4CMS/Calo/src/HGCNumberingScheme.cc
  SimG4CMS/Calo/src/HGCSD.cc
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1_cfg.py
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#42696 Phase2-hgx345 Modify HGCMouseBite such that it can work for both standard HGCal as well as for TB setups with 6 inch wafers
  SimG4CMS/Calo/interface/HGCMouseBite.h
  SimG4CMS/Calo/src/HGCMouseBite.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42697 Add v0_4_1 HI caloParams with updated centrality trigger thresholds
  L1Trigger/Configuration/python/customiseSettings.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2023_v0_4_1_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42705 Name change of jetCalibrationLUTFile
  L1Trigger/L1TCalorimeter/python/caloParams_2023_v0_4_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42701 Update 2023 MC GTs - 13_3_X
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#42690 Replace the access to track reference with a more robust approach
  RecoEgamma/EgammaElectronProducers/plugins/LowPtGSFToTrackLinker.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42678 [13_1_X] remove duplicate monitoring of FB at layer1 data-emulator workspace
  DQM/L1TMonitor/src/L1TdeStage2CaloLayer1.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, hcal, l1t

#42683 [13.2.X] Introduce PCL-like workflows for SiStrip Lorentz Angle Monitoring (and potentially calibration)
  CalibTracker/SiStripLorentzAngle/interface/SiStripLorentzAngleCalibrationHelpers.h
  CalibTracker/SiStripLorentzAngle/interface/SiStripLorentzAngleCalibrationStruct.h
  CalibTracker/SiStripLorentzAngle/plugins/BuildFile.xml
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLorentzAnglePCLHarvester.cc
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLorentzAnglePCLMonitor.cc
  CalibTracker/SiStripLorentzAngle/python/SiStripLorentzAnglePCLHarvester_cfi.py
  CalibTracker/SiStripLorentzAngle/python/SiStripLorentzAnglePCLMonitor_cfi.py
  CalibTracker/SiStripLorentzAngle/test/step_PromptCalibProdSiStripLA_ALCAHARVEST_cfg.py
  CalibTracker/SiStripLorentzAngle/test/step_PromptCalibProdSiStripLA_cfg.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiStripLorentzAngle_Output_cff.py
  Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiStripLorentzAngle_cff.py
  Calibration/TkAlCaRecoProducers/python/AlcaSiStripLorentzAngleHarvester_cff.py
  Calibration/TkAlCaRecoProducers/python/AlcaSiStripLorentzAngleHarvester_cfi.py
  Calibration/TkAlCaRecoProducers/test/parseFwkJobReport.py
  Calibration/TkAlCaRecoProducers/test/testPCLAlCaHarvesting.py
  CondFormats/Common/data/SiStripLorentzAngleRcd_multirun_prep.json
  CondFormats/Common/data/SiStripLorentzAngleRcd_multirun_prod.json
  CondFormats/Common/data/SiStripLorentzAngleRcd_prep.json
  CondFormats/Common/data/SiStripLorentzAngleRcd_prod.json
  CondFormats/Common/test/DropBoxMetadataReader.py
  CondFormats/Common/test/ProduceDropBoxMetadata.py
  Configuration/AlCa/python/autoAlca.py
  Configuration/AlCa/python/autoPCL.py
  Configuration/EventContent/python/AlCaRecoOutput_cff.py
  Configuration/PyReleaseValidation/python/relval_production.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/AlCaHarvesting_cff.py
  Configuration/StandardSequences/python/AlCaRecoStreams_cff.py
Labels: alca-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, db-approved, orp-approved, urgent, upgrade-approved, backport-ok, trk

#42679 [13_2_X] remove duplicate monitoring of FB at layer1 data-emulator workspace
  DQM/L1TMonitor/src/L1TdeStage2CaloLayer1.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, hcal, l1t

#42702 Update 2023 MC GTs - 13_2_X
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved

#42703 Update 2023 MC GTs - 13_1_X
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved

#42694 [13.0.X] add information on first hit from HitPattern to LostTracks
  PhysicsTools/PatAlgos/plugins/PATLostTracks.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved, tracking

#42710 [13_0_X] Fix typos in jetsAK4 CHS and Puppi tables
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_CHS_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_Puppi_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#42631 [13.2.X] Fixed channel decoding for the timeout error in SiPixelRawToClusterGPUKernel
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, trk

#42673 Herwig lhe matching fix (including multithreading fixes)
  Configuration/Generator/python/DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7_cff.py
  Configuration/Generator/python/DYToLL012Jets_5FS_TuneCH3_13TeV_amcatnloFxFx_herwig7_cff.py
  Configuration/Generator/python/DYToll01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff.py
  Configuration/Generator/python/Herwig7Settings/Herwig7LHECommonSettings_cfi.py
  Configuration/Generator/python/Herwig7Settings/Herwig7MGMergingSettings_cfi.py
  Configuration/Generator/python/TT_13TeV_Pow_Herwig7_cff.py
  Configuration/Generator/python/TTbar_Pow_LHE_13TeV_cff.py
  GeneratorInterface/Herwig7Interface/plugins/Herwig7Hadronizer.cc
  GeneratorInterface/LHEInterface/interface/LHEEvent.h
  GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc
  GeneratorInterface/LHEInterface/scripts/addLHEnumbers.py
  GeneratorInterface/LHEInterface/scripts/mergeLHE.py
  GeneratorInterface/LHEInterface/src/LHEEvent.cc
  GeneratorInterface/LHEInterface/src/LHEReader.cc
  SimDataFormats/GeneratorProducts/interface/LHEEventProduct.h
  SimDataFormats/GeneratorProducts/src/classes_def.xml
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#42704 [13_2_X] Port of 2022 and 2023 HI L1T CaloParams
  L1Trigger/Configuration/python/customiseSettings.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2022_v0_2_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2022_v0_3_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2022_v0_4_1_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2022_v0_4_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2022_v0_5_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2022_v0_6_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2023_v0_3_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2023_v0_4_cfi.py
  L1Trigger/L1TCalorimeter/python/caloParams_2023_v0_4_ppRef_cfi.py
Labels: l1-pending, pending-signatures, tests-started, orp-approved, backport-ok

#42722 miscellaneous code improvements from review of #42683
  CalibTracker/SiStripLorentzAngle/interface/SiStripLorentzAngleCalibrationHelpers.h
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLorentzAnglePCLHarvester.cc
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLorentzAnglePCLMonitor.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#42726 Fall17V2 Electron IDs and Isolations saved only in Run2
  PhysicsTools/NanoAOD/python/electrons_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#42717 [13_0_X backport ] Fall17V2 photon IDs and Isolations saved only in Run2 Nanos
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#42712 Update PbPb skims for 2023
  Configuration/Skimming/python/PbPb_EMuSkim_cff.py
  Configuration/Skimming/python/PbPb_ZEESkim_cff.py
  Configuration/Skimming/python/PbPb_ZMMSkim_cff.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#41011 Adding all geometries and the FullRecoGPU for Patatrack wfs for Phase2
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#42724 Apply ld fix for AllocMonitor to sl7 as well
  PerfTools/AllocMonitorPreload/src/memory_proxies.cc
Labels: core-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#42736 `ConfigureAlignmentProducer`: add mass constraint for `ALCARECOTkAlJpsiMuMu`
  Alignment/MillePedeAlignmentAlgorithm/python/alignmentsetup/ConfigureAlignmentProducer.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#41964 Remove obsolete Scouting Data Format unit tests
  DataFormats/Scouting/test/BuildFile.xml
  DataFormats/Scouting/test/scoutingCollectionsDumper.py
  DataFormats/Scouting/test/scoutingCollectionsIO_cfg.py
  DataFormats/Scouting/test/testDataFormatsScoutingRun2.sh
  DataFormats/Scouting/test/testDataFormatsScoutingRun2_expected.log
  DataFormats/Scouting/test/testDataFormatsScoutingRun3.sh
  DataFormats/Scouting/test/testDataFormatsScoutingRun3_expected.log
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42658 [13_0_X] remove duplicate monitoring of FB at layer1 data-emulator workspace
  DQM/L1TMonitor/src/L1TdeStage2CaloLayer1.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, hcal, l1t

#42718 Phase2-tb75 Enable the analysis code for HGCal TB for 6-inch wafer to run properly
  SimG4CMS/Calo/src/HGCSD.cc
  SimG4CMS/HGCalTestBeam/plugins/HGCalTBAnalyzer.cc
  SimG4CMS/HGCalTestBeam/plugins/HGCalTimingAnalyzer.cc
  SimG4CMS/HGCalTestBeam/test/HGCalTBCERN181Oct1_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimDigiReco_cfg.py
  SimG4CMS/HGCalTestBeam/test/HGCalTBGenSimDigi_cfg.py
  SimG4CMS/HGCalTestBeam/test/runTBAnalCERN181Oct1_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#42687 Fixes and modifications on GEM TnP efficiency plots (backport of #42639, 13_2_X)
  DQMOffline/MuonDPG/plugins/GEMTnPEfficiencyTask.cc
  DQMOffline/MuonDPG/python/gemTnPEfficiencyClient_cfi.py
  TrackingTools/TrackAssociator/src/TrackDetectorAssociator.cc
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, tracking, muon

#42686 Fixes and modifications on GEM TnP efficiency plots (backport of #42639, 13_1_X)
  DQMOffline/MuonDPG/plugins/GEMTnPEfficiencyTask.cc
  DQMOffline/MuonDPG/python/gemTnPEfficiencyClient_cfi.py
  TrackingTools/TrackAssociator/src/TrackDetectorAssociator.cc
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, tracking, muon

#42685 Fixes and modifications on GEM TnP efficiency plots (backport of #42639, 13_0_X)
  DQMOffline/MuonDPG/plugins/GEMTnPEfficiencyTask.cc
  DQMOffline/MuonDPG/python/gemTnPEfficiencyClient_cfi.py
  TrackingTools/TrackAssociator/src/TrackDetectorAssociator.cc
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, tracking, muon

#42730 [13_0_X backport] Fall17V2 Electron IDs and Isolations saved only in Run2 Nanos
  PhysicsTools/NanoAOD/python/electrons_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#42735 Update PbPb skims for 2023
  Configuration/Skimming/python/PbPb_EMuSkim_cff.py
  Configuration/Skimming/python/PbPb_ZEESkim_cff.py
  Configuration/Skimming/python/PbPb_ZMMSkim_cff.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, backport-ok

#42645 Phase 2 GT: Add missing GMTTkMuons instance name
  L1Trigger/Phase2L1GT/python/l1tGTProducer_cff.py
Labels: l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#42643 L1T Phase-2 Correlator Layer 1 updates for Multiboard tests
  L1Trigger/Phase2L1ParticleFlow/interface/L1TCorrelatorLayer1PatternFileWriter.h
  L1Trigger/Phase2L1ParticleFlow/interface/egamma/pfeginput_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/egamma/pftkegalgo_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/egamma/pftkegsorter_barrel_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/egamma/pftkegsorter_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/l1-converters/hgcalinput_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/l1-converters/muonGmtToL1ct_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/l1-converters/tkinput_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/pf/pfalgo2hgc_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/pf/pfalgo3_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/pf/pfalgo_common_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/pf/pfalgo_dummy_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/puppi/linpuppi_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/regionizer/buffered_folded_multififo_regionizer_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/regionizer/multififo_regionizer_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/regionizer/regionizer_base_ref.h
  L1Trigger/Phase2L1ParticleFlow/interface/regionizer/tdr_regionizer_ref.h
  L1Trigger/Phase2L1ParticleFlow/plugins/L1CTJetFileWriter.cc
  L1Trigger/Phase2L1ParticleFlow/plugins/L1TCorrelatorLayer1Producer.cc
  L1Trigger/Phase2L1ParticleFlow/plugins/L1TEGMultiMerger.cc
  L1Trigger/Phase2L1ParticleFlow/plugins/L1TPFCandMultiMerger.cc
  L1Trigger/Phase2L1ParticleFlow/python/l1ctLayer1_cff.py
  L1Trigger/Phase2L1ParticleFlow/python/l1ctLayer1_patternWriters_cff.py
  L1Trigger/Phase2L1ParticleFlow/python/l1tJetFileWriter_cfi.py
  L1Trigger/Phase2L1ParticleFlow/src/L1TCorrelatorLayer1PatternFileWriter.cc
  L1Trigger/Phase2L1ParticleFlow/src/egamma/pfeginput_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/egamma/pftkegalgo_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/l1-converters/hgcalinputt_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/l1-converters/muonGmtToL1ct_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/l1-converters/tkinput_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/pf/pfalgo2hgc_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/pf/pfalgo3_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/pf/pfalgo_common_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/pf/pfalgo_dummy_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/puppi/linpuppi_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/regionizer/buffered_folded_multififo_regionizer_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/regionizer/multififo_regionizer_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/regionizer/regionizer_base_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/src/regionizer/tdr_regionizer_ref.cpp
  L1Trigger/Phase2L1ParticleFlow/test/.gitignore
  L1Trigger/Phase2L1ParticleFlow/test/make_l1ct_binaryFiles_cfg.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#42588 Add 2023 WFs in runTheMatrix for tests
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#42749 remove `std::cout` calls in `TriggerMenuParser::parseEnergySumZdc`
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42752 check for empty collection in SiStripApproximateClusterCollection
  DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, trk

#42763 Change from numberOfMatches() to segment number in DisplacedMuonFilterProducer
  PhysicsTools/PatAlgos/plugins/DisplacedMuonFilterProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved, muon

#42744 update input collections of `pixelgpu` online-DQM client for HI mode
  DQM/Integration/python/clients/pixelgpu_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#42753 update input collections of `pixelgpu` online-DQM client for HI mode [`13_2_X`]
  DQM/Integration/python/clients/pixelgpu_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent, backport

#42646 Add mu beamspot constrained pT. Increase mu eta and phi precision to 16 bits
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  RecoMuon/GlobalTrackingTools/plugins/BuildFile.xml
  RecoMuon/GlobalTrackingTools/plugins/MuonBeamspotConstraintValueMapProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, muon

#42761 Update 2022 MC GTs for new ecal timing calibrations
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42748 MTD code: add debugging statements, clean ETL validation for obsolete one-disk scenario
  RecoMTD/TrackExtender/plugins/TrackExtenderWithMTD.cc
  SimFastTiming/FastTimingCommon/src/ETLDeviceSim.cc
  Validation/MtdValidation/plugins/EtlDigiHitsValidation.cc
  Validation/MtdValidation/plugins/EtlLocalRecoValidation.cc
  Validation/MtdValidation/plugins/EtlSimHitsValidation.cc
  Validation/MtdValidation/plugins/MtdTracksValidation.cc
Labels: dqm-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#42713 Update GPU workflows
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#42774 Changed FailPath/SkipEvent to TryToContinue [HLT]
  HLTrigger/Configuration/python/HLT_75e33/psets/options_cfi.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42767 Changed FailPath/SkipEvent to TryToContinue [RECO]
  RecoLocalCalo/EcalRecProducers/test/ecalRawDecodingAndMultifit.py
  RecoLocalCalo/EcalRecProducers/test/testEcalRechitProducer_cfg.py
  RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRecHitPhase2WeightsProducer.py
  RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRecHitPhase2WeightsProducerGPU.py
  RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRecHitPhase2WeightsProducerGPU_harvesting.py
  RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRechitProducerWithCC_cfg.py
  RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRechitProducer_cfg.py
  RecoTauTag/HLTProducers/test/testL2TauTagNN.py
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42765 Changed FailPath/SkipEvent to TryToContinue [Sim]
  SimG4CMS/Calo/test/python/Gen_MinBias.py
  SimG4CMS/Calo/test/python/Gen_SingleMuon.py
  SimG4CMS/Calo/test/python/dd4hep_SingleMuon_Step1_cfg.py
  SimG4CMS/Calo/test/python/ddd_SingleMuon_Step1_cfg.py
  SimG4CMS/Calo/test/python/run2018Step1_cfg.py
  SimG4CMS/Calo/test/python/runHFDD4HEP_cfg.py
  SimG4CMS/Calo/test/python/runHFDDD_cfg.py
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step2_cfg.py
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step3_cfg.py
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step4_cfg.py
  SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step5_cfg.py
  SimG4Core/Configuration/test/dd4hep_ttbar_2026D77_Step1_cfg.py
  SimG4Core/Configuration/test/dd4hep_ttbar_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step1_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step2_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step3_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step4_cfg.py
  SimG4Core/Configuration/test/ddd_ZMM_Run3_Step5_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42738 Fix compilation warning in SensitiveDetectorCatalog.cc
  SimG4Core/Geometry/src/SensitiveDetectorCatalog.cc
Labels: simulation-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved

#42731 motherID_correction_V1 : python part
  Validation/RecoEgamma/python/ElectronMcSignalValidatorPt1000_gedGsfElectrons_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidator_gedGsfElectrons_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42714 Update GPU workflows [13.2.x]
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, requires-external, backport-ok

#42612 Disentangle Phase-2 pixel Digitization and Reconstruction from Phase-1 conditions
  HLTrigger/Configuration/python/HLT_75e33/modules/MeasurementTrackerEvent_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/siPixelClusters_cfi.py
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.h
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelClusterProducer.cc
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerESProducer.cc
  RecoTracker/MeasurementDet/python/MeasurementTrackerEventProducer_cfi.py
  SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.h
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.cc
  SimTracker/SiPhase2Digitizer/plugins/PixelDigitizerAlgorithm.h
Labels: hlt-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, tracking, trk

#42246 [HGCAL trigger] Module splitting and updated seeding normalization
  DataFormats/ForwardDetId/interface/HGCalTriggerModuleDetId.h
  DataFormats/ForwardDetId/src/HGCalTriggerBackendDetId.cc
  DataFormats/L1THGCal/interface/HGCalTowerID.h
  DataFormats/L1THGCal/interface/HGCalTowerMap.h
  DataFormats/L1THGCal/src/HGCalTowerMap.cc
  L1Trigger/L1THGCal/interface/HGCalTriggerTowerGeometryHelper.h
  L1Trigger/L1THGCal/interface/backend/HGCalHistoSeedingImpl.h
  L1Trigger/L1THGCal/python/customHistoSeeding.py
  L1Trigger/L1THGCal/python/customTowers.py
  L1Trigger/L1THGCal/python/l1tHGCalBackEndLayer2Producer_cfi.py
  L1Trigger/L1THGCal/python/l1tHGCalTowerMapProducer_cfi.py
  L1Trigger/L1THGCal/src/HGCalTriggerTowerGeometryHelper.cc
  L1Trigger/L1THGCal/src/backend/HGCalHistoSeedingImpl.cc
  L1Trigger/L1THGCalUtilities/python/clustering3d.py
Labels: l1-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved

#42781 [Backport] Fix for proper separation of the ZDCP and ZDCM triggers in the uGT
  L1Trigger/L1TGlobal/src/EnergySumZdcCondition.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, urgent, backport

#42674 Add a 2023 data workflow for all patatrack reconstruction using the `gpuValidation` modifier
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: pending-signatures, tests-approved, pdmv-approved, orp-approved, upgrade-pending, code-checks-approved, tracking

#42773 Changed FailPath/SkipEvent to TryToContinue [CommonTools]
  CommonTools/PileupAlgos/test/recomputePuppiOnMiniAOD.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42789 Update 2022 MC GTs for new ecal timing calibrations - 13_2_X
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#42788 Update 2022 MC GTs for new ecal timing calibrations - 13_1_X
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#42740 add run3_miniAOD_12X era modifier
  Configuration/Eras/python/Modifier_run3_miniAOD_12X_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/PatAlgos/python/slimming/applySubstructure_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved

#42759 Move Phase2 HLT to ticl_v4
  HLTrigger/Configuration/python/HLT_75e33/modules/pfTICL_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersEM_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersHAD_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersMergeV3_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersMerge_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersTrkEM_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersTrk_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/tasks/iterTICLTask_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/tasks/ticlCLUE3DHighStepTask_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/tasks/ticlTracksterMergeTaskV3_cfi.py
  HLTrigger/Configuration/python/HLT_75e33_timing_cff.py
  RecoHGCal/TICL/plugins/LinkingAlgoBase.h
  RecoHGCal/TICL/plugins/LinkingAlgoByDirectionGeometric.cc
  RecoHGCal/TICL/plugins/LinkingAlgoByDirectionGeometric.h
  RecoHGCal/TICL/plugins/TrackstersMergeProducer.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#42782 [130X]: Add run3_miniAOD_12X modifier
  Configuration/Eras/python/Modifier_run3_miniAOD_12X_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/PatAlgos/python/slimming/applySubstructure_cff.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
Labels: operations-approved, reconstruction-approved, pending-signatures, tests-approved, pdmv-approved, orp-approved, upgrade-pending, xpog-approved

#42733 Adding ZDC Unpacker to L1RawtoDigi
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTCollections.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTSetup.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/L1TObjectCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/ZDCUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/ZDCUnpacker.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42754 Update autoSkim with 2023 PbPb skims
  Configuration/Skimming/python/PbPb_EMuSkim_cff.py
  Configuration/Skimming/python/PbPb_ZMMSkim_cff.py
  Configuration/Skimming/python/autoSkim.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#42800 [13_2_X] Adding ZDC Unpacker to L1RawtoDigi
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTCollections.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTSetup.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/L1TObjectCollections.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/ZDCUnpacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/ZDCUnpacker.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#42784 [13_2_X] Update autoSkim with 2023 PbPb skims
  Configuration/Skimming/python/PbPb_EMuSkim_cff.py
  Configuration/Skimming/python/PbPb_ZMMSkim_cff.py
  Configuration/Skimming/python/autoSkim.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, backport-ok

#42760 Move Phase2 HLT to ticl_v4 [13_1_X]
  HLTrigger/Configuration/python/HLT_75e33/modules/pfTICL_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersEM_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersHAD_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersMergeV3_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersMerge_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersTrkEM_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlTrackstersTrk_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/tasks/iterTICLTask_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/tasks/ticlCLUE3DHighStepTask_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/tasks/ticlTracksterMergeTaskV3_cfi.py
  HLTrigger/Configuration/python/HLT_75e33_timing_cff.py
  RecoHGCal/TICL/plugins/LinkingAlgoBase.h
  RecoHGCal/TICL/plugins/LinkingAlgoByDirectionGeometric.cc
  RecoHGCal/TICL/plugins/LinkingAlgoByDirectionGeometric.h
  RecoHGCal/TICL/plugins/TrackstersMergeProducer.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, backport-ok

#42791 [Phase-2] Fix usage of L1 egamma seeds in Phase-2 HLT
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkEleDouble12Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkEleSingle25Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkEleSingle36Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkEmDouble12Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkEmDouble24Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkEmSingle37Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkEmSingle51Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkIsoEleSingle22Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkIsoEleSingle28Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkIsoEmDouble12Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkIsoEmSingle22Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/L1TkIsoEmSingle36Filter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL1TEGammaHGCFilteredCollectionProducer_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/ticlSeedingL1_cfi.py
  HLTrigger/HLTfilters/plugins/L1TTkEleFilter.cc
  HLTrigger/HLTfilters/plugins/L1TTkEleFilter.h
  HLTrigger/HLTfilters/plugins/L1TTkEmFilter.cc
  HLTrigger/HLTfilters/plugins/L1TTkEmFilter.h
  RecoHGCal/TICL/plugins/SeedingRegionByL1.cc
  RecoHGCal/TICL/plugins/SeedingRegionByL1.h
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#42783 Add a Phase2 HLT tracking DQM monitoring
  Configuration/EventContent/python/EventContent_cff.py
  DQM/SiTrackerPhase2/plugins/Phase2ITMonitorCluster.cc
  DQM/SiTrackerPhase2/plugins/Phase2OTMonitorCluster.cc
  DQMOffline/Configuration/python/autoDQM.py
  DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py
  DQMOffline/Trigger/python/PrimaryVertexMonitoring_cff.py
  DQMOffline/Trigger/python/SiTrackerPhase2_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/TrackToTrackMonitoring_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_cff.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking, trk

#42786 Add mu beamspot constrained pT. Increase mu eta and phi precision to 16 bits [13.1.X]
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  RecoMuon/GlobalTrackingTools/plugins/BuildFile.xml
  RecoMuon/GlobalTrackingTools/plugins/MuonBeamspotConstraintValueMapProducer.cc
Labels: reconstruction-approved, pending-signatures, tests-approved, orp-approved, backport-ok, xpog-pending, muon

#42787 Add mu beamspot constrained pT. Increase mu eta and phi precision to 16 bits [13.2.X]
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  RecoMuon/GlobalTrackingTools/plugins/BuildFile.xml
  RecoMuon/GlobalTrackingTools/plugins/MuonBeamspotConstraintValueMapProducer.cc
Labels: reconstruction-approved, pending-signatures, tests-approved, orp-approved, backport-ok, xpog-pending, muon

#42809 PPS Conddb dump for mapping and mask
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#42764 Changed FailPath/SkipEvent to TryToContinue [Geometry]
  Geometry/CMSCommonData/test/run2017Plan0_cfg.py
  Geometry/HGCalCommonData/test/python/runHGCalDD4hep_cfg.py
  Geometry/HGCalCommonData/test/python/runHGCalDDD_cfg.py
  Geometry/HGCalCommonData/test/python/runHGCalTestDD4hep_cfg.py
  Geometry/HGCalCommonData/test/python/runHGCalTestDDD_cfg.py
  Geometry/HGCalCommonData/test/python/runHGCalWafer8DD4hep_cfg.py
  Geometry/HGCalCommonData/test/python/runHGCalWafer8DDD_cfg.py
  Geometry/HcalCommonData/test/python/TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_10024.0.py
  Geometry/HcalCommonData/test/python/TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_10024.911.py
  Geometry/HcalCommonData/test/python/TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_10824.0.py
  Geometry/HcalCommonData/test/python/TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_10824.911.py
  Geometry/HcalCommonData/test/python/step2_DIGI_L1_DIGI2RAW_HLT_10024.0.py
  Geometry/HcalCommonData/test/python/step2_DIGI_L1_DIGI2RAW_HLT_10024.911.py
  Geometry/HcalCommonData/test/python/step2_DIGI_L1_DIGI2RAW_HLT_10824.0.py
  Geometry/HcalCommonData/test/python/step2_DIGI_L1_DIGI2RAW_HLT_10824.911.py
  Geometry/HcalCommonData/test/python/step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_VALIDATION_DQM_10024.0.py
  Geometry/HcalCommonData/test/python/step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_VALIDATION_DQM_10024.911.py
  Geometry/HcalCommonData/test/python/step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_VALIDATION_DQM_10824.0.py
  Geometry/HcalCommonData/test/python/step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_VALIDATION_DQM_10824.911.py
  Geometry/HcalCommonData/test/python/testHitRelabeller_cfg.py
  Geometry/HcalCommonData/test/python/testPhase1_cfg.py
  Geometry/HcalCommonData/test/python/testPhase2_cfg.py
  Geometry/TrackerCommonData/test/python/dd4hepRun3_cfg.py
  Geometry/TrackerCommonData/test/python/run17.py
  Geometry/TrackerCommonData/test/python/run21.py
  Geometry/TrackerCommonData/test/python/run21Zero.py
  Geometry/TrackerCommonData/test/python/run21flat.py
  Geometry/VeryForwardData/test/testRun3_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, trk

#42768 Changed FailPath/SkipEvent to TryToContinue [DQM]
  DQM/Physics/test/qcdLowPtDQM_cfg.py
  DQM/SiTrackerPhase2/test/dqmstep_phase2tk_cfg.py
  DQM/SiTrackerPhase2/test/harvestingstep_phase2tk_cfg.py
  DQMOffline/Lumi/test/zcounting_step1_fromAOD.py
  DQMOffline/Lumi/test/zcounting_step1_fromRAW.py
  DQMOffline/Lumi/test/zcounting_step2_fromAOD.py
  DQMServices/Demo/test/harvesting.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#42810 remove unused vector in HiPuRhoProducer
  RecoHI/HiJetAlgos/plugins/HiPuRhoProducer.cc
Labels: reconstruction-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#42811 remove unused vector in HiPuRhoProducer [13_2_X]
  RecoHI/HiJetAlgos/plugins/HiPuRhoProducer.cc
Labels: reconstruction-pending, pending-signatures, tests-rejected, orp-approved, backport-ok

#42794 Update Phase2 MC GT to clean up unused Phase1 pixel conditions
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42812 `DQM/TrackingMonitorSource` cleanup
  DQM/TrackingMonitorSource/interface/AlcaRecoTrackSelector.h
  DQM/TrackingMonitorSource/interface/HLTPathSelector.h
  DQM/TrackingMonitorSource/interface/TrackMultiplicityFilter.h
  DQM/TrackingMonitorSource/interface/TrackTypeMonitor.h
  DQM/TrackingMonitorSource/interface/TtbarTrackProducer.h
  DQM/TrackingMonitorSource/interface/WtoLNuSelector.h
  DQM/TrackingMonitorSource/interface/ZEEDetails.h
  DQM/TrackingMonitorSource/interface/ZtoEEElectronTrackProducer.h
  DQM/TrackingMonitorSource/interface/ZtoEEEventSelector.h
  DQM/TrackingMonitorSource/interface/ZtoMMEventSelector.h
  DQM/TrackingMonitorSource/interface/ZtoMMMuonTrackProducer.h
  DQM/TrackingMonitorSource/interface/ttbarEventSelector.h
  DQM/TrackingMonitorSource/plugins/AlcaRecoTrackSelector.cc
  DQM/TrackingMonitorSource/plugins/HLTPathSelector.cc
  DQM/TrackingMonitorSource/plugins/StandaloneTrackMonitor.cc
  DQM/TrackingMonitorSource/plugins/TrackMultiplicityFilter.cc
  DQM/TrackingMonitorSource/plugins/TrackTypeMonitor.cc
  DQM/TrackingMonitorSource/plugins/TtbarTrackProducer.cc
  DQM/TrackingMonitorSource/plugins/WtoLNuSelector.cc
  DQM/TrackingMonitorSource/plugins/ZEEDetails.cc
  DQM/TrackingMonitorSource/plugins/ZtoEEElectronTrackProducer.cc
  DQM/TrackingMonitorSource/plugins/ZtoEEEventSelector.cc
  DQM/TrackingMonitorSource/plugins/ZtoMMEventSelector.cc
  DQM/TrackingMonitorSource/plugins/ZtoMMMuonTrackProducer.cc
  DQM/TrackingMonitorSource/plugins/ttbarEventSelector.cc
  DQM/TrackingMonitorSource/python/StandaloneTrackMonitor_cfi.py
  DQM/TrackingMonitorSource/python/TrackTypeMonitor_cfi.py
  DQM/TrackingMonitorSource/python/ZEEDetails_cfi.py
  DQM/TrackingMonitorSource/test/BuildFile.xml
  DQM/TrackingMonitorSource/test/Tracker_DataMCValidation_Harvest_cfg.py
  DQM/TrackingMonitorSource/test/Tracker_DataMCValidation_cfg.py
  DQM/TrackingMonitorSource/test/testTrackingDATAMC.sh
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#42808 Fix noisy HLT BTV DQM
  DQMOffline/Trigger/python/BTaggingMonitor_cfi.py
  DQMOffline/Trigger/python/BTaggingMonitoring_cff.py
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, btv

#42798 remove all uses of -p, --parameter-set with cmsRun
  Calibration/LumiAlCaRecoProducers/test/test.sh
  CondCore/ESSources/test/TestConcurrentIOVsCondCore.sh
  CondTools/DT/test/DTReadOutMapping-O2OProcedure
  CondTools/Ecal/o2oTests/read_o2o.sh
  CondTools/RPC/test/writeL1RPCHwConfig2DB.csh
  DQM/SiStripMonitorClient/test/ReadMe.txt
  DQM/SiStripMonitorCluster/test/batch_mtcc.sh
  DQM/SiStripMonitorCluster/test/filter_mtcc.sh
  DQM/SiStripMonitorCluster/test/filter_mtcc_reprocessed.sh
  DQMServices/FwkIO/test/run_tests.sh
  IOPool/Common/test/TestEdmFastMerge.sh
  RecoJets/JetProducers/doc/html/jetSimuChain.html
  RecoLuminosity/LumiProducer/test/run_lumiProd.sh
  Validation/GlobalDigis/test/valid_global.csh
  Validation/GlobalHits/test/README
  Validation/GlobalHits/test/valid_global.csh
  Validation/GlobalRecHits/test/valid_global.csh
  Validation/Mixing/test/testsuite.csh
  Validation/Mixing/test/testsuite_SmartPointers.csh
  Validation/TrackerHits/test/README
Labels: alca-approved, core-approved, dqm-approved, reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, trk

#42790 MTD Validation: fixes to tracks checks
  Validation/MtdValidation/plugins/MtdTracksHarvester.cc
  Validation/MtdValidation/plugins/MtdTracksValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42777 MTD Validation: add selection on vxt Ndof>4 in Primary4DVertexValidation
  Validation/MtdValidation/plugins/Primary4DVertexValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42745 Phase2 MuonHLTSeed MVA Classifier CMSSW_13_3_X
  HLTrigger/Configuration/python/HLT_75e33/modules/hltIter2Phase2L3FromL1TkMuonCkfTrackCandidates_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltIter2Phase2L3FromL1TkMuonPixelSeedsFiltered_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_IsoMu24_FromL1TkMuon_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_FromL1TkMuon_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_Mu37_Mu27_FromL1TkMuon_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_Mu50_FromL1TkMuon_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_TriMu_10_5_5_DZ_FromL1TkMuon_cfi.py
  RecoMuon/TrackerSeedGenerator/BuildFile.xml
  RecoMuon/TrackerSeedGenerator/interface/SeedMvaEstimatorPhase2.h
  RecoMuon/TrackerSeedGenerator/plugins/BuildFile.xml
  RecoMuon/TrackerSeedGenerator/plugins/MuonHLTSeedMVAClassifierPhase2.cc
  RecoMuon/TrackerSeedGenerator/src/SeedMvaEstimatorPhase2.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, muon

#42822 BackPort(#42745) Phase2 MuonHLTSeed MVA Classifier to CMSSW_13_1_X for AR
  HLTrigger/Configuration/python/HLT_75e33/modules/hltIter2Phase2L3FromL1TkMuonCkfTrackCandidates_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltIter2Phase2L3FromL1TkMuonPixelSeedsFiltered_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_IsoMu24_FromL1TkMuon_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_FromL1TkMuon_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_Mu37_Mu27_FromL1TkMuon_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_Mu50_FromL1TkMuon_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_TriMu_10_5_5_DZ_FromL1TkMuon_cfi.py
  RecoMuon/TrackerSeedGenerator/BuildFile.xml
  RecoMuon/TrackerSeedGenerator/interface/SeedMvaEstimatorPhase2.h
  RecoMuon/TrackerSeedGenerator/plugins/BuildFile.xml
  RecoMuon/TrackerSeedGenerator/plugins/MuonHLTSeedMVAClassifierPhase2.cc
  RecoMuon/TrackerSeedGenerator/src/SeedMvaEstimatorPhase2.cc
Labels: reconstruction-pending, hlt-approved, pending-signatures, tests-approved, orp-approved, requires-external, backport-ok, muon

#42826 fix `GeneralPurposeTrackAnalyzer` in the phase-2 case, due to missing conditions
  Alignment/OfflineValidation/plugins/GeneralPurposeTrackAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#42833 Fix random DQM path order from ConfigBuilder in case of duplicate DQM sequences
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/Applications/test/BuildFile.xml
  Configuration/Applications/test/ConfigBuilderTest.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#42834 [13_2_X] Fix random DQM path order from ConfigBuilder in case of duplicate DQM sequences
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/Applications/test/BuildFile.xml
  Configuration/Applications/test/ConfigBuilderTest.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#42847 Removed unused IDVectorMap class
  DataFormats/Common/interface/IDVectorMap.h
  DataFormats/Common/test/BuildFile.xml
  DataFormats/Common/test/testIDVectorMap.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42846 fix commented section of `EDAnalyzer::fillDescriptions` skeleton, such that it can actually compile
  FWCore/Skeletons/mkTemplates/EDAnalyzer/EDAnalyzer.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42844 ECAL - Add dummy collections to ECAL GPU unpacker
  EventFilter/EcalRawToDigi/plugins/EcalCPUDigisProducer.cc
  EventFilter/EcalRawToDigi/python/ecalDigis_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, ecal

#42805 Enable Laser 4 plots in ECAL DQM
  DQM/EcalCommon/python/CommonParams_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, ecal

#42803 update HLT selection for HI mode in `sistrip` and `l1tstage2` online-DQM clients
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42839 Make enum to int conversion in `SiStripRawToDigiUnpacker.cc` explicit
  EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#42819 Addition of SingleEleNonIso HLT path of pT threshold 115 GeV to Phase2 HLT menu
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEG115EtL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEGL1SeedsForSingleEleNonIsolatedFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEle115NonIsoClusterShapeL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEle115NonIsoClusterShapeSigmavvL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEle115NonIsoClusterShapeSigmawwL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEle115NonIsoGsfDetaL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEle115NonIsoGsfDphiL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEle115NonIsoHEL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEle115NonIsoHgcalHEL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEle115NonIsoPMS2L1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEle115NonIsoPixelMatchL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltPreEle115NonIsoL1Seeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_Ele115_NonIso_L1Seeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTEle115NonIsoL1SeededSequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/tasks/HLTEle115NonIsoL1SeededTask_cfi.py
  HLTrigger/Configuration/python/HLT_75e33_cff.py
  HLTrigger/Configuration/python/HLT_75e33_timing_cff.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, egamma

#42845 Prepare ECAL multifit reconstruction to use different time calibration records - 132x
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerMultiFit.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, ecal

#42813 [13_2_X] Port of v0_4_1 HI caloParams with updated centrality trigger thresholds
  L1Trigger/Configuration/python/customiseSettings.py
  L1Trigger/L1TCalorimeter/python/caloParamsHI_2023_v0_4_1_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#42830 minimal fixes to run Phase2 patatrack pixel only workflows without using phase-1 pixel conditions
  Configuration/StandardSequences/python/RawToDigi_cff.py
  EventFilter/SiPixelRawToDigi/python/siPixelDigis_cff.py
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizerPreSplitting_cfi.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#42804 update HLT selection for HI mode in `sistrip` and `l1tstage2` online-DQM clients [`13_2_X`]
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#42853 [13.2.X] Add 2D comparison histograms to `SiStripMonitorApproximateCluster`
  DQM/SiStripMonitorApproximateCluster/plugins/SiStripMonitorApproximateCluster.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport, trk

#42806 Enable Laser 4 plots in ECAL DQM [13_2_X]
  DQM/EcalCommon/python/CommonParams_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, ecal

#42870 Fixing bug in a photon path in Phase2 HLT
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEG108EtL1SeededFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEG108EtUnseededFilter_cfi.py
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, egamma

#42859 Add unit test for SiStripApproximateClusterCollection format
  DataFormats/SiStripCluster/README.md
  DataFormats/SiStripCluster/interface/SiStripApproximateCluster.h
  DataFormats/SiStripCluster/test/BuildFile.xml
  DataFormats/SiStripCluster/test/TestReadSiStripApproximateClusterCollection.cc
  DataFormats/SiStripCluster/test/TestSiStripApproximateClusterCollection.sh
  DataFormats/SiStripCluster/test/TestWriteSiStripApproximateClusterCollection.cc
  DataFormats/SiStripCluster/test/create_SiStripApproximateClusterCollection_test_file_cfg.py
  DataFormats/SiStripCluster/test/test_readSiStripApproximateClusterCollection_cfg.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, trk

#42857 Fix bug in defining bin edges of TH2F plots in ECAL DQM
  DQM/EcalCommon/src/MESetEcal.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport, code-checks-approved, ecal

#42852 Add 2D comparison histograms to `SiStripMonitorApproximateCluster`
  DQM/SiStripMonitorApproximateCluster/plugins/SiStripMonitorApproximateCluster.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#42849 Fix `PixelCountFilter` and introduce `PixelOccupancyFilter`
  CommonTools/UtilAlgos/interface/CollectionCountEventSelector.h
  CommonTools/UtilAlgos/interface/CollectionInCollectionFilter.h
  CommonTools/UtilAlgos/interface/CollectionInCollectionFilterTrait.h
  CommonTools/UtilAlgos/interface/DetSetCounterSelector.h
  CommonTools/Utils/interface/DetSetCounterSelector.h
  DPGAnalysis/Skims/src/PixelCountFilter.cc
  DPGAnalysis/Skims/src/PixelOccupancyFilter.cc
Labels: reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#42814 Extend AllocMonitor
  PerfTools/AllocMonitor/README.md
  PerfTools/AllocMonitor/interface/AllocMonitorRegistry.h
  PerfTools/AllocMonitor/plugins/PeriodicAllocMonitor.cc
  PerfTools/AllocMonitor/test/test_catch2_AllocMonitorRegistry.cc
  PerfTools/AllocMonitor/test/test_proxies.cc
  PerfTools/AllocMonitorPreload/src/memory_proxies.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42772 Changed FailPath/SkipEvent to TryToContinue [DPG]
  DPGAnalysis/Skims/python/reco_skim_cfg_mod.py
  DPGAnalysis/Skims/python/reco_skim_cfg_mod_350.py
  DPGAnalysis/Skims/test/test_TopMuEG_SKIM.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#42770 Changed FailPath/SkipEvent to TryToContinue [Configuration]
  Configuration/Skimming/test/test_CSCCluster_cfg.py
  Configuration/Skimming/test/test_DTCluster_cfg.py
  Configuration/Skimming/test/test_DelayedJetMET_cfg.py
  Configuration/Skimming/test/test_DelayedJet_cfg.py
  Configuration/Skimming/test/test_DisTrk_cfg.py
  Configuration/Skimming/test/test_EXOHighMET_cfg.py
  Configuration/Skimming/test/test_EXOLLPJetHCAL_SKIM.py
  Configuration/Skimming/test/test_ReserveDMu_SD_cfg.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#42728 [NanoAOD, JMENano] Updates for Nano and JMENano
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_CHS_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_Puppi_cff.py
  PhysicsTools/NanoAOD/python/jetsAK8_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nanojmeDQM_cff.py
  PhysicsTools/PatAlgos/python/tools/jetCollectionTools.py
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#42848 Remove noisy missing collection warnings coming from EcalDQMonitorTask
  DQM/EcalMonitorTasks/interface/EcalDQMonitorTask.h
  DQM/EcalMonitorTasks/interface/GpuTask.h
  DQM/EcalMonitorTasks/plugins/EcalDQMonitorTask.cc
  DQM/EcalMonitorTasks/plugins/EcalDQMonitorTask2.cc
  DQM/EcalMonitorTasks/python/EcalMonitorTask_cfi.py
  DQM/EcalMonitorTasks/python/ecalGpuTask_cfi.py
  DQM/EcalMonitorTasks/src/GpuTask.cc
  DQMOffline/Ecal/python/ecal_dqm_source_offline_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#42872 Fix for pixel FED error imbalance in DQM plots
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#42838 Remove duplicate entries from `CondTools/RunInfo/plugins/BuildFile.xml`
  CondTools/RunInfo/plugins/BuildFile.xml
Labels: fully-signed, tests-rejected, db-approved, orp-approved, code-checks-approved

#42858 Fix bug in defining bin edges of TH2F plots in ECAL DQM [13_2_X]
  DQM/EcalCommon/src/MESetEcal.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#42891 T0 scenario for repacked pp
  Configuration/DataProcessing/python/Impl/ppEra_Run3_2023_repacked.py
  Configuration/DataProcessing/test/run_CfgTest.sh
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#42863 Adding the scouting event content to MINIAODSIM
  Configuration/EventContent/python/EventContent_cff.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42892 [13_2_X] T0 scenario for repacked pp
  Configuration/DataProcessing/python/Impl/ppEra_Run3_2023_repacked.py
  Configuration/DataProcessing/test/run_CfgTest.sh
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#42873 [13_2_X] Fix for pixel FED error imbalance in DQM plots
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, trk

#42860 Enable ECAL reconstructions to use different time calibration records
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducer.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitWorkerSimple.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitWorkerGlobal.cc
  RecoLocalCalo/EcalRecProducers/python/ecalRecHit_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, ecal

#42503 Release ProcessDesc in main() to release some memory
  FWCore/Framework/bin/cmsRun.cpp
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42865 Fix maybe-uninitialized warning in HiTrivialConditionRetriever
  RecoHI/HiCentralityAlgos/plugins/HiTrivialConditionRetriever.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42824 Clean BuildFiles
  CommonTools/TrackerMap/BuildFile.xml
  CondCore/AlignmentPlugins/BuildFile.xml
  CondCore/BaseKeyedPlugins/BuildFile.xml
  CondFormats/RunInfo/BuildFile.xml
  CondTools/RunInfo/BuildFile.xml
  DPGAnalysis/HcalNanoAOD/plugins/BuildFile.xml
  DQM/HcalTasks/BuildFile.xml
  DQM/HcalTasks/plugins/BuildFile.xml
  DQMOffline/Trigger/BuildFile.xml
  L1Trigger/L1TZDC/BuildFile.xml
  L1Trigger/L1TZDC/plugins/BuildFile.xml
  L1Trigger/Phase2L1GT/plugins/BuildFile.xml
  RecoPPS/ProtonReconstruction/BuildFile.xml
  SimG4CMS/HGCalTestBeam/plugins/BuildFile.xml
Labels: alca-approved, dqm-approved, l1-approved, reconstruction-approved, simulation-approved, fully-signed, tests-rejected, db-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved, hcal, trk

#42867 Phase2-sim147 First step to permit 2 clorimeter hit collection from a given Sensitive Detector which will enable calibration cell
  SimG4CMS/Calo/interface/CaloSD.h
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Calo/src/ECalSD.cc
  SimG4CMS/Calo/src/HCalSD.cc
  SimG4CMS/Forward/src/CastorSD.cc
  SimG4CMS/Forward/src/ZdcSD.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42894 HCALDQM: Add new ZDC electronics constants
  DQM/HcalCommon/interface/Constants.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42884 Don't run testAllocMonitorPreloadX tests for ASAN IBs
  PerfTools/AllocMonitor/test/BuildFile.xml
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42851 DeepCore model 2.2.1 CMSSW_13_3_0_pre3 (fixed comments)
  RecoTracker/TkSeedGenerator/plugins/DeepCoreSeedGenerator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, tracking

#42901 (DAQ) increase monitoring limit on number of streams
  EventFilter/Utilities/interface/FastMonitoringThread.h
Labels: daq-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42895 HCALDQM: Add new ZDC electronics constants[13_2_X]
  DQM/HcalCommon/interface/Constants.h
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok, hcal

#42902 (DAQ) increase monitoring limit on number of streams (13_2_X)
  EventFilter/Utilities/interface/FastMonitoringThread.h
Labels: daq-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#42904 SiStrip Lorentz Angle PCL: minor fixes
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLorentzAnglePCLHarvester.cc
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLorentzAnglePCLMonitor.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk
