Repository cms-sw/cmssw, pull requests merged in 2023-11, with the labels that each got.

#42930 Add ECAL portable data formats, collections and conditions for alpaka
  CondFormats/DataRecord/interface/EcalMultifitConditionsRcd.h
  CondFormats/DataRecord/interface/EcalMultifitParametersRcd.h
  CondFormats/DataRecord/src/EcalMultifitConditionsRcd.cc
  CondFormats/DataRecord/src/EcalMultifitParametersRcd.cc
  CondFormats/EcalObjects/BuildFile.xml
  CondFormats/EcalObjects/interface/EcalElectronicsMappingHost.h
  CondFormats/EcalObjects/interface/EcalElectronicsMappingSoA.h
  CondFormats/EcalObjects/interface/EcalMultifitConditionsHost.h
  CondFormats/EcalObjects/interface/EcalMultifitConditionsSoA.h
  CondFormats/EcalObjects/interface/EcalMultifitParametersHost.h
  CondFormats/EcalObjects/interface/EcalMultifitParametersSoA.h
  CondFormats/EcalObjects/interface/alpaka/EcalElectronicsMappingDevice.h
  CondFormats/EcalObjects/interface/alpaka/EcalMultifitConditionsDevice.h
  CondFormats/EcalObjects/interface/alpaka/EcalMultifitParametersDevice.h
  CondFormats/EcalObjects/src/ES_EcalElectronicsMappingHost.cc
  CondFormats/EcalObjects/src/ES_EcalMultifitConditionsHost.cc
  CondFormats/EcalObjects/src/ES_EcalMultifitParametersHost.cc
  CondFormats/EcalObjects/src/alpaka/ES_EcalElectronicsMappingDevice.cc
  CondFormats/EcalObjects/src/alpaka/ES_EcalMultifitConditionsDevice.cc
  CondFormats/EcalObjects/src/alpaka/ES_EcalMultifitParametersDevice.cc
  DataFormats/EcalDigi/BuildFile.xml
  DataFormats/EcalDigi/interface/EcalConstants.h
  DataFormats/EcalDigi/interface/EcalDigiHostCollection.h
  DataFormats/EcalDigi/interface/EcalDigiPhase2HostCollection.h
  DataFormats/EcalDigi/interface/EcalDigiPhase2SoA.h
  DataFormats/EcalDigi/interface/EcalDigiSoA.h
  DataFormats/EcalDigi/interface/alpaka/EcalDigiDeviceCollection.h
  DataFormats/EcalDigi/interface/alpaka/EcalDigiPhase2DeviceCollection.h
  DataFormats/EcalDigi/src/alpaka/classes_cuda.h
  DataFormats/EcalDigi/src/alpaka/classes_cuda_def.xml
  DataFormats/EcalDigi/src/alpaka/classes_rocm.h
  DataFormats/EcalDigi/src/alpaka/classes_rocm_def.xml
  DataFormats/EcalDigi/src/classes.h
  DataFormats/EcalDigi/src/classes_def.xml
  DataFormats/EcalRecHit/BuildFile.xml
  DataFormats/EcalRecHit/interface/EcalUncalibratedRecHitHostCollection.h
  DataFormats/EcalRecHit/interface/EcalUncalibratedRecHitSoA.h
  DataFormats/EcalRecHit/interface/alpaka/EcalUncalibratedRecHitDeviceCollection.h
  DataFormats/EcalRecHit/src/alpaka/classes_cuda.h
  DataFormats/EcalRecHit/src/alpaka/classes_cuda_def.xml
  DataFormats/EcalRecHit/src/alpaka/classes_rocm.h
  DataFormats/EcalRecHit/src/alpaka/classes_rocm_def.xml
  DataFormats/EcalRecHit/src/classes.h
  DataFormats/EcalRecHit/src/classes_def.xml
Labels: alca-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, db-approved, orp-approved, requires-external, code-checks-approved, heterogeneous-approved, ecal

#43080 Clean up and migrating edm::RefToBase to edm::Ptr (list 2 for RNTuple)
  AnalysisDataFormats/EWK/interface/WMuNuCandidate.h
  AnalysisDataFormats/EWK/interface/WMuNuCandidatePtr.h
  AnalysisDataFormats/EWK/src/WMuNuCandidate.cc
  AnalysisDataFormats/EWK/src/WMuNuCandidatePtr.cc
  AnalysisDataFormats/EWK/src/classes.h
  AnalysisDataFormats/EWK/src/classes_def.xml
  CommonTools/RecoAlgos/plugins/CaloRecHitCandidateProducer.cc
  DataFormats/CaloRecHit/src/classes_def.xml
  DataFormats/RecoCandidate/interface/CaloRecHitCandidate.h
  DataFormats/RecoCandidate/src/classes_def.xml
Labels: analysis-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43083 Remove build warning in TrackerMap
  CommonTools/TrackerMap/interface/TrackerMap.h
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43093 Correct url of the GEN fragment in a Pythia8Interface test and of the RelMon main page, after SSO migration
  GeneratorInterface/Pythia8Interface/test/test_Pythia8ConcurrentGeneratorFilter_WZ_TuneCP5_13TeV-pythia8.sh
  Utilities/RelMon/python/definitions.py
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, code-checks-approved

#43096 Control maximum number of process to run for generating validation plots
  Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py
  Validation/RecoTrack/python/plotting/validation.py
  Validation/RecoTrack/scripts/makeTrackValidationPlots.py
  Validation/RecoTrack/test/test_makeTrackValidationPlots.sh
  Validation/RecoTrack/test/trackingCompare.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#43099 Fix Wdeprecated-copy warnings in DataFormats/Common (2nd attempt)
  DataFormats/Common/interface/Association.h
  DataFormats/Common/interface/DataFrameContainer.h
  DataFormats/Common/interface/DetSetVector.h
  DataFormats/Common/interface/HLTGlobalStatus.h
  DataFormats/Common/interface/OrphanHandleBase.h
  DataFormats/Common/interface/RangeMap.h
  DataFormats/Common/interface/RefVectorHolder.h
  DataFormats/Common/interface/TriggerResults.h
  DataFormats/Common/interface/ValueMap.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43106 Use likelihood fit instead of chi-square fit in DQMServices slice fits
  DQMServices/Components/plugins/DQMGenericClient.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43118 Replace deprecated hash_set with unordered_set
  DQMServices/Core/interface/DQMNet.h
  DQMServices/Core/src/DQMNet.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43129 Update Run3 MC GTs with corrected GEM geometry for GE21 demonstration chamber
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43151 Per-LS Monitor Elements for Heavy Ions
  DQMOffline/JetMET/src/JetAnalyzer_HeavyIons.cc
  DQMServices/Core/python/nanoDQMIO_perLSoutput_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#43152 Update ecalMultiFitUncalibRecHit_cfi.py
  RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, ecal

#43153 Remove defaulted constructors and operators of StdArray
  DataFormats/Common/interface/StdArray.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43115 Phase2-hgx347 Make hits for Calibration cells in the coming HGCal version
  Configuration/Eras/python/Era_Phase2C22I13M9_cff.py
  Configuration/Eras/python/Modifier_phase2_hgcalV18_cff.py
  Geometry/HGCalCommonData/interface/HGCalCellOffset.h
  Geometry/HGCalCommonData/interface/HGCalParameters.h
  Geometry/HGCalCommonData/src/HGCalCellOffset.cc
  SimG4CMS/Calo/interface/CaloSD.h
  SimG4CMS/Calo/interface/HGCalSD.h
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Calo/src/HGCMouseBite.cc
  SimG4CMS/Calo/src/HGCalSD.cc
  SimG4CMS/Calo/test/python/runHGC1_cfg.py
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/SensitiveDetector/interface/SensitiveCaloDetector.h
  SimG4Core/SensitiveDetector/interface/SensitiveDetector.h
  SimG4Core/SensitiveDetector/interface/SensitiveTkDetector.h
  SimG4Core/SensitiveDetector/src/SensitiveDetector.cc
Labels: geometry-approved, operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#42238 Introduce autoNANO
  Configuration/Applications/python/ConfigBuilder.py
  PhysicsTools/NanoAOD/python/autoNANO.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#43109 Update the Phase-2 L1 vertex tag in the P2GT producer
  L1Trigger/Phase2L1GT/python/l1tGTProducer_cff.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43132 Add minETA selection to HLT filter RecoTracker/DeDx/plugins/HLTDeDxFilter
  RecoTracker/DeDx/plugins/HLTDeDxFilter.cc
  RecoTracker/DeDx/plugins/HLTDeDxFilter.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#43110 Update beamhlt client unitTests
  DQM/Integration/test/BuildFile.xml
Labels: dqm-approved, fully-signed, tests-rejected, orp-approved, requires-external, code-checks-approved

#43139 HCAL: setting hardcoded PFCuts conditions for Phase2
  CalibCalorimetry/HcalAlgos/interface/HcalDbHardcode.h
  CalibCalorimetry/HcalAlgos/src/HcalDbHardcode.cc
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
Labels: alca-pending, pending-signatures, tests-started, orp-approved, code-checks-approved

#43131 [13.1.X] Selected backports of Phase-2 HLT Validation (w.r.t SIM)
  Configuration/StandardSequences/python/Harvesting_cff.py
  Configuration/StandardSequences/python/Validation_cff.py
  HLTriggerOffline/Common/python/HLTValidationHarvest_cff.py
  HLTriggerOffline/Common/python/HLTValidation_cff.py
  HLTriggerOffline/JetMET/python/Validation/SingleJetValidation_cfi.py
  Validation/Configuration/python/autoValidation.py
  Validation/RecoTrack/python/HLTmultiTrackValidator_cff.py
  Validation/RecoTrack/python/associators_cff.py
  Validation/RecoVertex/python/HLTmultiPVvalidator_cff.py
Labels: dqm-approved, operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok, tracking

#43028 Add EP combination variables to electron Table in NANOAOD
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, egamma

#43165 Fix upper bound of the scale in SUEP shower simulation
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43138 Updating SONIC ParticleNet Producer and Config Files
  RecoBTag/ONNXRuntime/plugins/ParticleNetSonicJetTagsProducer.cc
  RecoBTag/ONNXRuntime/python/pfHiggsInteractionNet_cff.py
  RecoBTag/ONNXRuntime/python/pfParticleNetFromMiniAODAK4_cff.py
  RecoBTag/ONNXRuntime/python/pfParticleNetFromMiniAODAK8_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#43160 Update SimBeamSpotObjects to handle different EvtVtxGenerators
  CondCore/BeamSpotPlugins/interface/BeamSpotPayloadInspectorHelper.h
  CondCore/BeamSpotPlugins/test/testBeamSpotPayloadInspector.cpp
  CondFormats/BeamSpotObjects/interface/SimBeamSpotObjects.h
  CondFormats/BeamSpotObjects/src/SimBeamSpotObjects.cc
  CondTools/BeamSpot/plugins/BeamProfile2DBReader.cc
  CondTools/BeamSpot/plugins/BeamProfile2DBWriter.cc
  CondTools/BeamSpot/test/BeamProfile2DBWriterAll_cfg.py
  CondTools/BeamSpot/test/BeamProfile2DBWriter_cfg.py
  CondTools/BeamSpot/test/extractAndUploadAll.py
  IOMC/EventVertexGenerators/interface/BetafuncEvtVtxGenerator.h
  IOMC/EventVertexGenerators/interface/GaussEvtVtxGenerator.h
  IOMC/EventVertexGenerators/src/BetafuncEvtVtxGenerator.cc
  IOMC/EventVertexGenerators/src/GaussEvtVtxGenerator.cc
Labels: alca-approved, simulation-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, tracking

#43161 Run3-hcx353 Merging the changes of ZDC code from Anna which was used by the ZDC collaboration for the Run2 setup
  Geometry/ForwardCommonData/data/zdc/2021/v3/zdc.xml
  SimG4CMS/Forward/interface/ZdcNumberingScheme.h
  SimG4CMS/Forward/interface/ZdcSD.h
  SimG4CMS/Forward/interface/ZdcShowerLibrary.h
  SimG4CMS/Forward/src/ZdcNumberingScheme.cc
  SimG4CMS/Forward/src/ZdcSD.cc
  SimG4CMS/Forward/src/ZdcShowerLibrary.cc
  SimTransport/HectorProducer/interface/Hector.h
  SimTransport/HectorProducer/src/Hector.cc
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43163 Improve the error message when trying to call a kernel from a .cc file
  HeterogeneousCore/AlpakaInterface/interface/config.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#43171 Adding lumi=0 defaults to hardcode HB PFCuts for Phase2
  CalibCalorimetry/HcalAlgos/src/HcalDbHardcode.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43178 Phase2-sim150 Update the scripts in SimG4Core/PrintGeomInfo
  SimG4Core/PrintGeomInfo/test/SolidFileCompare.cpp
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckCalo_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckHGCal_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runDD4hep2026_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runDDD2026_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runMaterialBudgeInfo2026_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runPrintG4Solids2_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runPrintG4Solids_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runPrintG4Touch2026_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runPrintSolid2026_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runSens2026_cfg.py
  SimG4Core/PrintGeomInfo/test/python/runSummary2026_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43145 [mkFit] Tools supporting better layer-related computations -- technical changes to support further development
  RecoTracker/MkFit/plugins/MkFitGeometryESProducer.cc
  RecoTracker/MkFitCMS/standalone/Makefile
  RecoTracker/MkFitCMS/standalone/MkStandaloneSeqs.cc
  RecoTracker/MkFitCMS/standalone/Shell.cc
  RecoTracker/MkFitCMS/standalone/buildtestMPlex.cc
  RecoTracker/MkFitCMS/standalone/mkFit.cc
  RecoTracker/MkFitCore/BuildFile.xml
  RecoTracker/MkFitCore/interface/Config.h
  RecoTracker/MkFitCore/interface/HitStructures.h
  RecoTracker/MkFitCore/interface/MkBuilder.h
  RecoTracker/MkFitCore/interface/Track.h
  RecoTracker/MkFitCore/interface/TrackStructures.h
  RecoTracker/MkFitCore/interface/TrackerInfo.h
  RecoTracker/MkFitCore/src/HitStructures.cc
  RecoTracker/MkFitCore/src/Matriplex/Matriplex.h
  RecoTracker/MkFitCore/src/Matriplex/MatriplexCommon.h
  RecoTracker/MkFitCore/src/Matriplex/MatriplexSym.h
  RecoTracker/MkFitCore/src/Matrix.h
  RecoTracker/MkFitCore/src/MiniPropagators.cc
  RecoTracker/MkFitCore/src/MiniPropagators.h
  RecoTracker/MkFitCore/src/MkBase.h
  RecoTracker/MkFitCore/src/MkBuilder.cc
  RecoTracker/MkFitCore/src/MkFinder.cc
  RecoTracker/MkFitCore/src/MkFinder.h
  RecoTracker/MkFitCore/src/Track.cc
  RecoTracker/MkFitCore/src/TrackStructures.cc
  RecoTracker/MkFitCore/standalone/ConfigStandalone.h
  RecoTracker/MkFitCore/standalone/Event.cc
  RecoTracker/MkFitCore/standalone/Event.h
  RecoTracker/MkFitCore/standalone/Geoms/CylCowWLids.cc
  RecoTracker/MkFitCore/standalone/Makefile
  RecoTracker/MkFitCore/standalone/Makefile.config
  RecoTracker/MkFitCore/standalone/RntDumper/MkFinder_selectHitIndices.icc
  RecoTracker/MkFitCore/standalone/RntDumper/RntDumper.cc
  RecoTracker/MkFitCore/standalone/RntDumper/RntDumper.h
  RecoTracker/MkFitCore/standalone/RntDumper/RntStructs.cc
  RecoTracker/MkFitCore/standalone/RntDumper/RntStructs.h
  RecoTracker/MkFitCore/standalone/RntDumper/RntStructs_Linkdef.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#43168 [13_2_X] Add minETA selection to HLT filter RecoTracker/DeDx/plugins/HLTDeDxFilter
  RecoTracker/DeDx/plugins/HLTDeDxFilter.cc
  RecoTracker/DeDx/plugins/HLTDeDxFilter.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, tracking

#43156 Fixing the maximum number of OMTF final candidates [12_4_X]
  L1Trigger/L1TMuonOverlapPhase1/src/Omtf/GhostBuster.cc
  L1Trigger/L1TMuonOverlapPhase1/src/Omtf/GhostBusterPreferRefDt.cc
  L1Trigger/L1TMuonOverlapPhase1/test/runMuonOverlap_run3_data.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43121 [13_2_X] Online DQM fed client: use rawDataRepacker for HCAL FEDIntegrity Task in HI runs (backport of 43120)
  DQM/Integration/python/clients/fed_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43034 Fix may be used uninitialized warning in `RecoTracker/MeasurementDet` (el8_aarch64_gcc12)
  RecoTracker/MeasurementDet/plugins/TkPixelMeasurementDet.cc
  RecoTracker/MeasurementDet/plugins/TkPixelMeasurementDet.h
Labels: reconstruction-approved, fully-signed, tests-rejected, orp-approved, code-checks-approved, tracking

#43043 Use ZDC digis in uGT DQM
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43124 MTD geometry: speed up MTD reco geometry construction
  Geometry/MTDNumberingBuilder/plugins/DDCmsMTDConstruction.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43170 Use likelihood fit instead of chi-square fit for PFJetDQMPostProcessor plugin
  Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43194 Phase2-hgx348B Take care of handling both HGCal and HFNose access to Geometry and Topology classes
  Geometry/CaloTopology/src/HGCalTopology.cc
  Geometry/CaloTopology/test/HGCalTopologyTester.cc
  Geometry/HGCalGeometry/src/HGCalGeometry.cc
Labels: geometry-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#43192 [106X] Update PdmV website links after SSO change
  GeneratorInterface/Pythia8Interface/test/test_Pythia8ConcurrentGeneratorFilter_WZ_TuneCP5_13TeV-pythia8.sh
  Utilities/RelMon/python/definitions.py
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#43180 [10_6_X] Fix upper bound of the scale in SUEP shower simulation
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#43191 [124X] Update PdmV website links after SSO change
  GeneratorInterface/Pythia8Interface/test/test_Pythia8ConcurrentGeneratorFilter_WZ_TuneCP5_13TeV-pythia8.sh
  Utilities/RelMon/python/definitions.py
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#43190 [126X] Update PdmV website links after SSO change
  GeneratorInterface/Pythia8Interface/test/test_Pythia8ConcurrentGeneratorFilter_WZ_TuneCP5_13TeV-pythia8.sh
  Utilities/RelMon/python/definitions.py
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#43184 [126X] Fix upper bound of the scale in SUEP shower simulation
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#43182 [130X] Fix upper bound of the scale in SUEP shower simulation
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#43183 [131X] Fix upper bound of the scale in SUEP shower simulation
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#43187 [132X] Update PdmV website links after SSO change
  GeneratorInterface/Pythia8Interface/test/test_Pythia8ConcurrentGeneratorFilter_WZ_TuneCP5_13TeV-pythia8.sh
  Utilities/RelMon/python/definitions.py
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#43185 [132X] Fix upper bound of the scale in SUEP shower simulation
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#43113 [13_2_X] Use ZDC digis in uGT DQM
  DQM/L1TMonitor/python/L1TStage2Emulator_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43173 [Backport 7_1_X] Fix EmissionVetoHook for BB4L
  GeneratorInterface/Pythia8Interface/plugins/EmissionVetoHook1.cc
Labels: generators-approved, fully-signed, tests-rejected, orp-approved

#43141 customize HLT offline DQM for Run3 PbPb and introduce HI 2023A relval workflow (with reHLT)
  Configuration/EventContent/python/EventContent_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  DQMOffline/Trigger/python/PrimaryVertexMonitoring_cff.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_Cluster_cff.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_TrackCluster_cff.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/SiStrip_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/TrackToTrackMonitoring_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_Client_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_cff.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#43175 Initial implementation of the FixMissingStreamerInfos service
  IOPool/Input/scripts/makeFileContainingStreamerInfos.C
  IOPool/Input/src/FixMissingStreamerInfos.cc
  IOPool/Input/test/SchemaEvolution_test_read_cfg.py
  IOPool/Input/test/testSchemaEvolution.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#43208 Add ActivityRegistry signals for between Events
  FWCore/Framework/src/EventProcessor.cc
  FWCore/ServiceRegistry/interface/ActivityRegistry.h
  FWCore/ServiceRegistry/src/ActivityRegistry.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43220 Ignoring raw channel ids in the unit test database dump comparison
  CondTools/Hcal/test/pfcuts_db_io_test.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, requires-external, code-checks-approved

#43174 Prototype web view of Tracer service information
  FWCore/Services/plugins/Tracer.cc
  FWCore/Services/plugins/tracer_setupFile.cc
  FWCore/Services/scripts/README.md
  FWCore/Services/scripts/edmTracerCompactLogViewer.py
  FWCore/Services/scripts/edmTracerLogToSimpleConfig.py
  FWCore/Services/web/README.md
  FWCore/Services/web/index.html
  FWCore/Services/web/transitions.css
  FWCore/Services/web/transitions.js
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43210 Phase 2 L1 cmsDriver/Menu Infrastructure
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/StandardSequences/python/SimPhase2L1GlobalTriggerEmulator_cff.py
  L1Trigger/Configuration/python/Phase2GTMenus/SeedDefinitions/prototypeSeeds.py
  L1Trigger/Configuration/python/Phase2GTMenus/prototype_2023_v1_0_0.py
  L1Trigger/Configuration/python/SimPhase2L1GlobalTrigger_cff.py
Labels: l1-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43137 migrate `JetMETDQMDCSFilter` to use `DSCRecord`
  DQMOffline/JetMET/interface/JetMETDQMDCSFilter.h
  DQMOffline/JetMET/src/JetMETDQMDCSFilter.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#43197 Add SimBeamSpotObject record to Run-1/2/3 MC GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43222 [13.2.X] customize HLT offline DQM for Run3 PbPb and introduce HI 2023A relval workflow (with reHLT)
  Configuration/EventContent/python/EventContent_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  DQMOffline/Trigger/python/PrimaryVertexMonitoring_cff.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_Cluster_cff.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_TrackCluster_cff.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/SiStrip_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/TrackToTrackMonitoring_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_Client_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_cff.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#43125 Drop local copy of conifer.h in favor of conifer external
  L1Trigger/Phase2L1ParticleFlow/BuildFile.xml
  L1Trigger/Phase2L1ParticleFlow/interface/conifer.h
  L1Trigger/Phase2L1ParticleFlow/interface/egamma/pftkegalgo_ref.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved

#43200 Run3-hcx354 Modify the DetId fo ZDC to accommodate the changes that happened during Run3 and some provision for the future
  DataFormats/HcalDetId/interface/HcalZDCDetId.h
  DataFormats/HcalDetId/src/HcalZDCDetId.cc
  DataFormats/HcalDetId/src/classes_def.xml
  Geometry/ForwardGeometry/interface/ZdcGeometry.h
  Geometry/ForwardGeometry/src/ZdcGeometry.cc
  Geometry/ForwardGeometry/src/ZdcHardcodeGeometryLoader.cc
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#43177 fix for tracks with two ETL hits and no time assigned
  RecoMTD/TrackExtender/plugins/TrackExtenderWithMTD.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43196 Phase2-hgx348C Update HGCSiliconDetId in view of adding a fourth type of wafer: high density but thicker
  DataFormats/ForwardDetId/interface/HGCSiliconDetId.h
  DataFormats/ForwardDetId/src/HGCSiliconDetIdToModule.cc
  DataFormats/ForwardDetId/test/testHGCDetId.cc
  Geometry/HGCalCommonData/test/HGCalPartialWaferTester.cc
  Geometry/HGCalCommonData/test/HGCalValidHexTester.cc
  Geometry/HGCalGeometry/src/HGCalMouseBite.cc
  Geometry/HGCalGeometry/test/HGCalGeometryMouseBiteTester.cc
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43198 Add superclusterEta of photon in NANOAOD
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#43202 APE tool: Hit validation plots added
  Alignment/APEEstimation/test/plottingTools/granularity.py
  Alignment/APEEstimation/test/plottingTools/validationPlotter.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43204 Make AlpakaTest tests to use their dependencies for controlling their execution, and extend module tests to ROCm.
  HeterogeneousCore/AlpakaCore/README.md
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaGlobalProducer.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaGlobalProducerOffset.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaStreamProducer.cc
  HeterogeneousCore/AlpakaTest/test/BuildFile.xml
  HeterogeneousCore/AlpakaTest/test/testAlpakaModules.sh
  HeterogeneousCore/AlpakaTest/test/testAlpakaModulesHostAndDevice_cfg.py
  HeterogeneousCore/AlpakaTest/test/testAlpakaModules_cfg.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#43216 Improve calo particle debugging
  SimGeneral/Debugging/plugins/CaloParticleDebugger.cc
  SimGeneral/Debugging/python/caloParticleDebugger_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43219 Implement ROOT read rules for PortableHostCollection
  DataFormats/Portable/BuildFile.xml
  DataFormats/Portable/README.md
  DataFormats/Portable/interface/PortableHostCollection.h
  DataFormats/Portable/interface/PortableHostCollectionReadRules.h
  DataFormats/PortableTestObjects/src/classes.cc
  DataFormats/PortableTestObjects/src/classes_def.xml
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#43225 Adds protection against name collision to SoA internal variables.
  DataFormats/SoATemplate/interface/SoALayout.h
  DataFormats/SoATemplate/interface/SoAView.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#43232 Run3-alca247 Update the macro which has analyzed momentum dependence in the extraction of depth-dependent correction factors using isolated charged hadrons
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43243 [SIM] Fixed ZDC simulation
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/src/SteppingAction.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43158 Implementation of DeepTau SONIC producers
  Configuration/ProcessModifiers/python/allSonicTriton_cff.py
  Configuration/ProcessModifiers/python/deepTauSonicTriton_cff.py
  RecoTauTag/RecoTau/BuildFile.xml
  RecoTauTag/RecoTau/interface/DeepTauIdBase.h
  RecoTauTag/RecoTau/plugins/BuildFile.xml
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/plugins/DeepTauIdSONIC.cc
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: reconstruction-pending, operations-approved, pending-signatures, tests-approved, orp-approved, requires-external, code-checks-approved

#43221 [13.3.X] customize HLT offline DQM for Run3 PbPb and introduce HI 2023A relval workflow (with reHLT)
  Configuration/EventContent/python/EventContent_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  DQMOffline/Trigger/python/PrimaryVertexMonitoring_cff.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_Cluster_cff.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_TrackCluster_cff.py
  DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/SiStrip_OfflineMonitoring_cff.py
  DQMOffline/Trigger/python/TrackToTrackMonitoring_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_Client_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_cff.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#43217 Vertex smearing for PbPb MC based on 2023 PbPb data
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealistic2023PbPbCollision_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43234 ECAL : DB PayloadInspector modification
  CondCore/EcalPlugins/plugins/EcalPedestals_PayloadInspector.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, ecal

#43241 Implement ROOT read rules for PortableHostCollection [13.3.x]
  DataFormats/Portable/BuildFile.xml
  DataFormats/Portable/README.md
  DataFormats/Portable/interface/PortableHostCollection.h
  DataFormats/Portable/interface/PortableHostCollectionReadRules.h
  DataFormats/PortableTestObjects/src/classes.cc
  DataFormats/PortableTestObjects/src/classes_def.xml
Labels: fully-signed, tests-approved, orp-approved, backport-ok, heterogeneous-approved

#43230 [13.3.X] migrate `JetMETDQMDCSFilter` to use `DSCRecord`
  DQMOffline/JetMET/interface/JetMETDQMDCSFilter.h
  DQMOffline/JetMET/src/JetMETDQMDCSFilter.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#43215 [13_3_X] Add SimBeamSpotObject record to Run-1/2/3 MC GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43209 [CMSSW_13_3_X Backport] Add superclusterEta of photon in NanoAOD
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#43207 Phase2-hgx348D Update HGCSiliconDetId in view of adding a fourth type of wafer: high density but thicker (backport of #43196)
  DataFormats/ForwardDetId/interface/HGCSiliconDetId.h
  DataFormats/ForwardDetId/src/HGCSiliconDetIdToModule.cc
  DataFormats/ForwardDetId/test/testHGCDetId.cc
  Geometry/HGCalCommonData/test/HGCalPartialWaferTester.cc
  Geometry/HGCalCommonData/test/HGCalValidHexTester.cc
  Geometry/HGCalGeometry/src/HGCalMouseBite.cc
  Geometry/HGCalGeometry/test/HGCalGeometryMouseBiteTester.cc
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#43206 Run3-hcx354X Modify the DetId fo ZDC to accommodate the changes that happened during Run3 and some provision for the future (backport of #43200)
  CondTools/Hcal/test/pfcuts_db_io_test.sh
  DataFormats/HcalDetId/interface/HcalZDCDetId.h
  DataFormats/HcalDetId/src/HcalZDCDetId.cc
  DataFormats/HcalDetId/src/classes_def.xml
  Geometry/ForwardGeometry/interface/ZdcGeometry.h
  Geometry/ForwardGeometry/src/ZdcGeometry.cc
  Geometry/ForwardGeometry/src/ZdcHardcodeGeometryLoader.cc
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, db-approved, orp-approved

#42990 Fix ratio plot for uGT data-emulator mismatches
  DQM/L1TMonitor/interface/L1TdeStage2uGT.h
  DQM/L1TMonitor/src/L1TdeStage2uGT.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43050 Minor CLUE3D optimization
  RecoHGCal/TICL/plugins/PatternRecognitionbyCLUE3D.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, hgcal-dpg-approved

#43223 Run3-hcx355 Trying out the most recent zdc description in the setup
  Geometry/ForwardCommonData/python/GeometryExtended2021Reco_cff.py
  Geometry/ForwardCommonData/python/cmsExtendedGeometry2021XML_cfi.py
  SimG4CMS/Calo/plugins/ZDCSimHitStudy.cc
  SimG4CMS/Calo/python/PythiaMinBias_cfi.py
  SimG4CMS/Calo/test/python/runZDCStudy_cfg.py
  SimG4CMS/Calo/test/python/zdcRun3_cfg.py
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43273 [14_0_X SIM] Allowed MT mode for RHStopTracer of R-hadron simulation
  SimG4Core/CustomPhysics/interface/RHStopTracer.h
  SimG4Core/CustomPhysics/plugins/RHStopTracer.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#43205 Introduce new utilities for writing Alpaka kernels
  HeterogeneousCore/AlpakaInterface/interface/workdivision.h
  HeterogeneousCore/AlpakaInterface/test/alpaka/testKernel.dev.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#43229 Add Alpaka Process Modifier
  Configuration/ProcessModifiers/python/alpaka_cff.py
  Configuration/StandardSequences/python/Accelerators_cff.py
  Configuration/StandardSequences/python/Services_cff.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43280 Introduce new utilities for writing Alpaka kernels [13.3.x]
  HeterogeneousCore/AlpakaInterface/interface/workdivision.h
  HeterogeneousCore/AlpakaInterface/test/alpaka/testKernel.dev.cc
Labels: fully-signed, tests-approved, orp-approved, backport-ok, heterogeneous-approved

#43253 Revert decrease of precision introduced in ea3f693d
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#43288 [13_2_X] Vertex smearing for PbPb MC based on 2023 PbPb data
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealistic2023PbPbCollision_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#43274 Change Sonic to use ExternalFailure exception
  HeterogeneousCore/SonicCore/src/SonicClientBase.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#43275 Add Correct EGM Run3 electron NonIso MVA ID for EB
  RecoEgamma/ElectronIdentification/data/ElectronIDVariablesRun3NonIso.txt
  RecoEgamma/ElectronIdentification/python/FWLite.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_RunIIIWinter22_noIso_V1_cff.py
  RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_tools.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, egamma

#43254 Revert decrease of precision introduced in ea3f693d
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#43287 [13_3_X] Vertex smearing for PbPb MC based on 2023 PbPb data
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealistic2023PbPbCollision_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43247 Add CaloIdL_MW seeded filter and split the legs of CaloIdL_TrackIdL_IsoVL filter on nanoAOD filterBits
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, egamma

#42664 PPS full simulation with beam spot information deom SimBeamSpotObjects
  SimTransport/PPSProtonTransport/interface/HectorTransport.h
  SimTransport/PPSProtonTransport/interface/OpticalFunctionsTransport.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#42711 PPS - RawToDigi update to handle mappings from CondDB
  DQM/CTPPS/test/strip_dqm_test_xml_cfg.py
  EventFilter/CTPPSRawToDigi/interface/CTPPSPixelDataFormatter.h
  EventFilter/CTPPSRawToDigi/interface/CTPPSPixelRawToDigi.h
  EventFilter/CTPPSRawToDigi/interface/CTPPSRawToDigiErrorSummary.h
  EventFilter/CTPPSRawToDigi/plugins/CTPPSPixelDigiToRaw.cc
  EventFilter/CTPPSRawToDigi/plugins/TotemVFATRawToDigi.cc
  EventFilter/CTPPSRawToDigi/python/ctppsRawToDigi_cff.py
  EventFilter/CTPPSRawToDigi/python/ctppsRawToDigi_xml_cff.py
  EventFilter/CTPPSRawToDigi/src/CTPPSPixelDataFormatter.cc
  EventFilter/CTPPSRawToDigi/src/CTPPSRawToDigiErrorSummary.cc
Labels: alca-approved, dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, ctpps

#43226 Add PPS DAQ mapping to 13_3_X real data Run2 and Run3 GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#43157 Replace C-style array with std::array in HLTHPDFilter
  HLTrigger/JetMET/src/HLTHPDFilter.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43237 Run3-hcx356 Include the updated XML file for ZDC to the 2023 scenario for CMS
  Configuration/Geometry/README.md
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023ZeroMaterialXML_cfi.py
  Geometry/ForwardCommonData/data/zdc/2026/v2/zdc.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43259 MTD validation: add plugin to monitor impact of MTD on electron isolation
  Validation/Configuration/python/mtdSimValid_cff.py
  Validation/MtdValidation/plugins/MtdEleIsoHarvester.cc
  Validation/MtdValidation/plugins/MtdEleIsoValidation.cc
  Validation/MtdValidation/python/MtdPostProcessor_cff.py
  Validation/MtdValidation/scripts/ROC_plotter.py
  Validation/MtdValidation/test/mtdHarvesting_cfg.py
  Validation/MtdValidation/test/mtdValidation_cfg.py
Labels: dqm-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43268 [ALIGNMENT] Fix DEVEL warnings on deprecated copy-constructors
  Alignment/OfflineValidation/interface/PrepareDMRTrends.h
  Alignment/OfflineValidation/src/PlotAlignmentValidation.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43269 Fix testCSCTriggerMapping test: avoid reading invalid data e.g empty line
  CondFormats/CSCObjects/src/CSCTriggerMappingFromFile.cc
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#43270 [RECO] Fix DEVEL warnings on deprecated copy-constructors
  DataFormats/CaloRecHit/interface/CaloID.h
  DataFormats/ParticleFlowReco/interface/PFCluster.h
  DataFormats/ParticleFlowReco/interface/PFTrajectoryPoint.h
  DataFormats/ParticleFlowReco/src/PFCluster.cc
  DataFormats/ParticleFlowReco/src/PFTrajectoryPoint.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43265 Fix BeamSpotRcdRead_cfg and add unitTest
  CondTools/BeamSpot/test/BeamSpotRcdRead_cfg.py
  CondTools/BeamSpot/test/testReadWriteBeamSpotsFromDB.sh
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, tracking

#43272 ECAL : DB PayloadInspector improvement
  CondCore/EcalPlugins/plugins/EcalIntercalibConstantsMC_PayloadInspector.cc
  CondCore/EcalPlugins/plugins/EcalIntercalibConstants_PayloadInspector.cc
  CondCore/EcalPlugins/plugins/EcalIntercalibErrors_PayloadInspector.cc
  CondCore/EcalPlugins/plugins/EcalLaserAPDPNRatiosRef_PayloadInspector.cc
  CondCore/EcalPlugins/plugins/EcalLaserAPDPNRatios_PayloadInspector.cc
  CondCore/EcalPlugins/plugins/EcalLaserAlphas_PayloadInspector.cc
  CondCore/EcalPlugins/plugins/EcalPFRecHitThresholds_PayloadInspector.cc
  CondCore/EcalPlugins/plugins/EcalPedestals_PayloadInspector.cc
  CondCore/EcalPlugins/plugins/EcalTimeCalibConstants_PayloadInspector.cc
  CondCore/EcalPlugins/plugins/EcalTimeCalibErrors_PayloadInspector.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, ecal

#43277 Delete alca legacy module types, cleanup
  CalibMuon/CSCCalibration/test/Compare_template.txt
  CondFormats/CSCObjects/test/stubs/CSCGasGainCorrectionDBReadAnalyzer.cc
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#43279 Delete references to legacy module types in DQM.
  DQM/CSCMonitorModule/plugins/CSCOfflineClient.h
  DQM/HcalTasks/plugins/OnlineDQMDigiAD_cmssw.cc
  DQM/Physics/src/EwkMuDQM.h
  DQMOffline/L1Trigger/interface/L1TBeamConfiguration.h
  DQMOffline/L1Trigger/interface/L1TLSBlock.h
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43281 SoA fixes (2nd round): fix and add broken / missing SoA (const) row-to-row assignment.
  DataFormats/SoATemplate/README.md
  DataFormats/SoATemplate/interface/SoACommon.h
  DataFormats/SoATemplate/interface/SoAView.h
  DataFormats/SoATemplate/test/BuildFile.xml
  DataFormats/SoATemplate/test/SoAUnitTests.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#43283 Remove try/catch clause in castor analyzer
  CalibCalorimetry/CastorCalib/src/CastorLedAnalysis.cc
  CalibCalorimetry/CastorCalib/src/CastorPedestalAnalysis.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43284 Run3-sim152 Restore the Run1 code for ZDC hit production using a library parametrisation which can be switched on through parameter setting
  SimG4CMS/Forward/interface/ZdcSD.h
  SimG4CMS/Forward/src/ZdcSD.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43298 Allow Alpaka ESProducer to produce a 'null' data product
  HeterogeneousCore/AlpakaCore/interface/alpaka/ESProducer.h
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaESProducerNull.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaGlobalProducerNullES.cc
  HeterogeneousCore/AlpakaTest/test/testAlpakaModules_cfg.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#43303 [CalibFormats] Remove explicit copy-assignment operator
  CalibFormats/SiPixelObjects/interface/PixelHdwAddress.h
  CalibFormats/SiPixelObjects/interface/PixelModuleName.h
  CalibFormats/SiPixelObjects/interface/PixelROCName.h
  CalibFormats/SiPixelObjects/src/PixelHdwAddress.cc
  CalibFormats/SiPixelObjects/src/PixelModuleName.cc
  CalibFormats/SiPixelObjects/src/PixelROCName.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43309 [13_0_X SIM] Allowed MT mode for RHStopTracer of R-hadron simulation
  SimG4Core/CustomPhysics/interface/RHStopTracer.h
  SimG4Core/CustomPhysics/plugins/RHStopTracer.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43308 [12_4_X SIM] Allowed MT mode for RHStopTracer of R-hadron simulation
  SimG4Core/CustomPhysics/interface/RHStopTracer.h
  SimG4Core/CustomPhysics/plugins/RHStopTracer.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43292 [CMSSW_13_3_X backport] Add CaloIdL_MW seeded filter and split the legs of CaloIdL_TrackIdL_IsoVL filter on nanoAOD filterBits
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved, egamma

#43146 [mkFit] Propagate to plane -- technical changes to support further development
  RecoTracker/MkFit/plugins/MkFitGeometryESProducer.cc
  RecoTracker/MkFitCore/interface/Config.h
  RecoTracker/MkFitCore/interface/TrackerInfo.h
  RecoTracker/MkFitCore/src/KalmanUtilsMPlex.cc
  RecoTracker/MkFitCore/src/KalmanUtilsMPlex.h
  RecoTracker/MkFitCore/src/Matrix.h
  RecoTracker/MkFitCore/src/MkBuilder.cc
  RecoTracker/MkFitCore/src/MkFinder.cc
  RecoTracker/MkFitCore/src/MkFinder.h
  RecoTracker/MkFitCore/src/PropagationMPlex.cc
  RecoTracker/MkFitCore/src/PropagationMPlex.h
  RecoTracker/MkFitCore/src/PropagationMPlex.icc
Labels: reconstruction-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved, tracking

#43291 add verbose option to `BeamSpotRcdPrinter` and use it in the unit tests
  CondTools/BeamSpot/plugins/BeamSpotRcdPrinter.cc
  CondTools/BeamSpot/test/BeamSpotRcdPrinter_cfg.py
  CondTools/BeamSpot/test/testReadWriteBeamSpotsFromDB.sh
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, tracking

#43324 Do not use `size() - 1` in `HLTL1TMatchedJetsVBFFilter`
  HLTrigger/JetMET/plugins/HLTL1TMatchedJetsVBFFilter.h
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#43326 Do not use `size() - 1` in `HLTL1TMatchedJetsVBFFilter` [`13_2_X`]
  HLTrigger/JetMET/plugins/HLTL1TMatchedJetsVBFFilter.h
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport

#43325 Do not use `size() - 1` in `HLTL1TMatchedJetsVBFFilter` [`13_3_X`]
  HLTrigger/JetMET/plugins/HLTL1TMatchedJetsVBFFilter.h
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#43025 Adapt PF code to read Hcal thresholds from GT
  Configuration/Eras/python/Era_Run3_cff.py
  Configuration/Eras/python/Modifier_hcalPfCutsFromDB_cff.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltParticleFlowClusterECALUncorrectedL1Seeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltParticleFlowClusterECALUncorrectedUnseeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltParticleFlowClusterHBHE_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltParticleFlowClusterHCAL_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltParticleFlowRecHitHBHE_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/particleFlowClusterECALUncorrected_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/particleFlowClusterHF_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/particleFlowClusterHGCalFromTICLL1Seeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/particleFlowClusterHGCalFromTICLUnseeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/particleFlowClusterHGCal_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/particleFlowClusterHO_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/particleFlowRecHitHF_cfi.py
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  RecoLocalCalo/HcalRecAlgos/plugins/HcalChannelPropertiesEP.cc
  RecoParticleFlow/PFClusterProducer/interface/InitialClusteringStepBase.h
  RecoParticleFlow/PFClusterProducer/interface/PFCPositionCalculatorBase.h
  RecoParticleFlow/PFClusterProducer/interface/PFClusterBuilderBase.h
  RecoParticleFlow/PFClusterProducer/interface/PFRecHitQTests.h
  RecoParticleFlow/PFClusterProducer/interface/SeedFinderBase.h
  RecoParticleFlow/PFClusterProducer/plugins/Basic2DClusterForEachSeed.cc
  RecoParticleFlow/PFClusterProducer/plugins/Basic2DGenericPFlowClusterizer.cc
  RecoParticleFlow/PFClusterProducer/plugins/Basic2DGenericPFlowPositionCalc.cc
  RecoParticleFlow/PFClusterProducer/plugins/Basic2DGenericTopoClusterizer.cc
  RecoParticleFlow/PFClusterProducer/plugins/Cluster3DPCACalculator.cc
  RecoParticleFlow/PFClusterProducer/plugins/ECAL2DPositionCalcWithDepthCorr.cc
  RecoParticleFlow/PFClusterProducer/plugins/LocalMaximumSeedFinder.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFClusterFromHGCalTrackster.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFClusterProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFMultiDepthClusterProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFMultiDepthClusterizer.cc
  RecoParticleFlow/PFClusterProducer/plugins/PFlow2DClusterizerWithTime.cc
  RecoParticleFlow/PFClusterProducer/plugins/PassThruSeedFinder.cc
  RecoParticleFlow/PFClusterProducer/plugins/SimMappers/GenericSimClusterMapper.cc
  RecoParticleFlow/PFClusterProducer/plugins/SimMappers/RealisticSimClusterMapper.cc
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterECALUncorrected_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHBHE_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHCAL_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHF_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHGC_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHO_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowClusterPS_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitHBHE_cfi.py
  RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitHF_cfi.py
Labels: hlt-approved, operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, pf

#43327 Add HLT-Scouting collections to `MINIAOD` event content (follow-up of #42863)
  Configuration/EventContent/python/EventContent_cff.py
  HLTrigger/Configuration/python/HLTrigger_EventContent_cff.py
  HLTrigger/Configuration/test/getEventContent.py
Labels: hlt-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43290 [13_0_X] Vertex smearing for PbPb MC based on 2023 PbPb data
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealistic2023PbPbCollision_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43289 [13_1_X] Vertex smearing for PbPb MC based on 2023 PbPb data
  Configuration/StandardSequences/python/VtxSmeared.py
  IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRealistic2023PbPbCollision_cfi.py
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, orp-approved, backport-ok

#42818 ZDC trigger primitive emulation and HCAL look up table generation
  CalibCalorimetry/HcalTPGAlgos/interface/HcaluLUTTPGCoder.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  CalibFormats/HcalObjects/interface/HcalTPGCoder.h
  CalibFormats/HcalObjects/src/HcalTPGCoder.cc
  CaloOnlineTools/HcalOnlineDb/interface/HcalLutManager.h
  CaloOnlineTools/HcalOnlineDb/src/HcalLutManager.cc
  Geometry/HcalTowerAlgo/interface/HcalTrigTowerGeometry.h
  Geometry/HcalTowerAlgo/src/HcalTrigTowerGeometry.cc
  L1Trigger/L1TZDC/plugins/L1TZDCProducer.cc
  L1Trigger/L1TZDC/python/etSumZdcAnalyzer_cfi.py
  L1Trigger/L1TZDC/python/etSumZdcProducer_cfi.py
  L1Trigger/L1TZDC/test/L1TZDCProducerV1.cc
  L1Trigger/L1TZDC/test/README
  L1Trigger/L1TZDC/test/etSumZDCProducerV1_cfi.py
  SimCalorimetry/HcalTrigPrimAlgos/interface/HcalTriggerPrimitiveAlgo.h
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalTriggerPrimitiveAlgo.cc
Labels: alca-approved, geometry-approved, l1-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#43144 [JMENano] Fix GenJetIdx for AK4 jets matched to low pt genjets
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#43263 Avoid unnecessary Framework delays closing luminosity blocks (simple version)
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/LuminosityBlockProcessingStatus.h
  FWCore/Integration/test/testLateLumiClosure_cfg.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43267 Run3-sim151 Modify the run script for the SIM step to get hits in the ZDC
  SimG4Core/Application/python/g4SimHits_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43282 remove try/catch clause on accessing vertex collection
  Alignment/OfflineValidation/plugins/PrimaryVertexValidation.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43311 Run3-sim153 Reorganize the codes relevant to forward detectors among Calo and Forward projects in SimG4CMS
  SimG4CMS/Forward/macro/MakeZDCPlots.C
  SimG4CMS/Forward/plugins/ZDCSimHitStudy.cc
  SimG4CMS/Forward/test/python/runZDCStudy_cfg.py
  SimG4CMS/Forward/test/python/zdcRun3_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43313 Fix array-bounds warning in DTMuonMillepede
  Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43315 Remove explicit copy-constructor from TotemTimingDigi
  DataFormats/CTPPSDigi/interface/TotemTimingDigi.h
  DataFormats/CTPPSDigi/interface/TotemTimingEventInfo.h
  DataFormats/CTPPSDigi/src/TotemTimingDigi.cc
  DataFormats/CTPPSDigi/src/TotemTimingEventInfo.cc
Labels: reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43316 [XPOG][RECO] Fix DEVEL warnings on deprecated copy-constructors
  DataFormats/PatCandidates/interface/PFIsolation.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#43320 cleanup classlib string List/Format usage
  DQMServices/Components/plugins/EDMtoMEConverter.cc
  DQMServices/Core/BuildFile.xml
  DQMServices/Core/interface/DQMNet.h
  DQMServices/Core/src/DQMNet.cc
  DQMServices/Core/src/DQMService.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43321 [14_0_X SIM] Replace deprecated method
  SimG4Core/Application/src/LowEnergyFastSimModel.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43328 Fix tracer log viewer issue with callID
  FWCore/Services/scripts/edmTracerCompactLogViewer.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43331 Add HLT-Scouting collections to `MINIAOD` event content (follow-up of #42863) [`13_3_X`]
  Configuration/EventContent/python/EventContent_cff.py
  HLTrigger/Configuration/python/HLTrigger_EventContent_cff.py
  HLTrigger/Configuration/test/getEventContent.py
Labels: hlt-approved, operations-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43340 update `totemT2NewDigi_reco_cfg.py` to get DAQ mapping from conditions DB
  RecoPPS/Local/test/totemT2NewDigi_reco_cfg.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43065 Fixes/impovements towards the first production version of the custom muon DPG NANO
  Configuration/PyReleaseValidation/python/relval_nano.py
  DPGAnalysis/MuonTools/plugins/MuCSCTnPFlatTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuDTMuonExtTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuGEMMuonExtTableProducer.cc
  DPGAnalysis/MuonTools/python/muNtupleProducerBkg_cff.py
  DPGAnalysis/MuonTools/python/muNtupleProducer_cff.py
  DPGAnalysis/MuonTools/python/nano_mu_global_cff.py
  DPGAnalysis/MuonTools/python/nano_mu_local_reco_cff.py
  PhysicsTools/NanoAOD/plugins/BuildFile.xml
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/python/autoNANO.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved

#43112 [HGCAL trigger] Additional cluster shape variables
  DataFormats/L1THGCal/interface/HGCalClusterT.h
  DataFormats/L1THGCal/src/classes_def.xml
  L1Trigger/L1THGCal/interface/backend/HGCalShowerShape.h
  L1Trigger/L1THGCal/src/backend/HGCalShowerShape.cc
  L1Trigger/L1THGCalUtilities/test/ntuples/HGCalTriggerNtupleHGCMulticlusters.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43261 Add relval for Herwig Matchbox
  Configuration/Generator/python/DY_TuneCH3_13TeV_herwig_madgraph_matchbox_cff.py
  Configuration/PyReleaseValidation/python/relval_extendedgen.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: generators-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#43271 Add L1 Upgrade Workflow: 0.78
  Configuration/PyReleaseValidation/README.md
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#43278 Phase 2 GTT TrackVertexAssociation Firmware limit
  L1Trigger/DemonstratorTools/interface/codecs/tracks.h
  L1Trigger/DemonstratorTools/src/codecs_tracks.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackVertexAssociationProducer.cc
  L1Trigger/L1TTrackMatch/python/l1tTrackVertexAssociationProducer_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43296 Print the labels of ConditionalTask modules that are not consumed in any of the associated Paths
  FWCore/Framework/interface/StreamSchedule.h
  FWCore/Framework/src/StreamSchedule.cc
  FWCore/Framework/test/BuildFile.xml
  FWCore/Framework/test/test_conditionaltasks_nonconsumed.sh
  FWCore/Framework/test/test_conditionaltasks_nonconsumed_cfg.py
  FWCore/Framework/test/unit_test_outputs/conditionaltasks_nonconsumed.log
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43330 follow-up to #43094, remove HLT tracking and vertexing validation harvesting from phase-2 modifier
  HLTriggerOffline/Common/python/HLTValidationHarvest_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#43332 Run3-alca248 Extend one more momentum bin to be studied in the calibration using isolated charged hadrons
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibPlotProperties.C
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43335 [SIMULATION] Fix DEVEL warnings on deprecated copy-constructors
  DataFormats/DTDigi/interface/DTDDUWords.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43337 Remove explicit assignment operator from edm::View
  DataFormats/Common/interface/View.h
  DataFormats/Common/src/View.cc
  DataFormats/Common/test/ptr_t.cppunit.cc
  DataFormats/Common/test/reftobaseprod_t.cppunit.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43342 Fixes needed for UB/ASANXX builds
  CommonTools/Utils/test/BuildFile.xml
  CondFormats/HcalObjects/BuildFile.xml
  FWCore/Services/test/BuildFile.xml
  FWCore/Services/test/test_resource_succeed_cfg.py
  PerfTools/AllocMonitor/test/BuildFile.xml
  Utilities/ReleaseScripts/test/BuildFile.xml
Labels: alca-approved, core-approved, reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#43350 [mkFit] Apply material effects after error propagation
  RecoTracker/MkFitCore/src/PropagationMPlex.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#43353 Update displacedRegional baseline workflow .701
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#43201 [12_4_X] Backport of new MCMultiSignatureFilter.cc
  GeneratorInterface/GenFilters/plugins/MCMultiSignatureFilter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved
