Repository cms-sw/cmssw, pull requests merged in 2023-12, with the labels that each got.

#43462 [RECONSTRUCTION] Define missing assignment operator to fix warnings reported in DEVEL IBs
  DataFormats/BTauReco/interface/TaggingVariable.h
  DataFormats/EgammaCandidates/interface/Photon.h
  DataFormats/METReco/interface/CorrMETData.h
  DataFormats/METReco/interface/HcalHaloData.h
  DataFormats/ParticleFlowReco/interface/PFTrack.h
  DataFormats/SiStripCommon/interface/SiStripFecKey.h
  DataFormats/SiStripCommon/interface/SiStripFedKey.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43461 [DAQ] Define missing assignment operator to fix warnings reported in DEVEL IBs
  DataFormats/FEDRawData/interface/FEDRawData.h
  DataFormats/FEDRawData/interface/FEDRawDataCollection.h
Labels: daq-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43460 [SIMULATION] Define missing assignment operator to fix warnings reported in DEVEL IBs
  DataFormats/GeometryVector/interface/private/Basic3DVectorLD.h
  DataFormats/GeometryVector/interface/private/sseBasic2DVector.h
  DataFormats/GeometryVector/interface/private/sseBasic3DVector.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43451 Update ROCm tools
  HeterogeneousCore/ROCmServices/plugins/ROCmService.cc
  HeterogeneousCore/ROCmUtilities/bin/rocmComputeCapabilities.cpp
  HeterogeneousCore/ROCmUtilities/interface/rsmiCheck.h
Labels: fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, heterogeneous-approved

#43447 Run3-gex175 Remove std::cout in favour of edm::LogVerbatim in Fireworks/Geometry
  Fireworks/Geometry/plugins/TGeoMgrFromDdd.cc
Labels: visualization-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43419 Run3-alca248Y Modify the macros to examine momentum dependence of the correction factors
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibPlotProperties.C
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43399 Fix deprecated-copy warnings in MagneticField/ParametrizedEngine
  MagneticField/ParametrizedEngine/src/rz_harm_poly.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43329 Migrate calotower code to use HCAL thresholds from GT
  RecoLocalCalo/CaloTowersCreator/python/calotowermaker_cfi.py
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersCreationAlgo.cc
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersCreationAlgo.h
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersCreator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#43418 Run3-gex174 Add RPD in the latest version of 2023 Gemetry as requested by the ZDC group for the next HI simulation effort
  Configuration/Geometry/README.md
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43445 Phase2-hcx359 Define modules for HFNose following the structure of updated HGCal (as in V17 version)
  Geometry/ForwardCommonData/data/hfnose/v5/hfnose.xml
  Geometry/ForwardCommonData/data/hfnoseCell/v2/hfnoseCell.xml
  Geometry/ForwardCommonData/data/hfnoseWafer/v2/hfnose.xml
  Geometry/ForwardCommonData/data/hfnoseWafer/v2/hfnoseWafer.xml
  Geometry/ForwardCommonData/data/hfnoseWafer/v2/hfnosepos.xml
  Geometry/ForwardCommonData/python/hfnoseWaferV1XML_cfi.py
  Geometry/ForwardCommonData/python/hfnoseWaferV2XML_cfi.py
  Geometry/ForwardCommonData/test/dumpHFNoseWafer_cfg.py
  Geometry/HGCalCommonData/data/hgcalMaterial/v3/hgcalMaterial.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43449 Phase2-hgx350 Make modifications for the HGCal version V18 in the case of mouse bite, guard rings, ...
  Geometry/HGCalCommonData/interface/HGCalCellUV.h
  Geometry/HGCalCommonData/interface/HGCalTypes.h
  Geometry/HGCalCommonData/interface/HGCalWaferMask.h
  Geometry/HGCalCommonData/src/HGCalCellUV.cc
  Geometry/HGCalCommonData/src/HGCalWaferMask.cc
  SimG4CMS/Calo/plugins/HGCalMouseBiteTester.cc
  SimG4CMS/Calo/src/HGCGuardRing.cc
  SimG4CMS/Calo/src/HGCGuardRingPartial.cc
  SimG4CMS/Calo/test/python/testHGCalMouseBite_cfg.py
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43459 [SIMULATION-UPGRADE] Define missing assignment operator to fix warnings reported in DEVEL IBs
  DataFormats/FTLDigi/interface/BTLSample.h
  DataFormats/FTLDigi/interface/ETLSample.h
  DataFormats/HGCDigi/interface/HGCSample.h
  DataFormats/HGCalDigi/interface/HGCROCChannelDataFrame.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43476 Add placeholders of phase2 geometry config files
  Configuration/Geometry/python/GeometryDD4hepExtended2026DefaultReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026Default_cff.py
  Configuration/Geometry/python/GeometryExtended2026DefaultReco_cff.py
  Configuration/Geometry/python/GeometryExtended2026Default_cff.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43435 Backport to 12_4_X for Py8PtExpGun
  Configuration/Generator/python/Py8Eta2MuGammaPtExpGun_cfi.py
  GeneratorInterface/Pythia8Interface/plugins/Py8PtExpGun.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved

#43452 BackPort of "Update ecalMultiFitUncalibRecHit_cfi.py' PR #43152
  RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, ecal

#43453 Trigger Filter Bit fixes for Run 3 (Tau Trigger Objects)
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#43481 [13.3.X] Fix `SiStripHashedDetId` constructor / operator and add more SiStripLorentzAngle PCL unit testings
  CalibFormats/SiStripObjects/interface/SiStripHashedDetId.h
  CalibFormats/SiStripObjects/src/SiStripHashedDetId.cc
  CalibFormats/SiStripObjects/test/BuildFile.xml
  CalibFormats/SiStripObjects/test/test_catch2_SiStripHashedDetId.cc
  CalibFormats/SiStripObjects/test/test_catch2_main.cc
  CalibTracker/SiStripLorentzAngle/interface/SiStripLorentzAngleCalibrationStruct.h
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLorentzAnglePCLMonitor.cc
  CalibTracker/SiStripLorentzAngle/test/BuildFile.xml
  CalibTracker/SiStripLorentzAngle/test/step_PromptCalibProdSiStripLA_cfg.py
  CalibTracker/SiStripLorentzAngle/test/testPromptCalibProdSiStripLA.sh
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#43465 [CORE] Define missing assignment operator to fix warnings reported in DEVEL IBs
  DataFormats/Common/interface/MapOfVectors.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43477 [14_0_X SIM] Improved initialisation of sensitive detectors Sens detectors
  SimG4Core/Application/plugins/OscarMTProducer.cc
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/SensitiveDetector/src/AttachSD.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43443 Run3-gex174C Backport the fix in #43418 on ZDC geometry to update the 2023 Run3 geometry to be used for te Heavy Ion MC
  Configuration/Geometry/README.md
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023XML_cfi.py
  Geometry/ForwardCommonData/data/rpd/2021/v1/rpd.xml
  Geometry/ForwardCommonData/data/zdc/2021/v3/zdc.xml
  Geometry/ForwardCommonData/plugins/DDRPDPosition.cc
  Geometry/ForwardCommonData/plugins/dd4hep/DDRPDPosition.cc
  Geometry/ForwardSimData/data/zdcProdCuts/2021/v3/zdcProdCuts.xml
  Geometry/ForwardSimData/data/zdcsens/2021/v1/zdcsens.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#43473 Miscellaneous updates to ` DQM/TrackingMonitorSource`
  DQM/TrackingMonitorSource/plugins/StandaloneTrackMonitor.cc
  DQM/TrackingMonitorSource/plugins/V0EventSelector.cc
  DQM/TrackingMonitorSource/plugins/V0VertexTrackProducer.cc
  DQM/TrackingMonitorSource/python/TrackingDataMCValidation_Standalone_cff.py
  DQM/TrackingMonitorSource/python/V0Selections_cfi.py
  DQM/TrackingMonitorSource/test/Tracker_DataMCValidation_cfg.py
  DQM/TrackingMonitorSource/test/testTrackingDATAMC.sh
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#43424 [GEM] Update for GEM pulse stretching simulation and minor bug fix
  CondFormats/GEMObjects/interface/GEMChMap.h
  EventFilter/GEMRawToDigi/plugins/GEMDigiToRawModule.cc
  EventFilter/GEMRawToDigi/python/gemPacker_cfi.py
  SimMuon/GEMDigitizer/plugins/GEMDigiProducer.cc
  SimMuon/GEMDigitizer/python/muonGEMDigis_cfi.py
  SimMuon/GEMDigitizer/src/GEMSignalModel.cc
Labels: reconstruction-approved, simulation-approved, fully-signed, tests-approved, db-approved, orp-approved, upgrade-approved, code-checks-approved

#43400 Fix deprecated-copy warnings in CondFormats/PhysicsToolsObjects and PhysicsTools/MVAComputer
  CondFormats/PhysicsToolsObjects/interface/MVAComputer.h
  PhysicsTools/MVAComputer/interface/Variable.h
Labels: alca-approved, analysis-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#43383 Monitoring of tau decay products in NanoDQM
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#43470 Trigger Filter Bit fixes for Run 3 (Tau Trigger Objects)
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#43500 Run3-sim152X Make changes which can handle both DDD and DD4hep inputs correctly
  SimG4Core/Application/src/GFlashHadronShowerModel.cc
  SimG4Core/Application/src/LowEnergyFastSimModel.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43489 Cleanup unnecessary include statements from L1Trigger/L1TMuonOverlapPhase1
  L1Trigger/L1TMuonOverlapPhase1/interface/Omtf/OMTFConfiguration.h
  L1Trigger/L1TMuonOverlapPhase1/src/Omtf/GoldenPattern.cc
  L1Trigger/L1TMuonOverlapPhase1/src/Omtf/OMTFSorter.cc
  L1Trigger/L1TMuonOverlapPhase1/src/Tools/DataROOTDumper2.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43480 Run3-alca248Z Modify the calibration code of HCAL to ignore the zside index and also change the name of some variables
  Calibration/HcalCalibAlgos/macros/CalibCorr.C
  Calibration/HcalCalibAlgos/macros/CalibFitPlots.C
  Calibration/HcalCalibAlgos/macros/CalibMonitor.C
  Calibration/HcalCalibAlgos/macros/CalibTree.C
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43448 Removing unnecessary try/catch clauses in Hcal{Led,Pedestal}Analysis.cc
  CalibCalorimetry/HcalAlgos/interface/HcalLedAnalysis.h
  CalibCalorimetry/HcalAlgos/interface/HcalPedestalAnalysis.h
  CalibCalorimetry/HcalAlgos/src/HcalLedAnalysis.cc
  CalibCalorimetry/HcalAlgos/src/HcalPedestalAnalysis.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43512 Update the DependencyGraph service
  FWCore/Services/plugins/DependencyGraph.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43511 Increase precision of photon variables to 10
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#43510 L1T o2o: fix int/2 bug
  L1TriggerConfig/L1TConfigProducers/src/L1TCaloParamsOnlineProd.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43493 [14_0_X SIM] Added ZDC transport as an option of FullSim for heavy ion simulation
  SimG4CMS/Forward/src/ZdcSD.cc
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/SteppingAction.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43513 Increase precision of photon variables to 10
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#43518 Phase2-hgx350Y Protection against segentation violation for V18 version of HGCal
  Geometry/HGCalCommonData/src/HGCalWaferMask.cc
  SimG4CMS/Calo/src/HGCGuardRing.cc
  SimG4CMS/Calo/src/HGCGuardRingPartial.cc
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#43540 NONLTO: Fix use after delete warning for bqueue
  RecoTracker/CkfPattern/interface/BaseCkfTrajectoryBuilder.h
  TrackingTools/PatternTools/interface/bqueue.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#43384 Tau decay products in NanoDQM
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/PatAlgos/plugins/PATTauSignalCandidatesProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, xpog-approved

#43494 [13_0_X SIM] Backport of ZDC transport modifier for heavy ion simulation modifier
  SimG4CMS/Forward/src/ZdcSD.cc
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/SteppingAction.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved

#43546 Run3-sim152Z Take care of difference between DDD and DD4hep in SteppingAction classes (replace the PR #43499)
  SimG4CMS/Calo/test/python/minbias2023_cfg.py
  SimG4Core/Application/interface/Phase2SteppingAction.h
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/Phase2SteppingAction.cc
  SimG4Core/Application/src/SteppingAction.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43528 Added transform info to Tracer Log
  FWCore/Framework/src/ProductResolvers.cc
  FWCore/Framework/src/WorkerT.cc
  FWCore/Services/plugins/monitor_file_utilities.h
  FWCore/Services/plugins/tracer_setupFile.cc
  FWCore/Services/scripts/edmTracerCompactLogViewer.py
  FWCore/Services/web/index.html
  FWCore/Services/web/transitions.css
  FWCore/Services/web/transitions.js
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43505 Add `BeamSpotOnlineShifter` class and related configuration
  CondCore/AlignmentPlugins/interface/AlignmentPayloadInspectorHelper.h
  CondTools/BeamSpot/plugins/BeamSpotOnlineShifter.cc
  CondTools/BeamSpot/plugins/BuildFile.xml
  CondTools/BeamSpot/test/BeamSpotOnlineShifter_cfg.py
  CondTools/BeamSpot/test/BuildFile.xml
  CondTools/BeamSpot/test/testShiftBeamSpotsFromDB.sh
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, tracking

#43245 emulator for Phase-2 GCT calo jets and taus
  DataFormats/L1TCalorimeterPhase2/interface/Phase2L1CaloJet.h
  DataFormats/L1TCalorimeterPhase2/src/classes.h
  DataFormats/L1TCalorimeterPhase2/src/classes_def.xml
  L1Trigger/L1CaloTrigger/interface/Phase2L1CaloJetEmulator.h
  L1Trigger/L1CaloTrigger/plugins/Phase2L1CaloJetEmulator.cc
  L1Trigger/L1CaloTrigger/python/l1tPhase2CaloJetEmulator_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43539 [Backport to 133X] Adding Two Secondary Datasets for JME POG
  Configuration/Skimming/python/PDWG_EGMJME_SD_cff.py
  Configuration/Skimming/python/PDWG_MUOJME_SD_cff.py
  Configuration/Skimming/python/Skims_PDWG_cff.py
  Configuration/Skimming/python/autoSkim.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, backport-ok

#43538 [Backport to 130X] Adding Two Secondary Datasets for JME POG
  Configuration/Skimming/python/PDWG_EGMJME_SD_cff.py
  Configuration/Skimming/python/PDWG_MUOJME_SD_cff.py
  Configuration/Skimming/python/Skims_PDWG_cff.py
  Configuration/Skimming/python/autoSkim.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, backport-ok

#43407 ETL Geometry V8
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2026D105Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2026D105_cff.py
  Configuration/Geometry/python/GeometryExtended2026D105Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2026D105_cff.py
  Configuration/Geometry/python/dict2026Geometry.py
  Configuration/PyReleaseValidation/python/relval_2026.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/GeometryConf.py
  DataFormats/ForwardDetId/interface/ETLDetId.h
  DataFormats/ForwardDetId/src/ETLDetId.cc
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D105.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D105XML_cfi.py
  Geometry/MTDCommonData/data/etl/v8/etl.xml
  Geometry/MTDCommonData/data/mtdParameters/v5/mtdParameters.xml
  Geometry/MTDCommonData/data/mtdParameters/v5/mtdStructureTopology.xml
  Geometry/MTDCommonData/interface/MTDTopologyMode.h
  Geometry/MTDCommonData/src/ETLNumberingScheme.cc
  Geometry/MTDCommonData/src/MTDTopologyMode.cc
  Geometry/MTDGeometryBuilder/src/MTDParametersFromDD.cc
  Geometry/MTDNumberingBuilder/plugins/CmsMTDConstruction.cc
  Geometry/MTDNumberingBuilder/plugins/CmsMTDConstruction.h
  Geometry/MTDNumberingBuilder/plugins/DDCmsMTDConstruction.cc
  Geometry/MTDNumberingBuilder/src/CmsMTDStringToEnum.cc
  Geometry/MTDNumberingBuilder/src/MTDTopology.cc
  Geometry/MTDSimData/data/v5/mtdProdCuts.xml
  Geometry/MTDSimData/data/v5/mtdsens.xml
  RecoMTD/DetLayers/src/ETLDetLayerGeometryBuilder.cc
  RecoMTD/DetLayers/src/MTDDetLayerGeometry.cc
  SimFastTiming/FastTimingCommon/src/ETLDeviceSim.cc
Labels: geometry-approved, operations-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#43378 Run3 era for 2023 PbPb UPC re-reco
  Configuration/Eras/python/Era_Run3_2023_UPC_cff.py
  Configuration/Eras/python/Modifier_run3_upc_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/Eras.py
  Configuration/StandardSequences/python/Reconstruction_cff.py
  PhysicsTools/PatAlgos/python/selectionLayer1/lowPtElectronSelector_cfi.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/isolatedTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/lostTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/slimming/packedPFCandidates_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimmedCaloJets_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSeeds_cfi.py
  RecoHI/HiCentralityAlgos/python/HiCentrality_cfi.py
  RecoHI/HiTracking/python/HILowPtConformalPixelTracks_cfi.py
  RecoJets/Configuration/python/RecoJets_EventContent_cff.py
  RecoTracker/Configuration/python/RecoTracker_EventContent_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoTracker/TkSeedGenerator/python/trackerClusterCheck_cfi.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved, tracking

#43561 [14_0 Bug Fix] Remove GenFilter when pgen_smear is used.
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#43563 Run3-sim153C Second level of cleanup of using methods from DD4hep in SimG4Core package
  SimG4Core/Application/interface/Phase2SteppingAction.h
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/Phase2SteppingAction.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
  SimG4Core/Application/src/SteppingAction.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43559 Implementation of the `DiMuonVertexValidation` in the TkAl all-in-one tool
  Alignment/OfflineValidation/bin/BuildFile.xml
  Alignment/OfflineValidation/bin/DiMuonVmerge.cc
  Alignment/OfflineValidation/interface/DiLeptonVertexHelpers.h
  Alignment/OfflineValidation/macros/loopAndPlot.C
  Alignment/OfflineValidation/plugins/DiMuonVertexValidation.cc
  Alignment/OfflineValidation/python/TkAlAllInOneTool/DiMuonV.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/DiMuonV_cfg.py
  Alignment/OfflineValidation/scripts/validateAlignments.py
  Alignment/OfflineValidation/test/BuildFile.xml
  Alignment/OfflineValidation/test/testingScripts/test_unitDiMuonV.sh
  Alignment/OfflineValidation/test/unit_test.json
  Alignment/OfflineValidation/test/unit_test.yaml
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43558 Run3-Sim153B First level of cleanup of using methods from DD4hep in SimG4CMS/Calo package
  SimG4CMS/Calo/BuildFile.xml
  SimG4CMS/Calo/interface/HCalSD.h
  SimG4CMS/Calo/src/CaloSD.cc
  SimG4CMS/Calo/src/HCalSD.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43557 Run3-sim153A Attempt to remove the dependence of DD4hep code to some of the packages in SimG4Core
  SimG4Core/Application/src/GFlashHadronShowerModel.cc
  SimG4Core/Application/src/LowEnergyFastSimModel.cc
  SimG4Core/Geometry/interface/DD4hep2DDDName.h
  SimG4Core/Geometry/src/DD4hep2DDDName.cc
  SimG4Core/PrintGeomInfo/plugins/PrintGeomInfoAction.cc
  SimG4Core/PrintGeomInfo/test/TouchFileCompare.cpp
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43553 MTD geometry: add BTL V3 (one crystal thickness only) to MTD scenario I17 (global scenario D105)
  Configuration/Geometry/README.md
  Configuration/Geometry/python/dict2026Geometry.py
  DataFormats/ForwardDetId/interface/BTLDetId.h
  DataFormats/ForwardDetId/src/BTLDetId.cc
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D105.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2026D105XML_cfi.py
  Geometry/MTDCommonData/data/btl/v3/btl.xml
  Geometry/MTDCommonData/data/mtdParameters/v5/mtdStructureTopology.xml
  Geometry/MTDCommonData/interface/BTLNumberingScheme.h
  Geometry/MTDCommonData/interface/MTDTopologyMode.h
  Geometry/MTDCommonData/src/BTLNumberingScheme.cc
  Geometry/MTDCommonData/src/MTDTopologyMode.cc
  Geometry/MTDGeometryBuilder/test/DD4hep_TestBTLPixelTopology.cc
  Geometry/MTDNumberingBuilder/src/MTDTopology.cc
  Geometry/MTDSimData/data/v5/mtdProdCuts.xml
  Geometry/MTDSimData/data/v5/mtdsens.xml
  RecoMTD/DetLayers/src/BTLDetLayerGeometryBuilder.cc
Labels: geometry-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43550 Miscellaneous improvements for generating and validating Phase2 SiPixel Lorentz Angle payloads
  CondCore/SiPixelPlugins/plugins/SiPixelLorentzAngle_PayloadInspector.cc
  CondTools/SiPixel/test/SiPixelLorentzAngleDBLoader_Phase2_cfg.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, trk

#43549 introduce `requireL3MuonTrajectorySeed` data member in `HLTMuonL3PreFilter` and use it do define whether or not to consume certain products
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc
  HLTrigger/Muon/plugins/HLTMuonL3PreFilter.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43542 Run3-Sim152Y Enable the code to handle DD4hep and DDD inputs simultaneously in SimTracker
  SimTracker/TrackerMaterialAnalysis/plugins/TrackingMaterialProducer.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43130 Add Alpaka Implementation of PFClusterProducer
  DataFormats/ParticleFlowReco/interface/PFClusterHostCollection.h
  DataFormats/ParticleFlowReco/interface/PFClusterSoA.h
  DataFormats/ParticleFlowReco/interface/PFRecHitFractionHostCollection.h
  DataFormats/ParticleFlowReco/interface/PFRecHitFractionSoA.h
  DataFormats/ParticleFlowReco/interface/alpaka/CaloRecHitDeviceCollection.h
  DataFormats/ParticleFlowReco/interface/alpaka/PFClusterDeviceCollection.h
  DataFormats/ParticleFlowReco/interface/alpaka/PFRecHitDeviceCollection.h
  DataFormats/ParticleFlowReco/interface/alpaka/PFRecHitFractionDeviceCollection.h
  DataFormats/ParticleFlowReco/src/alpaka/classes_cuda.h
  DataFormats/ParticleFlowReco/src/alpaka/classes_cuda_def.xml
  DataFormats/ParticleFlowReco/src/alpaka/classes_rocm.h
  DataFormats/ParticleFlowReco/src/alpaka/classes_rocm_def.xml
  DataFormats/ParticleFlowReco/src/classes_serial.h
  DataFormats/ParticleFlowReco/src/classes_serial_def.xml
  HeterogeneousCore/AlpakaInterface/interface/atomicMaxF.h
  RecoParticleFlow/PFClusterProducer/BuildFile.xml
  RecoParticleFlow/PFClusterProducer/interface/PFClusterParamsHostCollection.h
  RecoParticleFlow/PFClusterProducer/interface/PFClusterParamsSoA.h
  RecoParticleFlow/PFClusterProducer/interface/PFClusteringEdgeVarsSoA.h
  RecoParticleFlow/PFClusterProducer/interface/PFClusteringVarsSoA.h
  RecoParticleFlow/PFClusterProducer/interface/alpaka/PFClusterParamsDeviceCollection.h
  RecoParticleFlow/PFClusterProducer/interface/alpaka/PFClusteringEdgeVarsDeviceCollection.h
  RecoParticleFlow/PFClusterProducer/interface/alpaka/PFClusteringVarsDeviceCollection.h
  RecoParticleFlow/PFClusterProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFClusterProducer/plugins/LegacyPFClusterProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterECLCC.h
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterParamsESProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.dev.cc
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.h
  RecoParticleFlow/PFClusterProducer/python/particleFlowCluster_cff.py
  RecoParticleFlow/PFClusterProducer/python/pfClusterHBHEAlpaka_cff.py
  RecoParticleFlow/PFClusterProducer/src/PFClusterParamsHostCollection.cc
  RecoParticleFlow/PFClusterProducer/src/alpaka/PFClusterParamsDeviceCollection.cc
  RecoParticleFlow/PFClusterProducer/test/test_PFRecHitAndClusterSoA.py
  Validation/RecoParticleFlow/plugins/PFCaloGPUComparisonTask.cc
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved, pf

#43107 Allow TrackerMuons with only an ME0 segment match
  DataFormats/MuonReco/src/Muon.cc
  RecoLocalMuon/GEMSegment/plugins/GEMSegmentBuilder.cc
  RecoLocalMuon/GEMSegment/plugins/GEMSegmentBuilder.h
  RecoLocalMuon/GEMSegment/plugins/GEMSegmentProducer.cc
  RecoLocalMuon/GEMSegment/python/gemSegments_cfi.py
  RecoMuon/MuonIdentification/plugins/MuonIdProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43554 [13_0_HeavyIons_X SIM] Backport of ZDC simulation
  SimG4CMS/Forward/src/ZdcSD.cc
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/SteppingAction.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, urgent

#42725 GenFilter for selecting events with GenPhotons (based from right branch)
  GeneratorInterface/GenFilters/plugins/PhotonGenFilter.cc
  GeneratorInterface/GenFilters/plugins/PhotonGenFilter.h
  GeneratorInterface/GenFilters/python/PhotonGenFilter_cfi.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43562 [12_4 Bug Fix] Remove GenFilter when pgen_smear is used
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent

#43555 Integrate FED25 handling in electron online reconstruction
  RecoEgamma/EgammaElectronAlgos/src/TrajSeedMatcher.cc
  RecoTracker/MeasurementDet/plugins/TkPixelMeasurementDet.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking, egamma

#43529 Added additional entries to .gitignore
  .gitignore
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43589 Run3-SimG Cleanup in SimG4CMS/Muon against using codes directly from DD4hep
  SimG4CMS/Muon/BuildFile.xml
  SimG4CMS/Muon/src/MuonG4Numbering.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43588 Use likelihood fit instead of chi-square fit in PVValidation
  Alignment/OfflineValidation/src/PVValidationHelpers.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43586 Fix DQMOfflineConfiguration unit tests
  DQMOffline/Configuration/test/BuildFile.xml
  DQMOffline/Configuration/test/runrest.sh
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43585 Run3-Sim153F Cleanup in SimG4CMS/Calo against using codes directly from DD4hep
  SimG4CMS/Calo/BuildFile.xml
  SimG4CMS/Calo/src/CaloTrkProcessing.cc
  SimG4CMS/Calo/src/ECalSD.cc
  SimG4CMS/Calo/src/EcalDumpGeometry.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43583 Run3-Sim153D Cleanup in SimG4CMS/CherenkovAnalysis against using codes directly from DD4hep
  SimG4CMS/CherenkovAnalysis/BuildFile.xml
  SimG4CMS/CherenkovAnalysis/interface/DreamSD.h
  SimG4CMS/CherenkovAnalysis/src/DreamSD.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43580 mkFit: overlap area candidate re-check and start using the new hit selection V2 in pixelLess iteration
  RecoTracker/MkFitCMS/standalone/Shell.cc
  RecoTracker/MkFitCore/interface/IterationConfig.h
  RecoTracker/MkFitCore/interface/TrackStructures.h
  RecoTracker/MkFitCore/src/CandCloner.cc
  RecoTracker/MkFitCore/src/CandCloner.h
  RecoTracker/MkFitCore/src/FindingFoos.h
  RecoTracker/MkFitCore/src/HitStructures.cc
  RecoTracker/MkFitCore/src/IterationConfig.cc
  RecoTracker/MkFitCore/src/Matriplex/Matriplex.h
  RecoTracker/MkFitCore/src/Matriplex/MatriplexSym.h
  RecoTracker/MkFitCore/src/MkBuilder.cc
  RecoTracker/MkFitCore/src/MkFinder.cc
  RecoTracker/MkFitCore/src/MkFinder.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, tracking

#43579 Fix bug related to cmsRun exit code with FileReadError
  FWCore/Framework/src/ProductResolvers.cc
  IOPool/Input/test/testSchemaEvolution.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43576 [14_0_X SIM] Added Russian roulette to ZDC and optionally to HGCal
  SimG4CMS/Forward/interface/ZdcSD.h
  SimG4CMS/Forward/src/ZdcSD.cc
  SimG4Core/Application/interface/StackingAction.h
  SimG4Core/Application/interface/SteppingAction.h
  SimG4Core/Application/plugins/OscarMTProducer.cc
  SimG4Core/Application/python/g4SimHits_cfi.py
  SimG4Core/Application/src/EventAction.cc
  SimG4Core/Application/src/StackingAction.cc
  SimG4Core/Application/src/SteppingAction.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43441 Removed std::auto_ptr from Herwig7Interface
  GeneratorInterface/Herwig7Interface/interface/Herwig7Interface.h
  GeneratorInterface/Herwig7Interface/src/Herwig7Interface.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43455 Run3-174D Backport the fix in #43418 on ZDC geometry to update the 2023 Run3 geometry to be used for te Heavy Ion MC
  Configuration/Geometry/README.md
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2023.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2023XML_cfi.py
  Geometry/ForwardCommonData/data/rpd/2021/v1/rpd.xml
  Geometry/ForwardCommonData/data/zdc/2021/v3/zdc.xml
  Geometry/ForwardCommonData/plugins/DDRPDPosition.cc
  Geometry/ForwardCommonData/plugins/dd4hep/DDRPDPosition.cc
  Geometry/ForwardSimData/data/zdcProdCuts/2021/v3/zdcProdCuts.xml
  Geometry/ForwardSimData/data/zdcsens/2021/v1/zdcsens.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#43405 [GENERATORS] [DEVEL] Fix warnings on deprecated copy-constructors
  SimDataFormats/GeneratorProducts/interface/GenFilterInfo.h
  SimDataFormats/GeneratorProducts/interface/GenLumiInfoProduct.h
  SimDataFormats/GeneratorProducts/interface/GenRunInfoProduct.h
  SimDataFormats/GeneratorProducts/src/GenFilterInfo.cc
  SimDataFormats/GeneratorProducts/src/GenLumiInfoProduct.cc
  SimDataFormats/GeneratorProducts/src/GenRunInfoProduct.cc
Labels: generators-pending, pending-signatures, tests-approved, orp-approved, code-checks-approved

#43591 [14_0] Another fix to avoid running genfilter with pgen_smear
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43520 [13_2_X] Run3 era for 2023 PbPb UPC re-reco
  Configuration/Eras/python/Era_Run3_2023_UPC_cff.py
  Configuration/Eras/python/Modifier_run3_upc_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/Eras.py
  Configuration/StandardSequences/python/Reconstruction_cff.py
  PhysicsTools/PatAlgos/python/selectionLayer1/lowPtElectronSelector_cfi.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/isolatedTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/lostTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/slimming/packedPFCandidates_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimmedCaloJets_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSeeds_cfi.py
  RecoHI/HiCentralityAlgos/python/HiCentrality_cfi.py
  RecoHI/HiTracking/python/HILowPtConformalPixelTracks_cfi.py
  RecoJets/Configuration/python/RecoJets_EventContent_cff.py
  RecoTracker/Configuration/python/RecoTracker_EventContent_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoTracker/TkSeedGenerator/python/trackerClusterCheck_cfi.py
Labels: operations-approved, reconstruction-approved, pending-signatures, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok, xpog-approved, tracking

#43521 [13_3_X] Run3 era for 2023 PbPb UPC re-reco
  Configuration/Eras/python/Era_Run3_2023_UPC_cff.py
  Configuration/Eras/python/Modifier_run3_upc_cff.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/Eras.py
  Configuration/StandardSequences/python/Reconstruction_cff.py
  PhysicsTools/PatAlgos/python/selectionLayer1/lowPtElectronSelector_cfi.py
  PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py
  PhysicsTools/PatAlgos/python/slimming/isolatedTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/lostTracks_cfi.py
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
  PhysicsTools/PatAlgos/python/slimming/packedPFCandidates_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimmedCaloJets_cfi.py
  PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
  RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSeeds_cfi.py
  RecoHI/HiCentralityAlgos/python/HiCentrality_cfi.py
  RecoHI/HiTracking/python/HILowPtConformalPixelTracks_cfi.py
  RecoJets/Configuration/python/RecoJets_EventContent_cff.py
  RecoTracker/Configuration/python/RecoTracker_EventContent_cff.py
  RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
  RecoTracker/TkSeedGenerator/python/trackerClusterCheck_cfi.py
Labels: operations-approved, reconstruction-approved, pending-signatures, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok, xpog-approved, tracking

#43532 [13_2_X] Set HF FG bit thresholds for 2023 HI run
  Configuration/Eras/python/Era_Run3_pp_on_PbPb_2023_cff.py
  Configuration/Eras/python/Modifier_pp_on_PbPb_run3_2023_cff.py
  SimCalorimetry/HcalTrigPrimProducers/python/hcaltpdigi_cff.py
Labels: l1-approved, operations-approved, fully-signed, tests-approved, orp-approved, backport-ok

#43439 Short Matrix Update And Documentation
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/scripts/README.md
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#43457 Allow an InputSource to declare a run/lumi is the last to be merged
  DQMServices/FwkIO/plugins/DQMRootSource.cc
  DQMServices/StreamerIO/plugins/DQMProtobufReader.cc
  DQMServices/StreamerIO/plugins/DQMProtobufReader.h
  FWCore/Framework/interface/EventProcessor.h
  FWCore/Framework/interface/InputSource.h
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/InputSource.cc
  FWCore/Framework/src/TransitionProcessors.icc
  FWCore/Framework/test/MockEventProcessor.cc
  FWCore/Framework/test/MockEventProcessor.h
  FWCore/Framework/test/unit_test_outputs/test_deepCall_unscheduled.log
  FWCore/Framework/test/unit_test_outputs/test_onPath_unscheduled.log
  FWCore/Integration/plugins/PutOrMergeTestSource.cc
  FWCore/Integration/plugins/SourceWithWaits.cc
  FWCore/Integration/test/inputSourceTest.sh
  FWCore/Integration/test/testDeclareLastEntryForMerge_cfg.py
  FWCore/Integration/test/testLateLumiClosure_cfg.py
  FWCore/Integration/test/unit_test_outputs/testGetBy1.log
  FWCore/Integration/test/unit_test_outputs/testGetBy2.log
  FWCore/Integration/test/unit_test_outputs/testSubProcess.grep2.txt
  FWCore/Modules/src/TestSource.cc
  FWCore/Sources/interface/IDGeneratorSourceBase.h
  FWCore/Sources/interface/RawInputSource.h
  FWCore/Sources/src/IDGeneratorSourceBase.cc
  FWCore/Sources/src/RawInputSource.cc
  IOPool/Input/src/OneLumiPoolSource.cc
  IOPool/Input/src/PoolSource.cc
  IOPool/Input/src/PoolSource.h
  IOPool/Input/src/RepeatingCachedRootSource.cc
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RunHelper.cc
Labels: core-approved, dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43574 Adapt Alpaka-based PF Clustering to read Hcal thresholds from GT
  DataFormats/ParticleFlowReco/interface/PFRecHitSoA.h
  RecoParticleFlow/PFClusterProducer/interface/PFClusterParamsSoA.h
  RecoParticleFlow/PFClusterProducer/plugins/LegacyPFClusterProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterParamsESProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducer.cc
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.dev.cc
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.h
  RecoParticleFlow/PFClusterProducer/python/particleFlowCluster_cff.py
  RecoParticleFlow/PFClusterProducer/python/pfClusterHBHEAlpaka_cff.py
  RecoParticleFlow/PFClusterProducer/test/test_PFRecHitAndClusterSoA.py
  RecoParticleFlow/PFRecHitProducer/interface/PFRecHitTopologyRecord.h
  RecoParticleFlow/PFRecHitProducer/interface/PFRecHitTopologySoA.h
  RecoParticleFlow/PFRecHitProducer/plugins/BuildFile.xml
  RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitProducerKernel.dev.cc
  RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitProducerKernel.h
  RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitSoAProducer.cc
  RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitTopologyESProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved, pf

#43584 Run3-Sim153E Cleanup in SimG4CMS/HGCalTestBeam against using codes directly from DD4hep
  SimG4CMS/HGCalTestBeam/plugins/BuildFile.xml
  SimG4CMS/HGCalTestBeam/plugins/HGCPassive.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#43019 [13_2_X] Include ECAL Timing CC labelled tags in Run3 data and MC GTs
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#42946 Use ECAL ratio timing algorithm for Run 1 and Run 2, and CC timing algorithm for Run 3 and beyond - 132X
  Configuration/Eras/python/Era_Run3_cff.py
  Configuration/Eras/python/Modifier_run3_ecal_cff.py
  RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py
Labels: alca-approved, operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok, ecal

#43594 Fix bug related to cmsRun exit code with FileReadError, 13_3_X back port
  FWCore/Framework/src/ProductResolvers.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#43595 Fix bug related to cmsRun exit code with FileReadError, 13_2_X backport
  FWCore/Framework/src/ProductResolvers.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#43603 Fix bug related to cmsRun exit code with FileReadError, 13_0_X backport
  FWCore/Framework/src/ProductResolvers.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#43607 Fix bug related to cmsRun exit code with FileReadError, 12_6_X backport
  FWCore/Framework/src/ProductResolvers.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#43608 Fix bug related to cmsRun exit code with FileReadError, 12_4_X backport
  FWCore/Framework/src/ProductResolvers.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#43602 Fix bug related to cmsRun exit code with FileReadError, 13_1_X backport
  FWCore/Framework/src/ProductResolvers.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved

#43597 [12_4] Another fix to avoid running genfilter with pgen_smear
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved

#43598 [12_6] Fix to avoid running genfilter with pgen_smear
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved

#43600 [13_0] Fix to avoid running genfilter with pgen_smear
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved

#42890 CTPPS update Run3 Direct Simulation to use old LHCInfo after LHCInfo update
  CalibPPS/ESProducers/plugins/CTPPSBeamParametersFromLHCInfoESSource.cc
  CalibPPS/ESProducers/plugins/CTPPSInterpolatedOpticalFunctionsESSource.cc
  CalibPPS/ESProducers/python/ctppsBeamParametersFromLHCInfoESSource_cfi.py
  CalibPPS/ESProducers/python/ctppsInterpolatedOpticalFunctionsESSource_cff.py
  CalibPPS/ESProducers/python/ctppsInterpolatedOpticalFunctionsESSource_cfi.py
  CalibPPS/ESProducers/python/ctppsOpticalFunctions_cff.py
  CalibPPS/ESProducers/python/ctppsOpticalFunctions_non_DB_cff.py
  Calibration/PPSAlCaRecoProducer/test/test_express_PPSAlCaReco_output.py
  Calibration/PPSAlCaRecoProducer/test/test_prompt_PPSAlCaReco_output.py
  CondFormats/DataRecord/interface/CTPPSBeamParametersRcd.h
  CondTools/RunInfo/interface/LHCInfoCombined.h
  CondTools/RunInfo/src/LHCInfoCombined.cc
  Configuration/Eras/python/Modifier_ctpps_directSim_cff.py
  Configuration/ProcessModifiers/python/Era_Run3_CTPPS_directSim_cff.py
  RecoPPS/Local/test/2023_lhcinfo_test_recoCTPPS_cfg.py
  RecoPPS/ProtonReconstruction/plugins/CTPPSProtonProducer.cc
  RecoPPS/ProtonReconstruction/python/ctppsProtons_cff.py
  RecoPPS/ProtonReconstruction/python/ctppsProtons_cfi.py
  SimTransport/PPSProtonTransport/python/PPSTransportESSources_cfi.py
  Validation/CTPPS/plugins/CTPPSHepMCDistributionPlotter.cc
  Validation/CTPPS/plugins/CTPPSLHCInfoPlotter.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionEfficiencyEstimatorData.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionEfficiencyEstimatorMC.cc
  Validation/CTPPS/plugins/CTPPSProtonReconstructionSimulationValidator.cc
  Validation/CTPPS/python/ctppsHepMCDistributionPlotter_cfi.py
  Validation/CTPPS/python/ctppsLHCInfoPlotter_cff.py
  Validation/CTPPS/python/ctppsLHCInfoPlotter_cfi.py
  Validation/CTPPS/python/ctppsProtonReconstructionEfficiencyEstimatorData_cfi.py
  Validation/CTPPS/python/ctppsProtonReconstructionEfficiencyEstimatorMC_cfi.py
  Validation/CTPPS/python/ctppsProtonReconstructionSimulationValidator_cfi.py
  Validation/CTPPS/test/simu/run_multiple
  Validation/CTPPS/test/simu/template_cfg.py
Labels: alca-approved, dqm-approved, operations-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#43624 Implement independent_groups and independent_group_elements for Alpaka kernels
  HeterogeneousCore/AlpakaInterface/interface/workdivision.h
  HeterogeneousCore/AlpakaInterface/test/BuildFile.xml
  HeterogeneousCore/AlpakaInterface/test/alpaka/testIndependentKernel.dev.cc
  HeterogeneousCore/AlpakaInterface/test/alpaka/testKernel.dev.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved
