Repository cms-sw/cmssw, pull requests merged in 2024-03, with the labels that each got.

#44273 Fix logic in PFClusterSoAProducer kernels
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.dev.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, heterogeneous-approved, pf, allow-jsamudio

#44278 [14_0_X] Fix logic in PFClusterSoAProducer kernels
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.dev.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport, heterogeneous-approved, pf, allow-jsamudio

#43976 Fix on muon_mvaID in NanoAOD
  PhysicsTools/NanoAOD/python/muons_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, muon

#44201 Fix of LumiList.py so to allow the merge of JSON files
  FWCore/PythonUtilities/python/LumiList.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44234 Add missing newlines in FastSimulation modules
  FastSimulation/SimplifiedGeometryPropagator/interface/GeometryRecord.h
  FastSimulation/SimplifiedGeometryPropagator/src/GeometryRecord.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44241 Add missing newlines in IOMC modules
  IOMC/EventVertexGenerators/python/VtxSmearedRealistic25ns13TeVEarly2018Collision_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRun3RoundOptics25ns13TeVHighSigmaZ_cfi.py
  IOMC/EventVertexGenerators/python/VtxSmearedRun3RoundOptics25ns13TeVLowSigmaZ_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44235 Dynamic pps timing calibration fit
  CalibPPS/TimingCalibration/plugins/PPSTimingCalibrationPCLHarvester.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44260 Simulation: add test code to dump TrackingParticle/TrackingVertex event content
  SimGeneral/TrackingAnalysis/test/TrackingTruthDumper.cc
  SimGeneral/TrackingAnalysis/test/runTrackingTruthDumper_cfg.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#44265 Update Run3 HLT GT to remove unused JEC tags
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44279 Small fix in HeterogeneousCore/AlpakaCore/README.md
  HeterogeneousCore/AlpakaCore/README.md
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#42607 EGamma custom nano
  CommonTools/Utils/interface/parser/ExpressionBinaryOperatorSetter.h
  CommonTools/Utils/interface/parser/Grammar.h
  CommonTools/Utils/test/testExpressionParser.cc
  Configuration/PyReleaseValidation/python/relval_nano.py
  PhysicsTools/NanoAOD/python/autoNANO.py
  PhysicsTools/NanoAOD/python/egamma_custom_cff.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved, egamma

#44255 [14_0_X] Custom nano for e/gamma
  CommonTools/Utils/interface/parser/ExpressionBinaryOperatorSetter.h
  CommonTools/Utils/interface/parser/Grammar.h
  CommonTools/Utils/test/testExpressionParser.cc
  Configuration/PyReleaseValidation/python/relval_nano.py
  PhysicsTools/NanoAOD/python/autoNANO.py
  PhysicsTools/NanoAOD/python/egamma_custom_cff.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok, xpog-approved, egamma

#43913 [MTD simulation, validation]: implementation of MTD clusters association maps
  Geometry/MTDGeometryBuilder/interface/MTDGeomUtil.h
  Geometry/MTDGeometryBuilder/src/MTDGeomUtil.cc
  SimDataFormats/Associations/interface/MtdRecoClusterToSimLayerClusterAssociationMap.h
  SimDataFormats/Associations/interface/MtdRecoClusterToSimLayerClusterAssociator.h
  SimDataFormats/Associations/interface/MtdRecoClusterToSimLayerClusterAssociatorBaseImpl.h
  SimDataFormats/Associations/interface/MtdSimLayerClusterToRecoClusterAssociationMap.h
  SimDataFormats/Associations/interface/MtdSimLayerClusterToTPAssociator.h
  SimDataFormats/Associations/interface/MtdSimLayerClusterToTPAssociatorBaseImpl.h
  SimDataFormats/Associations/src/MtdRecoClusterToSimLayerClusterAssociationMap.cc
  SimDataFormats/Associations/src/MtdRecoClusterToSimLayerClusterAssociator.cc
  SimDataFormats/Associations/src/MtdRecoClusterToSimLayerClusterAssociatorBaseImpl.cc
  SimDataFormats/Associations/src/MtdSimLayerClusterToRecoClusterAssociationMap.cc
  SimDataFormats/Associations/src/MtdSimLayerClusterToTPAssociator.cc
  SimDataFormats/Associations/src/MtdSimLayerClusterToTPAssociatorBaseImpl.cc
  SimDataFormats/Associations/src/classes.h
  SimDataFormats/Associations/src/classes_def.xml
  SimDataFormats/CaloAnalysis/interface/MtdSimCluster.h
  SimDataFormats/CaloAnalysis/interface/MtdSimLayerClusterFwd.h
  SimDataFormats/CaloAnalysis/src/classes_def.xml
  SimFastTiming/MtdAssociatorProducers/plugins/BuildFile.xml
  SimFastTiming/MtdAssociatorProducers/plugins/MtdRecoClusterToSimLayerClusterAssociatorByHitsImpl.cc
  SimFastTiming/MtdAssociatorProducers/plugins/MtdRecoClusterToSimLayerClusterAssociatorByHitsImpl.h
  SimFastTiming/MtdAssociatorProducers/plugins/MtdRecoClusterToSimLayerClusterAssociatorByHitsProducer.cc
  SimFastTiming/MtdAssociatorProducers/plugins/MtdRecoClusterToSimLayerClusterAssociatorEDProducer.cc
  SimFastTiming/MtdAssociatorProducers/plugins/MtdSimLayerClusterToTPAssociatorByTrackIdImpl.cc
  SimFastTiming/MtdAssociatorProducers/plugins/MtdSimLayerClusterToTPAssociatorByTrackIdImpl.h
  SimFastTiming/MtdAssociatorProducers/plugins/MtdSimLayerClusterToTPAssociatorByTrackIdProducer.cc
  SimFastTiming/MtdAssociatorProducers/plugins/MtdSimLayerClusterToTPAssociatorEDProducer.cc
  SimFastTiming/MtdAssociatorProducers/python/mtdRecoClusterToSimLayerClusterAssociation_cfi.py
  SimFastTiming/MtdAssociatorProducers/python/mtdSimLayerClusterToTPAssociation_cfi.py
  SimGeneral/CaloAnalysis/plugins/MtdTruthAccumulator.cc
  Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py
  Validation/Configuration/python/mtdSimValid_cff.py
  Validation/MtdValidation/plugins/BtlLocalRecoValidation.cc
  Validation/MtdValidation/plugins/EtlLocalRecoValidation.cc
  Validation/MtdValidation/plugins/MtdTracksValidation.cc
Labels: core-approved, dqm-approved, geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, mtd

#44287 Fix PrimaryVertexProducer::fillDescriptions to generate a cfi file [141X]
  RecoVertex/PrimaryVertexProducer/plugins/PrimaryVertexProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, tracking

#43955 Alternative module configuration syntax
  FWCore/Integration/test/check_empty_event_cfg.py
  FWCore/Integration/test/delayedreader_throw_cfg.py
  FWCore/ParameterSet/bin/edmWriteConfigs.cpp
  FWCore/ParameterSet/interface/ConfigurationDescriptions.h
  FWCore/ParameterSet/python/ModulesProxy.py
  FWCore/ParameterSet/src/ConfigurationDescriptions.cc
  FWCore/ParameterSet/src/ParameterDescriptionBase.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44256 [ROOTMaster] Fix include for RNTuple*
  PhysicsTools/NanoAOD/plugins/rntuple/NanoAODRNTupleOutputModule.cc
  PhysicsTools/NanoAOD/plugins/rntuple/NanoAODRNTuples.cc
  PhysicsTools/NanoAOD/plugins/rntuple/NanoAODRNTuples.h
  PhysicsTools/NanoAOD/plugins/rntuple/TableOutputFields.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#44069 Fix some minor RooFit user errors
  Alignment/OfflineValidation/bin/Zmumumerge.cc
  DQMOffline/Alignment/src/DiMuonMassBiasClient.cc
  DQMOffline/EGamma/plugins/PhotonDataCertification.cc
  MuonAnalysis/MomentumScaleCalibration/test/Macros/RooFit/FitWithRooFit.cc
  PhysicsTools/TagAndProbe/src/TagProbeFitter.cc
  Validation/MtdValidation/macros/Pt_residuals_fit.C
Labels: alca-approved, analysis-approved, dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#43837 Fix LHCInfoPer* PopCons to produce lumi-type IOVs when running in duringFill mode
  CondTools/RunInfo/interface/LHCInfoHelper.h
  CondTools/RunInfo/plugins/LHCInfoPerFillPopConAnalyzer.cc
  CondTools/RunInfo/plugins/LHCInfoPerLSPopConAnalyzer.cc
  CondTools/RunInfo/python/LHCInfoPerFillPopConAnalyzer.py
  CondTools/RunInfo/python/LHCInfoPerLSPopConAnalyzer.py
  CondTools/RunInfo/src/LHCInfoHelper.cc
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#44044 [PPS] Added gtStage2DigisAlCaRecoProducer to ALCARECOPRODUCER
  Calibration/PPSAlCaRecoProducer/python/ALCARECOPPSCalMaxTracks_Output_cff.py
  Calibration/PPSAlCaRecoProducer/python/ALCARECOPPSCalMaxTracks_cff.py
  Calibration/PPSAlCaRecoProducer/test/README.md
  Calibration/PPSAlCaRecoProducer/test/test_express_AlCaRecoProducer.sh
  Calibration/PPSAlCaRecoProducer/test/test_express_PPSAlCaReco_output.py
  Calibration/PPSAlCaRecoProducer/test/test_express_PPSAlCaReco_output.sh
  Calibration/PPSAlCaRecoProducer/test/test_prompt_AlCaRecoProducer.sh
  Calibration/PPSAlCaRecoProducer/test/test_prompt_PPSAlCaReco_output.py
  Calibration/PPSAlCaRecoProducer/test/test_prompt_PPSAlCaReco_output.sh
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, ctpps

#44296 fix `BPHHistoSpecificDecay::fillDescriptions`
  HeavyFlavorAnalysis/SpecificDecay/plugins/BPHHistoSpecificDecay.cc
Labels: analysis-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44272 [14_0_X] Erase from correct vector in PATTauHybridProducer
  PhysicsTools/PatAlgos/plugins/PATTauHybridProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, xpog-approved

#44288 Fix PrimaryVertexProducer::fillDescriptions to generate a cfi file [140X]
  RecoVertex/PrimaryVertexProducer/plugins/PrimaryVertexProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, tracking

#44289 Dynamic PPS timing calibration fit [backport of 44235]
  CalibPPS/TimingCalibration/plugins/PPSTimingCalibrationPCLHarvester.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44001 Add cmsDriver option --maxmem_profile to prefix LD_PRELOAD="libPerfToolsAllocMonitorPreload.so libPerfToolsMaxMemoryPreload.so" to cmsRun
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/Applications/python/Options.py
  Configuration/Applications/python/cmsDriverOptions.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#44066 Fix labels in HGCal tower customisation
  L1Trigger/L1THGCal/python/customTowers.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#44298 Update the Run4 MC GT with the updated OMTF config
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44228 Add missing newlines in Configuration modules
  Configuration/DataProcessing/python/Repack.py
  Configuration/DataProcessing/test/Monitoring_t.py
  Configuration/EventContent/test/makeSkim.py
  Configuration/Generator/python/DY_TuneCH3_13TeV_herwig_madgraph_matchbox_cff.py
  Configuration/Generator/python/Herwig7Settings/Herwig7_7p1SettingsFor7p2_cfi.py
  Configuration/Generator/python/Hydjet_Quenched_B12_5020GeV_ExtGen_cfi.py
  Configuration/Generator/python/ReggeGribovPartonMC_EposLHC_4080_4080GeV_pPb_ExtGen_cfi.py
  Configuration/Generator/python/ZTT_Tauola_OneLepton_OtherHadrons_8TeV_TuneCUETP8M1_ExtGen_cfi.py
  Configuration/PyReleaseValidation/doc/README
  Configuration/Skimming/python/PDWG_EXOLLPJetHCAL_cff.py
  Configuration/StandardSequences/python/SimPhase2L1GlobalTriggerEmulator_cff.py
Labels: generators-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#44291 Add default values in `{CaloRecHitSoA,PFRecHitSoA,LegacyPFRecHit,PFClusterSoA}Producer::fillDescriptions` [`14_0_X`]
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducer.cc
  RecoParticleFlow/PFRecHitProducer/plugins/LegacyPFRecHitProducer.cc
  RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CaloRecHitSoAProducer.cc
  RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitSoAProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#44292 Revert #44256 - merged too early
  PhysicsTools/NanoAOD/plugins/rntuple/NanoAODRNTupleOutputModule.cc
  PhysicsTools/NanoAOD/plugins/rntuple/NanoAODRNTuples.cc
  PhysicsTools/NanoAOD/plugins/rntuple/NanoAODRNTuples.h
  PhysicsTools/NanoAOD/plugins/rntuple/TableOutputFields.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#44294 Fix on mvaID for muons (backport)
  PhysicsTools/NanoAOD/python/muons_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#44230 Add missing newlines in DataFormats modules
  DataFormats/Common/test/exTrie.cpp
  DataFormats/HcalCalibObjects/python/HFRecalibrationParameters_cff.py
  DataFormats/HepMCCandidate/doc/HepMCCandidate.doc
  DataFormats/L1Scouting/BuildFile.xml
  DataFormats/L1Scouting/README.md
  DataFormats/L1Scouting/interface/L1ScoutingCalo.h
  DataFormats/L1Scouting/interface/L1ScoutingMuon.h
  DataFormats/L1Scouting/src/classes.h
  DataFormats/L1Scouting/src/classes_def.xml
  DataFormats/L1Scouting/test/BuildFile.xml
  DataFormats/L1Scouting/test/TestL1ScoutingFormat.sh
  DataFormats/L1Scouting/test/TestReadL1Scouting.cc
  DataFormats/L1Scouting/test/TestWriteL1Scouting.cc
  DataFormats/L1Scouting/test/create_L1Scouting_test_file_cfg.py
  DataFormats/L1Scouting/test/read_L1Scouting_cfg.py
  DataFormats/L1ScoutingRawData/BuildFile.xml
  DataFormats/L1ScoutingRawData/README.md
  DataFormats/L1ScoutingRawData/interface/SDSNumbering.h
  DataFormats/L1ScoutingRawData/src/classes.h
  DataFormats/L1ScoutingRawData/src/classes_def.xml
  DataFormats/L1ScoutingRawData/test/BuildFile.xml
  DataFormats/L1ScoutingRawData/test/TestReadSDSRawDataCollection.cc
  DataFormats/L1ScoutingRawData/test/TestSDSRawDataCollectionFormat.sh
  DataFormats/L1ScoutingRawData/test/TestWriteSDSRawDataCollection.cc
  DataFormats/L1ScoutingRawData/test/create_SDSRawDataCollection_test_file_cfg.py
  DataFormats/L1TCalorimeterPhase2/interface/DigitizedClusterCorrelator.h
  DataFormats/L1TCalorimeterPhase2/interface/DigitizedClusterGT.h
  DataFormats/L1TCalorimeterPhase2/interface/DigitizedTowerCorrelator.h
  DataFormats/L1TrackTrigger/interface/TTDTC.h
  DataFormats/L1TrackTrigger/test/BuildFile.xml
  DataFormats/L1TrackTrigger/test/testDataFormatsTTTrackTrackWord_cfg.py
  DataFormats/L1Trigger/src/VertexWord.cc
  DataFormats/OnlineMetaData/test/dump_run000001_event6135_fed1022.txt
  DataFormats/Portable/README.md
  DataFormats/Portable/interface/PortableCollectionCommon.h
  DataFormats/Portable/interface/PortableDeviceCollection.h
  DataFormats/Portable/interface/PortableObject.h
  DataFormats/Portable/interface/alpaka/PortableObject.h
  DataFormats/Portable/scripts/portableDeviceCollectionHints
  DataFormats/PortableTestObjects/src/classes_def.xml
  DataFormats/SiPixelClusterSoA/src/classes.cc
  DataFormats/SoATemplate/test/SoAUnitTests.cc
  DataFormats/TestObjects/src/DeleteEarly.cc
  DataFormats/TrackingRecHitSoA/src/classes.cc
Labels: alca-approved, core-approved, daq-approved, generators-approved, l1-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, heterogeneous-approved, tracking, trk

#44053 Run3-gex176C Backport the PR's 44006 and 44052 for the 2024 scenario definition with additional chambers for GE21 and iRPC
  Configuration/Geometry/README.md
  Configuration/Geometry/python/GeometryDD4hepExtended2024FlatMinus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024FlatMinus05Percent_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024FlatMinus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024FlatMinus10Percent_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024FlatPlus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024FlatPlus05Percent_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024FlatPlus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024FlatPlus10Percent_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024Reco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024ZeroMaterialReco_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024ZeroMaterial_cff.py
  Configuration/Geometry/python/GeometryDD4hepExtended2024_cff.py
  Configuration/Geometry/python/GeometryExtended2024FlatMinus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2024FlatMinus05Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2024FlatMinus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2024FlatMinus10Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2024FlatPlus05PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2024FlatPlus05Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2024FlatPlus10PercentReco_cff.py
  Configuration/Geometry/python/GeometryExtended2024FlatPlus10Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2024Reco_cff.py
  Configuration/Geometry/python/GeometryExtended2024ZeroMaterialReco_cff.py
  Configuration/Geometry/python/GeometryExtended2024ZeroMaterial_cff.py
  Configuration/Geometry/python/GeometryExtended2024_cff.py
  Configuration/Geometry/python/dict2021Geometry.py
  Configuration/StandardSequences/python/GeometryConf.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024ZeroMaterialXML_cfi.py
Labels: geometry-approved, operations-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#44282 Add ntuplization code for sagitta-bias studies to `Alignment/OfflineValidation`
  Alignment/OfflineValidation/plugins/SagittaBiasNtuplizer.cc
  Alignment/OfflineValidation/test/SagittaBiasNtuplizer_cfg.py
  Alignment/OfflineValidation/test/testTrackAnalyzers.cc
  Alignment/OfflineValidation/test/testingScripts/test_unitMiscellanea.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#44285 Add two more PV variables requested by H->gammagamma conveners
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#44259 [14_0_X] Pythia8 photon flux
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/test/pythia8ex2_ConvertToMain70_cfg.py
  GeneratorInterface/Pythia8Interface/test/pythia8ex2_ConvertToMain70_cfg_Fragment.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved

#44300 Remove obsolete struct SimDataFormats_Associations
  SimDataFormats/Associations/src/classes.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44301 ECAL - Fix heap-buffer overflows reported by ASAN
  RecoLocalCalo/EcalRecProducers/plugins/alpaka/EcalMultifitConditionsHostESProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, ecal

#44091 [PPS] Added gtStage2DigisAlCaRecoProducer to ALCARECOPRODUCER [14_0_X backport]
  Calibration/PPSAlCaRecoProducer/python/ALCARECOPPSCalMaxTracks_Output_cff.py
  Calibration/PPSAlCaRecoProducer/python/ALCARECOPPSCalMaxTracks_cff.py
  Calibration/PPSAlCaRecoProducer/test/README.md
  Calibration/PPSAlCaRecoProducer/test/test_express_AlCaRecoProducer.sh
  Calibration/PPSAlCaRecoProducer/test/test_express_PPSAlCaReco_output.py
  Calibration/PPSAlCaRecoProducer/test/test_express_PPSAlCaReco_output.sh
  Calibration/PPSAlCaRecoProducer/test/test_prompt_AlCaRecoProducer.sh
  Calibration/PPSAlCaRecoProducer/test/test_prompt_PPSAlCaReco_output.py
  Calibration/PPSAlCaRecoProducer/test/test_prompt_PPSAlCaReco_output.sh
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, urgent, upgrade-approved, backport-ok, ctpps

#44276 Small fix for simulation of pixel bad components
  SimGeneral/MixingModule/python/pixelDigitizer_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#44311 Handling of FOG special HLT menus [141X]
  HLTrigger/Configuration/tables/Special.txt
  HLTrigger/Configuration/tables/makeOnlineCosmics
  HLTrigger/Configuration/tables/makeOnlineGRun
  HLTrigger/Configuration/tables/makeOnlineHIon
  HLTrigger/Configuration/tables/makeOnlinePIon
  HLTrigger/Configuration/tables/makeOnlinePRef
  HLTrigger/Configuration/tables/makeOnlineSpecial
  HLTrigger/Configuration/tables/makeSubTables
  HLTrigger/Configuration/tables/online_Circulating.txt
  HLTrigger/Configuration/tables/online_Cosmics.txt
  HLTrigger/Configuration/tables/online_ECALTiming.txt
  HLTrigger/Configuration/tables/online_FirstCollisions.txt
  HLTrigger/Configuration/tables/online_LumiScan.txt
  HLTrigger/Configuration/tables/online_PPS.txt
  HLTrigger/Configuration/tables/online_Special.txt
  HLTrigger/Configuration/tables/online_Splashes.txt
  HLTrigger/Configuration/tables/online_TrackerVR.txt
  HLTrigger/Configuration/tables/subtables.sh
  HLTrigger/Configuration/test/test_OnlineVsDevTablesConsistency.sh
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44310 Add standard open file message; minor updates
  PhysicsTools/NanoAODTools/python/postprocessing/framework/eventloop.py
  PhysicsTools/NanoAODTools/python/postprocessing/framework/output.py
  PhysicsTools/NanoAODTools/python/postprocessing/framework/postprocessor.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#44264 Fix to PYTHIA 8 photon flux.
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44038 PFMet and PuppiMET Branches
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#44317 Retain compatibility with RooFit prior to ROOT 6.28
  PhysicsTools/TagAndProbe/src/TagProbeFitter.cc
Labels: analysis-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44325 [CMSSW_14_0_X] Add two more PV variables requested by H->gammagamma c…
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#44313 Handling of FOG special HLT menus [140X]
  HLTrigger/Configuration/tables/Special.txt
  HLTrigger/Configuration/tables/makeOnlineCosmics
  HLTrigger/Configuration/tables/makeOnlineGRun
  HLTrigger/Configuration/tables/makeOnlineHIon
  HLTrigger/Configuration/tables/makeOnlinePIon
  HLTrigger/Configuration/tables/makeOnlinePRef
  HLTrigger/Configuration/tables/makeOnlineSpecial
  HLTrigger/Configuration/tables/makeSubTables
  HLTrigger/Configuration/tables/online_Circulating.txt
  HLTrigger/Configuration/tables/online_Cosmics.txt
  HLTrigger/Configuration/tables/online_ECALTiming.txt
  HLTrigger/Configuration/tables/online_FirstCollisions.txt
  HLTrigger/Configuration/tables/online_LumiScan.txt
  HLTrigger/Configuration/tables/online_PPS.txt
  HLTrigger/Configuration/tables/online_Special.txt
  HLTrigger/Configuration/tables/online_Splashes.txt
  HLTrigger/Configuration/tables/online_TrackerVR.txt
  HLTrigger/Configuration/tables/subtables.sh
  HLTrigger/Configuration/test/test_OnlineVsDevTablesConsistency.sh
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44305 [CMSSW_14_0_X] Update the Run4 GT with the updated OMTF config
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44304 ECAL - Fix heap-buffer overflows reported by ASAN - 140x
  RecoLocalCalo/EcalRecProducers/plugins/alpaka/EcalMultifitConditionsHostESProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, ecal

#44295 Reduce complexity of erasing elements from vectors in PATTauHybridProducer [14_0_X]
  PhysicsTools/PatAlgos/plugins/PATTauHybridProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, xpog-approved

#44297 [14.0.X] Add ntuplization code for sagitta-bias studies to `Alignment/OfflineValidation`
  Alignment/OfflineValidation/plugins/SagittaBiasNtuplizer.cc
  Alignment/OfflineValidation/test/SagittaBiasNtuplizer_cfg.py
  Alignment/OfflineValidation/test/testTrackAnalyzers.cc
  Alignment/OfflineValidation/test/testingScripts/test_unitMiscellanea.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#44329 Remove hanging references to `ReconstructionHeavyIons`
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/DataProcessing/test/BuildFile.xml
  Configuration/DataProcessing/test/run_CfgTest_4.sh
  DQM/BeamMonitor/test/2011_44X_HI_Test_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/2011_44X_Test_beampixel_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/42X_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/42X_beampixel_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/44X_HI_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/44X_beam_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/44X_beampixel_dqm_sourceclient-live_cfg.py
  DQM/BeamMonitor/test/HeavyIonBeamMonitor_cfg.py
  HeavyIonsAnalysis/Configuration/python/HI_PhotonSkim_cff.py
  HeavyIonsAnalysis/Configuration/test/SDmaker_3SD_1CS_PDHIAllPhysicsZSv2_cfg.py
  HeavyIonsAnalysis/Configuration/test/SDmaker_3SD_3CS_PDMinBias_cfg.py
  HeavyIonsAnalysis/Configuration/test/centralSkimsHI_SKIM.py
  RecoHI/HiEgammaAlgos/test/testElectronSequence_cfg.py
  RecoHI/HiJetAlgos/test/step3_RAW2DIGI_L1Reco_RECO_VALIDATION_DQM.py
  RecoHI/HiTracking/test/runIterCaloMatching_cfg.py
  RecoHI/HiTracking/test/testTracking_cfg.py
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripZS_EmulateHybrid_RealData.py
  RecoLocalTracker/SiStripZeroSuppression/test/SiStripZS_RealData.py
  Validation/RecoHI/test/step2_RAW2DIGI_RECO_VALIDATION.py
Labels: analysis-approved, dqm-approved, operations-approved, reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, urgent, code-checks-approved, tracking, trk

#44299 Updated btags and Working Points for Top Production mini AOD DQM
  DQM/Physics/src/SingleTopTChannelLeptonDQM_miniAOD.cc
  DQM/Physics/src/TopSingleLeptonDQM_miniAOD.cc
  DQM/Physics/test/topDQM_production_miniAOD.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44284 MSSM Hbb trigger dqm updates for 2024 triggers [14_1_X]
  DQMOffline/Trigger/python/MssmHbbBtagTriggerMonitor_Client_cfi.py
  DQMOffline/Trigger/python/MssmHbbBtagTriggerMonitor_cff.py
  DQMOffline/Trigger/python/MssmHbbBtagTriggerMonitor_cfi.py
  DQMOffline/Trigger/python/MssmHbbMonitoring_Client_cfi.py
  DQMOffline/Trigger/python/MssmHbbMonitoring_cff.py
  HLTriggerOffline/Higgs/python/hltHiggsPostProcessors_cff.py
  HLTriggerOffline/Higgs/python/hltHiggsValidator_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43998 Triplet emulator 14 0 0 pre3
  DataFormats/L1TCorrelator/interface/TkTriplet.h
  DataFormats/L1TCorrelator/interface/TkTripletFwd.h
  DataFormats/L1TCorrelator/src/TkTriplet.cc
  DataFormats/L1TCorrelator/src/classes.h
  DataFormats/L1TCorrelator/src/classes_def.xml
  DataFormats/L1Trigger/interface/TkTripletWord.h
  DataFormats/L1Trigger/src/TkTripletWord.cc
  DataFormats/L1Trigger/src/classes.h
  DataFormats/L1Trigger/src/classes_def.xml
  L1Trigger/L1TTrackMatch/plugins/L1TrackTripletEmulatorProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackUnpacker.h
  L1Trigger/L1TTrackMatch/python/l1tTrackTripletEmulation_cfi.py
  L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker.cc
  L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker_cfg.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#44270 [13_0_X] CepGen generator interface
  Configuration/Generator/python/CepGen_LPAIR_GamGamToLL_singlediss_13TeV_cfi.py
  Configuration/Generator/python/CepGen_pptoff_GamGamToLL_singlediss_13TeV_cfi.py
  GeneratorInterface/CepGenInterface/BuildFile.xml
  GeneratorInterface/CepGenInterface/interface/CepGenEventGenerator.h
  GeneratorInterface/CepGenInterface/interface/CepGenGeneratorFilter.h
  GeneratorInterface/CepGenInterface/interface/CepGenParametersConverter.h
  GeneratorInterface/CepGenInterface/plugins/BuildFile.xml
  GeneratorInterface/CepGenInterface/plugins/CepGenGeneratorFilter.cc
  GeneratorInterface/CepGenInterface/python/cepgenDefaultParameters_cff.py
  GeneratorInterface/CepGenInterface/src/CepGenEventGenerator.cc
  GeneratorInterface/CepGenInterface/src/CepGenGeneratorFilter.cc
Labels: generators-approved, fully-signed, tests-rejected, orp-approved, requires-external

#44258 [13_0_X] Pythia8 photon flux
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/test/pythia8ex2_ConvertToMain70_cfg.py
  GeneratorInterface/Pythia8Interface/test/pythia8ex2_ConvertToMain70_cfg_Fragment.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44269 [12_4_X] CepGen generator interface
  Configuration/Generator/python/CepGen_LPAIR_GamGamToLL_singlediss_13TeV_cfi.py
  Configuration/Generator/python/CepGen_pptoff_GamGamToLL_singlediss_13TeV_cfi.py
  GeneratorInterface/CepGenInterface/BuildFile.xml
  GeneratorInterface/CepGenInterface/interface/CepGenEventGenerator.h
  GeneratorInterface/CepGenInterface/interface/CepGenGeneratorFilter.h
  GeneratorInterface/CepGenInterface/interface/CepGenParametersConverter.h
  GeneratorInterface/CepGenInterface/plugins/BuildFile.xml
  GeneratorInterface/CepGenInterface/plugins/CepGenGeneratorFilter.cc
  GeneratorInterface/CepGenInterface/python/cepgenDefaultParameters_cff.py
  GeneratorInterface/CepGenInterface/src/CepGenEventGenerator.cc
  GeneratorInterface/CepGenInterface/src/CepGenGeneratorFilter.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external

#44088 Validation/RecoEgamma PHASE2 histos filling correction V1
  Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcFakeValidator.h
  Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcSignalValidator.h
  Validation/RecoEgamma/python/ElectronMcFakeValidator_gedGsfElectrons_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidatorPt1000_gedGsfElectrons_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidator_gedGsfElectrons_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44315 E2E NNVtx: A Phase 2 L1T Vertexing algorithm using End to End NN
  DataFormats/L1TrackTrigger/interface/TTTrack.h
  DataFormats/L1TrackTrigger/interface/TTTrack_TrackWord.h
  DataFormats/L1TrackTrigger/src/TTTrack_TrackWord.cc
  L1Trigger/L1TTrackMatch/BuildFile.xml
  L1Trigger/L1TTrackMatch/plugins/L1TrackVertexAssociationProducer.cc
  L1Trigger/L1TTrackMatch/python/l1tTrackVertexAssociationProducer_cfi.py
  L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker_cfg.py
  L1Trigger/TrackFindingTracklet/plugins/L1FPGATrackProducer.cc
  L1Trigger/VertexFinder/BuildFile.xml
  L1Trigger/VertexFinder/interface/AlgoSettings.h
  L1Trigger/VertexFinder/interface/L1Track.h
  L1Trigger/VertexFinder/interface/VertexFinder.h
  L1Trigger/VertexFinder/interface/VertexProducer.h
  L1Trigger/VertexFinder/plugins/VertexProducer.cc
  L1Trigger/VertexFinder/python/l1tVertexProducer_cfi.py
  L1Trigger/VertexFinder/src/AlgoSettings.cc
  L1Trigger/VertexFinder/src/VertexFinder.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved

#44342 Add standard open file message; minor updates [14.0.X]
  PhysicsTools/NanoAODTools/python/postprocessing/framework/eventloop.py
  PhysicsTools/NanoAODTools/python/postprocessing/framework/output.py
  PhysicsTools/NanoAODTools/python/postprocessing/framework/postprocessor.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#44341 Add standard open file message; minor updates [13.3.X]
  PhysicsTools/NanoAODTools/python/postprocessing/framework/eventloop.py
  PhysicsTools/NanoAODTools/python/postprocessing/framework/output.py
  PhysicsTools/NanoAODTools/python/postprocessing/framework/postprocessor.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#44345 2 New Trigger bits for Muon POG NanoAOD
  PhysicsTools/NanoAOD/python/custom_muon_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#44327 Phase2-hgx354A Attempt to make xml files for cassette tests from an overall silicon wafer flat file of HGCal
  Geometry/HGCalCommonData/data/hgcCassette/v01/cassette01.txt
  Geometry/HGCalCommonData/data/hgcCassette/v01/ee.txt
  Geometry/HGCalCommonData/data/hgcCassette/v01/hgcalCons.xml
  Geometry/HGCalCommonData/data/hgcCassette/v01/hgcalConsData.xml
  Geometry/HGCalCommonData/test/HGCalConvert.cpp
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#44340 Refactor scatterer addition in aGblPoint to explicitly specify type for scatPrecision.inverse()
  Alignment/ReferenceTrajectories/src/ReferenceTrajectory.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external, code-checks-approved, trk

#44344 Add ESInputTag to VPSet default added to cfi file
  FWCore/ParameterSet/src/FillDescriptionFromPSet.cc
  FWCore/ParameterSet/src/ParameterDescription.cc
  FWCore/ParameterSet/test/test_catch_ParameterSetDescription.cc
  FWCore/Utilities/src/FileInPath.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44351 [140X] Add Phase-2 T33 SIM LA payload
  Configuration/AlCa/python/autoCondPhase2.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#44356 Fix tag for the SiPixelLorentzAngleSimRcd in the Phase2 MC GT
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44362 Fix how empty FileInPaths are handled in python
  FWCore/ParameterSet/python/Types.py
  FWCore/ParameterSet/src/ParameterDescription.cc
  FWCore/ParameterSet/test/test_catch_ParameterSetDescription.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#44359 [14.0.X] Backport - Refactor scatterer addition in aGblPoint to explicitly specify type for scatPrecision.inverse()
  Alignment/ReferenceTrajectories/src/ReferenceTrajectory.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, urgent, requires-external, backport-ok, trk

#44357 [CMSSW_14_0_X ] Fix tag for the SiPixelLorentzAngleSimRcd in the Phase2 MC GT
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#44347 Backport of New Trigger Filter Bits for Muon POG NanoAOD
  PhysicsTools/NanoAOD/python/custom_muon_cff.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#44041 Bring HLT Phase2 simplified timing menu variant up to date.
  HLTrigger/Configuration/python/HLT_75e33_timing_cff.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#44334 Phase 2 GTT Fix ptbits z0bits of GTT ObjectWords
  DataFormats/L1Trigger/interface/TkJetWord.h
  DataFormats/L1Trigger/interface/VertexWord.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44358 Hack `EgammaHLTR9IDProducer` to be able to run it in Phase2 HLT
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTR9IDProducer.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, egamma

#44361 Remove invalid tool from L1Trigger/L1TZDC
  L1Trigger/L1TZDC/plugins/BuildFile.xml
Labels: l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, requires-external, code-checks-approved

#44019 Adding ZDC packer
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/CommonTokens.h
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTSetup.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/GTTokens.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/ZDCPacker.cc
  EventFilter/L1TRawToDigi/plugins/implementations_stage2/ZDCPacker.h
  EventFilter/L1TRawToDigi/python/gtStage2Raw_cfi.py
  EventFilter/L1TRawToDigi/test/test_RawToDigiToRawToDigi_GT.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44320 Kill both permanently and transiently bad pixel components in DataMixer
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
  SimGeneral/MixingModule/python/pixelDigitizer_cfi.py
  SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44348 Bug fixes & small improvements to L1 tracking of Phase 2 Outer Tracker
  L1Trigger/TrackFindingTracklet/README.md
  L1Trigger/TrackFindingTracklet/interface/MatchProcessor.h
  L1Trigger/TrackFindingTracklet/interface/Settings.h
  L1Trigger/TrackFindingTracklet/interface/Track.h
  L1Trigger/TrackFindingTracklet/python/L1TrackNtupleMaker_cfi.py
  L1Trigger/TrackFindingTracklet/src/MatchEngineUnit.cc
  L1Trigger/TrackFindingTracklet/src/MatchProcessor.cc
  L1Trigger/TrackFindingTracklet/src/MemoryBase.cc
  L1Trigger/TrackFindingTracklet/src/StubKiller.cc
  L1Trigger/TrackFindingTracklet/src/Tracklet.cc
  L1Trigger/TrackFindingTracklet/src/TrackletProcessorDisplaced.cc
  L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc
  L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker_cfg.py
  L1Trigger/TrackFindingTracklet/test/L1TrackNtuplePlot.C
  L1Trigger/TrackFindingTracklet/test/makeHists.csh
  L1Trigger/TrackFindingTracklet/test/skimForCI_cfg.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44364 EL9-migration related patches to All-in-one
  Alignment/OfflineValidation/bin/DMRtrends.cc
  Alignment/OfflineValidation/bin/PVtrends.cc
  Alignment/OfflineValidation/plugins/TrackerGeometryCompare.cc
  Alignment/OfflineValidation/plugins/TrackerGeometryCompare.h
  Alignment/OfflineValidation/python/TkAlAllInOneTool/MTS.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/MTS_cfg.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/findAndChange.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/templates/condorTemplate.submit
  Alignment/OfflineValidation/python/TkAlMap.py
  Alignment/OfflineValidation/scripts/validateAlignments.py
  Alignment/OfflineValidation/src/Trend.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#44365 [14_0_X] Hack `EgammaHLTR9IDProducer` to be able to run it in Phase2 HLT
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTR9IDProducer.cc
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok, egamma

#44331 [13_2_X] Pythia8 photon flux
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/test/pythia8ex2_ConvertToMain70_cfg.py
  GeneratorInterface/Pythia8Interface/test/pythia8ex2_ConvertToMain70_cfg_Fragment.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44370 add input / output LA `TkDetMaps` in `SiStripLorentzAnglePCLHarvester`
  CalibTracker/SiStripCommon/interface/TkDetMap.h
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLorentzAnglePCLHarvester.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#44377 [14.0.X] EL9-migration related patches to All-in-one
  Alignment/OfflineValidation/bin/DMRtrends.cc
  Alignment/OfflineValidation/bin/PVtrends.cc
  Alignment/OfflineValidation/plugins/TrackerGeometryCompare.cc
  Alignment/OfflineValidation/plugins/TrackerGeometryCompare.h
  Alignment/OfflineValidation/python/TkAlAllInOneTool/MTS.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/MTS_cfg.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/findAndChange.py
  Alignment/OfflineValidation/python/TkAlAllInOneTool/templates/condorTemplate.submit
  Alignment/OfflineValidation/python/TkAlMap.py
  Alignment/OfflineValidation/scripts/validateAlignments.py
  Alignment/OfflineValidation/src/Trend.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#44354 Updating ONNXRuntime to 1.17.1
  PhysicsTools/ONNXRuntime/interface/ONNXRuntime.h
Labels: fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, ml-approved

#44328 [ROOTMaster] Fix include for RNTuple* (redo of #44256)
  Alignment/OfflineValidation/bin/DiMuonVmerge.cc
  Alignment/OfflineValidation/macros/loopAndPlot.C
  PhysicsTools/NanoAOD/plugins/rntuple/NanoAODRNTupleOutputModule.cc
  PhysicsTools/NanoAOD/plugins/rntuple/NanoAODRNTuples.cc
  PhysicsTools/NanoAOD/plugins/rntuple/NanoAODRNTuples.h
  PhysicsTools/NanoAOD/plugins/rntuple/TableOutputFields.h
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, trk

#44366 MSSM Hbb trigger dqm updates for 2024 triggers [14.0.X]
  DQMOffline/Trigger/python/MssmHbbBtagTriggerMonitor_Client_cfi.py
  DQMOffline/Trigger/python/MssmHbbBtagTriggerMonitor_cff.py
  DQMOffline/Trigger/python/MssmHbbBtagTriggerMonitor_cfi.py
  DQMOffline/Trigger/python/MssmHbbMonitoring_Client_cfi.py
  DQMOffline/Trigger/python/MssmHbbMonitoring_cff.py
  HLTriggerOffline/Higgs/python/hltHiggsPostProcessors_cff.py
  HLTriggerOffline/Higgs/python/hltHiggsValidator_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44379 [13_0_HeavyIon_X] Pythia8 photon flux
  GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc
  GeneratorInterface/Pythia8Interface/test/pythia8ex2_ConvertToMain70_cfg.py
  GeneratorInterface/Pythia8Interface/test/pythia8ex2_ConvertToMain70_cfg_Fragment.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44378 [14.0.X] add input / output LA `TkDetMaps` in `SiStripLorentzAnglePCLHarvester`
  CalibTracker/SiStripCommon/interface/TkDetMap.h
  CalibTracker/SiStripLorentzAngle/plugins/SiStripLorentzAnglePCLHarvester.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#44393 Update unpacker for L1T Calo scouting
  EventFilter/L1ScoutingRawToDigi/interface/blocks.h
  EventFilter/L1ScoutingRawToDigi/plugins/ScCALORawToDigi.cc
  EventFilter/L1ScoutingRawToDigi/plugins/ScCALORawToDigi.h
  EventFilter/L1ScoutingRawToDigi/plugins/ScGMTRawToDigi.cc
  EventFilter/L1ScoutingRawToDigi/plugins/ScGMTRawToDigi.h
  EventFilter/L1ScoutingRawToDigi/python/ScCaloRawToDigi_cfi.py
  EventFilter/L1ScoutingRawToDigi/python/ScGMTRawToDigi_cfi.py
Labels: daq-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44389 Update 2024 MC GTs with the L1 menu L1Menu_Collisions2024_v1_0_1_xml
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#44054 Get AXOL1TL model version from menu as of utm v0.12.0
  Configuration/AlCa/python/autoCondModifiers.py
  Configuration/HLT/python/autoCondHLT.py
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  L1Trigger/L1TGlobal/interface/AXOL1TLCondition.h
  L1Trigger/L1TGlobal/interface/AXOL1TLTemplate.h
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.h
  L1Trigger/L1TGlobal/python/simGtStage2Digis_cfi.py
  L1Trigger/L1TGlobal/src/AXOL1TLCondition.cc
  L1Trigger/L1TGlobal/src/AXOL1TLTemplate.cc
  L1Trigger/L1TGlobal/src/GlobalBoard.cc
Labels: alca-approved, hlt-approved, l1-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#44382 `L1TUtmTriggerMenu_PayloadInspector`: support comparison of conditions
  CondCore/L1TPlugins/interface/L1TUtmTriggerMenuPayloadInspectorHelper.h
  CondCore/L1TPlugins/plugins/L1TUtmTriggerMenu_PayloadInspector.cc
  CondCore/L1TPlugins/test/testL1TObjectsPayloadInspector.cpp
  CondCore/L1TPlugins/test/testL1TPI.sh
Labels: l1-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#44061 Update Pythia Hook for BB4L
  GeneratorInterface/Pythia8Interface/plugins/PowhegHooksBB4L.h
  GeneratorInterface/Pythia8Interface/src/Py8InterfaceBase.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#43941 Add TF AOT interface.
  PhysicsTools/TensorFlow/test/createconstantgraph.py
  PhysicsTools/TensorFlow/test/readconstantgraph.py
  PhysicsTools/TensorFlowAOT/BuildFile.xml
  PhysicsTools/TensorFlowAOT/interface/Batching.h
  PhysicsTools/TensorFlowAOT/interface/Model.h
  PhysicsTools/TensorFlowAOT/interface/Util.h
  PhysicsTools/TensorFlowAOT/interface/Wrapper.h
  PhysicsTools/TensorFlowAOT/scripts/compile_model.py
  PhysicsTools/TensorFlowAOT/scripts/create_wrapper.py
  PhysicsTools/TensorFlowAOT/src/Batching.cc
  PhysicsTools/TensorFlowAOT/src/Wrapper.cc
  PhysicsTools/TensorFlowAOT/templates/wrapper.h.in
  PhysicsTools/TensorFlowAOT/test/BuildFile.xml
  PhysicsTools/TensorFlowAOT/test/create_model.py
  PhysicsTools/TensorFlowAOT/test/testAOTTools.py
  PhysicsTools/TensorFlowAOT/test/testBase.h
  PhysicsTools/TensorFlowAOT/test/testInterface.cc
  PhysicsTools/TensorFlowAOT/test/testRunner.cpp
  PhysicsTools/TensorFlowAOT/test/test_models/create_models.sh
Labels: fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, ml-approved

#43522 Allow a stream to skip a lumi if all events processed
  FWCore/Framework/src/EventProcessor.cc
  FWCore/Framework/src/LuminosityBlockProcessingStatus.cc
  FWCore/Framework/src/LuminosityBlockProcessingStatus.h
  FWCore/Framework/test/modules_2_concurrent_lumis_cfg.py
  FWCore/Framework/test/stubs/TestGlobalAnalyzers.cc
  FWCore/Framework/test/stubs/TestGlobalFilters.cc
  FWCore/Framework/test/stubs/TestGlobalProducers.cc
  FWCore/Framework/test/stubs/TestLimitedAnalyzers.cc
  FWCore/Framework/test/stubs/TestLimitedFilters.cc
  FWCore/Framework/test/stubs/TestLimitedProducers.cc
  FWCore/Framework/test/testRunLumiCaches_cfg.py
  FWCore/Framework/test/test_earlyTerminationSignal.sh
  FWCore/Framework/test/test_exceptionAtGlobalBeginRun_cfg.py
  FWCore/Framework/test/test_global_modules_cfg.py
  FWCore/Framework/test/test_limited_modules_cfg.py
  FWCore/Integration/test/test_TryToContinue_cfg.py
  FWCore/Services/plugins/CheckTransitions.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44395 Update for simulation of pixel bad components
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
  SimGeneral/MixingModule/python/pixelDigitizer_cfi.py
  SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py
Labels: simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#44384 Miscellaneous fixes for dqm online clients
  DQM/Integration/python/clients/pixellumi_dqm_sourceclient-live_cfg.py
  RecoVertex/PrimaryVertexProducer/python/OfflinePixel3DPrimaryVertices_cfi.py
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, tracking

#44385 [14.0.X] Miscellaneous fixes for dqm online clients
  DQM/Integration/python/clients/pixellumi_dqm_sourceclient-live_cfg.py
  RecoVertex/PrimaryVertexProducer/python/OfflinePixel3DPrimaryVertices_cfi.py
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, tracking

#44381 Make repack process be able to generate new data tiers: L1SCOUT, HLTSCOUT
  Configuration/DataProcessing/python/Repack.py
  Configuration/DataProcessing/test/RunRepack.py
  Configuration/EventContent/python/EventContent_cff.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#44406 Fix Looper type name used in python
  FWCore/ParameterSet/src/ParameterSetDescriptionFillerBase.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44387 Implement AlpakaBackendProducer and AlpakaBackendFilter
  HeterogeneousCore/AlpakaCore/plugins/AlpakaBackendFilter.cc
  HeterogeneousCore/AlpakaCore/plugins/BuildFile.xml
  HeterogeneousCore/AlpakaCore/plugins/alpaka/AlpakaBackendProducer.cc
  HeterogeneousCore/AlpakaCore/test/BuildFile.xml
  HeterogeneousCore/AlpakaCore/test/testAlpakaBackendFilter.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#44380 Make repack process be able to generate new data tiers: L1SCOUT, HLTSCOUT
  Configuration/DataProcessing/python/Repack.py
  Configuration/DataProcessing/test/RunRepack.py
  Configuration/EventContent/python/EventContent_cff.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44268 [10_6_X] CepGen generator interface
  Configuration/Generator/python/CepGen_LPAIR_GamGamToLL_singlediss_13TeV_cfi.py
  Configuration/Generator/python/CepGen_pptoff_GamGamToLL_singlediss_13TeV_cfi.py
  GeneratorInterface/CepGenInterface/BuildFile.xml
  GeneratorInterface/CepGenInterface/interface/CepGenEventGenerator.h
  GeneratorInterface/CepGenInterface/interface/CepGenParametersConverter.h
  GeneratorInterface/CepGenInterface/plugins/BuildFile.xml
  GeneratorInterface/CepGenInterface/plugins/CepGenGeneratorFilter.cc
  GeneratorInterface/CepGenInterface/python/cepgenDefaultParameters_cff.py
  GeneratorInterface/CepGenInterface/src/CepGenEventGenerator.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external

#44445 Fix plugin library name AlpakaCore/plugins/BuildFile.xml
  HeterogeneousCore/AlpakaCore/plugins/BuildFile.xml
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#44422 Add use of unsubtracted jets in RecoBTag info producers
  RecoBTag/FeatureTools/plugins/DeepBoostedJetTagInfoProducer.cc
  RecoBTag/FeatureTools/plugins/DeepFlavourTagInfoProducer.cc
  RecoBTag/FeatureTools/plugins/ParticleTransformerAK4TagInfoProducer.cc
  RecoBTag/FeatureTools/test/BuildFile.xml
  RecoBTag/FeatureTools/test/u0_cfg.py
  RecoJets/JetProducers/plugins/JetMatcherDR.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44426 Remove unused strstream to fix the deprecated header warning
  L1Trigger/L1TMuon/plugins/L1TMuonGlobalParamsESProducer.cc
  L1Trigger/L1TMuon/src/L1TMuonGlobalParamsHelper.cc
  L1Trigger/L1TMuonOverlap/plugins/L1TMuonOverlapTrackProducer.cc
  L1Trigger/L1TMuonOverlap/src/OMTFProcessor.cc
  L1Trigger/L1TMuonOverlap/src/OMTFSorter.cc
  L1TriggerConfig/L1TConfigProducers/src/L1TMuonGlobalParamsOnlineProd.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44427 KalmanFilter fix for Phase 2 L1 tracking
  L1Trigger/TrackFindingTMTT/src/KFbase.cc
Labels: l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#44441 Fix track sort order in PixelTrackProducerFromSoAAlpaka
  RecoTracker/PixelTrackFitting/plugins/PixelTrackProducerFromSoA.cc
  RecoTracker/PixelTrackFitting/plugins/PixelTrackProducerFromSoAAlpaka.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, tracking

#44429 Allow storing 2024 geometry in GEMGeometryParsFromDD
  Geometry/GEMGeometryBuilder/src/GEMGeometryParsFromDD.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#44434 `MillePedeAlignmentAlgorithm`: add a unit test for the mille step
  Alignment/MillePedeAlignmentAlgorithm/test/BuildFile.xml
  Alignment/MillePedeAlignmentAlgorithm/test/test_mille.py
  Alignment/MillePedeAlignmentAlgorithm/test/test_mille.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#44087 adding JME nano in autoNano
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/PyReleaseValidation/python/relval_nano.py
  PhysicsTools/NanoAOD/python/autoNANO.py
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved

#44430 Add NanoAOD flavours parameter to PromptReco
  Configuration/DataProcessing/python/Reco.py
  Configuration/DataProcessing/python/Utils.py
  Configuration/DataProcessing/test/RunPromptReco.py
  Configuration/DataProcessing/test/run_CfgTest_8.sh
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44376 Improve handling of TF CUDA tests for 14_1_X
  PhysicsTools/TensorFlow/src/TensorFlow.cc
  PhysicsTools/TensorFlow/test/BuildFile.xml
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, ml-approved

#44442 Fix track sort order in PixelTrackProducerFromSoAAlpaka [14.0.x]
  RecoTracker/PixelTrackFitting/plugins/PixelTrackProducerFromSoA.cc
  RecoTracker/PixelTrackFitting/plugins/PixelTrackProducerFromSoAAlpaka.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, tracking

#44439 Update the HLT alpaka customisation
  HLTrigger/Configuration/python/customizeHLTforAlpaka.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, hlt-integration

#44423 Produce r9 and trackIso(hollow cone) in EGamma development path
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEgammaHollowTrackIsoL1Seeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEgammaHollowTrackIsoUnseeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEgammaR9L1Seeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEgammaR9Unseeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTEle5OpenL1SeededSequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTEle5OpenUnseededSequence_cfi.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, egamma

#44462 Use default operator= in CondFormats/CSCObjects
  CondFormats/CSCObjects/interface/CSCDQM_DCSBase.h
  CondFormats/CSCObjects/interface/CSCDQM_DCSData.h
Labels: alca-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#44454 [14_0_X] Add NanoAOD flavours parameter to PromptReco
  Configuration/DataProcessing/python/Reco.py
  Configuration/DataProcessing/python/Utils.py
  Configuration/DataProcessing/test/RunPromptReco.py
  Configuration/DataProcessing/test/run_CfgTest_8.sh
Labels: operations-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44455 DeepTau - Do not call TF inference with empty grid
  RecoTauTag/HLTProducers/src/L2TauTagNNProducer.cc
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, ml-approved

#44431 modified for Phase2 DeepJet retraining model
  HLTrigger/Configuration/python/HLT_75e33/modules/hltPfDeepFlavourJetTagsModEta2p4_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltPfDeepFlavourJetTags_cfi.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#44388 Implement AlpakaBackendProducer and AlpakaBackendFilter [14.0.x]
  HeterogeneousCore/AlpakaCore/plugins/AlpakaBackendFilter.cc
  HeterogeneousCore/AlpakaCore/plugins/BuildFile.xml
  HeterogeneousCore/AlpakaCore/plugins/alpaka/AlpakaBackendProducer.cc
  HeterogeneousCore/AlpakaCore/test/BuildFile.xml
  HeterogeneousCore/AlpakaCore/test/testAlpakaBackendFilter.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, heterogeneous-approved

#44440 Update the HLT alpaka customisation [14.0.x]
  HLTrigger/Configuration/python/customizeHLTforAlpaka.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok, hlt-integration

#44412 add a python compilation unit test for DQM online clients
  DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hltrates_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1t_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage1emulator_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/physics_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
  DQM/Integration/test/BuildFile.xml
  DQM/Integration/test/runCompilationTest.sh
  DQM/Physics/python/qcdLowPtDQM_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44452 [14_0_X] Produce r9 and trackIso(hollow cone) in EGamma development path
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEgammaHollowTrackIsoL1Seeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEgammaHollowTrackIsoUnseeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEgammaR9L1Seeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltEgammaR9Unseeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/tasks/HLTEle5OpenL1SeededTask_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/tasks/HLTEle5OpenUnseededTask_cfi.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, backport-ok, egamma

#44407 Use standard naming for configs in CondTools/RunInfo
  CondCore/Utilities/o2o/deployed/online/RunInfoStart.sh
  CondCore/Utilities/o2o/deployed/online/RunInfoStartTest.sh
  CondCore/Utilities/o2o/deployed/online/RunInfoStop.sh
  CondCore/Utilities/o2o/deployed/online/RunInfoStopTest.sh
  CondCore/Utilities/o2o/templates/RunInfoStart.sh
  CondCore/Utilities/o2o/templates/RunInfoStartTest.sh
  CondCore/Utilities/o2o/templates/RunInfoStop.sh
  CondCore/Utilities/o2o/templates/RunInfoStopTest.sh
  CondTools/RunInfo/python/LHCInfoPerFillPopConAnalyzer_cfg.py
  CondTools/RunInfo/python/LHCInfoPerLSPopConAnalyzer_cfg.py
  CondTools/RunInfo/python/LHCInfoPopConAnalyzerEndFill_cfg.py
  CondTools/RunInfo/python/LHCInfoPopConAnalyzerStartFill_cfg.py
  CondTools/RunInfo/python/LHCInfoPopConAnalyzer_cfg.py
  CondTools/RunInfo/python/RunInfoPopConAnalyzer_cfg.py
  CondTools/RunInfo/test/RunInfoStart_O2O_test.sh
  CondTools/RunInfo/test/test_lhcInfoNewPopCon.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#44432 Updated quality bits of KMTF
  L1Trigger/L1TMuonBarrel/src/L1TMuonBarrelKalmanAlgo.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44460 Add GEM channel and strip payload dump utilities
  CondCore/Utilities/BuildFile.xml
  CondCore/Utilities/plugins/Module_2XML.cc
  CondCore/Utilities/src/CondDBFetch.cc
  CondCore/Utilities/src/CondDBImport.cc
  CondCore/Utilities/src/CondFormats.h
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#44466 reverts #44054 and #44389
  Configuration/AlCa/python/autoCond.py
  Configuration/AlCa/python/autoCondModifiers.py
  Configuration/HLT/python/autoCondHLT.py
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  L1Trigger/L1TGlobal/interface/AXOL1TLCondition.h
  L1Trigger/L1TGlobal/interface/AXOL1TLTemplate.h
  L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.h
  L1Trigger/L1TGlobal/python/simGtStage2Digis_cfi.py
  L1Trigger/L1TGlobal/src/AXOL1TLCondition.cc
  L1Trigger/L1TGlobal/src/AXOL1TLTemplate.cc
  L1Trigger/L1TGlobal/src/GlobalBoard.cc
Labels: alca-approved, hlt-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44467 TkAl: fix PV validation and PV resolution submission scripts
  Alignment/OfflineValidation/scripts/submitPVResolutionJobs.py
  Alignment/OfflineValidation/scripts/submitPVValidationJobs.py
  Alignment/OfflineValidation/test/PVResolutionExample.ini
  Alignment/OfflineValidation/test/PrimaryVertexResolution_templ_cfg.py
  Alignment/OfflineValidation/test/testingScripts/test_unitSubmitPVrbr.sh
  Alignment/OfflineValidation/test/testingScripts/test_unitSubmitPVsplit.sh
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#44482 Removed explicit copy ctr in TrackStub
  DataFormats/L1CSCTrackFinder/interface/TrackStub.h
  DataFormats/L1CSCTrackFinder/src/TrackStub.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44483 Apply rule-of-5 to ESPreFunctorDecorator
  FWCore/Framework/interface/ESPreFunctorDecorator.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44465 Add ESInputTag to VPSet default added to cfi file [14_0]
  FWCore/ParameterSet/python/Types.py
  FWCore/ParameterSet/src/FillDescriptionFromPSet.cc
  FWCore/Utilities/src/FileInPath.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, tests-external-failure

#44486 [CPP20][Analysis] Remove deprecated enum arithmetic
  DPGAnalysis/SiStripTools/plugins/TrackCount.cc
Labels: analysis-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#44490 [CPP20][RECONSTRUCTION] Remove deprecated enum arithmetic
  RecoPPS/Local/src/TotemTimingTrackRecognition.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44476 Improve error handling in GPU callbacks
  HeterogeneousCore/AlpakaCore/src/alpaka/EDMetadata.cc
  HeterogeneousCore/AlpakaInterface/BuildFile.xml
  HeterogeneousCore/AlpakaInterface/interface/HostOnlyTask.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#44472 [14.0.X] add a python compilation unit test for DQM online clients
  DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hltrates_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1t_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage1emulator_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/physics_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/sistrip_dqm_sourceclient-live_cfg.py
  DQM/Integration/test/BuildFile.xml
  DQM/Integration/test/runCompilationTest.sh
  DQM/Physics/python/qcdLowPtDQM_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44477 Improve error handling in GPU callbacks [14.0.x]
  HeterogeneousCore/AlpakaCore/src/alpaka/EDMetadata.cc
  HeterogeneousCore/AlpakaInterface/BuildFile.xml
  HeterogeneousCore/AlpakaInterface/interface/HostOnlyTask.h
Labels: fully-signed, tests-approved, orp-approved, backport-ok, heterogeneous-approved

#44480 Use standard file names in DQM/HcalTasks config files [14_0]
  DQM/HcalTasks/python/DigiTask_cfi.py
  DQM/HcalTasks/python/FCDTask_cfi.py
  DQM/HcalTasks/python/HFRaddamTask_cfi.py
  DQM/HcalTasks/python/HcalOfflineHarvesting_cfi.py
  DQM/HcalTasks/python/HcalOnlineHarvesting_cfi.py
  DQM/HcalTasks/python/HcalQualityTests_cfi.py
  DQM/HcalTasks/python/LEDTask_cfi.py
  DQM/HcalTasks/python/LaserTask_cfi.py
  DQM/HcalTasks/python/NoCQTask_cfi.py
  DQM/HcalTasks/python/OfflineHarvestSequence_cosmic.py
  DQM/HcalTasks/python/OfflineHarvestSequence_hi.py
  DQM/HcalTasks/python/OfflineHarvestSequence_pp.py
  DQM/HcalTasks/python/OfflineHarvestingSequence_cosmic.py
  DQM/HcalTasks/python/OfflineHarvestingSequence_hi.py
  DQM/HcalTasks/python/OfflineHarvestingSequence_pp.py
  DQM/HcalTasks/python/OfflineSourceSequence_cosmic.py
  DQM/HcalTasks/python/OfflineSourceSequence_hi.py
  DQM/HcalTasks/python/OfflineSourceSequence_pp.py
  DQM/HcalTasks/python/PedestalTask_cfi.py
  DQM/HcalTasks/python/QIE10Task_cfi.py
  DQM/HcalTasks/python/QIE11Task_cfi.py
  DQM/HcalTasks/python/RawTask_cfi.py
  DQM/HcalTasks/python/RecHitTask_cfi.py
  DQM/HcalTasks/python/TPTask_cfi.py
  DQM/HcalTasks/python/TestTask_cfi.py
  DQM/HcalTasks/python/UMNioTask_cfi.py
  DQM/HcalTasks/python/ZDCTask_cff.py
  DQM/Integration/python/clients/hcal_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hcalcalib_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hcalgpu_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/hcalreco_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#44495 [14_0_X] PFMet and PuppiMET Branches in NanoAOD
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#44458 Improve the memory usage in the alpaka pixel reconstruction
  DataFormats/TrackingRecHitSoA/interface/TrackingRecHitsDevice.h
  DataFormats/TrackingRecHitSoA/test/alpaka/Hits_test.cc
  HeterogeneousCore/AlpakaInterface/interface/OneToManyAssoc.h
  HeterogeneousCore/AlpakaInterface/test/alpaka/testPrefixScan.dev.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToCluster.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, heterogeneous-approved, tracking, trk

#44402 Change FEStatus flag labels in ECAL DQM
  DQM/EcalCommon/interface/FEFlags.h
  DQM/EcalMonitorClient/src/RawDataClient.cc
  DQM/EcalMonitorTasks/python/RawDataTask_cfi.py
  DQM/EcalMonitorTasks/src/RawDataTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44459 Improve the memory usage in the alpaka pixel reconstruction [14.0.x]
  DataFormats/TrackingRecHitSoA/interface/TrackingRecHitsDevice.h
  DataFormats/TrackingRecHitSoA/test/alpaka/Hits_test.cc
  HeterogeneousCore/AlpakaInterface/interface/OneToManyAssoc.h
  HeterogeneousCore/AlpakaInterface/test/alpaka/testPrefixScan.dev.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToCluster.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, heterogeneous-approved, tracking, trk

#44404 Change FEStatus flag labels in ECAL DQM [14_0_X]
  DQM/EcalCommon/interface/FEFlags.h
  DQM/EcalMonitorClient/src/RawDataClient.cc
  DQM/EcalMonitorTasks/python/RawDataTask_cfi.py
  DQM/EcalMonitorTasks/src/RawDataTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved

#44473 HLT XGBoost Photon MVA and Diphoton combination filter
  HLTrigger/Egamma/plugins/HLTEgammaDoubleXGBoostCombFilter.cc
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTClusterShapeProducer.cc
  RecoEgamma/PhotonIdentification/BuildFile.xml
  RecoEgamma/PhotonIdentification/interface/PhotonXGBoostEstimator.h
  RecoEgamma/PhotonIdentification/plugins/PhotonXGBoostProducer.cc
  RecoEgamma/PhotonIdentification/src/PhotonXGBoostEstimator.cc
  RecoEgamma/PhotonIdentification/test/BuildFile.xml
  RecoEgamma/PhotonIdentification/test/test_PhotonMvaXgb.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, hlt-integration

#44464 fix standard and upgrade validation workflows
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: pending-signatures, tests-approved, pdmv-pending, orp-approved, upgrade-approved, code-checks-approved

#44478 Phase2-hgx354B First attempt to prepare components of XML file for the scintillator components in the mixed layers of HGCal
  Geometry/HGCalCommonData/interface/HGCalProperty.h
  Geometry/HGCalCommonData/interface/HGCalTileIndex.h
  Geometry/HGCalCommonData/src/HGCalTileIndex.cc
  Geometry/HGCalCommonData/test/HGCalConvert.cpp
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#44396 Moved modules.py out of edmWriteConfig
  FWCore/ParameterSet/bin/edmWriteConfigs.cpp
  FWCore/ParameterSet/templates/modules.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44405 MTD Validation: Characterization of PU contribution in vertices
  Validation/MtdValidation/plugins/BuildFile.xml
  Validation/MtdValidation/plugins/MtdTracksValidation.cc
  Validation/MtdValidation/plugins/Primary4DVertexValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#44447 Initialize statsGuard_ on LogErrorEventFilter
  DPGAnalysis/Skims/src/LogErrorEventFilter.cc
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#44463 Use default op= in LASModuleProfile
  Alignment/LaserAlignment/interface/LASModuleProfile.h
  Alignment/LaserAlignment/src/LASModuleProfile.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk
