Repository cms-sw/cmssw, pull requests merged in 2024-09, with the labels that each got.

#45799 [14.0.X] Update Pixel GPU DQM online client
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  DQM/Integration/python/clients/pixelgpu_dqm_sourceclient-live_cfg.py
  DQM/SiPixelHeterogeneous/plugins/SiPixelCompareTrackSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelCompareTracks.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelMonitorTrackSoA.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelMonitorTrackSoAAlpaka.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelTrackComparisonHarvester.cc
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQMHarvesting_cff.py
Labels: dqm-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok, tracking, trk

#45750 [14_0_X] HCAL DQM Online Histogram for Bad Quality Events
  DQM/HcalTasks/data/HcalQualityTests.xml
  DQM/HcalTasks/interface/DigiTask.h
  DQM/HcalTasks/interface/RawTask.h
  DQM/HcalTasks/plugins/DigiTask.cc
  DQM/HcalTasks/plugins/RawTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45780 [14.0.X] Add certificates handling to Tier0Handler
  CondCore/Utilities/python/tier0.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, backport-ok

#45824 [14.1.X] Add certificates handling to Tier0Handler
  CondCore/Utilities/python/tier0.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, backport-ok

#45819 [14.1.X] L1T DQM: Combined backport of cms-sw/cmssw#45242 and cms-sw/cmssw#45634
  DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py
  DQM/L1TMonitor/python/L1TStage2uGTTiming_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45837 `TrackingRecHitsSoACollection`: early return `hostData` in `CopyHost::copyAsync()` when there aren't hits
  DataFormats/TrackingRecHitSoA/interface/alpaka/TrackingRecHitsSoACollection.h
  RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGenerator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved, heterogeneous-approved, tracking

#45852 Implement a test for the `copyFromDense` and `copyToDense` utilities
  DataFormats/TrackSoA/test/BuildFile.xml
  DataFormats/TrackSoA/test/alpaka/TrajectoryStateSoA_t.cc
  DataFormats/TrackSoA/test/alpaka/TrajectoryStateSoA_t.dev.cc
  DataFormats/TrackSoA/test/alpaka/TrajectoryStateSoA_t.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved, tracking, tests-ib-failure

#44924 [DT] Position fix and new filter to TPs from Phase2 L1T emulator
  L1Trigger/DTTriggerPhase2/interface/GlobalCoordsObtainer.h
  L1Trigger/DTTriggerPhase2/interface/MPCoincidenceFilter.h
  L1Trigger/DTTriggerPhase2/interface/constants.h
  L1Trigger/DTTriggerPhase2/plugins/DTTrigPhase2Prod.cc
  L1Trigger/DTTriggerPhase2/python/dtTriggerPhase2PrimitiveDigis_cfi.py
  L1Trigger/DTTriggerPhase2/src/GlobalCoordsObtainer.cc
  L1Trigger/DTTriggerPhase2/src/MPCoincidenceFilter.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathCorFitter.cc
  L1Trigger/DTTriggerPhase2/src/MuonPathSLFitter.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#45843 Add option to sort candidates by pT in Unified Particle Transformer
  RecoBTag/FeatureTools/plugins/UnifiedParticleTransformerAK4TagInfoProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45798 Reduce RelVal Events for `B0ToJpsiK0s_JMM_Filter_DGamma0`
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#45822 Phase2-hgx359X Modify the testing code in several packages in view of changes made in the Configuration/Geometry area for Phase2 scenarios
  CalibCalorimetry/EBPhase2TPGTools/test/runEBPhase2TPParamProducer.py
  CondTools/SiPixel/test/SiPixel2DTemplateDBObjectUploader_Phase2_cfg.py
  Geometry/CaloTopology/test/testHGCalTopology_cfg.py
  SimCalorimetry/EcalEBTrigPrimProducers/test/testPhase2_13_1_0_pre3.py
Labels: alca-approved, geometry-approved, l1-approved, fully-signed, tests-approved, db-approved, orp-approved, upgrade-approved, code-checks-approved, trk

#45813 improve pagination of `L1TUtmTriggerMenuPayloadInspector` plots
  CondCore/L1TPlugins/interface/L1TUtmTriggerMenuPayloadInspectorHelper.h
  CondCore/L1TPlugins/plugins/L1TUtmTriggerMenu_PayloadInspector.cc
Labels: l1-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#45684 [BTV, NanoAOD] Add UParT discriminants for strange-jet tagging
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_CHS_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_Puppi_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  RecoBTag/ONNXRuntime/python/pfUnifiedParticleTransformerAK4DiscriminatorsJetTags_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#45868 Fix issue with ZDCSimpleRecAlgo_Run3.cc
  RecoLocalCalo/HcalRecAlgos/src/ZdcSimpleRecAlgo_Run3.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#45867 Add certificates handling to `G2GainsValidator.py`
  CondCore/SiStripPlugins/scripts/G2GainsValidator.py
  CondCore/SiStripPlugins/scripts/testCompare.sh
  CondCore/SiStripPlugins/test/BuildFile.xml
  CondCore/SiStripPlugins/test/test_G2GainsValidator.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, trk

#45719 another apptainer workaround [13_3_X]
  HeterogeneousCore/SonicTriton/scripts/cmsTriton
Labels: fully-signed, tests-approved, orp-approved, backport-ok, heterogeneous-approved

#45801 Add possibility for a `CopyToHost::postCopy()` operation
  DataFormats/PortableTestObjects/interface/TestProductWithPtr.h
  DataFormats/PortableTestObjects/src/alpaka/classes_cuda.h
  DataFormats/PortableTestObjects/src/alpaka/classes_cuda_def.xml
  DataFormats/PortableTestObjects/src/alpaka/classes_rocm.h
  DataFormats/PortableTestObjects/src/alpaka/classes_rocm_def.xml
  DataFormats/PortableTestObjects/src/classes.h
  DataFormats/PortableTestObjects/src/classes_def.xml
  HeterogeneousCore/AlpakaCore/README.md
  HeterogeneousCore/AlpakaCore/interface/alpaka/ProducerBase.h
  HeterogeneousCore/AlpakaInterface/interface/CopyToHost.h
  HeterogeneousCore/AlpakaTest/plugins/TestAlpakaAnalyzerProductWithPtr.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaGlobalProducerWithPtr.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/testPtrAlgoAsync.dev.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/testPtrAlgoAsync.h
  HeterogeneousCore/AlpakaTest/test/BuildFile.xml
  HeterogeneousCore/AlpakaTest/test/testAlpakaModulesCopyOfPtr_cfg.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#45829 Fixed CLCT sorting in CSC TP emulator and synchronize the config to the Point-5 data-taking settings
  L1Trigger/CSCTriggerPrimitives/interface/CSCUpgradeCathodeLCTProcessor.h
  L1Trigger/CSCTriggerPrimitives/python/params/clctParams.py
  L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeCathodeLCTProcessor.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45730 [GCC13][AlCa] Avoid Wdangling-reference in SiPhase2OuterTrackerFakeLorentzAngleESSource
  CalibTracker/SiPhase2TrackerESProducers/plugins/SiPhase2OuterTrackerFakeLorentzAngleESSource.cc
  CondFormats/DataRecord/interface/SiPhase2OuterTrackerCondDataRecords.h
Labels: alca-approved, core-approved, fully-signed, tests-approved, db-approved, orp-approved, upgrade-approved, code-checks-approved, trk

#45866 add few more default geometry tests in `Geometry/TrackerGeometryBuilder`
  Geometry/TrackerGeometryBuilder/test/python/testPhase2TrackerHierarchy_cfg.py
  Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDD4hep_cfg.py
  Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDDD_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#45858 [14.0.X] `TrackingRecHitsSoACollection`: early return `hostData` in `CopyHost::copyAsync()` when there aren't hits
  DataFormats/TrackingRecHitSoA/interface/alpaka/TrackingRecHitsSoACollection.h
  RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGenerator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, heterogeneous-approved, tracking

#45857 [14.1.X] `TrackingRecHitsSoACollection`: early return `hostData` in `CopyHost::copyAsync()` when there aren't hits
  DataFormats/TrackingRecHitSoA/interface/alpaka/TrackingRecHitsSoACollection.h
  RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGenerator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, heterogeneous-approved, tracking

#45876 Alpaka Pixel: Write `nTracks=0` When No Track Stored
  RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGenerator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, tracking

#45881 [13_0_X_HLT] set bypassVersionCheck default to True again
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent

#45878 [14_1_X] Alpaka Pixel: Write `nTracks=0` When No Track Stored
  RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGenerator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, tracking

#45877 [14_0_X] Alpaka Pixel: Write `nTracks=0` When No Track Stored
  RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGenerator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, tracking

#45694 Update to `relval_gpu.py`for Alpaka and Pixel Triplets Alpaka Workflows
  Configuration/PyReleaseValidation/README.md
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQM_FirstStep_cff.py
  DataFormats/VertexSoA/interface/ZVertexDefinitions.h
  RecoTracker/Configuration/python/customizePixelTracksForTriplets.py
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, heterogeneous-approved, tracking, trk

#45635 Updates and Bug Fixes for NanoAOD related to muon
  PhysicsTools/NanoAOD/python/custom_muon_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#45755 change tune names for auto-bkg production
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP1DownSettings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP1UpSettings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP2DownSettings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP2UpSettings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP3DownSettings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP3UpSettings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP4DownSettings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP4UpSettings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP5CR1Settings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP5CR2Settings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP5DownSettings_cfi.py
  Configuration/Generator/python/MCTunesRun3ECM13p6TeV/PythiaCP5UpSettings_cfi.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45766 Add ECAL DCC desync DQM trend plots and update the DQM threshold for Integrity summary
  DQM/EcalMonitorClient/python/IntegrityClient_cfi.py
  DQM/EcalMonitorClient/src/IntegrityClient.cc
  DQM/EcalMonitorTasks/python/RawDataTask_cfi.py
  DQM/EcalMonitorTasks/src/RawDataTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45786 Another workaround for -O3 ASAN compilation issue in CTPPSProtonReconstructionPlotter
  Validation/CTPPS/plugins/CTPPSProtonReconstructionPlotter.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tests-ib-failure

#45795 Add plotting utilities to generate Tracker maps given user input
  DQM/TrackerRemapper/bin/BuildFile.xml
  DQM/TrackerRemapper/bin/printPixelLayersDisksMap.cc
  DQM/TrackerRemapper/bin/printPixelROCsMap.cc
  DQM/TrackerRemapper/bin/printPixelTrackerMap.cc
  DQM/TrackerRemapper/bin/printStripTrackerMap.cc
  DQM/TrackerRemapper/src/SiStripTkMaps.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#45849 Phase2-hgx359Z Update the scripts in Validation/HGCalValidation for the changes in Configuration/Geometry
  Validation/HGCalValidation/macros/MakePlots.C
  Validation/HGCalValidation/scripts/muonTomo.sh
  Validation/HGCalValidation/scripts/testHGCalCellHitSum_cfg.py
  Validation/HGCalValidation/scripts/testHGCalDigi_cfg.py
  Validation/HGCalValidation/scripts/testHGCalMTRecoStudy_cfg.py
  Validation/HGCalValidation/scripts/testHGCalReco_cfg.py
  Validation/HGCalValidation/scripts/testHGCalSimSingleMuonPt100_cfg.py
  Validation/HGCalValidation/scripts/testHGCalSimTTBar_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45836 Adding Golden Workflows for 2022 and 2023 Data
  Configuration/PyReleaseValidation/python/relval_data_highstats.py
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#45840 Improve QTest Pixel DQM
  DQM/SiPixelPhase1Config/test/qTests/mean_charge_qualitytest_config.xml
  DQM/SiPixelPhase1Config/test/qTests/mean_size_qualitytest_config.xml
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#45879 Update run3_data GT in autoCond from 140X_dataRun3_v4 to 140X_dataRun3_v9
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45889 [DQM-GEOMETRY] Changes suggested by new llvm18 clang-format
  Validation/Geometry/src/MaterialBudgetAction.cc
Labels: dqm-approved, geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45895 [ML] Changes suggested by new llvm18 clang-format
  PhysicsTools/TensorFlowAOT/test/testInterface.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, ml-approved

#45896 [HETEROGENEOUS] Changes suggested by new llvm18 clang-format
  HeterogeneousCore/AlpakaCore/plugins/alpaka/AlpakaBackendProducer.cc
  HeterogeneousCore/AlpakaInterface/interface/CachedBufAlloc.h
  HeterogeneousCore/AlpakaInterface/test/alpaka/testPrefixScan.dev.cc
  HeterogeneousCore/CUDACore/interface/ScopedContext.h
  HeterogeneousCore/CUDAUtilities/interface/device_unique_ptr.h
  HeterogeneousCore/CUDAUtilities/interface/host_noncached_unique_ptr.h
  HeterogeneousCore/CUDAUtilities/interface/host_unique_ptr.h
  HeterogeneousCore/SonicTriton/interface/TritonDummyCache.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#45902 [FASTSIM] Changes suggested by new llvm18 clang-format
  FastSimulation/CTPPSFastGeometry/interface/CTPPSToFDetector.h
  FastSimulation/CTPPSFastGeometry/interface/CTPPSTrkDetector.h
  FastSimulation/CaloGeometryTools/interface/CaloPoint.h
  FastSimulation/CaloGeometryTools/interface/CaloSegment.h
  FastSimulation/CaloGeometryTools/interface/CrystalPad.h
  FastSimulation/CaloHitMakers/src/EcalHitMaker.cc
  FastSimulation/Calorimetry/src/CalorimetryManager.cc
  FastSimulation/Event/interface/FSimTrackEqual.h
  FastSimulation/MaterialEffects/interface/CMSDummyDeexcitation.h
  FastSimulation/MaterialEffects/interface/MaterialEffectsSimulator.h
  FastSimulation/MaterialEffects/interface/MultipleScatteringSimulator.h
  FastSimulation/ShowerDevelopment/src/FastHFShowerLibrary.cc
  FastSimulation/ShowerDevelopment/src/HDShower.cc
  FastSimulation/ShowerDevelopment/src/HFShower.cc
  FastSimulation/SimplifiedGeometryPropagator/interface/BarrelSimplifiedGeometry.h
  FastSimulation/SimplifiedGeometryPropagator/interface/CMSDummyDeexcitation.h
  FastSimulation/SimplifiedGeometryPropagator/interface/Constants.h
  FastSimulation/SimplifiedGeometryPropagator/interface/ForwardSimplifiedGeometry.h
  FastSimulation/Tracking/interface/TrackingLayer.h
  FastSimulation/TrackingRecHitProducer/src/PixelResolutionHistograms.cc
  FastSimulation/TrackingRecHitProducer/src/PixelTemplateSmearerBase.cc
  FastSimulation/Validation/plugins/EmptySimHits.cc
Labels: fastsim-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#45913 [DQM-L1] Changes suggested by new llvm18 clang-format
  DQMOffline/L1Trigger/interface/L1TEfficiencyHarvesting.h
  DQMOffline/L1Trigger/interface/L1TMuonDQMOffline.h
  DQMOffline/L1Trigger/interface/L1TPhase2MuonOffline.h
  DQMOffline/L1Trigger/interface/L1TTauOffline.h
  DQMOffline/L1Trigger/src/L1TSync_Offline.cc
Labels: dqm-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45904 [GEOMETRY] Changes suggested by new llvm18 clang-format
  DetectorDescription/Core/interface/DDBase.h
  DetectorDescription/Core/src/DDExpandedView.cc
  DetectorDescription/Core/test/DDFilter.cppunit.cc
  DetectorDescription/OfflineDBLoader/plugins/OutputDDToDDL.cc
  DetectorDescription/OfflineDBLoader/plugins/OutputMagneticFieldDDToDDL.cc
  DetectorDescription/OfflineDBLoader/src/GeometryInfoDump.cc
  DetectorDescription/RegressionTest/interface/DDErrorDetection.h
  DetectorDescription/RegressionTest/interface/DDHtmlFormatter.h
  DetectorDescription/RegressionTest/src/TagName.h
  DetectorDescription/RegressionTest/test/tutorial.cc
  Geometry/CSCGeometry/interface/CSCWireGroupPackage.h
  Geometry/CSCGeometry/interface/OffsetRadialStripTopology.h
  Geometry/CSCGeometryBuilder/src/CSCGeometryBuilder.cc
  Geometry/CaloEventSetup/plugins/CaloGeometryBuilder.h
  Geometry/CaloGeometry/interface/CaloCellCrossing.h
  Geometry/CaloGeometry/interface/CaloNumberingScheme.h
  Geometry/CaloGeometry/interface/Line3D.h
  Geometry/CaloTopology/interface/CaloSubdetectorTopology.h
  Geometry/CaloTopology/interface/EcalBarrelHardcodedTopology.h
  Geometry/CaloTopology/interface/EcalBarrelTopology.h
  Geometry/CaloTopology/interface/EcalEndcapHardcodedTopology.h
  Geometry/CaloTopology/interface/EcalEndcapTopology.h
  Geometry/CaloTopology/src/CaloSubdetectorTopology.cc
  Geometry/CommonTopologies/src/TkRadialStripTopology.cc
  Geometry/CommonTopologies/src/TwoBowedSurfacesDeformation.cc
  Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromDDD.cc
  Geometry/DTGeometryBuilder/src/DTGeometryParsFromDD.cc
  Geometry/EcalMapping/interface/ESElectronicsMapper.h
  Geometry/EcalTestBeam/plugins/EcalTBHodoscopeGeometryLoaderFromDDD.h
  Geometry/HcalAlgo/plugins/DDHCalBarrelAlgo.cc
  Geometry/HcalAlgo/plugins/DDHCalEndcapAlgo.cc
  Geometry/MuonNumbering/interface/CSCNumberingScheme.h
  Geometry/MuonNumbering/interface/GEMNumberingScheme.h
  Geometry/MuonNumbering/interface/LevelBaseNumber.h
  Geometry/MuonNumbering/interface/ME0NumberingScheme.h
  Geometry/MuonNumbering/interface/MuonBaseNumber.h
  Geometry/MuonNumbering/interface/MuonGeometryNumbering.h
  Geometry/MuonNumbering/interface/MuonNumberingScheme.h
  Geometry/MuonNumbering/interface/MuonSubDetector.h
  Geometry/MuonNumbering/interface/RPCNumberingScheme.h
  Validation/MuonRPCGeometry/interface/Constants.h
  Validation/MuonRPCGeometry/plugins/RPCPhiEff.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45918 [DB-RECONSTRUCTION] Changes suggested by new llvm18 clang-format
  CondFormats/SiPixelTransient/interface/SiPixelGenError.h
  CondFormats/SiPixelTransient/interface/SiPixelTemplate2D.h
Labels: reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, trk

#45921 [DB-HLT] Changes suggested by new llvm18 clang-format
  CondCore/HLTPlugins/plugins/AlCaRecoTriggerBits_PayloadInspector.cc
Labels: hlt-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#45928 [HETERO-RECO-UPGRADE] Changes suggested by new llvm18 clang-format
  CUDADataFormats/HGCal/interface/HGCRecHitSoA.h
  CUDADataFormats/HGCal/interface/HGCUncalibRecHitSoA.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, heterogeneous-approved

#45906 [DAQ-RECONSTRUCTION] Changes suggested by new llvm18 clang-format
  DataFormats/OnlineMetaData/test/onlineMetaDataRecord_t.cpp
Labels: daq-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45903 [DAQ] Changes suggested by new llvm18 clang-format
  EventFilter/ESDigiToRaw/interface/ESDataFormatter.h
  EventFilter/EcalDigiToRaw/src/BlockFormatter.cc
  EventFilter/L1ScoutingRawToDigi/plugins/ScBMTFRawToDigi.cc
  EventFilter/L1ScoutingRawToDigi/plugins/ScCALORawToDigi.cc
  EventFilter/L1ScoutingRawToDigi/plugins/ScGMTRawToDigi.cc
  EventFilter/RawDataCollector/interface/RawDataFEDSelector.h
  EventFilter/Utilities/interface/DAQSourceModelsFRD.h
  EventFilter/Utilities/interface/DAQSourceModelsScoutingRun3.h
  EventFilter/Utilities/interface/JsonSerializable.h
  EventFilter/Utilities/plugins/FRDStreamSource.h
  IORawData/CSCCommissioning/src/CSCFileDumper.h
  L1TriggerScouting/Utilities/plugins/DumpScObjects.cc
Labels: daq-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45917 [XPOG] Changes suggested by new llvm18 clang-format
  DPGAnalysis/HcalNanoAOD/plugins/HcalUHTRTableProducer.cc
  DPGAnalysis/HcalNanoAOD/plugins/HcalUMNioTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuCSCTnPFlatTableProducer.cc
  DPGAnalysis/MuonTools/plugins/MuGEMMuonExtTableProducer.cc
  PhysicsTools/NanoAOD/plugins/BJetEnergyRegressionVarProducer.cc
  PhysicsTools/NanoAOD/plugins/BTVMCFlavourTableProducer.cc
  PhysicsTools/NanoAOD/plugins/BTagSFProducer.cc
  PhysicsTools/NanoAOD/plugins/GenJetFlavourTableProducer.cc
  PhysicsTools/NanoAOD/plugins/IsFromLostTrackMapProducer.cc
  PhysicsTools/NanoAOD/plugins/LeptonInJetProducer.cc
  PhysicsTools/NanoAOD/plugins/LeptonJetVarProducer.cc
  PhysicsTools/NanoAOD/plugins/NanoAODBaseCrossCleaner.h
  PhysicsTools/NanoAOD/plugins/PileupJetIDVarProducer.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, hcal

#45898 [VISUALIZATION] Changes suggested by new llvm18 clang-format
  Fireworks/Calo/interface/scaleMarker.h
  Fireworks/Calo/plugins/FWTracksterHitsProxyBuilder.cc
  Fireworks/Core/interface/FWJobMetadataUpdateRequest.h
  Fireworks/Core/interface/FWProxyBuilderBase.h
  Fireworks/Core/interface/FWViewManagerBase.h
  Fireworks/Core/src/CSGConnector.h
  Fireworks/Core/src/FW3DViewDistanceMeasureTool.h
  Fireworks/Core/src/FWGeometryTableViewBase.cc
  Fireworks/Core/src/fwPaletteExtra.cc
  Fireworks/FWInterface/src/FWPSetCellEditor.h
  Fireworks/Tracks/plugins/FWItemTrackAccessors.cc
  Fireworks/Tracks/plugins/FWSiPixelDigiProxyBuilder.cc
  Fireworks/Tracks/plugins/FWSiStripDigiProxyBuilder.cc
Labels: visualization-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45914 [DQM-HLT] Changes suggested by new llvm18 clang-format
  DQM/HLTEvF/plugins/FourVectorHLT.h
  DQM/HLTEvF/plugins/HLTObjectMonitor.cc
  DQM/HLTEvF/plugins/HLTObjectMonitorProtonLead.cc
Labels: dqm-approved, hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45894 [RECONSTRUCTION-UPGRADE] Changes suggested by new llvm18 clang-format
  RecoHGCal/TICL/interface/TICLInterpretationAlgoBase.h
  RecoHGCal/TICL/interface/TracksterLinkingAlgoBase.h
  RecoHGCal/TICL/plugins/ClusterFilterBase.h
  RecoHGCal/TICL/plugins/ClusterFilterByAlgo.h
  RecoHGCal/TICL/plugins/ClusterFilterByAlgoAndSize.h
  RecoHGCal/TICL/plugins/ClusterFilterByAlgoAndSizeAndLayerRange.h
  RecoHGCal/TICL/plugins/ClusterFilterBySize.h
  RecoHGCal/TICL/plugins/GeneralInterpretationAlgo.cc
  RecoHGCal/TICL/plugins/LinkingAlgoBase.h
  RecoHGCal/TICL/plugins/MergedTrackstersProducer.cc
  RecoHGCal/TICL/plugins/SeedingRegionAlgoBase.h
  RecoHGCal/TICL/plugins/SeedingRegionByL1.h
  RecoHGCal/TICL/plugins/SeedingRegionGlobal.cc
  RecoHGCal/TICL/plugins/SeedingRegionGlobal.h
  RecoHGCal/TICL/plugins/TICLCandidateProducer.cc
  RecoHGCal/TICL/plugins/TICLLayerTileProducer.cc
  RecoHGCal/TICL/plugins/TracksterLinkingbyFastJet.h
  RecoHGCal/TICL/plugins/TrackstersMergeProducer.cc
  RecoHGCal/TICL/test/TiclDebugger.cc
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalRecHitAbsAlgo.h
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalRecHitSimpleAlgo.h
  RecoLocalCalo/HGCalRecAlgos/interface/HGCalUncalibRecHitRecWeightsAlgo.h
  RecoLocalCalo/HGCalRecAlgos/src/HGCalDepthPreClusterer.cc
  RecoLocalCalo/HGCalRecProducers/interface/HGCalImagingAlgo.h
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalImagingAlgo.cc
  RecoLocalCalo/HGCalRecProducers/plugins/HGCalUncalibRecHitWorkerWeights.h
  RecoLocalCalo/HGCalRecProducers/src/ComputeClusterTime.cc
  RecoLocalFastTime/FTLClusterizer/interface/MTDClusterParameterEstimator.h
  RecoLocalFastTime/FTLCommonAlgos/interface/MTDRecHitAlgoBase.h
  RecoLocalFastTime/FTLCommonAlgos/interface/MTDTimeCalib.h
  RecoLocalFastTime/FTLRecProducers/plugins/MTDTrackingRecHitProducer.cc
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegFit.h
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentAlgorithm.h
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentBuilder.cc
  RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegmentBuilder.h
  RecoLocalMuon/GEMCSCSegment/test/GEMCSCCoincidenceRateAnalyzer.cc
  RecoLocalMuon/GEMRecHit/interface/GEMClusterizer.h
  RecoLocalMuon/GEMRecHit/interface/GEMMaskReClusterizer.h
  RecoLocalMuon/GEMSegment/plugins/GE0SegAlgoRU.h
  RecoLocalMuon/GEMSegment/plugins/GEMSegmentAlgorithmBase.h
  RecoLocalMuon/GEMSegment/plugins/ME0SegAlgoRU.h
  RecoLocalMuon/GEMSegment/plugins/ME0SegmentAlgorithmBase.h
  RecoLocalTracker/Phase2TrackerRecHits/interface/Phase2StripCPEGeometric.h
  RecoLocalTracker/Phase2TrackerRecHits/plugins/Phase2TrackerRecHits.cc
  RecoLocalTracker/SiPhase2VectorHitBuilder/interface/VectorHitBuilderAlgorithm.h
  RecoMTD/DetLayers/interface/MTDDetSector.h
  RecoMTD/TransientTrackingRecHit/interface/MTDTransientTrackingRecHitBuilder.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, trk

#45923 [DQM-RECONSTRUCTION] Changes suggested by new llvm18 clang-format
  CommonTools/TrackerMap/interface/TrackerMap.h
  CommonTools/TrackerMap/src/TrackerMap.cc
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#45905 [RECONSTRUCTION-XPOG] Changes suggested by new llvm18 clang-format
  DataFormats/PatCandidates/interface/JetCorrFactors.h
  DataFormats/PatCandidates/interface/ParametrizationHelper.h
  DataFormats/PatCandidates/interface/ResolutionHelper.h
  DataFormats/PatCandidates/interface/TauJetCorrFactors.h
  DataFormats/PatCandidates/interface/TriggerAlgorithm.h
  DataFormats/PatCandidates/interface/TriggerCondition.h
  DataFormats/PatCandidates/interface/TriggerEvent.h
  DataFormats/PatCandidates/interface/TriggerFilter.h
  DataFormats/PatCandidates/interface/TriggerObject.h
  DataFormats/PatCandidates/interface/TriggerObjectStandAlone.h
  DataFormats/PatCandidates/src/PATTauDiscriminator.cc
  PhysicsTools/PatAlgos/interface/BaseIsolator.h
  PhysicsTools/PatAlgos/interface/BaseMVAValueMapProducer.h
  PhysicsTools/PatAlgos/interface/HemisphereAlgo.h
  PhysicsTools/PatAlgos/interface/IsoDepositIsolator.h
  PhysicsTools/PatAlgos/interface/SimpleIsolator.h
  PhysicsTools/PatAlgos/plugins/DeDxEstimatorRekeyer.cc
  PhysicsTools/PatAlgos/plugins/JetCorrFactorsProducer.cc
  PhysicsTools/PatAlgos/plugins/PATLeptonTimeLifeInfoProducer.cc
  PhysicsTools/PatAlgos/plugins/PATObjectUserDataEmbedder.cc
  PhysicsTools/PatAlgos/plugins/PATRefitVertexProducer.cc
  PhysicsTools/PatAlgos/plugins/PATSecondaryVertexSlimmer.cc
  PhysicsTools/PatAlgos/plugins/PATTauHybridProducer.cc
  PhysicsTools/PatAlgos/plugins/PATTauIDEmbedder.cc
  PhysicsTools/PatAlgos/plugins/PATTauSignalCandidatesProducer.cc
  PhysicsTools/PatAlgos/plugins/PATTriggerEventProducer.cc
  PhysicsTools/PatAlgos/plugins/PATTriggerMatchEmbedder.cc
  PhysicsTools/PatAlgos/plugins/PATTriggerObjectStandAloneSlimmer.cc
  PhysicsTools/PatAlgos/plugins/PATTriggerObjectStandAloneUnpacker.cc
  PhysicsTools/PatAlgos/plugins/PATTriggerProducer.cc
  PhysicsTools/PatAlgos/plugins/TauJetCorrFactorsProducer.cc
  PhysicsTools/PatUtils/interface/RazorComputer.h
  PhysicsTools/PatUtils/interface/TriggerHelper.h
  PhysicsTools/PatUtils/plugins/PFMatchedCandidateRefExtractor.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#45900 [GEOMETRY-UPGRADE] Changes suggested by new llvm18 clang-format
  Geometry/HGCalCommonData/interface/HGCalParameters.h
  Geometry/HGCalCommonData/test/HGCalConvert.cpp
  Geometry/HGCalGeometry/test/HGCalValidScintTest.cc
  SLHCUpgradeSimulations/Geometry/test/Phase2PixelNtuple.cc
  SLHCUpgradeSimulations/Geometry/test/StdHitNtuplizer.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#45897 [HLT] Changes suggested by new llvm18 clang-format
  HLTrigger/Egamma/plugins/HLTEgammaDoubleXGBoostCombFilter.cc
  HLTrigger/Egamma/plugins/HLTEgammaL1MatchFilterRegional.cc
  HLTrigger/Egamma/plugins/HLTEgammaL1TMatchFilterRegional.cc
  HLTrigger/Egamma/plugins/HLTElectronEoverpFilterRegional.cc
  HLTrigger/Egamma/plugins/HLTElectronOneOEMinusOneOPFilterRegional.cc
  HLTrigger/Egamma/plugins/HLTElectronPixelMatchFilter.cc
  HLTrigger/HLTcore/interface/TriggerSummaryProducerAOD.h
  HLTrigger/JetMET/interface/HLTCATopTagFilter.h
  HLTrigger/JetMET/src/HLTHcalLaserFilter.cc
  HLTrigger/JetMET/src/HLTHcalTowerNoiseCleaner.cc
  HLTrigger/JetMET/src/HLTHcalTowerNoiseCleanerWithrechit.cc
  HLTrigger/JetMET/src/HLTJetCollectionsForBoostedLeptonPlusJets.cc
  HLTrigger/JetMET/src/HLTJetVBFFilter.cc
  HLTrigger/Muon/plugins/HLTMuonDimuonL3Filter.cc
  HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc
  HLTrigger/Muon/plugins/HLTMuonTrimuonL3Filter.cc
  HLTrigger/Tools/bin/hltDiff.cc
  HLTrigger/special/plugins/HLTCSCOverlapFilter.cc
  HLTrigger/special/plugins/HLTCSCRing2or3Filter.cc
  RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTCaloTowerProducer.cc
  RecoEgamma/EgammaHLTProducers/plugins/HLTRecHitInAllL1RegionsProducer.cc
  RecoTauTag/HLTProducers/interface/L2TauPixelIsoTagProducer.h
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45892 [ALCA-RECONSTRUCTION] Changes suggested by new llvm18 clang-format
  RecoVertex/BeamSpotProducer/src/BeamFitter.cc
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#45875 Add 2024 HiMix MC RelVal workflows
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#45891 [L1-SIMULATION] Changes suggested by new llvm18 clang-format
  SimTracker/TrackTriggerAssociation/plugins/TTClusterAssociator.cc
  SimTracker/TrackTriggerAssociation/plugins/TTStubAssociator.cc
Labels: l1-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#45874 Phase2-hgx360 Try to introduce the right longitudinal structure to the V10 version of HGCal geometry
  Geometry/CMSCommonData/data/caloBase/2026/v8/caloBase.xml
  Geometry/HGCalCommonData/data/hgcal/v19/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalEE/v19/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v19/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v19/hgcalHEsil.xml
  Geometry/HGCalCommonData/data/hgcalMaterial/v3/hgcalMaterial.xml
  Geometry/HGCalCommonData/data/hgcalPassive/v19/hgcalPassive.xml
  Geometry/HGCalCommonData/data/hgcalwafer/v19/hgcalwafer.xml
  Geometry/HGCalCommonData/plugins/DDHGCalPassive.cc
  Geometry/HGCalCommonData/plugins/DDHGCalSiliconRotatedCassette.cc
  Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalPassive.cc
  Geometry/HGCalCommonData/python/testHGCalV19XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#45911 [RECONSTRUCTION-SIMULATION] Changes suggested by new llvm18 clang-format
  DataFormats/CTPPSDigi/interface/CTPPSDiamondDigi.h
  DataFormats/CTPPSDigi/interface/TotemRPDigi.h
Labels: reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45909 [SIMULATION-UPGRADE] Changes suggested by new llvm18 clang-format
  DataFormats/GEMDigi/interface/GEMAMC.h
  DataFormats/GEMDigi/interface/GEMOptoHybrid.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/LCToCPAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/LCToSCAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/LCToSimTSAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/TSToSCAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/TSToSimTSAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalSimAlgos/interface/HGCalRadiationMap.h
  SimCalorimetry/HGCalSimAlgos/interface/HGCalSciNoiseMap.h
  SimCalorimetry/HGCalSimAlgos/interface/HGCalSiNoiseMap.h
  SimCalorimetry/HGCalSimProducers/interface/HGCDigitizerBase.h
  SimFastTiming/MtdAssociatorProducers/plugins/MtdRecoClusterToSimLayerClusterAssociatorByHitsImpl.cc
  SimG4CMS/HGCalTestBeam/plugins/HGCalTBAnalyzer.cc
  SimMuon/GEMDigitizer/src/ME0PreRecoGaussianModel.cc
  SimMuon/GEMDigitizer/test/GEMDigiReader.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#45820 Change ScoutingNano event content
  PhysicsTools/NanoAOD/plugins/SimpleScoutingFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/python/custom_run3scouting_cff.py
  PhysicsTools/NanoAOD/python/run3scouting_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#45882 [12_4_X_HLT] set bypassVersionCheck default to True again
  Configuration/DataProcessing/python/Merge.py
  Configuration/DataProcessing/test/RunMerge.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, urgent

#45861 Add a `zeroInitialise()` method to portable objects and collections
  DataFormats/Portable/interface/PortableDeviceCollection.h
  DataFormats/Portable/interface/PortableDeviceObject.h
  DataFormats/Portable/interface/PortableHostCollection.h
  DataFormats/Portable/interface/PortableHostObject.h
  DataFormats/PortableTestObjects/test/TestSoA.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlgo.dev.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlgo.h
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaProducer.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#45676 GEM TnP efficiency plots with bad VFAT masking and Etapartition-wise measurements
  DQMOffline/MuonDPG/BuildFile.xml
  DQMOffline/MuonDPG/plugins/GEMTnPEfficiencyTask.cc
  DQMOffline/MuonDPG/python/gemTnPEfficiencyClient_cfi.py
  DQMOffline/MuonDPG/python/gemTnPEfficiencyTask_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45873 Patch in MuonBeamspotConstraintValueMapProducer for VertexException
  RecoMuon/GlobalTrackingTools/plugins/MuonBeamspotConstraintValueMapProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#45809 modify turnon plots of BTV DQM
  DQMOffline/Trigger/plugins/BTVHLTOfflineSource.cc
  DQMOffline/Trigger/python/BTVHLTOfflineSource_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45890 [DQM-GENERATORS] Changes suggested by new llvm18 clang-format
  Validation/EventGenerator/interface/BPhysicsValidation.h
  Validation/EventGenerator/interface/BasicHepMCValidation.h
  Validation/EventGenerator/interface/HiggsValidation.h
  Validation/EventGenerator/interface/WeightManager.h
Labels: dqm-approved, generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45920 [DB-DQM] Changes suggested by new llvm18 clang-format
  CondFormats/DQMObjects/interface/HDQMSummary.h
  DQM/BeamMonitor/plugins/BeamMonitor.cc
  DQM/BeamMonitor/plugins/BeamMonitorBx.cc
  DQM/BeamMonitor/plugins/FakeBeamMonitor.cc
Labels: dqm-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, tracking

#45893 [HLT-RECONSTRUCTION] Changes suggested by new llvm18 clang-format
  RecoMuon/L3MuonProducer/src/L3TkMuonProducer.cc
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45899 [GENERATORS] Changes suggested by new llvm18 clang-format
  GeneratorInterface/AlpgenInterface/src/AlpgenHeader.cc
  GeneratorInterface/Core/plugins/ExternalGeneratorFilter.cc
  GeneratorInterface/CosmicMuonGenerator/src/CMSCGEN.cc
  GeneratorInterface/EvtGenInterface/interface/DataCardFileWriter.h
  GeneratorInterface/EvtGenInterface/interface/EvtGenInterfaceBase.h
  GeneratorInterface/ExhumeInterface/interface/Particle.h
  GeneratorInterface/ExhumeInterface/interface/Weight.h
  GeneratorInterface/GenFilters/plugins/HerwigMaxPtPartonFilter.cc
  GeneratorInterface/GenFilters/plugins/MCMultiParticleFilter.cc
  GeneratorInterface/GenFilters/plugins/MCPdgIndexFilter.h
  GeneratorInterface/GenFilters/plugins/ZgammaMassFilter.cc
  GeneratorInterface/Hydjet2Interface/test/Hydjet2Analyzer.cc
  GeneratorInterface/HydjetInterface/test/HydjetAnalyzer.cc
  GeneratorInterface/PhotosInterface/interface/PhotosInterfaceBase.h
  GeneratorInterface/Pythia6Interface/interface/PtYDistributor.h
  GeneratorInterface/Pythia8Interface/plugins/EmissionVetoHook1.cc
  GeneratorInterface/Pythia8Interface/plugins/Py8toJetInput.cc
  GeneratorInterface/RivetInterface/interface/DQMRivetClient.h
  GeneratorInterface/RivetInterface/interface/RivetAnalysis.h
  GeneratorInterface/RivetInterface/plugins/GenParticles2HepMCConverter.cc
  GeneratorInterface/RivetInterface/plugins/MergedGenParticleProducer.hh
  GeneratorInterface/TauolaInterface/interface/TauSpinnerCMS.h
  GeneratorInterface/TauolaInterface/interface/TauSpinnerFilter.h
  GeneratorInterface/TauolaInterface/interface/TauolaInterfaceBase.h
  GeneratorInterface/TauolaInterface/plugins/TauSpinner/TauSpinnerCMS.cc
  IOMC/ParticleGuns/src/MultiParticleInConeGunProducer.cc
  SimDataFormats/GeneratorProducts/interface/GenLumiInfoHeader.h
Labels: generators-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45915 [PDMV] Changes suggested by new llvm18 clang-format
  DPGAnalysis/Skims/src/CSCSkim.cc
  DPGAnalysis/Skims/src/PickEvents.cc
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, code-checks-approved

#45517 [12_4_X] CepGenInterface: Added missing include
  GeneratorInterface/CepGenInterface/interface/CepGenEventGenerator.h
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external

#45828 TauSpinner weight table producer for HTT
  PhysicsTools/NanoAOD/plugins/BuildFile.xml
  PhysicsTools/NanoAOD/plugins/TauSpinnerTableProducer.cc
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/tauSpinnerTable_cfi.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#45943 Tier0Handler: add maxTime, improve cert warning
  CondCore/Utilities/python/tier0.py
  CondCore/Utilities/scripts/conddb
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, tests-ib-failure

#45845 [14_1_X] Add option to sort candidates by pT in Unified Particle Transformer
  RecoBTag/FeatureTools/plugins/UnifiedParticleTransformerAK4TagInfoProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45869 [14_1_X] Fix issue with ZdcSimpleRecAlgo_Run3.cc
  RecoLocalCalo/HcalRecAlgos/src/ZdcSimpleRecAlgo_Run3.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45937 Update run3_data GT in autoCond from 140X_dataRun3_v4 to 140X_dataRun3_v9 [14_1_X]
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45935 [141X] Patch in MuonBeamspotConstraintValueMapProducer for VertexException
  RecoMuon/GlobalTrackingTools/plugins/MuonBeamspotConstraintValueMapProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved

#45949 [14_1_X] Backport of #45820: Change ScoutingNano event content
  PhysicsTools/NanoAOD/plugins/SimpleScoutingFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/python/custom_run3scouting_cff.py
  PhysicsTools/NanoAOD/python/run3scouting_cff.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#45933 Add ECAL DCC desync DQM trend plots and update the DQM threshold for Integrity summary [14_1_X]
  DQM/EcalMonitorClient/python/IntegrityClient_cfi.py
  DQM/EcalMonitorClient/src/IntegrityClient.cc
  DQM/EcalMonitorTasks/python/RawDataTask_cfi.py
  DQM/EcalMonitorTasks/src/RawDataTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45934 [14_1_X] Add 2024 HiMix MC RelVal workflows
  Configuration/PyReleaseValidation/python/relval_pileup.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#45833 [Backport 14.1.X] Refine RPCDigis Validation histograms
  Validation/MuonRPCDigis/interface/RPCDigiValid.h
  Validation/MuonRPCDigis/python/validationMuonRPCDigis_cfi.py
  Validation/MuonRPCDigis/src/RPCDigiValid.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45954 fix `SiStripBadStrip_PayloadInspector` after merging of cms-sw/cmssw#45795
  CondCore/SiStripPlugins/plugins/SiStripBadStrip_PayloadInspector.cc
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, urgent, code-checks-approved, trk

#45926 [ALCA-UPGRADE] Changes suggested by new llvm18 clang-format
  CalibTracker/SiPhase2TrackerESProducers/interface/SiPhase2OuterTrackerFakeLorentzAngleESSource.h
  CalibTracker/SiPhase2TrackerESProducers/plugins/SiPhase2BadStripConfigurableFakeESSource.cc
  CalibTracker/SiPhase2TrackerESProducers/plugins/SiPhase2OuterTrackerFakeLorentzAngleESSource.cc
  CondTools/SiPhase2Tracker/plugins/SiPhase2BadStripChannelBuilder.cc
  CondTools/SiPhase2Tracker/plugins/SiPhase2BadStripChannelReader.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, trk

#45932 [Phase 2 L1T] fixing ASAN errors in Phase2L1CaloJetEmulator
  L1Trigger/L1CaloTrigger/plugins/Phase2L1CaloJetEmulator.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#45951 Phase2-hgx360A Modify the V19 longitudinal structure of HGCal according to Meeting specification of 06/09/2024
  Geometry/HGCalCommonData/data/hgcal/v19/hgcal.xml
  Geometry/HGCalCommonData/data/hgcalEE/v19/hgcalEE.xml
  Geometry/HGCalCommonData/data/hgcalHEmix/v19/hgcalHEmix.xml
  Geometry/HGCalCommonData/data/hgcalHEsil/v19/hgcalHEsil.xml
  Geometry/HGCalCommonData/data/hgcalMaterial/v3/hgcalMaterial.xml
  Geometry/HGCalCommonData/data/hgcalwafer/v19/hgcalwafer.xml
  Geometry/HGCalCommonData/test/python/dumpHGCalDDD_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#45936 [140X] Patch in MuonBeamspotConstraintValueMapProducer for VertexException
  RecoMuon/GlobalTrackingTools/plugins/MuonBeamspotConstraintValueMapProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved

#45841 Improve QTest Pixel DQM (BP to [14_0_X])
  DQM/SiPixelPhase1Config/test/qTests/mean_charge_qualitytest_config.xml
  DQM/SiPixelPhase1Config/test/qTests/mean_size_qualitytest_config.xml
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#45835 [Backport 14.0.X] Refine RPCDigis Validation histograms
  Validation/MuonRPCDigis/interface/RPCDigiValid.h
  Validation/MuonRPCDigis/python/validationMuonRPCDigis_cfi.py
  Validation/MuonRPCDigis/src/RPCDigiValid.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45761 Add ECAL DCC desync DQM trend plots and update the DQM threshold for Integrity summary [14_0_13]
  DQM/EcalMonitorClient/python/IntegrityClient_cfi.py
  DQM/EcalMonitorClient/src/IntegrityClient.cc
  DQM/EcalMonitorTasks/python/RawDataTask_cfi.py
  DQM/EcalMonitorTasks/src/RawDataTask.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45862 rename modifier `run3_2024_L1T` to `stage2L1Trigger_2024` [`14_1_X`]
  Configuration/Eras/python/Era_Run3_2024_cff.py
  Configuration/Eras/python/Modifier_stage2L1Trigger_2024_cff.py
  DQM/L1TMonitor/python/L1TStage2uGTTiming_cfi.py
  DQM/L1TMonitor/python/L1TdeStage2EMTF_cff.py
  L1Trigger/L1TMuonBarrel/python/simKBmtfDigis_cfi.py
Labels: dqm-approved, l1-approved, operations-approved, fully-signed, tests-approved, orp-approved, backport

#45846 [13_2_X] Add option to sort candidates by pT in Unified Particle Transformer
  RecoBTag/FeatureTools/plugins/UnifiedParticleTransformerAK4TagInfoProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved

#45968 Additional tracks filter for vertices (minimum no. strip hits)
  RecoVertex/PrimaryVertexProducer/interface/TrackFilterForPVFinding.h
  RecoVertex/PrimaryVertexProducer/src/TrackFilterForPVFinding.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#45955 Reset Pixel Dead channels map Online GUI
  DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#45606 Phase-2 GT interface update and slice test pattern writers
  DataFormats/L1Trigger/interface/P2GTCandidate.h
  DataFormats/L1Trigger/src/P2GTCandidate.cc
  DataFormats/L1Trigger/src/classes_def.xml
  L1Trigger/Phase2L1GT/README.md
  L1Trigger/Phase2L1GT/plugins/L1GTAlgoBoardWriter.cc
  L1Trigger/Phase2L1GT/plugins/L1GTDoubleObjectCond.cc
  L1Trigger/Phase2L1GT/plugins/L1GTEvaluationInterface.h
  L1Trigger/Phase2L1GT/plugins/L1GTEvaluationProducer.cc
  L1Trigger/Phase2L1GT/plugins/L1GTFinOrBoardWriter.cc
  L1Trigger/Phase2L1GT/plugins/L1GTObjectBoardWriter.cc
  L1Trigger/Phase2L1GT/plugins/L1GTOutputObjectWriter.cc
  L1Trigger/Phase2L1GT/plugins/L1GTProducer.cc
  L1Trigger/Phase2L1GT/plugins/L1GTQuadObjectCond.cc
  L1Trigger/Phase2L1GT/plugins/L1GTSingleCollectionCut.h
  L1Trigger/Phase2L1GT/plugins/L1GTSingleObjectCond.cc
  L1Trigger/Phase2L1GT/plugins/L1GTTripleObjectCond.cc
  L1Trigger/Phase2L1GT/python/l1tGTBoardWriterVU13P_cff.py
  L1Trigger/Phase2L1GT/python/l1tGTBoardWriterVU9P_cff.py
  L1Trigger/Phase2L1GT/python/l1tGTBoardWriter_cff.py
  L1Trigger/Phase2L1GT/python/l1tGTMenu_BTagSeeds_cff.py
  L1Trigger/Phase2L1GT/python/l1tGTMenu_crossLepSeeds_cff.py
  L1Trigger/Phase2L1GT/python/l1tGTMenu_hadr_crossLepSeeds_cff.py
  L1Trigger/Phase2L1GT/python/l1tGTMenu_lepSeeds_cff.py
  L1Trigger/Phase2L1GT/python/l1tGTProducer_cff.py
  L1Trigger/Phase2L1GT/test/gt_firmware_evaluation.py
  L1Trigger/Phase2L1GT/test/test_GT.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, changes-dataformats

#45973 Fix mismatch between EB and EE recHits in Phase2 supercluster producer configs
  HLTrigger/Configuration/python/HLT_75e33/modules/hltParticleFlowSuperClusterECALUnseeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltParticleFlowSuperClusterECAL_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltParticleFlowSuperClusterHGCal_cfi.py
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, egamma

#45947 Better exception message if module label in ESInputTag doesn't match
  FWCore/Framework/interface/ESRecordsToProductResolverIndices.h
  FWCore/Framework/interface/EventSetupRecord.h
  FWCore/Framework/interface/EventSetupRecordImpl.h
  FWCore/Framework/interface/NoDataException.h
  FWCore/Framework/interface/NoProductResolverException.h
  FWCore/Framework/src/EDConsumerBase.cc
  FWCore/Framework/src/ESProducer.cc
  FWCore/Framework/src/ESRecordsToProductResolverIndices.cc
  FWCore/Framework/src/ESTagGetter.cc
  FWCore/Framework/src/EventSetupRecordImpl.cc
  FWCore/Framework/src/NoDataException.cc
  FWCore/Framework/src/NoProductResolverException.cc
  FWCore/Framework/test/eventsetup_t.cppunit.cc
  FWCore/Framework/test/eventsetuprecord_t.cppunit.cc
  FWCore/Framework/test/test_catch2notTP_ESRecordsToProductResolverIndices.cc
  FWCore/Utilities/interface/ESIndices.h
  RecoLuminosity/LumiProducer/test/TestDIPLumiProducer.cc
  RecoLuminosity/LumiProducer/test/TestLumiCorrectionSource.cc
Labels: core-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45927 [ALCA-L1] Changes suggested by new llvm18 clang-format
  CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc
  CalibCalorimetry/HcalTPGAlgos/interface/HcalEmap.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
Labels: alca-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45977 o2oRun_SiStripDCS email warning fix
  CondTools/SiStrip/scripts/o2oRun_SiStripDCS.py
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, urgent, code-checks-approved, trk

#45978 [14_1_X] o2oRun_SiStripDCS email warning fix
  CondTools/SiStrip/scripts/o2oRun_SiStripDCS.py
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, backport, trk

#45979 [14_0_X] o2oRun_SiStripDCS email warning fix
  CondTools/SiStrip/scripts/o2oRun_SiStripDCS.py
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, backport, trk

#45970 [14_1_X] Additional tracks filter for vertices (minimum no. strip hits)
  RecoVertex/PrimaryVertexProducer/interface/TrackFilterForPVFinding.h
  RecoVertex/PrimaryVertexProducer/src/TrackFilterForPVFinding.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, tracking

#45957 Reset Pixel Dead ROCs map Online GUI (BP to 14_1_X)
  DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#45956 Reset Pixel Dead ROCs map Online GUI (BP to 14_0_X)
  DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk

#45981 Add 2024 HI eras to reco processing configuation
  Configuration/DataProcessing/python/Impl/ppEra_Run3_2024_UPC.py
  Configuration/DataProcessing/python/Impl/ppEra_Run3_2024_ppRef.py
  Configuration/DataProcessing/python/Impl/ppEra_Run3_pp_on_PbPb_2024.py
  Configuration/DataProcessing/python/Impl/ppEra_Run3_pp_on_PbPb_approxSiStripClusters_2024.py
  Configuration/DataProcessing/python/RecoTLR.py
  Configuration/DataProcessing/test/run_CfgTest_5.sh
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45803 migrate calotowers creation code to use `EcalPFRecHitThresholds`
  RecoLocalCalo/CaloTowersCreator/python/calotowermaker_cfi.py
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersCreationAlgo.cc
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersCreationAlgo.h
  RecoLocalCalo/CaloTowersCreator/src/CaloTowersCreator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, hlt-integration

#45985 Adding subGenJets to NanoGEN
  PhysicsTools/NanoAOD/python/nanogen_cff.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#45887 Split ZVertexSoA in a run-time sized PortableMultiCollection
  DQM/SiPixelHeterogeneous/plugins/SiPixelCompareVertices.cc
  DQM/SiPixelHeterogeneous/plugins/SiPixelMonitorVertexSoAAlpaka.cc
  DataFormats/VertexSoA/README.md
  DataFormats/VertexSoA/interface/ZVertexDefinitions.h
  DataFormats/VertexSoA/interface/ZVertexDevice.h
  DataFormats/VertexSoA/interface/ZVertexHost.h
  DataFormats/VertexSoA/interface/ZVertexSoA.h
  DataFormats/VertexSoA/interface/alpaka/ZVertexSoACollection.h
  DataFormats/VertexSoA/src/classes.cc
  DataFormats/VertexSoA/src/classes_def.xml
  DataFormats/VertexSoA/test/alpaka/ZVertexSoA_test.cc
  DataFormats/VertexSoA/test/alpaka/ZVertexSoA_test.dev.cc
  DataFormats/VertexSoA/test/alpaka/ZVertexSoA_test.h
  RecoTauTag/HLTProducers/src/L2TauTagNNProducerAlpaka.cc
  RecoTracker/PixelTrackFitting/plugins/PixelTrackDumpAlpaka.cc
  RecoVertex/Configuration/python/RecoPixelVertexing_cff.py
  RecoVertex/PixelVertexFinding/plugins/PixelVertexProducerFromSoAAlpaka.cc
  RecoVertex/PixelVertexFinding/plugins/alpaka/PixelVertexProducerAlpaka.cc
  RecoVertex/PixelVertexFinding/plugins/alpaka/PixelVertexWorkSpaceSoADeviceAlpaka.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/clusterTracksByDensity.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/clusterTracksDBSCAN.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/clusterTracksIterative.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/fitVertices.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/sortByPt2.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/splitVertices.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/vertexFinder.dev.cc
  RecoVertex/PixelVertexFinding/plugins/alpaka/vertexFinder.h
  RecoVertex/PixelVertexFinding/test/alpaka/VertexFinder_t.dev.cc
Labels: dqm-approved, hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved, tracking, trk, changes-dataformats

#45990 Update in autoCond 141X data and MC GTs for HI, and also synchronize them with the updated 140X ones
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45960 GEM TnP efficiency plots with bad VFAT masking and Etapartition-wise measurements (backport of #45676, 14_1_X)
  DQMOffline/MuonDPG/BuildFile.xml
  DQMOffline/MuonDPG/plugins/GEMTnPEfficiencyTask.cc
  DQMOffline/MuonDPG/python/gemTnPEfficiencyClient_cfi.py
  DQMOffline/MuonDPG/python/gemTnPEfficiencyTask_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45989 Fix small typo in `makePileupJSON.py`: `runNumber` → `run`
  RecoLuminosity/LumiDB/scripts/makePileupJSON.py
  RecoLuminosity/LumiDB/scripts/pileupCalc.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#45966 protect `SiStripTkMaps` in case of empty inputs, also test for it in unit tests
  DQM/TrackerRemapper/src/SiStripTkMaps.cc
  DQM/TrackerRemapper/test/test_catch2_SiStripTkMaps.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#45965 Update classes inheriting from ROOT::Minuit2::FCNBase to account for changes in ROOTmaster
  OnlineDB/CSCCondDB/interface/CSCThrTurnOnFcn.h
  OnlineDB/CSCCondDB/src/CSCFitAFEBThr.cc
  OnlineDB/CSCCondDB/src/CSCThrTurnOnFcn.cc
  RecoVertex/BeamSpotProducer/interface/BSpdfsFcn.h
  RecoVertex/BeamSpotProducer/interface/FcnBeamSpotFitPV.h
  RecoVertex/BeamSpotProducer/src/BSpdfsFcn.cc
  RecoVertex/BeamSpotProducer/src/FcnBeamSpotFitPV.cc
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved, tracking

#45508 customiser for alpaka patatrack pixel seeding for phase2
  HLTrigger/Configuration/python/HLT_75e33/eventsetup/hltESPPixelCPEFastParams_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/eventsetup/hltESPSiPixelCablingSoA_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/eventsetup/hltESPSiPixelGainCalibrationForHLTSoA_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltPhase2OnlineBeamSpotDevice_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltPhase2PixelTracksSoA_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltPhase2PixelTracks_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltPhase2SiPixelClustersSoA_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltPhase2SiPixelRecHitsSoA_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltSiPixelClusters_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltSiPixelRecHits_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTBeamSpotSequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTDoLocalPixelSequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTItLocalRecoSequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTPhase2PixelTracksSequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33_cff.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved, tracking

#45986 [SIM] improved initialisation
  SimG4Core/Application/src/RunManagerMT.cc
  SimG4Core/Application/src/RunManagerMTWorker.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45993 bugfix: remove DoubleSensGeomDet (ph-2 InnerTracker)
  Alignment/TrackerAlignment/test/Misalignments/createRandomlyMisalignedGeometry_Phase2_cfg.py
  Configuration/AlCa/python/autoCondPhase2.py
  Fireworks/Geometry/src/FWRecoGeometryESProducer.cc
  Geometry/TrackerGeometryBuilder/src/PixelTopologyMap.cc
  Geometry/TrackerGeometryBuilder/src/TrackerGeomBuilderFromGeometricDet.cc
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.cc
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.h
  RecoTracker/MeasurementDet/plugins/TkDoubleSensMeasurementDet.cc
  RecoTracker/MeasurementDet/plugins/TkDoubleSensMeasurementDet.h
Labels: alca-approved, geometry-approved, reconstruction-approved, visualization-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved, tracking, trk

#45997 Update in autoCond 141X data and MC GTs for HI, and also synchronize them with the updated 140X ones - CMSSW_14_1_X
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#46000 Support lumi-weighted input files for the TkAl Primary Vertex Validation plotting
  Alignment/OfflineValidation/macros/FitPVResiduals.C
  Alignment/OfflineValidation/macros/FitPVResolution.C
Labels: alca-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#45996 backport in 14_1_X of PR#45993: bug-fix: remove DoubleSensGeomDet (ph-2 InnerTracker)
  Alignment/TrackerAlignment/test/Misalignments/createRandomlyMisalignedGeometry_Phase2_cfg.py
  Configuration/AlCa/python/autoCondPhase2.py
  Fireworks/Geometry/python/dumpRecoGeometry_cfg.py
  Geometry/TrackerGeometryBuilder/src/PixelTopologyMap.cc
  Geometry/TrackerGeometryBuilder/src/TrackerGeomBuilderFromGeometricDet.cc
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.cc
  RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.h
  RecoTracker/MeasurementDet/plugins/TkDoubleSensMeasurementDet.cc
  RecoTracker/MeasurementDet/plugins/TkDoubleSensMeasurementDet.h
Labels: alca-approved, geometry-approved, reconstruction-approved, visualization-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, tracking, trk

#45783 adding xrootd lhe producer for run2 campaign cmssw
  GeneratorInterface/LHEInterface/data/run_generic_tarball_xrootd.sh
Labels: generators-approved, fully-signed, tests-approved, orp-approved

#45950 [14_0_X] Backport of 44970 and 45820 (ScoutingNano event content changes for 2024 and T0 scenario for HLTSCOUT datatier)
  Configuration/DataProcessing/python/Impl/hltScouting.py
  Configuration/DataProcessing/python/Impl/hltScoutingEra_Run3_2024.py
  Configuration/DataProcessing/test/BuildFile.xml
  Configuration/DataProcessing/test/run_CfgTest_13.sh
  Configuration/DataProcessing/test/run_CfgTest_8.sh
  Configuration/Eras/python/Era_Run3_2024_cff.py
  Configuration/Eras/python/Modifier_run3_scouting_nanoAOD_post2023_cff.py
  Configuration/PyReleaseValidation/python/relval_nano.py
  PhysicsTools/NanoAOD/plugins/SimpleScoutingFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/python/custom_run3scouting_cff.py
  PhysicsTools/NanoAOD/python/run3scouting_cff.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok, xpog-approved

#45962 GEM TnP efficiency plots with bad VFAT masking and Etapartition-wise measurements (backport of #45676, 14_0_X)
  DQMOffline/MuonDPG/BuildFile.xml
  DQMOffline/MuonDPG/plugins/GEMTnPEfficiencyTask.cc
  DQMOffline/MuonDPG/python/gemTnPEfficiencyClient_cfi.py
  DQMOffline/MuonDPG/python/gemTnPEfficiencyTask_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45987 [14_1_X] Add 2024 HI eras to reco processing configuation
  Configuration/DataProcessing/python/Impl/ppEra_Run3_2024_UPC.py
  Configuration/DataProcessing/python/Impl/ppEra_Run3_2024_ppRef.py
  Configuration/DataProcessing/python/Impl/ppEra_Run3_pp_on_PbPb_2024.py
  Configuration/DataProcessing/python/Impl/ppEra_Run3_pp_on_PbPb_approxSiStripClusters_2024.py
  Configuration/DataProcessing/python/RecoTLR.py
  Configuration/DataProcessing/test/run_CfgTest_5.sh
Labels: operations-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45827 Checks eta windows from the L1Trigger menu to ensure minimum <= maximum
  L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#46005 make `V0EventSelector` produce skimmed V0 collections based on their mass
  DQM/TrackingMonitorSource/plugins/V0EventSelector.cc
  DQM/TrackingMonitorSource/python/TrackingDataMCValidation_Standalone_cff.py
  DQM/TrackingMonitorSource/python/V0Selections_cfi.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#46006 Minuit2::FCNBase: fix for root 6.32
  RecoVertex/BeamSpotProducer/interface/BSpdfsFcn.h
  RecoVertex/BeamSpotProducer/interface/FcnBeamSpotFitPV.h
  RecoVertex/BeamSpotProducer/src/BSpdfsFcn.cc
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#45984 Added Era_Run3_2024 modifier to simOmtfDigis, to use OMTF 2024 config
  L1Trigger/L1TMuonOverlapPhase1/python/simOmtfDigis_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#45980 Replace CUDA with Alpaka wf in `relval_2026.py`
  Configuration/PyReleaseValidation/python/relval_2026.py
Labels: fully-signed, tests-approved, pdmv-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#45976 [TauHLT] Add Phase2 MuTau HLT
  HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTau27LooseTauWPDeepTau_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsSelectedPFTauLooseTauWPDeepTau_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL3crIsoL1TkSingleMu22EcalIso0p41_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL3crIsoL1TkSingleMu22HcalIso0p40_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL3crIsoL1TkSingleMu22HgcalIso4p70_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL3crIsoL1TkSingleMu22TrkIsoRegionalNewFiltered0p07EcalHcalHgcalTrk_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL3fL1TkSingleMu18Filtered20_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltPuppiTauTkMuon4218L1TkFilter_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_IsoMu20_eta2p1_LooseDeepTauPFTauHPS27_eta2p1_CrossL1_cfi.py
  HLTrigger/Configuration/python/HLT_75e33_cff.py
  HLTrigger/Configuration/python/HLT_75e33_timing_cff.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tau

#45511 Run3-hcx360 Make ZDC geometry varying with ERAs
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.h
  CondFormats/HcalObjects/interface/HcalCondObjectContainer.h
  CondFormats/HcalObjects/src/HcalCondObjectContainerBase.cc
  CondTools/Geometry/plugins/calowriters.cc
  Configuration/Geometry/python/GeometryRecoDB_cff.py
  Geometry/CaloGeometry/src/CaloGenericDetId.cc
  Geometry/CaloTopology/src/HcalTopology.cc
  Geometry/ForwardGeometry/BuildFile.xml
  Geometry/ForwardGeometry/interface/CaloGeometryDBZdc.h
  Geometry/ForwardGeometry/interface/ZdcGeometry.h
  Geometry/ForwardGeometry/interface/ZdcHardcodeGeometryLoader.h
  Geometry/ForwardGeometry/interface/ZdcTopology.h
  Geometry/ForwardGeometry/plugins/SealModule.cc
  Geometry/ForwardGeometry/plugins/ZdcHardcodeGeometryEP.cc
  Geometry/ForwardGeometry/plugins/ZdcHardcodeGeometryEP.h
  Geometry/ForwardGeometry/plugins/ZdcTopologyEP.cc
  Geometry/ForwardGeometry/plugins/ZdcTopologyEP.h
  Geometry/ForwardGeometry/plugins/moduleDB.cc
  Geometry/ForwardGeometry/python/ZdcGeometry_cfi.py
  Geometry/ForwardGeometry/src/ES_ZdcGeometry.cc
  Geometry/ForwardGeometry/src/ZdcGeometry.cc
  Geometry/ForwardGeometry/src/ZdcHardcodeGeometryLoader.cc
  Geometry/ForwardGeometry/src/ZdcTopology.cc
  Geometry/HcalCommonData/data/hcalRecNumbering/2021/v2/hcalRecNumbering.xml
  Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/v3/hcalRecNumbering.xml
  Geometry/HcalCommonData/interface/HcalTopologyMode.h
  Geometry/HcalTowerAlgo/src/HcalHardcodeGeometryLoader.cc
  Geometry/Records/interface/ZDCGeometryRecord.h
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  SimCalorimetry/HcalSimProducers/src/HcalDigitizer.cc
  SimCalorimetry/HcalTrigPrimProducers/plugins/HcalTrigPrimDigiProducer.cc
Labels: alca-approved, geometry-approved, hlt-approved, l1-approved, simulation-approved, fully-signed, tests-approved, db-approved, bug-fix, orp-approved, urgent, upgrade-approved, code-checks-approved

#46019 Fix HLTPhoton187L1SeededSequence
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTPhoton187L1SeededSequence_cfi.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#46014 [AlCa] Fix clang static analyzer warnings about dead assignments
  Alignment/CommonAlignment/src/Utilities.cc
  Alignment/MuonAlignment/src/MuonAlignmentInputXML.cc
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#46015 Added Era_Run3_2024 modifier to simOmtfDigis, to use OMTF 2024 config (14_1_X)
  L1Trigger/L1TMuonOverlapPhase1/python/simOmtfDigis_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#46013 Added Era_Run3_2024 modifier to simOmtfDigis, to use OMTF 2024 config (14_0_X)
  L1Trigger/L1TMuonOverlapPhase1/python/simOmtfDigis_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, backport-ok

#45958 [14_1_X] Update to `relval_gpu.py`for Alpaka and Pixel Triplets Alpaka Workflows
  Configuration/PyReleaseValidation/README.md
  Configuration/PyReleaseValidation/python/relval_gpu.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQMHarvesting_cff.py
  DQM/SiPixelHeterogeneous/python/SiPixelHeterogenousDQM_FirstStep_cff.py
  RecoTracker/Configuration/python/customizePixelTracksForTriplets.py
Labels: dqm-approved, reconstruction-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, tracking, trk

#46016 Fix 'Assigned value is garbage or undefined' warning from llvm-analyzer in EcalTBHodoscopeRecInfoAlgo
  RecoTBCalo/EcalTBHodoscopeReconstructor/src/EcalTBHodoscopeRecInfoAlgo.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#46022 Add cfi file for CandPtrSelector
  CommonTools/CandAlgos/python/hltCandPtrSelector_cfi.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, hlt-integration

#46009 [BTV] Disable pT cut for AK4 Puppi ParticleNet and UParT taggers inference
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/FeatureTools/plugins/ParticleNetFeatureEvaluator.cc
  RecoBTag/FeatureTools/plugins/UnifiedParticleTransformerAK4TagInfoProducer.cc
  RecoBTag/ONNXRuntime/python/pfParticleNetFromMiniAODAK4_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#46018 Fix 'Assigned value is garbage or undefined' warning from llvm-analyzer in AlgoMuon
  L1Trigger/L1TMuonOverlap/interface/AlgoMuon.h
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#46036 CICADA L1TTtuples Data Format Update
  L1Trigger/L1TNtuples/plugins/L1CaloSummaryTreeProducer.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#46031 [LLVM analyzer] Assigned value is garbage or undefined in L1GctInternEtSum.cc
  DataFormats/L1GlobalCaloTrigger/src/L1GctInternEtSum.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#46011 Run3-hcx361 Make Era dependent ZDC geometry - backport #45511
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.h
  CondFormats/HcalObjects/interface/HcalCondObjectContainer.h
  CondFormats/HcalObjects/src/HcalCondObjectContainerBase.cc
  CondTools/Geometry/plugins/calowriters.cc
  Configuration/Geometry/python/GeometryRecoDB_cff.py
  Geometry/CaloGeometry/src/CaloGenericDetId.cc
  Geometry/CaloTopology/src/HcalTopology.cc
  Geometry/ForwardGeometry/BuildFile.xml
  Geometry/ForwardGeometry/interface/CaloGeometryDBZdc.h
  Geometry/ForwardGeometry/interface/ZdcGeometry.h
  Geometry/ForwardGeometry/interface/ZdcHardcodeGeometryLoader.h
  Geometry/ForwardGeometry/interface/ZdcTopology.h
  Geometry/ForwardGeometry/plugins/SealModule.cc
  Geometry/ForwardGeometry/plugins/ZdcHardcodeGeometryEP.cc
  Geometry/ForwardGeometry/plugins/ZdcHardcodeGeometryEP.h
  Geometry/ForwardGeometry/plugins/ZdcTopologyEP.cc
  Geometry/ForwardGeometry/plugins/ZdcTopologyEP.h
  Geometry/ForwardGeometry/plugins/moduleDB.cc
  Geometry/ForwardGeometry/python/ZdcGeometry_cfi.py
  Geometry/ForwardGeometry/src/ES_ZdcGeometry.cc
  Geometry/ForwardGeometry/src/ZdcGeometry.cc
  Geometry/ForwardGeometry/src/ZdcHardcodeGeometryLoader.cc
  Geometry/ForwardGeometry/src/ZdcTopology.cc
  Geometry/HcalCommonData/data/hcalRecNumbering/2021/v2/hcalRecNumbering.xml
  Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/v3/hcalRecNumbering.xml
  Geometry/HcalCommonData/interface/HcalTopologyMode.h
  Geometry/HcalTowerAlgo/src/HcalHardcodeGeometryLoader.cc
  Geometry/Records/interface/ZDCGeometryRecord.h
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
  SimCalorimetry/HcalSimProducers/src/HcalDigitizer.cc
  SimCalorimetry/HcalTrigPrimProducers/plugins/HcalTrigPrimDigiProducer.cc
Labels: l1-pending, alca-approved, geometry-approved, hlt-approved, simulation-approved, pending-signatures, tests-approved, db-approved, orp-approved, urgent, upgrade-approved, backport-ok

#46003 Use dedicated GT in pp ref 2024 relval workflow
  Configuration/AlCa/python/autoCond.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: alca-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#46033 Run3-hc362 Define the modified scenarios for 2024 (Affecting ZDC geometry)
  CalibCalorimetry/HcalPlugins/src/HcalHardcodeCalibrations.cc
  CondFormats/HcalObjects/src/HcalCondObjectContainerBase.cc
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024FlatMinus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024FlatMinus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024FlatPlus05Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024FlatPlus10Percent.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2024ZeroMaterial.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024FlatMinus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024FlatMinus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024FlatPlus05PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024FlatPlus10PercentXML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometry2024ZeroMaterialXML_cfi.py
  Geometry/ForwardGeometry/plugins/ZdcTopologyEP.cc
  Geometry/ForwardGeometry/plugins/ZdcTopologyEP.h
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
Labels: alca-approved, geometry-approved, hlt-approved, fully-signed, tests-approved, db-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#46054 Fix ordering of modules in HLT_TriMu_10_5_5_DZ_FromL1TkMuon path.
  HLTrigger/Configuration/python/HLT_75e33/paths/HLT_TriMu_10_5_5_DZ_FromL1TkMuon_cfi.py
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, code-checks-approved

#46045 Removed unused variable in TStorageFactoryFile
  IOPool/TFileAdaptor/src/TStorageFactoryFile.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#46060 [phase2] add missing ESProducers to timing menu for running alpaka tracking
  HLTrigger/Configuration/python/HLT_75e33_timing_cff.py
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, requires-external, code-checks-approved

#46044 Add tests with split level 0 input files to raw data unit tests
  DataFormats/Common/test/TestTriggerResultsFormat.sh
  DataFormats/DetId/README.md
  DataFormats/DetId/test/TestVectorDetId.sh
  DataFormats/FEDRawData/test/TestFEDRawDataCollectionFormat.sh
  DataFormats/HLTReco/test/TestTriggerEventFormat.sh
  DataFormats/L1Scouting/README.md
  DataFormats/L1Scouting/test/TestL1ScoutingFormat.sh
  DataFormats/L1ScoutingRawData/test/TestSDSRawDataCollectionFormat.sh
  DataFormats/L1TGlobal/README.md
  DataFormats/L1TGlobal/test/TestGlobalObjectMapRecordFormat.sh
  DataFormats/Scouting/README.md
  DataFormats/Scouting/test/TestRun2ScoutingFormats.sh
  DataFormats/Scouting/test/TestRun3ScoutingFormats.sh
  DataFormats/Scouting/test/test_readRun3Scouting_cfg.py
  DataFormats/SiStripCluster/README.md
  DataFormats/SiStripCluster/test/TestSiStripApproximateClusterCollection.sh
Labels: core-approved, daq-approved, hlt-approved, l1-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, trk

#46078 Run3-hcx365 Bug fix to HcalTopologyMode to enable understanding new modes backport of #46077
  Geometry/HcalCommonData/src/HcalTopologyMode.cc
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, backport
