Repository cms-sw/cmssw, pull requests merged in 2025-02, with the labels that each got.

#47160 Phase2-gex186C Modify all Run4 scenarios to include the modified RPC geometry
  Configuration/Geometry/python/dictRun4Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D100.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D101.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D102.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D103.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D104.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D105.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D106.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D107.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D108.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D109.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D110.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D111.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D112.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D113.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D114.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D115.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D116.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D95.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D96.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D98.xml
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometryRun4D99.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D100XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D101XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D102XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D103XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D104XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D105XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D106XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D107XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D108XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D109XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D110XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D111XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D112XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D113XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D114XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D115XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D116XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D95XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D96XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D98XML_cfi.py
  Geometry/CMSCommonData/python/cmsExtendedGeometryRun4D99XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47199 Remove unused variable in TestAssociator.cc
  SimTracker/TrackerHitAssociation/test/TestAssociator.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#47232 Dynamic Memory Allocation for LST Objects
  RecoTracker/LSTCore/interface/PixelSegmentsHostCollection.h
  RecoTracker/LSTCore/interface/PixelSegmentsSoA.h
  RecoTracker/LSTCore/interface/SegmentsHostCollection.h
  RecoTracker/LSTCore/interface/SegmentsSoA.h
  RecoTracker/LSTCore/interface/alpaka/PixelSegmentsDeviceCollection.h
  RecoTracker/LSTCore/interface/alpaka/SegmentsDeviceCollection.h
  RecoTracker/LSTCore/src/alpaka/Kernels.h
  RecoTracker/LSTCore/src/alpaka/LST.cc
  RecoTracker/LSTCore/src/alpaka/LSTEvent.dev.cc
  RecoTracker/LSTCore/src/alpaka/LSTEvent.h
  RecoTracker/LSTCore/src/alpaka/MiniDoublet.h
  RecoTracker/LSTCore/src/alpaka/PixelQuintuplet.h
  RecoTracker/LSTCore/src/alpaka/PixelTriplet.h
  RecoTracker/LSTCore/src/alpaka/Quintuplet.h
  RecoTracker/LSTCore/src/alpaka/Segment.h
  RecoTracker/LSTCore/src/alpaka/TrackCandidate.h
  RecoTracker/LSTCore/src/alpaka/Triplet.h
  RecoTracker/LSTCore/standalone/bin/lst.cc
  RecoTracker/LSTCore/standalone/code/core/trkCore.cc
  RecoTracker/LSTCore/standalone/code/core/trkCore.h
  RecoTracker/LSTCore/standalone/code/core/write_lst_ntuple.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#47205 add more limited matrix options, separately for Run1&2, Run3, Phase2 and HeavyIons
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#47216 Migrate Alpaka EDProducers to pass the edm::ParameterSet to base class constructor
  EventFilter/EcalRawToDigi/plugins/alpaka/EcalRawToDigiPortable.cc
  EventFilter/HcalRawToDigi/plugins/alpaka/HcalDigisSoAProducer.cc
  HeterogeneousCore/AlpakaCore/plugins/alpaka/AlpakaBackendProducer.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaGlobalProducerCopyToDeviceCache.cc
  HeterogeneousCore/AlpakaTest/plugins/alpaka/TestAlpakaGlobalProducerMoveToDeviceCache.cc
  RecoLocalCalo/EcalRecProducers/plugins/alpaka/EcalRecHitProducerPortable.cc
  RecoLocalCalo/EcalRecProducers/plugins/alpaka/EcalUncalibRecHitProducerPortable.cc
  RecoLocalCalo/HGCalRecAlgos/plugins/alpaka/HGCalRecHitProducers.cc
  RecoLocalCalo/HGCalRecAlgos/test/alpaka/HGCalRecHitESProducersTest.cc
  RecoLocalCalo/HGCalRecProducers/plugins/alpaka/HGCalSoALayerClustersProducer.cc
  RecoLocalCalo/HGCalRecProducers/plugins/alpaka/HGCalSoARecHitsLayerClustersProducer.cc
  RecoLocalCalo/HGCalRecProducers/plugins/alpaka/HGCalSoARecHitsProducer.cc
  RecoLocalCalo/HcalRecProducers/plugins/alpaka/HBHERecHitProducerPortable.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelPhase2DigiToCluster.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToCluster.cc
  RecoLocalTracker/SiPixelRecHits/plugins/alpaka/SiPixelRecHitAlpaka.cc
  RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducer.cc
  RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CaloRecHitSoAProducer.cc
  RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitSoAProducer.cc
  RecoTracker/LST/plugins/alpaka/LSTProducer.cc
  RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtuplet.cc
  RecoVertex/BeamSpotProducer/plugins/alpaka/BeamSpotDeviceProducer.cc
  RecoVertex/PixelVertexFinding/plugins/alpaka/PixelVertexProducerAlpaka.cc
Labels: alca-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, heterogeneous-approved, tracking, trk

#46198 Synchronize L1T L1TReEmulFromRAW and Repack_Full configurations
  Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47231 Add matrix tests for reMINI + NANOv15
  Configuration/PyReleaseValidation/python/relval_nano.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#47173 Introduce Unified Particle Transformer v2
  PhysicsTools/NanoAOD/python/custom_jme_cff.py
  PhysicsTools/NanoAOD/python/jetsAK4_Puppi_cff.py
  PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py
  PhysicsTools/PatAlgos/python/slimming/applyDeepBtagging_cff.py
  PhysicsTools/PatAlgos/python/tools/jetTools.py
  RecoBTag/Configuration/python/RecoBTag_cff.py
  RecoBTag/FeatureTools/plugins/UnifiedParticleTransformerAK4TagInfoProducer.cc
  RecoBTag/ONNXRuntime/plugins/UnifiedParticleTransformerAK4ONNXJetTagsProducer.cc
  RecoBTag/ONNXRuntime/python/pfUnifiedParticleTransformerAK4V1DiscriminatorsJetTags_cfi.py
  RecoBTag/ONNXRuntime/python/pfUnifiedParticleTransformerAK4V1_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, xpog-approved

#47253 [NANO] Fix PS weight parsing
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#47206 [JME,Nano] Refactor constituents table, add GloParT WvsQCD score
  PhysicsTools/NanoAOD/plugins/SimpleJetConstituentTableProducer.cc
  PhysicsTools/NanoAOD/plugins/SimplePATFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/python/jetConstituents_cff.py
  PhysicsTools/NanoAOD/python/jetsAK8_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/PatAlgos/plugins/PATObjectSelector.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, btv-pog-approved

#47256 Copy also chi2 for HCAL RecHits in HCALRecHitSoAProducer
  RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CaloRecHitSoAProducer.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, heterogeneous-approved

#47241 Fix the number for the last lumisection of the run
  CondCore/CondDB/src/Time.cc
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, code-checks-approved

#46884 Run-dependent pixel simulation using additionally compressed SimHit info
  Configuration/ProcessModifiers/python/runDependentForPixelVal_cff.py
  Configuration/PyReleaseValidation/python/relval_premix.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  SimDataFormats/TrackerDigiSimLink/interface/PixelSimHitExtraInfoLite.h
  SimDataFormats/TrackerDigiSimLink/src/classes.h
  SimDataFormats/TrackerDigiSimLink/src/classes_def.xml
  SimGeneral/MixingModule/python/SiPixelSimParameters_cfi.py
  SimGeneral/MixingModule/python/aliases_cfi.py
  SimGeneral/MixingModule/python/pixelDigitizer_cfi.py
  SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py
  SimTracker/Common/interface/SiPixelChargeReweightingAlgorithm.h
  SimTracker/SiPixelDigitizer/plugins/PreMixingSiPixelWorker.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.h
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc
  SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.h
Labels: operations-approved, simulation-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, trk, changes-dataformats

#47229 Fix NoParentDictionary test
  IOPool/Input/test/testNoParentDictionary.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47265 [GCC14] template-id not allowed for constructor in C++20
  DataFormats/TrackSoA/interface/TracksDevice.h
  DataFormats/TrackSoA/interface/TracksHost.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved, tracking

#47234 Renamed BranchChildren to ProductDependencies
  DataFormats/Provenance/interface/BranchChildren.h
  DataFormats/Provenance/interface/ProductDependencies.h
  DataFormats/Provenance/interface/ProductDependenciesFwd.h
  DataFormats/Provenance/interface/SubProcessParentageHelper.h
  DataFormats/Provenance/src/BranchChildren.cc
  DataFormats/Provenance/src/classes.h
  FWCore/Framework/interface/FileBlock.h
  FWCore/Sources/interface/DaqProvenanceHelper.h
  FWCore/Sources/src/DaqProvenanceHelper.cc
  IOPool/Input/src/RootFile.cc
  IOPool/Input/src/RootFile.h
  IOPool/Output/interface/PoolOutputModule.h
  IOPool/Output/src/PoolOutputModule.cc
  IOPool/Output/src/RootOutputFile.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47203 Update clang-tidy test to make sure it process header file too
  Utilities/ReleaseScripts/test/ref/test-clang-tidy.cc
  Utilities/ReleaseScripts/test/ref/test-clang-tidy.h
  Utilities/ReleaseScripts/test/test-clang-tidy.cc
  Utilities/ReleaseScripts/test/test-clang-tidy.cc.yaml
  Utilities/ReleaseScripts/test/test-clang-tidy.h
  Utilities/ReleaseScripts/test/test-clang-tidy.sh
  Utilities/ReleaseScripts/test/test-scram-code-checks.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47204 L1 P2GT region cut checks and fixing menu config
  L1Trigger/Configuration/python/Phase2GTMenus/SeedDefinitions/step1_2024/l1tGTMenu_hadr_crossLepSeeds_cff.py
  L1Trigger/Configuration/python/Phase2GTMenus/SeedDefinitions/step1_2024_explicitSeeds/l1tGTMenu_hadr_crossLepSeeds_cff.py
  L1Trigger/Configuration/python/Phase2GTMenus/SeedDefinitions/step1_2024_explicitSeeds/l1tGTMenu_lepSeeds_cff.py
  L1Trigger/Phase2L1GT/plugins/L1GTSingleCollectionCut.h
Labels: l1-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, upgrade-approved, code-checks-approved

#47264 move `HGCalHitCalibrationHLT` DQM plots from top folder to inside `HLT` folder
  HLTriggerOffline/Common/python/HLTValidation_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47266 [GCC14] Avoid std::clamp in device code
  RecoLocalTracker/SiPixelRecHits/interface/pixelCPEforDevice.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/clusterTracksByDensity.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking, trk

#47235 Scouting Offline DQM for 2025 data-taking (EGM+MUO+autoDQM)
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Configuration/python/autoDQM.py
  DQMOffline/HLTScouting/BuildFile.xml
  DQMOffline/HLTScouting/python/HLTScoutingDqmOffline_cff.py
  DQMOffline/HLTScouting/python/HLTScoutingPostProcessing_cff.py
  HLTriggerOffline/Scouting/plugins/BuildFile.xml
  HLTriggerOffline/Scouting/plugins/ElectronEfficiencyPlotter.cc
  HLTriggerOffline/Scouting/plugins/ElectronEfficiencyPlotter.h
  HLTriggerOffline/Scouting/plugins/PatElectronTagProbeAnalyzer.cc
  HLTriggerOffline/Scouting/plugins/PatElectronTagProbeAnalyzer.h
  HLTriggerOffline/Scouting/plugins/ScoutingEGammaCollectionMonitoring.cc
  HLTriggerOffline/Scouting/plugins/ScoutingEGammaCollectionMonitoring.h
  HLTriggerOffline/Scouting/plugins/ScoutingElectronTagProbeAnalyzer.cc
  HLTriggerOffline/Scouting/plugins/ScoutingElectronTagProbeAnalyzer.h
  HLTriggerOffline/Scouting/plugins/ScoutingMuonTagProbeAnalyzer.cc
  HLTriggerOffline/Scouting/plugins/ScoutingMuonTagProbeAnalyzer.h
  HLTriggerOffline/Scouting/plugins/ScoutingMuonTriggerAnalyzer.cc
  HLTriggerOffline/Scouting/plugins/ScoutingMuonTriggerAnalyzer.h
  HLTriggerOffline/Scouting/python/ElectronEfficiencyPlotter_cfi.py
  HLTriggerOffline/Scouting/python/HLTScoutingEGammaDqmOffline_cff.py
  HLTriggerOffline/Scouting/python/HLTScoutingEGammaPostProcessing_cff.py
  HLTriggerOffline/Scouting/python/PatElectronTagProbeAnalyzer_cfi.py
  HLTriggerOffline/Scouting/python/ScoutingEGammaCollectionMonitoring_cfi.py
  HLTriggerOffline/Scouting/python/ScoutingElectronTagProbeAnalyzer_cfi.py
  HLTriggerOffline/Scouting/python/ScoutingMuonMonitoring_Client_cff.py
  HLTriggerOffline/Scouting/python/ScoutingMuonTagProbeAnalyzer_cfi.py
  HLTriggerOffline/Scouting/python/ScoutingMuonTriggerAnalyzer_cfi.py
  HLTriggerOffline/Scouting/test/runScoutingMonitoringDQM_EGammaOnly_step1_cfg.py
  HLTriggerOffline/Scouting/test/runScoutingMonitoringDQM_EGammaOnly_step2_cfg.py
  HLTriggerOffline/Scouting/test/runScoutingMonitoringDQM_muonOnly_backup_cfg.py
  HLTriggerOffline/Scouting/test/runScoutingMonitoringDQM_muonOnly_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, allow-elfontan

#47269 [HGCAL] Fix the implementation of scaling test in HGCalRecHitProducers
  RecoLocalCalo/HGCalRecAlgos/plugins/alpaka/HGCalRecHitCalibrationAlgorithms.dev.cc
  RecoLocalCalo/HGCalRecAlgos/plugins/alpaka/HGCalRecHitProducers.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, hgcal-dpg-approved

#47244 [14_2_X] Update beamspot option in ConfigBuilder
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/HLT/python/addOnTestsHLT.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/VtxSmeared.py
Labels: hlt-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#47245 [14_1_X] Update beamspot option in ConfigBuilder
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/HLT/python/addOnTestsHLT.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/VtxSmeared.py
Labels: hlt-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#47246 [14_0_X] Update beamspot option in ConfigBuilder
  Configuration/Applications/python/ConfigBuilder.py
  Configuration/HLT/python/addOnTestsHLT.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/StandardSequences/python/VtxSmeared.py
Labels: hlt-approved, operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#47286 Remove duplication of configuration of `EGammaSuperclusterProducer` in the Phase-2 HLT menu
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTHgcalTiclPFClusteringForEgammaL1SeededSequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/HLTHgcalTiclPFClusteringForEgammaUnseededSequence_cfi.py
  HLTrigger/Configuration/test/BuildFile.xml
  HLTrigger/Configuration/test/check_phase2_hlt_duplicates.sh
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47248 [NGT] Extend edmEventSize to measure leaf sizes
  PerfTools/EdmEvent/bin/edmEventSize.cpp
  PerfTools/EdmEvent/doc/EdmEvent.doc
  PerfTools/EdmEvent/interface/EdmEventSize.h
  PerfTools/EdmEvent/src/EdmEventSize.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, ngt, allow-rsreds

#47255 [NGT] Update FastTimerService to new resource format in circles
  HLTrigger/Timer/plugins/FastTimerService.cc
  HLTrigger/Timer/scripts/mergeResourcesJson.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, ngt

#47289 Add protection for type change when updating branches
  PhysicsTools/NanoAODTools/python/postprocessing/framework/output.py
  PhysicsTools/NanoAODTools/python/postprocessing/framework/preskimming.py
  PhysicsTools/NanoAODTools/python/postprocessing/framework/treeReaderArrayTools.py
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved

#47271 Reduce minYsizeB1 and minYsizeB2 CA cuts for Phase1
  Geometry/CommonTopologies/interface/SimplePixelTopology.h
  RecoTracker/PixelSeeding/plugins/CAHitNtupletGeneratorOnGPU.cc
  RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGenerator.cc
  RecoTracker/PixelSeeding/plugins/alpaka/CAPixelDoubletsAlgos.h
  RecoTracker/PixelSeeding/plugins/gpuPixelDoubletsAlgos.h
Labels: geometry-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#47212 Developing offline JetMET DQM for Scouting jets
  DQMOffline/JetMET/interface/JetAnalyzer.h
  DQMOffline/JetMET/python/jetAnalyzer_cff.py
  DQMOffline/JetMET/python/jetAnalyzer_cfi.py
  DQMOffline/JetMET/python/jetMETDQMOfflineSource_cff.py
  DQMOffline/JetMET/src/JetAnalyzer.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47273 Fixes to the ChiSquared Test in RelMon
  Utilities/RelMon/python/utils.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47281 Remove size scalar from HcalRecHitSoALayout as unused
  DataFormats/HcalRecHit/interface/HcalRecHitSoA.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#47295 Fix event number overflow in ECAL packer
  EventFilter/EcalDigiToRaw/interface/BlockFormatter.h
  EventFilter/EcalDigiToRaw/src/BlockFormatter.cc
  EventFilter/EcalDigiToRaw/src/EcalDigiToRaw.cc
  EventFilter/EcalDigiToRaw/src/SRBlockFormatter.cc
  EventFilter/EcalDigiToRaw/src/TCCBlockFormatter.cc
  EventFilter/EcalDigiToRaw/src/TowerBlockFormatter.cc
Labels: daq-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, ecal

#47284 Fix read rules for CTPPSLocalTrackLite
  DataFormats/CTPPSReco/src/classes_def.xml
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, changes-dataformats

#47290 Fix event number overflow in ES packer
  EventFilter/ESDigiToRaw/interface/ESDataFormatter.h
  EventFilter/ESDigiToRaw/interface/ESDigiToRaw.h
Labels: daq-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, ecal

#47294 Fix event number overflow in ES packer - 150X
  EventFilter/ESDigiToRaw/interface/ESDataFormatter.h
  EventFilter/ESDigiToRaw/interface/ESDigiToRaw.h
Labels: daq-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, ecal

#47291 Fix event number overflow in ES packer - 142X
  EventFilter/ESDigiToRaw/interface/ESDataFormatter.h
  EventFilter/ESDigiToRaw/interface/ESDigiToRaw.h
Labels: daq-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, ecal

#47292 Fix event number overflow in ES packer - 141X
  EventFilter/ESDigiToRaw/interface/ESDataFormatter.h
  EventFilter/ESDigiToRaw/interface/ESDigiToRaw.h
Labels: daq-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, ecal

#47293 Fix event number overflow in ES packer - 140X
  EventFilter/ESDigiToRaw/interface/ESDataFormatter.h
  EventFilter/ESDigiToRaw/interface/ESDigiToRaw.h
Labels: daq-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, ecal

#47305 Fix gcc14 array-bound error
  CondCore/CondDB/src/DbCore.h
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#47296 [15_0_X] Reduce minYsizeB1 and minYsizeB2 CA cuts for Phase1
  Geometry/CommonTopologies/interface/SimplePixelTopology.h
  RecoTracker/PixelSeeding/plugins/CAHitNtupletGeneratorOnGPU.cc
  RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGenerator.cc
  RecoTracker/PixelSeeding/plugins/alpaka/CAPixelDoubletsAlgos.h
  RecoTracker/PixelSeeding/plugins/gpuPixelDoubletsAlgos.h
Labels: geometry-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, tracking

#47261 Geometry/HGCalCommonData: fix array bounds error
  Geometry/HGCalCommonData/src/HGCalCellOffset.cc
Labels: geometry-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#47069 [NGT] Implement `NanoAOD` ntuples production for HLT Muon objects
  Configuration/EventContent/python/EventContent_cff.py
  Configuration/PyReleaseValidation/README.md
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  DPGAnalysis/MuonTools/plugins/MuLocalRecoFlatTableProducers.cc
  DPGAnalysis/MuonTools/python/muNtupleProducerHlt_cff.py
  DPGAnalysis/MuonTools/python/nano_mu_hlt_cff.py
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/plugins/SimpleL1TFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/python/autoNANO.py
Labels: operations-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved, xpog-approved, ngt

#47276 HGCAL: ECON D CRC (trailer) computation in the Unpacker
  DataFormats/HGCalDigi/interface/HGCalECONDPacketInfoSoA.h
  DataFormats/HGCalDigi/interface/HGCalRawDataDefinitions.h
  EventFilter/HGCalRawToDigi/BuildFile.xml
  EventFilter/HGCalRawToDigi/interface/HGCalUnpacker.h
  EventFilter/HGCalRawToDigi/interface/UnpackerTools.h
  EventFilter/HGCalRawToDigi/src/HGCalUnpacker.cc
  EventFilter/HGCalRawToDigi/src/UnpackerTools.cc
Labels: reconstruction-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, hgcal-dpg-approved

#47280 Move `ResourceInformation` abstract base class to FWCore/AbstractServices, and few additional improvements
  FWCore/AbstractServices/BuildFile.xml
  FWCore/AbstractServices/interface/ResourceInformation.h
  FWCore/AbstractServices/src/ResourceInformation.cc
  FWCore/Framework/BuildFile.xml
  FWCore/Framework/src/ScheduleItems.cc
  FWCore/Services/BuildFile.xml
  FWCore/Services/plugins/CPU.cc
  FWCore/Services/plugins/CondorStatusUpdater.cc
  FWCore/Services/plugins/ResourceInformationService.cc
  FWCore/Services/test/test_resourceInformationService.sh
  FWCore/Utilities/src/ResourceInformation.cc
  HeterogeneousCore/CUDAServices/plugins/BuildFile.xml
  HeterogeneousCore/CUDAServices/plugins/CUDAService.cc
  HeterogeneousCore/CUDAServices/test/BuildFile.xml
  HeterogeneousCore/CUDAServices/test/testCUDAService.cpp
  HeterogeneousCore/ROCmServices/plugins/BuildFile.xml
  HeterogeneousCore/ROCmServices/plugins/ROCmService.cc
  HeterogeneousCore/ROCmServices/test/BuildFile.xml
  HeterogeneousCore/ROCmServices/test/testROCmService.cpp
  PhysicsTools/PyTorch/test/BuildFile.xml
  PhysicsTools/PyTorch/test/testBaseCUDA.h
  PhysicsTools/TensorFlow/BuildFile.xml
  PhysicsTools/TensorFlow/src/TensorFlow.cc
  PhysicsTools/TensorFlow/test/BuildFile.xml
  PhysicsTools/TensorFlow/test/testBaseCUDA.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved, ml-approved

#47311 [15_0_X] Remove size scalar from HcalRecHitSoALayout as unused
  DataFormats/HcalRecHit/interface/HcalRecHitSoA.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, heterogeneous-approved

#47268 Use `std::span` instead of `edm::Span`
  DataFormats/L1Scouting/interface/OrbitCollection.h
  DataFormats/NanoAOD/interface/FlatTable.h
  FWCore/Utilities/interface/Span.h
  HeterogeneousCore/SonicTriton/README.md
  HeterogeneousCore/SonicTriton/interface/TritonData.h
  HeterogeneousCore/SonicTriton/interface/triton_utils.h
  HeterogeneousCore/SonicTriton/src/TritonData.cc
  HeterogeneousCore/SonicTriton/src/triton_utils.cc
  L1TriggerScouting/OnlineProcessing/plugins/FinalBxSelector.cc
  L1TriggerScouting/OnlineProcessing/plugins/JetBxSelector.cc
  L1TriggerScouting/OnlineProcessing/plugins/MaskOrbitBx.cc
  L1TriggerScouting/OnlineProcessing/plugins/MuBxSelector.cc
  L1TriggerScouting/OnlineProcessing/plugins/MuTagJetBxSelector.cc
Labels: core-approved, daq-approved, l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, heterogeneous-approved

#47308 Added template argument to VPSet
  FWCore/ParameterSet/python/Mixins.py
  FWCore/ParameterSet/python/Types.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47285 Run3-gex187Z Add the XML files for RPC which provide the right z-positions for the endcap chmbers
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/MuonCommonData/data/rpcf/2015/v3/rpcf.xml
  Geometry/MuonCommonData/data/rpcf/2021/v5/rpcf.xml
  Geometry/MuonCommonData/data/rpcf/2023/v3/rpcf.xml
  Geometry/MuonCommonData/data/rpcf/2024/v4/rpcf.xml
  Geometry/MuonCommonData/data/rpcf/2025/v2/rpcf.xml
  Geometry/MuonCommonData/data/rpcf/2030/v5/rpcf.xml
  Geometry/MuonCommonData/python/cmsExtendedGeometryRun4D110XML_cfi.py
  Geometry/MuonCommonData/python/testExtendedGeometry2018XML_cfi.py
  Geometry/MuonCommonData/python/testExtendedGeometry2021XML_cfi.py
  Geometry/MuonCommonData/python/testExtendedGeometry2023XML_cfi.py
  Geometry/MuonCommonData/python/testExtendedGeometry2024XML_cfi.py
  Geometry/MuonCommonData/python/testExtendedGeometry2025XML_cfi.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47313 Fix compilation of EdmEventSize on clang
  PerfTools/EdmEvent/interface/EdmEventSize.h
  PerfTools/EdmEvent/src/EdmEventSize.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47252 HLT Gen Validation
  DQMOffline/Trigger/interface/FunctionDefs.h
  DQMOffline/Trigger/interface/VarRangeCutColl.h
  DQMOffline/Trigger/src/FunctionDefs.cc
  Validation/HLTrigger/BuildFile.xml
  Validation/HLTrigger/interface/HLTGenResHistColl.h
  Validation/HLTrigger/interface/HLTGenValHist.h
  Validation/HLTrigger/interface/HLTGenValObject.h
  Validation/HLTrigger/interface/HLTGenValObjectMgr.h
  Validation/HLTrigger/plugins/HLTGenResSource.cc
  Validation/HLTrigger/plugins/HLTGenValSource.cc
  Validation/HLTrigger/python/hltvalcust.py
  Validation/HLTrigger/src/HLTGenResHistColl.cc
  Validation/HLTrigger/src/HLTGenValHistCollFilter.cc
  Validation/HLTrigger/src/HLTGenValObjectMgr.cc
  Validation/HLTrigger/src/HLTGenValPathSpecificSettingParser.cc
  Validation/HLTrigger/test/doPhaseIIValidation.py
  Validation/HLTrigger/test/runPhaseIIValSource_cfg.py
  Validation/HLTrigger/test/runValClient_cfg.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47314 Run3-gex187A Add overlap check for 2016
  Configuration/Geometry/python/GeometryDD4hepExtended2016Reco_cff.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2016.xml
  Geometry/CMSCommonData/data/materials/2016/v1/materials.xml
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckDD4hep_cfg.py
  SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckDDD_cfg.py
Labels: geometry-approved, simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47254 Remove mkFit based workflow 12834.7 from short matrix
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, requires-external, code-checks-approved, tracking

#47247 Run3-gex187Y Update some of the scripts for 2021 and 2023 to make the payloads
  CondTools/Geometry/test/writehelpers/createExtended2021DD4hepPayloads.sh
  CondTools/Geometry/test/writehelpers/createExtended2023DD4hepPayloads.sh
  CondTools/Geometry/test/writehelpers/geometryExtended2021DD4hep_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2021DD4hep_xmlwriter.py
  CondTools/Geometry/test/writehelpers/geometryExtended2023DD4hep_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2023DD4hep_xmlwriter.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#47325 Fix `SiPixelClusterizer` alpaka code when `GPU_DEBUG` is defined
  FWCore/Utilities/interface/DeviceGlobal.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/PixelClustering.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.dev.cc
Labels: core-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#47297 Can specify TBranch aliases in PoolOutputModule
  IOPool/Output/interface/PoolOutputModule.h
  IOPool/Output/src/PoolOutputModule.cc
  IOPool/Output/src/RootOutputFile.cc
  IOPool/Output/test/BuildFile.xml
  IOPool/Output/test/PoolOutputAliasTest.sh
  IOPool/Output/test/PoolOutputAliasTestCheckResults.py
  IOPool/Output/test/PoolOutputAliasTest_cfg.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47321 Fix Wunused-result warnings in TRGScalers2DB.cc
  RecoLuminosity/LumiProducer/plugins/TRGScalers2DB.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47300 Implement a compile-time warp size constant
  HeterogeneousCore/AlpakaInterface/interface/warpsize.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/ClusterChargeCut.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/PixelClustering.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.dev.cc
  RecoVertex/PixelVertexFinding/plugins/alpaka/clusterTracksByDensity.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/sortByPt2.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, heterogeneous-approved, tracking, trk

#47327 add a test workflow for testing the new `@hltScouting` DQM sequence in `ScoutingPFMonitor` dataset
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#47332 Remove EMMT physics list, make EMH an alias for EMM + G4HepEm
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysicsEMH.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysicsEMMT.h
  SimG4Core/PhysicsLists/interface/CMSEmStandardPhysicsTrackingManager.h
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMH.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMH.h
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMMT.cc
  SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMMT.h
  SimG4Core/PhysicsLists/plugins/module.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsEMH.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsEMMT.cc
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysicsTrackingManager.cc
  SimG4Core/PhysicsLists/src/TrackingManagerHelper.h
  SimG4Core/PhysicsLists/src/TrackingManagerHelper.icc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47340 MtdValidation : Add monitoring of unassociated tracks
  Validation/MtdValidation/plugins/Primary4DVertexValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47346 add dictionary for `std::pair<short,int>`
  DataFormats/StdDictionaries/src/classes_def_pair.xml
  DataFormats/StdDictionaries/src/classes_def_vector.xml
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, changes-dataformats

#47354 Added VPSetTemplate to configuration
  FWCore/ParameterSet/python/Types.py
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47301 Implement a compile-time warp size constant [15.0]
  HeterogeneousCore/AlpakaInterface/interface/warpsize.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/ClusterChargeCut.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/PixelClustering.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.dev.cc
  RecoVertex/PixelVertexFinding/plugins/alpaka/clusterTracksByDensity.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/sortByPt2.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, heterogeneous-approved, tracking, trk

#47326 Fix `SiPixelClusterizer` alpaka code when `GPU_DEBUG` is defined [15.0.x]
  FWCore/Utilities/interface/DeviceGlobal.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/PixelClustering.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.dev.cc
Labels: core-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok, trk

#47349 [15.0.X] add a test workflow for testing the new `@hltScouting` DQM sequence in `ScoutingPFMonitor` dataset
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, backport-ok

#47347 add dictionary for `std::pair<short,int>` [`15_0_X`]
  DataFormats/StdDictionaries/src/classes_def_pair.xml
  DataFormats/StdDictionaries/src/classes_def_vector.xml
Labels: core-approved, fully-signed, tests-approved, orp-approved, backport-ok, changes-dataformats

#47299 Embedding update for run3
  TauAnalysis/MCEmbeddingTools/python/SelectingProcedure_cff.py
  TauAnalysis/MCEmbeddingTools/python/customisers.py
  TauAnalysis/MCEmbeddingTools/test/BuildFile.xml
  TauAnalysis/MCEmbeddingTools/test/run_2022_workflow_tests.sh
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47320 Fix improper use of std::unique and std::remove
  DQM/HLTEvF/plugins/TrigObjTnPHistColl.cc
  DQMOffline/RecoB/src/BTagDifferentialPlot.cc
  DQMOffline/RecoB/src/EtaPtBin.cc
  PhysicsTools/PatAlgos/plugins/PATElectronProducer.cc
  PhysicsTools/PatAlgos/plugins/PATPhotonProducer.cc
  RecoEcal/EgammaClusterProducers/src/InterestingDetIdCollectionProducer.cc
  RecoEcal/EgammaClusterProducers/src/InterestingDetIdFromSuperClusterProducer.cc
  RecoEcal/EgammaClusterProducers/src/ReducedRecHitCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaIsoESDetIdCollectionProducer.cc
  RecoEgamma/EgammaIsolationAlgos/plugins/EgammaIsoHcalDetIdCollectionProducer.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc
Labels: dqm-approved, hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, xpog-approved, tracking, trk

#47344 Updated HLT BTV validation paths from DeepCSV to PNet
  HLTriggerOffline/Btag/python/HltBtagPostValidation_cff.py
  HLTriggerOffline/Btag/python/HltBtagValidation_cff.py
  HLTriggerOffline/Btag/test/test.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, btv

#47351 MTD reconstruction and validation: update TkFilterParameters in MTD use with Phase2 settings
  RecoMTD/TimingIDTools/python/mvaTrainingNtuple_cff.py
  RecoMTD/TimingIDTools/test/mvaTrainingSaveNtuple_cfg.py
  Validation/Configuration/python/mtdSimValid_cff.py
  Validation/MtdValidation/python/vertices4DValid_cff.py
  Validation/MtdValidation/test/mtdValidation_cfg.py
Labels: dqm-approved, reconstruction-approved, simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved, mtd

#47356 Fix warning about implicitly-declared copy constructor
  DataFormats/METReco/interface/PhiWedge.h
  DataFormats/METReco/src/PhiWedge.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#47359 fix `throwOnMissing` logic in `ObjectSelectorBase`
  CommonTools/UtilAlgos/interface/ObjectSelectorBase.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#47365 Run3-gex187B Correct the payload creation scripts for the years 2024 and 2025
  CondTools/Geometry/test/writehelpers/createExtended2024DD4hepPayloads.sh
  CondTools/Geometry/test/writehelpers/createExtended2025DD4hepPayloads.sh
  CondTools/Geometry/test/writehelpers/createExtended2025Payloads.sh
  CondTools/Geometry/test/writehelpers/geometryExtended2025_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2025_xmlwriter.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#47375 Run3-gex187E Update several geometry scripts for misc. Extended scenarios
  Configuration/Geometry/python/GeometryExtended2015CastorMeasured_cff.py
  Configuration/Geometry/python/GeometryExtended2015CastorSystMinus_cff.py
  Configuration/Geometry/python/GeometryExtended2015CastorSystPlus_cff.py
  Configuration/Geometry/python/GeometryExtended2015FlatMinus05Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2015FlatMinus10Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2015FlatPlus05Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2015FlatPlus10Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2015MuonGEMDev_cff.py
  Configuration/Geometry/python/GeometryExtended2015ZeroMaterial_cff.py
  Configuration/Geometry/python/GeometryExtended2015_cff.py
  Configuration/Geometry/python/GeometryExtended2015dev_cff.py
  Configuration/Geometry/python/GeometryExtended2016_CTPPS_cff.py
  Configuration/Geometry/python/GeometryExtended2017DDD_cff.py
  Configuration/Geometry/python/GeometryExtended2017Plan0_cff.py
  Configuration/Geometry/python/GeometryExtended2017_CTPPS_cff.py
  Configuration/Geometry/python/GeometryExtended2018DDD_cff.py
  Configuration/Geometry/python/GeometryExtended2018DetailedCavern_cff.py
  Configuration/Geometry/python/GeometryExtended2018NoSD_cff.py
  Configuration/Geometry/python/GeometryExtended2018Plan0_cff.py_cff.py
  Configuration/Geometry/python/GeometryExtended2018Plan36_cff.py
  Configuration/Geometry/python/GeometryExtended2018_CTPPS_cff.py
  Configuration/Geometry/python/GeometryExtended2019_cff.py
  Configuration/Geometry/python/GeometryExtendedCastorMeasured2015dev_cff.py
  Configuration/Geometry/python/GeometryExtendedCastorSystMinus2015dev_cff.py
  Configuration/Geometry/python/GeometryExtendedCastorSystPlus2015dev_cff.py
  Configuration/Geometry/python/GeometryExtendedGFlash_cff.py
  Configuration/Geometry/python/GeometryExtendedHFLibraryNoCastor_cff.py
  Configuration/Geometry/python/GeometryExtendedTest2014_cff.py
  Configuration/Geometry/python/GeometryExtendedZeroMaterial_cff.py
  Configuration/Geometry/python/GeometryExtended_cff.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47371 Run3-gex187D Update some of the geometry cff's of Run2 period
  Configuration/Geometry/python/GeometryExtended2016_cff.py
  Configuration/Geometry/python/GeometryExtended2016dev_cff.py
  Configuration/Geometry/python/GeometryExtended2017Plan1FlatMinus05Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2017Plan1FlatMinus10Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2017Plan1FlatPlus05Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2017Plan1FlatPlus10Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2017Plan1ZeroMaterial_cff.py
  Configuration/Geometry/python/GeometryExtended2017Plan1_cff.py
  Configuration/Geometry/python/GeometryExtended2017_cff.py
  Configuration/Geometry/python/GeometryExtended2018FlatMinus05Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2018FlatMinus10Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2018FlatPlus05Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2018FlatPlus10Percent_cff.py
  Configuration/Geometry/python/GeometryExtended2018ZeroMaterial_cff.py
  Configuration/Geometry/python/GeometryExtended2018_cff.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47366 Run3-gex187C Update the scripts for the years 2021, 2023, 2024, 2026 which are used to prepare the payloads from DDD versions
  CondTools/Geometry/test/writehelpers/createExtended2021Payloads.sh
  CondTools/Geometry/test/writehelpers/createExtended2023Payloads.sh
  CondTools/Geometry/test/writehelpers/createExtended2024Payloads.sh
  CondTools/Geometry/test/writehelpers/createExtended2026Payloads.sh
  CondTools/Geometry/test/writehelpers/geometryExtended2021_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2021_xmlwriter.py
  CondTools/Geometry/test/writehelpers/geometryExtended2023_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2023_xmlwriter.py
  CondTools/Geometry/test/writehelpers/geometryExtended2024_writer.py
  CondTools/Geometry/test/writehelpers/geometryExtended2024_xmlwriter.py
  CondTools/Geometry/test/writehelpers/geometryExtended2026_writer.py
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#47374 Have fillDescriptions generate a template for VPSet in cfi files
  FWCore/Integration/test/unit_test_outputs/testProducerWithPsetDesc_cfi.py
  FWCore/ParameterSet/interface/ParameterSetDescription.h
  FWCore/ParameterSet/python/Config.py
  FWCore/ParameterSet/python/Mixins.py
  FWCore/ParameterSet/python/Types.py
  FWCore/ParameterSet/src/ParameterDescription.cc
  FWCore/ParameterSet/test/test_catch_ParameterSetDescription.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47380 Run3-gex187F Update the remaining scriptts in Configuration/Geometry for Calorimeter and Muon systems
  Configuration/Geometry/python/GeometryIdeal2015_cff.py
  Configuration/Geometry/python/GeometryIdeal2015dev_cff.py
  Configuration/Geometry/python/GeometryIdealAPD1_cff.py
  Configuration/Geometry/python/GeometryIdealNoAPD_cff.py
  Configuration/Geometry/python/GeometryIdeal_cff.py
  Configuration/Geometry/python/GeometryNoCastor_cff.py
  Configuration/Geometry/python/GeometrySLHCReco_cff.py
  Configuration/Geometry/python/GeometrySLHCSimIdeal_cff.py
  Configuration/Geometry/python/GeometrySimAll_cff.py
  Configuration/Geometry/python/GeometrySimIdealGFlash_cff.py
  Configuration/Geometry/python/GeometrySimIdeal_cff.py
  Configuration/Geometry/python/GeometrySimTracker_cff.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47352 add IT and OT cluster, rechit and tracking rechits validation at HLT for Phase-2
  HLTriggerOffline/Common/python/HLTValidation_cff.py
  Validation/SiTrackerPhase2V/python/HLTPhase2TrackerValidationFirstStep_cff.py
  Validation/SiTrackerPhase2V/python/Phase2ITValidateRecHit_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#47335 add a filter sequence if it is present in the fragment
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#47336 Backport: Developing offline JetMET DQM for Scouting jets
  DQMOffline/JetMET/interface/JetAnalyzer.h
  DQMOffline/JetMET/python/jetAnalyzer_cff.py
  DQMOffline/JetMET/python/jetAnalyzer_cfi.py
  DQMOffline/JetMET/python/jetMETDQMOfflineSource_cff.py
  DQMOffline/JetMET/src/JetAnalyzer.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#47282 [Phase-2 L1]: update readme for P2GT menu configs
  L1Trigger/Configuration/python/Phase2GTMenus/README.md
  L1Trigger/Phase2L1GT/README.md
  L1Trigger/Phase2L1GT/test/test_GT.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47330 [GCC14] Fix compilation errors
  JetMETCorrections/Modules/src/JetResolution.cc
  L1Trigger/GlobalCaloTrigger/src/L1GlobalCaloTrigger.cc
  RecoVertex/PixelVertexFinding/plugins/alpaka/clusterTracksDBSCAN.h
  RecoVertex/PixelVertexFinding/plugins/alpaka/clusterTracksIterative.h
Labels: l1-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#47370 Adding `SimpleTrackValidation` Analyzer
  Validation/RecoTrack/plugins/SimpleTrackValidation.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#47379 Remove unused L1T paths from the past from HLT Upgrade Menu.
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL1DoubleNNTau52_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL1TkDoubleMuFiltered7_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL1TkSingleMuFiltered15_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltL1TkSingleMuFiltered22_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1t1PFPuppiJet70offMaxEta2p4_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1t2PFPuppiJet55offMaxEta2p4_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1t4PFPuppiJet25OnlineMaxEta2p4_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1t4PFPuppiJet40offMaxEta2p4_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1tDoublePFPuppiJet112offMaxEta2p4_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1tDoublePFPuppiJets112offMaxDeta1p6_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1tPFPuppiHT400offMaxEta2p4_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1tPFPuppiHT450off_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1tPFPuppiMET220off_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/l1tSinglePFPuppiJet230off_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_DoubleNNTau52_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_DoublePFPuppiJets112_2p4_DEta1p6_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_DoubleTkMuon_15_7_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_PFHT400PT30_QuadPFPuppiJet_70_55_40_40_2p4_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_PFPuppiHT450off_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_PFPuppiMET220off_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_SingleNNTau150_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_SinglePFPuppiJet230off_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_SingleTkMuon_22_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_TkEle25TkEle12_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_TkEle36_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_TkEm37TkEm24_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_TkEm51_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_TkIsoEle22TkEm12_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_TkIsoEle28_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_TkIsoEm22TkIsoEm12_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_TkIsoEm36_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/paths/L1T_TripleTkMuon_5_3_3_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/L1TTkEle25TkEle12Sequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/L1TTkEle36Sequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/L1TTkEm37TkEm24Sequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/L1TTkEm51Sequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/L1TTkIsoEle22TkEm12Sequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/L1TTkIsoEle28Sequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/L1TTkIsoEm22TkIsoEm12Sequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/sequences/L1TTkIsoEm36Sequence_cfi.py
  HLTrigger/Configuration/python/HLT_75e33_cff.py
  HLTrigger/Configuration/python/HLT_75e33_timing_cff.py
Labels: hlt-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47382 Fixing `RelMon` Pages Stylesheets Locations
  Utilities/RelMon/python/directories2html.py
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#47283 Restriction of reemul fg0 in ieta16
  SimCalorimetry/HcalTrigPrimAlgos/src/HcalFinegrainBit.cc
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47341 ZS added to L1TCaloLayer1
  L1Trigger/L1TCaloLayer1/src/L1TCaloLayer1FetchLUTs.cc
  L1Trigger/L1TCalorimeter/interface/CaloParamsHelper.h
  L1Trigger/L1TCalorimeter/plugins/L1TCaloParamsESProducer.cc
  L1Trigger/L1TCalorimeter/plugins/L1TCaloStage2ParamsESProducer.cc
  L1Trigger/L1TCalorimeter/python/caloParams_2025_v0_1_cfi.py
Labels: l1-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47345 [15.0.X] Updated HLT BTV validation paths from DeepCSV to PNet
  HLTriggerOffline/Btag/python/HltBtagPostValidation_cff.py
  HLTriggerOffline/Btag/python/HltBtagValidation_cff.py
  HLTriggerOffline/Btag/test/test.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, btv

#47360 [15.0.X] fix `throwOnMissing` logic in `ObjectSelectorBase`
  CommonTools/UtilAlgos/interface/ObjectSelectorBase.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#47364 Fix warning about implicitly-declared copy constructor [15.0.x]
  DataFormats/METReco/interface/PhiWedge.h
  DataFormats/METReco/src/PhiWedge.cc
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#47393 fix `customizeHLTfor47047` to work also on menus already customized
  HLTrigger/Configuration/python/customizeHLTforCMSSW.py
Labels: hlt-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#47396 Modernize code of TagProbeFitter
  PhysicsTools/TagAndProbe/src/TagProbeFitter.cc
Labels: analysis-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47398 protect `Phase2IT{OT}ValidateCluster` against missing input collections
  Validation/SiTrackerPhase2V/plugins/Phase2ITValidateCluster.cc
  Validation/SiTrackerPhase2V/plugins/Phase2OTValidateCluster.cc
Labels: dqm-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved, trk

#45475 Outer Tracker Phase2 DQM: additional stub validation plots
  DQM/SiTrackerPhase2/test/README.md
  DQM/SiTrackerPhase2/test/dqmstep_phase2tk_cfg.py
  DQM/SiTrackerPhase2/test/harvestingstep_phase2tk_cfg.py
  Validation/SiTrackerPhase2V/plugins/Phase2OTHarvestReconstruction.cc
  Validation/SiTrackerPhase2V/plugins/Phase2OTHarvestTrackingParticles.cc
  Validation/SiTrackerPhase2V/plugins/Phase2OTValidateReconstruction.cc
  Validation/SiTrackerPhase2V/plugins/Phase2OTValidateTTStub.cc
  Validation/SiTrackerPhase2V/python/Phase2TrackerMCHarvesting_cff.py
  Validation/SiTrackerPhase2V/python/Phase2ValidateL1TTObjects_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#47334 add a filter sequence if it is present in the fragment [15.0.X]
  Configuration/Applications/python/ConfigBuilder.py
Labels: operations-approved, fully-signed, tests-approved, orp-approved

#47361 [14.2.X] fix `throwOnMissing` logic in `ObjectSelectorBase`
  CommonTools/UtilAlgos/interface/ObjectSelectorBase.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#47362 [14.1.X] fix `throwOnMissing` logic in `ObjectSelectorBase`
  CommonTools/UtilAlgos/interface/ObjectSelectorBase.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#47363 [14.0.X] fix `throwOnMissing` logic in `ObjectSelectorBase`
  CommonTools/UtilAlgos/interface/ObjectSelectorBase.h
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#47257 [GEM] Turning on the applyMasking flag for Run 3 GEM data taking
  Configuration/Eras/python/Era_Run3_2025_cff.py
  Configuration/Eras/python/Modifier_run3_GEM_2025_cff.py
  RecoLocalMuon/GEMRecHit/python/gemRecHits_cfi.py
Labels: alca-approved, operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47328 Developing offline JetMET DQM for Scouting jets - complementary to PR #47212
  DQMOffline/HLTScouting/python/HLTScoutingDqmOffline_cff.py
  DQMOffline/JetMET/python/jetMETDQMOfflineSource_cff.py
  DQMOffline/JetMET/src/JetAnalyzer.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47408 Fix TestRunnerDataFormatsFWLite unit test
  DataFormats/FWLite/test/chainevent_looping_cint.C
  DataFormats/FWLite/test/event_looping_cint.C
  DataFormats/FWLite/test/event_looping_consumes_cint.C
  DataFormats/FWLite/test/runlumi_looping_cint.C
  DataFormats/FWLite/test/triggernames_cint.C
  DataFormats/FWLite/test/triggernames_multi_cint.C
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47392 Added and_then function to Service class
  FWCore/ServiceRegistry/interface/Service.h
  IOMC/RandomEngine/plugins/RandomEngineStateProducer.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47407 Change fastjet RangeDefinition to Selector to fix warnings
  RecoJets/JetProducers/interface/BackgroundEstimator.h
  RecoJets/JetProducers/interface/PileUpSubtractor.h
  RecoJets/JetProducers/plugins/VirtualJetProducer.cc
  RecoJets/JetProducers/src/BackgroundEstimator.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47405 Follow up on using cms::alpakatools deltaPhi functions
  RecoTracker/LSTCore/src/alpaka/Hit.h
  RecoTracker/LSTCore/src/alpaka/Kernels.h
  RecoTracker/LSTCore/src/alpaka/NeuralNetwork.h
  RecoTracker/LSTCore/src/alpaka/TrackCandidate.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved, tracking

#47419 Fix `HcalUpgradeDataFrame` dummy type
  DataFormats/HcalDigi/src/classes.h
Labels: simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, code-checks-approved

#47383 Enable mkFit initialStep for track building in phase-2 era, and introduce noMkFit phase-2 era(s)
  Configuration/Eras/python/Era_Phase2C10_dd4hep_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C10_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C11I13M9_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C11I13T25M9_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C11I13T26M9_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C11I13_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C11M9_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C11_dd4hep_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C11_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C12_dd4hep_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C12_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C17I13M9_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C20I13M9_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C22I13M9_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C9_dd4hep_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2C9_noMkFit_cff.py
  Configuration/Eras/python/Era_Phase2_cff.py
  Configuration/Eras/python/Era_Phase2_noMkFit_cff.py
  Configuration/Eras/python/ModifierChain_trackingMkFitProd_cff.py
  Configuration/StandardSequences/python/Eras.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved, tracking

#47424 Backport to produce 2024 and 2025 Tau Embedding samples
  TauAnalysis/MCEmbeddingTools/python/SelectingProcedure_cff.py
  TauAnalysis/MCEmbeddingTools/python/customisers.py
  TauAnalysis/MCEmbeddingTools/test/BuildFile.xml
  TauAnalysis/MCEmbeddingTools/test/run_2022_workflow_tests.sh
Labels: simulation-approved, fully-signed, tests-approved, orp-approved

#47198 Add searchInCommands to runTheMatrix, interactive.
  Configuration/PyReleaseValidation/scripts/runTheMatrix.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#47426 Fix needed for boost 1.87.0
  EventFilter/HGCalRawToDigi/src/UnpackerTools.cc
  EventFilter/Utilities/interface/EvFDaqDirector.h
  EventFilter/Utilities/src/EvFDaqDirector.cc
  IOPool/TFileAdaptor/test/tfileTest.cpp
Labels: core-approved, daq-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47399 Fix FEVDEBUGHLT event content to include all Tracksters.
  RecoHGCal/Configuration/python/RecoHGCal_EventContent_cff.py
Labels: reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, upgrade-approved, code-checks-approved

#47418 move unit test for `onlinebeammonitor_dqm_sourceclient-live` to use streamer files
  DQM/Integration/python/clients/onlinebeammonitor_dqm_sourceclient-live_cfg.py
  DQM/Integration/test/BuildFile.xml
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#47277 Update cmsRunGP executable to link with gperftools libprofiler.so after toolfile change
  FWCore/Framework/bin/BuildFile.xml
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47420 Fix `HcalUpgradeDataFrame` dummy type [15.0.x]
  DataFormats/HcalDigi/src/classes.h
Labels: simulation-approved, fully-signed, tests-approved, bug-fix, orp-approved, backport-ok

#47430 `DQMStreamerReader`: re-throw all exceptions when run in unit test mode
  DQMServices/StreamerIO/plugins/DQMStreamerReader.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#47435 Included cstdint for uint64_t; fixes gcc14 header check
  SimCalorimetry/HGCalSimAlgos/interface/HGCalECONDEmulatorInfo.h
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#47436 Remove false positve in `scram b check-headers`
  DataFormats/Provenance/interface/BranchChildren.h
  DataFormats/Provenance/interface/BranchDescription.h
Labels: core-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#47386 [CMSSW_15_0_X] Update a few GTs in autoCond
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#47411 [GCC14]Fix type conversion not using user defined operator warning
  CondFormats/Serialization/interface/eos/portable_iarchive.hpp
Labels: core-approved, fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved

#47425 Implement additional framework integration tests
  DataFormats/TestObjects/interface/ThingWithDoNotSort.h
  DataFormats/TestObjects/interface/ThingWithPostInsert.h
  DataFormats/TestObjects/src/classes.h
  DataFormats/TestObjects/src/classes_def.xml
  FWCore/Integration/plugins/BuildFile.xml
  FWCore/Integration/plugins/PostInsertProducer.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/testPostInsertProducer_cfg.py
  FWCore/Integration/test/testStdProducts_cfg.py
  FWCore/TestModules/README.md
  FWCore/TestModules/plugins/GlobalFloatAnalyzer.cc
  FWCore/TestModules/plugins/GlobalFloatProducer.cc
  FWCore/TestModules/plugins/GlobalIntAnalyzer.cc
  FWCore/TestModules/plugins/GlobalIntProducer.cc
  FWCore/TestModules/plugins/GlobalStringAnalyzer.cc
  FWCore/TestModules/plugins/GlobalStringProducer.cc
  FWCore/TestModules/plugins/GlobalVectorAnalyzer.cc
  FWCore/TestModules/plugins/GlobalVectorProducer.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved, changes-dataformats

#47401 introduce `@phase2FakeHLT` and `@phase2ValidationFakeHLT` DQM / Validation sequences
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  Configuration/StandardSequences/python/Validation_cff.py
  DQMOffline/Configuration/python/autoDQM.py
  Validation/Configuration/python/autoValidation.py
Labels: dqm-approved, operations-approved, simulation-approved, fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#47432 XrdAdaptor: Do not add empty exclude strings
  Utilities/XrdAdaptor/src/XrdRequestManager.cc
  Utilities/XrdAdaptor/src/XrdSource.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47437 Monitor intermediate LST track collections at HLT
  Configuration/EventContent/python/EventContent_cff.py
  DQMOffline/Trigger/python/TrackingMonitoring_cff.py
  Validation/RecoTrack/python/HLTmultiTrackValidator_cff.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#47449 [15_0_X] Combined backport of #47430 and #47418
  DQM/Integration/python/clients/onlinebeammonitor_dqm_sourceclient-live_cfg.py
  DQM/Integration/test/BuildFile.xml
  DQMServices/StreamerIO/plugins/DQMStreamerReader.cc
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, requires-external, backport-ok

#47442 Modernise the interface of `ObjectWithDict`
  FWCore/Reflection/interface/ObjectWithDict.h
  FWCore/Reflection/src/ObjectWithDict.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#47355 Use HardwareResourcesDescription in ProcessConfiguration
  DQM/SiStripMonitorHardware/src/SiStripSpyEventMatcher.cc
  DQMServices/FwkIO/plugins/DQMRootOutputModule.cc
  DQMServices/FwkIO/plugins/format.h
  DataFormats/Provenance/interface/HardwareResourcesDescription.h
  DataFormats/Provenance/interface/ModuleDescription.h
  DataFormats/Provenance/interface/ProcessConfiguration.h
  DataFormats/Provenance/src/HardwareResourcesDescription.cc
  DataFormats/Provenance/src/ModuleDescription.cc
  DataFormats/Provenance/src/ProcessConfiguration.cc
  DataFormats/Provenance/src/ProcessHistory.cc
  DataFormats/Provenance/test/HardwareResourcesDescription_t.cpp
  FWCore/AbstractServices/BuildFile.xml
  FWCore/AbstractServices/interface/ResourceInformation.h
  FWCore/Framework/src/ScheduleItems.cc
  FWCore/Framework/test/Event_t.cpp
  FWCore/Framework/test/checkForModuleDependencyCorrectness_t.cppunit.cc
  FWCore/Framework/test/edproducer_productregistry_callback.cc
  FWCore/Framework/test/event_getrefbeforeput_t.cppunit.cc
  FWCore/Framework/test/eventprincipal_t.cppunit.cc
  FWCore/Framework/test/generichandle_t.cppunit.cc
  FWCore/Framework/test/makeDummyProcessConfiguration.h
  FWCore/Framework/test/maker2_t.cppunit.cc
  FWCore/Integration/plugins/DelayedReaderThrowingSource.cc
  FWCore/Integration/plugins/PutOrMergeTestSource.cc
  FWCore/Integration/test/ProcessConfiguration_t.cpp
  FWCore/Integration/test/ProcessHistory_t.cpp
  FWCore/Services/plugins/ResourceInformationService.cc
  FWCore/Sources/src/DaqProvenanceHelper.cc
  FWCore/TestProcessor/src/TestProcessor.cc
  GeneratorInterface/LHEInterface/plugins/BuildFile.xml
  GeneratorInterface/LHEInterface/plugins/LHEProvenanceHelper.cc
  IOPool/Common/bin/EdmProvDump.cc
  IOPool/Common/test/removeChangingParts.py
  IOPool/Common/test/unit_test_outputs/provdump.log
  IOPool/Input/src/ProvenanceAdaptor.cc
  IOPool/Input/test/BuildFile.xml
  IOPool/Input/test/testReducedProcessHistoryCreate_cfg.py
  IOPool/Input/test/testReducedProcessHistoryHardwareResources.sh
  IOPool/Input/test/testReducedProcessHistoryVersion.sh
  IOPool/SecondaryInput/test/SecondaryProducer.cc
  IOPool/Streamer/test/BuildFile.xml
  IOPool/Streamer/test/run_TestReducedProcessHistoryHardwareResources.sh
  IOPool/Streamer/test/run_TestReducedProcessHistoryVersion.sh
  IOPool/Streamer/test/testReducedProcessHistoryCreate_cfg.py
  Mixing/Base/src/PileUp.cc
Labels: core-approved, dqm-approved, generators-approved, simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, trk

#47438 Implement additional framework integration tests [15.0.x]
  DataFormats/TestObjects/interface/ThingWithDoNotSort.h
  DataFormats/TestObjects/interface/ThingWithPostInsert.h
  DataFormats/TestObjects/src/classes.h
  DataFormats/TestObjects/src/classes_def.xml
  FWCore/Integration/plugins/BuildFile.xml
  FWCore/Integration/plugins/PostInsertProducer.cc
  FWCore/Integration/test/BuildFile.xml
  FWCore/Integration/test/testPostInsertProducer_cfg.py
  FWCore/Integration/test/testStdProducts_cfg.py
  FWCore/TestModules/README.md
  FWCore/TestModules/plugins/GlobalFloatAnalyzer.cc
  FWCore/TestModules/plugins/GlobalFloatProducer.cc
  FWCore/TestModules/plugins/GlobalIntAnalyzer.cc
  FWCore/TestModules/plugins/GlobalIntProducer.cc
  FWCore/TestModules/plugins/GlobalStringAnalyzer.cc
  FWCore/TestModules/plugins/GlobalStringProducer.cc
  FWCore/TestModules/plugins/GlobalVectorAnalyzer.cc
  FWCore/TestModules/plugins/GlobalVectorProducer.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, urgent, changes-dataformats

#47455 fix gcc 14 warnings: use atomic_ref instead of casting
  HeterogeneousCore/CUDAUtilities/interface/OneToManyAssoc.h
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, heterogeneous-approved

#47444 Implement `edm::ProductNamePattern`
  DataFormats/Provenance/BuildFile.xml
  DataFormats/Provenance/interface/ProductNamePattern.h
  DataFormats/Provenance/src/ProductNamePattern.cc
  DataFormats/Provenance/test/BuildFile.xml
  DataFormats/Provenance/test/ProductNamePattern_t.cpp
  FWCore/Modules/src/GenericConsumer.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#47456 fix logical error when level>dim-1
  JetMETCorrections/InterpolationTables/interface/ArrayND.h
Labels: analysis-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47453 Run3-gex187H Modify some of the overlap scripts to test overlaps in the new muon scenarios
  Geometry/MuonCommonData/test/python/g4OverlapCheck2021_cfg.py
  Geometry/MuonCommonData/test/python/g4OverlapCheckMuon_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47394 Do not fail unit test due to undefined behavior
  PhysicsTools/MVAComputer/test/testBitSet.cppunit.cc
Labels: fully-signed, tests-approved, orp-approved, code-checks-approved, ml-approved

#47448 [GEM][backport] turning on the applyMasking for 2025 Run 3 GEM data taking [15.0.x]
  Configuration/Eras/python/Era_Run3_2025_cff.py
  Configuration/Eras/python/Modifier_run3_GEM_2025_cff.py
  RecoLocalMuon/GEMRecHit/python/gemRecHits_cfi.py
Labels: operations-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved

#47445 Implement `edm::ProductNamePattern` [15.0.x]
  DataFormats/Provenance/BuildFile.xml
  DataFormats/Provenance/interface/ProductNamePattern.h
  DataFormats/Provenance/src/ProductNamePattern.cc
  DataFormats/Provenance/test/BuildFile.xml
  DataFormats/Provenance/test/ProductNamePattern_t.cpp
  FWCore/Modules/src/GenericConsumer.cc
  FWCore/Reflection/interface/ObjectWithDict.h
  FWCore/Reflection/src/ObjectWithDict.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, urgent, backport-ok

#47443 Modernise the interface of `ObjectWithDict` [15.0.x]
  FWCore/Reflection/interface/ObjectWithDict.h
  FWCore/Reflection/src/ObjectWithDict.cc
Labels: core-approved, fully-signed, tests-approved, orp-pending, urgent, backport-ok

#47464 [FULLSIM] Updated configuration of G4HepEm physics
  SimG4Core/PhysicsLists/src/CMSEmStandardPhysics.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47439 Update 2023 and 2024 HI MC GTs in autoCond
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47440 DuplicateTrackMerger: fix relvals 29634.703,29834.703 failing in DBG_X IBs
  RecoTracker/FinalTrackSelectors/plugins/DuplicateTrackMerger.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, tracking

#47473 Revert "Add HardwareResourcesInformation printout to edmProvDump"
  IOPool/Common/bin/EdmProvDump.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47477 Add optional HardwareResourcesInformation printout to edmProvDump
  IOPool/Common/bin/EdmProvDump.cc
  IOPool/Input/test/testReducedProcessHistoryHardwareResources.sh
  IOPool/Streamer/test/run_TestReducedProcessHistoryHardwareResources.sh
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#47387 [CMSSW_14_2_X] Update a few GTs in autoCond
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok

#47463 [15_0_X] Update 2023 and 2024 HI MC GTs in autoCond
  Configuration/AlCa/python/autoCond.py
Labels: alca-approved, fully-signed, tests-approved, orp-approved, backport-ok
