Repository cms-sw/cmssw, pull requests merged in 2025-10, with the labels that each got.

#48876 [15_0_X] Fix documentation for SoftActivityJetNjets parameters
  PhysicsTools/NanoAOD/python/softActivity_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#49026 [15_0_X] Properly Clamping the Clusters in Module with maxNumClustersPerModules
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/ClusterChargeCut.h
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, heterogeneous-approved, trk

#49027 [15.1.X] add HLT vertexing resolution monitoring (by split vertex method)
  DQM/TrackingMonitor/src/PrimaryVertexResolution.cc
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Trigger/python/PrimaryVertexMonitoring_Client_cff.py
  DQMOffline/Trigger/python/PrimaryVertexMonitoring_cff.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, backport-ok, tracking

#48915 [13_3_X] Fixed pz transform for SUEP constituent
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#48920 [10_6_X] Fixed pz transform for SUEP constituent
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#48913 [14_1_X] Fixed pz transform for SUEP constituent
  GeneratorInterface/Pythia8Interface/src/SuepShower.cc
Labels: generators-approved, fully-signed, tests-approved, orp-approved, backport-ok

#49041 Run3-gex191 Update the ZDC geometry and the material in the transport region
  Configuration/Geometry/README.md
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2025.xml
  Geometry/CMSCommonData/data/extend/v4/cmsextent.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2025XML_cfi.py
  Geometry/ForwardCommonData/data/zdc/2025/v2/zdc.xml
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, urgent, upgrade-approved, code-checks-approved

#49044 handle multiple input tags in mixing for SimVertex and SimTrack
  SimGeneral/MixingModule/plugins/MixingModule.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#49023 Filter LayerClusters for TICL Recovery PR by AlgoID and Size
  HLTrigger/Configuration/python/HLT_75e33/modules/hltFilteredLayerClustersRecoveryL1Seeded_cfi.py
  HLTrigger/Configuration/python/HLT_75e33/modules/hltFilteredLayerClustersRecovery_cfi.py
  RecoHGCal/TICL/python/PRbyRecovery_cff.py
Labels: hlt-approved, reconstruction-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, allow-waredjeb

#49012 HCAL: Move HF fine-grain thresholds to conditions
  CalibCalorimetry/HcalTPGAlgos/interface/HcaluLUTTPGCoder.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  CalibCalorimetry/HcalTPGEventSetup/src/HcalTPGCoderULUT.cc
  SimCalorimetry/HcalTrigPrimProducers/python/hcaltpdigi_cff.py
  SimCalorimetry/HcalTrigPrimProducers/python/hcaltpdigi_cfi.py
Labels: alca-approved, l1-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#48907 New Validation/RecoEgamma PF differential Isolation Electrons plots V1
  Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc
  Validation/RecoEgamma/plugins/ElectronMcSignalValidator.h
  Validation/RecoEgamma/python/ElectronMcSignalValidatorPt1000_gedGsfElectrons_cfi.py
  Validation/RecoEgamma/python/ElectronMcSignalValidator_gedGsfElectrons_cfi.py
  Validation/RecoEgamma/test/ElectronMcSignalHistos.txt
  Validation/RecoEgamma/test/ElectronMcSignalHistosPt1000.txt
  Validation/RecoEgamma/test/ElectronMcSignalValidation_gedGsfElectrons_cfg.py
  Validation/RecoEgamma/test/electronValidationCheck_Env.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#48999 align HepMC3 plugin with HepMC2 plugin and add test configs
  GeneratorInterface/Pythia8Interface/plugins/Pythia8HepMC3Hadronizer.cc
  GeneratorInterface/Pythia8Interface/test/JetPlotsExample.py
  GeneratorInterface/Pythia8Interface/test/pythia8hmc3G4Jets_cfg.py
Labels: generators-approved, fully-signed, tests-approved, orp-approved, requires-external, code-checks-approved

#49036 [15_1_X] Modification of existing rawprime version of SiStripApproxCluster
  DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection_v1.h
  DataFormats/SiStripCluster/interface/SiStripApproximateCluster_v1.h
  DataFormats/SiStripCluster/interface/SiStripCluster.h
  DataFormats/SiStripCluster/src/SiStripApproximateClusterCollection_v1.cc
  DataFormats/SiStripCluster/src/SiStripApproximateCluster_v1.cc
  DataFormats/SiStripCluster/src/SiStripCluster.cc
  DataFormats/SiStripCluster/src/classes.h
  DataFormats/SiStripCluster/src/classes_def.xml
  RecoLocalTracker/SiStripClusterizer/plugins/SiStripApprox2Clusters.cc
  RecoLocalTracker/SiStripClusterizer/plugins/SiStripClusters2ApproxClusters_v1.cc
Labels: reconstruction-approved, fully-signed, tests-approved, orp-approved, backport-ok, trk, changes-dataformats

#48422 Modifications for Pythia 8.315
  Configuration/Generator/python/Pythia8CommonSettings_cfi.py
  Configuration/Generator/python/UpsMM_8TeV_TuneCUETP8M1_cfi.py
  Configuration/Generator/python/bJpsiX_8TeV_TuneCUETP8M1_cfi.py
  GeneratorInterface/EvtGenInterface/plugins/test/Py8_lambadb_evtgen1_Lb2plnuLCSR_cfg.py
  GeneratorInterface/EvtGenInterface/test/Py8_bplus_evtgen1_cfg.py
  GeneratorInterface/EvtGenInterface/test/external_Py8_bplus_evtgen1_cfg.py
  GeneratorInterface/PhotosInterface/test/DY_7TeV_pythia8_rivet.py
  GeneratorInterface/Pythia8Interface/test/FXFXewk_test.py
  GeneratorInterface/Pythia8Interface/test/ZToTauTau_photos_13TeV_rivet_cfg.py
  GeneratorInterface/Pythia8Interface/test/test_Pythia8ConcurrentGeneratorFilter_WZ_TuneCP5_13TeV-pythia8.sh
Labels: generators-approved, fully-signed, tests-pending, orp-approved, code-checks-approved

#48745 Met Validation for Phase-2 HLT
  HLTriggerOffline/JetMET/python/Validation/HLTJetMETPostVal_cff.py
  HLTriggerOffline/JetMET/python/Validation/HLTJetMETValidation_cff.py
  HLTriggerOffline/JetMET/python/Validation/JetMETPostProcessor_cff.py
  HLTriggerOffline/JetMET/run/plot_validation.C
  HLTriggerOffline/JetMET/src/HLTJetMETValidation.cc
  HLTriggerOffline/JetMET/src/JetMETDQMPostProcessor.cc
  Validation/RecoJets/plugins/JetTester.cc
  Validation/RecoJets/python/hltJetPostProcessor_cff.py
  Validation/RecoJets/scripts/makeHLTJetValidationPlots.py
  Validation/RecoMET/plugins/METTester.cc
  Validation/RecoMET/plugins/METTester.h
  Validation/RecoMET/plugins/METTesterPostProcessor.cc
  Validation/RecoMET/plugins/METTesterPostProcessor.h
  Validation/RecoMET/plugins/METTesterPostProcessorHarvesting.cc
  Validation/RecoMET/plugins/METTesterPostProcessorHarvesting.h
  Validation/RecoMET/python/METValidation_cfi.py
  Validation/RecoMET/python/hltMETPostProcessor_cff.py
  Validation/RecoMET/python/hltMETValidation_cff.py
  Validation/RecoMET/scripts/makeHLTMETValidationPlots.py
Labels: dqm-approved, fully-signed, tests-approved, orp-approved, code-checks-approved, ngt, allow-bfonta

#49031 [15.1.X] HCAL: Move HF fine-grain thresholds to conditions
  CalibCalorimetry/HcalTPGAlgos/interface/HcaluLUTTPGCoder.h
  CalibCalorimetry/HcalTPGAlgos/src/HcaluLUTTPGCoder.cc
  CalibCalorimetry/HcalTPGEventSetup/src/HcalTPGCoderULUT.cc
  SimCalorimetry/HcalTrigPrimProducers/python/hcaltpdigi_cff.py
  SimCalorimetry/HcalTrigPrimProducers/python/hcaltpdigi_cfi.py
Labels: alca-approved, l1-approved, fully-signed, tests-approved, orp-approved

#49052 [15_1_X] Reading Certification JSON from `cvmfs` in `das-up-to-nevents.py`
  Configuration/PyReleaseValidation/scripts/das-up-to-nevents.py
Labels: pending-signatures, tests-approved, pdmv-approved, orp-approved, upgrade-pending, backport-ok

#49043 Run3-gex191X Update the ZDC geometry and the material in the transport region - backport the PR #49041
  Configuration/Geometry/README.md
  Configuration/Geometry/python/dict2021Geometry.py
  Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2025.xml
  Geometry/CMSCommonData/data/extend/v4/cmsextent.xml
  Geometry/CMSCommonData/python/cmsExtendedGeometry2025XML_cfi.py
  Geometry/ForwardCommonData/data/zdc/2025/v2/zdc.xml
Labels: geometry-approved, pending-signatures, tests-approved, orp-approved, urgent, upgrade-approved, ppd-pending

#49050 Fixes for Digi Morphing: Limiting Histogram Size and Decoupling for `TrackerTraits` [15_1_X]
  Geometry/CommonTopologies/interface/SimplePixelTopology.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/PixelClustering.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToCluster.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.dev.cc
Labels: geometry-approved, reconstruction-approved, fully-signed, tests-approved, bug-fix, orp-approved, urgent, backport-ok, trk

#49065 Enabling SiPixel digi morphing from 2025 onward
  Configuration/Eras/python/Era_Run3_2025_cff.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, urgent, code-checks-approved

#49067 [15_0_X] Enabling SiPixel digi morphing from 2025 onward
  Configuration/Eras/python/Era_Run3_2025_cff.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, urgent, backport, ppd-approved

#48832 [15_0_X] Digi Morphing for HLT
  Geometry/CommonTopologies/interface/SimplePixelTopology.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/PixelClustering.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelMorphingConfig.h
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToCluster.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.dev.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.h
Labels: geometry-pending, reconstruction-approved, pending-signatures, tests-approved, orp-approved, urgent, backport-ok, heterogeneous-approved, trk

#49066 [15_1_X] Enabling SiPixel digi morphing from 2025 onward
  Configuration/Eras/python/Era_Run3_2025_cff.py
  DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py
  DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
Labels: dqm-approved, operations-approved, fully-signed, tests-approved, orp-approved, backport-ok

#49060 Update for BPHNano
  PhysicsTools/BPHNano/plugins/DiTrackBuilder.cc
  PhysicsTools/BPHNano/python/muons_cff.py
  PhysicsTools/NanoAOD/python/custom_bph_cff.py
Labels: fully-signed, tests-approved, orp-approved, urgent, code-checks-approved, xpog-approved

#49061 BPHNano: backport #49060 to CMSSW_15_1_X
  PhysicsTools/BPHNano/plugins/DiTrackBuilder.cc
  PhysicsTools/BPHNano/python/muons_cff.py
  PhysicsTools/NanoAOD/python/custom_bph_cff.py
Labels: fully-signed, tests-approved, orp-approved, xpog-approved

#49062 BPHNano: backport #49060 to CMSSW_15_0_X
  PhysicsTools/BPHNano/plugins/DiTrackBuilder.cc
  PhysicsTools/BPHNano/python/muons_cff.py
  PhysicsTools/NanoAOD/python/custom_bph_cff.py
Labels: fully-signed, tests-approved, orp-approved, backport-ok, xpog-approved

#49076 Fixing EcalPedestal plots for CondDB
  CondCore/EcalPlugins/plugins/EcalPedestals_PayloadInspector.cc
Labels: fully-signed, tests-approved, db-approved, bug-fix, orp-approved, code-checks-approved, ngt

#49045 Minor improvements to das-up-to-nevents.py
  Configuration/PyReleaseValidation/scripts/das-up-to-nevents.py
Labels: fully-signed, tests-approved, pdmv-approved, orp-approved, upgrade-approved, code-checks-approved

#49075 Phase2-hgx364F Add a test code to ivestigate the shrtcoming of V19
  Geometry/HGCalGeometry/data/missingIDsV19.txt
  Geometry/HGCalGeometry/test/HGCalMissingID.cc
  Geometry/HGCalGeometry/test/python/testHGCalMissingID_cfg.py
Labels: geometry-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved

#49070 Use the right TTreeCache in `RootTree::getEntryForAllBranches()` for prompt reading
  IOPool/Input/src/RootTree.cc
Labels: core-approved, fully-signed, tests-approved, orp-approved, code-checks-approved

#49054 Remove MultiClusterAssociators.
  SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreImpl.cc
  SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreImpl.h
  SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreProducer.cc
Labels: simulation-approved, fully-signed, tests-approved, orp-approved, upgrade-approved, code-checks-approved, ngt

#49049 Allow defining valid range of Energy values for LHCInfoPerFill O2O
  CondTools/RunInfo/interface/LHCInfoPerFillPopConSourceHandler.h
  CondTools/RunInfo/interface/LHCInfoPerLSPopConSourceHandler.h
  CondTools/RunInfo/interface/TestLHCInfoPerFillPopConSourceHandler.h
  CondTools/RunInfo/python/LHCInfoPerFillPopConAnalyzer_cfg.py
  CondTools/RunInfo/python/LHCInfoPerLSPopConAnalyzer_cfg.py
  CondTools/RunInfo/src/LHCInfoPerFillPopConSourceHandler.cc
  CondTools/RunInfo/src/LHCInfoPerLSPopConSourceHandler.cc
  CondTools/RunInfo/src/TestLHCInfoPerFillPopConSourceHandler.cc
  CondTools/RunInfo/test/BuildFile.xml
  CondTools/RunInfo/test/test_catch2_LHCInfoPerFillPopCon.cpp
  CondTools/RunInfo/test/test_lhcInfoNewPopCon.sh
Labels: fully-signed, tests-approved, db-approved, orp-approved, code-checks-approved
